### ISSUE TITLE
Help  ---- pg_stat_tmp": No such file or directory ---- node Start Failed

### ISSUE THREAD

**Issue by berezinalex** [zalando/patroni#1005]
Ubuntu 18.04
Postgresql-11

+-------------+--------+---------------------+--------+--------------+----+-----------+
|   Cluster   | Member |         Host            |  Role  |    State         | TL | Lag in MB |
+-------------+--------+---------------------+--------+--------------+----+-----------+
| 11-P        |  beta       | 192.168.0.1:5442 | Leader |   running    |  4 |         0        |
| 11-P        | gamma   | 192.168.0.2:5442 |             | start failed |     |   unknown |

when testing fault tolerance
just turns off the computer as a leader, the replica becomes the leader. The computer turns on and the recovery of the node that was the leader cannot start.

/var/log/postgresql/cluster.log

2019-03-19 00: 35: 02.017 UTC [12094] HINT: If this happens all the time, it is possible that you should select an earlier point for some data to restore.
2019-03-19 00: 35: 02.017 UTC [12095] postgres @ postgres IMPORTANT: the database system starts up
2019-03-19 00: 35: 02.025 UTC [12097] postgres @ postgres IMPORTANT: the database system starts up
2019-03-19 00: 35: 02.073 UTC [12094] COMMUNICATION: switch to backup server mode
2019-03-19 00: 35: 02.078 UTC [12094] IMPORTANT: Could not open directory "/var/run/postgresql/11-ku.pg_stat_tmp": there is no such file or directory
2019-03-19 00: 35: 02.079 UTC [12091] MESSAGE: Starting process (PID 12094) completed with exit code 1
2019-03-19 00: 35: 02.079 UTC [12091] MESSAGE: Startup interruption due to errors in the starting process
2019-03-19 00: 35: 02.087 UTC [12091] MESSAGE: the database system is turned off
2019-03-19 00: 35: 03.262 UTC [12108] MESSAGE: the DB system was interrupted during the recovery process, time in logs: 2019-03-18 13:31:35 UTC
2019-03-19 00: 35: 03.262 UTC [12108] TIP: If this happens all the time, it is possible that some data for recovery should be chosen from an earlier point.

Patroni Config.yml

scope: "11-P"
namespace: "/postgresql-common/"
name: gamma

etcd:
  host: 192.168.0.10 :2379

restapi:
  listen: 192.168.0.2:8008
  connect_address: 192.168.0.2:8008

bootstrap:
  method: pg_createcluster
  pg_createcluster:
    command: /usr/share/patroni/pg_createcluster_patroni
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
   postgresql:
      use_pg_rewind: true
      remove_data_directory_on_rewind_failure: true
      remove_data_directory_on_diverged_timelines: true
     parameters:
        max_connections: 2048
        shared_buffers: 512MB
        effective_cache_size: 1536MB
        maintenance_work_mem: 128MB
        checkpoint_completion_target: 0.7
        wal_buffers: 16MB
        default_statistics_target: 100
        random_page_cost: 4
        effective_io_concurrency: 2
        work_mem: 256kB
        min_wal_size: 1GB
        max_wal_size: 2GB
        max_worker_processes: 2
        max_parallel_workers_per_gather: 1
        max_parallel_workers: 2
        wal_level: replica
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 10
        max_replication_slots: 10
        wal_log_hints: "on"

      pg_hba:
      - local   all             all                                     peer
      - host    all             all             127.0.0.1/32            md5
      - host    all             all             ::1/128                 md5
     - local   replication     all                                     peer
      - host    replication     all             127.0.0.1/32            md5
      - host    replication     all             ::1/128                 md5
     - host replication replicator 192.168.0.1/32 md5
      - host replication replicator 192.168.0.2/32 md5
      - host all all 192.168.0.2/32 md5
      - host all all 192.168.0.1/32 md5
      - host all all 192.168.0.10/32 md5

postgresql:
  create_replica_method:
    - pg_clonecluster
  pg_clonecluster:
    command: /usr/share/patroni/pg_clonecluster_patroni

  listen: "192.168.0.2,127.0.0.1:5442"
  connect_address: 192.168.0.2:5442
  use_unix_socket: true
  data_dir: /var/lib/postgresql/11/ku
  bin_dir: /usr/lib/postgresql/11/bin
  config_dir: /etc/postgresql/11/ku
  pgpass: /var/lib/postgresql/11-P.pgpass
  authentication:
    replication:
      username: replicator
      password: replicator
   superuser:
      username: user
      password: password
  parameters:
    unix_socket_directories: '/var/run/postgresql/'
    logging_collector: 'on'
    log_directory: '/var/log/postgresql'
    log_filename: 'postgresql-11-P.log'

#you have to do re-initialization to restore the gamma node which is not entirely correct.
#Please tell me where is my mistake
#(I think that the problem is that after a failure, the replica cannot start synchronization with the leader, #but why she does not understand this)

so a little bit, but why I do not understand
node1 - beta -- leader
node2 - gamma -- start failded

to see log
"2019-03-19 00: 35: 02.078 UTC [12094] IMPORTANT: Could not open directory "/var/run/postgresql/11-ku.pg_stat_tmp": there is no such file or directory"

Node1 --Leader
root@beta:/var/run/postgresql# ls -la
total 8
drwxrwsr-x 5 postgres postgres 160 мар 19 05:21 .
drwxr-xr-x 26 root root 860 мар 18 12:55 ..
drwxr-s--- 2 postgres postgres 100 мар 19 05:26 11-ku.pg_stat_tmp
-rw-r--r-- 1 postgres postgres 6 мар 19 05:02 11-ku.pid
drwxrwsrwx 2 postgres postgres 40 мар 18 13:24 11-main.pg_stat_tmp
drwxr-s--- 2 root postgres 100 мар 19 05:21 paladin@172.74.130.157
srwxrwxrwx 1 postgres postgres 0 мар 19 05:02 .s.PGSQL.5442
-rw------- 1 postgres postgres 74 мар 19 05:02 .s.PGSQL.5442.lock

Node2 --Start Failed
root@gamma:/var/run/postgresql# ls -la

total 8
drwxrwsr-x 3 postgres postgres 120 мар 19 05:24 .
drwxr-xr-x 26 root root 860 мар 19 05:22 ..

I forcibly copied from node 1 leader to node 2 "launch error" directory /var/run/postgresql/11-
ku.pg_stat_tmp
with the same rights to the directory and files in it
and after that
+-------------+--------+---------------------+--------+---------+----+-----------+
| Cluster | Member | Host | Role | State | TL | Lag in MB |
+-------------+--------+---------------------+--------+---------+----+-----------+
| 11-ku | beta | 192.168.0.1:5442 | Leader | running | 5 | 0 |
| 11-ku | gamma | 192.168.0.2:5442 | | running | 5 | 0 |
+-------------+--------+---------------------+--------+---------+----+-----------+

What is wrong in the configuration and why is the replica not restored on its own?

**Comment by berezinalex** [comment]
so a little bit, but why I do not understand
node1 - beta      -- leader
node2 - gamma -- start failded

to see log 
"2019-03-19 00: 35: 02.078 UTC [12094] IMPORTANT: Could not open directory "/var/run/postgresql/11-ExoTanks.pg_stat_tmp": there is no such file or directory"

# Node1 --Leader

root@beta:/var/run/postgresql# ls -la
total 8
drwxrwsr-x  5 postgres postgres 160 мар 19 05:21 .
drwxr-xr-x 26 root     root     860 мар 18 12:55 ..
drwxr-s---  2 postgres postgres 100 мар 19 05:26 11-ExoTanks.pg_stat_tmp
-rw-r--r--  1 postgres postgres   6 мар 19 05:02 11-ExoTanks.pid
drwxrwsrwx  2 postgres postgres  40 мар 18 13:24 11-main.pg_stat_tmp
drwxr-s---  2 root     postgres 100 мар 19 05:21 paladin@172.74.130.157
srwxrwxrwx  1 postgres postgres   0 мар 19 05:02 .s.PGSQL.5442
-rw-------  1 postgres postgres  74 мар 19 05:02 .s.PGSQL.5442.lock


# Node2 --Start Failed

root@gamma:/var/run/postgresql# ls -la

total 8
drwxrwsr-x  3 postgres postgres 120 мар 19 05:24 .
drwxr-xr-x 26 root     root     860 мар 19 05:22 ..



# I forcibly copied from node 1 leader to node 2 "launch error" directory /var/run/postgresql/11-
# ExoTanks.pg_stat_tmp
# with the same rights to the directory and files in it
# and after that


+-------------+--------+---------------------+--------+---------+----+-----------+
|   Cluster   | Member |         Host        |  Role  |  State  | TL | Lag in MB |
+-------------+--------+---------------------+--------+---------+----+-----------+
| 11-ExoTanks |  beta  | 172.74.130.156:5442 | Leader | running |  5 |         0 |
| 11-ExoTanks | gamma  | 172.74.130.157:5442 |        | running |  5 |         0 |
+-------------+--------+---------------------+--------+---------+----+-----------+


What is wrong in the configuration and why is the replica not restored on its own?

**Comment by CyberDem0n** [comment]
``` 
2019-03-19 00: 35: 02.078 UTC [12094] IMPORTANT: Could not open directory "/var/run/postgresql/11-ExoTanks.pg_stat_tmp": there is no such file or directory
```
How did you installed Patroni?
The config seems to be generated by debian scripts.

On debian/ubuntu `stats_temp_directory` parameter is set to `/var/run/postgresql/%v-%c.pg_stat_tmp'` which is located on tmpfs and therefore needs to be recreated after the restart.
There are more details in the https://github.com/zalando/patroni/issues/863

I think maintainers of debian packages could help here, cc @mbanck @ChristophBerg

**Comment by ChristophBerg** [comment]
Nod. It's a pity that PostgreSQL doesn't attempt to create the directory by itself on startup...
