### ISSUE TITLE
Is there a way in patroni to set a tag on a postgres server "never to become a master"?

### ISSUE THREAD

**Issue by skooter777** [zalando/patroni#1006]
Is there a way in patroni to set a tag on a postgres server "never to become a master"?
It is necessary that one remote node of the server of the base does not take part in the master's elections at all. Is there such a possibility in the current functionality? I would be very grateful for the answer))

**Comment by kostiantyn-nemchenko** [comment]
You are looking for [nofailover](https://github.com/zalando/patroni/blob/680444ae13154aca6f03556cdd1280e296b549ca/postgres0.yml#L96) tag.

**Comment by skooter777** [comment]
Thx!!

**Comment by dabster2** [comment]
Good!!!
