### ISSUE TITLE
ERROR: Failed to get list of machines ... PermissionError(13, 'Permission denied')

### ISSUE THREAD

**Issue by drgarciafuentes** [zalando/patroni#1009]
Hello,

We are having issues with patroni accessing our etcd cluster to bootstrap the first PostgreSQL node after successful verification that SSL/TLS is working via etcdctl.
Our environment:
 - Five nodes cluster of ETCd (v3.2.17) on Ubuntu 18.04
 - Four PostgreSQL bare metals with PG 11 + Patroni (v1.5.5) on Ubuntu 18.04
 - ETCd has authentication enabled and a user 'root' with password.

We have read the patroni v1.5.5 documentation back and forth looking for something we might have missed, but haven't got any further. Similar issues described here and other internet resources do not address this particular problem. Disabling etcd authentication does not make any difference, the error is still present.
At the time of our test we just wanted to confirm that patroni can initialize the first node, then we will clean etcd, create a specific etcd role for the deployment, and substitute the root user/pass values in the config file.

**Here is the header of our config.yml including the details for etcd:**

> scope: "11-main"
namespace: "/postgresql-common/"
name: testhost-0
etcd:
   hosts: 192.168.45.245:2379,192.168.45.246:2379,192.168.45.247:2379,192.168.45.248:2379,192.168.45.249:2379
   protocol: https
   username: root
   password: myverysercurepassword
   cacert: /etc/ssl/etcd/ca.pem
   cert: /etc/ssl/etcd/testhost-0.pem
   key: /etc/ssl/etcd/testhost-0-key.pem

**And here is a fragment of the syslog output when we attempt to initialize patroni via systemd start patroni:**

> Mar 21 18:44:25 testhost-01 patroni[5820]: 2019-03-21 18:44:25,434 ERROR: Failed to get list of machines from https://192.168.45.249:2379/v2: MaxRetryError("HTTPSConnectionPool(host='192.168.45.249', port=2379): Max retries exceeded with url: /v2/machines (Caused by ProtocolError('Connection aborted.', PermissionError(13, 'Permission denied')))",)
Mar 21 18:44:25 testhost-01 patroni[5820]: 2019-03-21 18:44:25,434 INFO: Retrying on https://192.168.45.245:2379
Mar 21 18:44:25 testhost-01 patroni[5820]: 2019-03-21 18:44:25,436 ERROR: Failed to get list of machines from https://192.168.45.245:2379/v2: MaxRetryError("HTTPSConnectionPool(host='192.168.45.245', port=2379): Max retries exceeded with url: /v2/machines (Caused by ProtocolError('Connection aborted.', PermissionError(13, 'Permission denied')))",)
Mar 21 18:44:25 testhost-01 patroni[5820]: 2019-03-21 18:44:25,436 INFO: Retrying on https://192.168.45.246:2379
Mar 21 18:44:25 testhost-01 patroni[5820]: 2019-03-21 18:44:25,870 ERROR: Failed to get list of machines from https://192.168.45.246:2379/v2: MaxRetryError("HTTPSConnectionPool(host='192.168.45.246', port=2379): Max retries exceeded with url: /v2/machines (Caused by ProtocolError('Connection aborted.', PermissionError(13, 'Permission denied')))",)
Mar 21 18:44:25 testhost-01 patroni[5820]: 2019-03-21 18:44:25,871 INFO: Retrying on https://192.168.45.247:2379
Mar 21 18:44:25 testhost-01 patroni[5820]: 2019-03-21 18:44:25,873 ERROR: Failed to get list of machines from https://192.168.45.247:2379/v2: MaxRetryError("HTTPSConnectionPool(host='192.168.45.247', port=2379): Max retries exceeded with url: /v2/machines (Caused by ProtocolError('Connection aborted.', PermissionError(13, 'Permission denied')))",)
Mar 21 18:44:25 testhost-01 patroni[5820]: 2019-03-21 18:44:25,873 INFO: Retrying on https://192.168.45.248:2379
Mar 21 18:44:25 testhost-01 patroni[5820]: 2019-03-21 18:44:25,876 ERROR: Failed to get list of machines from https://192.168.45.248:2379/v2: MaxRetryError("HTTPSConnectionPool(host='192.168.45.248', port=2379): Max retries exceeded with url: /v2/machines (Caused by ProtocolError('Connection aborted.', PermissionError(13, 'Permission denied')))",)

Any suggestions?

**Comment by CyberDem0n** [comment]
`PermissionError(13, 'Permission denied')` -- for me it smells like lack of permissions to read one of the files (certificates or key) from disk

**Comment by drgarciafuentes** [comment]
I checked the permissions on the directory and the cert files, patroni should not have problems reading the files.
I disabled authentication on etcd, double checked that I still can access it with etcdctl using the same cert files, and now when I start patroni I get a different error in the syslog file, this time is a TLS alert (see below). I also created copies of the certs under /etc/patroni and make sure that the files have permissions for 'postgres' as per /etc/init.d/patroni
Certs should not be a problem cause they have been signed by the same ca used by etcd and the etcdctl tool can successfully use them to retrieve data (with- or without etcd auth)

>Mar 22 10:07:52 testhost-01 patroni[9528]: 2019-03-22 10:07:52,190 INFO: Retrying on https://192.168.45.245:2379
Mar 22 10:07:52 testhost-01 patroni[9528]: 2019-03-22 10:07:52,193 ERROR: Failed to get list of machines from https://192.168.45.245:2379/v2: MaxRetryError("HTTPSConnectionPool(host='192.168.45.245', port=2379): Max retries exceeded with url: /v2/machines (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:847)'),))",)
Mar 22 10:07:52 testhost-01 patroni[9528]: 2019-03-22 10:07:52,193 INFO: Retrying on https://192.168.45.246:2379
Mar 22 10:07:52 testhost-01 patroni[9528]: 2019-03-22 10:07:52,196 ERROR: Failed to get list of machines from https://192.168.45.246:2379/v2: MaxRetryError("HTTPSConnectionPool(host='192.168.45.246', port=2379): Max retries exceeded with url: /v2/machines (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:847)'),))",)
Mar 22 10:07:52 testhost-01 patroni[9528]: 2019-03-22 10:07:52,196 INFO: Retrying on https://192.168.45.247:2379
Mar 22 10:07:52 testhost-01 patroni[9528]: 2019-03-22 10:07:52,199 ERROR: Failed to get list of machines from https://192.168.45.247:2379/v2: MaxRetryError("HTTPSConnectionPool(host='192.168.45.247', port=2379): Max retries exceeded with url: /v2/machines (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:847)'),))",)
Mar 22 10:07:52 testhost-01 patroni[9528]: 2019-03-22 10:07:52,199 INFO: Retrying on https://192.168.45.248:2379
Mar 22 10:07:52 testhost-01 patroni[9528]: 2019-03-22 10:07:52,202 ERROR: Failed to get list of machines from https://192.168.45.248:2379/v2: MaxRetryError("HTTPSConnectionPool(host='192.168.45.248', port=2379): Max retries exceeded with url: /v2/machines (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:847)'),))",)
Mar 22 10:07:52 testhost-01 patroni[9528]: 2019-03-22 10:07:52,202 INFO: waiting on etcd
Mar 22 10:07:57 testhost-01 patroni[9528]: 2019-03-22 10:07:57,208 INFO: Selected new etcd server https://192.168.45.249:2379
Mar 22 10:07:57 testhost-01 patroni[9528]: 2019-03-22 10:07:57,211 ERROR: Failed to get list of machines from https://192.168.45.249:2379/v2: MaxRetryError("HTTPSConnectionPool(host='192.168.45.249', port=2379): Max retries exceeded with url: /v2/machines (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:847)'),))",)

Not sure what's going on here, any help is appreciated.

**Comment by CyberDem0n** [comment]
Now the error looking different.
Is there something interesting in the etcd logs?
What version of `python-etcd` do you have? You can check it by running `pip freeze`. If it is not the latest please try to upgrade.

**Comment by drgarciafuentes** [comment]
No entries on syslog regarding issues communicating with the etcd server host. I even replaced the "hosts: " line on the patroni config file for a single "host: " trying to isolate the problem.

I have python3-etcd  0.4.3-2 installed on the patroni client host

**Comment by CyberDem0n** [comment]
> No entries on syslog regarding issues communicating with the etcd server host

You have to check logs of etcd server. There should be something like:
```
2019-03-22 12:21:28.071231 I | embed: rejected connection from "127.0.0.1:44194" (error "tls: client offered an unsupported, maximum protocol version of 301", ServerName "")
```

> I have python3-etcd 0.4.3-2 installed on the patroni client host

The problem is that `python3-etcd` package is a bit outdated and doesn't include https://github.com/jplana/python-etcd/pull/196/files

I'll prepare a workaround for this problem in Patroni, but before that I would recommend you to either apply this patch manually or upgrade python-etcd with `pip3 install python-etcd --upgrade`, it should help.

**Comment by drgarciafuentes** [comment]
Yes, that was the issue. Apparently, Ubuntu does not have a specific group of maintainers looking at python libraries coming from upstream Debian, so python3-etcd is extremely outdated and the patch you suggested has not been incorporated yet.

Commenting the line `kw['ssl_version'] = ssl.PROTOCOL_TLSv1` resolved the problem, and after a few hoops with the yaml config file we were able to bring the first node up.

Next will be to re-enable authentication on the etcd cluster and try again.

Thanks for the help. We are looking forward to see that work around you suggested.
Regards
