### ISSUE TITLE
Hi again, having troubles with patroni + start postgresql control (everything is ok with patroni, but postgresql don't initialize at the same time i run patroni)

### ISSUE THREAD

**Issue by omm1979** [zalando/patroni#1012]
Hi, if someone could please help me i'll apreciate it, because i've configured etcd, patroni and postgresql and i haven't replication also i've read that when you start patroni this last have to control the postgresql start/stop cluster, and i've done some test without patroni installed, and replication works, but since i installed patroni replication failed, here are my configs:
- postgresql-10
- patroni 1.5.5

192.168.18.150 patroni_prueba1
192.168.18.151 patroni_prueba2
192.168.18.152 patroni_prueba3
192.168.18.153 etcd 		   
_______________________________
etcd
[etcd.txt](https://github.com/zalando/patroni/files/2998860/etcd.txt)
_______________________________
patroni.yml 3 nodes
[patroni1.yml.txt](https://github.com/zalando/patroni/files/2998861/patroni1.yml.txt)
[patroni2.yml.txt](https://github.com/zalando/patroni/files/2998862/patroni2.yml.txt)
[patroni3.yml.txt](https://github.com/zalando/patroni/files/2998863/patroni3.yml.txt)
_______________________________
pg_hba.conf
[pg_hba.conf.txt](https://github.com/zalando/patroni/files/2998865/pg_hba.conf.txt)
_______________________________
postgresql.conf
[postgresql.conf.txt](https://github.com/zalando/patroni/files/2998868/postgresql.conf.txt)
_______________________________
patroni.service
[patroni.service.txt](https://github.com/zalando/patroni/files/2998869/patroni.service.txt)

_______________________________

Regards.

**Comment by mashuma** [comment]
Hi @omm1979,

Please post logs from Primary and Replica for following
- patroni
- postgresql

Besides that, you really should run ETCD cluster with at least 3 nodes. Patroni cluster will become read only, if ETCD service becomes unavailable.

**Comment by omm1979** [comment]
Hi, thanks for your replay, in a moment i upload log files (postgresql, patroni and syslog), I've configured ETCD cluster with 1 node, and ETCD is working, because I can see the node and the parameters of leader, members, etc. 

![ETCD](https://user-images.githubusercontent.com/43590372/54939972-b58de080-4f21-11e9-8f9d-38fcf159636d.PNG)

What I do not see works or initiated is **postgresql** when I start patroni, so I have 3 virtual machines where I made a virtualbox snapshot before I started patroni to be able to change the configuration or what is necessary to retest, besides eliminating in ETCD the instance to clean the keys with: 
**patronictl -c /etc/patroni.yml list patroni_instance**

Also i've running all (postgresql, patroni, without root privileges, only with linux postgres user's).

Here you go log files:
_______________________________________________
/var/log/postgresql/postgresql-10-main.log

[postgresql-10-main.log.txt](https://github.com/zalando/patroni/files/3004631/postgresql-10-main.log.txt)
_______________________________________________
/data/patroni/pg_log/postgresql-2019-03-25_103112.log

[postgresql-2019-03-25_103112.log.txt](https://github.com/zalando/patroni/files/3004634/postgresql-2019-03-25_103112.log.txt)

_______________________________________________
/var/log/syslog
[syslog.txt](https://github.com/zalando/patroni/files/3004636/syslog.txt)

Thanks for your help, and best regards.

**Comment by CyberDem0n** [comment]
According to the "screenshot" Patroni is working only on one host. You need to start it on remaining hosts. If something doesn't work - check logs (probably syslog in your case).

**Comment by omm1979** [comment]
Thanks for your reply, i'll uploading my log files of leader node and 1 slave (syslog and /data/patroni/pg_log/patroni.log), It should be noted that all patroni's nodes and failover are already functioning, but the replication within postgres is not being done by patroni as I show in the next pics, there is a db called pedidos but this last didn't replicated to other nodes :
_______________________________________________________________________
patroni1
![image](https://user-images.githubusercontent.com/43590372/55008159-838b8580-4fd8-11e9-9d78-f8dd8c19d2bb.png)
_______________________________________________________________________
patroni2
![image](https://user-images.githubusercontent.com/43590372/55008645-2f34d580-4fd9-11e9-9f6e-e73e3ae7cd3c.png)
_______________________________________________________________________
patroni3
![image](https://user-images.githubusercontent.com/43590372/55008751-59869300-4fd9-11e9-8cd8-55796b62a150.png)
_______________________________________________________________________
etcd - as a I said etcd is running correctly.
![image](https://user-images.githubusercontent.com/43590372/55008446-ec72fd80-4fd8-11e9-912c-67591361bb9c.png)
_______________________________________________________________________
syslog (patroni1)
[syslog_patroni1.txt](https://github.com/zalando/patroni/files/3008914/syslog_patroni1.txt)

/data/patroni/pg_log/patroni.log (patroni1)
[postgresql-2019-03-25_140238_patroni1.log](https://github.com/zalando/patroni/files/3008917/postgresql-2019-03-25_140238_patroni1.log)
_______________________________________________________________________
syslog (patroni2)
[syslog_patroni2.txt](https://github.com/zalando/patroni/files/3008938/syslog_patroni2.txt)

/data/patroni/pg_log/patroni.log (patroni2)
[postgresql-2019-03-26_084702_patroni2.log](https://github.com/zalando/patroni/files/3008946/postgresql-2019-03-26_084702_patroni2.log)
_______________________________________________________________________
syslog (patroni3)
/data/patroni/pg_log/patroni.log (patroni3)
[postgresql-2019-03-26_084702_patroni3.log](https://github.com/zalando/patroni/files/3008965/postgresql-2019-03-26_084702_patroni3.log)


_______________________________________________________________________
I will follow the comments and the problem from https://github.com/zalando/patroni/issues/1011, in this post, as I said in the other post I guess, what I asked:
**_"I don't know if this subject (trouble) is misunderstood, because my main problem is that postgresql isn't doing database replication to the slaves nodes, obviously running with patroni (what i undestand how patroni do, is that patroni manage postgresql cluster instances to do a failover or HA, but i also understand that patroni control postgresql to do the replication, i mean databases also are replicated from master node to slaves nodes), am i rigth with the subject? or is unclear? I hope someone can help me with this, thanks."_**

So, Could you tell me what I'm missing in the configuration? because I did bare metal VM in ubuntu server 18.04, installed postgresql 10, patroni 1.5.5, and all necesary about 10 times, and the result is the same, null replication from master db postgresql to slaves postgresql, thanks.

**Comment by CyberDem0n** [comment]
Do you realize that there are TWO different postgres running on every host?
The first one was automatically created by when you installed postgres packages and data directory is located in the `/var/lib/postgresql/10/main`. It is visible when you run pg_lscluster.
The second one has the data directory in the `/data/patroni` and managed by Patroni.

When you use `psql`, it connects you to the first one via unix socket (which is not managed by Patroni)

**Comment by omm1979** [comment]
:O, :S ups i didn't realize that, I'll test again changing the parameter in **patroni.yml** in 3 nodes:
....
postgresql:
 listen: 192.168.18.150:5432
 connect_address: 192.168.18.150:5432
 bin_dir: /usr/lib/postgresql/10/bin
 **data_dir: /data/patroni/ ----> changing this to ---> /usr/lib/postgresql/10/bin**
 config_dir: /data/patroni/
.......
Thanks, I'll restore VMs before executing patroni changing that, and I'll put my feedback here and if it works I'll close this post, see you.

**Comment by CyberDem0n** [comment]
You've better remove the main cluster.
There should not be postgres running in auto-start mode!

**Comment by omm1979** [comment]
So, you propose to remove the main cluster with, **pg_dropcluster 10 main**?, and how can I create or handle dbs in patroni? many postgresql.conf/pgbackrest parameters are over postgresql cluster name-instance, how can I indicate or point to the instance of patroni to made working with any databases?, thanks a lot, I'll wait for your reply, regards.

**Comment by omm1979** [comment]
Goood news, after hours of meditation and understanding what https://github.com/CyberDem0n told me today **"You've better remove the main cluster. There should not be postgres running in auto-start mode!"** y realize that I don't need the **"postgresql 10 main"** instance, first stop patroni and change my patroni.yml (all 3 nodes):
....
postgresql:
listen: 192.168.18.150:5432
connect_address: 192.168.18.150:5432
bin_dir: /usr/lib/postgresql/10/bin
data_dir: /data/patroni/   <----- LET IT BE (THIS IS THE NEW postgresql 10 **_"main"_** instance)
config_dir: /data/patroni/
.......
next I did the: **pg_ctlcluster 10 main stop** and then **pg_dropcluster 10 main** (leaving only the postgresql patroni's instance):
Last I did in 3 nodes: **systemctl start patroni**
Everything was beautiful with replication and patroni working:
PATRONI
![OK FUNCIONANDO PATRONI 1](https://user-images.githubusercontent.com/43590372/55042263-a80f4e00-5028-11e9-8b27-74a1e8cf1fa6.PNG)
![OK FUNCIONANDO PATRONI 2](https://user-images.githubusercontent.com/43590372/55042264-a8a7e480-5028-11e9-8bf1-be07f1c79c24.PNG)
![OK FUNCIONANDO PATRONI 3](https://user-images.githubusercontent.com/43590372/55042265-a8a7e480-5028-11e9-8a2d-85710bf12ef7.PNG)
![OK FUNCIONANDO PATRONI ETCD](https://user-images.githubusercontent.com/43590372/55042266-a8a7e480-5028-11e9-8fbe-5ca2cfb9e3c3.PNG)

REPLICATION:
![OK FUNCIONANDO CREACION DE BD Y REPLICACION 1](https://user-images.githubusercontent.com/43590372/55042279-b1001f80-5028-11e9-9e61-e1494c07899d.PNG)
![OK FUNCIONANDO CREACION DE BD Y REPLICACION 2](https://user-images.githubusercontent.com/43590372/55042280-b198b600-5028-11e9-98f1-1f09d77da44d.PNG)
![OK FUNCIONANDO CREACION DE BD Y REPLICACION 3](https://user-images.githubusercontent.com/43590372/55042281-b198b600-5028-11e9-9793-5185b0f149f3.PNG)
![OK FUNCIONANDO PATRONI - PSQL DB REPLICATION](https://user-images.githubusercontent.com/43590372/55042282-b198b600-5028-11e9-8238-c3724c6169eb.PNG)


Thanks to all those who make things possible and help me, I hope this helps many more who are starting in patroni-postgresql-HA-failover my most sincere thanks to those who helped, I suppose that at some point I will return for some topic in specific (postgresql data backups), regards.
