### ISSUE TITLE
cluster broken

### ISSUE THREAD

**Issue by glushakov** [zalando/patroni#1016]
Hi. I created cluster in test env, it works sucessfull, and i forget it for 1 month.
Now it something strange.

When i start master node - it repeate in cycle:
 INFO: acquired session lock as a leader
Standby log:
Following a different leader because i am not the healthiest node

reinit, remove - not helped
I also try to delete all patroni files and config from master's PGDATA. Then change cluster name  in yml (like new clear postgres) - error not change.
What i'm doing wrong?
p.s. last time i played with pause\resume - maybe problem with it?

**Comment by CyberDem0n** [comment]
there is something wrong in global config stored in DCS
`patronictl show-config` will give you more details.

`ttl` must be not smaller than `loop_wait + 2*retry_timeout`

**Comment by glushakov** [comment]
at last i fixed it.
so i removed all etcd data to fix it.
i don't know what the problem, becausei "etcdctl cluster-health" shows OK. 
etcdctl ls - shows directory and keys, look likes everything ok, but master cannot write master key.
thank for your fast response

**Comment by CyberDem0n** [comment]
The problem was not with etcd, but with Patroni config stored in etcd.
