### ISSUE TITLE
How to Archive Command and Restore Command use GZ?

### ISSUE THREAD

**Issue by byazrail** [zalando/patroni#1027]
Hi guys,

my configs;
"restore_command": "cp ../wal_archive/%f %p"
"archive_command": "mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f"

How to use gz?
I did the trials, but I couldn't provide a solution.

**Comment by CyberDem0n** [comment]
Sorry, but your question has nothing to do with Patroni.
It is a general question about [PITR](https://www.postgresql.org/docs/current/continuous-archiving.html#COMPRESSED-ARCHIVE-LOGS) in postgres.
