### ISSUE TITLE
patronictl remove - cannot deletecollection endpoints in the namespace

### ISSUE THREAD

**Issue by scjoe** [zalando/patroni#1032]
We are on kubernetes 1.12 and we see an error if we try to call 'patronictl remove': 

HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"endpoints is forbidden: User "system:serviceaccount:XXXXX:postgresmaster" cannot deletecollection endpoints in the namespace "XXXXXX"","reason":"Forbidden","details":{"kind":"endpoints"},"code":403}

Adding "deletecollection" to the verbs in section endpoints for the role patronidemo seems to fix this.
Please review and add "deletecollection" to: https://github.com/zalando/patroni/blob/master/kubernetes/patroni_k8s.yaml

````
  resources:
  - endpoints
  verbs:
  - get
  - patch
  - update
  # the following three privileges are necessary only when using endpoints
  - create
  - list
  - watch
  # delete is required only for for 'patronictl remove'
  - delete
  - deletecollection
````

**Comment by CyberDem0n** [comment]
@scjoe please open a PR, we will happily review and merge it.
