### ISSUE TITLE
Can patroni handle the failover of multiple postgres instances? 

### ISSUE THREAD

**Issue by Kriss64** [zalando/patroni#1034]
Hi, 

I have two postgres instances running on same server (5432 and 5433).  
I have setup the HA for once instance but couldn't find any documentation on how it can be done for multiple instances. Is it even possible?

Thanks.

**Comment by uspen** [comment]
Yes, its possible, of course. But I run one HAproxy instance per one patroni cluster

**Comment by Kriss64** [comment]
@uspen , I have 3 postgres nodes. 1 is Master other 2 are replica. Each of these nodes have patroni and ETCD installed. This setup is working fine for single instance (5432 port).
I want to manage the failover of second instance (5433 port) as well. how can I implement this? please suggest.

**Comment by uspen** [comment]
![PostgreSQL HA - PgConf](https://user-images.githubusercontent.com/7964692/56130693-49395680-5f8e-11e9-9fe5-04379d0ae7a7.png)

What is it 'second instance'?

You have one cluster or two?

**Comment by Kriss64** [comment]
I was able to achieve this by creating two instances of patroni.service that used different patroni.yml files pointing to different postgres instances.

**Comment by Kriss64** [comment]
Thank you @uspen for the architecture diagram. It helped a lot.

**Comment by uspen** [comment]
And:
`cat /etc/systemd/system/patroni@.service 
[Unit]
Description=Runners to orchestrate a high-availability PostgreSQL
After=syslog.target network.target
[Service]
Type=simple
User=postgres
Group=postgres
ExecStart=/usr/bin/patroni /etc/patroni.d/%i.yml  <--- this templating
ExecReload=/usr/bin/kill -HUP $MAINPID
KillMode=process
TimeoutSec=600
Restart=no
OOMScoreAdjust=-1000
[Install]
WantedBy=multi-user.target
`
Usage:
systemctl enable patroni@_you_instance_

**Comment by Youhbi** [comment]
> 
> 
> I was able to achieve this by creating two instances of patroni.service that used different patroni.yml files pointing to different postgres instances.

Hi Kriss
Could you explain a little more in detail? I'm stuck with this problem right now :)
