### ISSUE TITLE
Patroni working on one instance but failing on another on same server with error: OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Kriss64** [zalando/patroni#1042]
Hi, I am trying to run two instances of patroni to manage failover of two instances of postgres. On master node, I got everything working but on slave node, I am getting below error:

Apr 18 03:16:20 dc2-rhel3 patroni: 2019-04-18 03:16:20,418 INFO: Failed to import patroni.dcs.consul
Apr 18 03:16:20 dc2-rhel3 patroni: 2019-04-18 03:16:20,425 INFO: Selected new etcd server http://172.26.248.112:2379
Apr 18 03:16:20 dc2-rhel3 patroni: 2019-04-18 03:16:20,933 INFO: Lock owner: postgresql-inst2-0; I am postgresql-inst2-2
Apr 18 03:16:20 dc2-rhel3 patroni: Traceback (most recent call last):
Apr 18 03:16:20 dc2-rhel3 patroni: File "/bin/patroni", line 11, in <module>
Apr 18 03:16:20 dc2-rhel3 patroni: load_entry_point('patroni==1.5.6', 'console_scripts', 'patroni')()
Apr 18 03:16:20 dc2-rhel3 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 169, in main
Apr 18 03:16:20 dc2-rhel3 patroni: return patroni_main()
Apr 18 03:16:20 dc2-rhel3 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 159, in patroni_main
Apr 18 03:16:20 dc2-rhel3 patroni: patroni.run()
Apr 18 03:16:20 dc2-rhel3 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 125, in run
Apr 18 03:16:20 dc2-rhel3 patroni: logger.info(self.ha.run_cycle())
Apr 18 03:16:20 dc2-rhel3 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1323, in run_cycle
Apr 18 03:16:20 dc2-rhel3 patroni: info = self._run_cycle()
Apr 18 03:16:20 dc2-rhel3 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1265, in _run_cycle
Apr 18 03:16:20 dc2-rhel3 patroni: data_sysid = self.state_handler.sysid
Apr 18 03:16:20 dc2-rhel3 patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 415, in sysid
Apr 18 03:16:20 dc2-rhel3 patroni: data = self.controldata()
Apr 18 03:16:20 dc2-rhel3 patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1236, in controldata
Apr 18 03:16:20 dc2-rhel3 patroni: data = subprocess.check_output([self._pgcommand('pg_controldata'), self._data_dir], env=env)
Apr 18 03:16:20 dc2-rhel3 patroni: File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
Apr 18 03:16:20 dc2-rhel3 patroni: process = Popen(stdout=PIPE, *popenargs, **kwargs)
Apr 18 03:16:20 dc2-rhel3 patroni: File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
Apr 18 03:16:20 dc2-rhel3 patroni: errread, errwrite)
Apr 18 03:16:20 dc2-rhel3 patroni: File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
Apr 18 03:16:20 dc2-rhel3 patroni: raise child_exception
Apr 18 03:16:20 dc2-rhel3 patroni: OSError: [Errno 2] No such file or directory
Apr 18 03:16:20 dc2-rhel3 systemd: patroni-inst2.service: main process exited, code=exited, status=1/FAILURE
Apr 18 03:16:20 dc2-rhel3 systemd: Unit patroni-inst2.service entered failed state.
Apr 18 03:16:20 dc2-rhel3 systemd: patroni-inst2.service failed.

Please note that on this server, I have one other instance of patroni running successfully. 
Let me know what I'm missing.

**Comment by CyberDem0n** [comment]
Have you tried to use [search](https://github.com/zalando/patroni/issues?q=is%3Aissue+OSError%3A+%5BErrno+2%5D+No+such+file+or+directory+is%3Aclosed) before creating an issue?

**Comment by Kriss64** [comment]
@CyberDem0n , I did. old posts indicated that it cannot find postgresql binaries. for this, I exported the path in .bashrc file but it still wasn't working. 
specifying the path bin_dir parameter inside yml file made it work.

**Comment by Kriss64** [comment]
I didn't close my old session after making the change in .bashrc file so it wasn't reading the updated path hence causing this issue.
