### ISSUE TITLE
what patroni parameter to be passed for creating a database

### ISSUE THREAD

**Issue by sysadmin-imran** [zalando/patroni#1043]
What patroni parameter is to be passed for creating a database during docker container startup with superuser creadentials. like below
PATRONI_SUPERUSER_PASSWORD=admin123
PATRONI_SUPERUSER_USERNAME=admin 
i wanna also passed a parameter which will create a database with above credentials.

How to do it using docker environment as i want that database to be created while container launching something like POSTGRES_DB=testdb of postgresql.

**Comment by CyberDem0n** [comment]
The primary goal of Patroni is automatic failover.
Creation of databases is out of scope.

**Comment by sysadmin-imran** [comment]
then how should we create a database of postgresql while launching of docker container of postgresql (i am using an image combining patroni 1.5.6 and postgresql 11.2 ). Right now i am creating that database manually by going into the container. i think patroni team needs to come up with something to resolve this like PATRONI_POSTGRES_DB environment variable, as it seems to be a limitation with patroni.

**Comment by CyberDem0n** [comment]
Patroni is able to execute `post_bootstrap` script for you, there you can do whatever you want.
