### ISSUE TITLE
Program terminated with signal 7, Bus error.

### ISSUE THREAD

**Issue by henrywangx** [zalando/patroni#1045]
Hi all, I have expericed bellow issue. After run serveral days, the standby pods always crash. And I try to decode with "gdb core.xxxx", only those info show:

```bash
startup process   recovering 0000001600000001000000D4  '.
Program terminated with signal 7, Bus error.
#0  0x0000556cefa9a379 in ?? ().
```

So how to decode those corefile? Could you know which problem may cause this issue?
And My configuration:

```bash
#K8S:
        resources:
          limits:
            hugepages-2Mi: 256Mi
          requests:
            hugepages-2Mi: 256Mi
            memory: 1Gi
# Patroni:
    postgresql:
      use_pg_rewind: true
      parameters:
        shared_preload_libraries: "timescaledb"
        synchronous_commit: "off"
        max_connections: "300"
        shared_buffers: "256MB"
        effective_cache_size: "768MB"
```

**Comment by CyberDem0n** [comment]
How do you run Patroni in container?
Do you use Spilo? Which version?
What Patroni version do you run?

I can guess that the issue is with `restore_command`.

**Comment by henrywangx** [comment]
Hi, I use the k8s's example to deploy and build container. And we use the config map as the DCS.
Not spilo. I don't know how to check the patroni's version. I think it should v1.5.5.
What's the story about `restore_command`? 
Do it has relationship to HugePage? I found if the host has enable the hugepage, the postgreSQL will crash. So here I just enable the HugePage.
Since we need the PV. I just modify a part in yaml, add an initContainer to deal the permission:

```bash
      initContainers:
      - name: init-permission
        image: busybox
        command: 
        - chown
        - "-R"
        - "999:999"
        - "/home/postgres"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: pgdata
          mountPath: "/home/postgres"
      containers:
      - name: *cluster_name
        image: patroni  # docker build -t patroni .
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /home/postgres/pgdata
          name: pgdata
        env:
        - name: PATRONI_KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PATRONI_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        #- name: PATRONI_KUBERNETES_USE_ENDPOINTS
        #  value: 'true'
        - name: PATRONI_KUBERNETES_LABELS
          value: '{application: patroni, cluster-name: patronidemo}'
        - name: PATRONI_SUPERUSER_USERNAME
          value: postgres
        - name: PATRONI_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: *cluster_name
              key: superuser-password
        - name: PATRONI_REPLICATION_USERNAME
          value: standby
        - name: PATRONI_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: *cluster_name
              key: replication-password
        - name: PATRONI_SCOPE
          value: *cluster_name
        - name: PATRONI_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PATRONI_POSTGRESQL_DATA_DIR
          value: /home/postgres/pgdata/pgroot/data
        - name: PATRONI_POSTGRESQL_PGPASS
          value: /tmp/pgpass
        - name: PATRONI_POSTGRESQL_LISTEN
          value: '0.0.0.0:5432'
        - name: PATRONI_RESTAPI_LISTEN
          value: '0.0.0.0:8008'
      terminationGracePeriodSeconds: 0
  volumeClaimTemplates:
  - metadata:
      labels:
        application: patroni
        cluster-name: *cluster_name
      name: pgdata
    spec:
      storageClassName: manual
      accessModes:
      - ReadWriteOnce
      selector:
        matchLabels:
          app: patroni
      resources:
        requests:
          storage: 1Gi
```

**Comment by CyberDem0n** [comment]
No, restore_command has nothing to do with huge pages.

Actually I don't know how `hugepages-2Mi` supposed to work and whether the value you specified there is enough to fit shared_buffers. Have you explicitly enabled huge pages in postgres config?

In order to get more info from gdb you need to install debug symbols package: `postgresql-XX-dbgsym`

**Comment by henrywangx** [comment]
shared_buffers: "256MB"
So the hugepages-2Mi is set to 256MB.
Actually, the postgres will check the /proc/meminfo when bootup. 
It find there is enough Hugepage and will use them. Otherwise, it will try the normal memory.
I will install the symbol package to debug this issue. Thanks for your help

**Comment by le-duane** [comment]
Postgres actually allocates slightly more than 256 MiB of shared memory when "256MB" shared buffers is requested. 

You can view the exact allocations via `pmap -X $(head -1 $PGDATA/postmaster.pid) |egrep '(zero|anon)'|awk '{print $6}'`

Your Postgres instance is most likely crashing when it crosses that 256MiB huge page limit of your Kuberenetes Pod.

P.S. I know this issue is stale - just updating for any others who might encounter.
