### ISSUE TITLE
Disallow bootstrapping replicas from backups if leader isn't bootstrapping from backups as well 

### ISSUE THREAD

**Issue by c4milo** [zalando/patroni#1048]
I'm not sure whether this should be Patroni's responsibility but I'm creating this ticket anyway to make people aware of the potential problem.

When bootstrapping new clusters, it is possible fall into a System ID mismatch problem if the cluster leader isn't bootstrapped from backups but its replicas are. It could be useful to tie up bootstrapping replicas from backups as long as the leader is also bootstrapped from backups.

**Comment by alexeyklyukin** [comment]
This could happen if you created your replicas from with the `create_replica_method` that images them from the backup while creating the primary with initdb (or bootstrapping it from another, unrelated backup). You should make sure the base backup you are bootstrapping your replicas has been produced from your current primary, or that your current primary has been bootstrapped from the same base backup.

This is not the task of Patroni to verify that, as Patroni relies on the external scripts to create replicas from the base backup. Perhaps those scripts can be improved to check the system Id of the base backup using pg_controldata from the matching version. From the Patroni side, we could pass the current primary systemID, when known, to those replica creation scripts
