### ISSUE TITLE
After Patroni 1.5.5 Upgrade and after update to parameter in patroni.yml, a systemctl restart patroni service crashes the original master with "ERROR: Exception during CHECKPOINT" 

### ISSUE THREAD

**Issue by kylekarus** [zalando/patroni#1050]
Hello,
After upgrading Patroni from 1.5.4 to 1.5.5 (same issue with 1.5.6 as well), when we restart the patroni service on the original Master, the original Master crashes with "ERROR: Exception during CHECKPOINT".  This is reproducible.  Here are the exact steps that were taken:
1) On Master - Updated /etc/patroni/patroni.yml file temp_file_size from 16gb to 24gb (same issue happens if a different parameter is modified)
2) On Master - systemctl restart patroni
3) Slave becomes the Master (Leader)
4) The "original" Master crashes with "stopped" state and we see the following errors:
Apr 30 14:13:21 <Slave_old_Master> patroni[85130]: 2019-04-30 14:13:21,616 INFO: Lock owner: <Master_old_Slave>; I am <Slave_old_Master>
Apr 30 14:13:21 <Slave_old_Master> patroni[85130]: 2019-04-30 14:13:21,623 INFO: Lock owner: <Master_old_Slave>; I am <Slave_old_Master>
Apr 30 14:13:21 <Slave_old_Master> patroni[85130]: 2019-04-30 14:13:21,636 INFO: running pg_rewind from <Master_old_Slave>
Apr 30 14:13:21 <Slave_old_Master> patroni[85130]: 2019-04-30 14:13:21,652 ERROR: Exception during CHECKPOINT

5) Here is the patronictl list output:
+--------------+--------------------+--------------------+--------+---------+----+-----------+
|   Cluster    |          Member    |           Host     |  Role  |  State  | TL | Lag in MB |
+--------------+--------------------+--------------------+--------+---------+----+-----------+
| patroni_pg11 | <Master_old_Slave> | <Master_old_Slave> | Leader | running | 25 |       0.0 |
| patroni_pg11 | <Slave_old_Master> | <Slave_old_Master> |        | stopped |    |   unknown |
+--------------+--------------------+--------------------+--------+---------+----+-----------+

6) Must recreate the replica OR downgrade Patroni to 1.5.4 and restart patroni service on <Slave_old_Master> and all looks good.  

This looks to be a bug of some sort as we didn't encounter this issue prior to version 1.5.5/1.5.6. 

Please help.  Thank you for your time.  

Kyle

**Comment by CyberDem0n** [comment]
Not enough information.
You have to provide configs and logs from patroni and postgres from both nodes.

**Comment by kylekarus** [comment]
[Master_old_Slave_Postgres-Wed.log](https://github.com/zalando/patroni/files/3139563/Master_old_Slave_Postgres-Wed.log)
[Master_old_Slave_System_Log.log](https://github.com/zalando/patroni/files/3139564/Master_old_Slave_System_Log.log)
[Slave_old_Master_System_Log.log](https://github.com/zalando/patroni/files/3139565/Slave_old_Master_System_Log.log)
[Slave_old_Master_Postgres-Wed.log](https://github.com/zalando/patroni/files/3139566/Slave_old_Master_Postgres-Wed.log)
[Master_old_Slave_patroni.txt](https://github.com/zalando/patroni/files/3139580/Master_old_Slave_patroni.txt)
[Slave_old_Master_patroni.txt](https://github.com/zalando/patroni/files/3139581/Slave_old_Master_patroni.txt)
[Master_old_Slave_postgresql.txt](https://github.com/zalando/patroni/files/3139582/Master_old_Slave_postgresql.txt)
[Slave_old_Master_postgresql.txt](https://github.com/zalando/patroni/files/3139583/Slave_old_Master_postgresql.txt)

**Comment by CyberDem0n** [comment]
```
May  1 09:20:38 Slave_old_Master patroni: 2019-05-01 09:20:38,145 ERROR: Exception during CHECKPOINT
May  1 09:20:38 Slave_old_Master patroni: Traceback (most recent call last):
May  1 09:20:38 Slave_old_Master patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 948, in checkpoint
May  1 09:20:38 Slave_old_Master patroni: with self._get_connection_cursor(**connect_kwargs) as cur:
May  1 09:20:38 Slave_old_Master patroni: File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
May  1 09:20:38 Slave_old_Master patroni: return self.gen.next()
May  1 09:20:38 Slave_old_Master patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1250, in _get_connection_cursor
May  1 09:20:38 Slave_old_Master patroni: with psycopg2.connect(**kwargs) as conn:
May  1 09:20:38 Slave_old_Master patroni: File "/usr/lib64/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
May  1 09:20:38 Slave_old_Master patroni: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
May  1 09:20:38 Slave_old_Master patroni: OperationalError: FATAL:  password authentication failed for user "postgres"
May  1 09:20:38 Slave_old_Master patroni: FATAL:  no pg_hba.conf entry for host "IP_Slave_old_Master", user "postgres", database "postgres", SSL off
```

```
2019-05-01 09:20:38 CDT [14418]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=y.y.y.y LOG:  connection received: host=y.y.y.y port=52464
2019-05-01 09:20:38 CDT [14418]: [2-1] db=postgres, user=postgres, app=[unknown], client=y.y.y.y FATAL:  password authentication failed for user "postgres"
2019-05-01 09:20:38 CDT [14418]: [3-1] db=postgres, user=postgres, app=[unknown], client=y.y.y.y DETAIL:  Password does not match for user "postgres".
	Connection matched pg_hba.conf line 21: "hostssl all             all             0.0.0.0/0               md5"
2019-05-01 09:20:38 CDT [14419]: [1-1] db=[unknown], user=[unknown], app=[unknown], client=y.y.y.y LOG:  connection received: host=y.y.y.y port=52466
2019-05-01 09:20:38 CDT [14419]: [2-1] db=postgres, user=postgres, app=[unknown], client=y.y.y.y FATAL:  no pg_hba.conf entry for host "y.y.y.y", user "postgres", database "postgres", SSL off
```

Does it ring a bell?

Either you (or somebody else) changed the password for postgres user in the cluster or changed the `postgresql.authentication` section in the Patroni config.
In both cases Patroni is not able to connect to postgres.

**Comment by kylekarus** [comment]
Hello, we've received that warning message when we were at 1.5.4 as well.  It can be cleared by updating the pg_hba.conf file.  When we went to 1.5.5, we are getting "ERROR: Exception during CHECKPOINT" when restarting the Master after a patroni.yml change (which becomes the Slave with the error).  If we downgrade to 1.5.4, everything works fine when we change a patroni.yml parameter.  On 1.5.4, we also see the password authentication issues.  On the box that the "ERROR: Exception during CHECKPOINT" occurs, if I run "pip install patroni==1.5.4" and restart the patroni service, all looks good again.  Thank you for your time.

**Comment by CyberDem0n** [comment]
If the former master needs to run pg_rewind in order to join as a new replica, it needs to connect to the new master and run a CHECKPOINT in order to make sure that pg_control was updated after promote.
pg_rewind itself also requires superuser access to the master until postgres 11.
The next patroni release will make it possible to create/specify a separate user for pg_rewind.

**Comment by kylekarus** [comment]
Thank you for the information.  Is this functionality different in 1.5.5/1.5.6 as it was in 1.5.4?  We don't understand why we never saw this issue in versions < 1.5.5.  Again, thank you for your time, we appreciate it!

**Comment by CyberDem0n** [comment]
No, it was always working like this.

**Comment by kylekarus** [comment]
Thank you.
