### ISSUE TITLE
post_init

### ISSUE THREAD

**Issue by Zzzwenjie** [zalando/patroni#1058]
where can i find the template of  post_init?please

**Comment by CyberDem0n** [comment]
Post init receives a single argument, the connection string.
Here is the post_init from Spilo: https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/post_init.sh

**Comment by Zzzwenjie** [comment]
Thank u for that.But what's the connection string means?And my purpose is just create a database,should i just add "create database eg" to the shell?

**Comment by Zzzwenjie** [comment]
> Post init receives a single argument, the connection string.
> Here is the post_init from Spilo: https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/post_init.sh

Thank u for that.But what's the connection string means?And my purpose is just create a database,should i just add "create database eg" to the shell?

**Comment by CyberDem0n** [comment]
> what's the connection string means?

Connection string to the postgres cluster, `postgres://host:port/database`.

> should i just add "create database eg" to the shell?

It is up to you. You don't need most of the stuff from our script.

**Comment by Zzzwenjie** [comment]
Thank u again.My postgres is deployed in k8s,but whatever ip i use(vm ip,service ip),i can't run it right.
eg:   postgres://192.168.56.122:5432/postgres ,postgres://postgres:5432/postgres.How does it work?

**Comment by Zzzwenjie** [comment]
> Connection string to the postgres cluster, `postgres://host:port/database`.
> Thank u again.My postgres is deployed in k8s,but whatever ip i use(vm ip,service ip),i can't run it right.
eg: postgres://192.168.56.122:5432/postgres ,postgres://postgres:5432/postgres.How does it work?

**Comment by Zzzwenjie** [comment]
> Connection string to the postgres cluster, `postgres://host:port/database`.
> Thank u again.My postgres is deployed in k8s,but whatever ip i use(vm ip,service ip),i can't run it right.
eg: postgres://vm ip:5432/postgres(the service type is nodeport) ,postgres://clusterip:5432/postgres(the service type is clusterip).How does it work?

**Comment by Zzzwenjie** [comment]
> Connection string to the postgres cluster, `postgres://host:port/database`.
> Thank u again.My postgres is deployed in k8s,but whatever ip i use(vm ip,service ip),i can't run it right.
eg: postgres://vm ip:5432/postgres(the service type is nodeport) ,postgres://clusterip:5432/postgres(the service type is clusterip).How does it work?

**Comment by Zzzwenjie** [comment]
> > what's the connection string means?
> 
> Connection string to the postgres cluster, `postgres://host:port/database`.


Thank u again.My postgres is deployed in k8s,but whatever ip i use(vm ip,service ip),i can't run it right.
eg: postgres://vm ip:5432/postgres(the service type is nodeport) ,postgres://clusterip:5432/postgres(the service type is clusterip).How does it work?

**Comment by Zzzwenjie** [comment]
And nether can it work when i use 127.0.0.1 0.0.0.0 or so.

**Comment by CyberDem0n** [comment]
Patroni executes post_init.sh as `post_init.sh postgres://$host:$port/$database`.
The only you have to do is to grab the first parameter (`$1`) and use it to run psql: `psql -d $1`.
Is it really so complicated?

**Comment by Zzzwenjie** [comment]
> Patroni executes post_init.sh as `post_init.sh postgres://$host:$port/$database`.
> The only you have to do is to grab the first parameter (`$1`) and use it to run psql: `psql -d $1`.
> Is it really so complicated?

The way you described is simple.But i didn't work it out. The same scripts for initializing,when i use 'kubectl exec' to exec in k8s pod,it's ok.But everytime i use it by post_init,it turns out failed.That's why i did't get the point how to truly use the post_init.
