### ISSUE TITLE
Allow a cluster member to bootstrap in the absence of the leader

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/patroni#106]
Previously, we could only use pg_basebackup to bootstrap the new replica, which obviously required a running master. Currently, we also have a possibility to use WAL-E, as well as user-supplied replica creation methods that don't require a running master, since the data is stored on S3 or any other external storage. We need to change the Patroni behavior to bootstrap even if the leader is not present, in case the replica creation method allows it. Since there is no way we can auto detect the ability of the replica creation method to create replicas without the running master, we should add a parameter to the method configuration, indicating that.

The result is that we can recover from stupid errors, like the case of someone just shutting down all Patroni instances at once.

**Comment by drnic** [comment]
Is this now supported with addition of `create_replica_method` list? Is there an example for configuring wal-e to allow a fresh cluster (disaster recovery) to recover from just the S3 backups?

**Comment by drnic** [comment]
From code reading, it seems that `no_master: true` is required; but the spilo project doesn't set this https://github.com/zalando/spilo/blob/master/postgres-appliance/postgres_ha.sh#L108-L117

**Comment by feikesteenbergen** [comment]
This is pretty much done at the moment. Spilo may set this in the future ...
