### ISSUE TITLE
Patroni Replication Issues after PITR

### ISSUE THREAD

**Issue by nico1106** [zalando/patroni#1062]
`Patroni Version: 1.5.6
WAL-G Version: v0.2.9
Postgres Version: 11`

Hi,
I've restored my PostgreSQL Cluster with PITR. Both Instances are getting up at the same time. 
After the restore my master instance came up, as well as the slave instance and patroni. 
BUT patroni says on the master instance:

`2019-05-16 06:33:21,040 INFO: Lock owner: lpdkpga00004vm-pc00000; I am lpdkpga00004vm-pc00000
2019-05-16 06:33:21,308 INFO: no action.  i am the leader with the lock
2019-05-16 06:33:31,024 INFO: Lock owner: lpdkpga00004vm-pc00000; I am lpdkpga00004vm-pc00000
2019-05-16 06:33:31,222 INFO: no action.  i am the leader with the lock`

on the slave instance I got:
`2019-05-16 06:33:09,272 INFO: no action.  i am a secondary and i am following a leader
2019-05-16 06:33:11,155 INFO: Lock owner: lpdkpga00004vm-pc00000; I am lpdkpgb00004vm-pc00000
2019-05-16 06:33:11,155 INFO: does not have lock
2019-05-16 06:33:11,254 INFO: no action.  i am a secondary and i am following a leader
2019-05-16 06:33:21,177 INFO: Lock owner: lpdkpga00004vm-pc00000; I am lpdkpgb00004vm-pc00000
2019-05-16 06:33:21,177 INFO: does not have lock`

Both postgres instances are running, but the problem here is, that they have different Timelines and the replication connection has been lost, but Patroni does nothing?

`[root@9635e307fe67 postgres]# patronictl list

+---------+------------------------+----------------------------------+--------+---------+----+-----------+
| Cluster |         Member         |               Host               |  Role  |  State  | TL | Lag in MB |
+---------+------------------------+----------------------------------+--------+---------+----+-----------+
| pc00000 | lpdkpga00004vm-pc00000 | lpdkpga00004vm:5435 | Leader | running |  9 |         0 |
| pc00000 | lpdkpgb00004vm-pc00000 | lpdkpgb00004vm:5435 |        | running |  8 |           |
+---------+------------------------+----------------------------------+--------+---------+----+-----------+`

ONLY after the new basebackup is uploaded to S3, a reinit will work.
If the new basebackup isn't uploaded to S3 and I do a reinit for the slave instance, I get the same behaviour as shown above...

In my opinion I would expect that patroni will try to fix that problem and tries to get the current timeline from the master and starts the replication connection again...

**Comment by CyberDem0n** [comment]
Have you looked into postgres logs?
There should be a hint of why the replica didn't follow the primary.

**Comment by nico1106** [comment]
PostgreSQL Logs show this on slave:

`could not start WAL streaming: ERROR:  requested timeline 9 is not in this server's history`
`new timeline 9 is not a child of database system timeline 8`

**Comment by CyberDem0n** [comment]
You see, the problem has nothing to do with Patroni.

**Comment by nico1106** [comment]
Patroni is not able to handle this and to sync again?

**Comment by CyberDem0n** [comment]
Handle what? It has no idea where backups were restored from.

**Comment by nico1106** [comment]
It has the the idea where backups were restored from with "clone_with_wale" method or "create_replica_method" where it syncs the slave from the master or from backups.

**Comment by CyberDem0n** [comment]
And? You are only referring to some configuration and scripts.
The actual backup/restore logic is hidden from Patroni.
