### ISSUE TITLE
Replication Catch Up of down node

### ISSUE THREAD

**Issue by cognition** [zalando/patroni#1063]
I'm asking a question here, since I can't find the answer elsewhere... 

I had a node go down for maintenance and was out by 350 mb when it came back up. The node was not able to catch up and the delta only grew. 
What parameter can I tweak to allow for that size of delta and still have the node catch up without having to rebuild it manually?

**Comment by uspen** [comment]
wal_keep_segments

**Comment by cognition** [comment]
I tried upping the wal_keep_segments and the max_wal_size but it only worked on one of three nodes. 
this is what I did to change the params: 
 ```
curl -s -XPATCH <ip>:8008/config -d '{"postgresql":{"parameters":
{"wal_keep_segments":"190","max_wal_size":"3GB"}}}'
```
