### ISSUE TITLE
k8s initdb Permission denied

### ISSUE THREAD

**Issue by Zzzwenjie** [zalando/patroni#1065]
hello,this is my error:
   019-05-18 20:44:21,057 INFO: Failed to import patroni.dcs.consul
2019-05-18 20:44:21,058 INFO: Failed to import patroni.dcs.etcd
2019-05-18 20:44:21,059 INFO: Failed to import patroni.dcs.exhibitor
2019-05-18 20:44:21,419 INFO: Reaped pid=11, exit status=0
2019-05-18 20:44:21,579 INFO: Reaped pid=63, exit status=0
2019-05-18 20:44:21,826 INFO: Lock owner: None; I am postgres-0
2019-05-18 20:44:23,159 INFO: trying to bootstrap a new cluster
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are enabled.

initdb: could not create directory "/home/postgres/pgdata/data": Permission denied
pg_ctl: database system initialization failed
2019-05-18 20:44:23,464 INFO: removing initialize key after failed attempt to bootstrap the cluster
2019-05-18 20:44:23,785 INFO: Lock owner: None; I am postgres-0
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/patroni/__init__.py", line 159, in patroni_main
    patroni.run()
  File "/usr/local/lib/python3.5/dist-packages/patroni/__init__.py", line 125, in run
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 1329, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 1238, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 1134, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 1129, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'

And the statefuset which i modified from the template is:

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: &cluster_name postgres
  labels:
    application: postgres
    cluster-name: *cluster_name
spec:
  replicas: 3
  serviceName: *cluster_name
  template:
    metadata:
      labels:
        application: postgres
        cluster-name: *cluster_name
    spec:
      serviceAccountName: postgres
      containers:
      - name: *cluster_name
        image: postgres:201905171713  # docker build -t patroni .
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        env:
        - name: PATRONI_KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PATRONI_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PATRONI_KUBERNETES_USE_ENDPOINTS
          value: 'true'
        - name: PATRONI_KUBERNETES_LABELS
          value: '{application: postgres, cluster-name: postgres}'
        - name: PATRONI_SUPERUSER_USERNAME
          value: postgres
        - name: PATRONI_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: *cluster_name
              key: superuser-password
        - name: PATRONI_REPLICATION_USERNAME
          value: standby
        - name: PATRONI_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: replication-password
        - name: PATRONI_SCOPE
          value: *cluster_name
        - name: PATRONI_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PATRONI_POSTGRESQL_DATA_DIR
          value: /home/postgres/pgdata/data
        - name: PATRONI_POSTGRESQL_PGPASS
          value: /tmp/pgpass
        - name: PATRONI_POSTGRESQL_LISTEN
          value: '0.0.0.0:5432'
        - name: PATRONI_RESTAPI_LISTEN
          value: '0.0.0.0:8008'
        volumeMounts:
        - name: pgdata
          mountPath: /home/postgres/pgdata
        - name: sys-time
          mountPath: /etc/localtime
      volumes:
      - name: sys-time
        hostPath:
            path: /etc/localtime
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast
      resources:
       requests:
         storage: 2Gi

i wonder know why there is an permission  problem and how to fix it.Thanks a lot

**Comment by fjodor-rybakov** [comment]
I had the same problem. I solved it by setting the permission to the current user. 
sudo chown -R <user>:<group> <path>

**Comment by henrywangx** [comment]
Hi just  `chmod 700` + `chown 999:999` like my example: [https://github.com/henrywangx/ha-pg](https://github.com/henrywangx/ha-pg)
