### ISSUE TITLE
patroni faiover test failed.

### ISSUE THREAD

**Issue by myeashion** [zalando/patroni#1066]
Hi,
  I have 3 nodes in my cluster. Every node running a zookeeper(zk) node.
  nodes:
    node1:(name=node-7e7b9093-0127-4fde-a7b3-6135068d14b0, ip=172.18.137.241)
    node2:(name=node-47442db8-4e77-4598-b869-a01e3e71621f, ip=172.18.137.242)
    node3:(name=node-8e0c2af6-2499-4b64-bfd6-4986ab2b8dfb, ip=172.18.137.243)  lock owner

I try to build the cluster. After some HA testing(just reboot os system, kill ptroni/pg process), there are two problems.

1. patroni on node1 can not start.
patroni logs are as follows:
2019-05-20 04:36:07,505 CRITICAL: system ID mismatch, node node-7e7b9093-0127-4fde-a7b3-6135068d14b0 belongs to a different cluster: 6691853177538966272 != 6691855245413036253
2019-05-20 04:36:07,986 INFO: Lock owner: node-8e0c2af6-2499-4b64-bfd6-4986ab2b8dfb; I am node-7e7b9093-0127-4fde-a7b3-6135068d14b0
[2019-05-20 04:36:12-startServer]: This is a cluster, so should start the haproxy.
[2019-05-20 04:36:12-startServer]: The haproxy(26725) already STARTED, No need to start

I check zk in every node, data is consisttent. 
It seems patroni found a different database_system_identifier 6691855245413036253, why this happens and how to sovle the problem.

 
2. pg on node2 is always in starting status and can not turn to work.
here are pg logings:
2019-05-20 04:17:20.616 CST [13608] LOG:  database system was shut down in recovery at 2019-05-19 15:28:12 CST
2019-05-20 04:17:20.616 CST [13608] LOG:  entering standby mode
2019-05-20 04:17:20.621 CST [13609] FATAL:  could not start WAL streaming: ERROR:  replication slot "node_47442db8_4e77_4598_b869_a01e3e71621f" does not exist
2019-05-20 04:17:20.625 CST [13610] FATAL:  could not start WAL streaming: ERROR:  replication slot "node_47442db8_4e77_4598_b869_a01e3e71621f" does not exist
2019-05-20 04:17:25.632 CST [13639] FATAL:  could not start WAL streaming: ERROR:  replication slot "node_47442db8_4e77_4598_b869_a01e3e71621f" does not exist
2019-05-20 04:17:30.636 CST [13644] FATAL:  could not start WAL streaming: ERROR:  replication slot "node_47442db8_4e77_4598_b869_a01e3e71621f" does not exist
2019-05-20 04:17:35.641 CST [13677] FATAL:  could not start WAL streaming: ERROR:  replication slot "node_47442db8_4e77_4598_b869_a01e3e71621f" does not exist
2019-05-20 04:17:40.646 CST [13705] FATAL:  could not start WAL streaming: ERROR:  replication slot "node_47442db8_4e77_4598_b869_a01e3e71621f" does not exist
2019-05-20 04:17:45.651 CST [13749] FATAL:  could not start WAL streaming: ERROR:  replication slot "node_47442db8_4e77_4598_b869_a01e3e71621f" does not exist
2019-05-20 04:17:50.656 CST [13756] FATAL:  could not start WAL streaming: ERROR:  replication slot "node_47442db8_4e77_4598_b869_a01e3e71621f" does not exist
2019-05-20 04:17:55.660 CST [13795] FATAL:  could not start WAL streaming: ERROR:  replication slot "node_47442db8_4e77_4598_b869_a01e3e71621f" does not exist
2019-05-20 04:18:00.665 CST [13801] FATAL:  could not start WAL streaming: ERROR:  replication slot "node_47442db8_4e77_4598_b869_a01e3e71621f" does not exist
2019-05-20 04:18:05.670 CST [13837] FATAL:  could not start WAL streaming: ERROR:  replication slot "node_47442db8_4e77_4598_b869_a01e3e71621f" does not exist

$ cat recovery.conf 
primary_slot_name = 'node_47442db8_4e77_4598_b869_a01e3e71621f'
standby_mode = 'on'
recovery_target_timeline = 'latest'
primary_conninfo = 'user=replicator password=rep-pass host=172.18.137.243 port=25432 sslmode=prefer sslcompression=1 application_name=node-47442db8-4e77-4598-b869-a01e3e71621f'

I try to stop patroni and pg process, clean pg_data directory, and start patroni. After a while pg process started. Replica streaming seems work. 
But something may be wrong.
1) path /service/pg-cluster/sync not exists in ZK
2) we set synchronous_mode as sync but show async in patroni.

Does patroni can seal this problem automatically?

Wish you feedbak, Thank you.

other infomation.
# patroni info
node1: patroni is down
node2: http://172.18.137.242:8008
{
	"database_system_identifier": "6691853177538966272",
	"postmaster_start_time": "2019-05-20 11:27:09.669 CST",
	"timeline": 110,
	"cluster_unlocked": false,
	"patroni": {
		"scope": "pg-cluster",
		"version": "1.5.1"
	},
	"state": "running",
	"role": "replica",
	"xlog": {
		"received_location": 1175098248,
		"replayed_timestamp": "2019-05-20 15:26:53.715 CST",
		"paused": false,
		"replayed_location": 1175098248
	},
	"server_version": 100006
}

node3: http://172.18.137.243:8008
{
	"database_system_identifier": "6691853177538966272",
	"postmaster_start_time": "2019-05-20 11:26:51.881 CST",
	"timeline": 110,
	"cluster_unlocked": false,
	"patroni": {
		"scope": "pg-cluster",
		"version": "1.5.1"
	},
	"replication": [{
		"sync_state": "async",
		"sync_priority": 0,
		"client_addr": "172.18.137.242",
		"state": "streaming",
		"application_name": "node-47442db8-4e77-4598-b869-a01e3e71621f",
		"usename": "replicator"
	}],
	"state": "running",
	"role": "master",
	"xlog": {
		"location": 1175118536
	},
	"server_version": 100006
}

# patroni.yml
node1-patroni.yml
scope: pg-cluster
name: node-7e7b9093-0127-4fde-a7b3-6135068d14b0

restapi:
  listen: 0.0.0.0:8008
  connect_address: 172.18.137.241:8008

zookeeper:
  hosts: ['127.0.0.1:2181'] 

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_standby_names: "*"
    postgresql:
      use_pg_rewind: true
      parameters:
        max_connections: "1000"

  
  initdb:  
    - auth-host: md5
    - auth-local: trust
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba:  
  - host replication replicator 172.18.137.241/16 md5
  - host all all 0.0.0.0/0 md5

postgresql:
  listen: 0.0.0.0:25432
  connect_address: 172.18.137.241:25432
  data_dir: /user/data/guard/node-data/postgresql/data
  bin_dir: /usr/lib/postgresql/10/bin
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: admin
  parameters:
    unix_socket_directories: '.'

node2-patroni.yml
scope: pg-cluster
name: node-47442db8-4e77-4598-b869-a01e3e71621f

restapi:
  listen: 0.0.0.0:8008
  connect_address: 172.18.137.242:8008

zookeeper:
  hosts: ['127.0.0.1:2181'] 

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_standby_names: "*"
    postgresql:
      use_pg_rewind: true
      parameters:
        max_connections: "1000"

  initdb: 
    - auth-host: md5
    - auth-local: trust
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba: 
  - host replication replicator 172.18.137.241/16 md5
  - host all all 0.0.0.0/0 md5

postgresql:
  listen: 0.0.0.0:25432
  connect_address: 172.18.137.242:25432
  data_dir: /user/data/guard/node-data/postgresql/data
  bin_dir: /usr/lib/postgresql/10/bin
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: admin
  parameters:
    unix_socket_directories: '.'

node3-patroni.yml
scope: pg-cluster
name: node-8e0c2af6-2499-4b64-bfd6-4986ab2b8dfb

restapi:
  listen: 0.0.0.0:8008
  connect_address: 172.18.137.243:8008

zookeeper:
  hosts: ['127.0.0.1:2181'] 

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_standby_names: "*"
    postgresql:
      use_pg_rewind: true
      parameters:
        max_connections: "1000"

  
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
    - auth-host: md5
    - auth-local: trust
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba:  
  - host replication replicator 172.18.137.241/16 md5
  - host all all 0.0.0.0/0 md5

postgresql:
  listen: 0.0.0.0:25432
  connect_address: 172.18.137.243:25432
  data_dir: /user/data/guard/node-data/postgresql/data
  bin_dir: /usr/lib/postgresql/10/bin
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: admin
  parameters:
    unix_socket_directories: '.'

**Comment by CyberDem0n** [comment]
> It seems patroni found a different database_system_identifier 6691855245413036253, why this happens and how to sovle the problem.

Patroni works with PGDATA is configured in the `postgresql.data_dir`. After restart it notices that system identifier doesn't match expectations.
If everything is configured correctly, that should not happen. You have to figure out why PGDATA was changed.

> pg on node2 is always in starting status and can not turn to work. here are pg logings:

The primary is responsible for creating of replication slot. If it doesn't create the slot that could only mean that it doesn't see the replica registered in zookeeper.

> I check zk in every node, data is consisttent.

Two above mentioned facts make me think that zookeeper state is inconsistent.

> zookeeper:
>  hosts: ['127.0.0.1:2181']

You have to specify ALL zookeeper nodes in the config! If for some reason one node is unavailable Patroni needs to switch to another node.
Having only local zookeeper node in the config is a SPoF.



>    path /service/pg-cluster/sync not exists in ZK
>    we set synchronous_mode as sync but show async in patroni.

If you change `bootstrap.dcs` section after cluster was initialized, that will not take an effect: https://patroni.readthedocs.io/en/latest/SETTINGS.html#bootstrap-configuration

**Comment by myeashion** [comment]
Thank you for you answer. 

> Patroni works with PGDATA is configured in the postgresql.data_dir

How to get the identifier in the the postgresql.data_dir or how to quickly find no matching? 

I need it for automatic testing. 

> Two above mentioned facts make me think that zookeeper state is inconsistent.

In my case, three zk instances turning from single to cluster

In addition, I found another problem, pg cant not start

```
2019-05-20 14:38:48.403 CST [1835] LOG:  listening on IPv4 address "0.0.0.0", port 25432
2019-05-20 14:38:48.410 CST [1835] LOG:  listening on Unix socket "./.s.PGSQL.25432"
2019-05-20 14:38:48.447 CST [1836] LOG:  database system was shut down in recovery at 2019-05-17 10:32:13 CST
2019-05-20 14:38:48.447 CST [1836] LOG:  entering standby mode
2019-05-20 14:38:48.447 CST [1836] LOG:  invalid resource manager ID in primary checkpoint record
2019-05-20 14:38:48.448 CST [1836] PANIC:  could not locate a valid checkpoint record
2019-05-20 14:38:48.448 CST [1835] LOG:  startup process (PID 1836) was terminated by signal 6: Aborted
2019-05-20 14:38:48.448 CST [1835] LOG:  aborting startup due to startup process failure
2019-05-20 14:38:48.455 CST [1835] LOG:  database system is shut down
```

We use "kill -9 pid" and  "reboot" command for failover test. I think it might be a rason.

I try to stop patroni, clean pg_data, and start patroni, then pg starts.

How can we avoid this problem, such as close patroni/pg gracefully. 

Can you give some advice, thank you very much.

**Comment by CyberDem0n** [comment]
> How to get the identifier in the the postgresql.data_dir or how to quickly find no matching?

pg_controldata

> In my case, three zk instances turning from single to cluster

Sorry, I am failing to decipher it.

> In addition, I found another problem, pg cant not start

It might be a consequence of a failed attempt to pg_rewind. 

> We use "kill -9 pid" and "reboot" command for failover test. I think it might be a rason.

The primary goal of Patroni is automatic failover and bootstrapping of new cluster nodes.
It also does its best to join the failed primary as a new replica. Unfortunately there is no 100% guaranty that such operation succeeds. This is more of a postgres limitation than Patroni.

**Comment by myeashion** [comment]
I'm so sorry to trouble you again.
My patroni.yml config bootstrap parameters as follows:

```
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_standby_names: "*"
    postgresql:
      use_pg_rewind: true
      parameters:
        max_connections: "1000"
```

but from patroni Leader, we found sync_sate is async, does not match patroni.yml config

```
{
	"database_system_identifier": "6690868012317218040",
	"postmaster_start_time": "2019-05-22 20:52:30.213 CST",
	"timeline": 25,
	"cluster_unlocked": false,
	"patroni": {
		"scope": "pg-cluster",
		"version": "1.5.1"
	},
	"replication": [{
		"sync_state": "async",
		"sync_priority": 0,
		"client_addr": "172.18.130.51",
		"state": "streaming",
		"application_name": "node-7cc25fec-e5d5-47d7-bc5c-04f1668b4639",
		"usename": "replicator"
	}],
	"state": "running",
	"role": "master",
	"xlog": {
		"location": 522247256
	},
	"server_version": 100006
}
```

use patronictl to show-config, can not find  synchronous_mode parameter, is it something wrong.

```
loop_wait: 10
postgresql:
  parameters:
    max_connections: '1000'
  use_pg_rewind: true
retry_timeout: 10
ttl: 30

```

and  path  /service/pg-cluster/sync not exists in ZK. 

Is it something wrong, and how to change from async mode to sync?

wish you feeback again, thanks a lot.

**Comment by CyberDem0n** [comment]
If you changed `bootstrap.dcs` after the cluster was initialized - that will not take any effect.
Instead you have to use `patronictl edit-config`.
