### ISSUE TITLE
Implement patronictl detach

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/patroni#107]
Currently, on exit Patroni tries to shut down the PostgreSQL database it manages. This makes sense generally (otherwise we won't be able to guarantee that the leftover database will keep its role), but on some occasions (i.e. upgrading Patroni itself) we might want to detach Patroni from the PostgreSQL cluster and keep the latter running.

**Comment by feikesteenbergen** [comment]
Perhaps we should allow Patroni upgrade to do this? Otherwise there's always `kill -9` ?

**Comment by kmoppel** [comment]
+1 . I would imagine this as a "patroni pause" command, that would keep patroni running but just not doing any actions.

**Comment by LappleApple** [comment]
@alexeyklyukin @CyberDem0n @feikesteenbergen Did you guys agree/decide to go with Feike's suggestion from April 21, or is more discussion needed?

**Comment by alexeyklyukin** [comment]
This is already implemented as a pause mode: http://patroni.readthedocs.io/en/latest/pause.html
