### ISSUE TITLE
How to integrate into configuration management tool?

### ISSUE THREAD

**Issue by whythisway** [zalando/patroni#1076]
As a PostgreSQL enthusiast I highly appreciate your efforts. Thank you so much for this nice piece of software.

Patroni has its focus on container technology. Well...

For developers and architects it might be unexpected that there are still IT operation admins where the databases are run on dedicated physical or virtualized hosts.
For developers and architects it might also be unexpected that there are still IT operation admins which use configuration management tools, e.g. Puppet or Ansible.

Patroni claims to exclusively manage the postgresql.conf file, which interferes with the common workflows of a traditional configuration management tool.
Patroni copies the initial/original postgresql.conf file to postgresql.base.conf.
The docs https://patroni.readthedocs.io/en/latest/dynamic_configuration.html say: "load parameters from file postgresql.base.conf" "leaves room for configuration tools that manage postgresql.conf directly without involving Patroni"
This behaviour unnecessarily complicates the intergration into existing configuration management.

Example of Puppet:
At my current employer we use Puppet with the official Puppetlabs module for PostgreSQL https://forge.puppet.com/puppetlabs/postgresql.
To configure PostgreSQL options the module provides the resource "postgresql::server::config_entry". The module expects to exclusively manage the postgresql.conf file. We already manage many PostgreSQL instances that way.

Question:
What is the most viable way to incorporate Patroni's possessive behaviour into Puppet managed PostgreSQL, when the official Puppet module for PostgreSQL is used?

**Comment by CyberDem0n** [comment]
You can specify `postgresql.custom_conf` in the patroni configuration and it will be included instead of postgresql.base.conf and actually, it is documented: https://patroni.readthedocs.io/en/latest/dynamic_configuration.html
