### ISSUE TITLE
Build psycopg2 from source, easy way!

### ISSUE THREAD

**Issue by psyhomb** [zalando/patroni#1077]
I have created simple build script for building a `psycopg2` python module from source inside of Docker container with statically linked `libpq`, it was primarily created for AWS lambda functions, but it can be used for any other project that requires `psycopg2` module.

Just suggestion to be added in the [README.rst](https://github.com/zalando/patroni/blob/master/README.rst#technical-requirementsinstallation) file as additional resource:
https://gitlab.com/psyhomb/aws-psycopg2

Cheers, and keep up the good work!

**Comment by CyberDem0n** [comment]
IMO it is better to stick with a "native" linux packages, python-psycopg2 or python3-psycopg2

**Comment by psyhomb** [comment]
> IMO it is better to stick with a "native" linux packages, python-psycopg2 or python3-psycopg2

@CyberDemOn could you please explain it to me how exactly you're going to achieve that in the lambda or any similar kind of environment where you do not have system access and you need statically linked `libpq`?

**Comment by CyberDem0n** [comment]
Do you  run Patroni and Postgres on such an environment?

**Comment by psyhomb** [comment]
I'm not running postgresql server but I'm running postgresql client, that's why I created this project in the first place, also this is the same reason why [psycopg2-binary](https://pypi.org/project/psycopg2-binary/) is created, the only difference is that psycopg2-binary isn't meant to be used in the production environments.

**Comment by psyhomb** [comment]
Also this was just a proposal to be used as alternative if you're running your code in these kind of envs or if you need the latest and greatest packages.

Anyhow thank you for your time and as far as I'm concerned you are free to close this one.

Cheers

**Comment by CyberDem0n** [comment]
Opening a similar issue in the psycopg2 repo (or maybe even opening a PR updating some docs there) would be more appropriate I believe.
