### ISSUE TITLE
patroni requires the psycopg2 even if the psycopg2-binary package is already installed

### ISSUE THREAD

**Issue by vitabaks** [zalando/patroni#1078]
CentOS Linux release 7.6.1810 (Core)

```
Collecting patroni
  Downloading https://files.pythonhosted.org/packages/bb/94/fe5b0c6af9df6e4add4c151e21564f038503c60af2d7cc09a3e10d4d3663/patroni-1.5.6-py3-none-any.whl (124kB)
     |████████████████████████████████| 133kB 770kB/s
Requirement already satisfied: PyYAML in /usr/local/lib64/python3.6/site-packages (from patroni) (5.1)
Collecting psycopg2>=2.5.4 (from patroni)
  Downloading https://files.pythonhosted.org/packages/23/7e/93c325482c328619870b6cd09370f6dbe1148283daca65115cd63642e60f/psycopg2-2.8.2.tar.gz (368kB)
     |████████████████████████████████| 368kB 2.3MB/s
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-u1ro4tzg/psycopg2/
```

pip3 list | grep psycopg2
`psycopg2-binary 2.8.2`

**Comment by vitabaks** [comment]
https://github.com/zalando/patroni#technical-requirementsinstallation

```
There are a few options available:

 1.   Use the package manager from your distro
 2.   Install psycopg2 from the binary package
 3.   Install psycopg2 from source
```
I was planning to use the method number 2

**Comment by psyhomb** [comment]
https://github.com/zalando/patroni/issues/1077#issue-451228220

**Comment by vitabaks** [comment]
> 
> 
> [#1077 (comment)](https://github.com/zalando/patroni/issues/1077#issue-451228220)

Thanks, but this is not exactly what I need.
I planned to use the binary package "psycopg2-binary"

**Comment by vitabaks** [comment]
http://initd.org/psycopg/docs/install.html#binary-install-from-pypi 

> Note
> 
> The psycopg2-binary package is meant for beginners to start playing with Python and PostgreSQL without the need to meet the build requirements.
> 
> If you are the maintainer of a publish package depending on psycopg2 you shouldn’t use ‘psycopg2-binary’ as a module dependency. For production use you are advised to use the source distribution.

...

> Warning
> 
> The psycopg2 wheel package comes packaged, among the others, with its own libssl binary. This may create conflicts with other extension modules binding with libssl as well, for instance with the Python ssl module: in some cases, under concurrency, the interaction between the two libraries may result in a segfault. In case of doubts you are advised to use a package built from source. 

**For production use you are advised to use the source distribution.**
You may want to remove from the Technical Requirements / Installation item number 2 "Install psycopg2 from the binary package"
