### ISSUE TITLE
patronictl show stopped

### ISSUE THREAD

**Issue by igortin** [zalando/patroni#1082]
Hi,

Can somebody help?
- Why it is stopped?
- How to start?
I just replace ips and used consul in postgres0.yml. 

[root@postgresql-01 forte]# /usr/bin/patronictl -c /tmp/postgres0.yml list
+---------+-------------+----------------+--------+---------+----+-----------+
| Cluster |    Member   |      Host      |  Role  |  State  | TL | Lag in MB |
+---------+-------------+----------------+--------+---------+----+-----------+
|  batman | postgresql0 | 10.x.x.x:5432 | Leader | stopped |    |   unknown |
|  batman | postgresql1 | 10.x.x.x:5433 |              | stopped |    |   unknown |
+---------+-------------+----------------+--------+---------+----+-----------+

**Comment by CyberDem0n** [comment]
The very first question you should ask yourself: "what is in logs?"

**Comment by uspen** [comment]
+
Some times (very rarely) i see 'start failed', but all works.
patronictl pause - resume fix

This issue appears after removing cluster from etcd (I restore to dev env from prod env)

**Comment by igortin** [comment]
patroni - version 1.5.6
The DCS - consul

- i checked failover, it is ok
- i checked logs, no errors 


logs from master:
Jun 07 15:19:28 postgresql-01 patroni[4729]: 2019-06-07 15:19:28,368 INFO: Lock owner: postgresql0; I am postgresql0
Jun 07 15:19:28 postgresql-01 patroni[4729]: 2019-06-07 15:19:28,413 INFO: no action.  i am the leader with the lock
Jun 07 15:19:38 postgresql-01 patroni[4729]: 2019-06-07 15:19:38,368 INFO: Lock owner: postgresql0; I am postgresql0
Jun 07 15:19:38 postgresql-01 patroni[4729]: 2019-06-07 15:19:38,438 INFO: no action.  i am the leader with the lock
Jun 07 15:19:48 postgresql-01 patroni[4729]: 2019-06-07 15:19:48,392 INFO: Lock owner: postgresql0; I am postgresql0
Jun 07 15:19:48 postgresql-01 patroni[4729]: 2019-06-07 15:19:48,493 INFO: no action.  i am the leader with the lock

logs from slave:
июн 07 15:20:26 postgresql-02 patroni[4730]: 2019-06-07 15:20:26,758 INFO: Lock owner: postgresql0; I am postgresql1
июн 07 15:20:26 postgresql-02 patroni[4730]: 2019-06-07 15:20:26,758 INFO: does not have lock
июн 07 15:20:26 postgresql-02 patroni[4730]: 2019-06-07 15:20:26,762 INFO: Local timeline=3 lsn=0/3CF5CA50
июн 07 15:20:26 postgresql-02 patroni[4730]: 2019-06-07 15:20:26,810 INFO: no action.  i am a secondary and i am following a leader

**Comment by bradnicholson** [comment]
Good timing, I've seen exactly the same thing for time to time and was going to start digging.

`patronctl cluster list` shows the Leader with the `State` start failed.  Patroni is fine.  The DB is up and running, it is correctly logging that it is the leader with the lock.

I suspect it is related to this the failed GET here right at startup time.  It's transient, the only time it appeared in the logs:

```
2018-10-09 17:59:26,993 INFO: establishing a new patroni connection to the postgres cluster
2018-10-09 17:59:26 UTC [56]: [1-1] user=[unknown],db=[unknown],client=127.0.0.1 LOG:  connection received: host=127.0.0.1 port=<PORT>
2018-10-09 17:59:26 UTC [56]: [2-1] user=postgres,db=postgres,client=127.0.0.1 LOG:  connection authorized: user=postgres database=postgres SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, compression=off)
2018-10-09 17:59:27,016 WARNING: request failed: GET http://<IP>:8008/patroni (HTTPConnectionPool(host='<IP>', port=8008): Max retries exceeded with url: /patroni (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f467c6f3518>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2018-10-09 17:59:27,122 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
2018-10-09 17:59:27,131 INFO: promoted self to leader by acquiring session lock
server promoting
```

**Comment by bradnicholson** [comment]
And `kill -3` to Patroni "fixes" it.

**Comment by igortin** [comment]
i fixed the problem.
Sorry, it was network problems.
Now it is ok.
Thanks for help.

**Comment by bradnicholson** [comment]
Should this be closed?  Seems like a bug in Patroni.  

A transient network error in the past, which does not interfere with Patroni startup should not show that startup failed later on.

**Comment by CyberDem0n** [comment]
@bradnicholson I can fix it if you describe in details how to reproduce it

**Comment by bradnicholson** [comment]
@CyberDem0n - I'll see if I can at some point.  I suspect it's a timing issue with transient DCS unavailability during startup.

**Comment by igortin** [comment]
today i found:
1) Cluster Patroni were started and shows states - stopped
2) Consul's patroni data was deleted without stop patroni.
3) Cluster recreate information in DCS with state running.
