### ISSUE TITLE
Question: using patroni.ctl as module

### ISSUE THREAD

**Issue by hatifnatt** [zalando/patroni#1083]
Hello.
I have plans to write SaltStack module for Patroni. It's required to update dynamic configuration directly form Salt. Without module it's only possible to do this in dirty (from Salt perspective) way with requests to API or by invoking `patronictl` from command line. Some 'dirt' can be cleaned by creating module  which will use API calls or run `patronictl` under the hood. But I think best way is to directly use `patroni.ctl` module, it contains all the necessary functions that only need to be wrapped for use with Salt.
First question: is it even possible to use `patroni.ctl` as module or it can only be used like command-line tool because of `click`?
If it's not possible to use `patroni.ctl` as module, I will fall back to other available methods.

Unfortunately I'm far from 'Python specialist'. I see that 'entry point' for `patronictl` is a [ctl](https://github.com/zalando/patroni/blob/master/patroni/ctl.py#L114) function, but I can't understand how it receive parameters. Looks like `click` pass them as context, but how that can be done when `patroni.ctl` imported as module?

I would be very appreciated for any advice which can help me to start moving in right direction.

**Comment by hatifnatt** [comment]
After more learning about `click` library it looks like it was not a best Idea to try to use `patroni.ctl` as a module. I think I will fall back to REST API. But any recommendations will be appreciated.

**Comment by CyberDem0n** [comment]
In most of the cases, patronictl simply calls the REST API.

Actually it is possible to "call" functions from patronictl with a little hack, which we already doing in the unit-tests. Fist you have to create the [runner](https://github.com/zalando/patroni/blob/master/tests/test_ctl.py#L45) and after that call [runner.invoke](https://github.com/zalando/patroni/blob/master/tests/test_ctl.py#L83). It is a bit hacky and not much different from calling patronictl directly.
