### ISSUE TITLE
What is the best valid method to update pg_hba on a running cluster?

### ISSUE THREAD

**Issue by ValeriyG** [zalando/patroni#1088]
I need to update pg_hba on a running cluster, but can't update it in usual way, pg_reload_conf() etc.
What is the best valid method to update pg_hba on a running cluster?

**Comment by CyberDem0n** [comment]
Please read [this](https://github.com/zalando/patroni/issues/953#issuecomment-458161117) comment.

**Comment by ValeriyG** [comment]
> Please read [this](https://github.com/zalando/patroni/issues/953#issuecomment-458161117) comment.

Thank you. 

I need move pg_hba to postgresql section and recreate the cluster, right?

**Comment by ValeriyG** [comment]
I have solved my problem.
I've updated section posgresql with pg_hba and executed pg_reload_conf().

It works. Thank you.
