### ISSUE TITLE
Exception when changing replication slots

### ISSUE THREAD

**Issue by sajal** [zalando/patroni#109]
Hi,

Just trying out patroni for the first time (after giving up on governor). I seem to have the replication working correctly, on my secondaries I see following error :-

    2015-12-10 21:04:19,823 ERROR: Exception when changing replication slots

Log snippet with stack trace: http://pastie.org/private/aup2rpvjfxsmgsjiwv9noa

Is that something to be worried about? Changes done on master are visible on the secondaries.

-Sajal

**Comment by sajal** [comment]
My bad. Turns out I was supposed to put all the servers as "trust" in pg_hba setting..

**Comment by sajal** [comment]
Putting all the servers as "trust" in pg_hba setting fixes the issue shot term, but I think thats not nice.

http://paste.ubuntu.com/13923118/  my config file for the test cluster. Other nodes have same config except for the IPs replaced and name changed. Adding Line 59 makes the problem go away.

Using postgres 9.4.5 and patroni master.

**Comment by alexeyklyukin** [comment]
Patroni expects to connect to the address/port PostgreSQL listens to (the server listen_addresses, configured via the "postgresql" section "listen" parameter) and postgres database without the password. Basically, if you running patroni on the same host as PostgreSQL itself, you can add 127.0.0.1 as the first address in the list of listen addresses (i.e. "127.0.0.1,1.2.3.4.5:5432") (or set it to *), and only enable trust  for 127.0.0.1 connections.

Unfortunately, it looks like we don't support Patroni talking to PostgreSQL via a local socket connection ATM, but this is something we are willing to fix in the future.
