### ISSUE TITLE
How to promote a Patroni standby cluster

### ISSUE THREAD

**Issue by Wolfsrudel** [zalando/patroni#1096]
Theoretical question: is it possible - and if, how - to promote a Patroni standby cluster?

The idea is to migrate all not-Patroni clusters in Patroni clusters by first replicating from the actual host/ cluster into a Patroni standby cluster and when everything is set up the right way - and tested - promote the standby cluster to be the "active" one.

I haven't found anything in the documentation about promoting a standby cluster - or if it's even implemented yet. :)

**Comment by CyberDem0n** [comment]
The easiest way:
1. run `patronictl edit-config`
2. remove the `standby_cluster` section from the config
3. Save and exit from the editor
4. review the config change and agree to apply it.

thats it

**Comment by Wolfsrudel** [comment]
Oh, ok, that easy. Thanks a lot. :)

**Comment by rangapraveen0414-max** [comment]
Hi Team, 
why should i create replication slot explictly in primary cluster to set up the standby cluster configuration, why can't it use its own hostname based replication slots b/w primary & standby cluster. 

 standby_cluster:
      host: Pr_node1,Pr_node2,Pr_node3
      port: 5432
      primary_slot_name: rep_dr
      create_replica_methods:
        - basebackup

      basebackup:
        host: Loadbalancer(VIP_primary)
        port: 5432
