### ISSUE TITLE
patroni-etcd fails to recover

### ISSUE THREAD

**Issue by smirnov-mi** [zalando/patroni#1097]
Hi guys. I'm running patroni with postgres9.6(1 master + 2 slaves) with it's own etcd (3 containers) on a k8s cluster (3 worker nodes). After killing one node, containers are restarting, and the postgres one is successfully rejoining it's cluster, but the patroni-etcd container is not able to re-join it's etcd-cluster. The name/IP of the newly created container can not be resolved by the k8s-dns service. 
 
I have the same error on k8s v.1.9.6, 1.13.4 and 1.14.3

I use helm charts and I managed to start Postgres9.6 and Postgres10, both have the same issue. 
Components versions:
PG9.6: patroni 1.3-p4; spilo-9.6 image; k8s.gcr.io/etcd-amd64 2.2.5 (chart v 0.3.7)
PG10:_ patroni 1.4-p7; spilo-10 image; k8s.gcr.io/etcd-amd64 2.2.5

All this is working on persistent storage devices, which seem to work.
 
I'm new to pretty much every technology here and I'm sorry if I mixed things up.
Trying to get it working (and failover resistent). See log of the remaining living etcd container, that can't find it's neighbour attached.
 
 
[20190618_patroni-etcd-rejoin-error.txt](https://github.com/zalando/patroni/files/3320724/20190618_patroni-etcd-rejoin-error.txt)

**Comment by smirnov-mi** [comment]
I tried various versions of etcd and finally found one that survives fail-over:    3.2.18

**Comment by CyberDem0n** [comment]
Despite the pod name `patroni-etcd`, this is just the name and has nothing to do with Patroni. It is provided by some other helm-chart.

You are also using very old Spilo image. The latest one can be found here: https://github.com/zalando/spilo/releases

Spilo-11 contains all postgres versions starting from 9.3 to 11.
By default it starts the latest postgres. It is possible to pick the version you need by providing `PGVERSION` environment variable (but I am unsure is the helm-chart can do it out of the box).

**Comment by smirnov-mi** [comment]
yes, this is not a patroni issue. I just thought someone here might have seen such behaviour before. I broke my patroni-etcd cluster again, having 2 out of 3 nodes down. It wasn't able to recover itself. As a workaround I removed the ReplicaSet and recreated it again. 
I will try to setup Spilo-11 image also for 9.6. Thanks for this hint.
