### ISSUE TITLE
new etcd cluster

### ISSUE THREAD

**Issue by wolfgangbrandl** [zalando/patroni#1101]
We have several postgres clusters. All cluster are configured in the was that ther a three servers and on all three etcd is installed and on two patroni with postgres.

We want to build up a central etcd cluster for all our postgres clusters.

How can i change the etcd configuration not even in the patroni.yml in that way that i am not loosing the data because patroni  makes in the background pg_ctl initdb ?
Thanks

**Comment by CyberDem0n** [comment]
It is very simple:
1. Disable auto failover: `patronictl pause --wait`
2. Stop Patroni on all nodes (in pause mode postgres will continue to run)
3. Update patroni.yaml on all nodes (change etcd configuration)
4. Start Patroni on all nodes
5. Check Patroni logs
6. If logs are fine, enable auto failover: `patronictl resume`

This is the migration plan for one patroni clister. You have to repeat it for all clusters you want to migrate.
Important! The `scope` must be different in every cluster you are migrating!
