### ISSUE TITLE
if Etcd password only number we get error

### ISSUE THREAD

**Issue by necipakca** [zalando/patroni#1102]
I think little cast issue there.

Jul 08 15:44:33 pg1 patroni[42483]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 129, in machines
Jul 08 15:44:33 pg1 patroni[42483]: kwargs = self._build_request_parameters()
Jul 08 15:44:33 pg1 patroni[42483]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 98, in _build_request_parameters
Jul 08 15:44:33 pg1 patroni[42483]: kwargs = {'headers': self._get_headers(), 'redirect': self.allow_redirect}
Jul 08 15:44:33 pg1 patroni[42483]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 991, in _get_headers
Jul 08 15:44:33 pg1 patroni[42483]: credentials = ':'.join((self.username, self.password))
Jul 08 15:44:33 pg1 patroni[42483]: TypeError: sequence item 1: expected string, int found

**Comment by CyberDem0n** [comment]
Hi,

You have to quote the password in the yaml.

P.S. Using only numbers for the password is a terrible idea.
