### ISSUE TITLE
Problem getting 2nd Patroni to bootstrap from 1st Patroni - dockers on different physical hosts

### ISSUE THREAD

**Issue by alonspiegel** [zalando/patroni#1103]
Our topology is composed this way:
We are planning to install on 3 physical hosts. Each host is running 3 docker containers:
1. haproxy
2. patroni/postgres
3. etcd 

We are having a problem running a 2nd node.

We have managed to bootstrap a stack on the 1st node.
This is the `docker-compose.yml` file:
```
# docker compose file for running a 3-node PostgreSQL cluster
# with 3-node etcd cluster as the DCS and one haproxy node
version: "2"

networks:
    mynet:

services:
    etcd1:
        image: patroni
        networks: [ mynet ]
        env_file: docker/etcd.env
        container_name: etcd1
        hostname: etcd1
        ports:
           - '2379:2379'
           - '2380:2380'
        command: etcd -name etcd1 -initial-advertise-peer-urls http://<physical_host_ip>:2380

    patroni1:
        image: patroni
        networks: [ mynet ]
        env_file: docker/patroni.env
        hostname: patroni1
        container_name: patroni
        environment:
            PATRONI_NAME: patroni
        ports:
            - "5432:5432"

    haproxy:
        image: patroni
        networks: [ mynet ]
        env_file: docker/patroni.env
        hostname: haproxy1
        container_name: haproxy
        ports:
            - "5000:5000"
            - "5001:5001"
        command: haproxy
```

On a 2nd physical host, using the same `docker-compose.yml` (hostnames are changed from 1 to 2 respectively) - we have managed to start-up a 2nd stack. The etcd cluster is running well with two members (leader and non-leader) - we manually added an etcd member using `etcdctl member add`. 
Our problem is that Patroni on the 2nd physical host tries to communicate with the postgres on the 1st physical host (pg_basebackup) using the 1st container's ip address. Because the 2nd physical host does not recognize the 1st's container's ip (it may even have the same ip as it is on a different physical host). So the pg_basebackup fails and so the cluster creation fails.

I wonder how can I instruct Patroni on the 2nd physical host to communicate with services on the 1st physical host using 1st physical's ip (not the ip managed by docker)

**Comment by CyberDem0n** [comment]
It seems that you are trying to use the demo docker image for production. In the container the patroni config is autogenerated.

Patroni itself is quite flexible, nodes are using values from `restapi.connect_address` and `postgresql.connect_address` to advertise themselves. Basically you have to fix patroni config files and put node ip address into aforementioned parameters.
