### ISSUE TITLE
How can a patroni process be stopped without affecting the cluster?

### ISSUE THREAD

**Issue by preet** [zalando/patroni#1117]
Is it possible to stop or restart patroni on a cluster node without any other changes to the cluster? I see patronictl provides a 'pause' option. Would the sequence 'patronictl pause; systemctl restart patroni; patroni resume' work without any adverse effects?

**Comment by CyberDem0n** [comment]
Yes, `patronictl pause --wait` will do exactly what you want.

**Comment by preet** [comment]
Thanks for the reply. Tangentially related follow up: I'm already using a DCS (ZK) to elect a master in a cluster. I'd like to just tell Patroni the new master. What is the right procedure for this? I think I can use `patronictl pause` and then `patronictl switchover <replica>` whenever I am notified that a new master was elected. Are there any important caveats with this? I can leave auto failover enabled and issue the switchover after but I guess that would create unnecessary thrash.

**Comment by CyberDem0n** [comment]
You can use (and it actually better to do so)  switchover without pausing the auto-failover.

**Comment by KaremSalhi** [comment]
hello,

how can Patroni or ETCD know a node is stopping ?
