### ISSUE TITLE
replication not working if patroni stop

### ISSUE THREAD

**Issue by Tekchanddagar** [zalando/patroni#1123]
Hello Team,

Please go through below points. Which have my scenario and please help me:
1. Before using patroni we have master-slave replication in our environment and it was working fine. But don't have automatic failover.
2. To achieve automatic failover we have started using patroni and its also working fine.

But now we are performing one test case i.e

We are assuming that if someday patroni stopped working or something goes wrong with etcd or haproxy. Then we will stop using patroni untill the problem will be fixed and switch back to our old master-slave configuration.

Now when we stopped patroni manually and start the postgresql service over master and slave manually then service is started but both the machine started working as independent or we can say replication is not working now. But before using patroni replication was working properly.

Can you please help me to fix this issue or help me to find out the cause of this issue.

Note:- We use existing data directory in patroni so the databases have latest data untill patroni was working.

Thanks.

**Comment by CyberDem0n** [comment]
It will not automagically work.
You probably will have to reconfigure the recovery.conf on the replica and make sure that the primary is really running not int recovery.
