### ISSUE TITLE
Patroni cannot connect to one of the cluster nodes etcd

### ISSUE THREAD

**Issue by 1QVAS1** [zalando/patroni#1124]
I created a cluster of two DBMS PostgreSQl, two Patroni and a cluster etcd (in the amount of three). I have the following configuration:
1.192.168.2.1 (postgreSQL, Patroni, etcd)
2. 192.168.2.2 (postgreSQL, Patroni, etcd)
3. 192.168.2.3 (etcd)

I emit the fall of two nodes of the cluster etc and get this error from Patroni:
> 2019-07-31 10:26:18,159 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='xxx.xx.x.xx', port=2379): Read timed out. (read timeout=1.6666666666666667)",)': /v2/keys/service/test_cluster/leader
> 2019-07-31 10:26:19,830 ERROR: Request to server http://xxx.xx.x.xx:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'xxx.xx.x.xx\', port=2379): Max retries exceeded with url: /v2/keys/service/test_cluster/leader (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'xxx.xx.x.xx\', port=2379): Read timed out. (read timeout=1.6666666666666667)",))',)
> 2019-07-31 10:26:19,830 INFO: Reconnection allowed, looking for another server.
> 2019-07-31 10:26:19,830 INFO: Selected new etcd server http://xxx.xx.x.xx:2379
> 2019-07-31 10:26:19,831 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabc935c588>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v2/keys/service/test_cluster/leader
> 2019-07-31 10:26:19,832 ERROR: Request to server http://xxx.xx.x.xx:2379 failed: MaxRetryError("HTTPConnectionPool(host='xxx.xx.x.xx', port=2379): Max retries exceeded with url: /v2/keys/service/test_cluster/leader (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabc935c978>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
> 2019-07-31 10:26:19,832 INFO: Reconnection allowed, looking for another server.
> 2019-07-31 10:26:19,832 INFO: Selected new etcd server http://xxx.xx.x.xx:2379
> 2019-07-31 10:26:19,832 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabc92fc400>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v2/keys/service/test_cluster/leader
> 2019-07-31 10:26:19,833 ERROR: Request to server http://xxx.xx.x.xx:2379 failed: MaxRetryError("HTTPConnectionPool(host='xxx.xx.x.xx', port=2379): Max retries exceeded with url: /v2/keys/service/test_cluster/leader (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabc92fce80>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
> 2019-07-31 10:26:19,833 INFO: Reconnection allowed, looking for another server.
> 2019-07-31 10:26:19,833 ERROR: Machines cache is empty, no machines to try.
> 2019-07-31 10:26:19,833 ERROR:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
>     (self.host, self.port), self.timeout, **extra_kw)
>   File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/etcd.py", line 426, in create_connection_patched
>     raise err
>   File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/etcd.py", line 416, in create_connection_patched
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/usr/lib/python3.6/http/client.py", line 1239, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
>     self.send(msg)
>   File "/usr/lib/python3.6/http/client.py", line 964, in send
>     self.connect()
>   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 166, in connect
>     conn = self._new_conn()
>   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 150, in _new_conn
>     self, "Failed to establish a new connection: %s" % e)
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fabc92fce80>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/etcd.py", line 164, in _do_http_request
>     response = request_executor(method, url, fields=fields, **kwargs)
>   File "/usr/lib/python3/dist-packages/urllib3/request.py", line 148, in request_encode_body
>     return self.urlopen(method, url, **extra_kw)
>   File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 321, in urlopen
>     response = conn.urlopen(method, u.request_uri, **kw)
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 668, in urlopen
>     **response_kw)
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 388, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='xxx.xx.x.xx', port=2379): Max retries exceeded with url: /v2/keys/service/test_cluster/leader (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabc92fce80>: Failed to establish a new connection: [Errno 111] Connection refused',))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/etcd/client.py", line 828, in _next_server
>     mach = self._machines_cache.pop()
> IndexError: pop from empty list
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/etcd.py", line 348, in wrapper
>     retval = func(self, *args, **kwargs) is not None
>   File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/etcd.py", line 547, in _update_leader
>     return self.retry(self._client.test_and_set, self.leader_path, self._name, self._name, self._ttl)
>   File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/etcd.py", line 332, in retry
>     return self._retry.copy()(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/patroni/utils.py", line 254, in __call__
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/etcd/client.py", line 703, in test_and_set
>     return self.write(key, value, prevValue=prev_value, ttl=ttl)
>   File "/usr/local/lib/python3.6/dist-packages/etcd/client.py", line 500, in write
>     response = self.api_execute(path, method, params=params)
>   File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/etcd.py", line 209, in api_execute
>     response = self._do_http_request(request_executor, method, self._base_uri + path, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/etcd.py", line 174, in _do_http_request
>     self._base_uri = self._next_server(cause=e)
>   File "/usr/local/lib/python3.6/dist-packages/etcd/client.py", line 832, in _next_server
>     cause=cause)
> etcd.EtcdConnectionFailed: No more machines in the cluster
> 2019-07-31 10:26:19,834 ERROR: failed to update leader lock
> 2019-07-31 10:26:19.847 UTC [13910] LOG:  received immediate shutdown request
> 2019-07-31 10:26:19.850 UTC [13920] WARNING:  terminating connection because of crash of another server process
> 2019-07-31 10:26:19.850 UTC [13920] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
> 2019-07-31 10:26:19.850 UTC [13920] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
> 2019-07-31 10:26:19.851 UTC [13946] WARNING:  terminating connection because of crash of another server process
> 2019-07-31 10:26:19.851 UTC [13946] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
> 2019-07-31 10:26:19.851 UTC [13946] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
> 2019-07-31 10:26:19.851 UTC [13921] WARNING:  terminating connection because of crash of another server process
> 2019-07-31 10:26:19.851 UTC [13921] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
> 2019-07-31 10:26:19.851 UTC [13921] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
> 2019-07-31 10:26:19.856 UTC [13910] LOG:  database system is shut down
> 2019-07-31 10:26:19,861 INFO: Selected new etcd server http://xxx.xx.x.xx:2379
> 2019-07-31 10:26:21,536 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='xxx.xx.x.xx', port=2379): Read timed out. (read timeout=1.6666666666666667)",)': /v2/keys/service/test_cluster/members/post-01
> 2019-07-31 10:26:23,206 ERROR: Request to server http://xxx.xx.x.xx:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'xxx.xx.x.xx\', port=2379): Max retries exceeded with url: /v2/keys/service/test_cluster/members/post-01 (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'xxx.xx.x.xx\', port=2379): Read timed out. (read timeout=1.6666666666666667)",))',)
> 2019-07-31 10:26:23,206 INFO: Reconnection allowed, looking for another server.
> 2019-07-31 10:26:23,206 INFO: Selected new etcd server http://xxx.xx.x.xx:2379
> 2019-07-31 10:26:23,207 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabc92fc0b8>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v2/keys/service/test_cluster/members/post-01
> 2019-07-31 10:26:23,207 ERROR: Request to server http://xxx.xx.x.xx:2379 failed: MaxRetryError("HTTPConnectionPool(host='xxx.xx.x.xx', port=2379): Max retries exceeded with url: /v2/keys/service/test_cluster/members/post-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabc92fc320>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
> 2019-07-31 10:26:23,207 INFO: Reconnection allowed, looking for another server.
> 2019-07-31 10:26:23,207 INFO: Selected new etcd server http://xxx.xx.x.xx:2379
> 2019-07-31 10:26:23,208 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabc92fc208>: Failed to establish a new connection: [Errno 111] Connection refused',)': /v2/keys/service/test_cluster/members/post-01
> 2019-07-31 10:26:23,208 ERROR: Request to server http://xxx.xx.x.xx:2379 failed: MaxRetryError("HTTPConnectionPool(host='xxx.xx.x.xx', port=2379): Max retries exceeded with url: /v2/keys/service/test_cluster/members/post-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fabc92fc9b0>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
> 2019-07-31 10:26:23,208 INFO: Reconnection allowed, looking for another server.
> 2019-07-31 10:26:23,208 ERROR: Machines cache is empty, no machines to try.
> 2019-07-31 10:26:23,209 ERROR:
> Traceback (most recent call last):
>

The situation does not depend on which cluster node etcd remains operational. The error repeats.

**Comment by CyberDem0n** [comment]
Etcd is a quorum based system.
The quorum of 3 is 2. If more than one node is not available you are losing the quorum. As a result Patroni can't determine its state and restarting postgres in read-only mode.

**Comment by 1QVAS1** [comment]
@CyberDem0n 
Thanks for the answer
