### ISSUE TITLE
replication issue after stoping patroni service

### ISSUE THREAD

**Issue by Tekchanddagar** [zalando/patroni#1125]
Hello Team,

I have setup patroni cluster and it was working fine. Then i stopped the patroni service manually over my both postgresql+patroni machine i.e postgresql01 and postgresql02 using the below command:
```
$ systemctl stop patroni.service
```
Then i start patroni service after some time. But over one machine its showing below error and replication is not working:

```
Jul 31 16:46:01 slave1 patroni[4871]: 2019-07-31 16:46:01,186 INFO: Lock owner: master1; I am slave1
Jul 31 16:46:01 slave1 patroni[4871]: 2019-07-31 16:46:01,190 INFO: does not have lock
Jul 31 16:46:01 slave1 patroni[4871]: 2019-07-31 16:46:01,207 INFO: no action.  i am a secondary and i am following a leader
Jul 31 16:46:04 slave1 patroni[4871]: LOG:  started streaming WAL from primary at 0/5000000 on timeline 7
Jul 31 16:46:04 slave1 patroni[4871]: FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 000000070000000000000005 has already been removed
```
Can you please help me.

Thanks.

**Comment by CyberDem0n** [comment]
Please use [search](https://github.com/zalando/patroni/issues?q=is%3Aissue+could+not+receive+data+from+WAL+stream%3A+ERROR%3A++requested+WAL+segment+is%3Aclosed)

**Comment by Tekchanddagar** [comment]
Heloo @CyberDem0n ,

Thank you for your response. I am unable to see the status of my cluster using below command:

```
patronictl -d etcd://192.168.56.7:2379 list abcdefg
```
Its showing blank table format. But my cluster is running.

Thanks.

**Comment by CyberDem0n** [comment]
`patronictl -c patroni.yaml list`

**Comment by Tekchanddagar** [comment]
@CyberDem0n ,

Thanks a lot for helping and take a bow.

I have one more question for you. My one node was goes down and came up after 2 days and now its lag with 16 GB from master. Currently i have fixed the issue by `reinit` and its working fine.

But i don't want to do it manually every time. So i increase the value of `wal_keep_segments` in `patroni.yml` file and restart the patroni service using the below command:

```
$ systemctl restart patroni.service
```
But its seems that the newly change configuration is not applied. If i am thinking in right way that once cluster is initialised first time by starting patroni service then we can't make changes in `patroni.yml` file. So how we can make changes if any change is required and how we can apply them.

Thanks.

**Comment by CyberDem0n** [comment]
> So how we can make changes if any change is required and how we can apply them.

`export EDITOR=vim` or any other your favorite editor.

**Comment by CyberDem0n** [comment]
Also I would recommend you to go through tutorial: https://www.pgcon.org/2019/schedule/events/1307.en.html

**Comment by Tekchanddagar** [comment]
@CyberDem0n ,

Thanks once again for your helping hands.
Just i got the answer of my question.

One more question or may be final, if we make any changes using `edit-config` it will be at node level or cluster level? Means we need to make these changes on each node or it will be at cluster level and reflect automatically on all nodes?

After making these changes we need to `reload` or it will applied automatically?

Thanks.

**Comment by CyberDem0n** [comment]
`edit-config` does cluster level changes. Depending on parameters you changed restart of postgres might be required (patronictl restart). More info [here](https://patroni.readthedocs.io/en/latest/dynamic_configuration.html)

> I will read the tutorial.

please do, it'll answer most of your questions

**Comment by Tekchanddagar** [comment]
@CyberDem0n ,

This tutorial have this [PDF](https://www.pgcon.org/2019/schedule/attachments/515_Patroni-training.pdf) file.

Or i am missing something?

Thanks.
