### ISSUE TITLE
Using an HA replica for read-only queries

### ISSUE THREAD

**Issue by michailbrynard** [zalando/patroni#1126]
I'm running Patroni using a Kubernetes endpoint as the DCS. 

I'm tempted to use the Patroni replicas for read-only analytics queries. Is there a chance that this would cause issues during failover?

I.e. if I set up a Kubernetes Service with a selector "spilo-role=replica" and route read-only queries to it, is there a chance that the failover process might be interrupted if it occurs while a query is being run on a replica?

**Comment by CyberDem0n** [comment]
Replica service will not affect failover process unless replicas are not significantly lagging behind the primary due to some heavy load.

**Comment by michailbrynard** [comment]
Thanks!
