### ISSUE TITLE
OK Status code for GET /replica, when replica is in recovery

### ISSUE THREAD

**Issue by jpuris** [zalando/patroni#1128]
Patroni version 1.5.6

**Problem**
`GET /replica` returns status code 200, when replica (hot standby) is not ready to accept connections.
API call returns
```json
{
  "state": "starting",
  "database_system_identifier": "<redacted>",
  "role": "replica",
  "patroni": {
    "scope": "<redacted>",
    "version": "1.5.6"
  }
}
```
This is misleading for out use case, as we rely on status code 200 for this API call, to determine, if replica is up and running, for us to potentially send reads to it.

**Steps to reproduce**
- Have an offline replica that has a lot of replication lag
- Have this replica use WAL archive to recover

Start replica, which is going to be in postgresql recovery state.

Expected behaviour - `GET /replica` returns status code 503

Actual behaviour - `GET /replica` returns status code 200

**Comment by CyberDem0n** [comment]
Yes, this is the known [problem](https://github.com/zalando/patroni/issues/772) and it should not be hard to fix it. Pull requests are always welcomed!

**Comment by anikin-aa** [comment]
Guys, am I correct, that 200 status code should be return only, when `state` == `running` ?

**Comment by CyberDem0n** [comment]
@anikin-aa, yes

**Comment by jpuris** [comment]
Thank you very much, everyone involved! :)
