### ISSUE TITLE
Consul ACL policy for Patroni

### ISSUE THREAD

**Issue by Wolfsrudel** [zalando/patroni#1129]
I've enabled Consul ACL and having some "not-so-nice" error messages in the logfile of consul:
```
Aug 01 16:20:04 patroni001-twolf-test consul[2565]:     2019/08/01 16:20:04 [ERR] http: Request GET /v1/kv/service/pg-cluster/leader?consistent=&index=403382&wait=1000ms, error: Permission denied from=127.0.0.1:40904
```
The policy i'm using is this one:
```
{
  "key_prefix": {
    "vault/": {
      "policy": "write"
    }
  },
  "key_prefix": {
    "service/": {
      "policy": "write"
    }
  },
  "node_prefix": {
    "": {
      "policy": "write"
    }
  },
  "service": {
    "vault": {
      "policy": "write"
    }
  },
  "agent_prefix": {
    "": {
      "policy": "write"
    }

  },
  "session_prefix": {
    "": {
      "policy": "write"
    }
  }
}
```
patroni.yaml
```
consul:
  [...]
  token: "<my-token>"
  [...]
```

Am i missing something, because everything under the key "service" should be available to Patroni.
 Can somebody help out with this?

**Comment by CyberDem0n** [comment]
Hi @Wolfsrudel,

I am afraid you will have to investigate why Consul denies requests on your own.

**Comment by Wolfsrudel** [comment]
I already thought so. Ticket is open. Should I document this here? If not, I also like to close the request.

**Comment by Wolfsrudel** [comment]
For those who are interested: https://discuss.hashicorp.com/t/consul-acl-policy-not-working-as-expected/2233
Something in my system isn't using the ACL token, but the default instead.

Closing this issue.

**Comment by chobostar** [comment]
I met the same issue, after adding Consul token on existing Patroni v1.5.6 setup. It was resolved by restarting Patroni service (reload doesn't help on 1.5.6, fixed only here - https://github.com/zalando/patroni/blob/master/docs/releases.rst#version-160)

**Comment by pySilver** [comment]
@Wolfsrudel you are using totally wrong policy.

See this guide first about how to integrate Vault with Consul: https://www.vaultproject.io/docs/secrets/consul

Then implement proper policy *at Consul*:

```
service_prefix "" {
   policy = "write"
}

session_prefix "" {
  policy = "write"
}

key_prefix "" {
  policy = "write"
}

node_prefix "" {
  policy = "read"
}

agent_prefix "" {
  policy = "read"
}
```

This policy is too permissive, but it should work for start.
