### ISSUE TITLE
Add 'list' method to API

### ISSUE THREAD

**Issue by hatifnatt** [zalando/patroni#1133]
Currently Patroni cluster can be mostly managed via API, almost all commands from `patronictl` is available. Although not of them documented. But I'm really missing `list` command.  It would be great if it will be implemented in foreseeable future.

I.e. for restart cluster nodes in correct order after changing `max_connections` PostgreSQL option, I need to get all nodes and then restart master first an then slaves or vice versa depending on increasing or decreasing the `max_connections` value.

Currently direct DCS (consul in my case) request can be used as workaround, but due different DCS supported by Patroni it is not versatile and pretty hard to support, while Patroni already have all required code.

**Comment by CyberDem0n** [comment]
Hi @hatifnatt,

feel free to contribute it.
