### ISSUE TITLE
Cannot use compose.io managed etcd

### ISSUE THREAD

**Issue by vchatterji** [zalando/patroni#1135]
I am trying to use compose.io managed etcd with Patroni.

**Configuration:**
2 HA Proxy nodes
3 etcd nodes

**Steps to Reproduce:**
1. Sign up for compose.io account (free for 30 days)
2. Create a etcd deployment
3. Use the deployment connection string as `proxy` key under `etcd`
```
etcd:
    proxy: https://[username]:[password]@xxxxx-etcd-yyyyyy.nnnnnnnn.composedb.com:nnnnnn
```
The above is the URL to one of the HA Proxy nodes in the etcd deployment created in compose

**Current Behaviour:**
A 404 response is returned.

**Expected Behaviour:**
This should work?

**Comment by CyberDem0n** [comment]
> Current Behaviour:
> A 404 response is returned.

I would recommend you to enable `DEBUG` [logs](https://github.com/zalando/patroni/blob/master/docs/SETTINGS.rst#log) in order to check what requests are executed.

> Expected Behaviour:
> This should work?

Well, I don't see a reason why it should not. IMO it is a matter of providing the correct configuration.

P.S. maybe @bradnicholson knows more details?

**Comment by vchatterji** [comment]
I opened an issue with compose.io as well. Here are the logs with debug turned on. It does seem like the /v2/members url returns a 404. I think it is a issue with compose:
```
etcdctl --endpoints=https://xxxxxxx-n.xxx-etcd-xxxxxxxxx.nnnnnnnnn.composedb.com:nnnnnn,https://yyyyyyyy-n.yyy-yyy-yyyyyyy.nnnnnnnnn.composedb.com:nnnnnn --username=root:xxxxxxxxxx --debug member list
start to sync cluster using endpoints(https://xxxxxxx-n.xxx-etcd-xxxxxxxxx.nnnnnnnnn.composedb.com:nnnnnn,https://yyyyyyyy-n.yyy-yyy-yyyyyyy.nnnnnnnnn.composedb.com:nnnnnn)
cURL Command: curl -X GET https://xxxxxxx-n.xxx-etcd-xxxxxxxxx.nnnnnnnnn.composedb.com:nnnnnn/v2/members
got endpoints(https://xxxxxxx-n.xxx-etcd-xxxxxxxxx.nnnnnnnnn.composedb.com:nnnnnn,https://yyyyyyyy-n.yyy-yyy-yyyyyyy.nnnnnnnnn.composedb.com:nnnnnn) after sync
Cluster-Endpoints: https://xxxxxxx-n.xxx-etcd-xxxxxxxxx.nnnnnnnnn.composedb.com:nnnnnn,https://yyyyyyyy-n.yyy-yyy-yyyyyyy.nnnnnnnnn.composedb.com:nnnnnn
cURL Command: curl -X GET https://xxxxxxx-n.xxx-etcd-xxxxxxxxx.nnnnnnnnn.composedb.com:nnnnnn/v2/members
unexpected status code 404
```
