### ISSUE TITLE
Is it possible to configure the system so that patroni starts automatically after a server reboot?

### ISSUE THREAD

**Issue by 1QVAS1** [zalando/patroni#1140]
Hi!
I run patroni as a daemon: `sudo systemctl start patroni`.
I would like to know if it is possible to configure the system so that when the server restarts, patroni starts automatically?
I tried to execute `sudo systemctl enable patroni.service` but got an error:
`Failed to enable unit: Invalid argument`

**Comment by jpuris** [comment]
Something is misconfigured in `patroni.service` file.
You can see it with `systemctl cat patroni`

Take a look at https://github.com/zalando/patroni/blob/master/extras/startup-scripts/patroni.service

When you have fixed the error, `sudo systemctl enable patroni` should make it start at boot.

**Comment by 1QVAS1** [comment]
@jpuris 
My patroni.service:
[Unit]
Description=Runners to orchestrate a high-availability PostgreSQL
After=syslog.target network.target

```
[Service]
Type=simple

User=postgres
Group=postgres

ExecStart=/usr/local/bin/patroni /opt/patroni/patroni.yml

KillMode=process

TimeoutSec=30

Restart=no

[Install]
WantedBy=multi-user.targ
```
I tried to use all the lines from the link you provided, but got the same result.

**Comment by jpuris** [comment]
`WantedBy=multi-user.targ` should be `WantedBy=multi-user.target`

**Comment by 1QVAS1** [comment]
Thank you very much for the help!

**Comment by DavidBaezDbz** [comment]
Thanks
