### ISSUE TITLE
How to get name of current master via patronictl?

### ISSUE THREAD

**Issue by twelfthdoctor** [zalando/patroni#1141]
How can I get name of current master in a cluster? I don't want to use **patronictl list** as I want to get exactly name of current master and nothing else. List command will show me a table where I can see all members of my cluster.

**Comment by CyberDem0n** [comment]
Well, you can query it from the DCS:

```bash
$ curl -s http://127.0.0.1:2379/v2/keys/service/batman/leader | jq -r .node.value
postgresql0
```

`patronictl list -f json` can output data in json format:
```bash
$ patronictl list -f json | jq -r '.[] | select(.Role == "Leader") | .Member'
postgresql0
```
The json format might be broken in `pause` mode or if the switchover is scheduled https://github.com/zalando/patroni/issues/675
