### ISSUE TITLE
Reasons of minimum PostgreSQL parameters value (max_connections, ...)

### ISSUE THREAD

**Issue by Soulou** [zalando/patroni#1142]
In `postresql/config.py` there is:

```
        'max_connections': (100, lambda v: int(v) >= 100, 90100),
        'max_wal_senders': (10, lambda v: int(v) >= 10, 90100),
        'wal_keep_segments': (8, lambda v: int(v) >= 8, 90100),
        # [...]
```

Is there any reason to have such "high" minimum in the validation method?

We're running small databases for customers where the number of connections for the first plan is 30, and we can't apply such configuration using patroni. (Same for `wal_keep_segments` and `max_wal_senders` which would be running correctly with lower values.

What about keeping the defaults and updating the minimum values?

ie

```
        'max_connections': (100, lambda v: int(v) >= 25, 90100),
        'max_wal_senders': (10, lambda v: int(v) >= 3, 90100),
        'wal_keep_segments': (8, lambda v: int(v) >= 1, 90100),
```

Regards,

**Comment by CyberDem0n** [comment]
Well, it is arguable if these values are "high", they actually mostly match current default values in the new cluster, but yes, we can make the minimal values smaller.
You can open a pull request if you like.

**Comment by Soulou** [comment]
Thanks a lot for your response @CyberDem0n I will open a PR, I wanted to be sure that there wasn't a good reason I would have missed.

It's definitely arguable if these values are "high", but it is a good thing I think to let users use a lower one.
