### ISSUE TITLE
Problem during startup

### ISSUE THREAD

**Issue by dapapko** [zalando/patroni#1144]
Hello. This issue is related to your docker image. In your docker/entrypoint.sh file you have the following strings:
 
```
 # We start an etcd
if [ -z "$PATRONI_ETCD_HOSTS" ] && [ -z "$PATRONI_ZOOKEEPER_HOSTS" ]; then
    export PATRONI_ETCD_URL="http://127.0.0.1:2379"
    etcd --data-dir /tmp/etcd.data -advertise-client-urls=$PATRONI_ETCD_URL -listen-client-urls=http://0.0.0.0:2379 > /var/log/etcd.log 2> /var/log/etcd.err &
fi 
```

I can set my etcd host via PATRONI_ETCD_HOST environmental variable, and if I do so, the entrypoint of your docker image will try to launch an instance of etcd and my address which I've set through PATRONI_ETCD_HOST will be ignored.
``` ## We start an etcd
if [ -z "$PATRONI_ETCD_HOSTS" ] && [ -z "$PATRONI_ZOOKEEPER_HOSTS" ] &&  [ -z "$PATRONI_ETCD_HOST"]; then
    export PATRONI_ETCD_URL="http://127.0.0.1:2379"
    etcd --data-dir /tmp/etcd.data -advertise-client-urls=$PATRONI_ETCD_URL -listen-client-urls=http://0.0.0.0:2379 > /var/log/etcd.log 2> /var/log/etcd.err &
fi 
`

**Comment by CyberDem0n** [comment]
My position regarding this docker image will not change, it is mainly targeted for playing with Patroni and Etcd locally (never aimed at production usage) and therefore it doesn't cover all configuration cases.

If you want to fix something, please open a pull request.
