### ISSUE TITLE
DCS values not activated

### ISSUE THREAD

**Issue by mzwettler2** [zalando/patroni#1147]
We had a running postgres cluster 9.6.5 with max_connections = 100.
We created a patroni 1.5.5 configuration on top of this existing cluster.
We modified "parameters: max_connections = 300" in the yml file beforehands and started patroni.
DCS showed (show-config): max_connections = 300
PG showed (show max_connections): max_connections = 100
We modified the DCS dynamically (edit-config) and restarted both members (restart).
DCS showed: max_connections = 300
PG showed: max_connections = 100
We stopped patroni (including PG), modified any config file to "max_connections = 300" and started up.
DCS showed: max_connections = 300
PG showed: max_connections = 100

Any time we start patroni max_connections is reset'ed to 100.
Any idea why we cannot change max_connections? 
Even with edit-config!

Thanks, Markus

**Comment by CyberDem0n** [comment]
I would recommend you to go through [tutorial](https://github.com/patroni-training/2019/blob/master/slides.pdf), starting from slide 50.

**Comment by mzwettler2** [comment]
thanks for the slide link.

you edit(ed)-config max_connections from 100 to 101 cluster-wide on slide 52
patroni1 is the leader according to slide 53
you restarted member patroni2 (standby) on slide 55
patroni1 (leader) shows max_connections 101 on slide 56
patroni2 (standby) shows max_connections 100 on slide 56
?
is this a mistake on the slides?
what do I miss here?




Von: Alexander Kukushkin <notifications@github.com>
Gesendet: Mittwoch, 14. August 2019 16:36
An: zalando/patroni <patroni@noreply.github.com>
Cc: Zwettler Markus (OIZ) <Markus.Zwettler@zuerich.ch>; Author <author@noreply.github.com>
Betreff: Re: [zalando/patroni] DCS values not activated (#1147)


I would recommend you to go through tutorial<https://github.com/patroni-training/2019/blob/master/slides.pdf>, starting from slide 50.

**Comment by CyberDem0n** [comment]
> is this a mistake on the slides?

Looks like a mistake on page 56.

**Comment by mzwettler2** [comment]
Ok.



I did again "edit-config" + "restart". But the postgres parameters where still not changed. See below in great detail. Any idea?




postgres@szhm49266:/home/postgres pcl_p011 $ patronictl list pcl_p011
+----------+--------------------+--------------------------+--------------+---------+----+-----------+
| Cluster  |       Member       |           Host           |     Role     |  State  | TL | Lag in MB |
+----------+--------------------+--------------------------+--------------+---------+----+-----------+
| pcl_p011 | pcl_p011@szhm49266 | szhm49266.global.szh.loc |    Leader    | running | 10 |       0.0 |
| pcl_p011 | pcl_p011@szhm49267 | szhm49267.global.szh.loc | Sync standby | running | 10 |       0.0 |
+----------+--------------------+--------------------------+--------------+---------+----+-----------+
postgres@szhm49266:/home/postgres pcl_p011 $ patronictl show-config pcl_p011
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
parameters:
  max_connections: 300
postgresql:
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
ttl: 30
postgres@szhm49266:/home/postgres pcl_p011 $ patronictl edit-config pcl_p011

"/tmp/pcl_p011-config-I9lFg3.yaml" 11L, 209C written
---
+++
@@ -2,7 +2,7 @@
master_start_timeout: 300
maximum_lag_on_failover: 1048576
parameters:
-  max_connections: 300
+  max_connections: 500
postgresql:
   use_pg_rewind: true
   use_slots: true

Apply these changes? [y/N]: y
Configuration changed
postgres@szhm49266:/home/postgres pcl_p011 $ patronictl restart pcl_p011
+----------+--------------------+--------------------------+--------------+---------+----+-----------+
| Cluster  |       Member       |           Host           |     Role     |  State  | TL | Lag in MB |
+----------+--------------------+--------------------------+--------------+---------+----+-----------+
| pcl_p011 | pcl_p011@szhm49266 | szhm49266.global.szh.loc |    Leader    | running | 10 |       0.0 |
| pcl_p011 | pcl_p011@szhm49267 | szhm49267.global.szh.loc | Sync standby | running | 10 |       0.0 |
+----------+--------------------+--------------------------+--------------+---------+----+-----------+
Are you sure you want to restart members pcl_p011@szhm49266, pcl_p011@szhm49267? [y/N]: y
Restart if the PostgreSQL version is less than provided (e.g. 9.5.2)  []:
When should the restart take place (e.g. 2015-10-01T14:30)  [now]:
Success: restart on member pcl_p011@szhm49266
Success: restart on member pcl_p011@szhm49267
postgres@szhm49266:/home/postgres pcl_p011 $ patronictl list pcl_p011
+----------+--------------------+--------------------------+--------------+---------+----+-----------+
| Cluster  |       Member       |           Host           |     Role     |  State  | TL | Lag in MB |
+----------+--------------------+--------------------------+--------------+---------+----+-----------+
| pcl_p011 | pcl_p011@szhm49266 | szhm49266.global.szh.loc |    Leader    | running | 10 |       0.0 |
| pcl_p011 | pcl_p011@szhm49267 | szhm49267.global.szh.loc | Sync standby | running | 10 |       0.0 |
+----------+--------------------+--------------------------+--------------+---------+----+-----------+
postgres@szhm49266:/home/postgres pcl_p011 $ patronictl show-config pcl_p011
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
parameters:
  max_connections: 500
postgresql:
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
ttl: 30

postgres@szhm49266:/home/postgres pcl_p011 $ psql
monitor@pcl_p011:pcl_p011 # show max_connections;
max_connections
-----------------
100
(1 row)

Time: 0.207 ms






Von: Alexander Kukushkin <notifications@github.com>
Gesendet: Donnerstag, 15. August 2019 12:11
An: zalando/patroni <patroni@noreply.github.com>
Cc: Zwettler Markus (OIZ) <Markus.Zwettler@zuerich.ch>; Author <author@noreply.github.com>
Betreff: Re: [zalando/patroni] DCS values not activated (#1147)


is this a mistake on the slides?

Looks like a mistake on page 56.

**Comment by mzwettler2** [comment]
Got it.

I changed the parameter within the bootstrap section. I had to change max_connections with the "postgresql section" of the config. It worked. Somewhat misleading.

postgres@szhm49266:/opt/app/patroni/etc pcl_p011 $ patronictl show-config pcl_p011
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
parameters:
  max_connections: 300
postgresql:
  parameters:
    max_connections: 300
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
ttl: 30
