### ISSUE TITLE
Update postgresql.conf via Patroni, that requires server restart

### ISSUE THREAD

**Issue by jpuris** [zalando/patroni#1149]
How would I go about restarting PG without restarting Patroni, in order to update the `postgresql.conf` parameter given by Patroni in `patroni.yaml`

I have following in my `patroni.yaml`
```
    parameters:
        unix_socket_directories: '/tmp/,/var/run/postgresql/'
```
and because of this I also have it in `postgresql.conf`, which is exactly what I expect. But then I want to get rid of this line and have PG use default. This particular config requires PG restart.

*What I have tried*
1. Update `postgresql.conf` - remove `unix_socket_directories` setting
2. Update `patroni.yaml` - remove `unix_socket_directories` setting
3. Run `patronictl -c /etc/patroni.yml restart <scope> <member>`
_What happens_
1. As expected, postgres restarts
2. `postgresql.conf` gets replaced with old version, which has `unix_socket_directories` in it.

*What happens*
I suppose this is because patroni does not see the changes for `parameters` key, when `restart` command is run. I do not know, if this is expected behavior or not, but it is what it is..

*Expected*
Either Patroni to not overwrite the manually updated config file or Patroni to refresh the config from yaml file before replacing the `postgresql.conf` file

_Alternative approaches_
`systemctl restart patroni`, but this will do a failover
`patronictl -c /etc/patroni.yml switchover <scope>`, but this also will do a failover (Ended up doing this)

What would be the go to method of achieving this, without a failover ?

**Comment by CyberDem0n** [comment]
Sorry for later reply.
When you change patroni.yaml and want Patroni to re-read it from disk you should either send SIGHUP to Patroni process or you `patronictl reload`.

After that `patronictl restart` will work as you want.

**Comment by jpuris** [comment]
Thank you! This solves it for me :)
