### ISSUE TITLE
Standby replica stuck in recovery - lag does not come down to zero

### ISSUE THREAD

**Issue by qasimmaqbool** [zalando/patroni#1153]
I'm running Patroni on Kubernetes and one of my replicas is seemingly unable to get out of recovery after a restart following a short period of downtime. What I see is in the affected replica's logs is that it has started accepting connections, but `select pg_is_in_recovery()` returns true. Moreover, `select pg_last_xact_replay_timestamp();` also returns a timestamp a few hours in the past so it seems the WAL was not completely streamed from the master. 

Note that I have another replica which has been successfully streaming the WAL from master all this time. Doing `patronictl list` shows both replicas to have 0MB lag but that is not actually the case, which I verified by running some queries on the data. Is this a known bug or something that needs fixing?

**Comment by CyberDem0n** [comment]
> has started accepting connections, but select pg_is_in_recovery() returns true

This absolutely normal and expected behavior of the replica.

> Moreover, select pg_last_xact_replay_timestamp(); also returns a timestamp a few hours in the past so it seems the WAL was not completely streamed from the master.

This function shows you the timestamp of the last completed transaction. Are you sure that there are some transactions happening on the primary?

> Doing patronictl list shows both replicas to have 0MB lag but that is not actually the case, which I verified by running some queries on the data

As you can see, the granularity of the output is 1MB, it is not possible to use it for nitpicking.

> Is this a known bug or something that needs fixing?

Have you checked `pg_stat_replication` view on the primary? Have you checked postgres logs?

**Comment by qasimmaqbool** [comment]
Thanks a lot for the detailed reply.

> This function shows you the timestamp of the last completed transaction. Are you sure that there are some transactions happening on the primary?

Yes, the primary is continuously receiving transactions and they are also being replicated on the other standby which did not go down. 
 
> Have you checked `pg_stat_replication` view on the primary? Have you checked postgres logs?

Yes, so pg_stat_replication show a single row for my replica which has been healthy all along and nothing for the affected replica. Also, pg_replication_slots shows that the slot for affected replica
has `active==false`. What does this indicate? Also, how can I check Postgres logs on the primary?

**Comment by CyberDem0n** [comment]
> Yes, so pg_stat_replication show a single row for my replica which has been healthy all along and nothing for the affected replica. Additionally, pg_replication_slots shows that the slot for affected replica has active==false. What does this indicate?

It indicates that indeed, the replica is not streaming from the primary.

> Also, how can I check Postgres logs on the primary?

What docker image do you use to run it? How the postgres logging is configured?
This is your setup after all, you should try to understand how it is configured and working.

**Comment by qasimmaqbool** [comment]
I am running Patroni v1.5.6 in an image built using the Dockerfile in kubernetes directory and I haven't done anything special to configure logging. Let me try and debug this further. Thanks.

**Comment by CyberDem0n** [comment]
If nothing special was configured postgres will write some logs to stderr which you can get from the pod:
```
kubectl logs pod-name
```
