### ISSUE TITLE
use_slots change not being recognized

### ISSUE THREAD

**Issue by dtseiler** [zalando/patroni#1158]
It looks like Patroni doesn't apply changes to `use_slots`, either setting it to true or false.

To test:

1. `patronictl edit-config`
2. Set `use_slots: true`
3. No slots are created on primary, and `primary_slot_name` is not added to replica recovery.conf.

Or:

1. `patronictl edit-config`
2. Set `use_slots: false`
3. Replica recovery.conf is not changed and replication slots not removed.

Restarting the Patroni members via `patronictl restart` does not change this. The only workaround is to restart the patroni service completely on all nodes. For example:

1. `patronictl edit-config`
2. Set `use_slots: false`
3. Restart patroni (eg systemctl restart patroni) on all replica nodes. (This will remove `primary_slot_name` from recovery.conf)
4. `patronictl pause`
5. Restart patroni on primary node
6. `patronictl resume`
7. Manually remove inactive replication slot (`select pg_drop_replication_slot('xxx');`)

**Comment by CyberDem0n** [comment]
It is a very rare case when somebody wants to enable/disable slots, therefore I didn't really care about changing it on the fly.
And even now I don't think that it worth the effort of implementing it.
Writing a few lines in the documentation might be good idea though.
