### ISSUE TITLE
Failed To Acquire Initialize Lock is still a problem

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#116]
Folks,

I'm doing a lot of testing which involves masters which fail to start.  Thing is, if this happens the initialize lock is left behind, and the only way to fix it is to manually delete the lock using curl.

There still needs to be a way that the initialize lock can be expired if there are no nodes in the cluster.

**Comment by alexeyklyukin** [comment]
I disagree that doing initdb anew is a proper automatic recovery procedure for the Patroni cluster that irrevocably lost all its nodes at the same time, which is what you seem to be suggesting with the lock expiration strategy.  Could you, please, describe you specific situation where you think it makes sense?

**Comment by jberkus** [comment]
Oh, I don't know that it should  happen automatically.  I just think there should be a better mechanism to get out of a cluster which failed to start than "curl -XDELETE".  Maybe this is a job for the CLI, will look.

**Comment by feikesteenbergen** [comment]
`patronictl remove` works, but it is very paranoid and asks multiple confirmations. We could implement `--force` on `patronictl`, which would wipe out the cluster from the DCS with force.

**Comment by alexeyklyukin** [comment]
+1 on this.

**Comment by LappleApple** [comment]
@jberkus Is there something more we should do to address your concerns on this one?
