### ISSUE TITLE
When new nodes pass tags: replicatefrom

### ISSUE THREAD

**Issue by cdy668** [zalando/patroni#1165]
Hello, I synchronize data to the primary node through tags: replicatefrom: postgres0，
When the synchronization is complete, I switch the node to the primary node and whether tags need to be removed？

**Comment by CyberDem0n** [comment]
`replicatefom` tag is designed for cascading replication, i.e: master->replica1->replica2.
Unless you have a very specific use-case you don't need to use it.

**Comment by cdy668** [comment]
> `replicatefom`tag用于级联复制，即：master-> replica1-> replica2。
> 除非你有一个非常具体的用例，否则你不需要使用它。

Thank you for your answer
