### ISSUE TITLE
Memory leak in Patroni 1.5.5 (Debian 10)

### ISSUE THREAD

**Issue by joshuaboniface** [zalando/patroni#1167]
I'm noticing what looks like a persistent memory leak in Patroni 1.5.5, installed from Debian Stable's package repository, and using the Zookeeper backend. After a restart (system or service), the memory usage of the main Patroni process climbs by about 1GB every 2-3 days [1]. Note that this isn't the Postgres process(es) themselves, but the actual main Patroni process [2]. I'm noticing this across several VMs with different databases;  I'm running 3 Patroni clusters, each of 3 hosts, and it affects all of them, so I don't think it's a particular host issue.

I don't see any references to this in the recent changelogs for 1.5.6 or 1.6.0, but I'm wondering if anyone else has noticed this? My config is pretty barebones, but could this be a config issue? And if not, any suggestions on debugging it?

[1] ![matrix-pg1_memused](https://user-images.githubusercontent.com/4031396/64476657-a2816c80-d15f-11e9-9ecf-061064fd25fa.png)

[2] ![patroni-mem-usage](https://user-images.githubusercontent.com/4031396/64476672-f5f3ba80-d15f-11e9-802b-08e6bcee4e5e.png)

**Comment by CyberDem0n** [comment]
That's very interesting...
I don't think that it is a configuration issue. There were no recent changes in the zookeeper implementation either.
Could you please share a version of `kazoo` module?

**Comment by joshuaboniface** [comment]
Certainly - it's also from the Debian repos:

```
python3-kazoo  2.5.0-1
```

**Comment by CyberDem0n** [comment]
I tried to reproduce it on debian:10 docker images with no luck.
Is there maybe something unusual in the patroni logs?

**Comment by tonis** [comment]
I am also having the same problem on Debian 10, with Patroni 1.5.5, installed from pip and not the debian package. The memory usage isn't growing as fast as in the first post here, but from 26. september it has grown to about 600mb on one instance.

There is nothing special in the logs, the usual messages about Lock owner and "i am secondary and i am following a leader" every 10 seconds.

**Comment by CyberDem0n** [comment]
First of all please enable debug logs. You can do it without restart, just put into patroni config:
```yaml
log:
  level: DEBUG
```

After that please send a `SIGHUP` to patroni process or do `patronictl reload`.

In addition to the usual patroni logs you should see something like following:
```
2019-09-30 14:06:50,197 DEBUG: Sending request(xid=42): SetData(path='/service/batman3/members/postgresql2', data='{"conn_url":"postgres://127.0.0.1:5434/postgres","api_url":"http://127.0.0.1:8010/patroni","tags":{"replicatefrom":"postgres1"},"timeline":1,"state":"running","version":"1.6.0","role":"replica","xlog_location":83886176}', version=-1)
2019-09-30 14:06:50,203 DEBUG: Received response(xid=42): ZnodeStat(czxid=28139, mzxid=28177, ctime=1569845038694, mtime=1569845210198, version=19, cversion=0, aversion=0, ephemeralOwner=102853146254508036, dataLength=219, numChildren=0, pzxid=28139)
```

If you got something more - this is already suspicious.

**Comment by tonis** [comment]
Below is a part from the debug log.

That "something more" are the OPTIONS queries by our script that manages a virtual IP that we use for accessing our servers. When looking at the output from top then the memory usage of patroni increases by 4, 8 or 12 bytes every few seconds, probably depending on how often top updates the data. Maybe there is something going wrong in the query handler?

`Sep 30 15:35:47 test-server1 patroni[26027]: 2019-09-30 15:35:47,913 DEBUG: Received response(xid=54736): ZnodeStat(czxid=4294970802, mzxid=77309493448, ctime=1530011301619, mtime=1569846947908, version=3941196, cversion=0, aversion=0, ephemeralOwner=0, dataLength=13, numChildren=0, pzxid=4294970802)
Sep 30 15:35:47 test-server1 patroni[26027]: 2019-09-30 15:35:47,913 DEBUG: Sending request(xid=54737): SetData(path='/service/test/members/postgresql0', data=b'{"conn_url":"postgres://192.168.9.226:5438/postgres","api_url":"http://192.168.9.226:5450/patroni","state":"running","role":"master","version":"1.6.0","xlog_location":7632798938296,"timeline":24}', version=-1)
Sep 30 15:35:47 test-server1 patroni[26027]: 2019-09-30 15:35:47,915 DEBUG: Received response(xid=54737): ZnodeStat(czxid=77309411394, mzxid=77309493449, ctime=1569572347904, mtime=1569846947913, version=27460, cversion=0, aversion=0, ephemeralOwner=216293534190010368, dataLength=195, numChildren=0, pzxid=77309411394)
Sep 30 15:35:47 test-server1 patroni[26027]: 2019-09-30 15:35:47,915 INFO: no action.  i am the leader with the lock
Sep 30 15:35:48 test-server1 patroni[26027]: 2019-09-30 15:35:48,202 DEBUG: API thread: 192.168.9.227 - - [30/Sep/2019 15:35:48] OPTIONS /ismaster 200 latency: 2.043008804321289 ms
Sep 30 15:35:49 test-server1 patroni[26027]: 2019-09-30 15:35:49,259 DEBUG: API thread: 192.168.9.226 - - [30/Sep/2019 15:35:49] OPTIONS /ismaster 200 latency: 2.0546913146972656 ms
Sep 30 15:35:50 test-server1 patroni[26027]: 2019-09-30 15:35:50,709 DEBUG: API thread: 192.168.9.225 - - [30/Sep/2019 15:35:50] OPTIONS /ismaster 200 latency: 2.0880699157714844 ms
Sep 30 15:35:51 test-server1 patroni[26027]: 2019-09-30 15:35:51,207 DEBUG: API thread: 192.168.9.227 - - [30/Sep/2019 15:35:51] OPTIONS /ismaster 200 latency: 2.025127410888672 ms`

**Comment by CyberDem0n** [comment]
@tonis yes, it is possible.
I'll check it tomorrow.

**Comment by joshuaboniface** [comment]
@CyberDem0n Here's debug logs from my instance just going through a few checkins. Nothing unusual that I can see:

```
Sep 30 12:03:30 matrix-pg2 patroni[469]: 2019-09-30 12:03:30,940 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:30] "GET / HTTP/1.1" 200 -                                                                                 
Sep 30 12:03:30 matrix-pg2 patroni[469]: 2019-09-30 12:03:30,944 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:30] "GET / HTTP/1.1" 200 -                                                                                               
Sep 30 12:03:32 matrix-pg2 patroni[469]: 2019-09-30 12:03:32,947 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:32] "GET / HTTP/1.1" 200 -              
Sep 30 12:03:32 matrix-pg2 patroni[469]: 2019-09-30 12:03:32,952 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:32] "GET / HTTP/1.1" 200 -                                                                                               
Sep 30 12:03:34 matrix-pg2 patroni[469]: 2019-09-30 12:03:34,111 INFO: Lock owner: matrix-pg2; I am matrix-pg2                                                                                                                                
Sep 30 12:03:34 matrix-pg2 patroni[469]: 2019-09-30 12:03:34,113 DEBUG: Sending request(xid=29147): SetData(path='/db/postgres/optime/leader', data=b'26399424896', version=-1)                                                               
Sep 30 12:03:34 matrix-pg2 patroni[469]: 2019-09-30 12:03:34,117 DEBUG: Received response(xid=29147): ZnodeStat(czxid=25769803938, mzxid=459561562267, ctime=1554012890658, mtime=1569859414113, version=987580, cversion=0, aversion=0, ephemeralOwner=0, dataLength=11, numChildren=0, pzxid=25769803938)
Sep 30 12:03:34 matrix-pg2 patroni[469]: 2019-09-30 12:03:34,118 DEBUG: Sending request(xid=29148): SetData(path='/db/postgres/members/matrix-pg2', data=b'{"conn_url":"postgres://matrix-pg2:5432/postgres","api_url":"http://matrix-pg2:8008/patroni","state":"running","role":"master","xlog_location":26399424896,"timeline":166}', version=-1)                                                                                                                                           Sep 30 12:03:34 matrix-pg2 patroni[469]: 2019-09-30 12:03:34,128 DEBUG: Received response(xid=29148): ZnodeStat(czxid=455266533384, mzxid=459561562269, ctime=1569696581089, mtime=1569859414118, version=16288, cversion=0, aversion=0, ephemeralOwner=144115188981825536, dataLength=198, numChildren=0, pzxid=455266533384)
Sep 30 12:03:34 matrix-pg2 patroni[469]: 2019-09-30 12:03:34,128 INFO: no action.  i am the leader with the lock                                             
Sep 30 12:03:34 matrix-pg2 patroni[469]: 2019-09-30 12:03:34,953 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:34] "GET / HTTP/1.1" 200 -                                                                                                Sep 30 12:03:34 matrix-pg2 patroni[469]: 2019-09-30 12:03:34,958 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:34] "GET / HTTP/1.1" 200 -              
Sep 30 12:03:36 matrix-pg2 patroni[469]: 2019-09-30 12:03:36,960 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:36] "GET / HTTP/1.1" 200 -                                                                                                Sep 30 12:03:36 matrix-pg2 patroni[469]: 2019-09-30 12:03:36,965 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:36] "GET / HTTP/1.1" 200 -              
Sep 30 12:03:38 matrix-pg2 patroni[469]: 2019-09-30 12:03:38,967 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:38] "GET / HTTP/1.1" 200 -                                                                                                Sep 30 12:03:38 matrix-pg2 patroni[469]: 2019-09-30 12:03:38,971 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:38] "GET / HTTP/1.1" 200 -              
Sep 30 12:03:40 matrix-pg2 patroni[469]: 2019-09-30 12:03:40,975 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:40] "GET / HTTP/1.1" 200 -                                                                                                Sep 30 12:03:40 matrix-pg2 patroni[469]: 2019-09-30 12:03:40,980 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:40] "GET / HTTP/1.1" 200 -                                                                                               
Sep 30 12:03:42 matrix-pg2 patroni[469]: 2019-09-30 12:03:42,982 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:42] "GET / HTTP/1.1" 200 -              
Sep 30 12:03:42 matrix-pg2 patroni[469]: 2019-09-30 12:03:42,987 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:42] "GET / HTTP/1.1" 200 -                                                                                               
Sep 30 12:03:44 matrix-pg2 patroni[469]: 2019-09-30 12:03:44,111 INFO: Lock owner: matrix-pg2; I am matrix-pg2                                                                                                                                 Sep 30 12:03:44 matrix-pg2 patroni[469]: 2019-09-30 12:03:44,113 DEBUG: Sending request(xid=29149): SetData(path='/db/postgres/optime/leader', data=b'26399431848', version=-1)                                                               
Sep 30 12:03:44 matrix-pg2 patroni[469]: 2019-09-30 12:03:44,118 DEBUG: Received response(xid=29149): ZnodeStat(czxid=25769803938, mzxid=459561562271, ctime=1554012890658, mtime=1569859424114, version=987581, cversion=0, aversion=0, ephemeralOwner=0, dataLength=11, numChildren=0, pzxid=25769803938)
Sep 30 12:03:44 matrix-pg2 patroni[469]: 2019-09-30 12:03:44,119 DEBUG: Sending request(xid=29150): SetData(path='/db/postgres/members/matrix-pg2', data=b'{"conn_url":"postgres://matrix-pg2:5432/postgres","api_url":"http://matrix-pg2:8008/patroni","state":"running","role":"master","xlog_location":26399431848,"timeline":166}', version=-1)                                                                                                                                           
Sep 30 12:03:44 matrix-pg2 patroni[469]: 2019-09-30 12:03:44,123 DEBUG: Received response(xid=29150): ZnodeStat(czxid=455266533384, mzxid=459561562273, ctime=1569696581089, mtime=1569859424119, version=16289, cversion=0, aversion=0, ephemeralOwner=144115188981825536, dataLength=198, numChildren=0, pzxid=455266533384)
Sep 30 12:03:44 matrix-pg2 patroni[469]: 2019-09-30 12:03:44,123 INFO: no action.  i am the leader with the lock              
Sep 30 12:03:44 matrix-pg2 patroni[469]: 2019-09-30 12:03:44,990 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:44] "GET / HTTP/1.1" 200 -                                                                                               
Sep 30 12:03:44 matrix-pg2 patroni[469]: 2019-09-30 12:03:44,995 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:44] "GET / HTTP/1.1" 200 -                                                                                               
Sep 30 12:03:46 matrix-pg2 patroni[469]: 2019-09-30 12:03:46,998 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:46] "GET / HTTP/1.1" 200 -                                                                                               
Sep 30 12:03:47 matrix-pg2 patroni[469]: 2019-09-30 12:03:47,002 DEBUG: API thread: 127.0.0.1 - - [30/Sep/2019 12:03:47] "GET / HTTP/1.1" 200 -  
```

Now, one thing that maybe contributing: I have a check script that hits the API every 2 seconds, from 2 hosts (load balancer config, if you're interested: https://www.boniface.me/post/patroni-and-haproxy-agent-checks/) as you can see in the logs there. Maybe it's the API?

**Comment by CyberDem0n** [comment]
It turned out that the memory leak has nothing to do with zookeeper and as usual the fix is very simple, just a single line.

**Comment by joshuaboniface** [comment]
Gotta love when they're that easy! I'll test out your patch and see how it looks on my systems.
