### ISSUE TITLE
patroni overriding max_prepared_transactions

### ISSUE THREAD

**Issue by k1ng440** [zalando/patroni#1169]
Hello,
i have provided my own config file using `postgresql.custom_conf` but patroni overriding some recommended settings by timescaledb-tune

here is a list
```
max_locks_per_transaction
max_prepared_transactions
max_replication_slots
max_wal_senders
max_worker_processes 
```

**Comment by kostiantyn-nemchenko** [comment]
Hi,
Patroni restricts setting values from the list you provided to the Dynamic configuration. Actually this is a documented [here](https://patroni.readthedocs.io/en/latest/dynamic_configuration.html#patroni-configuration).
