### ISSUE TITLE
How to upgrade from postgres 9.4 to 9.5?

### ISSUE THREAD

**Issue by sajal** [zalando/patroni#117]
Good news everyone! 
[postgres 9.5 is now released with UPSERT support](http://www.postgresql.org/about/news/1636/)

I am running a 3 node patroni cluster with basebackup and WAL managed by Wal-e running postgres 9.4. What would be a good upgrade procedure causing minimum downtime?

dump/restore is not a good option, my data is > 200GB

**Comment by alexeyklyukin** [comment]
Hi,

You can use pg_upgrade on your master and then re-initialize the replicas from it. There is no zero-downtime upgrade solution provided by patroni.

**Comment by LappleApple** [comment]
@sajal Is there anything more we need to help you with, or can we close out this issue?
