### ISSUE TITLE
patronictl does not honor PATRONI_CONFIGURATION env

### ISSUE THREAD

**Issue by k1ng440** [zalando/patroni#1171]
thanks

**Comment by CyberDem0n** [comment]
I am not sure how is it ever possible, because patronictl is [using](https://github.com/zalando/patroni/blob/master/patroni/ctl.py#L83) the same Config class as Patroni itself.

**Comment by k1ng440** [comment]
```
@click.option('--config-file', '-c', help='Configuration file',
              envvar='PATRONICTL_CONFIG_FILE', default=CONFIG_FILE_PATH)
```

it seems like I have to set PATRONICTL_CONFIG_FILE.

**Comment by CyberDem0n** [comment]
It seems that you are mixing up two different things:
1. PATRONI_CONFIGURATION is the env variable which should contain the Patroni configuration (the content of the config file), not the file name.
2. PATRONICTL_CONFIG_FILE is the file name with Patroni or patronictl config.
