### ISSUE TITLE
Delayed Replication configuration Issue

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [zalando/patroni#1179]
Im trying to implement Delay replication on an existing patroni cluster. On the slave node, I added this variable under `bootstrap`
```yml
    recovery_conf:
            recovery_min_apply_delay: '8h'
```
Then I did restart of patroni, after that, it didn't come up. 
```
Sep 15 07:27:12 bhuvi-psql2 patroni[26183]: LOG:  aborting startup due to startup process failure
Sep 15 07:27:12 bhuvi-psql2 patroni[26183]: LOG:  database system is shut down
Sep 15 07:27:21 bhuvi-psql2 patroni[26183]: localhost:5432 - no response
Sep 15 07:27:21 bhuvi-psql2 patroni[26183]: LOG:  database system was shut down in recovery at 2019-09-15 07:21:18 UTC
Sep 15 07:27:21 bhuvi-psql2 patroni[26183]: LOG:  entering standby mode
Sep 15 07:27:21 bhuvi-psql2 patroni[26183]: LOG:  invalid resource manager ID in primary checkpoint record
Sep 15 07:27:21 bhuvi-psql2 patroni[26183]: PANIC:  could not locate a valid checkpoint record
Sep 15 07:27:21 bhuvi-psql2 patroni[26183]: LOG:  startup process (PID 26250) was terminated by signal 6: Aborted
Sep 15 07:27:21 bhuvi-psql2 patroni[26183]: LOG:  aborting startup due to startup process failure
Sep 15 07:27:21 bhuvi-psql2 patroni[26183]: LOG:  database system is shut down
```
I want to use `basebackup for this replica creation.

I don't know what's wrong with these settings?

**Comment by CyberDem0n** [comment]
> I added this variable under bootstrap

First of all, the `bootstrap` section works only once, when you deploy a new cluster, therefore any change of `bootstrap` for the cluster which was already deployed will not take any effect.

`postgresql.recovery_conf.recovery_min_apply_deleay` is a more appropriate place to configure it, because you don't want _all_ nodes to be delayed.

> Then I did restart of patroni, after that, it didn't come up.

Well, Patroni itself is up and running, but it fails to start the postgres up. From the logs you posted here is not possible to figure out what has happened and why. You must read ALL Patroni and Postgres logs from the restart moment. As I already mentioned earlier the change of bootstrap section doesn't have any effect and therefore can't cause such problems.

**Comment by BhuviTheDataGuy** [comment]
Hey @CyberDem0n 

Thanks for your response, Im able to bring the node up and running. 
I have reinitiated the node and restarted the patroni service. 
But Im not able to see the lag in the status.
```root@bhuvi-psql:/pgdata/data# patronictl -c /etc/patroni.yml list
+----------+-------------+-------------+--------+---------+----+-----------+
| Cluster  |    Member   |     Host    |  Role  |  State  | TL | Lag in MB |
+----------+-------------+-------------+--------+---------+----+-----------+
| postgres |  bhuvi-psql | 10.128.0.18 |        | running |  8 |       0.0 |
| postgres | bhuvi-psql2 | 10.128.0.98 |        | running |  8 |       0.0 |
| postgres | bhuvi-psql3 | 10.128.0.99 | Leader | running |  8 |       0.0 |
+----------+-------------+-------------+--------+---------+----+-----------+
```

On master node I ran `pgbench` for 1min, but still the lag is zero.

```sql
postgres=# SELECT
  pg_last_xlog_receive_location() receive,
  pg_last_xlog_replay_location() replay,
  (
   extract(epoch FROM now()) -
   extract(epoch FROM pg_last_xact_replay_timestamp())
  )::int lag;
  receive   |   replay   | lag 
------------+------------+-----
 1/6D462180 | 1/1F00CBA8 |   
```

**Comment by BhuviTheDataGuy** [comment]
Never mind, after generating huge transactions, Im able to see the lag.

**Comment by efterlow86** [comment]
@CyberDem0n would you mind to describe yhis clause "postgresql.recovery_conf.recovery_min_apply_deleay" or where should i config this.? I plan to configure delay replica only on one nodes for my patroni postgres cluster. Please
