### ISSUE TITLE
patroni does not recover replica when we remove it.

### ISSUE THREAD

**Issue by alizaaliza** [zalando/patroni#1180]
Hi 

we evaluate patroni as HA management solution.
we try to remove the replica look for the correct procedure to recover.

1) restart patroni - patroni initiate pg_basebackup - but hangs after copying all the data
2) tryed to  stop patroni and run pg_basebackup manually. but after restarting patroni it reinitiate pg_basebackup and hangs.

what is the correct procedure to recover in such case?

thanks Aliza

**Comment by CyberDem0n** [comment]
I am sorry, but I totally fail to understand what and how you are doing.

**Comment by alizaaliza** [comment]
Thanks for reading. 
my question is what are the correct steps to recover full data crash ( removal) of the replica.

**Comment by CyberDem0n** [comment]
If the postgres data directory is empty, Patroni will create the new one by taking pg_basebackup from master or one of the replicas (if they allow to do so)
