### ISSUE TITLE
What happens if a DC goes down in a Postgresql, Patroni, etcd multi DC setup

### ISSUE THREAD

**Issue by s4vicky** [zalando/patroni#1182]
I have a question regarding how Patroni and etcd handle the below scenarios.

Assume there are two sites in this deployment, Site1 and Site2 and it's a 5 node cluster spread across these two sites. This is a primary/replica HA deployment.

Site1 has
S1node1 (Patroni + etcd leader + PostgreSQL master),
S1node2 (Patroni + etcd follower + PostgreSQL replica) and
S1node3 (Patroni + etcd follower + PostgreSQL replica)

Site2 has
S2node1 (Patroni + etcd follower + PostgreSQL replica) and
S2node2 (Patroni + etcd follower + PostgreSQL replica).

Scenario 1:

My understanding is that since the etcd leader is in Site1 and quorum is (5/2)+1 = 3, in case of a network split between the two sites Site1 will continue to accept updates since it has majority and meets quorum. Site2 will stop accepting updates since quorum is not met. Once the network glitch is resolved then the Site2 nodes just join back into the cluster. No action required.

Scenario 2:

If for some reason the entire Site1 went down (disaster scenario), then in Site2 we just have two nodes which don't meet the quorum. There will be no etcd leader which means that Patroni cannot promote the PostgreSQL replica to master in Site2.

Now the question for Scenario 2 is how to ensure that one of the Site2 node can get promoted to master? Does Patroni take care of this scenario? How do i achieve this?

**Comment by CyberDem0n** [comment]
You got nearly everything correctly. If the Site1 is down Site2 will not promote due to lack of quorum.
There is no way to automatically recover from such a situation.

The only solution would be to run one Etcd node somewhere else, Site3. You don't have to run postgres there. And BTW, It is not necessarily that the Postgres master is running on the same node where etcd leader. They are independent from each other.

**Comment by s4vicky** [comment]
thanks for the quick response.
The issue is that i dont have a site3... i was planning to have 3nodes in site1 and 2nodes in site2... odd number in one site so that i could have the quorum in site1 in case of split brain i.e dc link failure.

So if i dont have site3... there is no way to recover automatically from such a situation?

Lets assume i do get a site3 into the mix.. then the below is what you suggesting.. please confirm.

Site1 has
S1node1 (Patroni + etcd leader + PostgreSQL master),
S1node2 (Patroni + etcd follower + PostgreSQL replica) and
S1node3 (Patroni + etcd follower + PostgreSQL replica)

Site2 has
S2node1 (Patroni + etcd follower + PostgreSQL replica) and
S2node2 (Patroni + etcd follower + PostgreSQL replica).

Site3 has
S3node1 (etcd follower)

quorum = 6/2+1=4

With above combination:
a. if there is split brain between site1 and site2... the leader in site1 will continue to have the quorum (site1 and site3 are normal)
b. if there is split brain between site1 and site3... the leader in site1 will continue to have the quorum (site1 and site2 are normal)
**c. if there is split  brain between site1 and rest of the sites .... then in this case again we will lose the qorum and we cannot recover from it.... correct?**

**Comment by CyberDem0n** [comment]
> there is no way to recover automatically from such a situation?

There is no way to recover from it automatically.

> quorum = 6/2+1=4

You should run the odd number of etcd nodes, 3 or 5!

**Comment by s4vicky** [comment]
thanks for the clarification. i will go with site1(2 nodes), site2(2 nodes) and site3(1 node).

**Comment by CyberDem0n** [comment]
There is one simple rule which Patroni is following: Postgres can be running as master only when itm is owner of the leader key and it can update the leader key.

Everything else comes from properties of quorum based systems:
* It is only possible to create/update/delete keys in Etcd when majority of nodes acknowledge rutransaction (Quorum). Therefore if the Site2 is isolated from Site1 Patroni can't create/update leader key and postgres will not be running as maste
* Change of Etcd topology also requires Quorum. Therefore you can't add new etcd node on the Site2. Even in case if you can do so that will not help at all, because size of your etcd cluster will become 6. Quorum of 6 is 4. Three Etcd nodes will not give you a quorum. Removal of nodes from Etcd cluster also requires a Quorum.

With only two data centers it would be better to have two independent etcd clusters and run Patroni standby_cluster in the second data center. If the first site is down, you can MANUALLY promote the standby_cluster.

Automatic promotion is not possible, because site2 will never able to figure out the state of site1. What if it is not dead but there is a network communication problem? Do you really want to end up with TWO masters running at the same time in two data centers?

**Comment by s4vicky** [comment]
Thanks @CyberDem0n for the explanation. 
Definitely do not want two masters running at the same time in 2 DCs. 

I'm fine running 2 separate clusters of etcd, but question is once we manually promote the standby_cluster in DC2 (when DC1 is down)... and later we recover the DC1 (this will have the replicas now) can the DC2 promoted master start replicating to the DC1 replicas? If yes, then will it be automatically taken care by Patroni or we need human intervention here?

**Comment by CyberDem0n** [comment]
> Node2: SYNC Replica Postgresql (from Node1), etcd2 (cluster1-follower), patroni
> Node3: ASYNC Replica Postgresql (from Node1), etcd3 (cluster1-follower), patroni

You have to set `synchronous_mode: true` in the global configuration (`patronictl edit-config`).
This enables sync replication and the master node will choose one of the nodes as synchronous.
It is not necessarily would be node2.

>No impact to the call read/write requests. They continue to be processed because of the quorum (2).

Well, applications will have to reconnect.

> a. Will patroni automatically reconfigure Node3 to become the SYNC replica?

Yes

b. Will patroni automatically reconfigure Node4 to point to new master Node2 for replication?

No, you have to use something stable. VIP or HAProxy


> We then manually failover and promote DC2 Node4 standby to primary using the command “pg_ctl -D data/postgresql promote”

You should not use pg_ctl promote, but remove the `standby_cluster` section from the global configuration. You have to use `patronictl edit-config` for that.

> Will patroni automatically reconfigure Node5 and Node6 to change from cascade replication to SYNC or ASYNC replication?

5 and 6 already streaming from the 4, they don't need to be reconfigured.
Sync replication is configured independently from the standby_cluster. I think it should be possible to enable it on the standby cluster from the very beginning.


> DC1 restored back to normal and will be configured as Standby Cluster.

You'll have to do it manually, i.e. you need to create the `standby_cluster` section it the global configuration (`patronictl edit-config`) before starting the patroni up. Etcd cluster must be already running at that moment. Anything else Patroni should be able to figure out automatically.

**Comment by avaczi** [comment]
FYI this was asked at https://dba.stackexchange.com/q/249004/6219, too - I compiled an answer from @CyberDem0n's posts here.

**Comment by virtuel99** [comment]
Hi s4vicky,
Have you evaluated this solution ?

DC1: Active Cluster:
Node1: Primary Postgresql, etcd1 (cluster1-leader), patroni
Node2: SYNC Replica Postgresql (from Node1), etcd2 (cluster1-follower), patroni
Node3: ASYNC Replica Postgresql (from Node1), etcd3 (cluster1-follower), patroni
Quorum: 3/2+1 = 2

DC2: Standby Cluster:
Node4: STANDBY ASYNC Replica Postgresql (from Node1), etcd4 (cluster2-standby leader), patroni-standby
Node5: Cascade Replica Postgresql (from Node4), etcd5 (cluster2-follower), patroni-standby
Node6: Cascade Replica Postgresql (from Node4), etcd6 (cluster2-follower), patroni-standby
Quorum: 3/2+1 = 2

Thanks & regards,

**Comment by virtuel99** [comment]
Hi @s4vicky,
Have you evaluated this solution ?

DC1: Active Cluster:
Node1: Primary Postgresql, etcd1 (cluster1-leader), patroni
Node2: SYNC Replica Postgresql (from Node1), etcd2 (cluster1-follower), patroni
Node3: ASYNC Replica Postgresql (from Node1), etcd3 (cluster1-follower), patroni
Quorum: 3/2+1 = 2

DC2: Standby Cluster:
Node4: STANDBY ASYNC Replica Postgresql (from Node1), etcd4 (cluster2-standby leader), patroni-standby
Node5: Cascade Replica Postgresql (from Node4), etcd5 (cluster2-follower), patroni-standby
Node6: Cascade Replica Postgresql (from Node4), etcd6 (cluster2-follower), patroni-standby
Quorum: 3/2+1 = 2

Thanks & regards,

**Comment by hkilicvdub** [comment]
What will happen if 2 DCs are present
They have split network
and there is a Layer 2 extension. 
All of the nodes has takes IP from same subnet and they are all in same broadcast domain 
or 
there is any solution without Layer 2 extension and 2 DCs have split network?
