### ISSUE TITLE
patroni sets postgresql.conf to 600 even outside PGDATA

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#1185]
Debian (or rather pgapt, via https://redmine.postgresql.org/issues/4717 - might not be public) got an issue that patroni-1.6.0 now sets the `postgresql.conf` to 600 due to the `os.chmod()` in https://github.com/zalando/patroni/commit/0b1b1e3b542714b47634391f7dbb00016d885bff#diff-a534a7e0f2c46ba53349f820d9014468R286

I can verify that starting patroni over a Debian instance (with e.g. `/etc/postgresql/11/test/postgresq.conf`) renders that config file 600, while the same instance created via `pg_createcluster 11 test2` has it as 644:

```
 ls -l /etc/postgresql/11/test{2,}/postgresql.conf
-rw------- 1 postgres postgres   723 Sep 20 16:09 /etc/postgresql/11/test/postgresql.conf
-rw-r--r-- 1 postgres postgres 24070 Sep 20 16:10 /etc/postgresql/11/test2/postgresql.conf
```

That was part of a rather large patch so maybe unintentional? Maybe it was assumed that `postgresql.conf` is in PGDATA so should be 600 anyway? So how about checking `config_dir` in the YAML config to see whether that is set?

**Comment by CyberDem0n** [comment]
Oh...

my idea behind this change was that starting from 12 postgresql.conf will contain primary_conninfo, which is sensitive.

It is not a big deal to avoid setting permission to 600 if the config_dir is different from data_dir, but there is a question though, what are you going to do on 12? How are you going to protect it?
I don't really like the idea of keep primary_conninfo in the postgresql.auto.conf...

**Comment by mbanck** [comment]
Hrm good point, I've passed that on to the Debian postgresql maintainers.

**Comment by CyberDem0n** [comment]
Maybe we can go with 640?

**Comment by df7cb** [comment]
Use ~/.pgpass instead. The location is even configurable if you want to programmatically write the password to a file: `primary_conninfo = 'passfile=/some/where/else'`.
