### ISSUE TITLE
How to disable auto failover for some nodes in cluster.

### ISSUE THREAD

**Issue by gsl23** [zalando/patroni#1187]
Hi ! Tnx for your grealty HA instrument! 
I have next question : 
how to disable autofailover for some nodes (not all) in cluster ? 
Example - i have 6 nodes in cluster : 
3 in main DataCenter(mDC) and 3 in reserve DataCenter(rDC).
Master in mDC. I don't want auto failover to rDC, if one of nodes is alive in mDC.
How i may do it with patroni ?

**Comment by CyberDem0n** [comment]
```yaml
tags:
  nofailover: true
```

would do the trick.

**Comment by gsl23** [comment]
thx!
