### ISSUE TITLE
Documentation for rest api yaml does not include cacert property

### ISSUE THREAD

**Issue by geokala** [zalando/patroni#1188]
The documentation for the rest API section of the yaml file doesn't include the 'cacert' property, meaning that if a key and cert signed by a CA are provided, patronictl commands such as reinit will fail due to a certificate warning for anyone who doesn't code dive to find out how the request is formed.

**Comment by CyberDem0n** [comment]
@geokala REST API doesn't support cacert yet.
Feel free to implement it.

**Comment by geokala** [comment]
It absolutely does support it.

Try running a reinit on a node when you're using rest with certfile and keyfile specified (for a ca signed cert). It'll give you an SSL error.
Then add in cacert in the restapi section of the yaml and it'll work.

**Comment by geokala** [comment]
Specifically, this is the part of the code that causes this behaviour: https://github.com/zalando/patroni/blob/master/patroni/ctl.py#L155

**Comment by CyberDem0n** [comment]
Well, in this case we are talking not about `restapi.cacert`, but about `ctl.cacert`, which is [documented](https://github.com/zalando/patroni/blob/master/docs/SETTINGS.rst#ctl)

**Comment by geokala** [comment]
The code I linked also checks against restapi.cacert

If it is intended that ctl.cacert should be used instead then the code should maybe be logging some sort of warning about that?
Either way, it would be helpful if the docs regarding the restapi.certfile also advised where one is expected to locate the cacert path in the config, because otherwise everything can appear to work until one tries to use patronictl

**Comment by CyberDem0n** [comment]
> The code I linked also checks against restapi.cacert

The code first gets `ctl.cacers` and only if there is nothing it uses `restapi` as a fallback.

> if the docs regarding the restapi.certfile also advised where one is expected to locate the cacert path

As I mentioned earlier, please feel free to submit a PR fixing it.

**Comment by geokala** [comment]
PR created: https://github.com/zalando/patroni/pull/1190/files
