### ISSUE TITLE
Create a health check that returns 200 if and only if PostgreSQL is running

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/patroni#119]
If you put an ELB that incorporates all nodes to scale up reads that you want this health check.

**Comment by feikesteenbergen** [comment]
We currently have:

* /replica
* /master
* /patroni

Should we add the following?

* /postgres

**Comment by alexeyklyukin** [comment]
Another idea would be having a /replica/running and /master/running in order to return only the nodes that actually run PostgreSQL.

**Comment by LappleApple** [comment]
@alexeyklyukin @feikesteenbergen @CyberDem0n Is this something we can open up as a "Help Wanted" task?

**Comment by alexeyklyukin** [comment]
yes

**Comment by antineutron** [comment]
I might be able to pick this up.

**Comment by henrywangx** [comment]
Hi, actually we want the rest API to check running node.
If we redirect all the reading connetction to replica.
There is a situation that when all the replica is down, haproxy can't redirect the reading connection to master.

**Comment by jberkus** [comment]
@alexeyklyukin  is this still a valid task worth having a contributor pick it up?
