### ISSUE TITLE
patroni for production

### ISSUE THREAD

**Issue by alizaaliza** [zalando/patroni#1192]
Hi we are evaluating postgreSQL High-Availability solutions for our cumming productions.
as part of the evaluation we would like to get 
1) patroni official support for production
2) patroni and replication expert for evaluation benchmark. 

can we contact you or get your recommendation for the above.

Our typical production will include 
 4251 updates/sec, ~1000 deletes/sec, ~3221 inserts/s,  1 billion transactions per day.
database size will reach few terabytes.

Thanks in advance, Aliza.

**Comment by ants** [comment]
Hi,

my employer [Cybertec](https://www.cybertec-postgresql.com/en/) offers support plans that include support for Patroni high-availability setups and also consulting for architectural design, setup and performance evaluations. Feel free to contact us for an offer.

**Comment by alizaaliza** [comment]
Thanks a lot.
