### ISSUE TITLE
[Question] Send SIGHUP to Postgres

### ISSUE THREAD

**Issue by ccakes** [zalando/patroni#1198]
I’m running Patroni on Hashicorp Nomad and I’m using Vault to generate TLS certs for Postgres. I’d like to automate the rollover which should mean just replacing the files and sending the Postgres process a HUP.

The first part is easy, I’ve looked through the documentation but can’t find a straightforward way to pull off the second.

Since Patroni “owns” the Postgres process is there a way I can tell Patroni to send a HUP to Postgres? I’m running Patroni in Docker

**Comment by CyberDem0n** [comment]
Hi.

change of certificates requires a restart of postgres.
You can do it either with `patronictl restart` or do a `POST /restart` REST API call

**Comment by ccakes** [comment]
Not entirely sure that's correct, from the [Postgres docs](https://www.postgresql.org/docs/current/ssl-tcp.html) under table 18.2 (emphasis mine)
> The server reads these files at server start and **whenever the server configuration is reloaded**. On Windows systems, they are also re-read whenever a new backend process is spawned for a new client connection.

I knew Patroni has it's own SIGHUP handler which is why I asked the question, but I dug around in the code and it looks like SIGHUP reloads the Patroni config but is also passed through to Postgres.

I configured Nomad to send a SIGHUP when a new certificate is issued from Vault and so far it seems to work fine. I've only gone through one rollover but the first certificate is no longer valid, the Postgres process hasn't been restarted and it seems to be serving the new certificate to new clients (tested with [this](https://github.com/thusoy/postgres-mitm/blob/master/postgres_get_server_cert.py)).

Will keep testing and make sure it doesn't break in a day or two, but so far so good.

**Comment by CyberDem0n** [comment]
Cool, somehow I missed that starting from 10 change of `ssl_*_file` doesn't require a restart.
Unfortunately at the moment Patroni doesn't send a SIGHUP to postgres if there are no changes in postgres parameters.
I am going to improve it. Doing `pg_ctl reload` when you have been explicitly asked to doesn't hurt.
