### ISSUE TITLE
Consul support?

### ISSUE THREAD

**Issue by stretchkennedy** [zalando/patroni#120]
While I was evaluating patroni, I noticed the [feature/consul](/zalando/patroni/tree/feature/consul) branch. How much work would be required to add consul support: is it enough to finish the client, add some tests, and update the readme, or is there more? Why was the branch dropped?

**Comment by CyberDem0n** [comment]
The branch is there but it hasn't been synced from master for nearly half a year.
As far as I remember Consul support was functional, but unfortunately I didn't had time to run some serious  tests, therefore there might be some bugs.
Today I spend some time, synced code with the master branch and fixed broken unit-tests, but again, I didn't tried to run any tests against working postgres and consul.
If you are interested you can try it on your own.

**Comment by stretchkennedy** [comment]
Great, thanks! I'll take a look at it over the weekend, maybe write some tests, and see what comes up.

**Comment by jberkus** [comment]
Yeah, I was working on this, and then the person who wanted it migrated to Zookeeper.  So it's all yours.

**Comment by LappleApple** [comment]
Following up on this--@stretchkennedy, anything interesting to report back?

**Comment by stretchkennedy** [comment]
Hey all, sorry for the wait. Going forward, the company I'm with won't be using Patroni and may not even be using Postgres, so I haven't done much beyond setting up a test cluster and checking whether failover worked.

Since I don't know when and if I'll be able to devote any more time, I'm closing this issue for now, but best of luck to anyone who takes it up in the future.
