### ISSUE TITLE
Patroni not marking "Pending restart" flag

### ISSUE THREAD

**Issue by RajKiranS** [zalando/patroni#1201]
We are using Patroni v1.6.0. We noticed that Patroni has stopped marking 'Pending restart' flag in this version.

For example, we changed the restore_command and it wasn't marked for 'pending restart' but the config in ZooKeeper was successfully updated and patroni.dynamic.json too.

We updated the config using `patronictl edit-config` option only.

```
---
+++
@@ -12,7 +12,7 @@
     wal_level: hot_standby
     wal_log_hints: true
   recovery_conf:
-    restore_command: get-wal %f %p
+   restore_command: /usr/bin/get-wal %f %p
   use_pg_rewind: true
   use_slots: true
 retry_timeout: 10

Apply these changes? [y/N]: y
Configuration changed
```
```
$ ag restore_command
**patroni.dynamic.json**
1:{"retry_timeout": 10, "postgresql": {"use_slots": true, "parameters": {"hot_standby": true, "wal_keep_segments": 16, "wal_level": "hot_standby", "archive_command": "exit 0", "wal_log_hints": true, "max_wal_senders": 5, "archive_mode": "on", "max_replication_slots": 5}, "use_pg_rewind": true, "recovery_conf": {"restore_command": "/usr/bin/get-wal %f %p"}}, "synchronous_mode": true, "maximum_lag_on_failover": 1048576, "ttl": 10, "master_start_timeout": 10, "loop_wait": 10}

**recovery.conf**
2:restore_command = 'get-wal %f %p'
```
```
+------------+--------------------------------------+--------------------------------------------+--------------+---------+----+-----------+-----------------+-------------------+
|  Cluster   |                Member                |                    Host                    |     Role     |  State  | TL | Lag in MB | **Pending restart** | Scheduled restart |
+------------+--------------------------------------+--------------------------------------------+--------------+---------+----+-----------+-----------------+-------------------+
| abc | xxx | xxx:1234 |    Leader    | running | 7 |           |                 |                   |
| abc | yyy  | yyy:1234  | Sync standby | running | 7 |           |                 |                   |
+------------+--------------------------------------+--------------------------------------------+--------------+---------+----+-----------+-----------------+-------------------+
```

Am I missing something here?

**Comment by RajKiranS** [comment]
FTR: And the PostgeSQL version is 9.6

**Comment by RajKiranS** [comment]
Also, I tested out changing `wal_keep_segments` and that seems to have been smoothly updated.

From PostgreSQL logs:

```
< 2019-10-01 13:44:03.989 BST > LOG:  received SIGHUP, reloading configuration files
< 2019-10-01 13:44:03.990 BST > LOG:  parameter "wal_keep_segments" changed to "16"
```

**Comment by CyberDem0n** [comment]
restore_command actually never worked

**Comment by RajKiranS** [comment]
But, if I restart patroni, I see that the new value gets written to recovery.conf and is picked up.

Sorry, I don't understand when you meant it "actually never worked". Do you mean to say, its never updated by patroni automatically? If yes, what are other configs that I need to be aware of?

**Comment by CyberDem0n** [comment]
Patroni never tracked changes in the `postgresql.recovery_conf`...

Anything else should work fine.

**Comment by RajKiranS** [comment]
Oh! Wasn't aware of that. Thanks for quick responses @CyberDem0n 

Any reason why changes to `postgresql.recovery_conf` are not tracked? We were trying to automate pushing of changes from puppet to DCS and issue alerts incase of 'Pending restart' flag being set. And that not working for `postgresql.recovery_conf` breaks the consistency in the workflow. And folks should remember to manually restart...

**Comment by CyberDem0n** [comment]
People don't change it to often, therefore nobody complained so far, but I am going to fix it in the next release.

**Comment by RajKiranS** [comment]
True, it isn't changed that often. But, its ideal to have consistent behavior.

Thanks again!
