### ISSUE TITLE
Patroni Lag Problem

### ISSUE THREAD

**Issue by rootqu** [zalando/patroni#1203]
Hello,

we have 3 servers and was installed as sql1, sql2 and etcd.

etcd1 - 10.10.10.101 - etcdctl version: 3.2.22
sql1 - 10.10.10.102 - patronictl version 1.5.1
sql2 - 10.10.10.103 - patronictl version 1.5.1

# patronictl -d etcd://10.10.10.101:2379 list sql
+---------+--------+--------------+--------+---------+-----------+
| Cluster | Member |     Host     |  Role  |  State  | Lag in MB |
+---------+--------+--------------+--------+---------+-----------+
|   sql|  sql1| 10.10.10.102 |        | running |   13591.0 |
|   sql|  sql2| 10.10.10.103| Leader | running |       0.0 |
+---------+--------+--------------+--------+---------+-----------+

we are having a LAG problem and I didn't seen problems with network access.

Error Logs:

sql1:

2019-10-02 13:24:26.611 +04 [24938] LOG:  started streaming WAL from primary at 96/B7000000 on timeline 26
2019-10-02 13:24:26.611 +04 [24938] FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 0000001B00000096000000B7 has already been removed

sql2:

2019-10-02 13:25:38.671 +04 [10876] ERROR:  requested WAL segment 0000001B00000096000000B7 has already been removed

sql2 is Leader to sql cluster. what could be problem of this error? why is LAG happening and giving errors? what would you offer me?

Thanks for all help.

**Comment by CyberDem0n** [comment]
Hi @rootqu,

please use [search](https://github.com/zalando/patroni/issues?q=is%3Aissue+requested+WAL+segment+has+already+been+removed+is%3Aclosed)
