### ISSUE TITLE
How we can add multiple etcd host in patroni?

### ISSUE THREAD

**Issue by Tekchanddagar** [zalando/patroni#1206]
Hello Team,
Currently we are using patroni with single etcd node. But now we want to make it with 3 etcd node. We know the configuration in `patroni.yml`:
```
etcd:
    hosts: 192.168.56.9:2379,192.168.56.19:2379,192.168.56.21:2379
```
But when we are checking the member list in etcd then its showing only that host where we run the command `etcdctl member list`.

Its seems that we need to make the changes in `/etc/default/etcd` file but don't know what are the exactly changes. Can you please help me what changes are required to use multiple etcd node for HA.

Thanks.

**Comment by CyberDem0n** [comment]
Let me google it for you: https://www.google.com/search?q=etcd+clustering+guide

**Comment by Tekchanddagar** [comment]
@CyberDem0n, before asking on forum i have tried some configuration combination at my end but no success after that i posted on forum. I have followed below link :
[https://medium.com/searce/design-a-highly-available-postgresql-cluster-with-patroni-in-gcp-part-2-9df6ab4de741](url)

But when i am checking the member of cluster its showing only single node on which i am running the command.

Can you please check it once?

Thanks.

**Comment by Tekchanddagar** [comment]
@CyberDem0n, I am facing strange issue i.e

When i am running the below command individually on each etcd host:

```
etcd --name slave1 --initial-advertise-peer-urls http://192.168.56.9:2380 --listen-peer-urls http://192.168.56.9:2380 --listen-client-urls http://192.168.56.9:2379,http://127.0.0.1:2379 --advertise-client-urls http://192.168.56.9:2379 --initial-cluster-token cluster1 --initial-cluster slave1=http://192.168.56.9:2380,master1=http://192.168.56.19:2380,slave2=http://192.168.56.11:2380 --initial-cluster-state new
```

Then the each etcd host joining the cluster and when checking the `cluster member` its showing all the member in list.

But when i am putting the below config in `/etc/default/etcd` file and starting the service via `systemctl start etcd` then checking the member in cluster then its showing only single etcd host on which we run the command.

```
ETCD_NAME="master1"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://192.168.56.19:2380"
ETCD_LISTEN_PEER_URLS="http://192.168.56.19:2380"
ETCD_LISTEN_CLIENT_URLS="http://192.168.56.19:2379,http://127.0.0.1:2379"
ETCD_ADVERTISE_CLIENT_URLS="http://192.168.56.19:2379"
ETCD_INITIAL_CLUSTER_TOKEN="cluster1"
ETCD_INITIAL_CLUSTER="slave1=http://192.168.56.9:2380,master1=http://192.168.56.19:2380,slave2=http://192.168.56.11:2380"
ETCD_INITIAL_CLUSTER_STATE="new"
```

Can you please help me on this issue.

Thanks.

**Comment by Tekchanddagar** [comment]
@CyberDem0n,

This issue is fixed.
Need to remove the data from `/var/lib/etcd/default` directory and restart the etcd service on all 3 node.

Thanks.
