### ISSUE TITLE
Patroni failed to get list machines from etcd

### ISSUE THREAD

**Issue by Pravin-kumbhar** [zalando/patroni#1207]
Oct 03 10:21:11 ip-172-31-47-117 patroni[4647]: 2019-10-03 10:21:11,433 INFO: Selected new etcd server http://172.31.36.180:2379
Oct 03 10:21:14 ip-172-31-47-117 patroni[4647]: 2019-10-03 10:21:14,772 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError
Oct 03 10:21:18 ip-172-31-47-117 patroni[4647]: 2019-10-03 10:21:18,110 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError
Oct 03 10:21:21 ip-172-31-47-117 patroni[4647]: 2019-10-03 10:21:21,448 ERROR: Failed to get list of machines from http://172.31.36.180:2379/v2: MaxRetryError("HTTPConnectionPool(host='172.31.36.180', por
Oct 03 10:21:21 ip-172-31-47-117 patroni[4647]: 2019-10-03 10:21:21,448 INFO: waiting on etcd
Oct 03 10:21:26 ip-172-31-47-117 patroni[4647]: 2019-10-03 10:21:26,453 INFO: Selected new etcd server http://172.31.36.180:2379
Oct 03 10:21:29 ip-172-31-47-117 patroni[4647]: 2019-10-03 10:21:29,792 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError
Oct 03 10:21:33 ip-172-31-47-117 patroni[4647]: 2019-10-03 10:21:33,130 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError
Oct 03 10:21:36 ip-172-31-47-117 patroni[4647]: 2019-10-03 10:21:36,468 ERROR: Failed to get list of machines from http://172.31.36.180:2379/v2: MaxRetryError("HTTPConnectionPool(host='172.31.36.180', por
Oct 03 10:21:36 ip-172-31-47-117 patroni[4647]: 2019-10-03 10:21:36,468 INFO: waiting on etcd

**Comment by Pravin-kumbhar** [comment]
how i can solve this problem please help me

**Comment by Pravin-kumbhar** [comment]
I have created a 3 node patroni postgresql cluster my patroni.yml files

[Patroni_cluster.docx](https://github.com/zalando/patroni/files/3685667/Patroni_cluster.docx)

Initially i did not face this problem but now it occured

**Comment by CyberDem0n** [comment]
Have you checked that etcd cluster is up and running? Apparently no...

**Comment by Pravin-kumbhar** [comment]
yes

**Comment by CyberDem0n** [comment]
And network connectivity?
Patroni just telling you that it can't access etcd. You have to figure out why.

**Comment by shreeramk** [comment]
What's the solution for this? I am facing exactly same issue
