### ISSUE TITLE
initdb not being run after upgrade to 1.6.0

### ISSUE THREAD

**Issue by Lobo75** [zalando/patroni#1216]
I have a testing lab setup with three etdc servers and three postgresql/patroni servers on 1.5.6.  Part of normal testing is to completely reset the environment by removing the /var/lib/etcd/* directories in the cluster of the etdc servers and delete the data directory on the postgresql servers.  Then start patroni.  Normally patroni does the initdb and creates an empty db, life goes on. 

An unanticipated upgrade to patroni 1.6.0 occurred and now the cluster will not rebuild, it appears initdb is not being run (the yml files were not changed).  From the log below looks like patroni is confused as to the cluster status.  From looking at comments in the code it appears as if it's trying to get configuration from etdd but there is none so it fails on a KeyError.

Can you assist in how patroni would be looking for configuration on a cluster that does not exist yet or how the cluster status would be incorrect leading to that message indicating it's trying to start as a secondary?

2019-10-08 14:14:27,170 INFO: Failed to import patroni.dcs.consul
2019-10-08 14:14:27,189 INFO: Selected new etcd server http://10.x.x.x:2379
2019-10-08 14:14:27,203 INFO: No PostgreSQL configuration items changed, nothing to reload.
2019-10-08 14:14:27,216 WARNING: Postgresql is not running.
2019-10-08 14:14:27,216 INFO: Lock owner: None; I am postgresqlL0
2019-10-08 14:14:27,217 INFO: pg_controldata:

2019-10-08 14:14:27,219 INFO: Lock owner: None; I am postgresqlL0
2019-10-08 14:14:27,249 INFO: Lock owner: None; I am postgresqlL0
2019-10-08 14:14:27,255 INFO: starting as a secondary
2019-10-08 14:14:27,258 ERROR: Exception during execution of long running task restarting after failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 728, in follow
    self.start(timeout=timeout, block_callbacks=change_role, role=role)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 414, in start
    configuration = self.config.effective_configuration
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/config.py", line 731, in effective_configuration
#   insecure: false # Allow connections to SSL sites without certs
    cvalue = parse_int(data[cname])
KeyError: 'max_connections setting'
10.x.x.x:5432 - no response

Thanks.

**Comment by kostiantyn-nemchenko** [comment]
Could you please post a patroni configuration file?

**Comment by CyberDem0n** [comment]
I can imagine that postgres data directory is not empty, but at the same time it is invalid.

**Comment by CyberDem0n** [comment]
Magic doesn't exist. We run integration tests for every commit, i.e. we start etcd/zookeeper/consul/kubernetes and run a few patroni insurances to make sure that cluster is initialised correctly, that replicas are bootstrapped, that replication works, that failover also works, and so on.

I would really recommend you to make sure that /apps/PostgreSQL/pgsql_data/11/data is empty.

P. S.: rm -fr * doesn't deletes files with name starting with "." (dot)

**Comment by Lobo75** [comment]
Thank you for your replies.  I completely understand the development life cycle and realize this could be something unique to my environment or some kind of one off not exposed in a integration test.  If it was broken for everyone it never would have been released.

That's why I'm looking for help in understanding where the process could be going wrong.

The directory was definitively empty.  The experiment of switching to a new path was run.  The key error goes away but it still spins waiting for a leader.  I have attached a partial trace so you can see what was retrieved from etcd.  I'm not sure what the actual value of the key should be but I see a key for initialize then a state of stopped uninitialized.

I can send the full un-sanitized trace to a direct email.

Thank you.
[patroni1.6.trace.txt](https://github.com/zalando/patroni/files/3709477/patroni1.6.trace.txt)

**Comment by CyberDem0n** [comment]
That's because your previous attachment left initialise key in etcd. Just clean up etcd and it'll be fine.

**Comment by Lobo75** [comment]
On each etcd VM I would remove the entire directory for the data.  In the trace I sent you it would have been /var/lib/etcd/LabCluster1.  LabCluster1 would be the directory removed.

Then to verify my work etcdctl ls / --recursive

Then re-apply the etcd security.

Am I missing something?

**Comment by CyberDem0n** [comment]
> Am I missing something?

Yes.
After that you already did an attempt to start Patroni which failed due to non-empty PGDATA.
This attempt left some traces in etcd, more specifically `/initialize` key. Therefore now it assumes that cluster was initialized and waiting for a leader. That's why I told you to clean up etcd.

BTW, you don't need to re-bootstrap the whole etcd cluster, it is enough to remove `/service/LabCluster1`. You can do it with etcdctl or use `patronictl remove`.

**Comment by Lobo75** [comment]
In my case root cause turned out to be etcd.   

etcd also got updated as well as patroni.  The problem was with etcd authentication.  If your authentication is broken you get the same behavior I described and no error messages in the patroni logs. 

Thank you for your time and comments.
