### ISSUE TITLE
patroni - failover

### ISSUE THREAD

**Issue by ThePatzen** [zalando/patroni#1220]
Hi!

Patroni seems to be really nice but i have one question about the concept.

Isn't patroni a single point of failure? Or did i miss the point?
If Patroni is offline also no Failover is done right?

Best Regards,
David!

**Comment by CyberDem0n** [comment]
@ThePatzen,

no, Patroni is not SPoF.
You can find a lot of articles, blog posts, and presentations on the internet about  [patroni architechture](https://www.google.de/search?q=patroni+architecture).
