### ISSUE TITLE
Patroni doesn't load libraries set in patroni yml config

### ISSUE THREAD

**Issue by skullchap** [zalando/patroni#1222]
Hi, everything works great for me except "show shared_preload_libraries ;" in psql show nothing for me. When i start postgresql using default config without patroni everything works as it should. Library i want to load is pg_prewarm.so. 

i set it in patroni.yml like this:

 bootstrap:

    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            parameters:
              shared_preload_libraries: 'pg_prewarm.so'

Changing config using "patronictl -c /etc/patroni.yml edit-config" doesn't help either.

Logs of patroni also doesn't show any errors related to it.

**Comment by CyberDem0n** [comment]
After doing `patronictl edit-config` you have to use `patronictl restart`

**Comment by skullchap** [comment]
@CyberDem0n already did it, doesn't help

**Comment by CyberDem0n** [comment]
@skullchap either it is redefined with `ALTER SYSTEM` or you are doing something wrong:
```
$ psql -h localhost -U postgres -c 'SHOW shared_preload_libraries'
 shared_preload_libraries 
──────────────────────────

(1 row)

$ ./patronictl.py -c postgres0.yml edit-config -p shared_preload_libraries=pg_prewarm
--- 
+++ 
@@ -1,7 +1,8 @@
 loop_wait: 10
 maximum_lag_on_failover: 1048576
 postgresql:
-  parameters: null
+  parameters:
+    shared_preload_libraries: pg_prewarm
   use_pg_rewind: true
 retry_timeout: 10
 ttl: 30

Apply these changes? [y/N]: y
Configuration changed
$ ./patronictl.py -c postgres0.yml show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    shared_preload_libraries: pg_prewarm
  use_pg_rewind: true
retry_timeout: 10
ttl: 30

$ ./patronictl.py -c postgres0.yml list
+---------+-------------+-----------+--------+---------+----+-----------+-----------------+
| Cluster |    Member   |    Host   |  Role  |  State  | TL | Lag in MB | Pending restart |
+---------+-------------+-----------+--------+---------+----+-----------+-----------------+
|  batman | postgresql0 | 127.0.0.1 | Leader | running |  1 |       0.0 |        *        |
+---------+-------------+-----------+--------+---------+----+-----------+-----------------+
$ ./patronictl.py -c postgres0.yml restart batman postgresql0 --force
+---------+-------------+-----------+--------+---------+----+-----------+-----------------+
| Cluster |    Member   |    Host   |  Role  |  State  | TL | Lag in MB | Pending restart |
+---------+-------------+-----------+--------+---------+----+-----------+-----------------+
|  batman | postgresql0 | 127.0.0.1 | Leader | running |  1 |       0.0 |        *        |
+---------+-------------+-----------+--------+---------+----+-----------+-----------------+
Success: restart on member postgresql0
$ psql -h localhost -U postgres -c 'SHOW shared_preload_libraries'
 shared_preload_libraries 
──────────────────────────
 pg_prewarm
(1 row)
```

**Comment by skullchap** [comment]
It worked! :) 
Also what i noticed after
 `./patronictl.py -c postgres0.yml edit-config -p shared_preload_libraries=pg_prewarm` 
 'shared_preload_libraries: pg_prewarm' parameter went into section:


    postgresql: 
        parameters:
            shared_preload_libraries: pg_prewarm

but not like i configured all other postgresql.conf related parameters by putting it in:

    bootstrap:
        dcs:
            postgresql:
                parameters:
                    shared_preload_libraries: pg_prewarm

Thank you.
