### ISSUE TITLE
Bootstrap patroni with PGbackrest

### ISSUE THREAD

**Issue by kolbasky** [zalando/patroni#1223]
Hello,

if i get it correct, to restore whole cluster from a backup the correct way is to remove patroni cluster, then restart patroni so it would bootstrap a new one, but i must specify custom bootstrap method.
I am having trouble with this.
My bootstrap section of patroni.yml looks like this:
```
bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            recovery_conf:
                restore_command: 'pgbackrest --stanza=testpg archive-get %f %p'
    method: pgbackrest
    pgbackrest:
        command: pgbackrest --stanza=testpg  --process-max=4 restore
        keep_existing_recovery_conf: True
        no_params: True


    initdb:
    - encoding: UTF8
    - data-checksums

< pg_hba section here>.
```

So i remove cluster, clear PGDATA directory. Restart patroni and it starts to bootstrap, but fails with following messages:
```
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: 2019-10-11 15:07:24,104 INFO: Lock owner: None; I am testpgdb1
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: 2019-10-11 15:07:24,127 INFO: trying to bootstrap a new cluster
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: 2019-10-11 15:07:24,129 INFO: Running custom bootstrap script: pgbackrest --stanza=testpg  --process-max=4 restore
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: ERROR: [031]: invalid option '--scope=postgres'
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: 2019-10-11 15:07:24,172 INFO: removing initialize key after failed attempt to bootstrap the cluster
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: 2019-10-11 15:07:24,278 INFO: Lock owner: None; I am testpgdb1
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: Traceback (most recent call last):
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: File "/usr/bin/patroni", line 11, in <module>
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: load_entry_point('patroni==1.6.0', 'console_scripts', 'patroni')()
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 196, in main
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: return patroni_main()
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 160, in patroni_main
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: patroni.run()
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 125, in run
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: logger.info(self.ha.run_cycle())
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1344, in run_cycle
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: info = self._run_cycle()
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1253, in _run_cycle
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: return self.post_bootstrap()
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1149, in post_bootstrap
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: self.cancel_initialization()
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1144, in cancel_initialization
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: raise PatroniException('Failed to bootstrap cluster')
Oct 11 15:07:24 testpgdb1.foo.bar patroni[42256]: patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
```

As i got from the docs (https://patroni.readthedocs.io/en/latest/replica_bootstrap.html), patroni supplies the parameter, that causes problem, as pgbackrest doesn't have one with such name.
So i added "no_params: True" line, but no luck.
What am i doing wrong?

P.S.: i've managed to successfully restore cluster doing following:

- stopped patroni on each node
- removed contents of old pgdata data dir on each node
- manualy restored from pgbackrest on one node
- after starting patroni, it became leader
- after starting patroni on other nodes the successfully restored themselves with pgbackrest and start ed follwing the leader. 

so custom 'create_replica_methods' using pbackrest works correctly.

But i still can't get bootstrapping master with pgbackrest to work.

**Comment by CyberDem0n** [comment]
It seems that you are mixing two different concepts.
1. Replica bootstrap, use something different from `pg_basebackup` to initialize replica.
2. Custom bootstrap, use something different from `initdb` to initialize a new cluster.

`no_params` supported only in the first one, and documentation didn't promise that it will wort for the second option.

**Comment by kolbasky** [comment]
I am talking about bootstraping. Sorry if I've confused you. 
In your documentation (link I provided in my first message) bootstrap section ends with: 

If keep_existing_recovery_conf is defined and set to True, Patroni will not remove the existing recovery.conf file if it exists. This is useful when bootstrapping from a backup with tools like pgBackRest that generate the appropriate recovery.conf for you.

Which sounds like it is possible to bootstrap with pgbackrest. But I can get how.

**Comment by CyberDem0n** [comment]
I know that you are talking about bootstrap, I am also pretty confident that keep_existing_recovery_conf works as expected for custom bootstrap, while `no_params` works only for custom replica creation.

**Comment by kolbasky** [comment]
So how can I bootstrap with pgbackrest? 
If patroni supplies parameters, that back rest doesn't accept.

**Comment by CyberDem0n** [comment]
Wrap it into the shell script.

**Comment by kolbasky** [comment]
Ok, thanks, i'll try.

**Comment by vjtm** [comment]
Hi @kolbasky,

I'm having exactly the same problem.
As I am understanding, there are two options for successfully restoring a backup using pgbackrest.

1. As you mentioned in the P.S, do a manual restore procedure using the pgbackrest command and then start Patroni.
2. Let Patroni do the initial bootstrap using the latest backup made by pgbackrest, so when postgresql start it will have the latest data backup restored.
2a. You can also add new replicas using pgbackrest, but that's not the case.

Did the wrapper shell script workout for you? Would you mind sharing it?

Thanks

**Comment by vjtm** [comment]
I've found this https://github.com/zalando/patroni/issues/959
It works fine.

**Comment by kolbasky** [comment]
@vjtm, glad you've figured out.
@CyberDem0n, maybe you could implement "no params" option for bootstraping in some future release. That would be neater than writing wrappers for one-line command.

**Comment by guihecheng** [comment]
@vjtm hi, I've checked the issue #959 , but failed to find a working solution for bootstraping from pgbackrest backup, patroni either overwrites the `recovery.conf` if I do a manual restore or stayed waiting for the leader to bootstrap if I only config the bootstrap method without a manual restore.
Could you share your configuration that works fine?

**Comment by guihecheng** [comment]
#937 this solves my problem. After I checked my custom bootstrap script very carefully and ensure that it succeeded, I found that patroni is always waiting for leader to bootstrap, after manually remove the initialize node with etcdctl, patroni start to do a PITR correctly.

**Comment by guihecheng** [comment]
But I still have a question. I am able to bootstrap patroni with a backup from scratch now with an empty data dir.
But if a have a really larger data dir now, then:
1. filled a small but important table with some data
2. make a incr backup with pgbackrest
3. accidentally dropped the small but important table !!!
Obviously, I should do a PITR with pgbackrest. But for now I can only stop patroni and purge the really large data dir, then do a bootstrap from the backup which supposed to take a long time.
Is there any other way that allow me to do a small delta restore with `--delta` and restart my patroni quickly with the small important table back ? @CyberDem0n

**Comment by CyberDem0n** [comment]
@guihecheng please also read https://github.com/zalando/patroni/issues/1309

**Comment by guihecheng** [comment]
@CyberDem0n thanks a lot, the problem is solved, really a hacky way.

**Comment by amadhaka** [comment]
@guihecheng   Mate is it possible if you could share the fin al working patroni yml file for master and slave , I am very confused in making patroni work with pgbackrest.
Thanks,
Aman

**Comment by guihecheng** [comment]
@amadhaka ok
1. To config the archive stuff, you need the following:
```
bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        postgresql:
            use_pg_rewind: true
            parameters:
              wal_level: replica
              archive_mode: 'on'
              archive_command: pgbackrest --stanza=patroni_stanza archive-push %p
              archive_timeout: 60
           recovery_conf:
             restore_command: pgbackrest --stanza=patroni_stanza archive-get %f %p
             standby_mode: 'on'
```
Then,  there may be 2 operations you want to do:

1. Bootstrap
2. PITR

To do the 1st, you should follow the discussion in this thread above, because this is not the case I faced.
To do the 2nd, you should have the following:
```
    # should be commented out
    #initdb:
    #- encoding: UTF8
    #- data-checksums
    
    method: pgbackrest
    pgbackrest:
        command: /pgbackrest_bootstrap.sh
        keep_existing_recovery_conf: True
```
And the script pgbackrest_bootstrap.sh
```
#!/bin/bash
sudo -u postgres mv /data/patroni.bak/* /data/patroni/
```
After you stop patroni, pgbackrest restore, and restart your patroni service, do the operation as suggested by the thread as I was suggested above.
`etcdctl rm /db/postgres/initialize`
Then you have a complete PITR.

**Comment by vitabaks** [comment]
@guihecheng 

what is it? what for?
> sudo -u postgres mv /data/patroni.bak/* /data/patroni/

there should be this command:
`/usr/bin/pgbackrest --stanza=<my_stanza_name> --delta restore`

**Comment by guihecheng** [comment]
@vitabaks yeah, the command you provided is right and must be executed after stop patroni and **before** the script `pgbackrest_bootstrap.sh` is executed just to restore the data you want at the very point, and the restored data shoud be in /data/patroni.bak.
And the script aims to bring the restored data back, this trick is suggested in the thread https://github.com/zalando/patroni/issues/1309

**Comment by vitabaks** [comment]
ok, thanks @guihecheng for your comment.

I personally prefer to perform PITR is manually, then i [deploy](https://github.com/vitabaks/postgresql_cluster) of cluster over already existing and running PostgreSQL.
And I use pgbackrest for [create](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#building-replicas) and reinit replicas.

**Comment by guihecheng** [comment]
@vitabaks oh, yes, that's a really good idea for PITR, thanks.

**Comment by amadhaka** [comment]
Thanks , I would prefer PITR manually as well depending on the issue and situation I will be in.
So mentioned bootstrap and PITR configs , what I understood while setting up the cluster I should use bootstrap config's and when I have to do PITR I would change the yml file and start my recovery. and during all this I will be targeting only one node keeping others down.
Am I going right ?
Thanks,
Aman

**Comment by patsevanton** [comment]
@guihecheng what is final pgbackrest_bootstrap.sh script?

**Comment by dberardo-com** [comment]
for me the solution was to wrap the command inside /bin/bash, like:

`bootstrap:
    dcs:
        .... whatever
    method: pgbackrest
    pgbackrest:
        command: /bin/bash -c "pgbackrest --stanza=testpg  --process-max=4 restore"
        keep_existing_recovery_conf: True
       # this has no effect, so remove it
       #no_params: True`
