### ISSUE TITLE
`custom_conf` file changes not loaded after `patronictl restart`

### ISSUE THREAD

**Issue by jpuris** [zalando/patroni#1225]
Hi. I've run into unexpected behaviour with using `patronictl restart`

I'm using the "main" config file and then some replication related settings configured in `postgresql.parameters` to override.
```
postgresql:
    custom_conf: /etc/postgresql/postgresql.base.conf
```
And I can see it in the `$PGDATA/postgresql.conf`
```
cat /data/db/data/postgresql.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
include '/etc/postgresql/postgresql.base.conf'
[..]
```
***The problem however is, when I update the `custom_conf` file and run `patronictl restart`, the postgres server comes up without the change..***
````patronictl -c /etc/patroni.yml restart <scope> <node>````

However when I restart patroni via `systemctl restart patroni`, postgres is shut down and started with the new settings.

I'd expect from postgres point of view, both restarts to be identical, so how come with `patronictl restart` the new settings are not applied?

Patroni version 1.6.0
Postgresql version 9.6.15
Changed setting "shared_preload_libraries"

**Comment by CyberDem0n** [comment]
> when I update the custom_conf file and run patronictl restart, the postgres server comes up without the change

I am failing to understand what exactly you update, the content of custom_conf or postgresql.custom_conf in the patroni.yaml
If the second one - it has a good explanation. You have to first run patronictl reload in order to tell Patroni that it should re-read patroni.yaml.

If the first one - than I don't believe you:
```
$ head -n3 data/postgresql0/postgresql.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
include 'postgresql.custom.conf'

$ psql -h localhost -U postgres -c 'SHOW shared_preload_libraries'
 shared_preload_libraries 
──────────────────────────
 
(1 row)

$ echo shared_preload_libraries=pg_prewarm >> data/postgresql0/postgresql.custom.conf 
$ ./patronictl.py -c postgres0.yml restart batman --force
+---------+-------------+-----------+--------+---------+----+-----------+
| Cluster |    Member   |    Host   |  Role  |  State  | TL | Lag in MB |
+---------+-------------+-----------+--------+---------+----+-----------+
|  batman | postgresql0 | 127.0.0.1 | Leader | running |  3 |       0.0 |
+---------+-------------+-----------+--------+---------+----+-----------+
Success: restart on member postgresql0
$ psql -h localhost -U postgres -c 'SHOW shared_preload_libraries'
 shared_preload_libraries 
──────────────────────────
 pg_prewarm
(1 row)

```

**Comment by jpuris** [comment]
> I am failing to understand what exactly you update, the content of custom_conf or postgresql.custom_conf in the patroni.yaml

Contents of the postgresql configuration file were updated.

After looking into this once more, it seems I had failed to update the correct file :(
Patroni config points to `/etc/postgresql/postgresql.base.conf`, but I had updated `/etc/postgresql/postgresql.conf`.

Feels bad and lessons learned. Sorry for the confusion.
