### ISSUE TITLE
My patroni service is not running i got the logs after starting patroni service is

### ISSUE THREAD

**Issue by Pravin-kumbhar** [zalando/patroni#1227]
Oct 15 09:27:46 ip-172-31-41-186 patroni[11059]:     HTTPServer.__init__(self, info[0][-1][:2], RestApiHandler)
Oct 15 09:27:46 ip-172-31-41-186 patroni[11059]:   File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
Oct 15 09:27:46 ip-172-31-41-186 patroni[11059]:     self.server_bind()
Oct 15 09:27:46 ip-172-31-41-186 patroni[11059]:   File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
Oct 15 09:27:46 ip-172-31-41-186 patroni[11059]:     socketserver.TCPServer.server_bind(self)
Oct 15 09:27:46 ip-172-31-41-186 patroni[11059]:   File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
Oct 15 09:27:46 ip-172-31-41-186 patroni[11059]:     self.socket.bind(self.server_address)
Oct 15 09:27:46 ip-172-31-41-186 patroni[11059]: OSError: [Errno 98] Address already in use
Oct 15 09:27:46 ip-172-31-41-186 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Oct 15 09:27:46 ip-172-31-41-186 systemd[1]: patroni.service: Failed with result 'exit-code'.

**Comment by Pravin-kumbhar** [comment]
how to solve this problem

**Comment by anikin-aa** [comment]
@Pravin-kumbhar
> OSError: [Errno 98] Address already in use
Seems like you've got already running instance on port, default is set to 8008

You can change REST service port via next parameter:
https://github.com/zalando/patroni/blob/master/postgres0.yml#L5
https://github.com/zalando/patroni/blob/master/docs/SETTINGS.rst#rest-api
