### ISSUE TITLE
patroni connection problem with postgresql

### ISSUE THREAD

**Issue by Pravin-kumbhar** [zalando/patroni#1229]

**Comment by Pravin-kumbhar** [comment]
Oct 15 12:42:24 ip-172-31-41-186 patroni[28208]: FATAL:  no pg_hba.conf entry for host "172.31.41.186", user "postgres", database "postgres", SSL off
Oct 15 12:42:24 ip-172-31-41-186 patroni[28208]: During handling of the above exception, another exception occurred:
Oct 15 12:42:24 ip-172-31-41-186 patroni[28208]: Traceback (most recent call last):
Oct 15 12:42:24 ip-172-31-41-186 patroni[28208]:   File "/usr/local/lib/python3.6/dist-packages/patroni/api.py", line 452, in get_postgresql_status
Oct 15 12:42:24 ip-172-31-41-186 patroni[28208]:     self.server.patroni.postgresql.lsn_name), retry=retry)[0]
Oct 15 12:42:24 ip-172-31-41-186 patroni[28208]:   File "/usr/local/lib/python3.6/dist-packages/patroni/api.py", line 424, in query
Oct 15 12:42:24 ip-172-31-41-186 patroni[28208]:     return self.server.query(sql, *params)
Oct 15 12:42:24 ip-172-31-41-186 patroni[28208]:   File "/usr/local/lib/python3.6/dist-packages/patroni/api.py", line 511, in query
Oct 15 12:42:24 ip-172-31-41-186 patroni[28208]:     raise PostgresConnectionException('connection problems')
Oct 15 12:42:24 ip-172-31-41-186 patroni[28208]: patroni.exceptions.PostgresConnectionException: 'connection problems'

**Comment by CyberDem0n** [comment]
The error clearly tells you that pg_hba.conf doesn't allow patroni to connect to postgres.
You have to configure it.

**Comment by Pravin-kumbhar** [comment]
I have created 3 node cluster in which node 2 is working correctly and remaining nodes are not working
whatever settings of node 2 are same settings for node1 and node3
