### ISSUE TITLE
switchover: handle read only transaction error

### ISSUE THREAD

**Issue by oleg9301** [zalando/patroni#1235]
Hello guys!
I have next config:
Ha cluster postgresql(patroni,etcd,exabgp)
How It works:
Exabgp once in 2 sec checks api patroni, if postgresql is Primary, then exabgp announce bgp route with MED.
It  works good with failure scenario.
But when I do manual switchover, for 1-2 sec I have INSERT/UPDATE on my OLD primary postgresql, which currently is read only.

Logs:
```
Oct 18 17:09:06 hotname patroni[18827]: 2019-10-18 17:09:06.592 MSK [20565] ERROR:  cannot execute INSERT in a read-only transaction
Oct 18 17:09:06 hostname patroni[18827]: 2019-10-18 17:09:06.592 MSK [20565] STATEMENT:  INSERT INTO TABLE_NAME (some_columns) VALUES ($1, $2, $3, $4, $5, $6)
Oct 18 17:09:06 hostname patroni[18827]: #011RETURNING *
```

How to properly deal with this case?

I see 3 options:
1) before running switchover, make ban session with iptables
Example:
`iptables -A INPUT -s IP-ADDRESS_APPLICATIONS -j REJECT ; patronictl switchover`
2) Rewrite java app to properly handle this error(ERROR:  cannot execute INSERT in a read-only transaction).
3) Use some balancer session(maybe pgbouncer or pgppol).

**Comment by imcitius** [comment]
Hi

Use Haproxy with session termination option.
You can announce host in bgp if haproxy listen its port, and configure all Haproxy instances to check all patroni instances, and send traffic to master.

**Comment by oleg9301** [comment]
Mayby OK
But
As I see in https://github.com/zalando/patroni/blob/master/haproxy.cfg

`default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions`

As I understand, haproxy make a active healthcheck and for interval 3s * 3(fall), connection(queries INSERT/UPDATE) will be routed TO READ ONLY replica?
