### ISSUE TITLE
Question on DCS failover configuration

### ISSUE THREAD

**Issue by mzwettler2** [zalando/patroni#1246]
I want to prevent an automatic failover to a not completely updated standby.

I do not want a strict synchronous standby as I have only 1 standby.

Would this DCS configuration do the job?

Any issues with this configuration (switchover, etc.)?

**===================================
bootstrap:
  dcs:
    ...
    ...
    maximum_lag_on_failover: 0                                             ## NO FAILOVER WHEN BEHIND
    synchronous_mode: true
    synchronous_mode_strict: false
    ...
    ...
===================================**

**Comment by CyberDem0n** [comment]
When the `synchronous_mode` is set to true, the `maximum_lag_on_failover` effectively does nothing.
Only the synchronous node can become the new master if the old one failed.

P.S. speaking of configuration. I suppose you want to apply these settings on an already existing cluster, therefore you have to do it via `patronictl edit-config`.

**Comment by mzwettler2** [comment]
You got me wrong. I want to prevent this scenario:

1. replication is - not strict - synchronous (synchronous_mode: true + synchronous_mode_strict: false)
2. network between primary and standby gets broken
3. patroni degrades replication to asynchronous ((synchronous_mode: false + synchronous_mode_strict: false)
4. the standby falls behind and is not actualised anymore
5. primary database crashes
6. patroni promotes standby to be the new primary as long as lag <= maximum_lag_on_failover

The promotion at point 6 should only happen when there is no lag.
If there is a lag no promotion should happen.

Can this be reached with the configuration above?
Would there be any other issues with this configuration?

**Comment by CyberDem0n** [comment]
I've got you absolutely right.
When the only sync standby disconnects from the primary Patroni will remove it from the `/sync` key in the DCS and remove it from sync_standby_names.
Effectively that means that after the master has crashed the old sync standby will not be allowed to promote.

**Comment by mzwettler2** [comment]
Thanks. I could do a testcase on this and got the behavior you mentioned.

Maybe you want do a small change on the documentation: 
maximum_lag_on_failover ....... only valid when cluster is bootstrapped in asynchron replication mode.
