### ISSUE TITLE
Failed to switchover using patronictl 1.6

### ISSUE THREAD

**Issue by weiyinteo** [zalando/patroni#1247]
Hi Guys,

I've tried to run `patronictl -c postgres.yml switchover` to switchover the master but it failed with the following message:
> Switchover failed, details: 412, switchover is not possible: no good candidates have been found

On the other hand, this is the log from the master:
> 2019-10-24 00:13:48,987 WARNING: Request failed to db-1: GET http://10.1.1.1:8008/patroni (the JSON object must be str, not 'bytes')

This works before I upgraded to patroni 1.6.

I've managed to pinpoint it to ha.py line 557:
```python
logger.info('Got response from %s %s: %s', member.name, member.api_url, response.data.decode('utf-8'))
return _MemberStatus.from_api_response(member, json.loads(response.data))
```

The exception is caused by `json.loads(response.data)`. If I change it to `json.loads(response.data.decode('utf-8')` like line 556, then I could switch over the master succesfully.

**Comment by CyberDem0n** [comment]
That's interesting.
I guess you installed Patroni from the master branch.

What python version do you use?

**Comment by weiyinteo** [comment]
It's python 3.5 actually.
