### ISSUE TITLE
Question: patroni failover in case of errors only

### ISSUE THREAD

**Issue by mzwettler2** [zalando/patroni#1255]
I want patroni to failover only in case of errors.

I do not want patroni to failover at regular shutdowns whether by hand nor by start-stop script.

Using systemd I included "ExecStartPost / ExecStop" clauses with "patronictl pause / resume".

This worked in most cases except stopping both nodes but starting the formerly standby first.

Starting the formerly standby first still results in a failover.

Any idea or coded solution?

**Comment by CyberDem0n** [comment]
The main purpose of Patroni is providing HA.
If you shut the master down, it will result in a failover. If there is no master running and the other node is healthy enough to become the new master - you'll get a failover. Period.

**Comment by mzwettler2** [comment]
I agree with HA. I disagree with failover in any case. There is failover and switchover. It's a decisive difference.

Anyway. I understood there is neither an idea nor a coded solution?

**Comment by CyberDem0n** [comment]
> There is failover and switchover. It's a decisive difference.

Well, yes, Patroni will try to do it's best and shutdown postgres cleanly. In case if there are active standbys connected to the primary they will receive WAL stream till the last bit. This is a switchover.

But, I am absolutely unsure about the shutdown strategy. It might start killing processes after a certain period if the normal shutdown after SIGTERM didn't happen. This is not a switchover anymore.

> Anyway. I understood there is neither an idea nor a coded solution?

You can enable `synchronous_mode: on`, in this case only the former master will promote.

**Comment by mzwettler2** [comment]
There should never be an automated switchover. Hate the idea.

synchronous_mode on will also promote the former standby if it is synchronous till the last bit. That's my actual configuration. and problem... ;-)

**Comment by CyberDem0n** [comment]
> There should never be an automated switchover. Hate the idea.

Makeup your mind. After all, these are just words. You can call it failover if you like.
But main idea remains, Patroni is doing its best to minimize possible data loss and downtime.

> synchronous_mode on will also promote the former standby if it is synchronous till the last bit. That's my actual configuration. and problem... ;-)

You can tag it with `tags.nofailover: true`, problem solved.

**Comment by mzwettler2** [comment]
You would lose HA on failure with "tags.nofailover: true" in a 2-node configuration. No?

**Comment by CyberDem0n** [comment]
Absolutely.
You should really make up your mind whether you want HA or not.
Intention to shut everything down makes me think that you don't want to have it.
