### ISSUE TITLE
Show Async mode replication

### ISSUE THREAD

**Issue by patsevanton** [zalando/patroni#1257]
If install Patroni with default variable, patronictl don`t show Async_standby mode replication.
![image](https://user-images.githubusercontent.com/10828883/67787912-93ea6e00-fa9b-11e9-8057-fdaae89d70a9.png)

May be add show Async_standby mode replication?
Thanks!

**Comment by caseyallenshobe** [comment]
I agree that this would be useful to see when using `patronictl list -e`

**Comment by glushakov** [comment]
Agree, very usefull. Also would like see role with synchronous replication (e.g. sync, potential , like in pg_stat_replication)

**Comment by CyberDem0n** [comment]
patronictl list is using DCS as a source and therefore doesn't show real-time information.
In the worst case it could be outdated up to `loop_wait` seconds.

**Comment by CyberDem0n** [comment]
I think https://github.com/zalando/patroni/pull/2733 addresses it, at least partially.
About the rest it is not clear.
