### ISSUE TITLE
Installation Problem of Patroni

### ISSUE THREAD

**Issue by bagafoot** [zalando/patroni#1258]
Hi,
I want to install the last release of patoni on Centos7 which support postgresql12,
but I face up with this error.
Is it issue caused by the network or incompatible versions of libs.
Thanks a lot.
![patroni](https://user-images.githubusercontent.com/30403489/67835631-8795fd80-fafb-11e9-8a67-5c373bd01535.PNG)

**Comment by vitabaks** [comment]
Make sure you have time synchronization is configured (NTP).

**Comment by bagafoot** [comment]
thanks a lot, its problem caused by network problem, I export this vm and import in my laptop and it working.
