### ISSUE TITLE
Add enhancement to patronictl: pause a single cluster member

### ISSUE THREAD

**Issue by mzwettler2** [zalando/patroni#1259]
Actually one can pause and resume the whole patroni cluster only:
patronictl pause [cluster]

It would be desirable to pause and resume any individual cluster member:
patronictl pause [cluster] [member]

This would allow more flexibility in case of maintenance.

**Comment by CyberDem0n** [comment]
> This would allow more flexibility in case of maintenance.

This would be a great foot gun.
1. you paused the leader
2. stopped patroni on the leader
3. another node promotes
4. good luck in resolving the split-brain

**Comment by ants** [comment]
What would the semantics of pausing a single member be and how would they functionally differ from pausing the whole cluster?

**Comment by mzwettler2** [comment]
@CyberDem0n: when there is a paused leader there is no promotion. quite simple.

@ants: actually only the whole configuration can be paused or resumed. pausing the master but resuming a slave would resume the whole configuration. resuming a slave should not resume the whole configuration.

**Comment by ants** [comment]
> resuming a slave would resume the whole configuration. resuming a slave should not resume the whole configuration.

I think you made some mistake here, as this statement is self contradictory.

**Comment by mzwettler2** [comment]
resuming a slave resumes the whole configuration today. 
resuming a slave should not resume the whole configuration in the future.
better now?

**Comment by CyberDem0n** [comment]
No, it is not better. That simply doesn't make any sense to "pause" a single node.
If you want the specific node to be excluted from automatic failover - use `tags.nofailover: true`.

**Comment by mzwettler2** [comment]
tags is a flag. a command would be easier to handle.
