### ISSUE TITLE
broken backup trail in case of quickly patroni switchback and forth

### ISSUE THREAD

**Issue by mzwettler2** [zalando/patroni#1264]
we take our (wal) backups on the primary side based on intervals and thresholds.
our archived wal's are written to a local wal directory first and moved to tape afterwards.

we got a case where patroni switched back and forth sides quickly, e.g.:
12:00h: primary - standby
12:05h: standby - primary
12:10h: primary - standby

we realised that we will not have a wal backup of those wal's generated between 12:05h and 12:10h in this scenario.

how can we make sure that the whole wal sequence will be backuped?

**Comment by CyberDem0n** [comment]
Patroni is neither managing backups nor does a wal archiving.

**Comment by mzwettler2** [comment]
yes, patroni doesn't do backup or wal archiving.
but it changes the database roles and therefore the backup source location.
that's why I asked for some ideas on this one.
it has only been a question not a critic.

**Comment by CyberDem0n** [comment]
You'll get exactly the same behaviour even without any HA system.

**Comment by mzwettler2** [comment]
Nope. I would never come into this situation with a non HA system.
