### ISSUE TITLE
support piping config to patroni

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#127]
In order for Patroni to work better on Kubernetes/Docker, it would be very useful if we could pass the Patroni configuration into new containers as one big variable instead of needing to have a shell script or CMS setup which writes a config file.  This would require:

1. support JSON for config as well as YAML (should be trivial)
2. support config as single value with the --config switch

Doesn't seem more complicated than that; any gotchas before I start working on this?

**Comment by feikesteenbergen** [comment]
+1, we also would like to be able to reconfigure patroni during its execution. We're thinking of only using the initial configuration to populate the dcs, afterwards the dcs will be leading when it comes to configuration.

As far as I know, all json is valid yaml, so it should be trivial to implement that one:
```python
>>> import json
>>> import yaml
>>> config = {'list': [1,2,3], 'dict': {'key':'value'}}
>>> config_json = json.dumps(config)
>>> config_json
'{"dict": {"key": "value"}, "list": [1, 2, 3]}'
>>> yaml.load(config_json)
{'dict': {'key': 'value'}, 'list': [1, 2, 3]}
```

We would also like to allow reconfiguration, which has some relation to this feature I suppose, thoughts would be appreciated:

https://github.com/zalando/patroni/issues/121

**Comment by feikesteenbergen** [comment]
Fixed? by https://github.com/zalando/patroni/commit/9744019341608c475873d4d214299e3019cb1361

**Comment by alexeyklyukin** [comment]
We implemented support for reading Patroni configuration from the environment variable (PATRONI_CONFIGURATION at present). It's trivially to emulate the use-case above by doing

`PATRONI_CONFIGUARION="... yaml configuration" patroni.py`

Since JSON is a subset of YAML, our existing code should handle a JSON configuration as well.

**Comment by jberkus** [comment]
The funny thing is that, with ConfigMap, this become less necessary for Kubernetes ...
