### ISSUE TITLE
Another 'waiting for leader to bootstrap'

### ISSUE THREAD

**Issue by tmpm697** [zalando/patroni#1272]
I found useful ticket but it doesn't work for me: https://github.com/zalando/patroni/issues/937

How to destroy and re-create `/service/$CLUSTER_NAME/initialize` with `the same name`?

I tried both patronictl remove cluster and remove datadir of zookeeper and restart zookeeper (try to make it new fresh zookeeper), both don't work, still `'waiting for leader to bootstrap'` when I restart patroni service.

**Comment by CyberDem0n** [comment]
Sorry, but magic doesn't exist.
If Patroni is reporting `'waiting for leader to bootstrap'` that could only mean that the `/initialize` key is still presented in the zookeeper cluster.

**Comment by tmpm697** [comment]
> Sorry, but magic doesn't exist.
> If Patroni is reporting `'waiting for leader to bootstrap'` that could only mean that the `/initialize` key is still presented in the zookeeper **cluster**.

Thank you, but help me to remove `/initialize` in zookeeper cluster, howot?

**Comment by tmpm697** [comment]
Still got error because wrong config, `patronictl -c /etc/patroni/config.yml remove <cluster_name>` would help.
