### ISSUE TITLE
Patroni docker-compose not working

### ISSUE THREAD

**Issue by shreeramk** [zalando/patroni#1273]
Is patroni docker compose not working?
`$ docker-compose up -d`

Creating network "patroni_demo" with the default driver
Pulling etcd1 (patroni:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling etcd1 (patroni:)...
ERROR: pull access denied for patroni, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Even `docker run -d patroni ` didn't worked.

**Comment by CyberDem0n** [comment]
Have you built it?

**Comment by shreeramk** [comment]
No.

Shouldn't it built automatically when we run `docker run -d patroni ` and docker doesn't found the build locally?

**Comment by CyberDem0n** [comment]
`docker build -t patroni .`

**Comment by shreeramk** [comment]
I got the build command but I assumed if on running with docker run command if it is not found then docker builds it automatically.
