### ISSUE TITLE
Howto recovery to specific time in past?

### ISSUE THREAD

**Issue by tmpm697** [zalando/patroni#1274]
I have a patroni cluster with two nodes, it works as expected.

But I want to restore backup at specific time in the past, e.g: `2019-11-12 3:21:37`

I tried to manually set `recovery_target_timeline = '2019-11-12 3:21:37'` in `recovery.conf` but then patroni failover to other node, `recovery.conf` file in other node always has `recovery_target_timeline =  'latest'`

So can we control the way to restore to specific timeline in past with patroni?

**Comment by vitabaks** [comment]
> So can we control the way to restore to specific timeline in past with patroni?

Point-in-Time Recovery (PITR) is not a task that Patroni should solve.
There are backup and recovery tools for this.

For example:
[pgbackrest](https://github.com/pgbackrest/pgbackrest)

[Point-in-Time Recovery](https://pgbackrest.org/user-guide.html#pitr) allows the WAL to be played from the last backup to a specified time, transaction id, or recovery point.

**Comment by CyberDem0n** [comment]
The [custom bootstrap](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#bootstrap) feature allows to automate it nicely.
