### ISSUE TITLE
Legacy PostgreSQL10 Cluster

### ISSUE THREAD

**Issue by u02249** [zalando/patroni#1280]
I  use legacy cluster PostgreSQL 10 now. If I will create a new PostgreSQL 11 clusters on the same servers, Does Patroni break my legacy cluster?

**Comment by CyberDem0n** [comment]
Hi @u02249,

> I use legacy cluster PostgreSQL 10 now.

PG 10 is not legacy, it will continue receiving updates for another three years.

> Does Patroni break my legacy cluster?

All in your hands, or in other words, it all depends on how you configure everything.
That's like flying a modern aircraft, mostly auto-pilot, but you really have to know how to fly manually. The same here, you have to understand what you are doing and everything would be fine. If you are unsure about something - deploy a test system and try to perform your task there before doing it in prod.
