### ISSUE TITLE
cleared rewind state after becoming the leader - more info required.

### ISSUE THREAD

**Issue by gowtham500** [zalando/patroni#1287]
Hello team,

Can you please provide more info on this message -"cleared rewind state after becoming the leader."

When I failover to a new master, the new master's patroni logs says- " cleared rewind state after becoming the leader"

Does this mean the rewind took place ?

**Comment by CyberDem0n** [comment]
That's just an informational message that the state of internal state machine has changed.
You can see it only during promote.

**Comment by gowtham500** [comment]
Thanks
