### ISSUE TITLE
Support for additional tags in consul

### ISSUE THREAD

**Issue by harlequin** [zalando/patroni#1298]
Support for additional tags in consul.

We are using fabiolb as Load Balancer in front of our applications.

Therefore an additional tag [urlprefix] is needed that fabio will discover the services.

Is there a way to define more tags in consul service registration?

**Comment by CyberDem0n** [comment]
Hi @harlequin,

no, it is not supported, but it shouldn't be very hard to implement.
It boils down to propagating them from the config to the place where tags are set: https://github.com/zalando/patroni/blob/master/patroni/dcs/consul.py#L417
It would be also great to support the update of tags on [reload](https://github.com/zalando/patroni/blob/master/patroni/dcs/consul.py#L240-L242).
If you have some python skills please feel free to contribute.

**Comment by CyberDem0n** [comment]
No progress on this. Closing.
