### ISSUE TITLE
Support shared secrets instead of passwords in conf file

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#130]
We need to support a more secure way to supply passwords than putting them in the conf file.  Here's my proposal:

1. support shared secrets configuration, such as Kubernetes secrets
2. add a new key, defaulting to "conf" when not present:

    secrets=[conf,kubernetes,vault,...?]

3. add a new subtree to the config for each secret config, e.g.:

    kubernetes-secrets:
       secretname: 
       secretdir:

4. Add a flag for each password entry to indicate the key in the secrets:

       superuser:
          username: #supername
          password: #superpassword

Questions:

* does this make sense?
* what token can we use to indicate a shared secret lookup key?

Notes:

* I will do the implementation of the above for Kubernetes.  Implementing it for other shared secret tools will be up to someone else.

**Comment by feikesteenbergen** [comment]
> 1. support shared secrets configuration, such as Kubernetes secrets

+1, we currently use AWS and use a their infrastructure to decrypt secrets. We've been thinking of creating something like this.

> 2. add a new key, defaulting to "conf" when not present:

Makes sense, I myself was thinking of `plain` vs `conf`, but your proposal seems a better fit. I do have another proposal making it unnecessary to specify this globally.

3. add a new subtree to the config for each secret config, e.g.:

    kubernetes-secrets:
       secretname: 
       secretdir:

> 4. Add a flag for each password entry to indicate the key in the secrets:
>
> what token can we use to indicate a shared secret lookup key?

What if we do not use a special token, but something like this:
```yaml
superuser:
  username:
    kubernetes-secrets: secretname
  password:
    kubernetes-secrets: secretname
```

This would allow Patroni to read these values, if it is a `dict` it should use the secret provider and the specified key to retrieve the value.

> does this make sense?
Yes

We'd be happy to implement this for something like KMS on AWS.

**Comment by alexeyklyukin** [comment]
I'd agree with Feike that having an explicit way to distinguish between the encrypted and plain-text values is better than introducing some "magical" tokens, but I do't like the idea of converting the single-value keys like the username into the lists.

What if we change the keys themselves, and instead of doing

    username:
    password:
specify

    encrypted-username:
    encrypted-password:

for the encrypted values (the same way as PostgreSQL accepts ENCRYPTED PASSWORD when specifying a password for the user). That would keep the schema compatible with the current versions of Patroni, since the plain text values will still go into the "username" and "password" keys. In addition, it would also allow us to encrypt other values, not just usernames and passwords.

**Comment by feikesteenbergen** [comment]
```yaml
encrypted-value: value
```

Would work for me as well, might be the cleanest solution.

**Comment by jberkus** [comment]
I don't know how clean it will be; we're not very good about consolidating where we access username/password information for the database credentials.  I suspect that there will be some debugging involved here.

Also, I don't think "encrypyted-value" is a good key, because you're not supplying a value, your supplying a key.  Note that Kubernetes secrets are supplied unencrypted inside the container, but that's not a serious objection to the name.

An alternative "zeroconf" version of this is to have preset key names for the shared secrets implementations.  For example, if we required that all of the kubernetes secrets have specfic names, all the user would need to supply is the secrets filename and location.  That would definitiely be more user-friendly, but might not map well to other solutions.

**Comment by jberkus** [comment]
Thoughts on my "zeroconf" proposal above?  I have no idea what the AWS secrets look like.

**Comment by CyberDem0n** [comment]
Hi Josh, recently we implemented possibility to configure a lot of thing via environment variables (including all kind of passwords).
All possible environment variables are listed in [documentation](https://github.com/zalando/patroni/blob/master/docs/ENVIRONMENT.rst)
[Here](https://github.com/zalando/patroni/blob/8ddb5908f29cd6338f2bae99e57d481bbd3afb9f/docker/entrypoint.sh#L83) you can find an example how to use them.
Taking into account that [dynamic configuration](https://github.com/zalando/patroni/blob/master/docs/dynamic_configuration.rst) is already in master, patroni.yml could be really small.
If you are creating the new cluster it must contain only``bootstrap`` section. Everything else can be configured with ENV.

**Comment by jberkus** [comment]
Yeah, closing this one, because I think the new ENV works as well as anything we can expect.

Just to clarify: if I have enough ENV set, I don't need a yml file at all?

**Comment by CyberDem0n** [comment]
> Just to clarify: if I have enough ENV set, I don't need a yml file at all?

If you are joining new node to existing cluster, yes, it's possible to do it without yml.

**Comment by jberkus** [comment]
OK, closing this in favor of this issue: #224

Bootstrap section?

**Comment by CyberDem0n** [comment]
> Bootstrap section?

Yep, https://github.com/zalando/patroni/blob/master/postgres0.yml#L15

It is needed only for initializing of a new cluster. It contains some settings for ``initdb``, ``pg_hba``, users which needs to be created after initdb and ``dcs``. It will write into the given configuration store (key=``/<namespace>/<scope>/config``) content of ``bootstrap.dcs``. All other instances of the cluster using value from ``config`` for configuring itself.
