### ISSUE TITLE
Multiple Synchronous Standby Databases Support

### ISSUE THREAD

**Issue by kmsarabu** [zalando/patroni#1307]
Our current setup includes one master and 3 standby databases (2 standbys are in synchronous mode and 1 on async). The parameter synchronous_commit on master is set to REMOTE_APPLY. This is to guarantee that there is absolutely zero data-loss in case of a failover. We are currently using RepMgr for High Availability and looking into Patroni. 

Does Patroni Support this setup? especially master operating with 2 synch and 1 async standby?

e.g.:
synchronous_standby_names = '2 (*)'
synchronous_commit = remote_apply

Per doc, it appears that it doesn't dynamically change synchronous_standby_names out of the box during database failover/switchover? 

ref:
https://patroni.readthedocs.io/en/latest/replication_modes.html#synchronous-mode

**Comment by CyberDem0n** [comment]
> Does Patroni Support this setup? especially master operating with 2 synch and 1 async standby?

Well, it depends.
From the perspective of the configuration you are free to set whatever you want to the `synchronous_standby_names` and `synchronous_commit`, but...
1. When there are 2 sync and 1 async we don't really know which one is async. In case if the primary and both sync replicas failed Patroni will highly likely promote the remaining replica unless the sync_mode is used.
2. It is possible to change the `synchronous_commit` setting per transaction.

> Per doc, it appears that it doesn't dynamically change synchronous_standby_names

If you set `synchronous_mode: true`, Patroni on the primary will pick one of the replicas and put its name into synchronous_standby_names. In the case of primary failure only this replica will be allowed to take it over. If both, the primary and sync replica are failed together, non of the other nodes will be automatically promoted.

**Comment by kmsarabu** [comment]
> 1. When there are 2 sync and 1 async we don't really know which one is async. In case if the primary and both sync replicas failed Patroni will highly likely promote the remaining replica unless the sync_mode is used.
We intend to use synchronous_mode on in Patroni configuration.

> 2. It is possible to change the `synchronous_commit` setting per transaction.
No. None of our applications manipulates synchronous_commit at session level.

> If you set `synchronous_mode: true`, Patroni on the primary will pick one of the replicas and put its name into synchronous_standby_names. In the case of primary failure only this replica will be allowed to take it over. If both, the primary and sync replica are failed together, non of the other nodes will be automatically promoted.

Does Patroni failover to either one of the sync standby node if master db crash & when the following settings are used in master's Patroni yaml file? please note that there are 3 standbys in this case, 2 sync and 1 async. Thanks.
...
synchronous_mode: true
parameters:
 synchronous_commit: "remote_apply"
 synchronous_standby_names: "2 (*)"
....

**Comment by CyberDem0n** [comment]
Most likely one of the sync standbys will become the new primary in case of failover, but as I explained earlier the main issue here is that we don't know exactly which 2 out of 3 were synchronous at the moment when the primary failed.
The https://github.com/zalando/patroni/pull/672 is aiming to slove this problem and implement the support of quorum commit.

P.S. If you set `synchronous_mode: true`, Patroni will manage synchronous_standby_names for you and put there just one name.
