### ISSUE TITLE
Nodes fail to start when master node is powered off

### ISSUE THREAD

**Issue by manishps824** [zalando/patroni#1310]
We have a 3 node setup as follows:
- 3 VMs. Each node has patroni running. Each node has etcd running. 
- Sync mode is on. 
- The archive logs storage is attached to the node that is the master. 

When we power off the master VM, all the other nodes immediately go into 'start failed' mode and then fail to start by showing following errors:

2019-11-28 09:57:11.076 GMT [20376] FATAL:  the database system is starting up
ssh: connect to host 10.15.115.11 port 22: No route to host^M
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.2]
2019-11-28 09:57:11.244 GMT [20355] FATAL:  could not restore file "00000011.history" from archive: child process exited with exit code 255
2019-11-28 09:57:11.244 GMT [20352] LOG:  startup process (PID 20355) exited with exit code 1
2019-11-28 09:57:11.244 GMT [20352] LOG:  aborting startup due to startup process failure
2019-11-28 09:57:11.244 GMT [20352] LOG:  database system is shut down

Following is the patroni.yml

`namespace: /service/
scope: AK9EI5UHFA
name: host_1

log: 
  level: DEBUG
  dir: /var/log/patroni

restapi:
    connect_address: 10.15.115.11:8679
    listen:          10.15.115.11:8679

etcd:
    protocol: http
    hosts: 10.15.115.11:2379,10.15.115.12:2379,10.15.115.13:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: "on"
    synchronous_mode_strict: "on"
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: hot_standby
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 10
        max_replication_slots: 10
        wal_log_hints: on
        config_file: /pg_data/postgresql.conf
        archive_mode: "on"
        archive_timeout: 1800s
        max_connections: 100
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        track_commit_timestamp: off
        archive_command: 'rsync -e "ssh -o StrictHostKeyChecking=no" -a %p postgres@10.15.115.12:/home/postgres/postgres_archive_logs//%f'
      recovery_conf:
        restore_command: 'rsync -e "ssh -o StrictHostKeyChecking=no" postgres@10.15.115.12:/home/postgres/postgres_archive_logs//%f %p'

  initdb:  
  - encoding: UTF8
  - data-checksums

  pg_hba: 
  - host all all 0.0.0.0/0 md5
  - host replication rep_user 10.15.115.11/32 trust
  - host replication rep_user 10.15.115.12/32 trust
  - host replication rep_user 10.15.115.13/32 trust

postgresql:
  listen: localhost,10.15.115.11:5432
  connect_address: 10.15.115.11:5432
  data_dir: /pg_data
  bin_dir:  /usr/pgsql-10.4/bin
  pgpass: /tmp/pgpass0
  authentication:
    superuser:
      username: postgres
      password: Welcome123$
    replication:
      username: rep_user
      password: Welcome1234$
  parameters:
    unix_socket_directories: '.'
  custom_conf: /home/postgres/pg_params.conf

watchdog:
  mode: automatic # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false`
[patroni.txt](https://github.com/zalando/patroni/files/3901937/patroni.txt)

Observations:
1) This does not happen when there is absolutely no data written into the DB.
    When there is some load and some data generated this is seen. The load does not have to be 
    active at the time the VM is powered off.
2) This is also only seen when the node being powered off is 10.15.115.12 and its the master.
If some other node is master, we don't see this issue.

Any guidance is appreciated.

**Comment by CyberDem0n** [comment]
```
ssh: connect to host 10.15.115.11 port 22: No route to host^M
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.2]
2019-11-28 09:57:11.244 GMT [20355] FATAL: could not restore file "00000011.history" from archive: child process exited with exit code 255
```

Your restore_command is failing, this is not a Patroni issue.

**Comment by amit1995sharma** [comment]
@CyberDem0n 
postgres@10.15.115.12:/home/postgres/postgres_archive_logsis is in the Master ... 
if the master is powered off then the **sync standby** node should automatically come up 
 which is not happening in this case.
Is there any improvement required in the config.

**Comment by manishps824** [comment]
@CyberDem0n You are correct. The restore command fails because the archive location was on the same VM that gets powered off. 
In general is it an expectation that the archive location MUST always be available for the failover to work?

**Comment by CyberDem0n** [comment]
> then the sync standby node should automatically come up

I don't see any proof (logs) here that the sync standby wasn't promoted.

> In general is it an expectation that the archive location MUST always be available for the failover to work?

How do you think? Do you really want to have SPoF here?
