### ISSUE TITLE
Basebackup performed over insecure connection

### ISSUE THREAD

**Issue by geokala** [zalando/patroni#1320]
It appears that the built-in basebackup call is still performed over an insecure connection, even when sslmode=verify-full and sslrootcert=/path/to/cert are set for the replication user.

Dumping the conn_url, user_options, and env when triggering a reinit showed that basebackup used:
conn_url: postgres://replicator@192.0.2.120:5432/postgres
user_options: []
env: {'LANG': 'en_US.UTF-8', 'SHELL': '/bin/bash', 'PGPASSFILE': '/var/lib/patroni/pgpass', 'LOGNAME': 'postgres', 'USER': 'postgres', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin', 'HOME': '/var/lib/pgsql'}

**Comment by geokala** [comment]
Side note: I suspect this can be fixed by forcing some env var settings, which I'll be testing shortly, but it'd be nice if it used the secure settings that were already specified for the replication user.

**Comment by geokala** [comment]
The workaround for this is to supply the following env vars when running patroni:
PGSSLMODE=verify-full
PGSSLROOTCERT=/path/to/cert

**Comment by CyberDem0n** [comment]
@geokala you are absolutely right, we have to fix it.

**Comment by geokala** [comment]
Sounds good!

Setting the above env vars when running patroni (e.g. in an EnvironmentFile if using a systemd service) does appear to do the right thing, in that it invokes the pg_basebackup command with the appropriate env vars so it can at least be mitigated by that.

Thanks for your quick response!
