### ISSUE TITLE
PITR under split brain scenario using patroni

### ISSUE THREAD

**Issue by gowtham500** [zalando/patroni#1323]
Hello team,

I have a 3 node setup node 1, node2 and node 3 with patroni and pgbackrest. node 1 was master.
Patroni was setup successfully and backups were successful using pgbackrest.

I wanted to simulate a split brain scenario. node 1 is current master. Although this is a manual arrived state , I still wanted to check how this works.

1. I stopped patroni on node 3. 
2. Removed standby.signal file. 
3. Started postgresql manually.
4. Created a table on node 3. 
5. stopped psotgresql manually on node 3.
6. Started patroni on node 3.
7. patroni tried to do pg_rewind and it seems to be doing it continuously, it didnt stop.
pg_rewind is unable to switch back the timeline.

2019-12-06 07:01:40,333 INFO: Local timeline=123 lsn=8/810001B0
2019-12-06 07:01:40,428 INFO: master_timeline=122

This was the recovery.conf setting

recovery_target = 'immediate'
recovery_target_action = 'promote'
recovery_target_timeline = 'latest'
restore_command = '/bin/pgbackrest --stanza=pgadmin archive-get %f %p

Now I wanted to change the recovery_target_timeline to the timeline number of the existing master instead of latest.
and used patronictl -c /etc/patroni/stampede.yml edit-config to do that.

recovery_target_timeline = '122'

Now i restarted patroni and still got the same error. I used the native pgbasebackup to create the replica here.

I checked the contents of data directory and did vi postgresql.conf and found that the line

recovery_target_timeline = 'latest'.

I am unable to change this to 122.

At this point i decided to restore the entire cluster from previous back.

1. Stopped patroni on all nodes.
2. Wiped data directories on all nodes.
3. Simulated race condition and deleted the initialize key on consul.
4. Patroni bootstrapped (custom bootstrap using pgbackrest) and created a master node with a new timeline.

5. I was happy at this stage and tried to start patroni only on node 2. My expectation was i will get a new replica (i didnt specify any custom methods - so its used pg_basebackup) and created a new replica for me on node 2.

6. While node came up i saw below error.

2019-12-06 07:19:22.825 UTC [29220] FATAL:  highest timeline 122 of the primary is behind recovery timeline 123
2019-12-06 07:19:23.656 UTC [29227] FATAL:  highest timeline 122 of the primary is behind recovery timeline 123
2019-12-06 07:19:28.659 UTC [29248] FATAL:  highest timeline 122 of the primary is behind recovery timeline 123

7. This brought me the original case where i wanted to change the recovery_target_timeline to the timeline of the current master.

Can you please let me know as to how to recover from this scenario

**Comment by CyberDem0n** [comment]
How are the things you've done correlate with the issue title?

**Comment by gowtham500** [comment]
> How are the things you've done correlate with the issue title?

Sorry for the confusion, now changed the headline.

**Comment by gowtham500** [comment]
@CyberDem0n  Can you please help here. Headline has been changed.

**Comment by CyberDem0n** [comment]
> This brought me the original case where i wanted to change the recovery_target_timeline to the timeline of the current master.

There is no way to change recovery_taget_timeline, Patroni will always enforce it to be latest.
Why? Let's imagine it is set to something custom, 122, it will even start working, but after the first failover the new primary will get the new timeline, but remaining replicas will still use 122 and will not receive any changes.


> While node came up i saw below error.

It happens because the replica is restoring history files from the archive.
After the PITR is complete all nodes must use the new directory for archive/recovery.
