### ISSUE TITLE
Kuberentes + Etcd?

### ISSUE THREAD

**Issue by le-duane** [zalando/patroni#1329]
Hi,

Is it possible to use etcd for leader election, but still utilize Patroni's ability to update Kubernetes objects tags for service configuration, etc? 

I'd like for our Patroni cluster to have members in at least 2 Kubernetes clusters, which I think means we cannot use Kubernetes as the DCS. 

Thanks!

**Comment by CyberDem0n** [comment]
It is possible to use callbacks to update labels, but...
How pods from one K8s cluster will access pods in the other cluster? It requires at least ingress and really complicates the setup.

**Comment by le-duane** [comment]
Thanks @CyberDem0n, I will need to look into that!

Regarding ingress: there are some CNIs that create pod IPs which are routable outside the Kubernetes cluster e.g. AWS's.
