### ISSUE TITLE
Patroni 1.6.1 continuously restarting PostgreSQL 12 replica

### ISSUE THREAD

**Issue by caseyallenshobe** [zalando/patroni#1333]
The following configuration was working perfectly with Patroni 1.6.0, as installed from apt.postgresql.org repo, with PostgreSQL 12 as well as older PostgreSQL releases.

At some point the package on that repo was replaced by a 1.6.1 one, and once I upgraded to that, the standby nodes will not come online.  Patroni ends up looping forever restarting PostgreSQL about once every second.

I tried to use a manual install of Patroni using pip, and that did not work either.  I then tried a manual install of version 1.6.0 using pip, and that is working, so it seem to be a problem introduced in 1.6.1.

Attached is my Patroni YML, the Patroni startup log, and what PostgreSQL logs each time it is started.
[patroni.zip](https://github.com/zalando/patroni/files/3957346/patroni.zip)

**Comment by caseyallenshobe** [comment]
Working with Alexander Kukushkin on Slack, this can be worked around by putting the restore_command into postgresql.parameters.restore_command in Patroni's YML.

**Comment by CyberDem0n** [comment]
Or in other words archive_cleanup_command, promote_trigger_file, recovery_end_command, recovery_min_apply_delay, and restore_command should not be used for comparison if they are not defined in the patroni config but defined in the configs other than postgresql.auto.conf and postgresql.conf
