### ISSUE TITLE
Question: Can we mask passwords in stampede.yml 

### ISSUE THREAD

**Issue by gowtham500** [zalando/patroni#1340]
Hello team,

Are there are any methods by which we can mask the passwords in postgresql.authentication section?
I read about the .pgpass file, but still passwords in plain text. 

1. If we remove the passwords, after patroni configures a cluster, will this cause a problem during bootstrapping or creating replicas in future ?
[or]
2. Are there any methods by which we can mask the password ?

**Comment by jpuris** [comment]
Patroni needs to be able to connect to the cluster to fetch various stats to be able to do what it does.

_Your options_
- Restrict the read permissions to the patroni conf file
- Use `.pgpass` with appropriate permissions
- Configure clusters `pg_hba.conf` with `trust` as auth method
- ???
