### ISSUE TITLE
If Patroni can't access Consul it will restart postgres read-only

### ISSUE THREAD

**Issue by invin12** [zalando/patroni#1346]
Hi all,
I have a 2 node Patroni cluster with Consul DCS. 
As I know, patroni use only one Consul server, so If Consul leader switch to other node, patroni loose DCS information. To solve this issue, I install local consul agents on every patroni node. Everything work fine. 
But when I stop local consul agent on patroni leader, patroni restart former leader in read-only. And old replica can't became new leader with a such logs -
Dec 26 11:57:40 app2.local patroni[24874]: 2019-12-26 11:57:40,966 INFO: Got response from app1.local http://172.28.128.122:8008/patroni: {"state": "running", "postmaster_start_time": "2019-12-26 08:52:36.406 UTC", "role": "replica", "server_version": 110006, "cluster_unlocked": true, "xlog": {"received_location": 503316632, "replayed_location": 503316632, "replayed_timestamp": null, "paused": false}, "timeline": 22, "database_system_identifier": "6774361730750817920", "patroni": {"version": "1.6.3", "scope": "postgresql-patroni-cluster"}}
Dec 26 11:57:41 app2.local patroni[24874]: 2019-12-26 11:57:41,057 INFO: Wal position of app1.local is ahead of my wal position
Dec 26 11:57:41 app2.local patroni[24874]: 2019-12-26 11:57:41,067 INFO: following a different leader because i am not the healthiest node

And now, I have 2 servers in replica(read-only) state. That is not what I want, is it possible only stop former Postgresql master on DSC connection error without restarting it in read-only? Without former Postgresql master old replica will became new master with no problems.

**Comment by CyberDem0n** [comment]
> But when I stop local consul agent on patroni leader, patroni restart former leader in read-only

This is expected behavior, postgres should not be running as a primary without the leader lock in DCS.

> And old replica can't became new leader

This is because the former primary is a bit ahead of this replica, and logs actually telling you about it: **Wal position of app1.local is ahead of my wal position**. There would be a guaranteed data loss if Patroni promote such replica.

> is it possible only stop former Postgresql master on DSC connection error without restarting it in read-only?

Yes, you just have to stop patroni on the primary. The consul agent MUST be always running.
I would even recommend to do the `patronictl switchover` before stopping it.

**Comment by invin12** [comment]
> Yes, you just have to stop patroni on the primary. The consul agent MUST be always running.
> I would even recommend to do the `patronictl switchover` before stopping it.

Thank you for your reply. Current behavor - patroni stop and then start former master in read-only on DCS connection error. It would be better for me just stop former master without start it in read-only until DCS will became reachable again. Is it possible to make a such patroni config?

**Comment by CyberDem0n** [comment]
What problem are you trying to solve?

**Comment by invin12** [comment]
> What problem are you trying to solve?
My test installation is a two-node patroni cluster(psql 11.2) without any client connections. As I can see, cluster is full-replicated
**master** -
[test@app1 ~]# curl -s http://172.28.128.123:8008/replica | jq '.xlog, .timeline'
{
  "location": 201327016
}
12

**slave** -
[test@app2 ~]# curl -s http://172.28.128.122:8008/replica | jq '.xlog, .timeline'
{
  "received_location": 201327016,
  "replayed_location": 201327016,
  "replayed_timestamp": null,
  "paused": false
}
12

Now, I stop consul agent on master node. Patroni restart postgresql on former master with old timeline but with a new wal location -
[test@app1 ~]# curl -s http://172.28.128.123:8008/replica | jq '.xlog, .timeline'
{
  "received_location": 218103960,
  "replayed_location": 218103960,
  "replayed_timestamp": null,
  "paused": false
}
12

also, no changes on former slave -
[test@app2 ~]# curl -s http://172.28.128.122:8008/replica | jq '.xlog, .timeline'
{
  "received_location": 201327016,
  "replayed_location": 201327016,
  "replayed_timestamp": null,
  "paused": false
}
12

Now I have a strange situation - former slave can't became a master because it see a node with a  wal position ahead of it own. And former master also can't became a master because it can't connect to DCS. 
As I said, there is no client connections and transactions on DB, but former master change wal position after restart and it was not replicated to slave. Is it's a normal postgresql behaviour or my misconfiguration?

**Comment by CyberDem0n** [comment]
> Now, I stop consul agent on master node.

Can you please explain why are you doing that? Consul agent is a dependancy and in case if it stopped or crashed it must be immediately restarted.

**Comment by invin12** [comment]
> > Now, I stop consul agent on master node.
> 
> Can you please explain why are you doing that? Consul agent is a dependancy and in case if it stopped or crashed it must be immediately restarted.

I'm tryin to test all possible failures before any production deployment. Consul started as a systemd-service, and systemd will restart it when it crash, but it can hang or something else. It`s a single point of failure. I have a full-operabable second node, but without consul on first node all cluster is down. I don`t like it.

**Comment by CyberDem0n** [comment]
> I dont like it.

The reality is that WAL location on the former master is ahead of the old replica. Promoting the replica in such a situation is accepting the **data loss**. Patroni will not do it automatically under any circumstances.

The big question is why the old primary is ahead. If the DCS is not accessible Patroni does a "fast" shutdown of the postgres. It gives a chance to other replicas to receive all available WAL till the very last bit. For some reason it didn't happen. Why?
My only guess that you didn't set `consul.checks: []` in the patroni.yaml, therefore the leader session is invalidated immediately after you stopped the agent. Documentation for the reference: https://patroni.readthedocs.io/en/latest/SETTINGS.html#consul

**Comment by invin12** [comment]
Yes, I don't set consul checks. But I don't think that it can help us
Other test with a command -
logger $(date) && systemctl stop consul

Consul was stopped after a second(18:23:09)
Dec 26 18:23:08 app2.local vagrant[30979]: Thu Dec 26 18:23:08 MSK 2019
Dec 26 18:23:09 app2.local consul[30891]: 2019/12/26 18:23:09 [INFO] serf: EventMemberLeave: ocs-app2.local 172.28.128.123
Dec 26 18:23:09 app2.local consul[30891]: serf: EventMemberLeave: ocs-app2.local 172.28.128.123

Patroni stopped postgres after 15seconds(18:23:23) -

Dec 26 18:23:23 app2.local patroni[24612]: 2019-12-26 18:23:23,401 ERROR: Error communicating with DCS
Dec 26 18:23:23 app2.local patroni[24612]: 2019-12-26 18:23:23,479 INFO: closed patroni connection to the postgresql cluster

But after it, patroni **immediately** start postgresql -  

Dec 26 18:23:23 app2.local patroni[24612]: 2019-12-26 18:23:23,491 DEBUG: Starting postgres: postgres -D /var/lib/pgsql/11/data/ --config-file=/var/lib/pgsql/11/data/postgresql.conf --listen_addresses=172.28.1
28.123 --port=5432 --cluster_name=postgresql-patroni-cluster --wal_level=replica --hot_standby=on --max_connections=200 --max_wal_senders=10 --max_prepared_transactions=0 --max_locks_per_transaction=64 --track_com
mit_timestamp=off --max_replication_slots=10 --max_worker_processes=8 --wal_log_hints=on
Dec 26 18:23:23 app2.local patroni[24612]: 2019-12-26 15:23:23.650 UTC [31012] LOG:  listening on IPv4 address "172.28.128.123", port 5432
Dec 26 18:23:23 app2.local patroni[24612]: 2019-12-26 18:23:23,651 INFO: postmaster pid=31012

Maybe I will be better to make some delay before stop and start. I think former slave doesn't have time to get all available WALs.

**Comment by CyberDem0n** [comment]
> I think former slave doesn't have time to get and apply all available WALs.

There are no slaves in postgres. The replica doesn't have a chance to receive the WAL, because on the same second as you stopped the consul agent on the primary it will be notified that the leader has gone. Therefore it removes `primary_conninfo` from the configuration and restarts postgres. It is no longer streaming from the old primary.

> Yes, I don't set consul checks. But I don't think that it can help us

Just do it... There were very-very-very-very good reasons to implement it. You can read https://github.com/zalando/patroni/issues/522 for more details.

**Comment by invin12** [comment]
> Just do it... There were very-very-very-very good reasons to implement it. You can read #522 for more details.

I'm sorry for the question -

Checks was added to consul section -

consul:
  host: 127.0.0.1:8500
  checks: []

patroni was restarted on both nodes, but still serf-checks.
curl -s 127.0.0.1:8500/v1/health/service/postgresql-patroni-cluster | jq .[].Checks[].CheckID
"serfHealth"
"service:postgresql-patroni-cluster/app1.local"
"serfHealth"
"service:postgresql-patroni-cluster/app2.local"

As I can see through wireshark, patroni didn't change checks field in consul connection string -

JavaScript Object Notation: application/json
    JSON compact form: [...]
    Array
        Object
            Member Key: ID
            Member Key: Name
            Member Key: Node
            Member Key: Checks
                **Null value
                Key: Checks**
            Member Key: LockDelay
            Member Key: Behavior
            Member Key: TTL
                String value: 15.0s
                Key: TTL
            Member Key: CreateIndex
            Member Key: ModifyIndex

What should I do for correct patroni reconfiguration?

**Comment by CyberDem0n** [comment]
It seems that you are mixing two different concepts, `session` and `service`.
Just do `curl -s 127.0.0.1:8500/v1/session/list` and see the `"Checks": []`

**Comment by invin12** [comment]
> curl -s 127.0.0.1:8500/v1/session/list

curl -s 127.0.0.1:8500/v1/session/list | jq .[].Checks
null
null
I guess it should be empty array, not null

**Comment by invin12** [comment]
Everything works good, now. Thank you CyberDem0n!
Little investigation.
If I stop consul agent through systemd, it send
serf: EventMemberLeave: app2.local 172.28.128.123
and session destroys immediately. No matter of checks and ttls values. It was a main problem - gracefull shutdown of consul agent.

But If I kill -9 consul, no serf EventMemberLeave will bi sent and session(with a lock) will be destroyed with configured ttls. PostgreSQL replica will have enought time to recieve and apply all wal logs.
