### ISSUE TITLE
Question: WAL Shipping for Standby Cluster

### ISSUE THREAD

**Issue by cdloh** [zalando/patroni#1352]
Not really a bug report but looking for advice for people that have used Patroni with a standby cluster before.

I have two DCs each with a Patroni cluster running Postgres 10.

The second DC has the Patroni cluster running in standby mode replicating from the master.

This is working fairly well in testing however every so often streaming replication falls behind due to various issues and then it can't catchup.

I'm looking for advice / best recommendations around WAL log shipping and how others have done this in the past.

My initial thoughts are just to send the WAL logs from the Master to all 3 other Postgres servers and let them cleanup the WAL logs themselves with the correct archive_cleanup command. But then if promotions is needed due to failover in the Master cluster I'm concerned around any issues with that.

Either way looking for advice. Thanks in advance.

**Comment by CyberDem0n** [comment]
I would advise to not reinvent the wheel, but use existing battled-tested proven to be  working solution, like pgBackRest, wal-e, wal-g, barman

**Comment by cdloh** [comment]
Would you recommend them to be used in conjuction with Patroni or in place of?

**Comment by neale-bpm** [comment]
It would be good to read the docs.  Patroni works with WAL shipping solutions.

In particular, see https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#standby-cluster.
