### ISSUE TITLE
New leader was not appointed when old leader disk space was full

### ISSUE THREAD

**Issue by komal-lunkad** [zalando/patroni#1356]
Leader machine disk space was full. So ideally some other machine from the cluster should be appointed as a leader. Also the machine which had no space was showing in running state. So how to handle such scenarios where when the leader machine space becomes full, that machine should either stop or remove itself from the cluster?

**Comment by CyberDem0n** [comment]
You MUST monitor cluster health including disk space.

**Comment by komal-lunkad** [comment]
> You MUST monitor cluster health including disk space.
How to do that?

**Comment by CyberDem0n** [comment]
There are dozens of monitoring solutions available, just pick one.
