### ISSUE TITLE
Question: patroni config customize postgres log output file and wal_level

### ISSUE THREAD

**Issue by Ecako** [zalando/patroni#1360]
Hello, I have a couple of questions on the config aspect of patroni.

1.
I have many postgres servers running on a large box and would like to configure where the server logging goes when using patroni. Previously I was using the `-l` arg when launching my postgres server directly when using `pg_ctl` but now that patroni takes care of that I can't seem to find where I can customize the log location.

I have tried setting `log_directory` and `log_filename` in both the patroni config and the `postgresql.base.conf` but it did not take effect. Is it possible to customize where the log goes with patroni?

2.

My wal_level config is set to `hot_standby`. However when I launch the postgres server with patroni I see that the auto generated postgresql.conf file sets this to `replica` instead which is the equivalent of `hot_standby`. This is only available from postgres 9.6 and higher as far as I can see. Is it possible to run patroni on 9.5? If so, how can I ensure the wal_level is correctly configure to hot_standby without patroni overwriteing it to replica?

Thanks!

**Comment by CyberDem0n** [comment]
Logs:
```
postgresql:
  parameters:
    log_directory: ....
```

> sets this to replica

In 9.6 `hot_standby` was renamed to `replica`.

> Is it possible to run patroni on 9.5?

It is even possible to run it with 9.3, just provide the correct configuration

**Comment by Ecako** [comment]
ahh i was missing setting `logging_collector: on` to get it to properly work. Thanks so much for the quick response!
