### ISSUE TITLE
Password logging on user creation with passwordcheck

### ISSUE THREAD

**Issue by benjaminjb** [zalando/patroni#1365]
I'm using a postgres image with the passwordcheck library preloaded; and with a password generator to create a random password for the superuser and replication user for patroni. 

One time the password generator created a password that would not pass the passwordcheck requirements, and PSQL printed out the error (reasonable) and the statement that failed, producing something like:

`ERROR:  password is too short` 
`STATEMENT:  CREATE ROLE "hello" WITH LOGIN CREATEROLE CREATEDB PASSWORD 'world'`

I noticed that `create_or_update_role` does a SQL query to create/alter roles (see https://github.com/zalando/patroni/blob/master/patroni/postgresql/bootstrap.py#L303-L313) and I was wondering if there was ever any discussion about suppressing the error logs just for that query to prevent logging passwords. (Even if the password is rejected, I feel it's better to avoid printing any passwords.)

For reference on PSQL printing passwords, see https://www.postgresql.org/message-id/CAHJZqBDe1-oiYtdh5pcWLAhr3jsDMFQg4miv3PYADH3YWKqZ2w%40mail.gmail.com

**Comment by CyberDem0n** [comment]
Indeed, we need to `set log_statement = none` before creating users.
