### ISSUE TITLE
patronictl flush doesn't have a means to flush a scheduled switchover

### ISSUE THREAD

**Issue by caseyallenshobe** [zalando/patroni#1376]
Is there any way to cancel a scheduled switchover?  `patronictl flush` seems to only work for scheduled restarts.

**Comment by BernieRedAle** [comment]
As a workaround, you can schedule the switchover again, but choose a date far, far in the future.  Before that date, perform a manual switchover/switchback (non-scheduled) and the scheduled one will be removed.
