### ISSUE TITLE
After upgrade from 1.6.1 to 1.6.3

### ISSUE THREAD

**Issue by bimcas** [zalando/patroni#1381]
Hello,
I upgraded my patroni version from 1.6.1 to 1.6.3 and after that when I'm trying to add new cluster member,  rebootstrap slave node, I'm getting error message:

INFO: trying to bootstrap from leader
pg_basebackup: too many command-line arguments (first is "user=replication")
Try "pg_basebackup --help" for more information.
ERROR: Error creating replica using method custom_waldir_basebackup: /etc/patroni/custom_waldir_basebackup.sh exited with code=1
ERROR: failed to bootstrap from leader

I have PostgreSQL version 10.11. When I downgraded patroni to 1.6.1 again everything is OK. What is the problem with pg_basebackup?

Thanks.

**Comment by CyberDem0n** [comment]
The problem is with your wrapper script, you have to quote connection string when calling pg_basebackup: `--dbname="$connstr"`

**Comment by bimcas** [comment]
Now everything is OK. I quoted all variables in my script:
pg_basebackup  --pgdata="$C_DATADIR" --waldir="$C_WALDIR" --dbname="$C_CONNSTRING"

Thank you very much.
