### ISSUE TITLE
patronictl history related Question

### ISSUE THREAD

**Issue by chefun** [zalando/patroni#1382]
Hello Team,
"patronictl history" shows the history of switchovers/failovers in a Cluster, including a field "reason".
We would like to use this field for documentation of our maintenance. 
Is there a more convenient way to specify a reason than using  etcdctl set /service/<CLUSTERNAME>/history/ value ?
Thank you very much.

**Comment by CyberDem0n** [comment]
The "reason" is coming from the history file, which is generated by postgres during/after promote.
Patroni is not really relying on this value.
There is also no mechanism in Patroni to update it, moreover, whatever you put there manually by updating the corresponding key in DCS will be overwritten by Patroni after the next failover/switchover by whatever content is stored in the new history file.

**Comment by chefun** [comment]
Okay. Thank you for your fast reply.
