### ISSUE TITLE
API endpoints related to standby leader return wrong codes

### ISSUE THREAD

**Issue by caseyallenshobe** [zalando/patroni#1388]
The REST API endpoints that indicate that a node should be able to accept read-write transactions (e.g. `/read-write`, `/master`, etc.) return 200 for a standby leader, which is in fact read-only.  These should return 503.

The REST API endpoint `/standby-leader` returns 200 for a master node which is not a standby leader.  This should return 503.

Tested with Patroni 1.6.1.

**Comment by uspen** [comment]
For me too

**Comment by uspen** [comment]
Its a problem
