### ISSUE TITLE
cant see the secondary db on my member list patroni 

### ISSUE THREAD

**Issue by buluxan** [zalando/patroni#1389]
Hi all ,

i just tried setup patroni following  the tutorial online ,  its was succesfully when i ran on my primary server , i saw there was leader running there when i check using patronictl -c /etc/patroni.yml list , the problem came after i tried running patroni on db2  , i cant see the member list db2 on my primary db , but when i ran patronictl -c /etc/patroni.yml list in db2 i got the Leader running  , below is the logs on each servers  

DB1 logs patroni : 
================
db1-pgsql:/home/mbiz# tail -f /var/log/postgresql/patroni.log
2020-02-13 11:58:39,595 INFO: Lock owner: odoo-psql; I am odoo-psql
2020-02-13 11:58:39,598 INFO: no action.  i am the leader with the lock
2020-02-13 11:58:49,595 INFO: Lock owner: odoo-psql; I am odoo-psql
2020-02-13 11:58:49,598 INFO: no action.  i am the leader with the lock
2020-02-13 11:58:59,595 INFO: Lock owner: odoo-psql; I am odoo-psql
2020-02-13 11:58:59,598 INFO: no action.  i am the leader with the lock
2020-02-13 11:59:09,595 INFO: Lock owner: odoo-psql; I am odoo-psql
2020-02-13 11:59:09,598 INFO: no action.  i am the leader with the lock
2020-02-13 11:59:19,595 INFO: Lock owner: odoo-psql; I am odoo-psql
2020-02-13 11:59:19,598 INFO: no action.  i am the leader with the lock

DB2 logs patroni : 
================
db2-pgsql:/pgdata/data# tail -f /var/log/postgresql/patroni.log
2020-02-13 11:59:08,380 INFO: Lock owner: odoopsql1; I am odoopsql1
2020-02-13 11:59:08,382 INFO: no action.  i am the leader with the lock
2020-02-13 11:59:18,380 INFO: Lock owner: odoopsql1; I am odoopsql1
2020-02-13 11:59:18,382 INFO: no action.  i am the leader with the lock
2020-02-13 11:59:28,380 INFO: Lock owner: odoopsql1; I am odoopsql1
2020-02-13 11:59:28,382 INFO: no action.  i am the leader with the lock
2020-02-13 11:59:38,380 INFO: Lock owner: odoopsql1; I am odoopsql1
2020-02-13 11:59:38,382 INFO: no action.  i am the leader with the lock
2020-02-13 11:59:48,380 INFO: Lock owner: odoopsql1; I am odoopsql1
2020-02-13 11:59:48,382 INFO: no action.  i am the leader with the lock

YAML CONFIG 
================

scope: postgres
namespace: /db/
name: odoo-psql
restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.0.22.36:8008
consul:
        host: localhost:8500
        checks: []
        register_service: true

bootstrap:
    dcs:
        ttl: 100
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            use_slots: true
            parameters:
                    wal_level: replica
                    hot_standby: "on"
                    wal_keep_segments: 8
                    max_wal_senders: 5
                    max_replication_slots: 5
                    checkpoint_timeout: 30
initdb:
    - encoding: UTF8
    - data-checksums
pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.0.22.36/32 md5
    - host replication replicator 10.0.22.37/32 md5
    - host replication replicator 10.0.22.34/32 md5
    - host all all 0.0.0.0/0 md5
users:
        admin:
            password: admin
            options:
                - createrole
                - createdb
postgresql:
    listen: 0.0.0.0
    connect_address: 10.0.22.36:5432
    data_dir: /pgdata/data
    config_dir: /pgdata/data
    bin_dir: /usr/lib/postgresql/12/bin/
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: qwerty
        superuser:
            username: postgres
            password: qwerty
    parameters:
        unix_socket_directories: '/tmp'
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
log:
   dir: /var/log/postgresql
   level: INFO 

i put also the screenshoot 

<img width="691" alt="Screen Shot 2020-02-13 at 12 06 09" src="https://user-images.githubusercontent.com/7418412/74403279-4252cd00-4e59-11ea-82c5-81fae0118a01.png">

thx,
lookman

**Comment by buluxan** [comment]
<img width="691" alt="Screen Shot 2020-02-13 at 12 06 09" src="https://user-images.githubusercontent.com/7418412/74403279-4252cd00-4e59-11ea-82c5-81fae0118a01.png">

**Comment by CyberDem0n** [comment]
It is either `namespace` is defferent or consul is not clustered.

**Comment by buluxan** [comment]
> It is either `namespace` is defferent or consul is not clustered.

yes in db2 the namespace was different, i'm already changed it  , and then try run yaml file in db2 
the different logs error is came in patroni logs 
fyi my consul is cluster so i just setup agent on every node db1 n db2 postgres
=========
log patroni
=========
system ID mismatch, node odoo-psql1 belongs to a different cluster: 6792149796479795020 != 6792778940113894796
2020-02-13 14:58:34,771 INFO: Lock owner: odoo-psql; I am odoo-psql1 

also checking another consul ui =

<img width="1270" alt="Screen Shot 2020-02-13 at 15 32 09" src="https://user-images.githubusercontent.com/7418412/74415502-0f6b0200-4e76-11ea-8bb3-a843d415b4d3.png">

also checking Database system identifier was different db1 and db2 : 

<img width="944" alt="Screen Shot 2020-02-13 at 15 33 56" src="https://user-images.githubusercontent.com/7418412/74415643-578a2480-4e76-11ea-8d0e-3e4d5838e86c.png">

i'm still troubleshooting n googling  :)

**Comment by buluxan** [comment]
Hi ,
fyi i just left db2 running with current configuration and i try using db3 with fresh installation postgresql and consul agent  its seem looks good . i can see my member postgresql in patroni

<img width="1122" alt="Screen Shot 2020-02-13 at 16 53 41" src="https://user-images.githubusercontent.com/7418412/74422612-7641e880-4e81-11ea-901a-50d1e40157d2.png">

Database system identifier looks same now right now 

<img width="930" alt="Screen Shot 2020-02-13 at 17 03 25" src="https://user-images.githubusercontent.com/7418412/74423400-c5d4e400-4e82-11ea-9eb8-170283acd8b7.png">

next is try to failover , will close this , looks the problem in db2 is  i cant get same number database system identifier  should be same in db1 , looks need reinstall in db2 consul n postgreql

**Comment by buluxan** [comment]
hi CyberDem0n  ,

really appreciate if you have suggestion on  my issue  regarding the  in db2 cant get the same database system identifier from db1 

Thx,

**Comment by CyberDem0n** [comment]
I think it is a good time to learn how to use [search](https://github.com/zalando/patroni/issues?q=is%3Aissue+system+ID+mismatch+is%3Aclosed)

**Comment by buluxan** [comment]
> I think it is a good time to learn how to use [search](https://github.com/zalando/patroni/issues?q=is%3Aissue+system+ID+mismatch+is%3Aclosed)

hehehe okay thx u
