### ISSUE TITLE
Docker image does not exist

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#14]
https://os-registry.stups.zalan.do/acid/patroni-1.0

That's a 404.

I'm going to upload something to the docker hub, once I have it built.

**Comment by CyberDem0n** [comment]
$ docker pull os-registry.stups.zalan.do/acid/patroni:1.0

works like a charm.

**Comment by jberkus** [comment]
Ah, you might mention that that's a pull target only and there's no web page there, then.
