### ISSUE TITLE
[Question] Difference between pg restart with or without patronictl

### ISSUE THREAD

**Issue by stedounet** [zalando/patroni#1401]
Hi,

Sorry if it's already answered, could not find it

Patronictl (and patroni API) can restart postgres and it won't trigger failover. Restarting postgres via systemctl does not trigger failover as well for me.

My question is : 
Is the fact that I did not have a failover with systemctl a lucky coincidence linked to postgres restart speed ? Or is it actually handled by patroni,  checking if it's restarting properly and waiting for it to come online again without failover ?

Or in short, should I restrict myself to restart postgres with and only with patronictl/API ?

**Comment by CyberDem0n** [comment]
Having ability to control postgres with sysctl is wrong is the first place.
Init system should only start patroni and forget about postgres forever.

**Comment by stedounet** [comment]
I'm still what we could call junior, can you enlighten me on why I should not ?

**Comment by CyberDem0n** [comment]
1. Let's imagine that node running the primary has crashed and one of the replicas was promoted.
2. After the node was restarted the init system will start postgres as a primary again, while there is already another primary running [1].
3. You've got a split-brain situation.

Do I need to continue?

**Comment by stedounet** [comment]
Yes of course auto-restart is wrong in this case, I agree and this is not my case
I was more thinking in situations like restarts after changing a non-dynamic parameter, simple and plain manual restarts. Is it something patroni should always handle ?

To be precise, I need to understand risks to later "teach" what is the right ways to maintain patroni

**Comment by CyberDem0n** [comment]
In theory Patroni will notice that postgres was restarted and everything should be fine.
On practice I would always recommend performing restart via Patroni REST API or patronictl.
The scheduled restart feature makes it especially handy.

**Comment by stedounet** [comment]
Perfect that's all I need to know, thank you
