### ISSUE TITLE
Hello, ask about the Patroni configuration file 

### ISSUE THREAD

**Issue by cdy668** [zalando/patroni#1404]
My Patroni configuration file 
-----------------------------------
cat /etc/patroni/patroni.yml
scope: postgres-cluster
name: pgnode01
namespace: /service/
 
restapi:
  listen: 192.168.1.133:8008
  connect_address: 192.168.1.133:8008
etcd:
  hosts: 192.168.1.133:2379,192.168.1.121:2379,192.168.1.105:2379
 
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 10000
        superuser_reserved_connections: 5
        max_prepared_transactions: 10000
        huge_pages: try
        shared_buffers: 8192MB
        work_mem: 8MB
        maintenance_work_mem: 2GB
        effective_cache_size: 16GB
        checkpoint_timeout: 30min
        checkpoint_completion_target: 0.9
        min_wal_size: 4GB
        max_wal_size: 16GB
        wal_buffers: 16MB
.....................................................................
I know that I can modify my current configuration information through postgresql.base.conf，But I found that the configuration file seems to keep only part of the configuration information ，If I want to remove some of the configurations in patroni.yml, what should I do most quickly

**Comment by cdy668** [comment]
Sorry, I just checked the help document
Modify in this way：
patronictl - C / etc / Patroni / patroni.yml edit-config

**Comment by cdy668** [comment]
Patroni.yml has a higher priority, right? Then read postgresql.base.conf

**Comment by CyberDem0n** [comment]
Please read the documentation: https://patroni.readthedocs.io/en/latest/dynamic_configuration.html
