### ISSUE TITLE
PostgreSQL synchronous replication

### ISSUE THREAD

**Issue by alexeyshishkin01** [zalando/patroni#1409]
Hello, all!

two questions with the subject:

1)
the documentation says:
To enable a simple synchronous replication test, add the following lines to the parameters section of your YAML configuration files:
synchronous_commit: "on"
synchronous_standby_names: "*"

Is it possible to be more specific (example is always a good idea) what is 'parameters section'?

A snippet of my YAML file:

...
bootstrap:
    dcs:
        ttl: 100
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            use_slots: true
            parameters:
                wal_level: replica
                hot_standby: "on"
                wal_keep_segments: 5120
                max_wal_senders: 5
                max_replication_slots: 5
                checkpoint_timeout: 30

postgresql:
    listen: 0.0.0.0:5433
    connect_address: 127.0.0.1:5433
    data_dir: /var/lib/pgpro/std-12/data
    config_dir: /var/lib/pgpro/std-12/data
    bin_dir: /opt/pgpro/std-12/bin
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: patroni_replicator
            password: replicatorpassword
        superuser:
            username: patroni_superuser
            password: superuserpassword
    create_replica_methods:
        basebackup:
            checkpoint: 'fast'
    parameters:
        unix_socket_directories: '.'
...

it has two 'parameters' section - in 'bootstrap' and in 'postgresql' - which one shall I choose?

2)
I tried to put mentioned parameters in either of 'parameter' section - it doesn't work as expected - replication is 'async'

psql -c "show ..." does not show these parameters have been changed

replication goes 'sync' only if I fire 'alter system set ...' on cluster nodes

what do I do wrong?

**Comment by alexeyshishkin01** [comment]
the third question is similar to question №2, but in this case 'synchronous_mode' is used:

bootstrap:
    dcs:
        ttl: 100
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            use_slots: true
            parameters:
                wal_level: replica
                hot_standby: "on"
                wal_keep_segments: 5120
                max_wal_senders: 5
                max_replication_slots: 5
                checkpoint_timeout: 30
        synchronous_mode: true

and again 'async' replication instead of 'sync' is in place:

psql 'postgres://patroni_superuser:superuserpassword@myvm-std-02:5000/postgres' -x -c 'table pg_stat_replication'
-[ RECORD 1 ]----+------------------------------
pid              | 5200
usesysid         | 16423
usename          | patroni_replicator
application_name | myvm-std-02
client_addr      | 10.0.0.102
client_hostname  | myvm-std-02
client_port      | 41330
backend_start    | 2020-02-21 21:27:05.36608+00
backend_xmin     |
state            | streaming
sent_lsn         | 0/B000148
write_lsn        | 0/B000148
flush_lsn        | 0/B000148
replay_lsn       | 0/B000148
write_lag        |
flush_lag        |
replay_lag       |
sync_priority    | 0
sync_state       | async
reply_time       | 2020-02-21 21:31:27.478211+00
-[ RECORD 2 ]----+------------------------------
pid              | 5496
usesysid         | 16423
usename          | patroni_replicator
application_name | myvm-std-03
client_addr      | 10.0.0.103
client_hostname  | myvm-std-03
client_port      | 42012
backend_start    | 2020-02-21 21:30:12.217125+00
backend_xmin     |
state            | streaming
sent_lsn         | 0/B000148
write_lsn        | 0/B000148
flush_lsn        | 0/B000148
replay_lsn       | 0/B000148
write_lag        |
flush_lag        |
replay_lag       |
sync_priority    | 0
sync_state       | async
reply_time       | 2020-02-21 21:31:27.477918+00

what's wrong with it/me?

**Comment by CyberDem0n** [comment]
I would recommend you (actually insist) to read the documentation:
* https://patroni.readthedocs.io/en/latest/SETTINGS.html#bootstrap-configuration
* https://patroni.readthedocs.io/en/latest/SETTINGS.html#dynamic-configuration-settings
* https://patroni.readthedocs.io/en/latest/replication_modes.html#synchronous-mode

**Comment by alexeyshishkin01** [comment]
unfortunately, I was not able to find required info in the docs, including those you mention - hence my questions are there

the docs should be improved with more examples, imho

so, once again:

my YAML file has two 'parameters' section - in 'bootstrap' and in 'postgresql' - which one shall I choose to put mentioned 'synchronous*...' parameters into?

**Comment by CyberDem0n** [comment]
> Bootstrap configuration
dcs: This section will be written into /\<namespace>/\<scope>/config of the given configuration store after initializing of new cluster. The global dynamic configuration for the cluster.

> Under the bootstrap.dcs you can put any of the parameters described in the Dynamic Configuration settings and after Patroni initialized (bootstrapped) the new cluster, it will write this section into /\<namespace>/\<scope>/config of the configuration store. All later changes of bootstrap.dcs will not take any effect! If you want to change them please use either patronictl edit-config or Patroni REST API

**Comment by alexeyshishkin01** [comment]
unfortunately, this does not answer my question, it is really simple:

what section to put these parameters into:
synchronous_commit: "on"
synchronous_standby_names: "*"

I have two sections:

bootstrap:
    dcs:
        ttl: 100
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            use_slots: true
            parameters:
                wal_level: replica
                hot_standby: "on"
                wal_keep_segments: 5120
                max_wal_senders: 5
                max_replication_slots: 5
                checkpoint_timeout: 30

postgresql:
    listen: 0.0.0.0:5433
    connect_address: 127.0.0.1:5433
    data_dir: /var/lib/pgpro/std-12/data
    config_dir: /var/lib/pgpro/std-12/data
    bin_dir: /opt/pgpro/std-12/bin
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: patroni_replicator
            password: replicatorpassword
        superuser:
            username: patroni_superuser
            password: superuserpassword
    create_replica_methods:
        basebackup:
            checkpoint: 'fast'
    parameters:
        unix_socket_directories: '.'

the documentation should not be so unclear

what is PR, btw?

**Comment by caseyallenshobe** [comment]
The documentation covers all this well.

Read the page on Dynamic Configuration.  What is in postgresql.parameters in the YML on each node will override what is in the DCS, which will in turn override whatever is in the base.conf or custom_conf file.  The values in bootstrap are what gets stored into the DCS when a cluster is bootstrapped - when the first node in that cluster is started and there is no configuration in the DCS yet.

In my case, I have nothing at all in postgresql.parameters as I don’t want any per-node overrides and exclusively use the DCS to manage the configuration of the cluster.

**Comment by dminGod** [comment]
For people stumbling on this thread the query to the original question is:

- Bootstrap postgres section is used when initializing a new node.
- The next postgres section is the configuration you need to modify if you want to change the configuration in the existing node.
