### ISSUE TITLE
docs 1.6.3

### ISSUE THREAD

**Issue by alexeyshishkin01** [zalando/patroni#1410]
Hello, all!

the 1.6.3 documentation says:

1)
Some of the PostgreSQL parameters must hold the same values on the master and the replicas. For those, values set either in the local patroni configuration files or via the environment variables take no effect. To alter or set their values one must change the shared configuration in the DCS. Below is the actual list of such parameters together with the default values:
• max_connections: 100
• max_locks_per_transaction: 64
• max_worker_processes: 8
• max_prepared_transactions: 0
• wal_level: hot_standby
• wal_log_hints: on
• track_commit_timestamp: off

- 'wal_level: hot_standby'
- most probably you mean 'wal_level: replica'
- if so, pls. fix, if not, pls. explain

2)
For the parameters below, PostgreSQL does not require equal values among the master and all the replicas. However, considering the possibility of a replica to become the master at any time, it doesn’t really make sense to set them differently; therefore, Patroni restricts setting their values to the Dynamic configuration
• max_wal_senders: 5
• max_replication_slots: 5
• wal_keep_segments: 8

the 'ps -ef | grep postgres' output is
...
/opt/pgpro/std-12/bin/postgres
 -D /var/lib/pgpro/std-12/data
 --config-file=/var/lib/pgpro/std-12/data/postgresql.conf
 --listen_addresses=10.0.0.101
 --port=5433
 --cluster_name=mypatroni
 --wal_level=replica
 --hot_standby=on
 --max_connections=100
 --max_wal_senders=5
 --max_prepared_transactions=0
 --max_locks_per_transaction=64
 --track_commit_timestamp=off
 --max_replication_slots=5
 --max_worker_processes=8
 --wal_log_hints=on
...

it all means:
- 'hot_standby: on' is missing in the docs
- 'wal_keep_segments=8' is missing in the 'ps -ef ...' output
- why?

**Comment by CyberDem0n** [comment]
>    'wal_level: hot_standby'
>    most probably you mean 'wal_level: replica'
>    if so, pls. fix, if not, pls. explain

pls learn the history: https://www.postgresql.org/docs/9.6/release-9-6.html#AEN134720

> 'wal_keep_segments=8' is missing in the 'ps -ef ...' output
> why?

because you can/want to change it without a restart.

If you really want to update the documentation - just open a PR, asking it in the ultimate form by opening a tonne of issues this is not how it will work.
