### ISSUE TITLE
Data loss after hard reboot

### ISSUE THREAD

**Issue by acmzero** [zalando/patroni#1411]
We are using docker-compose as it is setup to run.

Last night we had to reboot the server that is hosting patroni, today after starting the docker images seems like the data from yesterday is missing, looking at the logs seems like patroni1 was the master now is patroni2 but patroni2 was behind patroni1.

Now patroni1 as a slave did pg_rewind and removed what was ahead of patroni2
I get the idea that data was reverted from the following log:
  **new timeline 5 forked off current database system timeline 4 before current recovery point 2A/70000098**
> {"log":"2020-02-21 13:09:25,248 INFO: Failed to import patroni.dcs.consul\n","stream":"stderr","time":"2020-02-21T13:09:25.249059942Z"}
{"log":"2020-02-21 13:09:25,267 INFO: Selected new etcd server http://etcd3:2379\n","stream":"stderr","time":"2020-02-21T13:09:25.376412421Z"}
{"log":"2020-02-21 13:09:25,967 WARNING: Postgresql is not running.\n","stream":"stderr","time":"2020-02-21T13:09:25.96774008Z"}
{"log":"2020-02-21 13:09:25,967 INFO: Lock owner: None; I am patroni1\n","stream":"stderr","time":"2020-02-21T13:09:25.967936748Z"}
{"log":"2020-02-21 13:09:26,035 INFO: doing crash recovery in a single user mode\n","stream":"stderr","time":"2020-02-21T13:09:26.035379403Z"}
{"log":"2020-02-21 13:09:35,643 INFO: Lock owner: None; I am patroni1\n","stream":"stderr","time":"2020-02-21T13:09:35.643852314Z"}
{"log":"2020-02-21 13:09:35,643 INFO: not healthy enough for leader race\n","stream":"stderr","time":"2020-02-21T13:09:35.643922572Z"}
{"log":"2020-02-21 13:09:35,872 INFO: doing crash recovery in a single user mode in progress\n","stream":"stderr","time":"2020-02-21T13:09:35.873092255Z"}
{"log":"2020-02-21 13:09:36,596 WARNING: Postgresql is not running.\n","stream":"stderr","time":"2020-02-21T13:09:36.596284541Z"}
{"log":"2020-02-21 13:09:36,596 INFO: Lock owner: patroni2; I am patroni1\n","stream":"stderr","time":"2020-02-21T13:09:36.596371068Z"}
{"log":"2020-02-21 13:09:36,601 INFO: Lock owner: patroni2; I am patroni1\n","stream":"stderr","time":"2020-02-21T13:09:36.601778322Z"}
{"log":"2020-02-21 13:09:36,612 INFO: Local timeline=4 lsn=2A/70000028\n","stream":"stderr","time":"2020-02-21T13:09:36.612797029Z"}
{"log":"2020-02-21 13:09:36,612 INFO: Lock owner: patroni2; I am patroni1\n","stream":"stderr","time":"2020-02-21T13:09:36.612954942Z"}
{"log":"2020-02-21 13:09:36,642 INFO: starting as a secondary\n","stream":"stderr","time":"2020-02-21T13:09:36.64256252Z"}
{"log":"2020-02-21 13:09:36,696 INFO: postmaster pid=36\n","stream":"stderr","time":"2020-02-21T13:09:36.697732776Z"}
{"log":"localhost:5432 - no response\n","stream":"stdout","time":"2020-02-21T13:09:36.704202802Z"}
{"log":"LOG:  database system was shut down at 2020-02-21 13:09:36 UTC\n","stream":"stderr","time":"2020-02-21T13:09:36.913122645Z"}
{"log":"LOG:  entering standby mode\n","stream":"stderr","time":"2020-02-21T13:09:36.913181333Z"}
{"log":"FATAL:  the database system is starting up\n","stream":"stderr","time":"2020-02-21T13:09:36.913464211Z"}
{"log":"LOG:  consistent recovery state reached at 2A/70000098\n","stream":"stderr","time":"2020-02-21T13:09:37.013027488Z"}
{"log":"LOG:  invalid record length at 2A/70000098: wanted 24, got 0\n","stream":"stderr","time":"2020-02-21T13:09:37.013042717Z"}
{"log":"LOG:  database system is ready to accept read only connections\n","stream":"stderr","time":"2020-02-21T13:09:37.013931881Z"}
{"log":"LOG:  fetching timeline history file for timeline 5 from primary server\n","stream":"stderr","time":"2020-02-21T13:09:37.017116712Z"}
{"log":"FATAL:  could not start WAL streaming: ERROR:  replication slot \"patroni1\" does not exist\n","stream":"stderr","time":"2020-02-21T13:09:37.030500189Z"}
{"log":"\u0009\n","stream":"stderr","time":"2020-02-21T13:09:37.030513089Z"}
{"log":"LOG:  new timeline 5 forked off current database system timeline 4 before current recovery point 2A/70000098\n","stream":"stderr","time":"2020-02-21T13:09:37.030651347Z"}
{"log":"FATAL:  could not start WAL streaming: ERROR:  replication slot \"patroni1\" does not exist\n","stream":"stderr","time":"2020-02-21T13:09:37.034581668Z"}
{"log":"\u0009\n","stream":"stderr","time":"2020-02-21T13:09:37.03459615Z"}
{"log":"LOG:  new timeline 5 forked off current database system timeline 4 before current recovery point 2A/70000098\n","stream":"stderr","time":"2020-02-21T13:09:37.034705012Z"}
{"log":"localhost:5432 - accepting connections\n","stream":"stdout","time":"2020-02-21T13:09:37.713474248Z"}
{"log":"localhost:5432 - accepting connections\n","stream":"stdout","time":"2020-02-21T13:09:37.721039712Z"}
{"log":"2020-02-21 13:09:37,725 INFO: Lock owner: patroni2; I am patroni1\n","stream":"stderr","time":"2020-02-21T13:09:37.726233656Z"}
{"log":"2020-02-21 13:09:37,726 INFO: does not have lock\n","stream":"stderr","time":"2020-02-21T13:09:37.72632454Z"}
{"log":"2020-02-21 13:09:37,726 INFO: establishing a new patroni connection to the postgres cluster\n","stream":"stderr","time":"2020-02-21T13:09:37.726432998Z"}
{"log":"2020-02-21 13:09:38,146 INFO: Local timeline=4 lsn=2A/70000098\n","stream":"stderr","time":"2020-02-21T13:09:38.1472552Z"}
{"log":"2020-02-21 13:09:38,149 INFO: master_timeline=5\n","stream":"stderr","time":"2020-02-21T13:09:38.149643363Z"}
{"log":"2020-02-21 13:09:38,149 INFO: master: history=1\u00090/40004C8\u0009no recovery target specified\n","stream":"stderr","time":"2020-02-21T13:09:38.149889928Z"}
{"log":"\n","stream":"stderr","time":"2020-02-21T13:09:38.149905693Z"}
{"log":"2\u00090/40005D8\u0009no recovery target specified\n","stream":"stderr","time":"2020-02-21T13:09:38.149912379Z"}
{"log":"\n","stream":"stderr","time":"2020-02-21T13:09:38.149918624Z"}
{"log":"3\u00090/8FC68178\u0009no recovery target specified\n","stream":"stderr","time":"2020-02-21T13:09:38.149924395Z"}
{"log":"\n","stream":"stderr","time":"2020-02-21T13:09:38.149930288Z"}
{"log":"4\u00092A/6F4F9220\u0009no recovery target specified\n","stream":"stderr","time":"2020-02-21T13:09:38.149935831Z"}
{"log":"\n","stream":"stderr","time":"2020-02-21T13:09:38.149941705Z"}
{"log":"2020-02-21 13:09:38,178 INFO: running pg_rewind from patroni2\n","stream":"stderr","time":"2020-02-21T13:09:38.178704394Z"}
{"log":"LOG:  received fast shutdown request\n","stream":"stderr","time":"2020-02-21T13:09:38.179239576Z"}
{"log":"LOG:  aborting any active transactions\n","stream":"stderr","time":"2020-02-21T13:09:38.179282993Z"}
{"log":"FATAL:  terminating connection due to administrator command\n","stream":"stderr","time":"2020-02-21T13:09:38.179292853Z"}
{"log":"LOG:  shutting down\n","stream":"stderr","time":"2020-02-21T13:09:43.185976563Z"}
{"log":"LOG:  database system is shut down\n","stream":"stderr","time":"2020-02-21T13:09:43.219923367Z"}
{"log":"2020-02-21 13:09:43,347 INFO: running pg_rewind from user=postgres host=172.19.0.4 port=5432 dbname=postgres sslmode=prefer sslcompression=1\n","stream":"stderr","time":"2020-02-21T13:09:43.348046927Z"}
{"log":"servers diverged at WAL position 2A/6F4F9220 on timeline 4\n","stream":"stdout","time":"2020-02-21T13:09:43.359484824Z"}
{"log":"rewinding from last common checkpoint at 2A/6F44EF60 on timeline 4\n","stream":"stdout","time":"2020-02-21T13:09:43.359498545Z"}
{"log":"2020-02-21 13:09:47,726 INFO: Lock owner: patroni2; I am patroni1\n","stream":"stderr","time":"2020-02-21T13:09:47.726944944Z"}
{"log":"2020-02-21 13:09:47,877 INFO: running pg_rewind from patroni2 in progress\n","stream":"stderr","time":"2020-02-21T13:09:47.877745802Z"}
{"log":"2020-02-21 13:09:57,725 INFO: Lock owner: patroni2; I am patroni1\n","stream":"stderr","time":"2020-02-21T13:09:57.725387251Z"}
{"log":"2020-02-21 13:09:57,794 INFO: running pg_rewind from patroni2 in progress\n","stream":"stderr","time":"2020-02-21T13:09:57.794778528Z"}
{"log":"Done!\n","stream":"stdout","time":"2020-02-21T13:10:05.08383992Z"}
{"log":"2020-02-21 13:10:05,086 INFO: Lock owner: patroni2; I am patroni1\n","stream":"stderr","time":"2020-02-21T13:10:05.087176266Z"}
{"log":"2020-02-21 13:10:05,162 INFO: failed to start postgres\n","stream":"stderr","time":"2020-02-21T13:10:05.162351363Z"}
{"log":"2020-02-21 13:10:07,168 WARNING: Postgresql is not running.\n","stream":"stderr","time":"2020-02-21T13:10:07.168872225Z"}
{"log":"2020-02-21 13:10:07,168 INFO: Lock owner: patroni2; I am patroni1\n","stream":"stderr","time":"2020-02-21T13:10:07.16893941Z"}
{"log":"2020-02-21 13:10:07,174 INFO: Lock owner: patroni2; I am patroni1\n","stream":"stderr","time":"2020-02-21T13:10:07.174540754Z"}
{"log":"2020-02-21 13:10:07,174 INFO: Lock owner: patroni2; I am patroni1\n","stream":"stderr","time":"2020-02-21T13:10:07.175190913Z"}
{"log":"2020-02-21 13:10:07,207 INFO: starting as a secondary\n","stream":"stderr","time":"2020-02-21T13:10:07.207496322Z"}
{"log":"2020-02-21 13:10:07,208 INFO: closed patroni connection to the postgresql cluster\n","stream":"stderr","time":"2020-02-21T13:10:07.208292652Z"}
{"log":"2020-02-21 13:10:07,263 INFO: postmaster pid=84\n","stream":"stderr","time":"2020-02-21T13:10:07.263818159Z"}
{"log":"localhost:5432 - no response\n","stream":"stdout","time":"2020-02-21T13:10:07.270328436Z"}
{"log":"LOG:  database system was interrupted while in recovery at log time 2020-02-21 13:09:43 UTC\n","stream":"stderr","time":"2020-02-21T13:10:07.444520995Z"}
{"log":"HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.\n","stream":"stderr","time":"2020-02-21T13:10:07.444561996Z"}
{"log":"LOG:  entering standby mode\n","stream":"stderr","time":"2020-02-21T13:10:07.646661773Z"}
{"log":"LOG:  redo starts at 2A/6F44EF28\n","stream":"stderr","time":"2020-02-21T13:10:07.673608752Z"}
{"log":"LOG:  consistent recovery state reached at 2A/6F527158\n","stream":"stderr","time":"2020-02-21T13:10:07.690260558Z"}
{"log":"LOG:  invalid record length at 2A/6F527158: wanted 24, got 0\n","stream":"stderr","time":"2020-02-21T13:10:07.690274972Z"}
{"log":"LOG:  database system is ready to accept read only connections\n","stream":"stderr","time":"2020-02-21T13:10:07.690863237Z"}
{"log":"LOG:  started streaming WAL from primary at 2A/6F000000 on timeline 5\n","stream":"stderr","time":"2020-02-21T13:10:07.69466092Z"}
{"log":"localhost:5432 - accepting connections\n","stream":"stdout","time":"2020-02-21T13:10:08.281005439Z"}
{"log":"localhost:5432 - accepting connections\n","stream":"stdout","time":"2020-02-21T13:10:08.288461228Z"}
{"log":"2020-02-21 13:10:08,294 INFO: Lock owner: patroni2; I am patroni1\n","stream":"stderr","time":"2020-02-21T13:10:08.294759141Z"}
{"log":"2020-02-21 13:10:08,294 INFO: does not have lock\n","stream":"stderr","time":"2020-02-21T13:10:08.294823464Z"}
{"log":"2020-02-21 13:10:08,294 INFO: establishing a new patroni connection to the postgres cluster\n","stream":"stderr","time":"2020-02-21T13:10:08.294968508Z"}
{"log":"2020-02-21 13:10:09,070 INFO: no action.  i am a secondary and i am following a leader\n","stream":"stderr","time":"2020-02-21T13:10:09.071126046Z"}

I'm not sure if this is a bug or a feature, but if I'm ahead in the transactions shouldn't I fail instead of recover from the master that it's behind me?

I'm not sure if I'm missing something as well.

Thanks.

Edit1: I'm using patroni from commit https://github.com/zalando/patroni/commit/22044540946dbaef68c36ec45d5d5cdceb43c402

**Comment by caseyallenshobe** [comment]
Bu default, PostgreSQL replication is asynchronous, so some data loss is possible when a failover occurs.  You can adjust the amount of loss you are willing to lose by lowering Patroni’s `maximum_lag_on_failover` value, but lower values are more likely to result in a failure of the master causing a service outage instead of a failover.  You can achieve zero data loss and high-availability by using synchronous replication, but this has an impact on write performance as data must be synced to synchronous standby nodes before the database tells the client that the write is committed.

**Comment by acmzero** [comment]
Thanks I think we are going for synchronous.

**Comment by CyberDem0n** [comment]
> I'm ahead in the transactions shouldn't I fail instead of recover from the master that it's behind me?

Your configuration allows using of pg_rewind, so Patroni did a rewind.

Also, divergence doesn't always mean a data loss, because:
1. it might be that transactions were never reported to the client as successful
2. there are some background activities like autovacuum which are also generating WAL records.
