### ISSUE TITLE
Cancelling of PG query while waiting synchronous replication could lead to split brain

### ISSUE THREAD

**Issue by michail-nikolaev** [zalando/patroni#1412]
Hello.

Just want to warn and inform about the issue with possible split brain and data loss even in synchronous mode strict in case of cancelation of execution of the query.

Issue is described and discussed with details into related links below. But in few words it looks like this:

* master is isolated from all replicas due network partition just microsecond ago
* client 1 inserts new records to isolated master, commits and waits for synchronous replication (it is stuck because synchronous replica is not available)
* client 1 cancels the query (for example because timeout)
* clients 2, 3, 4 and 5 now see new data (!) and perform some actions outside
of the database in external systems (but new records are not exists on any replica)
* master is finally switched to the replica with no WAL of new records replicated yet

Results: inserted data is lost, possible split-brain actions performed.

Related topic: https://www.postgresql.org/message-id/flat/C1F7905E-5DB2-497D-ABCC-E14D4DEE506C%40yandex-team.ru

And something related mostly to the java world:
https://www.postgresql.org/message-id/flat/CANtu0ogbu%2By6Py963p-zKJ535b8zm5AOq7zkX7wW-tryPYi1DA%40mail.gmail.com#5ff0828b7928739c84771ea46b5fc213

**Comment by michail-nikolaev** [comment]
Also, it is seems like issue could also be triggered by `statement_timeout` setting.

**Comment by CyberDem0n** [comment]
Well, we are aware of it, but there is not much we can do about it, except maybe documenting.

**Comment by michail-nikolaev** [comment]
> Well, we are aware of it, but there is not much we can do about it, except maybe documenting.

Nice. Yep, some notes in documentation would be helpful. Prepare PR?

**Comment by CyberDem0n** [comment]
That would be awesome.

**Comment by michail-nikolaev** [comment]
Done - https://github.com/zalando/patroni/pull/1414

**Comment by wb14123** [comment]
Hi @michail-nikolaev @CyberDem0n , I know this is an old issue but how could this happen?

> clients 2, 3, 4 and 5 now see new data

The transaction is not committed if it cannot be synchronous replicated, right? How can other clients see that if it's not committed?

**Comment by wb14123** [comment]
Oh sorry I missed the link you provided. So basically even the transaction is not committed, the retry after cancellation will be acked to client.  That's really a surprising behavior and I'm wondering if anything has changed. Anyway, I think we can better document the situation so there is less confusing.

**Comment by wb14123** [comment]
Also seems [this part of PostgreSQL doc](https://www.postgresql.org/docs/current/warm-standby.html#SYNCHRONOUS-REPLICATION)  is more related:

> If primary restarts while commits are waiting for acknowledgment, those waiting transactions will be marked fully committed once the primary database recovers. There is no way to be certain that all standbys have received all outstanding WAL data at time of the crash of the primary. Some transactions may not show as committed on the standby, even though they show as committed on the primary. The guarantee we offer is that the application will not receive explicit acknowledgment of the successful commit of a transaction until the WAL data is known to be safely received by all the synchronous standbys.
