### ISSUE TITLE
patronictl issue

### ISSUE THREAD

**Issue by alexeyshishkin01** [zalando/patroni#1413]
sudo yum install -y python3-pip python3-devel python3-psycopg2
sudo pip3 install --upgrade pip
sudo pip3 install patroni[consul,etcd]
patronictl version

Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 5, in <module>
    from patroni.ctl import ctl
  File "/usr/local/lib/python3.6/site-packages/patroni/ctl.py", line 29, in <module>
    from patroni.postgresql import Postgresql
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 3, in <module>
    import psycopg2
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /usr/lib64/python3.6/site-packages/psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PQencryptPasswordConn

[azureuser@centos-std96-prepare ~]$ uname -a
Linux centos-std96-prepare 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[azureuser@centos-std96-prepare ~]$ cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)

what could be the reason of the issue?

**Comment by CyberDem0n** [comment]
Let me [google](https://www.google.com/search?q=ImportError%3A+%2Fusr%2Flib64%2Fpython3.6%2Fsite-packages%2Fpsycopg2%2F_psycopg.cpython-36m-x86_64-linux-gnu.so%3A+undefined+symbol%3A+PQencryptPasswordConn) it for you...

**Comment by alexeyshishkin01** [comment]
pls. do

**Comment by alexeyshishkin01** [comment]
sudo pip3 install psycopg2-binary

solves the issue

pls. close the issue

it's all about 9.6 (probably for 9.5/9.4 as well)
