### ISSUE TITLE
[Question] Auto restart on patroni.service risks

### ISSUE THREAD

**Issue by stedounet** [zalando/patroni#1415]
Hi

In https://github.com/zalando/patroni/blob/master/extras/startup-scripts/patroni.service there is this comment
`# Do not restart the service if it crashes, we want to manually inspect database on failure`
`Restart=no`

I do not understand why because : 

- if postgres crash, the "restart" is handled in patroni conf, hence we have our "inspect on database failure" possibility
 - if patroni crash, I would want it to restart as it won't stop any running leader postgres. Plus not doing so could make a failover happen with the old master still running unsupervised by patroni
- in case of reboot there's nothing to manually inspect, everything should have stopped gracefully

What do I miss ?

Thanks

**Comment by CyberDem0n** [comment]
Off course, ideally Patroni should be restarted, because we don't want to leave postgres running without supervision.
I can imagine that the comment only applies to the case when the whole node crached.
If the watchdog is enabled it will actually restart the whole node if Patroni has crashed.
