### ISSUE TITLE
Leadership decision question

### ISSUE THREAD

**Issue by doribd** [zalando/patroni#1416]
Hi
Is it possible to have the following 

DC1                                         DC2                                  DC3
ETCD                                        ETCD                                ETCD
Master, HotStandby                 HotStandby

I can work in sync inside DC1 while the Hotstandby in DC2 is Async right ?

Now, ETCD may elect the DC2 in case of failure to be the leader --> bad for me. 
May i 'object' or disallow from this situation from happening ?  
May i obligate leader selection only from DC1 ?

**Comment by CyberDem0n** [comment]
Please read the [documentation](https://patroni.readthedocs.io/en/latest/SETTINGS.html#tags)
