### ISSUE TITLE
Sync replication

### ISSUE THREAD

**Issue by doribd** [zalando/patroni#1417]
in Patroni documents you wrote 
'When using PostgreSQL synchronous replication, use at least three Postgres data nodes to ensure write availability if one host fails.'

Does it means: 1 master and , 2 sync replicates or 
1 master, 1 sync replica, 1 async replica ?

**Comment by CyberDem0n** [comment]
Patroni doesn't support more than one sync replica.

**Comment by doribd** [comment]
isn't this a contradiction to 'When using PostgreSQL synchronous replication, use at least three Postgres data nodes to ensure write availability if one host fails.' or did you mean 
2 sync and 1 async in this phrase?
