### ISSUE TITLE
Patroni in DR

### ISSUE THREAD

**Issue by doribd** [zalando/patroni#1419]
Hi
I read couple of the open / closed / merged issues regard this topic. 
What is the suggested solution by you for DR?
How zalando is using Patroni for their DR ? 

Does ASYNC replication to the DR site is the recommended solution with patroni ?

**Comment by CyberDem0n** [comment]
We mostly run Patroni on AWS (EC2 and K8s).
The typical setup - two or three Patroni nodes. For daily backups and continuous archiving to S3 we use wal-e.
