### ISSUE TITLE
Standby failed bootstrap fills up disk with timestamped directories

### ISSUE THREAD

**Issue by neale-bpm** [zalando/patroni#1421]
Hi,

We've got a standby cluster where we're clearly doing something wrong in our bootstrap script (a wal-g hack of your wal-e one), but on failure the postgres/current directory is renamed with a timestamp, and the process starts again.  This soon fills up a disk.

Is there any reason not to just rename once to `current.failed` as if this is a repeated problem then only the last failure is really relevant?

Thanks.

**Comment by CyberDem0n** [comment]
Maybe you are right. It was just easier to implement back than.
If you want to change it - please open a PR.
