### ISSUE TITLE
patroni operation 

### ISSUE THREAD

**Issue by Liuzhj** [zalando/patroni#1425]
pg cluster has 3 members of patroni .
and i need to enable some extend to shared_preload_libraries.
i want to know the correctly step or official recommend. 
and now i set 3 times to each pg instance and restart pg , it's normal . 
thank you very much .

**Comment by CyberDem0n** [comment]
As a first step I would recommend you to read the [documentation](https://patroni.readthedocs.io/en/latest/dynamic_configuration.html).
You can also go through Patroni [tutorial](https://github.com/patroni-training/2019).

**Comment by Liuzhj** [comment]
thank you , close issue.
