### ISSUE TITLE
Propagation Support

### ISSUE THREAD

**Issue by doribd** [zalando/patroni#1427]
Hi
Can patroni work like 

Master  -----Sync--> Standby(1) ------Sync-->Standby(2)

Will this will work ? 
(very similar to the concept of cascading in PG, does it supported with Patroni?)

**Comment by CyberDem0n** [comment]
Sorry, I am absolutely not following your question.
All capabilities of Patroni are documented, including some support of cascading replication [tags.replicatefrom](https://patroni.readthedocs.io/en/latest/SETTINGS.html#tags).

If you think that some useful feature is missing - feel free to implement and contribute it back by opening a pull request.

**Comment by doribd** [comment]
Can you have one sync replication to the master and another sync replication to the sync replicaion ? 
Let's assume you can. Unless you will say you can't.
When a request comes, it will be 'written' in the master, then in the sync. Then, will it return to the client ? while the other sync from the sync will be receiving it.
