### ISSUE TITLE
Use patroni for PostgreSQL cluster management without automatic failover

### ISSUE THREAD

**Issue by awiller42** [zalando/patroni#1428]
We are looking into using patroni as our default solution for PostgreSQL HA clustering.

Our path to achieve this goal includes a phase of indefinite length during which patroni should bascially do everything it does normally - except automatic failover. This is due to the fact that we want to see first how everything works - including manual switchover - and only then deploy some clusters that also perform automatic failover.

I have found the Pause mode (https://github.com/zalando/patroni/blob/master/docs/pause.rst) and am unsure if it has too much implications to be considered as a "normal mode without failover"-type of operation. It seems like this may be the case, e.g. as automatic restart of failed PostgreSQL-Servers is disabled.

Also, I found the `nofailover` tag, but this seems to also disallow manual switchover according to #769, which we still want to be able to perform.

The "no automatic failover" mode of operation would ideally be accompanied by some logging of sorts "Now a failover would happen, but no nodes are available to failover to" to monitor for and evaluate situations where failover would occur without actually doing it.

Any advice / insights how this could be implemented would be greatly appreciated.

**Comment by kiaplayer** [comment]
Yes, I think #769 was wrong decision. 
"nofailover" tag should protect you from failover only, not from switchover.

**Comment by CyberDem0n** [comment]
The main goal of Patroni - reliable automatic failover.
Turning it into configuration management tool is absolutely out of scope.

@kiaplayer the node with `nofailover` tag is not allowed to become the primary under any circumstances. Internally there is not so much difference between failover and switchover, so introducing the new tag doesn't make much sense.

**Comment by awiller42** [comment]
Thank you for your response. I want to explain the reasoning a bit more:

Our goal is to have one company-wide solution for all PostgreSQL clusters with dynamic primary/standby server roles. In future, we want to replace some Oracle HA database clusters with that solution, so an upgrade path to automatic failover is definitely needed.

By gaining experience in "manual mode" in some less-important applications we can be more confident doing this replacement in the future, probably switching those manual mode applications to fully automatic failover too. Also, the overhead and non-transferrable experience which would come from use of two different solutions would place too much of an burden on our DBA people.

I would argue that patroni can already provide lots of value just for manual replication management and cluster health monitoring.

I'd also like to ask about possible workarounds: 

Would it be possible to ensure that the cluster is healthy, then remove the `nofailover` tag from the node to switch over to and perform or schedule a switchover? Can a `nofailover` tag be assigned to the current primary node without causing immediate demotion, but only hindering future promotion?

May the primary be demoted due to intermittent issues when no suitable standby to failover to is available or will patroni just do nothing as long as no suitable standbys are available?

**Comment by CyberDem0n** [comment]
> Would it be possible to ensure that the cluster is healthy, then remove the nofailover tag from the node to switch over to and perform or schedule a switchover?

Yes.

> Can a nofailover tag be assigned to the current primary node without causing immediate demotion, but only hindering future promotion?

Yes

In both cases you have to update patroni.yaml and reload config either by sending SIGHUP to patroni process or do `patronictl reload`.

> May the primary be demoted due to intermittent issues when no suitable standby to failover to is available or will patroni just do nothing as long as no suitable standbys are available?

Patroni will demote postgres if it fails to update the leader lock in DCS. There is no way to avoid it, because this is one of the indicators of network partitioning.

> By gaining experience in "manual mode" in some less-important applications we can be more confident doing this replacement in the future, probably switching those manual mode applications to fully automatic failover too.

Well, I would suggest starting with non-production systems.

**Comment by awiller42** [comment]
Thanks, that will most probably allow us to achieve the desired functionality.

We realize that any issues with the DCS will cause demotion, I was more thinking in the direction of a crashed PostgreSQL process on the primary with only this primary being allowed to failover to. I found that master_start_timeout allows for a window of PostgreSQL restart attempts and if they fail with timeout, the instance is broken one way or the other, so demotion doesn't matter anyway in that case.

Just for future reference, I want to link this issue, which also goes into those questions and helped me to understand the introduction of the `nofailover` tag a bit more: #48
