### ISSUE TITLE
failover when data missing 

### ISSUE THREAD

**Issue by thomasdba** [zalando/patroni#1429]
I did a test few days ago , I deleted the db data files from primary , but the pg process is still running , but db cannot be accessed , failover didn't happen , is it as expected ?

**Comment by CyberDem0n** [comment]
I have no idea what you have done, but if the PGDATA is empty or missing Patroni will perform a failover.

**Comment by thomasdba** [comment]
just deleted all data in PGDATA when it is running,then no failover happened, weird.
