### ISSUE TITLE
trying to setup patroni.

### ISSUE THREAD

**Issue by amadhaka** [zalando/patroni#1430]
Hi All,

I am trying to setup patroni first time on RHEL for postgres but not able to configure it properly, please help.

-bash-4.2$ service patroni status
Redirecting to /bin/systemctl status patroni.service
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/etc/systemd/system/patroni.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2020-03-06 15:04:26 UTC; 29min ago
  Process: 29922 ExecStart=/usr/local/bin/patroni /etc/patroni.yml (code=exited, status=203/EXEC)
 Main PID: 29922 (code=exited, status=203/EXEC)

Mar 06 15:04:26 ple-gpe1887-ide-cin-euwest2-postgres-pyt-master systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
Mar 06 15:04:26 ple-gpe1887-ide-cin-euwest2-postgres-pyt-master systemd[1]: patroni.service: main process exited, code=exited, status=203/EXEC
Mar 06 15:04:26 ple-gpe1887-ide-cin-euwest2-postgres-pyt-master systemd[1]: Unit patroni.service entered failed state.
Mar 06 15:04:26 ple-gpe1887-ide-cin-euwest2-postgres-pyt-master systemd[1]: patroni.service failed.
-bash-4.2$

-bash-4.2$ patronictl -c /etc/patroni.yml list
+---------+--------+------+------+-------+----+-----------+
| Cluster | Member | Host | Role | State | TL | Lag in MB |
+---------+--------+------+------+-------+----+-----------+
+---------+--------+------+------+-------+----+-----------+
-bash-4.2$

**Comment by CyberDem0n** [comment]
> Mar 06 15:04:26 ple-gpe1887-ide-cin-euwest2-postgres-pyt-master systemd[1]: **Unit patroni.service entered failed state**.
> Mar 06 15:04:26 ple-gpe1887-ide-cin-euwest2-postgres-pyt-master systemd[1]: **patroni.service failed.**

Please ALWAYS check logs before opening the issue!

**Comment by amadhaka** [comment]
The problem is mate, I am not getting where to see the patroni logs, its the first time I am doing patroni.

**Comment by caseyallenshobe** [comment]
> The problem is mate, I am not getting where to see the patroni logs, its the first time I am doing patroni.

You created the configuration, which you're specifying in your patronictl command via the `-c` argument.  What does it say in the `log` section?  Patroni will log as you configure it to.  The [documentation](https://patroni.readthedocs.io/en/latest/SETTINGS.html#log) covers the options on this well.  Filing bug reports is not a substitute for reading the docs!

**Comment by amadhaka** [comment]
Thanks for review, let me redo my work.
