### ISSUE TITLE
[Question] Recommended way of changing postgres params which do not require restart

### ISSUE THREAD

**Issue by marqos** [zalando/patroni#1433]
Hello,

I'm writing ansible role for automating patroni+postgres installation and configuration, and I am not sure what's the optimal or recommended way of changing Postgres parameters which do not require restart? 
One way which works is updating `postgresql.base.conf` and then run `select pg_reload_conf()` in postgres db. 

For postgres params which do require restart, I use `patronictl edit-config` and after that, I run `patronictl restart` if `pending_restart` flag is set. I've tried the same for non-restart params, but with running `patronictl reload`, but it didn't work.

Thanks,

**Comment by CyberDem0n** [comment]
If you changed some postgres parameters with `patronictl edit-config` and restart is not required Patroni updates postgresql.conf and does reload.

**Comment by marqos** [comment]
Thank you @CyberDem0n !
