### ISSUE TITLE
Location for TCP load balancer for patroni

### ISSUE THREAD

**Issue by amadhaka** [zalando/patroni#1436]
Dear All, I am trying to setup TCP cloud native load balancer instead of HAProxy but did not found what path i should give as a healthcheck path, i get the rest api as 8008 so thinking load balancer should able to communicate on this port and patroni should revert with proper code to tcp load balancer but it isn't working.
Any leads please ?
thanks and kind regards,
aman

**Comment by caseyallenshobe** [comment]
https://patroni.readthedocs.io/en/latest/rest_api.html

**Comment by amadhaka** [comment]
Very strange I tried all options in google tcp load balancer I am getting response form curl from all nodes but load balancer isn't working, any help would be appreciable.

Using this to setup :- HealthCheck: Protocol → HTTP, Port → 8008, Request Path → /master, health criteria → 2 seconds.


curl -s http://10.1.100.217:8008/
{"state": "running", "postmaster_start_time": "2020-03-11 11:58:24.484 UTC", "role": "replica", "server_version": 100012, "cluster_unlocked": false, "xlog": {"received_location": 318767584, "replayed_location": 318767584, "replayed_timestamp": null, "paused": false}, "timeline": null, "database_system_identifier": "6802263629542410170", "patroni": {"version": "1.6.0", "scope": "patroni_cluster_1"}, "action": null}[amandhaka@ple-gpe1887-ide-cin-euwest2-postgres-pyt-master ~]$
[amandhaka@ple-gpe1887-ide-cin-euwest2-postgres-pyt-master ~]$
[amandhaka@ple-gpe1887-ide-cin-euwest2-postgres-pyt-master ~]$
[amandhaka@ple-gpe1887-ide-cin-euwest2-postgres-pyt-master ~]$ curl -s http://10.1.100.217:8008/master
{"state": "running", "postmaster_start_time": "2020-03-11 11:58:24.484 UTC", "role": "replica", "server_version": 100012, "cluster_unlocked": false, "xlog": {"received_location": 318767584, "replayed_location": 318767584, "replayed_timestamp": null, "paused": false}, "timeline": null, "database_system_identifier": "6802263629542410170", "patroni": {"version": "1.6.0", "scope": "patroni_cluster_1"}, "action": null}[amandhaka@ple-gpe1887-ide-cin-euwest2-postgres-pyt-master ~]$

**Comment by amadhaka** [comment]
i tried request path as    / , /master  , /patroni etc etc

**Comment by amadhaka** [comment]
closing it as fixed the issue, there was a issue within google cloud components. thanks for all the help.
