### ISSUE TITLE
Support for notifying a replica of its sync_stanbdy status

### ISSUE THREAD

**Issue by RajKiranS** [zalando/patroni#1439]
Let us assume a 3 node Patroni cluster with `sync_standby` support enabled. So, you would have one `Master`, one `Sync_Standby` and one `async_stabndby`.

Unfortunately, whenever a callback is fired this information is not present, its instead only `replica` as the role. Also, when a `sync_standby` changes, a callback is fired only on master(because of the reload), but nothing on the new `sync_standby`/`replica` node so that we could take appropriate actions.

Our use case is to start/stop/run services only on `Master` and `Sync_Standby` nodes.

**Comment by CyberDem0n** [comment]
I can only suggest you to implement it and open a PR, which we will review and merge.
