### ISSUE TITLE
Patroni API returns stale data on the current role

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/patroni#145]
I've noticed that even for the promoted patroni instance that holds a lock in etcd the API endpoint (i.e. /master) may still return 503 for some seconds. The reason is that do_GET method uses the cached cluster object and does not re-read it from DCS on each invocation. This is obviously done to speedup concurrent GET requests and avoid blocking the other threads on the _cluster_thread_lock, but on the same time it makes extremely difficult to run the tests that check that the /master API endpoint works normally without inserting explicit sleeps there, and explicit sleeps are bad since they make the tests run longer.

Should we explicitly re-read the cluster object from DCS on each change to the node's role to avoid situations like this?

**Comment by CyberDem0n** [comment]
Actually we already dong it (re-reading cluster object): https://github.com/zalando/patroni/blob/master/patroni/ha.py#L327

And I even run test:
Log of stopping old master:
```
^C2016-02-26 09:13:50,077 INFO: closed patroni connection to the postgresql cluster
LOG:  received fast shutdown request
LOG:  aborting any active transactions
waiting for server to shut down....LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
 done
server stopped
```

Log of promote of replica:
```
2016-02-26 09:13:51,149 ERROR: request failed: GET http://127.0.0.1:8009/patroni
server promoting
2016-02-26 09:13:51,271 INFO: cleared rewind flag after becoming the leader
cp: cannot stat ‘../wal_archive/000000020000000000000006’: No such file or directory
LOG:  received promote request
LOG:  redo done at 0/6000028
cp: cannot stat ‘../wal_archive/000000020000000000000006’: No such file or directory
cp: cannot stat ‘../wal_archive/00000003.history’: No such file or directory
LOG:  selected new timeline ID: 3
LOG:  restored log file "00000002.history" from archive
2016-02-26 09:13:51,336 INFO: promoted self to leader by acquiring session lock
```

And the third log, output of: `while true; do curl -v 127.0.0.1:8008/; sleep 0.1; done`
```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8008 (#0)
> GET / HTTP/1.1
> Host: localhost:8008
> User-Agent: curl/7.43.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 503 Service Unavailable
< Server: BaseHTTP/0.6 Python/3.5.0+
< Date: Fri, 26 Feb 2016 08:13:51 GMT
< Content-Type: application/json
< 
* Closing connection 0
{"postmaster_start_time": "2016-02-26 09:12:42.392 CET", "state": "running", "tags": {"nofailover": false, "noloadbalance": false, "clonefrom": false}, "xlog": {"paused": false, "received_location": 100663440, "replayed_location": 100663440}, "role": "replica", "server_version": 90406}
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8008 (#0)
> GET / HTTP/1.1
> Host: localhost:8008
> User-Agent: curl/7.43.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: BaseHTTP/0.6 Python/3.5.0+
< Date: Fri, 26 Feb 2016 08:13:51 GMT
< Content-Type: application/json
< 
* Closing connection 0
{"postmaster_start_time": "2016-02-26 09:12:42.392 CET", "state": "running", "tags": {"nofailover": false, "noloadbalance": false, "clonefrom": false}, "xlog": {"paused": false, "received_location": 100663440, "replayed_location": 100663440}, "role": "replica", "server_version": 90406}
```

Basically on the same second as promote happened (actually not exactly promote, but acquisition of leader lock) status has changed from 503 to 200

**Comment by alexeyklyukin** [comment]
> On 26 Feb 2016, at 09:33, Alexander Kukushkin <notifications@github.com> wrote:
> 
> Actually we already dong it (re-reading cluster object): https://github.com/zalando/patroni/blob/master/patroni/ha.py#L327 <https://github.com/zalando/patroni/blob/master/patroni/ha.py#L327>Apparently we are not very consistent here, just after starting a new instance I’m getting 503s for couple of seconds, at the
same time the postgres role is the master and the lock is taken.

Good news from your reply is that we probably have to fix it only for taking a lock right after initializing the replica.

Kind regards,
--
Oleksii Kliukin | 5432 Engineer | phone: +4917612759799 |  hipchat: @OleksiiKliukin

**Comment by CyberDem0n** [comment]
Fixed with https://github.com/zalando/patroni/commit/e564fa7f083aab2018d7b095ebd9309a5164267d
