### ISSUE TITLE
Enabling SSL for  Postgres

### ISSUE THREAD

**Issue by vishnugr** [zalando/patroni#1451]
I have build docker image by the provided Dockerfile and started docker-compose. All containers are up and leader/secondary selections are fine. I need to use SSL certificate for Postgres. I can't find the steps  to enable ssl=on in postrgresql.base.conf. I tried to provide environment values PATRONI_REPLICATION_SSLMODE,  PATRONI_REPLICATION_SSLKEY to patroni.env, but it doesn't enable SSL. Can you tell me the steps to enable SSL?

**Comment by CyberDem0n** [comment]
Step 1: understand how Patroni works, the [tutorial](https://github.com/patroni-training/2019) might be very helpful
Step 2: Change the dockerfile and build your own image
Step 3: Profit

And please, don't try to skip the first step.

**Comment by vishnugr** [comment]
> Step 1: understand how Patroni works, the [tutorial](https://github.com/patroni-training/2019) might be very helpful
> Step 2: Change the dockerfile and build your own image
> Step 3: Profit
> 
> And please, don't try to skip the first step.

I went through the tutorial on the understanding Patroni. But it doesn't help me to apply the SSL certificate. I tried to add SSL certificate by copying to data directory. But the Patroni fails in error. Is there any settings to enable SSL?

**Comment by vishnugr** [comment]
Thanks CyberDemOn. I have gone through tutorial. I have changed the postgres0.yml and included the parameters under PostgresSQL. It worked well with below parameters,

```
parameters:
  ssl: on
  ssl_cert_file: /home/postgres/cert.pem
  ssl_key_file: /home/postgres/key.pem
```

**Comment by amadhaka** [comment]
@vishnugr   hi mate what changes you made to make ssl work ? changed the conf file at postgre and placed the cert's right ? or anything need to change in patroni.yml file as well ?
