### ISSUE TITLE
Break the glass procedure for Patroni

### ISSUE THREAD

**Issue by pottacode** [zalando/patroni#1454]
Hi,
let's assume that for emergency (broken dcs or broken VMs) purposes I have to take out the Postgres master out from Patroni control and cannot use the pause and resume commands, is there any emergency procedure that I can use to uninstall, modify or uninstall Patroni ?

thanks,

Paolo

**Comment by caseyallenshobe** [comment]
You can start PostgreSQL manually with pg_ctl.  See $PGDATA/postmaster.opts for the exact command and arguments the Patroni uses to start PostgreSQL - you can execute that manually.

**Comment by pottacode** [comment]
Is there any procedure to uninstall Patroni ? Is this documented somewhere ?

**Comment by CyberDem0n** [comment]
You can always uninstall it the same way as you installed it, for example `pip uninstall` if it was installed with pip
