### ISSUE TITLE
Patroni Openshift/Kubernetes Postgres 10.6

### ISSUE THREAD

**Issue by BK-STAR77** [zalando/patroni#1455]
**_Environnement:_**
Openshift 3.11

**_Issue:_**

I'm trying to build a Patroni with a Postgres 10.6. I change in the top on the Dockerfile 

"FROM postgres:11" to "FROM postgres:10.6" but it always create a Postgres 10.12, it doesn't take my change. Any solution please?

**Comment by CyberDem0n** [comment]
Could you give any single reason to use the 10.6, which was released more than a year ago instead of the latest minor version 10.12?
In both cases you get postgres 10, but 10.6 lacks more than a year of bug and security issues fixes.

**Comment by BK-STAR77** [comment]
I tested an application with a standalone postgres 10.6 for test before production without any particular problem and I wanted to continue with this version.

**Comment by CyberDem0n** [comment]
The general recommendation of postgresql development group is to always run the latest minor version.

**Comment by BK-STAR77** [comment]
> The general recommendation of postgresql development group is to always run the latest minor version.

OK thank you very much for the clarification
