### ISSUE TITLE
Rewind failure due to .s.PGSQL.5432 file, patroni stuck at startup

### ISSUE THREAD

**Issue by ponvenkates** [zalando/patroni#1456]
I have setup a patroni cluster in nomad. During stop and start of nomad jobs often patroni doesn't finish startup and gets stuck in "Unknown role type uninitialized error". This happens randomly. On removing the data folder and restart the job postgresql starts as replica and replicates from master.

**Comment by CyberDem0n** [comment]
1. There's no slaves in postgresql world
2. Have you looked into logs?

**Comment by ponvenkates** [comment]
1. Sorry about that, I have changed the term to "replica".
2. Here are the logs, This happened again today,
```
2020-03-23 03:51:26.719 GMT [1] INFO: starting patroni
2020-03-23 03:51:27.527 GMT [176] WARNING: Postgresql is not running.
.
.
.
.
2020-03-23 03:56:11.700 GMT [176] ERROR: Failed to rewind from healty master: pg-perf-lab-cluster-01-pg2
2020-03-23 03:56:11.700 GMT [176] WARNING: remove_data_directory_on_rewind_failure is set. removing...
2020-03-23 03:56:22.503 GMT [176] WARNING: Could not register service: unknown role type uninitialized
servers diverged at WAL location F0/4992AFD8 on timeline 34
rewinding from last common checkpoint at F0/46586090 on timeline 34
"/bitnami/postgresql/data/.s.PGSQL.5432" is not a regular file
Failure, exiting

After this when my job restarts it gets stuck at this point without going further,
2020-03-23 03:57:01.692 GMT [1] INFO: starting patroni
2020-03-23 03:57:02.80 GMT [176] WARNING: Could not register service: unknown role type uninitialized
WARNING:  skipping special file "./.s.PGSQL.5432" 
```
At this point I remove the data directory of the failed PG instance and it starts up as replica without any issues.

**Comment by CyberDem0n** [comment]
> 2020-03-23 03:51:27.527 GMT [176] WARNING: Postgresql is not running.
.
.
.
.
2020-03-23 03:56:11.700 GMT [176] ERROR: Failed to rewind from healty master: pg-perf-lab-cluster-01-pg2

You skipped lines containing pg_rewind call and explaining what exactly failed.

**Comment by ponvenkates** [comment]
Skipped part is all postgresql is not

> > 2020-03-23 03:51:27.527 GMT [176] WARNING: Postgresql is not running.
> > .
> > .
> > .
> > .
> > 2020-03-23 03:56:11.700 GMT [176] ERROR: Failed to rewind from healty master: pg-perf-lab-cluster-01-pg2
> 
> You skipped lines containing pg_rewind call and explaining what exactly failed.

I skipped that part is because it's repeatition of PostgreSQL is not running. I have updated the comment with the complete log.

**Comment by CyberDem0n** [comment]
First of all, the issue title ( "Unknown role type uninitialized error") is absolutely misleading, the log severity is WARNING, not an error and it is harmless.
```
2020-03-23 03:56:22.503 GMT [176] WARNING: Could not register service: unknown role type uninitialized
```

The pg_rewind fails, you need to figure out why:
```
servers diverged at WAL location F0/4992AFD8 on timeline 34
rewinding from last common checkpoint at F0/46586090 on timeline 34
"/bitnami/postgresql/data/.s.PGSQL.5432" is not a regular file
Failure, exiting
```

In any case, after pg_rewind failed Patroni cleans up the PGDATA and reinitializing the node (because you configured it to do so).
```
2020-03-23 03:56:11.700 GMT [176] WARNING: remove_data_directory_on_rewind_failure is set. removing...
```

**Comment by ponvenkates** [comment]
@CyberDem0n 
1. Yes I understand, patroni removes the data folder and tries to reinitialize because I have set it to do so.  
2. Also yes, pg_rewind fails and that's the primary issue. Any idea what this ".s.PGSQL.5432" file is? This file seems to be causing the rewind to fail. Is it created by patroni, because Patroni is the one that initializes the data folder. I have noticed a similar issue with stolon where rewind is failing because of "postgresql.auto.conf", the fix provided was to remove the file before rewind. 
3. Most importantly, when the rewind fails and restart patroni seems to get stuck without moving ahead. Shouldn't the failed partial rewind be rolled back so that patroni doesn't get stuck at that point. 

Any help would be much appreciated. I will update the issue header accordingly. Thanks.

**Comment by CyberDem0n** [comment]
`.s.PGSQL.5432` is the unix socket file, it is created by postgres because unix_socket_directories contains PGDATA.
Why the bootstrap doesn't work after PGDATA cleanup is a different question, I don't have the answer right now, and don't have much time to investigate either.

**Comment by ponvenkates** [comment]
Thanks @CyberDem0n for your response.

**Comment by ponvenkates** [comment]
If unix_socket_directories is set to "." the socket files are created in the data directory itself and these files cause a problem during rewind. I have addressed this issue by setting the unix_socket_directories to something other than the data directory (".") and removing the .s.PGSQL.<portnumber> and .s.PGSQL.<portnumber>.lock files that were there in the data directory. After that the issue didn't arise.
