### ISSUE TITLE
Backup solution

### ISSUE THREAD

**Issue by ghost** [zalando/patroni#1457]
Dear Team,

Which would be preferred method to create a backup with Patroni ? We are looking for PITR in backup , is it possible with any commands of patroni to setup the full and incremental backups or WAL logs ?
Thanks,
Aman

**Comment by vitabaks** [comment]
Hi @amadhaka 
I can recommend the following backup and restore tools:
* [pgbackrest](https://github.com/pgbackrest/pgbackrest) << _i use it_
* [pg_probackup](https://github.com/postgrespro/pg_probackup)
* [wal-g](https://github.com/wal-g/wal-g)

Do not forget to validate your backups (for example [pgbackrest auto](https://github.com/vitabaks/pgbackrest_auto)).

**Comment by amadhaka** [comment]
Thanks a ton , any document for pgbackrest setup with patroni would be highly appreciated, my patroni is done and it is up and running perfect, need pgbackrest doc to setup with patroni.
Thanks,
Aman

**Comment by vitabaks** [comment]
pgbackrest doc:
https://pgbackrest.org/user-guide.html

**Comment by amadhaka** [comment]
Hi,
I tried to create the backup , I installed pgbackrest 2.14 via yum install and then changed below only on primary server  :-
archive_command = 'pgbackrest --stanza=stanza archive-push %p'


-bash-4.2$ cat /etc/pgbackrest.conf
[global]
repo1-path=/mnt/disks/data/backup
[stanza]
log-level-console=info
log-level-file=debug
start-fast=y
pg1-path=/mnt/disks/data/pdata
repo1-retention-full=2



pgbackrest --stanza=stanza --log-level-console=info --db-port=5432 stanza-create



but this messed up Patroni as it is down on my standby servers and its not working anymore on standby 

-bash-4.2$ patronictl -c rhel_patroni.yml list
+-------------------+---------------+------------+--------+------------------+----+-----------+
|      Cluster      |     Member    |    Host    |  Role  |      State       | TL | Lag in MB |
+-------------------+---------------+------------+--------+------------------+----+-----------+
| patroni_cluster_1 | patroni_etcd1 | 10.85.4.40 | Leader |     running      |  6 |         0 |
| patroni_cluster_1 | patroni_etcd2 | 10.85.4.41 |        | creating replica |    |   unknown |
+-------------------+---------------+------------+--------+------------------+----+-----------+


-bash-4.2$ ps -ef|grep post
root      1290     1  0 01:20 ?        00:00:00 /usr/libexec/postfix/master -w
postfix   1291  1290  0 01:20 ?        00:00:00 pickup -l -t unix -u
postfix   1292  1290  0 01:20 ?        00:00:00 qmgr -l -t unix -u
root      4287  3660  0 01:47 pts/1    00:00:00 su - postgres
postgres  4288  4287  0 01:47 pts/1    00:00:00 -bash
postgres  4465  4288  0 01:49 pts/1    00:00:00 python3.6 /bin/patroni rhel_patroni.yml
postgres  4474  4465  0 01:49 pts/1    00:00:00 /usr/pgsql-10/bin/pg_basebackup --pgdata=/mnt/disks/data/pdata -X stream --dbname=postgres://repuser@10.85.4.40:5432/postgres



its on pg basebackup but no files are being generated in data directory and no errors anywhere not sure how to debug or fix the issue.

Any particular steps or configurations in patroni.yml files need to be done before running or using pgbackrest ?

Thanks,
Aman

**Comment by vitabaks** [comment]
> but this messed up Patroni as it is down on my standby servers and its not working anymore on standby

This issue should not be related to running stanza-create.

In case of any problems with the patroni, you should attach patroni logs...


> Any particular steps or configurations in patroni.yml files need to be done before running or using pgbackrest ?

I would recommend that you first read the pgbackrest documentation.
You should also have a dedicated backup repository from which you can receive data for creating replicas.
See the patroni documentation: 
https://patroni.readthedocs.io/en/latest/replica_bootstrap.html

**Comment by doribd** [comment]
pgBackRest

**Comment by amadhaka** [comment]
Got it resolved. Thanks all for help.

**Comment by ilevennet** [comment]
> Got it resolved. Thanks all for help.

How?
