### ISSUE TITLE
"unix_socket_directories" can't be modified after bootstrap

### ISSUE THREAD

**Issue by ponvenkates** [zalando/patroni#1459]
Patroni Version: 1.6.3
Changed the "unix_socket_directories" in consul kv config. None of the nodes changed to "restart_pending":true and postgresql also didn't reflect the change. I tried adding the setting to be postgresql.base.conf file. This doesn't work too. Unix socket directories setting is present in postgresql.conf generated by patroni, so I believe it should be changed from KV. What am i doing wrong here?
My KV config:
{"ttl":30,"loop_wait":10,"retry_timeout":10,"maximum_lag_on_failover":1048576,"postgresql":{"use_pg_rewind":true,"use_slots":true,"parameters":{"unix_socket_directories":"/tmp","wal_level":"replica","max_replication_slots":2,"max_wal_senders":20,"wal_keep_segments":128,"max_connections":100}}}

**Comment by CyberDem0n** [comment]
I bet it is set in the patroni.yaml and therefore overrides value from DCS. This behaviour is documented: https://patroni.readthedocs.io/en/latest/dynamic_configuration.html

P.S. you are not running the latest version, please upgrade

**Comment by ponvenkates** [comment]
@CyberDem0n Thanks for your help. I found what I did wrong, I had set the unix_socket_directories in patroni.yml under "Local configuration" which was taking precendence over the setting in DCS. That's why it was not reflecting.
