### ISSUE TITLE
Replica status running when streaming replication is not

### ISSUE THREAD

**Issue by riddhi89** [zalando/patroni#1462]
We noticed that the Patroni REST API returns `status: running` for `role:replica` when streaming replication was not running at all (`select * from pg_stat_wal_receiver;` --> returned 0 records) on the replica node.

It looks like the API is only checking if PG is up on the node and not actually the replica health. The expectation for a node to be marked as a valid replica (`role: replica`) should be replication working fine, no?

We rely on the Patroni API for health checks. But since the API does not return the true replication health of a replica node, it requires us to check the status directly using a PG query. 

It would be great if the Patroni API itself provided the replica health information in the response. This could be either implicitly (`status: running` means replica health also is fine) or an explicit attribute in the response body (`replica_healthy: true`).

**Comment by CyberDem0n** [comment]
Postgres is up and running, and maybe even applying changes by replying WALs from archive, therefore role is replica and status is running.

If you want to have some additional health checks, like it is actually streaming - feel free to implement them and open a pull request.

**Comment by riddhi89** [comment]
Thanks. We will try to see based on bandwidth/priority on our end if we are able to add the information around replica health to the endpoint. 
Also, it seems like without any explicit current replication health check, it is all the more important to specify the `maximum_lag_on_failover` setting to prevent selecting an "unhealthy" replica to be the next leader on failover.
