### ISSUE TITLE
Thread hang cause "waiting for leader to bootstrap"

### ISSUE THREAD

**Issue by qingguee** [zalando/patroni#1476]
Hi,

We meet an issue during "helm install". After analysis, I think there is a chance python thread hang and cause  "waiting for leader to bootstrap". 
So I would like to report this issue, I don't know if you could do something to improve this part or not?

Patroni v1.6.3
Python 2.7

--- LOG ---
```
2020-03-31T19:07:05.066891092Z Skip service level restore action.
2020-03-31T19:07:05.093194223Z /entrypoint.sh: dir data changed for postgresql
2020-03-31T19:07:05.096706161Z /entrypoint.sh: dir /var/lib/postgresql/data/pgdata changed owner for postgresql
2020-03-31T19:07:05.117268451Z ls: cannot access '/var/lib/postgresql/data/pgdata/pg_replslot/': No such file or directory
2020-03-31T19:07:05.119851734Z /entrypoint.sh: create dir done, uid=26(postgres) gid=26(postgres) groups=26(postgres),0(root)
2020-03-31T19:07:05.685056852Z 2020-03-31 19:07:05,684 INFO: postgres connection_string is postgres://192.168.21.199:5432/postgres
2020-03-31T19:07:05.68508475Z 2020-03-31 19:07:05,684 INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-03-31T19:07:05.686310355Z 2020-03-31 19:07:05,686 INFO: Selected address family is 2
2020-03-31T19:07:05.68791133Z 2020-03-31 19:07:05,687 INFO: Postgres stop: success: True, signaled: False, block_callbacks: False
2020-03-31T19:07:05.688267346Z 2020-03-31 19:07:05,687 INFO: Lock owner: None; I am eric-adp-gs-testapp-db-pg-0
2020-03-31T19:07:05.688286198Z 2020-03-31 19:07:05,688 INFO: waiting for leader to bootstrap
2020-03-31T19:07:15.688363227Z 2020-03-31 19:07:15,687 INFO: Postgres stop: success: True, signaled: False, block_callbacks: False
2020-03-31T19:07:15.688460201Z 2020-03-31 19:07:15,688 INFO: Lock owner: None; I am eric-adp-gs-testapp-db-pg-0
```
If we take a look source code, I find this
ha.py
```python
                else:
                    ret = self._async_executor.try_run_async('bootstrap', self.state_handler.bootstrap.bootstrap,
                                                             args=(self.patroni.config['bootstrap'],))
                    return ret or 'trying to bootstrap a new cluster'
```
async_executor.py
```python
    def run_async(self, func, args=()):
        Thread(target=self.run, args=(func, args)).start()

    def try_run_async(self, action, func, args=()):
        prev = self.schedule(action)
        if prev is None:
            return self.run_async(func, args)
        return 'Failed to run {0}, {1} is already in progress'.format(action, prev)
```
As we didn't see "trying to bootstrap a new cluster" printout, I think the python thread had some kind of run-time problem.

Do you have any suggestions? 

BRs,
Fan Liu

**Comment by CyberDem0n** [comment]
> Do you have any suggestions?

Yes, use the [search](https://github.com/zalando/patroni/issues?q=is%3Aissue+waiting+for+leader+to+bootstrap+is%3Aclosed) before opening the new issue.

**Comment by qingguee** [comment]
Hi @CyberDem0n 

I did do "search", I think my case is different. 
- It's a fresh installation, our pvc is empty.
- We have a cleanup hook which delete patroni configmap, it will secure we don't have old config and data records.
- Our cluster name is correct. This issue only happens once, same chart can be success install.

Could you help me which issue is same as mine?

BRs,
Fan Liu

**Comment by CyberDem0n** [comment]
The only place which keeps the information about the initialized cluster is configmap or endpoint on K8s and the `/config` key for any other DCS.
If you still get `waiting for leader to bootstrap` message - that means `<cluster-name>-config` configmap or endpoint is still there. Nothing else is possible.

**Comment by qingguee** [comment]
Thanks @CyberDem0n 
I will double check the configmap. So, the configmap should not exist.

**Comment by qingguee** [comment]
Hi @CyberDem0n 
There is configmap "eric-adp-gs-testapp-db-pg-config"
```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    initialize: ""
  creationTimestamp: "2020-03-31T18:49:01Z"
  labels:
    app: eric-adp-gs-testapp-db-pg
    cluster-name: eric-adp-gs-testapp-db-pg
  name: eric-adp-gs-testapp-db-pg-config
  namespace: staging1
  resourceVersion: "86117183"
  selfLink: /api/v1/namespaces/staging1/configmaps/eric-adp-gs-testapp-db-pg-config
  uid: 0f1df8ad-587e-4d3b-b62b-05c5f58e20f7
```

But the POD log I can find is from "2020-03-31T19:01:03.858222644Z"
As I can't find log around  18:49, I think there was some problem during bootstrap.
Then POD restart, it find that configmap existed then enter "waiting for leader to bootstrap"

BRs,
Fan Liu

**Comment by qingguee** [comment]
Hi @CyberDem0n 

It seems that if bootstrap failed at half way, but configmap created, then we are blocked at current satiation. Unless we manual delete the configmap, there is no way it could recover by itself. 

I think we can do some improvement here, if bootstrap failed, it could call a callback script which do some clean up things.  
After POD restart, patroni should try again the bootstrap. Even it could fail again, but log will show what caused the bootstrap fail. Not like current situation, the log does not tell what was happen.

So, I don't know will Patroni welcome we do such kind of contribution or not? Maybe you didn't do this by reason, so I just want to get some feedback from you. 

BRs,
Fan Liu

**Comment by CyberDem0n** [comment]
> if bootstrap failed, it could call a callback script which do some clean up things.

Thats exactly what we are doing: https://github.com/zalando/patroni/blob/master/patroni/ha.py#L1156-L1166

The world is way more complicated than people realise. Pod might be killed right after it created initialize key. You can't do anything about it.

**Comment by qingguee** [comment]
Thanks for the info @CyberDem0n 
You are right, especially on K8s. Restart just happens by many reason. 

BRs,
Fan Liu

**Comment by bitsmaestro** [comment]
faced same problem...

solution... 
add field in the configmap , metadata.annotations.status
set it to bootstrapping initially and once done set it to new value 
this way operator will be able to identify the state and work accordingly
