### ISSUE TITLE
wal2json component on Patroni.

### ISSUE THREAD

**Issue by amadhaka** [zalando/patroni#1477]
Hi All,

I need to provide wal2json to app and for which I should have logical replication, but did not get wal_level to logical in Patroni, i tried to edit config and restarted patroni cluster but wal_level remains replica , is it possible to use wal2json with patroni ? or any alternative plugin which gives desired results of wal2json please ?

Thanks,
Aman

**Comment by amadhaka** [comment]
Dear Team,

Please suggest.
Thanks,
Aman

**Comment by amadhaka** [comment]
-bash-4.2$ patronictl -c /home/postgres/patroni/rhel_patroni.yml show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    wal_keep_segments: 100
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
wal_level: logical

-bash-4.2$ psql
psql (9.2.24, server 10.12)
WARNING: psql version 9.2, server version 10.0.
         Some psql features might not work.
Type "help" for help.

postgres=# \x
Expanded display is on.
postgres=# select * from pg_settings where name like 'wal_level';
-[ RECORD 1 ]---+-------------------------------------------------
name            | wal_level
setting         | replica
unit            |
category        | Write-Ahead Log / Settings
short_desc      | Set the level of information written to the WAL.
extra_desc      |
context         | postmaster
vartype         | enum
source          | command line
min_val         |
max_val         |
enumvals        | {minimal,replica,logical}
boot_val        | replica
reset_val       | replica
sourcefile      |
sourceline      |
pending_restart | f

**Comment by CyberDem0n** [comment]
Just follow the tutorial: https://github.com/patroni-training/2019

**Comment by amadhaka** [comment]
Mate it is not working , when I build the patroni on my VM replication as logical working fine , and as soon as I did switchover it went back again to replica.

postgres=# select * from pg_settings where name like 'wal_level';
-[ RECORD 1 ]---+-------------------------------------------------
name            | wal_level
setting         | logical
unit            |
category        | Write-Ahead Log / Settings
short_desc      | Set the level of information written to the WAL.
extra_desc      |
context         | postmaster
vartype         | enum
source          | configuration file
min_val         |
max_val         |
enumvals        | {minimal,replica,logical}
boot_val        | replica
reset_val       | logical
sourcefile      | /mnt/disks/data/pdata/postgresql.conf
sourceline      | 20
pending_restart | f

postgres=# SELECT * FROM pg_create_logical_replication_slot('hans_slot', 'wal2json');
-[ RECORD 1 ]---------
slot_name | hans_slot
lsn       | 0/26000098

postgres=#



and post switchover 

postgres=# select * from pg_settings where name like 'wal_level';
-[ RECORD 1 ]---+-------------------------------------------------
name            | wal_level
setting         | replica
unit            |
category        | Write-Ahead Log / Settings
short_desc      | Set the level of information written to the WAL.
extra_desc      |
context         | postmaster
vartype         | enum
source          | command line
min_val         |
max_val         |
enumvals        | {minimal,replica,logical}
boot_val        | replica
reset_val       | replica
sourcefile      |
sourceline      |
pending_restart | f


postgres=# SELECT * FROM pg_logical_slot_get_changes('hans_slot', NULL, NULL);
ERROR:  logical decoding requires wal_level >= logical


Anything special needs to be done , please suggest. 
Thanks,
Aman

**Comment by amadhaka** [comment]
@CyberDem0n   I have gone through trainings but confused at logical replication vs slots, what I understood is I have to define slots and mention the plugin as wal2json but confused about the parameters started with test , they can be any name I like ? like instead of test_logical I can put aman_logical , plugin as aman_decoding or wal2json  , its just the naming convention or with some significance ? Apologies if my question is stupid but I am a bit of newbie.


maximum_lag_on_failover: 1048576
+slots:
+
test_physical:
+
type: physical
+
test_logical:
+
type: logical
+
database: postgres
+
plugin: test_decoding

**Comment by amadhaka** [comment]
i read it made the changes but still same issue:-

postgres=# select * from pg_settings where name like 'wal_level';
-[ RECORD 1 ]---+-------------------------------------------------
name | wal_level
setting | logical
unit |
category | Write-Ahead Log / Settings
short_desc | Set the level of information written to the WAL.
extra_desc |
context | postmaster
vartype | enum
source | configuration file
min_val |
max_val |
enumvals | {minimal,replica,logical}
boot_val | replica
reset_val | logical
sourcefile | /mnt/disks/data/pdata/postgresql.conf
sourceline | 22
pending_restart | f

but at slave it shows postgres=# select * from pg_settings where name like 'wal_level';
-[ RECORD 1 ]---+-------------------------------------------------
name | wal_level
setting | replica
unit |
category | Write-Ahead Log / Settings
short_desc | Set the level of information written to the WAL.
extra_desc |
context | postmaster
vartype | enum
source | command line
min_val |
max_val |
enumvals | {minimal,replica,logical}
boot_val | replica
reset_val | replica
sourcefile |
sourceline |
pending_restart | f

my yml file is like :- -bash-4.2$ cat rhel_patroni.yml
scope: patroni_cluster_1
name: patroni_etcd1
restapi:
listen: 0.0.0.0:8008
connect_address: 10.84.1.:8008
etcd:
hosts: 10.84.1.:2379,10.84.1.:2379,10.84.1.:2379
protocol: http
bootstrap:
method: pgbackrest
pgbackrest:
command: /home/postgres/patroni/custon_bootstrap.sh
keep_existing_recovery_conf: false
recovery_conf:
recovery_target: immediate
recovery_target_action: pause
restore_command: /bin/pgbackrest --stanza=stanza archive-get %f %p
#This will always be immediate as we will be recovering until the last backup set. pgbackrest backup set will define the checkpoint.
#This section will be written into /<namespace>/<scope>/config of a given configuration store after initializing of new cluster.
dcs:
ttl: 30
loop_wait: 10
retry_timeout: 10
maximum_lag_on_failover: 1048576
# master_start_timeout: 300
# synchronous_mode: false
#standby_cluster:
#host: 127.0.0.1
#port: 1111
#primary_slot_name: patroni
postgresql:
callbacks:
on_role_change: /home/postgres/patroni/callback.sh
create_replica_methods:
- pgbackrest
use_pg_rewind: true
use_slots: true
parameters:
archive_command: /bin/pgbackrest --stanza=stanza archive-push %p
archive_mode: off
archive_timeout: 10s
hot_standby: 'on'
log_directory: /home/postgres/patroni
log_filename: /home/postgres/patroni/postgresql-10-main.log
log_rotation_size: 1GB
log_statement: ddl
log_truncate_on_rotation: true
max_replication_slots: 10
max_wal_senders: 10
wal_keep_segments: 1000
wal_level: logical
wal_log_hints: 'on'
pgbackrest:
command: /home/postgres/patroni/create_replica.sh
keep_data: true
keep_existing_recovery_conf: true
no_params: false
pg_hba:
- host all all 127.0.0.1/32 trust
- host replication all 127.0.0.1/32 trust
- host replication repuser 10.84.1./32 md5
- host replication repuser 10.84.1./32 md5
- host replication repuser 10.84.1./32 md5
- host all all 0.0.0.0/0 md5
recovery_conf:
restore_command: "/bin/pgbackrest --stanza=stanza archive-get %f %p"
recovery_target_timeline: "latest"
recovery_target_action: "promote"
# users:
# admin:
# password:
# options:
# - createrole
# - createdb
postgresql:
listen: 0.0.0.0:5432
connect_address: 10.84.1.:5432
data_dir: /mnt/disks/data/pdata
bin_dir: /usr/pgsql-10/bin
authentication:
replication:
username: repuser
password: repuser
superuser:
username: postgres
password:
parameters:
logging_collector: "on"
log_directory: "/home/postgres/patroni/"
log_filename: "postgresql-10-main.log"
synchronous_commit: "on"
synchronous_standby_names: "*"
slots:
wal2json_logical_slot:
type: logical
database: postgres
plugin: wal2json
log:
dir: /home/postgres/patroni/
file_size: 10240000
level: INFO

please help and suggest.

**Comment by CyberDem0n** [comment]
Please read the documentation: https://patroni.readthedocs.io/en/latest/SETTINGS.html#bootstrap-configuration

> dcs: This section will be written into /<namespace>/<scope>/config of the given configuration store after initializing of new cluster. The global dynamic configuration for the cluster. Under the bootstrap.dcs you can put any of the parameters described in the [Dynamic Configuration settings](https://patroni.readthedocs.io/en/latest/SETTINGS.html#dynamic-configuration-settings) and after Patroni initialized (bootstrapped) the new cluster, it will write this section into `/<namespace>/<scope>/config` of the configuration store. All later changes of `bootstrap.dcs` **will not take any effect!** If you want to change them please use either `patronictl edit-config` or Patroni [REST API](https://patroni.readthedocs.io/en/latest/rest_api.html#rest-api).

**Comment by amadhaka** [comment]
Hi Mate,

I made changes as suggested rebooted the cluster but still no result.

-bash-4.2$ patronictl -c /home/postgres/patroni/rhel_patroni.yml show-config
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      callbacks:
        on_role_change: /home/postgres/patroni/callback.sh
      create_replica_methods:
      - pgbackrest
      parameters:
        archive_command: /bin/pgbackrest --stanza=stanza archive-push %p
        archive_mode: false
        archive_timeout: 10s
        hot_standby: 'on'
        log_directory: /home/postgres/patroni
        log_filename: /home/postgres/patroni/postgresql-10-main.log
        log_rotation_size: 1GB
        log_statement: ddl
        log_truncate_on_rotation: true
        max_replication_slots: 10
        max_wal_senders: 10
        wal_keep_segments: 1000
        wal_level: logical
        wal_log_hints: 'on'
      pgbackrest:
        command: /home/postgres/patroni/create_replica.sh
        keep_data: true
        keep_existing_recovery_conf: true
        no_params: false
      recovery_conf:
        recovery_target_action: promote
        recovery_target_timeline: latest
        restore_command: /bin/pgbackrest --stanza=stanza archive-get %f %p
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 30
  method: pgbackrest
  pgbackrest:
    command: /home/postgres/patroni/custon_bootstrap.sh
    keep_existing_recovery_conf: false
    recovery_conf:
      recovery_target: immediate
      recovery_target_action: pause
      restore_command: /bin/pgbackrest --stanza=stanza archive-get %f %p
log:
  dir: /home/postgres/patroni/
  file_size: 10240000
  level: INFO
postgresql:
  authentication:
    replication:
      password: repuser
      username: repuser
    superuser:
      password: Wgy232NodISNWSnS
      username: postgres
  bin_dir: /usr/pgsql-10/bin
  data_dir: /mnt/disks/data/pdata
  parameters:
    log_directory: /home/postgres/patroni/
    log_filename: postgresql-10-main.log
    logging_collector: 'on'
    synchronous_commit: 'on'
    synchronous_standby_names: '*'
  slots:
    database: postgres
    plugin: wal2json
    type: logical
    wal2json_logical_slot: null



My configs are right for logical replication and wal2json plugin slot ?
Thanks,
Aman

**Comment by amadhaka** [comment]
got it sorted, thanks a lot for help.
