### ISSUE TITLE
Asking help about the Patroni cluster after restart it lost all data?

### ISSUE THREAD

**Issue by darapenhchet** [zalando/patroni#1480]
Dear Zalando,

Could i ask you about the Patroni Cluster why after I restarted the Patroni Cluster server it lost all data?

Best Regards,
Dara Penhchet

**Comment by vitabaks** [comment]
PGDATA on tempfs? ))

With the correct configuration of the cluster, this should not be. Patroni does not delete data on its own.
Can you attach of patroni/postgres logs and patroni conf file?

**Comment by darapenhchet** [comment]
Dear @vitabaks ,

It works now. sorry it is my fault. 

Could I ask you one more question? Could you share me about the Backup technique with Patroni I want to backup everyday? 

Best Regards,
Dara Penhchet

**Comment by vitabaks** [comment]
Ok @darapenhchet. See #1457
