### ISSUE TITLE
How to scale down a patroni cluster ?

### ISSUE THREAD

**Issue by smogili1** [zalando/patroni#1481]
I scaled up my cluster to handle to additional capacity and no longer need the additional node. How can I safely scale down so that I can remove the additional replica node that I don't need?

**Comment by vitabaks** [comment]
`systemctl stop patroni` on additional replica node that don't need.

**Comment by smogili1** [comment]
is that it ? will doing so not make the master node swell up waiting for the node to come back up ?

Also if I need to scale up again, can I just start the patroni service and that would be it ?

Thanks,

**Comment by vitabaks** [comment]
@smogili1 

> is that it ? will doing so not make the master node swell up waiting for the node to come back up ?

No, because replication slots are automatically deleted.

> Also if I need to scale up again, can I just start the patroni service and that would be it ?

It depends on the configuration (`wal_keep_segments`, `restore_command`...), and on the time during which the replica was turned off. Or, you will need to reinit the replica.
