### ISSUE TITLE
What is the purpose of the connect_address parameters in the restapi and postgresql directives?

### ISSUE THREAD

**Issue by newman0089** [zalando/patroni#1485]
Hello!
I have two questions.
First.
What is the purpose of the connect_address parameters in the restapi and postgresql directives if the listen parameter affects the connection to restapi and postgresql? Or is this parameter required if listen specifies 0.0.0.0?

Second.

Can I change the listen parameter with `patronictl -c /path/to/patroni.yml edit-config <cluster_name>`?
Or do I need to modify this directly in patroni.yml itself?
Is it possible to specify multiple ip addresses for the listen parameter?

**Comment by vitabaks** [comment]
1. See https://patroni.readthedocs.io/en/latest/SETTINGS.html#rest-api 
2. in patroni.yml

**Comment by newman0089** [comment]
Thanks!

**Comment by arthur-2sheds-jackson** [comment]
Necropost: fixing link rot. 

PATRONI_RESTAPI_CONNECT_ADDRESS: IP address and port to access the REST API.

PATRONI_RESTAPI_LISTEN: IP address and port that Patroni will listen to, to provide health-check information for HAProxy.
