### ISSUE TITLE
timeline history consuming space in dcs

### ISSUE THREAD

**Issue by ksarabu1** [zalando/patroni#1487]
Do you foresee any issues with trimming the data in dcs to last 20 (or configurable) timeline history points?

```
zk: xxxxxxx:xxxx: get /......../xyz/history
....
dataLength = 31117
....
```

**Comment by CyberDem0n** [comment]
I have an idea to make it configurable how many lines to keep there.

**Comment by ksarabu1** [comment]
Do you see any advantage in keeping this configurable over a hard limit of 20? I have made changes to the code using hard limit and also an additional issue addressing replica reinitialize  when user-defined tablespaces are present. I can submit PR if hard-limit is acceptable. Otherwise, I will use configurable and submit changes.
Thanks.

**Comment by CyberDem0n** [comment]
I just envision that after making the hard limit people will start asking why is it so small or large.

**Comment by ksarabu1** [comment]
Agree. But, I think too many parameters would unnecessarily complicate and trying to see if we can avoid introducing new parameter for such a change where it won't make much of a difference for a custom-value over hard-limit?
Thanks.

**Comment by CyberDem0n** [comment]
I agree that 20 is a reasonable default. It should be ok for most of setups, but in case if someone is unhappy there'll be a way to change it.

I'm actually talking about global configuration, similar to maximum_lag_on_failover.

**Comment by ksarabu1** [comment]
Thanks. Will update the code to to use dcs param for time history points to retain in dcs & submit changes for both the issues.
