### ISSUE TITLE
HAProxy Implementation

### ISSUE THREAD

**Issue by Argha-2890** [zalando/patroni#1488]
Hi Team,

Not sure if this is right forum for my query, but I would really appreciate any assistance on this topic.

I am currently trying to deploy Load Balancing using HAProxy for my PostgreSQL cluster (used Patroni HA solution). Now, I have been able to successfully implement a basic setup and Load Balancing is working to an extent. My HAProxy configuration :

```
global
maxconn 100

defaults
log global
mode tcp
retries 2
timeout client 30m
timeout connect 4s
timeout server 30m
timeout check 5s

listen stats
mode http
bind *:7000
stats enable
stats uri /

listen read_write
bind *:5004
option httpchk OPTIONS /master
http-check expect status 200
default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
server pg1 IP:5432 maxconn 100 check port 8008
server pg2 IP:5432 maxconn 100 check port 8009

listen read_only
bind *:5005
mode tcp
balance roundrobin
http-check expect status 200
default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
server pg1 IP:5432 maxconn 100 check port 8008
server pg2 IP:5432 maxconn 100 check port 8009
```

However, my question is how will the application interact with HAProxy for read only requests. Does the application need to connect using port 5005 or is there any other logic required for  HAProxy to do this.

**Comment by vitabaks** [comment]
@Argha-2890 
Your application must have support sending read requests to a custom port 5005, and write requests to port 5004.

**Comment by Argha-2890** [comment]
@vitabaks Got it thanks.
