### ISSUE TITLE
data-checksums parameter shouldn't pass value

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#149]
if you do this:

    - data-checksums: True

you get this:

```
/usr/pgsql-9.5/bin/initdb: option '--data-checksums' doesn't allow an argument
Try "initdb --help" for more information.
pg_ctl: database system initialization failed
```

**Comment by CyberDem0n** [comment]
Hi Josh,

You don't need to pass value for the `data-checksum` option.
Just `- data-checksum` will perfectly work.

**Comment by jberkus** [comment]
ok, we need to document that then.  will open a new issue
