### ISSUE TITLE
switchover leads to rewind/reclone in third node if remove_data_directory_on_diverged_timelines is true

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#1493]
If I do a manual switchover, the third node (i.e. neither the old nor the new leader) gets rewound/recloned (depending on whether `use_pg_rewind` is set or not) if `remove_data_directory_on_diverged_timelines` is set to true. If the latter is not the case, the third node just closes the connection and happily follows the new one (I can post logs for that, if needed). If 
`remove_data_directory_on_diverged_timelines` is set to true, I get (with some additional debugging `info` added):

```
Apr 15 12:15:16 pg2 patroni[11343]: 2020-04-15 12:15:16,011 INFO: Lock owner: pg3; I am pg2
Apr 15 12:15:16 pg2 patroni[11343]: 2020-04-15 12:15:16,011 INFO: does not have lock
Apr 15 12:15:16 pg2 patroni[11343]: 2020-04-15 12:15:16,017 INFO: no action.  i am a secondary and i am following a leader
Apr 15 12:15:16 pg2 patroni[11343]: 2020-04-15 12:15:16,346 INFO: Got response from pg1 http://192.168.122.163:8008/patroni: {"state": "running", "postmaster_start_time": "2020-04-15 12:13:11.090 UTC", "role": "
Apr 15 12:15:16 pg2 patroni[11343]: 2020-04-15 12:15:16,347 INFO: manual failover: to pg1, i am pg2
Apr 15 12:15:18 pg2 patroni[11343]: 2020-04-15 12:15:18,369 INFO: Local timeline=5 lsn=0/C000178
Apr 15 12:15:18 pg2 patroni[11343]: 2020-04-15 12:15:18,379 INFO: master_timeline=6
Apr 15 12:15:18 pg2 patroni[11343]: 2020-04-15 12:15:18,379 INFO: master: history=1        0/4000178        no recovery target specified
Apr 15 12:15:18 pg2 patroni[11343]: 2        0/6000178        no recovery target specified
Apr 15 12:15:18 pg2 patroni[11343]: 3        0/8000258        no recovery target specified
Apr 15 12:15:18 pg2 patroni[11343]: 4        0/A000258        no recovery target specified
Apr 15 12:15:18 pg2 patroni[11343]: 5        0/C000178        no recovery target specified
Apr 15 12:15:18 pg2 patroni[11343]: 2020-04-15 12:15:18,379 INFO: need_rewind: None
Apr 15 12:15:18 pg2 patroni[11343]: 2020-04-15 12:15:18,379 INFO: parent_timeline: 1, local_timeline: 5
Apr 15 12:15:18 pg2 patroni[11343]: 2020-04-15 12:15:18,379 INFO: parent_timeline: 2, local_timeline: 5
Apr 15 12:15:18 pg2 patroni[11343]: 2020-04-15 12:15:18,379 INFO: parent_timeline: 3, local_timeline: 5
Apr 15 12:15:18 pg2 patroni[11343]: 2020-04-15 12:15:18,379 INFO: parent_timeline: 4, local_timeline: 5
Apr 15 12:15:18 pg2 patroni[11343]: 2020-04-15 12:15:18,379 INFO: parent_timeline: 5, local_timeline: 5
Apr 15 12:15:18 pg2 patroni[11343]: 2020-04-15 12:15:18,379 INFO: local_lsn: 201326968, switchpoint: 201326968
Apr 15 12:15:18 pg2 patroni[11343]: 2020-04-15 12:15:18,379 INFO: need_rewind at end: True
Apr 15 12:15:18 pg2 patroni[11343]: 2020-04-15 12:15:18,382 INFO: reinitializing due to diverged timelines
Apr 15 12:15:18 pg2 patroni[11343]: 2020-04-15 12:15:18,392 INFO: Removing data directory: /var/lib/postgresql/11/test
```

So we are on the same timeline and LSN as the old primary, yet we re-clone, because of:
```
                        need_rewind = parse_lsn(local_lsn) >= switchpoint 
```

If I relax that temporarily to `> switchpoint`, it does not re-clone, but I assume the `>=` is there intentionally?

So my question is whether there's something to be done here for a clean switchover event, i.e. whether Patroni can figure out that a clean switchover is happening and in that case allow for the third node to just follow the new leader in case its timeline/LSN aren't newer than it, of course.

**Comment by CyberDem0n** [comment]
> but I assume the >= is there intentionally?

I was trying to "replicate" pg_rewind [logic](https://github.com/postgres/postgres/blob/master/src/bin/pg_rewind/pg_rewind.c#L331), but you are right, there are certain issues.
Such a comparison makes total sense when we get the checkpoint record from the controldata.
In case if the postgres is running we take not the checkpoint location, but the current wal position, which apparently is the same as branching point and therefore rewind isn't required.

**Comment by mbanck** [comment]
Thanks!
