### ISSUE TITLE
Patroni fails to connect with zookeeper

### ISSUE THREAD

**Issue by Rajendra08** [zalando/patroni#1495]
Patroni uses kazoo to connect Zookeeper.
kazoo version specified in requirement.txt as 
**"patroni/requirements.txt" ==> kazoo>=1.3.1**

This was working fine till last month. 
Recently kazoo released 2.7.0 and it has breaking change 

**2.6.1:**
 https://github.com/python-zk/kazoo/blob/2.6.1/kazoo/protocol/connection.py

_def _connect(self, host, port):_
It has only two parameters

**2.7.0**
_def _connect(self, host, hostip, port):_

It has three parameters and "hostip" parameter has been added.

Because of this we get below exception when "patroni" tries to connect with zookeeper via kazoo.

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/kazoo/protocol/connection.py", line 565, in _connect_attempt
>     read_timeout, connect_timeout = self._connect(host, hostip, port)
> TypeError: _kazoo_connect() takes 3 positional arguments but 4 were given
> 2020-04-15 03:17:07,825 INFO: Zookeeper session closed, state: CLOSED
> Exception in thread Thread-4:
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.5/threading.py", line 862, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/kazoo/protocol/connection.py", line 497, in zk_loop
>     if retry(self._connect_loop, retry) is STOP_CONNECTING:
>   File "/usr/local/lib/python3.5/dist-packages/kazoo/retry.py", line 126, in __call__
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/kazoo/protocol/connection.py", line 537, in _connect_loop
>     status = self._connect_attempt(host, hostip, port, retry)
>   File "/usr/local/lib/python3.5/dist-packages/kazoo/protocol/connection.py", line 565, in _connect_attempt
>     read_timeout, connect_timeout = self._connect(host, hostip, port)
> TypeError: _kazoo_connect() takes 3 positional arguments but 4 were given

**Moreover "kazoo" 2.7.0 release doesn't support python 3.5 version, but patroni uses python 3.5.

We need to change "requirements.txt" file to use "kazoo>=1.3.1,<=2.6.1"**

Can some one fix this release quickly. Our project blocked because of this change.
We were using "patroni 1.6.0" for many days and it was working fine. but now stopped working

**Comment by CyberDem0n** [comment]
Just do `pip install kazoo==2.6.1` to fix it.
The current master already supports 2.7.0, we are going to do a release soon.
