### ISSUE TITLE
hello,ask a question about editing cluster configuration

### ISSUE THREAD

**Issue by cdy668** [zalando/patroni#1502]
When I edit the cluster configuration with the following command：
patronictl -c /etc/patroni/patroni.yml edit-config
After saving, I restarted the database cluster.the patroni.yml configuration file does not change and remains in its original state.
It seems that the changed configuration information will produce a patroni.dynamic.json file。
What do I need to do to synchronize the updated configuration to patroni.yml？

**Comment by uspen** [comment]
See https://patroni.readthedocs.io/en/latest/dynamic_configuration.html

edit-config writes to DCS
