### ISSUE TITLE
pgpass overwrite

### ISSUE THREAD

**Issue by sandeepkalra** [zalando/patroni#1511]
I have scripts that execute with different credentials (and -w to pick password from .pgpass). I am trying to use .pgpass that I have given to Patroni. It looks to me that Patroni overwrites the existing records to make it's own. If this is the case, it must append the record instead.

**Comment by CyberDem0n** [comment]
You can configure Patroni to use arbitrary pgpass file, there is no need to use _exactly_ .pgpass

**Comment by sandeepkalra** [comment]
Thanks for quick response!
