### ISSUE TITLE
Warning message when used consul and urllib3 v1.25.9

### ISSUE THREAD

**Issue by WiXZlo** [zalando/patroni#1516]
Hello.

OS: Ubuntu 18.04
When I use urllib3 from pip (v1.25.9) and use consul I get warning for patronictl
```
2020-04-28 17:42:11,444 - WARNING - /usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```
If I change consul->etcd then no warnings.
If I uninstall urllib and install via apt (v1.22-1ubuntu0.18.04.1 from ubuntu repo) then no warning.

**Comment by CyberDem0n** [comment]
What can I say?
Welcome to python dependency hell.
The requests module (used by consul) strictly checks urllib3 versions.
You did upgrade of urllib3, but not requests, so you got the warning.

This is not really Patroni problem. It uses only urllib3 and supports a wide range of its versions, just chose one that you like.

**Comment by WiXZlo** [comment]
Thanks.
With latest version from pip for requests and urllib3 works without warnings.
