### ISSUE TITLE
Actual replication lag obscured by formatting in patronictl list command

### ISSUE THREAD

**Issue by awiller42** [zalando/patroni#1536]
The replication lag shown by the command `patronictl list` is always displayed in megabytes. Due to rounding and formatting, small replication lag values are displayed as '0', even if the actual value is greater than zero, but smaller than 1 MB. This obscures important information.

I'm not sure how this is handled best, as the Unit 'MB' is fixed for the entire column/field:
https://github.com/zalando/patroni/blob/master/patroni/ctl.py#L755

As of now, the output fields and values seem to be exactly the same for all output formats (pretty, json, yaml, tsv). Keeping this assumption while solving the issue would only allow for one least-breaking-change solution:  Allow fractional replication lag values, displayed decimally.

This may break scripts consuming the output of patronictl that are not able to parse decimal numbers correctly, but would be compatible with resonably-designed scripts using common yaml/json parsers. Implementation would be the easiest of all options.

An alternative would be to differentiate on the `fmt` parameter (https://github.com/zalando/patroni/blob/master/patroni/ctl.py#L749) to change formatting only for the `pretty` output style so that the value is either shown in bytes, or even better, with an individual per-value suffixes like `k`, `M`  for better readability. This breaks consistency between output formats, the significance of which I cannot assess. 

In my opinion, the (compatibility-breaking, theoretical) way it should be is that at least the output modes that are meant to be parsed (`tsv`, `yaml`, etc.) output the lag in bytes, leaving conversion up to the user. For the pretty-printed table itself, aforementioned additional suffixes could be an option for better readability, while keeping the field name the same across all formats.

**Comment by CyberDem0n** [comment]
I don't see a lot of value in showing something smaller than 1MB in the lag column.
The number is not very precise anyway due to asynchronous nature.
I case if there is very little activity on the primary, the lag would be always more or less zero.
When there is a lot of going on and replica started lagging behind, usually lag quickly exceeds 1MB.

**Comment by awiller42** [comment]
Okay, I understand that reasoning - I just stumbled over this issue during initial evaluation / test, when there wasn't that much activity on the cluster, where it was somewhat irritating.

I dont know if there are use cases that require high availability, but generally have very little activity, so that this issue becomes relevant in production use. Possibly, one should explicitly look on / monitor PoststgreSQL replication behaviour if even low replication lag is of such relevance (or use sync replication).

Thanks!
