### ISSUE TITLE
Docs clarification: reload configuration

### ISSUE THREAD

**Issue by jsirex** [zalando/patroni#1540]
It is explicitly stated that `bootstrap.dcs` configuration loads from yaml configuration once and cannot be reload. I must use `edit-config` or `api` to reload.

But it is not clear for me what about another `bootstrap.*` options? If I change them and do `patronictl reload` - will it adjust pg_hba.conf according to `bootstrap.pg_hba`? Will it add new users if any in `bootstrap.users`? Will it update theirs passwords if only passwords changes? I'm expecting that the answer is "**no**". Because it is a "bootstrap" section. Am I right? Should documentation be updated to explicitly state this?

**Comment by kostiantyn-nemchenko** [comment]
You're right. Feel free to update documentation.
BTW you can create `bootstrap.dcs.pg_hba` section and change one via `patronictl edit-config`.

**Comment by jsirex** [comment]
No, I cannot. There is not documentation about `bootstrap.dcs.pg_hba`. There is `bootstrap.pg_hba`.
I spent week to understand the `patroni` and it still fills like and implicit magic everywhere.

I also cannot update documentation regarding tool I don't know

**Comment by CyberDem0n** [comment]
The bootstrap section works only once, during cluster initialization, when either initdb or custom bootstrap methods are executed.

Bootstrap.pg_hba  was invented a long time before we implemented `postgresql.pg_hba`, it was adding a few lines into pg_hba.conf generated by initdb. We don't need it anymore and should remove it from all places.

Boostrap.dcs might contain nearly everything from `postgresql` section, hence postgresql.pg_hba.

**Comment by jsirex** [comment]
@CyberDem0n thank you for clarification. Now I better understand the direction patroni is going.

If I change `postgresql.authentication` section will `patronictl` reload this? Documentation says "during initialization and later used by patroni`. I expect that if I change this section after initialization (for example change password) - I must manually update superusers' password, becuase patroni will use new password but will not updated user (because it only creates it on init)?

**Comment by CyberDem0n** [comment]
If you want to change credentials:
1. CREATE or UPDATE them manually in the database
2. update patroni.yaml (on all nodes)
3. run `patronictl reload <SCOPE>`

Patroni on all nodes will re-read patroni.yaml
