### ISSUE TITLE
Best way to use timescaledb-tune w/ Patroni manage config?

### ISSUE THREAD

**Issue by roshan5595** [zalando/patroni#1541]
Hello, I just started learning how to use Patroni to manage a PG cluster. My PG cluster is using timescaledb extension which has a list of settings that can be recommend by using a timescaledb-tune utility.  This is written to postgresql.conf.

From what I understand, Patroni maintains this file and on restarts using patronictl, this file is overwritten based on what is in patroni.yml. This ends up removing the tuning settings that timescaledb-tune wrote into this file. 

There are a few settings(max_connections, max_locks_per_transaction, max_worker_processes) that overlap between the default config Patroni provides that is stored as Dynamic Config and what timescaledb-tune recommends. I'm okay with Patroni overwriting these settings with whatever is stored in dcs. 

I would like to know if there is someway to utilize both these tools without them stepping on eachother.

**Comment by roshan5595** [comment]
timescaledb-tune also can write to another file, which I can include in postgres.conf but unfortunately it is overwritten on patronictl restart.

**Comment by vitabaks** [comment]
patroni renames the original postgresql.conf to postgresql.base.conf.
You can use the `--conf-path` option to write to postgresql.base.conf
example:

    timescaledb-tune --conf-path=/etc/postgresql/11/main/postgresql.base.conf

The parameters would be applied in the following order (run-time are given the highest priority):

    load parameters from file postgresql.base.conf (or from a custom_conf file, if set)
    load parameters from file postgresql.conf
    load parameters from file postgresql.auto.conf
    run-time parameter using -o –name=value


But, I would recommend using timescaledb-tune only to get recommendations, then you can decide which parameters to add to the patroni [configuration](https://patroni.readthedocs.io/en/latest/dynamic_configuration.html) file yourself.
If you just want to see the recommendations without writing:

    timescaledb-tune --dry-run --quiet --yes

**Comment by roshan5595** [comment]
Thank you @vitabaks !
