### ISSUE TITLE
REST API is trivial to accidentally DoS when TLS enabled

### ISSUE THREAD

**Issue by bjh21** [zalando/patroni#1545]
If I make a long-lived TCP connection to Patroni's REST API port, this causes any other attempts at connecting to it to time out until I close that connection. So if in one window I run:
```
# nc localhost 8008
```
then in another:
```
# curl --insecure https://localhost:8008/
curl: (7) Failed to connect to localhost port 8008: Connection timed out
```
This means that it's trivial to accidentally break the API endpoint on a Patroni node simply by opening a TCP connection to it and then forgetting to do anything. I discovered this because a nearby OpenVAS connected to my API port and thus broke my monitoring.

I think the REST API endpoint should either be able to cope with a reasonable number of simultaneous connections or should time out idle connections quickly. Alternatively, a documented way to get the cluster state from etcd might avoid some need for the REST API.

I've observed this problem on version 1.6.5-2.pgdg18.04+1 of the PGDG package of Patroni for Ubuntu, but I have no reason to think it's specific to the packaged version.

**Comment by CyberDem0n** [comment]
> So if in one window I run:
>  nc localhost 8008
> then in another:
>  curl --insecure https://localhost:8008/
> curl: (7) Failed to connect to localhost port 8008: Connection timed out

I can't reproduce it. Every incoming request is processed by a new thread, they are not waiting until the previous disconnects.

**Comment by bjh21** [comment]
That's very curious.  I shall investigate further.

**Comment by bjh21** [comment]
It appears that the problem only occurs when:
* I have TLS enabled on the API server, and
* The incoming connection stops before completing the TLS handshake.

So the problem doesn't occur if TLS is disabled (as it presumably was in your test).  It also doesn't occur if I connect using `openssl s_client` in place of `nc`: once the TLS handshake is complete, the new thread is properly created.

I'm sorry I didn't explicitly mention the use of TLS in original report.
