### ISSUE TITLE
Unable to add third node to Existing Patroni Cluster

### ISSUE THREAD

**Issue by Argha-2890** [zalando/patroni#1548]
Hi Team,

```
Patroni Version : 1.6.4
Postgresql Version: 11
```

I am getting the below error while setting up a new node to my existing Patroni cluster.

```
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 5, in <module>
    from patroni import main
ImportError: cannot import name 'main'
```

I've followed the same steps for installing Patroni HA cluster for the other nodes and didn't come across this issue.

Please give your suggestions in order to fix this.

**Comment by CyberDem0n** [comment]
> Patroni Version : 1.6.4
> Please give your suggestions in order to fix this.

Start from scratch and always use the lastest version.

**Comment by Argha-2890** [comment]
I've reinstalled all the libraries and modules, but I am still getting the same error. Infact I'm getting an error while doing patroni --version. 

```
/usr/local/bin$ patroni --version
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 5, in <module>
    from patroni import main
ImportError: cannot import name 'main'
```

Is this some issue related to Linux permissions?
