### ISSUE TITLE
Disable creation of PGPASS if using kerberos

### ISSUE THREAD

**Issue by RajKiranS** [zalando/patroni#1551]
Hello,

It doesn't make sense to create `PGPASS` file if we are using [kerberos](https://github.com/zalando/patroni/pull/1015). Can we disable in that case?

PGPASS is being created in [here](https://github.com/zalando/patroni/blob/881bba9e1cd081f7cd4c340f9a6ad977daa92c58/patroni/postgresql/config.py#L369).

I know that we don't populate or use PGPASS when kerberos is enabled, but creating parent dir of default PGPASS file could be a trouble when the default(~) directory doesn't exist on a node.

**Comment by CyberDem0n** [comment]
@RajKiranS you are right. Feel free to create a PR implementing the necessary check.
