### ISSUE TITLE
Can we have more than one Etcd at Postgres Patroni Cluster ?

### ISSUE THREAD

**Issue by sulito18** [zalando/patroni#1558]
Hi

Can we have more than one Etcd node at Postgres Patroni Cluster ? if yes ,please provide some config example or documentation about it .

example 

ETCD controller nodes (3 nodes)

etcd1-host
etcd2-host
etcd3-host

Databases nodes (2 nodes)

Postgres1-host
Postgres2-host

Thanks

**Comment by vitabaks** [comment]
Your cluster must have at least three nodes.
See doc:
https://etcd.io/docs/v3.4.0/op-guide/

Examples are in the past issues .  

Or use etcdadm
https://github.com/kubernetes-sigs/etcdadm

**Comment by nerzhul** [comment]
yes it's one of our setup at work. And it's clearly recommended.
Note: if you are fine with the answer please close the issue
