### ISSUE TITLE
Patronictl List not displaying a Node

### ISSUE THREAD

**Issue by Argha-2890** [zalando/patroni#1564]
Hi Team,

Below are the versions : 

```
Patroni : 1.6.5
PostgreSQL : 11.8
OS : Ubuntu 18.04
```

I have come across a strange issue and need some help regarding the same. One of my nodes is not showing in the `patronictl list` even though the node seems to be active and also data is getting replicated properly. The respective node "pg3" also doesn't show in the members list when I check in the etcd server list. Only when I restart the service that the issue gets resolved.

```
postgres@q-sw-pgdb-r05:/var/log/postgresql$ patronictl -c /etc/patroni/deepthought1.yml list
+ Cluster: deepthought (6828106004191544221) ----+-----------+
| Member |      Host     |  Role  |  State  | TL | Lag in MB |
+--------+---------------+--------+---------+----+-----------+
|  pg1   | 10.47.226.202 | Leader | running |  4 |           |
|  pg2   | 10.47.226.203 |        | running |  4 |         0 |
+--------+---------------+--------+---------+----+-----------+
```

```
postgres=# select * from pg_stat_replication ;
-[ RECORD 1 ]----+------------------------------
pid              | 115230
usesysid         | 16384
usename          | replicator
application_name | pg2
client_addr      | 10.47.226.203
client_hostname  |
client_port      | 50754
backend_start    | 2020-05-25 23:21:03.287489-07
backend_xmin     |
state            | streaming
sent_lsn         | 7/DA04ABF8
write_lsn        | 7/DA04ABF8
flush_lsn        | 7/DA04ABF8
replay_lsn       | 7/DA04ABF8
write_lag        |
flush_lag        |
replay_lag       |
sync_priority    | 0
sync_state       | async
-[ RECORD 2 ]----+------------------------------
pid              | 27783
usesysid         | 16384
usename          | replicator
application_name | pg3
client_addr      | 10.47.226.80
client_hostname  |
client_port      | 41776
backend_start    | 2020-05-28 03:17:51.67092-07
backend_xmin     |
state            | streaming
sent_lsn         | 7/DA04ABF8
write_lsn        | 7/DA04ABF8
flush_lsn        | 7/DA04ABF8
replay_lsn       | 7/DA04ABF8
write_lag        |
flush_lag        |
replay_lag       |
sync_priority    | 0
sync_state       | async
```

However, after a few hours again the same issue crops up and I am struggling to reproduce the issue from Postgresql & Patroni logs.

**Comment by CyberDem0n** [comment]
Looks like Patroni on pg3 is not running, you have to figure out why.
And pg1 should periodically write into logs `Failed to drop replication slot 'pg3'`

**Comment by Argha-2890** [comment]
> Looks like Patroni on pg3 is not running, you have to figure out why.

But If Patroni on pg3 is not running how come the data is getting replicated?..And i checked the logs and status of the patroni service in pg3, it's active.

> And pg1 should periodically write into logs `Failed to drop replication slot 'pg3'`

Yes..That's the error that I'm getting.. I saw one of the tickets which addressed this issue. 

https://github.com/zalando/patroni/issues/425

Could you please suggest further ways to debug this issue.

**Comment by CyberDem0n** [comment]
That's not Patroni replicating data, but PostgreSQL

**Comment by Argha-2890** [comment]
Got it..Thanks..Will check from my side and get back in case I need any further assistance.

**Comment by Argha-2890** [comment]
Hi Team,

I've been monitoring my Patroni cluster and intermittently I am still getting the issue w.r.t patroniclt list not showing all the members despite Patroni showing as running in both Patroni and Postgres logs. I am only getting this issue with my replicas, the leader never has this issue.

I had two questions:

1. I have a etcd cluster with 3 nodes. While starting  all my Patroni nodes, each node is picking a different etcd node for connection. Could it be an issue?

2. I'm getting the below warning in my logs. Could this be causing an issue??

`WARNING: Loop time exceeded, rescheduling immediately.`

**Comment by CyberDem0n** [comment]
> each node is picking a different etcd node for connection. Could it be an issue?

In case is etcd is properly clustered - no

> Could this be causing an issue??

In case if the HA loop takes longer than TTL - yes.
But you didn't show the configuration. Specifically ttl, loop_wait, and retry_timeout.

**Comment by Argha-2890** [comment]
> In case is etcd is properly clustered - no

ETCD is clustered properly as per my understanding.

```
etcd Version: 3.3.13

ETCDCTL_API=3 etcdctl endpoint status --cluster -w table
+--------------------------+------------------+---------+---------+-----------+-----------+------------+
|         ENDPOINT         |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+--------------------------+------------------+---------+---------+-----------+-----------+------------+
| http://etcd1:2379 | 1da7c39b7549d6f1 |  3.3.13 |   20 kB |      true |      1017 |    5100113 |
| http://etcd2:2379 | 3621abceb174911d |  3.3.13 |   20 kB |     false |      1017 |    5100113 |
| http://etcd3:2379 | 443fd214976c4c49 |  3.3.13 |   20 kB |     false |      1017 |    5100113 |
+--------------------------+------------------+---------+---------+-----------+-----------+------------+
 
```
> > Could this be causing an issue??
> 
> In case if the HA loop takes longer than TTL - yes.
> But you didn't show the configuration. Specifically ttl, loop_wait, and retry_timeout.

Configuration : 


```
:~$ patronictl -c /etc/patroni/deepthought1.yml show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 300
    max_replication_slots: 30
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

**Comment by CyberDem0n** [comment]
Are you sure that time is in sync across all etcd nodes?

> WARNING: Loop time exceeded, rescheduling immediately.

This is an indicator that Patroni can't run HA loop in 10 seconds. Maybe it doesn't have enough resources (cpu, memory)?

**Comment by Argha-2890** [comment]
> Are you sure that time is in sync across all etcd nodes?

If you don't mind could you please elaborate on this. Although I am seeing that leader of the etcd cluster also keeps on changing.

ETCD Config : 


```
[Unit]
Description=etcd
Documentation=https://github.com/coreos/etcd
Conflicts=etcd.service
Conflicts=etcd2.service

[Service]
Type=notify
Restart=always
RestartSec=5s
LimitNOFILE=40000
TimeoutStartSec=0

ExecStart=/usr/local/bin/etcd --name etcd1  \
          --initial-advertise-peer-urls http://xx.xx.xx:2380 \
          --listen-peer-urls http://xx.xx.xx.xx:2380 \
          --listen-client-urls http://xx.xx.xx.xx:2379,http://127.0.0.1:2379 \
          --advertise-client-urls http://xx.xx.xx.xx:2379 \
          --initial-cluster-token dt_cluster \
          --initial-cluster etcd1=http://xx.xx.xx:2380,etcd2=http://xx.xx.xx:2380,etcd3=http://xx.xx.xx:2380  \
          --initial-cluster-state new \
          --data-dir /var/lib/etcd
		  
		  

[Install]
WantedBy=multi-user.target	
```


> This is an indicator that Patroni can't run HA loop in 10 seconds. Maybe it doesn't have enough resources (cpu, memory)?

Resources shouldn't be an issue. All of the nodes in question have 128 GB RAM and 16 core CPUs.

**Comment by CyberDem0n** [comment]
The system clock must be synchronized across all etcd members.
Etcd is also very sensitive to disk latency, therefore you should not keep etcd data directory and PGDATA on the same device.

> I am seeing that leader of the etcd cluster also keeps on changing.

Have you checked etcd logs?

**Comment by Argha-2890** [comment]
@CyberDem0n - My postgresql and etcd services are running on different nodes.

What should I look for in the logs. The issue with clock synchronization was resolved at 31st May as per my logs.


```

May 31 04:53:11 q-sw-pgdb-p-r01 etcd[68303]: the clock difference against peer 1da7c39b7549d6f1 is too high [4.556111601s > 1s] (prober "ROUND_TRIPPER_RAFT_MESSAGE")
May 31 04:53:41 q-sw-pgdb-p-r01 etcd[68303]: the clock difference against peer 1da7c39b7549d6f1 is too high [1.445491254s > 1s] (prober "ROUND_TRIPPER_SNAPSHOT")
May 31 04:53:41 q-sw-pgdb-p-r01 etcd[68303]: the clock difference against peer 1da7c39b7549d6f1 is too high [1.445216326s > 1s] (prober "ROUND_TRIPPER_RAFT_MESSAGE")

```

**Comment by CyberDem0n** [comment]
I would still double-check that time is in sync across all nodes.

**Comment by Argha-2890** [comment]
Ok..So basically the time in all the nodes should be same.  I will make the changes and check whether issue still persists.

FYI, I found that the time difference between most of our Postgresql and etcd is around 5-10 second,barring one of the etcd nodes where it's quite high. Could this be the root cause for this issue?

**Comment by CyberDem0n** [comment]
Yes, it could be the root cause.

**Comment by Argha-2890** [comment]
Syncing the clock time in all the servers has resolved the issue. Thank you very much.

**Comment by huchangqiqi** [comment]
> Looks like Patroni on pg3 is not running, you have to figure out why.
> And pg1 should periodically write into logs `Failed to drop replication slot 'pg3'`

which situation will cause it periodically write into logs `Failed to drop replication slot `
i notice if _schedule_load_slots = False, if the slots is not active , it will not call drop_replicaiton_slots,
if i has called drop_replicaiton_slots but failed due to the slots is still active, it will try to do it again and again.
i my environment, i have a 3 node patroni cluseter,  and i also have some postgres use logical replication with the patroni leader node, but i find the patroni leader node try to drop the logical replication slots, and report `Failed to drop replication slot `
the patroni version is v1.6.0 and postgres version is 10.

**Comment by huchangqiqi** [comment]
any way to stop it call `drop_replicaiton_slots`, because if it drop the slots, on my other postgres machine which subscribe the publication running a program which will do drop subscription and truncate table, and recreate the subscription (which will auto create slots on the publication side)

**Comment by huchangqiqi** [comment]
every time in run_cycle when it comes 
[here](https://github.com/zalando/patroni/blob/278bf9852b0d74bd2a2f166bce6f7a007cee9343/patroni/ha.py#L1324)
it call `sync_replication_slots`
and some reason it call `drop_replicaiton_slots` 
[failed](https://github.com/zalando/patroni/blob/278bf9852b0d74bd2a2f166bce6f7a007cee9343/patroni/postgresql/slots.py#L56)
and it will periodically write into logs Failed to drop replication slot

**Comment by cobolbaby** [comment]
Same question.
