### ISSUE TITLE
Add before_role_change as a callback

### ISSUE THREAD

**Issue by avinashvallarapu** [zalando/patroni#1567]
Hi Team,

Several times, due to some of limitations related to logical replication or for some of the preparations required in the Application ecosystem, we see several requirements related to performing an action before a failover is done. But this time, it has got to be **synchronous** as it is an action that must be performed before the failover is done. 

Was looking at the code and all the callbacks are performed as asynchronous. But this should be synchronous and only allowed to run on the node with the new role master. So, the action can be performed on the newly elected leader before promoting the leader. 

As this is not a mandate to set it, it may not cause any issues for whatever is existing today. 
The only reason why several users get stuck with some HA tools (unwillingly) though they wish to take advantages of Patroni is because : (1)we do not have an option to call a script to actually perform some prepare or the actual scripted failover (like promote_command : ) like some other HA tools today. 

All of this can be solved with a synchronous before_role_change callback. May require some minor changes to callback function and may be we add a sync_wait function. 
What are your thoughts ?

**Comment by CyberDem0n** [comment]
You need to take a look at https://github.com/zalando/patroni/pull/1099

**Comment by avinashvallarapu** [comment]
WOW, thank you. So, once the PR is merged to master, we should see a new parameter pre_promote: that could let us run a script before promote. Thanks again.

**Comment by CyberDem0n** [comment]
Actually I would suggest you to try it proactively, i.e. apply patch, test and maybe put on one of your test systems.

**Comment by avinashvallarapu** [comment]
Yeah, already on it. Thanks again.

**Comment by BijiPanicker** [comment]
@avinashvallarapu Were you able to achieve " an action that must be performed before the failover is done" using pre_promote ?
