### ISSUE TITLE
Missing member in patronictl list json output

### ISSUE THREAD

**Issue by nvarscar** [zalando/patroni#1572]
It seems that after [this](https://github.com/zalando/patroni/pull/1486/files#diff-b558c390fbbb65333f66b7b6a8fe73cdR170) change, the JSON output omits the members that have empty value, which brings inconsistency to the output: in my case the "Role" column is empty on slaves and thus omitted by the command.
Before:
```
{"Lag in MB": 0.0, "Pending restart": "", "State": "running", "Member": "server-1", "Cluster": "server", "Host": "10.0.0.1", "Role": "", "TL": 5}
```
After:
```
{"Cluster": "server", "Member": "server-1", "Host": "10.0.0.1", "State": "running", "TL": 5, "Lag in MB": 0}
```

**Comment by CyberDem0n** [comment]
That was intentional, I don't see much value in showing empty values.

**Comment by nvarscar** [comment]
In my use-case I parse the json to get the leader out of the member list and my code didn't expect that the dict key, previously present in each member, would disappear.

**Comment by CyberDem0n** [comment]
Sorry about that.
Maybe you should better switch to the `GET /cluster` endpoint. I can promise that it would be more consistent and backward-compatible. It also contains information about the pause and scheduled switchover.

**Comment by nvarscar** [comment]
Thanks! I'll try that.
PS for some reason the /cluster endpoint returns one node being
```
"role": "replica", "state": "starting", "lag": "unknown"
``` while the other replica has all the proper values. The node is online and fully functional from what I can see.

**Comment by CyberDem0n** [comment]
This is strange. What dcs is used?

**Comment by nvarscar** [comment]
Zookeeper, yep. In this case, should I be concerned when using the /cluster endpoint? Or it only affects that status?
BTW, after patroni service restart it shows proper state for all nodes. This particular node was re-initialized yesterday, perhaps that's where the starting state is coming from.

**Comment by CyberDem0n** [comment]
There is no consistent view of node status across the cluster. Patroni itself needs to know only names of nodes and IP's, therefore it does some aggressive caching and skips changes of member znodes. It doesn't affect the failover, but apparently the cluster endpoint shows wrong information in case of zookeeper :(
You probably better stick with patronictl, and fill up missing keys with empty strings.
