### ISSUE TITLE
sed error in pg_createconfig_patroni

### ISSUE THREAD

**Issue by victor-sudakov** [zalando/patroni#1574]
/usr/bin/pg_createconfig_patroni from Debian buster gives the following error when a consul configuration is specified in dcs.yml:

pg_createconfig_patroni 12 foo1
sed: -e expression #9, char 40: unknown option to `s'
 
Attaching the offending files.
[files.zip](https://github.com/zalando/patroni/files/4721783/files.zip)

There is no problem with the default etcd configuration.

**Comment by victor-sudakov** [comment]
Sed expression No 9 is seemingly `-e s/@DCS_CONFIG@/consul:\n `

**Comment by victor-sudakov** [comment]
Workaround: slashes in URLs should be escaped in dcs.yml like this:
```
consul:
  hosts: http:\/\/127.0.0.1:8500
  register_service: true
```
Is it documented somewhere?

**Comment by CyberDem0n** [comment]
> Workaround: slashes in URLs should be escaped in dcs.yml like this:

1. There is no `consul.hosts`, only `consul.host`
2. The `consul.host` expects to get `host:port` string, to the url

**Comment by victor-sudakov** [comment]
> > Workaround: slashes in URLs should be escaped in dcs.yml like this:
> 
>     1. There is no `consul.hosts`, only `consul.host`
> 
>     2. The `consul.host` expects to get `host:port` string, to the url

Then the vanilla dcs.yml from the patroni 1.5.5-2 Debian package is incorrect, because it looks like this:
```
#etcd:
#  host: 127.0.0.1:2379

#consul:
#  host: http://127.0.0.1:8500
#  host: https://127.0.0.1:8500

zookeeper:
  hosts: 127.0.0.1:2181

```
And "host: http://127.0.0.1:8500" in patroni config throws a Python error: patroni.dcs.consul.ConsulError: 'Consul is not responding properly' while "hosts: http://127.0.0.1:8500" even works there!

**Comment by CyberDem0n** [comment]
> while "hosts: http://127.0.0.1:8500" even works there!

This is just a coincidence. If the `consul.host` unspecified Patroni is using `127.0.0.1:8500` by default.

> Then the vanilla dcs.yml from the patroni 1.5.5-2 Debian package is incorrect, because it looks like this:

Sure, but packages are maintained not by us.
cc @mbanck @df7cb

**Comment by victor-sudakov** [comment]
> > while "hosts: http://127.0.0.1:8500" even works there!
> 
> This is just a coincidence. If the `consul.host` unspecified Patroni is using `127.0.0.1:8500` by default.
> 

Oh, I see now.

> > Then the vanilla dcs.yml from the patroni 1.5.5-2 Debian package is incorrect, because it looks like this:
> 
> Sure, but packages are maintained not by us.
> cc @mbanck @df7cb

Where do I open an issue about the Debian package? And I think we can close this one.

**Comment by mbanck** [comment]
> > > while "hosts: http://127.0.0.1:8500" even works there!
> > 
> > 
> > This is just a coincidence. If the `consul.host` unspecified Patroni is using `127.0.0.1:8500` by default.
> 
> Oh, I see now.
> 
> > > Then the vanilla dcs.yml from the patroni 1.5.5-2 Debian package is incorrect, because it looks like this:
> > 
> > 
> > Sure, but packages are maintained not by us.
> > cc @mbanck @df7cb
> 
> Where do I open an issue about the Debian package? And I think we can close this one.

See https://www.debian.org/Bugs/Reporting

**Comment by victor-sudakov** [comment]
> > > Sure, but packages are maintained not by us.
> > > cc @mbanck @df7cb
> > 
> > 
> > Where do I open an issue about the Debian package? And I think we can close this one.
> 
> See https://www.debian.org/Bugs/Reporting

Is this really a Debian bug to be reported to the Debian team? My patroni install comes from pgdg:
Package: patroni
Versions: 
1.6.5-2.pgdg100+1 (/var/lib/apt/lists/apt.postgresql.org_pub_repos_apt_dists_buster-pgdg_main_binary-amd64_Packages)

**Comment by mbanck** [comment]
Well, it's an issue in the Debian packaging; there is no separate issue tracker for binary packages on apt.postgresql.org, they are just rebuilds of the Debian package.

About the issue, it is commented-out example config and I admit I don't test it with consul regularly. I'll update the example configuration, but the idea is that the user adapts it to their needs.

**Comment by mbanck** [comment]
Is https://salsa.debian.org/postgresql/patroni/-/commit/98213cc260cbe1ed768866bbc0d915f077588ed9 okay?

**Comment by victor-sudakov** [comment]
> Is https://salsa.debian.org/postgresql/patroni/-/commit/98213cc260cbe1ed768866bbc0d915f077588ed9 okay?

Looks fine to me, thank you!
