### ISSUE TITLE
set a weight for leader election

### ISSUE THREAD

**Issue by cskinfill** [zalando/patroni#1577]
Is it possible to set a weight or other factor to influence the leader election?  I'd like to run a cluster with 3 db nodes in the same, central region, and 2 in separate regions.  I'd like to weight the 3 nodes in the central region so they are more likely to become the master, and allow for the other 2 to be used as read-only replicas and only prompted to master if the central nodes are all completely unavailable.

Doable?

**Comment by CyberDem0n** [comment]
It is only possible to mark some nodes which should never become the leader with `nofailover` tag: https://patroni.readthedocs.io/en/latest/SETTINGS.html#tags

**Comment by lehab666** [comment]
Where can i read how the elections works? Cant find this information. In some place i see, that election uses etcd (or whatever), is it true? In some place i see that nearest slave is preferred, but what if they all are the same?
Sory, little offtop, but problem si similar, as i think. 
Thank you!

**Comment by CyberDem0n** [comment]
I would recommend you to go through tutorial: https://github.com/patroni-training/2019

**Comment by dberardo** [comment]
this feature would be of very high importance, as one could save costs, allocating higher resources to the high priority node, while still benefiting from HA.

is this a limitation of etcd or of patroni itself?
