### ISSUE TITLE
Running patroni and postgres in managed kubernetes 

### ISSUE THREAD

**Issue by smogili1** [zalando/patroni#1595]
Hi - Anyone use patroni and postgres in a managed k8s instance such as GKE / Digital Ocean with HA ? 

I am wondering what I should be aware of before making the switch. Concerned about performance and stability. Please share if you are doing this already.

Thanks,

**Comment by CyberDem0n** [comment]
For production we use [Postgres Operator](https://github.com/zalando/postgres-operator) and [Spilo](https://github.com/zalando/spilo).

Performance depends only on your environment and how you tune PostgreSQL.
