### ISSUE TITLE
Production Grade - Patroni

### ISSUE THREAD

**Issue by dhanasg** [zalando/patroni#1598]
Hi,

I am looking for Production grade Patroni cluster setup. Can you kindly help with a corresponding helm chart?

As per below links, i see Production Grade is yet to be released. Sorry, if i am looking at an older readout.

https://github.com/zalando/patroni/blob/master/Dockerfile
https://github.com/zalando/patroni/blob/master/docker/README.md

**Comment by CyberDem0n** [comment]
For production we use [Postgres Operator](https://github.com/zalando/postgres-operator) and [Spilo](https://github.com/zalando/spilo).

Performance depends only on your environment and how you tune PostgreSQL.
