### ISSUE TITLE
Error starting PATRONI

### ISSUE THREAD

**Issue by Mahe-alain** [zalando/patroni#1605]
Hello,

Here is the error message:

[root@mfle1548q ~]# systemctl status patroni
● patroni.service - PostgreSQL high-availability manager
   Loaded: loaded (/usr/lib/systemd/system/patroni.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2020-07-07 09:31:10 CEST; 10s ago
  Process: 25557 ExecStart=/opt/app/patroni/bin/patroni ${PATRONI_CONFIG_LOCATION} (code=exited, status=1/FAILURE)
 Main PID: 25557 (code=exited, status=1/FAILURE)

Jul 07 09:31:10 mfle1548q patroni[25557]: File "/opt/app/patroni/lib/python3.6/site-packages/patroni/ha.py", line 1260, in _run_cycle
Jul 07 09:31:10 mfle1548q patroni[25557]: return self.post_bootstrap()
Jul 07 09:31:10 mfle1548q patroni[25557]: File "/opt/app/patroni/lib/python3.6/site-packages/patroni/ha.py", line 1156, in post_bootstrap
Jul 07 09:31:10 mfle1548q patroni[25557]: self.cancel_initialization()
Jul 07 09:31:10 mfle1548q patroni[25557]: File "/opt/app/patroni/lib/python3.6/site-packages/patroni/ha.py", line 1151, in cancel_initialization
Jul 07 09:31:10 mfle1548q patroni[25557]: raise PatroniException('Failed to bootstrap cluster')
Jul 07 09:31:10 mfle1548q patroni[25557]: patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
Jul 07 09:31:10 mfle1548q systemd[1]: patroni.service: main process exited, code=exited, status=1/FAILURE
Jul 07 09:31:10 mfle1548q systemd[1]: Unit patroni.service entered failed state.
Jul 07 09:31:10 mfle1548q systemd[1]: patroni.service failed.

Thanks for your help

**Comment by CyberDem0n** [comment]
You have to look into Patroni logs. There should be a bit more information pointing to the exact error.

**Comment by Mahe-alain** [comment]
Thank you, I found the origin of the error, an error in the PATH
