### ISSUE TITLE
Lack of documented procedure of upgrading a PostgreSQL cluster managed by Patroni

### ISSUE THREAD

**Issue by victor-sudakov** [zalando/patroni#1606]
If I run a Patroni cluster with PostgreSQL 10 and want to upgrade the cluster members to another major version, e.g. PostgreSQL 12, is there a documented step-by-step procedure of doing that, with minimum downtime and without losing data?

I'm well familiar with pg_upgrade and pg_basebackup, but what would be the recommended steps of upgrading a Patroni cluster?

**Comment by CyberDem0n** [comment]
This question poped up a [few times](https://github.com/zalando/patroni/issues?q=is%3Aissue+pg_upgrade+is%3Aclosed) already.
Some of them have the answer for sure, for example https://github.com/zalando/patroni/issues/541#issuecomment-349229838.

Since Patroni is open source project feel free to open a PR updating the documentation.

**Comment by victor-sudakov** [comment]
> Some of them have the answer for sure, for example [#541 (comment)](https://github.com/zalando/patroni/issues/541#issuecomment-349229838).
> 
After pg_upgrade I will have a completely new Postgres instance with a new database system identifier. So basically I should demolish all my Patroni cluster and then follow https://patroni.readthedocs.io/en/latest/existing_data.html as if converting from standalone?

> Since Patroni is open source project feel free to open a PR updating the documentation.

Excuse me, where do I open PRs for documentation? It would be good to have all of the above mentioned in the docs.

**Comment by CyberDem0n** [comment]
> So basically I should demolish all my Patroni cluster and then follow

Not really. You can continue using the existing cluster, just need to update patroni config and remove the initialize key from DCS, because it contains the cluster system identifier.

> Excuse me, where do I open PRs for documentation? It would be good to have all of the above mentioned in the docs.

[Readthedocs](https://patroni.readthedocs.io/en/latest/), on every page, in the top-right corner there is a link, "Edit on GitHub".

**Comment by victor-sudakov** [comment]
> > So basically I should demolish all my Patroni cluster and then follow
> 
> Not really. You can continue using the existing cluster, just need to update patroni config and remove the initialize key from DCS, because it contains the cluster system identifier.

As running pg_upgrade on standbys is not supported, I don't think the existing cluster will be of any use. Anyway you'll have to drop _all_ the standbys from Patroni and re-add them for pg_basebackup to happen on them.

> [Readthedocs](https://patroni.readthedocs.io/en/latest/), on every page, in the top-right corner there is a link, "Edit on GitHub".

As soon as I understand the procedure and caveats, I'll try to contribute something.

**Comment by victor-sudakov** [comment]
This is actually why the procedure https://github.com/zalando/patroni/issues/541#issuecomment-349229838 looks incomplete to me. You stop the cluster, update Postgres binaries on the node which was (?) the last master, run pg_upgrade on the node which was the last master, remove initialize key from DCS. Then you should update Postgres binaries on the standby nodes... and probably wipe PGDATA on them before starting patroni?

**Comment by CyberDem0n** [comment]
Yes, you only need to run pg_upgrade on the former primary.
And you don't necessarily need to rebuild replicas from scratch, if a few prerequisites are met:
1. First, do a fast shutdown of the primary
2. Shut down replicas and make sure that they received all changes from the primary
3. Run pg_upgrade with `-k` option.
4. Follow the [procedure](https://www.postgresql.org/docs/current/pgupgrade.html#PGUPGRADE-STEP-REPLICAS) to rsync (upgrade) replicas

Important that you should not try to start the former primary before you do rsync.

**Comment by victor-sudakov** [comment]
Though it is documented, I would not use the rsync procedure in production. It may be faster, but has too many caveats, and speed seems the only gain. IMHO having Patroni run basebackup for me is much better, especially that the standby nodes will be added to the cluster automatically right after basebackup is successfully finished.

**Comment by CyberDem0n** [comment]
Everybody decides on its own. Rebuilding 5TB-10TB nodes is not a very enjoyable exercise.

**Comment by victor-sudakov** [comment]
5TB-10TB of data seems like an extreme case to me. Anyway, I would like to know if Patroni is officially capable of "adopting" a replica created by some means outside of Patroni (be it rsync or whatever).

**Comment by CyberDem0n** [comment]
> is officially capable of "adopting" a replica created by some means outside of Patroni (be it rsync or whatever).

I don't see any obstacles, but it is your responsibility to provide the correct Patroni configuration.

**Comment by victor-sudakov** [comment]
> > is officially capable of "adopting" a replica created by some means outside of Patroni (be it rsync or whatever).
> 
> I don't see any obstacles, but it is your responsibility to provide the correct Patroni configuration.

What should I put into postgresql.create_replica_methods if I'm going to adopt an already existing replica? Something like /bin/true ?

**Comment by CyberDem0n** [comment]
Since the PGDATA is there and non-empty whatever you put there will not be used anyway, Patroni will only try to start postgres if it is not yet running.

**Comment by victor-sudakov** [comment]
> Since the PGDATA is there and non-empty whatever you put there will not be used anyway, Patroni will only try to start postgres if it is not yet running.

In Debian you may encounter a surprise. In the packaged Patroni config, create_replica_method is set to "command: /usr/share/patroni/pg_clonecluster_patroni" which includes "rm -rf $DATADIR " among other things.

**Comment by CyberDem0n** [comment]
That doesn't change anything. Patroni is also deleting PGDATA before calling the create replica script/pg_basebackup. The trick is _when_ it calls it. There are only three cases:
1. When explicitly asked to do so (patronictl reinit)
2. When replica timeline diverges from the primary, pg_rewind is disabled and `remove_data_directory_on_diverged_timelines` is set.
3. When pg_rewind failed and `remove_data_directory_on_rewind_failure` is set.

Aforementioned parameters you can find in the documentation: https://patroni.readthedocs.io/en/latest/SETTINGS.html#postgresql

**Comment by victor-sudakov** [comment]
> That doesn't change anything. Patroni is also deleting PGDATA before calling the create replica script/pg_basebackup. 

So "rm -rf $DATADIR " in  /usr/share/patroni/pg_clonecluster_patroni is actually superfluous and not necessary?

**Comment by CyberDem0n** [comment]
There might be good reasons to do so, for example if the script itself is doing retries.

**Comment by victor-sudakov** [comment]
> There might be good reasons to do so, for example if the script itself is doing retries.

No, not actually. Have a look if you are interested.
[pg_clonecluster_patroni.gz](https://github.com/zalando/patroni/files/4922730/pg_clonecluster_patroni.gz)
