### ISSUE TITLE
Node cannot restart

### ISSUE THREAD

**Issue by dlacoste-esrf** [zalando/patroni#1611]
Hi,
After one of the node of my cluster went down it couldn't restart.
It was keeping trying to restart but failed each time with:
`Traceback (most recent call last):
   File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql/rewind.py", line 59, in check_leader_is_not_in_recovery
     with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **kwargs) as cur:
   File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
     return next(self.gen)
   File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
     with psycopg2.connect(**kwargs) as conn:
   File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", line 126, in connect
     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
 psycopg2.OperationalError: FATAL:  password authentication failed for user "rewind"
 FATAL:  password authentication failed for user "rewind"`

changing the rewind auth parameter in the patroni.yml file to a user I knew could log in allowed me to start the node again.
But what is this user rewind ? Do I have to create it on the database myself or is it managed by patroni ? 

Thanks

**Comment by CyberDem0n** [comment]
If the user is defined in the config file when you initialize the new cluster it will create it automatically and grant [necessary permissions](https://www.postgresql.org/docs/11/app-pgrewind.html#id-1.9.5.8.8) to it.

If you changed Patroni configs for already existing cluster - Patroni will not create the user or grant permissions on functions.

**Comment by dlacoste-esrf** [comment]
thanks, this is what I guessed.
But then something happened that I couldn't log in with this user anymore. And it made the node unavailable.
