### ISSUE TITLE
[docs] Required Consul ACLs

### ISSUE THREAD

**Issue by Legogris** [zalando/patroni#1615]
When using a Consul Cluster with ACLs, the token needs to have sufficient ACL permissions (`key_prefix`/`service`). The required permissions are missing from docs.

**Comment by CyberDem0n** [comment]
Hi @Legogris, please feel free to create a PR updating docs.

**Comment by Legogris** [comment]
> Hi @Legogris, please feel free to create a PR updating docs.

I probably will, I just have to figure out what's required first, still troubleshooting!

**Comment by Legogris** [comment]
Took a shot at this in #1626
