### ISSUE TITLE
 ERROR: Can not fetch local timeline and lsn from replication connection

### ISSUE THREAD

**Issue by gabricar** [zalando/patroni#1618]
I have 2 cluster deployed with the same configuration (using ansible) but just one cluster has those error messages. I'm not sure what is wrong here. 

Jul 21 13:38:02 brm-prhsnsdb02 patroni: 2020-07-21 13:38:02,888 ERROR: Can not fetch local timeline and lsn from replication connection
Jul 21 13:38:02 brm-prhsnsdb02 patroni: Traceback (most recent call last):
Jul 21 13:38:02 brm-prhsnsdb02 patroni: File "/opt/patroni/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 685, in get_local_timeline_lsn_from_replication_connection
Jul 21 13:38:02 brm-prhsnsdb02 patroni: with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
Jul 21 13:38:02 brm-prhsnsdb02 patroni: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Jul 21 13:38:02 brm-prhsnsdb02 patroni: return next(self.gen)
Jul 21 13:38:02 brm-prhsnsdb02 patroni: File "/opt/patroni/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 679, in get_replication_connection_cursor
Jul 21 13:38:02 brm-prhsnsdb02 patroni: with get_connection_cursor(**conn_kwargs) as cur:
Jul 21 13:38:02 brm-prhsnsdb02 patroni: File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
Jul 21 13:38:02 brm-prhsnsdb02 patroni: return next(self.gen)
Jul 21 13:38:02 brm-prhsnsdb02 patroni: File "/opt/patroni/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Jul 21 13:38:02 brm-prhsnsdb02 patroni: with psycopg2.connect(**kwargs) as conn:
Jul 21 13:38:02 brm-prhsnsdb02 patroni: File "/opt/patroni/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
Jul 21 13:38:02 brm-prhsnsdb02 patroni: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Jul 21 13:38:02 brm-prhsnsdb02 patroni: psycopg2.OperationalError: timeout expired
Jul 21 13:38:02 brm-prhsnsdb02 patroni: could not create socket: Address family not supported by protocol

patroni version is 1.6.5

My config:

/opt/patroni/etc/postgresql.yml
scope: psql_cluster_11
namespace: /service/
name: brm-prhsnsdb02

restapi:
  listen: 0.0.0.0:8008
  connect_address: brm-prhsnsdb02:8008
  authentication:
    username: patroniapi
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

etcd:
  hosts: 10.1.77.11:2379,10.1.77.12:2379,10.1.77.13:2379
  protocol: https
  cacert: /opt/postgres/ca.pem
  cert: /opt/postgres/patroni_client_cert.pem
  key: /opt/postgres/patroni_client_key.pem

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    check_timeline: false
    postgresql:
      use_pg_rewind: false
      use_slots: true
      parameters:
        max_connections: 100
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: replica
        wal_log_hints: on
        track_commit_timestamp: off
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_segments: 8
        ssl: "on"
        ssl_ca_file: "/opt/postgres/ca.pem"
        ssl_key_file: "/opt/postgres/postgres_server_key.pem"
        ssl_cert_file: "/opt/postgres/postgres_server_cert.pem"
        log_filename: server_log.%H%M
        log_rotation_age: 1440
        log_rotation_size: 1000
        logging_collector: on
        log_truncate_on_rotation: on
        log_min_error_statement: error
        log_connections: on
        log_error_verbosity: default
        log_statement: ddl
        log_min_messages: warning
  initdb:
    - encoding: UTF8
    - data-checksums
  users:
    postgres:
      password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    replicator:
      password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      options:
        - replication

postgresql:
  use_unix_socket: true
  listen: 0.0.0.0:5432
  connect_address: brm-prhsnsdb02:5432
  data_dir: /opt/pgsql/11/data
  bin_dir: /usr/pgsql-11/bin
  config_dir: /opt/pgsql/11/data
  pgpass: /var/lib/pgsql/.pgpass
  authentication:
    superuser:
      username: postgres
      password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      sslmode: verify-ca
      sslkey: /opt/postgres/patroni_supuser_key.pem
      sslcert: /opt/postgres/patroni_supuser_cert.pem
      sslrootcert: /opt/postgres/ca.pem
  
    replication:
      username: replicator
      password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      sslmode: verify-ca
      sslkey: /opt/postgres/patroni_replication_key.pem
      sslcert: /opt/postgres/patroni_replication_cert.pem
      sslrootcert: /opt/postgres/ca.pem
  
  create_replica_methods:
    - basebackup
  parameters:
    unix_socket_directories: /var/run/postgresql
  pg_hba:
    - hostssl all all 0.0.0.0/0 md5 clientcert=1
    - hostssl replication replicator 0.0.0.0/0 md5 clientcert=1
    - local all all  md5 
    - host all all 127.0.0.1/32 trust 
    - host all all ::1/128 trust 
    - local replication all  trust 
  pg_ctl_timeout: 60

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

All 3 nodes are presenting the same error message

+ Cluster: psql_cluster_11 (6823030040516528033) ----+----+-----------+
|     Member     |      Host      |  Role  |  State  | TL | Lag in MB |
+----------------+----------------+--------+---------+----+-----------+
| brm-prhsnsdb01 | brm-prhsnsdb01 |        | running |    |         0 |
| brm-prhsnsdb02 | brm-prhsnsdb02 |        | running |    |         0 |
| brm-prhsnsdb03 | brm-prhsnsdb03 | Leader | running |  7 |           |
+----------------+----------------+--------+---------+----+-----------+

**Comment by CyberDem0n** [comment]
It is trying to connect via `localhost`.

**Comment by gabricar** [comment]
@CyberDem0n  where do you see this?

**Comment by CyberDem0n** [comment]
I just know. Please make sure that postgres is accessible via the localhost and port 5432

**Comment by gabricar** [comment]
I've found the issue... closing this. It was a mistype on /etc/hosts 

Thank you very much
