### ISSUE TITLE
 etcd.EtcdException: PUT /v2/keys/service/psql_cluster_11/members/wel-pphsnsdb01 request failed

### ISSUE THREAD

**Issue by gabricar** [zalando/patroni#1619]
Hi, I need some help with this cluster. I can see that every 20 minutes the same error message. And My Postgres restarts. All 3 nodes are like this.

Patroni version patroni-1.6.5
etcd version etcd-3.3.11-2.el7.x86_64

cat /var/log/message | grep etcd.EtcdException
Jul 21 16:04:27 wel-pphsnsdb01 patroni: etcd.EtcdException: PUT /v2/keys/service/psql_cluster_11/members/wel-pphsnsdb01 request failed
Jul 21 16:04:37 wel-pphsnsdb01 patroni: raise etcd.EtcdException('{0} {1} request failed'.format(method, path))
Jul 21 16:04:37 wel-pphsnsdb01 patroni: etcd.EtcdException: PUT /v2/keys/service/psql_cluster_11/members/wel-pphsnsdb01 request failed
Jul 21 16:04:47 wel-pphsnsdb01 patroni: raise etcd.EtcdException('{0} {1} request failed'.format(method, path))
Jul 21 16:04:47 wel-pphsnsdb01 patroni: etcd.EtcdException: PUT /v2/keys/service/psql_cluster_11/members/wel-pphsnsdb01 request failed
Jul 21 16:24:43 wel-pphsnsdb01 patroni: raise etcd.EtcdException('{0} {1} request failed'.format(method, path))
Jul 21 16:24:43 wel-pphsnsdb01 patroni: etcd.EtcdException: PUT /v2/keys/service/psql_cluster_11/members/wel-pphsnsdb01 request failed
Jul 21 16:24:53 wel-pphsnsdb01 patroni: raise etcd.EtcdException('{0} {1} request failed'.format(method, path))
Jul 21 16:24:53 wel-pphsnsdb01 patroni: etcd.EtcdException: PUT /v2/keys/service/psql_cluster_11/members/wel-pphsnsdb01 request failed
Jul 21 16:44:59 wel-pphsnsdb01 patroni: raise etcd.EtcdException('{0} {1} request failed'.format(method, path))
Jul 21 16:44:59 wel-pphsnsdb01 patroni: etcd.EtcdException: PUT /v2/keys/service/psql_cluster_11/members/wel-pphsnsdb01 request failed
Jul 21 17:44:55 wel-pphsnsdb01 patroni: raise etcd.EtcdException('{0} {1} request failed'.format(method, path))
Jul 21 17:44:55 wel-pphsnsdb01 patroni: etcd.EtcdException: PUT /v2/keys/service/psql_cluster_11/members/wel-pphsnsdb01 request failed

ON the postgres logs I see it restarting

2020-07-21 16:29:42.191 EDT [1251] LOG:  database system was interrupted while in recovery at log time 2020-07-21 16:24:59 EDT
2020-07-21 16:29:42.191 EDT [1251] HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
2020-07-21 16:29:42.191 EDT [1252] LOG:  connection received: host=[local]
2020-07-21 16:29:42.191 EDT [1252] FATAL:  the database system is starting up
2020-07-21 16:29:42.198 EDT [1254] LOG:  connection received: host=[local]
2020-07-21 16:29:42.198 EDT [1254] FATAL:  the database system is starting up
2020-07-21 16:29:42.410 EDT [1251] LOG:  entering standby mode
2020-07-21 16:29:42.428 EDT [1251] LOG:  redo starts at 1/6ED0D950
2020-07-21 16:29:42.428 EDT [1251] LOG:  consistent recovery state reached at 1/6ED0D9F8
2020-07-21 16:29:42.429 EDT [1242] LOG:  database system is ready to accept read only connections
2020-07-21 16:29:42.493 EDT [1251] LOG:  invalid record length at 1/6ED0F0E8: wanted 24, got 0
2020-07-21 16:29:42.545 EDT [1260] FATAL:  could not start WAL streaming: ERROR:  replication slot "wel_pphsnsdb01" is active for PID 31105
2020-07-21 16:29:42.583 EDT [1262] FATAL:  could not start WAL streaming: ERROR:  replication slot "wel_pphsnsdb01" is active for PID 31105
2020-07-21 16:29:43.211 EDT [1396] LOG:  connection received: host=[local]
2020-07-21 16:29:43.224 EDT [1397] LOG:  connection received: host=[local]
2020-07-21 16:29:43.224 EDT [1397] LOG:  connection authorized: user=postgres database=postgres
2020-07-21 16:29:43.412 EDT [1461] LOG:  connection received: host=127.0.0.1 port=32300
2020-07-21 16:29:43.464 EDT [1461] LOG:  replication connection authorized: user=replicator SSL enabled (protocol=TLSv1.2, cipher=ECDHE-ECDSA-AES256-GCM-SHA384, bits=256, compression=off)
2020-07-21 16:29:47.603 EDT [1607] LOG:  started streaming WAL from primary at 1/6E000000 on timeline 350
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2020-07-21 16:44:49.780 EDT [1607] FATAL:  could not receive data from WAL stream: SSL SYSCALL error: EOF detected
2020-07-21 16:44:49.781 EDT [1251] LOG:  invalid record length at 1/6ED13AF0: wanted 24, got 0
2020-07-21 16:44:49.798 EDT [7053] FATAL:  could not connect to the primary server: server closed the connection unexpectedly
		This probably means the server terminated abnormally
		before or while processing the request.
2020-07-21 16:44:54.842 EDT [7056] LOG:  started streaming WAL from primary at 1/6E000000 on timeline 350
2020-07-21 16:44:59.625 EDT [7056] LOG:  replication terminated by primary server
2020-07-21 16:44:59.625 EDT [7056] DETAIL:  End of WAL reached on timeline 350 at 1/6ED13AF0.
2020-07-21 16:44:59.625 EDT [7056] LOG:  fetching timeline history file for timeline 351 from primary server
2020-07-21 16:44:59.690 EDT [1251] LOG:  new target timeline is 351
2020-07-21 16:44:59.691 EDT [7056] LOG:  restarted WAL streaming at 1/6E000000 on timeline 351
2020-07-21 16:45:10.603 EDT [7159] LOG:  connection received: host=127.0.0.1 port=33544
2020-07-21 16:45:10.623 EDT [7159] LOG:  replication connection authorized: user=replicator SSL enabled (protocol=TLSv1.2, cipher=ECDHE-ECDSA-AES256-GCM-SHA384, bits=256, compression=off)

ETCD looks healthy and I don't see any network issues

etcdctl -ca-file /opt/postgres/ca.pem -cert-file /opt/postgres/patroni_client_cert.pem -key-file /opt/postgres/patroni_client_key.pem  --endpoints https://10.2.77.13:2379 cluster-health
member 9d748e4902122aad is healthy: got healthy result from https://10.2.77.11:2379
member b8bad376c4a1a7e8 is healthy: got healthy result from https://10.2.77.13:2379
member dff33cb3d1d840f8 is healthy: got healthy result from https://10.2.77.12:2379
cluster is healthy

going further into messages logs I have:
Jul 21 17:44:40 wel-pphsnsdb01 patroni: 2020-07-21 17:44:40,987 INFO: Selected new etcd server https://10.2.77.12:2379
Jul 21 17:44:40 wel-pphsnsdb01 patroni: 2020-07-21 17:44:40,988 ERROR: Request to server https://10.2.77.11:2379 failed: MaxRetryError('HTTPSConnectionPool(host=\'10.2.77.11\', port=2379): Max retries exceeded w
ith url: /v2/keys/service/psql_cluster_11/members/wel-pphsnsdb01 (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'10.2.77.11\', port=2379): Read timed out. (read timeout=3.333199675333352)",))',)
Jul 21 17:44:40 wel-pphsnsdb01 patroni: 2020-07-21 17:44:40,988 INFO: Reconnection allowed, looking for another server.
Jul 21 17:44:55 wel-pphsnsdb01 etcd: sync duration of 25.708037449s, expected less than 1s
Jul 21 17:44:55 wel-pphsnsdb01 patroni: 2020-07-21 17:44:40,988 ERROR:
Jul 21 17:44:55 wel-pphsnsdb01 patroni: Traceback (most recent call last):
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
Jul 21 17:44:55 wel-pphsnsdb01 patroni: six.raise_from(e, None)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "<string>", line 3, in raise_from
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
Jul 21 17:44:55 wel-pphsnsdb01 patroni: httplib_response = conn.getresponse()
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
Jul 21 17:44:55 wel-pphsnsdb01 patroni: response.begin()
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/usr/lib64/python3.6/http/client.py", line 307, in begin
Jul 21 17:44:55 wel-pphsnsdb01 patroni: version, status, reason = self._read_status()
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status
Jul 21 17:44:55 wel-pphsnsdb01 patroni: line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/usr/lib64/python3.6/socket.py", line 586, in readinto
Jul 21 17:44:55 wel-pphsnsdb01 patroni: return self._sock.recv_into(b)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/usr/lib64/python3.6/ssl.py", line 968, in recv_into
Jul 21 17:44:55 wel-pphsnsdb01 patroni: return self.read(nbytes, buffer)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/usr/lib64/python3.6/ssl.py", line 830, in read
Jul 21 17:44:55 wel-pphsnsdb01 patroni: return self._sslobj.read(len, buffer)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/usr/lib64/python3.6/ssl.py", line 587, in read
Jul 21 17:44:55 wel-pphsnsdb01 patroni: v = self._sslobj.read(len, buffer)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: socket.timeout: The read operation timed out
Jul 21 17:44:55 wel-pphsnsdb01 patroni: During handling of the above exception, another exception occurred:
Jul 21 17:44:55 wel-pphsnsdb01 patroni: Traceback (most recent call last):
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
Jul 21 17:44:55 wel-pphsnsdb01 patroni: chunked=chunked,
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/urllib3/connectionpool.py", line 428, in _make_request
Jul 21 17:44:55 wel-pphsnsdb01 patroni: self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
Jul 21 17:44:55 wel-pphsnsdb01 patroni: self, url, "Read timed out. (read timeout=%s)" % timeout_value
Jul 21 17:44:55 wel-pphsnsdb01 patroni: urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='10.2.77.11', port=2379): Read timed out. (read timeout=3.333199675333352)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: During handling of the above exception, another exception occurred:
Jul 21 17:44:55 wel-pphsnsdb01 patroni: Traceback (most recent call last):
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 196, in _do_http_request
Jul 21 17:44:55 wel-pphsnsdb01 patroni: response = request_executor(method, base_uri + path, fields=fields, **kwargs)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/urllib3/request.py", line 171, in request_encode_body
Jul 21 17:44:55 wel-pphsnsdb01 patroni: return self.urlopen(method, url, **extra_kw)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/urllib3/poolmanager.py", line 336, in urlopen
Jul 21 17:44:55 wel-pphsnsdb01 patroni: response = conn.urlopen(method, u.request_uri, **kw)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
Jul 21 17:44:55 wel-pphsnsdb01 patroni: method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
Jul 21 17:44:55 wel-pphsnsdb01 patroni: raise MaxRetryError(_pool, url, error or ResponseError(cause))
Jul 21 17:44:55 wel-pphsnsdb01 patroni: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.2.77.11', port=2379): Max retries exceeded with url: /v2/keys/service/psql_cluster_11/members/wel-pphsnsdb01
 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='10.2.77.11', port=2379): Read timed out. (read timeout=3.333199675333352)",))
Jul 21 17:44:55 wel-pphsnsdb01 patroni: During handling of the above exception, another exception occurred:
Jul 21 17:44:55 wel-pphsnsdb01 patroni: Traceback (most recent call last):
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 422, in wrapper
Jul 21 17:44:55 wel-pphsnsdb01 patroni: retval = func(self, *args, **kwargs) is not None
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 588, in touch_member
Jul 21 17:44:55 wel-pphsnsdb01 patroni: return self._client.set(self.member_path, data, None if permanent else self._ttl)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/etcd/client.py", line 721, in set
Jul 21 17:44:55 wel-pphsnsdb01 patroni: return self.write(key, value, ttl=ttl)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/etcd/client.py", line 500, in write
Jul 21 17:44:55 wel-pphsnsdb01 patroni: response = self.api_execute(path, method, params=params)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 248, in api_execute
Jul 21 17:44:55 wel-pphsnsdb01 patroni: response = self._do_http_request(retry, machines_cache, request_executor, method, path, **kwargs)
Jul 21 17:44:55 wel-pphsnsdb01 patroni: File "/opt/patroni/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 216, in _do_http_request
Jul 21 17:44:55 wel-pphsnsdb01 patroni: raise etcd.EtcdException('{0} {1} request failed'.format(method, path))
Jul 21 17:44:55 wel-pphsnsdb01 patroni: etcd.EtcdException: PUT /v2/keys/service/psql_cluster_11/members/wel-pphsnsdb01 request failed

Patroni CLT also returns healthy

patronictl -c /opt/patroni/etc/postgresql.yml list
+ Cluster: psql_cluster_11 (6817879084446162092) ----+-----+-----------+
|     Member     |      Host      |  Role  |  State  |  TL | Lag in MB |
+----------------+----------------+--------+---------+-----+-----------+
| wel-pphsnsdb01 | wel-pphsnsdb01 |        | running | 355 |         0 |
| wel-pphsnsdb02 | wel-pphsnsdb02 |        | running | 355 |         0 |
| wel-pphsnsdb03 | wel-pphsnsdb03 | Leader | running | 355 |           |
+----------------+----------------+--------+---------+-----+-----------+

I'm not sure if that is the case but sometimes my VMs reboots. Not sure if watchdog is killing it or not. I don't see any logs on the reboot it is like a hard reset.

**Comment by CyberDem0n** [comment]
If Patroni can't access DCS and PostgreSQL running as primary, it is demoted to avoid split-brain.
In your case Patroni clearly did its best by trying to make a request to all nodes of etcd cluster.
The fact that Etcd cluster was in a healthy state when you checked it doesn't prove that it didn't have had issues earlier.
Patronictl list doesn't write anything to Etcd and not using quorum read either, therefore it could just show stale information.

It seems that you are missing the full picture. The very first thing you should do - check logs of all etcd nodes and also make sure that system time is in sync across etcd nodes.
