### ISSUE TITLE
Minimal number of nodes in a Patroni cluster is not clearly documented

### ISSUE THREAD

**Issue by victor-sudakov** [zalando/patroni#1620]
There is an opinion I often hear that it is a requirement to have at least 3 PostgreSQL nodes in a Patroni cluster. Is this a misconception?

I'm aware that etcd/consul should have an uneven number of nodes, 3 or 5, but what about the database itself, is it OK to have a 2 nodes Patroni cluster: one master and one standby (like the Sith lords)?

**Comment by CyberDem0n** [comment]
Patroni/PostgreSQL nodes are decoupled from DCS nodes (except when Patroni [implements RAFT](https://github.com/zalando/patroni/pull/375) on its own) and therefore there is no requirement on minimal number of nodes.

As usual, feel free to contribute PR updating the documentation.

**Comment by victor-sudakov** [comment]
> Patroni/PostgreSQL nodes are decoupled from DCS nodes (except when Patroni [implements RAFT](https://github.com/zalando/patroni/pull/375) on its own) and therefore there is no requirement on minimal number of nodes.
> 

Thanks, I thought as much.

> As usual, feel free to contribute PR updating the documentation.

I've created a pull request to amend the FAQ.

**Comment by victor-sudakov** [comment]
I think the proposed paragraph went to the wrong place in the documentation. Is there a generic FAQ somewhere in the docs?

**Comment by victor-sudakov** [comment]
My pull request https://github.com/zalando/patroni/pull/1622 is still in the "checks haven’t completed yet" phase. Should I do something on my part to advance it?
