### ISSUE TITLE
Does patroni 1.6.5 support python-kubernetes version 11.0?

### ISSUE THREAD

**Issue by crunchyjohn** [zalando/patroni#1624]
Hello!

I noticed that the dependency on python-kubernetes has recently been removed in this PR (and with good reason):
https://github.com/zalando/patroni/pull/1586

However, until the next version of patroni is released that includes this change, I have a question.  There has recently been a new version of python-kubernetes released: v11.0.  Here is its changelog:
https://github.com/kubernetes-client/python/blob/release-11.0/CHANGELOG.md

Note that they mentioned that the code includes an API change.

Looking at the 1.6.5 version of patroni's requirements.txt (https://github.com/zalando/patroni/blob/v1.6.5/requirements.txt), I see this line:

```kubernetes>=2.0.0,<=10.0.1,!=4.0.*,!=5.0.*```

So, it is currently hardcoded to use python-kubernetes 10.0.1 or less.  While I am currently waiting on the next patroni release, I was curious if the api-change in python-kubernetes 11.0 is safe for working with patroni 1.6.5.

Thank you.

**Comment by CyberDem0n** [comment]
Hi @crunchyjohn,

The 10.0.1 is hardcoded only because back in October it was the latest version.
Patroni is using very limited number of API methods which are very stablle (they didn't change in 4 years), therefore I can imagine that v11 will also work without issues.

**Comment by CyberDem0n** [comment]
Update.

Unit and behave tests are passing successfully with v11.0.

**Comment by crunchyjohn** [comment]
Thanks for the help @CyberDem0n.  I will close out the ticket.
