### ISSUE TITLE
How to manage multiple clusters?

### ISSUE THREAD

**Issue by zelgo-dba** [zalando/patroni#1627]
Hi!
I have several clusters patroni+etcd+haproxy
How to manage multiple clusters from one central spot? Maybe there is a web interface for this?

I will be glad to any suggestions

**Comment by vitabaks** [comment]
@zelgo-dba 
There is no single management interface for all cluster components.
Use ssh.

**Comment by CyberDem0n** [comment]
It depends on the definition of "manage".
One could run `patronictl` anywhere, the only requirement that all nodes and DCS should be accessible from there.
