### ISSUE TITLE
does patron log rotate for postgres?

### ISSUE THREAD

**Issue by sandeepkalra** [zalando/patroni#1628]
Hi, 
I have the following settings in postgres block with respect to log setting.
```
    logging_collector: "on"
    log_min_messages: DEBUG1
    log_rotation_size: 1MB
    log_truncate_on_rotation: "true"
    log_destination: "stderr"
    log_directory: "/pg_root/log/pg_log/"
    log_file_mode: "0644"
    log_filename: "postgresql.log"
    log_line_prefix: '%t %n [%p]: [%l] sqlstate=%e application_name=%a,user=%u,db=%d,client=%h '
    log_min_duration_statement: 0
    log_statement: all
    log_checkpoints: "on"
    log_connections: "on"
    log_disconnections: "on"
    log_lock_waits: "on"
    log_temp_files: 0
    log_autovacuum_min_duration: 0
```
I am observing log file for postgres (/pg_root/log/pg_log/postgres.log) constantly growing. 
Is there anything I am missing that must be done so that patroni can set log-rotate on postgres log.

Thanks,

**Comment by CyberDem0n** [comment]
This question has nothing to do with patroni.
You have to configure postgres for that https://www.postgresql.org/docs/12/runtime-config-logging.html

**Comment by sandeepkalra** [comment]
Thanks!

**Comment by CyberDem0n** [comment]
Or you should configure logrotate, but in any case it is not a job of patroni to rotate postgres logs.
