### ISSUE TITLE
Add ability to set data directory permissions

### ISSUE THREAD

**Issue by caseyallenshobe** [zalando/patroni#1629]
Patroni seems to create the PG data directory (and parent directories) with mode 0700.  This leads to psql not working for users other than postgres and root, producing the following error:

```
$ psql
Error: /var/lib/postgresql/12/main is not accessible; please fix the directory permissions (/var/lib/postgresql/12/ should be world readable)
```

Please add a setting to allow this to be configured.  I would like the ability to set the mode to 750 so that other users added to the postgres group can access the database by running psql.  I believe mode 755 would match what initdb does by default...

**Comment by CyberDem0n** [comment]
The `0700` permission is set by default by `initdb`, not Patroni.
If you don't like it - you can specify `--allow-group-access` option for initdb:
```yaml
bootstrap:
  initdb:
  - allow-group-access
```
If permission is set to `0755`, postgres will refuse to start.

**Comment by caseyallenshobe** [comment]
Ahh, the error message is a bit misleading.  As it states that the parent directory of the data directory should be world-readable, and either Patroni or initdb is also creating that, how can I ensure that it gets the world-readable permissions that psql is complaining about?

**Comment by caseyallenshobe** [comment]
Adding the allow-group-access option caused the parent directory to become group-readable as well, which appears to be sufficient.  Thank you!
