### ISSUE TITLE
Patroni - postgresql connection issues.

### ISSUE THREAD

**Issue by aditya1808** [zalando/patroni#1632]
Hi, in our cluster, i keep seeing this error frequently

![image](https://user-images.githubusercontent.com/6763803/89005027-1bae2300-d321-11ea-865a-a1ef6d7b2b7b.png)

These are pod logs of master

I dont see any error in postgresql logs (pg_log) but it seems to be issue with patroni not able to connect to postgresql.
I spent quite sometime to get more information but this is all  i could find in logs.

I get this error when i try to run a query

![image](https://user-images.githubusercontent.com/6763803/89005166-6e87da80-d321-11ea-939b-d69958300370.png)

Could someone help me understand what might be wrong with this?

**Comment by CyberDem0n** [comment]
Postgres is crashing from time to time. You need to figure out why.
