### ISSUE TITLE
patronictl cannot do the discovery of the etcd cluster topology

### ISSUE THREAD

**Issue by victor-sudakov** [zalando/patroni#1635]
If patrony.yml has only one host for etcd cluster topology automatic discovery:
```
etcd:
  host: 172.31.xx.xx:2379
```
then patroni itself seems to discover the etcd nodes well, but patronictl does not do the discovery, so "patronictl list" and other patronictl commands fail when the only host specified in patroni.yml is not available (though the whole etcd cluster is still functional).

I thought that `patronictl -d "{etcd: {host: '172.31.yy.yy:2379'}}" list` would be a workaround but cannot figure out the syntax for -d, the one I have here produces a Python error.

**Comment by victor-sudakov** [comment]
Ah, it's probably `patronictl -d etcd://172.31.yy.yy:2379 list` - not documented or too obvious to be documented?

**Comment by CyberDem0n** [comment]
Such a way to specify dcs configuration for patronictl is very unflexible and limited. It is still there only for backward compatibility.
You should just use the same config file as for Patroni.

**Comment by victor-sudakov** [comment]
>  You should just use the same config file as for Patroni.

That is the core of the problem! If you use the same config file as for Patroni, and it contains **only one** etcd node, and that node goes down, patronictl becomes useless because it does not discover/see other healthy etcd nodes.

**Comment by CyberDem0n** [comment]
What stops you from putting more than one node there?

**Comment by victor-sudakov** [comment]
> What stops you from putting more than one node there?

I want Patroni to discover the cluster topology, instead of enumerating all the endpoints manually, so I set one "host" parameter as specified here:
```
etcd:
  #Provide host to do the initial discovery of the cluster topology:
  host: 127.0.0.1:2379
  #Or use "hosts" to provide multiple endpoints
  #Could be a comma separated string:
  #hosts: host1:port1,host2:port2
  #or an actual yaml list:
  #hosts:
  #- host1:port1
  #- host2:port2
  #Once discovery is complete Patroni will use the list of advertised clientURLs

```

**Comment by CyberDem0n** [comment]
1. There is no requirement to run etcd on the same host as Patroni.
2. What if etcd on the same host fails to start?

You better use something more reliable as localhost there, like multiple hosts, SRV record listing all etcd hosts, or A record listing all etcd IPs.

**Comment by victor-sudakov** [comment]
>     1. There is no requirement to run etcd on the same host as Patroni.

Sure. But no matter what you put into etcd.host, patronictl will use that host and only that host. On the other hand, if this one and only host does not respond, patronictl has no way to figure out other hosts.

> 
>     2. What if etcd on the same host fails to start?

What if the local consul agent fails to start? We'll have the same problem.

I've noticed that patronictl requests "/v2/machines" from the first etcd node it contacts. Does it use this list further?

> 
> You better use something more reliable as localhost there, like multiple hosts, SRV record listing all etcd hosts, or A record listing all etcd IPs.

Of course I can manually enumerate all etcd nodes in some way or another, but this will be yet another static list to maintain.

**Comment by CyberDem0n** [comment]
> Sure. But no matter what you put into etcd.host, patronictl will use that host and only that host. On the other hand, if this one and only host does not respond, patronictl has no way to figure out other hosts.

What made you think so? Patonictl is using exactly the same code for communicating with DCS as Patroni.
And you can use Patroni config for patronictl: `patronictl -c patroni.yaml list`

> What if the local consul agent fails to start? We'll have the same problem.

If consul agent fails to start you have a bigger problem. There is nothing to discuss.

**Comment by victor-sudakov** [comment]
> > Sure. But no matter what you put into etcd.host, patronictl will use that host and only that host. On the other hand, if this one and only host does not respond, patronictl has no way to figure out other hosts.
> 
> What made you think so? Patonictl is using exactly the same code for communicating with DCS as Patroni.

Steps to reproduce:

1. Confrigure
```
etcd:
  host: 172.31.xx.xx:2379
```
in your patroni.yml, where 172.31.xx.xx is one of your etcd servers.

2. Start Patroni.

3. Shutdown 172.31.xx.xx

4. Patroni still works because it has had the opportunity to discover other etcd servers.

5. `patronictl -c patroni.yml list` does not work any more.

**Comment by CyberDem0n** [comment]
https://github.com/zalando/patroni/issues/1635#issuecomment-667860260:
> You better use something more reliable as localhost there, like **_multiple_ hosts**, **SRV record** listing _all_ etcd hosts, or A record listing _all_ etcd IPs.**

**Comment by victor-sudakov** [comment]
> [#1635 (comment)](https://github.com/zalando/patroni/issues/1635#issuecomment-667860260):
> 
> > You better use something more reliable as localhost there, like **_multiple_ hosts**, **SRV record** listing _all_ etcd hosts, or A record listing _all_ etcd IPs.**

Of course I can manually enumerate all etcd nodes somewhere (config, DNS etc), but this will be yet another static list to maintain.

**Comment by CyberDem0n** [comment]
I hope you realize that this is the chicken-egg problem and pushing the solution to be implemented on the patroni side is not only unfair, but impossible.
The only task of patroni is implementing high availability, not solving all your infrastructure problems.
