### ISSUE TITLE
basic auth in REST API does not work?

### ISSUE THREAD

**Issue by victor-sudakov** [zalando/patroni#1636]
I deliberately configured restapi.authentication.username and restapi.authentication.password to different random values on each node of the Patroni cluster, restarted Patroni, but the cluster for some reason still works. I expected some kind of authentication error and inability for the misconfigured nodes to form a cluster.

Do I need to enable something else to enable the basic auth (without certificates) between Patroni nodes? I don't expect it to be very secure but I expect it to protect the cluster from members joined in error.

**Comment by CyberDem0n** [comment]
Basic auth is only checked for unsafe endpoints (which are serving non GET requests).
During normal operation the REST API is not even used across nodes, only during the leader race.
Unsafe endpoints are called only by patroninctl.

**Comment by victor-sudakov** [comment]
So the best protection from a rogue node are "scope" and "namespace", not the username and password?

**Comment by CyberDem0n** [comment]
What problem are you trying to solve?

**Comment by victor-sudakov** [comment]
> What problem are you trying to solve?

I would like to provide some basic protection from untrusted users communicating to the Patroni cluster via its REST API (sending commands, queries, adding or deleting nodes etc).

**Comment by CyberDem0n** [comment]
Perfect. Just configure basic auth credentials. As I told it will protect all non `GET` endpoints.

**Comment by victor-sudakov** [comment]
> Perfect. Just configure basic auth credentials. As I told it will protect all non `GET` endpoints.
How can I verify that? For the present, I see that when I join a new Patroni  node with a deliberately incorrect 
restapi.authentication.username and restapi.authentication.password, it just joins successfully.

**Comment by CyberDem0n** [comment]
> How can I verify that?

1. Read the [documentation](https://patroni.readthedocs.io/en/latest/rest_api.html).
2. Find any endpoint accepting non GET requests.
3. Try to execute this request without (or with the wrong) authorization header.

**Comment by victor-sudakov** [comment]
> > How can I verify that?
> 
>     1. Read the [documentation](https://patroni.readthedocs.io/en/latest/rest_api.html).
> 
>     2. Find any endpoint accepting non GET requests.
> 
>     3. Try to execute this request without (or with the wrong) authorization header.

True, some non-GET commands (like `patronictl switchover` or `patronictl restart`) are prevented with the status code=401, (not authenticated).

But for example `patronictl edit-config` is not prevented, you can edit all you want including pg_hba, without knowing the right username/password. And "PATCH /config" is not a GET request.

**Comment by CyberDem0n** [comment]
> But for example patronictl edit-config is not prevented, you can edit all you want including pg_hba, without knowing the right username/password. And "PATCH /config" is not a GET request.

What made you think that `patronictl edit-config` is using `PATCH /config`? There is not a single word about it in the documentation.

**Comment by victor-sudakov** [comment]
> > But for example patronictl edit-config is not prevented, you can edit all you want including pg_hba, without knowing the right username/password. And "PATCH /config" is not a GET request.
> 
> What made you think that `patronictl edit-config` is using `PATCH /config`? There is not a single word about it in the documentation.

Please, where is the documentation about what patronictl is using and how to secure the patronictl interface? I must have missed it.

**Comment by CyberDem0n** [comment]
> where is the documentation about what patronictl is using and how to secure the patronictl interface? I must have missed it.

`git blame`, `git log -p`, and GitHub search through the list of merged PR.
Documenting any minor implementation detail is way too much.

**Comment by victor-sudakov** [comment]
> > where is the documentation about what patronictl is using and how to secure the patronictl interface? I must have missed it.
> 
> `git blame`, `git log -p`, and GitHub search through the list of merged PR.
> Documenting any minor implementation detail is way too much.

Sorry, but information security and protection is not a minor implementation detail, and should not be scraped from Git logs. I could offer help writing up a security readme, but then you should not be cross with me asking several questions.

**Comment by CyberDem0n** [comment]
Despite DCS doesn't contain any sensitive information it allows changing some of patroni/postgres [configuration](https://patroni.readthedocs.io/en/latest/dynamic_configuration.html). Therefore the very first thing that should be protected - DCS itself, i.e. TLS should is enabled and tokens/basic-auth/client certificates are used to authenticate Patroni.

Patronictl is also working directly with DCS. Besides that, patronictl could call the REST API on Patroni nodes (not everything could be done via DCS). What and how patronictl is doing are implementation details, which could be changed and don't really deserve to be documented.

Rule of thumb - use TLS everywhere. Basic-auth without TLS not worth the time spend on it.

**Comment by victor-sudakov** [comment]
If I write a paragraph on Patroni security for the README, would you accept that?

**Comment by CyberDem0n** [comment]
It is better to create a dedicated page for that.

**Comment by victor-sudakov** [comment]
A very interim document is at https://github.com/victor-sudakov/patroni/blob/security/docs/security.rst 

Can you explain what we need the `ctl:` section for? Everything there seems to be configurable under the `restapi:` section

**Comment by CyberDem0n** [comment]
> Can you explain what we need the ctl: section for? Everything there seems to be already configurable under the restapi: section

They might look quite similar, but they serve a different suppose, `restapi` is for configuring server-side, while `ctl` for the client-side. For example there is `ctl.insecure`, which allows disabling verification of server certificates (similar to `curl --insecure`).
