### ISSUE TITLE
Localisation file logs

### ISSUE THREAD

**Issue by Mahe-alain** [zalando/patroni#1643]
Hello,

In which file to configure the location and historization of logs ?

Thanks for your help

**Comment by CyberDem0n** [comment]
Please consult the PostgreSQL [documentation](https://www.postgresql.org/docs/current/runtime-config-logging.html) for that.

**Comment by Mahe-alain** [comment]
I'm talking about patroni logs, not postgresql

**Comment by CyberDem0n** [comment]
There is no localization option.
Regarding log rotation and so on you can check [documentation](https://patroni.readthedocs.io/en/latest/SETTINGS.html#log) (as usual).
