### ISSUE TITLE
How to setup standby Patroni cluster using Streaming replication in Kubernetes with ISTIO environment for DC/DR

### ISSUE THREAD

**Issue by dhanasg** [zalando/patroni#1648]
Hi,

I was able to get useful references from the below github issue to understand Patroni disaster recovery strategy.
https://github.com/zalando/patroni/issues/1182

Can you please clarify my below questions based on the below user case:
User case: Two independent Data Center, running on Kubernetes with ISTIO enabled. 3 node Patroni and 3 node zookeeper running in each of the data center. Deployed using HELM Charts.
Scenario: Fail over from Active DC to Standby DC.

1. We are deploying as statefulsets. Thus was trying to understand how do i setup SYNC replica and ASYNC replica among the nodes of a cluster running in DC1, because helm charts take common environment variables.
2. Question related to streaming replication. As per standby cluster configuration section, i could see "primary_slot_name" can be used for streaming replication. But the "create_replica_methods" has examples of basebackup and wal-e, which are not streaming replication. How to define these variables to enable streaming replication.
3. How to achieve streaming replication to standby cluster using helm charts. (K8s with ISTIO)

**Comment by CyberDem0n** [comment]
Helm chart just obscures deployment with providing zero value on top of that.

> As per standby cluster configuration section, i could see "primary_slot_name" can be used for streaming replication. But the "create_replica_methods" has examples of basebackup and wal-e, which are not streaming replication. How to define these variables to enable streaming replication.

You are mixing two different concepts. Creating the replica by restoring from the backup and streaming repication to the replica that is already running.
The `basebackup` is actually the reference to the `pg_basebackup`, which builds the replica via streaming replication protocol.
The `primary_slot_name` option tells that the standby should use the replication slot existing on the primary.

> How to achieve streaming replication to standby cluster using helm charts. (K8s with ISTIO)

The primary cluster should provide the single endpoint (ingress) and the standby cluster should connect to the primary via this endpoint.
How to implement ingress heavily depends on the environment. Usually it should be some kind of load balancer.

**Comment by dhanasg** [comment]
thanks a lot for the quick and prompt response. Appreciate that...
