### ISSUE TITLE
Does all transactions pass via the haproxy

### ISSUE THREAD

**Issue by doribd** [zalando/patroni#1649]
As part of the patroni solution, we have in the 'entrance' the haproxy (or different lb) that directs all the transactions 
to the master. 

**My question divides into two:** 
WiIl the lb/haproxy be the bottleneck in case of high load of multiple transactions
Why or is it possible to switch the traffic to the master directly once it passed via the ha proxy?

**Comment by CyberDem0n** [comment]
HAProxy is quite performant.
If it becomes a bottleneck you can deploy more instances of HAProxy on different serves.

There are multiple ways to route application connections to the primary.
If all hosts are located in the same network you probably should better use [vip-manager](https://github.com/cybertec-postgresql/vip-manager)

**Comment by doribd** [comment]
ok thanks.
