### ISSUE TITLE
Patroni cluster , Postgres log not rotating.

### ISSUE THREAD

**Issue by ani-tvm** [zalando/patroni#1650]
Hi,

I have 3 node patroni cluster with all node having etcd, haproxy, pgbouncer, keepalived, postgres.
Our issue is from last 3 days  in Leader Node postgres logs are not rotating because of this servers space (/) 100% utilized (except /pg). 
From other node we can get the cluster status all node running and Lag in MB 0. 

How we can solve this.

Thanks

**Comment by CyberDem0n** [comment]
> postgres logs are not rotating 

And how is this a Patroni issue?

**Comment by ani-tvm** [comment]
i have no idea it is from postgres issue or patroni. last two days I make 5GB free space on the drive again and again space filed by postgres log and it was not rotating  to next day log usually it will every day new log will generate.

How we can solve. Through patroni or postgres ?

**Comment by CyberDem0n** [comment]
It depends on how you configured log rotation.
Patroni's only responsibility is implementing HA.

**Comment by ani-tvm** [comment]
log rotation configured throgh patronictl editconfig postgres
configuration is rotate log on every day with Sun, Mon, Tue

**Comment by ani-tvm** [comment]
Issue because of postgres log_statement='all'  configuration. It makes  faster growing of log file (it logs including the cluster related information) and postgres not able to rotate the log. after disable that its working fine.

**Comment by ani-tvm** [comment]
thanks for the support
