### ISSUE TITLE
Patronictl not showing cluster stats in docker swarm setup 

### ISSUE THREAD

**Issue by floitet** [zalando/patroni#1652]
I have installed custom simple build of patroni into a docker swarm environment creating 3-node cluster paired with zookeeper and am having an issue calling cluster stats from patronictl from inside docker containers running my patroni services even though the cluster itself is working just fine and has no issues operating with zookeeper as it can be seen on the screenshots. 
It's just patronictl being unable to find connection with zookeeper. 

Active functioning cluster:

![patroni_node_ok1](https://user-images.githubusercontent.com/59524220/90137144-e0c6d900-dd7d-11ea-9527-a9caf367ef3c.png)
![patroni_node_ok2](https://user-images.githubusercontent.com/59524220/90137146-e1f80600-dd7d-11ea-91e8-8f48ca4e73c6.png)
![patroni_node_ok3](https://user-images.githubusercontent.com/59524220/90137147-e1f80600-dd7d-11ea-9291-274d1f0f84ee.png)

Patronictl responding to basic commands called from inside container:

![patronictl_repsonding](https://user-images.githubusercontent.com/59524220/90135263-15856100-dd7b-11ea-87f8-2142c4c9ae57.jpg)

Patronictl failing to find active zookeeper service:

![patronictl_fail](https://user-images.githubusercontent.com/59524220/90135330-2fbf3f00-dd7b-11ea-873e-aa829a2a6c77.jpg)

Docker file I built my images with: 

![patroni_dockerfile](https://user-images.githubusercontent.com/59524220/90135382-3e0d5b00-dd7b-11ea-9626-b04ab9ff01f8.jpg)

Really looking forward to any help.
Even though as far as I am concerned, it is possible to cover most of the tasks patronictl takes care of simply using Patroni Rest API, I am still wondering how is that possible that patronictl itself is not wokring..

**Comment by CyberDem0n** [comment]
> Even though as far as I am concerned, it is possible to cover most of the tasks patronictl takes care of simply using Patroni Rest API, I am still wondering how is that possible that patronictl itself is not working..

Because the config file (-c etc/patroni.yml) is wrong.

**Comment by floitet** [comment]
> > Even though as far as I am concerned, it is possible to cover most of the tasks patronictl takes care of simply using Patroni Rest API, I am still wondering how is that possible that patronictl itself is not working..
> 
> Because the config file (-c etc/patroni.yml) is wrong.

![patroni_config](https://user-images.githubusercontent.com/59524220/90140718-cc390f80-dd82-11ea-9772-05de6d409d38.png)

I'd be really grateful if you could point out what is wrong in my config file

**Comment by CyberDem0n** [comment]
There is no zookeeper section.

**Comment by floitet** [comment]
> There is no zookeeper section.

Wow, thanks! 
I did miss out on it

**Comment by CyberDem0n** [comment]
Your environment works only for the patroni process, patronictl can't see it.

Your config file is stil wrong (it would be way better if you stop posting pictures but do the real copy&paste of text):
```yaml
zookeeper:
  hosts:zoo1:2181,zoo2:2181,zoo3:2181
```

Is parsed into: `{'zookeeper': 'hosts:zoo1:2181,zoo2:2181,zoo3:2181'}`

Instead it should look like:
```yaml
zookeeper:
  hosts: 'zoo1:2181,zoo2:2181,zoo3:2181'
```

In YAML every single space and quote character matter a lot.
