### ISSUE TITLE
Support for arm devices

### ISSUE THREAD

**Issue by mgonzaga1990** [zalando/patroni#1653]
Do we have arm support on this?
Specifically raspberry pi? I have a k8s cluster set up on my raspberry pi's and I'm hoping to take advantage of this if we have arm64 support.

**Comment by CyberDem0n** [comment]
All you need is python.

**Comment by mgonzaga1990** [comment]
i see.. but how about if im going to run this in a kubernetes cluster in my
raspberry pi?

**Comment by CyberDem0n** [comment]
If there is python available for your platform (and PostgreSQL of course) I don't expect it to be a problem.
But don't expect that someone will do everything for you.
