### ISSUE TITLE
Pgbackrest backup on patroni

### ISSUE THREAD

**Issue by ani-tvm** [zalando/patroni#1656]
Hi,

How to do backup and restoration of running 3 node patroni cluster using pgbackrest. any documentation available?. Please help.

Thanks

**Comment by CyberDem0n** [comment]
Please read the [documentation](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html).

**Comment by ani-tvm** [comment]
Thanks
in this document not mentioned about the configuration for taking backup using pgbackrest on a running patroni cluster.
any configuration document for backup  from patroni cluster DB using pgbackrest?

**Comment by CyberDem0n** [comment]
> not mentioned about the configuration for taking backup using pgbackrest on a running patroni cluster.

How is it different from backing up PostgreSQL cluster?

**Comment by ani-tvm** [comment]
my thanks for the support.
my postgres.conf file on the 3 node patroni cluster is having **archive_command = 'cd .'**

1. If I change that to following for the pgbackrest, is it will make any issue in patroni cluster - replication or anything?
archive_command = 'pgbackrest --stanza=proddb archive-push %p'

2. Take the backup from Leader or Replica node - what is the best practice for the patroni?

Thanks

**Comment by vitabaks** [comment]
See pgBackRest User Guides:
https://pgbackrest.org/user-guide-index.html

**Comment by ani-tvm** [comment]
thanks vitbaks.

I configured the backup using pgbackrest from a 3 node patroni cluster. 
Backup/restoration successfull.
I restored using bootstrap method on leader node, then reinit the replica node successfully. 

1. While reinit on the replication node, leader node contacting the pgbackrest backup server ( i  am able to see this in /var/log/secure).  why leader node contacting pgbackrest backup server during reinit of replica server? . Can we able to enable log  in pgbackrest server log for backup/restoration. 

2. Do we have any other method to restore on leader node without deleting the data in data folder (to save the restoration time)

Thanks in advance.

**Comment by vitabaks** [comment]
@ani-tvm 
1. Please read the pgbackrest documentation
`/var/log/pgbackrest`
https://pgbackrest.org/configuration.html#section-log/option-log-path

2. Yes. Use `--delta` restore
See my example:
"Recovery steps with pgBackRest" 
https://github.com/vitabaks/postgresql_cluster#restore-and-cloning

**Comment by ani-tvm** [comment]
Thanks Vitbaks.

1.  I am getting the log for backup in pgbackrest server- initiate backup from backup server. but not getting the restoration log in pgbackrest server while restoration  initiate from DB server.    

2.  thanks for providing https://github.com/vitabaks/postgresql_cluster#restore-and-cloning . 
     I am able to --delta restore  in leader node and able to start DB. My mistake was every time after restoration immediately i start the patroni. this time as per your documentation  i start postgres , after everything fine then stop postgres  then start patroni.

Still i have problem in restoring in replica node using --delta. after restoring i am getting the following error.
-bash-4.2$ /usr/pgsql-11/bin/pg_ctl stop -D /pg/data/
pg_ctl: PID file "/pg/data/postmaster.pid" does not exist
Is server running?

Thanks for your support.

**Comment by vitabaks** [comment]
@ani-tvm 
The pgbackrest restore log is on the target server. Look at the log on the server on which you are performing the restore.

You are trying to stop postgres (pg_ctl stop), but it is not running. Patroni will stop the postgres when you stopped the Patroni service.

**Comment by ani-tvm** [comment]
@vitabaks 

Thanks. yes its working fine.
