### ISSUE TITLE
Specify pg_rewind user on postgres 10 and lower

### ISSUE THREAD

**Issue by zorgan** [zalando/patroni#1657]
Is it possible to specify pg_rewind user with superuser privileges on PG 10 and lower? Patroni uses pg_rewind with _postgres_ user by default.

**Comment by CyberDem0n** [comment]
No it is not possible, because pg_rewind is using functions that are only available for superuser.

**Comment by zorgan** [comment]
I just want to specify superuser other than postgres. You can use pg_rewind with any user who has the superuser privileges.
