### ISSUE TITLE
Secured connection to zookeeper

### ISSUE THREAD

**Issue by oleg-beltz** [zalando/patroni#1658]
It looks like that for now Patroni doesn't support security configuration for Patroni-Zookeeper connectivity (TLS, ceritificates) in the same way like it is done for etcd.
Is it planned to implement Zookeeper secured communication in the nearest future?

**Comment by CyberDem0n** [comment]
Hi @oleg-beltz,

we don't have such plans.
This is an open-source project, if you are interested in a specific feature, feel free to work on it. All contributions are always welcomed.
