### ISSUE TITLE
[Question] [Standby Cluster] Leader demotion

### ISSUE THREAD

**Issue by uspen** [zalando/patroni#1660]
Hello dear developers!

Since when the leader is demoted to the standby leader, Patroni turns off the postgres immediately (SIGQUIT), you [told](https://github.com/zalando/patroni/issues/1164#issuecomment-528270637) how to do it right.

But this option is very difficult to automate and writing to DCS looks like an ideal option, but as a result brings to data loss during replication

What is your view on this situation, what would you recommend?

**Comment by CyberDem0n** [comment]
As I understand the only problem for you is a clean shut down?
There is a way to make it easier:
1. Pause cluster: `patronictl pause --wait`
2. Stop the leader postgres: `pg_ctl stop -mf`
3. Create the standby configuration and resume:
```yaml
$ patronictl edit-config -s 'standby_cluster.restore_command="true"' -s pause=null 
--- 
+++ 
@@ -1,8 +1,9 @@
 loop_wait: 10
 maximum_lag_on_failover: 1048576
-pause: true
 postgresql:
   parameters: null
   use_pg_rewind: true
 retry_timeout: 10
+standby_cluster:
+  restore_command: 'true'
 ttl: 30

Apply these changes? [y/N]: y
Configuration changed
```

Maybe a bit hacky, but works.
