### ISSUE TITLE
patroni auto-failover problem

### ISSUE THREAD

**Issue by bimcas** [zalando/patroni#1663]
Hi,

I have a problem with patroni 1.6.5 auto-failover when WAL disk is full in the master node and PostgreSQL service is down on master. 

See disk statistics of master node (mycluster001):
Filesystem      Size  Used   Avail    Use% Mounted on
/dev/vda1        50G  3.6G    47G     8%       /
/dev/vdb         32G  7.1G     23G     24%     /data
**/dev/vdc      24G   24G    2.2M   100%    /wal**

PostgreSQL service is down and unavailable on master node:
psql: error: could not connect to server: Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**but patroni gives such info**:

patronictl list
+ Cluster: mycluster (6842627710757961095) ---+--------+---------+----+-----------+
|               Member               |                Host                |  Role      |  State       | TL | Lag in MB |
+-------------------------+-----------------------+--------+---------+----+-----------+
| mycluster001                    | mycluster001                 | Leader  | running    |  9 |                    |
| mycluster002                   | mycluster002                 |               | running    |  9 |         0         |
+------------------------+------------------------+--------+---------+----+-----------+

See disk statics of slave node:
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        50G  3.6G   47G   8%     /
/dev/vdb         32G  7.0G   23G  24%    /data
**/dev/vdc         24G  2.4G   22G  10%    /wal**

Slave node (mycluster002) is healthy and PostgreSQL service is available. 
psql (12.3)
Type "help" for help.

postgres=#

**Why patroni didn't determine PostgreSQL service unavailability on master node (status is Running) and it didn't perform auto-failover from dead master to the healthy slave node?**

Thanks

**Comment by CyberDem0n** [comment]
Rule number zero - you MUST monitor the free disk space, it is not a task of Patroni.

Also I have a feeling that you don't tell the full story. In case if Postgres for some reason is not running (crashed, exited, etc...) Patroni always tries to start it up, but you didn't even look into Patroni logs.

**Comment by bimcas** [comment]
Of course, disk space is not a task of Patroni. I understand it, I don't ask you regarding this. 

My question was why patroni didn't determine PostgreSQL service unavailability on the master node and it didn't perform auto-failover? It seems that patroni stuck on retries to start Postgres up on master node.
In my opinion, if Postgres service is crashed (no matter what happens) on the master node, patroni should perform auto-failover to the healthy slave node? Now I had Postgres service downtime and I performed manual failover.

You said: "you don't tell the full story". Which info I could present for you?

**Comment by CyberDem0n** [comment]
>  In my opinion, if Postgres service is crashed (no matter what happens) on the master node, patroni should perform auto-failover to the healthy slave node? Now I had Postgres service downtime and I performed manual failover.

First of all, there is no slaves in the postgres world.
Second - if you want immediate failover on master crash you have to configure it explicitly: https://patroni.readthedocs.io/en/latest/SETTINGS.html. More specifically, set `master_start_timeout=0`.

**Comment by bimcas** [comment]
Now my patroni configuration is:
dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    master_start_timeout: 300

I checked logs Postgres service is crashed at night time. I found the problem only in the morning.  So, the duration of downtime was more than 3 hours. It much longer then master_start_timeout (300s). Why patroni stuck on retries to start Postgres up on master node and didn't switch to standby node?

I'd like to present some details from patroni log that you imagine what happens in master node:

Aug 24 04:37:05 mycluster001 patroni: 2020-08-24 04:37:05,101 INFO: Lock owner: mycluster001.example.com; I am mycluster001.example.com
Aug 24 04:37:05 mycluster001 patroni: 2020-08-24 04:37:05,103 INFO: starting as readonly because i had the session lock
Aug 24 04:37:05 mycluster001 patroni: 2020-08-24 02:37:05.362 UTC [13238] LOG:  starting PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
Aug 24 04:37:05 mycluster001 patroni: 2020-08-24 02:37:05.362 UTC [13238] LOG:  listening on IPv4 address "127.0.0.1", port 5432
Aug 24 04:37:05 mycluster001 patroni: 2020-08-24 02:37:05.366 UTC [13238] LOG:  listening on IPv4 address "11.2.30.4", port 5432
Aug 24 04:37:05 mycluster001 patroni: 2020-08-24 02:37:05.366 UTC [13238] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
Aug 24 04:37:05 mycluster001 patroni: 2020-08-24 02:37:05.380 UTC [13238] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
Aug 24 04:37:05 mycluster001 patroni: 2020-08-24 02:37:05.394 UTC [13238] LOG:  redirecting log output to logging collector process
Aug 24 04:37:05 mycluster001 patroni: 2020-08-24 02:37:05.394 UTC [13238] HINT:  Future log output will appear in directory "pg_log".
Aug 24 04:37:05 mycluster001 patroni: 2020-08-24 04:37:05,391 INFO: postmaster pid=13238
Aug 24 04:37:05 mycluster001 patroni: localhost:5432 - rejecting connections
Aug 24 04:37:09 mycluster001 patroni: 2020-08-24 04:37:09,639 INFO: Lock owner: mycluster001.example.com; I am mycluster001.example.com
Aug 24 04:37:09 mycluster001 patroni: 2020-08-24 04:37:09,639 INFO: establishing a new patroni connection to the postgres cluster
Aug 24 04:37:09 mycluster001 patroni: 2020-08-24 04:37:09,684 INFO: Software Watchdog activated with 25 second timeout, timing slack 15 seconds
**Aug 24 04:37:09 mycluster001 patroni: 2020-08-24 04:37:09,844 INFO: promoted self to leader because i had the session lock**
Aug 24 04:37:09 mycluster001 patroni: server promoting
Aug 24 04:37:09 mycluster001 patroni: 2020-08-24 04:37:09,874 INFO: cleared rewind state after becoming the leader
Aug 24 04:37:17 mycluster001 patroni: 2020-08-24 04:37:17,343 ERROR: get_postgresql_status
Aug 24 04:37:17 mycluster001 patroni: Traceback (most recent call last):
Aug 24 04:37:17 mycluster001 patroni: File "/usr/lib/python3.4/site-packages/patroni/api.py", line 499, in query
Aug 24 04:37:17 mycluster001 patroni: cursor.execute(sql, params)
Aug 24 04:37:17 mycluster001 patroni: psycopg2.OperationalError: server closed the connection unexpectedly
Aug 24 04:37:17 mycluster001 patroni: This probably means the server terminated abnormally
Aug 24 04:37:17 mycluster001 patroni: before or while processing the request.
Aug 24 04:37:17 mycluster001 patroni: During handling of the above exception, another exception occurred:
Aug 24 04:37:17 mycluster001 patroni: Traceback (most recent call last):
Aug 24 04:37:17 mycluster001 patroni: File "/usr/lib/python3.4/site-packages/patroni/api.py", line 443, in get_postgresql_status
Aug 24 04:37:17 mycluster001 patroni: self.server.patroni.postgresql.lsn_name), retry=retry)[0]
Aug 24 04:37:17 mycluster001 patroni: File "/usr/lib/python3.4/site-packages/patroni/api.py", line 416, in query
Aug 24 04:37:17 mycluster001 patroni: return self.server.query(sql, *params)
Aug 24 04:37:17 mycluster001 patroni: File "/usr/lib/python3.4/site-packages/patroni/api.py", line 504, in query
Aug 24 04:37:17 mycluster001 patroni: raise PostgresConnectionException('connection problems')
Aug 24 04:37:17 mycluster001 patroni: patroni.exceptions.PostgresConnectionException: 'connection problems'
Aug 24 04:37:19 mycluster001 patroni: 2020-08-24 04:37:19,630 INFO: Lock owner: mycluster001.example.com; I am mycluster001.example.com
Aug 24 04:37:19 mycluster001 patroni: 2020-08-24 04:37:19,635 INFO: establishing a new patroni connection to the postgres cluster
Aug 24 04:37:20 mycluster001 patroni: 2020-08-24 04:37:20,437 INFO: establishing a new patroni connection to the postgres cluster
Aug 24 04:37:20 mycluster001 patroni: 2020-08-24 04:37:20,438 WARNING: Retry got exception: 'connection problems'
Aug 24 04:37:20 mycluster001 patroni: localhost:5432 - no response
Aug 24 04:37:20 mycluster001 patroni: 2020-08-24 04:37:20,455 INFO: updated leader lock during promote
Aug 24 04:37:22 mycluster001 patroni: 2020-08-24 04:37:22,355 ERROR: get_postgresql_status
Aug 24 04:37:22 mycluster001 patroni: Traceback (most recent call last):
Aug 24 04:37:22 mycluster001 patroni: File "/usr/lib/python3.4/site-packages/patroni/api.py", line 498, in query
Aug 24 04:37:22 mycluster001 patroni: with self.patroni.postgresql.connection().cursor() as cursor:
Aug 24 04:37:22 mycluster001 patroni: File "/usr/lib/python3.4/site-packages/patroni/postgresql/__init__.py", line 228, in connection
Aug 24 04:37:22 mycluster001 patroni: return self._connection.get()
Aug 24 04:37:22 mycluster001 patroni: File "/usr/lib/python3.4/site-packages/patroni/postgresql/connection.py", line 23, in get
Aug 24 04:37:22 mycluster001 patroni: self._connection = psycopg2.connect(**self._conn_kwargs)
Aug 24 04:37:22 mycluster001 patroni: File "/usr/lib64/python3.4/site-packages/psycopg2/__init__.py", line 130, in connect
Aug 24 04:37:22 mycluster001 patroni: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Aug 24 04:37:22 mycluster001 patroni: psycopg2.OperationalError: could not connect to server: Connection refused
Aug 24 04:37:22 mycluster001 patroni: Is the server running on host "localhost" (::1) and accepting
Aug 24 04:37:22 mycluster001 patroni: TCP/IP connections on port 5432?
Aug 24 04:37:22 mycluster001 patroni: could not connect to server: Connection refused
Aug 24 04:37:22 mycluster001 patroni: Is the server running on host "localhost" (127.0.0.1) and accepting
Aug 24 04:37:22 mycluster001 patroni: TCP/IP connections on port 5432?
Aug 24 04:37:22 mycluster001 patroni: During handling of the above exception, another exception occurred:
Aug 24 04:37:22 mycluster001 patroni: Traceback (most recent call last):
Aug 24 04:37:22 mycluster001 patroni: File "/usr/lib/python3.4/site-packages/patroni/api.py", line 443, in get_postgresql_status
Aug 24 04:37:22 mycluster001 patroni: self.server.patroni.postgresql.lsn_name), retry=retry)[0]
Aug 24 04:37:22 mycluster001 patroni: File "/usr/lib/python3.4/site-packages/patroni/api.py", line 416, in query
Aug 24 04:37:22 mycluster001 patroni: return self.server.query(sql, *params)
Aug 24 04:37:22 mycluster001 patroni: File "/usr/lib/python3.4/site-packages/patroni/api.py", line 504, in query
Aug 24 04:37:22 mycluster001 patroni: raise PostgresConnectionException('connection problems')
Aug 24 04:37:22 mycluster001 patroni: patroni.exceptions.PostgresConnectionException: 'connection problems'
Aug 24 04:37:22  mycluster001 patroni: 2020-08-24 04:37:22,680 WARNING: Postgresql is not running.

**Comment by CyberDem0n** [comment]
The postgres start operation performed faster than 300 seconds, I don't see a problem here.
I am pretty sure that the `crash -> start -> promote -> crash` loop has happened more than once.

And regarding failing over in such a situation. It was just a happy coincidence that on the replica the wal directory was not full. In case if it was full, performing the failover would bring nothing. Patroni knows nothing about your infrastructure and should not know. You have to monitor the free disk space! It is totally your fault that pg_wal became full.

**Comment by bimcas** [comment]
I return to question, why after unsuccessful loops (crash -> start -> promote -> crash ....., which duration was longer than 300s, I mean "master_start_timeout") to start Postgres up on Leader node, patroni didn't switch (auto-failover) to healthy standby node? Why patroni stuck on retries to start Postgres up on Leader node? 

You said: "_Patroni knows nothing about your infrastructure_". 

patronictl list

Cluster: mycluster (6842627710757961095) ---+--------+------------+
| Member          |  Host                 | Role          | State     | TL    | Lag in MB  |
+------------------------------+--------------------------+-----------+-
| mycluster001 | mycluster001   | Leader     | running |   9     |                   |
| mycluster002 | mycluster002  |                  | running |   9     |            0    |
+------------------------------+-------------------------+-----------+

Patroni very well knows cluster nodes. It knows healthy standby node "mycluster002", but it didn't auto-failover after master_start_timeout to standby node. Why?

I just like to inform you that patroni auto-failover functionality in 1.6.5 version with PostgreSQL 12.3 version isn't work very well in all cases and you should investigate it and fix. Thanks.

**Comment by CyberDem0n** [comment]
> I mean "master_start_timeout") to start Postgres up on Leader node, patroni didn't switch (auto-failover) to healthy standby node? Why patroni stuck on retries to start Postgres up on Leader node?

I will just quote my previous answer:
`The postgres start operation performed faster than 300 seconds.`. Everything worked exactly as it was configured. When postgres panicked (exited) due to out of disk space, Patroni successfully started it up. The startup took less than 300 seconds.

>Patroni very well knows cluster nodes. 

Please! Don't mix things up! I was talking about infrastructure! The only Patroni knows about other nodes is their IPs. It has no idea what hardware is used and the amount of free disk space there. There is only an assumption that everything could be symmetrical. Therefore most likely all replicas are in the same conditions as primary.

> It knows healthy standby node "mycluster002", but it didn't auto-failover

If the primary crashed and you do a failover, very likely that the new master will also crash with the same conditions. Then it will happen again and again. Chains of failovers will cause data loss with 99.99% chances.

There is a way to enable immediate failover on primary crash. You didn't enable it. 

> auto-failover functionality in 1.6.5 version with PostgreSQL 12.3 version isn't work very well in all cases and you should investigate it and fix.

Functionality perfectly works. The problem is that you infrastructure lacks monitoring. Free disk space MUST be ALWAYS monitored and alerted when it is low. WAL directory size is not growing out of nothing. If the wal size is growing this is an indicator of much bigger troubles.

**Comment by kmoppel** [comment]
I can easily understand why the OP got confused of the default behaviour - it's a bit counter intuitive indeed. But also good in sense that it avoids propagation of failure to other cluster members in case of WAL overflow.

Would probably make sense to extend documentation of _master_start_timeout_ on that - to mention that this does not avoid the above described "death loop". Or even maybe consider adding another more understandable parameter - something like _min_healthy_seconds_, meaning Postgres needs to stay up for X seconds and is demoted otherwise

**Comment by bimcas** [comment]
Thanks, **kmoppel** for your idea and offer (min_healthy_duration). I totally agree with you.
**CyberDem0n** don't concentrate to WAL disk full problem only. I think that we have the same "dead loop" with patroni when WAL disk fails in the master node. I mean HW problem or file system error, input/output error or WAL disk becomes read-only in the master node. It's difficult to predict such situations in advance, but it can happen. Do you agree with me?

Patroni is HA solution, so it would be great if patroni guarantee HA solution in any case (avoids "dead loops"). Thanks for understanding.

**Comment by CyberDem0n** [comment]
Feel free to implement it. Or you can just complain and  demand that someone else will do it?

**Comment by bimcas** [comment]
My mission was inform you and other patroni users about patroni auto-failover problem ("dead loop") in some cases.  As kmoppel said maybe new parameter **min_healthy_duration** (Postgres needs to stay up (healthy) for min X seconds or is demoted otherwise) will solved "dead loop" issue of patroni. I think you'll decide how it's better to implement it.
**Please, keep in mind it when you'll plan to develop and release new versions of patroni.** Thanks.
