### ISSUE TITLE
change PATRONI_LOG_DIR question

### ISSUE THREAD

**Issue by Liuzhj** [zalando/patroni#1665]
### Version
patronictl version 1.6.5
postgresql version: 11.8 

I forget specify the PATRONI_LOG_DIR when i initialize the postgresql cluster, the patroni log write to /var/log/messages.

i want to change the PATRONI_LOG_DIR to other path, but it not work.

- set variables for postgres
```
/var/lib/psql/.bash_profile
export PATRONI_LOG_DIR=/var/log/patroni
source /var/lib/psql/.bash_profile
```

- set variables for root
```
/root/.bash_profile
export PATRONI_LOG_DIR=/var/log/patroni
source /root/.bash_profile
```

- modify patroni config
systemctl restart patroni 
```
scope: xx
namespace: /xx/
name: xx_ha1
patroni_log_dir: /var/log/patroni/
```

Need you hands, thank you .

**Comment by CyberDem0n** [comment]
> patroni_log_dir: /var/log/patroni/

There is no such config parameter, please read the [documentation](https://patroni.readthedocs.io/en/latest/SETTINGS.html#log)
