### ISSUE TITLE
callback scripts

### ISSUE THREAD

**Issue by glushakov** [zalando/patroni#1666]
Hi. 
I have an issue with callbacks script.
in shell script i try to start\stop route announce. 
Here:

[05:31:25 postgres@host]:~$ cat /opt/scripts/bgp/patroni_vip_up.sh         
```
#!/bin/bash
readonly action=$1
readonly role=$2
readonly scope=$3

echo OK > /tmp/res.tmp

function usage() { echo "Usage: $0 <on_start|on_stop|on_role_change> <role> <scope>";exit 1; }
case $action in
   on_stop )
      vtysh -f /opt/scripts/bgp/ifdown
      ;;
   on_start|on_role_change )
      [[ $role == 'master' ]] && vtysh -f /opt/scripts/bgp/ifup || vtysh -f /opt/scripts/bgp/ifdown
      ;;
   * )
      usage
      ;;
esac
```

postgres user has permission to execute vtysh without sudo.

config part with callback scripts:

postgresql:
  callbacks:
    on_start: /opt/scripts/bgp/patroni_vip_up.sh
    on_stop: /opt/scripts/bgp/patroni_vip_up.sh
    on_role_change: /opt/scripts/bgp/patroni_vip_up.sh

But when i try stop\start\switchover postgres - nothing happening. 
part with ECHO - works correctly (so script was executed)

When i tried execute script manualy, from user postgres
 (/opt/scripts/bgp/patroni_vip_up.sh on_start master) - script execute correctly.

debug mode in patroni, not logged any errors in works callback scripts

**Comment by CyberDem0n** [comment]
My bet is that `vtysh` is not available in the PATH.

**Comment by glushakov** [comment]
> My bet is that `vtysh` is not available in the PATH.

Omg, you win. It's really problem with PATH
Thanks!
