### ISSUE TITLE
avoid restarts on pg13

### ISSUE THREAD

**Issue by fvannee** [zalando/patroni#1667]
Postgresql 13 makes some recovery settings (primary_conninfo and primary_slot_name) online reloadable as discussed here:
- https://commitfest.postgresql.org/27/1896/
- https://www.postgresql.org/docs/13/runtime-config-replication.html#RUNTIME-CONFIG-REPLICATION-STANDBY

I believe this can avoid most of the database restarts that Patroni initiates when hosts fail. For example, in a replication structure A->B, A->C. When A fails and B gets promoted. Now C can replicate from B without a restart.

**Comment by CyberDem0n** [comment]
It is implemented in the master branch a long time ago.

**Comment by fvannee** [comment]
Ah perfect, thanks! I didn't see it in the 'Compatibility with PG13' #1654  PR. But I see now it was already part of a different commit.
