### ISSUE TITLE
make heart beat log less verbose

### ISSUE THREAD

**Issue by nurali-techie** [zalando/patroni#1668]
**Issue:**
Currently, every loop_wait iteration, 2 info log entry added to master node and 3 info log entry added to replica node.

**Details:**
Below 2 info log entry added to master node:
```
2020-08-27 05:55:07,591 INFO: Lock owner: patroni1; I am patroni1
2020-08-27 05:55:07,598 INFO: no action.  i am the leader with the lock
```
Below 3 info log entry added to replica node:
```
2020-08-27 05:55:49,603 INFO: Lock owner: patroni1; I am patroni2
2020-08-27 05:55:49,603 INFO: does not have lock
2020-08-27 05:55:49,609 INFO: no action.  i am a secondary and i am following a leader
```

**Expectation:**
Ask is to make 1 info log entry for both master and replica.

**Benefit:**
With 1 info log entry there will be less log generated.  Also, with 1 log entry, there will be pattern when you see log file and if there is something else is added to log then you can find odd man out very easily.

**Version:**
Patroni: 1.6.5
PG: 12

**Comment by CyberDem0n** [comment]
Are you going to work on it?
If not I will close the issue as a duplicate.

**Comment by nurali-techie** [comment]
Thanks @CyberDem0n ; for now let's close this.  I will plan to do it soon and at that time I will ask more details on new log entry text etc. :+1:
