### ISSUE TITLE
local patroni config with a directory of yml files rather than a single file

### ISSUE THREAD

**Issue by fvannee** [zalando/patroni#1669]
What's your opinion on adding a feature where instead of specifying a single local configuration file, you can specify a directory containing multiple .yml files, which will all be loaded and combined. 
The main advantage this brings is to allow some common configuration files to be identical across all hosts in a cluster, while overriding specific settings in a separate file. Currently, it's often the case that 95% of the `patroni.yml` file is identical across hosts in a cluster, but there are a few things that may differ. It would be great in deployments if we could make this clear on a file-level with a layered structure.

For example, start Patroni by passing `config` directory. This `config` directory has files:
- `config/00-base.yml`
- `config/01-specific.yml`

In my example, everything in `00-base.yml` would be identical for all hosts in a cluster. `01-specific.yml` could contain some specific stuff like `tags` or the `raft.self_addr` attribute.
My proposal would be to modify `_load_config_file` to loop over all yml files in the directory in alphabetical order and run `patch_config` each time updating the current configuration. There are a couple of other places that need updating, but this is the rough idea.

I'd be happy to give this a try with a PR if it's a feature you'd be willing to accept.

**Comment by CyberDem0n** [comment]
IMO this is more a task of the configuration management system.

**Comment by fvannee** [comment]
In general I agree, but sometimes you have to deal with whatever configuration management system that's already in use, and it would be nice if Patroni could cater to some of these cases too.

**Comment by CyberDem0n** [comment]
Since if you volunteer to implement the feature I am fine with it.
