### ISSUE TITLE
the database system is starting up

### ISSUE THREAD

**Issue by buluxan** [zalando/patroni#1676]
Dear all ,

i have an issue with my 1 node patroni cluster , one of the node showing like in below after 
was rebooting , i have tried stop and then start the patroni it still showing starting only not running 
is there any step that i can following to make my node is running again 
```
patronictl -c /etc/patroni.yml list
+----------+--------+---------------+--------+----------+----+-----------+
| Cluster  | Member |      Host     |  Role  |  State   | TL | Lag in MB |
+----------+--------+---------------+--------+----------+----+-----------+
| postgres | pgha1  | 10.100.150.20 |                         | running  | 30 |    9367.0 |
| postgres | pgha2  | 10.100.150.21 |                         | starting |    |   unknown |
| postgres | pgha3  | 10.100.150.22 | Leader            | running  | 31 |           |
+----------+--------+---------------+--------+----------+----+-----------+
```
#################
service patroni status 
##################

Sep 01 17:08:31 dmp-prod-pgsql02 patroni[41887]: 2020-09-01 17:08:31.942 WIB [50705] FATAL:  the database system is starting up
Sep 01 17:08:31 dmp-prod-pgsql02 patroni[41887]: 2020-09-01 17:08:31.945 WIB [50708] FATAL:  the database system is starting up
Sep 01 17:08:31 dmp-prod-pgsql02 patroni[41887]: 2020-09-01 17:08:31.948 WIB [50709] FATAL:  the database system is starting up
Sep 01 17:08:31 dmp-prod-pgsql02 patroni[41887]: 2020-09-01 17:08:31.952 WIB [50712] FATAL:  the database system is starting up
Sep 01 17:08:31 dmp-prod-pgsql02 patroni[41887]: 2020-09-01 17:08:31.979 WIB [50716] FATAL:  the database system is starting up
Sep 01 17:08:32 dmp-prod-pgsql02 systemd[1]: Stopping Runners to orchestrate a high-availability PostgreSQL...

#################
here's the logs patroni
#################

tail -f /var/log/postgresql/patroni.log
2020-09-01 17:08:20,944 INFO: Error communicating with PostgreSQL. Will try again later
2020-09-01 17:08:29,924 INFO: Lock owner: pgha3; I am pgha2
2020-09-01 17:08:29,924 INFO: Still starting up as a standby.
2020-09-01 17:08:29,926 INFO: Lock owner: pgha3; I am pgha2
2020-09-01 17:08:29,926 INFO: does not have lock
2020-09-01 17:08:29,926 INFO: establishing a new patroni connection to the postgres cluster
2020-09-01 17:08:30,469 INFO: establishing a new patroni connection to the postgres cluster
2020-09-01 17:08:30,473 WARNING: Retry got exception: 'connection problems'
2020-09-01 17:08:30,477 INFO: Error communicating with PostgreSQL. Will try again later
2020-09-01 17:08:32,533 INFO: Lock owner: pgha3; I am pgha2

**Comment by CyberDem0n** [comment]
You should ALWAYS check postgres logs.

There is not only `pgha2`not running, but also `pgha1` lagging too much behind.

When you figure out from postgres logs what is wrong you can reinitialize both replicas with `patronictl reinit`.

**Comment by buluxan** [comment]
ok thx u @CyberDem0n  already following your instruction  , have running reinitialize in both replica node 

patronictl -c /etc/patroni.yml list
+----------+--------+---------------+--------+---------+----+-----------+
| Cluster  | Member |      Host     |  Role  |  State  | TL | Lag in MB |
+----------+--------+---------------+--------+---------+----+-----------+
| postgres | pgha1  | 10.100.150.20 |        | running | 31 |       0.0 |
| postgres | pgha2  | 10.100.150.21 |        | running | 31 |       0.0 |
| postgres | pgha3  | 10.100.150.22 | Leader | running | 31 |           |
+----------+--------+---------------+--------+---------+----+-----------+

**Comment by Hieu-Arrow** [comment]
thanks you @CyberDem0n node
my cluster is running good now
