### ISSUE TITLE
Patroni Etcd read_timeout

### ISSUE THREAD

**Issue by ahmedjami** [zalando/patroni#1681]
Patroni version: 1.6.5
PostgreSQL version: 11.8
Etcd version: 3.4

Configuration:
```
    ttl: 30
    loop_wait: 10
    retry_timeout: 10

```
Exception encountered 

 ```
ERROR: Request to server http://10.1.1.0:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'10.1.1.0\', port=2379): Max retries exceeded with url: /v2/keys/db/pg-ha/leader (Ca
used by ReadTimeoutError("HTTPConnectionPool(host=\'10.1.1.0\', port=2379): Read timed out. (read timeout=1.999905027449131)",))',)
2020-09-02 10:59:43,659 INFO: Reconnection allowed, looking for another server.
2020-09-02 10:59:43,659 INFO: Retrying on http://10.1.1.1:2379
2020-09-02 10:59:44,661 ERROR: Request to server http://10.1.1.1:2379 failed: MaxRetryError("HTTPConnectionPool(host='10.1.1.1', port=2379): Max retries exceeded with url: /v2/keys/db/pg-ha/leader (Ca
used by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f63fc80a400>, 'Connection to 10.1.1.1 timed out. (connect timeout=1)'))",)
```
I'm wondering about the value of read timeout, I can see from the logs that the `read timeout = 1.999905027449131`, It is my understanding that this timeout is set to 10second at retry_timeout parameter.
Can someone help me understand this value, please ? :)

**Comment by CyberDem0n** [comment]
The read timeout is calculated from the retry_timeout and the number of nodes in the etcd cluster..

**Comment by ahmedjami** [comment]
thanks @CyberDem0n for the for the quick response.
So, if I have 5 nodes, the read time out will be `retry_timeout / 5` seconds ? which corresponds to the read_timeout that I see from the logs.

**Comment by CyberDem0n** [comment]
Yes. In case if one node fails we still  have time to retry on other nodes.

**Comment by ahmedjami** [comment]
thanks a lot @CyberDem0n

**Comment by ahmedjami** [comment]
sorry @CyberDem0n 
I will have another question. In my case, I will increase the value of retry_timeout. I should also increase the values of loop_wait and/or ttl ? Is it recommended to have the same value for retry_timeout and loop_wait ?
Thanks a lot

**Comment by CyberDem0n** [comment]
There is the formula:
```
loop_wait + 2*retry_timeout <= ttl
```

**Comment by ahmedjami** [comment]
thanks again @CyberDem0n
