### ISSUE TITLE
Issue while building Patroni Dockerfile

### ISSUE THREAD

**Issue by dhanasg** [zalando/patroni#1683]
Hi,

Due to a security requirement, i am trying to build Patroni image from scratch.
Only change is instead of "ubuntu:18.04", i am using Ubuntu OS on which few hardening and security fixes are applied.

I fetched the dockerfile from "https://github.com/zalando/spilo/releases" - spilo-1.6-p3\postgres-appliance\Dockerfile.

I observed the below line fails for some reason. Any workaround?

git clone -b $PAM_OAUTH2 --recurse-submodules https://github.com/CyberDem0n/pam-oauth2.git

![image](https://user-images.githubusercontent.com/46438725/92438525-9f7fe880-f1c6-11ea-9cab-2f225c128e6d.png)

If i remove "--recurse-submodules", its able to download pam-oauth2 folder. Any help is appreciated.

![image](https://user-images.githubusercontent.com/46438725/92438080-cd186200-f1c5-11ea-8d7d-d964a179f954.png)

**Comment by CyberDem0n** [comment]
1. This is a wrong repo (Patroni, not Spilo)
2. You are abusing screenshots, it could be just a text copy&paste
3. Last, but not least, you are using a 4 month old release, everything should work in the master branch (or at least the latest release).
