### ISSUE TITLE
The problem is in patroni.service.j2

### ISSUE THREAD

**Issue by sgrinko** [zalando/patroni#1688]
Hi,
In the file:

[https://github.com/zalando/patroni/blob/master/extras/startup-scripts/patroni.service](https://github.com/zalando/patroni/blob/master/extras/startup-scripts/patroni.service)

there is such a line
`WorkingDirectory = ~`
at startup, we see the following message:
```
Sep 10 15:15:55 node1 systemd[1]: [/etc/systemd/system/patroni.service:14] Not an absolute path, ignoring: ~
Sep 10 15:15:55 node1 systemd[1]: [/etc/systemd/system/patroni.service:14] Not an absolute path, ignoring: ~
```
systemd service files must specify absolute paths.

**Comment by CyberDem0n** [comment]
And? What is your suggestion?

**Comment by sgrinko** [comment]
options to choose from:
- delete this string from service file (it is ignored anyway and the default is applied)
- set value with absolute path (choose appropriate path)

this error is written to the log when the command is running:
`systemctl daemon-reload`

based on the documentation, it should work, but it does not work ... 
```
WorkingDirectory=
    Takes a directory path relative to the service's root directory specified by RootDirectory=, or the special value "~". 
    Sets the working directory for executed processes. If set to "~", the home directory of the user specified in User= is used. 
    If not set, defaults to the root directory when systemd is running as a system instance and the respective user's home 
    directory if run as user. If the setting is prefixed with the "-" character, a missing working directory is not considered fatal. 
    If RootDirectory=/RootImage= is not set, then WorkingDirectory= is relative to the root of the system running the service
    manager. Note that setting this parameter might result in additional dependencies to be added to the unit (see above).
```
maybe I have not a completely new edition of systemd
```
#lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.8.2003 (Core)
Release:        7.8.2003
Codename:       Core
# uname -a
Linux 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by CyberDem0n** [comment]
There is also a third option, comment it out and let the user configure it:
```
# WorkingDirectory = /home/postgres
```

It would be very cool if you open a PR.

**Comment by sgrinko** [comment]
I am still just mastering github while it is still difficult for me

**Comment by CyberDem0n** [comment]
> I am still just mastering github while it is still difficult for me

You can do it even via web.
