### ISSUE TITLE
 system ID mismatch and patroni crash after DCS timeout and recovery

### ISSUE THREAD

**Issue by danielabelski** [zalando/patroni#1690]
I am testing a failre condition

I have 3 node consul cluster and 2 node PG. patroni 2.0

After I shut down the consul cluster I see that all PG nodes enter RO state. But aster I restart the consul nodes I get:

> 2020-09-11 17:17:27,622 ERROR: Error communicating with DCS
2020-09-11 17:17:27,624 INFO: DCS is not accessible
2020-09-11 17:17:27,626 WARNING: Loop time exceeded, rescheduling immediately.
2020-09-11 17:17:30,679 CRITICAL: system ID mismatch, node postgres1 belongs to a different cluster: 6870866589780482360 != 6871098321080277194
2020-09-11 17:17:31,083 INFO: Register service pgsql, params {'service_id': 'pgsql/postgres1', 'address': '172.16.0.108', 'port': 5432, 'check': {'http': 'http://172.16.0.108:8008/replica', 'interval': '5s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['replica']}
2020-09-11 17:17:31,151 INFO: Deregister service pgsql/postgres1

and patroni goes down

> [root@pg1 /]# systemctl status patroni
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/etc/systemd/system/patroni.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2020-09-11 17:17:31 +05; 31min ago
  Process: 37630 ExecStart=/usr/local/bin/patroni /etc/patroni.yml (code=exited, status=1/FAILURE)
 Main PID: 37630 (code=exited, status=1/FAILURE)

> Sep 11 17:16:35 pg1.navixy patroni[37630]: 2020-09-11 17:16:35.346 +05 [37707] LOG:  listening on IPv4 address "0.0.0.0", port 5432
Sep 11 17:16:35 pg1.navixy patroni[37630]: 2020-09-11 17:16:35.346 +05 [37707] LOG:  listening on IPv6 address "::", port 5432
Sep 11 17:16:35 pg1.navixy patroni[37630]: 2020-09-11 17:16:35.349 +05 [37707] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
Sep 11 17:16:35 pg1.navixy patroni[37630]: 2020-09-11 17:16:35.352 +05 [37707] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
Sep 11 17:16:35 pg1.navixy patroni[37630]: 2020-09-11 17:16:35.369 +05 [37707] LOG:  redirecting log output to logging collector process
Sep 11 17:16:35 pg1.navixy patroni[37630]: 2020-09-11 17:16:35.369 +05 [37707] HINT:  Future log output will appear in directory "log".
Sep 11 17:16:36 pg1.navixy patroni[37630]: /var/run/postgresql:5432 - accepting connections
Sep 11 17:16:36 pg1.navixy patroni[37630]: /var/run/postgresql:5432 - accepting connections
Sep 11 17:17:31 pg1.navixy systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Sep 11 17:17:31 pg1.navixy systemd[1]: patroni.service: Failed with result 'exit-code'.

As you can see - first there is a restart in RO and then it goes down

the `CRITICAL: system ID mismatch, node postgres1 belongs to a different cluster: 6870866589780482360 != 6871098321080277194` is a mistery to me as when I do `[root@pg1 /]# pg_controldata /data/patroni/`

I get
> Database system identifier:           6871098321080277194

and cluster/pgsql/initialize/ contains the same value

So where does 6870866589780482360 come from?

If I issue `systemctl restart partoni` everything starts working like there was no error.

I need patroni to resume working and not going down in this case, but cant undestand how.

**Comment by CyberDem0n** [comment]
> So where does 6870866589780482360 come from?

It came from consul. For some reason it gives you stale data.

You can try to change the [consistency mode](https://github.com/zalando/patroni/blob/master/docs/SETTINGS.rst#consul) to `consistent`, it should help.

**Comment by danielabelski** [comment]
It helped.
Last question - should I change any timout values if I use `consistent`?

Thanks for your help and wonderful software.

**Comment by CyberDem0n** [comment]
> should I change any timout values if I use consistent?

No. It is only important to follow the formula: `loop_wait + 2 * retry_timeout <= ttl`
