### ISSUE TITLE
Will pausing WAL replay affect patroni?

### ISSUE THREAD

**Issue by victor-sudakov** [zalando/patroni#1691]
If I temporarily pause the recovery process by issuing "SELECT pg_wal_replay_pause()" on a standby node (to create a filesystem snapshot for example), will it disrupt the operation of Patroni?

**Comment by CyberDem0n** [comment]
Paused WAL replay will make the node to lag behind and it is very unlikely that on primary failure this node will become the new leader.

Actually, pausing the wal replay is not enough to make your snapshot consistent, you should use [pg_start_backup()/pg_stop_backup()](https://www.postgresql.org/docs/current/continuous-archiving.html#BACKUP-LOWLEVEL-BASE-BACKUP-NONEXCLUSIVE) in non-exclusive mode.

**Comment by victor-sudakov** [comment]
> Paused WAL replay will make the node to lag behind and it is very unlikely that on primary failure this node will become the new leader.
> 

Depending on the  maximum_lag_on_failover, right?

> Actually, pausing the wal replay is not enough to make your snapshot consistent, you should use [pg_start_backup()/pg_stop_backup()](https://www.postgresql.org/docs/current/continuous-archiving.html#BACKUP-LOWLEVEL-BASE-BACKUP-NONEXCLUSIVE) in non-exclusive mode.

To obtain a consistent backup, I use pg_basebackup from another host. For a quick PITR, pausing the WAL replay has always been sufficient.

**Comment by CyberDem0n** [comment]
> Depending on the maximum_lag_on_failover, right?

Sort of. Patroni might call pg_ctl promote, but if wal replay is paused postgres will not promote until resume is called.

> To obtain a consistent backup, I use pg_basebackup from another host. For a quick PITR, pausing the WAL replay has always been sufficient.

Come on, in the original message you referred to `filesystem snapshot`, which is effectively a backup.

**Comment by victor-sudakov** [comment]
> > Depending on the maximum_lag_on_failover, right?
> 
> Sort of. Patroni might call pg_ctl promote, but if wal replay is paused postgres will not promote until resume is called.
> 

I understood every word but they did not make sense :-) Need to experiment probably.

> > To obtain a consistent backup, I use pg_basebackup from another host. For a quick PITR, pausing the WAL replay has always been sufficient.
> 
> Come on, in the original message you referred to `filesystem snapshot`, which is effectively a backup.

I use 12-hour ZFS snapshots on a standby as a cheap time machine. Whenever I need a PITR, I clone the nearest ZFS snapshot, start a separate instance there with the recovery_target_time I need, and let it catch up from the WAL archive. Works like charm.

**Comment by victor-sudakov** [comment]
I think you even cannot use pg_start_backup() on a standby:

```
postgres=# select pg_is_in_recovery();
 pg_is_in_recovery 
-------------------
 t
(1 row)

postgres=# select pg_start_backup('test');
ERROR:  recovery is in progress
HINT:  WAL control functions cannot be executed during recovery.
postgres=# 

```

**Comment by CyberDem0n** [comment]
You are trying to start exclusive backup, while I was specifically talking about the non-exclusive mode: `SELECT pg_start_backup('label', false, false);`

**Comment by victor-sudakov** [comment]
Interesting. Never had to use pg_start_backup() before (directly).

**Comment by victor-sudakov** [comment]
As I have just double checked, select `pg_start_backup('test1',false,false);` does not prevent the database from writing to disk (checked with mtree). Thus, for a filesystem level backup (which a ZFS snapshot essentially is) this pg_start_backup() does not make much sense, probably.

**Comment by uspen** [comment]
pg_start_backup function execute checkpoint (and other actions) and this guarantees consistency

**Comment by CyberDem0n** [comment]
> does not prevent the database from writing to disk

Of course it doesn't and it shouldn't, but it makes a backup consistent! There is one additional step required though, you have to save the backup label.

Actually, pausing wal replay doesn't necessarily stop writes, the background writer is still active and might update some pages.

**Comment by victor-sudakov** [comment]
There is nothing magical about `pg_start_backup()`. There is a good article online: https://www.2ndquadrant.com/en/blog/what-does-pg_start_backup-do/ which stresses that _the base backup is NOT a consistent copy of the database. You might have copied every file, but all the data is taken at different times. So its wrong. Until you recover the database with the WAL changes that occurred between the start backup and the stop backup._ 

Therefore I just create a ZFS snapshot and don't care much, because it's the recovery process that will make the database  consistent when it reaches the required  recovery_target_time.

Anyway, PostgreSQL is designed to survive a sudden poweroff. That's probably how the world looks for the PITR instance on a filesystem - it awakes as if after a poweroff. But is has the WAL archive available readily available to it.

Pausing WAL replay doesn't necessarily stop writes, but it quiets the filesystem quite a bit, just to be on the safe side. Maybe even stopping the WAL replay before snapshot is excessive and unnecessary.

**Comment by victor-sudakov** [comment]
> pg_start_backup function execute checkpoint (and other actions) and this guarantees consistency

No, not actually.

**Comment by victor-sudakov** [comment]
> > pg_start_backup function execute checkpoint (and other actions) and this guarantees consistency
> 
> No, not actually.

Let me explain. I mean that pg_basebackup also fetches WAL files and stores them in a separate archive (pg_wal.tar.gz). Without those WAL files, the backup is NOT consistent even though pg_basebackup executes pg_start_backup() or BASE_BACKUP or whatever to that effect.

**Comment by CyberDem0n** [comment]
With correctly configured archive_command you don't need to stream WAL files.
