### ISSUE TITLE
'patronictl list' hangs in infinite loop

### ISSUE THREAD

**Issue by 60090830** [zalando/patroni#1694]
Hello!

I'm testing patroni in OpenStack on Centos7 with postgresql 11 version and pysync on pure raft.

I have 3 node configuration (patroni + postgres + pysync) and everything seems to work fine:

![patroni_list_node0](https://user-images.githubusercontent.com/71021458/93201979-9b217580-f75a-11ea-81aa-cc5a3eb16808.jpg)

![patroni_list_node1](https://user-images.githubusercontent.com/71021458/93202033-af657280-f75a-11ea-9d0a-982f731009f7.jpg)

And failover is also performing great:

![patroni_list_node1_after_restart](https://user-images.githubusercontent.com/71021458/93202141-e3d92e80-f75a-11ea-8731-56fc5f96c76f.jpg)

But on 1 of the nodes 'patronictl list' hangs and never ends:

![patroni_list_node2_hang](https://user-images.githubusercontent.com/71021458/93202378-48948900-f75b-11ea-864a-f59090a2d653.jpg)

Looks like in /usr/local/lib/python3.6/site-packages/patroni/dcs/raft.py class KVStoreTTL(DynMemberSyncObj) never gets data inside __onTick function

    def _onTick(self, timeToWait=0.0):
        # The SyncObj starts applying the local log only when there is at least one node connected.
        # We want to change this behavior and apply the local log even when there is nobody except us.
        # It gives us at least some picture about the last known cluster state.

        if self.__early_apply_local_log and not self.applied_local_log and self._SyncObj__needLoadDumpFile:
            self._SyncObj__raftCommitIndex = self._SyncObj__getCurrentLogIndex()
            self._SyncObj__raftCurrentTerm = self._SyncObj__getCurrentLogTerm()

        super(KVStoreTTL, self)._onTick(timeToWait)

        # The SyncObj calls onReady callback only when cluster got the leader and is ready for writes.
        # In some cases for us it is safe to "signal" the Raft object when the local log is fully applied.
        # We are using the `applied_local_log` property for that, but not calling the callback function.
        if self.__early_apply_local_log and not self.applied_local_log and self._SyncObj__raftCommitIndex != 1 and \
                self._SyncObj__raftLastApplied == self._SyncObj__raftCommitIndex:
            self.applied_local_log = True

        if self._isLeader():
            self.__expire_keys()
        else:
            self.__limb.clear()

And never exit infinite loop in class Raft __init__

       while True:
            ready_event.wait(5)
            if ready_event.isSet() or self._sync_obj.applied_local_log:
                break
            else:
                logger.info('waiting on raft')

Here is config file from node 2:

[patroni_2.zip](https://github.com/zalando/patroni/files/5224409/patroni_2.zip)

After patroni restart on node2 list start to work correctly, but hangs in the same way on node 1 and so on.

All this time syncobj_admin is working fine:

[root@pg1 ~]# syncobj_admin -conn `hostname -i`:4321 -status
commit_idx: 159439
enabled_code_version: 0
last_applied: 159439
leader: 10.203.97.123:4321
leader_commit_idx: 159439
log_len: 50
match_idx_count: 2
match_idx_server_10.203.97.106:4321: 159439
match_idx_server_10.203.97.81:4321: 159439
next_node_idx_count: 2
next_node_idx_server_10.203.97.106:4321: 159440
next_node_idx_server_10.203.97.81:4321: 159440
partner_node_status_server_10.203.97.106:4321: 2
partner_node_status_server_10.203.97.81:4321: 2
partner_nodes_count: 2
raft_term: 772
readonly_nodes_count: 0
revision: deprecated
self: 10.203.97.123:4321
self_code_version: 0
state: 2
uptime: 2225
version: 0.3.6

Could you please help?

Thank you.

**Comment by CyberDem0n** [comment]
I can reproduce it.
Here is the fix that should help:
```diff
diff --git a/patroni/dcs/raft.py b/patroni/dcs/raft.py
index 66359d1..7fe618f 100644
--- a/patroni/dcs/raft.py
+++ b/patroni/dcs/raft.py
@@ -269,14 +269,19 @@ class Raft(AbstractDCS):
         super(Raft, self).__init__(config)
         self._ttl = int(config.get('ttl') or 30)
 
-        self_addr = None if self._ctl else config.get('self_addr')
+        self_addr = config.get('self_addr')
+        partner_addrs = config.get('partner_addrs', [])
+        if self._ctl:
+            if self_addr:
+                partner_addrs.append(self_addr)
+            self_addr = None
         template = os.path.join(config.get('data_dir', ''), self_addr or '')
         files = {'journalFile': template + '.journal', 'fullDumpFile': template + '.dump'} if self_addr else {}
 
         ready_event = threading.Event()
         conf = SyncObjConf(commandsWaitLeader=False, appendEntriesUseBatch=False, onReady=ready_event.set,
                            dynamicMembershipChange=True, **files)
-        self._sync_obj = KVStoreTTL(self_addr, config.get('partner_addrs', []), conf, self._on_set, self._on_delete)
+        self._sync_obj = KVStoreTTL(self_addr, partner_addrs, conf, self._on_set, self._on_delete)
         while True:
             ready_event.wait(5)
             if ready_event.isSet() or self._sync_obj.applied_local_log:
```

**Comment by 60090830** [comment]
@CyberDem0n Thank you so much for the reply.
This fix is working for me.

Thanks again!

**Comment by alexeymyltsev** [comment]
@CyberDem0n Will be this patch added to some release?

**Comment by CyberDem0n** [comment]
Sure, I will create the PR later today.
