### ISSUE TITLE
Kubernetes endpoint for leader not updated after resuming from hard crash

### ISSUE THREAD

**Issue by le-duane** [zalando/patroni#1698]
**Describe the bug**
After a non-graceful termination of the leader pod, if the leader recovers before TTL, the Kubernetes [endpoint](https://github.com/zalando/patroni/blob/d662d4073ceec36e1702c80d536ceba464aeab08/kubernetes/patroni_k8s.yaml#L118) used for leader-election retains the old pod IP of the leader instead of the new IP. 

I did not find an obvious way to rectify this aside from gracefully restarting the leader pod. Until the leader is restarted, the replicas are left orphaned since they are looking for leader at wrong IP.

**To Reproduce**
`shutdown -h now` on worker node of leader pod

**Expected behavior**
I would expect that Patroni updates the Kubernetes leader election endpoint with the new IP of the leader pod

**Environment**
- Patroni version: 1.6.5, 2.0.0
- PostgreSQL version: 11.9
- DCS (and its version): Kubernetes 1.15.11

**Have you checked Patroni logs?**
```
2020-09-15 19:08:13,605 INFO: establishing a new patroni connection to the postgres cluster
2020-09-15 19:08:13,785 INFO: promoted self to leader because i had the session lock
server promoting
2020-09-15 19:08:13.789 UTC [73] LOG:  received promote request
2020-09-15 19:08:13.789 UTC [73] LOG:  redo done at 0/3003C60
2020-09-15 19:08:13.791 UTC [73] LOG:  selected new timeline ID: 2
2020-09-15 19:08:13,791 INFO: cleared rewind state after becoming the leader
2020-09-15 19:08:13.838 UTC [73] LOG:  archive recovery complete
2020-09-15 19:08:13.846 UTC [71] LOG:  database system is ready to accept connections
```

**Have you tried to use GitHub issue search?**
Yes

**Comment by CyberDem0n** [comment]
> Until the leader is restarted, the replicas are left orphaned since they are looking for leader at wrong IP.

And what is wrong with it? Only the leader updates the endpoint. Since you killed the node it wasn't able to do that.

> I would expect that Patroni updates the Kubernetes leader election endpoint with the new IP of the leader pod

And it does that when the pod is rescheduled and Patroni started there.

**Comment by le-duane** [comment]
@CyberDem0n apologies if I was not clear on this:

1. Leader pod with IP x.x.192.139 is terminated non-gracefully 
2. Leader pod comes back with IP x.x.192.250 before TTL expires (`promoted self to leader because i had the session lock`)
 - Leader is running perfectly fine, but endpoint is still pointing to x.x.192.139
 - Replicas cannot connect to x.x.192.139
3. Leader pod deleted gracefully and comes back with IP x.x.192.23
 -  Endpoint is updated to x.x.192.23 and replicas can now communicate with leader pod.

**Comment by CyberDem0n** [comment]
Could you please exec into the pod and check the environment variable and patroni.yaml?
I am specifically interested in the `kubernetes.pod_ip`.

**Comment by le-duane** [comment]
Here you go!

```
# =================
# Before State
# =================

+ Cluster: argos-gato-clr (6840100328021692497) -----+---------+----+-----------+
| Member             | Host           | Role         | State   | TL | Lag in MB |
+--------------------+----------------+--------------+---------+----+-----------+
| argos-gato-clr-c-0 | x.x.196.238    | Leader       | running | 82 |           |
| argos-gato-clr-d-0 | x.x.199.14     | Sync Standby | running | 82 |         0 |
+--------------------+----------------+--------------+---------+----+-----------+

# =================
# After State
# =================

+ Cluster: argos-gato-clr (6840100328021692497) +---------+----+-----------+
| Member             | Host           | Role    | State   | TL | Lag in MB |
+--------------------+----------------+---------+---------+----+-----------+
| argos-gato-clr-c-0 | x.x.196.238    | Leader  | running | 83 |           |
| argos-gato-clr-d-0 | x.x.199.14     | Replica | running | 82 |         0 |
+--------------------+----------------+---------+---------+----+-----------+

## Leader IP
kubectl get pod argos-gato-clr-c-0 -o jsonpath='{.status.podIP}'
x.x.197.167

## Leader IP in Patroni config
kubectl exec -it argos-gato-clr-c-0 -c admin -- bash -c \
    'yq read /ephemeral_configs/patronictl.yaml kubernetes.pod_ip'
x.x.197.167

## Leader IP in Endpoint
kubectl get ep argos-gato-clr -o json|jq -r '.subsets[0].addresses[0].ip'
x.x.196.238
```

**Comment by CyberDem0n** [comment]
Could you also please check `postgresql.connect_address` and `restapi.connect_address`?
The thing is that `patronictl list` also reports `x.x.196.238`!

**Comment by le-duane** [comment]
Yep!

```
## postgresql.connect_address
kubectl exec -it argos-gato-clr-c-0 -c admin -- bash -c \
    'yq read /ephemeral_configs/patronictl.yaml postgresql.connect_address'
x.x.197.167

## restapi.connect_address
kubectl exec -it argos-gato-clr-c-0 -c admin -- bash -c \
    'yq read /ephemeral_configs/patronictl.yaml restapi.connect_address'
x.x.197.167
```

**Comment by CyberDem0n** [comment]
Something is fishy here.
Probably the config file was updated after Patroni was started.

**Comment by CyberDem0n** [comment]
And BTW, you check the `patronictl.yaml`, is it the same file that is used by Patroni?

**Comment by le-duane** [comment]
Thanks so much for your time on this @CyberDem0n 

Still trying to rule out config file being modified after start.

Here's the config file check.

```
## config used by process
kubectl exec -it argos-gato-clr-c-0 -c postgres -- bash -c \
    'ps -fp $(pgrep patroni)|grep .'
UID        PID  PPID  C STIME TTY          TIME CMD
postgres    24     6  0 07:45 ?        00:00:02 /usr/bin/python3 /usr/local/bin/patroni /home/postgres/.config/patroni/patronictl.yaml

## config used by process is a symlink
kubectl exec -it argos-gato-clr-c-0 -c postgres -- bash -c \
    'readlink -f /home/postgres/.config/patroni/patronictl.yaml'
/ephemeral_configs/patronictl.yaml
```

**Comment by le-duane** [comment]
Looks like my "ephemeral_configs" aren't as ephemeral as I thought! 

Config was definitely templated with new IP _after_ Patroni started.

```
## patroni start time
kubectl exec -it argos-gato-clr-c-0 -c admin -- bash -c \
    "ls --time-style='+%d-%m-%Y %H:%M:%S' -ld /proc/\$(pgrep patroni)"
dr-xr-xr-x 9 postgres postgres 0 16-09-2020 07:45:13 /proc/24

## last modificztion date on config file
kubectl exec -it argos-gato-clr-c-0 -c admin -- bash -c \
    "ls --time-style='+%d-%m-%Y %H:%M:%S' -l /ephemeral_configs/patronictl.yaml"
-rw-r--r-- 1 postgres postgres 8999 16-09-2020 07:45:14 /ephemeral_configs/patronictl.yaml
```

```
  - emptyDir: {}
    name: ephemeral-configs
```

Should have been

```
  - emptyDir:
      medium: Memory
    name: ephemeral-configs
```

Thanks so much for lending your expertise on this @CyberDem0n
