### ISSUE TITLE
Modifying the parameters through edit-config does not actually take effect in postgres

### ISSUE THREAD

**Issue by palosky** [zalando/patroni#1703]
### **Describe the bug**
Hello, friends, when I modify the parameter value through the edit-config command, it does not actually take effect in postgres. I don’t know why。Thans for help！

### **To Reproduce**
patronictl -c /etc/node1.yml edit-config

loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  cluster_name: pgdb10
  listen_addresses: '*'
  max_connections: 300              --------
  max_replication_slots: 10
  max_wal_senders: 10
  max_worker_processes: 64
  port: 25432
  track_commit_timestamp: false
  wal_keep_segments: 300          --------
  wal_level: replica
  wal_log_hints: true
retry_timeout: 10
synchronous_mode: false
ttl: 30

### **Expected behavior**
show max_connections; ---- 300
show wal_keep_segments;  ---- 300

### **Actual behavior**
psql (10.9)
Type "help" for help.

show max_connections;
 max_connections 
-----------------
 100
(1 row)

show wal_keep_segments;
 wal_keep_segments 
-------------------
 8
(1 row)

### **Environment**
- Patroni version:   patroni 2.0.0
- PostgreSQL version:  10.9
- DCS (and its version):  etcd Version: 3.3.11

### **Patroni configuration file**
scope: pgdb10
namespace: /service/
name: node1

restapi:
  listen: 192.168.0.131:8008
  connect_address: 192.168.0.131:8008

etcd:
  host: 192.168.0.131:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:

postgresql:
  listen: 0.0.0.0:25432
  connect_address: 192.168.0.131:25432
  data_dir: /app/pgsql-10/data
  bin_dir: /app/pgsql-10/bin
  authentication:
    replication:
      username: repuser
      password: rep2019@test.com
    superuser:
      username: postgres
      password: 123456

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

### **patronictl show-config**
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  cluster_name: pgdb10
  listen_addresses: '*'
  max_connections: 300
  max_replication_slots: 10
  max_wal_senders: 10
  max_worker_processes: 64
  port: 25432
  track_commit_timestamp: false
  wal_keep_segments: 300
  wal_level: replica
  wal_log_hints: true
retry_timeout: 10
synchronous_mode: false
ttl: 30

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**

**Comment by CyberDem0n** [comment]
Because it has to be `postgresql.parameters.wal_keep_segments`. For the rest please read the [documentation](https://patroni.readthedocs.io/en/latest/dynamic_configuration.html).
