### ISSUE TITLE
Add option to disable CORS for the REST api

### ISSUE THREAD

**Issue by Penagwin** [zalando/patroni#1704]
Hello! I know this is likely pretty niche, but I need a way to disable CORS. I know the security implications involved, but actual operations are password protected and it's on our internal network.

**Comment by CyberDem0n** [comment]
You can add arbitrary headers to REST API responses: https://patroni.readthedocs.io/en/latest/SETTINGS.html#rest-api

**Comment by Penagwin** [comment]
Oh perfect! Never mind then!
