### ISSUE TITLE
Switchover restarts server that is not switched over from/to

### ISSUE THREAD

**Issue by rsmoorthy** [zalando/patroni#1708]
**Describe the bug**
Servers are s1, s2, s3. When s1 is the Leader, manually switching over to s2, s3 (not directly part of this transaction) goes from running state to stopped state and back to running state. During this time, all client postgres connections to s3 are closed.

In addition, all client connections are closed on s1. However, client connections to s2 (which becomes a new leader) stays alive.

Summary: In a switchover or failover, the server that comes the leader has no disruptions on the client postgres connections, while the the other standby server's client connections gets disrupted.

**To Reproduce**
1. All servers are in running state.
2. Leader is s1
3. Open 3 windows. Execute "psql -U postgres -h s1/s2/s3" (respectively in each of the window). And run "select pg_sleep(300);"
4. On the 4th window, Issue `patronictl switchover` to switch over from s1 to s2
5. Switches over successfully to s2
6. Just as s2 becomes the Leader, watch s3 going from running state to stopped state and then to running state
7. Notice that "psql" connections to s2 (the new leader) stays alive, while psql connections to s1 and s3 are disrupted.

**Expected behavior**
I am entirely not sure, if a new leader will require all standby servers to go to stopped state, before getting to running state. Is it possible that the switchover does not disrupt the postgres connections wherever possible. (I don't know what is involved in technically switching over)

**Environment**
- Patroni version:  1.6.5
- PostgreSQL version: 9.6
- DCS (and its version): etcd 3.2.18

**Comment by CyberDem0n** [comment]
Change of primary_connino requires restart (until postgres 13)
