### ISSUE TITLE
The 'ipaddress' distribution was not found and is required by urllib3

### ISSUE THREAD

**Issue by seenutn** [zalando/patroni#1709]
This is not an patroni issue but I encountered while running patroni 2 on centos 8.2 and hence posting it here.

Here is the error I am encountering:

[root@Maindb-rep ~]# patroni --version
Traceback (most recent call last):
  File "/usr/bin/patroni", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ipaddress' distribution was not found and is required by urllib3

[root@Maindb-rep ~]# python3 --version
Python 3.6.8

[root@Maindb-rep ~]# locate ipaddress.py
/usr/lib/python3.6/site-packages/pip/_vendor/ipaddress.py
/usr/lib64/python3.6/ipaddress.py
/usr/lib64/python3.6/site-packages/psycopg2/_ipaddress.py
[root@Maindb-rep ~]#

How can I fix this error?

Regards,
Seenu.

**Comment by CyberDem0n** [comment]
> How can I fix this error?

How was the Patroni installed? Judging from ` File "/usr/bin/patroni", line 6, in ` you haven't used pip.

**Comment by seenutn** [comment]
Using yum.  

[root@Maindb-rep ~]# rpm -qfi /usr/bin/patroni
Name        : patroni
Version     : 2.0.0
Release     : 2.rhel8
Architecture: x86_64
Install Date: Sunday 20 September 2020 10:38:40 PM IST
Group       : Unspecified
Size        : 2090358
License     : MIT
Signature   : DSA/SHA1, Monday 07 September 2020 06:33:24 PM IST, Key ID 1f16d2e1442df0f8
Source RPM  : patroni-2.0.0-2.rhel8.src.rpm
Build Date  : Monday 07 September 2020 06:33:24 PM IST
Build Host  : koji-rhel8-x86-64-pgbuild
Relocations : (not relocatable)
Vendor      : PostgreSQL Global Development Group
URL         : https://github.com/zalando/patroni
Summary     : A Template for PostgreSQL HA with ZooKeeper, etcd or Consul
Description :
Patroni is a template for you to create your own customized,
high-availability solution using Python and - for maximum accessibility - a
distributed configuration store like ZooKeeper, etcd, Consul or Kubernetes.
Database engineers, DBAs, DevOps engineers, and SREs who are looking to
quickly deploy HA PostgreSQL in the datacenter-or anywhere else-will
hopefully find it useful.

We call Patroni a "template" because it is far from being a
one-size-fits-all or plug-and-play replication system. It will have its own
caveats. Use wisely.
[root@Maindb-rep ~]#

**Comment by CyberDem0n** [comment]
Looks like a packaging issue, or maybe @devrimgunduz has some ideas.

As a workaround I can recommend trying to install it with pip.

**Comment by devrimgunduz** [comment]
@CyberDem0n I was told that ipaddress is built-in in recent PY3 versions. If that is the case, how can I fix this issue?

**Comment by CyberDem0n** [comment]
Yes, exactly, it is built-in, I don't know why pkg_resources is unhappy :(

**Comment by devrimgunduz** [comment]
Hi @CyberDem0n , any plans for a new release so that I can fix the RPMs as well?

Cheers, Devrim

**Comment by CyberDem0n** [comment]
Sure, today or tomorrow.

**Comment by devrimgunduz** [comment]
Things work great. Thanks!
