### ISSUE TITLE
Lag always increases, and no down

### ISSUE THREAD

**Issue by smartbayaraa** [zalando/patroni#1715]
Hello,

Currently, my lag always increases, and no down. And Leader database very slow this time. When I stop the slave node, it is getting fast.

+----------+-----------------+----------------+--------+---------+-----------+
| Cluster  |      Member     |      Host      |  Role  |  State  | Lag in MB |
+----------+-----------------+----------------+--------+---------+-----------+
| postgres | postsqlmaster01 | 192.168.15.203 | Leader | running |       0.0 |
| postgres | postsqlmaster03 | 192.168.15.204 |        | running |   70460.0 |
+----------+-----------------+----------------+--------+---------+-----------+

How can fix it?

Thank you

**Comment by CyberDem0n** [comment]
Why don't you use the issue template?
It has very valid questions regarding checking logs of all kinds and using github issue search.
You haven't done anything like that!

**Comment by smartbayaraa** [comment]
> k

Can you attach the link to a similar issue? 
I could not find it. 

Thanks

**Comment by CyberDem0n** [comment]
Repeating my questions:
* have you checked patroni logs?
* have you checked postgres logs?
* have you used GH search?

**Comment by smartbayaraa** [comment]
> Repeating my questions:
> 
> * have you checked patroni logs?
> * have you checked postgres logs?
> * have you used GH search?

Do you have dedicated support? If yes, how can I connect you?

**Comment by CyberDem0n** [comment]
This is an open-source project. As maintainers we don't provide commercial support.
There are some companies doing that, but I don't really want to name them here.

**Comment by smartbayaraa** [comment]
Okay. Thanks.

I am trying to reproduce it.

I configured log in patroni.yml file follows:

> log:
>   dir: /var/log/patroni
>   file_size: 30000000
>   file_num: 10
>   dateformat: '%Y-%m-%d %H:%M:%S'
>   loggers:
>     etcd.client: DEBUG
>     urllib3: DEBUG

and created /var/log/patroni directory with 777 (root:root).

But the log didn't come. Anything wrong?

Thanks

**Comment by CyberDem0n** [comment]
> But the log didn't come. Anything wrong?

you still don't give answers to all questions, specifically about postgres logs
