### ISSUE TITLE
2.0.1 point release?

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#1716]
There seem to have been a few bug fixes since 2.0.0, do you plan to issue a 2.0.1 relatively soon, or are more bug fixes pending? Or asked otherwise, is there some roadmap/milestone/todo list for 2.0.1?

**Comment by CyberDem0n** [comment]
My hope that @ants will implement the `master_start_timeout` for crash recovery and after that we can do a release.
BTW, have you seen https://github.com/zalando/patroni/pull/1696#issuecomment-692746126 ?

**Comment by mbanck** [comment]
Ah right, that was post-2.0.0 as well. I'll pick that patch it for the Debian package and test it.

**Comment by CyberDem0n** [comment]
Closed in https://github.com/zalando/patroni/pull/1722
