### ISSUE TITLE
libpq's sslpassword parameter support?

### ISSUE THREAD

**Issue by kostiantyn-nemchenko** [zalando/patroni#1719]
PostgreSQL 13 introduced a new connection parameter to unlock encrypted client certificate key files called [`sslpassword`](https://www.postgresql.org/docs/13/libpq-connect.html#LIBPQ-CONNECT-SSLPASSWORD). I'm not sure if it's excluded intentionally from all Postgres 13 related PRs? I would like to submit a PR on this if you don't have any objections.

**Comment by CyberDem0n** [comment]
Sure, please do.
You can take https://github.com/zalando/patroni/pull/1523/files as an example.
