### ISSUE TITLE
reinit new master from pg_basebackup

### ISSUE THREAD

**Issue by dbajunky** [zalando/patroni#1725]
Reviewed the resolution to this issue - "Make it possible to automatically reinit the former master #948" and its predecessor issue #942, however the steps to reinit a former master from a pgbasebackup is not included.  By using the new parameter "postgresql.remove_data_directory_on_diverged_timelines", will a new master be reinitiatialized from a pgbasebackup?

**Comment by CyberDem0n** [comment]
Please read the documentation: https://patroni.readthedocs.io/en/latest/
Also follow the tutorial https://github.com/patroni-training/2019
