### ISSUE TITLE
Possibility to specify minimum version of TLS for patroni

### ISSUE THREAD

**Issue by jprecuch** [zalando/patroni#1730]
**Describe the bug**
We are trying to setup patroni to use minimum TLS version to 1.2 for port 8008. However there is no option how we can fullfil this currently seems so. Is this somehow possible or planned in near future? 

**To Reproduce**
Port 8008 on patroni nodes are reporting as supporting TLS 1.0/1.1. based on documentation.
On this port we expose Patroni's HTTP API for use with the TCP LB's health check. This needs to be set to 1.2 minimum currently

**Expected behavior**
Possibility to specify TLS 1.2 as minimum version 

**Additional context**
Might be this line? 
https://github.com/zalando/patroni/blob/master/patroni/api.py#L636

**Comment by CyberDem0n** [comment]
Hi @jprecuch,

yes as a quick hack you can set `ctx.options`: https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLSv1_2
Of couse, It would be nice to have it configurable. If you wish, you can create a PR implementing it.

**Comment by CyberDem0n** [comment]
@jprecuch are you going to work on this? If not, I will close the issue, because it is not in the my priority list.

**Comment by jprecuch** [comment]
We are testing the fix for this internally. Once all tested we will hopefully commit it here so it is part of next version of patroni.

**Comment by CyberDem0n** [comment]
Hi @jprecuch, how tests are going?
It would be nice to see a PR open.

**Comment by CyberDem0n** [comment]
I think #1824 is partially (if not fully solves it).
