### ISSUE TITLE
initdb not possible when data_dir is a mounted file system

### ISSUE THREAD

**Issue by joernott** [zalando/patroni#1735]
**Describe the bug**
On larger postgresql instances, my customer puts various database related directories on lvm volumes which are then mounted to their respective places. The data _dir is usually one of them. This leads to patroni not running initdb on the first node in the cluster (as the data dir already exists). Postgres then ends up as malconfigured secondary node.

As we have automated our server provisioning and use puppet to automatically configure our servers, everything is set up automatically. In order to mount the volume into the data dir, the data dir has to exist though and in order to bootstrap the patroni/postgres cluster it has to be absent. 

**To Reproduce**
- Create an empty pg_data dir with mkdir
- Run patroni for the first time

**Expected behavior**
I would love to have a way to tell patroni to do the initdb stuff, even if the data dir is there but completely empty.

**Environment**
- Patroni version: 1.6.5
- PostgreSQL version: 9.6 (but also on 10 and 11)
- DCS (and its version): etcd 3.2.28

**Patroni configuration file**
not relevant, works fine when removing the directory

**patronictl show-config**
not relevant, works fine when removing the directory

**Have you checked Patroni logs?**
yes, that is how I found out about this problem

**Have you checked PostgreSQL logs?**
yes, that is how I found out about this problem

**Have you tried to use GitHub issue search?**
yes, didn't find one but found something somewhere else about not running initdb if there is already a directory

**Additional context**
As wa workaround, I can disable puppet, change the data_dir entry to some nonexistent path, start patroni once, then move the content to the real data dir, re-enable puppet and have puppet correct the patroni config and start patroni. I can automate that procedure but it is a horrible crutch.

**Comment by CyberDem0n** [comment]
Hi @joernott,

This is actually not a good practice. You can read on this topic in the postgres mailing list: https://www.postgresql.org/message-id/flat/CAKoxK%2B6H40imynM5P31bf0DnpN-5f5zeROjcaj6BKVAjxdEA9w%40mail.gmail.com

**Comment by joernott** [comment]
Hi @CyberDem0n 
Thanks for the link. The folder and mountpoint layout has been designed by my customers DBA team. Essentially, it looks to me, as if they have adapted a lot of their DB2 concepts to postgres. I will try to take that topic to them and I fear, that I will end up with /opt/companyname/pgsql/data/data instead of /opt/companyname/pgsql/data/data, while the backup and wal dirs (which are also separated end up in /opt/companyname/pgsql/backup and /opt/companyname/pgsql/wal.

It is worth noticing, that the "regular" initdb does not have a problem with the pre-existing data dir (I had to convince the puppet module not to run it, when setting up patroni).

**Comment by CyberDem0n** [comment]
When Patroni is trying to figure out whether the specific directory is empty and suitable for initdb (or pg_basebackup) it is doing the same check as initdb itself. I.e. if there is anything in the directory except lost+found or name starting with dot, it assumes that it is not empty. If you try to manually call initdb with such path, most likely it will complain and exit with an error.

**Comment by CyberDem0n** [comment]
> patroni sets up a secondary node even though there is no other primary node yet

That means the initialize key in DCS already exists (cluster with the same scope was already initialized once)

**Comment by joernott** [comment]
> That means the initialize key in DCS already exists

That is what I kept reading when googling for that problem. So I ensured that this is not the case by issuing a "etcdctl rm /service --recursive" just before starting patroni. The etcd cluster is healthy and does not contain any other data except my "testing" key used to validate the replication.

**Comment by CyberDem0n** [comment]
Without Patroni logs I can't tell anything more.

**Comment by joernott** [comment]
I ran a few more tests and I believe, I have located the issue outside of patroni:
- When using the puppetlabs::postgresql module, it detects the empty data folder and runs initdb, depending on your OS
- Depending on the package, the systemctl unit for postgresql contains a call to initdb

So I had to thell the postgresql module explicitly not to manage the service and not to run initdb by setting service_manage and needs_initdb explicitly to false.
