### ISSUE TITLE
Documentation about how to update patroni

### ISSUE THREAD

**Issue by jprecuch** [zalando/patroni#1738]
Hi,
I've tried to find some documentation how is the easiest and most secure way to update patroni (without upgrade of postgres) but couldn't find anyhing yet. Is there some available documentation for this? For example update from 1.6 to 2.0.1. 

Thanks

**Comment by CyberDem0n** [comment]
It is as simple as:
1. Install the new version
2. Restart patroni

Optionally you can enable maintenance mode by running `patronictl pause --wait` berore the restart. In this case don't forget to resume it after.

**Comment by jprecuch** [comment]
Thanks @CyberDem0n ..Thought it will be much harder.

**Comment by victor-sudakov** [comment]
> Optionally you can enable maintenance mode

@CyberDem0n Why optionally? If patroni is stopped for restart without enabling maintenance mode, is it not going to shutdown the postgres it is managing? I'm especially concerned about the leader.

**Comment by Tibingeo** [comment]
I installed Postgres using zalando helm chart, how we can upgrade patronictl in that ?
