### ISSUE TITLE
Unexpected exception raised please report it as a BUG

### ISSUE THREAD

**Issue by rootqa** [zalando/patroni#1740]
Hello,

CentOS Linux 7.8
Kernel 3.10 x86_64
Python v3
PIP v3
PostgreSQL 10

after updating CentOS i think python version was also updated and i upgrade to pip3 then i uninstalled the patroni and reinstalled patroni[etcd] but i get this error:

Oct 23 13:52:16 db2 patroni: 2020-10-23 13:52:16,247 INFO: Got response from pg01 http://10.0.0.1:8008/patroni: {"state": "running", "postmaster_start_time": "2020-10-23 13:51:44.671 +04", "role": "replica", "server_version": 100014, "cluster_unlocked": true, "xlog": {"received_location": 180841611472, "replayed_location": 180841611472, "replayed_timestamp": null, "paused": false}, "timeline": 13, "database_system_identifier": "6792123284981424270", "patroni": {"version": "2.0.1", "scope": "dcs"}}

Oct 23 13:52:16 db2 patroni: 2020-10-23 13:52:16,335 ERROR: Exception when changing replication slots
Oct 23 13:52:16 db2 patroni: Traceback (most recent call last):
Oct 23 13:52:16 db2 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1422, in _run_cycle
Oct 23 13:52:16 db2 patroni: return self.process_unhealthy_cluster()
Oct 23 13:52:16 db2 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 940, in process_unhealthy_cluster
Oct 23 13:52:16 db2 patroni: if self.acquire_lock():
Oct 23 13:52:16 db2 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 148, in acquire_lock
Oct 23 13:52:16 db2 patroni: self.set_leader_access_is_restricted(self.cluster.has_permanent_logical_slots(self.state_handler.name))
Oct 23 13:52:16 db2 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 527, in has_permanent_logical_slots
Oct 23 13:52:16 db2 patroni: slots = self.get_replication_slots(name, 'master').values()
Oct 23 13:52:16 db2 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 474, in get_replication_slots
Oct 23 13:52:16 db2 patroni: use_slots = self.config and self.config.data.get('postgresql', {}).get('use_slots', True)
Oct 23 13:52:16 db2 patroni: AttributeError: 'NoneType' object has no attribute 'get'
Oct 23 13:52:16 db2 patroni: During handling of the above exception, another exception occurred:
Oct 23 13:52:16 db2 patroni: Traceback (most recent call last):
Oct 23 13:52:16 db2 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/slots.py", line 47, in sync_replication_slots
Oct 23 13:52:16 db2 patroni: slots = cluster.get_replication_slots(self._postgresql.name, self._postgresql.role)
Oct 23 13:52:16 db2 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 474, in get_replication_slots
Oct 23 13:52:16 db2 patroni: use_slots = self.config and self.config.data.get('postgresql', {}).get('use_slots', True)
Oct 23 13:52:16 db2 patroni: AttributeError: 'NoneType' object has no attribute 'get'
Oct 23 13:52:16 db2 patroni: 2020-10-23 13:52:16,349 ERROR: Unexpected exception
Oct 23 13:52:16 db2 patroni: Traceback (most recent call last):
Oct 23 13:52:16 db2 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1452, in run_cycle
Oct 23 13:52:16 db2 patroni: info = self._run_cycle()
Oct 23 13:52:16 db2 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1422, in _run_cycle
Oct 23 13:52:16 db2 patroni: return self.process_unhealthy_cluster()
Oct 23 13:52:16 db2 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 940, in process_unhealthy_cluster
Oct 23 13:52:16 db2 patroni: if self.acquire_lock():
Oct 23 13:52:16 db2 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 148, in acquire_lock
Oct 23 13:52:16 db2 patroni: self.set_leader_access_is_restricted(self.cluster.has_permanent_logical_slots(self.state_handler.name))
Oct 23 13:52:16 db2 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 527, in has_permanent_logical_slots
Oct 23 13:52:16 db2 patroni: slots = self.get_replication_slots(name, 'master').values()
Oct 23 13:52:16 db2 patroni: File "/usr/local/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 474, in get_replication_slots
Oct 23 13:52:16 db2 patroni: use_slots = self.config and self.config.data.get('postgresql', {}).get('use_slots', True)
Oct 23 13:52:16 db2 patroni: AttributeError: 'NoneType' object has no attribute 'get'
Oct 23 13:52:16 db2 patroni: 2020-10-23 13:52:16,349 INFO: Unexpected exception raised, please report it as a BUG

What would you recommend me?

**Comment by CyberDem0n** [comment]
> What would you recommend me?

Please answer to all questions from the bug template

**Comment by rootqa** [comment]
> > What would you recommend me?
> 
> Please answer to all questions from the bug template

Sorry, i think browser based my fault i will attention next time.

My goal was to upgrade a fully CentOS based and working patroni + postgresql infrastructure.

first stop patroni:

$ systemctl stop patroni

second install new package:

$ yum install -y python3-pip pyOpenSSL python3-devel gcc
$ pip3 install --upgrade setuptools
$ pip3 install psycopg2-binary
$ pip3 install wheel

remove old patroni:

$ sudo pip uninstall patroni

and re-install patroni (pip3)

$ sudo pip3 install patroni[etcd]

I restarted Patroni and tried connect and postgresql worked but i kept getting these errors.
I completely turned off and on the Linux system.
I solved the problem now:

I get a database backup and deleted all files under /data/patroni folder and when i restarted patroni no get error and re-restore from backup.

**Comment by CyberDem0n** [comment]
@rootqa, when you open an issue it asks you to fill up the form with very specific questions:
```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment**
- Patroni version:
- PostgreSQL version:
- DCS (and its version):

**Patroni configuration file**

Please copy&paste your Patroni configuration file here


**patronictl show-config**

Please copy&paste the output of "patronictl show-config" command here


**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.


**Additional context**
Add any other context about the problem here.
```

Most of them are very important and helping me to identify the problem.
In your specific case `Patroni configuration file` and `patronictl show-config output` would have helped. But since you already solved it, now it is probably too late.

**Comment by rootqa** [comment]
Hello @CyberDem0n ,

I get now however i couldnt get a patronictl show-config output (i use etcd) but these error messages i get were already error message patroni generated (/var/log/messages).

I don't think PostgreSQL error and create logs but i looking "/data/patroni/log" and didnt see any errors.

I wrote PostgreSQL version at the top :) (PostgreSQL 10.14)
previous Python version: Python 2.7 (CentOS)
currently Python version is: 3.6 (CentOS)

And i'm absolutely sure about it: i didnt make any changes to the patroni.yaml file patroni worked with same config.
I think problem was related to a file /data/patroni/* and i'm sorry that no longer exists.

maybe first i got errors hints would understand for you:

first problem about slots.py and was giving an error about:

"get_replication_slots" 

and slots.py file was in a folder such as old python2.7/site-packages directory.
Currently seeing slots.py file under python3.6/site-packages directory now.

And we can still close this ticket because i was able to solve the problem and thanks for all help!
