### ISSUE TITLE
Change data dir

### ISSUE THREAD

**Issue by cihantunali** [zalando/patroni#1741]
Hi there,

I am using Patroni with 3 node cluster. After setup, my node's disks are getting full and i need to use external disk for it. I attached additional disk to each node and mount it with same name on each node. I need to change data folder from /var/lib/pgsql/patroni to /data/patroni. I tried from patroni configuration but nothing worked. I tried to copy data from old path to new one, it did not work either.

How can i change data directory? Thanks!

**Comment by CyberDem0n** [comment]
1. Stop patroni
2. Update postgresql.data_dir in patroni.yaml
3.  Copy data to new place
4. Start patroni

**Comment by cihantunali** [comment]
Thanks @CyberDem0n ! I forgot to change permission (written at status page "Permissions should be u=rwx (0700) or u=rwx,g=rx (0750)" ). After that, it succesfully worked.
