### ISSUE TITLE
Error " CRITICAL: system ID mismatch"

### ISSUE THREAD

**Issue by Mahe-alain** [zalando/patroni#1744]
Hi,

After a crash of my server, I recreated my postgresql database and restored but data.
When trying to start patroni I got the following error:

[postgres@mfle1548q ~]$ patroni /etc/patroni.yml
2020-10-30 16:10:57,462 INFO: Selected new etcd server http://10.66.40.178:2379
2020-10-30 16:10:57,475 INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-10-30 16:10:57,486 CRITICAL: system ID mismatch, node pgzabbix01 belongs to a different cluster: 6864843511243778900 != 6889429568915863164
2020-10-30 16:10:57,981 INFO: Lock owner: None; I am pgzabbix01
[postgres@mfle1548q ~]$ patronictl -d etcd://10.66.40.178:2379 list ZABBIX
+---------+------------+--------------+------+---------+----+-----------+
| Cluster |   Member   |     Host     | Role |  State  | TL | Lag in MB |
+---------+------------+--------------+------+---------+----+-----------+
|  ZABBIX | pgzabbix01 | 10.66.40.216 |      | stopped |    |   unknown |
+---------+------------+--------------+------+---------+----+-----------+
[postgres@mfle1548q ~]$  /usr/lib/postgresql/12/bin/pg_controldata -D /var/lib/postgresql/12/main | grep "Database system identifier"
-bash: /usr/lib/postgresql/12/bin/pg_controldata: No such file or directory
[postgres@mfle1548q ~]$ pg_controldata -D $PGDATA  | grep "Database system identifier"
Database system identifier:           6889429568915863164

**Environment**
- Patroni version: 1.6.0
- PostgreSQL version: 12.2 
- DCS (and its version):

**Patroni configuration file**
[postgres@mfle1548q ~]$ cat /etc/patroni.yml
scope: ZABBIX
name: pgzabbix01
patroni_log_dir: "/var/log/patroni/"
patroni_log_file_size: 100MB
patroni_log_file_num: 5

restapi:
    listen: 10.66.40.216:8008
    connect_address: 10.66.40.216:8008

etcd:
    host: 10.66.40.178:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.66.40.216/0 md5
    - host replication replicator 10.66.40.121/0 md5
    - host all all 0.0.0.0/0 md5

    users:
        postgres:
            password: Psql!0519
            options:
                - createrole
                - createdb

postgresql:
    listen: 10.66.40.216:5432
    connect_address: 10.66.40.216:5432
    data_dir: /pg_data/pgtezabor0
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: s0519HkprtZq!RSTe
        superuser:
            username: postgres
            password: Psql!0519
    parameters:
        unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
**patronictl show-config**
```

thanks for your help

**Comment by CyberDem0n** [comment]
Please use [search](https://github.com/zalando/patroni/issues?q=is%3Aissue+system+ID+mismatch+is%3Aclosed)

**Comment by Mahe-alain** [comment]
Hi,

No mistakes match mine.

Best regards

**Comment by sandeepkalra** [comment]
Hi @Mahe-alain ,
I have dealt with this issue for few days now and now I have a fix. In my case the issue was the init block 
```initdb:
- encoding: UTF8
- data-checksums
```
This must only be available when you are initializing the cluster. If the cluster is not getting initialized, then remove this from yaml file.

Hope this fixes the issue for you too.

**Comment by Mahe-alain** [comment]
Hi,

I deleted the cluster, and relaunched Patroni, it worked.

Best regards

Cordialement,
[cid:image001.jpg@01D6C95F.C71F9460]<http://www.generali.fr/?utm_source=emailing-prm-crm&utm_medium=signature-email&utm_campaign=signature-email&zanpid=signature-email>
Alain MAHE

amahe2@externe.generali.fr<mailto:amahe2@externe.generali.fr>
GSS\OCP (Operation Cross Platform)
Generali Infrastructure Services S.c.a.r.l.
Building WILO - Area W03 B3C142
11-17, Avenue François Mitterrand
93200 Saint Denis / France
T. +33 158 381 406
Website www.generali.com<http://www.generali.com/>


De : Sandeep Kalra <notifications@github.com>
Envoyé : mercredi 2 décembre 2020 16:32
À : zalando/patroni <patroni@noreply.github.com>
Cc : MAHE Alain <AMAHE2@externe.generali.fr>; Mention <mention@noreply.github.com>
Objet : Re: [zalando/patroni] Error " CRITICAL: system ID mismatch" (#1744)


Hi @Mahe-alain<https://github.com/Mahe-alain> ,
I have dealt with this issue for few days now and now I have a fix. In my case the issue was the init block

- encoding: UTF8

- data-checksums

This must only be available when you are initializing the cluster. If the cluster is not getting initialized, then remove this from yaml file.

Hope this fixes the issue for you too.

**Comment by sandeepkalra** [comment]
A reboot may still end you with same situation if the init block exists. I was hitting the point where a backup/restore/reboot cycle was randomly ending me with this situation (1 in 20 times).

**Comment by sandeepkalra** [comment]
@CyberDem0n 

I think there is a race-condition in code. I am seeing this on multi-host when repeated restore/restart cycles are performed. We restore fresh i.e. we remove PGDATA and starts as new.

A, B*, C are host (* is master). The init block is part of each yaml file because we use collate = 'c'  

Repeated restore/restart we see this mismatch error:
   1. on restore, we stop pg on each host machine, delete each db folder. 
   2. Then, Master starts first. Restores(pg_dump/psql -f) while others wait. 
   3. Master completes, and sets id in zookeeper.
   4. Other hosts starts (after removing everything). They have initdb in yaml, they start.. sometimes tries to create cluster 
   ends in error where local control data has id different that zookeer.

If i re-run without initdb on restore in yaml (i.e. collate = utf8), then everything works... and we never see mismatch id

Do replica A, C node need initdb block?

**Comment by CyberDem0n** [comment]
@sandeepkalra your issues are not related to the `bootstrap.initdb`.

When the new cluster is deployed, Patroni creates the initialize key in DCS. Only one node in the Patroni could grab the initialize lock and run initdb. In fact, only the `bootstrap` section affects the ability to perform a bootstrap, which is initdb by default.

If the initialize key already exists in DCS, Patroni will never run initdb or custom bootstrap. I.e. the bootstrap section is harmless.

The situation that the replica complains about system id missmatch could happen only in two cases:
1. Upon start init system of your OS notice that PGDATA is empty and runs initdb (for example pg_createcluster in Debian/Ubuntu).
2. Your Zookeeper cluster is broken. Different Patroni nodes connect to different Zookeeper nodes and see a different picture and more important they both succeed in creating the initialize ZNode. This is a very bad situation and such zookeeper cluster should not be use for Patroni.

You can easily distinguish between 1 and 2 by checking Patroni logs.

**Comment by sandeepkalra** [comment]
Thanks @CyberDem0n . I do have a very stable Zookeeper, so it is condition#1. 
I implemented a wait on replicas while leader is restoring. The code also checks if PGDATA exists then removes the initdb block from yaml.
