### ISSUE TITLE
Patroni Postgresql cluster with 2+2 PG members on 3 datacenters using sync+ asyncronous replication

### ISSUE THREAD

**Issue by viljohakala** [zalando/patroni#1745]
Hello,

Is it possible to have a following Patroni Postgresql cluster in two datacenters?

DC1:
- master PG -- synchronous replication --> standby  PG#1 in DC1
+1 etcd in DC1

DC2: --> async. replication --> standby PG#2 in DC2-->standby PG#3 in DC2
+1 etcd in DC2

DC3:
+1 etcd in DC3

Using standby_cluster = standby PG#2 should work?
and synchronous_standby_names = standby PG#1

Any caveats on using such an architecture? Should we use instead 3 PG nodes in DC1/DC2 ? But I believe only 
more than 2 standbys is possible ionly n PG13 with Patroni ?

Regards,
Viljo

**Comment by CyberDem0n** [comment]
You can get such configuration working by only specifying tags in config files: https://patroni.readthedocs.io/en/latest/SETTINGS.html#tags

**Comment by viljohakala** [comment]
Any caveats in such an architecture?

So If I read your comment rights, I should use:
in DC2 for PG#3
replicatefrom: The IP address/hostname of another replica. Used to support cascading replication... set to the master PG#1 in DC1
nosync: true or false. If set to true the node will never be selected as a synchronous replica.

How about standby_cluster parameter or syncronous_standby_names? Are these needed?

**Comment by CyberDem0n** [comment]
1. For the entire cluster you have to set synchronous_mode: on, it will take care about managing synchronous_standby_names
2. DC2: nosync: true
3. One of nodes in DC2 should set replicatefrom

**Comment by viljohakala** [comment]
Any caveats in such an architecture?

Alexander Kukushkin <notifications@github.com> kirjoitti 1.11.2020 kello 21.12:

﻿

  1.  For the entire cluster you have to set synchronous_mode: on, it will take care about managing synchronous_standby_names
  2.  DC2: nosync: true
  3.  One of nodes in DC2 should set replicatefrom

**Comment by CyberDem0n** [comment]
> Any caveats in such an architecture?

not that I know, but you better try it in some test environment first

**Comment by hseyindemir** [comment]
Hi @viljohakala,

You can use standby cluster that replicates from a primary patroni cluster. And these standby clusters will have a standby leader that can act as a primary if required.

By doing this, you do not have to use 1 consul/etcd for 3 DC. You can configure a different DCS for each datacenter. This will improve your availability. 

Regards.

PS: If you have any question feel free to ask

**Comment by viljohakala** [comment]
Hi,

With that failover is not automatic to DC2, as DC3 does not have etcd, and failover/switchover shoud be manual in promoting standby cluster to primary, am I right?

Hüseyin Demir <notifications@github.com> kirjoitti 14.11.2020 kello 20.50:

﻿

Hi @viljohakala<https://github.com/viljohakala>,

You can use standby cluster that replicates from a primary patroni cluster. And these standby clusters will have a standby leader that can act as a primary if required.

By doing this, you do not have to use 1 consul/etcd for 3 DC. You can configure a different DCS for each datacenter. This will improve your availability.

Regards.

PS: If you have any question feel free to ask

**Comment by hseyindemir** [comment]
Yes, it is not possible to automatic swtichover between two datacenters in this design. 

You have to do switchover/failover **when you have to change your primary datacenter.**
