### ISSUE TITLE
Question on using JDBC client based failover feature, instead of VIP with Patroni

### ISSUE THREAD

**Issue by viljohakala** [zalando/patroni#1750]
The PostgreSQL driver documentation states, that multiple hosts can be specified in the jdbc connection url:

jdbc:postgresql://host1:port1,host2:port2/database

Provided that I have master-standby postgresql replication setup using patroni, will JDBC client software be able to pickup connection only to the master database even after promoting standby to master after failover?

I don't want to use haproxy or vip with patroni.

**Comment by CyberDem0n** [comment]
> will JDBC client software be able to pickup connection only to the master database even after promoting standby to master after failover?

At least this is what JDBC documentation promise.
Have you tried it?

**Comment by mbanck** [comment]
> The PostgreSQL driver documentation states, that multiple hosts can be specified in the jdbc connection url:
> 
> jdbc:postgresql://host1:port1,host2:port2/database
> 
> Provided that I have master-standby postgresql replication setup using patroni, will JDBC client software be able to pickup connection only to the master database even after promoting standby to master after failover?

I think you need as additional connection option `targetServerType=primary` to make it pin to the primary, otherwise, it will just connect to each node and not care about primary or standby.
