### ISSUE TITLE
Base goes into reading mode.

### ISSUE THREAD

**Issue by timur1988** [zalando/patroni#1755]
Good afternoon!

the cartridge was no longer available within 2 minutes.

log etcd:
Nov 11 16:34:55 haproxy-etcd etcd[2044]: got unexpected response error (etcdserver: request timed out) [merged 1 repeated lines in 2s]
Nov 11 16:34:57 haproxy-etcd etcd[2044]: got unexpected response error (etcdserver: request timed out) [merged 1 repeated lines in 2s]
Nov 11 16:34:59 haproxy-etcd etcd[2044]: sync duration of 2m49.911614472s, expected less than 1s

log patroni:
Nov 11 07:07:52 patroni-postgres-node-1 patroni[97730]: 2020-11-11 07:07:52,755 ERROR: Request to server http://******:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'*****\', port=2379): Max retries exceeded with url: /v2/keys/db/postgres/members/postgresql0 (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'*****\', port=2379): Read timed out. (read timeout=3.3333333333333335)",))',)

Base goes into reading mode.
help me please.

**Comment by timur1988** [comment]
etcdctl version: 3.2.17
API version: 2
patronictl version 1.6.4

**Comment by CyberDem0n** [comment]
This is exactly how it is supposed to work. If etcd isn't accessible for writes Postgres cluster goes read-only.

**Comment by timur1988** [comment]
what can be done with etcd?


Nov 11 18:52:40 haproxy-etcd etcd[2044]: got unexpected response error (etcdserver: request timed out)
Nov 11 18:52:43 haproxy-etcd etcd[2044]: got unexpected response error (etcdserver: request timed out)
Nov 11 18:52:45 haproxy-etcd etcd[2044]: got unexpected response error (etcdserver: request timed out) [merged 1 repeated lines in 1.72s]
Nov 11 18:52:46 haproxy-etcd etcd[2044]: got unexpected response error (etcdserver: request timed out)
Nov 11 18:52:48 haproxy-etcd etcd[2044]: got unexpected response error (etcdserver: request timed out) [merged 1 repeated lines in 1.38s]

**Comment by timur1988** [comment]
config etcd:

**Comment by timur1988** [comment]
config etcd:

ETCD_LISTEN_PEER_URLS=http://****:2380,http://127.0.0.1:7001
ETCD_LISTEN_CLIENT_URLS=http://127.0.0.1:2379, http://*****:2379
ETCD_INITIAL_ADVERTISE_PEER_URLS=http://******:2380
ETCD_INITIAL_CLUSTER=etcd0=http://******:2380,
ETCD_ADVERTISE_CLIENT_URLS=http://******:2379
ETCD_INITIAL_CLUSTER_TOKEN=cluster
ETCD_INITIAL_CLUSTER_STATE=new

**Comment by CyberDem0n** [comment]
> what can be done?

1. Read documentation: https://etcd.io/docs/v2/clustering/
2. Ensure that time is synchronized across all etcd nodes

**Comment by timur1988** [comment]
etcd only one node, should synchronized time be with patroni?

**Comment by CyberDem0n** [comment]
Single etcd node is a SPoF!
You have to run at least three in the cluster.

**Comment by timur1988** [comment]
Well, at the moment to remake etcd before launching, I need to clear the directory:
/ var / lib / etcd / default / member
Initially, the cluster is not initialized.
After clearing the directory, I can add all etcd nodes to the etcd config.
Will there be a problem with the existing cluster if I clear the directory?

**Comment by timur1988** [comment]
etcd should be on separate nodes, right?

**Comment by CyberDem0n** [comment]
Etcd documentation has all answers
Also I am pretty sure there are a lot of tutorials in internet about setting up etcd cluster.
I don't really want to work as a proxy.

**Comment by timur1988** [comment]
good thank you very much

**Comment by vitabaks** [comment]
> etcd only one node

See an example of how to scale your etcd cluster (without downtime) :
https://github.com/zalando/patroni/issues/1269
