### ISSUE TITLE
postgresql HA cluster  using patroni

### ISSUE THREAD

**Issue by thcb3181** [zalando/patroni#1757]
HI ,i using patroni etcd haproxy build a pgsql cluster , but i sometime arise 
this message ， server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request

Where can I start the investigation ,thanks

**Comment by CyberDem0n** [comment]
> Where can I start the investigation ,thanks

like with any other software or tool - logs.

**Comment by thcb3181** [comment]
So there may be a problem with the toolkit? Would like to ask

**Comment by CyberDem0n** [comment]
> So there may be a problem with the toolkit? Would like to ask

The problem could be anywhere and you can't find the reason (and solution) without analyzing your setup, i.e. configs and logs of all kinds.
