### ISSUE TITLE
patroni connection session 

### ISSUE THREAD

**Issue by thcb3181** [zalando/patroni#1761]
Hello, I would like to ask, will the session be cleared after patroni connection to postgresql is disconnected? There are still parameters to set

**Comment by CyberDem0n** [comment]
I have no idea what you are talking about.

**Comment by thcb3181** [comment]
I use patroni to manage and connect to postgresql. What I want to know now is how long the session will be cleared when I disconnect.
Or is there any configuration about connection pool？

**Comment by CyberDem0n** [comment]
Patroni neither intercepts nor manages client connections. It is not managing your connection pool either.

The only Patroni does - manages Postgres to ensure that there is only one primary running in the cluster.
