### ISSUE TITLE
question on client HA

### ISSUE THREAD

**Issue by jacks33** [zalando/patroni#1762]
Hello,

is it safe to connect to a patroni cluster using postgres client HA (provided from postgreSQL 10):

example : 

psql "postgresql://firsthost:port,secondhost:port/dbname?target_session_attrs=read-write"

instead of using a http check (throught a load balancer).

thank you

Best Regards

**Comment by CyberDem0n** [comment]
It is safe as long as Patroni running on all hosts.
As a safety measure you can configure watchdog, so it will restart the host if Patroni on primary is not running.
