### ISSUE TITLE
failover happen pg log "received immediate shutdown request", no patroni log for 35 secs

### ISSUE THREAD

**Issue by yinan8128** [zalando/patroni#1765]
Hello

**Describe the bug**
patroni failover from 01 to 02
01 node no patroni log for 35 secs(Nov 16 12:03:21 to Nov 16 12:03:56, normal log every 10 secs), then log "Could not register service: unknown role type promoted"
01 node postgresql log: [2020-11-16 12:03:57.005 UTC] p=32103:14@ c=@/: LOG:  received immediate shutdown request

**Environment**
- Patroni version: 2.0.1
- PostgreSQL version: 11.4
- DCS (and its version): Consul

**Patroni configuration file**
scope: pgcluster11
name: s06y-patroni_cluster-6700

restapi:
  listen: 0.0.0.0:8008
  connect_address: :8008

consul:
  register_service: true
  host: 127.0.0.1:8500
  checks: []

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        archive_mode: "on"
        archive_command: /bin/true
        archive_timeout: 1800s
        autovacuum: "on"
        autovacuum_work_mem: 1GB
        autovacuum_vacuum_threshold: 50
        autovacuum_vacuum_cost_delay: 10ms
        autovacuum_vacuum_cost_limit: 8000
        autovacuum_vacuum_scale_factor: 0.01
        autovacuum_analyze_threshold: 50
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_max_workers: 6
        bgwriter_delay: 50ms
        bgwriter_lru_maxpages: 4000
        bgwriter_lru_multiplier: 4
        checkpoint_completion_target: 0.7
        checkpoint_timeout: 30min
        config_file: /var/lib/pgsql/11/data/postgresql.conf
        constraint_exclusion: partition
        datestyle: "ISO, MDY"
        default_statistics_target: 100
        default_text_search_config: "pg_catalog.english"
        effective_cache_size: "5952MB"
        hot_standby: "on"
        idle_in_transaction_session_timeout: 10min
        lc_messages: 'C'
        lc_monetary: 'C'
        lc_numeric: 'C'
        lc_time: 'C'
        lock_timeout: 30s
        log_autovacuum_min_duration: 500
        log_checkpoints: "off"
        log_connections: "off"
        log_destination: "stderr"
        log_directory: "/var/log/postgresql"
        log_disconnections: "off"
        log_duration: "off"
        log_filename: 'postgresql.log'
        log_line_prefix: '[%m] p=%p:%l@%v c=%u@%h/%d:%a '
        log_lock_waits: "on"
        log_min_duration_statement: "5s"
        log_rotation_age: 0
        log_rotation_size: 0
        log_statement: "ddl"
        log_temp_files: 1MB
        log_timezone: "UTC"
        log_truncate_on_rotation: "off"
        logging_collector: "on"
        maintenance_work_mem: 2GB
        max_connections: 1000
        max_replication_slots: 10
        max_wal_senders: 10
        max_wal_size: "7936"
        min_wal_size: 1024
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        shared_buffers: 1984MB
        shared_preload_libraries: 'pg_stat_statements,pg_stat_kcache'
        statement_timeout: 10min
        temp_file_limit: 1GB
        timezone: "UTC"
        track_io_timing: "on"
        unix_socket_directories: '/var/run/postgresql'
        wal_buffers: -1
        wal_compression: "on"
        wal_keep_segments: "10"
        wal_level: replica
        wal_log_hints: "on"
        work_mem: "3MB"
      recovery_conf:
        restore_command: /bin/true
  initdb:
    - encoding: UTF8
    - data-checksums
    - locale: en_US.UTF-8
    - lc-collate: en_US.UTF-8
    - lc-ctype: en_US.UTF-8

  users:
    replicator:
      password: 
      options:
        - replication

postgresql:
  listen: '*'
  connect_address: :5432
  data_dir: /var/lib/pgsql/11/data
  bin_dir: /usr/pgsql-11/bin
  config_dir: /var/lib/pgsql/11/data
  hba_file: /var/lib/pgsql/11/data/pg_hba.conf
  restore: /usr/bin/patroni_wale_restore
  pgpass: /tmp/pgpass
  authentication:
    pg_rewind:
      username: postgres
      password: 
    replication:
      username: replicator
      password: 
      network: 0.0.0.0/0
    superuser:
      username: postgres
      password: 
  callbacks:
    on_start: /etc/patroni/callback.sh
    on_stop: /etc/patroni/callback.sh
    on_role_change: /etc/patroni/callback.sh
  basebackup:
    - verbose
    - checkpoint: 'fast'

watchdog:
  mode: off

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

log:
    format: '{"time": "%(asctime)s", "name": "%(name)s", "process": %(process)d, "thread": %(thread)d, "level": "%(levelname)s", "message": "%(message)s"}'

**Have you checked Patroni logs?**
Nov 16 12:02:51 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:02:51,341", "name": "patroni.ha", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "Lock owner: eu4-baas-patroni-cluster-vm01; I am eu4-baas-patroni-cluster-vm01"}
Nov 16 12:02:51 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:02:51,393", "name": "patroni", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "no action.  i am the leader with the lock"}
Nov 16 12:03:01 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:01,334", "name": "patroni.ha", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "Lock owner: eu4-baas-patroni-cluster-vm01; I am eu4-baas-patroni-cluster-vm01"}
Nov 16 12:03:01 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:01,374", "name": "patroni", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "no action.  i am the leader with the lock"}
Nov 16 12:03:11 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:11,334", "name": "patroni.ha", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "Lock owner: eu4-baas-patroni-cluster-vm01; I am eu4-baas-patroni-cluster-vm01"}
Nov 16 12:03:11 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:11,367", "name": "patroni", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "no action.  i am the leader with the lock"}
Nov 16 12:03:21 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:21,347", "name": "patroni.ha", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "Lock owner: eu4-baas-patroni-cluster-vm01; I am eu4-baas-patroni-cluster-vm01"}
Nov 16 12:03:21 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:21,457", "name": "patroni", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "no action.  i am the leader with the lock"}
Nov 16 12:03:56 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:56,922", "name": "patroni.dcs.consul", "process": 32085, "thread": 140350381303616, "level": "WARNING", "message": "Could not register service: unknown role type promoted"}
Nov 16 12:03:56 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:56,923", "name": "patroni.ha", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "Lock owner: eu4-baas-patroni-cluster-vm02; I am eu4-baas-patroni-cluster-vm01"}
Nov 16 12:03:56 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:56,923", "name": "patroni.ha", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "does not have lock"}
Nov 16 12:03:59 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:59,158", "name": "patroni.dcs.consul", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "Deregister service pgcluster11/eu4-baas-patroni-cluster-vm01"}
Nov 16 12:03:59 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:59,180", "name": "patroni", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "demoting self because i do not have the lock and i was a leader"}
Nov 16 12:03:59 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:59,181", "name": "patroni", "process": 32085, "thread": 140350381303616, "level": "WARNING", "message": "Loop time exceeded, rescheduling immediately."}
Nov 16 12:03:59 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:59,184", "name": "patroni.ha", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "Lock owner: eu4-baas-patroni-cluster-vm02; I am eu4-baas-patroni-cluster-vm01"}
Nov 16 12:03:59 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:59,185", "name": "patroni", "process": 32085, "thread": 140350381303616, "level": "INFO", "message": "starting after demotion in progress"}
Nov 16 12:03:59 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:59,186", "name": "patroni.postgresql.connection", "process": 32085, "thread": 140349984724736, "level": "INFO", "message": "closed patroni connection to the postgresql cluster"}
Nov 16 12:03:59 eu4-baas-patroni-cluster-vm01 patroni[32085]: {"time": "2020-11-16 12:03:59,668", "name": "patroni.postgresql.postmaster", "process": 32085, "thread": 140349984724736, "level": "INFO", "message": "postmaster pid=31495"}
Nov 16 12:03:59 eu4-baas-patroni-cluster-vm01 patroni[32085]: localhost:5432 - no response

**Have you checked PostgreSQL logs?**
[2020-11-16 12:03:56.592 UTC] p=31485:3@ c=pgwatch2@127.0.0.1/eu4_baas_bckp_epmgr:pgwatch2 LOG:  disconnection: session time: 0:00:00.037 user=pgwatch2 database=eu4_baas_bckp_epmgr host=127.0.0.1 port=36916
[2020-11-16 12:03:57.005 UTC] p=32103:14@ c=@/: LOG:  received immediate shutdown request
[2020-11-16 12:03:57.017 UTC] p=31189:3@314/0 c=atp_si_user@10.253.85.203/eu4_baas_software_inventory:[unknown] WARNING:  terminating connection because of crash of another server process
[2020-11-16 12:03:57.017 UTC] p=31189:4@314/0 c=atp_si_user@10.253.85.203/eu4_baas_software_inventory:[unknown] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
[2020-11-16 12:03:57.017 UTC] p=31189:5@314/0 c=atp_si_user@10.253.85.203/eu4_baas_software_inventory:[unknown] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
[2020-11-16 12:03:57.017 UTC] p=31183:3@313/0 c=atp_pm@10.253.86.62/eu4_baas_atp_pm:[unknown] WARNING:  terminating connection because of crash of another server process
[2020-11-16 12:03:57.017 UTC] p=31183:4@313/0 c=atp_pm@10.253.86.62/eu4_baas_atp_pm:[unknown] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
[2020-11-16 12:03:57.017 UTC] p=31183:5@313/0 c=atp_pm@10.253.86.62/eu4_baas_atp_pm:[unknown] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
[2020-11-16 12:03:57.017 UTC] p=31182:3@310/281059 c=bckp_epmgr@10.253.85.202/eu4_baas_bckp_epmgr:[unknown] WARNING:  terminating connection because of crash of another server process
[2020-11-16 12:03:57.017 UTC] p=31182:4@310/281059 c=bckp_epmgr@10.253.85.202/eu4_baas_bckp_epmgr:[unknown] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
[2020-11-16 12:03:57.017 UTC] p=31182:5@310/281059 c=bckp_epmgr@10.253.85.202/eu4_baas_bckp_epmgr:[unknown] HINT:  In a moment you should be able to reconnect to the database and repeat your command.

**Additional context**
Please help check, thanks

**Comment by CyberDem0n** [comment]
It seems your system is under so much stress that there was no resources for Patroni to execute HA loop for 35 seconds.
This interval exceeds ttl=30s, therefore the leader key expired, Patroni noticed it and demoted Postgres.

You need to figure out what is going on with your system, and what is the reason for cpu/memory pressure. Ideally fix these issues.

Another option could be increasing the `ttl` and `retry_timeout`. That would increase the failover time, but make your setup more reliable to such problems.

Parameters must be chaged via `patronictl edit-config` and you must follow the rule:
```
loop_wait + 2*retry_timeot <= ttl`
```

For example: ttl=90, loop_wait=10, retry_timeout=40.

**Comment by yinan8128** [comment]
Grafana shows that CPU load max is 8, as 16 cores, so means CPU load is around 50%, not under stress

Is it possible any other root caused?

**Comment by CyberDem0n** [comment]
> Is it possible any other root caused?

Memory pressure.

**Comment by yinan8128** [comment]
Thank you for your reply

Grafana shows Memory usage:
Cached: 20.32GB
Used:       4.12GB
Free:         672MB

**Comment by CyberDem0n** [comment]
Is it running a container?

**Comment by yinan8128** [comment]
Running in VM

**Comment by CyberDem0n** [comment]
Well, this is something for you to figure out. I don't have other ideas.

We have had quite similar issues (Patroni stuck for 30s+) in containers due to high amount of dirty buffers caused by high transaction rate and solved them by `limiting vm.dirty_background_bytes` and `vm.dirty_bytes`.

**Comment by yinan8128** [comment]
Thank you

What 's the limitation rule for ```vm.dirty_background_bytes``` and ```vm.dirty_bytes``` in Centos 7 container if CPU core 16, memory 24GB? 

Known this maybe will help us to check the problem our vm env, thanks

**Comment by CyberDem0n** [comment]
We use very conservative values:`vm.dirty_background_bytes=67108864` and `vm.dirty_bytes=134217728`.

By default dirty buffers are limited not in bytes, but as percents of available memory:
vm.dirty_background_ratio = 10
vm.dirty_ratio = 20

The issue is that this limit is configured per host. If your host has 64GB of RAM, but the container is allowed to use for example only 2GB, we get a situation that the container is allowed to generate up to 12GB of dirty buffers, which of course doesn't fit into the 2GB limit.  It makes memory pressure on all processes in the container, eventually paging out Patroni process.

In your case (in the VM) it is not necessarily causing the problem, but, usually monitoring tools collecting metrics not often than once per minute. If there is a sudden spike of memory usage for a few seconds, usually it is not possible to see it on the graph.

**Comment by gsmol** [comment]
Hello, @CyberDem0n!
> We have had quite similar issues (Patroni stuck for 30s+) in containers due to high amount of dirty buffers
>
Can you please elaborate a bit more on this case?
How the high amount of dirty buffers affected the patroni,  AFAIK patroni do not allocate large amount of memory on regular basis.

**Comment by CyberDem0n** [comment]
@gsmol every python module or library used by Patroni are loaded into the memory.
Under high memory pressure OS might decide to page out the memory occupied by these libraries. When the Patroni next time is trying to access some library function, the OS will have to read the library from a disk. But, since the memory is occupied by dirty buffers, before we can read something from disk OS needs to free up some memory by flushing dirty pages.

**Comment by gsmol** [comment]
I`m well aware of how paging is working, but executables and library modules usually are quite small and usually are always loaded in memory. Did you happens to observe the stack-trace of loader, trying to load library in memory, and been stack in memory reclaim?

**Comment by CyberDem0n** [comment]
The environment where we run is quite strict and there are not so many tools available except procps&co.
During the normal run we see something like RES=39MB and SHR=15MB for Patroni process in the top.
At times when Patroni was "hanging" the `RES` and `SHR` values were going down nearly to 0.

Also, I was looking at minflt and majflt counters from /proc/$pid/stat, and they were growing, while normally majflt is 0.
From `man procfs`:
```
       /proc/[pid]/stat
              Status information about the process.  This is used by ps(1).
  It is defined in the kernel source file fs/proc/array.c.

...
              (12) majflt  %lu
                        The number of major faults the process has made which have
 required loading a memory page from disk.
```
