### ISSUE TITLE
Primary demoted after concurrent update

### ISSUE THREAD

**Issue by le-duane** [zalando/patroni#1767]
**Describe the bug**
Primary demoted after only 1 concurrent update

**To Reproduce**
I'm not sure - in my testing, the leader lock update was retried after concurrent updates were encountered. It is possible something else was going on in this case which did not show up in Patroni or API logs; some other Patroni instances reported timeout errors around the same time.

```
2020-11-16 13:35:19,571 ERROR: Request to server https://172.20.0.1:443 failed: ReadTimeoutError("HTTPSConnectionPool(host='172.20.0.1', port=443): Read timed out. (read timeout=12.409012882038951)",)
``` 

We use managed Kubernetes (EKS) so there is not a lot of visibility as to what happened to the API server to cause the timeout.

**Expected behavior**
Patroni to retry after 409 response from API server. Patroni does not demote before retry_timeout expires

**Environment**
- Patroni version: 2.0.0
- PostgreSQL version: 11.9
- DCS (and its version): Kubernetes 14.9

**patronictl show-config**
```
loop_wait: 10
master_start_timeout: 300
master_stop_timeout: 135
maximum_lag_on_failover: 0
postgresql:
  parameters:
    max_connections: 100
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 8
    track_commit_timestamp: 'off'
    wal_keep_segments: 64
    wal_level: logical
    wal_log_hints: 'off'
  use_pg_rewind: false
  use_slots: false
retry_timeout: 90
synchronous_mode: true
ttl: 200
```

**Have you checked Patroni logs?**
```
2020-11-16 13:34:52,439 INFO: no action.  i am the leader with the lock
2020-11-16 13:35:02,386 INFO: Lock owner: connections-profile-gato-clr-c-0; I am connections-profile-gato-clr-c-0
2020-11-16 13:35:02,440 WARNING: Concurrent update of connections-profile-gato-clr
2020-11-16 13:35:03,441 ERROR: failed to update leader lock
2020-11-16 13:35:03.442 UTC [3481] LOG:  received immediate shutdown request
2020-11-16 13:35:03.444 UTC [20085] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
...
2020-11-16 13:35:03.460 UTC [3481] LOG:  database system is shut down
2020-11-16 13:35:03,528 INFO: demoted self because failed to update leader lock in DCS
...
2020-11-16 13:35:04,785 INFO: Lock owner: connections-profile-gato-clr-c-0; I am connections-profile-gato-clr-c-0
2020-11-16 13:35:04,839 WARNING: Concurrent update of connections-profile-gato-clr
2020-11-16 13:35:05,840 ERROR: failed to update leader lock
2020-11-16 13:35:05,896 INFO: not promoting because failed to update leader lock in DCS
2020-11-16 13:35:15,285 INFO: Lock owner: connections-profile-gato-clr-c-0; I am connections-profile-gato-clr-c-0
2020-11-16 13:35:15,335 WARNING: Concurrent update of connections-profile-gato-clr
```

**Additional context**
API Audit Logs
```
2020-11-16T13:34:52.667-07:00 | 200 | patch  | Patroni/2.0.0 Python/3.5.3 Linux
2020-11-16T13:35:01.962-07:00 | 200 | update | kube-controller-manager/v1.14.9
2020-11-16T13:35:02.467-07:00 | 409 | patch  | Patroni/2.0.0 Python/3.5.3 Linux
# patroni demotes here after one 409 response
2020-11-16T13:35:04.964-07:00 | 409 | patch  | Patroni/2.0.0 Python/3.5.3 Linux
2020-11-16T13:35:05.965-07:00 | 200 | update | kube-controller-manager/v1.14.9
2020-11-16T13:35:15.470-07:00 | 409 | patch  | Patroni/2.0.0 Python/3.5.3 Linux
2020-11-16T13:35:16.471-07:00 | 200 | patch  | Patroni/2.0.0 Python/3.5.3 Linux
```

**Comment by CyberDem0n** [comment]
> Expected behavior
Patroni to retry after 409 response from API server. Patroni does not demote before retry_timeout expires

That's a tricky topic. The 409 is a non-retriable status code.

Let me explain how it works.
* First of all, Patroni fetches via K8s API all objects associated with the cluster and stores them in the internal cache.
* Second, Patroni is using the `resource_version` from the first response and does a WATCH request to asynchronously receive updates of these objects. Every received event also updates the internal cache.
* Third - when Patroni is updating some objects via K8s API and there is a risk of the concurrent update, it always uses `resource_version` in such requests. The update usually returns the new version of the object and Patroni also stores it into the internal cache.

Update of the leader object is already an exceptional case and actually Patroni could retry it when it knows that this specific pod is still the owner of the leader lock:
https://github.com/zalando/patroni/blob/4dd902fbf13ea9be81b652e28e1e84725cb6779d/patroni/dcs/kubernetes.py#L896-L919

The idea is simple:
If an update failed with code 409, wait for 1 second (give time to receive en event via WATCH channel), double-check that we are still owning the leader lock and that the `resource_version` of the leader object in the internal cache is changed. Retrying update with the same `resource_version` _doesn't make sense, because it would fail_.

Apparently, in your case,  there were not events received with the new version of the leader object via WATCH channel (after 1 second), therefore Patroni gave up.

Now I think that maybe instead of waiting for 1 second (events in the WATCH channel) we could explicitly perform the `read_namespaced_endpoints()`. It could help in a situation like you have.

**Comment by le-duane** [comment]
Thank you very much for explaining that in detail to me @CyberDem0n 

To add more context to the situation, I'm guessing from the logs, that there was an issue with etcd which caused the controller manager and scheduler to fail at renewing their lease.

```
20:34:53.881464 1 leaderelection.go:263] failed to renew lease kube-system/kube-controller-manager: failed to tryAcquireOrRenew context deadline exceeded
20:34:53.878825 1 leaderelection.go:263] failed to renew lease kube-system/kube-scheduler: failed to tryAcquireOrRenew context deadline exceeded
```

It seems that when the controller manager restarts or promotes itself, it updates the resource version for all the endpoints, as I see lots of 409 errors when that happens.

Also, the API Server was having issues for almost a minute.

```
20:34:25.239403 1 log.go:172] http: TLS handshake error from x.x.20.166:19024: EOF
20:34:29.350926 1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
...
20:34:42.764097 1 log.go:172] http2: server: error reading preface from client x.x.3.180:39190: read tcp x.x.4.60:443->x.x.3.180:39190: read: connection reset by peer
...
E1116 20:35:19.571559 1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
```

What are the ramifications of read_namespaced_endpoints() failing if the cluster is still in a bad state when it is called? My concern being that if it were to fail, then the primary would demote itself before retry_timeout is reached. We've had to increase this parameter substantially due to unanticipated instability in the EKS control plane. We are hoping to reduce it after fully testing and implementing the bypass of the API service.

Would it be possible or would there be any value in resetting the state to where Patroni is trying to pull the DCS information instead of push when the 1 second timeout is reached?

**Comment by CyberDem0n** [comment]
> To add more context to the situation, I'm guessing from the logs, that there was an issue with etcd which caused the controller manager and scheduler to fail at renewing their lease.
20:34:53.881464 1 leaderelection.go:263] failed to renew lease kube-system/kube-controller-manager: failed to tryAcquireOrRenew context deadline exceeded
20:34:53.878825 1 leaderelection.go:263] failed to renew lease kube-system/kube-scheduler: failed to tryAcquireOrRenew context deadline exceeded

It seems that they experience exactly the same problem as Patroni. I.e. leaderelection.go is also using endpoints or configmaps for leader election, and the update seems to fail.

> It seems that when the controller manager restarts or promotes itself, it updates the resource version for all the endpoints, as I see lots of 409 errors when that happens.

It would be good to verify that the controller manager updates all endpoints. Do you have a label selector on the leader service?

> What are the ramifications of read_namespaced_endpoints() failing if the cluster is still in a bad state when it is called? My concern being that if it were to fail, then the primary would demote itself before retry_timeout is reached.

We can retry `read_namespaced_endpoints()` call with the usual policy and exponential back-off. In case if read_namespaced_endpoints() didn't fail, but the consecutive `patch_namespaced_endpoints()` got the 409, I don't see a point in doing further retries.

> Would it be possible or would there be any value in resetting the state to where Patroni is trying to pull the endpoint* information instead of push when the 1 second timeout is reached?

I don't really understand what do you mean. My idea is: if PATCH endpoint failed with code 409, immediately (without waiting 1 second) call GET endpoint, and if the lock is still owned by the current pod repeat the PATCH, but with the different resource_version.

**Comment by le-duane** [comment]
Thanks for your response @CyberDem0n 

> It would be good to verify that the controller manager updates all endpoints. Do you have a label selector on the leader service?

Yes! Although I did not realize it until I checked the live values. We use the "commonLabels" feature in Kustomize to apply labels to multiple objects. It is also adding these labels to the selector for us. Do you see any negative consequences of that beyond the issue we're facing in this thread?

> I don't really understand what do you mean. My idea is: if PATCH endpoint failed with code 409, immediately (without waiting 1 second) call GET endpoint, and if the lock is still owned by the current pod repeat the PATCH, but with the different resource_version. 

I was thinking by kicking Patroni into the normal workflow where it's trying to retrieve DCS values, it would be pulling the latest resource version and have known retry logic already in case components in the control plane are still unresponsive.  No worries if my thinking here is completely flawed though :)

**Comment by CyberDem0n** [comment]
@le-duane, do you have a possibility to test it: https://github.com/zalando/patroni/pull/1796?

**Comment by le-duane** [comment]
@CyberDem0n yes I will test in our dev environment and get back to you. Thanks!
