### ISSUE TITLE
Need help on Enabling SSL for Postgres using patroni

### ISSUE THREAD

**Issue by navaneswarareddy** [zalando/patroni#1768]

**Comment by CyberDem0n** [comment]
It is not different from enabling SSL for PostgreSQL.

**Comment by navaneswarareddy** [comment]
https://github.com/zalando/patroni Followed github account but not unable to setup SSL

**Comment by navaneswarareddy** [comment]
What is root user password for this docker container ?
postgres@patroni3:~/data$ sudo su -
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:
    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.
[sudo] password for postgres:
sudo: PAM authentication error: Module is unknown
