### ISSUE TITLE
Etcd migration from v2 to v3

### ISSUE THREAD

**Issue by mneirynck** [zalando/patroni#1769]
Hi,
We have a current patroni cluster running with etcd v2, but would like to migrate to start using etcd v3.
What would be the process for this? Etcd is already on 3.3, and can upgrade to 3.4.

Do we need to completely rebuild the patroni cluster? Or can we just migrate the keys and specify the etcd v3 endpoint in patroni config?

Is there a step by step guide somewhere?

**Comment by CyberDem0n** [comment]
Have you already tested etcd v3 support in Patroni?

**Comment by mneirynck** [comment]
No, I have not.
But it's nowhere stated as unsupported, so I suspect it's working as intended?

**Comment by CyberDem0n** [comment]
In the release notes it is marked as beta, therefore I would recommend to give it a spin on test systems before going to production.

The "upgrade" path is straightforward:
1. patronictl pause --wait
2. Update all patroni config files
3. Restart Patroni on all nodes
4. patronictl resume

**Comment by williamchanrico** [comment]
Hi @mneirynck, noticed your Issue while creating #1771 where `patroni --validate-config /etc/patroni/patroni.yml` returns error on a valid `etcd3` config. Waiting for confirmation.

Just want to let you know in case you bump into the same issue in your migration to v3 (especially your existing script which already works on v2)

**Comment by mneirynck** [comment]
I'll wait for at least a stable release on etcd v3 before taking it into production.
Thanks for the info, closing this ticket.

**Comment by CyberDem0n** [comment]
> I'll wait for at least a stable release on etcd v3 before taking it into production.

Well, if nobody is testing it there will be no stable release.

**Comment by mneirynck** [comment]
> > I'll wait for at least a stable release on etcd v3 before taking it into production.
> 
> Well, if nobody is testing it there will be no stable release.

Not saying I don't want to test, but I won't take into production as long as it's not stable.
When I have more time I can invest it in testing this, but it's not a crucial upgrade at the moment.
