### ISSUE TITLE
Question: consul checks configuration example

### ISSUE THREAD

**Issue by ponvenkates** [zalando/patroni#1772]
Hi Team,
I have a three node setup with Patroni 1.6.5. Often, when PG is restarted it's stuck at "database is shutting down.." state, I am aware that this is not a patroni issue and Patroni doesn't allow force shutdown of PostgreSQL unless it's configured in Sync mode. 
As a counter measure, I am trying to add a consul script health check to monitor the health of Postgres. In patroni configuration, I configured consul checks as below, but I am getting an error which I am not able to interpret, it would be helpful if you could provide an example on how to configure additional consul checks.
Configuration:
`
consul:
  checks: ["{"id": "pg-health", "name": "postgres-health", "args": "["pg_isready", "-h", "localhost"]"}"]
`

Error Message:
`2020-12-01 08:41:53.253 GMT [170] ERROR: refresh_session
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/patroni/dcs/consul.py", line 293, in refresh_session
    return self.retry(self._do_refresh_session)
  File "/usr/local/lib/python3.7/dist-packages/patroni/dcs/consul.py", line 231, in retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/patroni/utils.py", line 330, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/patroni/dcs/consul.py", line 282, in _do_refresh_session
    lock_delay=0.001, behavior='delete')
  File "/usr/lib/python3/dist-packages/consul/base.py", line 1668, in create
    data=data)
  File "/usr/local/lib/python3.7/dist-packages/patroni/dcs/consul.py", line 117, in wrapper
    return callback(self.response(self.http.request(method.upper(), self.uri(path, params), **kwargs)))
  File "/usr/lib/python3/dist-packages/consul/base.py", line 202, in cb
    CB.__status(response, allow_404=allow_404)
  File "/usr/lib/python3/dist-packages/consul/base.py", line 161, in __status
    raise BadRequest('%d %s' % (response.code, response.body))
consul.base.BadRequest: 400 Request decode failed: json: cannot unmarshal object into Go struct field .Checks of type types.CheckID`

Thanks,
Pon Venkatesh M

**Comment by CyberDem0n** [comment]
Patroni doesn't provide an interface for creating checks in Consul.
The `consul.checks` parameter only allows specifying list of defined checks by their ID when the [session is created](https://www.consul.io/api-docs/session#create-session).

You can read about creating checks [here](https://www.consul.io/api-docs/agent/check).

**Comment by oxycash** [comment]
> Patroni doesn't provide an interface for creating checks in Consul. The `consul.checks` parameter only allows specifying list of defined checks by their ID when the [session is created](https://www.consul.io/api-docs/session#create-session).
> 
> You can read about creating checks [here](https://www.consul.io/api-docs/agent/check).

Does this still hold true? `consul.checks` doesnt create a health check? We need to create one manually at consul and sepcify the Id?

I am trying this and failing. What should be the format, if consul.checks allows creation of a health check.

```
consul:
  host: 127.0.0.1:8500
  checks: [{"Args": ["systemctl", "status", "pgbouncer"], "Interval": "5s"}]
  register_service: true
```

**Comment by CyberDem0n** [comment]
Yep, nothing is changed in this area, and likely will not change.
Regarding your "check" do you really want the primary to be demoted if pgbouncer isn't running?

**Comment by oxycash** [comment]
That is our thought. Why shouldnt we, if our app is using the pgbouncer port?

**Comment by CyberDem0n** [comment]
If checks are failing all sessions created via this Consul agent are invalidated -> leader key is removed -> postgres is demoted
