### ISSUE TITLE
patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: consul, etcd, etcd3, kubernetes'

### ISSUE THREAD

**Issue by maxlinux1** [zalando/patroni#1775]
patroni /etc/patroni.yml 
2020-12-03 23:14:11,263 INFO: Failed to import patroni.dcs.exhibitor
2020-12-03 23:14:11,266 INFO: Failed to import patroni.dcs.raft
2020-12-03 23:14:11,267 INFO: Failed to import patroni.dcs.zookeeper
Traceback (most recent call last):
  File "/usr/bin/patroni", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/lib/python2.7/site-packages/patroni/daemon.py", line 98, in abstract_main
    controller = cls(config)
  File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 29, in __init__
    self.dcs = get_dcs(self.config)
  File "/usr/lib/python2.7/site-packages/patroni/dcs/__init__.py", line 106, in get_dcs
    Available implementations: """ + ', '.join(sorted(set(available_implementations))))
patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: consul, etcd, etcd3, kubernetes'
[root@host192 opt]# patroni --version
patroni 2.0.1

**Comment by CyberDem0n** [comment]
Either something is wrong with the config (which you didn't show, despite the issue checklist), or you didn't installed kazoo or pysyncobj module.

Last, but not least, python 2.7 is deprecated since 01.01.2020

**Comment by redelephant2020** [comment]
> Either something is wrong with the config (which you didn't show, despite the issue checklist), or you didn't installed kazoo or pysyncobj module.
> 
> Last, but not least, python 2.7 is deprecated since 01.01.2020

Hi ，i get same error like this:

2021-01-05 13:15:11,134 INFO: Failed to import patroni.dcs.consul
2021-01-05 13:15:11,139 INFO: Failed to import patroni.dcs.etcd
2021-01-05 13:15:11,142 INFO: Failed to import patroni.dcs.etcd3
2021-01-05 13:15:11,149 INFO: Failed to import patroni.dcs.exhibitor
2021-01-05 13:15:11,162 INFO: Failed to import patroni.dcs.zookeeper
Traceback (most recent call last):
  File "patroni.py", line 6, in <module>
    main()
  File "/home/kingbase/patroni/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/home/kingbase/patroni/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/home/kingbase/patroni/patroni/daemon.py", line 98, in abstract_main
    controller = cls(config)
  File "/home/kingbase/patroni/patroni/__init__.py", line 29, in __init__
    self.dcs = get_dcs(self.config)
  File "/home/kingbase/patroni/patroni/dcs/__init__.py", line 107, in get_dcs
    Available implementations: """ + ', '.join(sorted(set(available_implementations))))
patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: kubernetes, raft'



My enviroment like this：

Python 3.6
pip3 20.3.3

I use this command "python patroni.py standby.yml" and add this node in a cluster as standby cluster.

My config like this:

scope: postgresql1
namespace: /service/
name: pgsql10_node1

restapi:
    listen: 192.168.137.105:8008
    connect_address: 192.168.137.105:8008

etcd:
    host: 192.168.137.101:2379

bootstrap:
    dcs:
        standby_cluster:
            host: 192.168.137.101
            port: 5432
            create_replica_methods:
            - basebackup

    initdb:
    - encoding: UTF8
    - data-checksums
    pg_hba:
    - host replication postgres 192.168.137.0/24 md5
    - host all all 0.0.0.0/0 md5

postgresql:
    listen: 192.168.137.105:5432
    connect_address: 192.168.137.105:5432
    bin_dir: /home/kingbase/install/bin
    data_dir: /home/kingbase/install/data
    pgpass: /home/kingbase/.pgpass
    db_style: oracle
    authentication:
        replication:
            username: postgres
            password: zalando
        superuser:
            username: postgres
            password: zalando
    parameters:
        #listen_addresses: '0.0.0.0'
        #port: 5432
        #max_connections: 1000
        #superuser_reserved_connections: 13
        #unix_socket_directories: '.'
        #unix_socket_permissions: 0700
        #tcp_keepalives_idle: 60
        #tcp_keepalives_interval: 10
        #tcp_keepalives_count: 10
        #shared_buffers: 2048MB
        #vacuum_cost_delay: 10
        #bgwriter_delay: 10ms
        wal_level: hot_standby
        #wal_writer_delay: 10ms
        #max_wal_senders: 10
        hot_standby: on
        #wal_receiver_status_interval: 1s
        #hot_standby_feedback: on
        #log_destination: 'csvlog'
        #logging_collector: on
        #log_directory: 'pg_log'
        #log_truncate_on_rotation: on
        #log_rotation_age: 1d
        #log_rotation_size: 10MB
        #log_checkpoints: on
        #log_connections: on
        #log_disconnections: on
        #log_error_verbosity: verbose
        #log_timezone: 'PRC'
        #datestyle: 'iso, mdy'
        #timezone: 'PRC'
        #lc_messages: 'C'
        #lc_monetary: 'C'
        #lc_numeric: 'C'
        #lc_time: 'C'
        #full_page_writes: on
        #synchronous_commit: on
        #wal_log_hints: on
        #synchronous_standby_names: ''
        #max_replication_slots: 10
    create_replica_methods:
        - basebackup
    basebackup:
        max-rate: '100M'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

**Comment by maxlinux1** [comment]
dear all

After the environment is restarted, this problem is gone
















At 2021-01-05 13:20:30, "redelephant2020" <notifications@github.com> wrote:

Either something is wrong with the config (which you didn't show, despite the issue checklist), or you didn't installed kazoo or pysyncobj module.

Last, but not least, python 2.7 is deprecated since 01.01.2020

Hi ，i get same error like this:

2021-01-05 13:15:11,134 INFO: Failed to import patroni.dcs.consul
2021-01-05 13:15:11,139 INFO: Failed to import patroni.dcs.etcd
2021-01-05 13:15:11,142 INFO: Failed to import patroni.dcs.etcd3
2021-01-05 13:15:11,149 INFO: Failed to import patroni.dcs.exhibitor
2021-01-05 13:15:11,162 INFO: Failed to import patroni.dcs.zookeeper
Traceback (most recent call last):
File "patroni.py", line 6, in
main()
File "/home/kingbase/patroni/patroni/init.py", line 170, in main
return patroni_main()
File "/home/kingbase/patroni/patroni/init.py", line 138, in patroni_main
abstract_main(Patroni, schema)
File "/home/kingbase/patroni/patroni/daemon.py", line 98, in abstract_main
controller = cls(config)
File "/home/kingbase/patroni/patroni/init.py", line 29, in init
self.dcs = get_dcs(self.config)
File "/home/kingbase/patroni/patroni/dcs/init.py", line 107, in get_dcs
Available implementations: """ + ', '.join(sorted(set(available_implementations))))
patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: kubernetes, raft'

My enviroment like this：

Python 3.6
pip3 20.3.3

I use this command "python patroni.py standby.yml" and add this node in a cluster as standby cluster.

My config like this:

scope: postgresql1
namespace: /service/
name: pgsql10_node1

restapi:
listen: 192.168.137.105:8008
connect_address: 192.168.137.105:8008

etcd:
host: 192.168.137.101:2379

bootstrap:
dcs:
standby_cluster:
host: 192.168.137.101
port: 5432
create_replica_methods:
- basebackup

initdb:

- encoding: UTF8

- data-checksums

pg_hba:

- host replication postgres 192.168.137.0/24 md5

- host all all 0.0.0.0/0 md5



postgresql:
listen: 192.168.137.105:5432
connect_address: 192.168.137.105:5432
bin_dir: /home/kingbase/install/bin
data_dir: /home/kingbase/install/data
pgpass: /home/kingbase/.pgpass
db_style: oracle
authentication:
replication:
username: postgres
password: zalando
superuser:
username: postgres
password: zalando
parameters:
#listen_addresses: '0.0.0.0'
#port: 5432
#max_connections: 1000
#superuser_reserved_connections: 13
#unix_socket_directories: '.'
#unix_socket_permissions: 0700
#tcp_keepalives_idle: 60
#tcp_keepalives_interval: 10
#tcp_keepalives_count: 10
#shared_buffers: 2048MB
#vacuum_cost_delay: 10
#bgwriter_delay: 10ms
wal_level: hot_standby
#wal_writer_delay: 10ms
#max_wal_senders: 10
hot_standby: on
#wal_receiver_status_interval: 1s
#hot_standby_feedback: on
#log_destination: 'csvlog'
#logging_collector: on
#log_directory: 'pg_log'
#log_truncate_on_rotation: on
#log_rotation_age: 1d
#log_rotation_size: 10MB
#log_checkpoints: on
#log_connections: on
#log_disconnections: on
#log_error_verbosity: verbose
#log_timezone: 'PRC'
#datestyle: 'iso, mdy'
#timezone: 'PRC'
#lc_messages: 'C'
#lc_monetary: 'C'
#lc_numeric: 'C'
#lc_time: 'C'
#full_page_writes: on
#synchronous_commit: on
#wal_log_hints: on
#synchronous_standby_names: ''
#max_replication_slots: 10
create_replica_methods:
- basebackup
basebackup:
max-rate: '100M'

tags:
nofailover: false
noloadbalance: false
clonefrom: false
nosync: false
