### ISSUE TITLE
Callback 'on_role_change' running twice when we have postgres SIGKILL

### ISSUE THREAD

**Issue by pkonotopov** [zalando/patroni#1776]
**Describe the bug**
May be this is the feature. When we have an unexpected stop of postgres process the hook `on_role_change` executes twice (and no failover, patroni hasn't had time to react to a postgres restart).

**To Reproduce**

Here the simple script which logs the callback parameters:

```python
#!/usr/bin/env python3
"""
Usage:
    switch_replication.py <hook> <role> <scope>
Examples:
    switch_replication.py on_role_change master my_cluster
Options:
    <hook>     Event
    <role>       Current cluster member role
    <scope>   Current cluster name
"""
import sys
import logging
from docopt import docopt

logger = logging.getLogger('switch-debug')
logger.setLevel(logging.INFO)
handler = logging.StreamHandler(sys.stdout)
handler.setLevel(logging.INFO)
formatter = logging.Formatter(
    '%(name)s: %(asctime)s %(levelname)s: %(message)s')

handler.setFormatter(formatter)
logger.addHandler(handler)

def main():

    args = docopt(__doc__, options_first=True)
    logger.info("hook == {}, role == {}, scope == {}".format(
        args['<hook>'], args['<role>'], args['<scope>']))

if __name__ == '__main__':
    main()
```

Then `pkill -9 postgres` on Leader host, and we got - see logs below - the string which contains `switch-debug`. 

**Expected behavior**
This script should be run once.

**Environment**
- Patroni version: 2.0.1
- PostgreSQL version: 12.5
- DCS (and its version): etcd 3.3.11

**Patroni configuration file**

The most relevant part:
```
callback:
  on_role_change: '/etc/patroni/scripts/callback_test.py
```

**Have you checked Patroni logs?**
```
...some restart and recovery logs...
Dec  3 23:04:05 db2-dc2 patroni: 2020-12-03 23:04:05,456 INFO: starting as readonly because i had the session lock
...
Dec  3 23:04:06 db2-dc2 patroni: 2020-12-03 23:04:06,146 INFO: establishing a new patroni connection to the postgres cluster
Dec  3 23:04:06 db2-dc2 patroni: server signaled

Dec  3 23:04:06 db2-dc2 patroni: switch-debug: 2020-12-03 23:04:06,201 INFO: hook == on_role_change, role == replica, scope == pg_pub

Dec  3 23:04:06 db2-dc2 patroni: 2020-12-03 23:04:06,204 INFO: promoted self to leader because i had the session lock
Dec  3 23:04:06 db2-dc2 patroni: server promoting

Dec  3 23:04:06 db2-dc2 patroni: 2020-12-03 23:04:06,212 INFO: cleared rewind state after becoming the leader
Dec  3 23:04:06 db2-dc2 patroni: switch-debug: 2020-12-03 23:04:06,281 INFO: hook == on_role_change, role == master, scope == pg_pub

Dec  3 23:04:07 db2-dc2 patroni: 2020-12-03 23:04:07,245 INFO: Lock owner: 10.38.2.22; I am 10.38.2.22
```

**Have you checked PostgreSQL logs?**

No need to provide PG logs.

**Have you tried to use GitHub issue search?**

Not found.

**Additional context**

No any additional context here.

**Comment by CyberDem0n** [comment]
As a precaution Patroni always starting Postgres in read-only.
Since it was running before as primary, the first time callback is executed with parameter role=replica.
After that it was promoted, and the second run is with parameter role=master.

**Comment by pkonotopov** [comment]
Sure, i'm understand this. But, this is an intermediate state, should we detect that cluster running in single user mode, and do nothing? In terms of execution of the callback script? Callback with hook=on_role_change, role=replica, scope=pg_pub most relevant for transition `leader--(failover)-->replica`, but not `leader->crash recovery (single user mode)->leader`.

**Comment by pkonotopov** [comment]
Besides that, if we have a crash of the postgres process, should we switch over immediately to the replica with replica's promotion?

**Comment by CyberDem0n** [comment]
By default Patroni always prefers recovering crashed postgres instead of failover because there is a chance that some transactions were not replicated (especially in async mode).

Please read about [master_start_timeout](https://patroni.readthedocs.io/en/latest/SETTINGS.html).
When Patroni starts postgres in recovery (or in single-user mode) there is no guaranty that it will finish within the configured threshold. In this case, if there are other healthy nodes the leader key is removed and therefore the failover triggered. If you set master_start_timeout to 0, the failover will happen immediately.

**Comment by pkonotopov** [comment]
Thanks for explanation! Closing this.
