### ISSUE TITLE
409(Conflict) returned when updating leader configmap

### ISSUE THREAD

**Issue by zhanshen8D** [zalando/patroni#1793]
**Describe the bug**
In our testing environment, the Patroni reported the error occasionally

2020-12-12 00:07:10,525 ERROR: (409)
Reason: Conflict

More logs can be found in "Have you checked Patroni logs?"

It seemed the leader configmap was updated concurrently but we had no idea why that happened. There should be no other application updating the configmap by mistake.

**To Reproduce**
This issue happened only once until now. We don't know how to reproduce.

**Expected behavior**
The 409 error is not expected to happen when updating leader.

**Screenshots**

**Environment**
- Patroni version: 1.6.3
- PostgreSQL version: 10.14
- DCS (and its version): kubernetes

**Patroni configuration file**
bootstrap:
  dcs:
    synchronous_mode: true
    loop_wait: 5
    postgresql:
      use_pg_rewind: true
  initdb:
  - auth-host: md5
  - auth-local: trust
  - encoding: UTF8
  - locale: en_US.UTF-8
  - data-checksums
  pg_hba:
  - host all all samehost md5
  - host all all ::0/0    md5
  - host all all all md5
  - host replication replica all md5
  post_init: /var/lib/postgresql/scripts/pg_init.sh
postgresql:
  callbacks:
    on_start: /var/lib/postgresql/scripts/patroni_callback.py
    on_stop: /var/lib/postgresql/scripts/patroni_callback.py
    on_role_change: /var/lib/postgresql/scripts/patroni_callback.py
  authentication:
    superuser:
      sslmode: verify-ca
      sslrootcert: /tmp/certificates/ca/cacertbundle.pem
      sslkey: /tmp/cliprivkey.pem.postgres
      sslcert: /tmp/certificates/client/postgres/clicert.pem
    replication:
      sslmode: verify-ca
      sslrootcert: /tmp/certificates/ca/cacertbundle.pem
      sslkey: /tmp/cliprivkey.pem.replica
      sslcert: /tmp/certificates/client/replica/clicert.pem
    rewind: # Has no effect on postgres 10 and lower
      sslmode: verify-ca
      sslrootcert: /tmp/certificates/ca/cacertbundle.pem
      sslkey: /tmp/cliprivkey.pem.postgres
      sslcert: /tmp/certificates/client/postgres/clicert.pem
  parameters:
    logging_collector: "off"
    #unix_socket_directories: '/tmp'
    huge_pages: "off"
    ssl: on
    ssl_ca_file: /tmp/certificates/clica/cliCAcertbundle.pem
    ssl_cert_file: /tmp/certificates/server/srvcert.pem
    ssl_key_file: /tmp/certificates/server/srvprivkey.pem
    ssl_ciphers: "HIGH+ECDHE:HIGH+AES256!DHE!SHA!ADH"
  pg_hba:
    - local all all trust
    - host all all 127.0.0.1/32 trust
    - host all all ::1/128 trust
    - local replication all trust
    - host replication all 127.0.0.1/32 trust
    - host replication all ::1/128 trust
    - host all all samehost trust
    - hostssl all all ::0/0    cert
    - hostssl all all all cert
    - hostssl replication replica all cert
watchdog:
  mode: off

**patronictl show-config**
loop_wait: 5
postgresql:
  use_pg_rewind: true
synchronous_mode: true

**Have you checked Patroni logs?**

2020-12-12 00:07:05,569 INFO: Lock owner: eric-data-document-database-pg-0; I am eric-data-document-database-pg-0
2020-12-12 00:07:10,471 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff457597160>, 'Connection to 10.96.0.1 timed out. (connect timeout=1)')': /api/v1/namespaces/cm-stage3-ns/configmaps/eric-data-document-database-pg-leader
2020-12-12 00:07:10,525 ERROR: (409)
Reason: Conflict
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Fri, 11 Dec 2020 23:07:10 GMT', 'Content-Length': '370'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on configmaps \"eric-data-document-database-pg-leader\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"eric-data-document-database-pg-leader","kind":"configmaps"},"code":409}

**Have you checked PostgreSQL logs?**
Postgres was restarted after the 409 error, but it seemed the Patroni's logic.

2020-12-12 00:07:17,934 ERROR: (409)
Reason: Conflict
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Fri, 11 Dec 2020 23:07:17 GMT', 'Content-Length': '370'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on configmaps \"eric-data-document-database-pg-leader\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"eric-data-document-database-pg-leader","kind":"configmaps"},"code":409}

2020-12-12 00:07:17,934 ERROR: failed to update leader lock
2020-12-12 00:07:17,934 INFO: pg_rewind args: ['pg_rewind', '--help']
2020-12-12 00:07:17,947 INFO: Reaped pid=12230, exit status=0
2020-12-12 00:07:17.948 CET   [55]LOG:  received immediate shutdown request

**Have you tried to use GitHub issue search?**
Yes. But can't find enough clue.

**Additional context**

**Comment by CyberDem0n** [comment]
Patroni version: 1.6.3 was released more than a year ago, please upgrade to 2.0.1, there were a few issues fixed in this area .
