### ISSUE TITLE
support 9.3 by allowing disabling replication slots

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#18]
... this should be possible.

**Comment by jberkus** [comment]
Taken care of with PR #23

**Comment by CyberDem0n** [comment]
Oh!
We can actually make this feature more smart and even make patroni compatible with postgresql  < 9.3

1) We should query major version in Postgresql.__init__
2) If version < 9.4 forcefully set `use_slots` to False
3) Get rid from `pg_xlog_location_diff` which exists only from 9.3 and use function `utils.lsn_to_bytes` (https://github.com/zalando/patroni/blob/master/helpers/utils.py#L45) instead.
4) Profit

**Comment by CyberDem0n** [comment]
Hmm, for postgres version < 9.3 formula is a little bit different...
Ok, will move this method into Postgresql and make it version-specific.

**Comment by CyberDem0n** [comment]
`2` wont work for slaves...
We have to know in advance that version < 9.4 in order to create proper recovery.conf but without starting cluster it's not really possible to determine version.

But at least everything else is doable.

https://github.com/zalando/patroni/pull/25

**Comment by jberkus** [comment]
We don't care about supporting < 9.3  Here's why:

1. Before 9.3, you couldn't remaster over streaming replication, making failover/failback and master change *much* more complicated.

2. 9.3 was 2 years ago, and is the supported version in current stable Ubuntu, Debian, and Red Hat.

**Comment by jberkus** [comment]
For that reason, and others: -1 from me.  

I feel that this complicates the code in order to support versions of PostgresQL which we have other problems supporting.

**Comment by CyberDem0n** [comment]
Ok, dropped unneeded  code.
