### ISSUE TITLE
Replication issue in PostgreSQL patroni  setup 

### ISSUE THREAD

**Issue by navaneswarareddy** [zalando/patroni#1803]
Followed below tutorial to create high available PostgreSQL cluster : 
https://www.techsupportpk.com/2020/02/how-to-set-up-highly-available-postgresql-cluster-ubuntu-19-20.html

can anyone help me with Replication .when I created table on node1 it is not replicated on node2 and node3 

root@node1:~# patronictl -c /etc/patroni.yml list
+ Cluster: postgres (6907947263552216792) --+----+-----------+
| Member | Host         | Role    | State   | TL | Lag in MB |
+--------+--------------+---------+---------+----+-----------+
| node1  | 192.168.10.1 | Replica | running |  6 |       0.0 |
| node2  | 192.168.10.2 | Replica | running |  6 |       0.0 |
| node3  | 192.168.10.3 | Leader  | running |  6 |           |
+--------+--------------+---------+---------+----+-----------+

node3: Leader 
postgres=# \dt
         List of relations
 Schema | Name  | Type  |  Owner
--------+-------+-------+----------
 public | roles | table | postgres
(1 row)

node2:
postgres-# \dt
Did not find any relations.

node1:
postgres-# \dt
Did not find any relations.

root@node4:~# etcdctl cluster-health
member 8e9e05c52164694d is healthy: got healthy result from http://192.168.10.4:2379
cluster is healthy

root@node4:~# etcd --version
etcd Version: 3.2.26
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.13.7
Go OS/Arch: linux/amd64

root@node3:~# systemctl status patroni
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
     Loaded: loaded (/etc/systemd/system/patroni.service; disabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-12-21 05:40:45 UTC; 3h 42min ago
   Main PID: 19897 (patroni)
      Tasks: 15 (limit: 1137)
     Memory: 98.3M
     CGroup: /system.slice/patroni.service
             ├─19897 /usr/bin/python2 /usr/local/bin/patroni /etc/patroni.yml
             ├─19926 postgres -D /data/patroni --config-file=/data/patroni/postgresql.conf --listen_addresses=192.168.10.3 --max_worker_processes=8 --max_prepared_transact>
             ├─19929 postgres: postgres: checkpointer
             ├─19930 postgres: postgres: background writer
             ├─19931 postgres: postgres: stats collector
             ├─19936 postgres: postgres: postgres postgres 192.168.10.3(55234) idle
             ├─27643 postgres: postgres: walwriter
             ├─27644 postgres: postgres: autovacuum launcher
             ├─27645 postgres: postgres: logical replication launcher
             ├─31342 postgres: postgres: walsender replicator 192.168.10.1(46392) streaming 0/8000840
             └─31346 postgres: postgres: walsender replicator 192.168.10.2(43432) streaming 0/8000840

Dec 21 09:22:23 node3 patroni[19897]: 2020-12-21 09:22:23,232 INFO: Lock owner: node3; I am node3
Dec 21 09:22:23 node3 patroni[19897]: 2020-12-21 09:22:23,240 INFO: no action.  i am the leader with the lock
Dec 21 09:22:33 node3 patroni[19897]: 2020-12-21 09:22:33,233 INFO: Lock owner: node3; I am node3
Dec 21 09:22:33 node3 patroni[19897]: 2020-12-21 09:22:33,241 INFO: no action.  i am the leader with the lock
Dec 21 09:22:43 node3 patroni[19897]: 2020-12-21 09:22:43,232 INFO: Lock owner: node3; I am node3
Dec 21 09:22:43 node3 patroni[19897]: 2020-12-21 09:22:43,241 INFO: no action.  i am the leader with the lock
Dec 21 09:22:53 node3 patroni[19897]: 2020-12-21 09:22:53,233 INFO: Lock owner: node3; I am node3
Dec 21 09:22:53 node3 patroni[19897]: 2020-12-21 09:22:53,241 INFO: no action.  i am the leader with the lock
Dec 21 09:23:03 node3 patroni[19897]: 2020-12-21 09:23:03,232 INFO: Lock owner: node3; I am node3
Dec 21 09:23:03 node3 patroni[19897]: 2020-12-21 09:23:03,240 INFO: no action.  i am the leader with the lock

**Comment by CyberDem0n** [comment]
Magic doesn't exist. If the replication works (and according to the two walsender processes it does), the table should be replicated.
Please make sure that you don't have a transaction in progress in the psql session and that there is no other postgres running on the nodes where you might be accidentally connected.

Also, python 2.7 is EOL for about 1 year.

**Comment by navaneswarareddy** [comment]
No other postgres is running on the nodes and only one table is created on leader

**Comment by CyberDem0n** [comment]
Once again, magic doesn't exist.

If you don't know how to fly manually, autopilot won't help.
The same with Patroni and Postgres. If you don't know how to configure streaming replication manually and verify that it works, Patroni will not make your life easier.
