### ISSUE TITLE
 Available implementations: """ + ', '.join(sorted(set(available_implementations)))) patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: kubernetes, raft'

### ISSUE THREAD

**Issue by redelephant2020** [zalando/patroni#1807]
Hi ，i get same error like this:

2021-01-05 13:15:11,134 INFO: Failed to import patroni.dcs.consul
2021-01-05 13:15:11,139 INFO: Failed to import patroni.dcs.etcd
2021-01-05 13:15:11,142 INFO: Failed to import patroni.dcs.etcd3
2021-01-05 13:15:11,149 INFO: Failed to import patroni.dcs.exhibitor
2021-01-05 13:15:11,162 INFO: Failed to import patroni.dcs.zookeeper
Traceback (most recent call last):
File "patroni.py", line 6, in
main()
File "/home/kingbase/patroni/patroni/init.py", line 170, in main
return patroni_main()
File "/home/kingbase/patroni/patroni/init.py", line 138, in patroni_main
abstract_main(Patroni, schema)
File "/home/kingbase/patroni/patroni/daemon.py", line 98, in abstract_main
controller = cls(config)
File "/home/kingbase/patroni/patroni/init.py", line 29, in init
self.dcs = get_dcs(self.config)
File "/home/kingbase/patroni/patroni/dcs/init.py", line 107, in get_dcs
Available implementations: """ + ', '.join(sorted(set(available_implementations))))
patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: kubernetes, raft'

My enviroment like this：

Python 3.6.0
pip3 20.3.3

pip3 list

Package Version
boto 2.49.0
certifi 2020.12.5
chardet 4.0.0
click 7.1.2
dnspython 2.0.0
flake8 3.8.4
idna 2.10
importlib-metadata 3.3.0
kazoo 2.8.0
mccabe 0.6.1
patroni 2.5
pip 20.3.3
prettytable 2.0.0
psutil 5.8.0
psycopg2 2.5.4
pycodestyle 2.6.0
pyflakes 2.2.0
pysyncobj 0.3.7
python-consul 1.1.0
python-dateutil 2.8.1
python-etcd 0.4.5
PyYAML 5.3.1
requests 2.25.1
setuptools 28.8.0
six 1.15.0
typing-extensions 3.7.4.3
urllib3 1.26.2
wcwidth 0.2.5
wheel 0.36.2
ydiff 1.2
zipp 3.4.0

I use this command "python patroni.py standby.yml" and add this node in a cluster as standby cluster.

My config like this:

scope: postgresql1
namespace: /service/
name: pgsql10_node1

restapi:
listen: 192.168.137.105:8008
connect_address: 192.168.137.105:8008

etcd:
host: 192.168.137.101:2379

bootstrap:
dcs:
standby_cluster:
host: 192.168.137.101
port: 5432
create_replica_methods:
- basebackup

initdb:
- encoding: UTF8
- data-checksums
pg_hba:
- host replication postgres 192.168.137.0/24 md5
- host all all 0.0.0.0/0 md5
postgresql:
listen: 192.168.137.105:5432
connect_address: 192.168.137.105:5432
bin_dir: /home/kingbase/install/bin
data_dir: /home/kingbase/install/data
pgpass: /home/kingbase/.pgpass
db_style: oracle
authentication:
replication:
username: postgres
password: zalando
superuser:
username: postgres
password: zalando
parameters:
#listen_addresses: '0.0.0.0'
#port: 5432
#max_connections: 1000
#superuser_reserved_connections: 13
#unix_socket_directories: '.'
#unix_socket_permissions: 0700
#tcp_keepalives_idle: 60
#tcp_keepalives_interval: 10
#tcp_keepalives_count: 10
#shared_buffers: 2048MB
#vacuum_cost_delay: 10
#bgwriter_delay: 10ms
wal_level: hot_standby
#wal_writer_delay: 10ms
#max_wal_senders: 10
hot_standby: on
#wal_receiver_status_interval: 1s
#hot_standby_feedback: on
#log_destination: 'csvlog'
#logging_collector: on
#log_directory: 'pg_log'
#log_truncate_on_rotation: on
#log_rotation_age: 1d
#log_rotation_size: 10MB
#log_checkpoints: on
#log_connections: on
#log_disconnections: on
#log_error_verbosity: verbose
#log_timezone: 'PRC'
#datestyle: 'iso, mdy'
#timezone: 'PRC'
#lc_messages: 'C'
#lc_monetary: 'C'
#lc_numeric: 'C'
#lc_time: 'C'
#full_page_writes: on
#synchronous_commit: on
#wal_log_hints: on
#synchronous_standby_names: ''
#max_replication_slots: 10
create_replica_methods:
- basebackup
basebackup:
max-rate: '100M'

tags:
nofailover: false
noloadbalance: false
clonefrom: false
nosync: false

**Comment by CyberDem0n** [comment]
Have you tried to read the [readme](https://github.com/zalando/patroni/#technical-requirementsinstallation) file?

> Patroni can be installed with pip:

> pip install patroni[dependencies]

> where dependencies can be either empty, or consist of one or more of the following:

> etcd or etcd3
    **python-etcd** module in order to use Etcd as DCS

**Comment by redelephant2020** [comment]
May i run it by source code? 

If i user python2.7 ,this is ok!

**Comment by CyberDem0n** [comment]
It doesn't matter how you run it, `python-etcd` module must be installed if you want to run Patroni with etcd.

**Comment by redelephant2020** [comment]
python-etcd 0.4.5  in the pip3 list . I am sure i install it .

**Comment by CyberDem0n** [comment]
Magic doesn't exists.

**Comment by redelephant2020** [comment]
python-etcd 0.4.5 in the pip3 list . I am sure i install it.

It in the list:
Package Version
boto 2.49.0
certifi 2020.12.5
chardet 4.0.0
click 7.1.2
dnspython 2.0.0
flake8 3.8.4
idna 2.10
importlib-metadata 3.3.0
kazoo 2.8.0
mccabe 0.6.1
patroni 2.5
pip 20.3.3
prettytable 2.0.0
psutil 5.8.0
psycopg2 2.5.4
pycodestyle 2.6.0
pyflakes 2.2.0
pysyncobj 0.3.7
python-consul 1.1.0
python-dateutil 2.8.1
**### python-etcd 0.4.5**
PyYAML 5.3.1
requests 2.25.1
setuptools 28.8.0
six 1.15.0
typing-extensions 3.7.4.3
urllib3 1.26.2
wcwidth 0.2.5
wheel 0.36.2
ydiff 1.2
zipp 3.4.0

**Comment by CyberDem0n** [comment]
> If i use python2.7 ,this is ok. I use release.sh and get the whl file . so i run the patroni command and get same error.

I totally don't undestand what you are doing. The only purpose of release.sh is publishing Patroni on PyPI.

**Comment by redelephant2020** [comment]
I need change some code for our database ,the database base on postgresql, so i need build the package to publish some users.

**Comment by CyberDem0n** [comment]
> I need change some code for our database ,the database base on postgresql, so i need build the package to publish some users.

Perfect, then you should be qualified enough to figure out what is wrong with _your system_ and why python can't find/load certain modules.

The recommended way of installing Patroni either from PyPI (pip install patroni[$EXTRAS]) or via PGDG packages (apt-get/yum install). We can't be responsible for something that you do on your own.
