### ISSUE TITLE
Data Integrity issue/Inconsistency noticed in patroni postgresql cluster

### ISSUE THREAD

**Issue by Tekchanddagar** [zalando/patroni#1809]
Hello Team,

Today we were performing some testing with our patroni cluster and i am explaing same in below steps:

1. We are using OS Centos 8.
2. We create 2 node cluster (Node-1, Node-2), Node-1 as master node and Node-2 as replica with tag `nofailover: true` so it can't become master even after our master node (Node-1) fail. We did this because we are performing some DR testing.
3. Now we stopped the patroni service on Replica node (Node-2) and delete the `standby.signal` file from data directory and start the postgresql service using `systemctl start postgresql-13` command and its started fine in read-write mode.
4. Now we did some changes at our application like user account creation etc and these changes were saved succsessfully in the database on Node-2.
5. Now we again stopped the postgresql service using `systemctl stop postgresql-13` command on Node-2.
6. Now we started the patroni service again on Node-2 (without deleting the data from data directory) and its started and join the cluster also as secondary node. We checked the status using the below command and its showing cluster in sync state:
                        `patronictl -c /etc/patroni.yml list`
but we were expecting that it will fail to join the cluster due to data inconsistency on both the nodes.
7. Node-2 able to join the cluster but data was not replicating on Node-2. Because we did some changes at our application end and those changes were showing in Node-1 database but not in the Node-2 database.

So we are feeling that there is some data integrity/inconsistency issue with patroni.

Can you please help us on this issue or we are doing something wrong at our end?

Thank You

**Comment by CyberDem0n** [comment]
> Now we stopped the patroni service on Replica node (Node-2) and delete the standby.signal file from data directory and start the postgresql service using systemctl start postgresql-13 command and its started fine in read-write mode.

Congratulations, you shoot your own foot.
Of course, it hurts badly.
Don't do that.

**Comment by Tekchanddagar** [comment]
@CyberDem0n, Thank You for your response.

We did this because we were testing our DR site.

1. We have database node in DR site which is also part of primary site patroni cluster.
2. We did this so we can reduce RPO in DR.

Now let suppose our primary site goes down and we need to move on DR site and we want to use the database node which is in DR site because its have all the data. 

And once our primary site is up we will need to move back on the primary site and we want to join back the patroni cluster with DR site which have latest data.

is it feasible with patroni?
If yes can you please explain in few points?

Thank You

**Comment by CyberDem0n** [comment]
Have you looked at the [standby cluster](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#standby-cluster) feature?
