### ISSUE TITLE
hot_standby = 'off' for HA standby only (but 'on' for HOT standby)

### ISSUE THREAD

**Issue by jdutreve** [zalando/patroni#1811]
**Describe the bug**
It seems hot_standby is a global DCS attribute. Would it be possible to set it per local configuration ?
I would like to set to 'off' for any HA standby instance (synchronous replication), but to 'on' for any read-only replicas (asynchronous replication).

**Comment by CyberDem0n** [comment]
With hot_standby=off it is not possible to open a connection to the replica, but Patroni needs to be able to do that.
Therefore Patroni doesn't allow setting the hot_standby to a value different from "on".

**Comment by jdutreve** [comment]
Thank you very much for your quick reply. Would be interesting to add this reason into the documentation.
BTW, great work!

**Comment by CyberDem0n** [comment]
@jdutreve, this is the OS project, anyone can contribute.
Feel free to open a PR updating the docs :)

**Comment by jdutreve** [comment]
Yes, of course. Shoud I have to fork the repo ? Because currenlty, I can't create a new branch...

**Comment by CyberDem0n** [comment]
Yes, you need to fork it.
