### ISSUE TITLE
consulting about the new feature of patroni

### ISSUE THREAD

**Issue by mxli441** [zalando/patroni#1815]
HI,
   Our company uses patroni for a lot of productions, and sometimes we encounter the problem from customers that the patroni has not the load balance feature, so I want to consult whether the load-balance feature is under  consideration?

**Comment by CyberDem0n** [comment]
What is your understanding of load balancing?
If you are talking about load balancing read queries across all replicas - it is possible with HAProxy or any other kind of load balancer. 
There is a sample config in the repo: https://github.com/zalando/patroni/blob/master/haproxy.cfg#L25

**Comment by mxli441** [comment]
I   truly  appreciate of your reply,we have already  used HAProxy in our productions,thanks!
