### ISSUE TITLE
keys not written in etcd when using etcd3 key in config

### ISSUE THREAD

**Issue by sleewoo** [zalando/patroni#1822]
**Describe the bug**

when using this config there are no keys written in `etcd`.

`etcdctl ... ls / --recursive` returns nothing

```yml
etcd3:
  hosts: 192.168.4.2:2379,192.168.4.4:2379,192.168.4.6:2379
```

instead when using `etcd.hosts` the keys are written and `ls /` returns them.

**Environment**
- Patroni version: 2.0.1
- PostgreSQL version: 12
- DCS (and its version): etcd Version: 3.3.25

**Additional context**
on `Centos 7`

```
yum install -y \
  python3-psycopg2 \
  python3-devel \
  gcc

pip3 install patroni[etcd3]
```

**Comment by CyberDem0n** [comment]
Etcd v3 is using a different keyspace.
Before 3.4 etcdctl defaults to v2. In order to see keys from v3 you have to do `export ETCDCTL_API=3`.

**Comment by CyberDem0n** [comment]
Well, that's the issue with vip-manager, not Patroni.
