### ISSUE TITLE
HAproxy to balance between replica in kubernetes

### ISSUE THREAD

**Issue by zorx** [zalando/patroni#1823]
I'm using patroni with kubernetes (helm chart) and i was wondering how can I implement an HAproxy to balance between replica pods, the idea is about to create two endpoints `/master` & `/replica` with different ports and add an HAproxy between replica (for read queries)

any idea ?

**Comment by CyberDem0n** [comment]
Ok K8s it is enough to have the service with label selector `cluster-name=foobar&role=replica`.

`cluster-name` and `role` keywords could be different depending on your configuration.
`foobar` it the name of the cluster (SCOPE)

**Comment by CyberDem0n** [comment]
See the provided manifest: https://github.com/zalando/patroni/blob/master/kubernetes/patroni_k8s.yaml#L139-L155
