### ISSUE TITLE
Возможность оставить кластер командой самого patroni

### ISSUE THREAD

**Issue by Aytuar** [zalando/patroni#1831]
Сейчас, как я понимаю, единственный способ остановки кластера postgres это последовательная остановка сервиса patroni на всех серверах кластера.
Есть ли возможность корректной остановки кластера через команды самого patroni?

**Comment by CyberDem0n** [comment]
No, there is no such option, and will never be, because it defeats the purpose of HA.

**Comment by Aytuar** [comment]
@CyberDem0n но ведь для перезапуска нод postgres команда есть, которая позволяет перезапускать postgres как на одной ноду, так и на всех сразу. 
Почему для остановки кластера, например для обновлений, мне нужно заходить на каждую ноду и останавливать сервис patroni чтобы погасить postgres?
И я не понимаю как это должно повлиять на HA?

**Comment by CyberDem0n** [comment]
Don't you see the difference between restart of the postgres and stopping Patroni?

**Comment by Aytuar** [comment]
Вот именно, чтобы просто остановить сервисы postgres мне сейчас нужно остановить сам patroni.
Я же хочу не останавливать сами сервисы patroni, а используя команду самого patroni остановить postgres.
Это как maintenance, но не для обслуживания patroni или DCS, а самого postgres.
Возможно эта функциональность излишняя. Тогда на этом можно закрыть Issue окончательно.
Спасибо за ответы.

**Comment by CyberDem0n** [comment]
It seems that you are looking for maintenance mode: https://patroni.readthedocs.io/en/latest/pause.html

**Comment by Aytuar** [comment]
Нет. Я написал схожим на текущий режим обслуживания.
В текущем режиме обслуживания сам сервис postgres не затрагивается и продолжает работать.
А мне наоборот нужно его остановить

**Comment by CyberDem0n** [comment]
If the maintenance mode is enabled it is possible to do with postgres whatever you want.
There is no mode where Patroni will stop the postgres and will never be.

**Comment by Aytuar** [comment]
Спасибо. Вопрос закрыт.
