### ISSUE TITLE
Question: How to get the name of replica running on current server?

### ISSUE THREAD

**Issue by sleewoo** [zalando/patroni#1835]
Hello,

currently grep-ing config file to get the name of replica running on current server:

```
name=pg02
cat /etc/patroni/patroni.yml | grep -E "^name:\s+$name$"
```

can i use `patronictl` or REST api to get the name?

`patronictl list` does not mark any member as current.
of course i could get the `.Host` from `patronictl list -f json` and compare to `ip addr` but that's a lot of fuss.

thanks.

**Comment by sleewoo** [comment]
more context.
i need to run backups on first replica only.
running this on every server:

```
patronictl -c /etc/patroni/patroni.yml list -f json | jq -r '[ .[] | select(.Role == "Replica") ][0] | .Member'
```

now i need to know if returned member is actually the current server.
if yes, take backup
else `exit 0`

**Comment by CyberDem0n** [comment]
> can i use patronictl or REST api to get the name?

Not really. And there is no general solution to this problem. In order to access REST API you need to know at least the IP address it is listening on and it is not necessarily could answer on localhost. In order to work reliably, it still requires parsing the config file.

The normal practice (this is what most people do) is assigning the name in the patroni config from the hostname.

**Comment by sleewoo** [comment]
right, for using REST need to know ip.

but if providing the config file to `patronictl` it can get ip from the file and mark the member with that ip as current?

**Comment by CyberDem0n** [comment]
patronictl is a tool that could be called from any place, not necessarily from the same host where patroni is running.


> but if providing the config file to patronictl

If patronictl is able to parse yaml file I don't see any single reason why your scripts can't do the same.
After all, it seems that you are quite professional in `jq`. There is a python wrapper for jq, called `yq`, it will help you to avoid gripping, which could be error-prone.

**Comment by sleewoo** [comment]
ok, not a big issue, will parse config file with python, it's a runtime dependency anyway.
thanks.
