### ISSUE TITLE
Is there any document about mkbinary.sh?

### ISSUE THREAD

**Issue by pylSER** [zalando/patroni#1838]
I tried to make a patroni binary instead of installing it by pip, but it does not work well on docker(pgo_container). 

I think it is my binary problem. So is there a correct way to make binary?

What do i need to install and run before running mkbinary.sh and how to install patronictl in this way? Is there any python version requirement when i run mkbinary.sh and binary?

**Comment by CyberDem0n** [comment]
If you look into mkbinary.sh that will answer most of your questions.
Regarding patronictl: currently patroni.spec creates binary only for patroni, but you can do the same for patronictl.

I don't think that many people rely binary packaging. Pip is more flexible and better tested.
