### ISSUE TITLE
Unable to start because of /entrypoint.sh: Syntax error

### ISSUE THREAD

**Issue by DAGorchakov** [zalando/patroni#1841]
**Describe the bug**
Error occurred when try to `docker-compose up -d` with just builded patroni. Error msg:  `demo-patroni1 | /entrypoint.sh: 15: /entrypoint.sh: Syntax error: word unexpected (expecting "in")`. 

**To Reproduce**
```
git clone https://github.com/zalando/patroni.git
cd .\patroni\
docker build -t patroni .
docker-compose up -d
docker logs demo-patroni1
  : not found.sh: 2: /entrypoint.sh:
  /entrypoint.sh: 15: /entrypoint.sh: Syntax error: word unexpected (expecting "in")
```
**Screenshots**
![image](https://user-images.githubusercontent.com/17656075/107474868-35f47380-6b84-11eb-93fa-7743e8a62a9e.png)
![image](https://user-images.githubusercontent.com/17656075/107475200-ce8af380-6b84-11eb-9bc6-b7ae9e0a13e2.png)

**Environment**
Windows 10 build 18363
Docker version 20.10.2, build 2291f61

**Comment by CyberDem0n** [comment]
The example perfectly works when started on Linux.
Since I am not a windows user I can't help here.
