### ISSUE TITLE
How to split configuration beetween master and replica?

### ISSUE THREAD

**Issue by vladloskut** [zalando/patroni#1842]
We have 2 node patroni cluster and found the following issue:

archive_command is replicated to both mater and replica
we have crontab job on master only that performing physical postgresql backup 

the question is how to disable archive_command on replica and how to enable it after failover/switchover?

we want turn off archive_mode on replica at all

Thanks in advance

**Comment by CyberDem0n** [comment]
Have you tried reading the postgres documentation? Specifically about [archive_mode](https://www.postgresql.org/docs/current/runtime-config-wal.html#GUC-ARCHIVE-MODE)?

**Comment by vladloskut** [comment]
My bad
