### ISSUE TITLE
how to change default postgres cmdline ?

### ISSUE THREAD

**Issue by sokoow** [zalando/patroni#1852]
**Describe the bug**
No matter what I try in patroni.yaml/postgres:parameter: section of config, I seem to be unable to change this default postgres command line parameter set:

```
$ cat /proc/31/cmdline 
postgres-D/var/lib/postgresql/data--config-file=/var/lib/postgresql/data/postgresql.conf--listen_addresses=0.0.0.0--port=5432--cluster_name=tobs--wal_level=replica--hot_standby=on--max_connections=100--max_wal_senders=10--max_prepared_transactions=150--max_locks_per_transaction=64--track_commit_timestamp=off--max_replication_slots=10--max_worker_processes=8--wal_log_hints=on
```

is there any way to change all these values above at will ?

**Comment by CyberDem0n** [comment]
Yes, because they could be set only globally, documentation for the reference: https://patroni.readthedocs.io/en/latest/dynamic_configuration.html

You can change them with `patronictl edit-config`.
Please also go through the tutorial: https://github.com/patroni-training/2019
