### ISSUE TITLE
Can Patroni setup auto failover priority ?

### ISSUE THREAD

**Issue by hunterhuang8810** [zalando/patroni#1853]
Hi,

I want to consult a question , Can Patroni setup auto failover priority ?

example, I have a patroni managed cluster with 3 nodes, node01/node02/node03, and assume current state as below:
Node01 : primary
Node02: standby
Node03: standby(used for backup and other maintain purpose)

so, if node01 crash and auto failover occur, I want to elect Node02 as new primary with high priorith thank Node03, I checked the doc not find the method or APT to setup node's priority.

Can Patroni support setup auto failover priority to let standby node elect as primary with high priority than backup node？

**Comment by CyberDem0n** [comment]
https://patroni.readthedocs.io/en/latest/SETTINGS.html#tags

For the future: GH Issues is not a chat, please use the #patroni channel in the [PostgreSQL slack](https://postgres-slack.herokuapp.com/).

**Comment by hunterhuang8810** [comment]
> https://patroni.readthedocs.io/en/latest/SETTINGS.html#tags
> 
> For the future: GH Issues is not a chat, please use the #patroni channel in the [PostgreSQL slack](https://postgres-slack.herokuapp.com/).

I checked patroni tags config, so there's no priority config? not nofailover, just the priority config
