### ISSUE TITLE
Patroni can't auto failover when open archive_mode

### ISSUE THREAD

**Issue by hunterhuang8810** [zalando/patroni#1854]
**Describe the bug**

env info:

[postgres@localhost pgdata]$ patroni --version
patroni 2.0.1
[postgres@localhost pgdata]$

postgres=# select version();
                                                 version                                                 
---------------------------------------------------------------------------------------------------------
 PostgreSQL 12.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit
(1 row)

postgres=# 

I tested a patroni managed postgres cluster with 3 nodes.
I found when Postgres archive_mode = off, and I shutdown leader machine, auto failover can success.

archive_mode = off
#archive_command = 'test ! -f /home/service/var/pgdata/archivedir/%f && cp %p /home/service/var/pgdata/archivedir/%f'
#archive_timeout = '5min'

but when I open archive mode:
archive_mode = always
archive_command = 'test ! -f /home/service/var/pgdata/archivedir/%f && cp %p /home/service/var/pgdata/archivedir/%f'
archive_timeout = '5min'

then when I shutdown leader machine, patroni can't elect new leader, and always shows lag=16
my test db is static with no any data change.

[postgres@localhost pgdata]$ patronictl list
+ Cluster: pgsql (6932366804563343747) --+---------+----+-----------+
| Member | Host                | Role    | State   | TL | Lag in MB |
+--------+---------------------+---------+---------+----+-----------+
| pg01   | 192.168.56.94:54322 | Replica | running |  3 |        16 |
| pg03   | 192.168.56.96:54322 | Replica | running |  3 |        16 |
+--------+---------------------+---------+---------+----+-----------+
[postgres@localhost pgdata]$ 

--------patroni log
2021-02-23 16:43:45,058 INFO: My wal position exceeds maximum replication lag
2021-02-23 16:43:45,065 INFO: following a different leader because i am not the healthiest node
2021-02-23 16:43:50,057 INFO: My wal position exceeds maximum replication lag
2021-02-23 16:43:50,065 INFO: following a different leader because i am not the healthiest node
2021-02-23 16:43:55,058 INFO: My wal position exceeds maximum replication lag
2021-02-23 16:43:55,064 INFO: following a different leader because i am not the healthiest node
2021-02-23 16:44:00,057 INFO: My wal position exceeds maximum replication lag
2021-02-23 16:44:00,065 INFO: following a different leader because i am not the healthiest node
2021-02-23 16:44:05,057 INFO: My wal position exceeds maximum replication lag
2021-02-23 16:44:05,064 INFO: following a different leader because i am not the healthiest node
2021-02-23 16:44:10,058 INFO: My wal position exceeds maximum replication lag
2021-02-23 16:44:10,065 INFO: following a different leader because i am not the healthiest node
2021-02-23 16:44:15,064 INFO: My wal position exceeds maximum replication lag
2021-02-23 16:44:15,080 INFO: following a different leader because i am not the healthiest node

--log of postgres instance:
2021-02-23 16:44:40.066 CST,,,2384,"127.0.0.1:59960",6034c078.950,1,"",2021-02-23 16:44:40 CST,,0,LOG,00000,"connection received: host=127.0.0.1 port=59960",,,,,,,,,""
2021-02-23 16:44:40.067 CST,"repl","",2384,"127.0.0.1:59960",6034c078.950,2,"authentication",2021-02-23 16:44:40 CST,4/31,0,LOG,00000,"replication connection authorized: user=repl",,,,,,,,,""
2021-02-23 16:44:40.068 CST,"repl","",2384,"127.0.0.1:59960",6034c078.950,3,"idle",2021-02-23 16:44:40 CST,,0,LOG,00000,"disconnection: session time: 0:00:00.003 user=repl database= host=127.0.0.1 port=59960",,,,,,,,,""
2021-02-23 16:44:45.061 CST,,,2386,"127.0.0.1:59964",6034c07d.952,1,"",2021-02-23 16:44:45 CST,,0,LOG,00000,"connection received: host=127.0.0.1 port=59964",,,,,,,,,""
2021-02-23 16:44:45.062 CST,"repl","",2386,"127.0.0.1:59964",6034c07d.952,2,"authentication",2021-02-23 16:44:45 CST,4/32,0,LOG,00000,"replication connection authorized: user=repl",,,,,,,,,""
2021-02-23 16:44:45.063 CST,"repl","",2386,"127.0.0.1:59964",6034c07d.952,3,"idle",2021-02-23 16:44:45 CST,,0,LOG,00000,"disconnection: session time: 0:00:00.002 user=repl database= host=127.0.0.1 port=59964",,,,,,,,,""
2021-02-23 16:44:50.062 CST,,,2387,"127.0.0.1:59968",6034c082.953,1,"",2021-02-23 16:44:50 CST,,0,LOG,00000,"connection received: host=127.0.0.1 port=59968",,,,,,,,,""
2021-02-23 16:44:50.062 CST,"repl","",2387,"127.0.0.1:59968",6034c082.953,2,"authentication",2021-02-23 16:44:50 CST,4/33,0,LOG,00000,"replication connection authorized: user=repl",,,,,,,,,""
2021-02-23 16:44:50.064 CST,"repl","",2387,"127.0.0.1:59968",6034c082.953,3,"idle",2021-02-23 16:44:50 CST,,0,LOG,00000,"disconnection: session time: 0:00:00.002 user=repl database= host=127.0.0.1 port=59968",,,,,,,,,""
2021-02-23 16:44:55.061 CST,,,2390,"127.0.0.1:59972",6034c087.956,1,"",2021-02-23 16:44:55 CST,,0,LOG,00000,"connection received: host=127.0.0.1 port=59972",,,,,,,,,""
2021-02-23 16:44:55.062 CST,"repl","",2390,"127.0.0.1:59972",6034c087.956,2,"authentication",2021-02-23 16:44:55 CST,4/34,0,LOG,00000,"replication connection authorized: user=repl",,,,,,,,,""
2021-02-23 16:44:55.063 CST,"repl","",2390,"127.0.0.1:59972",6034c087.956,3,"idle",2021-02-23 16:44:55 CST,,0,LOG,00000,"disconnection: session time: 0:00:00.001 user=repl database= host=127.0.0.1 port=59972",,,,,,,,,""
2021-02-23 16:45:00.059 CST,,,2396,"127.0.0.1:59976",6034c08c.95c,1,"",2021-02-23 16:45:00 CST,,0,LOG,00000,"connection received: host=127.0.0.1 port=59976",,,,,,,,,""
2021-02-23 16:45:00.060 CST,"repl","",2396,"127.0.0.1:59976",6034c08c.95c,2,"authentication",2021-02-23 16:45:00 CST,4/35,0,LOG,00000,"replication connection authorized: user=repl",,,,,,,,,""
2021-02-23 16:45:00.061 CST,"repl","",2396,"127.0.0.1:59976",6034c08c.95c,3,"idle",2021-02-23 16:45:00 CST,,0,LOG,00000,"disconnection: session time: 0:00:00.001 user=repl database= host=127.0.0.1 port=59976",,,,,,,,,""
2021-02-23 16:45:05.060 CST,,,2397,"127.0.0.1:59980",6034c091.95d,1,"",2021-02-23 16:45:05 CST,,0,LOG,00000,"connection received: host=127.0.0.1 port=59980",,,,,,,,,""
2021-02-23 16:45:05.060 CST,"repl","",2397,"127.0.0.1:59980",6034c091.95d,2,"authentication",2021-02-23 16:45:05 CST,4/36,0,LOG,00000,"replication connection authorized: user=repl",,,,,,,,,""
2021-02-23 16:45:05.062 CST,"repl","",2397,"127.0.0.1:59980",6034c091.95d,3,"idle",2021-02-23 16:45:05 CST,,0,LOG,00000,"disconnection: session time: 0:00:00.002 user=repl database= host=127.0.0.1 port=59980",,,,,,,,,""

--patroni config
[postgres@localhost ~]$ patronictl show-config
loop_wait: 5
maximum_lag_on_failover: 1048576
postgresql:
  parameters: null
  remove_data_directory_on_rewind_failure: true
  use_pg_rewind: true
retry_timeout: 10
ttl: 20

[postgres@localhost ~]$ 

I checked if I set all nodes with no archive, the problem will not happen. Auto failover always sucess.

So seems this is relate to pg archive config, is this a bug or any other config need I do？
I not config restore_comand.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
- Patroni version:
- PostgreSQL version:
- DCS (and its version):

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**

**Comment by CyberDem0n** [comment]
There is no issue with Patroni, please in future use the slack.

**Comment by hunterhuang8810** [comment]
> There is no issue with Patroni, please in future use the slack.

why do you close my log? please confirm, you can't always confirm there's no any bug

**Comment by hunterhuang8810** [comment]
> There is no issue with Patroni, please in future use the slack.

If no issue, please help to find out the cause

**Comment by hunterhuang8810** [comment]
> There is no issue with Patroni, please in future use the slack.

If you dun't want to check , can someone else help to check? I think this is maybe a bug

please dun't close this with no any action.

**Comment by CyberDem0n** [comment]
Since you always ignore requirements of the issue template there is nothing I can help with.

**Comment by hunterhuang8810** [comment]
> Since you always ignore requirements of the issue template there is nothing I can help with.

OK, let me re-submit it with the template.

I will paste everything, as our company env can't upload file, so I can only paste contents.

If I submit as template, please dun't close directly , I think it's a potential bug.

**Comment by CyberDem0n** [comment]
There is no bug. You just do something wrong (again!).

If you don't want to be ignored, you really have to provide self-containted example based on the config files from the repo.
There is even commented out section with archive_command and recovery_command: https://github.com/zalando/patroni/blob/master/postgres0.yml#L64-L68
And if I uncomment it, everything still works as expected (surprise!).

**Comment by hunterhuang8810** [comment]
My config file is just modified from repo.

[postgres@localhost patroni]$ cat patroni.yml 
scope: pgsql
namespace: /service/
name: pg01

restapi:
  listen: 192.168.56.94:8008
  connect_address: 192.168.56.94:8008
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: password

# ctl:
#   insecure: false # Allow connections to SSL sites without certs
#   certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#   cacert: /etc/ssl/certs/ssl-cacert-snakeoil.pem

etcd:
  #Provide host to do the initial discovery of the cluster topology:
  hosts: 192.168.56.91:2379,192.168.56.92:2379,192.168.56.93:2379
  #Or use "hosts" to provide multiple endpoints
  #Could be a comma separated string:
  #hosts: host1:port1,host2:port2
  #or an actual yaml list:
  #hosts:
  #- host1:port1
  #- host2:port2
  #Once discovery is complete Patroni will use the list of advertised clientURLs
  #It is possible to change this behavior through by setting:
  #use_proxies: true

#raft:
#  data_dir: .
#  self_addr: 127.0.0.1:2222
#  partner_addrs:
#  - 127.0.0.1:2223
#  - 127.0.0.1:2224

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 20
    loop_wait: 5
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    master_start_timeout: 300
#    synchronous_mode: false
    #standby_cluster:
      #host: 127.0.0.1
      #port: 1111
      #primary_slot_name: patroni
    postgresql:
      use_pg_rewind: true
      remove_data_directory_on_rewind_failure: true
#      use_slots: true
      parameters:
#        max_connections:88   ???????max_connections,??show-config????
#        wal_level: hot_standby
#        hot_standby: "on"
#        wal_keep_segments: 8
#        max_wal_senders: 10
#        max_replication_slots: 10
#        wal_log_hints: "on"
#        archive_mode: "on"
#        archive_timeout: 1800s
#        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
#      recovery_conf:
#        restore_command: cp ../wal_archive/%f %p

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  # For kerberos gss based connectivity (discard @.*$)
  #- host replication replicator 127.0.0.1/32 gss include_realm=0
  #- host all all 0.0.0.0/0 gss include_realm=0  
  - host replication repl 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5
#  - hostssl all all 0.0.0.0/0 md5

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

  # Some additional users users which needs to be created after initializing new cluster
#  users:
#    admin:
#      password: admin
#      options:
#        - createrole
#        - createdb

postgresql:
  listen: 0.0.0.0:54322
  connect_address: 192.168.56.94:54322
  data_dir: /home/service/var/pgdata
  bin_dir: /usr/local/postgresql_12.5/bin
#  bin_dir:
#  config_dir:
  pgpass: /home/postgres/patroni/pgpassfile     
  authentication:
    replication:
      username: repl
      password: "RpDevNuae2685Juead"
    superuser:
      username: postgres
      password: "PgDevade68Jup685je"
  # Server side kerberos spn
#  krbsrvname: postgres
  parameters:
    # Fully qualified kerberos ticket file for the running user
    # same as KRB5CCNAME used by the GSS
#   krb_server_keyfile: /var/spool/keytabs/postgres
    #unix_socket_directories: '.'
  # Additional fencing script executed after acquiring the leader lock but before promoting the replica
  #pre_promote: /path/to/pre_promote.sh
  callbacks:
    on_role_change: /bin/bash /home/postgres/patroni/scripts/pg_role_change.sh   

#watchdog:
#  mode: automatic # Allowed values: off, automatic, required
#  device: /dev/watchdog
#  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
[postgres@localhost patroni]$ 

so you mean I must config archive and recover option in patroni config file? if I not set in patroni config file but setup in postgres config file, it will not work?

**Comment by hunterhuang8810** [comment]
I can't upload file as our company rule, so only can paste

**Comment by CyberDem0n** [comment]
Self-containted reproducable case please.

**Comment by hunterhuang8810** [comment]
> Self-containted reproducable case please.

If I config archive option in postgresql.base.conf rather than in patroni config,  will cause this problem?

If I setup archive option while not setup restore_command, will cause this?

my env is static db with no data change, why auto failed ？ before shutdown leader all nodes work well with no any lag.

could you answer these questions?

**Comment by hunterhuang8810** [comment]
I think it's a bug

**Comment by CyberDem0n** [comment]
> If I config archive option in postgresql.base.conf rather than in patroni config, will cause this problem?

No

> If I setup archive option while not setup restore_command, will cause this?

No. Why should one do that anyway?

> my env is static db with no data change, why auto failed ？ before shutdown leader all nodes work well with no any lag.

Have you checked that the replica was really streaming? When postgres is shutdown cleanly all replicas (that are streaming) end up EXACTLY on the same LSN as the former primary.

**Comment by CyberDem0n** [comment]
> I think it's a bug

Self-containted reproducable case please.

**Comment by hunterhuang8810** [comment]
-------before shutdown ---------
[postgres@localhost pgdata]$ patronictl list
+ Cluster: pgsql (6932366804563343747) --+---------+----+-----------+
| Member | Host                | Role    | State   | TL | Lag in MB |
+--------+---------------------+---------+---------+----+-----------+
| pg01   | 192.168.56.94:54322 | Replica | running |  4 |         0 |
| pg02   | 192.168.56.95:54322 | Leader  | running |  4 |           |
| pg03   | 192.168.56.96:54322 | Replica | running |  4 |         0 |
+--------+---------------------+---------+---------+----+-----------+
[postgres@localhost pgdata]$ 

postgres=# select * from pg_stat_replication ;
-[ RECORD 1 ]----+------------------------------
pid              | 2268
usesysid         | 16384
usename          | repl
application_name | pg03
client_addr      | 192.168.56.96
client_hostname  | 
client_port      | 36666
backend_start    | 2021-02-23 17:35:46.690986+08
backend_xmin     | 
state            | streaming
sent_lsn         | 0/10000288
write_lsn        | 0/10000288
flush_lsn        | 0/10000288
replay_lsn       | 0/10000288
write_lag        | 00:00:00.000468
flush_lag        | 00:00:00.001175
replay_lag       | 00:00:00.001403
sync_priority    | 0
sync_state       | async
reply_time       | 2021-02-23 17:37:14.398883+08
-[ RECORD 2 ]----+------------------------------
pid              | 2267
usesysid         | 16384
usename          | repl
application_name | pg01
client_addr      | 192.168.56.94
client_hostname  | 
client_port      | 52428
backend_start    | 2021-02-23 17:35:45.41354+08
backend_xmin     | 
state            | streaming
sent_lsn         | 0/10000288
write_lsn        | 0/10000288
flush_lsn        | 0/10000288
replay_lsn       | 0/10000288
write_lag        | 00:00:00.00054
flush_lag        | 00:00:00.001134
replay_lag       | 00:00:00.00125
sync_priority    | 0
sync_state       | async
reply_time       | 2021-02-23 17:37:14.398309+08

postgres=# 

---------------------------archive options in postgresql.base.conf, I added restore_comand this time------------
archive_mode = always
archive_command = 'test ! -f /home/service/var/pgdata/archivedir/%f && cp %p /home/service/var/pgdata/archivedir/%f'
archive_timeout = '5min'

restore_command = 'cp /home/service/var/pgdata/archivedir/%f "%p"'


-----shutdown leader machine
[root@localhost ~]# init 0

---after shutdown
[postgres@localhost patroni]$ patronictl list
+ Cluster: pgsql (6932366804563343747) --+---------+----+-----------+
| Member | Host                | Role    | State   | TL | Lag in MB |
+--------+---------------------+---------+---------+----+-----------+
| pg01   | 192.168.56.94:54322 | Replica | running |  4 |        16 |
| pg03   | 192.168.56.96:54322 | Replica | running |  4 |        16 |
+--------+---------------------+---------+---------+----+-----------+
[postgres@localhost patroni]$ 

----patroni log---
2021-02-23 17:39:56,488 INFO: My wal position exceeds maximum replication lag
2021-02-23 17:39:56,495 INFO: following a different leader because i am not the healthiest node
2021-02-23 17:40:01,497 INFO: My wal position exceeds maximum replication lag
2021-02-23 17:40:01,526 INFO: following a different leader because i am not the healthiest node
2021-02-23 17:40:06,487 INFO: My wal position exceeds maximum replication lag
2021-02-23 17:40:06,495 INFO: following a different leader because i am not the healthiest node
2021-02-23 17:40:11,488 INFO: My wal position exceeds maximum replication lag
2021-02-23 17:40:11,496 INFO: following a different leader because i am not the healthiest node
2021-02-23 17:40:16,489 INFO: My wal position exceeds maximum replication lag
2021-02-23 17:40:16,496 INFO: following a different leader because i am not the healthiest node

**Comment by hunterhuang8810** [comment]
I think this is bug, 

1. before shutdown no lag, static db , after shutdown showed 16, this is incorrect
2. maybe it do caused by wrong check for lag, so report wal position exceeds maximum replication lag,  maximum_lag_on_failover: 1048576. so auto-failover failed.

**Comment by hunterhuang8810** [comment]
-----postgresql.base.conf
[postgres@localhost pgdata]$ cat postgresql.base.conf
# -----------------------------
# PostgreSQL configuration file
# Patroni控制的参数保存在DCS中，同时会dump到postgresql.conf
# postgresql.conf文件不要编辑修改
# postgresql.base.conf文件保存除DCS中以外的PG参数
# -----------------------------

#data_directory = 'ConfigDir'                    不需要配置，patroni配置文件中指定
#hba_file = 'ConfigDir/pg_hba.conf'                  默认，不需要配置
#listen_addresses = '0.0.0.0'                    patroni.yml中配置

superuser_reserved_connections = 10
unix_socket_directories = '/tmp'
unix_socket_permissions = 0700
#authentication_timeout = 1min                  默认值为1min,不需要调整
#ssl = off                                      默认为off，不需要调整
tcp_keepalives_idle = 60
tcp_keepalives_interval = 10
tcp_keepalives_count = 10

temp_buffers = 128MB

shared_preload_libraries = 'pg_stat_statements,auto_explain,pgsentinel,pg_squeeze'   
#max_files_per_process = 1000                  默认值为1000，不需要修改
#max_locks_per_transaction = 64                DCS中配置
temp_file_limit = 15GB
#track_io_timing = off
track_functions = pl
track_activity_query_size = 10240           

pg_stat_statements.max = 10000                # 在pg_stat_statements中最多保留多少条统计信息，通过LRU算法，覆盖老的记录。  
pg_stat_statements.track = all                # all - (所有SQL包括函数内嵌套的SQL), top - 直接执行的SQL(函数内的sql不被跟踪), none - (不跟踪)
pg_stat_statements.track_utility = on         # 是否跟踪非DML语句 (例如DDL，DCL)，on表示跟踪, off表示不跟踪  
pg_stat_statements.save = on                  # 重启后是否保留统计信息  

auto_explain.log_min_duration = '1s'
auto_explain.log_nested_statements =on   

#max_worker_processes = 256                           DCS配置
bgwriter_delay = 20ms                          

#wal_level = replica                                  DCS中配置
wal_compression = on                     
fsync = on                                   
synchronous_commit = local               
wal_buffers = 16MB

#checkpoint_completion_target = 0.5               默认值为 0.5，不需要修改
#checkpoint_warning = 30s                             默认值为 30s，不需要修改

#archive_mode = off                                 
archive_mode = always                               
archive_command = 'test ! -f /home/service/var/pgdata/archivedir/%f && cp %p /home/service/var/pgdata/archivedir/%f'
archive_timeout = '5min'                 

restore_command = 'cp /home/service/var/pgdata/archivedir/%f "%p"'

#cluster_name = 'pcfcrs'                            在patroni.yml中配置

#max_wal_senders = 64                   DCS中配置
#wal_keep_segments = 10                     DCS中配置***
#hot_standby = on                                   patroni默认打开，不需要配置

#max_replication_slots = 10                 DCS中配置 
#track_commit_timestamp = off           DCS中配置
log_destination = 'csvlog'
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%d.log'
log_truncate_on_rotation = on
log_line_prefix = '%t:%r:%u@%d:[%p]: '
log_statement = 'ddl'
log_checkpoints = on
log_connections = on
log_disconnections = on

log_min_duration_statement = 1000
log_lock_waits = on
log_timezone = 'PRC'     
log_autovacuum_min_duration = 1000
  
datestyle = 'iso, mdy'
timezone = 'PRC'        
lc_messages = 'en_US.UTF-8'                     # locale for system error message
lc_monetary = 'en_US.UTF-8'                     # locale for monetary formatting
lc_numeric = 'en_US.UTF-8'                      # locale for number formatting
lc_time = 'en_US.UTF-8'                         # locale for time formatting
default_text_search_config = 'pg_catalog.english'
      
random_page_cost = 1.1                 # 离散IO很好的机器（例如ssd, nvme ssd），不需要考虑离散和顺序扫描的成本差异 
search_path = 'public'  # schema names
# 如果要使用pg_rewind，flashback 时间线，需要打开这个功能    
# [《PostgreSQL pg_rewind，时间线修复，脑裂修复，flashback - 从库开启读写后，回退为只读从库。异步主从发生角色切换后，主库rewind为新主库的从库》](201901/20190128_02.md)      
##wal_log_hints = on                      DCS中配置

autovacuum_max_workers = 5              # max number of autovacuum subprocesses
vacuum_freeze_table_age = 1500000000
vacuum_multixact_freeze_table_age = 1500000000
old_snapshot_threshold = 3h             # 1min-60d; -1 disables; 0 is immediate
autovacuum_vacuum_cost_limit = 1000     # default vacuum cost limit for
autovacuum_vacuum_cost_delay = 10ms

idle_in_transaction_session_timeout = 2h        # in milliseconds, 0 is disabled
vacuum_cost_page_miss = 5               # 0-10000 credits
vacuum_cost_page_dirty = 10             # 0-10000 credits
max_wal_size =48GB
min_wal_size =12GB
max_parallel_maintenance_workers = 4
work_mem = 128MB

##动态参数##
#port = 5432                                     patroni.yml中配置 
#max_connections = 2000                              DCS中配置
shared_buffers = 1GB                                    # shared_buffers 公式： IF use hugepage: 主机内存*(1/4) ELSE: min(32GB, 主机内存*(1/4)) 
#max_prepared_transactions =2000  DCS中配置
maintenance_work_mem = 1GB                             #  公式： min( 8G, (主机内存*1/8)/max_parallel_maintenance_workers )  

[postgres@localhost pgdata]$ 


I dun't know why always shows lag 16, I checked wal_buffers = 16MB, dun't know whether relate with this?

**Comment by CyberDem0n** [comment]
How many more times should I repeat? You MUST provide the self-contained reproducable case!

**Comment by hunterhuang8810** [comment]
> How many more times should I repeat? You MUST provide the self-contained reproducable case!

 I can't upload file, and pasted contents is mix-showed.

**Comment by hunterhuang8810** [comment]
> > How many more times should I repeat? You MUST provide the self-contained reproducable case!
> 
> I can't upload file, and pasted contents is mix-showed.

I tested if I switch wal log on leader node before shutdown leader machine, the issue will not occur.

16M is just the Wal size 

---- 1 postgres postgres 16777216 Feb 23 18:42 0000000B0000000000000024
-rw------- 1 postgres postgres 16777216 Feb 23 18:42 0000000B0000000000000025
-rw------- 1 postgres postgres      427 Feb 23 18:36 0000000B.history
-rw------- 1 postgres postgres 16777216 Feb 23 18:44 0000000C0000000000000025
-rw------- 1 postgres postgres 16777216 Feb 23 18:34 0000000C0000000000000026
-rw------- 1 postgres postgres      471 Feb 23 18:42 0000000C.history
drwx------ 2 postgres postgres     4096 Feb 23 18:47 archive_status
[postgres@localhost pg_wal]$

**Comment by hunterhuang8810** [comment]
also tested if set maximum_lag_on_failover: 17825792, which is 17M

it will not occur
