### ISSUE TITLE
Patroni Leader Election Sequence during Auto Failover

### ISSUE THREAD

**Issue by Argha-2890** [zalando/patroni#1856]
Hi Team,

Patroni Version : 1.6.5

Just wanted to know whether it is possible to define any order for leader election during the auto failover process. Currently we have nodes configured across different regions and one of them is functioning slower than the rest. So, we want that region to be the last option for master election.

Furthermore, we don't want to use the "**nofailover**" tag as that completely disables the feature.  Also, in case we increase the **"ttl"** time for that specific node, would that be a good workaround?

**Comment by CyberDem0n** [comment]
There is no such option and I don't plan to work on this.

**Comment by Argha-2890** [comment]
Fair enough . Does increasing the ttl value for the specific node help in this scenario?

**Comment by CyberDem0n** [comment]
The `ttl` value controls the expiration time of the leader key in the DCS. Cluster nodes are watching to the leader key, and get notified at the same time when it expired.

**Comment by Argha-2890** [comment]
@CyberDem0n - In case I mark `nofailover:True` for a specific node. In case rest of the nodes are down in the cluster will the said node become leader automatically or do we have to manually elect it as a leader.

**Comment by CyberDem0n** [comment]
The node with `nofailover: true` will never become the leader. Neither automatically nor manually.
