### ISSUE TITLE
How to make Major postgresql upgrade in patroni raft cluster

### ISSUE THREAD

**Issue by oleg9301** [zalando/patroni#1861]
We have next doc about major upgrade - https://patroni.readthedocs.io/en/latest/existing_data.html
And it works fine every time in patroni + etcd cluster

But when i have paroni + raft cluster(2 patroni node + 1 patroni_raft_controller) i have problem on step 4
`Remove the initialize key from DCS or wipe complete cluster state from DCS. The second one could be achieved by running patronictl remove <cluster-name>`

After step 1(stop patroni) we dont have quorum, and "patronictl remove"  doesn't work.

How to make major upgrade postgresql in cluster 2 patroni with 1 patroni_raft_controller ?

**Comment by CyberDem0n** [comment]
Removing raft dump and journal file should help (you need to stop all components for that)
