### ISSUE TITLE
Follower cluster

### ISSUE THREAD

**Issue by jamessewell** [zalando/patroni#1863]
I have two Kubernetes clusters and I am trying to work out how to operate Patroni between them.

Consider this example:

SiteA - two PG pods
SiteB - two PG pods

Ideally when I denote siteA as active it will have the master. siteB will not elect a master, but will instead replicate async from siteA.

Later on, if siteA fails I can manually cause siteB to elect a master and become active.

At a later time I can connect siteA to siteB (hopefully without much intervention, ie: using Patroni pg_rewind capabilities).

All this seems possible (I think the Patroni pause function can work at siteB? Or could I just have all instances pointing at the siteA etcd, then flip to siteB when I need to?), but I'm just not sure how much of it I can do without scripting things myself. Is any of this supported out of the box?

Cheers,
James

**Comment by CyberDem0n** [comment]
> Ideally when I denote siteA as active it will have the master. siteB will not elect a master, but will instead replicate async from siteA.

Yes, it is possible. SiteB should be configured to run as a [standby cluster](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#standby-cluster).

> Later on, if siteA fails I can manually cause siteB to elect a master and become active.

For that you need to remove the `standby_cluster` section from the global configuration with the help of `patronictl edit-config` and one of the nodes will promote (most likely the standby_leader).

> At a later time I can connect siteA to siteB (hopefully without much intervention, ie: using Patroni pg_rewind capabilities).

This is also possible. You need to create the standby_cluster section in the global configuration which points to the siteB.

> All this seems possible (I think the Patroni pause function can work at siteB? Or could I just have all instances pointing at the siteA etcd, then flip to siteB when I need to?),

IMO, it is better to keep siteA and siteB isolated from each other. Only two points of contact are reuiqred. The first one - a single endpoint for replication/pg_rewind (it must connect to the primary on the other side). And the second - the custom `standby_cluster.restore_command`, which should restore WAL files from the remote site (every site should perform wal archiving to its own place).

> but I'm just not sure how much of it I can do without scripting things myself. Is any of this supported out of the box?

Certainly, some scripting is required, but it should not be hard and could be implemented on top of the `patronictl`.

P.S. if case if you swap roles of siteA and siteB, that would require converting the normal cluster to the standby cluster, and better if postgres is shutdown cleanly. There is a recipe: https://github.com/zalando/patroni/issues/1660#issuecomment-678124810
