### ISSUE TITLE
deploy patroni on Minikube

### ISSUE THREAD

**Issue by mgori24** [zalando/patroni#1867]
Gents, 
I'm testing Patroni manifest on Windows 10. Where I have Minikube installed. First, I built the image of Patroni from the Dockerfile from https://github.com/zalando/patroni/blob/master/kubernetes/Dockerfile.
 Then, I execute the kubectl to create from the manifest on this link: https://github.com/zalando/patroni/blob/master/kubernetes/patroni_k8s.yaml.
 I had an error of Missing property "selector". So I added the selector. After that I used kubectl create after the file update. I have error of Image bulling back. So I create a docker image and push it docker hub and then I updated the manifest to use the image that I created. Now I have the below error
/entrypoint.sh: line 2: $'\r': command not found
/entrypoint.sh: line 38: syntax error: unexpected end of file

for the entrypoint.sh I used the following file https://github.com/zalando/patroni/blob/master/kubernetes/entrypoint.sh.
Would please support or advice.

**Comment by CyberDem0n** [comment]
There was a similar complaint about the docker-compose: https://github.com/zalando/patroni/issues/1841
Since I neither use Windows myself nor have it available for testing the stuff, I have absolutely no idea what is wrong with Docker on Windows.

**Comment by mbanck** [comment]
Well, I get the same error about "selector" using minikube on Linux; I think it's probably a patroni <-> k8s issue?
```
patroni/kubernetes$ kubectl apply -f patroni_k8s.yaml 
service/patronidemo-config unchanged
error: error validating "patroni_k8s.yaml": error validating data: ValidationError(StatefulSet.spec): missing required field "selector" in io.k8s.api.apps.v1.StatefulSetSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by CyberDem0n** [comment]
@mbanck the issue is in the yaml file in the StatefulSet definition.
You need to add the following to the spec:
```diff
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
   name: &cluster_name patronidemo
   labels:
     application: patroni
     cluster-name: *cluster_name
 spec:
+  selector:
+    matchLabels:
+      application: patroni
+      cluster-name: *cluster_name
   replicas: 3
   serviceName: *cluster_name
```

Before the StatefulSet became GA it didn't require a label selector, and it seems that I forgot to add it when [bumped](https://github.com/zalando/patroni/commit/db8c634db3c1059c4ae4b48903ec44157f5db2ca#diff-2b6aaa019dd025da52d255d5e7bce998341bdd654ea027f5cd39549bf37b5a7bR13) the apiVersion

**Comment by mbanck** [comment]
Right, I had this comment open/pending when I went through my open browser tabs and apparently never send it. I had fixed it up like you said and now created a PR if that's helpful.
