### ISSUE TITLE
Patroni Master failed,Unable to start it

### ISSUE THREAD

**Issue by Kumar6295** [zalando/patroni#1869]
We are running 3 etcd nodes and two patroni nodes.
few days back patroni slave node was failed unable to replicate,So we remove slave try make new slave at the point of time master database (patroni) storage was full. 
Patroni cluster failed.
Now,Storage issue is resolved.Try to start patroni service.it is showing below error

2021-03-09 16:14:39,158 INFO: establishing a new patroni connection to the postgres cluster
2021-03-09 16:14:39,159 WARNING: Retry got exception: 'connection problems'
2021-03-09 17:45:16,938 INFO: Selected new etcd server http://ipAddress:2379
2021-03-09 17:45:17,205 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-03-09 17:45:17,312 INFO: establishing a new patroni connection to the postgres cluster
2021-03-09 17:45:17,664 INFO: establishing a new patroni connection to the postgres cluster
2021-03-09 17:45:17,665 WARNING: Retry got exception: 'connection problems'
2021-03-09 17:55:18,345 INFO: Selected new etcd server http://ipAddress:2379
2021-03-09 17:55:18,352 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-03-09 17:55:18,361 INFO: establishing a new patroni connection to the postgres cluster
2021-03-09 17:55:18,852 INFO: establishing a new patroni connection to the postgres cluster
2021-03-09 17:55:18,853 WARNING: Retry got exception: 'connection problems'
ipAddress:etcd-3 node ip 

**Patroni services status**

 systemctl status patroni 
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/etc/systemd/system/patroni.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2021-03-09 18:05:19 IST; 1min 57s ago
  Process: 21046 ExecStart=/usr/local/bin/patroni /etc/patroni.yml (code=exited, status=1/FAILURE)
 Main PID: 21046 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/patroni.service
           └─13085 /usr/pgsql-11/bin/postgres --single -D /pgdata/patroni -c archive_command=false -c archive_mode=on -c cluster_name=postgres -c config-file=/pgdata/patroni/postgresql.conf -c hot_standby=on -c listen_addresses=0.0.0.0 -c max_connections=1000 -c max_locks_per_transaction=256 -c max_prepared_transactions=0 -c max_replication_slots=30 -c max_wal_senders=30 -c max_worker_processes=16 -c port=5432 -c track_commit_timestamp=off -c wal_level=logical -c wal_log_hints=on template1

Mar 09 18:05:19 hostname systemd[1]: patroni.service: main process exited, code=exited, status=1/FAILURE
Mar 09 18:05:19 hostname systemd[1]: Unit patroni.service entered failed state.
Mar 09 18:05:19 hostname systemd[1]: patroni.service failed.

**Comment by CyberDem0n** [comment]
I bet you are using some old version of Patroni, please upgrade to 2.0.2.

**Comment by Kumar6295** [comment]
we are using patroni version 2.0.0,Suppose we upgrade the patroni,Is it solve problem????

**Comment by CyberDem0n** [comment]
https://github.com/zalando/patroni/commit/fa88d80c4f65a8ae5b48729eb598d7bf22923f2d fixes it

**Comment by Kumar6295** [comment]
Master_start_timeout default value is 300 sec, what value we need set up..
When we try to start patroni service using systemctl..
Immediately logs generating like below and service showing activating..


2021-03-09 17:55:18,345 INFO: Selected new etcd server http://ipAddress:2379
2021-03-09 17:55:18,352 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-03-09 17:55:18,361 INFO: establishing a new patroni connection to the postgres cluster
2021-03-09 17:55:18,852 INFO: establishing a new patroni connection to the postgres cluster
2021-03-09 17:55:18,853 WARNING: Retry got exception: 'connection problems'

**Comment by Kumar6295** [comment]
Now changed master_start_timeout to 600 sec in patroni.yml file.
After that try to start patroni.service at the time it showing like below.patroni service is failing 

**patroni.exceptions.PostgresConnectionException: "'Too many retry attempts'"**

 **patroni.service**
 patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/etc/systemd/system/patroni.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2021-03-10 10:25:34 IST; 3s ago
  Process: 12443 ExecStart=/usr/local/bin/patroni /etc/patroni.yml (code=exited, status=1/FAILURE)
 Main PID: 12443 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/patroni.service
           └─13085 /usr/pgsql-11/bin/postgres --single -D /pgdata/patroni -c archive_command=false -c archive_mode=on -c cluster_name=postgres -c config-file=/pgdata/patroni/postgresql.conf -c hot_standby=on -c listen_addresses=0.0.0.0 -c max_connections=1000 -c max_locks_per_transaction=256 -c max_prepared_transactions=0 -c max_replication_slots=30 -c max_wal_senders=30 -c max_worker_processes=16 -c port=5432 -c track_commit_timestamp=off -c wal_level=logical -c wal_log_hints=on template1

Mar 10 10:25:34  patroni[12443]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 111, in __init__
Mar 10 10:25:34  patroni[12443]: self.set_role('master' if self.is_leader() else 'replica')
Mar 10 10:25:34  patroni[12443]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 338, in is_leader
Mar 10 10:25:34  patroni[12443]: return bool(self._cluster_info_state_get('timeline'))
Mar 10 10:25:34  patroni[12443]: File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 318, in _cluster_info_state_get
Mar 10 10:25:34  patroni[12443]: raise PostgresConnectionException(self._cluster_info_state['error'])
Mar 10 10:25:34  patroni[12443]: patroni.exceptions.PostgresConnectionException: "'Too many retry attempts'"
Mar 10 10:25:34  systemd[1]: patroni.service: main process exited, code=exited, status=1/FAILURE
Mar 10 10:25:34  systemd[1]: Unit patroni.service entered failed state.
Mar 10 10:25:34  systemd[1]: patroni.service failed.


**patroni logs**
2021-03-10 10:25:34 INFO: Selected new etcd server http://ipAddress:2379
2021-03-10 10:25:34 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-03-10 10:25:34 INFO: establishing a new patroni connection to the postgres cluster
2021-03-10 10:25:34 INFO: establishing a new patroni connection to the postgres cluster
2021-03-20 10:25:34 WARNING: Retry got exception: 'connection problems

Patroni logs are generating when try to start patroni service.only once it is giving logs like above

**Comment by CyberDem0n** [comment]
> Now changed master_start_timeout to 600 sec in patroni.yml file.

Why? I was talking about upgrading Patroni. Was it done? There is not a single word about it.


> └─13085 /usr/pgsql-11/bin/postgres --single -D /pgdata/patroni -c archive_command=false -c archive_mode=on -c cluster_name=postgres -c config-file=/pgdata/patroni/postgresql.conf -c hot_standby=on -c listen_addresses=0.0.0.0 -c max_connections=1000 -c max_locks_per_transaction=256 -c max_prepared_transactions=0 -c max_replication_slots=30 -c max_wal_senders=30 -c max_worker_processes=16 -c port=5432 -c track_commit_timestamp=off -c wal_level=logical -c wal_log_hints=on template1

Please pay attention that PID didn't change since yesterday! Postgres clearly stuck in a single-user mode. It should be killed.

**Comment by Kumar6295** [comment]
Issue is resolved,Thank you so much
