### ISSUE TITLE
How to Convert patroni cluster to Standlone

### ISSUE THREAD

**Issue by Kumar6295** [zalando/patroni#1871]
our patroni cluster fully failed..We have data directory of patroni.
Can we set it as standalone postgresql?
What is the procedure to make standalone?

**Comment by CyberDem0n** [comment]
Like usual, pg_ctl start ...

**Comment by CyberDem0n** [comment]
Running HA system is like flying an airlainer.
Mostly autopilot, but you really have to know how to fly _manually_.
