### ISSUE TITLE
When force delete master pod, failover does not happen

### ISSUE THREAD

**Issue by MiaoRachelYu** [zalando/patroni#1872]
**Describe the bug**
When executing "kubectl delete pod <master-pod-name> -n <namespace> --force --grace-period=0" to kill master pod, the master pod is restarted with keeping the master role. Replica pod with sync standby role does not take the master role as a failover behavior.

**To Reproduce**
1. helm install service with at least two replicaCount
2. executing "kubectl delete pod <master-pod-name> -n <namespace> --force --grace-period=0" 

**Expected behavior**
Replica pod with sync standby role should take the master role.

**Environment**
- Patroni version: 1.6.3
- PostgreSQL version: 10.14

**Comment by CyberDem0n** [comment]
It takes up to `ttl` for the leader key to expire.
By forcefully killing the pod you leave no chance to Patroni to do the clean shutdown and release the leader key.
Also, Kubernetes is starting the replacement pod faster than the leader key expires.
The default behavior is to trying to start postgres on the failed leader. It could be changed by setting the [master_start_timeout](https://patroni.readthedocs.io/en/latest/SETTINGS.html#dynamic-configuration-settings) to 0.

Last, but not least, please upgrade Patroni.
