### ISSUE TITLE
lag issue

### ISSUE THREAD

**Issue by sandeepkalra** [zalando/patroni#1878]
This is more of query than a bug. We have multi-host setup and what we observe over time is that system starts having lags. They grow as the host machines get rebooted, and then the lagging containers fail to catch up. A typical setup with such problem will show this kind of situation

```
root@ab414858d9d9:/bp2/src# patronictl list
2021-03-12 18:51:40,319 - INFO - Connecting to 172.16.2.8:2181, use_ssl: False
2021-03-12 18:51:40,324 - INFO - Zookeeper connection established, state: CONNECTED
+ Cluster: postgres (6938686524203462765) -+----+-----------+-----------------+
| Member | Host        | Role    | State   | TL | Lag in MB | Tags            |
+--------+-------------+---------+---------+----+-----------+-----------------+
| pg_0   | 172.16.0.21 | Leader  | running |  4 |           | clonefrom: true |
| pg_1   | 172.16.1.9  | Replica | running |  2 |         0 | clonefrom: true |
| pg_2   | 172.16.2.5  | Replica | running |  2 |        13 | clonefrom: true |
+--------+-------------+---------+---------+----+-----------+-----------------+
```

It clears if we 'reinit' the lagging nodes. I would like to know what can be done to not see this issue in first place. It is some resource issue, or settings. Second, is there  a preventive way to force replicas to sync to master every x minutes (say 60 minutes).

**Comment by CyberDem0n** [comment]
I am 100% sure that postgres logs have an answer.
After you check logs I would insistent on reading the postgres documentation: https://www.postgresql.org/docs/current/high-availability.html

**Comment by sandeepkalra** [comment]
Thanks @CyberDem0n .. I will do the reading and look for the gaps.
