### ISSUE TITLE
Dual stack check is not correct on the ipv4 stack cluster.

### ISSUE THREAD

**Issue by Telzeng** [zalando/patroni#1880]
**Describe the bug**
dual stack check is not correct that cause patroni start a service of API failure. There are two issues:

issue 1.
In my cluster,  there is only support Ipv4 and dual stack should be disable and. but when the code call self.__has_dual_stack(), it will get the return value True. Then patroni will choose ipv6 family as self.address_family. 
So the start service failure.

issue 2.

There is comment in the code that # in case dual stack is not supported we want IPv4 to be preferred over IPv6.

In my view, if the cluster does not support dual stack, it should be single stack either ipv4 or ipv6.  so patroni should have no choice to IPv4 over IPv6.

code from patroni/api.py:
`

def __httpserver_init(self, host, port):
--
675 | dual_stack = self.__has_dual_stack()
676 | if host in ('', '*'):
… |  
680 | # in case dual stack is not supported we want IPv4 to be preferred over IPv6
681 | info.sort(key=lambda x: x[0] == socket.AF_INET, reverse=not dual_stack)
682 |  
683 | self.address_family = info[0][0]

`
 
/etc/hosts file:
/> cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
- Patroni version: 2.0.2
- PostgreSQL version: 10.5
- DCS (and its version): kubernetes 1.18

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here
################## debug
2021-03-15 05:23:48,880 INFO: No PostgreSQL configuration items changed, nothing to reload.
debug.......reload_config......config is {'listen': 'localhost:8008', 'connect_address': 'localhost:8008'}
debug..............host is %s localhost
debug..............port is %s 8008
debug..............dual_stack is %s True
debug..............info is %s [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 8008)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 8008, 0, 0))]
debug..............info is %s [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 8008, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 8008))]
2021-03-15 05:23:48,888 INFO: Selected address family is AddressFamily.AF_INET6
2021-03-15 05:23:48,889 ERROR: Couldn't start a service on 'localhost:8008', please check your `restapi.listen` configuration
Traceback (most recent call last):
  File "/var/lib/postgresql/patroni.py", line 6, in <module>

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**

**Comment by CyberDem0n** [comment]
The rest api must be accessible from other nodes in the cluster, by setting the listen_address/connect_address to localhost you violate it.

You can easily force Patroni to listen only on IPv4 by specifying the proper in the listen_address to listen on.

**Comment by Telzeng** [comment]
Hi, 

@CyberDem0n, thanks for your reply.
Considering the security case, we want to access to rest API only for localhost and then set the localhost as listen_address/connect_address.
Two questions here:
1. How to set IP faimily type as listen_address when dual stack enable for patroni. 
2. In above case, dual stack check is true. But the cluster does not support ipv6. Is the checker right?

Thanks
Zeng

**Comment by CyberDem0n** [comment]
> Considering the security case, we want to access to rest API only for localhost

REST API **must** be accessible from all members of the cluster, and it is documented: https://patroni.readthedocs.io/en/latest/SETTINGS.html#rest-api
If you want/need to protect it, it is possible to enable SSL and basic auth.

> How to set IP faimily type as listen_address when dual stack enable for patroni.

I already told you, you have to specify the exact IP to listen on. If the IP is from family 4, it will not try to listen on IPv6.

> dual stack check is true. But the cluster does not support ipv6. Is the checker right?

The check is absolutely correct.

**Comment by Telzeng** [comment]
As i know, if specify the IP as localhost.,  other work member will be not accessable to it.  Does it have other impact on patroni cluster?
Or which scenario need access to other member via RestAPI.
BTW My patroni worked well as following setting.
PATRONI_RESTAPI_CONNECT_ADDRESS="localhost:8008"
PATRONI_RESTAPI_LISTEN="localhost:8008"
 
Thanks
Zeng.

**Comment by CyberDem0n** [comment]
> Does it have other impact on patroni cluster?

YES! Rest API is used during the leader race.

**Comment by Telzeng** [comment]
Some confusions for me,  leader race seems no problem when setting the CONNECT_ADDRESS as localhost as above. Both HA and failover function are well. 
Why does RestAPI impact the leader race here?  Could you give me details about leader race.

Thanks
Zeng

**Comment by CyberDem0n** [comment]
Leader race is a part of failover and it requires that any node in the cluster is able to connect to any other node via REST API.
Without such connections not the most up-to-date node could become the leader.
