### ISSUE TITLE
Question: interaction between patroni.service and postgresql.service

### ISSUE THREAD

**Issue by edysli** [zalando/patroni#1881]
**How is Patroni designed to start/stop PostgreSQL?**

I've been running PostgreSQL with streaming replication so far and it is managed by systemd through the (package-provided) `postgresql-12.service` unit. I'm trying to introduce Patroni in this setup and noticed that sometimes it sees PostgreSQL processes started by systemd and does nothing and sometimes kills them to restart them itself (they then appear under the same cgroup when running `systemctl status patroni.service`.

So I'm wondering: are Patroni itself and `patroni.service` designed to work in combination with `postgresql-12.service` or should the latter be disabled to let Patroni directly manage `postmaster`? The ["Convert a Standalone to a Patroni Cluster" procedure](https://patroni.readthedocs.io/en/latest/existing_data.html#convert-a-standalone-to-a-patroni-cluster) in the documentation implies that Patroni can live with a PostgreSQL instance that it hasn't itself started ("1. Manually start PostgreSQL daemon").

**Environment**
- Patroni version: 2.0.2
- PostgreSQL version: 12.6
- DCS (and its version): Consul 1.9.4

**Have you tried to use GitHub issue search?**
Yes, I didn't find anything answering my question there nor in the project's documentation at https://patroni.readthedocs.io/en/latest/.

**Comment by CyberDem0n** [comment]
It is a task of Patroni to start/stop/restart Postgres with very specific configuration, therefore postgresql.service must be disabled.

**Comment by edysli** [comment]
Thanks for the clarification. :smiley:
