### ISSUE TITLE
Patroni creates unexpected physical slot

### ISSUE THREAD

**Issue by L30M4GN4** [zalando/patroni#1882]
We've faced an issue with overflowing disk space by WAL logs, so we've wrote script to check disk space and send request to patroni to delete replication slot.
The part where request executes:
`url = 'http://patroni/config'
    payload = {
        "slots":
            {
                current_slot_info_['slot_name']: null
            }
    }
    try:
        request_for_deletion = requests.patch(url, data=json.dumps(payload))`
      
So one day our disk space start grow until amount more than we expected.
Investigating this issue, we found that for some reason slot's type changed from logical to physical.

Also we've found that right at the same moment when script sends a request to patroni to kill slot, patroni wrote in logs "Failed to create physical replication slot 'slot_name'" with the same name, as logical slot had.

May be related:
Response at this deletion request, during manual replication of this issue, shows that "slots" dict from patroni config is empty. But right after that we send GET request to http://patroni/config and in response we've found "slots" dict with '"slot_name":null' in it. Also this slot was not deleted from Postgres itself (but type still was logical). If we were trying to delete it manually, we gets error that this slot was used by wal_getter process. After killing this process we were able to kill this slot manually, but not with patroni.

We are not able to reproduce this issue

**Comment by CyberDem0n** [comment]
Patroni only creates slots that represent cluster members and slots that are configured in the dynamic configuration.
Anyone with replication credentials could create a slot via the replication protocol: https://www.postgresql.org/docs/current/protocol-replication.html#PROTOCOL-REPLICATION-CREATE-SLOT

Also, your PATCH request is broken. Removing the "slot_name" from the dynamic configuration would look like: `{"slots": {"slot_name": null}}`

**Comment by L30M4GN4** [comment]
> Patroni only creates slots that represent cluster members and slots that are configured in the dynamic configuration.
> Anyone with replication credentials could create a slot via the replication protocol: https://www.postgresql.org/docs/current/protocol-replication.html#PROTOCOL-REPLICATION-CREATE-SLOT
> 
> Also, your PATCH request is broken. Removing the "slot_name" from the dynamic configuration would look like: `{"slots": {"slot_name": null}}`

Yes, that's exactly how it looks like. `current_slot_info_['slot_name']` = "slot_name".
Or you mean that it's incorrect?

**Comment by CyberDem0n** [comment]
> Or you mean that it's incorrect?

Does it produce a JSON that looks like my example?

The global configuration and slots are not the right tool for removing unexpected slots. The slot you have been fighting with wasn't created by Patroni.

**Comment by CyberDem0n** [comment]
Maybe it is not very clear, but Patroni implements JSON Merge Patch: https://tools.ietf.org/html/rfc7386

**Comment by L30M4GN4** [comment]
Ye

> > Or you mean that it's incorrect?
> 
> Does it produce a JSON that looks like my example?

Yes, it makes payload, which looks like `{"slots": {"slot_name": null}}`

> The global configuration and slots are not the right tool for removing unexpected slots. The slot you have been fighting with wasn't created by Patroni.

We creating slots using AWS lambda but we are asking there Patroni to create slot
Code:
`patroni_url = "http://patroni/config"
response = requests.patch(
                            patroni_url,
                            json={"slots": {"slot_name": {"type": "logical", "database": "database_name", "plugin": "test_decoding"}}},
                            headers={'Content-Type': 'application/json'},
                            verify=False,
                            timeout=3)`

**Comment by CyberDem0n** [comment]
```
~/git/patroni$ curl -s http://localhost:8008/config | jq .
{
  "loop_wait": 10,
  "maximum_lag_on_failover": 1048576,
  "postgresql": {
    "parameters": {
      "wal_level": "logical"
    },
    "use_pg_rewind": true
  },
  "retry_timeout": 10,
  "ttl": 30
}

~/git/patroni$ psql -h localhost -U postgres -c 'select * from pg_replication_slots'
 slot_name │ plugin │ slot_type │ datoid │ database │ temporary │ active │ active_pid │ xmin │ catalog_xmin │ restart_lsn │ confirmed_flush_lsn │ wal_status │ safe_wal_size 
───────────┼────────┼───────────┼────────┼──────────┼───────────┼────────┼────────────┼──────┼──────────────┼─────────────┼─────────────────────┼────────────┼───────────────
(0 rows)


~/git/patroni$ curl -s -X PATCH -d '{"slots": {"my_slot": {"type": "logical", "database": "postgres", "plugin": "test_decoding"}}}' http://localhost:8008/config | jq .
{
  "loop_wait": 10,
  "maximum_lag_on_failover": 1048576,
  "postgresql": {
    "parameters": {
      "wal_level": "logical"
    },
    "use_pg_rewind": true
  },
  "retry_timeout": 10,
  "ttl": 30,
  "slots": {
    "my_slot": {
      "type": "logical",
      "database": "postgres",
      "plugin": "test_decoding"
    }
  }
}

~/git/patroni$ psql -h localhost -U postgres -c 'select * from pg_replication_slots'
 slot_name │    plugin     │ slot_type │ datoid │ database │ temporary │ active │ active_pid │ xmin │ catalog_xmin │ restart_lsn │ confirmed_flush_lsn │ wal_status │ safe_wal_size 
───────────┼───────────────┼───────────┼────────┼──────────┼───────────┼────────┼────────────┼──────┼──────────────┼─────────────┼─────────────────────┼────────────┼───────────────
 my_slot   │ test_decoding │ logical   │  13421 │ postgres │ f         │ f      │            │      │          494 │ 0/1826660   │ 0/1826698           │ reserved   │              
(1 row)


~/git/patroni$ curl -s -X PATCH -d '{"slots": {"my_slot": null}}' http://localhost:8008/config | jq .
{
  "loop_wait": 10,
  "maximum_lag_on_failover": 1048576,
  "postgresql": {
    "parameters": {
      "wal_level": "logical"
    },
    "use_pg_rewind": true
  },
  "retry_timeout": 10,
  "ttl": 30,
  "slots": {}
}

~/git/patroni$ psql -h localhost -U postgres -c 'select * from pg_replication_slots'
 slot_name │ plugin │ slot_type │ datoid │ database │ temporary │ active │ active_pid │ xmin │ catalog_xmin │ restart_lsn │ confirmed_flush_lsn │ wal_status │ safe_wal_size 
───────────┼────────┼───────────┼────────┼──────────┼───────────┼────────┼────────────┼──────┼──────────────┼─────────────┼─────────────────────┼────────────┼───────────────
(0 rows)                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                           
```

What am I doing wrong?

**Comment by krumstein** [comment]
Hi @CyberDem0n !

Something wrong is happening here:
`$ curl -s -X PATCH -d '{"slots": {"SLOT_NAME": null}}' http://localhost:8008/config | jq .
{
  "ttl": 30,
  "loop_wait": 10,
  "retry_timeout": 10,
  "maximum_lag_on_failover": 1048576,
  "master_start_timeout": 300,
  "synchronous_mode": false,
  "postgresql": {
    "use_pg_rewind": true,
    "use_slots": true,
    "parameters": {
      "max_connections": 1000,
      "max_locks_per_transaction": 64,
      "max_worker_processes": 8,
      "max_prepared_transactions": 0,
      "wal_level": "logical",
      "wal_log_hints": true,
      "track_commit_timestamp": false,
      "max_wal_senders": 30,
      "max_replication_slots": 30,
      "wal_keep_segments": 16,
      "maintenance_work_mem": "2GB",
      "work_mem": "10MB",
      "shared_buffers": "8GB",
      "effective_cache_size": "16GB",
      "wal_buffers": "16MB",
      "min_wal_size": "1GB",
      "max_wal_size": "2GB",
      "effective_io_concurrency": 100,
      "random_page_cost": 1.1,
      "temp_file_limit": "150GB",
      "tcp_keepalives_idle": 200,
      "max_standby_streaming_delay": "1s",
      "autovacuum_vacuum_scale_factor": 0.02,
      "autovacuum_analyze_scale_factor": 0.01,
      "autovacuum_vacuum_cost_limit": 1000,
      "log_autovacuum_min_duration": 0
    }
  },
  "slots": {}
}
$  curl -s http://localhost:8008/config | jq .
{
  "ttl": 30,
  "loop_wait": 10,
  "retry_timeout": 10,
  "maximum_lag_on_failover": 1048576,
  "master_start_timeout": 300,
  "synchronous_mode": false,
  "postgresql": {
    "use_pg_rewind": true,
    "use_slots": true,
    "parameters": {
      "max_connections": 1000,
      "max_locks_per_transaction": 64,
      "max_worker_processes": 8,
      "max_prepared_transactions": 0,
      "wal_level": "logical",
      "wal_log_hints": true,
      "track_commit_timestamp": false,
      "max_wal_senders": 30,
      "max_replication_slots": 30,
      "wal_keep_segments": 16,
      "maintenance_work_mem": "2GB",
      "work_mem": "10MB",
      "shared_buffers": "8GB",
      "effective_cache_size": "16GB",
      "wal_buffers": "16MB",
      "min_wal_size": "1GB",
      "max_wal_size": "2GB",
      "effective_io_concurrency": 100,
      "random_page_cost": 1.1,
      "temp_file_limit": "150GB",
      "tcp_keepalives_idle": 200,
      "max_standby_streaming_delay": "1s",
      "autovacuum_vacuum_scale_factor": 0.02,
      "autovacuum_analyze_scale_factor": 0.01,
      "autovacuum_vacuum_cost_limit": 1000,
      "log_autovacuum_min_duration": 0
    }
  },
  "slots": {
    "SLOT_NAME": null
  }
}
$ pql  -c 'select * from pg_replication_slots'
   slot_name    | plugin | slot_type | datoid | database | temporary | active | active_pid |   xmin    | catalog_xmin | restart_lsn  | confirmed_flush_lsn
----------------+--------+-----------+--------+----------+-----------+--------+------------+-----------+--------------+--------------+---------------------
`

So, the replication slot persists in Patroni, but it's removed from DB. How could it happen?

**Comment by CyberDem0n** [comment]
I am unsure what you are doing and what you are trying to show here.
