### ISSUE TITLE
Downgrade

### ISSUE THREAD

**Issue by KostLinux** [zalando/patroni#1883]
Hey!
How can i downgrade my patroni cluster from PSQLv12 to PSQLv11 ?
I need some tutorial steps, because i didn't find any manuals about downgrading cluster.
My OS is ubuntu 20.04.

**Comment by CyberDem0n** [comment]
The only you can do - change the postgresql.bin_dir and create the new cluster and somehow migrate the date with dump/restore.
There is no major downgrade workflow for postgres, it is counterproductive.

**Comment by KostLinux** [comment]
ok. thx.
