### ISSUE TITLE
Changing user password in patroni cluster.

### ISSUE THREAD

**Issue by KostLinux** [zalando/patroni#1885]
When i'm trying to reset user password, it says success, but i can't login from client.
postgres=# alter role someuser with login password 'somepass';
It gives success.
But when i try: psql -h myhost -p myport -d mydb -U someuser
Password: (inserted pass)
It gives: password authentication failed for user "someuser"

I also tried \password method, but it didn't work.

**Comment by CyberDem0n** [comment]
Sorry, but this "problem" has nothing to do with Patroni.
