### ISSUE TITLE
Hot certificate change (reload patroni?)

### ISSUE THREAD

**Issue by michael-todorovic** [zalando/patroni#1886]
Hello,
I'm securing the rest api with TLS+auth for my lovely patroni 2.0.2 (Debian 10 with python 3.7.3).

Is there a way to reload patroni in order to switch the certificate? I tried:
```
systemctl reload patroni
patronictl -c /etc/patroni/ reload cluster_name node_name
patronictl -c /etc/patroni/ restart cluster_name node_name
``` 
with no effect the certificate being used. I'm checking the cert with
```
openssl s_client -connect node_name.domain.com:8008 </dev/null 2>/dev/null | openssl x509 -noout -text | grep -E 'Subject:|DNS:'
```

The only thing that made it change is a violent
```
systemctl restart patroni
```
which makes the cluster to switch.

Is there another way to reload the certificate? I may try to provide a PR for this if it's not supported yet.

Thanks!

**Comment by CyberDem0n** [comment]
Hi @michael-todorovic,

no, it is not supported yet.

`patronictl restart` - in fact restarts only postgres and doesn't affect Patroni at all.
`patronictl reload` - forces Patroni to re-read config file. Some of the configuration settings are applied on the fly. For example, you can change `listen`, `connect_address`, `authentication`, and so on.

Actually, even if you change the `certfile`, `keyfile`, or something similar, it will apply it on the fly (after reload).

What is not done yet - Patroni doesn't check that the content of these files has been changed. Although, probably we can even make it simpler. It would be enough to change the condition https://github.com/zalando/patroni/blob/master/patroni/api.py#L766 to:
```python
-        if self.__listen != config['listen'] or self.__ssl_options != ssl_options:
+        if self.__listen != config['listen'] or ssl_options:
```

Feel free to open a PR.

**Comment by michael-todorovic** [comment]
Ok, I was only changing file content. If I change the filename, `patroni reload` works just fine.

I'll check the file content change and submit a PR

Thanks for your quick answer!
