### ISSUE TITLE
Patroni LB gives password authentication failed, but direct access is ok

### ISSUE THREAD

**Issue by KostLinux** [zalando/patroni#1890]
Hey.
Having trouble with cluster connection via HAProxy.
When i'm trying direct connection from app > db, it's success.
But when i'm trying to connect from app > haproxy_VIP : db_port, it gives:
Password authentication failed for user "myuser".

Can you help me with this trouble ?

**Comment by CyberDem0n** [comment]
HAProxy connects with the IP that is different from the application IP.
I bet pg_hba.conf doesn't allow it.
All details are as usual in Postgres logs.

How pg_hba.conf is evaluated by Postgres you can read in the documentation: https://www.postgresql.org/docs/current/auth-pg-hba-conf.html
