### ISSUE TITLE
pg_wal file clean up

### ISSUE THREAD

**Issue by Kumar6295** [zalando/patroni#1892]
we are using patroni cluster setup.
Pg_wal file size become 180 GB and Storage of disk is full so now patroni cluster is failed, patroni is not running.
How we can resolve.How to keep wal size 100GB or less.
How free up disk space and make patroni cluster works

**patroni.yml**
wal_level:logical
wal_keep_segements:250
max_wal_senders:30
max_replication_slots:30

**postgresql.base.conf** 

max_wal_size:1 GB
min_wal_size: 80 GB
archive_mode:off

**Comment by CyberDem0n** [comment]
Patroni is not responsible for cleaning up pg_wal.

You can learn about diagnostic from the article: https://dataegret.com/2018/04/pg_wal-is-too-big-whats-going-on/

**Comment by Kumar6295** [comment]
Thanks
