### ISSUE TITLE
Logical replication slot inquery

### ISSUE THREAD

**Issue by viljohakala** [zalando/patroni#1893]
Hello!

When using logical replication between two patroni clusters a logical replication slot is created by the
setup process of logical replication ( the name of the subscription is the name for the logical replication slot).

How can we use the permanent logical replication slot feature of Patroni to preserve this logical replication slot
during cluster failovers to keep the logical replication running even after failover?

There is something in the documentation, but I wouldl ike to get an exact configuration example how this should work?

For example, the plugin parameter is not clear to me how to use it.  What should it be?

slots: define permanent replication slots. These slots will be preserved during switchover/failover. Patroni will try to create slots before opening connections to the cluster.
my_slot_name: the name of replication slot. If the permanent slot name matches with the name of the current primary it will not be created. Everything else is the responsibility of the operator to make sure that there are no clashes in names between replication slots automatically created by Patroni for members and permanent replication slots.
type: slot type. Could be physical or logical. If the slot is logical, you have to additionally define database and plugin.
database: the database name where logical slots should be created.
plugin: the plugin name for the logical slot.

**Comment by CyberDem0n** [comment]
The logical failover slots feature was merged only last Friday: https://github.com/zalando/patroni/pull/1820
It allows to have exactly what you want, preserve the position of logical slot on failover. In worst case the position would be a bit lower than it was, but the subscriber can handle it with no problems. The feature exists only in the master branch yet. And it supports only Postgres starting from version 11.

Regarding the `plugin` parameter: if you already have logical replication working you can get the plugin name from the `pg_replication_slots` view.

**Comment by viljohakala** [comment]
Hi,

So to have this working I should upgrade to latest version of Patroni (in the master branch) and use Postgresql 11 ?

Thanks


Lähettäjä: Alexander Kukushkin ***@***.***>
Vastausosoite: zalando/patroni ***@***.***>
Päivämäärä: maanantai 29. maaliskuuta 2021 klo 13.12
Vastaanottaja: zalando/patroni ***@***.***>
Kopio: Viljo Hakala ***@***.***>, Author ***@***.***>
Aihe: Re: [zalando/patroni] Logical replication slot inquery (#1893)


The logical failover slots feature was merged only last Friday: #1820<https://github.com/zalando/patroni/pull/1820>
It allows to have exactly what you want, preserve the position of logical slot on failover. In worst case the position would be a bit lower than it was, but the subscriber can handle it with no problems. The feature exists only in the master branch yet. And it supports only Postgres starting from version 11.

Regarding the plugin parameter: if you already have logical replication working you can get the plugin name from the pg_replication_slots view.

**Comment by CyberDem0n** [comment]
> So to have this working I should upgrade to latest version of Patroni (in the master branch) 

Before using Patroni from the master branch I would recommend to test it first.

> and use Postgresql 11 ?

It does not necessarily have to be 11. Anything newer (12, 13) is actually much better due to lots of reasons.
