### ISSUE TITLE
question: how many databases can patroni supervise?

### ISSUE THREAD

**Issue by alizaaliza** [zalando/patroni#1896]

**Comment by CyberDem0n** [comment]
I don't get the question.

**Comment by alizaaliza** [comment]
Hi to the patroni team,


we have a situation of 2 databases at the same vm.  
1) I would like to ask how many databases can patroni supervise? can I configure 2 database with same patroni?
2)  2 patroni's on same VM with default config, will conflict on whatchdog device. is there anyway to solve it ? can we configure patroni to use whatchdog daemon? 


thanks , Aliza
