### ISSUE TITLE
question: can patroni support 2 postgresql databases on the same VM?

### ISSUE THREAD

**Issue by alizaaliza** [zalando/patroni#1897]
Hi to the patroni team,

we have a situation of 2 databases at the same vm.

I would like to ask how many databases can patroni supervise? can I configure 2 database with same patroni?
2 patroni's on same VM with default config, will conflict on whatchdog device. is there anyway to solve it ? can we configure patroni to use whatchdog daemon?
thanks , Aliza

**Comment by CyberDem0n** [comment]
> will conflict on whatchdog device. is there anyway to solve it ?

no

> can we configure patroni to use whatchdog daemon?

no

In case if there is HAProxy in front you can live without a watchdog.

**Comment by alizaaliza** [comment]
Thank you

**Comment by alizaaliza** [comment]
thanks, just to be clear
can I configure 2 database with same patroni?

**Comment by CyberDem0n** [comment]
> can I configure 2 database with same patroni?

what have you tried so far?

**Comment by alizaaliza** [comment]
Hi Alexander
we are using one patroni per single postgresql cluster.


Thanks , Aliza.

**Comment by alizaaliza** [comment]
Hi Alexander
we are using one patroni per single postgresql cluster.



Thanks , Aliza.
