### ISSUE TITLE
Patroni silently restarted a leader for no explicit reason

### ISSUE THREAD

**Issue by iomatters** [zalando/patroni#1900]
Patroni cluster c1.6.3, 2 PG nodes, 3 etcd nodes, silently restarted PG on a leader for no explicit reason, please see what I got from logs:

Apr  7 14:43:26 server1 patroni[14480]: 2021-04-07 14:43:26,525 INFO: no action.  i am the leader with the lock
Apr  7 14:43:36 server1 patroni[14480]: 2021-04-07 14:43:36,516 INFO: Lock owner: server1; I am server1
Apr  7 14:43:36 server1 patroni[14480]: 2021-04-07 14:43:36,525 INFO: no action.  i am the leader with the lock
Apr  7 14:43:46 server1 patroni[14480]: 2021-04-07 14:43:46,516 INFO: Lock owner: server1; I am server1
Apr  7 14:43:46 server1 patroni[14480]: 2021-04-07 14:43:46,525 INFO: no action.  i am the leader with the lock
**Apr  7 14:43:46 server1 systemd[1]: Stopping Runners to orchestrate a high-availability PostgreSQL...**
Apr  7 14:43:48 server1 patroni[14480]: 2021-04-07 14:43:48,665 INFO: Lock owner: server1; I am server1
Apr  7 14:43:49 server1 systemd[1]: Stopped Runners to orchestrate a high-availability PostgreSQL.
Apr  7 14:43:49 server1 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
Apr  7 14:43:49 server1 patroni[11537]: 2021-04-07 14:43:49,923 INFO: Selected new etcd server http://10.1.1.2:2379
Apr  7 14:43:49 server1 patroni[11537]: 2021-04-07 14:43:49,937 INFO: No PostgreSQL configuration items changed, nothing to reload.
Apr  7 14:43:49 server1 patroni[11537]: 2021-04-07 14:43:49,958 WARNING: Postgresql is not running.
Apr  7 14:43:49 server1 patroni[11537]: 2021-04-07 14:43:49,958 INFO: Lock owner: None; I am server1
Apr  7 14:43:49 server1 patroni[11537]: 2021-04-07 14:43:49,961 INFO: pg_controldata:
Apr  7 14:43:49 server1 patroni[11537]:   Catalog version number: 201707211
Apr  7 14:43:49 server1 patroni[11537]:   pg_control last modified: Wed Apr  7 14:43:47 2021
Apr  7 14:43:49 server1 patroni[11537]:   Minimum recovery ending location: 0/0
Apr  7 14:43:49 server1 patroni[11537]:   Latest checkpoint's full_page_writes: on
Apr  7 14:43:49 server1 patroni[11537]:   End-of-backup record required: no
Apr  7 14:43:49 server1 patroni[11537]:   track_commit_timestamp setting: off
......
Apr  7 14:43:49 server1 patroni[11537]: 2021-04-07 14:43:49,963 INFO: Lock owner: None; I am server1
Apr  7 14:43:50 server1 patroni[11537]: 2021-04-07 14:43:50,003 INFO: Lock owner: None; I am server1
Apr  7 14:43:50 server1 patroni[11537]: 2021-04-07 14:43:50,010 INFO: starting as a secondary
Apr  7 14:43:50 server1 patroni[11537]: 2021-04-07 14:43:50,234 INFO: postmaster pid=11563
Apr  7 14:43:50 server1 patroni[11537]: localhost:5432 - no response
......
Apr  7 14:43:51 server1 patroni[11537]: 2021-04-07 14:43:51,364 INFO: establishing a new patroni connection to the postgres cluster
Apr  7 14:43:53 server1 patroni[11537]: 2021-04-07 14:43:53,533 INFO: following a different leader because I am not allowed to promote
Apr  7 14:44:03 server1 patroni[11537]: 2021-04-07 14:44:03,396 INFO: following a different leader because I am not allowed to promote
Apr  7 14:44:13 server1 patroni[11537]: 2021-04-07 14:44:13,393 INFO: following a different leader because I am not allowed to promote
Apr  7 14:44:23 server1 patroni[11537]: 2021-04-07 14:44:23,391 INFO: following a different leader because I am not allowed to promote
Apr  7 14:44:33 server1 patroni[11537]: 2021-04-07 14:44:33,395 INFO: following a different leader because I am not allowed to promote

I have sort of a clue on what happened next, why the leader become readonly. I am really concerned about this line:
**Apr  7 14:43:46 server1 systemd[1]: Stopping Runners to orchestrate a high-availability PostgreSQL...**

What might have caused that and why ?? That was not a command sent by a human for 100% sure, that's verified.

Any idea is highly appreciated, thanks!

**Comment by CyberDem0n** [comment]
> What might have caused that and why ?? That was not a command sent by a human for 100% sure, that's verified.

Magic doesn't exist. Logs clearly tell that shutdown was initiated by systemd/systemctl. Either it was a human or puppet/ansible/etc, which is after all also maintained by a human.

> I have sort of a clue on what happened next, why the leader become readonly

Well, `following a different leader because I am not allowed to promote` message could be shown only in one case, when `tags.nofailover` is set. This is yet another confirmation that someone updated Patroni config file and did a restart.

**Comment by iomatters** [comment]
Thank you for the prompt reply.

> when `tags.nofailover` is set
That's true, I'm not questioning about that, that was intentional. Regarding the restart, are you 100% confident that couldn't be Patroni ? I searched through the logs back and forth, no evidence at all.

**Comment by CyberDem0n** [comment]
Yes, I am 100% sure that Patroni never restarts itself.
In old versions there were some bugs that causing crash, but logs look different in this case.
Speaking of old versions, 16.1 is veeery old...

**Comment by iomatters** [comment]
OK, thanks, closing the issue.
