### ISSUE TITLE
Patroni did not restart as slave 

### ISSUE THREAD

**Issue by thuybt** [zalando/patroni#1902]
**Describe the bug**
![image](https://user-images.githubusercontent.com/59462501/114049502-b1894d00-98b5-11eb-8050-dba2df3e411a.png)

**To Reproduce**
Systemctl start patroni 
Systemctl status patroni

**Expected behavior**
Patroni Status Running I am a slaves

**Screenshots**
![image](https://user-images.githubusercontent.com/59462501/114049757-ea292680-98b5-11eb-8410-9d63875c2b62.png)

**Environment**
- Patroni version: **Patroni 2.0.2**
- PostgreSQL version: **postgresql-12**
- DCS (and its version):
-etcd Version: 3.3.11
Git SHA: 2cf9e51
Go Version: go1.10.3
Go OS/Arch: linux/amd64

**Patroni configuration file**
scope: postgres
namespace: /db/
name: postgres-sl1

restapi:
    listen: 192.168.1.201:8008
    connect_address: 192.168.1.201:8008

etcd:
    host: 192.168.1.200:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 192.168.1.200/0 md5
    - host replication replicator 192.168.1.201/0 md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 192.168.1.201:5432
    connect_address: 192.168.1.201:5432
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: rep-pass
        superuser:
            username: postgres
            password: secretpassword
    parameters:
        unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
![image](https://user-images.githubusercontent.com/59462501/114051318-2dd06000-98b7-11eb-9095-26103be7f2ce.png)

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Similar issue has been raised here 
https://github.com/zalando/patroni/issues/569
I followed , 
set postgresql.bin_dir by the following command:
![image](https://user-images.githubusercontent.com/59462501/114051644-7a1ba000-98b7-11eb-8010-80e406bac84b.png)

the link above also contain pg-ready package
![image](https://user-images.githubusercontent.com/59462501/114051793-9f101300-98b7-11eb-8cc0-cd3a635a5b21.png)
But still remain the issue

**Additional context**

**Comment by CyberDem0n** [comment]
How systemd supposed to see the PATH set in the .bashrc?

**Comment by thuybt** [comment]
Sorry for the mistakes,
Already config **bin_dir: /usr/pgsql-12/bin**  in patroni.yml file, and reset + restart patroni.
Solved
