### ISSUE TITLE
How to tell patroni to update password after secrets are being rotated

### ISSUE THREAD

**Issue by mehfuzh** [zalando/patroni#1904]
**Describe the bug**
I use three instances with 0 as leader,1 and 2 as replicas. I am using AWS ebs. Often I want to rotate the secrets, how to trigger patroni once the secrets are being rotated so that I don't have to do 'alter role with password ..` to update the standby and other roles manually?

**To Reproduce**
Update secrets

**Expected behavior**
It should auto-rotate the database passwords

**Screenshots**

**Environment**
- Patroni version:
- PostgreSQL version:
- DCS (and its version):

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Yes

**Have you checked PostgreSQL logs?**
Yes

**Have you tried to use GitHub issue search?**
Yes

**Additional context**
NA

**Comment by CyberDem0n** [comment]
> so that I don't have to do 'alter role with password ..` to update the standby and other roles manually?

Don't get me wrong, but if we go the way you want, Patroni will turn into yet another salt/ansible/puppet/chose-your-own.

Magic doesn't exist. You have to:
1. Update patroni configs on all nodes
2. Reload patroni configs by either sending SIGHUP to the patroni pid or by running `patronictl reload`
3. Do ALTER ROLE ...

This is easily automatable with the help of external tools.
