### ISSUE TITLE
Is it possible to override wal_level setting?

### ISSUE THREAD

**Issue by dboyleitrs** [zalando/patroni#1906]
Sorry I'm not using the template as this is just a basic usage question.

Is it possible to override the `wal_level: replica` in the `bootstrap.dcs.postgres.parameters` section?

When I try to set this to `minimal`, it always gets overwritten.

I would like to do this when we deploy in dev environments with a single node.

**Comment by CyberDem0n** [comment]
> Is it possible to override the wal_level: replica

Yes, but only to `logical`.

> in the bootstrap.dcs.postgres.parameters section?

No, after the cluster was bootstrapped the `bootstrap` doesn't work anymore. You have to use `patronictl edit-config`.

But anyway, Patroni will not allow reducing wal_level from logical down to minimal.
