### ISSUE TITLE
patroni.service entered failed state: socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by thuybt** [zalando/patroni#1911]
**Describe the bug**
socket.gaierror: [Errno -2] Name or service not known
**To Reproduce**

**Expected behavior**
patroni status successful running

**Screenshots**
![image](https://user-images.githubusercontent.com/59462501/115337055-89112500-a1ca-11eb-945c-65acf120c64a.png)
**Environment**
- Patroni version: patroni 2.0.2
- PostgreSQL version: 12
- DCS (and its version):

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
scope: postgres
namespace: /db/
name: postgres-sl1

restapi:
    listen: 10.128.0.11.201:8008
    connect_address: 10.128.0.11:8008

etcd:
    host: 10.128.0.10:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator 10.128.0.10/0 md5
    - host replication replicator 10.128.0.11/0 md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 10.128.0.11:5432
    connect_address: 10.128.0.11:5432
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: rep-pass
        superuser:
            username: postgres
            password: secretpassword
    parameters:
        unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

Please copy&paste the output of "patronictl show-config" command here

![image](https://user-images.githubusercontent.com/59462501/115337304-ed33e900-a1ca-11eb-8d8b-adedf5df23c1.png)

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
![image](https://user-images.githubusercontent.com/59462501/115337332-fc1a9b80-a1ca-11eb-8e56-9aaf2769079a.png)
**Have you tried to use GitHub issue search?**
There is already a similar issue solved. But they did not apply to my case

**Additional context**

**Comment by CyberDem0n** [comment]
```yaml
restapi:
    listen: 10.128.0.11.201:8008
```

Since when IPv4 contains 5 octets?
