### ISSUE TITLE
Promotion to leader/sync standby with 4 postgresql dbs in DC1 & DC2 upon DC1 failure

### ISSUE THREAD

**Issue by viljohakala** [zalando/patroni#1915]
Hi,

I have a 4 node PostgreSQL cluster with 3 etcds. 2 postgresql dbs pgps1-2 are in the DC1,
pgsps3-4 are in DC2.

etcds are in DC1,DC2,DC3 (one in each)

I have a situation when the cluster Leader and sync standby are in the DC1, if that dc fails, or if I simulate it
by shutting down Patroni on pgsps1 & 2, then pgsps3-4 will not be promoted from replica to leader/sync standby
thus there is no failover from DC1 to DC2 if DC1 fails.

+ Cluster: test_cluster  (12345) -------+----+-----------+------------------------+
| Member                | Host         | Role         | State   | TL | Lag in MB | Tags                   |
+-----------------------+--------------+--------------+---------+----+-----------+------------------------+
| pgsps1| 192.168.0.1 | Leader       | running | 21 |           | synchronous_mode: true |
| pgsps2 | 192.168.0.2 | Sync Standby | running | 21 |         0 | synchronous_mode: true |
| pgsps3 | 192.168.0.3 | Replica      | running | 21 |         0 | synchronous_mode: true |
| pgsps4 | 192.168.0.4 | Replica      | running | 21 |         0 | synchronous_mode: true |
+-----------------------+--------------+--------------+---------+----+-----------+------------------------+

How can I have with this configuration and have pgsps3-4 promoted to leader / sync standby ?

Here's my config

loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=test_cluster archive-push %p
    archive_mode: true
    autovacuum_max_workers: '6'
    autovacuum_vacuum_scale_factor: '0.1'
    autovacuum_vacuum_threshold: '50'
    client_min_messages: WARNING
    log_autovacuum_min_duration: 60s
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_duration: 'off'
    log_filename: postgresql-%a.log
    log_line_prefix: '%m - %l - %p - %h - %u@%d - %x'
    log_lock_waits: 'on'
    log_min_duration_statement: 30s
    log_min_error_statement: NOTICE
    log_min_messages: WARNING
    log_rotation_age: '1440'
    log_statement: ddl
    log_temp_files: '0'
    log_timezone: Europe/Helsinki
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    max_connections: 1000
    max_prepared_transactions: 2000
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 8
    restore_command: pgbackrest --stanza=test_cluster  archive-get %f %p
    synchronous_commit: 'on'
    wal_keep_segments: 100
    wal_keep_size: 12800MB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 5
synchronous_mode: true
ttl: 30

/etc/patroni.d/patroni.yml

tags:
    synchronous_mode: true
#    nofailover: false
#    noloadbalance: false
#    clonefrom: false
#    nosync: false

~

**Comment by viljohakala** [comment]
The error from dc2 pgps3-4 are in patroni.log

following a different leader because i am not the healthiest node

**Comment by viljohakala** [comment]
Is this a similar issue to 
https://github.com/zalando/patroni/issues/1860

the postgresql dbs pgsps1&2 fail at the same time when I stopped patroni processes.

So is there a fix in newer Patroni version?

**Comment by CyberDem0n** [comment]
You can specify `synchronous_node_count=2`. It will guaranty that there will be always a sync node in a different DC.

**Comment by viljohakala** [comment]
Applied the parameter, but it has no effect

postgresql:
  parameters:
    synchronous_node_count: 2

postgres=# select application_name, sync_state from pg_stat_replication;;
   application_name    | sync_state 
-----------------------+------------
 pgsps2- | sync
 pgsps3 | async
 pgsps4| async
(3 rows)

**Comment by viljohakala** [comment]
patronictl  version
patronictl version 2.0.2

**Comment by viljohakala** [comment]
synchronous_node_count: 2

Now works after applying as last parameter.

Thanks

**Comment by hkilicvdub** [comment]
> Hi,
> 
> I have a 4 node PostgreSQL cluster with 3 etcds. 2 postgresql dbs pgps1-2 are in the DC1,
> pgsps3-4 are in DC2.
> 
> etcds are in DC1,DC2,DC3 (one in each)
> 
> I have a situation when the cluster Leader and sync standby are in the DC1, if that dc fails, or if I simulate it
> by shutting down Patroni on pgsps1 & 2, then pgsps3-4 will not be promoted from replica to leader/sync standby
> thus there is no failover from DC1 to DC2 if DC1 fails.
> 
> * Cluster: test_cluster  (12345) -------+----+-----------+------------------------+
>   | Member                | Host         | Role         | State   | TL | Lag in MB | Tags                   |
>   +-----------------------+--------------+--------------+---------+----+-----------+------------------------+
>   | pgsps1| 192.168.0.1 | Leader       | running | 21 |           | synchronous_mode: true |
>   | pgsps2 | 192.168.0.2 | Sync Standby | running | 21 |         0 | synchronous_mode: true |
>   | pgsps3 | 192.168.0.3 | Replica      | running | 21 |         0 | synchronous_mode: true |
>   | pgsps4 | 192.168.0.4 | Replica      | running | 21 |         0 | synchronous_mode: true |
>   +-----------------------+--------------+--------------+---------+----+-----------+------------------------+
> 
> How can I have with this configuration and have pgsps3-4 promoted to leader / sync standby ?
> 
> Here's my config
> 
> loop_wait: 10
> maximum_lag_on_failover: 1048576
> postgresql:
> parameters:
> archive_command: pgbackrest --stanza=test_cluster archive-push %p
> archive_mode: true
> autovacuum_max_workers: '6'
> autovacuum_vacuum_scale_factor: '0.1'
> autovacuum_vacuum_threshold: '50'
> client_min_messages: WARNING
> log_autovacuum_min_duration: 60s
> log_checkpoints: 'on'
> log_connections: 'on'
> log_disconnections: 'on'
> log_duration: 'off'
> log_filename: postgresql-%a.log
> log_line_prefix: '%m - %l - %p - %h - %u@%d - %x'
> log_lock_waits: 'on'
> log_min_duration_statement: 30s
> log_min_error_statement: NOTICE
> log_min_messages: WARNING
> log_rotation_age: '1440'
> log_statement: ddl
> log_temp_files: '0'
> log_timezone: Europe/Helsinki
> log_truncate_on_rotation: 'on'
> logging_collector: 'on'
> max_connections: 1000
> max_prepared_transactions: 2000
> max_replication_slots: 10
> max_wal_senders: 10
> max_worker_processes: 8
> restore_command: pgbackrest --stanza=test_cluster archive-get %f %p
> synchronous_commit: 'on'
> wal_keep_segments: 100
> wal_keep_size: 12800MB
> use_pg_rewind: true
> use_slots: true
> retry_timeout: 5
> synchronous_mode: true
> ttl: 30
> 
> /etc/patroni.d/patroni.yml
> 
> tags:
> synchronous_mode: true
> 
> # nofailover: false
> # noloadbalance: false
> # clonefrom: false
> # nosync: false
> ~

In your configuration all DCs are interconnect with L2 extension.
Did I truely understand ?
Because I need to make a configuration with 2 DCs and  I am complicated with the configuration
