### ISSUE TITLE
Initiating a Standby Cluster

### ISSUE THREAD

**Issue by virtuel99** [zalando/patroni#1916]
Hello There,

I would need some support as i am stuck in standby_cluster initialisation.
I have a Primary cluster with 3 nodes  and I would like to add a 3 nodes standby cluster.

![image](https://user-images.githubusercontent.com/45622677/115742983-7e54bc80-a391-11eb-8984-4e61a022141c.png)

I have setup YAML bootstrap section for the standby leader as following.

![image](https://user-images.githubusercontent.com/45622677/115743574-1488e280-a392-11eb-8884-c935e1c4871a.png)

pg_hba: section contains infos concerning all 6 nodes in both clusters.

$PGDATA has been cleared.

I was expecting patroni to recrte PG instance at restart, but nothing happened.

![image](https://user-images.githubusercontent.com/45622677/115744216-a690eb00-a392-11eb-9eae-ccff3cfada9e.png)

Thanks for your support.

Ubuntu 18.0.4
Patroni 1.6.5
PG 12.6.1

**Comment by virtuel99** [comment]
to be complete : service Patroni status

![image](https://user-images.githubusercontent.com/45622677/115747712-cd9cec00-a395-11eb-860a-e46e226889f2.png)

**Comment by CyberDem0n** [comment]
Please use search: https://github.com/zalando/patroni/issues?q=is%3Aissue+waiting+for+leader+to+bootstrap+is%3Aclosed

**Comment by virtuel99** [comment]
Hi Alex,
Thanks for your link, it is now working 👍 
![image](https://user-images.githubusercontent.com/45622677/115872428-15794d00-a442-11eb-99c5-2a2956ce03b4.png)

What I have changed is : 

- New name for standby cluster
- Remove previous cluster in DCS
- Update pg_hba.conf in all primary instance and reboot cluster/instances.
- Remove slot name "patroni" in standby_cluster section of yml file.

Thanks & regards.

**Comment by virtuel99** [comment]
I am closing case. Thanks for all, Patroni is a great product !

**Comment by rajankhosla35** [comment]
@virtuel99 we're still facing the same issue, is it possible for you to share the patroni.yml configuration?

@CyberDem0n do you have any insights what could be the exact configuration which we can use for standby DR configuration.
