### ISSUE TITLE
What is right way to make active cluster to be standby one

### ISSUE THREAD

**Issue by dmshprivate** [zalando/patroni#1923]
Hi,

We have Active - Standby patroni cluster configuration.
Use cases:
1) In case of failover on Active we promote Standby to Active. When ex Active will repare we need to make it Standby. 
2) It's need to switch clusters (Active-Standby switch on Standby-Active) while maintenance is going on. 

We remove the standby_cluster section from the config to promote Standby to Active.

But, What are steps to make Active to be Standby?

Thanks

**Comment by CyberDem0n** [comment]
I guess https://github.com/zalando/patroni/issues/1660#issuecomment-678124810 is the answer you are looking for.

**Comment by dmshprivate** [comment]
Thanks, @CyberDem0n

One more question, is there reinit command/steps for Standby cluster?

**Comment by CyberDem0n** [comment]
> is there reinit command/steps for Standby cluster?

`patronictl reinit` perfectly works on replicas, but not on the standby leader.
Basically, you will have to manually remove PGDATA.
