### ISSUE TITLE
 patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'

### ISSUE THREAD

**Issue by Aleksey-10081967** [zalando/patroni#1924]
Hi.
Service does not start service patroni.

[root@test-second bin]# systemctl status patroni
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/etc/systemd/system/patroni.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2021-04-27 16:50:59 MSK; 4s ago
  Process: 8474 ExecStart=/usr/local/bin/patroni /etc/patroni/patroni.yml (code=exited, status=1/FAILURE)
 Main PID: 8474 (code=exited, status=1/FAILURE)

Apr 27 16:50:59 test-second patroni[8474]: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1351, in _run_cycle
Apr 27 16:50:59 test-second patroni[8474]: return self.post_bootstrap()
Apr 27 16:50:59 test-second patroni[8474]: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1247, in post_bootstrap
Apr 27 16:50:59 test-second patroni[8474]: self.cancel_initialization()
Apr 27 16:50:59 test-second patroni[8474]: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1240, in cancel_initialization
Apr 27 16:50:59 test-second patroni[8474]: raise PatroniFatalException('Failed to bootstrap cluster')
Apr 27 16:50:59 test-second patroni[8474]: patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
Apr 27 16:50:59 test-second systemd[1]: patroni.service: main process exited, code=exited, status=1/FAILURE
Apr 27 16:50:59 test-second systemd[1]: Unit patroni.service entered failed state.
Apr 27 16:50:59 test-second systemd[1]: patroni.service failed.

patroni.conf
scope: test-postgres
name: test-second
namespace: /db/
restapi:
  listen: 0.0.0.0:8008
  connect_address: test-second:8008
  authentication:
    username: patroni
    password: patroni
etcd:
 host: localhost:2379
# username: root
# password: 12345678
 hosts:
 - test-second:2379
 - test-third:2379
 - test-fourth:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
     use_pg_rewind: true
     use_slots: true
     parameters:
     wal_level: replica
     hot_standby: "on"
     wal_keep_segments: 8
     max_wal_senders: 5
     max_replication_slots: 5
     checkpoint_timeout: 30
  initdb:
  - aut-host: md5
  - auth-local: peer
  - encoding: UTF8
  - data-checksums
  - locale: ru_RU.UTF-8
  pg_hba:
  - host replication replicator samenet md5
  - host replication all 127.0.0.1/32 md5
  - host all all 0.0.0.0/0 md5
  users:
    admin:
    password: admin
    options:
    - superuser
postgresql:
  listen: 0.0.0.0:5432
  connect_address: test-second:5432
  config_dir: /mnt/pgs-cluster
  bin_dir: /usr/pgsql-12/bin/
  data_dir: /mnt/pgs-cluster
  pgpass: /tmp/pgpass
  authentication:
   superuser:
    username: postgres
    password: postgres
   replication:
    username: replicator
    password: replicator
   rewind:
    username: rewind_user
    password: rewind_user
  parameters:
   unix_socket_directories: '/var/run/postgresql'
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

[root@test-second bin]# python3 --version
Python 3.6.8
[root@test-second bin]# python --version
Python 2.7.5
[root@test-second bin]#

CentOS Linux release 7.9.2009 (Core)

**Comment by CyberDem0n** [comment]
You have to check the full log, not just last few lines from systemctl.
