### ISSUE TITLE
Patroni lacks pg_hba <> cluster role binds

### ISSUE THREAD

**Issue by Drugoy** [zalando/patroni#1925]
**Describe the bug**
Patroni lacks any logic of handling pg_hba rules based on roles of the nodes in cluster (primary, replica).

**To Reproduce**
There is a cluster of 2 nodes: primary + replica.
There is an account that should always be permitted to connect only to replica, so I restrict access for it in pg_hba.conf on primary.
Then a switchover/failover occurs.
Due to switched roles and a restrictive pg_hba rule is present on new replica (ex. primary) - the account can't now connect to replica, but is able to connect to primary, which should have been forbidden for it.

**Expected behavior**
I want patroni to have a config with 2 pg_hba lists: one for primary and the other one for replica.
This rules need to be forced to Postgres by Patroni whenever it can.
Currently, even `edit-config` doesn't show a list of pg_hba rules to edit.

**Comment by CyberDem0n** [comment]
> Patroni lacks any logic of handling pg_hba rules based on roles of the nodes in cluster (primary, replica).

Not really, you can use [postgresql.callbacks](https://patroni.readthedocs.io/en/latest/SETTINGS.html#postgresql) to update pg_hba.conf

> Expected behavior
I want patroni to have a config with 2 pg_hba lists: one for primary and the other one for replica.
This rules need to be forced to Postgres by Patroni whenever it can.

Do you want to work on it? Just keep in mind that pg_hba.conf is not always located in the PGDATA. 

> Currently, even edit-config doesn't show a list of pg_hba rules to edit.

What is it supposed to show there? The empty array will produce the empty pg_hba.conf. If there is no `postgresql.pg_hba` either there is one in the same section of patroni.yaml or pg_hba.conf is not managed by Patroni. I would recommend you to read a chapter in the documentation: https://patroni.readthedocs.io/en/latest/dynamic_configuration.html and also check [slides](https://raw.githubusercontent.com/patroni-training/2019/master/slides.pdf) 65-68 of Patroni tutorial.

**Comment by Drugoy** [comment]
> Not really, you can use postgresql.callbacks to update pg_hba.conf

Well, that I definitely missed, thanks for pointing it out, looks like a way to at least write an external script as a solution for my problem.

> Just keep in mind that pg_hba.conf is not always located in the PGDATA.

Doesn't seem to be a big problem, because usually it is located there and for fancy configs when someone decides to move it - the path can be obtained via simple SQL query `SHOW hba_file;`
