### ISSUE TITLE
Replication issue with postgres between master and slaves

### ISSUE THREAD

**Issue by gssmahes** [zalando/patroni#1927]
Currently we have enabled 5 centos server setup as given below for PGHA and facing these 2 issues. It will be helpful if you share inputs on this.
1.	Data replication between postgres servers i.e. master and slaves. 
-	Adding new row or db on master doesn’t get reflected on slaves
2.	Accessing haproxy statistics page using VIP (keepalived)
-	Statistics page is accessible via haproxy ip but not with VIP

AWS instance 	Components installed
x.x.x.x	postgres, patroni, etcd
y.y.y.y 	postgres, patroni, etcd 
z.z.z.z 	postgres, patroni, etcd

/etc/patroni.yml has been attached here.
[patroni_yml.txt](https://github.com/zalando/patroni/files/6404731/patroni_yml.txt)

**Comment by CyberDem0n** [comment]
Usually, all investigations on problems start with analyzing logs.
