### ISSUE TITLE
pg_hba: is not changing pg_hba.conf on standby leader.

### ISSUE THREAD

**Issue by virtuel99** [zalando/patroni#1929]
Hello,

I have a 3 nodes primary cluster with HA Proxy and Consul.
addresses are 192.168.10.131, 132 and 133 for the nodes, 120 for the HA proxy  VIP, 121 and 122 for HaProxy1 and HAProxy2.

I have installed a 3 nodes Standby Cluster
addresses are 192.168.10.141, 142 and 143 for the nodes, 120 for the HA proxy  VIP, 121 and 122 for HaProxy1 and HAProxy2.

Standby Leader synchronisation is done by pg_basebackup.

bootstrap: section  of  YAML file on Standby side is : 

![image](https://user-images.githubusercontent.com/45622677/117305717-51b79f00-ae7f-11eb-9a1e-35402b081e31.png)

When I am running "service patroni start" on standby side, Standby Leader is initialized correctly, excepted for pg_hba.conf which is  not been updated with 3 standby nodes (141, 142 & 143).
I have the same pg_hba.conf than Primary Leader  : 

![image](https://user-images.githubusercontent.com/45622677/117306060-a65b1a00-ae7f-11eb-923b-791b0c4a5e5e.png)

What is wrong in my configuration  ?
Where do I have to put the pg_hba: section ? bootstrap: section looks fine, as I want pg_hba.conf updated at instance creation.
Is the pg_hba: syntax is correct ?

Thanks in advance for your answers.

**Comment by CyberDem0n** [comment]
Because the pg_hba must be located in the `postgresql` section

**Comment by pgodfrin-nov** [comment]
This is ours:

patroni:

  log:

    level: WARNING

  # https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#bootstrap

  bootstrap:

    method: restore_or_initdb

    restore_or_initdb:

      command: >

        /etc/timescaledb/scripts/restore_or_initdb.sh

        --encoding=UTF8

        --locale=C.UTF-8

      keep_existing_recovery_conf: true

    post_init: /etc/timescaledb/scripts/post_init.sh

    dcs:

      loop_wait: 10

      maximum_lag_on_failover: 33554432

# Adding this as per https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/values/high_throughput.example.yaml#L47-L58

      synchronous_mode: true

      master_start_timeout: 0

      postgresql:

        parameters:

          archive_command: "/etc/timescaledb/scripts/pgbackrest_archive.sh %p"

          archive_mode: 'on'

          archive_timeout: 1800s

<snip>

          restart_after_crash: 'off'

          shared_buffers: 46GB

          superuser_reserved_connections: 10

          track_io_timing: 'on'

          wal_buffers: 128MB

          wal_keep_segments: 64

          wal_writer_flush_after: 16MB

          work_mem: 256MB

          pg_stat_statements.max: 5000

<snip>

        use_slots: false

      retry_timeout: 10

      ttl: 30

  kubernetes:

    role_label: role

    scope_label: cluster-name

    use_endpoints: true

  postgresql:

    create_replica_methods:

    - pgbackrest

    - basebackup

    pgbackrest:

      command: /etc/timescaledb/scripts/pgbackrest_restore.sh

<snip>

    authentication:

      replication:

        username: standby

      superuser:

        username: postgres

    listen: 0.0.0.0:5432

    pg_hba:

    - local     all             postgres                              peer

    - local     all             all                                   md5

    - hostnossl all,replication all                all                reject

    - hostssl   all             all                127.0.0.1/32       md5

    - hostssl   all             all                ::1/128            md5

    - hostssl   replication     standby            all                md5

    - hostssl   all             all                all                md5

    use_unix_socket: true

  restapi:

    listen: 0.0.0.0:8008

From: virtuel99 ***@***.***>
Sent: Thursday, May 6, 2021 8:35 AM
To: ***@***.***
Cc: ***@***.***
Subject: [EXTERNAL] [zalando/patroni] pg_hba: is not changing pg_hba.conf on standby leader. (#1929)

Use caution when interacting with this [EXTERNAL] email!

Hello,

I have a 3 nodes primary cluster with HA Proxy and Consul.
addresses are 192.168.10.131, 132 and 133 for the nodes, 120 for the HA proxy VIP, 121 and 122 for HaProxy1 and HAProxy2.

I have installed a 3 nodes Standby Cluster
addresses are 192.168.10.141, 142 and 143 for the nodes, 120 for the HA proxy VIP, 121 and 122 for HaProxy1 and HAProxy2.

Standby Leader synchronisation is done by pg_basebackup.

bootstrap: section of YAML file on Standby side is :

When I am running "service patroni start" on standby side, Standby Leader is initialized correctly, excepted for pg_hba.conf which is not been updated with 3 standby nodes (141, 142 & 143).
I have the same pg_hba.conf than Primary Leader :

What is wrong in my configuration ?
Where do I have to put the pg_hba: section ? bootstrap: section looks fine, as I want pg_hba.conf updated at instance creation.
Is the pg_hba: syntax is correct ?

Thanks in advance for your answers.

**Comment by virtuel99** [comment]
Thank you very much, guys, it is working fine now !
