### ISSUE TITLE
Method for removing cluster info from DCS

### ISSUE THREAD

**Issue by hunterhuang8810** [zalando/patroni#1932]
Dear expert,

If I want to remove cluster info from DCS， I need to run  patronictl remove command as below:

[postgres@10-177-146-143.rds-fatpod-devops.dgtest01 ~]$ patronictl remove citus-wk02
Please confirm the cluster name to remove: citus-wk02
You are about to remove all information in DCS for citus-wk02, please type: "Yes I am aware": Yes I am aware
[postgres@10-177-146-143.rds-fatpod-devops.dgtest01 ~]$ 

My problem is I want to write command in my scripts to remove with no interaction, such as a command like  patronictl remove citus-wk02 --force ,but no such options, I also checked the doc to find RESTAPI to remove cluster from DCS but I can't find.

is there method to remove cluster info from DCS with no interaction? or RESTAPI command?

Thanks a lot!

**Comment by CyberDem0n** [comment]
```
echo -e 'my-cluster-name\nYes I am aware' | patronictl remove my-cluster-name
```
