### ISSUE TITLE
Zalando Patroni on Docker Swarm, with GlusterFS Integration - 3 node docker-swarm stack setup

### ISSUE THREAD

**Issue by laplace777** [zalando/patroni#1936]
I would like to share my work with this awesome community.

I had managed to make Patroni work on Docker Swarm, using GlusterFS.

If you are interested please have a look at my setup:

**https://github.com/laplace777/patroni.git**

**Comment by CyberDem0n** [comment]
Please keep in mind that the Dockerfile in the Patroni repo was never meant to be used in production.
It has only Patroni and Postgres inside. For production, you need to take care at least about backups.
