### ISSUE TITLE
Question. Patroni without balancer.

### ISSUE THREAD

**Issue by kolbasky** [zalando/patroni#1937]
Hello.

Everywhere on the internet in the docs i see people implement patroni cluster with load balancer like haproxy.
I followed the guides and i have several working clusters now. But I wonder, what if i omit haproxy? The only thing that haproxy does is check who is master and who is replica and redirects from one port to master and from second to replica (have a look at the attached pic).
![Patroni](https://user-images.githubusercontent.com/42576088/118050142-6ddba480-b387-11eb-8834-57e94f571990.PNG)

What i want to do is: 3 etcd nodes for voting, 3 PG nodes with pgbouncer and on these nodes i install keepalived.
keepalived will use script 
curl --silent $(hostname):8008\master 2>&1 | grep -c "\"role\": \"master\""
to always keep one ip on master

and for second ip i will use script
curl --silent $(hostname):8008\master 2>&1 | grep -c "\"role\": \"replica\""
to keep second ip on one of the replicas.

This way i may save some virtual machines and will be able to see ip addresses from which clients connect (instead if haproxy ip).
And the app will have to connect to two or more different addresses instead of two ports. So no big deal here

Are there any known drawbacks in this implementation?

**Comment by CyberDem0n** [comment]
> curl --silent $(hostname):8008\master 2>&1 | grep -c ""role": "master""

Wrong, you should check the HTTP status code instead. Please read the documentation: https://patroni.readthedocs.io/en/latest/rest_api.html#health-check-endpoints

> Are there any known drawbacks in this implementation?

When there is more than one replica how would you choose where to assign the IP to?

**Comment by kolbasky** [comment]
the feature of load balancing is not used very much in our company. so i will place one ip on sync replica, or replica with sufficiently low lag in case of async replication.
