### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by feelan03** [zalando/patroni#1940]
Hello.  I need to collect information about the status of patroni in prometheus.  I examined the code and saw the integration with prometheus.  How can I take advantage of this?  When will the information appear in the documentation?

https://github.com/zalando/patroni/blob/eaa98e71e37d5061ae7b11c57cc74325b8095698/patroni/api.py#L183-L258

**Comment by CyberDem0n** [comment]
It is not released yet. If you want to use it, you can try to install Patroni directly from the master branch.

**Comment by feelan03** [comment]
Do you have a rough plan for when you want to release it?
