### ISSUE TITLE
"wal_log_hints" parameter  is not configurable 

### ISSUE THREAD

**Issue by ckh0618** [zalando/patroni#1942]
Hello. 

I just found "wal_log_hints" parameter is not configurable. 

```
    CMDLINE_OPTIONS = CaseInsensitiveDict({
        'listen_addresses': (None, lambda _: False, 90100),
        'port': (None, lambda _: False, 90100),
        'cluster_name': (None, lambda _: False, 90500),
        'wal_level': ('hot_standby', lambda v: v.lower() in ('hot_standby', 'replica', 'logical'), 90100),
        'hot_standby': ('on', lambda _: False, 90100),
        'max_connections': (100, lambda v: int(v) >= 25, 90100),
        'max_wal_senders': (10, lambda v: int(v) >= 3, 90100),
        'wal_keep_segments': (8, lambda v: int(v) >= 1, 90100),
        'wal_keep_size': ('128MB', lambda v: parse_int(v, 'MB') >= 16, 130000),
        'max_prepared_transactions': (0, lambda v: int(v) >= 0, 90100),
        'max_locks_per_transaction': (64, lambda v: int(v) >= 32, 90100),
        'track_commit_timestamp': ('off', lambda v: parse_bool(v) is not None, 90500),
        'max_replication_slots': (10, lambda v: int(v) >= 4, 90400),
        'max_worker_processes': (8, lambda v: int(v) >= 2, 90400),
        'wal_log_hints': ('on', lambda _: False, 90400)
    })
```

Is there any reason or intention for this ? 
I want to set "wal_log_hints" to off because I don't want  to produce too much WALs.

**Comment by CyberDem0n** [comment]
It is required for pg_rewind to work.

**Comment by ckh0618** [comment]
thanks for the reply. 

How about "wal_log_hints" parameter to be configurable if a user set "use_pg_rewind" to "off" ?

**Comment by CyberDem0n** [comment]
> How about "wal_log_hints" parameter to be configurable if a user set "use_pg_rewind" to "off" ?

Are you volunteering to implement it?
Please also keep in mind that enabled data_checksums effectively producing the same impact as wal_log_hints...

**Comment by mbanck** [comment]
Right, but I think not having `wal_log_hints` is a valid usecase, if you don't want/need checksums and rewind - it might drastically cut down on the size of WAL.

I do think having checksums is probably better, but others might disagree - and I'm not volunteering to implement it either
