### ISSUE TITLE
patroni is not syncing with postgresql 12

### ISSUE THREAD

**Issue by guillermocol** [zalando/patroni#1944]
Hi team,

I was trying to get patroni running with postgresql 12 and debian 10, but I get the following error message in the node1:

Jun  1 12:14:06 ip-x.x.x.x patroni[1248]: 2021-06-01 12:14:06.706 UTC [19117] LOG:  starting PostgreSQL 12.7 (Debian 12.7-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
Jun  1 12:14:06 ip-x.x.x.x patroni[1248]: 2021-06-01 12:14:06.706 UTC [19117] LOG:  listening on IPv4 address "x.x.x.x", port 5432
Jun  1 12:14:06 ip-x.x.x.x patroni[1248]: 2021-06-01 12:14:06.711 UTC [19117] LOG:  listening on Unix socket "./.s.PGSQL.5432"
Jun  1 12:14:06 ip-x.x.x.x patroni[1248]: 2021-06-01 12:14:06.727 UTC [19117] LOG:  authentication option not in name=value format: -
Jun  1 12:14:06 ip-x.x.x.x patroni[1248]: 2021-06-01 12:14:06.727 UTC [19117] CONTEXT:  line 101 of configuration file "/data/patroni/pg_hba.conf"
Jun  1 12:14:06 ip-x.x.x.x patroni[1248]: 2021-06-01 12:14:06.727 UTC [19117] FATAL:  could not load pg_hba.conf
Jun  1 12:14:06 ip-x.x.x.x patroni[1248]: 2021-06-01 12:14:06.728 UTC [19117] LOG:  database system is shut down
^C

I am creating a cluster of 2 postgresql database servers (one main and one slave) that have also patroni running in both of them, one etcd server and one HA Proxy server.

Thank you for your help,
gcol

**Comment by guillermocol** [comment]
Also the postgresql service appears as active (existed) although postgres process is running.

Warning: The unit file, source configuration file or drop-ins of postgresql.service changed on disk. Run 'systemctl daemon
● postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
   Active: active (exited) since Tue 2021-06-01 11:12:12 UTC; 1h 17min ago
  Process: 24486 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 24486 (code=exited, status=0/SUCCESS)

**Comment by bradnicholson** [comment]
The error message tells you have an error your pg_hba.conf and Postgres is not starting as a result. You need to fix that

**Comment by guillermocol** [comment]
The strange thing is that psql works and the processes are running. 
One only thing I can see is the pg_hba.config in /data/patroni/pg_hba.conf and the /etc/postgresql/12/main/pg_hba.conf are different. Do they need to be the same?

The linux version that I am using is Debian 10 Buxter.

Thank you for your help.

**Comment by guillermocol** [comment]
what I can see is for some reason the user replicator wasn't created in the database in none of the servers. Not sure why, should not do this automatically with the /etc/patroni.yml file during the installation? :/

Thank you for your help

**Comment by CyberDem0n** [comment]
> Not sure why, should not do this automatically with the /etc/patroni.yml file during the installation?

Users are created only when the absolutely new cluster is initialized by Patroni.
For the existing cluster please read https://patroni.readthedocs.io/en/latest/existing_data.html to get some ideas how it could be "converted".

**Comment by CyberDem0n** [comment]
I am not even talking that the postgresql systems unit MUST be disabled (it is the responsibility of Patroni to start and stop Postgres) and that python 2.7 is EOL for nearly 1.5 years.

**Comment by guillermocol** [comment]
Thank you CybeDem0n, I will test it. Do you know if there is a proper user guide step by step to install postgresql12 with patroni/etc/haproxy?

**Comment by guillermocol** [comment]
I am starting to loose the patience :/

I changed the pg_hba.conf to Trust from md5 and I have the users in the database postgres, but I still get this error:

Jun 02 15:13:54 ip-x.x.x.x patroni[15722]: 2021-06-02 15:13:54.839 UTC [15781] FATAL:  role "replicator" does not exist
Jun 02 15:13:54 ip-x.x.x.x patroni[15722]: 2021-06-02 15:13:54.844 UTC [15782] FATAL:  role "replicator" does not exist
Jun 02 15:13:59 ip-x.x.x.x patroni[15722]: 2021-06-02 15:13:59.846 UTC [15783] FATAL:  role "replicator" does not exist
Jun 02 15:14:00 ip-x.x.x.x patroni[15722]: 2021-06-02 15:14:00,734 INFO: Lock owner: node1; I am node1
Jun 02 15:14:00 ip-x.x.x.x patroni[15722]: 2021-06-02 15:14:00,738 INFO: no action.  i am the leader with the lock
Jun 02 15:14:04 x.x.x.x patroni[15722]: 2021-06-02 15:14:04.846 UTC [15784] FATAL:  role "replicator" does not exist
Jun 02 15:14:09 x.x.x.x patroni[15722]: 2021-06-02 15:14:09.851 UTC [15785] FATAL:  role "replicator" does not exist
Jun 02 15:14:10 x.x.x.x patroni[15722]: 2021-06-02 15:14:10,734 INFO: Lock owner: node1; I am node1
Jun 02 15:14:10 x.x.x.x patroni[15722]: 2021-06-02 15:14:10,739 INFO: no action.  i am the leader with the lock
Jun 02 15:14:14 x.x.x.x patroni[15722]: 2021-06-02 15:14:14.855 UTC [15786] FATAL:  role "replicator" does not exist

My database in both servers has the following users/roles:

postgres=# \du
                                    List of roles
 Role name  |                         Attributes                         | Member of 
------------+------------------------------------------------------------+-----------
 postgres   | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 replicator | Replication                                                | {}

This is why I am a bit confused about the errors that I am getting.

This was done already too:

CREATE USER postgres WITH SUPERUSER ENCRYPTED PASSWORD 'secretpassword';
CREATE USER replicator WITH REPLICATION ENCRYPTED PASSWORD 'reppassword'

Any opinions would be really appreciated,
thank you very much for your help!

**Comment by alago197** [comment]
I'd suggest you start again from scratch, for example studying each of the steps taken in https://github.com/alexeyklyukin/patroni-training/blob/master/bootstrap.sh  (a inital install/bootstrap script which was created by the Patroni's developers for training).

**Comment by guillermocol** [comment]
Thank you Alago197, I managed to solve my issue. The issue was my pg_hba.conf that wasn't accepting connections from the secondary postgres server. I have changed it and restarted posgresql after that. Now both patroni seem communicating correctly and both accessing to the database.

The second issue that I am investigating now is the HAProxy web interface I am not able to connect via public ip address, but the service is up and running and listening on the port 7000. Any possible suggestions?

Thank you for your help

**Comment by alago197** [comment]
Well, I'm sorry, but.. this is something unrelated to Patroni. Just ask in the haproxy mailing list  (you can subscribe to it from haproxy's main website,  https://haproxy.org). 

Regards,

**Comment by guillermocol** [comment]
Hello Alago197, 
The information provided was very helpful.  I have started from scratch and I got some improvements in the configuration  setup as the previous issues disappeared.

I can see the following logs or status of the patronis, postgresql, etcd and haproxy services in the 4 nodes (2 psql- 2 patronis, 1 etcd node and 1 haproxy node)

**Node1:**

 patroni.service - High availability PostgreSQL Cluster
   Loaded: loaded (/etc/systemd/system/patroni.service; disabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-06-05 09:17:17 UTC; 4min 59s ago
 Main PID: 6069 (patroni)
    Tasks: 5 (limit: 2373)
   Memory: 22.0M
   CGroup: /system.slice/patroni.service
           └─6069 /usr/bin/python3 /usr/local/bin/patroni /etc/patroni.yml

Jun 05 09:21:27 ip-x.x.x.1 patroni[6069]: 2021-06-05 09:21:27,644 INFO: Lock owner: None; I am node1
Jun 05 09:21:27 ip-x.x.x.1 patroni[6069]: 2021-06-05 09:21:27,647 INFO: waiting for leader to bootstrap
Jun 05 09:21:37 ip-x.x.x.1 patroni[6069]: 2021-06-05 09:21:37,644 INFO: Lock owner: None; I am node1
Jun 05 09:21:37 ip-x.x.x.1 patroni[6069]: 2021-06-05 09:21:37,647 INFO: waiting for leader to bootstrap
Jun 05 09:21:47 ip-x.x.x.1 patroni[6069]: 2021-06-05 09:21:47,645 INFO: Lock owner: None; I am node1
Jun 05 09:21:47 ip-x.x.x.1 patroni[6069]: 2021-06-05 09:21:47,647 INFO: waiting for leader to bootstrap
Jun 05 09:21:57 ip-x.x.x.1 patroni[6069]: 2021-06-05 09:21:57,644 INFO: Lock owner: None; I am node1
Jun 05 09:21:57 ip-x.x.x.1 patroni[6069]: 2021-06-05 09:21:57,647 INFO: waiting for leader to bootstrap
Jun 05 09:22:07 ip-x.x.x.1 patroni[6069]: 2021-06-05 09:22:07,644 INFO: Lock owner: None; I am node1
Jun 05 09:22:07 ip-x.x.x.1 patroni[6069]: 2021-06-05 09:22:07,647 INFO: waiting for leader to bootstrap

**Node2:**

● patroni.service - High availability PostgreSQL Cluster
   Loaded: loaded (/etc/systemd/system/patroni.service; disabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-06-05 09:09:43 UTC; 12min ago
 Main PID: 5189 (patroni)
    Tasks: 5 (limit: 2373)
   Memory: 49.9M
   CGroup: /system.slice/patroni.service
           └─5189 /usr/bin/python /usr/local/bin/patroni /etc/patroni.yml

Jun 05 09:21:24 ip-x.x.x.2 patroni[5189]: 2021-06-05 09:21:24,044 INFO: Lock owner: None; I am node2
Jun 05 09:21:24 ip-x.x.x.2 patroni[5189]: 2021-06-05 09:21:24,047 INFO: waiting for leader to bootstrap
Jun 05 09:21:34 ip-x.x.x.2 patroni[5189]: 2021-06-05 09:21:34,044 INFO: Lock owner: None; I am node2
Jun 05 09:21:34 ip-x.x.x.2 patroni[5189]: 2021-06-05 09:21:34,046 INFO: waiting for leader to bootstrap
Jun 05 09:21:44 ip-x.x.x.2 patroni[5189]: 2021-06-05 09:21:44,044 INFO: Lock owner: None; I am node2
Jun 05 09:21:44 ip-x.x.x.2 patroni[5189]: 2021-06-05 09:21:44,047 INFO: waiting for leader to bootstrap
Jun 05 09:21:54 ip-x.x.x.2 patroni[5189]: 2021-06-05 09:21:54,044 INFO: Lock owner: None; I am node2
Jun 05 09:21:54 ip-x.x.x.2 patroni[5189]: 2021-06-05 09:21:54,046 INFO: waiting for leader to bootstrap
Jun 05 09:22:04 ip-x.x.x.2 patroni[5189]: 2021-06-05 09:22:04,044 INFO: Lock owner: None; I am node2
Jun 05 09:22:04 ip-x.x.x.2 patroni[5189]: 2021-06-05 09:22:04,047 INFO: waiting for leader to bootstrap
root@ip-x.x.x.2:/etc/postgresql# systemctl status postgresql@12-main.service

postgresql@12-main.service result:

● postgresql@12-main.service - PostgreSQL Cluster 12-main
   Loaded: loaded (/lib/systemd/system/postgresql@.service; enabled-runtime; vendor preset: enabled)
   Active: active (running) since Sat 2021-06-05 09:09:45 UTC; 15min ago
  Process: 5192 ExecStart=/usr/bin/pg_ctlcluster --skip-systemctl-redirect 12-main start (code=exited, status=0/SUCCESS)
 Main PID: 5199 (postgres)
    Tasks: 7 (limit: 2373)
   Memory: 18.4M
   CGroup: /system.slice/system-postgresql.slice/postgresql@12-main.service
           ├─5199 /usr/lib/postgresql/12/bin/postgres -D /var/lib/postgresql/12/main -c config_file=/etc/postgresql/12/main/postgresql.conf
           ├─5201 postgres: 12/main: checkpointer   
           ├─5202 postgres: 12/main: background writer   
           ├─5203 postgres: 12/main: walwriter   
           ├─5204 postgres: 12/main: autovacuum launcher   
           ├─5205 postgres: 12/main: stats collector   
           └─5206 postgres: 12/main: logical replication launcher   

**ETCD node status of etcd service:**

● etcd.service - etcd - highly-available key value store
   Loaded: loaded (/lib/systemd/system/etcd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-06-05 09:01:48 UTC; 16min ago
     Docs: https://github.com/coreos/etcd
           man:etcd
 Main PID: 3462 (etcd)
    Tasks: 8 (limit: 1163)
   Memory: 21.4M
   CGroup: /system.slice/etcd.service
           └─3462 /usr/bin/etcd

Jun 05 09:01:48 node3 etcd[3462]: 8e9e05c52164694d became candidate at term 11
Jun 05 09:01:48 node3 etcd[3462]: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 11
Jun 05 09:01:48 node3 etcd[3462]: 8e9e05c52164694d became leader at term 11
Jun 05 09:01:48 node3 etcd[3462]: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 11
Jun 05 09:01:48 node3 etcd[3462]: published {Name:node3 ClientURLs:[http://x.x.x.3:2379]} to cluster cdf818194e3a8c32
Jun 05 09:01:48 node3 systemd[1]: Started etcd - highly-available key value store.
Jun 05 09:01:48 node3 etcd[3462]: ready to serve client requests
Jun 05 09:01:48 node3 etcd[3462]: serving insecure client requests on x.x.x.3:2379, this is strongly discouraged!
Jun 05 09:01:48 node3 etcd[3462]: ready to serve client requests
Jun 05 09:01:48 node3 etcd[3462]: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!


**Node4 HAPROXY Service:**

● haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/lib/systemd/system/haproxy.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-06-03 10:34:36 UTC; 1 day 22h ago
     Docs: man:haproxy(1)
           file:/usr/share/doc/haproxy/configuration.txt.gz
  Process: 1226 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $EXTRAOPTS (code=exited, status=0/SUCCESS)
 Main PID: 1227 (haproxy)
    Tasks: 2 (limit: 1163)
   Memory: 2.0M
   CGroup: /system.slice/haproxy.service
           ├─1227 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid
           └─1228 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid

Jun 03 10:34:36 node4 systemd[1]: Starting HAProxy Load Balancer...
Jun 03 10:34:36 node4 haproxy[1227]: Proxy stats started.
Jun 03 10:34:36 node4 haproxy[1227]: Proxy stats started.
Jun 03 10:34:36 node4 haproxy[1227]: Proxy postgres started.
Jun 03 10:34:36 node4 haproxy[1227]: Proxy postgres started.
Jun 03 10:34:36 node4 systemd[1]: Started HAProxy Load Balancer.

I am not sure what is the issue as using journalctl -u service or checking the logs doesn't show any typical error of connection or anything, logs in /var/log just say the status of the services showing the same messages I have provided above.

If there is any other log or config I should check, let me know I followed the following guide and all is exactly configured the same way:

https://alibaba-cloud.medium.com/how-to-set-up-a-highly-available-postgresql-cluster-using-patroni-on-ubuntu-16-04-a3a210fce2ab

I have also allowed in postgresql configs remote connections to make it easier the testing for now following this article. The configuration used seemed to work well.

https://zaiste.net/posts/postgresql-allow-remote-connections/

There is no errors, but there is not guarantee that the cluster is working as expected.
What makes me to suspect that there is still something missing is that I cannot connect to the haproxy. However, the data provided above may show some evidence of something else. Any possible ideas? 

Thank you for your help,
gcol

**Comment by alago197** [comment]
Hello,

Correct me if I'm wrong. You seem, from the etcd logs and for the patroni's log above, to have only 1 etcd node, is that correct?. If so, this is a bad configuration for both etcd and patroni, as a minimal number of nodes (read https://etcd.io/docs/v3.4/faq/, and https://speakerdeck.com/alexeyklyukin/managing-postgresql-clusters-with-patroni?slide=20) is required, for any high availability.  

Install and configure etcd on 3 nodes at least (for example, in the haproxy node, and in one of the postgresql nodes, aside the existing etcd node you already configured

Regarding any issues with haproxy, it's better you check them in the haproxy mailing list/groups.
