### ISSUE TITLE
Unable to resume from maintenance mode

### ISSUE THREAD

**Issue by dbary** [zalando/patroni#1949]
Patroni Version: 2.0.2
Postgres Version: 12
DCS: Consul (  v1.6.6  ) 
OS: Ubuntu/bionic

Hello,

I am using patronictl pause/resume command to test out scenarios with maintenance mode,  however after I put the cluster into maintenance mode ( patronictl pause), i can't seem to resume it. Below is the output from consul, it seems to revert the config right after I resume it. 

consul watch -type=key -key=shared/postgres/production/postgres-production-cluster999/config -- bash -c 'cat | jq -r .Value | base64 -d'
{"pause": false}{"pause":true}{}{"pause":true}

Here is what i was doing when consul was outputting those logs.

1 ) there was no maintenance mode to begin with
2) cluster put into maintenance mode
3) resume from maintenance mode ( but configs were reverted )

Please let me know what may be causing this.

Thanks
Dinesh

**Comment by CyberDem0n** [comment]
The `/config` key is not supposed to be empty.
Please put there something like (with `patronictl edit-config`):
```yaml
loop_wait: 10
retry_timeout: 10
ttl: 30
```

**Comment by dbary** [comment]
ahh, okay. this particular issue is resolved by doing the following.

( patronictl -c /etc/patroni/config.yml edit-config postgres-production-cluster999 --apply /etc/patroni/config.yml )

thank you for your quick response.

Dinesh

**Comment by CyberDem0n** [comment]
> resolved by doing the following.

That's totally wrong! Only the content from `bootstrap.dcs` section supposed to be in dcs. Now you ended up writing all credentials there.

**Comment by dbary** [comment]
oh some of those configs should be local  only right. Yeah, I understand what you are saying now. we are testing, so we can revert this now. I will just remove the cluster from DCS and start fresh.
