### ISSUE TITLE
Failure in starting patroni as postgres user

### ISSUE THREAD

**Issue by rjoroy89** [zalando/patroni#1950]
Hi,

Before I describe the issue I am facing, let me introduce my setup - 

OS: Ubuntu 18.04

etcd --version
etcd Version: 3.4.16
Git SHA: d19fbe541
Go Version: go1.12.17
Go OS/Arch: linux/amd64

python --version
Python 2.7.17

patroni --version
patroni 2.0.2

I am trying to bootstrap patroni on my existing test Postgresql which is running on v12.6 as postgres user but it fails to start and errors out like below - 
`● patroni.service - Patroni PostgreSQL Cluster Service
   Loaded: loaded (/etc/systemd/system/patroni.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2021-06-08 18:43:14 UTC; 1min 27s ago
     Docs: https://github.com/zalando/patroni
  Process: 12473 ExecStart=/usr/local/bin/patroni /var/log/postgres/patroni/testpg.yaml (code=exited, status=1/FAILURE)
 Main PID: 12473 (code=exited, status=1/FAILURE)

Jun 08 18:43:14 db-postgres-12-3 systemd[1]: Started Patroni PostgreSQL Cluster Service.
Jun 08 18:43:14 db-postgres-12-3 patroni[12473]: Traceback (most recent call last):
Jun 08 18:43:14 db-postgres-12-3 patroni[12473]:   File "/usr/local/bin/patroni", line 7, in <module>
Jun 08 18:43:14 db-postgres-12-3 patroni[12473]:     from patroni import main
Jun 08 18:43:14 db-postgres-12-3 patroni[12473]: ImportError: cannot import name 'main'
Jun 08 18:43:14 db-postgres-12-3 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Jun 08 18:43:14 db-postgres-12-3 systemd[1]: patroni.service: Failed with result 'exit-code'.`

It will run without any issues if I try running it  as root user like this - patroni /etc/patroni/test.yml &> /var/log/postgresql/patroni.log

Here is test.yml fyr - 

`scope: testpg
name: node3

restapi:
  listen: node3ip:8008
  connect_address: node3ip:8008

etcd3:
  hosts: node3ip:2379,node1ip:2379,node2ip:2379

bootstrap:

  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host replication replicator 127.0.0.1/32 scram-sha-256
  - host replication replicator node1ip/32 scram-sha-256
  - host replication replicator node2ip/32 scram-sha-256
  - host replication replicator node3ip/32 scram-sha-256
  - host all all 0.0.0.0/0 scram-sha-256
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb
postgresql:
  listen: node3ip:5432
  connect_address: node3ip:5432
  data_dir: /data/pgdata/12
  config_dir: /data/pgdata/12
  bin_dir: /usr/lib/postgresql/12/bin
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: replicator
      password: cccccc
    superuser:
      username: patroni
      password: aaaaaa
    rewind:  # Has no effect on postgres 10 and lower
      username: patroni
      password: aaaaaa
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
log:
   dir: /var/log/postgres
   level: INFO`
   
Here is my patroni.service file fyr- 
`[Unit]
Description=Patroni PostgreSQL Cluster Service
Documentation=https://github.com/zalando/patroni
After=etcd.service

[Service]
User=postgres
Group=postgres
Type=simple
ExecStart=/usr/local/bin/patroni /var/log/postgres/patroni/testpg.yaml
Restart=no
RestartSec=10s
LimitNOFILE=40000

[Install]
WantedBy=multi-user.target`

Another issue I noticed is that the below did not write a new log file into the path specified for patroni logs. 
`log:

   dir: /var/log/postgres`

And here is the only logs I see in journalctl - 
`Jun 08 19:15:43 nodename-3 systemd[1]: Started Patroni PostgreSQL Cluster Service.

Jun 08 19:15:43 nodename-3 patroni[13851]: Traceback (most recent call last):

Jun 08 19:15:43 nodename-3 patroni[13851]:   File "/usr/local/bin/patroni", line 7, in <module>

Jun 08 19:15:43 nodename-3 patroni[13851]:     from patroni import main

Jun 08 19:15:43 nodename-3 patroni[13851]: ImportError: cannot import name 'main'

Jun 08 19:15:43 nodename-3 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE

Jun 08 19:15:43 nodename-3 systemd[1]: patroni.service: Failed with result 'exit-code'.
`

Furthermore, if I just run patroni --version as postgres user, I get the same error - 
`Traceback (most recent call last):

  File "/usr/local/bin/patroni", line 7, in <module>
  
    from patroni import main
    
ImportError: cannot import name 'main'`

which works perfectly fine when ran as root!

And because of the above, I thought it could be a permission issue on patroni or python hence I reverted the permission as 755 on the binaries which I will not be able to set when we take this to production.

Thanks in advance for your valuable time!

Best Regards,
Rijo Roy

**Comment by alago197** [comment]
Hi,
If possible for you, I would try the latest ubuntu binary dist (which is for Patroni 2.0.2, https://ubuntu.pkgs.org/18.04/postgresql-amd64/patroni_2.0.2-1.pgdg18.04+1_all.deb.html) which uses Python 3 instead. Python 2.7 was already deprecated.

**Comment by rjoroy89** [comment]
Thanks @alago197 . Yes that solved my issue. My 1st patroni node started on my existing PG v12.6 data_directory without changing file permissions to root. And now postgres user can run patroni and patronictl commands.

I really express my sincere gratitude to all the supporters including you making this forum particularly helpful!! 

Best Regards,
Rijo Roy
