### ISSUE TITLE
Question on change of config at time of restart

### ISSUE THREAD

**Issue by sandeepkalra** [zalando/patroni#1954]
Patroni provides edit-config / reload to set the new config parameters. This works. In case we are restarting and find that config has changes then Is there a way the set new config to patroni at startup than to do multi step process of (a) starting patroni, (b) inquire of config followed by (c) set new config.

**Comment by luss** [comment]
AFAIK patroni does not offer a set of magical python scripts to do exactly
what you are asking.  Get a skilled devops/dba type to do what you need and
make sure they test, test, test to prove it works.

If this is something you only gonna need to do once or twice...  are you
sure you need to automate the task?

--Luss

**Comment by sandeepkalra** [comment]
Thanks @luss.
