### ISSUE TITLE
Feature Request: Add user defined tags and healthchecks to instances

### ISSUE THREAD

**Issue by jooof** [zalando/patroni#1958]
We are running Patroni with 5 nodes, 3 for short queries which are also participating in leader election and 2 for OLAP queries which can lag behind the leader and are not participating.

There are 2 things that I felt could really be helpful if added to patroni. 

1- the ability to add user defined tags to each instance. for example I would be able to tag a particular instance as analyze and also be able to check if an instance is tagged with a health check api like:
 `GET /tag/analyze?lag=50MB`
and also be abled to see the tags for each instance in requests like `GET /patroni `and `GET /cluster` .

2- the ability to attach a health check script to a specific health check api. For example I don't want any read or analyze query to be   redirected to leader, unless there is no other running db to do the job. So by being able to attach other (preferably python) scripts to patroni api, We can define any kind of complex health check and redirect mechanism to the databases. 

If this seems like a promising feature, I am also very happy to be able to contribute to the project this way:)

**Comment by CyberDem0n** [comment]
> the ability to add user defined tags to each instance

The `tags` section is not limited by documented tags. You can add any arbitrary information that you like and it is already visible everywhere:
```json
$ curl -sL localhost:8008/cluster | jq .
{
  "members": [
    {
      "name": "postgresql0",
      "tags": {
        "foo": "bar"
      },
      "timeline": 17,
      "state": "running",
      "host": "127.0.0.1",
      "role": "leader",
      "port": 5432,
      "api_url": "http://127.0.0.1:8008/patroni"
    }
  ]
}

$ curl -sL localhost:8008/patroni | jq .
{
  "database_system_identifier": "6971790382475598570",
  "postmaster_start_time": "2021-06-14 07:19:32.185583+02:00",
  "tags": {
    "foo": "bar"
  },
  "timeline": 17,
  "cluster_unlocked": false,
  "patroni": {
    "scope": "batman",
    "version": "2.0.2"
  },
  "state": "running",
  "role": "master",
  "xlog": {
    "location": 50491592
  },
  "server_version": 130003
}

$ patronictl list
+ Cluster: batman (6971790382475598570) -----+----+-----------+----------+
| Member      | Host      | Role   | State   | TL | Lag in MB | Tags     |
+-------------+-----------+--------+---------+----+-----------+----------+
| postgresql0 | 127.0.0.1 | Leader | running | 17 |           | foo: bar |
+-------------+-----------+--------+---------+----+-----------+----------+
```

Health checks based on tags IMO should be added to the https://github.com/zalando/patroni/blob/master/patroni/api.py#L91-L146. Specifically, this method is already in charge of checking the replication lag.

> I don't want any read or analyze query to be redirected to leader, unless there is no other running db to do the job.

Short answer: this is not something that you can achieve with Patroni REST API health checks. But, the load-balancer for example should be able to do that.

Long answer. The health check is supposed to be as fast as precise as possible. I.e. every node should speak only for itself and not take into account the states of other nodes. For example, the health check is executed on the leader node, but for a very specific tag, and specifies that the lag shouldn't exceed a certain threshold. The leader knows about other members, it also knows whether they are tagged or not, but, the leader doesn't know the precise replication lag on these replicas (information in DCS is updated only once per `loop_wait` seconds). Connecting to these nodes and checking the WAL replay position could take an indefinite time.

**Comment by jooof** [comment]
Thank you for your complete answer.
 

> Health checks based on tags IMO should be added to the https://github.com/zalando/patroni/blob/master/patroni/api.py#L91-L146. Specifically, this method is already in charge of checking the replication lag.

I'll look into it.


> The leader knows about other members, it also knows whether they are tagged or not

I think this is the totally sufficient for the user defined script. Since the main problem that I'm referring to is the ability to define health check for an instance based on whether there is no running replica with a certain tag (or basically doing any kind of logic based on the data in the dcs)


> The leader doesn't know the precise replication lag on these replicas (information in DCS is updated only once per loop_wait seconds). Connecting to these nodes and checking the WAL replay position could take an indefinite time.

At least in my case, just being abled to check the replication lag from the DCS is just fine and I don't need the exact lag between master and the replicas, even though it's not precise, the worst thing that can happen is for the period of `loop_wait `, the master and replica both accept some read query.

But still even though if this wouldn't be a fine case for most of the users, I think the ability to add user defined check script for a more complicated scenario is a useful feature.

**Comment by CyberDem0n** [comment]
> Since the main problem that I'm referring to is the ability to define health check for an instance based on whether there is no running replica with a certain tag (or basically doing any kind of logic based on the data in the dcs)

It seems that you a bit underestimate the problem. If we, for example, take the HAProxy, it is highly recommended to use `on-marked-down shutdown-sessions`. And the health check that was returning 200 on the leader due to not having enough healthy replicas will suddenly start returning 503 when some replicas are back. As a result, HAProxy will happily terminate existing connections.

IMO, the best way of solving it would be a logic in the application. If replica isn't accessible - retry the query on the primary.

**Comment by jooof** [comment]
You have a point in there. But there are 2 things I think are good to consider. 
1 is that I think this situation is something that happens not very often and so there shouldn't be a big problem for lots users. 
The second one is that when something like this happens where there is no other replica with the specific tag, whether it's because we just started the replication and there is only on master server or there is a real problem at the tagged server side, it usually takes some time for it to be fixed. So if we make the application to try to connect to a dead replica each time and then reconnect to the master db might not be so good in terms of application performance. of course you can cache the replica state in the application for a period of time so it doesn't happen every time there is a query to that instance. But I think handling this kind of logic in the service discovery itself is easier than handling it in the application, since lots of application frameworks are not so easy to be modified this way.
