### ISSUE TITLE
Change RESTAPI password procedure

### ISSUE THREAD

**Issue by czterocyty** [zalando/patroni#1961]
Hi,

Is there any procedure to change PATRONI_RESTAPI_PASSWORD and not to break running cluster in Patroni?

I this RESTAPI password somehow persisted inside Patroni. I was looking at DCS (at etcd3) and nothing found.

**Comment by CyberDem0n** [comment]
If we talk about `PATRONI_RESTAPI_PASSWORD` environment variable, then it would require restarting of Patroni.
If the password is stored in the patroni.yaml - it is enough to do a reload.

The restapi password value doesn't affect automatic failover. Between nodes Patroni calls only GET endpoints, which are not password protected.

> I was looking at DCS (at etcd3) and nothing found.

It is not very smart idea to keep passwords in DCS.
