### ISSUE TITLE
The issue template explicitly asking to use [search](https://github.com/zalando/patroni/issues?q=is%3Aissue+requested+WAL+segment+has+already+been+removed+is%3Aclosed) first.

### ISSUE THREAD

**Issue by gsl23** [zalando/patroni#1967]
The issue template explicitly asking to use [search](https://github.com/zalando/patroni/issues?q=is%3Aissue+requested+WAL+segment+has+already+been+removed+is%3Aclosed) first.

_Originally posted by @CyberDem0n in https://github.com/zalando/patroni/issues/1966#issuecomment-861490116_

I searched but didn't find answer .
Case with reinit doesn't feel good for us. DB isn't small. We have all needed wals on master, why we must reinit full DB ?
WHy patroni can't just synced lag with wals? 
We have use_pg_rewind: true

**Comment by CyberDem0n** [comment]
Please learn how continuos achieving and PITR work: https://www.postgresql.org/docs/current/continuous-archiving.html
