### ISSUE TITLE
Patroni not generating replication logs

### ISSUE THREAD

**Issue by sahanasreenath** [zalando/patroni#1968]
I have added patroni log parameters in patroni.yml file to get replication logs,

 patroni_log_destination: stderr
    patroni_log_level: INFO
    patroni_log_format: "%(asctime)s %(levelname)s: %(message)s"
    patroni_log_dateformat: ""
    patroni_log_max_queue_size: 1000
    patroni_log_dir: /var/log/patroni
    patroni_log_file_num: 4
    patroni_log_file_size: 25000000
    patroni_log_loggers:
       - { module: "patroni.postmaster", level: "WARNING" }
       - { module: "urllib3", level: "DEBUG" }

patroni is not generating any logs even after the configuration changes, I restarted the cluster to see if the effect takes place. I do not see any logs under the directory.

**Comment by CyberDem0n** [comment]
Make up your mind...
It is either environment variable, but names ALL CAPITAL.
Or it must be in config.yaml as:
```yaml
log:
  level: INFO
#...and so on
```
