### ISSUE TITLE
Help needed in setting up confd_pgbouncer for my patroni setup

### ISSUE THREAD

**Issue by rjoroy89** [zalando/patroni#1973]
Hi, 

With constant efforts to setup a HA PostgreSQL environment, I have configured my Patroni cluster in such a way that the application will hit at an NLB which will redirect based on the role of the patroni node(master/replica). The DCS I use in my case is etcd.
I wanted to use pgbouncer in this setup which will get updated about leader status using confd by referring to https://github.com/zalando/patroni/blob/master/extras/confd/templates/pgbouncer.tmpl but pgbouncer fails to determine the database section when it starts by complaining like below:

Jun 19 18:45:05 db-postgres-12-2 systemd[1]: Started Patroni PostgreSQL Cluster Service.
Jun 19 18:45:05 db-postgres-12-2 pgbouncer[10847]: 2021-06-19 18:45:05.307 UTC [10847] ERROR syntax error in configuration (/etc/pgbouncer/pgbouncer.ini:2), stopping loading
Jun 19 18:45:05 db-postgres-12-2 pgbouncer[10847]: 2021-06-19 18:45:05.308 UTC [10847] FATAL cannot load config file
Jun 19 18:45:05 db-postgres-12-2 systemd[1]: pgbouncer.service: Main process exited, code=exited, status=1/FAILURE
Jun 19 18:45:05 db-postgres-12-2 systemd[1]: pgbouncer.service: Failed with result 'exit-code'.

Here is my pgbouncer.ini file (copied as is from the above link with slight modification on auth type)
[databases]
{{with get "/leader"}}{{$leader := .Value}}{{$leadkey := printf "/members/%s" $leader}}{{with get $leadkey}}{{$data := json .Value}}{{$hostport := base (replace (index (split $data.conn_url "/") 2) "@" "/" -1)}}{{ $host := base (index (split $hostport ":") 0)}}{{ $port := base (index (split $hostport ":") 1)}}* = host={{ $host }} port={{ $port }} pool_size=10{{end}}{{end}}

[pgbouncer]
logfile = /var/log/postgresql/pgbouncer.log
pidfile = /var/run/postgresql/pgbouncer.pid
listen_addr = *
listen_port = 6432
unix_socket_dir = /var/run/postgresql
auth_type = hba
auth_file = /etc/pgbouncer/userlist.txt
auth_hba_file = /data/pgdata/12/pg_hba.conf
admin_users = pgbouncer
stats_users = pgbouncer
pool_mode = session
max_client_conn = 400
default_pool_size = 20

Secondly, I tried to follow the link https://github.com/zalando/patroni/tree/master/extras to setup confd but i am facing an issue when I run confd - the pgbouncer.tmpl I have in /etc/confd/template folder gets overwritten into /etc/pgbouncer/pgbouncer.ini

 its contents gets updated like below:
[template]
owner = "postgres"
mode = "0644"
src = "pgbouncer.tmpl"
dest = "/etc/pgbouncer/pgbouncer.ini"

reload_cmd = "systemctl reload pgbouncer"

keys = [
    "/members/","/leader"
]

Could some on please guide me in correctly configuring pgbouncer and confd for my cluster.

Appreciate your time and help!

Thanks,
Rijo Roy

**Comment by luss** [comment]
Is it normal to have Json in the INI file for Patroni?   Perhaps try
commenting out or getting rid of line 2 & 3.   Your errors message
suggest it doesn't like line2.

--Luss

**Comment by CyberDem0n** [comment]
> I have configured my Patroni cluster in such a way that the application will hit at an NLB which will redirect based on the role of the patroni node(master/replica)

Perfect, now you just need to start a pgbouncer on all hosts and set up yet another target group that will route traffic to the pgbouncer port.
You don't need to use the confd for that.

**Comment by rjoroy89** [comment]
Thanks for your inputs @luss & @CyberDem0n . 

I was in the impression that we needed to setup confd to ensure right kind of traffic(writes to /master and reads to /replica after) is sent to cluster in the event of a failover/switchover and addition/removal of instances as per this comment "It will periodically update haproxy.cfg and pgbouncer.ini with the actual list of Patroni nodes from etcd and "reload" haproxy and pgbouncer.ini when it is necessary." in https://github.com/zalando/patroni/tree/master/extras 

Thanks,
Rijo Roy
