### ISSUE TITLE
Patroni doesn't start as leader, when try to restore using pgbackrest 

### ISSUE THREAD

**Issue by chronic90** [zalando/patroni#1976]
Hello,
I have backed up one of the patroni cluster with pgbackrest, when trying to restore on another node in different network and environment.

Patroni logs: 

> 2021-06-21 17:41:49,311 INFO: bootstrap in progress
2021-06-21 17:41:59,311 INFO: Lock owner: None; I am adn-ic-noc-dev-tsdb-node-3
2021-06-21 17:41:59,311 INFO: not healthy enough for leader race
2021-06-21 17:41:59,313 INFO: bootstrap in progress
2021-06-21 17:42:09,311 INFO: Lock owner: None; I am adn-ic-noc-dev-tsdb-node-3
2021-06-21 17:42:09,311 INFO: not healthy enough for leader race
2021-06-21 17:42:09,311 INFO: bootstrap in progress
2021-06-21 17:42:19,310 INFO: Lock owner: None; I am adn-ic-noc-dev-tsdb-node-3
2021-06-21 17:42:19,311 INFO: not healthy enough for leader race
2021-06-21 17:42:19,314 INFO: bootstrap in progress
2021-06-21 17:42:29,310 INFO: Lock owner: None; I am adn-ic-noc-dev-tsdb-node-3
2021-06-21 17:42:29,311 INFO: not healthy enough for leader race
2021-06-21 17:42:29,311 INFO: bootstrap in progress
2021-06-21 17:42:39,311 INFO: Lock owner: None; I am adn-ic-noc-dev-tsdb-node-3
2021-06-21 17:42:39,311 INFO: not healthy enough for leader race
2021-06-21 17:42:39,522 INFO: bootstrap in progress
2021-06-21 17:42:49,311 INFO: Lock owner: None; I am adn-ic-noc-dev-tsdb-node-3
2021-06-21 17:42:49,311 INFO: not healthy enough for leader race
2021-06-21 17:42:49,311 INFO: bootstrap in progress
2021-06-21 17:42:59,024 INFO: postmaster pid=21956
2021-06-21 17:42:59,311 INFO: Lock owner: None; I am adn-ic-noc-dev-tsdb-node-3
2021-06-21 17:42:59,311 INFO: not healthy enough for leader race
2021-06-21 17:42:59,319 INFO: bootstrap in progress
2021-06-21 17:43:03,130 INFO: removing initialize key after failed attempt to bootstrap the cluster
2021-06-21 17:43:03,152 INFO: renaming data directory to /mnt/disks/timescaledata_2021-06-21-17-43-03

Postgresql logs:  

> Jun 21 17:42:58  patroni[17801]: 2021-06-21 17:42:58.528 P01   INFO: restore file /mnt/disks/timescaledata/base/1/1417 (0B, 100%)
Jun 21 17:42:58  patroni[17801]: 2021-06-21 17:42:58.529 P01   INFO: restore file /mnt/disks/timescaledata/base/1/13260 (0B, 100%)
Jun 21 17:42:58  patroni[17801]: 2021-06-21 17:42:58.531 P01   INFO: restore file /mnt/disks/timescaledata/base/1/13255 (0B, 100%)
Jun 21 17:42:58  patroni[17801]: 2021-06-21 17:42:58.532 P01   INFO: restore file /mnt/disks/timescaledata/base/1/13250 (0B, 100%)
Jun 21 17:42:58  patroni[17801]: 2021-06-21 17:42:58.634 P01   INFO: restore file /mnt/disks/timescaledata/base/1/13245 (0B, 100%)
Jun 21 17:42:58  patroni[17801]: 2021-06-21 17:42:58.635 P00   INFO: write updated /mnt/disks/timescaledata/postgresql.auto.conf
Jun 21 17:42:58  patroni[17801]: 2021-06-21 17:42:58.651 P00   INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)
Jun 21 17:42:58  patroni[17801]: 2021-06-21 17:42:58.656 P00   INFO: restore command end: completed successfully (2509331ms)
Jun 21 17:42:59  patroni[17801]: localhost:5432 - no response
Jun 21 17:42:59  postgres[21956]: [1-1] 2021-06-21 17:42:59.110 UTC [21956] LOG:  ending log output to stderr
Jun 21 17:42:59  patroni[17801]: 2021-06-21 17:42:59.110 UTC [21956] LOG:  ending log output to stderr
Jun 21 17:42:59  patroni[17801]: 2021-06-21 17:42:59.110 UTC [21956] HINT:  Future log output will go to log destination "syslog".
Jun 21 17:42:59  postgres[21956]: [1-2] 2021-06-21 17:42:59.110 UTC [21956] HINT:  Future log output will go to log destination "syslog".
Jun 21 17:42:59  postgres[21956]: [2-1] 2021-06-21 17:42:59.111 UTC [21956] LOG:  starting PostgreSQL 13.3 (Debian 13.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
Jun 21 17:42:59  postgres[21956]: [3-1] 2021-06-21 17:42:59.111 UTC [21956] LOG:  listening on IPv4 address "0.0.0.0", port 5432
Jun 21 17:42:59  postgres[21956]: [4-1] 2021-06-21 17:42:59.113 UTC [21956] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
Jun 21 17:42:59  postgres[21958]: [5-1] 2021-06-21 17:42:59.127 UTC [21958] LOG:  database system was interrupted; last known up at 2021-06-21 16:15:49 UTC
Jun 21 17:42:59  postgres[21958]: [6-1] 2021-06-21 17:42:59.767 UTC [21958] LOG:  restored log file "00000003.history" from archive
Jun 21 17:43:00  postgres[21958]: [7-1] 2021-06-21 17:43:00.030 UTC [21958] LOG:  restored log file "00000004.history" from archive
Jun 21 17:43:00  postgres[21966]: [5-1] 2021-06-21 17:43:00.059 UTC [21966] postgres@postgres FATAL:  the database system is starting up
Jun 21 17:43:00  postgres[21967]: [5-1] 2021-06-21 17:43:00.060 UTC [21967] postgres@postgres FATAL:  the database system is starting up
Jun 21 17:43:00  patroni[17801]: localhost:5432 - rejecting connections
Jun 21 17:43:00  postgres[21969]: [5-1] 2021-06-21 17:43:00.075 UTC [21969] postgres@postgres FATAL:  the database system is starting up
Jun 21 17:43:00  postgres[21970]: [5-1] 2021-06-21 17:43:00.076 UTC [21970] postgres@postgres FATAL:  the database system is starting up
Jun 21 17:43:00  patroni[17801]: localhost:5432 - rejecting connections
Jun 21 17:43:00  postgres[21958]: [8-1] 2021-06-21 17:43:00.329 UTC [21958] LOG:  starting point-in-time recovery to earliest consistent point
Jun 21 17:43:00  postgres[21958]: [9-1] 2021-06-21 17:43:00.642 UTC [21958] LOG:  restored log file "00000004.history" from archive
Jun 21 17:43:01  postgres[21982]: [5-1] 2021-06-21 17:43:01.092 UTC [21982] postgres@postgres FATAL:  the database system is starting up
Jun 21 17:43:01  postgres[21983]: [5-1] 2021-06-21 17:43:01.093 UTC [21983] postgres@postgres FATAL:  the database system is starting up
Jun 21 17:43:01  patroni[17801]: localhost:5432 - rejecting connections
Jun 21 17:43:02  postgres[21995]: [5-1] 2021-06-21 17:43:02.115 UTC [21995] postgres@postgres FATAL:  the database system is starting up
Jun 21 17:43:02  postgres[21996]: [5-1] 2021-06-21 17:43:02.117 UTC [21996] postgres@postgres FATAL:  the database system is starting up
Jun 21 17:43:02  patroni[17801]: localhost:5432 - rejecting connections
Jun 21 17:43:02  postgres[21958]: [10-1] 2021-06-21 17:43:02.221 UTC [21958] LOG:  restored log file "00000002000004F00000003F" from archive
Jun 21 17:43:02  postgres[21958]: [11-1] 2021-06-21 17:43:02.251 UTC [21958] FATAL:  requested timeline 4 is not a child of this server's history
Jun 21 17:43:02  postgres[21958]: [11-2] 2021-06-21 17:43:02.251 UTC [21958] DETAIL:  Latest checkpoint is at 4F0/862A0608 on timeline 2, but in the history of the requested timeline, the server forked off from that timeline at 455/AA983238.
Jun 21 17:43:02  postgres[21956]: [5-1] 2021-06-21 17:43:02.253 UTC [21956] LOG:  startup process (PID 21958) exited with exit code 1
Jun 21 17:43:02  postgres[21956]: [6-1] 2021-06-21 17:43:02.253 UTC [21956] LOG:  aborting startup due to startup process failure
Jun 21 17:43:02  postgres[21956]: [7-1] 2021-06-21 17:43:02.258 UTC [21956] LOG:  database system is shut down
Jun 21 17:43:03  patroni[17801]: localhost:5432 - no response
Jun 21 17:43:03  patroni[17801]: Traceback (most recent call last):
Jun 21 17:43:03  patroni[17801]:   File "/usr/local/bin/patroni", line 10, in <module>
Jun 21 17:43:03  patroni[17801]:     sys.exit(main())
Jun 21 17:43:03  patroni[17801]:   File "/usr/local/lib/python3.7/dist-packages/patroni/__init__.py", line 170, in main
Jun 21 17:43:03  patroni[17801]:     return patroni_main()
Jun 21 17:43:03  patroni[17801]:   File "/usr/local/lib/python3.7/dist-packages/patroni/__init__.py", line 138, in patroni_main
Jun 21 17:43:03  patroni[17801]:     abstract_main(Patroni, schema)
Jun 21 17:43:03  patroni[17801]:   File "/usr/local/lib/python3.7/dist-packages/patroni/daemon.py", line 100, in abstract_main
Jun 21 17:43:03  patroni[17801]:     controller.run()
Jun 21 17:43:03  patroni[17801]:   File "/usr/local/lib/python3.7/dist-packages/patroni/__init__.py", line 108, in run
Jun 21 17:43:03  patroni[17801]:     super(Patroni, self).run()
Jun 21 17:43:03  patroni[17801]:   File "/usr/local/lib/python3.7/dist-packages/patroni/daemon.py", line 59, in run
Jun 21 17:43:03  patroni[17801]:     self._run_cycle()
Jun 21 17:43:03  patroni[17801]:   File "/usr/local/lib/python3.7/dist-packages/patroni/__init__.py", line 111, in _run_cycle
Jun 21 17:43:03  patroni[17801]:     logger.info(self.ha.run_cycle())
Jun 21 17:43:03  patroni[17801]:   File "/usr/local/lib/python3.7/dist-packages/patroni/ha.py", line 1457, in run_cycle
Jun 21 17:43:03  patroni[17801]:     info = self._run_cycle()
Jun 21 17:43:03  patroni[17801]:   File "/usr/local/lib/python3.7/dist-packages/patroni/ha.py", line 1351, in _run_cycle
Jun 21 17:43:03  patroni[17801]:     return self.post_bootstrap()
Jun 21 17:43:03  patroni[17801]:   File "/usr/local/lib/python3.7/dist-packages/patroni/ha.py", line 1247, in post_bootstrap
Jun 21 17:43:03  patroni[17801]:     self.cancel_initialization()
Jun 21 17:43:03  patroni[17801]:   File "/usr/local/lib/python3.7/dist-packages/patroni/ha.py", line 1240, in cancel_initialization
Jun 21 17:43:03  patroni[17801]:     raise PatroniFatalException('Failed to bootstrap cluster')
Jun 21 17:43:03  patroni[17801]: patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
Jun 21 17:43:03  systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Jun 21 17:43:03  systemd[1]: patroni.service: Failed with result 'exit-code'.
Jun 21 17:45:01  CRON[22019]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jun 21 17:46:03  collectd[745]: uc_update: Value too old: name = /processes-all/disk_octets; value time = 1624297563.287; last cache update = 1624297563.287;

Tried with full and incremental backup, with archive-copy on and off.
Can you please have a look into this?

**Comment by CyberDem0n** [comment]
> DETAIL: Latest checkpoint is at 4F0/862A0608 on timeline 2, but in the history of the requested timeline, the server forked off from that timeline at 455/AA983238.

The error comes from a postgres and has nothing to do with patroni. If you perform a restore and start postgres manually you will get into the same situation.

It seems that the backup place contains history files that don't belong to the given cluster.

**Comment by chronic90** [comment]
Not restarting the Postgres manually. Followed [this article](https://community.pivotal.io/s/article/How-to-Use-pgbackrest-to-bootstrap-or-add-replica-to-HA-Patroni?language=en_US) for bootstrapping the cluster from backup.

Want to bootstrap a new cluster from another cluster backup, if you can please help it would be great!!

Patroni yaml used for bootstrapping the cluster

>scope: tfdevtsdb27
namespace: /db00439/
name: node-3
restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.100.64.16.8008
etcd3:
  host: 10.100.64.210:2379
bootstrap:
  method: pgbackrest
  pgbackrest:
      command: /etc/pgbackrest/custom.sh
      keep_existing_recovery_conf: True
      no_params: True
      recovery_conf:
          recovery_target_timeline: latest
          recovery_target_action: promote
          restore_command: pgbackrest --stanza=demo --pg1-path=/mnt/disks/timescaledata archive-get %f %p
  dcs:
    ttl: 100
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        listen_addresses: '*'
        archive_mode: "on"
        archive_command: 'pgbackrest --stanza=demo archive-push %p'
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - local all all peer
    - host replication replicator 127.0.0.1/32 md5
    - host all all 0.0.0.0/0 md5
postgresql:
    listen: 0.0.0.0
    connect_address: 10.100.64.16:5432
    data_dir: /mnt/disks/timescaledata
    bin_dir: /usr/lib/postgresql/13/bin
    config_dir: /etc/postgresql/13/main/
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: passw0rd
        superuser:
            username: postgres
            password: passw0rd
    parameters:
        unix_socket_directories: '/var/run/postgresql'
        stats_temp_directory: '/var/run/postgresql/main.pg_stat_tmp'
        log_destination: syslog
        log_min_messages: info
        log_checkpoints: true
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
log:
   dir: /var/log/postgresql
   level: INFO

custom.sh

>#!/bin/sh
mkdir -p /mnt/disks/timescaledata
pgbackrest --stanza=demo --pg1-path=/mnt/disks/timescaledata --log-level-console=info --type=immediate --target-action=promote --delta restore


If restore an sample database of few MB's, it's working fine. Cluster gets created a leader is in place we can add replicas.
But when we try to restore timescale db data, it fails.

**Comment by CyberDem0n** [comment]
> But when we try to restore timescale db data, it fails.

Please re-read the [message](https://github.com/zalando/patroni/issues/1976#issuecomment-865283257), I have nothing more to add.
