### ISSUE TITLE
sighup doesnt reload consul.register_service

### ISSUE THREAD

**Issue by tommyzli** [zalando/patroni#1988]
**Describe the bug**
The register_service setting for Consul isn't dynamically adjustable.

**To Reproduce**
1. Start Patroni with Consul as the DCS and without setting consul.register_service in patroni.yml, so it defaults to false
2. set consul.register_service: true in patroni.yml
3. reload patroni (either by sighup or by the reload endpoint)

**Expected behavior**
I'd expect this to enable Consul service registration

**Environment**
- Patroni version: 2.0.2
- PostgreSQL version: 13..3
- DCS (and its version): Consul 1.10.0

I'm happy to put together a PR if this is something that yall are interested in accepting

**Comment by CyberDem0n** [comment]
@tommyzli please, go ahead.
