### ISSUE TITLE
Cannot execute SQL commands in WAL sender for physical replication

### ISSUE THREAD

**Issue by zelgo-dba** [zalando/patroni#1989]
Hi

**Describe the bug**
Duplicate of #1977, #1969, #1979, and #1980, but my version psycopg2 = 2.8.5
I tried to install psycopg2 = 2.8.6
the error is reproducible

2021-06-30 17:05:28,630 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 738, in get_replica_timeline
cur.execute('IDENTIFY_SYSTEM')
psycopg2.errors.InternalError_: cannot execute SQL commands in WAL sender for physical replication
Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 738, in get_replica_timeline
cur.execute('IDENTIFY_SYSTEM')
psycopg2.errors.InternalError_: cannot execute SQL commands in WAL sender for physical replication

**To Reproduce**
yum install python3-psycopg2
pip3 show psycopg2
Name: psycopg2
Version: 2.8.5

**Environment**
- Patroni version: 2.0.2
- PostgreSQL version: 12

**Comment by Lobo75** [comment]
Ran into the same issue on patroni 2.0.1 and 2.0.2.

In my case the cause of the problem was psycop2 version 2.9.1.

Doing pip3 install psycop2-binary==2.8.6 corrected the issue for now.

**Comment by CyberDem0n** [comment]
I am 100% sure that the psycopg2 version used by Patroni is different from what you see in the pip3 output

**Comment by Lobo75** [comment]
I'm using a python venv, no RPM's or other means of installing psycop2 is used outside of pip3.  The version reported by pip3 is correct in my case.  

(postgres_python_venv) [postgres@mysystem psycopg2]$ python -c "import psycopg2; print(psycopg2.__version__)"
2.8.6 (dt dec pq3 ext lo64)

An strace of patroni confirms:

97118 stat("/apps/postgres_python_venv/lib64/python3.6/site-packages/psycopg2", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
97118 stat("/apps/postgres_python_venv/lib64/python3.6/site-packages/psycopg2", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
97118 stat("/apps/postgres_python_venv/lib64/python3.6/site-packages/psycopg2", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
97118 openat(AT_FDCWD, "/apps/postgres_python_venv/lib64/python3.6/site-packages/psycopg2", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
97118 getdents(3, /* 17 entries */, 32768) = 592
97118 getdents(3, /* 0 entries */, 32768) = 0
97118 close(3)                          = 0
97118 stat("/apps/postgres_python_venv/lib64/python3.6/site-packages/psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so", {st_mode=S_IFREG|0755, st_size=1159888, ...}) = 0
97118 open("/apps/postgres_python_venv/lib64/python3.6/site-packages/psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so", O_RDONLY|O_CLOEXEC) = 3

**Comment by CyberDem0n** [comment]
@Lobo75 my comment was addressed to @zelgo-dba.

**Comment by honglei** [comment]
https://github.com/psycopg/psycopg2/issues/941
