### ISSUE TITLE
In Raft mode, does Patroni only communicate with the raft service on its own node?

### ISSUE THREAD

**Issue by cobolbaby** [zalando/patroni#2000]
When the DCS of the PG high-availability cluster adopts native RAFT, how does patroni communicate with raft? Does it only communicate with the raft on its own node, or something else?

**Comment by cobolbaby** [comment]
If I use the `syncobj_admin -remove` command to take the raft service on one node offline, should it affect the `patroni` and `postgres` services on that node?

**Comment by CyberDem0n** [comment]
> how does patroni communicate with raft? Does it only communicate with the raft on its own node, or something else?

In raft any node communicates with any other node participating in the quorum. This resource could be very useful to get some ideas behind raft: http://thesecretlivesofdata.com/raft/


>    If I use the syncobj_admin -remove command to take the raft service on one node offline, should it affect the patroni and postgres services on that node?

Of course it will. It will try to work with remaining nodes as it is a part of the quorum but other nodes will reject it.

**Comment by cobolbaby** [comment]
> In raft any node communicates with any other node participating in the quorum.

What I want to know is the communication strategy between patroni and raft, rather than the communication principle between raft nodes.

> It will try to work with remaining nodes as it is a part of the quorum but other nodes will reject it.

Could you elaborate more, I don't quite understand what you mean.

**Comment by CyberDem0n** [comment]
> Could you elaborate more, I don't quite understand what you mean.

There are two types of nodes:
1. that participate in a quorum (self_addr is set)
2. read-only nodes (self_addr is null)

The second one communicates with all quorum nodes without, while the first one has to be recognized by the remaining quorum nodes in order to work.

Patroni doesn't work directly with any kind of raft nodes, it only relying on the [API provided by PySyncObj](https://github.com/bakwc/PySyncObj#usage). How does it work internally - we don't care. Just keep in mind, that the Raft leader and Patroni Leader are absolutely disconnected from each other.

**Comment by cobolbaby** [comment]
>  Just keep in mind, that the Raft leader and Patroni Leader are absolutely disconnected from each other.

I understand that patroni and raft are at different levels, and I have not confuse them.

**What I want to know is the communication strategy between patroni and raft**, rather than the communication principle between raft nodes.

When I remove a raft node, the availability of the raft service will not be affected, because most nodes work fine. But why is the patronictl list affected at this time? The command output changed from three nodes to two nodes #2005 

- before

```
+ Cluster: pgcluster_12_7_raft (6982518760078413881) ---------+
| Member | Host          | Role    | State   | TL | Lag in MB |
+--------+---------------+---------+---------+----+-----------+
| pg11   | 172.17.232.69 | Replica | running |  4 |         0 |
| pg22   | 172.17.232.66 | Leader  | running |  4 |           |
| pg33   | 172.17.232.68 | Replica | running |  4 |         0 |
+--------+---------------+---------+---------+----+-----------+
```

- execute

```
syncobj_admin -conn xxxxx -remove xxxx
```

- after

```
+ Cluster: pgcluster_12_7_raft (6982518760078413881) ---------+
| Member | Host          | Role    | State   | TL | Lag in MB |
+--------+---------------+---------+---------+----+-----------+
| pg22   | 172.17.232.66 | Leader  | running |  4 |           |
| pg33   | 172.17.232.68 | Replica | running |  4 |         0 |
+--------+---------------+---------+---------+----+-----------+
```

**Comment by cobolbaby** [comment]
If the dcs adopts etcd strategy, the patronictl list will not change when a node of etcd cluster goes offline.

**Comment by CyberDem0n** [comment]
> If the dcs adopts etcd strategy, the patronictl list will not change when a node of etcd cluster goes offline.

Well, you have the wrong expectations.
If you removed the node from the raft it will stop receiving updates and more important Patroni losing its ability to update the /member key and as a result, it disappears from patronictl list.

If you shoot your own foot - it hurts.

I already told you many times, if you want the flexibility of etcd - please use etcd.
The Raft is implemented for cases with static clusters, preferably for nodes with static IP addresses.

**Comment by cobolbaby** [comment]
> more important Patroni losing its ability to update the /member key and as a result

IMO, Patroni on the node where the removed raft is can still communicate with the raft service of other nodes. Will the raft service of other nodes reject the request sent by the node patroni? Or does the patroni on that node only communicate with the local raft?

**Comment by CyberDem0n** [comment]
I told it many times already, other quorum nodes reject all requests from the node that was removed.

**Comment by cobolbaby** [comment]
Which one of `raft service nodes` or `patroni service nodes` does `quorum nodes` refer to?

**Comment by CyberDem0n** [comment]
We are running in circles.

> Which one of raft service nodes or patroni service nodes does quorum nodes refer to?

Quorum nodes - Patroni/Raft nodes that participate in Raft quorum. Patroni node will want to participate in quorum if there is `self_addr` defined in the config.

> If I delete one raft node, it will only affect the election of raft. Why does it affect the election of patroni?

I am telling it probably for the 5th time already. The removed node can't communicate with the cluster anymore. The show is over.

**Comment by CyberDem0n** [comment]
> Patroni is implemented at two levels, the raft dcs is the data persistence layer, and patroni is the upper-level business. I'm misunderstanding?

If you replace `raft` with `etcd` -- you will get exactly that, but not with PySyncObj.

**Comment by cobolbaby** [comment]
Thank you for your patient answers, I think I probably realized what the problem is. Thanks again.
