### ISSUE TITLE
How to find the cluster's leader in haproxy.cfg file?

### ISSUE THREAD

**Issue by DXdouxin** [zalando/patroni#2001]
Hi, I have a question. Why this config file haproxy.cfg can connect to the cluster's leader? How to recognize the leader? Does haproxy interact with patroni when finding the cluser's leader?

**Comment by CyberDem0n** [comment]
HAProxy is configured for calling health-check REST API endpoints: https://patroni.readthedocs.io/en/latest/rest_api.html#health-check-endpoints

**Comment by DXdouxin** [comment]
It means the haproxy recognize the cluster's leader according to the 
patroni? @CyberDem0n
