### ISSUE TITLE
After removing a raft node, there is a problem after patroni changes master?

### ISSUE THREAD

**Issue by huiyalin525** [zalando/patroni#2005]
Problem: Remove a raft node. The problem of selecting the master of the node patroni that is removed. After the patroni cluster changed its master, its container log was printed and it did not show that the master was changed. Its master was still the master before the master was switched. Although the data is inserted into the master after the switch, the data can also be synchronized at the point removed, but there is always a problem.

You can look at my test case

Execute patronictl list
```
+ Cluster: pgcluster_12_7_raft (6982518760078413881) ---------+
| Member | Host          | Role    | State   | TL | Lag in MB |
+--------+---------------+---------+---------+----+-----------+
| pg11   | 172.17.232.69 | Replica | running |  4 |         0 |
| pg22   | 172.17.232.66 | Leader  | running |  4 |           |
| pg33   | 172.17.232.68 | Replica | running |  4 |         0 |
+--------+---------------+---------+---------+----+-----------+

```
lock top command
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
     11 postgres  20   0  712128  33888  13700 S   0.7   0.1   9:25.86 /usr/bin/python3 /usr/local/bin/patroni /home/postgres/.config/patroni/patronictl.yaml
   1480 postgres  20   0 4424444   9840   8012 S   0.3   0.0   0:01.25 postgres: pgcluster_12_7_raft: walreceiver   streaming 0/4000998
      1 postgres  20   0   19548  11444   5892 S   0.0   0.0   0:00.11 /usr/bin/python3 /usr/local/bin/patroni /home/postgres/.config/patroni/patronictl.yaml
      8 root      20   0   15852   2952   2104 S   0.0   0.0   0:00.00 /usr/sbin/sshd
    155 postgres  20   0    6992   3744   3256 S   0.0   0.0   0:00.04 bash
   1272 postgres  20   0    6992   3716   3220 S   0.0   0.0   0:00.07 bash
   1463 postgres  20   0 4424056 151264 149480 S   0.0   0.6   0:00.14 postgres -D /var/lib/postgresql/12/data --config-file=/var/lib/postgresql/12/data/postgresql.conf --listen_addresses=+
   1465 postgres  20   0   68244   4936   3168 S   0.0   0.0   0:00.00 postgres: pgcluster_12_7_raft: logger
   1466 postgres  20   0 4424168   6764   4948 S   0.0   0.0   0:00.02 postgres: pgcluster_12_7_raft: startup   recovering 000000040000000000000004
   1467 postgres  20   0 4424056  39532  37744 S   0.0   0.2   0:00.02 postgres: pgcluster_12_7_raft: checkpointer
   1468 postgres  20   0 4424056  35640  33856 S   0.0   0.1   0:00.09 postgres: pgcluster_12_7_raft: background writer
   1469 postgres  20   0   68328   4952   3168 S   0.0   0.0   0:00.01 postgres: pgcluster_12_7_raft: stats collector
   1477 postgres  20   0 4426420  25436  22380 S   0.0   0.1   0:00.10 postgres: pgcluster_12_7_raft: postgres postgres 127.0.0.1(46966) idle
   1503 postgres  20   0   10988   3520   3048 R   0.0   0.0   0:00.28 top

```
look the raft cluster  status

```
postgres@pg11:~$ syncobj_admin -conn 10.191.7.22:2223 -status
commit_idx: 23574
enabled_code_version: 0
last_applied: 23574
leader: 10.191.7.22:2223
leader_commit_idx: 23574
log_len: 22
match_idx_count: 2
match_idx_server_10.191.7.22:2222: 23574
match_idx_server_10.191.7.22:2224: 23574
next_node_idx_count: 2
next_node_idx_server_10.191.7.22:2222: 23575
next_node_idx_server_10.191.7.22:2224: 23575
partner_node_status_server_10.191.7.22:2222: 2
partner_node_status_server_10.191.7.22:2224: 2
partner_nodes_count: 2
raft_term: 269
readonly_nodes_count: 0
revision: deprecated
self: 10.191.7.22:2223
self_code_version: 0
state: 2
uptime: 55268
version: 0.3.8

```
**begin to remove node**
remove the 2222 raft node
```
postgres@pg11:~$ syncobj_admin -conn 10.191.7.22:2223 -remove 10.191.7.22:2222
SUCCESS REMOVE 10.191.7.22:2222
```

**After removing the view node status**
```
postgres@pg11:~$ syncobj_admin -conn 10.191.7.22:2223 -status
commit_idx: 23596
enabled_code_version: 0
last_applied: 23596
leader: 10.191.7.22:2223
leader_commit_idx: 23596
log_len: 44
match_idx_count: 1
match_idx_server_10.191.7.22:2224: 23596
next_node_idx_count: 1
next_node_idx_server_10.191.7.22:2224: 23597
partner_node_status_server_10.191.7.22:2224: 2
partner_nodes_count: 1
raft_term: 269
readonly_nodes_count: 0
revision: deprecated
self: 10.191.7.22:2223
self_code_version: 0
state: 2
uptime: 55325
version: 0.3.8

```
Execute patronictl list
```
+ Cluster: pgcluster_12_7_raft (6982518760078413881) ---------+
| Member | Host          | Role    | State   | TL | Lag in MB |
+--------+---------------+---------+---------+----+-----------+
| pg22   | 172.17.232.66 | Leader  | running |  4 |           |
| pg33   | 172.17.232.68 | Replica | running |  4 |         0 |
+--------+---------------+---------+---------+----+-----------+

```
pg11's top command
```
tcp        0      0 0.0.0.0:2222            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.11:45207        0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:postgresql      0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8008            0.0.0.0:*               LISTEN
tcp        0      0 pg11:56646              pureraft_pg2:postgresql ESTABLISHED
tcp        0      0 localhost:46966         localhost:postgresql    ESTABLISHED
tcp        0      0 localhost:postgresql    localhost:46966         ESTABLISHED
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN
udp        0      0 127.0.0.11:51026        0.0.0.0:*
udp        0      0 localhost:55039         localhost:55039         ESTABLISHED

```
pg11 Container log

```
2021-07-09 02:59:59,779 INFO: Lock owner: pg22; I am pg11
2021-07-09 02:59:59,780 DEBUG: does not have lock
2021-07-09 03:00:02,250 INFO: no action. I am a secondary (pg11) and following a leader (pg22)
2021-07-09 03:00:09,779 INFO: Lock owner: pg22; I am pg11
2021-07-09 03:00:09,779 DEBUG: does not have lock
2021-07-09 03:00:11,785 INFO: no action. I am a secondary (pg11) and following a leader (pg22)
2021-07-09 03:00:19,779 INFO: Lock owner: pg22; I am pg11
2021-07-09 03:00:19,780 DEBUG: does not have lock
2021-07-09 03:00:21,784 INFO: no action. I am a secondary (pg11) and following a leader (pg22)

```
look the pg11's database logs
```
postgres@pg11:/var/lib/postgresql/12/data/log$ cat postgresql-2021-07-09_022758.csv
2021-07-09 02:27:58.644 UTC,,,1463,,60e7b42e.5b7,1,,2021-07-09 02:27:58 UTC,,0,LOG,00000,"ending log output to stderr",,"Future log output will go to log destination ""csvlog"".",,,,,,,""
2021-07-09 02:27:58.774 UTC,,,1466,,60e7b42e.5ba,1,,2021-07-09 02:27:58 UTC,,0,LOG,00000,"database system was shut down at 2021-07-09 02:27:55 UTC",,,,,,,,,""
2021-07-09 02:27:58.789 UTC,,,1466,,60e7b42e.5ba,2,,2021-07-09 02:27:58 UTC,,0,LOG,00000,"entering standby mode",,,,,,,,,""
2021-07-09 02:27:59.009 UTC,,,1466,,60e7b42e.5ba,3,,2021-07-09 02:27:58 UTC,1/0,0,LOG,00000,"consistent recovery state reached at 0/4000798",,,,,,,,,""
2021-07-09 02:27:59.009 UTC,,,1466,,60e7b42e.5ba,4,,2021-07-09 02:27:58 UTC,1/0,0,LOG,00000,"invalid record length at 0/4000798: wanted 24, got 0",,,,,,,,,""
2021-07-09 02:27:59.010 UTC,,,1463,,60e7b42e.5b7,2,,2021-07-09 02:27:58 UTC,,0,LOG,00000,"database system is ready to accept read only connections",,,,,,,,,""
2021-07-09 02:27:59.082 UTC,,,1470,,60e7b42f.5be,1,,2021-07-09 02:27:59 UTC,,0,LOG,00000,"fetching timeline history file for timeline 4 from primary server",,,,,,,,,""
2021-07-09 02:27:59.410 UTC,,,1470,,60e7b42f.5be,2,,2021-07-09 02:27:59 UTC,,0,FATAL,XX000,"could not start WAL streaming: ERROR:  replication slot ""pg11"" is active for PID 359",,,,,,,,,""
2021-07-09 02:27:59.411 UTC,,,1466,,60e7b42e.5ba,5,,2021-07-09 02:27:58 UTC,1/0,0,LOG,00000,"new target timeline is 4",,,,,,,,,""
2021-07-09 02:27:59.419 UTC,,,1475,,60e7b42f.5c3,1,,2021-07-09 02:27:59 UTC,,0,FATAL,XX000,"could not start WAL streaming: ERROR:  replication slot ""pg11"" is active for PID 359",,,,,,,,,""
2021-07-09 02:27:59.427 UTC,,,1476,,60e7b42f.5c4,1,,2021-07-09 02:27:59 UTC,,0,FATAL,XX000,"could not start WAL streaming: ERROR:  replication slot ""pg11"" is active for PID 359",,,,,,,,,""
2021-07-09 02:28:04.427 UTC,,,1480,,60e7b434.5c8,1,,2021-07-09 02:28:04 UTC,,0,LOG,00000,"started streaming WAL from primary at 0/4000000 on timeline 4",,,,,,,,,""
2021-07-09 02:28:05.064 UTC,,,1466,,60e7b42e.5ba,6,,2021-07-09 02:27:58 UTC,1/0,0,LOG,00000,"redo starts at 0/4000798",,,,,,,,,""

```

Insert data into the database
```
postgres@pg22:~$ psql -U postgresql
psql: error: FATAL:  no pg_hba.conf entry for host "[local]", user "postgresql", database "postgresql", SSL off
postgres@pg22:~$ psql -U postgres
psql (12.7 (Debian 12.7-1.pgdg100+1))
Type "help" for help.

postgres=# create database test1;
CREATE DATABASE

```
look the pg11 database，Synchronized successfully
```
postgres@pg11:/var/lib/postgresql/12/data/log$ psql -U postgres
psql (12.7 (Debian 12.7-1.pgdg100+1))
Type "help" for help.

postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 test1     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
(4 rows)


```
**switchover leader**
Enter the pg22，Switch the master node to pg33
```
postgres@pg22:~$ patronictl switchover
2021-07-09 03:09:42,526 - DEBUG - Loading configuration from file /home/postgres/.config/patroni/patronictl.yaml
Master [pg22]: pg22
Candidate ['pg33'] []: pg33

```
Execute patronictl list， You can see that the switch is successful 

```
+ Cluster: pgcluster_12_7_raft (6982518760078413881) ---------+
| Member | Host          | Role    | State   | TL | Lag in MB |
+--------+---------------+---------+---------+----+-----------+
| pg22   | 172.17.232.66 | Replica | running |  5 |         0 |
| pg33   | 172.17.232.68 | Leader  | running |  5 |           |
+--------+---------------+---------+---------+----+-----------+

```
Log of the pg22 container after the master change
```
2021-07-09 03:10:54,938 INFO: Lock owner: pg33; I am pg22
2021-07-09 03:10:54,938 DEBUG: does not have lock
2021-07-09 03:10:54,941 ERROR: Failed to drop replication slot 'pg11'
2021-07-09 03:10:55,045 INFO: no action. I am a secondary (pg22) and following a leader (pg33)
2021-07-09 03:11:04,938 INFO: Lock owner: pg33; I am pg22
2021-07-09 03:11:04,938 DEBUG: does not have lock
2021-07-09 03:11:04,941 ERROR: Failed to drop replication slot 'pg11'
2021-07-09 03:11:05,045 INFO: no action. I am a secondary (pg22) and following a leader (pg33)

```

After changed of leader the pg11 database log
```
2021-07-09 02:28:04.427 UTC,,,1480,,60e7b434.5c8,1,,2021-07-09 02:28:04 UTC,,0,LOG,00000,"started streaming WAL from primary at 0/4000000 on timeline 4",,,,,,,,,""
2021-07-09 02:28:05.064 UTC,,,1466,,60e7b42e.5ba,6,,2021-07-09 02:27:58 UTC,1/0,0,LOG,00000,"redo starts at 0/4000798",,,,,,,,,""
2021-07-09 03:09:52.656 UTC,,,1480,,60e7b434.5c8,2,,2021-07-09 02:28:04 UTC,,0,LOG,00000,"replication terminated by primary server","End of WAL reached on timeline 4 at 0/4001110.",,,,,,,,""
2021-07-09 03:09:52.656 UTC,,,1480,,60e7b434.5c8,3,,2021-07-09 02:28:04 UTC,,0,FATAL,XX000,"could not send end-of-streaming message to primary: no COPY in progress",,,,,,,,,""
2021-07-09 03:09:52.657 UTC,,,1466,,60e7b42e.5ba,7,,2021-07-09 02:27:58 UTC,1/0,0,LOG,00000,"invalid record length at 0/4001110: wanted 24, got 0",,,,,,,,,""
2021-07-09 03:09:52.745 UTC,,,1570,,60e7be00.622,1,,2021-07-09 03:09:52 UTC,,0,FATAL,XX000,"could not connect to the primary server: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.",,,,,,,,,""
2021-07-09 03:09:57.666 UTC,,,1571,,60e7be05.623,1,,2021-07-09 03:09:57 UTC,,0,LOG,00000,"fetching timeline history file for timeline 5 from primary server",,,,,,,,,""
2021-07-09 03:09:57.744 UTC,,,1571,,60e7be05.623,2,,2021-07-09 03:09:57 UTC,,0,LOG,00000,"started streaming WAL from primary at 0/4000000 on timeline 4",,,,,,,,,""
2021-07-09 03:09:57.744 UTC,,,1571,,60e7be05.623,3,,2021-07-09 03:09:57 UTC,,0,LOG,00000,"replication terminated by primary server","End of WAL reached on timeline 4 at 0/4001110.",,,,,,,,""
2021-07-09 03:09:57.744 UTC,,,1466,,60e7b42e.5ba,8,,2021-07-09 02:27:58 UTC,1/0,0,LOG,00000,"new target timeline is 5",,,,,,,,,""
2021-07-09 03:09:57.745 UTC,,,1571,,60e7be05.623,4,,2021-07-09 03:09:57 UTC,,0,LOG,00000,"restarted WAL streaming at 0/4000000 on timeline 5",,,,,,,,,""

```
After  change of leader，the pg11 container log
```
2021-07-09 03:14:59,780 INFO: Lock owner: pg22; I am pg11
2021-07-09 03:14:59,780 DEBUG: does not have lock
2021-07-09 03:15:01,785 INFO: no action. I am a secondary (pg11) and following a leader (pg22)
2021-07-09 03:15:09,780 INFO: Lock owner: pg22; I am pg11
2021-07-09 03:15:09,780 DEBUG: does not have lock
2021-07-09 03:15:11,784 INFO: no action. I am a secondary (pg11) and following a leader (pg22)
2021-07-09 03:15:19,780 INFO: Lock owner: pg22; I am pg11
2021-07-09 03:15:19,780 DEBUG: does not have lock

```
After  change of leader the pg11 ports

```
postgres@pg11:~$ netstat -ntlp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:2222            0.0.0.0:*               LISTEN      11/python3
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.11:45207        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      1463/postgres
tcp        0      0 0.0.0.0:8008            0.0.0.0:*               LISTEN      11/python3
tcp6       0      0 :::22                   :::*                    LISTEN      -

```

After  change of leader,   Insert data in the pg33 master node

```
dev@container-build-2:~$ docker exec -ti pureraft_pg33_1 bash
postgres@pg33:~$ psql -U postgres
psql (12.7 (Debian 12.7-1.pgdg100+1))
Type "help" for help.

postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 test1     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
(4 rows)

postgres=# create database test2;
CREATE DATABASE
postgres=#

```
look the pg11 the data synchronization is successful

```
dev@container-build-2:~$ docker exec -ti pureraft_pg11_1 bash
postgres@pg11:~$ psql -U postgres
psql (12.7 (Debian 12.7-1.pgdg100+1))
Type "help" for help.

postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 test1     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 test2     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
(5 rows)


```
add the raft 2222 node 

```
+ Cluster: pgcluster_12_7_raft (6982518760078413881) ---------+
| Member | Host          | Role    | State   | TL | Lag in MB |
+--------+---------------+---------+---------+----+-----------+
| pg11   | 172.17.232.69 | Replica | running |  5 |         0 |
| pg22   | 172.17.232.66 | Replica | running |  5 |         0 |
| pg33   | 172.17.232.68 | Leader  | running |  5 |           |
+--------+---------------+---------+---------+----+-----------+
```

**Comment by CyberDem0n** [comment]
> syncobj_admin -conn 10.191.7.22:2223 -remove 10.191.7.22:2222

Why? Why are you doing that? 

Also, I can't really understand what you are doing and what problem you are trying to solve.

**Comment by cobolbaby** [comment]
IMO, he is verifying how the status of each node will change after the raft service of a node is abnormal.

In theory, as long as the vast majority of raft nodes are online, patroni should not be affected when reading and writing status data. But according to the above test case, when the raft on a node fails, the `pg11` on that node also starts to go wrong.

**Comment by cobolbaby** [comment]
> Problem: Remove a raft node. The problem of selecting the master of the node patroni that is removed. After the patroni cluster changed its master, its container log was printed and it did not show that the master was changed. Its master was still the master before the master was switched. Although the data is inserted into the master after the switch, the data can also be synchronized at the point removed, but there is always a problem.

Please correct the problem description, I didn't understand it.

**Comment by huiyalin525** [comment]
>Why? Why are you doing that?

When I remove a raft node, the corresponding Patroni node will also be removed When I execute the ’patronictl list‘ 

command, I want to test whether the removed node can work as well as the previous healthy cluster? Therefore, I switchover 

the master between the remaining two patroni nodes, and I want to check whether the removed node can change the 

master.Obviously it cannot be changed master, I don't know if this is a bug, this test is very important when I want to 

deploy a cluster.

**Comment by CyberDem0n** [comment]
> When I remove a raft node, the corresponding Patroni node will also be removed When I execute the ’patronictl list‘ command

Of course, it is removed. It was a quorum node and by removing it other nodes don't accept connections from it

> I want to test whether the removed node can work as well as the previous healthy cluster?

If you restart Patroni it will add itself back to the quorum (the same way as `syncobj_admin -add` does it). Another option would be removing `self_addr` from the config and restarting Patroni. After that it will start as a non-voting raft member (actually, patronictl always work this way). Non-voting in this case doesn't mean that this node could not become a postgres primary (leader). In fact, it could. Raft leader and Patroni leader are absolutely disconnected concepts.

> I want to check whether the removed node can change the master.Obviously it cannot be changed master, I don't know if this is a bug

The "removed" node can't communicate with remaining raft nodes, because it wants to do it like it is a part of a quorum, but since you forcefully "removed" it - it is not, and there are other nodes rejecting such connections. This is not a bug, but intentional behavior.

If the given node should stop being a quorum node, first you have to remove `self_addr` from the config and restart Patroni and after that use synconj_admin.

**Comment by huiyalin525** [comment]
> In fact, it could. Raft leader and Patroni leader are absolutely disconnected concepts.

I know this.thank you

> The "removed" node can't communicate with remaining raft nodes,

Patroni can only communicate with its own local raft, and raft exchanges data with other raft nodes through tcp connections to ensure data consistency. Is my understanding correct?
So,in my test case, when I delete the raft node of pg11:2222, this raft node cannot communicate with other raft nodes, which means that the patroni of pg11 cannot communicate with the other two patroni nodes. But it has no effect on the postgres cluster. pg11 postgres can also synchronize data from the leader postgres. This is normal, because before removing the raft node of pg11, it knows that it is a slave node and who is the master node. At this time, when I switch the leader between the remaining two patroni nodes, I am in the new leader’s Insert data in postgres, pg11 postgres can also synchronize data. Through the container log I can see that the patroni leader of pg11 has not changed

That can you talk about the difference between'patroni with etcd and patroni with raft? What are the advantages of'patroni with raft'?

**Comment by huiyalin525** [comment]
> In fact, it could. Raft leader and Patroni leader are absolutely disconnected concepts.

I know this.thank you

> The "removed" node can't communicate with remaining raft nodes,

Patroni can only communicate with its own local raft, and raft exchanges data with other raft nodes through tcp connections to ensure data consistency. Is my understanding correct?
So,in my test case, when I delete the raft node of pg11:2222, this raft node cannot communicate with other raft nodes, which means that the patroni of pg11 cannot communicate with the other two patroni nodes. But it has no effect on the postgres cluster. pg11 postgres can also synchronize data from the leader postgres. This is normal, because before removing the raft node of pg11, it knows that it is a slave node and who is the master node. At this time, when I switch the leader between the remaining two patroni nodes, I am in the new leader’s Insert data in postgres, pg11 postgres can also synchronize data. Through the container log I can see that the patroni leader of pg11 has not changed

That can you talk about the difference between'patroni with etcd' and 'patroni with raft'? What are the advantages of 'patroni with raft' ?

**Comment by CyberDem0n** [comment]
> Patroni can only communicate with its own local raft, and raft exchanges data with other raft nodes through tcp connections to ensure data consistency. Is my understanding correct?

More or less.

> So,in my test case, when I delete the raft node of pg11:2222, this raft node cannot communicate with other raft nodes, which means that the patroni of pg11 cannot communicate with the other two patroni nodes. But it has no effect on the postgres cluster. pg11 postgres can also synchronize data from the leader postgres.

From the moment when the node was removed it stuck with the snapshot of a cluster view that took place at the time of removal. Hence, it continues to stream from the current leader. But, it will not see any further changes of the cluster.

> That can you talk about the difference between'patroni with etcd' and 'patroni with raft'? What are the advantages of 'patroni with raft' ?

The main use-case for Raft is when you want to run just _one_ **static** Postgres cluster of two or three nodes.
If you need to run many clusters - choose Etcd. If your clusters aren't static (nodes changing IPs and/or names), or the number of nodes also supposed to be changed - choose Etcd.

**Comment by huiyalin525** [comment]
> From the moment when the node was removed it stuck with the snapshot of a cluster view that took place at the time of removal.


How long will this snapshot last? Is it a run_cycle time?

> Hence, it continues to stream from the current leader

As you said, when I removed the raft node, the patroni node had been separated from the cluster, and now we call it the A node. The A node saves the current snapshot, and the leader of the A node will not change. At this time, the cluster is artificially switched to the master node, and the leader of node A becomes a slave node. In my test case, node A can also synchronize data from the slave node. This is obviously incorrect

**Comment by CyberDem0n** [comment]
> How long will this snapshot last? Is it a run_cycle time?

forever

> As you said, when I removed the raft node, the patroni node had been separated from the cluster, and now we call it the A node. The A node saves the current snapshot, and the leader of the A node will not change. At this time, the cluster is artificially switched to the master node, and the leader of node A becomes a slave node. In my test case, node A can also synchronize data from the slave node. This is obviously incorrect

Again, I am not following what you are trying to say. And again, as I already explained many times, please stop using raft for anything but static clusters.
