### ISSUE TITLE
Unable to start patroni with Key error - KeyError: 'data_dir'

### ISSUE THREAD

**Issue by dinesh-nithyanandam** [zalando/patroni#2015]
Hi Team,

I am seeing impediments while running patroni and not sure what was this issue.

**Exception-**

Jul 22 05:19:24 rhxecmtestazew4 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]: Traceback (most recent call last):
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]:   File "/usr/local/bin/patroni", line 8, in <module>
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]:     sys.exit(main())
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]:   File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 171, in main
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]:     return patroni_main()
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]:   File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 139, in patroni_main
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]:     abstract_main(Patroni, schema)
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]:   File "/usr/local/lib/python3.9/site-packages/patroni/daemon.py", line 98, in abstract_main
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]:     controller = cls(config)
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]:   File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 33, in __init__
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]:     self.postgresql = Postgresql(self.config['postgresql'])
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]:   File "/usr/local/lib/python3.9/site-packages/patroni/postgresql/__init__.py", line 67, in __init__
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]:     self._data_dir = config['data_dir']
Jul 22 05:19:25 rhxecmtestazew4 patroni[458154]: KeyError: 'data_dir'
Jul 22 05:19:25 rhxecmtestazew4 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Jul 22 05:19:25 rhxecmtestazew4 systemd[1]: patroni.service: Failed with result 'exit-code'.

**patroni.yaml file**

scope: my-ha-cluster
name: pg-1

restapi:
  listen: 10.0.3.11:8008
  connect_address: 10.0.3.11:8008

etcd:
  host: 10.0.3.13:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:

  initdb:
  - encoding: UTF8

  pg_hba:
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator 10.0.3.11/0 md5
  - host replication replicator 10.0.3.12/0 md5
  - host all all 0.0.0.0/0 md5

  users:
    dba:
      password: admin
      options:
        - createrole
        - createdb
    repl:
      password: secret
      options:
        - replication

  postgresql:
  listen: 10.0.3.11:5432
  connect_address: 10.0.3.11:5432
  data_dir: data/postgresql0
  authentication:
    replication:
      username: replicator
      password: password
    superuser:
      username: postgres
      password: replicator
  parameters:
    unix_socket_directories: '.'

**Comment by CyberDem0n** [comment]
Your config file is invalid.
Please take configs from the repo as a reference.

**Comment by dinesh-nithyanandam** [comment]
Tried using the sample config as a reference and changed the parameters, but it was throwing different bootstrap exception, can someone please validate confirm where I am missing here

**patroni.yaml**

scope: batman
#namespace: /service/
name: postgresql0

restapi:
  listen: 10.0.3.11:8008
  connect_address: 10.0.3.11:8008
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: password

# ctl:
#   insecure: false # Allow connections to SSL sites without certs
#   certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#   cacert: /etc/ssl/certs/ssl-cacert-snakeoil.pem

etcd:
  #Provide host to do the initial discovery of the cluster topology:
  host: 10.0.3.13:2379
  #Or use "hosts" to provide multiple endpoints
  #Could be a comma separated string:
  #hosts: host1:port1,host2:port2
  #or an actual yaml list:
  #hosts:
  #- host1:port1
  #- host2:port2
  #Once discovery is complete Patroni will use the list of advertised clientURLs
  #It is possible to change this behavior through by setting:
  #use_proxies: true

#raft:
#  data_dir: .
#  self_addr: 127.0.0.1:2222
#  partner_addrs:
#  - 127.0.0.1:2223
#  - 127.0.0.1:2224

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    master_start_timeout: 300
#    synchronous_mode: false
    #standby_cluster:
      #host: 127.0.0.1
      #port: 1111
      #primary_slot_name: patroni
    postgresql:
#      use_slots: true
      parameters:
#        wal_level: hot_standby
#        hot_standby: "on"
#        max_connections: 100
#        max_worker_processes: 8
#        wal_keep_segments: 8
#        max_wal_senders: 10
#        max_replication_slots: 10
#        max_prepared_transactions: 0
#        max_locks_per_transaction: 64
#        wal_log_hints: "on"
#        track_commit_timestamp: "off"
#        archive_mode: "on"
#        archive_timeout: 1800s
#        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
#      recovery_conf:
#        restore_command: cp ../wal_archive/%f %p

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  # For kerberos gss based connectivity (discard @.*$)
  #- host replication replicator 127.0.0.1/32 gss include_realm=0
  #- host all all 0.0.0.0/0 gss include_realm=0

  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator 10.0.3.11/0 md5
  - host replication replicator 10.0.3.12/0 md5
  - host all all 0.0.0.0/0 md5
#  - hostssl all all 0.0.0.0/0 md5

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 127.0.0.1:5432
  connect_address: 127.0.0.1:5432
  data_dir: data/postgresql0
#  bin_dir:
#  config_dir:
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: password
    superuser:
      username: postgres
      password: TGerAQW0C2XE
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: rewind_password
  # Server side kerberos spn
#  krbsrvname: postgres
  parameters:
    # Fully qualified kerberos ticket file for the running user
    # same as KRB5CCNAME used by the GSS
#   krb_server_keyfile: /var/spool/keytabs/postgres
    unix_socket_directories: '.'
  # Additional fencing script executed after acquiring the leader lock but before promoting the replica
  #pre_promote: /path/to/pre_promote.sh

#watchdog:
#  mode: automatic # Allowed values: off, automatic, required
#  device: /dev/watchdog
#  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

**Exception-**

Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]: 2021-07-22 05:50:46,149 INFO: removing initialize key after failed attempt to bootstrap the cluster
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]: Traceback (most recent call last):
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:   File "/usr/local/bin/patroni", line 8, in <module>
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:     sys.exit(main())
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:   File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 171, in main
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:     return patroni_main()
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:   File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 139, in patroni_main
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:     abstract_main(Patroni, schema)
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:   File "/usr/local/lib/python3.9/site-packages/patroni/daemon.py", line 100, in abstract_main
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:     controller.run()
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:   File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 109, in run
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:     super(Patroni, self).run()
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:   File "/usr/local/lib/python3.9/site-packages/patroni/daemon.py", line 59, in run
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:     self._run_cycle()
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:   File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 112, in _run_cycle
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:     logger.info(self.ha.run_cycle())
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:   File "/usr/local/lib/python3.9/site-packages/patroni/ha.py", line 1469, in run_cycle
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:     info = self._run_cycle()
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:   File "/usr/local/lib/python3.9/site-packages/patroni/ha.py", line 1343, in _run_cycle
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:     return self.post_bootstrap()
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:   File "/usr/local/lib/python3.9/site-packages/patroni/ha.py", line 1236, in post_bootstrap
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:     self.cancel_initialization()
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:   File "/usr/local/lib/python3.9/site-packages/patroni/ha.py", line 1229, in cancel_initialization
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]:     raise PatroniFatalException('Failed to bootstrap cluster')
Jul 22 05:50:46 rhxecmtestazew4 patroni[460142]: patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'

**Comment by dinesh-nithyanandam** [comment]
Below were my pg_hba.conf file for additional reference

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     scram-sha-256
# IPv4 local connections:
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             10.0.3.10/32            scram-sha-256
host    all             all             10.0.3.11/32            scram-sha-256
host    all             all             0.0.0.0/0               md5
# IPv6 local connections:
host    all             all             ::1/128                 scram-sha-256
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust

**Comment by CyberDem0n** [comment]
In order to make your life easier please first use Patroni _without_ systemd or any other init scripts, i.e. start it directly from the command line.

**Comment by dinesh-nithyanandam** [comment]
[root@rhxecmtestazew4 bin]# ./patroni /etc/patroni.yml

Traceback (most recent call last):
  File "/usr/local/bin/./patroni", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 171, in main
    return patroni_main()
  File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 139, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.9/site-packages/patroni/daemon.py", line 98, in abstract_main
    controller = cls(config)
  File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 33, in __init__
    self.postgresql = Postgresql(self.config['postgresql'])
  File "/usr/local/lib/python3.9/site-packages/patroni/postgresql/__init__.py", line 67, in __init__
    self._data_dir = config['data_dir']
KeyError: 'data_dir'

**Comment by dinesh-nithyanandam** [comment]
I still see that it was showing up KeyError issue

**Comment by CyberDem0n** [comment]
> I still see that it was showing up KeyError issue

Your config file is still invalid.

**Comment by dinesh-nithyanandam** [comment]
scope: my-ha-cluster
name: pg-1

restapi:
  listen: 10.0.3.11:8008
  connect_address: 10.0.3.11:8008

etcd:
  host: 10.0.3.13:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:

  initdb:
  - encoding: UTF8

  pg_hba:
  - host replication replicator 127.0.0.1/32 md5
  - host all all 0.0.0.0/0 md5

  users:
    dba:
      password: admin
      options:
        - createrole
        - createdb
    repl:
      password: secret
      options:
        - replication

  postgresql:
  listen: 10.0.3.11:5432
  connect_address: 10.0.3.11:5432
  data_dir: /data/postgresql0
  authentication:
    replication:
      username: replicator
      password: password
    superuser:
      username: postgres
      password: replicator
  parameters:
    unix_socket_directories: '.'

**Comment by dinesh-nithyanandam** [comment]
Not sure - I have checked on indentations as well - but not sure where I am missing here - Between @CyberDem0n  - Thanks a lot for your swift response

**Comment by CyberDem0n** [comment]
> I have checked on indentations as well 

Really?

```yaml
  postgresql:  # Why this node is indented?
  listen: 10.0.3.11:5432
  connect_address: 10.0.3.11:5432
  data_dir: /data/postgresql0
  authentication:
    replication:
      username: replicator
      password: password
    superuser:
      username: postgres
      password: replicator
  parameters:
    unix_socket_directories: '.'
```

**Comment by dinesh-nithyanandam** [comment]
![image](https://user-images.githubusercontent.com/81683617/126600218-e001d39e-e689-408e-8e64-7fb41fe63750.png)

**Comment by dinesh-nithyanandam** [comment]
This was the latest exception 

[root@rhxecmtestazew4 bin]# ./patroni /etc/patroni.yml.sm
2021-07-22 07:04:58,022 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-07-22 07:04:58,034 INFO: Lock owner: None; I am postgresql0
2021-07-22 07:04:58,060 INFO: trying to bootstrap a new cluster
2021-07-22 07:04:58,063 ERROR: Exception during execution of long running task bootstrap
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/usr/local/lib/python3.9/site-packages/patroni/postgresql/bootstrap.py", line 292, in bootstrap
    return do_initialize(config.get(method)) and self._postgresql.config.append_pg_hba(pg_hba) \
  File "/usr/local/lib/python3.9/site-packages/patroni/postgresql/bootstrap.py", line 79, in _initdb
    ret = self._postgresql.pg_ctl('initdb', *options)
  File "/usr/local/lib/python3.9/site-packages/patroni/postgresql/__init__.py", line 199, in pg_ctl
    return subprocess.call(pg_ctl + ['-D', self._data_dir] + list(args), **kwargs) == 0
  File "/usr/local/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pg_ctl'
2021-07-22 07:04:58,069 INFO: removing initialize key after failed attempt to bootstrap the cluster
Traceback (most recent call last):
  File "/usr/local/bin/./patroni", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 171, in main
    return patroni_main()
  File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 139, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.9/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 109, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.9/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.9/site-packages/patroni/__init__.py", line 112, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.9/site-packages/patroni/ha.py", line 1469, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.9/site-packages/patroni/ha.py", line 1343, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.9/site-packages/patroni/ha.py", line 1236, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.9/site-packages/patroni/ha.py", line 1229, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'

**Comment by CyberDem0n** [comment]
I am not sure what you are trying to tell by posting screenshots here, but syntactically valid yaml file is not the same as the valid patroni config file.

Moreover, I already [pointed](https://github.com/zalando/patroni/issues/2015#issuecomment-884688546) you what is wrong with the config

**Comment by CyberDem0n** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'pg_ctl'

Since you didn't specify the `postgresql.bin_dir` and postgres binaries isn't in the default PATH you get this error.
Please, read the [documentation](https://patroni.readthedocs.io/en/latest/SETTINGS.html#postgresql) and use the issues search
