### ISSUE TITLE
Patroni does not move the master

### ISSUE THREAD

**Issue by chigarevvb** [zalando/patroni#2017]
Hi team! 
My name is Vladimir , from our client constantly reproduced some problem:
When they try change master on their node he cant switch to other node Only when reboot one node master migration go to other node. If they try do "switchower" or "failower" that causes causes the whole node to hang. I know this should work, but unfortunately i not understand why it's not working.
In log I not found some mistackes 
But I was told that when the master hangs, the node goes into the "idle" state and then the entire server hangs
I can't get more informations on time because it's bank  and my access is very limited But I try ged additional information if you can help me
Their configuration: Centos 7 , Patroni 1.5.1 Postgres 10, 3 nodes in different Datacenter 1and 2 in one 3 in other datacenter.  ``` 
```bash
 name: postgres_node3

scope: &scope cluster-pgsql

consul:
  host:  http://localhost:8500
  url: http:localhost:8500

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.*.*.*:8008
  auth: 'username:f9************

bootstrap: 
  dcs:
    ttl: &ttl 30
    loop_wait: &loop_wait 10
    retry_timeout: 10
    
    maximum_lag_on_failover: 1048576

    initdb:
    - encoding: UTF8
    - data-checksums

    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: "on"
        wal_level: hot_standby
        archive_command: mkdir -p ../wal_archive && cp %p ../wal_archive/%f
        max_wal_senders: 10
        wal_keep_segments: 8
        archive_timeout: 1800s
        max_replication_slots: 5
        hot_standby: "on"
        wal_log_hints: "on"
        default_text_search_config: "russian"
    
pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5
  - host    all             postgres         ::1/128            md5
users: 
  - postgres:
     password: f********
     options:
            - createrole
            - createdb
      
postgresql:
  listen: 0.0.0.0:5432
  connect_address: 10.*.*.*:5432
  data_dir: /var/lib/pgsql/10/data
  bin_dir: /usr/pgsql-10/bin/
  pg_rewind:
    username: superuser
    password: f**********
  pg_hba:
  - host all all localhost trust
  - host all all 0.0.0.0/0 md5
  - hostssl all all 0.0.0.0/0 md5
  - host replication replicator 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5
  - host    all             postgres         0.0.0.0/0            md5
  - local   all             all                                   trust
  replication:
    username: replicator
    password: f*********
  superuser:
    username: superuser
    password: f**********
  admin:
    username: superuser
    password: f**********
  restore: /opt/patroni/patroni/scripts/wale_restore.py

  parameters:
      log_line_prefix: '%t [%p]: [%l-1] '
      log_checkpoints: on
      log_connections: on
      log_disconnections: on
      log_lock_waits: on
      log_temp_files: 0
      log_autovacuum_min_duration: 0
      log_error_verbosity: default
      log_min_duration_statement: 1s 
``
bash 
# Do not edit this file manually!
# It will be overwritten by Patroni!
include 'postgresql.base.conf'

archive_command = 'mkdir -p ../wal_archive && cp %p ../wal_archive/%f'
archive_mode = 'off'
archive_timeout = '1800s'
autovacuum = 'off'
checkpoint_completion_target = '0.9'
cluster_name = 'cluster-pgsql'
default_statistics_target = '100'
default_text_search_config = 'russian'
effective_cache_size = '9 GB'
effective_io_concurrency = '2'
hot_standby = 'on'
listen_addresses = '0.0.0.0'
log_autovacuum_min_duration = '0'
log_checkpoints = 'True'
log_connections = 'True'
log_disconnections = 'True'
log_error_verbosity = 'default'
log_line_prefix = '%t [%p]: [%l-1] '
log_lock_waits = 'True'
log_min_duration_statement = '1s'
log_temp_files = '0'
maintenance_work_mem = '768 MB'
max_connections = '800'
max_locks_per_transaction = '64'
max_parallel_workers = '8'
max_parallel_workers_per_gather = '4'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_wal_senders = '10'
max_wal_size = '4GB'
max_worker_processes = '8'
min_wal_size = '1GB'
pg_stat_statements.track = 'all'
port = '5432'
random_page_cost = '4'
shared_buffers = '3 GB'
shared_preload_libraries = 'pg_stat_statements'
track_commit_timestamp = 'off'
wal_buffers = '16MB'
wal_keep_segments = '300'
wal_level = 'logical'
wal_log_hints = 'on'
work_mem = '1572kB'
hba_file = '/var/lib/pgsql/10/data/pg_hba.conf'
ident_file = '/var/lib/pgsql/10/data/pg_ident.conf'

**Comment by CyberDem0n** [comment]
> But I was told that when the master hangs, the node goes into the "idle" state and then the entire server hangs
> I can't get more informations on time because it's bank and my access is very limited 

Well... The very first thing you have to do - check logs.

> Their configuration: Centos 7 , Patroni 1.5.1

Really? Nearly three years old version? Do you realize how many issues have been fixed between it and the latest release?

**Comment by chigarevvb** [comment]
I understand, not everything is in my power)) Your recomented install 2.1.0 release ? Ok ,I try update on new version and try will get logs. Please, if you can, do not close the task yet.  I try will get additional information

**Comment by chigarevvb** [comment]
Please help me if you dont mind The only error found in the logs sounds like this 
 Jul 19 23:12:12 dbpmosomn1 patroni.py: 2021-07-19 23:12:12,828 ERROR: Bad value for slot 'my_slot_name' in permanent_slots: debezium it's permanent mistacken with differnts slots.  In other cases absolytly normal situation. 
 As example: 
Jul 19 23:12:12dbpmosomn1 patroni.py: 2021-07-19 23:12:12,828 ERROR: Bad value for slot 'my_slot_name' in permanent_slots: debezium
Jul 19 23:12:12 dbpmosomn1 patroni.py: 2021-07-19 23:12:12,828 ERROR: Bad value for slot 'database' in permanent_slots: cti_omni_prod
Jul 19 23:12:12 dbpmosomn1 patroni.py: 2021-07-19 23:12:12,829 ERROR: Bad value for slot 'type' in permanent_slots: logical
Jul 19 23:12:12 dbpmosomn1 patroni.py: 2021-07-19 23:12:12,829 ERROR: Bad value for slot 'plugin' in permanent_slots: pgoutput
Jul 19 23:12:12 dbpmosomn1 patroni.py: 2021-07-19 23:12:12,840 INFO: no action.  i am the leader with the lock

**Comment by CyberDem0n** [comment]
Logs only show that there is something wrong with the global config (patronictl show-config) but you didn't show it.
But, the `debezium` word in the logs makes me think that you are using logical replication and debezium.
As far as I know, most of the software doesn't correctly implement logical replication protocol what typically results in infinite time required for postgres clean shutdown and looks like symptoms you describe.
This isn't really a Patroni problem. In case of switchover the primary must be preferably shut down cleanly and the shutdown lasts until there are some walsender processes are still alive in order to ensure that all data is fully replicated. If the logical receiver is misbehaving and doesn't correctly report its flush lsn the shutdown may hand forever.

You may verify it by running `ps auxwf | grep postgres`. In the output there will be only the postmaster, walsender, and maybe logger processes.

**Comment by chigarevvb** [comment]
Dear collegies another question I'm right if I suppose what when patroni try send master to other node he waiting  while end replications And if going the lag replication he cant send master on other node ? Me send conclusion:
 select * from pg_stat_replication;
And i saw differnt between master and replica node And I suppose problem it here
-[ RECORD 1 ]----+----------------------------------
pid              | 44587
usesysid         | 16384
usename          | replicator
application_name | postgres_node3
client_addr      | 10.46.65.168
client_hostname  | 
client_port      | 36458
backend_start    | 2021-07-20 15:12:23.102741+03
backend_xmin     |
state            | streaming
sent_lsn         | 158/13213E48
write_lsn        | 158/13213E48
**flush_lsn        | 158/13213E48
replay_lsn       | 158/13213E48**
write_lag        | 00:00:00.000791
flush_lag        | 00:00:00.001248
replay_lag       | 00:00:00.001251
sync_priority    | 0
sync_state       | async
-[ RECORD 2 ]----+----------------------------------
pid              | 44561
usesysid         | 16384
usename          | replicator
application_name | postgres_node2
client_addr      | 10.46.65.167
client_hostname  | 
client_port      | 33704
backend_start    | 2021-07-20 15:12:22.220351+03
backend_xmin     |
state            | streaming
sent_lsn         | 158/13213E48
write_lsn        | 158/13213E48
**flush_lsn        | 158/13213E48
replay_lsn       | 158/131A68C0**
write_lag        | 00:00:00.006602
flush_lag        | 00:00:00.006603
replay_lag       | 00:00:06.08638
sync_priority    | 0
sync_state       | async
-[ RECORD 3 ]----+----------------------------------
pid              | 24064
usesysid         | 16384
usename          | replicator
application_name | PostgreSQL JDBC Driver
client_addr      | 10.46.65.167
client_hostname  | 
client_port      | 27754
backend_start    | 2021-07-26 11:11:52.551778+03
backend_xmin     |
state            | streaming
sent_lsn         | 158/13213E48
write_lsn        | 158/131F6E40
**flush_lsn        | 158/12EB9AF0
replay_lsn       | 158/12EB9AF0**
write_lag        | 00:00:01.159518
flush_lag        | 00:00:57.509073
replay_lag       | 00:00:57.509073
sync_priority    | 0
sync_state       | async

**Comment by CyberDem0n** [comment]
```
-[ RECORD 3 ]----+----------------------------------
pid | 24064
usesysid | 16384
usename | replicator
application_name | PostgreSQL JDBC Driver
```

Yes, it could be the problem. Shutdown finishes successfully only when all streaming replicas acknowledge that they have received everything till the last bit.
And as I already mentioned, very often libraries don't implement streaming replication protocol correctly what typically results in the infinite Postgres shutdownn.

**Comment by chigarevvb** [comment]
Thank you very much ! Perhaps this is the mistake. I will move in this direction!

**Comment by chobostar** [comment]
Here a related issue with logical decoding: https://issues.redhat.com/browse/DBZ-1727
>>Cannot shutdown PostgreSQL if there is an active Debezium connector

I wonder, @CyberDem0n could you consider a feature to terminate hunged replication during switchover if someones brings a PR ?
