### ISSUE TITLE
Not rejecting issue with synchronous_mode_strict=true when only master is alive

### ISSUE THREAD

**Issue by Terence2000** [zalando/patroni#2019]
The Patroni doc mentions following:
"it is absolutely necessary to guarantee that each write is stored durably on at least two nodes, enable synchronous_mode_strict in addition to the synchronous_mode. This parameter prevents Patroni from switching off the synchronous replication on the primary when no synchronous standby candidates are available. "
" As a downside, the primary is not be available for writes (unless the Postgres transaction explicitly turns of synchronous_mode), blocking all client write requests until at least one synchronous replica comes up."

But according to my test, with following configuration for a 3 nodes postgres cluster, 
postgres config：synchronous_commit=remote_apply, standby_names=ANY 1
Patroni config: synchronous_mode=true, synchronous_mode_strict=true
When 2 replicas goes down and I try to insert data to master, I can still fire query to the master, but without any rejection. The insert SQL will be hanging there until I bring up one of the replicas and then the data will be inserted successfully.

Is this as expected? I'm confused because the Doc I'm reading tells me the primary is "not be available for writes", to me, I'm expecting it will reject my query, not hang there and wait and then response the result. 
The observed behavior of "Not rejecting direcctly but taking the query, hanging there until a replica comes online and then return" is a headache, because from backend software perspective, I cannot easily deal with the "no response" SQL query, should I wait it forever until a response comes back? what if the 2 replicas go down for 10 days or a month and then comes back?

**Comment by CyberDem0n** [comment]
> Is this as expected?

Yes, this is how Postgres works.

> Is this as expected? I'm confused because the Doc I'm reading tells me the primary is "not be available for writes", to me, I'm expecting it will reject my query, not hang there and wait and then response the result.
The observed behavior of "Not rejecting direcctly but taking the query, hanging there until a replica comes online and then return"

One should understand, that Patroni neither modify nor replace the PostgreSQL, it only manages it. Whatever behavior Postgres has - the same will continue to exist. And such behavior is clearly described in the documentation https://www.postgresql.org/docs/current/warm-standby.html#SYNCHRONOUS-REPLICATION
```
each commit of a write transaction will wait until confirmation is received that the commit
has been written to the write-ahead log on disk of both the primary and standby server. 
```

> what if the 2 replicas go down for 10 days or a month and then comes back?

HA doesn't replace the usual monitoring, backups, and PITR. Specifically, the monitoring must notify a human person that the replica is down and that person has to take care about recovering it.
