### ISSUE TITLE
Add ETCD srv_name config parametter

### ISSUE THREAD

**Issue by DavidPavlicek** [zalando/patroni#2028]
Please consider adding ETCD SRV name config parameter to Patroni. 

As per ETCD documentation:

> The -discovery-srv-name flag additionally configures a suffix to the SRV name that is queried during discovery. Use this flag to differentiate between multiple etcd clusters under the same domain. For example, if discovery-srv=example.com and -discovery-srv-name=foo are set, the following DNS SRV queries are made:
> 
>     _etcd-server-ssl-foo._tcp.example.com
>     _etcd-server-foo._tcp.example.com

we use SRV name suffixes to differentiate ETCD clusters in our private domain (around 40k users) and there is no simple way how to point Patroni to a specific ETCD cluster using SRV.

**Comment by CyberDem0n** [comment]
It is perfectly supported, please read the docs: https://patroni.readthedocs.io/en/latest/SETTINGS.html#etcd

https://github.com/zalando/patroni/blob/c81391e3148dad86adbb79e017cf105b61c8d869/patroni/dcs/etcd.py#L287-L313

**Comment by DavidPavlicek** [comment]
OK then, how I can configure Patroni to retrieve _etcd-server-gis._tcp.ourdomain.org SRV records from DNS? (Note the -gis part of the url) Because it is not obvious from docs or even source code.

**Comment by CyberDem0n** [comment]
I see, discovery-srv-name is something that didn't exist 6 years ago.
If you want to have it supported - please feel free to implement the support.
