### ISSUE TITLE
Watchdog not supported because leader TTL 3 is less than 2x loop_wait 1

### ISSUE THREAD

**Issue by luczakmtm** [zalando/patroni#2040]
**Describe the bug**
I set ttl=3, loop_wait=1 and retry_tiemout=1, patroni leader logs no warnings but when I kill patroni leader then the new leader logs
_Watchdog not supported because leader TTL 3 is less than 2x loop_wait 1_, but 3 is greater than 2x1

**To Reproduce**
Steps to reproduce the behavior: set ttl=3, loop_wait=1 and retry_tiemout=1, kill patroni leader

**Environment**
- Patroni version: 2.0.2
- PostgreSQL version: psql (PostgreSQL) 12.7
- DCS (and its version):

**Patroni configuration file**
```
bootstrap:
  dcs:
    loop_wait: 1
    ttl: 3
    retry_timeout: 1
    (...)
```

**patronictl show-config**
```
sh-4.4$ patronictl show-config
2021-08-20 08:28:03,149 - ERROR - ObjectCache.run ApiException()
```

**Have you checked Patroni logs?**
![image](https://user-images.githubusercontent.com/25184456/130203319-9e70e2ce-5b18-4eaa-9d52-2bb6ebc82f9f.png)

**Comment by CyberDem0n** [comment]
Please don't set TTL smaller than 20s-30s.
Instead of sub-second failover you will just get a lot of false positives.

**Comment by luczakmtm** [comment]
I don't see in documentation what values are supported
https://patroni.readthedocs.io/en/latest/SETTINGS.html#dynamic-configuration-settings

Why the issue is closed? This log is misleading, it's false that 3 is less than 2x1

**Comment by CyberDem0n** [comment]
There is a separate documentation for the watchdog: https://patroni.readthedocs.io/en/latest/watchdog.html
Please pay attention to a safety_margine parameter which default value is 5s.
