### ISSUE TITLE
Is native RAFT available for production?

### ISSUE THREAD

**Issue by luciolebrillante** [zalando/patroni#2041]
Hello,

First of all, I would like you to thank you for the wonderful work you are doing.

In the release note, it was written for Patroni 2.0  that the RAFT mode (without an external etcd) is in BETA.

In which version of Patroni is it consider ready for production?

Thank you in advance,
Luciolebrillante

**Comment by CyberDem0n** [comment]
Alpha-beta-production-etc - are just words.
The world has seen many examples when the "production-ready" software is very buggy, unstable, and constantly crashing. At the same time there are also examples the the software never leaves the beta state but is stable as a rock.
I have very little idea about the user-base of RAFT, therefore can only speak about ourselves: we don't use Raft and all recent bugfixes were triggered by reports of existing users.
In the spirit of open-source I can only advise to start using it, maybe not for production systems, but for staging/testing or something similar it should be absolutely fine. After that, you can make your own opinion whether it is production-ready or not, and maybe report your experience back.
