### ISSUE TITLE
Feature request: settings for config names and connection parameters

### ISSUE THREAD

**Issue by ideev** [zalando/patroni#2042]
**Describe the feature**

Ability to customize configuration file names and all connection parameters for PostgreSQL forks.  

It would be useful to have additional configuration settings for the names of pg_hba.conf and pg_ident.conf files.  
As we can see, there are two useful undocumented YAML configuration settings:
1) for the postgresql.conf file name there is _**config_base_name**_ setting. (https://github.com/zalando/patroni/blob/75e52226a848d64317ac98264234e62706fd762c/patroni/postgresql/config.py#L297)
1) for the database name there is _**database**_ setting (https://github.com/zalando/patroni/blob/c51234557da46e492d7564234b4a6023033b484f/patroni/postgresql/__init__.py#L68)
So we already have two settings.   
We also need two additional settings for the configuration files:
1)  _**config_hba_name**_ - for the pg_hba.conf 
1) _**config_ident_name**_ - for the pg_ident.conf
These additional settings can be used instead of hard-coded values in the following code:
 - https://github.com/zalando/patroni/blob/75e52226a848d64317ac98264234e62706fd762c/patroni/postgresql/config.py#L348-L351
 - https://github.com/zalando/patroni/blob/75e52226a848d64317ac98264234e62706fd762c/patroni/postgresql/config.py#L302-L303
 
Also we have the ability to use the YAML parameter superuser.username, but its value is not used in this code: https://github.com/zalando/patroni/blob/75e52226a848d64317ac98264234e62706fd762c/patroni/postgresql/config.py#L896
 
**Expected behavior**
All names for configuration files and connection parameters can be customized.

**Additional context**
The desired functionality can be very useful for Postgres forks. This could be a continuation of earlier work on flexible Patroni customization.

**Comment by CyberDem0n** [comment]
I don't really want to invest my time in implementing the support of forks. If you want to contribute it - PRs are welcome.
