### ISSUE TITLE
Start Postgres after reboot without DCS

### ISSUE THREAD

**Issue by tifling85** [zalando/patroni#2047]
Hello.
If the DCS is unavailable, Patroni switch master to a replica. But after rebooting the server, Patroni does not start Postgres. Is it possible to start Postgres in replica mode after reboot(with the Consul unavailable)?
Thanks!

**Comment by CyberDem0n** [comment]
No, it is not. Without DCS the state can't be determined.

**Comment by tifling85** [comment]
thanks for the answer.
