### ISSUE TITLE
Postgresql Health Check before patroni decides to demote a leader node

### ISSUE THREAD

**Issue by dbary** [zalando/patroni#2049]
Hello

I would greatly appreciate if someone could list in detail the health checks performed on  Postgresql ( leader node)  BEFORE  Patroni decides to demote that node in case health check fails. 

For example if a connection can't be opened to postgres, then that's a red flag. I would like to gather a list of things Patroni checks when deciding whether Postgresql is healthy or not. 
If this information is somewhere else ( other than the code base), please let me know.

Thanks for your help.
Dinesh

**Comment by CyberDem0n** [comment]
Demote happens only if update of leader lock in DCS failed.

**Comment by dbary** [comment]
what are the criteria that update  to DCS will fail based on the status of postgres? is it only because patroni can not connect to postgres or postgres is down or are there more criterias ? that's what I wanted to know. 

Thanks
Dinesh

**Comment by dbary** [comment]
@CyberDem0n do you have any response to my last question?

**Comment by CyberDem0n** [comment]
Let me google it for you: https://www.google.de/search?q=how+patroni+works

**Comment by dbary** [comment]
well, i know from my on searches and testing that patroni does health checks but  I wanted to know what type of health checks.
Anyway, you have been helpful so far and I do not want to go down to rabbit hole.

Dinesh

**Comment by CyberDem0n** [comment]
Patroni keeps a permanent connection to Postgres. Once every heartbeat it calls a few functions located in pg_catalog, like pg_is_in_recovery() and pg_current_wal_lsn(). That's it. Also it checks that PGDATA still exists and postmaster is running.
