### ISSUE TITLE
maximum_lag_on_failover inifinite

### ISSUE THREAD

**Issue by kikijolicoeur** [zalando/patroni#2058]
Hello. Wich value should  I set  for the maximum_lag_on_failover parameter to be able to authorize Patroni to elect a replica whatever the delay of the replica.

Thanks to have develop Patroni.

Christian

**Comment by CyberDem0n** [comment]
You can use the [sys.maxsize](https://docs.python.org/3.8/library/sys.html#sys.maxsize) value.
