### ISSUE TITLE
Patronictl some options do not work

### ISSUE THREAD

**Issue by fatihmtekin** [zalando/patroni#2059]
Hello,

patroni version : 2.1.1
etcd version: 3.5.0
Postgresql: 13.4
OS: RHEL 8.4

I got this error when i want to run patronictl edit-config/failover/switchover so on.
**Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: etcd, etcd3, kubernetes'**

However, my patroni cluster and etcd cluster are healthy. When I stopped a patroni node, the other node can become leader.

patronictl -c /etc/patroni/patroni.yml list
+ Cluster: edinbrg_cluster (7004257328245966713) ----+----+-----------+
| Member   | Host               | Role    | State   | TL | Lag in MB |
+----------+--------------------+---------+---------+----+-----------+
| edinbrg1 | 10.22.47.15:6432  | Leader  | running |  6 |           |
| edinbrg2 | 10.22.47.16:6432 | Replica | running |  6 |         0 |
| edinbrg3  | 10.118.199.62:6432  | Replica | running |  6 |         0 |
+----------+--------------------+---------+---------+----+-----------+

etcdctl endpoint --cluster health
http://10.22.47.16:2379 is healthy: successfully committed proposal: took = 1.58888ms
http://10.22.47.15:2379 is healthy: successfully committed proposal: took = 1.563195ms
http://10.118.199.62:2379 is healthy: successfully committed proposal: took = 40.287882ms

etcd setting in patroni.yml is;
etcd3:
  hosts: 10.22.47.15:2379,10.22.47.16:2379,10.118.199.62:2379

I did not understand where the problem is. Can you guide me?
Thank you so much.

**Comment by CyberDem0n** [comment]
It can't be true that with the same yaml file patronictl list works, but rest of the commands don't.

**Comment by fatihmtekin** [comment]
I'm sorry for that. I didn't pay attention to the other yaml file. It worked this way.
Thank you again.
