### ISSUE TITLE
Failed to bootstrap cluster

### ISSUE THREAD

**Issue by cyhyyq** [zalando/patroni#2066]
hello everyone

After Patroni started, I checked the status and got the following error

systemctl status patroni
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/etc/systemd/system/patroni.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2021-09-23 03:50:06 UTC; 3s ago
  Process: 2274 ExecStart=/usr/local/bin/patroni /etc/patroni.yml (code=exited, status=1/FAILURE)
 Main PID: 2274 (code=exited, status=1/FAILURE)

Sep 23 03:50:06 0426e237b62a patroni[2274]: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1345, in _run_cycle
Sep 23 03:50:06 0426e237b62a patroni[2274]: return self.post_bootstrap()
Sep 23 03:50:06 0426e237b62a patroni[2274]: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1238, in post_bootstrap
Sep 23 03:50:06 0426e237b62a patroni[2274]: self.cancel_initialization()
Sep 23 03:50:06 0426e237b62a patroni[2274]: File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1231, in cancel_initialization
Sep 23 03:50:06 0426e237b62a patroni[2274]: raise PatroniFatalException('Failed to bootstrap cluster')
Sep 23 03:50:06 0426e237b62a patroni[2274]: patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
Sep 23 03:50:06 0426e237b62a systemd[1]: patroni.service: main process exited, code=exited, status=1/FAILURE
Sep 23 03:50:06 0426e237b62a systemd[1]: Unit patroni.service entered failed state.
Sep 23 03:50:06 0426e237b62a systemd[1]: patroni.service failed.

**Comment by CyberDem0n** [comment]
Please don't think that you are unique and nobody else experienced a similar "problem" (which is in fact not a problem et all).
Also, you completely ignored the issue template, that is explicitly asking to use github issue search to look for a similar problem.
