### ISSUE TITLE
How to safely add and remove nodes into and out of a patroni cluster without causing any downtime

### ISSUE THREAD

**Issue by rjoroy89** [zalando/patroni#2069]
Hi, 

Let me give a brief about my environment before anything - 

**BLUE**
OS: Ubuntu 18.04
Postgres version: 12.5
Patroni : 2.1.1
etcd: 3.5.15

I have successfully deployed a 3 node cluster setup using Patroni in my environment and now as part of a high priority project, we are planning to move to a better hardware but no downtime to achieve it. For the same I have built 3 additional nodes lets call them the **GREEN** cluster with the same set of softwares I mentioned above. I seek your valuable suggestion for my journey to successfully migrate from blue to green.

Here are my questions that I ask myself - 

1. Can I just add green's one by one to the existing blue cluster as replica nodes
2. Once the sync is completed, I wanted to remove the blue's one by one, can I do that? 
3. Would that cause any issues with etcd or patroni quorum as it know it had 6 nodes before the cutover to green? If yes, please suggest the best way to achieve this without downtime.

Looking forward to hear for your valuable guidance at the earliest.

Thanks in advance!

**Comment by CyberDem0n** [comment]
Etcd and Patroni should not necessarily run on the same hardware and it is actually better to keep them separated.
Regarding migrating Patroni to better hardware. It is a simple as starting Patroni on the new host (with a proper config) and doing the switchover.

**Comment by rjoroy89** [comment]
Thanks for the quick response @CyberDem0n . 

Since we cannot afford a separate hardware for etcd, we are running etcd along with patroni on the same database nodes. Hence, in my situation can I just cutover to green nodes and stop blue nodes - would stopping or removing blue nodes cause a downtime?

**Comment by CyberDem0n** [comment]
I will not give you any advice regarding Etcd. Please consult the documentation: https://etcd.io/docs/v3.5/op-guide/

P.S. Before rushing and doing anything in production you better start with fire drills on your test setup.

**Comment by aubu616** [comment]
Hello，po，I have the same situation,that we need transfer to another env,that's do u done with this?
