### ISSUE TITLE
failed to add new node in patroni cluster

### ISSUE THREAD

**Issue by Tekchanddagar** [zalando/patroni#2071]
Hello Team,
Below is the details of OS and Patroni versios:

OS: Ubuntu 20.04
Postgresql Version: 12.X
Patroni Version: 2.1.0

Currently we are using 2 node patroni cluster and its working fine. But we are palnning to upgrade our postgresql version using `pg_upgrade` from postgresql version 12.X to 13.X. So we have installed postgresql 13.X on both the patroni node.

But before performing `pg_upgrade` activity we want to add one more node to our existing patroni cluster.

But when we are trying to add 3rd node in the cluster we are facing issue in replication. Below are the some logs which we are getting in `patroni` log and `syslog`

patroni.log:
```
2021-09-27 06:20:05,328 ERROR: Error when fetching backup: pg_basebackup exited with code=1
2021-09-27 06:20:05,329 WARNING: Trying again in 5 seconds

```
syslog:
```
Sep 27 15:50:06 sql06 patroni[6274]: pg_basebackup: error: could not get COPY data stream: ERROR:  canceling statement due to user request
Sep 27 15:50:06 sql06 patroni[6274]: pg_basebackup: removing data directory "/var/lib/postgresql/12/main"
Sep 27 15:50:07 sql06 patroni[6274]: pg_basebackup: changes to tablespace directories will not be undone
```
The below log line indicate that user terminate the replication process. But we didn't stop/restart patroni service:
```
Sep 27 15:50:06 sql06 patroni[6274]: pg_basebackup: error: could not get COPY data stream: ERROR:  canceling statement due to user request
```

Can you please help us what causing this issue?

I have one more question can we add 3rd node with postgresql version 13.X in existing patroni cluster which have 2 node with postgresql version 12.X?

Thank You

**Comment by Tekchanddagar** [comment]
@CyberDem0n, Thank You for your response.
As per my knowledge Patroni use internall `pg_basebackup` tool of postgresql internall for basebackup.
In our case when we start patroni service on 3rd node then we can see few GB data is copied on replica node from master node but then basebackup failed.

So connectivity between nodes for port 5432 and `pg_hba.conf` entry are looking fine.If there is issue with connectivity for port 5432 and `pg_hba.conf` entry then replication will not start.

Do you have any idea whats went wrong? We have checked all logs but not geeting any other lead from postgresql logs.

Thank You

**Comment by CyberDem0n** [comment]
> Do you have any idea whats went wrong? We have checked all logs but not geeting any other lead from postgresql logs.

It is your setup and therefore your task to debug it. You can try to run pg_basebackup on your own and most likely it will fail the same way.

**Comment by Tekchanddagar** [comment]
@CyberDem0n, Thank You for your help.

We found the issue. Our developres setup a script which kill the long pending queries. So that script kill the `pg_basebckup` process also and replication never completed.

Thank You

**Comment by Tekchanddagar** [comment]
@CyberDem0n, I have one more question.

Can we use 2 node with different postgresql version in patroni cluster?
We will use same data directory for postgresql in both nodes. 

If its feasible then postgresql version upgrade activity become very easy for us.

Thank You

**Comment by CyberDem0n** [comment]
> Can we use 2 node with different postgresql version in patroni cluster?

Minor version - yes, major - no.

**Comment by Tekchanddagar** [comment]
@CyberDem0n, Thank You for your quick response.

We are aware about minor version like postgresql 12.4 and postgresql 12.8 works fine with patroni cluster.

We are checking for some documentation where we can read more about it i.e why we should not use 2 major postgresql version nodes in patroni cluster. Can you please share any URL where we can find it?

Thank You.

**Comment by CyberDem0n** [comment]
> We are checking for some documentation where we can read more about it i.e why we should not use 2 major postgresql version nodes in patroni cluster. Can you please share any URL where we can find it?

PostgreSQL docs have everything, you just need to read them: https://www.postgresql.org/docs/current/warm-standby.html#STANDBY-PLANNING
