### ISSUE TITLE
pg_upgrade 13 to 14 with patroni 

### ISSUE THREAD

**Issue by fatihmtekin** [zalando/patroni#2075]
Hello team,
I have a healthy patroni cluster with 3 nodes, PostgreSQL 13.4 on RHEL8.4. I did the following steps for major upgrade;

- Stop replica patroni nodes
- Stop leader patroni node
- initdb with version 14 (/pgdata/data14)
- pg_upgrade ( /usr/pgsql-14/bin/pg_upgrade -b /usr/pgsql-13/bin/ -B /usr/pgsql-14/bin/ -d /pgdata/data -D /pgdata/data14/)
- cp data/*.conf data14/ (sed 13 to 14)
- mv /pgdata/data /pgdata/dataold
- mv /pgdata/data14 /pgdata/data
- start patroni

Everything is okay until the "start patroni" step. Database starting gets error when starting patroni. I saw this info: 
INFO: starting as a secondary. 
I didn't understand why this happened.
Can you guide me?
Thanks a lot.

**Comment by CyberDem0n** [comment]
Have you seen the documentation https://patroni.readthedocs.io/en/latest/existing_data.html#major-upgrade-of-postgresql-version?

**Comment by fatihmtekin** [comment]
Please forgive me. I'm sorry for wasting your time.
