### ISSUE TITLE
Patroni with 2 nodes and Patroni_raft_controller without leader node

### ISSUE THREAD

**Issue by rafaelburischipfer** [zalando/patroni#2077]
**Describe the bug**
Patroni with 2 nodes and Patroni_raft_controller without leader node

People I configure Patroni to use Raft Algorithm instead use etcd.

Everything works fine, I have 2 nodes with patroni, 1 node with patroni_raft_controller and more 2 nodes with HAProxy, I tested manual switchover, manual failover, automatic failover (I stopped Patroni, I rebooted the server) and everything is OK.

But sometime I restart patroni in secundary node and after I restart patroni in primary node (try to automatic failover) but something is wrong, but node now is Replica, I don't have any Leader node anymore.

![image](https://user-images.githubusercontent.com/91749730/136066337-031138d6-62ec-44e7-bac0-f3acf509ecdc.png)

The history only has history until TL 102 but my list is in TL 103.
![image](https://user-images.githubusercontent.com/91749730/136066943-b13e8a75-81de-40bc-adb1-c4655e73a766.png)

I tried a manual failover but nothing happens.
![image](https://user-images.githubusercontent.com/91749730/136067104-39ffdf59-ee63-4af6-9908-4b072c5c2ded.png)

Could someone help me? This is the Test environment.

My patroni version is 2.1.1 and my O.S is CentOS 8, my customer is using Red Hat 8 because this I am testing in CentOS 8.

![image](https://user-images.githubusercontent.com/91749730/136067317-9e395987-3b4f-4ebc-bd70-841d00346761.png)

Both nodes with this message in Patroni log

![image](https://user-images.githubusercontent.com/91749730/136067776-6f2e9acf-c3ca-416b-a533-ba5d3628201b.png)

My raft configuration, servers 172.23.19.92 and 172.23.19.93 is Patroni nodes and 172.23.19.91 is Patroni_raft_controller node.

![image](https://user-images.githubusercontent.com/91749730/136068699-83306dd7-2081-4be8-a1ce-31cb37040102.png)

Patroni Raft Controller "service", I created a service to call Python script patroni_raft_controller.

![image](https://user-images.githubusercontent.com/91749730/136069004-3110835c-41d5-4b84-80f0-2cf77d490e0f.png)

**Comment by mbanck** [comment]
I would advise to check the Postgres logs for anything suspicious

**Comment by rafaelburischipfer** [comment]
I checked the Postgres log but I found nothing.

I tried other thing, this environment is for test purpose, I stop Patroni and Postgres service, I deleted $PGDATA directory, create again, this will take another PostgreSQL cluster, I start Patroni service again, but they start as secundary =/.
