### ISSUE TITLE
Separate configuration areas for containerization

### ISSUE THREAD

**Issue by tonybecker** [zalando/patroni#208]
I'm just starting to play with Patroni, interested in it mostly to run Postgres on Kubernetes with auto-failover.

Won't there need to be a more robust method of merging "my" config parameters, the ones that you'd typically find in the patroni yaml file, with the ones that need to be set at container creation time? At the moment (in the repository's Dockerfile) these settings are assumed to be set in entrypoint.sh, which is baked into the container, but it would be nice if we could have a standard container and mount-in the configs. This is related to #53 but is not exactly the same concern.

**Comment by alexeyklyukin** [comment]
Hi Tony,

> On 06 Jun 2016, at 02:40, Tony Becker <notifications@github.com> wrote:
> 
> I'm just starting to play with Patroni, interested in it mostly to run Postgres on Kubernetes with auto-failover.
> 
> Won't there need to be a more robust method of merging "my" config parameters, the ones that you'd typically find in the patroni yaml file, with the ones that need to be set at container creation time? At the moment (in the repository's Dockerfile) these settings are assumed to be set in entrypoint.sh, which is baked into the container, but it would be nice if we could have a standard container and mount-in the configs. This is related to #53 <https://github.com/zalando/patroni/issues/53> but is not exactly the same concern.
> 
Even now you can set any custom patroni options using the PATRONI_CONFIGURATION variable, that should be passed on as a string to the container running Patroni.

We are already working on setting the Patroni and PostgreSQL configuration dynamically and merging the values coming from different sources (dynamic updates, static .yaml configuration) together.

Take a look at the changes here: https://github.com/zalando/patroni/pull/202. They are described by the following document: https://github.com/zalando/patroni/blob/feature/dynamic_configuration/specs/dynamic_configuration.rst spe

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/zalando/patroni/issues/208>, or mute the thread <https://github.com/notifications/unsubscribe/AAUvyZf6hvh3Qp2dMrGMM4WiYdcviPT5ks5qI2x_gaJpZM4IufSs>.
> 

Kind regards,
--
Oleksii Kliukin | 5432 Engineer | phone: +4917612759799 |  hipchat: @OleksiiKliukin

**Comment by tonybecker** [comment]
I think that will address it well. Sorry I missed that when I was searching through the repo.
