### ISSUE TITLE
pg_rewind database used for connect

### ISSUE THREAD

**Issue by kikijolicoeur** [zalando/patroni#2087]
Hello.
Is there a way to indicate in yaml settings which is the database used by pg_rewind (when it is used) to connect on leader. I saw that is the database postgres used by default. Same question with the superuser.

Is it possible to have something like:
superuser:
&ensp;username: postgres
&ensp;password: zalando
&ensp;database: mydatabase
rewind:  # Has no effect on postgres 10 and lower
&ensp;username: rewind_user
&ensp;password: rewind_password
&ensp;database: mydatabase
 

Thanks a lot for Patroni.

Christian

**Comment by kikijolicoeur** [comment]
Thanks !! it works for superuser.
But I can't find a use case to force Patroni to use pg_rewind (and verify that the database I put in postgresql.database is well used)
I saw in Patroni log : 
2021-10-14 17:36:40,034 INFO: master: history=31  0/880000A0  no recovery target specified
32  0/920000A0  no recovery target specified
33  0/9A0000A0  no recovery target specified
34  0/9C0000A0  no recovery target specified
2021-10-14 17:36:40,034 INFO: Lock owner: **** my new leader****; I am **** my old leader****
2021-10-14 17:36:40,036 INFO: starting as a secondary
2021-10-14 17:36:40,051 DEBUG: Starting postgres ....

My use case:

1. stop leader, the replica is well promoted with a new timeline
2. create some data in the new leader+ force a checkpoint + force a wal swicth
3. start Patroni on old leader

So what is the best use case to force Patroni to trigger pg_rewind (for test of course).

Christian

**Comment by CyberDem0n** [comment]
> So what is the best use case to force Patroni to trigger pg_rewind (for test of course).

You have to kill -9 Patroni process and make sure it is not restarted (if you just do a graceful stop Patroni shuts postgres down). After that you wait until other node promotes, connect to the old master postgres and do something, for example create a table.

If you start Patroni after that it will do a rewind.
