### ISSUE TITLE
Implement scheduled restarts

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/patroni#209]
Patroni can already schedule a switchover to be performed at a given date/time. We need to extend this mechanism to support restarts of a given node (most commonly master). The restarts should piggyback on our existing restart mechanism, which retains the role of a node being restarted.

The specific use-case we have for this is performing automatic minor version upgrades of our production databases during the off hours.

**Comment by alexeyklyukin** [comment]
Those are the use cases I have in mind.

- Schedule a restart at a certain point in time.

We need it, for instance, to apply the restart-only PostgreSQL configuration changes in a low activity time.

- Support more than a single scheduled restart.

If we change some critical parameters like max_connections, we need to apply them to the replicas and only then to the master.

- Support a simultaneous restart of more than a single node.

We might need to restart all replicas at once.

-  Restart only the node that has only a certain role.

We need to make sure the replicas are restarted before the master, no matter which specific hosts hold those roles.

- Restart only if the restart pending flag is set.

We might want to restart nodes to apply configuration changes.

- Restart a specific node only if it has a version of PostgreSQL less than a specific one.

Minor version upgrades in the low-activity time, but only when needed.

Note that this is more powerful than just scheduling tasks via cron on the Patroni host. Because we have the cluster-wide information, we can implement additional safety checks:

- when the role is set to the master, never restart unless no replicas are present.
- when the role is set to the replica, never restart unless no master is present.

**Comment by alexeyklyukin** [comment]
We had a discussion about how to implement this, and the most simple way seems to be to decouple the task into the 2 steps:

- get the list of all nodes in the cluster from the patroni API. This would allow us to filter the list of nodes to post the restart requests, as well as to make the patronictl truly RESTful. Additionally, it would provide a simple endpoint for haproxy-like routers to discover the cluster topology.

- be able to do a scheduled restart of an individual node based on the criteria listed above (role, postgres version, pending restart flag). The restart will be posted to the node directly and the request will be stored in the DCS member section of this node. We only need to support one request at a time for a node, since we can post different requests to the replicas and to the master (therefore, applying the parameters first to the replicas and afterwards to the master will be covered). As a bonus, we don't need any locking for multiple concurrent request or any synchronization between nodes on a common object representing the scheduled restart.

**Comment by jberkus** [comment]
All of this points to implementation in a management utility, rather than in the Patroni daemon code.  It also duplicates some functionality available from container orchestation systems, although those systems don't have any PostgreSQL knowledge.

**Comment by alexeyklyukin** [comment]
I think scheduled maintenance is too important for the use case Patroni aims at (24x7 operations) to be left to the yet to be written external tools.

**Comment by alexeyklyukin** [comment]
I’d expect everyone deploying Patroni to be doing  scheduled restarts differently: by employing some cron jobs or running scripts to trigger the equivalent cloud provider capabilities. This would lead to a lot of extra maintenance when running at scale. We can avoid that by providing a simple in-core implementation that would cover a majority of possible use cases.

**Comment by jberkus** [comment]
Alexey:

Well, go for it then.  I don't personally have a use for scheduled restarts at all, unless you're talking about for PostgreSQL updates ... in which case I'd just use Kubernetes' rolling upgrade.

**Comment by CyberDem0n** [comment]
https://github.com/zalando/patroni/pull/227 and https://github.com/zalando/patroni/pull/248 are solving this issue
