### ISSUE TITLE
Standby Cluster docs possibly need a FAQ

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#2090]
I tried to setup a standby cluster with the Debian packages, but had a hard time.

I think the following (rookie) question should be answered by the docs, maybe as an FAQ similar to the RAFT one (note that I answer some of them below):

1. Must the standby cluster have the same scope as the main cluster?
2. If it has the same scope, does it need a separate DCS from the main cluster?
3. Must the standby cluster have the same filesystem layout as the main one, e.g. `data_directory`?
4. Should the standby cluster be visible from the main cluster somehow, e.g. via `patronictl list` or `patronictl topology`?

The main problem I have if I use a different scope (`14-main_standby` vs. `14-main`) is that after bootstrap, in `_configuration_to_save()`, the `postgresql.base.conf` configuration from the leader seems to be copied over to the standby leader, overwriting e.g. the different `data_directory` and then failing to start up PostgreSQL:

```
Okt 17 09:10:43 pg3 patroni@14-main_standby[15669]: 2021-10-17 09:10:43,203 INFO: Selected new etcd server http://10.0.3.164:2379
Okt 17 09:10:43 pg3 patroni@14-main_standby[15669]: 2021-10-17 09:10:43,207 INFO: No PostgreSQL configuration items changed, nothing to reload.
Okt 17 09:10:43 pg3 patroni@14-main_standby[15669]: 2021-10-17 09:10:43,212 INFO: Lock owner: None; I am pg3
Okt 17 09:10:43 pg3 patroni@14-main_standby[15669]: 2021-10-17 09:10:43,215 INFO: trying to bootstrap a new standby leader
Okt 17 09:10:46 pg3 patroni@14-main_standby[15669]: 2021-10-17 09:10:46,363 INFO: replica has been created using pg_clonecluster
Okt 17 09:10:46 pg3 patroni@14-main_standby[15669]: 2021-10-17 09:10:46,366 INFO: bootstrapped clone from remote master postgresql://pg1:5432
Okt 17 09:10:46 pg3 patroni@14-main_standby[15724]: 2021-10-17 09:10:46.501 GMT [15724] LOG:  fehlende Konfigurationsdatei »/var/lib/postgresql/14/main/postgresql.auto.conf« wird übers>
Okt 17 09:10:46 pg3 patroni@14-main_standby[15724]: 2021-10-17 09:10:46.501 UTC [15724] FATAL:  Datenverzeichnis »/var/lib/postgresql/14/main« existiert nicht
Okt 17 09:10:46 pg3 patroni@14-main_standby[15669]: 2021-10-17 09:10:46,510 INFO: postmaster pid=15724
```

Note `/var/lib/postgresql/14/main` (the leader's data directory) vs. the one the data got cloned to during bootstrap, namely ``/var/lib/postgresql/14/main_standy`.

The `configuration.append()` in `_configuration_to_save()` only fires if no `custom_conf` is set, however, I don't set that because I want Patroni to move over the regular `postgresql.conf` to `postgresql.base.conf` - should I do that during boostrap; rather and set `custom_conf`?

If I patch out the `configuration.append(os.path.basename(self._postgresql_base_conf_name))` in `_configuration_to_save()`, the standby cluster bootstraps fine, but is not visible in the main cluster's info (like `patronictl topology`), I guess that is to be expected?

If I use the same scope as the primary cluster, the `standby_cluster` section in `bootstrap/dcs` gets ignored (because the cluster exists already), and I just get a new standby in the main cluster, not a standy leader.

So I guess one needs the same scope, but a different DCS? Or is the above just a quick bugfix (don't clobber the config during standby bootstrap), and everything else works as intended?

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 14.0
- DCS (and its version): etcd 3.3.25

**Patroni configuration file**
```
    standby_cluster:
      host: pg1
      port: 5432
      create_replica_methods: ['pg_clonecluster']
      pg_clonecluster:
        command: /usr/share/patroni/pg_clonecluster_patroni
```

**Comment by CyberDem0n** [comment]
Some of these questions will go away when there will be an understanding that the standby cluster doesn't know anything about where it replicates from. It could be just a standalone Postgres instance.

And regarding `custom_conf` - it simply gets included instead of `postgresql.base.conf` and hence there is no rename happens.

**Comment by mbanck** [comment]
Ok, so to answer my own question:

1. if you use the same DCS, they must not have the same scope; otherwise, it does not matter.
2. yes, see 1.
3. this is unclear
4. no

**Comment by mbanck** [comment]
Question3 is really independent of standby cluster - I ran into it again today on a regular 2-node (non-standby) cluster installation at a client where both nodes do not have the same data directory path. I'll check if there's an issue open about this and possibly file this as a new one.

**Comment by goran-kuzmanovic** [comment]
Hey @mbanck . I know this was a while ago, but any chance you could share what is behind /usr/share/patroni/pg_clonecluster_patroni ? I want to do something similar, as default basebackup command won't cut it (mainly because of WAL directory going to default location) and my first attempt was not successful

**Comment by mbanck** [comment]
> Hey @mbanck . I know this was a while ago, but any chance you could share what is behind /usr/share/patroni/pg_clonecluster_patroni ? I want to do something similar, as default basebackup command won't cut it (mainly because of WAL directory going to default location) and my first attempt was not successful

@goran-kuzmanovic That is a script shipped with the Debian patroni package that takes care about the differences in the Debian PostgreSQL layout compared to the standard one.
