### ISSUE TITLE
logical slots keeps wal on standby clusters

### ISSUE THREAD

**Issue by ymtvs** [zalando/patroni#2098]
Hi,

Patroni Version: 2.1.1
Postgresql Version: 11.11

We have some logical slots on database and configure from patroni. After version 2.1.0 this slots create also on standby databases. pg_catalog.pg_replication_slot_advance() get errors on standby databases and keep wal. 

I saw that statement get timeout then fail. 
```

< user=dba db=test host=127.0.0.1 pid=16893 time=2021-10-21 16:14:22.069 +03 app=Patroni > LOG:  starting logical decoding for slot "test_slot"
< user=dba db=test host=127.0.0.1 pid=16893 time=2021-10-21 16:14:22.069 +03 app=Patroni > DETAIL:  Streaming transactions committing after F33/5CE7E40, reading WAL from F21/5E341240.
< user=dba db=test host=127.0.0.1 pid=16893 time=2021-10-21 16:14:22.069 +03 app=Patroni > STATEMENT:  SELECT pg_catalog.pg_replication_slot_advance('test', 'F33/45C445C0')
< user=dba db=test host=127.0.0.1 pid=16893 time=2021-10-21 16:14:22.070 +03 app=Patroni > LOG:  logical decoding found consistent point at F21/5E341240
< user=dba db=test host=127.0.0.1 pid=16893 time=2021-10-21 16:14:22.070 +03 app=Patroni > DETAIL:  Logical decoding will begin using saved snapshot.
< user=dba db=test host=127.0.0.1 pid=16893 time=2021-10-21 16:14:22.070 +03 app=Patroni > STATEMENT:  SELECT pg_catalog.pg_replication_slot_advance('test', 'F33/45C445C0')
< user=dba db=test host=127.0.0.1 pid=16893 time=2021-10-21 16:14:24.069 +03 app=Patroni > ERROR:  canceling statement due to statement timeout
< user=dba db=test host=127.0.0.1 pid=16893 time=2021-10-21 16:14:24.069 +03 app=Patroni > STATEMENT:  SELECT pg_catalog.pg_replication_slot_advance('test', 'F33/45C445C0')
```

**Comment by K3ndu** [comment]
@CyberDem0n you fixed it in the master branch, I currently have 2.1.1 installed on live and I'm affected by this problem. How can I apply this fix to my cluster?

**Comment by NiharDudam** [comment]
@CyberDem0n - We are on 2.1.1 and facing this issue 

If I understand this correctly, this issue can happen if slot advance has to catch up lot of data right? I see the same if I bring down my logical replica for a long time (2 days) 

I have follow up questions on this issue 

- How do we detect that slot advance is failing from code? (not looking at postgres logs) 
- If I do `patronictl reinit` on that replica, seems like slot advance feature started working - is this the correct workaround?

**Comment by K3ndu** [comment]
Just install latest version and it should be fixed
