### ISSUE TITLE
Questions about Patroni role

### ISSUE THREAD

**Issue by cyhyyq** [zalando/patroni#2107]
I have three examples of PostgreSQL and built ha through Patroni. When I use patronictl to query, I find that the roles of the two standby machines are replica and standby respectively. I'd like to ask how the roles are determined

Querying the pg_stat_replication table, it is found that the synchronization modes of the two standby machines are synchronous and asynchronous respectively, but the YML is synchronous_ mode is false.

Waiting for your reply, thank you.

**Comment by cyhyyq** [comment]
I change the synchronization mode to false through the patronictl edit config. The roles of both standby machines are changed to replica

But I wonder why I changed the synchronization mode in the YML configuration to false and restarted Patroni, and the synchronization mode is still true

**Comment by cyhyyq** [comment]
Another question is whether all standby machines are in synchronous mode and one will always become asynchronous to ensure that the host will not be blocked

**Comment by CyberDem0n** [comment]
GH issues is not your personal support chat.
Most of the questions you have are answered in the documentation: https://patroni.readthedocs.io/en/latest/
Also please take some time to follow the tutorial: https://github.com/patroni-training/2019
