### ISSUE TITLE
Does Patroni only support data synchronization to port 5432

### ISSUE THREAD

**Issue by cyhyyq** [zalando/patroni#2110]
My host has modified the database port

When starting the standby machine, the standby machine does not request from the host port, but from the default port 5432

I modified postgresql.port in DCS through dynamic configuration and found that it did not take effect

Can I specify in the configuration file

Waiting for your reply thank you

**Comment by CyberDem0n** [comment]
Please stop using GH issues like your personal chat and read the [documentation](https://patroni.readthedocs.io/en/latest/SETTINGS.html)!
```
listen: IP address + port that Postgres listens to; must be accessible from other nodes in the cluster,
if you’re using streaming replication. Multiple comma-separated addresses are permitted, as long as
the port component is appended after to the last one with a colon, i.e. listen: 127.0.0.1,127.0.0.2:5432.
Patroni will use the first address from this list to establish local connections to the PostgreSQL node.
```
