### ISSUE TITLE
State of raft?

### ISSUE THREAD

**Issue by bt90** [zalando/patroni#2112]
Is it already stable enough for a production environment? I skimmed the release notes, but I'm not sure if it was or currently is considered beta (or anything in between?).

I currently have a 3 node cluster with two PG instances using async replication and an etcd-only node. I'd like to get rid of etcd as it's an additional layer.

**Comment by CyberDem0n** [comment]
Nothing really changes since I answered the same question last time: https://github.com/zalando/patroni/issues/2041#issuecomment-904698227
