### ISSUE TITLE
patronictl list showing a different IP than host IP

### ISSUE THREAD

**Issue by nijesh8** [zalando/patroni#2117]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
- Patroni version:
- PostgreSQL version:
- DCS (and its version):

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**

**Comment by nijesh8** [comment]
`postgres@lvs-2:~/pgdata/pgroot/data$ patronictl list
+ Cluster: postgres2021-patroni-cluster (7006050946545012814) ---------+
| Member | Host          | Role    | State            | TL | Lag in MB |
+--------+---------------+---------+------------------+----+-----------+
| lvs-2  | 10.184.80.92  | Leader  | running          |  5 |           |
| rno-1  | 10.119.33.86  | Replica | running          |  4 |        48 |
| slc-3  | 10.27.209.138 | Replica | creating replica |    |   unknown |
+--------+---------------+---------+------------------+----+-----------+`

**Comment by nijesh8** [comment]
But the host IP is 10.184.80.55 

postgres@lvs-2:~/pgdata/pgroot/data$ hostname -I
10.184.80.55

**Comment by CyberDem0n** [comment]
It shows exactly what you have configured in the patroni.yaml
