### ISSUE TITLE
Commands to stop and start patroni other than systemctl

### ISSUE THREAD

**Issue by moindba** [zalando/patroni#2119]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
- Patroni version: patroni 2.1.1
- PostgreSQL version: 11.14
- DCS (and its version): 

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**

Hello Team, 

I am using below command to start patroni service on my CentOS 7.x OS.

patroni patroni.yml   -- To start patroni services

what will be the command to stop patroni services ?

I have used pip3 method for patroni installation..

If i used systemctl start patroni then it shows Unit patroni.service could not be found..

so is systemctl will not be worked if i install patroni with pip3 ?

Regards,
Moin

**Comment by CyberDem0n** [comment]
Apparently, your problem qualify as a general system administration topic, which is far outside of the scope of this project.
Maybe you need to hire a SysAdmin...
