### ISSUE TITLE
parse is missing in configuration file

### ISSUE THREAD

**Issue by yuluc123** [zalando/patroni#2122]
**Describe the bug**
Hi
I notice that **parse** is used in _features/steps/patroni_api.py_ but not declared in any requirement file.
https://github.com/zalando/patroni/blob/51cda9fb6e32cccc565fcb6ac52f1883c9156dd9/features/steps/patroni_api.py#L3
https://github.com/zalando/patroni/blob/51cda9fb6e32cccc565fcb6ac52f1883c9156dd9/features/steps/patroni_api.py#L19
So it it necessary to add parse to configuration files such as requirement-*.txt?

**Comment by CyberDem0n** [comment]
`parse` is a dependency for behave
