### ISSUE TITLE
etcd machines_cache can have duplicate entries

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#2126]
**Describe the bug**

While researching retries in case of DCS failures, I noticed that `_calculate_timeouts()` gets 7 as `etcd_nodes` when I use etcd, but only 3 if I use etcd3. In both cases, etcd is running locally on a 3-node Patroni cluster, and all three nodes are mentioned in the `etcd:` (or `etcd3`) section.

Not sure where the difference is from, but `machines_cache()` for `etcd` gets three times three nodes, and removes only the duplicate `base_uri` (the etcd leader it seems) hosts, not the others, so 7 remain.

This implies that `retry_timeout` with  a 3-node etcd cluster is divided by 7 for `etcd` and only 3 for `etcd3`, which looks wrong to me? On the other hand, it is not a big deal.

**Expected behavior**

Same timeout for etcd and etcd3.

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 14.1
- DCS (and its version): etcd-3.3.25

**Patroni configuration file**
```
etcd:
  hosts:
    - 10.0.3.195:2379
    - 10.0.3.237:2379
    - 10.0.3.178:2379
```

**Comment by CyberDem0n** [comment]
etcd.hosts is only the initial list, it is used to get the topology from etcd itself.
You need to check what cluster returns as advertiseClientURLs or something like this.

**Comment by mbanck** [comment]
You mean this?

```
# etcdctl member list
7e0dcc3da2b4420c: name=pg1 peerURLs=http://10.0.3.195:2380 clientURLs=http://10.0.3.178:2379,http://10.0.3.195:2379,http://10.0.3.237:2379 isLeader=false
da0a559998aaa18f: name=pg2 peerURLs=http://10.0.3.237:2380 clientURLs=http://10.0.3.178:2379,http://10.0.3.195:2379,http://10.0.3.237:2379 isLeader=true
f8de622058acb8bf: name=pg3 peerURLs=http://10.0.3.178:2380 clientURLs=http://10.0.3.178:2379,http://10.0.3.195:2379,http://10.0.3.237:2379 isLeader=false
```
