### ISSUE TITLE
Patroni leader is in read-only transaction

### ISSUE THREAD

**Issue by Kumar6295** [zalando/patroni#2130]
Hi,
We are using patroni cluster with 2 nodes and 3 etcd nodes.
servers
10.90.99.91 master
10.90.99.92 slave

when 10.90.99.91 server is master all the functionality working fine.
SELECT pg_is_in_recovery();
false
when 10.90.99.92 became master and other server slave , only select command working. try to execute other commands (like update,insert,delete,create) showing read-only transaction.
SELECT pg_is_in_recovery()
true
Can you please on this. what is the issue and how to resolve it.

Thanks,
kumar

**Comment by CyberDem0n** [comment]
When opening a new issue you are supposed to follow the issue template. And if you do so 99% it will help you to solve the problem.
