### ISSUE TITLE
Patroni config doesn't appear to recognize the CIDR notation such as: host replication replicator 10.10.10.0/24 md5:

### ISSUE THREAD

**Issue by tomkcpr** [zalando/patroni#2132]
**Describe the bug**
When ever configuration such as this is used:

```
pg_hba: 
- host all all 0.0.0.0/0 md5.
- host replication replicator 10.10.10.0/24 md5:
- host replication replicator 127.0.0.1/32 md5:
```

Patroni 2.1.1 prints out:

`FATAL: no pg_hba.conf entry for replication connection from host "10.10.10.5", user "replicator", SSL off`

is seen

**To Reproduce**
Use the configuration above. 

**Expected behavior**
Expect that the CIDR used will cover the given IP's.  It doesn't appear to do so via the patroni config.  Moreover, other non typical subnets such as /26, /27, etc don't work either.

**Screenshots**
No screenshots available. 

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 10
- DCS (and its version):  (Not sure what this is at the moment.)

**Patroni configuration file**
Full config not available to me.  Snippet provided.  More info can be provided later.

**patronictl show-config**
Full config not available to me.  Snippet provided.  More info can be provided later.

**Have you checked Patroni logs?**
Yes, and included the error above. 

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Yes I did.  Can't find anything specific.

**Additional context**
RHEL 7 machine is used for the installation.

**Comment by CyberDem0n** [comment]
Wherever you put such configuration it will not work.
pg_hba array items must be the valid lines for pg_hba.conf, but you have them ended with `.` and `:`.

Morover, the issue template was built in a way to reduce ping-pongs when not enough information is provided, and somehow you completely ignored points about **Patroni configuration file** and **patronictl show-config**. Without them it is not even clear to which part of config you put this pg_hba section.
