### ISSUE TITLE
Network hosting of patroni servers

### ISSUE THREAD

**Issue by zuss777** [zalando/patroni#2133]
Good day!
I am planning to deploy postgresql + patroni + haproxy + keepalived on three servers. 
Question: should the server and virtual IP (for keepalived) be on the same VLAN?

Best wishes zuss777

**Comment by CyberDem0n** [comment]
For VIP all HAProxy nodes must be located in the same VLAN.

**Comment by zuss777** [comment]
Many thanks, CyberDem0n !!
