### ISSUE TITLE
In Openshift: usage of Endpoints mechanism

### ISSUE THREAD

**Issue by Samusername** [zalando/patroni#2148]
Hi!

I would like to use "endpoints" mechanisms in Patroni and (Zalando) postgres-operator, in Openshift.
[Link to patroni documentation](https://patroni.readthedocs.io/en/latest/kubernetes.html).
I would like to try to avoid the mentioned "ConfigMap" alternative. 
"ConfigMap" alternative is almost "deprecated", and may be more unsafe/instable, according to documentations.

Usage of endpoints gives an error in Opensfhit, when Patroni DB cluster is tried to be started up.
The error looks like following:
"message":"endpoints \\"acid-upgrade-test\\" is forbidden: endpoint address <x.y.z.w> is not allowed","reason":"Forbidden"
See also:
https://github.com/zalando/postgres-operator/issues/1702

If we give more "heavy" "admin" types of permissions, 
in an own namespace, 
then the DB cluster works also in Openshift.
Other types of permissions do not help. We have tried all kinds of other combinations.

We would like to try to avoid the "heavy" types of permissions. And we would like to give only limited permissions instead.

Latest comment **from Red Hat** contains following, regarding usage in Openshift:

""I will recommend you to check feasibility of this deployment on OpenShift. Because its your (users) responsibility to have supported stuff on OpenShift, if you face any issue with these type of custom configurations on OpenShift platform you have to resolve them.""
They also recommend to discuss with experts who develop the functionalities (in Patroni, and maybe in postgres-operators).

And, from Red Hat:
""it's unlikely that for a non-supported component we change the Endpoint working in OpenShift since Endpoint working is at the core k8s/OCP functionality altogether""

Red Hat does not plan to add more specific "verbs" to allow the type of patching of endpoints, in Opensfhit, currently.
So, they are asking the Open source component to change the mechanisms. 
Or then we would need to use the more unsafe ConfigMaps alternatve. ConfigMaps alternative is "almost deprecated" (according to documentations of Zalando postgres-operator).
Then, there is the workaround alternative, of using wider admin type of permissions.

Could this be solved by some means?

**Comment by CyberDem0n** [comment]
> Could this be solved by some means?

No, either service account has admin privileges and endpoints what allows writing Pod IPs to subsets of the endpoint, or you have to use config maps.

**Comment by Samusername** [comment]
Sadly,
Red Hat has rejected requests to allow patching of endpoints:
https://issues.redhat.com/browse/RFE-2732
