### ISSUE TITLE
Feature request: Work in consul service mesh

### ISSUE THREAD

**Issue by lifedanceman** [zalando/patroni#2149]
Good day!

Is it possible to register services in consul so that they participate in the service mesh [across datacenters](https://learn.hashicorp.com/tutorials/consul/service-mesh-gateways)?

**Comment by CyberDem0n** [comment]
@lifedanceman are you planning to work on it?
If not, I will close the issue.

**Comment by lifedanceman** [comment]
> @lifedanceman are you planning to work on it? If not, I will close the issue.

It was question for develop community. Does that functionality exist or plan for to do?

**Comment by CyberDem0n** [comment]
It seems there isn't much interest from the community, therefore closing it.
