### ISSUE TITLE
Each leader restart generates new WAL file which pile up and may lead to out of space

### ISSUE THREAD

**Issue by kostrzewa9ld** [zalando/patroni#2156]
**Describe the bug**
Whenever leader is restarted a new WAL file for a new timeline is created and nothing cleans up the old WAL files.

**To Reproduce**
1. Deploy Patroni two node cluster.
2. Keep restarting current leader.
3. List `pg_xlog/` (or `pg_wal/`)

**Expected behavior**
Size of WAL files is capped by `max_wal_size` and the number of WAL files should be more or less equal to `wal_keep_segments` in a cluster where all replicas and master are healthy.

**Screenshots**
After a series of restarts `pg_wal/` contains around 70 WAL files:
```
docker exec demo-patroni2 ls /home/postgres/data/pg_wal | grep -Ev "history|archive_status" | wc -l
71
```
and the directory reached around 1.2GB:
```
docker exec demo-patroni2 du -sh /home/postgres/data/pg_wal
1.2G    /home/postgres/data/pg_wal
```
`wal_keep_segments` is configured to:
```
docker exec -e PGPASSWORD=postgres -it demo-patroni2 psql -U postgres -h localhost -c 'show wal_keep_segments;'
 wal_keep_segments 
-------------------
 8
(1 row)
```
and `max_wal_size`:
```
docker exec -e PGPASSWORD=postgres -it demo-patroni2 psql -U postgres -h localhost -c 'show max_wal_size;'
 max_wal_size 
--------------
 1GB
(1 row)
```

**Environment**
For the first time noticed in following setup:
- Patroni version: 1.6.0
- PostgreSQL version: 9.6.15
- DCS (and its version): ZooKeeper 3.6.2

But this is easily reproducible with Patroni docker image build from this repo and a cluster created using `docker-compose.yml` also available in this repository.

**Patroni configuration file**
For the reproduction I am using Patroni docker image and docker-compose file available in this repository.

**patronictl show-config**
```
docker exec demo-patroni2 patronictl show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 100
  pg_hba:
  - local all all trust
  - host replication all all md5
  - host all all all md5
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

**Have you checked Patroni logs?**
```
2022-01-04 11:25:55,337 INFO: running pg_rewind from patroni3
2022-01-04 11:25:55,340 INFO: running pg_rewind from dbname=postgres user=postgres host=192.168.0.5 port=5432
2022-01-04 11:25:55,346 INFO: pg_rewind exit code=0
2022-01-04 11:25:55,347 INFO:  stdout=servers diverged at WAL location 0/4006488 on timeline 67
no rewind required

2022-01-04 11:25:55,347 INFO:  stderr=
2022-01-04 11:25:55,348 WARNING: Postgresql is not running.
2022-01-04 11:25:55,348 INFO: Lock owner: patroni3; I am patroni2
2022-01-04 11:25:55,350 INFO: Reaped pid=101, exit status=0
2022-01-04 11:25:55,350 INFO: pg_controldata:
  wal_level setting: replica
  Latest checkpoint's oldestCommitTsXid: 0
  Mock authentication nonce: 34a7a9db9071342c00f46b1a836c603758b87851b2d2da6900c8c7131d87d04f
  Latest checkpoint's newestCommitTsXid: 0
  max_prepared_xacts setting: 0
  Backup end location: 0/0
  Latest checkpoint's NextXID: 0:559
  Data page checksum version: 1
  Maximum columns in an index: 32
  Latest checkpoint's oldestXID's DB: 1
  Backup start location: 0/0
  Database system identifier: 7049287094581809183
  Database cluster state: shut down in recovery
  Blocks per segment of large relation: 131072
  Latest checkpoint's NextOID: 16386
  Time of latest checkpoint: Tue Jan  4 11:25:36 2022
  Float8 argument passing: by value
  Latest checkpoint's NextMultiOffset: 0
  Maximum data alignment: 8
  Fake LSN counter for unlogged rels: 0/1
  Latest checkpoint's oldestXID: 549
  Size of a large-object chunk: 2048
  pg_control last modified: Tue Jan  4 11:25:44 2022
  Latest checkpoint's TimeLineID: 67
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's REDO location: 0/4006418
  Maximum length of identifiers: 64
  Bytes per WAL segment: 16777216
  max_connections setting: 100
  Latest checkpoint's oldestMultiXid: 1
  Min recovery ending loc's timeline: 67
  Latest checkpoint's oldestActiveXID: 0
  Maximum size of a TOAST chunk: 1996
  Latest checkpoint location: 0/4006418
  Latest checkpoint's PrevTimeLineID: 67
  Latest checkpoint's REDO WAL file: 000000430000000000000004
  Catalog version number: 201707211
  Database block size: 8192
  track_commit_timestamp setting: off
  wal_log_hints setting: on
  Prior checkpoint location: 0/4006418
  End-of-backup record required: no
  Date/time type storage: 64-bit integers
  Latest checkpoint's NextMultiXactId: 1
  WAL block size: 8192
  max_locks_per_xact setting: 64
  Float4 argument passing: by value
  Latest checkpoint's oldestMulti's DB: 1
  max_worker_processes setting: 8
  Minimum recovery ending location: 0/4006488
  pg_control version number: 1002

2022-01-04 11:25:55,351 INFO: Lock owner: patroni3; I am patroni2
2022-01-04 11:25:55,351 INFO: starting as a secondary
2022-01-04 11:25:55,352 INFO: closed patroni connection to the postgresql cluster
2022-01-04 11:25:55.517 UTC [108] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-01-04 11:25:55.518 UTC [108] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-01-04 11:25:55.527 UTC [109] LOG:  database system was shut down in recovery at 2022-01-04 11:25:44 UTC
2022-01-04 11:25:55.527 UTC [109] LOG:  entering standby mode
2022-01-04 11:25:55,527 INFO: postmaster pid=108
2022-01-04 11:25:55.528 UTC [109] LOG:  consistent recovery state reached at 0/4006488
2022-01-04 11:25:55.528 UTC [109] LOG:  invalid record length at 0/4006488: wanted 24, got 0
2022-01-04 11:25:55.529 UTC [108] LOG:  database system is ready to accept read only connections
2022-01-04 11:25:55.532 UTC [114] LOG:  fetching timeline history file for timeline 69 from primary server
localhost:5432 - accepting connections
2022-01-04 11:25:55.535 UTC [114] LOG:  started streaming WAL from primary at 0/4000000 on timeline 68
localhost:5432 - accepting connections
```

**Have you checked PostgreSQL logs?**
They are included in the Patroni logs in the previous section.

**Have you tried to use GitHub issue search?**
Yes and what's astonishing is that I could not find any information about such behavior or what to do to prevent out of disk due to WAL files piling up.

**Comment by kostrzewa9ld** [comment]
@CyberDem0n Thanks for responding. I understand it is not directly related to Patroni and I asked about this behavior on pgsql-performance first [here](https://www.postgresql.org/message-id/CA%2BVG59En-5bJPDwisAMOCZEmcSkPjEq0EAYo3BEV6qFKpt1Dbw%40mail.gmail.com). 
As reported there I excluded the most obvious reasons:
- failing archive command
- abandoned replication slot
- issues with checkpoints

What's more, I am using the default configuration available in this repository and the only thing I am doing is restarting the leader node. The surprising thing to me is that this has not been reported yet so I start to wonder whether I am missing something obvious though I can't find any information related to this.
If that's the case, that something is missing in the setup, then maybe there is some way the WAL files can be safely removed? and maybe putting information about this behavior in Patroni documentation is something worth considering?

**Comment by CyberDem0n** [comment]
Patroni only starts/stops/promotes Postgres. It doesn't even try to look at pg_wal/pg_xlog.
If files are piling there up you have to figure out what prevents Postgres from cleaning them up.

**Comment by kostrzewa9ld** [comment]
It seems that as soon as I start writing anything to the database Postgres starts cleaning up the old WAL files.
