### ISSUE TITLE
Patroni with Two DataCenters and sync/async replication

### ISSUE THREAD

**Issue by OriRub** [zalando/patroni#2157]
Hi,

I am implementing a Patroni PostgreSQL cluster between two data centers.
I would like to have the Leader and one sync Standby on DC1 and remote async replica on DC2 with a sync replica for it in order to have HA for the second DC.

I am using the Patroni synchronous_mode: true, however it seems that there is no distinguish between the datacenters and mode of replication.

How can I achieve such a desired mode of replication between Data Center and inside each Data Center ?
Is it something that Patroni can managed with the synchronous_mode, or requires the PostgreSQL replication parameters ?

Thanks,

Ori

**Comment by CyberDem0n** [comment]
https://patroni.readthedocs.io/en/latest/SETTINGS.html#tags


`tags.nosync` allows to exclude replica from being synchronous

**Comment by OriRub** [comment]
> https://patroni.readthedocs.io/en/latest/SETTINGS.html#tags
> 
> `tags.nosync` allows to exclude replica from being synchronous

**Comment by OriRub** [comment]
Hi,

Thanks!!!! that can assist for sure.

Few additional questions:

1.
The config I would like to achieve is:
DC1:
Master ans Sync Replica

DC2:
ASync Replica for Master on DC1
cascade Sync Replica to first Replica in DC2

Is it possible to achieve that with Patroni ?
Or, should I have two ASync Replicas in DC2 from Master on DC1 ?

2.
When we have Sync and ASync Replicas, in case of failover, which one will Patroni favor ?
Will it always favor the Sync over ASync ?
What if DC1 is completely down and all that left is DC2 with two ASync replication, will the Failover be automatically ?
(*) considering that there is always a quruom for etcd.


Thanks,

Ori

**Comment by CyberDem0n** [comment]
The documentation https://patroni.readthedocs.io has all the answers.
Also, I would really recommend you:
1. Go through Patroni tutorial slides: https://github.com/patroni-training/2019
2. Deploy a test setup and play with it.

It will give your more understanding and confidence than just blindly asking questions.

**Comment by ronbarak** [comment]
Did you manage to do what you wanted, OriRub?

Because, reading through the [patroni](https://patroni.readthedocs.io/en/latest/ha_multi_dc.html) (HA multi-datacentre) documentation, I gather that to implement failover between two datacentres (IOW, to have a multi datacentre (DC) cluster that can automatically tolerate a zone drop) using Synchronous Replication, then a minimum of three data centres is required.

**Comment by CongSon** [comment]
hi @OriRub , did you implement successfully? Can you share your solution?

**Comment by yondkoo** [comment]
Hi, I just got lost somewhere in the documentation. Has anyone accomplished the HA multi-datacenter with a sync cluster on the primary side and an async cluster on the standby side?

I've read the documentation, but it doesn't provide information about implementing HA multi-datacenter with Async Replication (or I couldn't find the exact documentation). 

I have an HA sync rep cluster with 3 nodes in the A zone already, and I want to have a standby HA async rep cluster in the B zone that replicates from the A zone.
