### ISSUE TITLE
Patroni and etcd using SSL

### ISSUE THREAD

**Issue by OriRub** [zalando/patroni#2160]
Hi,

I have a generated Certificate with Private Key which has a password.
I am using the AWS ACM PCA (Private Certificate Authority).

There are the following parameters for Patroni and equivalent for etcd:
PATRONI_ETCD_CACERT: The ca certificate. If present it will enable validation.
PATRONI_ETCD_CERT: File with the client certificate.
PATRONI_ETCD_KEY: File with the client key. Can be empty if the key is part of certificate

I would like to use the certificate for the communication between Patroni and etcd.
How and where can I set the password for the Private Key ?

Thanks,

Ori

**Comment by CyberDem0n** [comment]
> How and where can I set the password for the Private Key ?

You can't, please use a non-encrypted key.

**Comment by CyberDem0n** [comment]
For the future, please use #patroni channel in the [Postgres Slack](https://postgres-slack.herokuapp.com/) for asking general questions.
