### ISSUE TITLE
PostgreSQL Doesn't Initialize when S3 is Down

### ISSUE THREAD

**Issue by haslersn** [zalando/patroni#2163]
When using patroni with wal-g backups enabled and the S3 endpoint is down, then PostgreSQL does not initialize. Instead, the container log spams

```
default-db-0 postgres /var/run/postgresql:5432 - rejecting connections
```

and the PostgreSQL log spams:

```
2022-01-08 17:19:39.018 UTC,,,546,"[local]",61d9c7ab.222,1,"",2022-01-08 17:19:39 UTC,,0,LOG,00000,"connection received: host=[local]",,,,,,,,,"","not initialized"
2022-01-08 17:19:39.018 UTC,"postgres","postgres",546,"[local]",61d9c7ab.222,2,"",2022-01-08 17:19:39 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,"","client backend"
```

(I don't know whether wal-e is affected, too, but I guess so.)

**To Reproduce**

1. Create a PostgreSQL cluster with `AWS_ENDPOINT` pointing to your own S3-compatible object storage. (When using postgres-operator, this can be done using the ConfigMap referred as `pod_environment_configmap`.)
2. Take the PostgreSQL cluster down.
3. Take the object storage down.
4. Take the PostgreSQL cluster up again.

**Expected behavior**

If the object storage is not available, then the PostgreSQL cluster's instances should use their local WAL data in order to recover from the downtime.

It is somewhat unexpected, that enabling backups can lead to *less* availability. If backups aren't enabled, then the instances can recover using their local WAL data. Why should this be impossible if backups are enabled?

**Environment**
- Patroni version: 2.1.1
- PostgreSQL version: 13

**Comment by CyberDem0n** [comment]
That's the behavior of the Postgres.

**Comment by haslersn** [comment]
I think I mixed up the two repositories spilo and patroni. Is this a spilo issue?

**Comment by CyberDem0n** [comment]
Spilo is only a docker image that contains PostgreSQL + Patroni + wal-e/wal-g + a few Postgres extensions. 

Patroni doesn't change Postgres and doesn't replace it either. It can only manage Postgres: update configs/start/stop/reload/promote. That's it.

If PostgreSQL wants to fetch WAL file from the archive it's not a Patroni to blame.

**Comment by haslersn** [comment]
> If PostgreSQL wants to fetch WAL file from the archive it's not a Patroni to blame.

Correct, but Patroni writes the PostgreSQL configuration and maybe there's a PostgreSQL configuration option that can fix the problem described here. I'm currently looking at section [19.5.4](https://www.postgresql.org/docs/13/runtime-config-wal.html#RUNTIME-CONFIG-WAL-ARCHIVE-RECOVERY) and [19.5.5](https://www.postgresql.org/docs/13/runtime-config-wal.html#RUNTIME-CONFIG-WAL-RECOVERY-TARGET) of the PostgreSQL 13 documentation.

**Comment by haslersn** [comment]
As I understand it, Patroni just passes the relevant config options on to PostgreSQL. Therefore I moved this issue to Spilo: https://github.com/zalando/spilo/issues/685
