### ISSUE TITLE
Plaintext password

### ISSUE THREAD

**Issue by HoLo-Debris** [zalando/patroni#2164]
**Describe the bug**
Plaintext passwords are generally considered insecure, like these in file pgpass and postgres.yml. Someone may read these file by some illegal ways. How to eliminate this kind of hidden danger?

**Comment by CyberDem0n** [comment]
> How to eliminate this kind of hidden danger?

You can't. One way or another you will have to keep unencrypted passwords on the host and it doesn't matter whether that would be postgres passwords or passwords to unencrypt other passwords. Without it Patroni/Postgres couldn't start automatically.

**Comment by HoLo-Debris** [comment]
> > How to eliminate this kind of hidden danger?
> 
> You can't. One way or another you will have to keep unencrypted passwords on the host and it doesn't matter whether that would be postgres passwords or passwords to unencrypt other passwords. Without it Patroni/Postgres couldn't start automatically.

Thank you so much about that, by the way, I don't know it clearly how the pgpass file works or what is the function of pgpass file through reading the relative code. Can you make a brief induction ?

**Comment by CyberDem0n** [comment]
https://www.postgresql.org/docs/current/libpq-pgpass.html

**Comment by HoLo-Debris** [comment]
> https://www.postgresql.org/docs/current/libpq-pgpass.html

Thanks a lot!
