### ISSUE TITLE
Accelerate standby synchronization if "replica-method basebackup" is used.

### ISSUE THREAD

**Issue by rachid-casa** [zalando/patroni#2169]
Are there any parameters we can set to speed up standby synchronization when using "replica-method basebackup"?
Can we determine the block size that is used for a new standby synchronization if "replica-method basebackup" is used?
I mean: Can we determine the block size that is transferred from the master to the slave  when using "replica-method basebackup"?
thank you very much for your support 
Kind regards

**Comment by CyberDem0n** [comment]
I am sorry, but I don't understand what you want.

**Comment by rachid-casa** [comment]
Sorry for the incomprehensible description of the problem.
We have the following current situation:
If we synchronize a slave as VM from the master as hardware, the complete synchronization process takes 2 hours.
But if we synchronize the other way around, i.e. if we synchronize the slave as hardware from the master as VM, the complete synchronization process takes 10 hours.
There is probably some optimization work that we can do on the VM. 
That is why I asked the questions above.
Thanks for any advice.

**Comment by CyberDem0n** [comment]
I am still not following what you are trying to say.
Anyway, Patroni offers custom replica creation methods: https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#building-replicas, you can build on top of that anything you want.

**Comment by rachid-casa** [comment]
Thanks for the link.
I see we can specify basebackup parameters.
What does the parameter "max-rate: '100M'" do ?

**Comment by CyberDem0n** [comment]
Have you tried reading PostgreSQL documentation: https://www.postgresql.org/docs/current/app-pgbasebackup.html#id-1.9.4.10.6 ?

**Comment by rachid-casa** [comment]
Thanks for your help
