### ISSUE TITLE
Patroni Trouble on Openshift with Evicted Pods

### ISSUE THREAD

**Issue by Schmaetz** [zalando/patroni#2170]
Hello all, 
I could observe problems with Patroni in use on Openshift in connection with evicted pods.

Openshift (pure Kubernetes possibly too?) keeps evicted pods in the list. These pods are dead but still listed as a warning. Patroni messes this up as the pods continue to be listed as a node in the PG cluster. 

This hinders or blocks the failover, as well as the automatic failover, because Patroni permanently thinks there could be a pod that is healthier than one of the running pods. 

Only when all evicted pods are removed is the problem solved and Patroni can stabilise the PG cluster again. 

Have you ever observed this behaviour? 

Many greetings

**Comment by CyberDem0n** [comment]
> Have you ever observed this behaviour?

No.

Maybe these pods are indeed healthier? Without providing logs you can't prove anything.

**Comment by Schmaetz** [comment]
Thank you for your answer. 
These pods cannot be healthier as they no longer exist. They are just an entry in the list without any running containers. 

Many greetings

**Comment by CyberDem0n** [comment]
> These pods cannot be healthier 

It depends on the definition of health. Apparently, you think about it from a different perspective than Patroni.
Again, without logs there will be no progress.
