### ISSUE TITLE
Question: Prioritizing hosts (give higher chances to be the leader)

### ISSUE THREAD

**Issue by gerardo-ongres** [zalando/patroni#2176]
Suppose we have a 5 node cluster, in 2 different datacenters (DC1 and DC2):
host_1 (DC1)
host_2 (DC1)
host_3 (DC1)
host_4 (DC2)
host_5 (DC2)

DC1 hosts should be prioritized over DC2 hosts because DC1 is "closer" to the app, so as to minimize network roundtrip...Now lets suppose all 3 nodes from DC1 (or the entire DC) goes down...Some host from DC2 would become the leader and that is fine...but (and here is the question) as soon as any host from D1 becomes alive, it should be automagically promoted as a leader
Is this something doable using Patroni config/tags/etc?

**Comment by CyberDem0n** [comment]
> Is this something doable using Patroni config/tags/etc?

No, you can find more details by looking through issues
