### ISSUE TITLE
Question: error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by bagafoot** [zalando/patroni#2177]
I get this error too frequent in /var/log/messages

```
kernel: 3.10.0-1160.49.1.el7.x86_64
Python 2.7.5
Centos7
patronictl version 2.1.2
```
What could be the problem ?

```
Jan 19 11:10:11 vtyspostdb06s01 python: WARNING: Exception happened during processing of request from 172.24.27.22:38416
Jan 19 11:10:11 vtyspostdb06s01 python: WARNING: Traceback (most recent call last):
Jan 19 11:10:11 vtyspostdb06s01 python: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Jan 19 11:10:11 vtyspostdb06s01 python: self.finish_request(request, client_address)
Jan 19 11:10:11 vtyspostdb06s01 python: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Jan 19 11:10:11 vtyspostdb06s01 python: self.RequestHandlerClass(request, client_address, self)
Jan 19 11:10:11 vtyspostdb06s01 python: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Jan 19 11:10:11 vtyspostdb06s01 python: self.finish()
Jan 19 11:10:11 vtyspostdb06s01 python: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Jan 19 11:10:11 vtyspostdb06s01 python: self.wfile.close()
Jan 19 11:10:11 vtyspostdb06s01 python: File "/usr/lib64/python2.7/socket.py", line 279, in close
Jan 19 11:10:11 vtyspostdb06s01 python: self.flush()
Jan 19 11:10:11 vtyspostdb06s01 python: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Jan 19 11:10:11 vtyspostdb06s01 python: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Jan 19 11:10:11 vtyspostdb06s01 python: error: [Errno 32] Broken pipe
```

**Comment by CyberDem0n** [comment]
> What could be the problem ?

Which Patroni version is it? I bet not the latest one.
Also, python 2.7 is EOL for more than a year.

**Comment by bagafoot** [comment]
> > What could be the problem ?
> 
> Which Patroni version is it? I bet not the latest one. Also, python 2.7 is EOL for more than a year.

patronictl version 2.1.2

**Comment by CyberDem0n** [comment]
> patronictl version 2.1.2

I am asking about Patroni version that runs.
You can check it by querying /patroni [endpoint](https://patroni.readthedocs.io/en/latest/rest_api.html#monitoring-endpoint).

Actually, the exception is raised because the other side that called Patroni API prematurely closed the connection without reading the full response.

P.S. It would be much simpler if you follow the issue template...

**Comment by bagafoot** [comment]
> 

 curl -s http://localhost:8008/patroni | jq .

  "patroni": {
    "scope": "test",
    "version": "2.1.2"

**Comment by bagafoot** [comment]
> Actually, the exception is raised because the other side that called Patroni API prematurely closed the connection without reading the full response.

You mention that the problem actually is on client side right, dont wait until the response.

**Comment by CyberDem0n** [comment]
Whatever.
The exception is harmless. You need to figure out what sends these requests and why they close connections prematurely.
