### ISSUE TITLE
Force leader election (using synchronous_mode_strict and nosync tags)

### ISSUE THREAD

**Issue by gerardo-ongres** [zalando/patroni#2182]
Hi all. I have a 5 member cluster, using `synchronous_mode_strict` and setting the `nosync` tag on two (because they are in a distant DC). So it looks like this:

```
+-----------+-------------+--------------+---------+----+-----------+--------------+
| Member    | Host        | Role         | State   | TL | Lag in MB | Tags         |
+ Cluster: patroni-cluster (7055270466850224281) --+----+-----------+--------------+
| patroni-1 | 10.20.30.51 | Leader       | running |  5 |           |              |
| patroni-2 | 10.20.30.52 | Replica      | running |  5 |        64 |              |
| patroni-3 | 10.20.30.53 | Sync Standby | running |  5 |         0 |              |
| patroni-4 | 10.20.30.54 | Replica      | running |  5 |         0 | nosync: true |
| patroni-5 | 10.20.30.55 | Replica      | running |  5 |         0 | nosync: true |
+-----------+-------------+--------------+---------+----+-----------+--------------+
```

Because of the  `nosync: true` plus `synchronous_mode_strict=on`, if the first 3 nodes goes down, you end up in a situation where no leader can be elected, and the remaining nodes being unable to be promoted:

```
Jan 24 17:28:27 patroni-5 patroni[10348]: 2022-01-24 17:28:27,339 INFO: following a different leader because i am not the healthiest node
Jan 24 17:28:37 patroni-5 patroni[10348]: 2022-01-24 17:28:37,348 INFO: following a different leader because i am not the healthiest node
Jan 24 17:28:47 patroni-5 patroni[10348]: 2022-01-24 17:28:47,348 INFO: following a different leader because i am not the healthiest node
```
And either `patroni-4` or `patroni-5` must be manually promoted. (This is the part we want to automate)

So, the idea is to have a configuration to allow:
- Use synchronous replication (this is a must)
- Prevent `patroni-4` and `patroni-5` from being elected as a leader (providing that one of `patroni-[123]` is available)
- Automatically Promote `patroni-4` or `patroni-5` in case of all other 3 nodes goes down

Is there an alternative way to do this, in order to make it work? 

Thanks!
Gerardo

**Comment by CyberDem0n** [comment]
> Automatically Promote patroni-4 or patroni-5 in case of all other 3 nodes goes down

This is not what Patroni will do if sync replication is enabled because it could lead to a data loss.

**Comment by gerardo-ongres** [comment]
> > Automatically Promote patroni-4 or patroni-5 in case of all other 3 nodes goes down
> 
> This is not what Patroni will do if sync replication is enabled because it could lead to a data loss.

I see, that make sense. Is there another way to achieve this?

**Comment by CyberDem0n** [comment]
Not really. It is not possible to have a configuration that automatically acts as synchronous and asynchronous at the same time.
The decision on promoting nosync replicas is always left to a human.
