### ISSUE TITLE
Question about Patroni behavior in case of network issues.

### ISSUE THREAD

**Issue by gglybin** [zalando/patroni#2191]
Hello,

Assume I have Master-Replica Postgres cluster managed by Patroni. I also have Etcd running on each DB node + third server.

What will happen in case of all 3 nodes will be isolated over the network from each other?

I don't have test lab to check it by myself right now. Quick search through the patroni docs didn't lead me to an answer.

Please advice.

Thanks.

**Comment by CyberDem0n** [comment]
When there is no quorum everything goes read-only.
