### ISSUE TITLE
Question: In what order are init_scripts vs Bootstrap configurations applied?

### ISSUE THREAD

**Issue by benkroeger** [zalando/patroni#2203]
According to the [Bootstrap configuration](https://patroni.readthedocs.io/en/latest/ENVIRONMENT.html#bootstrap-configuration), you can define additional users (created only when a cluster is first initialized) through environment variables (e.g. `PATRONI_admin_PASSWORD`.
Also, you can run custom scripts on `post_bootstrap` or `post_init` (see [YAML Bootstrap configuration](https://patroni.readthedocs.io/en/latest/SETTINGS.html#bootstrap-configuration)).
What's the order these ('hooks' + user creation) are executed in?
It appears that when using `post_init`, my additional users are not available yet - but when patroni has successfully started the cluster, users are ready to be used.

**Comment by benkroeger** [comment]
What I found out so far is that `post_bootstrap` and `post_init` are mutually exclusive - meaning you can use on or the other. When `post_bootstrap` is defined, `post_init` is ignored. (I actually hoped for them to describe different hooks)

**Comment by benkroeger** [comment]
Dang...
I think this is where the relevant code is executed;

- [run post_bootstrap command](https://github.com/zalando/patroni/blob/fce889cd048da605c60fe607f19d7c82f526359d/patroni/postgresql/bootstrap.py#L332)
- [create users](https://github.com/zalando/patroni/blob/fce889cd048da605c60fe607f19d7c82f526359d/patroni/postgresql/bootstrap.py#L349)

which basically confirms my suspicions... users are only created after `post_bootstrap` scripts have completed.

What's the official take on this? Why is it done in this order? Is it not common that you'd want to have the additional users availabe in your custom init scripts?

**Comment by CyberDem0n** [comment]
The `post_init` is just an alias for `post_bootstrap`.

Users are created after the `post_bootstrap`. Why? Good question. Because it was possible to create them even before the post_init/post_bootstrap were implemented.
The latter is way more flexible and allows creating any arbitrary objects in the DB, including users.
I.e., `users` are sort of redundant and the only reason it is not removed is for backward compatibility.

**Comment by benkroeger** [comment]
Thanks for the confirmation. Would you recommend to create users in `post_bootstrap` then?

**Comment by CyberDem0n** [comment]
> Would you recommend to create users in post_bootstrap then?

Yes, that was exactly my point.
