### ISSUE TITLE
Question: Changing nofailover Property for Specific Node Using curl

### ISSUE THREAD

**Issue by avi1818** [zalando/patroni#2205]
I would like to change the nofailover property for a specific node.  If I run the following command it changes it to all nodes.
What is the way to change it just for one specific node?

curl -s -XPATCH -d \
        '{"tags":{"nofailover":"true"}}' \
        http://localhost:8008/config | jq .

Thanks

**Comment by CyberDem0n** [comment]
Tags could be set only in the local patroni.yaml
