### ISSUE TITLE
Rewind check does not use the Connection class and there for does not use e.g. client certificates

### ISSUE THREAD

**Issue by darix** [zalando/patroni#2207]
**Describe the bug**
I try to setup a cluster that uses client certificates for everything, even replication. All that works nicely until we try to use pg_rewind.

The rewind code does use `get_connection_cursor` instead of using the Connection class which would have gotten all connection settings like client cert and key. Is there any specific reason why the code in this place uses psycopg directly?

**To Reproduce**

**Expected behavior**

No matter which part of patroni opens a PG connection it should honor all the settings.

**Screenshots**

**Environment**
- Patroni version: 2.1.2
- PostgreSQL version: pg 14.1
- DCS (and its version): etc 3.4.3

**Comment by CyberDem0n** [comment]
It looks like a problem with the config.
Client certs/keys must be configured per user, and pg_rewind could have its own: https://patroni.readthedocs.io/en/latest/SETTINGS.html#postgresql
