### ISSUE TITLE
Cluster initialization crash with some specific initial password

### ISSUE THREAD

**Issue by bastienwirtz** [zalando/patroni#2209]
**Describe the bug**

Crash during cluster initialization when the configuration file includes a user with a password containing a `%` caracter.
See `Additional context` section below for investigation details.

**To Reproduce**
- Edit your configuration file to include a user with a password password containing a `%` caracter (see `users` field in the `Patroni configuration file` section below)
- Launch patroni to initialise a **new** cluster.
- Watch Patroni logs, a python stacktrace should apear (see `Have you checked Patroni logs?` section below)

**Expected behavior**

The cluster is initialised without crash.

**Screenshots**

N/A, see Patroni logs section below.

**Environment**
- Patroni version: 2.1.2
- PostgreSQL version: 14
- DCS (and its version): Consul 1.8.6

**Patroni configuration file**

```yaml
scope: xxxxxxxxx
name: patroni

restapi:
  listen: 0.0.0.0:8008
  connect_address: xxx.xxx.xxx.xxx:8008

consul:
  host: consul-client:8500

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: true
    max_timelines_history: 10
    postgresql:
      use_pg_rewind: true
      use_slots: true

  initdb:
  - encoding: UTF8
  - auth-host: md5

  users:
    monitoring:
      password: "pas%sword"
      options:
        - VALID UNTIL 'infinity'
        - SUPERUSER
        - NOINHERIT
        - LOGIN

postgresql:
  listen: 0.0.0.0:5432
  connect_address: xxx.xxx.xxx.xxx:5432
  data_dir: /var/lib/postgresql/data
  bin_dir: /usr/lib/postgresql/14/bin
  authentication:
    replication:
      username: "repl"
      password: "password"
    superuser:
      username: "admin"
      password: "password"

watchdog:
  mode: off
```

**Have you checked Patroni logs?**

**With `psycopg2`**
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/patroni/postgresql/bootstrap.py", line 351, in post_bootstrap
    self.create_or_update_role(name, value.get('password'), value.get('options', []))
  File "/usr/local/lib/python3.9/dist-packages/patroni/postgresql/bootstrap.py", line 319, in create_or_update_role
    self._postgresql.query(sql)
  File "/usr/local/lib/python3.9/dist-packages/patroni/postgresql/__init__.py", line 287, in query
    return self.retry(self._query, sql, *args)
  File "/usr/local/lib/python3.9/dist-packages/patroni/utils.py", line 334, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/patroni/postgresql/__init__.py", line 267, in _query
    cursor.execute(sql, params)
IndexError: tuple index out of range
```

**With `psycopg3`**
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/patroni/postgresql/bootstrap.py", line 354, in post_bootstrap
    self.create_or_update_role(name, value.get('password'), value.get('options', []))
  File "/usr/local/lib/python3.9/dist-packages/patroni/postgresql/bootstrap.py", line 322, in create_or_update_role
    self._postgresql.query(sql)
  File "/usr/local/lib/python3.9/dist-packages/patroni/postgresql/__init__.py", line 287, in query
    return self.retry(self._query, sql, *args)
  File "/usr/local/lib/python3.9/dist-packages/patroni/utils.py", line 334, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/patroni/postgresql/__init__.py", line 278, in _query
    raise e
  File "/usr/local/lib/python3.9/dist-packages/patroni/postgresql/__init__.py", line 267, in _query
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/psycopg/cursor.py", line 568, in execute
    raise ex.with_traceback(None)
psycopg.ProgrammingError: the query has 2 placeholders but 0 parameters were passed
```

**Have you checked PostgreSQL logs?**
Yes, nothing relevant to this issue.

**Have you tried to use GitHub issue search?**
Yes

**Additional context**

The [`_query`](https://github.com/zalando/patroni/blob/master/patroni/postgresql/__init__.py#L267) function used by the [`create_or_update_role`](https://github.com/zalando/patroni/blob/master/patroni/postgresql/bootstrap.py#L319) function during cluster initialization for initial user setup always call `execute` with a `params` args which is set to empty set when no args provided, for possible substitutions. As a result, if the password contain a '%' char, `execute` will try (and fail) to find a substitution in `params`. The issue exist with `psycopg2` & `psycopg3`

Possible solution:

- Escape the caractere in `create_or_update_role` (replace any `%` by `%%` in the password variable)
- Create an alternative `query` function which does not take parameters (if no second argument is given to `execute`, no substitution atempt will be made)

Let me know what could work for you, I would be happy to submit a pull request to fix it.

**Comment by CyberDem0n** [comment]
Nice catch @bastienwirtz! 

After looking at psycopg2 and psycopg3 source code I think the following could help:
```python
cursor.execute(sql, params or None)
```

It would be nice if you open a PR with the fix.
Please also update `patroni[012].yml` sample configs (bootstrap.users.admin.password) so that the change get tested.

**Comment by bastienwirtz** [comment]
[There](https://github.com/zalando/patroni/pull/2212) you go @CyberDem0n !
