### ISSUE TITLE
standby_cluster/logical_slots_in_sync step fails on v10

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#2215]
**Describe the bug**

On v10, the `logical_slots_in_sync` step of the `standby_cluster` feature fails:

```
07:46:06 Feb 14 06:46:05 Feature: standby cluster # features/standby_cluster.feature:1
[...]
07:46:17 Feb 14 06:46:17 
07:46:17 Feb 14 06:46:17   @skip
07:46:17 Feb 14 06:46:17   Scenario: check permanent logical slots are synced to the replica                            # features/standby_cluster.feature:18
07:46:17 Feb 14 06:46:17     Given I run patronictl.py restart batman postgres1 --force                                 # features/steps/patroni_api.py:85
07:46:18 Feb 14 06:46:18     Then Logical slot test_logical is in sync between postgres0 and postgres1 after 10 seconds # features/steps/slots.py:41
07:46:28 Feb 14 06:46:28       Assertion Failed: Logical slot test_logical is not in sync between postgres0 and postgres1
```

This is not the case with v11+, and I also checked that this is not because of the latest point release.

Here is the full log: https://pgdgbuild.dus.dg-i.net/job/patroni-binaries/150/architecture=amd64,distribution=sid/consoleFull#console-section-7

I wonder whether the `@skip` should do something but doesn't?

**To Reproduce**

Run behave on 2.1.2 or master with v10 Postgres binaries

**Expected behavior**

**Screenshots**

**Environment**
- Patroni version: 2.1.2
- PostgreSQL version: 10.19, 10.20
- DCS (and its version): raft

**Comment by CyberDem0n** [comment]
You need to start behave with `--tags=-skip` option if testing with v10 or older.
Somehow I didn't find a better way to do it.

**Comment by mbanck** [comment]
Thanks, done so
