### ISSUE TITLE
Question: max-rate for replication after initial sync (set rate limit for replication even after basebackup finished)

### ISSUE THREAD

**Issue by avi1818** [zalando/patroni#2216]
Is it possible to limit the bandwidth used by streaming or logical replication?  I know there is max-rate for basebackup, but I need it also for replication after initial sync.

**Comment by CyberDem0n** [comment]
If Postgres doesn't support it how Patroni is supposed to do it?
Also, your wish goes against all principles of building HA. You want to have replicas as much close to the primary as possible...
