### ISSUE TITLE
[Question] Do Not Copy Subscriptions/Publications From Active To Standby Cluster

### ISSUE THREAD

**Issue by avi1818** [zalando/patroni#2232]
I have somewhat complex setup:
1) Active site with 1 master and 2 replicas.  The data is copied from master to replicas using streaming replication.  
2) Standby site with 3 nodes (standby leader + 2 replica), initial data is copied using basebackup and then streaming replication
3) In addition to the above, Active site has several logical subscriptions and publications that copy data to/from other destinations

I would like to have the logical subscriptions/publications only on Active site and it should not be copied to Standby site.  If the Standby site becomes active, only then I will create those subscriptions/publications.  I did not see pg_basebackup has option to not copy the subscriptions/publications (but pg_dump does: --no-subscriptions).  Can Patroni assist in some way?

**Comment by CyberDem0n** [comment]
> Can Patroni assist in some way?

No. Physical replication doesn't allow that.
