### ISSUE TITLE
Move `boto` to `boto3`

### ISSUE THREAD

**Issue by jonringer** [zalando/patroni#2237]
**Describe the bug**
`boto` has been abandoned since 2018. And the hmac calls for the standard library have changed in python3.9:

```
  File "/build/boto-2.49.0/boto/utils.py", line 787, in set
    self.str = self.hashfunc(value).hexdigest()
  File "/build/boto-2.49.0/tests/unit/utils/test_utils.py", line 101, in <lambda>
    hmac_hashfunc = lambda msg: hmac.new(b'mysecretkey', msg)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/hmac.py", line 170, in new
    return HMAC(key, msg, digestmod)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/hmac.py", line 56, in __init__
    raise TypeError("Missing required parameter 'digestmod'.")
TypeError: Missing required parameter 'digestmod'.
```

**To Reproduce**
- install python 3.9
- use `boto` functionality which includes the need for hmac

**Expected behavior**
Suceeds

**Screenshots**

**Environment**
- Patroni version: N/A
- PostgreSQL version: N/A
- DCS (and its version): N/A

**Comment by CyberDem0n** [comment]
@jonringer do you plan to work on it?

**Comment by jonringer** [comment]
I do not.

I marked it broken on the Nixpkgs side [here](https://github.com/NixOS/nixpkgs/commit/732b38a835492f4e07b170e04010d2b8b2c9a2b3), but it recently came up at work.

If it's just the test suite which uses the older API, then this might not be much of an issue. But didn't spend much time investigating, as it was [part of a larger stabilizaiton effort](https://github.com/NixOS/nixpkgs/pull/105368)
