### ISSUE TITLE
Question: will patronictl restart on lead node trigger switchover or failover?

### ISSUE THREAD

**Issue by hunterhuang8810** [zalando/patroni#2241]
Hi Expert,

if restart leader node via command:
   patronictl rerstart cluster memer_leader 

will switchover of failover be triggerred? 

I checked on my env, the result is will not , can I get a confirmation? thanks a lot

**Comment by CyberDem0n** [comment]
If everything goes normal there will be just a restart.
But, in case if it takes longer than `master_start_timeout` seconds there will be a failover.
