### ISSUE TITLE
This cluster has no master

### ISSUE THREAD

**Issue by Stan92** [zalando/patroni#2246]
Hi
I don't know if it's the right place but..

Currently I have a cluster with 3 servers.
I had a problem this morning and my master/leader server had no space disk (I notice that I have a lot large files within the base folder (another problem).

So I plan to stop the master node Server (and focus later to solve this space disk problem).
But my cluster doesn't start anymore.
My nodes 2 & 3 are in "stopped" mode and I can't reinit them and  get an error "Cluster has no leader, can not reinitialize".

Any precious help is welcome

About the space disk, If you have direction.
My 3 servers have the same hard disk capacity 2TB.
The "master"  hard disk was full this morning while the 2 others servers has more than 75% of free space.

**Comment by CyberDem0n** [comment]
> I don't know if it's the right place

Most definitely not.

Disk space issues are not related to Patroni, it is your responsibility to monitor them and react accordingly.

> But my cluster doesn't start anymore.

Patroni is only an auto-pilot. If you don't know how to fly the plane manually crash is inevitable.

> My nodes 2 & 3 are in "stopped" mode

Well... It tells nothing. What about logs? Have you tried to examine them?

**Comment by Stan92** [comment]
Thanks for your feedback @CyberDem0n 
Yep I did examine the logs... from the master I get from Patroni "OSErro : [Errno 28] No space left of device"

**Comment by CyberDem0n** [comment]
I mean all logs on all nodes.

**Comment by Stan92** [comment]
After reading some posts, I finally cleaned some files on the master node and everything comes back to up.
In fact, I think I missed something during the installation (newbie I am) cause I have  plenty of files within the folder /data/patroni/base/16386

**Comment by CyberDem0n** [comment]
> I have plenty of files within the folder /data/patroni/base/16386

Please never mess up with files in PGDATA.
