### ISSUE TITLE
GPF with patroni 2.1.3 and EC@ Ubuntu 20.04.1

### ISSUE THREAD

**Issue by pgodfrin-nov** [zalando/patroni#2247]
Patroni appears to be pegging CPU at 100%. Syslog information not consistent, but did capture a GPF on 3-16.
Server with v2.1.2 not experiencing this issue. However I cannot be certain if patroni is the victim or the cause as there a psql process failing at the same time with a  GPF as well.

**To Reproduce**
Unknown, issue has occurred approximately the same time 3-17, 3-16, but at different times on 3-12 & 3-10

**Environment**
- Patroni version: 2.1.3
- PostgreSQL version: 13.5
- DCS (and its version): etcd 
etcd Version: 3.5.2
Git SHA: 99018a77b
Go Version: go1.16.3
Go OS/Arch: linux/amd64

**Patroni configuration file**

scope: unidb01
namespace: /unidb01
#TODO: referencing this name instead of the ip
name: devudb01

log:
  level: WARNING
  #level: DEBUG
  dir: /postgres/admin/logs

restapi:
  listen: 172.21.61.224:8008
  connect_address: 172.21.61.224:8008

etcd3:
  hosts:
  - 172.21.61.224:2379
  - 172.21.67.12:2379
  - 172.21.58.245:2379
  - 172.21.69.253:2379

bootstrap:
<snip>

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 172.21.61.224:5432
  data_dir: /postgres/udb01/data
  bin_dir: /usr/lib/postgresql/13/bin
  pgpass: /home/postgres/.pgpass
  authentication:
    replication:
      username: replication
      # password: rep-pass
    superuser:
      username: postgres
      # password: zalando
    rewind:  # Has no effect on postgres 10 and lower
      username: postgres
  use_pg_rewind: true
  parameters:
    archive_command: 'pgbackrest --stanza=unidb01 archive-push %p'
    archive_mode: 'on'
    archive_timeout: '900s'
    bgwriter_lru_maxpages: 1024
    bgwriter_flush_after: 0
    checkpoint_timeout: '30s'
    checkpoint_completion_target: '0.2'
    commit_delay: 100000
    commit_siblings: 5
    datestyle: 'iso, mdy'
    default_statistics_target: 5000
    default_text_search_config: 'pg_catalog.english'
    dynamic_shared_memory_type: posix  
    effective_cache_size: '14GB'
    effective_io_concurrency:  500
    full_page_writes: 'on'
    fsync: 'on'
    enable_partitionwise_aggregate: on
    huge_pages: 'on'
    lc_messages: 'C.UTF-8'                 
    lc_monetary: 'C.UTF-8'                 
    lc_numeric: 'C.UTF-8'                  
    lc_time: 'C.UTF-8'                      
    listen_addresses: '*'            
    lock_timeout: '15s'
    log_destination: 'stderr'           
    log_directory: '/postgres/admin/logs'
    log_file_mode: 0740                   
    log_filename: 'alert_devudb01.log'        # log file name pattern,
    log_line_prefix: '%m DEVUDB01 [%p] '
    log_min_messages: WARNING
    log_min_error_statement: LOG
    #log_min_messages: DEBUG1
    log_rotation_age: '43200'
    log_statement: ddl
    log_timezone: 'Etc/UTC'
    log_truncate_on_rotation: 'on'
    logging_collector: on
    maintenance_work_mem: 128MB          
    max_parallel_workers: 1024
    max_parallel_workers_per_gather: 8
    max_wal_size: 12GB
    min_wal_size: 2GB
    port: 5432
    restore_command: 'pgbackrest --stanza=unidb01 archive-get %f "%p"'
    shared_buffers: 10GB                  
    shared_preload_libraries: 'pg_stat_statements,timescaledb'
    ssl: 'off'
    synchronous_commit: 'off'
    temp_buffers: 128MB                     
    temp_tablespaces: 'temp01'
    timezone: 'Etc/UTC'
    track_commit_timestamp: 'on'
    unix_socket_directories: '/var/run/postgresql'
    wal_buffers: 512MB
    wal_compression: on
    wal_init_zero: 'off'
    wal_level: replica
    wal_log_hints: "on"
    wal_receiver_status_interval: '0'
    wal_writer_delay: 3s
    wal_writer_flush_after : 1024MB
    superuser_reserved_connections: 10
  pg_hba:
  - local       all             postgres,godfrinpe                             trust
  - local       replication     postgres,replication                           trust
  - hostnossl   all             all                   127.0.0.1/32             md5 
  - host        postgres        postgres              127.0.0.1/32             trust
  - host        replication     replication           127.0.0.1/32             trust
  - host        postgres        postgres,replication  172.21.67.12/32          trust
  - host        replication     postgres,replication  172.21.67.12/32          trust

  recovery_conf:
    restore_command: 'pgbackrest --stanza=unidb01 archive-get %f "%p"'
    standby_mode: on
    primary_conninfo: 'application_name=devudb01 host=devudb02.novcds.io user=replication port=5432'
    recovery_target_timeline: latest
    primary_slot_name: devudb02

watchdog:
#TODO: check out softdog
#  mode: automatic # Allowed values: off, automatic, required
  mode: off # Allowed values: off, automatic, required
#  device: /dev/watchdog
#  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
yes, there is no info at the time of failure

**Have you checked PostgreSQL logs?**
Yes, nothing of import at the time of GPF:
```
2022-03-16 23:24:54.907 UTC DEVUDB02 [12399] LOG:  checkpoint starting: time
2022-03-16 23:24:55.047 UTC DEVUDB02 [12399] LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 
removed, 1 recycled; write=0.116 s, sync=0.003 s, total=0.141 s; sync files=1, longest=0.003 s, average=0.003 s; distan
ce=131072 kB, estimate=131072 kB
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@2022-03-17 12:5
0:04.192 UTC DEVUDB02 [1782] LOG:  starting PostgreSQL 13.5 (Ubuntu 13.5-2.pgdg20.04+1) on x86_64-pc-linux-gnu, compile
d by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
2022-03-17 12:50:04.192 UTC DEVUDB02 [1782] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-03-17 12:50:04.194 UTC DEVUDB02 [1782] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-03-17 12:50:04.201 UTC DEVUDB02 [1785] LOG:  database system was interrupted while in recovery at log time 2022-03
-17 12:49:03 UTC
```


**Have you tried to use GitHub issue search?**
Yes


**Additional context**
Add any other context about the problem here.

**Comment by pgodfrin-nov** [comment]
Addt'l infor:
CPU is pegging at 100% and another server w/2.1.2 is not failing

**Comment by pgodfrin-nov** [comment]
oh duh, let me fix that.
General Protection Fault.
It would help if I actually attached the dump... Sorry
pg
[syslog-0316-gpf.log](https://github.com/zalando/patroni/files/8289312/syslog-0316-gpf.log)

**Comment by CyberDem0n** [comment]
Well, it doesn't prove anything.

**Comment by pgodfrin-nov** [comment]
Indeed it does not. Since it appears that patroni is somehow involved, I thought this issue could lead somewhere. I suppose if you haven't seen a 'GPF' related syslog dump, then I am mistaken.
Here's why I thought I'd ask:

```
general protection fault, probably for non-canonical address 0x2938a0ef75379ff2: 0000 [#2] SMP NOPTI
CPU: 0 PID: 432477 Comm: patroni Tainted: G      D    OE     5.11.0-1028-aws #31~20.04.1-Ubuntu
Hardware name: Amazon EC2 m6i.xlarge/, BIOS 1.0 10/16/2017
RIP: 0010:kmem_cache_alloc+0xfd/0x440
Code: 4c 03 05 1e ee 53 5f 49 83 78 10 00 4d 8b 28 0f 84 f8 02 00 00 4d 85 ed 0f 84 ef 02 00 00 41 8
RSP: 0018:ffffae31c87ab890 EFLAGS: 00010012
RAX: 2938a0ef75379ff2 RBX: ffffffffc066d118 RCX: ffff90088ece73ca
RDX: 000000000001378b RSI: 0000000000000a20 RDI: 00003e25a0c25930
RBP: ffffae31c87ab8c0 R08: ffffce31bfc25930 R09: ffff900900ca3000
R10: 000000000006995d R11: 0000000000000006 R12: ffff9008366d7e00
R13: 2938a0ef75379fba R14: 0000000000000a20 R15: 0000000000000000
FS:  00007f5a7d7fa700(0000) GS:ffff900c1f000000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 00007ff95e2021f9 CR3: 0000000047c24002 CR4: 00000000007706f0
DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
```

**Comment by pgodfrin-nov** [comment]
yes indeed. I take it you have not seen this issue with patroni?

**Comment by CyberDem0n** [comment]
We never saw Patroni using 100% CPU.

**Comment by pgodfrin-nov** [comment]
Thanks very much. Have a nice weekend!
