### ISSUE TITLE
The Decision to Failover

### ISSUE THREAD

**Issue by MichaelDBA** [zalando/patroni#2248]
My goal is to delay automatic failover to help decrease the chances of a false positive (network hiccup, etc.)  Also, I want to avoid failover if the standby asynchronous slave is not up to date with the master.  In fact, I may want to cancel the failover if the slave is not up to date with the master.  Also, if the best slave candidate is not up to date, and the master crashes, I would like to wait for however long it takes for the master to recover and be active again.  Another reason I want to wait for the master to recover is that there may be many WALs that are not archived yet, and the slave that is behind will never see these WALs still residing in the master's WAL directory. 

I see some alternatives to help prevent situations like this by:
1. making checkpoints happen much faster, every minute, to help ensure WALs are archived ASAP.
2. making the standby a synchronous slave so that we are pretty much guaranteed that a failover to it will be very consistent with the former master.

Problems with the 1st one is that for heavy OLTP updates, this can lead to performance degradation.  The 2nd one may add more than tolerable network lag to each committed transaction.  The network lag within the same data center is normally not a problem, usually less than a couple milliseconds.  This assumes we are using synchronous_commit = on or remote_write (implied by "on").

Is there a configurable way either through ETCD, PATRONI, or POSTGRESQL to help achieve my goals?

**Comment by CyberDem0n** [comment]
Have you tried to read the documentation https://patroni.readthedocs.io/en/latest/replication_modes.html ?

**Comment by MichaelDBA** [comment]
Thanks for that link.  It cleared up some of my confusion, but not all.  Firstly, the YAML configuration file for patroni has 2 of the same parameters as does the PostgreSQL configuration file, namely:
- synchronous_commit: "on"
- synchronous_standby_names: "*"
I don't quite understand how they work with each other.  What happens when you have synchronous turned "off" in patroni, but "on" in postgresql?
Also I don't understand this statement from the docs:
`Turning on synchronous_mode does not guarantee multi node durability of commits under all circumstances. When no suitable standby is available, primary server will still accept writes, but does not guarantee their replication. 
`
How can that be?  Being in synchronous mode means that if there is no response from an available synchronous standby, then the primary will not accept writes.

**Comment by CyberDem0n** [comment]
> synchronous_commit: "on"

The `synchronous_commit` must be set to `on`, `remote_write`, or `remote_apply`.

> synchronous_standby_names: "*"

The `synchronous_standby_names` is managed by Patroni if `synchronous_mode` enabled.

> Also I don't understand this statement from the docs:
...
How can that be? 

It is the design choice. Patroni can disable `synchronous_mode` if there are no sync nodes available. You can change it by enabling `synchronous_mode_strict`.

**Comment by MichaelDBA** [comment]
Thanks for the clarification.  Appreciate the feedback, @CyberDem0n
