### ISSUE TITLE
ETCD/Patroni ERROR: Failed to get list of machines 

### ISSUE THREAD

**Issue by hschoenh** [zalando/patroni#2249]
Hi,
i run into this error when starting patroni, any advises?

patroni[6864]: ERROR: Failed to get list of machines from localhost:2379/v2: EtcdException('Bad response : 404 page not found\n',)
patroni[6864]: INFO: waiting on etcd

etcd Version: 3.5.2
patroni 2.1.3

**Comment by CyberDem0n** [comment]
Have you seen https://github.com/zalando/patroni/issues/1939 ?

**Comment by CyberDem0n** [comment]
Also, in 3.5 the v2 API is disabled by default.

**Comment by hschoenh** [comment]
Thanks for sharing the article.
adding the etcd3 flag to the config file and restart the service pop up another error.

# patroni config
etcd3:
  host: srvpgs1:2379
  enable-grpc-gateway: true

Mar 22 14:58:44 srvpgs1 systemd[1]: Started Run High Availability.
Mar 22 14:58:45 srvpgs1 patroni[5220]: 2022-03-22 14:58:45,041 INFO: Selected new etcd server http://192.168.56.11:2379
Mar 22 14:58:45 srvpgs1 patroni[5220]: Traceback (most recent call last):
Mar 22 14:58:45 srvpgs1 patroni[5220]:  File "/usr/local/bin/patroni", line 11, in <module>
Mar 22 14:58:45 srvpgs1 patroni[5220]:    sys.exit(main())
Mar 22 14:58:45 srvpgs1 patroni[5220]:  File "/usr/local/lib/python3.6/site-packages/patroni/__main__.py", line 143, in main
Mar 22 14:58:45 srvpgs1 patroni[5220]:    return patroni_main()
Mar 22 14:58:45 srvpgs1 patroni[5220]:  File "/usr/local/lib/python3.6/site-packages/patroni/__main__.py", line 135, in patroni_main
Mar 22 14:58:45 srvpgs1 patroni[5220]:    abstract_main(Patroni, schema)
Mar 22 14:58:45 srvpgs1 patroni[5220]:  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 98, in abstract_main
Mar 22 14:58:45 srvpgs1 patroni[5220]:    controller = cls(config)
Mar 22 14:58:45 srvpgs1 patroni[5220]:  File "/usr/local/lib/python3.6/site-packages/patroni/__main__.py", line 29, in __init__
Mar 22 14:58:45 srvpgs1 patroni[5220]:    self.postgresql = Postgresql(self.config['postgresql'])
Mar 22 14:58:45 srvpgs1 patroni[5220]:  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 67, in __init__
Mar 22 14:58:45 srvpgs1 patroni[5220]:    self._data_dir = config['data_dir']
Mar 22 14:58:45 srvpgs1 patroni[5220]: KeyError: 'data_dir'
Mar 22 14:58:45 srvpgs1 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Mar 22 14:58:45 srvpgs1 systemd[1]: patroni.service: Failed with result 'exit-code'.


[root@srvpgs1 ~]# curl -XPOST localhost:2379/v3/cluster/member/list |jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   238  100   238    0     0  59500      0 --:--:-- --:--:-- --:--:-- 59500
{
  "header": {
    "cluster_id": "770398461291026846",
    "member_id": "1661647507645041861",
    "raft_term": "2"
  },
  "members": [
    {
      "ID": "1661647507645041861",
      "name": "srvpgs1",
      "peerURLs": [
        "http://192.168.56.11:2380"
      ],
      "clientURLs": [
        "http://192.168.56.11:2379"
      ]
    }
  ]
}

**Comment by CyberDem0n** [comment]
I am not sure what exactly you are doing, but you get the error because Patroni config file is invalid.

P.S.  enable-grpc-gateway: true -- this is not the option for the Patroni config.

**Comment by hschoenh** [comment]
disable this parameter "enable-grpc-gateway: true " doesnt help so far

scope: ha_cluster
name: srvpgs1
restapi:
  listen: srvpgs1:8008
  connect_addresses: srvpgs1:8008
  #authentication:
  #username: api
  #password: password
etcd3:
  host: srvpgs1:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
  initdb:
    - encoding: UTF8
    - locale: en_US.UTF-8
  pg_hba:
    - host replication replicator 192.168.56.11/32 md5
    - host all all 0.0.0.0/0 md5
  users:
    admin:
    password: password
    options:
      - createrole
      - createdb
  postgresql:
    listen: localhost,192.168.56.11:5432
    connect_address: 192.168.56.11:5432
    bin_dir: /usr/pgsql-13/bin
    data_dir: /var/lib/pgsql/13/data
    pgpass: /var/lib/pgsql/.pgpass
    use_pg_rewind: true
    authentication:
      superuser: 
        username: superadmin
        password: password
      replication:
        username: replicator
        password: password
      rewind:
        username: rewind
        password: password
    parameters:
      shared_buffers: "128MB"
      work_mem: "4MB"
      wal_level: hot_standby
      hot_standby: "on"
      wal_keep_segments: 8
      max_wal_sender: 10
      max_replication_slots: 10
      wal_log_hints: "on"
      archive_mode: "on"
      active_timeout: 1800s
      archive_command: /bin/true
  watchdog:
    mode: automatic
    device: /dev/watchdog
  tags: 
    nofailover: false
    noloadbalncer: false

**Comment by CyberDem0n** [comment]
Your config is wrongly formatted.
Please start from scratch by using sample configs from the repo.

**Comment by hschoenh** [comment]
ok, thx
