### ISSUE TITLE
docs/index.rst: Introduction misses an introduction ;-)

### ISSUE THREAD

**Issue by cboltz** [zalando/patroni#2250]
**Describe the bug**

Someone just told me something like "you might be interested in patroni", and answered my "what's this?" question with "google for patroni postgresql". This lead me to https://patroni.readthedocs.io/en/latest/ aka `docs/index.rst`.

The "Introduction" section might be obvious for you, but for someone who never heard about patroni before, it's hard to get a first idea what it's doing.

**To Reproduce**

Think you never heard about patroni, then read the introduction section and try to understand what it does.

How long does it take you to understand that patroni is "something to manage a postgresql HA setup"? (IMHO: too long)

**Expected behavior**

The introduction section should start with a simple explanation what patroni is and does, before going into details.

A simple solution might be to copy over the headline of `README.rst` to the introduction section:

    Patroni: A Template for PostgreSQL HA with ZooKeeper, etcd or Consul

or use my summary from above (assuming I got it right)

    Patroni is something to manage a PostgreSQL HA setup

With one of these, it would be much easier for newbies to understand what patroni does.

(Feel free to use a different text if you find one that is even more newbie-friendly.)

**Comment by CyberDem0n** [comment]
@cboltz Patroni is an open-source project and we accept any kind of contributions including documentation improvement.
Please feel free to fork, update, and open a pull request.
