### ISSUE TITLE
How to set the patroni.yml config file when i want to ipv4&ipv6 synchronously

### ISSUE THREAD

**Issue by mxli441** [zalando/patroni#2255]
How to set the patroni.yml config file when i want to ipv4&ipv6 synchronously,could you give me a patroni.yml template?

Thanks

**Comment by CyberDem0n** [comment]
I am failing to understand what you are doing.
One can configure postgres to listen on many IPs.
With Patroni API you may set it to the `restapi.listen` to the `*:8080` and it will listen by default on IPv4 and IPv6.

**Comment by CyberDem0n** [comment]
> it doesn't work!

That's not a Patroni problem, the `*` is the special character in YAML and **must** be quoted:
```yaml
listen: "*:18008"
``

**Comment by mxli441** [comment]
Yes,it works now !
Thank you very much !!@CyberDem0n
