### ISSUE TITLE
Repeat ! Exception when working with leader ... in check_leader_is_not_in_recovery ... permission denied for database "postgres"

### ISSUE THREAD

**Issue by sgrinko** [zalando/patroni#2257]
Please return to the problem from Issue. #2256

[CyberDem0n](https://github.com/CyberDem0n) It proposes to give the right to connect the user to the REPLICATION and thus give it more rights than it is necessary - processing the replication protocol.

I think this approach is wrong. The documentation clearly said - do not give rights more than required.
[STREAMING-REPLICATION-AUTHENTICATION](https://www.postgresql.org/docs/14/warm-standby.html#STREAMING-REPLICATION-AUTHENTICATION)

The Patroni settings have a place to establish a separate user, which is used in this part of the code in meaning!
```
authentication:
    rewind:
```
Commit https://github.com/zalando/patroni/commit/3e1076a5746b4d7f313eaba0ff374824644c8ab1fully removed this opportunity.

Be able to build system security in the desired way an important advantage!
Otherwise, everyone would always worked from the rights of SuperUser :)

However, this is not.

[CyberDem0n](https://github.com/CyberDem0n) This approach destroys the security of the system!

Please roll back this COMMIT!

**Comment by xinferum** [comment]
I support this position regarding the access rights for the replication user.
I don't understand why my issue https://github.com/zalando/patroni/issues/2256 was closed without discussion.

**Comment by CyberDem0n** [comment]
> This approach destroys the security of the system!

I am sorry, but you are totally wrong. Whoever has replication access can already get the entire PGDATA via the replication protocol. I.e., it gives way more powerful access than the ability to connect to one or another database in the cluster.

**Comment by CyberDem0n** [comment]
> there is nothing about the new requirement 

Well, Patorni never revoked the CONNECT privilege from the replication user.

**Comment by sgrinko** [comment]
Explain what the user did not come up?
```
authentication:
    rewind:
```

Why was it just that just took to use the user with the right replication?

Why not start a separate user with the requirement of only the right rights?

**Comment by CyberDem0n** [comment]
It is only possible to use pg_rewind without a superuser on v11 and newer.
Demanding a new user for every little thing will create more problems than solve.

**Comment by sgrinko** [comment]
> If the intruder got the replication credentials it already can access everything in the DB, regardless of whether it can explicitly CONNECT or not.

So let's give this user even more right so that the attacker makes it much easier!
Is this the right approach? Not!

Earlier on the code, if the user of the Rewind was not specified, the user was used, the user SuperUser was used
What prevents users from the 10th version to remain in this paradigm?

**Comment by CyberDem0n** [comment]
> even more right so that the attacker makes it much easier!

You either don't read what I am writing or don't understand...

> the user SuperUser was used

There are v10 deployments that don't allow superuser access between nodes. They don't rely on pg_rewind, but instead rebuild the node by taking the basebackup in case if timelines are diverging. Diverged timelines could be reliably detected only if the new leader is not in recovery. Introducing the new user just for this one stupid thing is way too much.

**Comment by CyberDem0n** [comment]
> Be able to connect to the database and read all of it much easier :)

Replication protocol allows to download the entire PGDATA. Think about it, security officer...

**Comment by sgrinko** [comment]
Of course you can, but why give even more rights?!
While someone will do it there is a chance to notice and take steps ...
Note short connections much more difficult ...

**Comment by CyberDem0n** [comment]
Once again, you deliberately revoked the CONNECT privilege from the replication user or public role, hence it is your problem. I don't see any single reason why we should create workarounds in Patroni  just for you.
If you care about security so much there is always a way to allow CONNECT to the postgres db and revoke everything except calling pg_is_in_recovery(). It is absolutely the same as introducing a new user.

**Comment by xinferum** [comment]
> Well, Patorni never revoked the CONNECT privilege from the replication user.
The CONNECT right was never required for a replication user.

**Comment by sgrinko** [comment]
> If you care about security so much there is always a way to allow CONNECT to the postgres db and revoke everything except calling pg_is_in_recovery(). It is absolutely the same as introducing a new user.

This is a very unexpected demand from the patroni to add new rights to the user who is completely alien to him because of his direct duties.

Why don't you want to add a few lines of code on your side to perform a very important function - determining the status of instance, what affects the integrity of the entire system?

**Comment by CyberDem0n** [comment]
How adding the new user is better than modifying the existing one?

**Comment by sgrinko** [comment]
User function Replicator - Only work on a replication protocol. I really want to leave for him only this opportunity.

Another user with an instance status check function is very good, since he will not be able to do anything else in the system.

This will allow you to have the best security control at the work of the system.

**Comment by sgrinko** [comment]
Checking the status of instance - a frequent operation. A separate user with minimal rights will make it completely safe, i.e. You can not pay attention to these connections.

User Connect with replicator rights in the database is a sign of something unexpected. It is worth paying attention to it. The elimination of this situation greatly facilitates control.

**Comment by CyberDem0n** [comment]
No, it's not convincing.
Another user creates more problems than solves nonexistent problems. Period.

**Comment by sgrinko** [comment]
I do not see any problems in the presence of a special user for software.
The `postgres` user already has and is used as SuperUser in system setup operations.
The user with the right replicate is also used when operating instance replication and only for this.
An application user (Patroni) is normal and expected. To perform specific functions where you do not need much rights.
I admit that you as an ordinary developer can not see the need for a complication of the security system. But it is very important in ordinary life.

Have a special user software - is it so difficult?

Give the opportunity to customize users as they want - this is the right way!
Do you think otherwise?

**Comment by sgrinko** [comment]
Patroni is a complex software with a large number of different opportunities.
Use for these features of different users is normal and expected.
To strive to reduce their number - it is commendable, but it is not necessary to bring it to the detriment of security settings.

**Comment by sgrinko** [comment]
Patroni is a complex software with a large number of different opportunities.
Use for these features of different users is normal and expected.
To strive to reduce their number - it is commendable, but it is not necessary to bring it to the detriment of security settings.

**Comment by xinferum** [comment]
I still don’t understand why, in response to issue https://github.com/zalando/patroni/issues/2162, you simply didn’t indicate what is required in this case to use a separate user rewind (which is applicable for these cases in your config and code ), but changed the requirements for replication user rights, and the credentials of the check_leader_is_not_in_recovery() function.
It is not correct.
