### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Tiago-DBA** [zalando/patroni#2260]
Hi,

I am aware of new parameter pre_promote.

Do you have the same feature *after* promotion is done (e.g . a parameter on patroni's config where we could set a script to  trigger after promote) ?

Use case is : after promotion patroni is the one which is fully aware promotion happened succesfully, sometimes after promote we could have internal IT operations to trigger (e.g. reconfigure others related tools, example  switch backup repositories configuration). This could also provide usage of custom scripts for the "switch ip" feature, we could use whatever we want the way we want.

Thank you

**Comment by CyberDem0n** [comment]
There are callbacks: https://patroni.readthedocs.io/en/latest/SETTINGS.html#postgresql
They are doing exactly what you want.

> callbacks: callback scripts to run on certain actions. Patroni will pass the action, role and cluster name. (See scripts/aws.py as an example of how to write them.)
     -   on_reload: run this script when configuration reload is triggered.
     -   on_restart: run this script when the postgres restarts (without changing role).
     -   on_role_change: run this script when the postgres is being promoted or demoted.
     -   on_start: run this script when the postgres starts.
     -   on_stop: run this script when the postgres stops.

You can learn more about callbacks from the tutorial: https://github.com/patroni-training/2019
