### ISSUE TITLE
Question on packaging

### ISSUE THREAD

**Issue by Tiago-DBA** [zalando/patroni#2262]
Hello,

Where do you recommend to get rpm for SUSE linux distributions ?

also about _https://patroni.readthedocs.io/en/latest/SETTINGS.html#raft-settings
Q: Where to get the syncobj_admin utility?
A: It is installed together with pysyncobj module (python RAFT implementation), which is Patroni dependency._

Could you clarify in which packaging tool you specify that dependency ?

Thank you.

**Comment by CyberDem0n** [comment]
There are Patroni packages in pgdg repo.
I'm not sure though if they support raft, but, you can install pysyncobj module separately with pip.
Please keep in mind that it's not production ready.
