### ISSUE TITLE
Patroni configuration flow

### ISSUE THREAD

**Issue by izenk** [zalando/patroni#2266]
Hello
Is there any description about how patroni apply configuration from file?
I see some info there [docs](https://patroni.readthedocs.io/en/latest/SETTINGS.html#)
But it is still unclear how and when is "postgresl:" section applied. I understand that bootstrap(with "postgres:" inside) is applied only when postgres data_dir is empty during bootstrap.
For the "postgresql:" section outside of bootstrap section I can define connect_address for example and, after patronictl restart, it will be applied.
But with "recovery_conf" section behaviour is different.
If I add this section to bootstrap, it will be applied
If I add this section to "postgresql:" section outside of bootstrap - it is ignored
If I add this section to dcs as runtime config - it will be applied

**Comment by CyberDem0n** [comment]
1. https://patroni.readthedocs.io/en/latest/dynamic_configuration.html
2. I would also recommend going through the [tutorial](https://github.com/patroni-training/2019), this topic is pretty well covered.

P.S. `postgresql.recovery_conf` section perfectly works if it is in the local config.
P.P.S When changing the local config you have to perform an explicit reload either by sending SIGHUP to the Patroni pid or by calling `patronictl reload $SCOPE $MEMBER_NAME`
