### ISSUE TITLE
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: exhibitor, kubernetes, zookeeper

### ISSUE THREAD

**Issue by Shiva2199** [zalando/patroni#2267]
I am trying to load the ssl certificates by executing the patronictl reload config / patronictl reload <my-cluster-name>
when I execute the command I am getting this error Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: exhibitor, kubernetes, zookeeper

**Expected behavior**
patroni to reload the config and work with no down time

**Environment**
- Patroni version:
- PostgreSQL version:2.0.1

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
``
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: exhibitor, kubernetes, zookeeper'

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

2022-04-07 15:44:40,254 INFO: does not have lock
2022-04-07 15:44:40,256 INFO: no action.  i am a secondary and i am following a leader

**Comment by CyberDem0n** [comment]
`patronictl -c patroni.yaml`

**Comment by Shiva2199** [comment]
after executing patronictl -c /etc/patroni.yaml reload cluset_name
Reload request received for member patroni_xxxxxx and will be processed within 10 seconds
my expectation is that patroni will load the new ssl certificates 

systemctl status patroni
Apr 06 12:54:22 hybrid-postgres patroni[7903]: localhost:6432 - accepting connections
Apr 06 12:54:24 hybrid-postgres- patroni[7903]: server promoting
Apr 06 12:54:38 hybrid-postgress patroni[7903]: server signaled
Apr 08 07:23:30 hybrid-postgres- patroni[7903]: server signaled
Apr 12 10:40:27 hybrid-postgres patroni[7903]: server signaled
Apr 12 11:07:57 hybrid-postgres- patroni[7903]: server signaled
Apr 12 13:31:07 hybrid-postgres- patroni[7903]: server signaled

but when I looked into server certificates it is still using old ssl certificates.
can someone help me in understanding how to load the ssl certificates after renewal
