### ISSUE TITLE
[Question] How to verify if Patroni is using watchdog?

### ISSUE THREAD

**Issue by markosutic** [zalando/patroni#2296]
Hello,

When using _automatic_ mode watchdog (softdog) will be used if available. 

We can verify if watchdog is used by Patroni process using _lsof_ command or check in the Patroni logs.

```
# lsof /dev/watchdog
COMMAND PID     USER   FD   TYPE DEVICE SIZE/OFF  NODE NAME
patroni 882 postgres    6w   CHR 10,130      0t0 13550 /dev/watchdog
```

Is there any other way to verify if watchdog is used by Patroni other then specified above?
For example if you want to monitor if watchdog is used.

If not, maybe it would be useful to have this info in Consul UI.

Thank you.

**Comment by CyberDem0n** [comment]
If something isn't right you'll see it immediately in logs. Also, if watchdog is required, node can't become a leader if watchdog isn't working.

**Comment by markosutic** [comment]
If _automatic_ mode is used, and something is not right with watchdog, Patroni will start with warning message "WARNING: Could not activate Linux watchdog device...".

I was just curious if there is any info available other than log or running _lsof_ command.

For example if you want to check the status of the leader and get output if watchdog is activated or not.

**Comment by CyberDem0n** [comment]
> I was just curious if there is any info available other than log or running lsof command.

No, there is nothing.
If the _automatic_ mode is chosen you already agreed to run without a watchdog (sort of).

**Comment by markosutic** [comment]
Thank you for the info.
