### ISSUE TITLE
"Pending Restart" does not clear up

### ISSUE THREAD

**Issue by sandeepkalra** [zalando/patroni#2297]
**Describe the bug**
On my standby setup, the "Pending Restart" appears and the restart (via command or cURL) does not clear it, but reports it successfully done.

**To Reproduce**
I have 3 Active cluster, and 3 standby cluster. They do not share DCS and for testing purposes are deployed on same host with different cluster name. The standby setup has `standby_cluster` with `host: ip of active leader` and port mentioned in all 3 standby nodes, and on deployment they show "Pending Restart"

```
+ Cluster: postgres-alias (6987041695289602141) ------+----+-----------+-----------------+-----------------+
| Member     | Host        | Role           | State   | TL | Lag in MB | Pending restart | Tags            |
+------------+-------------+----------------+---------+----+-----------+-----------------+-----------------+
| pg_SiteA_0 | 172.16.0.44 | Standby Leader | running |  5 |           | *               | clonefrom: true |
| pg_SiteA_1 | 172.16.0.48 | Replica        | running |  5 |         0 | *               | clonefrom: true |
| pg_SiteA_2 | 172.16.0.49 | Replica        | running |  5 |         0 | *               | clonefrom: true |
+------------+-------------+----------------+---------+----+-----------+-----------------+-----------------+

```

At this point if i run : patronictl restart postgres-alias pg_SiteA_0, it prints success

```
+ Cluster: postgres-alias (6987041695289602141) ------+----+-----------+-----------------+-----------------+
| Member     | Host        | Role           | State   | TL | Lag in MB | Pending restart | Tags            |
+------------+-------------+----------------+---------+----+-----------+-----------------+-----------------+
| pg_SiteA_0 | 172.16.0.44 | Standby Leader | running |  6 |           | *               | clonefrom: true |
| pg_SiteA_1 | 172.16.0.48 | Replica        | running |  6 |         0 | *               | clonefrom: true |
| pg_SiteA_2 | 172.16.0.49 | Replica        | running |  6 |         0 | *               | clonefrom: true |
+------------+-------------+----------------+---------+----+-----------+-----------------+-----------------+
When should the restart take place (e.g. 2022-05-12T21:40)  [now]:
Are you sure you want to restart members pg_SiteA_0? [y/N]: y
Restart if the PostgreSQL version is less than provided (e.g. 9.5.2)  []:
2022-05-12 20:40:16,004 - DEBUG - Starting new HTTP connection (1): 172.16.0.44:8008
2022-05-12 20:40:17,307 - DEBUG - http://172.16.0.44:8008 "POST /restart HTTP/1.1" 200 None
Success: restart on member pg_SiteA_0
```
but the "Pending Restart" does not clear up. I have tried to do this for each of the 3 standby nodes.

**Expected behavior**
"pending restart" status must clear.
 
**Environment**
- Patroni version: patronictl version 2.1.3
- PostgreSQL version: postgres 12.10
- DCS (and its version): ZooKeeper CLI version: 3.6.2--803c7f1a12f85978cb049af5e4ef23bd8b688715, built on 09/04/2020 12:44 GMT 

![image](https://user-images.githubusercontent.com/5566402/168165019-454a3b3d-4488-48de-a188-66c6f40dc059.png)

**Have you checked Patroni logs?**
yes-  i enabled "DEBUG" logs, and have records.
[patroni.restart.log](https://github.com/zalando/patroni/files/8682516/patroni.restart.log)

**Have you checked PostgreSQL logs?**
Please provide a snippet here
I  did not see any postgres log appearing due to this restart.

**Have you tried to use GitHub issue search?**
I did not find anything relevant.

**Comment by CyberDem0n** [comment]
It doesn't get cleared because in the standby cluster configuration one of the following parameters is set to values that are lower than on the source cluster:
https://github.com/zalando/patroni/blob/96b75fa7cbf43f185642cf7d5e5b6b57ecf231bc/patroni/postgresql/config.py#L1076-L1086
