### ISSUE TITLE
patronictl -c *path_to_config_file* edit-config shows empty config {}

### ISSUE THREAD

**Issue by Dan2B** [zalando/patroni#2303]
Good Day!
We having an issue with patroni 1.6.5-1 on etcd 3.5.2.
Cant change postgres parameters with edit-config or even alter system. 
Command patronictl -c *path_to_config_file* edit-config shows empty brackets - {}
Cluster bootstrapped succefully and fully operational, except issue above.
Error, when trying to write configuration:

--- 
+++ 
@@ -1 +1,3 @@
-{}
+postgresql:
+  parameters:
+    max_connections: 500

Apply these changes? [y/N]: y
2022-05-18 17:56:33,323 - ERROR - 
Traceback (most recent call last):
  File "/opt/app/patroni/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 422, in wrapper
    retval = func(self, *args, **kwargs) is not None
  File "/opt/app/patroni/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 613, in set_config_value
    return self._client.write(self.config_path, value, prevIndex=index or 0)
  File "/opt/app/patroni/lib/python3.6/site-packages/etcd/client.py", line 500, in write
    response = self.api_execute(path, method, params=params)
  File "/opt/app/patroni/lib/python3.6/site-packages/patroni/dcs/etcd.py", line 249, in api_execute
    return self._handle_server_response(response)
  File "/opt/app/patroni/lib/python3.6/site-packages/etcd/client.py", line 987, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/opt/app/patroni/lib/python3.6/site-packages/etcd/__init__.py", line 306, in handle
    raise exc(msg, payload)
etcd.EtcdCompareFailed: Compare failed : [178438 != 178446]
Error: Config modification aborted due to concurrent changes

Thank you in advance.

**Comment by CyberDem0n** [comment]
> Error: Config modification aborted due to **concurrent changes**

You have to try one more time.

**Comment by Dan2B** [comment]
Thank you for your answer, but i have tried several times with same outcome, before i decided to open this issue.
--- 
+++ 
@@ -1 +1,3 @@
-{}
+postgresql:
+  parameters:
+    max_connections: 500

What should i do with brackets in config file? Delete or append configuration below them?
And why other parameters, which cluster currently using not showed when i edit configuration?
Maybe Edit-config recreate option help me in this situation? If so, which parameters should i include in new configuration file?
Thank you for your time.

**Comment by CyberDem0n** [comment]
> What should i do with brackets in config file?
 And why other parameters, which cluster currently using not showed when i edit configuration?

Remove them, they represent the empty json object. That it, the /config key in etcd is either empty or has `{}`.
Why it ended up in such state is another question, most likely it is caused by wrong YAML formatting of Patroni config, but you didn't show it despite the issue template explicitly asking to provide the patroni.yaml

Last, but not least `1.6.5` is more than two years old, you have to upgrade to the latest version.

**Comment by Dan2B** [comment]
Sorry, here is our postgresql.yml used for bootstraping cluster.
Postgresql configuration parameters did not apllied at all, others do (like use_slots)

========================================

scope: scope_name
#namespace: /service/
name: node_name

restapi:
  listen: Node01_IP:8008
  connect_address: Node01_IP:8008
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: password

etcd:
  hosts: etcd-1_IP:2379,etcd-2_IP:2379, etcd-3_IP:2379

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    master_start_timeout: 300
#    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
         max_connections = 500
         shared_buffers = 2GB
         effective_cache_size = 6GB
         maintenance_work_mem = 512MB
         checkpoint_completion_target = 0.9
         wal_buffers = 16MB
         default_statistics_target = 100
         random_page_cost = 1.1
         effective_io_concurrency = 200
         work_mem = 2097kB
         min_wal_size = 2GB
         max_wal_size = 8GB
         max_worker_processes = 4
         max_parallel_workers_per_gather = 2
         max_parallel_workers = 4
         max_parallel_maintenance_workers = 2
#        wal_level: hot_standby
#        hot_standby: "on"
#        wal_keep_segments: 8
#        max_wal_senders: 5
#        max_replication_slots: 5
#        wal_log_hints: "on"
#        archive_mode: "on"
#        archive_timeout: 1800s
#        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
#      recovery_conf:
#        restore_command: cp ../wal_archive/%f %p

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator node-1_IP/0  md5
  - host replication replicator node-2_IP/0  md5
  - host all all 0.0.0.0/0 md5
#  - hostssl all all 0.0.0.0/0 md5

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

  # Some additional users users which needs to be created after initializing new cluster
  users:
    admin:
      password: password
      options:
        - createrole
        - createdb

postgresql:
  listen: Node01_IP:5432
  connect_address: Node01_IP:5432
  data_dir: /var/lib/pgsql/data
  bin_dir: /usr/pgsql-12/bin
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: 
    superuser:
      username: postgres
      password: 

#watchdog:
#  mode: automatic # Allowed values: off, automatic, required
#  device: /dev/watchdog
#  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

**Comment by CyberDem0n** [comment]
You don't tell the full story...
If the `bootstrap.dcs` section was changed after the cluster was bootstrapped it will not be applied.

Right now I can only recommend to take the latest Patroni release and start from scratch: empty etcd, empty PGDATA, and so on.

**Comment by Dan2B** [comment]
> You don't tell the full story... If the `bootstrap.dcs` section was changed after the cluster was bootstrapped it will not be applied.
> 
> Right now I can only recommend to take the latest Patroni release and start from scratch: empty etcd, empty PGDATA, and so on.

Оk, thank you. 
Have a nice day.
