### ISSUE TITLE
Missing API endpoint for synchronous setups?

### ISSUE THREAD

**Issue by Dennis4b** [zalando/patroni#2305]
I am using Patroni in a 2-server synchronous setup. This works well.

I am using `haproxy` to route read-only queries to both database instances, and read-write requests to the primary (using two different pools in the application, connecting to different ports).

This looks (partially) like this in the `haproxy` config:

```
frontend db_ro 
        mode tcp 
        bind 127.0.0.1:5433
 
        default_backend all_db 
 
frontend db_rw 
        mode tcp 
        bind 127.0.0.1:5434 
 
        default_backend only_primary 
 
backend all_db 
        option httpchk OPTIONS /read-only 
        http-check expect status 200 
 
        server db1 192.168.1.1:5432 check port 8008 on-marked-down shutdown-sessions 
        server db2 192.168.1.2:5432 check port 8008 on-marked-down shutdown-sessions 
 
backend only_primary 
        option httpchk OPTIONS /master 
        http-check expect status 200 
 
        server db1 192.168.1.1:5432 check port 8008 on-marked-down shutdown-sessions 
        server db2 192.168.1.2:5432 check port 8008 on-marked-down shutdown-sessions
```

The problem with this setup is that *while* a standby has reconnected and is catching up (but is *not yet* a synchronous standby), the `/read-only` endpoint already returns successfully. The standby is set up as `remote_apply` and it is important that it not return stale data, so it should not be queried until it has fully transitioned back to the `synchronous standby` state.

There is the `/synchronous` endpoint, which is great, but this only returns success on the standby and not on the primary. 

As far as I have found so far, i can only set one `httpchk` method for the `haproxy` `backend`, and not per server. So I don't have a single endpoint that returns `true if primary or synchronous standby` (with `/read-only` being `true if primary or any standby`).

I've looked at the code to add this, but it's a rather long nested `if-then-else` where I'm not familiar with all the details to confidently add a `/read-only-sync` endpoint.

There's probably `haproxy` tricks to be done (and I of course welcome any tips - I'd also like to `leastconn` balance across both `backends` etc), but it's perhaps worth adding such an endpoint as this is probably a common use-case?

**Comment by CyberDem0n** [comment]
When relying on the `/synchronous` endpoint for traffic routing you have to keep in mind that it is only _eventually_ synchronous, because the replica can know that it is a synchronous one only by querying the `/sync` key in DCS. The last one happens only every `loop_wait` (10s by default). That being said, it could happen that the given replica stopped being synchronous, but the endpoint will continue returning 200 for another 10s.

> I've looked at the code to add this, but it's a rather long nested if-then-else where I'm not familiar with all the details to confidently add a /read-only-sync endpoint.

It should be rather trivial. If you open a PR we will provide feedback if something isn't right.
