### ISSUE TITLE
"data directory ... has invalid permissions", after postgresql process got restarted

### ISSUE THREAD

**Issue by Samusername** [zalando/patroni#2307]
patronictl version 2.1.3
spilo: 14:2.1-p4
In kubernetes (K8s)

"data" dir permission problem started to occur at 13:27 UTC time.

**2022-05-18 13:27**:44 UTC [18805]: [1-1] 6284f450.4975 0 FATAL: data directory "/home/postgres/pgdata/pgroot/data" has invalid permissions
2022-05-18 13:27:44 UTC [18805]: [2-1] 6284f450.4975 0 DETAIL: Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).

postgres process was restarted before that (because of other problems).
Container was not restarted. Only the postgress process got restarted.

postgres container has been up and running before the permissions problem started to occur:

```
Containers:
  postgres:
    Container ID:   ...
    Ports:          8008/TCP, 5432/TCP, 8080/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Tue, 17 May 2022 07:45:06 +0000
    Ready:          True
    Restart Count:  0
```

Inside postgres container, see dates (patroni has been running all the time):

ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
postgres       1       0  0 May17 ?        00:00:00 /usr/bin/dumb-init -c --rewrite 1:0 -- /bin/sh /launch.sh
postgres       7       1  0 May17 ?        00:00:00 /bin/sh /launch.sh
postgres      28       7  0 May17 ?        00:00:02 /usr/bin/runsvdir -P /etc/service
postgres      29      28  0 May17 ?        00:00:00 runsv patroni
postgres      30      28  0 May17 ?        00:00:00 runsv pgqd
postgres      31      29  0 **May17** ?        00:02:19 /usr/bin/python3 /usr/local/bin/**patroni** /home/postgres/postgres.yml
postgres      32      30  0 May17 ?        00:00:03 /usr/bin/pgqd /home/postgres/pgq_ticker.ini
postgres   28712       1  0 **May18** ?        00:00:07 /usr/lib/postgresql/13/**bin/postgres** -D /home/postgres/**pgdata/pgroot/data** --config-file=/home/postgres/pgdata/pgroot/data/postgresql.
postgres   28715   28712  0 May18 ?        00:00:18 postgres: rdbms-pg-cluster: checkpointer 

We are trying to find out where / when we could execute e.g. chmod 700, regarding the data directory.

This permissions problem has been noticed only in **certain type** of lab setup, now. With other types of setups, it has not occurred (now).

**Comment by CyberDem0n** [comment]
Neither Spilo nor Patroni doing such permissions update. Please look the problem in your infrastructure.

**Comment by Samusername** [comment]
Thanks!

**Comment by CyberDem0n** [comment]
There was already an attempt to fix it on Spilo start: https://github.com/zalando/spilo/pull/447/files
We can't do anything else. Especially when the container isn't running as the root user.

**Comment by Samusername** [comment]
On CruchyData side, similar problem has been noticed by various persons?
https://github.com/CrunchyData/postgres-operator/issues/3023


( A note: We have seen permission change operations also in **non** PostgreSQL setups. Certain "Change" happens at the exact same time moment: in PostgreSQL pod and in other STS microservice pod. At the **same second** in **both**. )
