### ISSUE TITLE
How to gracefully stop Patroni for maintenance ?

### ISSUE THREAD

**Issue by AllwynJesu** [zalando/patroni#2312]
Hi,

Say I am running three instances of Patroni within the same Datacenter with etcd as DCS. Due to some reason, Datacenter is undergoing some planned maintenance which might result in restarting the nodes.  So, in this case, how to stop the Patroni cluster?

I understand that there is an option to put the Patroni cluster into the PAUSE state, but this does not stop Patroni nodes. So is there a patronictl command by which I can stop Patroni (and PostgreSQL) in nodes, or do I need to execute the _kill -SIGTERM_ command to patroni process in each node?

Thanks

**Comment by CyberDem0n** [comment]
If you stop Patroni (not paused) it also stops Postgres.
Just first stop all replicas and than the leader.

**Comment by AllwynJesu** [comment]
@CyberDem0n Thanks for the response but is there a patronictl command to stop the patroni or do I need to use the _kill command_ only?

**Comment by CyberDem0n** [comment]
> is there a patronictl command to stop the patroni 

of course there is no such patronictl command, it defeats the purpose of Patroni.

> or do I need to use the kill command only?

Well... Patroni should be started as a service in your system, for example as systemd unit, and you are supposed to use your OS features to start/stop services. Actually, the service better be configured to restart Patroni if it exits unexpectedly.

**Comment by xoyteam** [comment]
does patroni send sigint or sigquit when shutdown postgresql?
