### ISSUE TITLE
[Question] patroni drops replication slots while in maintenance mode

### ISSUE THREAD

**Issue by 1exx** [zalando/patroni#2314]
Hello.
Why Patroni drops replication slots of the stopped standby node (PostgreSQL & patroni service) when cluster was in maintenance mode (pause)? 
Is this expected behavior?

I supposed that in maintenance mode patroni will not be change postgres configuration
I'm using Patroni 2.1.2

**Comment by CyberDem0n** [comment]
It was always like that. To be honest, I don't know what would be better, to keep them or remove.

**Comment by Dsolik** [comment]
In what version can this appear?

**Comment by CyberDem0n** [comment]
@Dsolik the next one after it is implemented and committed to the master branch.
