### ISSUE TITLE
Service account refresh ability for patroni in k8s 1.21 cluster

### ISSUE THREAD

**Issue by kost2191** [zalando/patroni#2316]
Starting from k8s cluster 1.21 patroni needs to resfresh service token. This is commited to master here: https://github.com/zalando/patroni/commit/aa0cd480604069519ebd9b52b0d629e33287341c
But without new release tag, when it is going to be?
Also needed to add to spilo image: https://github.com/zalando/spilo/blob/23f712d1d5eed8ccd4da02b5f1cc5ae40afbb7b7/postgres-appliance/Dockerfile#L402

**Comment by CyberDem0n** [comment]
> when it is going to be?

Maybe next week.
