### ISSUE TITLE
How to use physical and logical replication in Patroni together?

### ISSUE THREAD

**Issue by kozld** [zalando/patroni#2317]
I want to construct cluster like this:

- 3 MAIN nodes linked by physical replication
- N OTHER nodes that receiving data from MAIN nodes via logical replication

I successfully configured physical replication between 3 MAIN nodes, but I did't go far.
I must note that I specify "logical" value for "wal_level" fields for all nodes in my cluster. 
But when I try to create subscription at any OTHER node I got error like this: "logical decoding cannot be used while in recovery".

Can anybody help me please?

I also asked the question here https://stackoverflow.com/questions/72393740/how-to-use-physical-and-logical-replication-in-patroni-together

**Comment by CyberDem0n** [comment]
Well, Postgres doesn't allow logical decoding on replicas.
You can create subscriptions and do logical replication only from the primary.
Although, Patroni can help with not losing logical replication slot on failover.
```yaml
slots:
  permanent_logical_slot_name:
    type: logical
    database: my_db
    plugin: test_decoding
```

I recently did a presentation on this topic: https://www.postgresql.eu/events/pgconfde2022/schedule/session/3745-implementing-failover-of-logical-replication-slots-in-patroni/

**Comment by kozld** [comment]
@CyberDem0n Thanks! I have one more question:
Do I right understand that I can make my primary a Publisher when he also is physical leader?
And I can create Subscription on a standby with the condition that Publisher is only Primary.
Or not?

**Comment by CyberDem0n** [comment]
You can create publications and subscriptions only on nodes that are running as primary.
The question has nothing to do with Patroni, this is how Postgres works.

**Comment by kozld** [comment]
Thanks. 
Is it mean than I can create fictive primary for this purposes? 

That will be something look like this:

              physical           physical
                    |                        |
A. primary <->  B. standby <-> C. standby
          |                   
          | - logical  
          | 
 D. primary
    (fictive)
     
On this scheme nodes A, B and C is a main nodes linked by a physical replication;
Also node A is a publisher and node D is a his subscriber. Both nodes is a primary.
Is it possible?

**Comment by CyberDem0n** [comment]
Node D isn't a fictive primary, but the real one, and it is independent of the cluster it is replicating from.
Again, all your questions have nothing to do with Patroni.

**Comment by skizilbash** [comment]
I am working on a similar setup but following your doc/presentation i've made the change in my yml file through edit-config but i don't see the logical slot in the database. Is there something i am missing?

root@patroni-pgcluster-qa01:/etc/patroni# patronictl -c /etc/patroni/patroni.yml show-config
dcs:
  loop_wait: 10
  maximum_lag_on_failover: 1048576
  permanent_slots:
    logicreplica:
      database: test1
      plugin: pgoutput
      type: logical
    ttl: 30
  retry_timeout: 10
loop_wait: 10
maximum_lag_on_failover: 1048576
pg_hba:
- local   all             all                                     peer
- host    all             all             127.0.0.1/32            scram-sha-256
- host    all             all             10.10.11.140/32         scram-sha-256
- host    all             all             10.10.11.141/32         scram-sha-256
- host    all             all             10.10.11.142/32         scram-sha-256
- host    all             all             10.10.11.11/32          scram-sha-256
- local   replication     all                                     peer
- host    replication     all             127.0.0.1/32            scram-sha-256
- host    replication     replicator     10.10.11.140/32          scram-sha-256
- host    replication     replicator     10.10.11.141/32          scram-sha-256
- host    replication     replicator     10.10.11.142/32          scram-sha-256
postgresql:
  parameters:
    hot_standby: true
    logging_collector: 'on'
    max_replication_slots: 10
    max_wal_senders: 5
    wal_keep_segments: 10
    wal_level: logical
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true

test1=# select * from pg_replication_slots;
-[ RECORD 1 ]-------+-----------------------
slot_name           | patroni_pgcluster_qa02
plugin              | 
slot_type           | physical
datoid              | 
database            | 
temporary           | f
active              | t
active_pid          | 38817
xmin                | 
catalog_xmin        | 
restart_lsn         | 0/9898D90
confirmed_flush_lsn | 
wal_status          | reserved
safe_wal_size       | 
two_phase           | f
-[ RECORD 2 ]-------+-----------------------
slot_name           | patroni_pgcluster_qa03
plugin              | 
slot_type           | physical
datoid              | 
database            | 
temporary           | f
active              | t
active_pid          | 38815
xmin                | 
catalog_xmin        | 
restart_lsn         | 0/9898D90
confirmed_flush_lsn | 
wal_status          | reserved
safe_wal_size       | 
two_phase           | f
