### ISSUE TITLE
Question : how to change etcd3 configurations without stop PostgreSQL

### ISSUE THREAD

**Issue by kikijolicoeur** [zalando/patroni#2325]
Hello.
I have some patroni clustesr configured with etcd with etcd v3 protocol.
Initialy , my etcd cluster had 3 nodes. So the patroni configuration file has the following;

etcd3:
  hosts: X.X.XX:2379,X.X.X.X:2379,X.X.X.X:2379

Now my etcd cluster has 5 nodes. So I want update patroni configuration without stop PostgreSQL (not the primary nor the replica).
Is the following scenario ok
1) set patroni in pause (patronictl pause)
2) update patroni configuration file with the 2 new etcd nodes on primary and replica 
  hosts: X.X.XX:2379,X.X.X.X:2379,X.X.X.X:2379,Y.Y.Y.Y:2379,Y.Y.Y.Y:2379
3) reload patroni service: systemctl reload patroni@12-main on primary and replica
4) resume patroni : patronictl resume

Thanks to have developed Patroni. 

Christian 
3)

**Comment by CyberDem0n** [comment]
> Now my etcd cluster has 5 nodes. So I want update patroni configuration

Great, unless you set `etcd3.use_proxies` Patroni already knows about new Etcd nodes (there is automatic discovery).
Just update the config and no further action is required.

> Is the following scenario ok

If you need to restart Patroni without restarting Postgres - Yes.

**Comment by kikijolicoeur** [comment]
Is there a way to know if patroni has correctly discovered the new nodes ?

**Comment by CyberDem0n** [comment]
If debug logs are enabled it prints (occasionally) `Retrieved list of machines: %s`.
