### ISSUE TITLE
Backup issues

### ISSUE THREAD

**Issue by SzhiH** [zalando/patroni#2328]
pgbackrest tool incremental backup is no problem, full backup will report an error, the error message is as follows

ERROR: [050]: unable to acquire lock on file '/tmp/pgbackrest/main-backup.lock': Resource temporarily unavailable
       HINT: is another pgBackRest process running?
2022-06-09 04:57:09.212 P00   INFO: backup command end: aborted with exception [050]

**Comment by CyberDem0n** [comment]
This is not a Patroni problem
