### ISSUE TITLE
patronidemo-config service

### ISSUE THREAD

**Issue by SzhiH** [zalando/patroni#2329]
What does this service do？

 
apiVersion: v1
kind: Service
metadata:
  name: patronidemo-config
  namespace: postgres
  labels:
    application: patroni
    cluster-name: patronidemo
spec:
  clusterIP: None

**Comment by CyberDem0n** [comment]
@SzhiH GH issues aren't your personal chat, please use slack for such kinds of questions.

And answering your question: patronidemo-config service is required to prevent recycling of patronidemo-config endpoint, which hold global configuration.
