### ISSUE TITLE
Is there way to store password in memory 

### ISSUE THREAD

**Issue by t-ushar** [zalando/patroni#2330]
Hi Team ,

Is there any way to keep the password in memory  ? Instead of keeping in .pgpass or in passing in plan text to yaml .

I have tried by below ways - 

Export the password on shell 

Export password : --
=================

export patroniPassword=patroni
export replicaton_password=patroni_replication

======YAML FILE =====

name: "ip-100-91-45-10.ec2.internal"
scope: inmempass
namespace: /patroni-testing/
restapi:
  connect_address: "ip-100-91-45-10.ec2.internal:8008"
  listen: "0.0.0.0:8008"
consul:
  url: http://100.91.11.11:8500
  register_service: true
bootstrap:
  dcs:
    ttl: 60
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:

  pg_hba:  
   - host replication replicator 0.0.0.0/0 md5
   - host all all 0.0.0.0/0 md5
  users:

parameters:
  - name: patroni_replication
    type: string
    values: ${patroniPasswords}
    
  - name: patroniPassword
    type: string
    values: ${replicaton_passwords}

setps:
  - script: echo (Hiiii)
postgresql:
  listen: "*:5301"
  connect_address: 100.91.45.10:5301
  data_dir: /data/postgres/13/5301
  bin_dir: /usr/pgsql-13/bin/
  authentication:
    replication:
     username: patroni_replication
     password: "{{parameters}}"
    superuser:
     username: patroni
     password: "{{parameters.patroniPassword}}"
    rewind:  
     username: patroni
     password: "{{parameters.patroniPassword}}"
  parameters:

Run the service - 

patroni patroni.yaml  > patroni.log 2>&1 &

But it it not able to pick the password

**Comment by CyberDem0n** [comment]
You can use environment variables https://patroni.readthedocs.io/en/latest/ENVIRONMENT.html#postgresql, but on Postgres v10+ Patroni will write replication password to pgpass anyway and reference it from the `primary_conninfo`.

**Comment by kumar1202** [comment]
So PostgreSQL 10+, environment variables cannot be used at all for configuring Patroni right? We are looking to pass passwords as secrets, is there any other suggested way to do this?

**Comment by CyberDem0n** [comment]
One way or another there will be a password stored on FS.

**Comment by t-ushar** [comment]
@CyberDem0n  - is there any way we can get the password from any wallet  ? Ex - Patroni will fetch the password from secret/wallet.

**Comment by anikin-aa** [comment]
@t-ushar , hi
we are using Vault and env-inject of the password to k8s pods and it's working fine. But, anyway it will be just env variable at the end
