### ISSUE TITLE
CRITICAL: system ID mismatch

### ISSUE THREAD

**Issue by SzhiH** [zalando/patroni#2338]
Hello, please ask Patroni how to delete DCS information in k8s. At present, an error is reported

CRITICAL: system ID mismatch, node patronidemo-0 belongs to a different cluster: 7109647345248743455 != 7109643968243466272

**Comment by HAKANMAZI** [comment]
Here is my solution, but be carefull you are going to remove cluster 

root@8:~# patronictl --config-file /etc/patroni/config.yml list
+ Cluster: postgres (7199592786127882124) ------+
| Member | Host | Role | State | TL | Lag in MB |
+--------+------+------+-------+----+-----------+
+--------+------+------+-------+----+-----------+

root@8:~# patronictl -c /etc/patroni/config.yml remove postgres
+ Cluster: postgres (7199592786127882124) ------+
