### ISSUE TITLE
restarting after failure time too long

### ISSUE THREAD

**Issue by HalacliSeda** [zalando/patroni#2340]
Hello,

I use Consul 1.12 and Patroni 2.1.3

After the switchover, standby take leader lock  and patroni log like that:

INFO: updated leader lock during restarting after failure
INFO: Lock owner: secondary-pg-2; I am secondary-pg-2

And postgres log like that:
FATAL:  the database system is starting up

But, it goes on like this for minutes. Finally, it's switchover again. 
Shouldn't this wait time be shorter if the database is not opening? 
How can I solve this?

Thanks.

**Comment by CyberDem0n** [comment]
Postgres does crash recovery and time depends on many different factors.
There is nothing Patroni could do about it.

**Comment by HalacliSeda** [comment]
Hi,

Thank you for your answer.
