### ISSUE TITLE
QUESTION()- How to set Multiple Consul clusters for DCS

### ISSUE THREAD

**Issue by krishna281803special** [zalando/patroni#2341]
Hi Team, Thank you for providing the tool. 
This is Question, I have repmgr cluster and would like to move from repmgr to Patroni. 

I have this setup. 

DB-PG1 --> HOST1
DB-PG2 --> HOST2

CONSUL-1 ---> HOST3
CONSUL-2 ---> HOST4
CONSUL-3 ---> HOST5

Both DB's are in different hosts and also the Consul nodes are also in different hosts.  (ideally the patroni and consul agents are not in single host. ), From the patroni configuration file, We have to provide consul server endpoint.. 

consul:
       url: https://CONSUL-1:PORT

As of now, i have kept Leader(CONSUL-1) endpoint in Patroni.yaml file.  The question comes here. 

1. What happens to the patroni cluster if consul-1 down. i thought another consul server (consul-2 or consul-3) become leader. But how Patroni knows them..?
2. What happens if complete Consul cluster down(all three nodes)..?, Does DB's still run..
3. What happens if Patroni agent down on Primary and Standby..

I have done some tests, before posting the questions and could not able to understand the functioning. 

Thank you very much in advance. 
Siva

**Comment by CyberDem0n** [comment]
Consul requires you to work with local agent that runs on every host.
The agent is supposed to handle the rest.

**Comment by krishna281803special** [comment]
@CyberDem0n , Thank you for the details.
