### ISSUE TITLE
[Feature Request] Run script when primary changes or gets removed

### ISSUE THREAD

**Issue by mcassaniti** [zalando/patroni#2346]
I'd like to be able to run a script on __all__ nodes when the following occurs:

- A PostgreSQL server becomes the new primary
- There is no primary PostgreSQL server

I know I could write some wrapper that polls the API and looks for primary server changes, but patroni already knows as an event when this occurs. I'm happy to submit a PR for this work but I don't know where to hook into.

My suggestion for calling the script would be `./on-primary-change.sh <primary_ip> <port>` and `./on-primary-change.sh` when there is no primary server.

**Comment by CyberDem0n** [comment]
I am failing to understand how it could be useful.
What problem are you trying to solve?

**Comment by mcassaniti** [comment]
For my particular use case I'm wanting to adjust rules on each node to point to the primary PostgreSQL server. I'm intending to use NAT rules rather than HA proxy.

**Comment by CyberDem0n** [comment]
Well... How is it supposed to work if Patroni isn't running on the node?

**Comment by mcassaniti** [comment]
That's a very good question. For my use case patroni and PostgreSQL are running across all nodes, with any clients running on a subset of the nodes. I'm sure this sounds backward as usually you would expect to have a PostgreSQL cluster and an app cluster that is on separate hosts without patroni running.

**Comment by CyberDem0n** [comment]
Very similar approach is using kube-proxy (it maintains iptables on all nodes).
It sort of works, until it fails because for example change event got missing.
As a result, the node starts looking in the wrong direction.

**Comment by CyberDem0n** [comment]
There is yet another "feature" of iptables, that will make your life hard.
It won't terminate existing connections when rules are updated.
Typically it results in the following situations:
1. application is connected to the replica instead of the primary
2. application is connected to the primary instead of the replica

The second doesn't create many problems, but the first one does.

**Comment by mcassaniti** [comment]
Really? What about a remove and replace which was what I was intending to do?

**Comment by CyberDem0n** [comment]
When you update iptables rules they don't affect existing connections.

**Comment by mcassaniti** [comment]
Based on this it seems I'll need to go the HA proxy route after all. I'll close this one out.
