### ISSUE TITLE
Cannot mix str and non-str arguments

### ISSUE THREAD

**Issue by mneverov** [zalando/patroni#2347]
**Describe the bug**
Got `Cannot mix str and non-str arguments` when performing a failover on unhealthy cluster.

**To Reproduce**
Create a cluster with 1 leader & 1 replica. The cluster is unhealthy (performing a clone from a backup with more data than the cluster storage):

```sh
$ p list
+ Cluster: b35870fb-ee3b-... (initializing) -----+---------------------------------+----+-----------+
| Member              | Host           | Role    | State                           | TL | Lag in MB |
+---------------------+----------------+---------+---------------------------------+----+-----------+
| b35870fb-ee3b-...-0 | X.X.X.X        | Replica | stopped                         |    |   unknown |
| b35870fb-ee3b-...-1 | Y.Y.Y.Y        | Replica | running custom bootstrap script |    |   unknown |
+---------------------+----------------+---------+---------------------------------+----+-----------+

```

Perform a failover:

```sh
$ p failover
Candidate ['b35870fb-ee3b-...-0', 'b35870fb-ee3b-...-1'] []: b35870fb-ee3b-...-1
Current cluster topology
+ Cluster: b35870fb-ee3b-... (initializing) -----+---------+---------+---------------------------------+----+-----------+
| Member                                         | Host    | Role    | State                           | TL | Lag in MB |
+------------------------------------------------+---------+---------+---------------------------------+----+-----------+
| b35870fb-ee3b-...-0                            | X.X.X.X | Replica | stopped                         |    |   unknown |
| b35870fb-ee3b-...-1                            | Y.Y.Y.Y | Replica | running custom bootstrap script |    |   unknown |
+------------------------------------------------+---------+---------+---------------------------------+----+-----------+
Are you sure you want to failover cluster b35870fb-ee3b-...? [y/N]: y
2022-06-17 13:09:49,247 - ERROR - None
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 719, in _do_failover_or_switchover
    r = request_patroni(member, 'post', action, failover_value)
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 171, in request_patroni
    return request_executor(member, method, endpoint, data)
  File "/usr/local/lib/python3.6/dist-packages/patroni/request.py", line 55, in __call__
    url = urlunparse((scheme, netloc, endpoint, '', '', ''))
  File "/usr/lib/python3.6/urllib/parse.py", line 486, in urlunparse
    _coerce_args(*components))
  File "/usr/lib/python3.6/urllib/parse.py", line 123, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
2022-06-17 13:09:49,254 - WARNING - Failing over to DCS
2022-06-17 13:09:49.25450 Could not failover using Patroni api, falling back to DCS
```

**Expected behavior**
No errors.

**Screenshots**

**Environment**
```sh
p version
patronictl version 2.1.3
```

- PostgreSQL version: `pg_control version number:            1201`

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**

**Comment by mneverov** [comment]
@CyberDem0n, thanks for the prompt response. 
I agree, they are not eligible. Maybe in this case patroni should not try to send a failover request with args that cause `urlunparse` fail?

**Comment by mfpekala-nutanix** [comment]
Was looking into this today, and believe the changes in 76b3b99de2f2bfaa8ab2df9e47dbfc3749d14e84 should have resolved this issue. Reverting `request.py` to the version before this commit I am able to reproduce, but afterwards I am not. (I believe the `url = member.api_url or ""` change prevents `url` from being `None` before the call to `urlparse`.) Hope this helps!

**Comment by CyberDem0n** [comment]
closing it, thank you @mfpekala-nutanix for checking

**Comment by pierreozoux** [comment]
We had something that is probably like a split brain, similar error, both pods were in replica.
We tried to failover, we got the same issue.

Updating to patroni 3.0.4 fixed the issue immediatly.

Looking on how to update patroni in zalando.
