### ISSUE TITLE
Pgbouncer with patroni cluster

### ISSUE THREAD

**Issue by therus000** [zalando/patroni#2353]
Good day 
i used a docker compose file to deploy a patroni cluster 
i got now haproxy. etcd. and patroni with Postgres
what the way to deploy pgbouncer and should i need to reconfig a haproxy in this way, and how config pgbouncer connect
thanx so much

**Comment by CyberDem0n** [comment]
you have two options:
1. run pgbouncer next to every Patroni/Postgres and point HAProxy to pgbouncer port instead of Postgres
2. run pgbouncer in front of HAProxy

**Comment by duyhustvn** [comment]
@CyberDem0n Which options is better? Running HAProxy in front of pgbouncer or running pgbouncer in front of HAProxy?

**Comment by bashfreak** [comment]
@CyberDem0n Which options is better? Running HAProxy in front of pgbouncer or running pgbouncer in front of HAProxy?

**Comment by therus000** [comment]
> [@CyberDem0n](https://github.com/CyberDem0n) Which options is better? Running HAProxy in front of pgbouncer or running pgbouncer in front of HAProxy?

I go with option 1 and run haproxy Infront of pgbouncer
Haproxy ---> pgbouncer ---> patroni
Since 2022 everything works fine )))

**Comment by bashfreak** [comment]
> > [@CyberDem0n](https://github.com/CyberDem0n) Which options is better? Running HAProxy in front of pgbouncer or running pgbouncer in front of HAProxy?
> 
> I go with option 1 and run haproxy Infront of pgbouncer Haproxy ---> pgbouncer ---> patroni Since 2022 everything works fine )))

We are experiencing connection termination issues in our database stack: Node.js → → HAProxy -> Pgbouncer → Patroni 

PostgreSQL cluster HAProxy timeouts are terminating both client and server connections. This disruption is causing two major problems:

**Haproxy Timeout Parameters**

\` timeout client 30m

timeout server 30m \`

Our Node.js application is restarting when it tries to use connections that have been terminated after 30min.

**Application Log when client timeout occurs**

\`Error in running query for unprocessed jobs: ConnectionRefusedError \[SequelizeConnectionRefusedError\]: connect ECONNREFUSED 127.0.0.1:1254

parent: Error: connect ECONNREFUSED 127.0.0.1:1254

```
code: 'ECONNREFUSED',
```

original: Error: connect ECONNREFUSED 127.0.0.1:1254

```
code: 'ECONNREFUSED',
```

{"hostname":"SAPR00A98409","level":"\\u001b\[31merror\\u001b\[39m","message":"Unhandled Rejection at:, \[object Promise\], reason:, SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:1254","service":"user-service","timestamp":"Feb-28-2025 18:26:14","timezone":"Asia/Riyadh"}
