### ISSUE TITLE
[Question] How to verify if node reboot was triggered by the Watchdog?

### ISSUE THREAD

**Issue by markosutic** [zalando/patroni#2356]
Hello,

Is there a possibility to verify when and if node reboot was triggered by the Watchdog?
I was expecting ` softdog: Initiating system reboot` message in the OS logs.

OS: Centos 7

Checked `/var/log/dmesg` and `/var/log/messages`. 

There is only info when software watchdog was initialized:
```
Jul 12 09:49:00 patroni4 kernel: softdog: Software Watchdog Timer: 0.08 initialized. soft_noboot=0 soft_margin=60 sec soft_panic=0 (nowayout=0)
```

Thank you for the info.

Best regards,
Marko

**Comment by CyberDem0n** [comment]
It doesn't really look like Patroni specific question.

**Comment by markosutic** [comment]
Thanks for the answer.
Closing issue.
