### ISSUE TITLE
problem with restore a patroni cluster with pgbackrest

### ISSUE THREAD

**Issue by msrd4** [zalando/patroni#2357]
i have a postgres cluster managed by patroni and  i'm trying to test if i can successfuly backup and restore my cluster
i am using pgbackrest and everything seems to work fine with that , i have my backup on a server and have  2 nodes database server
i destroyed my cluster and deleted /var/lib/postgresql/13/main and also etcd keys
i used: sudo -u postgres pgbackrest --stanza=test  --log-level-console=detail restore
and it completed succesfully
some files were created in /var/lib/postgresql/13/main directory including backup_label which contains some info about my backup and a recovery.signal which is  empty
i have this in patroni.yml : 
bootstrap:
    method: pgbackrest
    pgbackrest:
        command: /etc/patroni/boot_pgbackrest.sh
        keep_existing_recovery_conf: False
        no_params: False
        recovery_conf:
            recovery_target_timeline: latest
            restore_command: pgbackrest --stanza=test archive-get %f "%p"
    method: initdb
    initdb:
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        synchronous_mode: true
        synchronous_mode_strict: false
        postgresql:
            use_pg_rewind: true
            use_slots: true
            remove_data_directory_on_rewind_failure: true
            parameters:
                logging_collector: 'on'
                log_min_duration_statement: 500
                log_line_prefix: '%t [%p]: '
                log_checkpoints: 'on'
                log_connections: 'off'
                log_disconnections: 'off'
                log_replication_commands: 'on'
                log_statement: ddl
                log_lock_waits: 'on'
                log_temp_files: 0
                log_autovacuum_min_duration: 2s
                log_error_verbosity: verbose
                log_truncate_on_rotation: 'on'
                log_rotation_size: '10000'
                log_filename: 'bmn-postgresql-%H%M.log'
                log_rotation_age: 60
                log_timezone: 'localtime'
                deadlock_timeout: 500ms
                max_wal_senders: 20
                max_replication_slots: 15
                hot_standby: 'on'
                wal_level: logical
                wal_log_hints: 'on'
                wal_buffers : 16MB
                wal_writer_delay: 20ms
                autovacuum_naptime: 1min
                autovacuum_vacuum_scale_factor: 0.09
                autovacuum_analyze_scale_factor: 0.05
                autovacuum_vacuum_cost_delay: -1
                autovacuum_vacuum_cost_limit: -1
                commit_delay: 30
                hot_standby_feedback: 'on'
                shared_buffers : 3GB
                effective_cache_size : 9GB
                maintenance_work_mem : 768MB
                default_statistics_target : 100
                random_page_cost : 1.1
                effective_io_concurrency : 200
                max_connections: 300
                superuser_reserved_connections: 10
                work_mem : 2621kB
                min_wal_size : 1GB
                max_wal_size : 4GB
                checkpoint_timeout: 15min
                max_logical_replication_workers: 6
                max_sync_workers_per_subscription: 6
                max_worker_processes : 10
                max_parallel_workers_per_gather : 4
                max_parallel_workers : 10
                max_parallel_maintenance_workers : 4
                track_io_timing : 'on'
                track_activity_query_size : '8192'
                track_functions: all
                pg_stat_statements.track : 'all'
                pg_stat_statements.max: 10000
                pg_stat_monitor.pgsm_query_max_len : '2048'
                idle_in_transaction_session_timeout: 10min
                archive_mode: 'on'
                archive_command: 'pgbackrest --stanza=test archive-push %p'
            recovery_conf:
               recovery_target_timeline: latest
               restore_command: pgbackrest --stanza=test archive-get %f "%p"

....
postgresql:
    create_replica_methods:
        - basebackup
        - pgbackrest
    basebackup:
        - max-rate: '200M'
        - checkpoint: fast
        - status-interval: 2s
        - progress
    pgbackrest:
        - command: pgbackrest --stanza=test restore --delta --link -all
        - keep_data: True
        - no_params: True
    recovery.conf:
        - recover_target_timeline: latest
        - restore_command: pgbackrest --stanza=test archive-get %f "%p"
__
after sudo systemctl start patroni 
i have this logs from systemctl status patroni:
LOG:  invalid checkpoint record
FATAL:  could not locate required checkpoint
HINT:  If you are restoring from a backup, touch "/var/lib/postgresql/13/main/recovery.signal"  and add required recovery options.

and now when i see my /var/lib/postgresql/13/main directory i dont have recovery.signal file anymore and i have a standby.signal file which is empty too!
here  is my postgresql logs which shows my database isn't able to start  

2022-07-12 16:30:46 +0430 [23356]: FATAL:  57P03: the database system is starting up
2022-07-12 16:30:46 +0430 [23356]: LOCATION:  ProcessStartupPacket, postmaster.c:2341
2022-07-12 16:30:46 +0430 [22714]: LOG:  00000: received fast shutdown request

it would be nice if someone help me with this

**Comment by CyberDem0n** [comment]
You have to use custom bootstrap: https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#bootstrap

I.e., Patroni should be configured to call pgbackrest.

**Comment by CyberDem0n** [comment]
But, Patroni will not do it if $PGDATA isn't empty.
As a workaround, you can wrap pgbackrest into a shell script that will do some directory renaming.

**Comment by msrd4** [comment]
> But, Patroni will not do it if $PGDATA isn't empty. As a workaround, you can wrap pgbackrest into a shell script that will do some directory renaming.

what do you mean by directory rename?

**Comment by msrd4** [comment]
> > i used that doccuments and this is my bootstrap_script:
> > i used: sudo -u postgres pgbackrest --stanza=test --log-level-console=detail restore
> 
> Since PGDATA isn't empty, Patroni will not call bootstrap command

i skiped the part which i manually restore from pgbackrest and my PGDATA was empty , patroni started but did not restore my backup it was empty and still it didn't call bootstrap command

**Comment by CyberDem0n** [comment]
> patroni started but did not restore my backup it was empty and still patroni didn't call bootstrap command

Because according to the DCS the cluster is already initialized (the /initialize key is present)

**Comment by msrd4** [comment]
> > patroni started but did not restore my backup it was empty and still patroni didn't call bootstrap command
> 
> Because according to the DCS the cluster is already initialized (the /initialize key is present)

no i destroyed the cluster and created that again

**Comment by msrd4** [comment]
> > > patroni started but did not restore my backup it was empty and still patroni didn't call bootstrap command
> > 
> > 
> > Because according to the DCS the cluster is already initialized (the /initialize key is present)
> 
> no i destroyed the cluster and created that again
it started as a new cluster

**Comment by CyberDem0n** [comment]
And still you didn't provide any logs.

**Comment by msrd4** [comment]
> And still you didn't provide any logs.

which log file should i look into? my patroni log is on syslog.log i can provide that

**Comment by CyberDem0n** [comment]
Have you seen the issue template (which you apparently ignored)?

**Comment by msrd4** [comment]
> Have you seen the issue template (which you apparently ignored)?

not gonna lie i opened a blank issue but here is my log after start patroni for the first time after destroyed it:

Jul 12 17:42:33 -bckup01 systemd[1]: patroni.service: Succeeded.
Jul 12 17:43:55 -bckup01 patroni[61133]: 2022-07-12 17:43:55,715 INFO: Selected new etcd server http://10.1.10.89:2379
Jul 12 17:43:55 -bckup01 patroni[61133]: 2022-07-12 17:43:55,732 INFO: No PostgreSQL configuration items changed, nothing to reload.
Jul 12 17:43:55 -bckup01 patroni[61133]: 2022-07-12 17:43:55,744 INFO: Lock owner: None; I am bckup01-n01
**Jul 12 17:43:55 -bckup01 patroni[61133]: 2022-07-12 17:43:55,759 INFO: trying to bootstrap a new cluster**
Jul 12 17:43:55 -bckup01 patroni[61157]: The files belonging to this database system will be owned by user "postgres".
Jul 12 17:43:55 -bckup01 patroni[61157]: This user must also own the server process.
Jul 12 17:43:55 -bckup01 patroni[61157]: The database cluster will be initialized with locale "en_US.UTF-8".
Jul 12 17:43:55 -bckup01 patroni[61157]: The default text search configuration will be set to "english".
Jul 12 17:43:55 -bckup01 patroni[61157]: Data page checksums are enabled.
Jul 12 17:43:55 -bckup01 patroni[61157]: fixing permissions on existing directory /var/lib/postgresql/13/main ... ok
Jul 12 17:43:55 -bckup01 patroni[61157]: creating subdirectories ... ok
Jul 12 17:43:55 -bckup01 patroni[61157]: selecting dynamic shared memory implementation ... posix
Jul 12 17:43:55 -bckup01 patroni[61157]: selecting default max_connections ... 100
Jul 12 17:43:55 -bckup01 patroni[61157]: selecting default shared_buffers ... 128MB
Jul 12 17:43:55 -bckup01 patroni[61157]: selecting default time zone ... Asia/Tehran
Jul 12 17:43:55 -bckup01 patroni[61157]: creating configuration files ... ok
**Jul 12 17:43:56 -bckup01 patroni[61157]: running bootstrap script ... ok**
Jul 12 17:43:57 -bckup01 patroni[61157]: performing post-bootstrap initialization ... ok
Jul 12 17:43:57 -bckup01 patroni[61157]: syncing data to disk ... ok
Jul 12 17:43:57 -bckup01 patroni[61157]: initdb: warning: enabling "trust" authentication for local connections
Jul 12 17:43:57 -bckup01 patroni[61157]: You can change this by editing pg_hba.conf or using the option -A, or
Jul 12 17:43:57 -bckup01 patroni[61157]: --auth-local and --auth-host, the next time you run initdb.
Jul 12 17:43:57 -bckup01 patroni[61157]: Success. You can now start the database server using:
Jul 12 17:43:57 -bckup01 patroni[61157]:     /usr/lib/postgresql/13/bin/pg_ctl -D /var/lib/postgresql/13/main -l logfile start
Jul 12 17:43:57 -bckup01 patroni[61133]: 2022-07-12 17:43:57,869 INFO: postmaster pid=61179
Jul 12 17:43:57 -bckup01 patroni[61180]: localhost:5432 - no response
Jul 12 17:43:58 -bckup01 patroni[61179]: 2022-07-12 17:43:58 +0430 [61179]: LOG:  00000: redirecting log output to logging collector process
Jul 12 17:43:58 -bckup01 patroni[61179]: 2022-07-12 17:43:58 +0430 [61179]: HINT:  Future log output will appear in directory "log".
Jul 12 17:43:58 -bckup01 patroni[61179]: 2022-07-12 17:43:58 +0430 [61179]: LOCATION:  SysLogger_Start, syslogger.c:671
Jul 12 17:43:58 -bckup01 patroni[61192]: localhost:5432 - accepting connections
Jul 12 17:43:58 -bckup01 patroni[61197]: localhost:5432 - accepting connections
Jul 12 17:43:58 -bckup01 patroni[61133]: 2022-07-12 17:43:58,991 INFO: establishing a new patroni connection to the postgres cluster
Jul 12 17:43:59 -bckup01 patroni[61133]: 2022-07-12 17:43:59,003 INFO: running post_bootstrap
Jul 12 17:43:59 -bckup01 patroni[61133]: 2022-07-12 17:43:59,041 INFO: Software Watchdog activated with 25 second timeout, timing slack 15 seconds
Jul 12 17:43:59 -bckup01 patroni[61133]: 2022-07-12 17:43:59,143 INFO: initialized a new cluster
Jul 12 17:43:59 -bckup01 patroni[61133]: 2022-07-12 17:43:59,221 INFO: no action. I am (bckup01-n01), the leader with the lock

i dont get the line which says bootstrap script executed successfully 
maybe i should change y script

**Comment by CyberDem0n** [comment]
>i dont get the line which says bootstrap script executed successfully

This is the line from `initdb` logs.
That is, Patroni is configured to run initdb, not custom bootstrap.

**Comment by msrd4** [comment]
> > i dont get the line which says bootstrap script executed successfully
> 
> This is the line from `initdb` logs. That is, Patroni is configured to run initdb, not custom bootstrap.
it might sounds stupid but
if i change it only to pgbackrest method
does my cluster try to restore my data after every os reboot or systemd restart?
if yes wouldn't that cause me loose of data?

**Comment by CyberDem0n** [comment]
As I already said, magic doesn't exist.
It works like a charm if there are no problems with the config.
