### ISSUE TITLE
Need help on few questions 

### ISSUE THREAD

**Issue by t-ushar** [zalando/patroni#2359]
Hi Team ,

I am looking to get to know more info on below few questions .

1. Which DCS is best fit for Patroni consul or etcd ?
2. Is there is limit at consul or etcd  side to hold x number of cluster information ? 
3. If we needed upgrade Patroni and  consul or etcd will this can be done online or needed outage ?
4. Post Patroni to consul connection broken by any reason and i don't want to go my primary into readonly mode is there any way i can disable it .

Thanks 
Tushar

**Comment by CyberDem0n** [comment]
> Which DCS is best fit for Patroni consul or etcd ?

etcd

> Is there is limit at consul or etcd side to hold x number of cluster information ?

I would recommend to read https://github.com/zalando/patroni/issues/2273

> If we needed upgrade Patroni and consul or etcd will this can be done online or needed outage ?

If everything is correctly configured/prepared there will be no downtime.

> Post Patroni to consul connection broken by any reason and i don't want to go my primary into readonly mode is there any way i can disable it .

No, at least not yet.
