### ISSUE TITLE
Switchover failed, details: 412, switchover is not possible: no good candidates have been found

### ISSUE THREAD

**Issue by laurentnadot45** [zalando/patroni#2362]
Hello,
Can you help me please

[root@patroni1-14 ~]# patronictl -c /etc/patroni/patroni.yml switchover --master patroni1 --candidate patroni2 --force
Current cluster topology
+ Cluster: BANZAI (7117620985695882024) ------+----+-----------+
| Member   | Host         | Role    | State   | TL | Lag in MB |
+----------+--------------+---------+---------+----+-----------+
| patroni1 | 192.168.1.73 | Leader  | running |  7 |           |
| patroni2 | 192.168.1.74 | Replica | running |  7 |         0 |
+----------+--------------+---------+---------+----+-----------+
Switchover failed, details: 412, switchover is not possible: no good candidates have been found

[postgres@patroni1-14 ~]$ patronictl  -c /etc/patroni/patroni.yml switchover
Master [patroni1]: patroni1
Candidate ['patroni2'] []: patroni2
When should the switchover take place (e.g. 2022-07-19T10:26 )  [now]: now
Current cluster topology
+ Cluster: BANZAI (7117620985695882024) ------+----+-----------+
| Member   | Host         | Role    | State   | TL | Lag in MB |
+----------+--------------+---------+---------+----+-----------+
| patroni1 | 192.168.1.73 | Leader  | running |  7 |           |
| patroni2 | 192.168.1.74 | Replica | running |  7 |         0 |
+----------+--------------+---------+---------+----+-----------+
Are you sure you want to switchover cluster BANZAI, demoting current master patroni1? [y/N]: y
Switchover failed, details: 412, switchover is not possible: no good candidates have been found

[root@patroni2-14 ~]# patronictl -c /etc/patroni/patroni.yml switchover --master patroni1 --candidate patroni2 --force
Current cluster topology
+ Cluster: BANZAI (7117620985695882024) ------+----+-----------+
| Member   | Host         | Role    | State   | TL | Lag in MB |
+----------+--------------+---------+---------+----+-----------+
| patroni1 | 192.168.1.73 | Leader  | running |  7 |           |
| patroni2 | 192.168.1.74 | Replica | running |  7 |         0 |
+----------+--------------+---------+---------+----+-----------+
Switchover failed, details: 412, switchover is not possible: no good candidates have been found

Rocky Linux release 8.6 (Green Obsidian)
patroni 2.1.1
psql (14.4)
etcd Version: 3.5.0
Git SHA: 946a5a6f2
Go Version: go1.16.3
Go OS/Arch: linux/amd64

[postgres@patroni1-14~]$ cat /etc/patroni/patroni.yml
scope: BANZAI
name: patroni1

restapi:
  listen: 0.0.0.0:8008
  connect_address: 192.168.1.73:8008

log:
  level: INFO
  dir: /var/log/postgresql/patroni

etcd3:
  hosts:
  - 192.168.1.70:2379
  - 192.168.1.71:2379
  - 192.168.1.72:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
         archive_mode: true
         archive_command: 'test ! -f "/var/lib/pgsql/TEST1/archives/%f" && cp "%p" "/var/lib/pgsql/TEST1/archives/%f"'
         wal_level: replica
         wal_log_hints: 'on'
         max_wal_senders: 10
         hot_standby: on
         password_encryption: 'scram-sha-256'
         log_directory: '/var/log/postgresql/TEST1'
         log_filename: 'TEST1.log'
         log_file_mode: 0640
         log_truncate_on_rotation: off
         log_rotation_age: 0
         syslog_facility: 'local3'
         log_checkpoints: on
         log_line_prefix: 'user=%u,db=%d,time=%t,pid=%p'
         log_lock_waits: on
         log_statement: 'ddl'
         log_temp_files: 0
         idle_in_transaction_session_timeout: 604800000
         lc_messages: 'C'
         lc_monetary: 'C'
         lc_numeric: 'C'
         lc_time: 'C'
         default_text_search_config: 'pg_catalog.french'
         include_dir: 'conf.d'
         shared_preload_libraries: 'pg_stat_statements,auto_explain'

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - local   all             postgres                               peer
  - local   all             all                                    scram-sha-256
  - host replication replicator all scram-sha-256
  - host all all all scram-sha-256
  users:
    postgres:
      password: admin
      options:
        - createrole
        - createdb
    replicator:
      password: admin
      options:
        - replication

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 192.168.1.73:5432
  data_dir: /var/lib/pgsql/TEST1/data
  bin_dir: /usr/pgsql-14/bin
  authentication:
    replication:
      username: replicator
      password: admin
    superuser:
      username: postgres
      password: admin
    rewind:
      username: rewind_user
      password: rewind_password
  parameters:
    unix_socket_directories: '/var/run/postgresql'

watchdog:
    mode: required # Allowed values: off, automatic, required
    device: /dev/watchdog
    safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

[postgres@patroni1-14 ~]$ patronictl  -c /etc/patroni/patroni.yml show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: test ! -f "/var/lib/pgsql/TEST1/archives/%f" && cp "%p" "/var/lib/pgsql/TEST1/archives/%f"
    archive_mode: true
    checkpoint_completion_target: 0.9
    default_statistics_target: 100
    default_text_search_config: pg_catalog.french
    effective_cache_size: 3GB
    effective_io_concurrency: 200
    hot_standby: true
    idle_in_transaction_session_timeout: 604800000
    include_dir: conf.d
    lc_messages: C
    lc_monetary: C
    lc_numeric: C
    lc_time: C
    log_checkpoints: true
    log_directory: /var/log/postgresql/TEST1
    log_file_mode: 416
    log_filename: TEST1.log
    log_line_prefix: user=%u,db=%d,time=%t,pid=%p
    log_lock_waits: true
    log_min_duration_statement: 3000
    log_rotation_age: 0
    log_statement: ddl
    log_temp_files: 0
    log_timezone: Europe/Paris
    log_truncate_on_rotation: false
    logging_collector: true
    maintenance_work_mem: 256MB
    max_connections: 30
    max_parallel_maintenance_workers: 2
    max_parallel_workers: 4
    max_parallel_workers_per_gather: 2
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: 8GB
    max_worker_processes: 4
    min_wal_size: 2GB
    password_encryption: scram-sha-256
    random_page_cost: 1.1
    shared_buffers: 1GB
    shared_preload_libraries: pg_stat_statements,auto_explain
    syslog_facility: local3
    timezone: Europe/Paris
    wal_buffers: 16MB
    wal_level: replica
    wal_log_hints: 'on'
    work_mem: 26214kB
  pg_hba:
  - local   all             postgres                               peer
  - local   all             all                                    scram-sha-256
  - host    all             all             127.0.0.1/32            scram-sha-256
  - host replication replicator 127.0.0.1/32 scram-sha-256
  - host replication replicator 192.168.1.73/32 scram-sha-256
  - host replication replicator 192.168.1.74/32 scram-sha-256
  - host dvdrental dvdrental 192.168.1.43/32 scram-sha-256
  - host all rewind_user 192.168.1.73/24 scram-sha-256
  - host all rewind_user 192.168.1.74/24 scram-sha-256
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30

patroni1 :

2022-07-19 09:26:25,577 INFO: no action. I am (patroni1) the leader with the lock
2022-07-19 09:26:35,577 INFO: no action. I am (patroni1) the leader with the lock
2022-07-19 09:26:39,240 INFO: received switchover request with leader=patroni1 candidate=patroni2 scheduled_at=None
2022-07-19 09:26:39,244 INFO: Got response from patroni2 http://192.168.1.74:8008/patroni: {"state": "running", "postmaster_start_time": "2022-07-18 23:19:45.200737+02:00", "role": "replica", "server_version": 140004, "cluster_unlocked": false, "xlog": {"received_location": 18589155944, "replayed_location": 18589155944, "replayed_timestamp": null, "paused": false}, "timeline": 7, "database_system_identifier": "7117620985695882024", "patroni": {"version": "2.1.1", "scope": "BANZAI"}, "watchdog_failed": true}
2022-07-19 09:26:45,577 INFO: no action. I am (patroni1) the leader with the lock

patroni2 :
2022-07-19 09:30:06,278 INFO: no action. I am a secondary (patroni2) and following a leader (patroni1)
2022-07-19 09:30:16,321 INFO: no action. I am a secondary (patroni2) and following a leader (patroni1)
2022-07-19 09:30:26,278 INFO: no action. I am a secondary (patroni2) and following a leader (patroni1)
2022-07-19 09:30:36,321 INFO: no action. I am a secondary (patroni2) and following a leader (patroni1)
2022-07-19 09:30:46,278 INFO: no action. I am a secondary (patroni2) and following a leader (patroni1)
2022-07-19 09:30:56,321 INFO: no action. I am a secondary (patroni2) and following a leader (patroni1)
2022-07-19 09:31:06,278 INFO: no action. I am a secondary (patroni2) and following a leader (patroni1)

Log Postgres1:
no mistake

Log Postgres2:
no mistake

Thank you very much

Best regards

Laurent

**Comment by CyberDem0n** [comment]
> watchdog:
  **mode: required** # Allowed values: off, automatic, required

> 2022-07-19 09:26:39,244 INFO: Got response from patroni2 http://192.168.1.74:8008/patroni: {"state": "running", "postmaster_start_time": "2022-07-18 23:19:45.200737+02:00", "role": "replica", "server_version": 140004, "cluster_unlocked": false, "xlog": {"received_location": 18589155944, "replayed_location": 18589155944, "replayed_timestamp": null, "paused": false}, "timeline": 7, "database_system_identifier": "7117620985695882024", "patroni": {"version": "2.1.1", "scope": "BANZAI"}, **"watchdog_failed": true**}

Everything works as expected: https://patroni.readthedocs.io/en/latest/watchdog.html

> Patroni will try to activate the watchdog before promoting PostgreSQL to master. **If watchdog activation fails and watchdog mode is required then the node will refuse to become master**. When deciding to participate in leader election Patroni will also check that watchdog configuration will allow it to become leader at all. After demoting PostgreSQL (for example due to a manual failover) Patroni will disable the watchdog again. Watchdog will also be disabled while Patroni is in paused state.

**Comment by laurentnadot45** [comment]
Hello,
Thanks you very much.
I've turned off SELinux   SELINUX=disabled
Best regards.
