### ISSUE TITLE
Replication network different than control network

### ISSUE THREAD

**Issue by romanogit** [zalando/patroni#2367]
Patroni defines `connect_address` as the address to use by external applications. However, this address is also used to internal communication and replication.

It would be nice to be able to split these address in:
- connect_address: external address connection - useful for confd and other applications willing to query DCS
- control_address: internal connection and patroni access to postgres
- replication_address: replication address - used in postgresql replication

There could be a validation to guarantee all these address are reachible and defined in the `listen` field

**Comment by CyberDem0n** [comment]
`postgresql.use_unix_socket` and `postgresql.use_unix_socket_repl` already solving the "problem" of the "control_address"

**Comment by martinmarques** [comment]
Sorry for coming in so late, but I was researching how to separate application connections from replication connections in a Patroni cluster and bumped into this. 
How can `postgresql.use_unix_socket` and `postgresql.use_unix_socket_repl`help with that? (unless I misunderstood the OPs initial request)
What I'm looking for is to define different NIC addresses that the node has for application and replication connections. In essence, replication between Patroni nodes should happen through address XXX, while the Postgres service should be listening and receiving connections through address YYY.
I'm not able to match that with the use_unix_socket options.
