### ISSUE TITLE
Switchover failed, details: 503, Switchover status unknown

### ISSUE THREAD

**Issue by Aleksey-10081967** [zalando/patroni#2376]
[log-patroni-pezbdb-n1.txt](https://github.com/zalando/patroni/files/9251596/log-patroni-pezbdb-n1.txt)
[log-patroni-pezbdb-n2.txt](https://github.com/zalando/patroni/files/9251576/log-patroni-pezbdb-n2.txt)
Hi.
When executing the switchover, I encountered this behavior:
[postgres@pezbdb-n1 ~]$ patronictl -c /etc/patroni/patroni.yml switchover zabbix-eivi-patroni-cluster
Master [zabbix-patroni02]:
Candidate ['zabbix-patroni01'] []:
When should the switchover take place (e.g. 2022-08-02T15:24 )  [now]:
Current cluster topology
+------------------+-----------------------------+---------+---------+----+-----------+
| Member               | Host                                  | Role        | State      |  TL     Lag in MB |
+ Cluster: zabbix-eivi-patroni-cluster (7073402546076050600) --------+----+-----------+
| zabbix-patroni01 | pezbdb-n1					 | Replica | running | 10 |         0 |
| zabbix-patroni02 | pezbdb-n2					 | Leader  | running | 10 |           |
+------------------+-----------------------------+---------+---------+----+-----------+
Are you sure you want to switchover cluster zabbix-eivi-patroni-cluster, demoting current master zabbix-patroni02? [y/N]: y
After 40 seconds the following message appears
**Switchover failed, details: 503, Switchover status unknown**
After 1 - 1.5 minutes while executing the command patronictl -c /etc/patroni/patroni.yml list displays information about the change of leader.
[postgres@pezbdb-n1 ~]$ patronictl -c /etc/patroni/patroni.yml list
+------------------+-----------------------------+---------+---------+----+-----------+
| Member           | Host                        | Role    | State   | TL | Lag in MB |
+ Cluster: zabbix-eivi-patroni-cluster (7073402546076050600) --------+----+-----------+
| zabbix-patroni01 | 		pezbdb-n1			 | Leader  | running |  11|           |
| zabbix-patroni02 | 		pezbdb-n2			 | Replica | running |  11|         0 |
+------------------+-----------------------------+---------+---------+----+-----------+

***Environment**
- Patroni version: 2.4.1
- PostgreSQL version: 13.6
- DCS (and its version): etcdctl version: 3.5.4 API version: 3.5
 

**Patroni configuration file**

name: zabbix-patroni01
namespace: /zabbix-eivi/
scope: zabbix-eivi-patroni-cluster
restapi:
  listen: 0.0.0.0:8008
  connect_address: pezbdb-n1.tn.tngrp.ru:8008
  authentication:
    username: patroni
    password: 26GLV4rLFcJCmJ8eZgyp8LiU9jdHKqpTP
etcd3:
  hosts: 10.5.112.211:2379,10.5.112.212:2379,10.5.112.237:2379
  username: root
  password: passw0rd
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
  postgresql:
     use_pg_rewind: true
     use_slots: true
     parameters:
       wal_level: replica
       hot_standby: "on"
       wal_keep_segments: 8
       max_wal_senders: 5
       max_replication_slots: 5
       checkpoint_timeout: 30
  initdb:
   - encoding: UTF8
   - data-checksums
   - locale: en_US.UTF-8
  pg_hba:
   - local all all trust
   - host all all 10.5.112.211/32 trust
   - host all all 10.5.112.212/32 trust
   - host all all 0.0.0.0/0 md5
   - host replication replicator 0.0.0.0/0 md5
   - host replication replicator 127.0.0.1/32 md5
postgresql:
  listen: 0.0.0.0:5432
  connect_address: pezbdb-n1.tn.tngrp.ru:5432
  config_dir: /pgdata/13/data
  bin_dir: /usr/pgsql-13/bin
  data_dir: /pgdata/13/data
  pgpass: /tmp/pgpass
  authentication:
    superuser:
      username: postgres
      password: passw0rd
    replication:
      username: replicator
      password: passw0rd
    rewind:
      username: rewind_user
      password: passw0rd
  parameters:
    unix_socket_directories: '/var/run/postgresql/'
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

**patronictl show-config**
[postgres@pezbdb-n1 ~]$ patronictl -c /etc/patroni/patroni.yml show-config
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  hot_standby: 'on'
  max_replication_slots: 5
  max_wal_senders: 5
  parameters:
    archive_mode: 'off'
    checkpoint_completion_target: 0.9
    checkpoint_timeout: 15min
    effective_cache_size: 16GB
    lc_messages: en_US.UTF-8
    listen_addresses: '*'
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_directory: /pgdata/log
    log_disconnections: 'on'
    log_duration: 'off'
    log_file_mode: 384
    log_filename: postgresql-%a.log
    log_line_prefix: '%m [%p]: [%l-1] db=%d,tx=%x,user=%u,app=%a,client=%h'
    log_lock_waits: 'on'
    log_min_duration_statement: 100
    log_min_error_statement: warning
    log_min_messages: info
    log_replication_commands: 'on'
    log_rotation_age: 1d
    log_rotation_size: 0
    log_statement: none
    log_temp_files: 0
    log_truncate_on_rotation: 'off'
    logging_collector: 'on'
    maintenance_work_mem: 1638MB
    max_connections: 100
    max_wal_size: 20GB
    min_wal_size: 5GB
    shared_buffers: 8192MB
    shared_preload_libraries: timescaledb
    timescaledb.telemetry_level: 'off'
    work_mem: 82MB
  pg_hba:
  - local all postgres peer
  - local all all md5
  - host all all 127.0.0.1/32 md5
  - host all all      ::1/128 md5
  - host all all 0.0.0.0/0 md5
  - host replication replicator 0.0.0.0/0 md5
  - host replication replicator 127.0.0.1/32 md5
  use_pg_rewind: true
  use_slots: true
  wal_level: replica
retry_timeout: 10
synchronous_mode: true
synchronous_mode_restrict: false
ttl: 30

**Have you checked PostgreSQL logs?**
Below are the logs in the process of switching from [log-patroni-pezbdb-n1.txt](https://github.com/zalando/patroni/files/9251566/log-patroni-pezbdb-n1.txt) to pezbdb-n2. 
In this case, the reverse switching worked without an error message. Although previously the error message occurred every time I switched
logs patroni attach.

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.
Watched issue. There is a similar open issue.  https://github.com/zalando/patroni/issues/743

**Comment by CyberDem0n** [comment]
The switchover isn't an instant operation. It involves the shutdown of the old primary which could take some time.
If switchover started successfully but didn't finish after `2*loop_wait` seconds you get the message `Switchover status unknown`.

**Comment by Aleksey-10081967** [comment]
Thanks for the answer. Now it is clear

**Comment by skunkworker** [comment]
> The switchover isn't an instant operation. It involves the shutdown of the old primary which could take some time. If switchover started successfully but didn't finish after `2*loop_wait` seconds you get the message `Switchover status unknown`.

If the cluster is paused, should running a `switchover` or `failover` always return a `503`?
