### ISSUE TITLE
patronictl restart behavior

### ISSUE THREAD

**Issue by yinan8128** [zalando/patroni#2385]
Hello,

Below url shows that **patronictl restart** _restart all nodes in the cluster without downtime_ and _manage auto switchover during the process_. But we tested in our env, the restart is rolling restart(checkpoint, terminate connections and startup) but there is no switchover happen, searched "restart" in patroni docs, also doesn't mention switchover. What's patronictl restart behavior please? Will have switchover or not? Thanks

https://bootvar.com/useful-patroni-commands/
patronictl restart - It will restart all nodes in the postgres cluster. Sometimes you need to restart all nodes in the cluster without downtime, you can use this to avoid downtime. Patroni will manage auto switchover during the process.

**Environment**
- Patroni version: 2.0.1
- PostgreSQL version: 11.11
- DCS (and its version): consul 1.2.2

**patronictl restart**
patronictl -c /etc/patroni/postgresql.yml restart pgcluster11
+ Cluster: pgcluster11 (7097358165010485275) --+--------------+---------+----+-----------+
| Member                        | Host         | Role         | State   | TL | Lag in MB |
+-------------------------------+--------------+--------------+---------+----+-----------+
| patroni-cluster-vm01 | 10.35.43.114 | Leader       | running | 15 |           |
| patroni-cluster-vm02 | 10.35.43.113 | Sync Standby | running | 15 |         0 |
| patroni-cluster-vm03 | 10.35.43.112 | Replica      | running | 15 |         0 |
+-------------------------------+--------------+--------------+---------+----+-----------+
When should the restart take place (e.g. 2022-08-16T01:58)  [now]:
Are you sure you want to restart members patroni-cluster-vm01, patroni-cluster-vm02, patroni-cluster-vm03? [y/N]: y
Restart if the PostgreSQL version is less than provided (e.g. 9.5.2)  []:
Success: restart on member patroni-cluster-vm01
Success: restart on member patroni-cluster-vm02
Success: restart on member patroni-cluster-vm03

**patroni-cluster-vm01 Patroni logs**
Aug 16 00:58:44 patroni-cluster-vm01.lh patroni[5574]: {"time": "2022-08-16 00:58:44,824", "name": "patroni", "process": 5574, "thread": 140383637845824, "level": "INFO", "message": "no action.  i am the leader with the lock"}
Aug 16 00:58:45 patroni-cluster-vm01.lh patroni[5574]: {"time": "2022-08-16 00:58:45,792", "name": "patroni.ha", "process": 5574, "thread": 140383297771264, "level": "INFO", "message": "Lock owner: patroni-cluster-vm01; I am patroni-cluster-vm01"}
Aug 16 00:58:54 patroni-cluster-vm01.lh patroni[5574]: {"time": "2022-08-16 00:58:54,807", "name": "patroni.ha", "process": 5574, "thread": 140383637845824, "level": "INFO", "message": "Lock owner: patroni-cluster-vm01; I am patroni-cluster-vm01"}
Aug 16 00:58:54 patroni-cluster-vm01.lh patroni[5574]: {"time": "2022-08-16 00:58:54,816", "name": "patroni", "process": 5574, "thread": 140383637845824, "level": "INFO", "message": "updated leader lock during restart"}
Aug 16 00:58:59 patroni-cluster-vm01.lh patroni[5574]: {"time": "2022-08-16 00:58:59,071", "name": "patroni.postgresql.connection", "process": 5574, "thread": 140383297771264, "level": "INFO", "message": "closed patroni connection to the postgresql cluster"}
Aug 16 00:58:59 patroni-cluster-vm01.lh patroni[5574]: {"time": "2022-08-16 00:58:59,316", "name": "patroni.postgresql.postmaster", "process": 5574, "thread": 140383297771264, "level": "INFO", "message": "postmaster pid=32688"}
Aug 16 00:58:59 patroni-cluster-vm01.lh patroni[5574]: [2022-08-16 00:58:59.317 UTC] p=32688:1@ c=@/: LOG:  Auto detecting pg_stat_kcache.linux_hz parameter...
Aug 16 00:58:59 patroni-cluster-vm01.lh patroni[5574]: [2022-08-16 00:58:59.321 UTC] p=32688:2@ c=@/: LOG:  pg_stat_kcache.linux_hz is set to 90909
Aug 16 00:58:59 patroni-cluster-vm01.lh patroni[5574]: localhost:5432 - no response
Aug 16 00:58:59 patroni-cluster-vm01.lh patroni[5574]: [2022-08-16 00:58:59.324 UTC] p=32688:3@ c=@/: LOG:  listening on IPv4 address "0.0.0.0", port 5432
Aug 16 00:58:59 patroni-cluster-vm01.lh patroni[5574]: [2022-08-16 00:58:59.324 UTC] p=32688:4@ c=@/: LOG:  listening on IPv6 address "::", port 5432
Aug 16 00:58:59 patroni-cluster-vm01.lh patroni[5574]: [2022-08-16 00:58:59.325 UTC] p=32688:5@ c=@/: LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
Aug 16 00:58:59 patroni-cluster-vm01.lh patroni[5574]: [2022-08-16 00:58:59.664 UTC] p=32688:6@ c=@/: LOG:  redirecting log output to logging collector process
Aug 16 00:58:59 patroni-cluster-vm01.lh patroni[5574]: [2022-08-16 00:58:59.664 UTC] p=32688:7@ c=@/: HINT:  Future log output will appear in directory "/var/log/postgresql".
Aug 16 00:59:00 patroni-cluster-vm01.lh patroni[5574]: localhost:5432 - accepting connections
Aug 16 00:59:00 patroni-cluster-vm01.lh patroni[5574]: localhost:5432 - accepting connections
Aug 16 00:59:00 patroni-cluster-vm01.lh patroni[5574]: {"time": "2022-08-16 00:59:00,360", "name": "patroni.ha", "process": 5574, "thread": 140383637845824, "level": "INFO", "message": "Lock owner: patroni-cluster-vm01; I am patroni-cluster-vm01"}
Aug 16 00:59:00 patroni-cluster-vm01.lh patroni[5574]: {"time": "2022-08-16 00:59:00,360", "name": "patroni.postgresql.connection", "process": 5574, "thread": 140383637845824, "level": "INFO", "message": "establishing a new patroni connection to the postgres cluster"}
Aug 16 00:59:00 patroni-cluster-vm01.lh patroni[5574]: {"time": "2022-08-16 00:59:00,376", "name": "patroni.ha", "process": 5574, "thread": 140383637845824, "level": "INFO", "message": "Updating synchronous privilege temporarily from ['patroni-cluster-vm02'] to []"}
Aug 16 00:59:00 patroni-cluster-vm01.lh patroni[5574]: {"time": "2022-08-16 00:59:00,383", "name": "patroni.ha", "process": 5574, "thread": 140383637845824, "level": "INFO", "message": "Assigning synchronous standby status to []"}
Aug 16 00:59:00 patroni-cluster-vm01.lh patroni[5574]: server signaled
Aug 16 00:59:00 patroni-cluster-vm01.lh patroni[5574]: {"time": "2022-08-16 00:59:00,399", "name": "patroni.dcs.consul", "process": 5574, "thread": 140383637845824, "level": "INFO", "message": "Register service pgcluster11, params {'service_id': 'pgcluster11/patroni-cluster-vm01', 'address': '10.35.43.114', 'port': 5432, 'check': {'http': 'http://10.35.43.114:8008/master', 'interval': '5s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['master']}"}
Aug 16 00:59:00 patroni-cluster-vm01.lh patroni[5574]: {"time": "2022-08-16 00:59:00,435", "name": "patroni", "process": 5574, "thread": 140383637845824, "level": "INFO", "message": "no action.  i am the leader with the lock"}

**patroni-cluster-vm01 PostgreSQL logs**
[2022-08-16 00:58:55.818 UTC] p=31209:1@164/0 c=postgres@::1/postgres:Patroni LOG:  duration: 10013.888 ms  statement: CHECKPOINT
[2022-08-16 00:58:55.818 UTC] p=3983:12@ c=@/: LOG:  received fast shutdown request
[2022-08-16 00:58:55.820 UTC] p=3983:13@ c=@/: LOG:  aborting any active transactions
[2022-08-16 00:58:55.820 UTC] p=31261:1@267/0 c=aaa@10.35.43.128/test_aaa:[unknown] FATAL:  terminating connection due to administrator command
...
[2022-08-16 00:58:59.039 UTC] p=3983:15@ c=@/: LOG:  database system is shut down
[2022-08-16 00:58:59.667 UTC] p=32691:1@ c=@/: LOG:  database system was shut down at 2022-08-16 00:58:56 UTC
[2022-08-16 00:58:59.668 UTC] p=32692:1@ c=aaa@10.35.43.124/test_aaa:[unknown] FATAL:  the database system is starting up
...
[2022-08-16 00:58:59.684 UTC] p=32688:8@ c=@/: LOG:  database system is ready to accept connections

**Comment by CyberDem0n** [comment]
> Below url shows that patronictl restart restart all nodes in the cluster without downtime and manage auto switchover during the process. But we tested in our env, the restart is rolling restart(checkpoint, terminate connections and startup) but there is no switchover happen, searched "restart" in patroni docs, also doesn't mention switchover. What's patronictl restart behavior please? Will have switchover or not? Thanks

> https://bootvar.com/useful-patroni-commands/
patronictl restart - It will restart all nodes in the postgres cluster. Sometimes you need to restart all nodes in the cluster without downtime, you can use this to avoid downtime. Patroni will manage auto switchover during the process.

You should address the question to whoever wrote that article. `patronictl restart` is just for Postgres restarts.

**Comment by yinan8128** [comment]
Hello

Thank you for your reply

Do the patroni nodes always restart follow below sequence?
1st node shutdown and startup and then
2nd node shutdown and startup and then
3rd node shutdown and startup

So 2 things need to confirm please:
1. No nodes restart at the same time
2. And if always restart follow the same sequence

Thank you

**Comment by CyberDem0n** [comment]
> No nodes restart at the same time

Yes, they are restarted sequentially. But, the restart is done via the REST API call and it could happen that the call will be interrupted _before_ the start is finished. In this case patronictl continues with the next member.

> And if always restart follow the same sequence

No

**Comment by yinan8128** [comment]
Hello

Thank you for your reply

2. As our local test is follow the sequence: 1st node then 2nd node and then 3rd node
   Does it mean that some times will not start from 1st node will start from 2nd node or 3rd node? Thanks

**Comment by CyberDem0n** [comment]
order isn't guaranteed.

**Comment by yinan8128** [comment]
Hello

Thank you for your reply

What is the restart sequence logic please? Thanks
