### ISSUE TITLE
No Failover Following NFS Disk Malfunction

### ISSUE THREAD

**Issue by andrewlecuyer** [zalando/patroni#2388]
**Describe the bug**
When the `PGDATA` directory is on an NFS disk is no longer accessible/reachable (i.e., because the NFS server is no longer running and/or accessible over the network), the TTL of the leader lock expires, but a failover does not occur.

**To Reproduce**
This was detected while testing failure scenarios in a lab.

Deploy two Patroni instances in a Kubernetes cluster, with Endpoints for the cluster's DCS.  When deploying the cluster, ensure the current primary is running on NFS, with the other using another form of storage (as to not be impacted by a NFS failure).

After the cluster is fully up-and-running, with the replica successfully replicating from the primary, terminate the NFS server (e.g. shut down the host running NFS).

At this point, the leader lock expires, and the primary simply stops logging:

```bash
$ kubectl logs -c database test1-instance1-hjlg-0 | tail -n 5
2022-08-16 00:05:07,009 INFO: no action. I am (test1-instance1-hjlg-0), the leader with the lock
2022-08-16 00:05:16,980 INFO: no action. I am (test1-instance1-hjlg-0), the leader with the lock
2022-08-16 00:05:26,959 INFO: no action. I am (test1-instance1-hjlg-0), the leader with the lock
2022-08-16 00:05:37,021 INFO: no action. I am (test1-instance1-hjlg-0), the leader with the lock
2022-08-16 00:05:46,984 INFO: no action. I am (test1-instance1-hjlg-0), the leader with the lock
# Nothing else is logged after this for the duration of the test.
```

Additionally, the readniness check for the primary (implemented using the Patroni `/readiness` REST endpoint) starts to fail:

```bash
$ kubectl describe pod test-instance1-hjlg-0 | tail -1
Warning  Unhealthy         2m9s (x75 over 17m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503
```

Yet, no failover occurs:

```bash
$ kubectl exec -c database test1-instance2-g5px-0 -- patronictl list
+------------------------+-----------------------------------+---------+---------+----+-----------+
| Member                 | Host                              | Role    | State   | TL | Lag in MB |
+ Cluster: test1-ha (7129659798145802323) -------------------+---------+---------+----+-----------+
| test1-instance1-hjlg-0 | test1-instance1-hjlg-0.test1-pods | Leader  | running |  1 |           |
| test1-instance2-g5px-0 | test1-instance2-g5px-0.test1-pods | Replica | running |  1 |         0 |
+------------------------+-----------------------------------+---------+---------+----+-----------+
```

And looking at the replica (now 5+ minutes since the lock expired), I see the following repeating:

```bash
$ kubectl logs -c database test1-instance2-g5px-0 | tail -n 10
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:1050: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test1-instance1-hjlg-0.test1-pods'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
InsecureRequestWarning,
2022-08-16 00:11:27,528 INFO: Got response from test1-instance1-hjlg-0 https://test1-instance1-hjlg-0.test1-pods:8008/patroni: {"state": "running", "postmaster_start_time": "2022-08-16 00:01:54.738595+00:00", "role": "master", "server_version": 140004, "xlog": {"location": 67108864}, "timeline": 1, "cluster_unlocked": true, "dcs_last_seen": 1660003556, "database_system_identifier": "7129659798145802323", "patroni": {"version": "2.1.3", "scope": "test1-ha"}}
2022-08-16 00:11:27,613 WARNING: Master (test1-instance1-hjlg-0) is still alive
2022-08-16 00:11:27,633 INFO: following a different leader because i am not the healthiest node
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:1050: InsecureRequestWarning: Unverified HTTPS request is being made to host 'test1-instance1-hjlg-0.test1-pods'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
InsecureRequestWarning,
2022-08-16 00:11:37,515 INFO: Got response from test1-instance1-hjlg-0 https://test1-instance1-hjlg-0.test1-pods:8008/patroni: {"state": "running", "postmaster_start_time": "2022-08-16 00:01:54.738595+00:00", "role": "master", "server_version": 140004, "xlog": {"location": 67108864}, "timeline": 1, "cluster_unlocked": true, "dcs_last_seen": 1660003556, "database_system_identifier": "7129659798145802323", "patroni": {"version": "2.1.3", "scope": "test1-ha"}}
2022-08-16 00:11:37,611 WARNING: Master (test1-instance1-hjlg-0) is still alive
2022-08-16 00:11:37,642 INFO: following a different leader because i am not the healthiest node
```

**Expected behavior**
The expectation was that a failover would take place (specifically to the healthy replica) after the TTL of the leader lock expired.

**Screenshots**
N/A

**Environment**
- Patroni version: 2.1.3
- PostgreSQL version: 14.4
- DCS (and its version): Kubernetes, v1.23.1

**Patroni configuration file**
```
kubernetes:
  namespace: andrewlecuyer
  role_label: role
  scope_label: patroni
  use_endpoints: true
postgresql:
  pgpass: /tmp/.pgpass
  use_unix_socket: true
scope: test1-ha
watchdog:
  mode: 'off'
```

**patronictl show-config**
```
loop_wait: 10
postgresql:
  parameters:
    jit: 'off'
    wal_level: logical
  pg_hba:
  - local all postgres peer
  - hostssl all all all md5
  use_pg_rewind: true
  use_slots: false
ttl: 30
```

**Have you checked Patroni logs?**
See above.

**Have you checked PostgreSQL logs?**
Postgres logs were stored in the `PGDATA` directory on the NFS server that is no longer available in the scenario above.

**Have you tried to use GitHub issue search?**
This issue seems to describe a similar symptom, but does not appear to be the same: https://github.com/zalando/patroni/issues/1663.

**Additional context**
N/A

**Comment by CyberDem0n** [comment]
The problem described in the https://github.com/zalando/patroni/issues/2380 is much closer.

In fact, Patroni most likely hangs [here](https://github.com/zalando/patroni/blob/2ee09d0a66e61e9e4474be325a8da72cd4bb6e40/patroni/postgresql/__init__.py#L292) or [here](https://github.com/zalando/patroni/blob/2ee09d0a66e61e9e4474be325a8da72cd4bb6e40/patroni/utils.py#L478-L481), while performing a check that PGDATA is still there.

> # Nothing else is logged after this for the duration of the test.

As a result, the main thread hangs and the leader lock expires because of no updates. Since the main thread hangs, it also can't make a decision to demote Postgres.

> Additionally, the readniness check for the primary (implemented using the Patroni /readiness REST endpoint) starts to fail:

The /readiness endpoint fails because it knows that the leader lock has expired.

> And looking at the replica (now 5+ minutes since the lock expired), I see the following repeating:

But, the API thread on the leader is alive and Postgres is still _up_ and is able to execute some queries that don't involve reading or writing, therefore the REST API responds that the primary is still alive and no automatic failover happens.

> The expectation was that a failover would take place (specifically to the healthy replica) after the TTL of the leader lock expired.

The failover can't happen before the old primary is demoted. But, it can't be because the heartbeat thread hangs.

Usually, the [watchdog](https://patroni.readthedocs.io/en/latest/watchdog.html) helps to protect from this problem, but you can't use it with K8s.

**Comment by andrewlecuyer** [comment]
Thank you for the detailed response and the additional context around what is going on in this scenario.

Per your following comment:

> Usually, the [watchdog](https://patroni.readthedocs.io/en/latest/watchdog.html) helps to protect from this problem, but you can't use it with K8s.

This has me wondering about the role  the `/liveness` check plays here (for this test we're using the Patroni `/liveness` endpoint for the liveness probes in all Pods).  Similar to a watchdog, a failed liveness probe will result in a restart of the container in a Kubernetes environment, which would seemingly achieve the same result.

Therefore, while `/liveness` (based on what I'm seeing in the Patroni code) currently checks to see if the API server is alive/running, it seems reasonable to assume it would also check to see if the HA loop is still running (meaning the "liveness" endpoint should consider Patroni as a whole, i.e., it shouldn't be considered "alive" if the HA loop is stuck).  In this specific scenario that would result in a restart of the original primary, getting it out of it's "stuck" state so that it can be demoted, the replica can grab the leader lock and failover, etc.

Is it possible to expand check done by the `/liveness` endpoint to also take into account the HA loop?

**Comment by CyberDem0n** [comment]
> Therefore, while /liveness (based on what I'm seeing in the Patroni code) currently checks to see if the API server is alive/running

Right now `/liveness` always responds with 200. They could be [dangerous](https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html).

> Is it possible to expand check done by the /liveness endpoint to also take into account the HA loop?

Yes, but not immediately. It would require some refactoring. In certain conditions it could happen that the heartbeat loop could be busy with executing some long-running tasks and it is sort of expected that it could take longer than `loop_wait` and sometimes even longer than `ttl` for it to run (for example when pg_replication_slot_advance() is called). Despite pg_replication_slot_advance() affecting only replicas IMO the `/liveness` EP should start failing if the heartbeat loop is stuck no matter if we run as the leader or replica.
