### ISSUE TITLE
Adding an extra start parameter to Patroni

### ISSUE THREAD

**Issue by rugzok** [zalando/patroni#2392]
Hello,

as you know, Patroni is launching PostgreSQL and however i must add following parameter to starting for PostgreSQL TDE. I dont know how to do this because when i added postgresql.base.conf it and Patroni didnt detect it.

Parameter:

encryption_key_command = '/db/key/db_key.sh'

Can Patroni detect this at startup and initiate PostgreSQL TDE?

**Comment by CyberDem0n** [comment]
What exactly Patroni is supposed to detect?

If this parameter is set in the patroni.yaml (postgresql.parameters section), it will not be written to postgresql.conf because this is not a standard Postgres GUC. With postgresql.base.conf there should be no problem, whatever is put there will be applied.

**Comment by rugzok** [comment]
> What exactly Patroni is supposed to detect?
> 
> If this parameter is set in the patroni.yaml (postgresql.parameters section), it will not be written to postgresql.conf because this is not a standard Postgres GUC. With postgresql.base.conf there should be no problem, whatever is put there will be applied.

Hello sir,

actually i tried this and i added this parameter to postgresql.base.conf file and when i restart patroni but database encrypt was not on. after all, postgresql encrypt (TDE) should be run by reading this key file.

Step 1: Stop Patroni
Step 2: add parameter to postgresql.base.conf

encryption_key_command = '/db/key/db_key.sh'

save file and exit.

3. start Patroni.

Normally in this case database encryption should be on but it will appear as off. and yes this is a custom PostgreSQL installation (Cybertec TDE version). and we had to install custom postgresql version by compiling source code. However when i look at db, seems that didnt start as encrypt on by reading contents of key file.

$ ./pg_controldata /db/tde/ | grep -i encrypt
Data encryption:                      off

# show data_encryption;
 data_encryption
-----------------
 off
(1 row)

Why do you think sql didnt start with parameter in postgresql.base.conf file? how can i adapt Patroni to a custom postgresql installation?

Thank you.

**Comment by CyberDem0n** [comment]
> $ ./pg_controldata /db/tde/ | grep -i encrypt
Data encryption: off

I have no clue how it is supposed to be enabled. Maybe it happens during initdb time.

**Comment by immercool** [comment]
I think I can help here (sounds like PostgreSQL-TDE from CYBERTEC). You have to do the following:
1. Change the initdb section to 
```
bootstrap:
  method: tde_initdb
  tde_initdb:
    command: /etc/patroni/tde_initdb.sh
```

2. Create the initdb script  (/etc/patroni/tde_initdb.sh) and add
```
#!/usr/bin/bash
set -euxo pipefail
/usr/local/pgsql13-tde/bin/initdb --pgdata=/var/lib/pgsql/13/data --encryption-key-command=/etc/patroni/encryption_command.sh  --encoding=UTF8 --data-checksums
```

(don't forget to make it executable) 


3. Create the Encryption script (/etc/patroni/encryption_command.sh) 
```
#!/usr/bin/bash
set -euo pipefail
echo 'f9bbf526005dc9c2fda17455f1c905f4'
```

 (this is the simplest way) (don't forget to make it executable)

**Comment by rugzok** [comment]
> I think I can help here (sounds like PostgreSQL-TDE from CYBERTEC). You have to do the following:
> 
> 1. Change the initdb section to
> 
> ```
> bootstrap:
>   method: tde_initdb
>   tde_initdb:
>     command: /etc/patroni/tde_initdb.sh
> ```
> 
> 2. Create the initdb script  (/etc/patroni/tde_initdb.sh) and add
> 
> ```
> #!/usr/bin/bash
> set -euxo pipefail
> /usr/local/pgsql13-tde/bin/initdb --pgdata=/var/lib/pgsql/13/data --encryption-key-command=/etc/patroni/encryption_command.sh  --encoding=UTF8 --data-checksums
> ```
> 
> (don't forget to make it executable)
> 
> 3. Create the Encryption script (/etc/patroni/encryption_command.sh)
> 
> ```
> #!/usr/bin/bash
> set -euo pipefail
> echo 'f9bbf526005dc9c2fda17455f1c905f4'
> ```
> 
> (this is the simplest way) (don't forget to make it executable)

Hi Patrick, this has been a great way and i was able to send --encryption-key-command by defining for bootstrap and it worked, thank you! i will also test it in prod clusters thanks for this great howto!

Regards
