### ISSUE TITLE
[question] Will watchdog trigger node restart for planned slow PostgreSQL shutdown?

### ISSUE THREAD

**Issue by markosutic** [zalando/patroni#2396]
Hello!

If we want to run planned shutdown/switchover for the Patroni leader node, and if this operation takes few minutes, will watchdog trigger node reboot?

Based on the documentation, and checking the source code, I think watchdog will skip rebooting the node as Patroni will update leader key in the DCS. I suppose this would be "normal circumstances".

In case of unplanned shutdown (connectivity problems with DCS, or node unresponsiveness) I would expect watchdog to trigger restart.

I have tried to reproduce such scenario but have difficulties to reproduce very slow shutdown in my test environment.

Thank you for the information

**Comment by CyberDem0n** [comment]
> Based on the documentation, and checking the source code, I think watchdog will skip rebooting the node as Patroni will update leader key in the DCS. I suppose this would be "normal circumstances".

Correct.

> In case of unplanned shutdown (connectivity problems with DCS, or node unresponsiveness) I would expect watchdog to trigger restart.
I have tried to reproduce such scenario but have difficulties to reproduce very slow shutdown in my test environment.

You can add a time.sleep(30) here, before the demote() call: https://github.com/zalando/patroni/blob/4a854a71c087a315e3d8697fa824e9714e6db7b2/patroni/ha.py#L1514

P.S. the next release will change it and demote() will be called [asynchronously](https://github.com/zalando/patroni/pull/2379/files#diff-b6a3a0ef64783a6d32feb908d74a3a009e9f25008b8ca5313c9c9747e3b74a63R1643-R1647) (not 100%, but very close to it).

**Comment by markosutic** [comment]
Thank you Alexander for the quick answer.
