### ISSUE TITLE
Detecting if the DB is writable when using synchronous_mode_strict

### ISSUE THREAD

**Issue by martinb-uk** [zalando/patroni#2400]
We are running our patroni setup with:

synchronous_mode: true
synchronous_mode_strict: true

as we want to 100% ensure data replication between the primary and a set of replicas. 
In the event of a VM crash/network issue, whereby a standby becomes unavailable, the primary postgres DB is no longer writable.

We would like a method to detect the DB is in such a state. In our case we'd like to stop the applications which were accessing the DB to prevent them hanging or creating errors. 

Are you able to suggest if there is an official (or unofficial!) way of detecting this? I took a look at all of the data exposed via the REST API and didn't see any obvious way.

**Comment by CyberDem0n** [comment]
You can check the value of `synchronous_standby_names`. If there is `*` in it, this is an indicator that Patroni on the primary can't find proper synchronous nodes. You can also check the value of the `/sync` key in DCS. It will contain only the name of the leader.
But, it doesn't always mean that writes are not possible, because:
1. There still could be a node that isn't allowed to be synchronous from Patroni perspective, but with `*` Postgres may make it synchronous.
2. Any connection can disable synchronous_mode for itself.

**Comment by martinb-uk** [comment]
Thanks for the response. I'll try out your ideas and check if anything is suitable for detecting the condition reliably.

**Comment by martinb-uk** [comment]
After playing around with this stuff a bit more I see that my understanding of some of these settings isn't quite as expected:

"synchronous_mode": true     <-- Whether to use synchronous replication
"synchronous_node_count": 3,  <-- How many synchronous replicas to have **(Assuming you have this many non-leader members available)**
"synchronous_mode_strict": true,  <-- Make the cluster READ ONLY if we don't have at least 1 synchronous replica. 

In an idea world, the synchronous_mode_strict setting would make the cluster READ ONLY if we don't have at least <synchronous_node_count> synchronous replicas.

From reading around a bit it looks like Patroni does not yet support this feature and will always 'automatically reduce' synchronous_node_count if a replica members fails or is stopped. 

Are you able to confirm that my understanding of this is correct? 

Our core problem is that we have got a 2 DataCenter setup where we run 2 patroni instances on each DC. e.g:

DC1 - Patroni1 : Leader
DC1 - Patroni2 : Sync Replica
DC2 - Patroni3 : Sync Replica
DC2 - Patroni4 : Sync Replica

I want to be able to be 100% confident that in any failure situation (e.g. node failure, DC failure, or network failure), we have got consistent data across  Patroni1/2/3/4 - Even if it means that all of the nodes go READ ONLY until a manual recovery can be performed (e.g. reducing synchronous_node_count down to a lower number)

**Comment by CyberDem0n** [comment]
> Are you able to confirm that my understanding of this is correct?

Yes, Patroni doesn't allow to set the minimum replication factor.

But, you can do it more or less manually without using `synchronous_mode` feature at all.
The only prerequisite is that node names in the cluster are more or less static. After that you change patroni.yaml on every node and adjust `postgresql.parameters.synchronous_standby_names` to a desired value.

**Comment by CyberDem0n** [comment]
But, now your question has nothing to do with the original one.
Also, please keep in mind that the only way to make the cluster read-only is stopping postgres and starting it up with the `standby.signal` file.

**Comment by martinb-uk** [comment]
Ok thanks for confirming that.

Sounds like the manual way of not using synchronous_mode and manually setting static values for synchronous_standby_names would need to be used for this requirement. 

I'll close this as you're right I have changed the question as my understanding of the behaviour changed.
