### ISSUE TITLE
Patroni service is gone from Consul after turning on "verify_client"

### ISSUE THREAD

**Issue by duj4** [zalando/patroni#2401]
**Describe the bug**
Patroni service is gone from Consul Services GUI after set "verify_client" as "required". I don't think this is a bug but some mis-configuration.

**To Reproduce**
1. Set Consul as the DCS
2. Turn on "verify_client" as "enabled" in restapi section (attached with the configuration)

**Expected behavior**
https is protected but keep everything else as it was.

**Screenshots**
In sections below.

**Environment**
- Patroni version: 2.1.4
- PostgreSQL version: 13.5
- DCS (and its version): Consul 1.12.2

**Patroni configuration file**
![patroni_config](https://user-images.githubusercontent.com/19278537/187166951-f74489bb-d7cf-4a77-a8b7-db77bfb4aef8.jpg)

**patronictl show-config**
![patronictl_showconfig](https://user-images.githubusercontent.com/19278537/187169841-1c0fa884-24e6-4287-bd36-1deeb00f3ffd.jpg)

**Have you checked Patroni logs?**
No error in Patroni log files.

**Have you checked PostgreSQL logs?**
No, this is not PostgreSQL related issue.

**Have you tried to use GitHub issue search?**
Yes, but I did not manged to find any.

**Additional context**
Log snippet from Consul:
```
2022-08-29T14:29:27.018+0800 [INFO]  agent: Synced check: check=service:pgcluster/[patroni hostname]
2022-08-29T14:35:18.543+0800 [INFO]  agent: Synced check: check=service:pgcluster/[patroni hostname]
2022-08-29T14:36:59.559+0800 [INFO]  agent: Deregistered service: service=pgcluster/[patroni hostname]
2022-08-29T14:38:12.256+0800 [ERROR] agent.http: Request error: method=PUT url=/v1/agent/service/deregister/pgcluster/[patroni hostname] from=[patroni host ip]:46508 error="Unknown service ID "pgcluster/[patroni hostname]". Ensure that the service ID is passed, not the service name."
2022-08-29T14:38:12.264+0800 [ERROR] agent.http: Request error: method=PUT url=/v1/agent/service/deregister/pgcluster/[patroni hostname] from=[patroni host ip]:46508 error="Unknown service ID "pgcluster/[patroni hostname]". Ensure that the service ID is passed, not the service name."
2022-08-29T14:38:13.045+0800 [INFO]  agent: Synced service: service=pgcluster/[patroni hostname]
2022-08-29T14:38:14.738+0800 [WARN]  agent: Check is now critical: check=service:pgcluster/[patroni hostname]
2022-08-29T14:38:29.742+0800 [WARN]  agent: Check is now critical: check=service:pgcluster/[patroni hostname]
```

I think this should be owning to the switch "verify_client", since PUT is an "unsafe" API and it should be used with client cert, but I have no idea how to set this together with Consul, please guide me if this is the case.

Again, apologies for missing the issue format.

**Comment by CyberDem0n** [comment]
@duj4 why did you decide to ignore the issue template?

**Comment by duj4** [comment]
@CyberDem0n Oh, sorry for that, since I thought this might not be a bug, I will edit it right now.

**Comment by CyberDem0n** [comment]
the whole point is that the issue template is asking very specific and important questions to avoid unnecessarily ping-pongs.
Also, while answering these questions you may already figure out what went wrong.

**Comment by duj4** [comment]
@CyberDem0n I have re-formated the issue, apologies for the mess and thanks for that.

**Comment by CyberDem0n** [comment]
> Turn on "verify_client" as "enabled" in restapi section (attached with the configuration)

It is set to "required".
According to the documentation in this case all REST API endpoints are protected: https://patroni.readthedocs.io/en/latest/SETTINGS.html#rest-api

> verify_client: (optional): none (default), optional or required. When none REST API will not check client certificates. **When required client certificates are required for all REST API calls.** 

If Consul connects to the Patroni API without valid client certificate such requests are rejected. You can verify it by enabling DEBUG logs: https://patroni.readthedocs.io/en/latest/SETTINGS.html#log

**Comment by duj4** [comment]
hi @CyberDem0n,
Thanks for your reply.
I enabled "DEBUG" in patroni log files:
![patroni_debug](https://user-images.githubusercontent.com/19278537/187182215-fe9ee56d-8361-4c47-be76-cf624374c101.jpg)

So I need to modify the consul configuration file to make it work?

Thanks.

**Comment by CyberDem0n** [comment]
I don't see API requests from consul in Patroni logs.

BTW, why consul.host is different from the localhost? Patroni has to connect to the local agent.

**Comment by duj4** [comment]
The hostname: vshgms11.ai.ms.com.cn is the one that patroni's running on, whcih is the same host as consul client.

**Comment by duj4** [comment]
One more question: in consul section of patroni config file, is the certfile is consul client cert file or just a client cert file?

**Comment by CyberDem0n** [comment]
> One more question: in consul section of patroni config file, is the certfile is consul client cert file or just a client cert file?

Patroni is a client for Consul.

**Comment by duj4** [comment]
@CyberDem0n Right, if that is the case, in the patroni.yml consul.certfile should be the consul client cert?

**Comment by CyberDem0n** [comment]
There is no such parameter `consul.certfile`: https://patroni.readthedocs.io/en/latest/SETTINGS.html#consul

> cacert: (optional) The ca certificate. If present it will enable validation.
cert: (optional) file with the client certificate.
key: (optional) file with the client key. Can be empty if the key is part of cert.

**Comment by duj4** [comment]
Well, my bad, I mean consul.cert here.

**Comment by CyberDem0n** [comment]
> This is the error I got from Consul GUI.

It is already answered here: https://github.com/zalando/patroni/issues/2401#issuecomment-1230025099
