### ISSUE TITLE
After using kill - 15 to stop, the server still has the established connection to send SQL, and sq is executed correctly

### ISSUE THREAD

**Issue by wangshiminwork** [zalando/patroni#2402]
After using kill - 15 to stop, the server still has the established connection to send SQL, and sq is executed correctly,The server does not report an error

**Comment by CyberDem0n** [comment]
I don't know what you are doing, but please stop it immediately.

**Comment by wangshiminwork** [comment]
> I don't know what you are doing, but please stop it immediately.

I'm doing a fault drill to test the abnormal conditions after the manual stop. It is found that the service can still receive data after the manual stop

**Comment by CyberDem0n** [comment]
> I'm doing a fault drill

Perfect. And why did you ignore the issue template?
