### ISSUE TITLE
postgresql no response while restore from pgbackrest

### ISSUE THREAD

**Issue by msrd4** [zalando/patroni#2403]
**Describe the bug**
i have a pgbackrest backup in my s3 repo and i am trying to bootstrap a new patroni cluster from it. 
as patroni says , the restore completed successfully but then i get an exception in replica creation , also it seems my postgresql won't start 

**Environment**
- Patroni version: 2.1.3
- PostgreSQL version: 13.7
- DCS (and its version): ubuntu 20.04

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```
scope: bckup01
name: bckup01-n01
namespace: /patroni_bckup01/
restapi:
    listen: 0.0.0.0:8008
    connect_address: bckup-c01n01:8008
etcd3:
    hosts: etcd01:2379,etcd022379,etcd03:2379
bootstrap:
    method: pgbackrest
    pgbackrest:
        command: /etc/patroni/boot_pgbackrest.sh
        keep_existing_recovery_conf: false
    recovery_conf:
        recovery_target: immediate
        recovery_target_action: promote
        recovery_target_timeline: latest
        restore_command: pgbackrest --stanza=demos3 archive-get %f "%p"    
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        synchronous_mode: true
        synchronous_mode_strict: false
        postgresql:
            use_pg_rewind: true
            use_slots: true
            remove_data_directory_on_rewind_failure: true
            parameters:
                logging_collector: 'on'
                log_min_duration_statement: 500
                log_line_prefix: '%t [%p]: '
                log_checkpoints: 'on'
                log_connections: 'off'
                log_disconnections: 'off'
                log_replication_commands: 'on'
                log_statement: ddl
                log_lock_waits: 'on'
                log_temp_files: 0
                log_autovacuum_min_duration: 2s
                log_error_verbosity: verbose
                log_truncate_on_rotation: 'on'
                log_rotation_size: '10000'
                log_filename: 'bmn-postgresql-%H%M.log'
                log_rotation_age: 60
                log_timezone: 'localtime'
                deadlock_timeout: 500ms
                max_wal_senders: 20
                max_replication_slots: 15
                hot_standby: 'on'
                wal_level: logical
                wal_log_hints: 'on'
                wal_buffers : 16MB
                wal_writer_delay: 20ms
                autovacuum_naptime: 1min
                autovacuum_vacuum_scale_factor: 0.09
                autovacuum_analyze_scale_factor: 0.05
                autovacuum_vacuum_cost_delay: -1
                autovacuum_vacuum_cost_limit: -1
                commit_delay: 30
                hot_standby_feedback: 'on'
                shared_buffers : 3GB
                effective_cache_size : 9GB
                maintenance_work_mem : 768MB
                default_statistics_target : 100
                random_page_cost : 1.1
                effective_io_concurrency : 200
                max_connections: 300
                superuser_reserved_connections: 10
                work_mem : 2621kB
                min_wal_size : 1GB
                max_wal_size : 4GB
                checkpoint_timeout: 15min
                max_logical_replication_workers: 6
                max_sync_workers_per_subscription: 6
                max_worker_processes : 10
                max_parallel_workers_per_gather : 4
                max_parallel_workers : 10
                max_parallel_maintenance_workers : 4
                track_io_timing : 'on'
                track_activity_query_size : '8192'
                track_functions: all
                pg_stat_statements.track : 'all'
                pg_stat_statements.max: 10000
                pg_stat_monitor.pgsm_query_max_len : '2048'
                idle_in_transaction_session_timeout: 10min
                recovery_conf: 
                    recovery_target_timeline: latest
                    restore_command: pgbackrest --stanza=demos3 archive-get %f "%p"
              
    pg_hba:
    - local all postgres  ident
    - host all all 0.0.0.0/0 md5
    - host all zbx_monitor localhost md5
    - local replication postgres  ident
    - host replication replicator 127.0.0.1/32 trust
    - host replication replicator 10.1.10.35/32 trust
    - host replication replicator 10.1.10.0/24 md5
    users:
        admin:
            password: 
            options:
                - createrole
                - createdb
postgresql:
    listen: '0.0.0.0:5432'
    connect_address: bckup-c01:5432
    data_dir: /var/lib/postgresql/13/main
    bin_dir: /usr/lib/postgresql/13/bin
    config_dir: /etc/postgresql/13/main
    pgpass: /var/lib/postgresql/.pgpass
    authentication:
        replication:
            username: replicator
            password: 
        superuser:
            username: postgres
            password: 
        rewind:
            username: rewind_user
            password: 
    parameters:
        stats_temp_directory: '/var/lib/postgresql/pg_stat_tmp'
        shared_preload_libraries: 'pg_stat_statements, pg_stat_monitor, dblink, postgres_fdw'
        archive_mode: 'on'
        archive_command: 'pgbackrest --stanza=demos3 archive-push %p'

    create_replica_methods:
        - pgbackrest
        - basebackup  
    pgbackrest:
         - command: /etc/patroni/boot_pgbackrest.sh
         - keep_data: True
         - no_params: false
           #    recovery.conf:
           #         - recover_target_timeline: latest
           #         - restore_command: pgbackrest --stanza=demos3 archive-get %f "%p"
    basebackup:
         - max-rate: '200M'
         - checkpoint: fast
         - status-interval: 2s
         - progress       
watchdog:
  mode: required
  device: /dev/watchdog
  safety_margin: 5
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here
617 INFO: not healthy enough for leader race
Aug 31 17:05:53 bckup01 patroni[196392]: 2022-08-31 17:05:53,621 INFO: bootstrap in progress
Aug 31 17:05:57 bckup01 patroni[196414]: 2022-08-31 17:05:57.114 P00   INFO: write updated /var/lib/postgresql/13/main/postgresql.auto.conf
Aug 31 17:05:57 bckup01 patroni[196414]: 2022-08-31 17:05:57.118 P00   INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)
Aug 31 17:05:57 bckup01 patroni[196414]: 2022-08-31 17:05:57.119 P00   INFO: restore size = 141.5MB, file total = 2354
Aug 31 17:05:57 bckup01 patroni[196414]: 2022-08-31 17:05:57.120 P00   INFO: restore command end: completed successfully (73443ms)
Aug 31 17:05:57 bckup01 patroni[196392]: 2022-08-31 17:05:57,139 WARNING: Removing unexpected parameter=recovery_conf value={'recovery_target_timeline': 'latest', 'restore_command': 'pgbackrest --stanza=demos3 archive-get %f "%p"'} from the config
Aug 31 17:05:57 bckup01 patroni[196392]: 2022-08-31 17:05:57,642 INFO: postmaster pid=196635
Aug 31 17:05:57 bckup01 patroni[196639]: localhost:5432 - no response
Aug 31 17:05:57 bckup01 patroni[196635]: 2022-08-31 17:05:57 +0430 [196635]: LOG:  00000: redirecting log output to logging collector process
Aug 31 17:05:57 bckup01 patroni[196635]: 2022-08-31 17:05:57 +0430 [196635]: HINT:  Future log output will appear in directory "log".
Aug 31 17:05:57 bckup01 patroni[196635]: 2022-08-31 17:05:57 +0430 [196635]: LOCATION:  SysLogger_Start, syslogger.c:671
Aug 31 17:05:58 bckup01 patroni[196392]: 2022-08-31 17:05:58,665 ERROR: postmaster is not running

**Have you checked PostgreSQL logs?**
Please provide a snippet here
2022-08-31 17:18:32 +0430 [197410]: LOG:  00000: starting PostgreSQL 13.7 (Ubuntu 2:13.7-3.focal) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
2022-08-31 17:18:32 +0430 [197410]: LOCATION:  PostmasterMain, postmaster.c:1124
2022-08-31 17:18:32 +0430 [197410]: LOG:  00000: listening on IPv4 address "0.0.0.0", port 5432
2022-08-31 17:18:32 +0430 [197410]: LOCATION:  StreamServerPort, pqcomm.c:585
2022-08-31 17:18:32 +0430 [197410]: LOG:  00000: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-08-31 17:18:32 +0430 [197410]: LOCATION:  StreamServerPort, pqcomm.c:580
2022-08-31 17:18:32 +0430 [197421]: LOG:  00000: database system was interrupted; last known up at 2022-08-28 13:59:05 +0430
2022-08-31 17:18:32 +0430 [197421]: LOCATION:  StartupXLOG, xlog.c:6423
2022-08-31 17:18:32 +0430 [197421]: LOG:  00000: invalid checkpoint record
2022-08-31 17:18:32 +0430 [197421]: LOCATION:  ReadCheckpointRecord, xlog.c:8347
2022-08-31 17:18:32 +0430 [197421]: FATAL:  XX000: could not locate required checkpoint record
2022-08-31 17:18:32 +0430 [197421]: HINT:  If you are restoring from a backup, touch "/var/lib/postgresql/13/main/recovery.signal" and add required recovery options.
	If you are not restoring from a backup, try removing the file "/var/lib/postgresql/13/main/backup_label".
	Be careful: removing "/var/lib/postgresql/13/main/backup_label" will result in a corrupt cluster if restoring from a backup.
2022-08-31 17:18:32 +0430 [197421]: LOCATION:  StartupXLOG, xlog.c:6593
2022-08-31 17:18:32 +0430 [197410]: LOG:  00000: startup process (PID 197421) exited with exit code 1
2022-08-31 17:18:32 +0430 [197410]: LOCATION:  LogChildExit, postmaster.c:3731
2022-08-31 17:18:32 +0430 [197410]: LOG:  00000: aborting startup due to startup process failure
2022-08-31 17:18:32 +0430 [197410]: LOCATION:  reaper, postmaster.c:2992
2022-08-31 17:18:32 +0430 [197410]: LOG:  00000: database system is shut down
2022-08-31 17:18:32 +0430 [197410]: LOCATION:  UnlinkLockFiles, miscinit.c:932

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.
yes i have read many issues and did not get my answer

this is my custom bootstrap script: 
#!/usr/bin/env bash

while getopts ":-:" optchar; do
  [[ "${optchar}" == "-" ]] || continue
  case "${OPTARG}" in
    datadir=* )
        DATA_DIR=${OPTARG#*=}
        ;;
    scope=* )
        SCOPE=${OPTARG#*=}
        ;;
  esac
done

/usr/bin/pgbackrest --stanza=demos3 --link-all restore --pg1-path=$DATA_DIR

**Comment by CyberDem0n** [comment]
There is an error in your config:
```yaml
bootstrap:
    dcs:
        postgresql:
            parameters:
                recovery_conf: 
                    recovery_target_timeline: latest
                    restore_command: pgbackrest --stanza=demos3 archive-get %f "%p"
```

While it should be:
```yaml
bootstrap:
    dcs:
        postgresql:
            recovery_conf: 
                recovery_target_timeline: latest
                restore_command: pgbackrest --stanza=demos3 archive-get %f "%p"
```
