### ISSUE TITLE
Patroni 2.1.4, switchover on async replica in sync mode

### ISSUE THREAD

**Issue by ChenChangAo** [zalando/patroni#2405]
**Describe the bug**
when doing manual switchover, i did not specify target node (just pressed enter) and patroni sometimes switchs on async replica

**To Reproduce**
make 3 nodes (1 leader, 1 sync, 1 async), and try to switch without specify target node

**Expected behavior**
patroni should not accept empty value OR should switchover only on sync standby (if available)

**Screenshots**
<img width="627" alt="1" src="https://user-images.githubusercontent.com/86454826/188056950-02281d36-4ec2-48bc-9053-35de43a0d78e.png">

**Environment**
- Patroni version: 2.1.4
- PostgreSQL version: 12.12
- DCS (and its version): etcd 3.3.11

**Have you tried to use GitHub issue search?**
yes, #2074 and #2076, but in v2.1.4 may still have the bug

**Comment by CyberDem0n** [comment]
How confident you are that Patroni didn't change the sync node right before the switch? Have you checked logs (the issue template is explicitly asking for it)?

**Comment by ChenChangAo** [comment]
Patroni change the sync node right. I think the bug may be here(file: ha.py function: is_healthiest_node).
<img width="608" alt="2" src="https://user-images.githubusercontent.com/86454826/188074146-190e1762-22ae-4b9c-9192-2c2de6ffbcfd.png">
without specify target node, self.cluster.failover.candidate will be None, and the async node will call self.manual_failover_process_no_leader() which returns true, so the async node will have chance to be new leader.

**Comment by CyberDem0n** [comment]
@ChenChangAo yeah, quite possible do you want to create a PR fixing it?

**Comment by ChenChangAo** [comment]
I want to know why there needs self.cluster.failover.leader and self.cluster.failover.candidate, without them, may fixing it.

**Comment by CyberDem0n** [comment]
When doing a switchover we want to exclude the former leader from the race.
Its name is stored in the `failover.leader`.
In case of switchover/failover to a specific member we use the `failover.candidate` to name it.

**Comment by ChenChangAo** [comment]
The reason why self.manual_failover_process_no_leader() return true in async node is that sync's and async's wal position are equal, I think.
My solution is deleting the condition self.cluster.failover.candidate in the if statement, so the async node will return false in function is_healthiest_node, but I don't know whether it will cause other bugs.
