### ISSUE TITLE
Setup cascade replica with sync mode

### ISSUE THREAD

**Issue by EdithChenLi** [zalando/patroni#2407]
I would like to setup the test05 as sync mode in this standby cluster but did not work with (syncxx_mode=on), is this possible to setup sync mode for cascade replica?  I read the patroni documentaion, did not find details on this part.

Appreciate for your help!

$ patronictl -c /opt/scripts/postgres.yml list
+--------+---------------+----------------+---------+----+-----------+
| Member | Host          | Role                     | State   | TL | Lag in MB |
+ Cluster: stdcluster (7129238778904648225) --------+----+-----------+
| test04 | 192.168.3.103 | Standby Leader | running | 55 |           |
| test05 | 192.168.3.104 | Replica               | running | 55 |         0 |
+--------+---------------+----------------+---------+----+-----------+

postgres=# select pid,state,client_addr,sync_priority,sync_state from pg_stat_replication;
 pid  |   state           |  client_addr  | sync_priority | sync_state 
------+-----------+---------------+---------------+------------
 5566 | streaming | 192.168.3.104 |             0 | async
(1 row)

**Comment by hughcapet** [comment]
[PG docs](https://www.postgresql.org/docs/current/warm-standby.html#CASCADING-REPLICATION:~:text=foopass%27%0Aprimary_slot_name%20%3D%20%27node_a_slot%27-,27.2.7.%C2%A0Cascading%20Replication,-The%20cascading%20replication)

```
Cascading replication is currently asynchronous. 
Synchronous replication settings have no effect on cascading replication at present.
```

**Comment by EdithChenLi** [comment]
Thank you for the confiramtion! I do missed this part on the documentation
