### ISSUE TITLE
Patroni 2.1.4 don't remove replication slots

### ISSUE THREAD

**Issue by shipiguzev** [zalando/patroni#2408]
#After patroni upgrade 2.1.0 -> 2.1.4, patroni don't remove custom replication slots.
I don't use settings "slots:" and "ignore_slots:"

**Comment by shipiguzev** [comment]
how can i fix it?

**Comment by hughcapet** [comment]
Please use the template when creating an Issue. It is almost impossible to say anything without the additional information.

**Comment by CyberDem0n** [comment]
Well...
Currently it works the same way as it was before 2.1.0. The unknown slot is removed when the new node joins the cluster.

**Comment by shipiguzev** [comment]
> Well... Currently it works the same way as it was before 2.1.0. The unknown slot is removed when the new node joins the cluster.

is new postgres node join the cluster?

**Comment by CyberDem0n** [comment]
> new postgres node join the cluster?

Yes. Let's say there are node1 and node2 in the cluster. If node3 will join, any unknown replication slot is removed. It was the behavior from very early days. We just try to avoid unnecessary queries on `pg_replication_slots` view.

**Comment by CyberDem0n** [comment]
> I checked it on version 2.1.0 and 1.6.5. Slots have been removed after few seconds

I also just tried it with 1.6.5. When the cluster topology doesn't change unknown slots are not removed.

**Comment by shipiguzev** [comment]
> > I checked it on version 2.1.0 and 1.6.5. Slots have been removed after few seconds
> 
> I also just tried it with 1.6.5. When the cluster topology doesn't change unknown slots are not removed.

Ok.  why i see in my log on 2.1.0 version this message after create custom slot?

2022-09-16 16:25:58.922 +07 [16932] patroni@postgres LOG:  statement: SELECT pg_catalog.pg_drop_replication_slot('test_logic_slot') WHERE EXISTS (SELECT 1 FROM pg_catalog.pg_replication_slots WHERE slot_name = 'test_logic_slot' AND NOT active)

cluster topology doesn't change

**Comment by shipiguzev** [comment]
> > > I checked it on version 2.1.0 and 1.6.5. Slots have been removed after few seconds
> > 
> > 
> > I also just tried it with 1.6.5. When the cluster topology doesn't change unknown slots are not removed.
> 
> Ok. why i see in my log on 2.1.0 version this message after create custom slot?
> 
> 2022-09-16 16:25:58.922 +07 [16932] patroni@postgres LOG: statement: SELECT pg_catalog.pg_drop_replication_slot('test_logic_slot') WHERE EXISTS (SELECT 1 FROM pg_catalog.pg_replication_slots WHERE slot_name = 'test_logic_slot' AND NOT active)
> 
> cluster topology doesn't change

i checked - it was changed in version 2.1.2. Unknown slots  are not removed

**Comment by shipiguzev** [comment]
> > > > I checked it on version 2.1.0 and 1.6.5. Slots have been removed after few seconds
> > > 
> > > 
> > > I also just tried it with 1.6.5. When the cluster topology doesn't change unknown slots are not removed.
> > 
> > 
> > Ok. why i see in my log on 2.1.0 version this message after create custom slot?
> > 2022-09-16 16:25:58.922 +07 [16932] patroni@postgres LOG: statement: SELECT pg_catalog.pg_drop_replication_slot('test_logic_slot') WHERE EXISTS (SELECT 1 FROM pg_catalog.pg_replication_slots WHERE slot_name = 'test_logic_slot' AND NOT active)
> > cluster topology doesn't change
> 
> i checked - it was changed in version 2.1.2. Unknown slots are not removed

i found. It https://github.com/zalando/patroni/pull/2055. But, it is a bad solution  for me.  

@CyberDem0n  thanks
