### ISSUE TITLE
Changed etcd server, reload and restart patroni (without resume/pause), patronictl -c patroni.yaml list says Cluster: uninitialized while Patroni REST API says that all OK

### ISSUE THREAD

**Issue by leprekorn** [zalando/patroni#2411]
**Describe the bug**
I have installed a patroni cluster on 3 nodes with etcd3 DCS.  Than I changed etcd server in patroni.yaml to another server.
I sended patroni /reload to API and also sended  /restart to API.
Than I watched the status:
patronictl -c patroni.yaml list:

[me@mylinux patroni]$ patronictl -c patroni.yml  list
+ Cluster: patroni-alt (uninitialized) ---------+
| Member | Host | Role | State | TL | Lag in MB |
+--------+------+------+-------+----+-----------+
+--------+------+------+-------+----+-----------+

And also checked status by API sendind GET to /cluster
I was very interersted because via API patroni sads that all OK:
```
curl http://10.92.16.181:8008/topology
{"state": "running", "postmaster_start_time": "2022-09-08 15:38:07.926280+03:00", "role": "master", "server_version": 140003, "xlog": {"location": 83889392}, "timeline": 1, "replication": [{"usename": "replicator", "application_name": "patroni-alt_novoselovdy-alt84-node2", "client_addr": "10.92.17.97", "state": "streaming", "sync_state": "async", "sync_priority": 0}, {"usename": "replicator", "application_name": "patroni-alt_novoselovdy-alt84-node3", "client_addr": "10.92.17.100", "state": "streaming", "sync_state": "async", "sync_priority": 0}],
```

I checked my new etcd server and figured out that there are no entries from patroni.

Than I restarted a patroni service on each node and  patronictl started to show that cluster is correct.

**To Reproduce**
Install patroni with etcd
Change etcd server in patroni config to new etcd server
reload patroni and restart patroni endpoints
check patronictl -c patroni.yml list   - says that cluster is unitialized
check /cluster via API  - says that cluster is up and running

**Expected behavior**
/cluster via API should say that cluster is unitialized and there is some issue

**Screenshots**

**Environment**
- Patroni version: 2.1.3
- PostgreSQL version: 14
- DCS (and its version): etcd  etcdctl version: 3.5.2
API version: 3.5

**Patroni configuration file**
```

Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved. NO

**Additional context**

**Comment by CyberDem0n** [comment]
The etcd cluster is a source of trues. You can't change etcd hosts for a _running_ Patroni cluster, because you'll end up in a situation when different Patroni nodes of the same cluster are working with different etcd clusters.
