### ISSUE TITLE
"Primary" vs "Master" usage in docs

### ISSUE THREAD

**Issue by jchancojr** [zalando/patroni#2414]
**Describe the bug**
The documentation uses “master” in place of “Primary”. While unintentional, occasionally there is feedback that the usage is insensitive. Can we `s/master/primary` in the docs without needing to change the ~1500 references to master in the code? I'll modify the docs in my fork with the proposed changes to documentation and create a PR in the meantime. Kindly let me know? Thanks!

**To Reproduce**
https://patroni.readthedocs.io/en/latest/search.html?q=master&check_keywords=yes&area=default

**Expected behavior**
Replication relationships are referred to by Primary, Standby, Replica, etc

**Screenshots**
https://patroni.readthedocs.io/en/latest/search.html?q=master&check_keywords=yes&area=default

**Environment**
- Patroni version:
- PostgreSQL version:
- DCS (and its version):

**Patroni configuration file**

**patronictl show-config**

**Have you checked Patroni logs?**
NA

**Have you checked PostgreSQL logs?**
NA

**Have you tried to use GitHub issue search?**
Looked but found nothing.

**Additional context**
NA

**Comment by CyberDem0n** [comment]
PR's are always welcome.
But, I would actually make a difference between the "primary" and the "leader"
The first one is more or less to indicate that Postgres is accepting writes, while the second one is more like a Patroni concept.
For example, there is no primary in a standby cluster, or there could be more than one primary in a pause mode.
That is, the simple search&replace will not work.

**Comment by jchancojr** [comment]
Thanks very much @CyberDem0n. I'll get working on that for review.
