### ISSUE TITLE
There is no "callback script" link for patroni use Kubernetes

### ISSUE THREAD

**Issue by yinan8128** [zalando/patroni#2429]
Hi 

We plan to use Patroni with Kubernetes, once click "callback script" link shows that "Page not found", there is no callback.py file in kubernetes directory any more, please indicate the file contents and how to use it, thanks

https://patroni.readthedocs.io/en/latest/kubernetes.html

**Comment by CyberDem0n** [comment]
If Patroni is using K8s as DCS you don't need to use callbacks.

**Comment by yinan8128** [comment]
Hi,

Thank you for the information

Does it mean that if use Configmaps only need to check this part? Thanks
_"configure the Kubernetes Postgres service to use the label selector with the role_label (configured in patroni configuration)."_

**Comment by yinan8128** [comment]
Hi,

Any update please? Thank you

**Comment by CyberDem0n** [comment]
> if use Configmaps only need to check this part?

Yes
