### ISSUE TITLE
patronictl timeout with raft

### ISSUE THREAD

**Issue by leagueofsoups** [zalando/patroni#2431]
**Describe the bug**
I have question about patroni cluster with three nodes with raft. There are probability to get infinity time of execution patronictl -c <cfg_path> topology, after one node shutdown. How I can fix this timeout?

**To Reproduce**

1) My test cluster topology
```
+----------+-----------+---------+---------+----+-----------+
| Member   | Host      | Role    | State   | TL | Lag in MB |
+ Cluster: demo-cluster-1 (7155048679605235377) +-----------+
| node-2   | 10.2.0.21 | Leader  | running |  1 |           |
| + node-1 | 10.2.0.6  | Replica | running |  1 |         0 |
| + node-3 | 10.2.0.25 | Replica | running |  1 |         0 |
+----------+-----------+---------+---------+----+-----------+
```
2) Then, I exec halt -p on node-3
3) Check partner_addrs on node-1
```
cat /etc/patroni.yml | grep part
  partner_addrs: [ "10.2.0.21:5010","10.2.0.25:5010" ]
```
4) Command for problem reproduce:
```
while true; do strace patronictl -c /etc/patroni.yml topology; sleep 1; done
```
patronictl try communicate with inaccessible node:
```
connect(3, {sa_family=AF_INET, sin_port=htons(5010), sin_addr=inet_addr("10.2.0.25")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=3, events=POLLIN|POLLOUT|POLLERR}], 1, 500) = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLOUT|POLLERR}], 1, 500) = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLOUT|POLLERR}], 1, 500) = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLOUT|POLLERR}], 1, 500) = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLOUT|POLLERR}], 1, 500) = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLOUT|POLLERR}], 1, 500) = 0 (Timeout)
poll([{fd=3, events=POLLIN|POLLOUT|POLLERR}], 1, 500) = 0 (Timeout)
```
This is because TcpUtility (pysyncobj/utility.py) have timeout = 900 in constructor. 

https://github.com/bakwc/PySyncObj/blob/master/pysyncobj/utility.py#L42
https://github.com/bakwc/PySyncObj/blob/master/pysyncobj/utility.py#L77

What is the reason for choosing this value for patroni? How can I change this value? Is this the expected behavior?

**Comment by CyberDem0n** [comment]
I think the timeout could be set to `retry_timeout/len(otherNodes)`, but it is not so straightforward to implement.
