### ISSUE TITLE
"No such file or directory" messages

### ISSUE THREAD

**Issue by joha78** [zalando/patroni#244]
[follower.txt](https://github.com/zalando/patroni/files/366324/follower.txt)
[leader.txt](https://github.com/zalando/patroni/files/366325/leader.txt)

This is more a question than an issue. I set up a cluster and I am experiencing error messages at the first start, that I can not interpret. Nevertheless it seems like it is working, just want to be sure if I understood something wrong. 

The first logging is from the leader, the second logging is from a follower that gets initially initialized from the leader: Whats about this "cp: cannot stat '/var/lib/postgresql/9.5/wal_archive/00000002.history': No such file or directory" messages?

/var/lib/postgresql/9.5/wal_archive  is a NFS share.
/var/lib/postgresql/9.5/cluster is a local directory.

I am getting similar messages when shutting down or starting followers again.

Thank you for this great work!
Jörg

**********Leader
`Jul 15 16:59:58 postgres-node1 patroni[7159]: 2016-07-15 16:59:58,160 INFO: waiting for leader to bootstrap
Jul 15 17:00:08 postgres-node1 patroni[7159]: The files belonging to this database system will be owned by user "postgres".
Jul 15 17:00:08 postgres-node1 patroni[7159]: This user must also own the server process.
Jul 15 17:00:08 postgres-node1 patroni[7159]: The database cluster will be initialized with locale "en_US.UTF-8".
Jul 15 17:00:08 postgres-node1 patroni[7159]: The default text search configuration will be set to "english".
Jul 15 17:00:08 postgres-node1 patroni[7159]: Data page checksums are enabled.
Jul 15 17:00:08 postgres-node1 patroni[7159]: creating directory /var/lib/postgresql/9.5/cluster ... ok
Jul 15 17:00:08 postgres-node1 patroni[7159]: creating subdirectories ... ok
Jul 15 17:00:08 postgres-node1 patroni[7159]: selecting default max_connections ... 100
Jul 15 17:00:08 postgres-node1 patroni[7159]: selecting default shared_buffers ... 128MB
Jul 15 17:00:08 postgres-node1 patroni[7159]: selecting dynamic shared memory implementation ... posix
Jul 15 17:00:08 postgres-node1 patroni[7159]: creating configuration files ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: creating template1 database in /var/lib/postgresql/9.5/cluster/base/1 ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: initializing pg_authid ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: setting password ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: initializing dependencies ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: creating system views ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: loading system objects' descriptions ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: creating collations ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: creating conversions ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: creating dictionaries ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: setting privileges on built-in objects ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: creating information schema ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: loading PL/pgSQL server-side language ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: vacuuming database template1 ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: copying template1 to template0 ... ok
Jul 15 17:00:09 postgres-node1 patroni[7159]: copying template1 to postgres ... ok
Jul 15 17:00:10 postgres-node1 patroni[7159]: syncing data to disk ... ok
Jul 15 17:00:10 postgres-node1 patroni[7159]: WARNING: enabling "trust" authentication for local connections
Jul 15 17:00:10 postgres-node1 patroni[7159]: You can change this by editing pg_hba.conf or using the option -A, or
Jul 15 17:00:10 postgres-node1 patroni[7159]: --auth-local and --auth-host, the next time you run initdb.
Jul 15 17:00:10 postgres-node1 patroni[7159]: Success. You can now start the database server using:
Jul 15 17:00:10 postgres-node1 patroni[7159]:     /usr/lib/postgresql/9.5/bin/pg_ctl -D /var/lib/postgresql/9.5/cluster -l logfile start
Jul 15 17:00:10 postgres-node1 patroni[7159]: waiting for server to start....LOG:  database system was shut down at 2016-07-15 17:00:09 CEST
Jul 15 17:00:10 postgres-node1 patroni[7159]: LOG:  MultiXact member wraparound protections are now enabled
Jul 15 17:00:10 postgres-node1 patroni[7159]: LOG:  database system is ready to accept connections
Jul 15 17:00:10 postgres-node1 patroni[7159]: LOG:  autovacuum launcher started
Jul 15 17:00:11 postgres-node1 patroni[7159]:  done
Jul 15 17:00:11 postgres-node1 patroni[7159]: server started
Jul 15 17:00:11 postgres-node1 patroni[7159]: 2016-07-15 17:00:11,570 INFO: establishing a new patroni connection to the postgres cluster
Jul 15 17:00:11 postgres-node1 patroni[7159]: 2016-07-15 17:00:11,583 INFO: initialized a new cluster
Jul 15 17:00:18 postgres-node1 patroni[7159]: 2016-07-15 17:00:18,161 INFO: Lock owner: postgres_node1; I am postgres_node1
Jul 15 17:00:18 postgres-node1 patroni[7159]: 2016-07-15 17:00:18,164 INFO: no action.  i am the leader with the lock`
*****************

*****************follower
`Jul 15 17:01:02 postgres-node2 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
Jul 15 17:01:02 postgres-node2 patroni[4877]: 2016-07-15 17:01:02,890 INFO: Starting new HTTP connection (1): 192.168.0.215
Jul 15 17:01:02 postgres-node2 patroni[4877]: 2016-07-15 17:01:02,897 INFO: trying to bootstrap from leader 'postgres_node1'
Jul 15 17:01:08 postgres-node2 patroni[4877]: 2016-07-15 17:01:08,141 INFO: Lock owner: postgres_node1; I am postgres_node2
Jul 15 17:01:08 postgres-node2 patroni[4877]: 2016-07-15 17:01:08,141 INFO: bootstrap from leader 'postgres_node1' in progress
Jul 15 17:01:18 postgres-node2 patroni[4877]: 2016-07-15 17:01:18,141 INFO: Lock owner: postgres_node1; I am postgres_node2
Jul 15 17:01:18 postgres-node2 patroni[4877]: 2016-07-15 17:01:18,142 INFO: bootstrap from leader 'postgres_node1' in progress
Jul 15 17:01:28 postgres-node2 patroni[4877]: 2016-07-15 17:01:28,142 INFO: Lock owner: postgres_node1; I am postgres_node2
Jul 15 17:01:28 postgres-node2 patroni[4877]: 2016-07-15 17:01:28,142 INFO: bootstrap from leader 'postgres_node1' in progress
Jul 15 17:01:38 postgres-node2 patroni[4877]: 2016-07-15 17:01:38,142 INFO: Lock owner: postgres_node1; I am postgres_node2
Jul 15 17:01:38 postgres-node2 patroni[4877]: 2016-07-15 17:01:38,142 INFO: bootstrap from leader 'postgres_node1' in progress
Jul 15 17:01:40 postgres-node2 patroni[4877]: WARNING:  skipping special file "./.s.PGSQL.5432"
Jul 15 17:01:45 postgres-node2 patroni[4877]: 2016-07-15 17:01:45,044 INFO: replica has been created using basebackup
Jul 15 17:01:45 postgres-node2 patroni[4877]: 2016-07-15 17:01:45,045 INFO: bootstrapped from leader 'postgres_node1'
Jul 15 17:01:45 postgres-node2 patroni[4877]: 2016-07-15 17:01:45,046 INFO: Starting new HTTP connection (2): 192.168.0.215
Jul 15 17:01:45 postgres-node2 patroni[4877]: waiting for server to start....LOG:  database system was interrupted; last known up at 2016-07-15 17:01:40 CEST
Jul 15 17:01:46 postgres-node2 patroni[4877]: FATAL:  the database system is starting up
Jul 15 17:01:46 postgres-node2 patroni[4877]: .FATAL:  the database system is starting up
Jul 15 17:01:47 postgres-node2 patroni[4877]: FATAL:  the database system is starting up
Jul 15 17:01:47 postgres-node2 patroni[4877]: .cp: cannot stat '/var/lib/postgresql/9.5/wal_archive/00000002.history': No such file or directory
Jul 15 17:01:47 postgres-node2 patroni[4877]: LOG:  entering standby mode
Jul 15 17:01:47 postgres-node2 patroni[4877]: LOG:  restored log file "000000010000000000000011" from archive
Jul 15 17:01:47 postgres-node2 patroni[4877]: LOG:  redo starts at 0/11000028
Jul 15 17:01:47 postgres-node2 patroni[4877]: LOG:  consistent recovery state reached at 0/113854C0
Jul 15 17:01:47 postgres-node2 patroni[4877]: LOG:  database system is ready to accept read only connections
Jul 15 17:01:47 postgres-node2 patroni[4877]: cp: cannot stat '/var/lib/postgresql/9.5/wal_archive/000000010000000000000012': No such file or directory
Jul 15 17:01:47 postgres-node2 patroni[4877]: LOG:  started streaming WAL from primary at 0/12000000 on timeline 1
Jul 15 17:01:48 postgres-node2 patroni[4877]:  done
Jul 15 17:01:48 postgres-node2 patroni[4877]: server started
Jul 15 17:01:48 postgres-node2 patroni[4877]: 2016-07-15 17:01:48,141 INFO: establishing a new patroni connection to the postgres cluster
Jul 15 17:01:48 postgres-node2 patroni[4877]: 2016-07-15 17:01:48,150 INFO: Lock owner: postgres_node1; I am postgres_node2
Jul 15 17:01:48 postgres-node2 patroni[4877]: 2016-07-15 17:01:48,150 INFO: does not have lock`

**Comment by alexeyklyukin** [comment]
Hi Jörg,

> On 15 Jul 2016, at 17:31, Jörg Hälker <notifications@github.com> wrote:
> 
> This is more a question than an issue. I set up a cluster and I am experiencing error messages at the first start, that I can not interpret. Nevertheless it seems like it is working, just want to be sure if I understood something wrong.
> 
> The first logging is from the leader, the second logging is from a follower that gets initially initialized from the leader: Whats about this "cp: cannot stat '/var/lib/postgresql/9.5/wal_archive/00000002.history': No such file or directory" messages?
> 
> /var/lib/postgresql/9.5/wal_archive is a NFS share.
> /var/lib/postgresql/9.5/cluster is a local directory.
> 
> 

This is normal (and in fact, comes from PostgreSQL executing your recovery command):

"Normally, recovery will proceed through all available WAL segments, thereby restoring the database to the current point in time (or as close as possible given the available WAL segments). Therefore, a normal recovery will end with a "file not found" message, the exact text of the error message depending upon your choice of restore_command. You may also see an error message at the start of recovery for a file named something like 00000001.history. This is also normal and does not indicate a problem in simple recovery situations; see Section 24.3.5 for discussion."

https://www.postgresql.org/docs/current/static/continuous-archiving.html

**Comment by joha78** [comment]
Hi Alex, 

ah I understand! thank yoT very much, I really appreciate you help. 

Best regards, Jörg
