### ISSUE TITLE
Managing multiple databases through patroni

### ISSUE THREAD

**Issue by ivan-da-ivan** [zalando/patroni#2441]
Hi !

Thanks for this awesome software !

Here's a problem I encountered recently with a simple setup :
2 patroni nodes, one etcd in each node
2 PostgreSQL nodes

This is the first time I try to configure patrony, patronyctlist gives the following:

+ Cluster: pg_cluster (7158749270371442718) ----------------+----+-----------+
| Member   | Host                      | Role    | State                 | TL | Lag in MB |
+----------+-------------------+---------+------------------+----+-----------+
| patroni1 | 170.17.5.119:5432 | Replica | creating replica |      |   unknown |
| patroni2 | 170.17.5.119:5432 | Leader  | running           |  1  |           |
+----------+-------------------+---------+------------------+----+-----------+

The host field displays the IP address of the database, which is intended for only one patroni node. I need to get a result roughly similar to::

+ Cluster: pg_cluster (7158749270371442718) ----------------+----+-----------+
| Member   | Host                      | Role    | State                 | TL | Lag in MB |
+----------+-------------------+---------+------------------+----+-----------+
| patroni1 | 170.17.5.119:5432 | Replica  |running            |      |           |
| patroni2 | 171.18.5.116:5432 | Leader  | running           |  1  |           |
+----------+-------------------+---------+------------------+----+-----------+

I do not understand where the host is explicitly specified, I do grep throughout the project and do not find a similar address at all. It looks like the configuration is sent to the subordinate by the leader, which is wrong. How to fix it?
______________________________________________________________________________________________________
my postgres0.yml for patroni1:

scope: pg_cluster
name: postgresql0
restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008
etcd:
  host: 127.0.0.1:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
  initdb:  
  - encoding: UTF8
  - data-checksums
  pg_hba:  
  - local all all trust
  - host all admin 170.17.5.119/24 trust
  - host all all 0.0.0.0/0 md5
  users:
    admin:
      password: admin321
      options:
        - createrole
        - createdb
        - replication
postgresql:
  listen: 0.0.0.0:5432
  connect_address: 170.17.5.119:5432
  data_dir: data/postgresql0
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: admin
      password: admin321
    superuser:
      username: admin
      password: admin321
    rewind:  
      username: admin
      password: admin321
  parameters:
    unix_socket_directories: '..'  
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

________________________________________________________________________________________
my postgres0.yml for patroni2:
scope: pg_cluster
name: postgresql0
restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008
etcd:
  host: 127.0.0.1:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      parameters:
  initdb:  
  - encoding: UTF8
  - data-checksums
  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - local all all trust
  - host all admin 171.18.5.116/24 trust
  - host all all 0.0.0.0/0 md5
  users:
    admin:
      password: admin321
      options:
        - createrole
        - createdb
        - replication
postgresql:
  listen: 0.0.0.0:5432
  connect_address: 171.18.5.116:5432
  data_dir: data/postgresql0
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: admin
      password: admin321
    superuser:
      username: admin
      password: admin321
    rewind:  
      username: admin
      password: admin321
  parameters:
    unix_socket_directories: '..'  
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

_______________________________________________________________________________________________
patronictl show-config:

loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 100
  pg_hba:
  - local all all trust
  - host replication all all md5
  - host all all all md5
  use_pg_rewind: true
retry_timeout: 10
ttl: 30

**Comment by CyberDem0n** [comment]
> I do not understand where the host is explicitly specified, I do grep throughout the project and do not find a similar address at all. It looks like the configuration is sent to the subordinate by the leader, which is wrong. How to fix it?

Hi @ivan-da-ivan 
Magic doesn't exists. Either you are looking at the wrong config file, or these settings are coming from [environment variables](https://patroni.readthedocs.io/en/latest/ENVIRONMENT.html).
