### ISSUE TITLE
[QUESTION] Patroni callbacks getting killed

### ISSUE THREAD

**Issue by RajKiranS** [zalando/patroni#2445]
We have noticed that Patroni itself is killing the callback it had just fired. Wanted to understand the reason behind it. And its happening randomly for different set of roles too.
```
Oct 31 10:28:06 foo.com patroni-foo: 2022-10-31 10:28:06,975 WARNING: Killed ['/usr/bin/patroni-callback-handler', '/etc/foo/patroni-callback.yaml', 'on_role_change', 'master', 'foo'] because it was still running
```
Why and when does this happen? How to prevent it?

Thanks in advance.

**Comment by CyberDem0n** [comment]
Well, there was some other callback executed, but the previous was still running.
In order not to get to the race condition the previous is killed.

**Comment by RajKiranS** [comment]
Yes, that is correct! In next 11 seconds, `on_reload` callback was fired because it assigned `synchronous_standby` to a replica.

But, how do we avoid such killings? That particular callback for `on_role_change` is very important as it would update and restart few things. Is there a flag to toggle such behavior? Having some configurable timeout makes sense than killing it..

**Comment by CyberDem0n** [comment]
Well, there are two questons:
1. why it takes so long to execute callback script?
2. what do you need the on_reload callback for?

**Comment by RajKiranS** [comment]
> why it takes so long to execute callback script?

We do restart a couple of services on the restart and that could sometimes take a while. And in this case, the on_reload callback was fired just within 11seconds...

> what do you need the on_reload callback for?

We do not need this... Is there a way to disable it?

**Comment by CyberDem0n** [comment]
> We do not need this... Is there a way to disable it?

Remove it from the patroni.yaml?

**Comment by RajKiranS** [comment]
> Remove it from the patroni.yaml?

Thought that they were mandatory! Will try this out. Thank you!

**Comment by RajKiranS** [comment]
Thanks @CyberDem0n . Removing unwanted callbacks has helped. Closing.
