### ISSUE TITLE
How to get password from wallet/password storage service

### ISSUE THREAD

**Issue by t-ushar** [zalando/patroni#2448]
**How to get password from wallet /password storage service**
Is there any way we can get the password from any wallet /password storage service and avoid storing the password in .pgpass ? Ex - Patroni will fetch the password from secret/wallet during run time and make the DB connection.

**Comment by CyberDem0n** [comment]
One way or another passwords will be stored on a file system.
Even if your wallet is password and/or certificate protected the last ones should still be stored somewhere where Patroni has an access.
With the same success you can configure authentication with client certificates.
