### ISSUE TITLE
[kubernetes] Patroni patch Postgres pods metadata each 10 sec that generate load on policy engine

### ISSUE THREAD

**Issue by YvesZelros** [zalando/patroni#2453]
**Describe**

Patroni patch Postgres pods metadata each 10 sec to update the annotations status with typical content :
```apiVersion: v1
kind: Pod
metadata:
  annotations:
    status: '{"conn_url":"postgres://10.10.2.105:5432/postgres","api_url":"http://10.10.2.105:8008/patroni","state":"running","role":"master","version":"2.1.4","xlog_location":181875880888,"timeline":99}'
```

As _xlog_location_ change each time, it's generate a call to all web-hook present on the cluster.
If many database are deployed it's generate lot load on _PodSecurity Admission Controller_ installed on the cluster like _kyverno.io_

**To Reproduce**
Occur only on cluster mode (more than one instance).

**Expected behavior**
status (and  xlog_location) must be store on pod:status in place of pod:metadata:annotations

**Comment by CyberDem0n** [comment]
> It's generate cpu load on admission webhooks of PodSecurity Admission Controller.

I am pretty sure you can make an exception for Patroni pods.

> As the annotation contain the api_url, isn't possible to call this Api to get the value of xlog_location and avoid to add it on pod annotation ?

Well, it could be possible, yes, but it will make a behaviour of K8s DCS implementation different from others.
