### ISSUE TITLE
The kubernetes folder of examples of the Docker image has problem

### ISSUE THREAD

**Issue by yinan8128** [zalando/patroni#2454]
https://patroni.readthedocs.io/en/latest/kubernetes.html indicate that use https://github.com/zalando/patroni/tree/master/kubernetes to setup the docker env, but it shows below error
"Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/stretch-pgdg/main/binary-amd64/Packages"

**To Reproduce**
service docker status
docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2022-11-09 05:14:01 UTC; 2min 59s ago

docker --version
Docker version 20.10.21, build baeda1f

cd /opt
apt-get install git
git clone https://github.com/zalando/patroni.git
cd patroni/kubernetes
export YOUR_TAG=patronikubernetesimage
docker build --tag $YOUR_TAG .

Sending build context to Docker daemon  39.94kB
Step 1/9 : FROM postgres:11
11: Pulling from library/postgres
bff3e048017e: Pull complete
e3e180bf7c2b: Pull complete
62eff3cc0cff: Pull complete
3d90a128d4ff: Pull complete
ba4ce0c5ab29: Pull complete
a8f4b87076a9: Pull complete
4b437d281a7e: Pull complete
f1841d9dcb17: Pull complete
bf897300657d: Pull complete
3bfdfb831df4: Pull complete
c44ac1fcc543: Pull complete
9ad3441d354a: Pull complete
2d79312566dd: Pull complete
Digest: sha256:5d2aa4a7b5f9bdadeddcf87cf7f90a176737a02a30d917de4ab2e6a329bd2d45
Status: Downloaded newer image for postgres:11
 ---> 60a93af0bba5
Step 2/9 : MAINTAINER Alexander Kukushkin <alexander.kukushkin@zalando.de>
 ---> Running in 0f99effbdeb8
Removing intermediate container 0f99effbdeb8
 ---> e22ab1915ca4
Step 3/9 : RUN export DEBIAN_FRONTEND=noninteractive     && echo 'APT::Install-Recommends "0";\nAPT::Install-Suggests "0";' > /etc/apt/apt.conf.d/01norecommend     && apt-get update -y     && apt-get upgrade -y     && apt-cache depends patroni | sed -n -e 's/.* Depends: \(python3-.\+\)$/\1/p'             | grep -Ev '^python3-(sphinx|etcd|consul|kazoo|kubernetes)'             | xargs apt-get install -y vim-tiny curl jq locales git python3-pip python3-wheel     && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8     && pip3 install setuptools     && pip3 install 'git+https://github.com/zalando/patroni.git#egg=patroni[kubernetes]'     && PGHOME=/home/postgres     && mkdir -p $PGHOME     && chown postgres $PGHOME     && sed -i "s|/var/lib/postgresql.*|$PGHOME:/bin/bash|" /etc/passwd     && chmod 775 $PGHOME     && chmod 664 /etc/passwd     && apt-get remove -y git python3-pip python3-wheel     && apt-get autoremove -y     && apt-get clean -y     && rm -rf /var/lib/apt/lists/* /root/.cache
 ---> Running in cd92cba5b1a6
 Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [59.1 kB]
Ign:3 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease
Get:4 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
Ign:5 http://apt.postgresql.org/pub/repos/apt stretch-pgdg Release
Get:6 http://deb.debian.org/debian stretch Release [118 kB]
Ign:7 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages
Get:8 http://deb.debian.org/debian stretch Release.gpg [3,177 B]
Ign:9 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main all Packages
Ign:10 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/11 amd64 Packages
Ign:11 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/11 all Packages
Ign:7 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages
Ign:9 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main all Packages
Ign:10 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/11 amd64 Packages
Ign:11 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/11 all Packages
Ign:7 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages
Ign:9 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main all Packages
Ign:10 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/11 amd64 Packages
Ign:11 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/11 all Packages
Get:12 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [782 kB]
Ign:7 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages
Ign:9 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main all Packages
Ign:10 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/11 amd64 Packages
Ign:11 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/11 all Packages
Ign:7 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages
Ign:9 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main all Packages
Ign:10 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/11 amd64 Packages
Ign:11 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/11 all Packages
Err:7 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main amd64 Packages
  404  Not Found [IP: 147.75.85.69 80]
Ign:9 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/main all Packages
Ign:10 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/11 amd64 Packages
Ign:11 http://apt.postgresql.org/pub/repos/apt stretch-pgdg/11 all Packages
Get:13 http://deb.debian.org/debian stretch/main amd64 Packages [7,080 kB]
Fetched 8,135 kB in 4s (1,796 kB/s)
Reading package lists...
W: The repository 'http://apt.postgresql.org/pub/repos/apt stretch-pgdg Release' does not have a Release file.
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/stretch-pgdg/main/binary-amd64/Packages  404  Not Found [IP: 147.75.85.69 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c export DEBIAN_FRONTEND=noninteractive     && echo 'APT::Install-Recommends "0";\nAPT::Install-Suggests "0";' > /etc/apt/apt.conf.d/01norecommend     && apt-get update -y     && apt-get upgrade -y     && apt-cache depends patroni | sed -n -e 's/.* Depends: \(python3-.\+\)$/\1/p'             | grep -Ev '^python3-(sphinx|etcd|consul|kazoo|kubernetes)'             | xargs apt-get install -y vim-tiny curl jq locales git python3-pip python3-wheel     && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8     && pip3 install setuptools     && pip3 install 'git+https://github.com/zalando/patroni.git#egg=patroni[kubernetes]'     && PGHOME=/home/postgres     && mkdir -p $PGHOME     && chown postgres $PGHOME     && sed -i "s|/var/lib/postgresql.*|$PGHOME:/bin/bash|" /etc/passwd     && chmod 775 $PGHOME     && chmod 664 /etc/passwd     && apt-get remove -y git python3-pip python3-wheel     && apt-get autoremove -y     && apt-get clean -y     && rm -rf /var/lib/apt/lists/* /root/.cache' returned a non-zero code: 100

**Comment by CyberDem0n** [comment]
Debian stretch is EOL. I don't know why the postgres:11 image is still relying on it.
Maybe you need to do a `docker pull postrges:11`? Or bump version to something more modern like 15.

**Comment by yinan8128** [comment]
After change to "FROM postgres;15" and build, try to run container shows errors "Failed to import..."

**To Reproduce**
export YOUR_TAG=patronikubernetesimage
docker build --tag $YOUR_TAG .

docker image ls
REPOSITORY               TAG       IMAGE ID       CREATED          SIZE
patronikubernetesimage   latest    dff8a60b0f93   28 minutes ago   425MB
postgres                 15        6e5b7c4abf29   3 days ago       379MB
postgres                 11        60a93af0bba5   4 months ago     284MB
hello-world              latest    feb5d9fea6a5   13 months ago    13.3kB

docker run -it patronikubernetesimage:latest

2022-11-14 10:11:52,556 INFO: Failed to import patroni.dcs.consul
2022-11-14 10:11:52,557 INFO: Failed to import patroni.dcs.etcd
2022-11-14 10:11:52,559 INFO: Failed to import patroni.dcs.etcd3
2022-11-14 10:11:52,560 INFO: Failed to import patroni.dcs.exhibitor
2022-11-14 10:11:52,561 INFO: Failed to import patroni.dcs.raft
2022-11-14 10:11:52,562 INFO: Failed to import patroni.dcs.zookeeper
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/patroni/__main__.py", line 135, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.9/dist-packages/patroni/daemon.py", line 106, in abstract_main
    controller = cls(config)
  File "/usr/local/lib/python3.9/dist-packages/patroni/__main__.py", line 25, in __init__
    self.dcs = get_dcs(self.config)
  File "/usr/local/lib/python3.9/dist-packages/patroni/dcs/__init__.py", line 110, in get_dcs
    raise PatroniFatalException("""Can not find suitable configuration of distributed configuration store
patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: kubernetes'

**Comment by CyberDem0n** [comment]
> docker run -it patronikubernetesimage:latest

You can't run it as a standalone image. It must be deployed on K8s with proper configuration propagated from ENV variables.
