### ISSUE TITLE
Patroni fails to deregister service in Consul

### ISSUE THREAD

**Issue by wdenbakker** [zalando/patroni#2455]
**Describe the bug**
It seems Patroni is using a very old version of the "python-consul" dependency, which still uses a GET request to deregister in Consul. Consul expects a PUT request since [v1.8 (and maybe older)](https://developer.hashicorp.com/consul/api-docs/v1.8.x/agent/service#deregister-service). In v1.13.3 of Consul (and maybe older as well) it does not accept this anymore resulting in `[ERROR] agent.http: Request error: method=GET url=/v1/agent/service/deregister/xxxx from=127.0.0.1:34620 error="method GET not allowed"`.

**To Reproduce**
Setup a Patroni cluster with the latest version of Consul. Stop one of the Patroni instances. See that it is still registered in consul (but with a failing health check).

**Environment**
- Patroni version: 2.1.4
- PostgreSQL version: 14.5
- DCS (and its version): Consul 1.13.3

**Patroni configuration file**
```
consul:
  host: localhost:8500
  register_service: true
  token: XXXXX
```

**Comment by CyberDem0n** [comment]
It was fixed in the master branch, but never released.
You can install `python-consul2` module instead
