### ISSUE TITLE
Single binary release

### ISSUE THREAD

**Issue by alkersan** [zalando/patroni#247]
Are there any plans to distribute `Patroni` as single binary? For example [docker-compose](https://github.com/docker/compose/blob/master/docker-compose.spec) or [dcos-cli](https://github.com/dcos/dcos-cli/blob/master/cli/binary/binary.spec) provide convenient binary packaging via PyInstaller.
If there is any interest, I could work on pull request.

**Comment by JamesClonk** [comment]
I'd very much interested in having just one single release package, that would be great! :+1:

**Comment by alkersan** [comment]
@JamesClonk, here is my initial [attempt](https://github.com/zalando/patroni/compare/master...alkersan:master). After some trial and error it passes analysis and packaging phases. Didn't check for correct functioning of all DCS yet. It would be great if someone could point to any kind of acceptance test.

**Comment by CyberDem0n** [comment]
@alkersan, please create a pull request.
I've already looked into your changes, and found out that you had problems with dynamic imports of DCS implementations, because modules were searched with `os.listdir.

https://github.com/zalando/patroni/pull/253 should solve this problem.

**Comment by alexeyklyukin** [comment]
I think this is already done at https://github.com/zalando/patroni/pull/290
