### ISSUE TITLE
Package patroni-etcd-2.1.5-2.rhel8.x86_64 seems to be broken

### ISSUE THREAD

**Issue by nick-ivanov-edb** [zalando/patroni#2477]
**Describe the bug**

Installation of the latest patroni-etcd package fails with 

```
 Problem: cannot install the best candidate for the job
  - nothing provides etcd needed by patroni-etcd-2.1.5-2.rhel8.x86_64
```

Installing the previous (2.1.4) version works fine using `dnf install patroni-etcd-2.1.4`

**To Reproduce**
```
dnf install patroni-etcd
```

**Expected behavior**
Successful completion of the `dnf install` command.

**Screenshots**

**Environment**
- Patroni version: 2.1.5
- PostgreSQL version: 14.5
- DCS (and its version): etcd 3.5.1

**Patroni configuration file**

N/A -- fails to install

**patronictl show-config**

N/A -- fails to install

**Have you checked Patroni logs?**

N/A -- fails to install

**Have you checked PostgreSQL logs?**

N/A -- fails to install

**Have you tried to use GitHub issue search?**

Not found.

**Additional context**

**Comment by matthbakeredb** [comment]
I was going to bring this up before but this prompts me...

The `patroni-etcd` is a set of python libraries acting as a client package, `etcd` is a server/client binary package. The python package uses `python-etcd` which doesn't need `etcd` to be installed on the same node. It communicates with the etcd server over the network, not calling etcd binaries. A valid topology would be to have `etcd` installed and running on separate nodes to the patroni nodes. I might not want to install etcd on the same node as patroni.

So, `patroni-etcd` shouldn't **depend** on `etcd`?

**Comment by matthbakeredb** [comment]
However, this currently requires PGDG `extras` repo to be enabled as `etcd` is built for RHEL there.

https://download.postgresql.org/pub/repos/yum/common/pgdg-rhel8-extras/redhat/rhel-8-x86_64/

**Comment by devrimgunduz** [comment]
Hi,

Thanks for the report @nick-ivanov-edb and thanks @matthbakeredb for the analysis. 2.1.7-1 packages will include fix for this (they  will appear to repos in an hour)

Regards, Devrim
