### ISSUE TITLE
Wrong file format on WIN32

### ISSUE THREAD

**Issue by martinmarques** [zalando/patroni#2492]
In the `find_executable()` function that is used to find if a program is available or not, for WIN32 there is code that appends `.exe` to the name of the current file name passed doesn't have `.exe` as the file extension.

What should really happen is that the extension should be added only when there is no extension (this is a big difference between how executables are seen in UNIX environments and in WIN32).

As an example, the pager code in `ctl.py` calls `find_executable()`, and if running in WIN32 platform it will pass the argument `more.com` which the current code replaces with `more.com.exe`.

**Comment by martinmarques** [comment]
I'll push a PR soon

**Comment by CyberDem0n** [comment]
Closed with https://github.com/zalando/patroni/pull/2493
