### ISSUE TITLE
[QUESTION] Using patroni with pg_partman

### ISSUE THREAD

**Issue by phuonghuynguyen** [zalando/patroni#2494]
Hi currently I'm planning to use patroni with pg_partman for rotating old data. 
Basically pg_partman is an extension that automatically creates/removes partitioned tables. I installed pg_partman and tested on the master node, it worked fine when data was pushed to the master; It auto creates new partitioned tables on both master and replication node. However, what happens when master downs and one of the replication node becomes the new master? 
Do I have to set the old master to be consistent master when it ups again or do I have to install pg_partman on all nodes? For the second context, since replication nodes is read-only so we cannot create extension on those nodes.
Any advice for using these 2 solutions together?
Thx in advance!

**Comment by CyberDem0n** [comment]
Your question has nothing to do with Patroni.
The partman extension files MUST be installed on all nodes.
