### ISSUE TITLE
Looking for the OpenAPI spec for the Patroni REST APIs

### ISSUE THREAD

**Issue by kumar1202** [zalando/patroni#2500]
**Describe the bug**
This isn't a bug per se, but I am looking for the OpenAPI spec file(yaml/json in any format) for the Patroni REST APIs so that I can create a Ruby client for the same.

**Comment by CyberDem0n** [comment]
There is no such thing.
Only the [documentation](https://patroni.readthedocs.io/en/latest/rest_api.html) and the source code: https://github.com/zalando/patroni/blob/e5d750e9b8f7fc6a4172932056eddeb3fc892e7f/patroni/api.py#L97-L593

**Comment by kumar1202** [comment]
Thanks, closing the issue.

**Comment by simPod** [comment]
@kumar1202 I've started with it here https://github.com/cdn77/patroni-openapi
