### ISSUE TITLE
Communicating with DCS from Master

### ISSUE THREAD

**Issue by uspen** [zalando/patroni#251]
Hello!

I have 3 node etcd and 3 node postgres. If Master Postgres do not have network communication with all etcd nodes, patroni not failover.

Slave nodes log:
WARNING: Master (pgsql2) is still alive
INFO: following a different leader because i am not the healthiest node

If I stop patroni on Master, then failover will work

**Comment by CyberDem0n** [comment]
Hi. I guess you cut off connection from the master node to the etcd cluster by your hands.
Is it right? If it is - which Patroni version do you run?

**Comment by uspen** [comment]
Yes, right! v1.0

**Comment by CyberDem0n** [comment]
When master was cut

**Comment by CyberDem0n** [comment]
I expect behavior you describe to happen for version 0.9, but not for 1.0...
Master should restart in read-only mode when it can't communicate with etcd...
Can you show logs from the master and one of the replicas?

**Comment by uspen** [comment]
Yes, true! But this happened if (my example) iptables -j REJECT. If -j DROP....not failover.

[Master](http://pastebin.com/AjWu1tZd)
[Replica](http://pastebin.com/H8rPCeec)

**Comment by uspen** [comment]
Hm. No, if REJECT not every failover (

**Comment by CyberDem0n** [comment]
Ahha! xlog.replated_location on the former master  (it demoted itself and running in readonly) is ahead of any other replica, so Patroni is absolutely right, when refusing to failover. Somehow your replicas were not fast enough to receive and apply latest changes.

And by the way, you are missusing replicate_from tag, it is designed to build cascading replication and it must contain only one name of the node, which should be used to replicate from. In your case it's better to remove this tag completely.

**Comment by uspen** [comment]
Ok, i removed tag and restart patroni. Don't working. If iptables DROP. If REJECT - working
[Master](http://pastebin.com/uk0BKtBr)
[Replica](http://pastebin.com/j7p0h6SS)

**Comment by CyberDem0n** [comment]
Got it. It is really a bug :(
Instead of retrying request to the etcd with another node it is trying to fetch new topology of etcd cluster, what is taking incredibly long, in your case about 150 seconds.
read_timeout=10
amount of nodes=3 but each node reports itself two times

So in the list there were 5 elements. With each url it tries to perform `GET /v2/machines` request 3 times with 10 sec. timeout.
5*3*10 = 150...

Hope https://github.com/zalando/patroni/pull/254 will fix it

**Comment by uspen** [comment]
Yes, thank you!
In my case, I am completely isolated from the master of all etcd cluster. But even I noticed the same behavior even if isolated from only one node etcd

**Comment by CyberDem0n** [comment]
Usually if you are isolated from etcd you are also isolated from other nodes as well.

And by the way, you need to reconfigure your etcd cluster, because each node announces itself twice, on port 2379 and 4001. For Patroni it looks like you etcd cluster of 6 nodes...
