### ISSUE TITLE
Regression tests fail with python3.7 (Debian buster/Ubuntu bionic)

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#2512]
**Describe the bug**

Starting from 2.1.6, the regression tests fail like this for older python versions (python3.7):

```
19:56:18 ==================================== ERRORS ====================================
19:56:18 __________________ ERROR collecting tests/test_kubernetes.py ___________________
19:56:18 /usr/lib/python3.7/doctest.py:932: in find
19:56:18     self._find(tests, obj, name, module, source_lines, globs, {})
19:56:18 /usr/lib/python3.7/doctest.py:991: in _find
19:56:18     if ((inspect.isroutine(inspect.unwrap(val))
19:56:18 /usr/lib/python3.7/inspect.py:515: in unwrap
19:56:18     raise ValueError('wrapper loop when unwrapping {!r}'.format(f))
19:56:18 E   ValueError: wrapper loop when unwrapping call
```

**To Reproduce**

Run regression tests on Ubuntu bionic.

**Expected behavior**

Regression tests pass.

**Environment**
- Patroni version: 2.1.6
- PostgreSQL version: n/a
- DCS (and its version): n/a

**Comment by CyberDem0n** [comment]
@mbanck could you please be more specific, are you talking about unit tests or behave?
Unit tests are executed from GH Actions for every commit and also include python 3.7: https://github.com/zalando/patroni/actions/runs/3822463219/jobs/6503362757#step:11:15

**Comment by mbanck** [comment]
Sorry yes, I meant unit tests.

If they pass with python3.7, then it must be something else in the environment for buster/bionic. The test results/logfiles are here:

https://pgdgbuild.dus.dg-i.net/job/patroni-binaries/189/architecture=amd64,distribution=buster/consoleFull#console-section-49
https://pgdgbuild.dus.dg-i.net/job/patroni-binaries/189/architecture=amd64,distribution=bionic/consoleFull#console-section-9

**Comment by mbanck** [comment]
I looks like it fails during coverage collection, not the unit tests themselves.

**Comment by CyberDem0n** [comment]
Seems to be related to https://github.com/zalando/patroni/pull/2465

**Comment by mbanck** [comment]
The jobs take ages because they run the behave tests for all postgres versions and dcs types, so it will take a while till I get a result...

**Comment by mbanck** [comment]
At least bionic was successful (this one only runs the basic_replication scenario for each), while buster is still running.

**Comment by mbanck** [comment]
And buster as well now
