### ISSUE TITLE
WRITES not blocked even with synchronous_mode_strict=TRUE

### ISSUE THREAD

**Issue by nijesh8** [zalando/patroni#2525]
We configured Synchronous Replication and was doing testing to ensure WRTIES are BLOCKED if Standbys are down.

But while testing we noticed that INSERTS are NOT FULLY blocked on the LEADER pod even with parameter 
"synchronous_mode_strict" = TRUE.

Question: 
1. How do we ensure that INSERT/UPDATE/DELETE are completely blocked in a SYNCHRONOUS STANDBY environment ? 
	Note: We WANT the WRITES to be completely blocked if ALL STANDBYS are down.

SUMMARY:
=============
Simulating a Network isolation scenario for a Patroni Postgres Cluster with 5 Synchronous Standbys 
spread across 2 data centers , we did the below:

	1. configured to strictly block writes ("synchronous_mode_strict" = TRUE.)
	2. crashed all Standbys (kill -9 postmaster process)
	3. with one client accessing the leader, all sessions with DML activity were successful
	4. The above was contradicting the patroni Documentation with  "synchronous_mode_strict" = TRUE.

Reference:
	https://patroni.readthedocs.io/en/latest/replication_modes.html?highlight=synchronous_mode_strict#synchronous-mode

Test environment:
==================
1. Patroni 2.1.5
2. PostgreSQL 15.1
3. Kubernetes pods with PGDATA filesystem on PVC.
4. Client : Python Script from HAPROXY pod. 
5. Leader Pod + 5 Standbys
6. SYNC parameters 

	synchronous_mode: true
	synchronous_mode_strict: true
	synchronous_node_count: 2

	+ Cluster: pg15poc1 (7185641438832263275) --+--------------+---------+----+-----------+
	| Member                   | Host           | Role         | State   | TL | Lag in MB |
	+--------------------------+----------------+--------------+---------+----+-----------+
	| pg15poc1-fss-lvs-4-xxbbz | 10.xx.yy.54    | Replica      | running | 24 |         0 |
	| pg15poc1-fss-lvs-5-xxjfz | 10.xx.yy.128   | Sync Standby | running | 24 |         0 |
	| pg15poc1-fss-lvs-6-xxthe | 10.xx.yy.81    | Sync Standby | running | 24 |         0 |
	| pg15poc1-fss-slc-1-yy4cb | 10.xx.zz.210   | Replica      | running | 24 |         0 |
	| pg15poc1-fss-slc-2-yy4cw | 10.xx.zz.128   | Replica      | running | 24 |         0 |
	| pg15poc1-fss-slc-3-yyhac | 10.xx.zz.73    | Leader       | running | 24 |           |
	+--------------------------+----------------+--------------+---------+----+-----------+

7. Entire YAML file:
	+--------------------------+----------------+--------------+---------+----+-----------+
	loop_wait: 1
	maximum_lag_on_failover: 1048576
	postgresql:
	  parameters:
	    archive_cleanup_command: pg_archivecleanup -d /arch/wal_archive %r  >> /home/postgres/wal_arch_cleanup.log 2>&1
	    archive_command: cp %p /arch/wal_archive/%f
	    archive_mode: false
	    log_autovacuum_min_duration: 0
	    log_connections: false
	    log_destination: stderr
	    log_directory: log
	    log_filename: postgresql.log
	    log_line_prefix: '%m [%p] '
	    log_min_duration_statement: 60
	    log_min_messages: debug1
	    log_rotation_age: 0
	    log_statement: ddl
	    logging_collector: true
	    max_connections: 2000
	    pg_stat_statements.track: all
	    shared_buffers: 900MB
	    shared_preload_libraries: pg_stat_statements
	    synchronous_commit: true
	    track_activity_query_size: 2048
	    wal_keep_size: 4096
	    wal_receiver_timeout: 20s
	    wal_sender_timeout: 20s
	  use_pg_rewind: true
	  use_slots: true
	retry_timeout: 2
	synchronous_mode: true
	synchronous_mode_strict: true
	synchronous_node_count: 2
	ttl: 6
	+--------------------------+----------------+--------------+---------+----+-----------+

Test 1: 
==================
1. Started the Continuous INSERT Python script from HAPROXY Pod, connecting to the Postgres MASTER pod.
	This script INSERT a ROW with CURRENT TIMESTAMP and also SELECT the MAX Row inserted.

2. At TIME T1, 
-------------------
	Stopped all 5 standbys. (Kill -9 postmaster process)
		(Also changed PGDATA directory permission [ chmod o+rx $PGDATA], so that Patroni will not restart the Postgres processes)

3. Python script from HAPROXY continued to run.
	It was appeared to be hanging.

4. It timed out. But HAPROXY client reconnected after 1 minute and Reattempted the INSERT.

Observation: DMLS are NOT BLOCKED.
				Since the Python script was able to INSERT + SELECT the MAX Row Inserted.

Expected Result: 
================
As per Patroni Documentation, All WRITES MUST BE completely blocked, if "synchronous_mode_strict" = TRUE.

	https://patroni.readthedocs.io/en/latest/replication_modes.html?highlight=synchronous_mode_strict#synchronous-mode

TEST 2:
===============
1. After TIME T1 , using PSQL, when I tried an INSERT , the session was hung.

2. But when I cancelled the INSERT statement in PSQL using CTRL-C, got the below message: 

		postgres=# INSERT INTO HATEST VALUES(CURRENT_TIMESTAMP) RETURNING TM ;

		^CCancel request sent
		WARNING:  canceling wait for synchronous replication due to user request
		DETAIL:  The transaction has already committed locally, but might not have been replicated to the standby.

Observation:
================
Transaction committed locally in spite of unavailable Standbys in a Cluster with  SYNCHRONOUS STANDBY configuration.

Expected Result: 
================
DML or the WRITES MUST BE completely blocked

Reference:
	 https://patroni.readthedocs.io/en/latest/replication_modes.html?highlight=synchronous_mode_strict#synchronous-mode

**Comment by CyberDem0n** [comment]
> Transaction committed locally in spite of unavailable Standbys in a Cluster with SYNCHRONOUS STANDBY configuration.

This is exactly how Postgres works. Any transaction is always first committed on the primary. After that it keeps locks and waits for a confirmation from sync standbys.
If you interrupt waiting state by any means changes done by transaction become visible. You can't blame Patroni for that.
