### ISSUE TITLE
How to speed up the creation of postgres replicas

### ISSUE THREAD

**Issue by cobolbaby** [zalando/patroni#2527]
**Describe the bug**

If the database storage uses a Raid disk (HDD), initializing the replica using the default pg_basebackup method takes a lot of time.

By default, pg_basebackup adopts non-compression mode, does Patroni support configuring it as compression mode? If it is not currently supported, is it possible to consider using pigz to implement streaming decompression in the future? Refer: https://www.cybertec-postgresql.com/en/speeding-up-creation-of-postgres-replicas/

I had a try. Compared with before, the data recovery speed is more than doubled.

However, **there is a problem with the state of the stanby node after recovery**. The standby node keeps printing the following log information `record with incorrect prev-link 10/1D0B7F at 1F00/CF0000A0`

**To Reproduce**

1. pg_basebackup -U postgres -D - -Ft -X fetch -v | pigz -6 -p 32 > ${BACKUP_DIR}/physical_backup.tgz (master node)
2. scp physical_backup.tgz ${username}@${host}:
3. tar -zxf physical_backup.tgz -C ${pgdata}
4. patroni patronictl.yaml
5. patronictl list && check $PGDATA/pg_log

**Expected behavior**

**Screenshots**

**Environment**
- Patroni version: 2.1.4
- PostgreSQL version: 12.12
- DCS (and its version): Etcd3

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**

**Comment by CyberDem0n** [comment]
Have you tried reading the documentation?
https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#building-replicas

**Comment by cobolbaby** [comment]
Refer: https://www.cybertec-postgresql.com/en/speeding-up-creation-of-postgres-replicas/

```bash
# pseudocode on the replica
# 1. start streaming of WALs
pg_receivexlog -h master -D streamed_wals
# 2. start the parallel (2 threads) streamed base backup
ssh master "pg_basebackup -h /unix/socket -Ft -D- | pigz -c -p2 " | pigz -cd -p2 | tar -xf- -C pgdata
# 3. stop WAL streaming and move WALs to XLOG folder
pkill pg_receivexlog && mv streamed_wals/* pgdata/pg_xlog
# 4. edit configs and start the replica
```

**Comment by CyberDem0n** [comment]
> Refer

And? How is that qualifies as Patroni problem?
Patroni gives you all controls to implement it with helper scripts.
