### ISSUE TITLE
 Available implementations: """ + ', '.join(sorted(set(available_implementations))))

### ISSUE THREAD

**Issue by shunyaio** [zalando/patroni#2529]
**Describe the bug**
We have 2 node pgsql cluster on centos 8 
##
[root@pg1 patroni]# cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
[root@pg1 patroni]# uname -a
Linux pg1 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

##

**To Reproduce**
[root@pg1 patroni]# systemctl status patroni
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/usr/lib/systemd/system/patroni.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2023-01-18 00:24:29 EST; 5s ago
  Process: 5119 ExecStart=/usr/bin/patroni /etc/patroni/patroni.yml (code=exited, status=1/FAILURE)
 Main PID: 5119 (code=exited, status=1/FAILURE)

Jan 18 00:24:29 pg1 patroni[5119]:     abstract_main(Patroni, schema)
Jan 18 00:24:29 pg1 patroni[5119]:   File "/usr/lib/python3.6/site-packages/patroni/daemon.py", line 106, in abstract_main
Jan 18 00:24:29 pg1 patroni[5119]:     controller = cls(config)
Jan 18 00:24:29 pg1 patroni[5119]:   File "/usr/lib/python3.6/site-packages/patroni/__main__.py", line 25, in __init__
Jan 18 00:24:29 pg1 patroni[5119]:     self.dcs = get_dcs(self.config)
Jan 18 00:24:29 pg1 patroni[5119]:   File "/usr/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 111, in get_dcs
Jan 18 00:24:29 pg1 patroni[5119]:     Available implementations: """ + ', '.join(sorted(set(available_implementations))))
Jan 18 00:24:29 pg1 patroni[5119]: patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distr>
Jan 18 00:24:29 pg1 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Jan 18 00:24:29 pg1 systemd[1]: patroni.service: Failed with result 'exit-code'.

**Expected behavior**
[root@pg1 patroni]# systemctl status patroni
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/usr/lib/systemd/system/patroni.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2023-01-18 00:24:29 EST; 5s ago
  Process: 5119 ExecStart=/usr/bin/patroni /etc/patroni/patroni.yml (code=exited, status=1/FAILURE)
 Main PID: 5119 (code=exited, status=1/FAILURE)

Jan 18 00:24:29 pg1 patroni[5119]:     abstract_main(Patroni, schema)
Jan 18 00:24:29 pg1 patroni[5119]:   File "/usr/lib/python3.6/site-packages/patroni/daemon.py", line 106, in abstract_main
Jan 18 00:24:29 pg1 patroni[5119]:     controller = cls(config)
Jan 18 00:24:29 pg1 patroni[5119]:   File "/usr/lib/python3.6/site-packages/patroni/__main__.py", line 25, in __init__
Jan 18 00:24:29 pg1 patroni[5119]:     self.dcs = get_dcs(self.config)
Jan 18 00:24:29 pg1 patroni[5119]:   File "/usr/lib/python3.6/site-packages/patroni/dcs/__init__.py", line 111, in get_dcs
Jan 18 00:24:29 pg1 patroni[5119]:     Available implementations: """ + ', '.join(sorted(set(available_implementations))))
Jan 18 00:24:29 pg1 patroni[5119]: patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distr>
Jan 18 00:24:29 pg1 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Jan 18 00:24:29 pg1 systemd[1]: patroni.service: Failed with result 'exit-code'.

**Screenshots**

**Environment**
-   Patroni version:
-   PostgreSQL version:
-   DCS (and its version):
- [root@pg1 patroni]# rpm -qa|grep -i patroni
patroni-2.1.7-1.rhel8.x86_64
[root@pg1 patroni]# rpm -qa|grep -i postgres
postgresql12-12.13-1PGDG.rhel8.x86_64
postgresql11-11.18-1PGDG.rhel8.x86_64
postgresql12-server-12.13-1PGDG.rhel8.x86_64
postgresql11-libs-11.18-1PGDG.rhel8.x86_64
postgresql12-libs-12.13-1PGDG.rhel8.x86_64
postgresql11-devel-11.18-1PGDG.rhel8.x86_64
[root@pg1 patroni]# rpm -qa|grep -i etcd
python3-etcd-0.4.5-20.rhel8.noarch
etcd-3.2.21-2.el8.x86_64

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```
 cat patroni.yml
scope: postgres
namespace: /pg_cluster/
name: pg1
restapi:
  listen: 172.30.14.102:8008
  connect_address: 172.30.14.102:8008
etcd:
  host: 172.30.14.102:2379,172.30.14.103:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
initdb:
  - encoding: UTF8
  - data-checksums
pg_hba:
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator 172.30.14.102/0 md5
  - host replication replicator 172.30.14.103/0 md5
  - host all all 0.0.0.0/0 md5
users:
    admin:
      password: admin
      options:
        - createrole
        - createdb
postgresql:
  listen: 172.30.14.102:5432
  connect_address: 172.30.14.102:5432
  data_dir: /var/lib/pgsql/12/data
  bin_dir: /usr/pgsql-12/bin
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: replicator
      password: replicator
    superuser:
      username: postgres
      password: postgres
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
[root@pg1 patroni]#

**Have you checked Patroni logs?**
Please provide a snippet of Patroni log files here

**Have you checked PostgreSQL logs?**
Please provide a snippet here

**Have you tried to use GitHub issue search?**
Maybe there is already a similar issue solved.

**Additional context**
[root@pg1 patroni]# patronictl -c patroni.yml reload postgres
Error: postgres cluster doesn't have any members
[root@pg1 patroni]# patronictl -c patroni.yml list postgres
+ Cluster: postgres (uninitialized) +-----------+
| Member | Host | Role | State | TL | Lag in MB |
+--------+------+------+-------+----+-----------+
+--------+------+------+-------+----+-----------+
[root@pg1 patroni]# etcdctl --write-out=table --endpoints=localhost:2379 member list
+------------------+---------+------+---------------------------+---------------------+
|        ID        | STATUS  | NAME |        PEER ADDRS         |    CLIENT ADDRS     |
+------------------+---------+------+---------------------------+---------------------+
| 8391cc269861cbd6 | started |  pg1 | http://172.30.14.102:2380 | http://0.0.0.0:2379 |
| f6df999375c710b7 | started |  pg2 | http://172.30.14.103:2380 | http://0.0.0.0:2379 |
+------------------+---------+------+---------------------------+---------------------+

**Comment by shunyaio** [comment]
[root@pg1 patroni]# patronictl show-config
Traceback (most recent call last):
  File "/usr/bin/patronictl", line 11, in <module>
    load_entry_point('patroni==2.1.7', 'console_scripts', 'patronictl')()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 721, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1065, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 894, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/patroni/ctl.py", line 1260, in show_config
    click.echo(format_config_for_editing(cluster.config.data))
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by CyberDem0n** [comment]
> Have you tried to use GitHub issue search?
Maybe there is already a similar issue solved.

Rules are the same for everybody, you have to use GH search: https://github.com/zalando/patroni/issues?q=is%3Aissue+Can+not+find+suitable+configuration+is%3Aclosed+
