### ISSUE TITLE
pyinstaller relative import

### ISSUE THREAD

**Issue by zloyded** [zalando/patroni#2535]
```Traceback (most recent call last):
  File "patroni/__main__.py", line 6, in <module>
ImportError: attempted relative import with no known parent package```
while using `pyintaller --clean patroni.spec` for rpm pkg
Think need update patroni.spec for fix.

**Comment by zloyded** [comment]
And one more, after fix pyinstaller spec and successful build package, start failed with error:
` File "six.py", line 87, in _import_module
ModuleNotFoundError: No module named 'http.server'`

**Comment by CyberDem0n** [comment]
> after fix pyinstaller spec

Could you please elaborate more on that?
What exactly have you changed?

**Comment by zloyded** [comment]
> > after fix pyinstaller spec
> 
> Could you please elaborate more on that? What exactly have you changed?

i`ve fix locally pyinstaller  spec file 
`a = Analysis(['patroni.py'],
....`
and compile binary and run it i have 
`ModuleNotFoundError: No module named 'http.server'`
Build whith python 3.11.1, 3.10 3.9.16

**Comment by zloyded** [comment]
`File "patroni/api.py", line 15, in <module>
File "six.py", line 237, in create_module
File "six.py", line 213, in load_module
File "six.py", line 120, in _resolve
File "six.py", line 87, in _import_module
ModuleNotFoundError: No module named 'http.server'
patroni[5001]: [5002] Failed to execute script 'patroni' due to unhandled exception!`
