### ISSUE TITLE
Immediate demotion on k8s api auth failure

### ISSUE THREAD

**Issue by le-duane** [zalando/patroni#2536]
**Describe the bug**
Patroni demotes leader well before retry_timeout (50 seconds) after single auth failure.

**To Reproduce**
Not sure - transient failure unrelated to a k8s control plain upgrade.

**Expected behavior**
Patroni retries until retry_timeout reached

**Environment**
-   Patroni version: 2.1.4
-   PostgreSQL version: 13.8
-   DCS (and its version): k8s 1.21 in EKS

**patronictl show-config**
```
loop_wait: 10
master_start_timeout: 300
master_stop_timeout: 135
maximum_lag_on_failover: 0
retry_timeout: 50
synchronous_mode: true
ttl: 120
```

**Have you checked Patroni/PostgreSQL logs?**
```
2023-01-24 05:09:31,853 INFO: no action. I am (<patroni-instance>), the leader with the lock
2023-01-24 05:09:41,858 INFO: no action. I am (<patroni-instance>), the leader with the lock
2023-01-24 05:09:51,723 ERROR: Failed to get "kubernetes" endpoint from https://10.204.4.8:443: ApiException()
2023-01-24 05:09:51,738 INFO: Lock owner: <patroni-instance>; I am <patroni-instance>
2023-01-24 05:09:51,746 ERROR: Unexpected error from Kubernetes API
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 974, in _update_leader_with_retry
    return self._patch_or_create(self.leader_path, annotations, resource_version, ips=ips, retry=_retry)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 921, in _patch_or_create
    ret = retry(func, self._namespace, body) if retry else func(self._namespace, body)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 971, in _retry
    return retry(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/utils.py", line 334, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 483, in wrapper
    return getattr(self._core_v1_api, func)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 419, in wrapper
    return self._api_client.call_api(method, path, headers, body, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 388, in call_api
    return self._handle_server_response(response, _preload_content)
  File "/usr/local/lib/python3.6/site-packages/patroni/dcs/kubernetes.py", line 218, in _handle_server_response
    raise k8s_client.rest.ApiException(http_resp=response)
patroni.dcs.kubernetes.K8sClient.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': '06feefe4-77aa-48b4-aab4-06ed0ef1d441', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 24 Jan 2023 05:09:51 GMT', 'Content-Length': '129'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}\n'

2023-01-24 05:09:51,755 ERROR: failed to update leader lock
2023-01-24 05:09:51,755 INFO: Demoting self (immediate-nolock)
2023-01-24 05:09:51.755 UTC [123] LOG:  received immediate shutdown request
2023-01-24 05:09:51.761 UTC [19184] WARNING:  terminating connection because of crash of another server process
```

**Have you tried to use GitHub issue search?**
Yes, closed issue [1729](https://github.com/zalando/patroni/issues/1729)

**Additional context**
Can addressing this be re-visited? We have no means of getting ahead of this infra-side. Thanks!

**Comment by CyberDem0n** [comment]
> "status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401

I am afraid there is nothing possible to do about it. HTTP Status code 401 is not supposed to be retried.

**Comment by le-duane** [comment]
Thanks for the quick reply!

Instead of retrying, is it something which can be caught and suppressed until retry_timeout has been reached?

Also, would the new "DCS failsafe mode" feature have saved us here?

**Comment by CyberDem0n** [comment]
The DCS failsafe feature will not help because of the same reason. 401 isn't really a retriable error.

**Comment by le-duane** [comment]
Since about 1/3rd of our databases restarted - I think the only recourse for us is to move to ectd for our DCS, which hopefully proves to be more resilient.

Appreciate your time on this!

**Comment by CyberDem0n** [comment]
You really need to figure out why it responds 401. It could be an indicator that something is incorrect in K8s upgrade process

**Comment by le-duane** [comment]
We're using EKS (manages k8s service from AWS) and sadly am at their mercy. I'm still waiting to hear back from them on any events which might have caused it. Right now the best lead I have is [this](https://github.com/aws/containers-roadmap/issues/1810).

**Comment by le-duane** [comment]
@CyberDem0n sorry to bother you on this, but would you be able to link to documentation which states 401 should not be retried? Google has failed me on this.

I'm asking because AWS is telling me to just "retry your API operations until they succeed" and I would like to share the documentation in order to push back on this stance. Also, they finally confirmed that a minor version update of the API server took place during our outage timeframe.

**Comment by le-duane** [comment]
Thanks @CyberDem0n!

**Comment by oneumyvakin** [comment]
@CyberDem0n JFYI
You can get 401 Unauthorized from K8s API in case of high time drift between k8s API/etcd nodes.

Here is real world example when two requests executed in sequence produce different results:
```
root@postgresql-cluster-0:/home/postgres# curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "10.67.89.86:6443"
    }
  ]
}
root@postgresql-cluster-0:/home/postgres# curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

I'm sure that there are more than one reason when K8s API can return 401 Unauthorized.

**Comment by CyberDem0n** [comment]
@oneumyvakin this is called undefined behavior....
