### ISSUE TITLE
Patroni drops logical replication slots after demoting the primary

### ISSUE THREAD

**Issue by mzwettler2** [zalando/patroni#2539]
**Describe the bug**
An external agent created and used a logical replication slot.
This replication slot was dropped after Patroni demoted the primary.

It seems that Patroni drops any replication slot when there is no "slot" or "ignore_slot" configuration.
Is this a feature or a bug?

**To Reproduce**
- create a logical replication slot
- let patroni demote the primary 

**Environment**
-   Patroni version: 2,1.3
-   PostgreSQL version: 13.7
-   DCS (and its version): etcd

**Patroni configuration file**
we did **_not_** configure "slots" **_nor_** "ignore_slots" in the patroni.yaml file.

**Have you checked Patroni logs?**
2023-01-23 19:02:35,407 INFO: demoted self because failed to update leader lock in DCS
2023-01-23 19:02:35,408 INFO: closed patroni connection to the postgresql cluster
…
2023-01-23 19:02:58,264 INFO: promoted self to leader by acquiring session lock
2023-01-23 19:02:58,265 WARNING: Logical replication slots that might be unsafe to use after promote: {'dpagent_ffsstbe_back_slot', 'dpagent_ffsstbe_main_slot'}
 
=> afterwards the replication slots were gone.

**Comment by CyberDem0n** [comment]
> It seems that Patroni drops any replication slot when there is no "slot" or "ignore_slot" configuration.

Yes, it is expected. Any unknown slot is removed because it may cause uncontrolled growth of pg_wal.

**Comment by mzwettler2** [comment]
Thanks. Maybe you would like to update the docs this way?

**Comment by CyberDem0n** [comment]
> Maybe you would like to update the docs this way?

Feel free to submit a PR.
