### ISSUE TITLE
patronictl query --member always returns 'No connection to member xxxxxx is available'

### ISSUE THREAD

**Issue by XiuhuaRuan** [zalando/patroni#2540]
**Describe the bug**
When execting patronictl query --command --member, the result always returns  'No connection to member xxxxxx is available'.

**To Reproduce**
1. Set up postgresql database cluster with member ivorysql_01 and ivorysql_02
$ patronictl -c hghac-ivorysql.yml list
+ Cluster: ivorysql-cluster (7188818754809229782) ----+-----------+
| Member      | Host         | Role    | State   | TL | Lag in MB |
+-------------+--------------+---------+---------+----+-----------+
| ivorysql_01 | 10.0.127.215 | Replica | running |  2 |         0 |
| ivorysql_02 | 10.0.127.216 | Leader  | running |  2 |           |
+-------------+--------------+---------+---------+----+-----------+
2. patronictl query --command with role could return correct psql result.
$ patronictl -c hghac-ivorysql.yml query --command 'select * from pg_is_in_recovery()' -d postgres-r master
pg_is_in_recovery
False
3. patronictl query --command with member could NOT return psql result.
$ patronictl -c hghac-ivorysql.yml query --command 'select * from pg_is_in_recovery()' -d postgres -m ivorysql_01
2023-01-25 10:43:33     No connection to member ivorysql_01 is available
$ patronictl -c hghac-ivorysql.yml query --command 'select * from pg_is_in_recovery()' -d postgres -m ivorysql_02
2023-01-25 10:43:35     No connection to member ivorysql_02 is available
 4. patronictl query --command with both role and member returns 'Error: --role and --member are mutually exclusive options', which is expected.
$ patronictl -c hghac-ivorysql.yml query --command 'select * from pg_is_in_recovery()' -d postgres-m ivorysql_02 -r master
Error: --role and --member are mutually exclusive options

**Expected behavior**
patronictl query --command with member should return correct psql result.

**Screenshots**

**Environment**
-   Patroni version: 2.1.7
-   PostgreSQL version: 14.2
-   DCS (and its version): etcd3.3.11

**Patroni configuration file**
```
Please copy&paste your Patroni configuration file here
```
$ cat hghac-ivorysql.yml
scope: ivorysql-cluster
namespace: /service/
name: ivorysql_01

restapi:
  listen: 10.0.12.215:8008
  connect_address: 10.0.12.215:8008

etcd:
  hosts: 10.0.12.215:2379,10.0.12.216:2379,10.0.12.217:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      parameters:
        listen_addresses: "*"
        port: 5432
        wal_level: replica
        hot_standby: "on"
        wal_keep_size: 100
        max_wal_senders: 10
        max_replication_slots: 10
        wal_log_hints: "on"
        archive_mode: "off"
        archive_timeout: 1800s

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 10.0.127.215:5432
  data_dir: /usr/local/ivorysql/data
  bin_dir: /usr/local/ivorysql/bin
  config_dir: /usr/local/ivorysql/data

  authentication:
    replication:
      username: ivorysql
      password: ******
    superuser:
      username: ivorysql
      password: ******
    rewind:
      username: ivorysql
      password: ******

  pg_hba:
    - local   all             all                                     trust
    - host    all             all             0.0.0.0/0               trust
    - host    all             all             ::1/128                 trust
    - local   replication     all                                     trust
    - host    replication     all             0.0.0.0/0               trust
    - host    replication     all             ::1/128                 trust

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```
$ patronictl -c hghac-ivorysql.yml show-config
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_mode: 'off'
    archive_timeout: 1800s
    hot_standby: 'on'
    listen_addresses: '*'
    max_replication_slots: 10
    max_wal_senders: 10
    port: 5432
    wal_keep_size: 100
    wal_level: replica
    wal_log_hints: 'on'
  use_pg_rewind: true
retry_timeout: 10
synchronous_mode: false
ttl: 30

**Comment by CyberDem0n** [comment]
It works in the master branch:
```
$ patronictl -c postgres0.yml query -m postgresql0 -U postgres -c 'select 1 as test' --format pretty
+------+
| test |
+------+
| 1    |
+------+
```

If the problem existed it was fixed by https://github.com/zalando/patroni/pull/2504.
Just wait for a next release, that will happen in a few days.
