### ISSUE TITLE
Distribution: release patroni 3.0 rpm in official pgdg repo

### ISSUE THREAD

**Issue by Vonng** [zalando/patroni#2550]
The official PostgreSQL [repo](https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-7-x86_64/) still uses patroni 2.1.7. Looking forward to using 3.0.0 and trying the new features.

https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-7-x86_64/

Maybe include rpms/debs on the release page? ;)

**Comment by CyberDem0n** [comment]
Sorry, but no.
We will leave package management to skilled people responsible for pgdg repo.
Specifically for RPM it would be @devrimgunduz

**Comment by devrimgunduz** [comment]
For the archives: 3.0.0 RPMs are in the PostgreSQL RPM repos now.
