### ISSUE TITLE
Method:Delay Replica and HA Prod Advice

### ISSUE THREAD

**Issue by prensgold** [zalando/patroni#2551]
Hi ,
We have a 3 node patroni cluster.
We want to delay one of the nodes by 1 hour.
How can I do this without disrupting the other two nodes?

We want to provide disaster to our existing 3 node Patroni cluster in the remote region. We want our replicas in the remote region (on premise) to be Patroni cluster. In a 3rd region we want to achieve this without setting up a witness server. Is this possible for HA?
We also want to guarantee that the primary role will not change when the witness goes down.

When there is a problem in the first primary dc, manual switchover or failover to the second dc is an acceptable option for us.
Will adding 3 more 3 nodes in the second dc in addition to the existing 3 node patroni cluster in the first primary dc and adding the following parameters to those nodes solve my HA availibity issues?

    nofailover: true
    noloadbalance: true

Thanks

**Comment by CyberDem0n** [comment]
First of all, there is no concept of witness in Patroni.
Regarding delayed replica - it could be achieved by setting [recovery_min_apply_delay](https://www.postgresql.org/docs/current/runtime-config-replication.html#GUC-RECOVERY-MIN-APPLY-DELAY) GUC to the value `1h` via patroni.yaml, `postgresql.parameters` on one of the nodes.

There is also an option to run a delayed [standby cluster](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#standby-cluster). In parameters it also accepts `recovery_min_apply_delay`.

**Comment by prensgold** [comment]
Is the architecture below possible?

DC1 has
DC1node1 (Patroni + etcd leader + PostgreSQL master),
DC1node2 (Patroni + etcd follower + PostgreSQL replica) and
DC1node3 (Patroni + etcd follower + PostgreSQL replica)

standby cluster among them.

DC2 has
DC2node1 (Patroni + etcd follower + PostgreSQL replica)
DC2node2 (Patroni + etcd follower + PostgreSQL replica) and
DC2node2 (Patroni + etcd follower + PostgreSQL replica) (6h delay replica server)

is it correct architecture in production environment for remote regions?

Thanks

**Comment by CyberDem0n** [comment]
Yes, it is possible to have it.

**Comment by prensgold** [comment]
> First of all, there is no concept of witness in Patroni. Regarding delayed replica - it could be achieved by setting [recovery_min_apply_delay](https://www.postgresql.org/docs/current/runtime-config-replication.html#GUC-RECOVERY-MIN-APPLY-DELAY) GUC to the value `1h` via patroni.yaml, `postgresql.parameters` on one of the nodes.
> 
> There is also an option to run a delayed [standby cluster](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#standby-cluster). In parameters it also accepts `recovery_min_apply_delay`.

I set up the standby cluster.
after I ran the delay parameter on one of the servers on the standby side as follows.
> alter system set recovery_min_apply_delay='5min';select pg_reload_conf();

I get a warning in the log as follows.

>2023-02-20 11:14:03 +03 [68944]: [126-1] db=,user=,app=,client=  LOG:  received SIGHUP, reloading configuration files
>2023-02-20 11:14:03 +03 [68944]: [127-1] db=,user=,app=,client=  LOG:  parameter "recovery_min_apply_delay" removed from configuration file, reset to default


Patroni cluster does not allow this?

**Comment by CyberDem0n** [comment]
As I said, you need to do it in the patroni.yaml: https://github.com/zalando/patroni/issues/2551#issuecomment-1418611900

**Comment by prensgold** [comment]
> As I said, you need to do it in the patroni.yaml: [#2551 (comment)](https://github.com/zalando/patroni/issues/2551#issuecomment-1418611900)

and that's how I got the delay to work. Thank you very much.

I would like to test another scenario.
I want to stop the progress of replication on the delay server.

I failed with the following line, what am I missing.
SELECT pg_wal_replay_pause(); SELECT pg_get_wal_replay_pause_state();

**Comment by prensgold** [comment]
Now that I think about it;
if recovery_min_apply_delay is set to 6h, I can save time at the time of the problem by giving a larger delay time (such as 12h) at the time of the problem.
Is there any other solution method for such a problem?
Or should the logical flow be like this?
You can stop replication in oracle data guard at the time of the problem.

**Comment by CyberDem0n** [comment]
> I failed with the following line, what am I missing.
SELECT pg_wal_replay_pause(); SELECT pg_get_wal_replay_pause_state();

On Postgres v14+ Patroni will automatically resume WAL replay.
The problem is that it could be paused because for example `max_connections` on the primary was increased and it impacts HA.
Unfortunately there is no way to figure out why WAL replay was paused.What you can do -
