### ISSUE TITLE
Etcd higload

### ISSUE THREAD

**Issue by careless6666** [zalando/patroni#2555]
**Describe the bug**
Hello. Faced with the problem of watching events on etcd, at first there was a version below 2.1.5 where the recording of events was much more frequent, now we have switched to 2.1.5, but the number of events still remains large. If we look at the message, we see `"ttl":55,"expiration":"2023-02-08T15:42:21.849758379Z",` the key lifetime is about 10 seconds, but it seems to be incorrect

https://etcd.io/docs/v3.5/learning/data_model/
**"etcd is designed to reliably store infrequently updated data and provide reliable watch queries"**

Due to the frequent recording, the data model of etcd suffers a lot and we often get misses during watches because compactions often happen, we have a little more than 1k patroni clusters, with so many compactions on etcd, which happen quite often, that breaks watches. If the key lifetime were longer, then it would not be necessary to make a record if there are no changes and everything would be fine. Most of the time only 4 fields change: createdIndex, modifiedIndex, ttl and expiration

**Comment by CyberDem0n** [comment]
I am sorry, but I can't following what you are trying to say.

**Comment by careless6666** [comment]
alex@alex-GS43VR-7RE:~/Documents/ae/gitlab/docker/db-entrypoint/certs/prod$ etcdctl --endpoints=https://prodetcdpatroni-1.server:2379 --ca-file=etcd_ca.crt --cert-file=etcd_cert.crt --key-file=etcd_key.crt watch   /service/ic-da-service-dwh-sync/leader -f
prodpostgres596x2f44-2513z3.server.net
Error:  401: The event in requested index is outdated and cleared (the requested history has been cleared [10348772585/10348772062]) [10348773584]

**Comment by careless6666** [comment]
You can't watch patroni service in etcd

**Comment by careless6666** [comment]
It is work, but if you have not many clusters. Now we have about 1000 patroni clusters and it is problem for watch. In principle, it is not true to make record in the etcd so often, this is contrary to the design etcd

**Comment by CyberDem0n** [comment]
Every node updates only `lease` every `loop_wait` seconds.
On top of that they could update their own member key, but only when it has been changed.
You can reduce the number of updates by increasing `loop_wait` (and `ttl` of course).
The other option would be tuning etcd configuration, but this is outside of Patroni scope.

Last, but not least, you gave absolutely no details about Patroni configuration despite the fact that the issue template explicitly asked for it, therefore I have no clue whether you are using v2 or v3 protocol and what are values of loop_wait/retry_timeout/ttl.

**Comment by careless6666** [comment]
Great, we try to  play and increase with parameter. 
Thanks a lot
