### ISSUE TITLE
Patroni node can't back to start

### ISSUE THREAD

**Issue by smartdatamn** [zalando/patroni#2572]
Dear Patronis,

My servers were working normally. But after the server restarted unexpectedly, one node can't back to normal.

I just tried reinit that node, getting the following error:
![patroni](https://user-images.githubusercontent.com/31835595/221883569-544c5bda-fc09-4b71-95d1-670d95494af3.PNG)

Also /data/patroni directory below folders created:
![folder](https://user-images.githubusercontent.com/31835595/221883897-b92aedbc-b9a1-4962-b574-bf4f5b343adf.PNG)

Thanks,

**Comment by CyberDem0n** [comment]
@smartdatamn all questions in the issue template are important and you didn't answer any of them.

**Comment by CyberDem0n** [comment]
Is `/data/patroni` a mount point by any chance?

**Comment by bj-pop** [comment]
Hi,

you might have tablespaces inside the data directory. I have the same situation.

Tablespaces are meant to be separate paths, 
Move the tablespaces outside the datadir or pgdata.
