### ISSUE TITLE
Wrong Info in Readme of max_replication_slots = 1

### ISSUE THREAD

**Issue by accelq** [zalando/patroni#2573]
**Describe the bug**
In the article it says max_replication_slots = 1. But I see during execution it creates two more one with name _tmp_, and one more.

**To Reproduce**
Just set max_replication_slots to 1 and run.

**Expected behavior**
Can you please share the correct value min values of max_replication_slots

**Environment**
-   PostgreSQL version: 10

**Comment by CyberDem0n** [comment]
I am not sure which article you are talking about.
By default Patroni sets max_replication_slots=10.
You have to configure it based on your needs: https://www.postgresql.org/docs/current/runtime-config-replication.html#GUC-MAX-REPLICATION-SLOTS

**Comment by accelq** [comment]
this screenshot I was referring to.
![image](https://user-images.githubusercontent.com/40689807/222091693-5aa2680a-407a-44df-a9c6-4c3c1ddbd7f6.png)
https://pgsync.com/getting-started/setup/

**Comment by CyberDem0n** [comment]
pgsync? And you decided to open an issue in Patroni repo?
