### ISSUE TITLE
Adding the GET /metrics endpoint to the Patroni Rest API page

### ISSUE THREAD

**Issue by burakergenn** [zalando/patroni#2574]
When I tried to monitor the Patroni through Prometheus, I couldn't see the GET /metrics endpoint on the Rest API page (https://patroni.readthedocs.io/en/latest/rest_api.html#). 
As far as I can see, it is mentioned only in the release notes page (https://patroni.readthedocs.io/en/latest/releases.html#version-2-1-0) that it was added with Version 2.1.0. 
However, the /metrics endpoint exists and when I run it, I get the output below. Can you please add the Rest API GET /metrics endpoint?

 ┌── root@my-company-pgdb01 ── ~ ─
 └─# curl http://127.0.0.1:8009/metrics
\# HELP patroni_version Patroni semver without periods.
\# TYPE patroni_version gauge
patroni_version{scope="pg14-mycompany"} 020103
\# HELP patroni_postgres_running Value is 1 if Postgres is running, 0 otherwise.
\# TYPE patroni_postgres_running gauge
patroni_postgres_running{scope="pg14-mycompany"} 1
\# HELP patroni_postmaster_start_time Epoch seconds since Postgres started.
\# TYPE patroni_postmaster_start_time gauge
patroni_postmaster_start_time{scope="pg14-mycompany"} 1657656955.179243
\# HELP patroni_master Value is 1 if this node is the leader, 0 otherwise.
\# TYPE patroni_master gauge
patroni_master{scope="pg14-mycompany"} 1
\# HELP patroni_xlog_location Current location of the Postgres transaction log, 0 if this node is not the leader.
\# TYPE patroni_xlog_location counter
patroni_xlog_location{scope="pg14-mycompany"} 22320573386952
\# HELP patroni_standby_leader Value is 1 if this node is the standby_leader, 0 otherwise.
\# TYPE patroni_standby_leader gauge
patroni_standby_leader{scope="pg14-mycompany"} 0
\# HELP patroni_replica Value is 1 if this node is a replica, 0 otherwise.
\# TYPE patroni_replica gauge
patroni_replica{scope="pg14-mycompany"} 0
\# HELP patroni_xlog_received_location Current location of the received Postgres transaction log, 0 if this node is not a replica.
\# TYPE patroni_xlog_received_location counter
patroni_xlog_received_location{scope="pg14-mycompany"} 0
\# HELP patroni_xlog_replayed_location Current location of the replayed Postgres transaction log, 0 if this node is not a replica.
\# TYPE patroni_xlog_replayed_location counter
patroni_xlog_replayed_location{scope="pg14-mycompany"} 0
\# HELP patroni_xlog_replayed_timestamp Current timestamp of the replayed Postgres transaction log, 0 if null.
\# TYPE patroni_xlog_replayed_timestamp gauge
patroni_xlog_replayed_timestamp{scope="pg14-mycompany"} 0
\# HELP patroni_xlog_paused Value is 1 if the Postgres xlog is paused, 0 otherwise.
\# TYPE patroni_xlog_paused gauge
patroni_xlog_paused{scope="pg14-mycompany"} 0
\# HELP patroni_postgres_server_version Version of Postgres (if running), 0 otherwise.
\# TYPE patroni_postgres_server_version gauge
patroni_postgres_server_version {scope="pg14-mycompany"} 140004
\# HELP patroni_cluster_unlocked Value is 1 if the cluster is unlocked, 0 if locked.
\# TYPE patroni_cluster_unlocked gauge
patroni_cluster_unlocked{scope="pg14-mycompany"} 0
\# HELP patroni_postgres_timeline Postgres timeline of this node (if running), 0 otherwise.
\# TYPE patroni_postgres_timeline counter
patroni_postgres_timeline{scope="pg14-mycompany"} 24
\# HELP patroni_dcs_last_seen Epoch timestamp when DCS was last contacted successfully by Patroni.
\# TYPE patroni_dcs_last_seen gauge
patroni_dcs_last_seen{scope="pg14-mycompany"} 1677658321
\# HELP patroni_pending_restart Value is 1 if the node needs a restart, 0 otherwise.
\# TYPE patroni_pending_restart gauge
patroni_pending_restart{scope="pg14-mycompany"} 1
\# HELP patroni_is_paused Value is 1 if auto failover is disabled, 0 otherwise.
\# TYPE patroni_is_paused gauge
patroni_is_paused{scope="pg14-mycompany"} 1

**Comment by CyberDem0n** [comment]
Hi @burakergenn,

Patroni is an open source project, feel free to contribute documentation update: https://github.com/zalando/patroni/blob/master/docs/rest_api.rst

**Comment by burakergenn** [comment]
Hi @CyberDem0n ,

I made the edit on the page you specified. Thank you for your suggestion and help.

**Comment by burakergenn** [comment]
Hi @CyberDem0n ,

I made the edit on the page you specified. Thank you for your suggestion and help.

**Comment by CyberDem0n** [comment]
@burakergenn please don't forget to open a PR :)

**Comment by burakergenn** [comment]
@CyberDem0n I created a Pull Request. Thank you for your help :)
