### ISSUE TITLE
Request recommendations on redirecting traffic after failover

### ISSUE THREAD

**Issue by pearlsprathap** [zalando/patroni#2575]
Hi Team,

This is not a bug, but we are looking for some recommendations/best practices for traffic redirection after using Patroni for PostgreSQL failover.

We are planning to migrate to Patroni for approx 2000+ PostgreSQL clusters and we are exploring the options available for IP address translation(redirect traffic to new primary) after PostgreSQL failover with Patroni. Our databases are spread across multi-AZ.

Option 1:

Using traffic manager above the AZs. SLB for each AZ, followed by HAproxy to redirect the traffic to PostgreSQL primary server(based on Haproxy's HTTP health-check). Below is the diagram we are looking for. Using this method there is no need for DNS Update as the HAProxy will redirect the traffic to primary always based on its health-check, but there are additional components for traffic flow. Especially this option increases complexity when we increase the number of underlying PostgreSQL clusters(scalability) and will need multiple SLB/HAProxy components.

![image](https://user-images.githubusercontent.com/77924081/222091048-1bde10c7-ebfb-4793-89da-21a078fef366.png)

Option 2:

Using DNS translation. Using Patroni's callback script on role change, we would make an API call to DNS and update the DNS alias name to the new Primary IP address. This simple solution, but would need DNS to be updated on every role transition(with TTL of 60 seconds).

![image](https://user-images.githubusercontent.com/77924081/222091547-8ad7c457-e92e-43df-a5d7-7252cce069d0.png)

We are planning to build a robust Patroni's callback script, which could have methods to handle DNS failures, by including retries or raising an exception in case if it fails even after retries.

From your experience, please suggest your thoughts on these approaches. Also let us know the robustness of Patroni Callback option(option 2) in general, as we will be fully dependent on it to trigger(to update DNS) which will ensure client connections on failover. 

Thanks a lot in advance.

Thanks and Regards,
Prathap

**Comment by CyberDem0n** [comment]
With callbacks one should be extra careful.
The problem is that they are asynchronous and in case if callback is slow and primary-standby quickly changing their roles a few times the result could be unpredictable and DNS could end up pointing to the wrong node.

The other issue with DNS - it doesn't forcefully terminating connections.
So following situation are possible:
1. primary demoted to a standby, applications quickly reconnecting and hitting the old primary because DNS was either not updated yet or cached.
2. Patroni on the primary crashed and not restarted, Postgres remains running ungoverned. All existing connections will remain. But in the meantime the standby will be promoted to the new primary and after DNS update new connections will go there.

Actually, if you can have the same network across different AZ, you may consider using VIP manager from Cybertec: https://github.com/cybertec-postgresql/vip-manager

**Comment by pearlsprathap** [comment]
Hi @CyberDem0n,

Thanks for your feedback. Yes, we understood from your reply about the async nature of DNS calls, we will see if we can include some logic in our workflow to mitigate this. Regarding the other points,

1. Yes, the applications will keep trying the old Primary IP address till the DNS is propagated. We are planning to use TTL of 60 to reduce this impact.

2. We are planning to use software watchdog for Patroni agent, so that the server will get rebooted to avoid split brain situation, if Patroni agent dies. Hope this will mitigate this issue. 

Do you have any thoughts of the first proposed architecture(using TM/SLB/HAproxy). We will in the meanwhile see the options of using vip-manager as you mentioned. Thanks again.

Regards,
Prathap

**Comment by CyberDem0n** [comment]
> We are planning to use TTL of 60 to reduce this impact.

Unfortunately it is not enough, "wrong" connections should be actively terminated. HAProxy could do that. Another option is using something like `targetServerType=primary` in the connection string on the application side: https://jdbc.postgresql.org/documentation/use/#connection-parameters

> We are planning to use software watchdog for Patroni agent, so that the server will get rebooted to avoid split brain situation, if Patroni agent dies. Hope this will mitigate this issue.

Yes, it does :+1:

> Do you have any thoughts of the first proposed architecture(using TM/SLB/HAproxy).

It looks good to me. But, I probably don't have enough knowledge about your platform and specifically TM/SLB. Are there any chances that they could perform health-checks similar to HAProxy?

**Comment by pearlsprathap** [comment]
Hi @CyberDem0n , 

Thanks for your response. Unfortunately we cannot force the applications to use the parameters in connection string, hence we will explore the HAProxy option.

Also we checked with our SLB and we dont have capability to perform such an extensive health-checks like HAproxy does. 

Thanks for your response
