### ISSUE TITLE
pg_rewind failed with psycopg2.OperationalError: FATAL: password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by plmayekar** [zalando/patroni#2581]
Issue :
I have observed one scenario , due to n/w loss , consul agent on primary not able to communicate with consul server leads to go down and promoting another node as primary . However when n/w connectivity is regained , pg_rewind got failed  for that node with error as 

Logs:

`Feb  3 23:59:46 test-host-13-02 patroni[983]: 2023-02-03 23:59:46,728 WARNING: Postgresql is not running.
Feb  3 23:59:46 test-host-13-02 patroni[983]: 2023-02-03 23:59:46,728 INFO: Lock owner: test-host-13-03; I am test-host-13-02
Feb  3 23:59:46 test-host-13-02 patroni[983]: 2023-02-03 23:59:46,731 INFO: pg_controldata:
Feb  3 23:59:46 test-host-13-02 patroni[983]:   pg_control version number: 1300
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Catalog version number: 202007201
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Database system identifier: 7090415485592090116
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Database cluster state: shut down in recovery
Feb  3 23:59:46 test-host-13-02 patroni[983]:   pg_control last modified: Tue Jan 31 14:38:18 2023
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint location: 795/E26FC688
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's REDO location: 795/E26FC688
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's REDO WAL file: 0000001000000795000000E2
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's TimeLineID: 16
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's PrevTimeLineID: 16
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's full_page_writes: on
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's NextXID: 0:358811896
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's NextOID: 17112
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's NextMultiXactId: 7453227
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's NextMultiOffset: 16060735
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's oldestXID: 160347409
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's oldestXID's DB: 16401
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's oldestActiveXID: 0
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's oldestMultiXid: 341189
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's oldestMulti's DB: 16401
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's oldestCommitTsXid: 0
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Latest checkpoint's newestCommitTsXid: 0
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Time of latest checkpoint: Tue Jan 31 14:28:40 2023
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Fake LSN counter for unlogged rels: 0/3E8
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Minimum recovery ending location: 795/E26FC700
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Min recovery ending loc's timeline: 16
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Backup start location: 0/0
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Backup end location: 0/0
Feb  3 23:59:46 test-host-13-02 patroni[983]:   End-of-backup record required: no
Feb  3 23:59:46 test-host-13-02 patroni[983]:   wal_level setting: replica
Feb  3 23:59:46 test-host-13-02 patroni[983]:   wal_log_hints setting: on
Feb  3 23:59:46 test-host-13-02 patroni[983]:   max_connections setting: 200
Feb  3 23:59:46 test-host-13-02 patroni[983]:   max_worker_processes setting: 8
Feb  3 23:59:46 test-host-13-02 patroni[983]:   max_wal_senders setting: 10
Feb  3 23:59:46 test-host-13-02 patroni[983]:   max_prepared_xacts setting: 0
Feb  3 23:59:46 test-host-13-02 patroni[983]:   max_locks_per_xact setting: 64
Feb  3 23:59:46 test-host-13-02 patroni[983]:   track_commit_timestamp setting: off
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Maximum data alignment: 8
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Database block size: 8192
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Blocks per segment of large relation: 131072
Feb  3 23:59:46 test-host-13-02 patroni[983]:   WAL block size: 8192
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Bytes per WAL segment: 16777216
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Maximum length of identifiers: 64
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Maximum columns in an index: 32
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Maximum size of a TOAST chunk: 1996
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Size of a large-object chunk: 2048
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Date/time type storage: 64-bit integers
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Float8 argument passing: by value
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Data page checksum version: 0
Feb  3 23:59:46 test-host-13-02 patroni[983]:   Mock authentication nonce: f7e490148b90aa29b4c2a42fd3ceb811d3ebbb1e736827af2f9f7e19f3da4a4e
Feb  3 23:59:46 test-host-13-02 patroni[983]: 2023-02-03 23:59:46,735 INFO: Lock owner: test-host-13-03; I am test-host-13-02
Feb  3 23:59:46 test-host-13-02 patroni[983]: 2023-02-03 23:59:46,756 INFO: running pg_rewind from test-host-13-03
Feb  3 23:59:46 test-host-13-02 patroni[983]: 2023-02-03 23:59:46,770 ERROR: Exception when working with leader
Feb  3 23:59:46 test-host-13-02 patroni[983]: Traceback (most recent call last):
Feb  3 23:59:46 test-host-13-02 patroni[983]:   File "/opt/app/patroni/lib/python3.8/site-packages/patroni/postgresql/rewind.py", line 66, in check_leader_is_not_in_recovery
Feb  3 23:59:46 test-host-13-02 patroni[983]:     with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **kwargs) as cur:
Feb  3 23:59:46 test-host-13-02 patroni[983]:   File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
Feb  3 23:59:46 test-host-13-02 patroni[983]:     return next(self.gen)
Feb  3 23:59:46 test-host-13-02 patroni[983]:   File "/opt/app/patroni/lib/python3.8/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
Feb  3 23:59:46 test-host-13-02 patroni[983]:     with psycopg2.connect(**kwargs) as conn:
Feb  3 23:59:46 test-host-13-02 patroni[983]:   File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 127, in connect
Feb  3 23:59:46 test-host-13-02 patroni[983]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Feb  3 23:59:46 test-host-13-02 patroni[983]: psycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"
Feb  3 23:59:46 test-host-13-02 patroni[983]: FATAL:  password authentication failed for user "postgres"`

Environment  : 
Patroni 2.1.3
consul 1.7.3
Postgres 13

**Comment by CyberDem0n** [comment]
> FATAL:  password authentication failed for user "postgres"

pg_rewinds requires either superuser connections between nodes or a special user allowed to execute [certain functions](https://www.postgresql.org/docs/current/app-pgrewind.html#id-1.9.5.9.8).

In your case apparently superuser connections are failing, either because of incorrect password or because pg_hba.conf doesn't allow them.

**Comment by plmayekar** [comment]
Hi @CyberDem0n  , This issue does not happened frequently , I  have the same conf across 3 nodes so there is no possibility of having wrong password /hba issue. Also note that if I reinitialised that failed node , it gets recovered.

**Comment by CyberDem0n** [comment]
> I have the same conf across 3 nodes so there is no possibility of having wrong password /hba issue.

Magic doesn't exists. I trust only logs, which are telling that postgres refusing superuser connections because of the wrong password.

> Also note that if I reinitialised that failed node , it gets recovered.

Reinitialize isn't using superuser, but replication user.

**Comment by plmayekar** [comment]
Thanks for clarification, Could you please guide me if such issue occurs in future , what kind of steps I should take to debug out before reinitialising cluster. Because I  see patroni conf file had the same password for postgres user  across all nodes during issue .

**Comment by CyberDem0n** [comment]
Repeating for the third time - you have to verify that it is possible to connect to postgres with the superuser credentials from Patroni config file.
