### ISSUE TITLE
Clustering on a Docker IPVlan environment on different hosts

### ISSUE THREAD

**Issue by balucio** [zalando/patroni#2582]
We use Docker in a multi host "IPvlan" enviroment , without any orchestrator. The network communication between containers on different subnet is left to the  IPVlan routing. In such environment each container could have a fixed Ip Address on an IPVlan network or binded to a bridge network.

For example:

- host1 -> etcd1, patroni1, haproxy
- host2 -> etcd2, patroni2, haproxy
...
- hostN -> etcdN, patroniN, haproxy

Each HA proxy configuration should be updated using correct ipvlan container addresses and not for example the bridge one.
How I can set the storage ip address on HA Proxy configuration?

Thanks

**Comment by CyberDem0n** [comment]
The simplest you can do - put the right IP to the `restapi.connect_address` and `postgresql.connect_address`.
These addresses will be written to member keys in etcd.
After that you can use for example confd to automatically create/update HAProxy configuration files.
There are some examples in extras: https://github.com/zalando/patroni/tree/master/extras/confd

**Comment by balucio** [comment]
Sorry @CyberDem0n I don't understand. Are these setting exposed in some ENV variable, or do I have to create a specific "docker" image for each HAproxy with relevant ip settings?
Couldn't another option be to fix the HA Proxy configuration file (mapping for example a volume) ?

**Comment by CyberDem0n** [comment]
I have no clue about your environment and TBH I don't really want to know these details.
I can only talk about Patroni and its configuration, which is either set from patroni.yaml: https://patroni.readthedocs.io/en/latest/SETTINGS.html#postgresql
Or, some parameters could be configured from env: https://patroni.readthedocs.io/en/latest/ENVIRONMENT.html

Regarding HAProxy and confd - please consult their docs: https://docs.haproxy.org/ and https://github.com/kelseyhightower/confd/blob/master/docs/quick-start-guide.md

Regarding packaging everything - this is up to you how to do it

**Comment by balucio** [comment]
Ok, thanks for your help.
