### ISSUE TITLE
high availability across multiple datacenter

### ISSUE THREAD

**Issue by voriol** [zalando/patroni#2587]
Hi!

I'm currently building a solution based on postgresql + patroni in a multiple datacenter. The best scenario would be to have two fully active-active synchronized clusters, but I don't know if this is possible with two datacenters: https://github.com/zalando/patroni/issues/1182

From what I understand in the previous issue, setting up a cluster with asyncrhronous unidirectional replication would be possible through a "standby cluster" configuration.

The architecture would be

datacenter A: 1 cluster postgresql + patoni nodes (primary-replica) + 1 cluster etcd/zookeeper + 1 cluster haproxy
datacenter B: 1 standby cluster postgresql + patoni nodes (primary-replica) + 1 cluster etcd/zookeeper + 1 cluster haproxy

My questions are:

- How to "manually promote" a standby cluster (because I understand that it is not possible to do it automatically)
- In the case of promoting the standby cluster, is it possible to do rollback? with what implication?

Thanks a lot!

**Comment by CyberDem0n** [comment]
> How to "manually promote" a standby cluster (because I understand that it is not possible to do it automatically)

`patronictl edit-config` and remove `standby_cluster` section from there

> In the case of promoting the standby cluster, is it possible to do rollback? with what implication?

If the source cluster is still up and running and you promote the standby cluster you create a split-brain.
There are only two ways of resolving it:
1.  add the `standby_cluster` section back and it will trigger `pg_rewind`, but there are chances that `pg_rewind` will fail.
2. rebuild the standby cluster from scratch.

**Comment by voriol** [comment]
> 2. rebuild the standby cluster from scratch.

Practical example:

- initial state:
`DC1 active cluster & DC2 standby cluster`

- then, DC1 go down (ie: network issue)
`patronictl edit-config and remove standby_cluster section from DC2 standby cluster`

- then, the issue in DC1 has been resolved
`rebuild the standby cluster from scratch in DC2`

Questions:
- How do I commit all the changes from DC2 to DC1? `pg_rewind`?
- Will there be a "collision" of data?

**Comment by voriol** [comment]
I understand. 

So what would be the correct way to ensure high availability of postgresql between datacenters?

On the other hand, I see that there are many doubts about this topic in github "issue" format, do you think it is correct that with the conclusions we draw in this thread, I send you a pull request with documentation on this topic?

**Comment by voriol** [comment]
> But, currently it is not possible because the source cluster has no clue about existence of the standby cluster.

In this case, 

https://www.postgresql.org/docs/current/warm-standby.html#STANDBY-SERVER-SETUP
https://www.postgresql.org/docs/current/warm-standby.html#STREAMING-REPLICATION

**Comment by voriol** [comment]
understood! I will prepare some documentation and send you PR

**Comment by voriol** [comment]
https://github.com/zalando/patroni/pull/2598
