### ISSUE TITLE
switchover causing client errors 

### ISSUE THREAD

**Issue by rjdp** [zalando/patroni#2591]
**Describe the bug**

When I use `docker-compose-citus.yml` switchover doesnot cause client errors, where as if I use `docker-compose.yml` I get client errors while switchover

**To Reproduce**
- docker-compose up
- docker exec -ti demo-haproxy bash
- psql -h localhost -p 5000 -U postgres
- create table my_distributed_table(id BIGSerial PRIMARY KEY    NOT NULL , value double precision);
```
with inserted as (
    insert into my_distributed_table(value)
     values(random()) RETURNING id
) SELECT now(), id from inserted\watch 0.9
```

**Expected behavior**
Switchover should cause some latency increase not errors

**Screenshots**
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/7734938/224181907-018b147b-e9a4-4af4-89af-eb7125641d3f.png">

**Environment**
-   Patroni version: 3.01
-   PostgreSQL version: 15
-   DCS (and its version): etcd 3.3.13

**Patroni configuration file**
```
Default
```

**patronictl show-config**
```
Please copy&paste the output of "patronictl show-config" command here
```

**Have you checked Patroni logs?**
N/A

**Have you checked PostgreSQL logs?**
N/A

**Have you tried to use GitHub issue search?**
Yes, did not find match

**Additional context**

**Comment by CyberDem0n** [comment]
Transparent switchover is a feature of Citus, not Patroni. And it only works when worker is switched. For coordinator nodes you'll also get an error

**Comment by rjdp** [comment]
Thanks ! any workaround or tips how to do it ?

**Comment by CyberDem0n** [comment]
Well, you may use connection pooler like pgbouncer to pause connections before switch, but it is outside of the Patroni scope

**Comment by rjdp** [comment]
Thankyou so much @CyberDem0n !! I understand this is outside scope of patroni. I was looking for recommendations, thanks for the tip
