### ISSUE TITLE
Question:  Client read/write connection to HaProxy

### ISSUE THREAD

**Issue by rjdp** [zalando/patroni#2592]
Do we need to have different client  for read and write ?
- a client connecting to haproxy 5000 port for write queries
- separate client for load balanced read queries to haproxy 5001 ?

**Comment by CyberDem0n** [comment]
1. there is no way to easily identify read-only queries to forward them to replicas
2. even if it would be easy, only the application knows whether this specific read-only query is safe to send to the replica because it might not received latest data from the primary

**Comment by rjdp** [comment]
Cool ! I meant given application is aware where to send quereies it needs to use two clients one of 5000 haproxy port and another for 5001.

I was just looking if there is way possible with just single client instantiation in nodejs/python
