### ISSUE TITLE
inquiry: pre-stop callback

### ISSUE THREAD

**Issue by le-duane** [zalando/patroni#2596]
Hi,

Sorry, this isn't a bug report, and I couldn't figure out how to get an invite to the Postgres Slack Workspace.

My team is attempting to move to ECTD as our DCS from Kubernetes. We would like to leverage callbacks to manage the role labels for our pods. We also from time to time have logical replication connections which hang shutdown, and would like to kill these before shutdown as well. However, the `on_stop` callback is too late for both of these things.

My thought was to do this via a pre-stop callback before the actual shutdown of the DB; perhaps [here](https://github.com/zalando/patroni/blob/60a7e5a514b1a9982c1ff1f9ee78f644a4e820bb/patroni/postgresql/__init__.py#L699)?

I would like to start a discussion of whether this is feasible or perhaps whether this is a better way to achieve our goals here.

Thanks!

**Comment by hughcapet** [comment]
> I couldn't figure out how to get an invite to the Postgres Slack Workspace

You can join using the link provided here: https://www.postgresql.org/community/

**Comment by le-duane** [comment]
Thanks @hughcapet - that got me going!
