### ISSUE TITLE
Security for API

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#26]
Currently the API is completely unsecured.  This limits us adding new features to the API which could actually destroy or reveal data, and isn't a great idea in general.  As such, I'd like two things for the API:

* simple user/password auth
* SSL support

There's two ways we could approach this: one would be to add these things using various snippets to the existing API.py (for example: https://gist.github.com/fxsjy/5465353).  The second way would be to offer sample configurations for an nginx proxy for the API.

Thoughts?

**Comment by CyberDem0n** [comment]
Sure, nginx is a great product, but for our needs it's kind of overkill :)
Adding support of basic-auth and ssl  to the current implementation of API is not a problem at all, but the question is how far we are going to extend our API. How many endpoints we are going to have?
SimpleHTTPServer works good for simple things, but if API is going to be extensive may be it makes sense to think about usage of more sophisticated framework.

Another question is: where we should keep user and password for basic auth? Is standard config.yaml good enough for this?

**Comment by jberkus** [comment]
Well, I think it's good enough, *especially* if I later add support for envdir (on the TODO list).  

The alternative is to authenticate against PostgreSQL.  This would have the advantage that you only need to rotate passwords in one place.

Here's the endpoints I'm thinking of:

* check replication status
* shutdown
* startup
* promote
* re-initialize
* more detailed statistics

Given that these involve actions which could disrupt production, I think you can see why some connection security is absolutely needed.

**Comment by CyberDem0n** [comment]
And Basic-Auth: https://github.com/zalando/patroni/pull/35
