### ISSUE TITLE
Patroni and Debian/Ubuntu Packaging

### ISSUE THREAD

**Issue by Xof** [zalando/patroni#260]
Right now, Patroni assumes that pg_ctl will be found in the PATH of the patroni process. Of course, this isn't true for Debian/Ubuntu packaging that uses the wrappers around pg_ctl. Would it make sense to parameterize the pg_ctl function such that it can use alternative control commands?

**Comment by alexeyklyukin** [comment]
Would it make sense to have a custom script that accepts the same arguments as pg_ctl (right now we use start, stop, restart, initdb with additional options supplied from the command line)? This way, we can limit the changes to making the pg_ctl path configurable (or you can even make a symlink without changing Patroni altogether).

Aslo #259 has a very similar request.

**Comment by Xof** [comment]
That's basically reasonable, but I'd be very leery of calling it "pg_ctl", since pg_ctl proper still exists on such systems, just in a version-specific location. Having multiple "pg_ctl"s running around sounds like asking for trouble.

**Comment by alexeyklyukin** [comment]
Then why won't you just add pg_ctl to the PATH? Seems that controlling this on an OS level is more flexible than doing it in Patroni.

**Comment by ants** [comment]
My CentOS packaging had a similar issue. In my use case it was nicer to add a config parameter `postgresql.bindir`. Defaults to empty string for current behavior, but having it enables custom installs where multiple minor versions are installed in parallel and multiple databases run on a single host. I'll post that patch later tonight.

That said, at least for generic CentOS packaging it would be best if pg_ctl selected via update_alternatives would be used by default, I just need to see if I can let the unit file initialize PATH for Patroni. I'm not that familiar with PostgreSQL packaging on Debian to say how to figure out a reasonable default there.

**Comment by CyberDem0n** [comment]
Is it really a problem to set a correct `PATH` before starting up Patroni?

```bash
PATH=/usr/lib/postgresql/9.5/bin:$PATH patroni ....
```

 If `pg_ctl` (or any other binary) can be found multiple time it will choose the first one:
```bash
$ PATH=/usr/lib/postgresql/9.3/bin:/usr/lib/postgresql/9.5/bin:$PATH pg_ctl -V
pg_ctl (PostgreSQL) 9.3.13
$ PATH=/usr/lib/postgresql/9.5/bin:/usr/lib/postgresql/9.3/bin:$PATH pg_ctl -V
pg_ctl (PostgreSQL) 9.5.3
```

**Comment by Xof** [comment]
It's fighting the rather extensive multiple-cluster system that the distribution packages provide, rather than working with it. This isn't an exceptional case on Linux; anyone using the community packages runs into this, so it's very common to have a "hidden" or wrapped pg_ctl.

**Comment by ants** [comment]
In my case Patroni will be started by a systemd unit. In theory the PATH could be set there, but having some of the configuration in the unit file and some in Patroni config would be cumbersome and confusing. As I said, I feel that it should still work out-of-the-box with update-alternatives set pg_ctl, but a fallback is still needed for cases when there are multiple deployments on a single host.

**Comment by CyberDem0n** [comment]
Well, pg_ctl is not the only binary used by Patroni. Although we are not calling initdb directly, pg_ctl expects to find it in the same directory as pg_ctl itself (as well as postgres)

Also Patroni calls: pg_basebackup, pg_controldata, pg_rewind and even postgres binary directly.
Do you really want to parametrize all these cases?

**Comment by Xof** [comment]
Yes, I think it's a good idea to work with the community packaging rather than against it. Some binaries (pg_basebackup) are wrapped and available without special modification. In the case of initdb, on Debian-style packaging, it makes sense to use pg_createcluster instead.

**Comment by CyberDem0n** [comment]
> In the case of initdb, on Debian-style packaging, it makes sense to use pg_createcluster instead.

Absolutely not agree, `pg_createcluster` is a simple perl script, which calls the old good `initdb` at the end. Personally I've never seen postgres packages, were all postgres binaries are not located in the same directory. All Ubuntu/Debian/RedHat/CentOS/SUSE/Gentoo/YourFavoriteDistro "magic-wrapper-scripts", i.e. pg_createcluster/pg_upgradecluster/pg_ctlcluster/etc are not doing anything except calling the original postgres binary (initdb/pg_upgrade/pg_ctl/etc). Taking into account that such wrappers are not available for other systems, I think it's not worth to spend time on using them.

**Comment by CyberDem0n** [comment]
https://github.com/zalando/patroni/pull/263 makes it possible to configure postgres bin_dir in config file or via environment.
