### ISSUE TITLE
[Question] : What are sequence of checks patroni do before it trigger the failover and enterprise support.

### ISSUE THREAD

**Issue by t-ushar** [zalando/patroni#2600]
### What happened?

Hi Team,

We are in a phase to onboard the patroni before that, we want to know the sequence of checks/validation patroni does before it triggers the failover which is categorized as below.

1. Host level checks. 
2. DB level checks.
3. How patroni do health checks of DB clusters, and what are the queries it executes for DB cluster validation?
4. Does zalando provides enterprise support for patroni and enterprise support for ETCD? 

Thanks,
Tushar Takate.

### How can we reproduce it (as minimally and precisely as possible)?

NA

### What did you expect to happen?

NA

### Patroni/PostgreSQL/DCS version

-   Patroni version: 
-   PostgreSQL version: 
-   DCS (and its version): 

### Patroni configuration file

```yaml
NA
```

### patronictl show-config

```yaml
NA
```

### Patroni log files

```shell
NA
```

### PostgreSQL log files

```shell
NA
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

NA

**Comment by CyberDem0n** [comment]
This is not a bug. Please post questions on Slack.
