### ISSUE TITLE
Feature: make it easier to run tests locally on developer workstation

### ISSUE THREAD

**Issue by matthbakeredb** [zalando/patroni#2602]
### What happened?

As a new developer to the project I want to be able to run tests and have access to environments and tooling to author code. It took a while to understand how to get behave tests to run. It wasn't clear to me from reading instructions on what tooling existed that I could run locally to validate my changes before pushing to the repo.

### How can we reproduce it (as minimally and precisely as possible)?

Get a fresh developer environment and assume no knowledge of Patroni or the tools used to develop and test its code, and run pytest and behave tests.

### What did you expect to happen?

Run standard commands that are reasonably consistent across platforms and OSes. There is a `tox.ini` so I run `tox` to get lint and unit tests.

### Patroni/PostgreSQL/DCS version

dcs = etcd

### Patroni configuration file

```yaml
n/a
```

### patronictl show-config

```yaml
n/a
```

### Patroni log files

```shell
n/a
```

### PostgreSQL log files

```shell
n/a
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

I have a PR coming with a suggestion of what could be added to resolve (some of) this.

**Comment by CyberDem0n** [comment]
closing due to https://github.com/zalando/patroni/commit/73797e85728cc2ba431d6a309515b7e95a4966f5
