### ISSUE TITLE
nothing provides python3-etcd

### ISSUE THREAD

**Issue by robinportigliatti** [zalando/patroni#2608]
### What happened?

Hello,

Installing `patroni-etcd` fails.

Just for your information and everyone having this issue today, an issue has been made to the pgdg team : https://redmine.postgresql.org/issues/7792

Robin,

### How can we reproduce it (as minimally and precisely as possible)?

Install fails

### What did you expect to happen?

Install fails

### Patroni/PostgreSQL/DCS version

Install fails

### Patroni configuration file

```yaml
Install fails
```

### patronictl show-config

```yaml
Install fails
```

### Patroni log files

```shell
Install fails
```

### PostgreSQL log files

```shell
Install fails
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

Install fails

**Comment by CyberDem0n** [comment]
Thanks for reporting.
Yes, Patroni is using `python-etcd` as dependency, but here we only develop Patroni and maintain pypi package.
Everything related to RPM or DEB packaging is handled by other people. 
The https://redmine.postgresql.org/issues/7792 seems to be good place to complain about missing packages.
