### ISSUE TITLE
Replication is not working in Patroni

### ISSUE THREAD

**Issue by rescue3** [zalando/patroni#2609]
### What happened?

Replication is not working in Patroni - replication slot does not exist

### How can we reproduce it (as minimally and precisely as possible)?

We have deployed a postgres cluster on Patroni. In which replication is not working, I am also getting an error 'could not start WAL streaming: Error:  replication slot node2 does not exist'. We are stuck here for a very long time.

### What did you expect to happen?

The Replication mechanism has to work

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.1
-   PostgreSQL version: 15.2
-   DCS (and its version): 3.2.26

### Patroni configuration file

```yaml
/etc/patroni.yml
```

### patronictl show-config

```yaml
scope: postgres
namespace: /db/
name: node1

restapi:
listen: 172.31.15.65:8008
connect_address: 172.31.15.65:8008

etcd:
host: 172.31.13.20:2379

bootstrap:
dcs:
ttl: 30
loop_wait: 10
retry_timeout: 10
maximum_lag_on_failover: 1048576
postgresql:
use_pg_rewind: true
use_slots: true
parameters:
wal_level: replica
hot_standby: "on"
wal_keep_segments: 8
max_wal_senders: 5
max_replication_slots: 5
checkpoint_timeout: 3

initdb:
- encoding: UTF8
- data-checksums

pg_hba:
- host replication replicator 127.0.0.1/32 md5
- host replication replicator 172.31.15.65/0 md5
- host replication replicator 172.31.0.176/0 md5
- host replication replicator 172.31.6.24/0 md5
- host all all 0.0.0.0/0 md5

users:
    admin:
        password: admin
        options:
            - createrole
            - createdb
postgresql:
listen: 172.31.15.65:5432
connect_address: 172.31.15.65:5432
data_dir: /data/patroni
pgpass: /tmp/pgpass
authentication:
replication:
username: replicator
password: password
superuser:
username: postgres
password: password
parameters:
unix_socket_directories: '.'

#tags:
#nofailover: false
#noloadbalance: false
#clonefrom: false
#nosync: false
```

### Patroni log files

```shell
Mar 12 07:59:11 p3 patroni[6806]: 2023-03-12 07:59:11.348 UTC [6806] LOG: listening on IPv4 address "172.31.33.87", port 5432
Mar 12 07:59:11 p3 patroni[6806]: 2023-03-12 07:59:11.352 UTC [6806] LOG: listening on Unix socket "./.s.PGSQL.5432"
Mar 12 07:59:11 p3 patroni[6810]: 2023-03-12 07:59:11.359 UTC [6810] LOG: database system was interrupted; last known up at 2023-03-12 07:59:10 UTC
Mar 12 07:59:11 p3 patroni[6810]: 2023-03-12 07:59:11.371 UTC [6810] LOG: entering standby mode
Mar 12 07:59:11 p3 patroni[6810]: 2023-03-12 07:59:11.377 UTC [6810] LOG: redo starts at 0/4000028
Mar 12 07:59:11 p3 patroni[6810]: 2023-03-12 07:59:11.380 UTC [6810] LOG: consistent recovery state reached at 0/4000100
Mar 12 07:59:11 p3 patroni[6806]: 2023-03-12 07:59:11.380 UTC [6806] LOG: database system is ready to accept read-only connections
Mar 12 07:59:11 p3 patroni[6811]: 2023-03-12 07:59:11.402 UTC [6811] FATAL: could not start WAL streaming: ERROR: replication slot "node3" does not exist
Mar 12 07:59:11 p3 patroni[6812]: 2023-03-12 07:59:11.421 UTC [6812] FATAL: could not start WAL streaming: ERROR: replication slot "node3" does not exist
Mar 12 07:59:11 p3 patroni[6810]: 2023-03-12 07:59:11.421 UTC [6810] LOG: waiting for WAL to become available at 0/5000018
```

### PostgreSQL log files

```shell
2023-03-19 13:04:49.626 UTC [602] LOG:  background worker "logical replication launcher" (PID 644) exited with exit code 1
2023-03-19 13:04:49.628 UTC [635] LOG:  shutting down
2023-03-19 13:04:49.631 UTC [635] LOG:  checkpoint starting: shutdown immediate
2023-03-19 13:04:49.655 UTC [635] LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.028 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=0 kB
2023-03-19 13:04:49.665 UTC [602] LOG:  database system is shut down
2023-03-21 09:57:22.289 UTC [611] LOG:  starting PostgreSQL 15.2 (Ubuntu 15.2-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
2023-03-21 09:57:22.291 UTC [611] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-03-21 09:57:22.301 UTC [611] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-03-21 09:57:22.326 UTC [646] LOG:  database system was shut down at 2023-03-19 13:04:49 UTC
2023-03-21 09:57:22.373 UTC [611] LOG:  database system is ready to accept connections
2023-03-21 10:02:22.329 UTC [644] LOG:  checkpoint starting: time
2023-03-21 10:02:22.344 UTC [644] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.002 s, total=0.016 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
```

### Have you tried to use GitHub issue search?

- [x] Yes

**Comment by sayyed3** [comment]
https://www.alibabacloud.com/blog/how-to-set-up-a-highly-available-postgresql-cluster-using-patroni-on-ubuntu-16-04_594477

**Comment by CyberDem0n** [comment]
You are not answering my questions...

> 0> As data is not replicating on other VM

This is not an acceptable answer. You need to check postgres state logs on the replica.

> $ patronictl show-config
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: etcd, etcd3, kubernetes'

`patronictl -c /etc/patroni.yml show-config`

> 2> I commented above I referred this installation from ...

I am sorry, but we can't be responsible for some unknown 3rd party blog posts

> These are patroni and postgres logs only

Once again. These are not Patroni logs. Patroni logs look totally different.

> but it has been closed so I created a new one and just copied and in which postgres logs was not there so I added that today. Please refer: https://github.com/zalando/patroni/issues/2595

Editing closed issue doesn't help. GH doesn't give a sign that the original message was edited. How are we supposed to know it?

> We are new to this Patroni

And I assume you are also new to Postgres...

> If any suggestions from your side on how we can make patroni work properly that will be really helpful.

Start from reading the official docs: https://github.com/zalando/patroni#running-and-configuring

**Comment by rescue3** [comment]
That's right we are new to Postgres as well. We will be following this  https://github.com/zalando/patroni#running-and-configuring . Apart from that could you please share any steps or suggestions from your side for the installation & verifying Patroni? That will helps us a lot

**Comment by CyberDem0n** [comment]
> That's right we are new to Postgres as well.

Patroni really requires from you to have some Postgres administration experience.
It is like with autopilot on airplanes, if you can't fly a plane manually autopilot is useless.

> suggestions from your side for the installation & verifying Patroni?

There is no one-fits-all guide/tutorial/solution, especially when you have no Postgres experience.

**Comment by rescue3** [comment]
Its resolved. We just reconfigured the data directory

**Comment by xtianus79** [comment]
@CyberDem0n that answer is ridiculous. What are you making a product for if you can't even explain how to use it.  A database setup shouldn't be akin to building a rocket ship. To be honest this entire process is turning me way off to postgres as it seems this bug is just not able to be overcome without manual intervention. @rescue3 I'm assuming meant you had to manually intervene? Your answer is lacking any real knowledge to help anyone else. I beg for you to edit it and make it more clear what you did.

**Comment by CyberDem0n** [comment]
@xtianus79 your reply is even more ridiculous. You are making some assumptions without full understanding of the complexity of the system. Every system must be properly setup and regularly maintained. Even such a simple thing as a bicycle.

There are only two options for that:
1. you learn at least some basics on Postgres administration and do it on your own with some _little_ help form the OS community.
2. you hire a professional that will do everything for you.

For some reason your expectations are that the professional from 2 will work for free. That doesn't work like this.

Besides that, please read the entire thread of messages, I really did my best trying to help by asking very specific questions and didn't got an answer to any of them. Its not possible to help if the other part doesn't collaborate.
