### ISSUE TITLE
Report the replica states from the monitoring endpoints.

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/patroni#261]
Right now, the only way to find out if the Patroni cluster has all the replicas streaming from the master is to compare the transaction location between the master and the replicas, which implies the are actually transactions happening. For many staging or just deployed environments that won't hold true.

What we can do is to return the state of pg_stat_replication, namely

```sql
postgres=# select application_name, client_addr, state, sync_state from pg_stat_replication ;
 application_name |  client_addr   |   state   | sync_state
------------------+----------------+-----------+------------
 i_4aeba3f6       | 172.31.156.141 | streaming | async
 i_bc56d001       | 172.31.132.36  | streaming | async
(2 rows)
```

Either the application name or the client address can be used to match the row against the known list of replicas, obtained from elsewhere (i.e. etcd or autoscaling group).

**Comment by CyberDem0n** [comment]
Implemented in https://github.com/zalando/patroni/pull/269
