### ISSUE TITLE
Feature: report replica status "Sync Standby" via /metrics

### ISSUE THREAD

**Issue by TLINDEN** [zalando/patroni#2613]
### What happened?

Patroni already reports the status of the master (or standby leader) and the replicas using the metrics:
```
patroni_replica
patroni_master
patroni_standby_leader
```
However, it doesn't report if a replica is the current "Sync Standby". But it would be nice to have this information as a metric (especially when no replica is actually the sync standby).

### How can we reproduce it (as minimally and precisely as possible)?

Scrape the mentioned metrics.

### What did you expect to happen?

A new metric would be nice to have, e.g. `patroni_sync_standby`.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.1.4
-   PostgreSQL version:  13.8
-   DCS (and its version): etcd

### Patroni configuration file

```yaml
doesn't matter.
```

### patronictl show-config

```yaml
doesn't matter.
```

### Patroni log files

```shell
doesn't matter.
```

### PostgreSQL log files

```shell
doesn't matter.
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
Fell free to add it, should be straightforward: https://github.com/zalando/patroni/blob/master/patroni/api.py#L228

**Comment by TLINDEN** [comment]
How about this?
