### ISSUE TITLE
How to change the Send-Q of patroni

### ISSUE THREAD

**Issue by PiPi-Dragon** [zalando/patroni#2618]
### What happened?

![image](https://user-images.githubusercontent.com/27352343/227488194-4ba23b87-671c-4e8d-b49c-ae97e15a487a.png)
How to change the somaxconn of patroni ? 
I have changed the parameters of the system and restarted patroni , but the Send-Q of the patroni do not change.

### How can we reproduce it (as minimally and precisely as possible)?

--

### What did you expect to happen?

--

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.0.2
-   PostgreSQL version: 
-   DCS (and its version): 

### Patroni configuration file

```yaml
--
```

### patronictl show-config

```yaml
--
```

### Patroni log files

```shell
--
```

### PostgreSQL log files

```shell
--
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

--

**Comment by CyberDem0n** [comment]
Meh, what problem are you trying to solve?

**Comment by PiPi-Dragon** [comment]
![image](https://user-images.githubusercontent.com/27352343/227499858-05d7cfb8-85ca-43ab-b9bf-016ff86a7777.png)

Patroni did not receive the client's ack packet, triggering a retransmission.
There are 387 times the listen queue of a socket overflowed.

**Comment by PiPi-Dragon** [comment]
![image](https://user-images.githubusercontent.com/27352343/227502126-3b01b3ac-8b64-4c7a-9c98-f5ec7f3fc384.png)

**Comment by CyberDem0n** [comment]
```
listen(...)
    listen([backlog])
    
    Enable a server to accept connections.  If backlog is specified, it must be
    at least 0 (if it is lower, it is set to 0); it specifies the number of
    unaccepted connections that the system will allow before refusing new
    connections. If not specified, a default reasonable value is chosen.
```

5 is the backlog size, and it has nothing to do with retransmissions.

**Comment by CyberDem0n** [comment]
@PiPi-Dragon  The issue template we created for purpose, therefore please take you time to fill it up.
After that we can discuss.

**Comment by PiPi-Dragon** [comment]
I have resubmitted the issue
