### ISSUE TITLE
Using mkbinary.sh to create excecutable with RAFT

### ISSUE THREAD

**Issue by triscuitoraus** [zalando/patroni#2640]
### What happened?

When running the executable created by mkbinary.sh, I get the following error when attempting to run it with a raft configuration. Is there a way to setup Patroni with raft before running this script? Thanks in advance.

  File "patroni/__main__.py", line 183, in <module>
  File "patroni/__main__.py", line 144, in main
  File "patroni/__main__.py", line 136, in patroni_main
  File "patroni/daemon.py", line 179, in abstract_main
  File "patroni/__main__.py", line 25, in __init__
  File "patroni/dcs/__init__.py", line 115, in get_dcs
patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: kubernetes'
[24142] Failed to execute script '__main__' due to unhandled exception!

### How can we reproduce it (as minimally and precisely as possible)?

run mkbinary.sh

### What did you expect to happen?

raft dcs support

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.2
-   PostgreSQL version: n/a
-   DCS (and its version): raft

### Patroni configuration file

```yaml
n/a
```

### patronictl show-config

```yaml
n/a
```

### Patroni log files

```shell
n/a
```

### PostgreSQL log files

```shell
n/a
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by hughcapet** [comment]
@triscuitoraus we currently have the appropriate link (with invitation) provided in the README. Please, try to join once again
