### ISSUE TITLE
 Endpoint / Endpointslice objects become stuck in state where IP condition differs (not ready vs ready)

### ISSUE THREAD

**Issue by szuecs** [zalando/patroni#2644]
### What happened?

Reference: https://github.com/kubernetes/kubernetes/issues/117193

I think the problem is that Kubernetes version 1.23 or 1.24 changes how endpoints/endpointslices work, such that the current patch endpoint seems to be not mature enough anymore.
I can't provide more data, because I just found a report in slack and asked for a kubernetes issue, but it seems that patroni  should also do something in order to fix the availability issue shown there. 
From what I understand we at Zalando did not have the issue running kubernetes 1.22 right now, that's why I think the problem will appear in 1.23 or 1.24.

Please reach out to the referenced issue.

### How can we reproduce it (as minimally and precisely as possible)?

check the referenced issue

### What did you expect to happen?

check the referenced issue

### Patroni/PostgreSQL/DCS version

-   Patroni version: 
-   PostgreSQL version: 
-   DCS (and its version): 

### Patroni configuration file

```yaml
check the referenced issue
```

### patronictl show-config

```yaml
check the referenced issue
```

### Patroni log files

```shell
check the referenced issue
```

### PostgreSQL log files

```shell
check the referenced issue
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
Something is weird. The endpoint object from the referenced issue isn't managed neither by Patroni nor scripts from Spilo.

**Comment by CyberDem0n** [comment]
I am pretty sure

**Comment by szuecs** [comment]
@CyberDem0n thanks for checking!
