### ISSUE TITLE
ENVIRONMENT.rst missing "optional" tag in pg_rewind username,password

### ISSUE THREAD

**Issue by htsnorman** [zalando/patroni#2647]
### What happened?

https://github.com/zalando/patroni/blob/master/docs/ENVIRONMENT.rst

missing "optional" tag in two parameter:

```
PATRONI_REWIND_USERNAME: name for the user for pg_rewind; the user will be created during initialization of postgres 11+ and all necessary [permissions](https://www.postgresql.org/docs/11/app-pgrewind.html#id-1.9.5.8.8) will be granted.
PATRONI_REWIND_PASSWORD: password for the user for pg_rewind; the user will be created during initialization.
```

if dont define this two paramter:
`PATRONI_SUPERUSER_USERNAME: name for the superuser, set during initialization (initdb) and later used by Patroni to connect to the postgres. Also this user is used by pg_rewind.`

### How can we reproduce it (as minimally and precisely as possible)?

--

### What did you expect to happen?

--

### Patroni/PostgreSQL/DCS version

-   Patroni version: 
-   PostgreSQL version: 
-   DCS (and its version): 

### Patroni configuration file

```yaml
--
```

### patronictl show-config

```yaml
--
```

### Patroni log files

```shell
--
```

### PostgreSQL log files

```shell
--
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
Closed in #2650
