### ISSUE TITLE
inquiry: Set member as witness node

### ISSUE THREAD

**Issue by MS-Painter** [zalando/patroni#2651]
### What happened?

Hi, 

Not a bug report, community links don't seem to work so excuse me for the issue.

There are tags for `nofailover` but I didn't find any configuration to set a Patroni member as a "witness" node -

A member in the Patroni DCS cluster that isn't allowed to promote to `Leader` that is also not replicating/running the database.

Is there a way to configure a member to behave like this?
If not I can help out contributing such a feature.

### How can we reproduce it (as minimally and precisely as possible)?

-

### What did you expect to happen?

-

### Patroni/PostgreSQL/DCS version

-

### Patroni configuration file

```yaml
-
```

### patronictl show-config

```yaml
-
```

### Patroni log files

```shell
-
```

### PostgreSQL log files

```shell
-
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by monsterxx03** [comment]
Only systems that utilize a quorum election mechanism require witness node.

Patroni replies on third-part DCS system(e.g.: etcd, consul...) to do primary election, so witness node is useless for patroni (just from my opinion), it means patroni can be deployed on different nodes from DCS.

BTW, patroni has a in house raft choice as DCS(based on pysyncobj), but it's deperated now.

**Comment by MS-Painter** [comment]
Hey @monsterxx03 thanks for the reply.

From what I can tell etcd, consul, zookeeper don't currently have this as an actual feature, some of them just sort of support this with some tinkering.

I brought this feature up because Patroni already plays around with actual acquisition of the Leader lock from DCS and database ownership -
With tags like `nofailover`, `nosync`.

**Comment by MS-Painter** [comment]
Thank you @CyberDem0n for the explanation!

Some more questions challenging this feature.
(This is coming from constraints we have of low specs, allowing us up to 2 databases.)
(We're also running Patroni using `synchronous` mode.)

If I can get a 5 member cluster, with 3 `witness` nodes would this improve the reliability of the cluster?

In a 3 member cluster, with 1 `witness` node, wouldn't it be fine to have the witness down in a Patroni `synchronous` mode? Where I am allowed one node failure.

**Comment by CyberDem0n** [comment]
> we only need database replication between 2 members.

Perfect, you don't have to solve anything, just run 3 or 5 etcd/consul/zookeeper nodes.

**Comment by MS-Painter** [comment]
@CyberDem0n thank you for the clarification!
I'll try this out.
