### ISSUE TITLE
Feature Request: Support use lease as kubernetes leader key

### ISSUE THREAD

**Issue by waynerv** [zalando/patroni#2655]
### What happened?

Compared to Configmap and Endpoints, Lease object is more lightweight and efficient. Most of the built-in distributed components in Kubernetes already use lease as the leader key. 

When there are many pods of pg, check and update the leader key at each loop_wait will increase the load on the Kubernetes apiserver. Using lease can definitely help.

Of course, this should be an optional choice, and I am very willing to help implementing it.

### How can we reproduce it (as minimally and precisely as possible)?

-

### What did you expect to happen?

-

### Patroni/PostgreSQL/DCS version

-   Patroni version: 
-   PostgreSQL version: 
-   DCS (and its version): 

### Patroni configuration file

```yaml
-
```

### patronictl show-config

```yaml
-
```

### Patroni log files

```shell
-
```

### PostgreSQL log files

```shell
-
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

-

**Comment by waynerv** [comment]
Very convincing explanation, thank you for your kindness. 

Have been studying the source code of Patroni recently, is there any good first issue I can help with?

**Comment by CyberDem0n** [comment]
@waynerv maybe you want to check https://github.com/zalando/patroni/issues/2495
