### ISSUE TITLE
Standby cluster - Replication issue

### ISSUE THREAD

**Issue by ShashiYadav06** [zalando/patroni#2664]
### What happened?

Earlier cluster was working fine with 6 servers, now recently have updated postgres version from 10 to 14 and have restored data using pg_dumpall.
Issue -
 3 server are live where replication is working fine and 3 are standby server where replication is not working from live (leader) using pg_basebackup we are replicating data

Now after clearing all the data from data_dir of postgres and clearing cluster **patroni remove**  after starting patroni on the standby cluster data is getting streamed by patroni is not getting started 

Error logs observed in standby cluster patroni are --

**not healthy enough for leader race -server_name_here-
bootstrap_standby_leader in progress** 

this logs will be printed till  90% or 95% the data is copied  then new error will come 

pg_basebackup: error:  could not create directory "/var/lib/pgsql/data/base/1236546" : File exists
pg_basebackup: removing content from dataf directory "/var/lib/pgsql/data"

ERROR: Error while fetching backup: pg_basebackup exited with code = 1
ERROR: Failed to bootstrap from remote master postgresql://10.10.2.198:5432

INFO: Removing data directory "/var/lib/pgsql/data"
INFO: Removing initialize key after failed attempt to bootstrap the cluster

NOTE:- Live servers are doing replication 

### How can we reproduce it (as minimally and precisely as possible)?

.

### What did you expect to happen?

.

### Patroni/PostgreSQL/DCS version

-   Patroni version:  2.4.1
-   PostgreSQL version:  14.3
-   DCS (and its version):  ETCD - v3.5.4

### Patroni configuration file

```yaml
.
```

### patronictl show-config

```yaml
.
```

### Patroni log files

```shell
.
```

### PostgreSQL log files

```shell
.
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
> pg_basebackup: error: could not create directory "/var/lib/pgsql/data/base/1236546" : File exists
pg_basebackup: removing content from dataf directory "/var/lib/pgsql/data"

Well, pg_basebackup fails. How this could be a Patroni issue?
