### ISSUE TITLE
Implement ENV secrets for PostgreSQL user accounts

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#27]
We need a better way to set passwords for the three PostgreSQL accounts we need to use than keeping them in a configuration file which may be in poorly secured CMS repo.   I suggest that we use envdir, as several other Python projects (like WAL-E) do.  

Other ideas?

**Comment by CyberDem0n** [comment]
What other parameters should it be possible to set via environment variables (except passwords)?
I'm thinking about: 
* NAME (node name)
* SCOPE (cluster name)
* NAMESPACE (path inside DCS where cluster is stored, /service by default)
* RESTAPI_AUTH ('username:password' for accessing some of the endpoints)
* RESTAPI_CERTFILE
* RESTAPI_KEYFILE
* RESTAPI_LISTEN
* RESTAPI_CONNECT_ADDRESS
* POSTGRESQL_LISTEN
* POSTGRESQL_CONNECT_ADDRESS
* POSTGRESQL_DATA_DIR ?
* POSTGRESQL_PGPASS ?
* (ETCD|CONSUL|ZOOKEEPER)_HOST(S) ?

What about order of precedence? I think config file should have a priority.

**Comment by feikesteenbergen** [comment]
What about PATRONI_CONFIG? As since 9744019341608c475873d4d214299e3019cb1361 In that way you can run patroni totally with an ``envdir``.

**Comment by CyberDem0n** [comment]
Yeah, but with PATRONI_CONFIG it's not possible to change config and reload it...

**Comment by alexeyklyukin** [comment]
It is actually called 'PATRONI_CONFIGURATION' and it's mutually exclusive with the actual configuration files, so you cannot read from both.

I think we only move the actual secrets to the envdir, obviously, the passwords, but also RESTAPI_AUTH, RESTAPI_CERTFILE and RESTAPI_KEYFILE.

**Comment by CyberDem0n** [comment]
It is not only about passwords, but about running Patroni in a docker. For example it's not always possible to figure out your "connect_address" from inside docker.

**Comment by jberkus** [comment]
Exactly.  For example, when starting Patroni in Kubernetes, I can pass the Pod IP address as an ENV; it's not visible inside the container.

**Comment by LappleApple** [comment]
@CyberDem0n @alexeyklyukin @feikesteenbergen @jberkus What's the next step to take for this issue?

**Comment by CyberDem0n** [comment]
I believe https://github.com/zalando/patroni/pull/211 covers most of the use-cases. Closing this issue. If something is missing we will create a new one.
