### ISSUE TITLE
Replication slot creation fails when name contains a dash

### ISSUE THREAD

**Issue by ants** [zalando/patroni#275]
PostgreSQL replication slots names can only contain \[a-z0-9_\]. When trying to use hostname containing a dash or period as name, this creates the following exception on the master:

    ERROR: Exception when changing replication slots
    Traceback (most recent call last):
    File "/opt/app/patroni/lib/python2.7/site-packages/patroni/postgresql.py", line 921, in sync_replication_slots
    WHERE slot_name = %s)""", slot, slot)
    File "/opt/app/patroni/lib/python2.7/site-packages/patroni/postgresql.py", line 320, in query
    return self.retry(self._query, sql, *params)
    File "/opt/app/patroni/lib/python2.7/site-packages/patroni/utils.py", line 292, in __call__
    return func(*args, **kwargs)
    File "/opt/app/patroni/lib/python2.7/site-packages/patroni/postgresql.py", line 313, in _query
    raise e
    ProgrammingError: replication slot name "patroni-n2" contains invalid character
    HINT:  Replication slot names may only contain lower case letters, numbers, and the underscore character.

On the standby PostgreSQL fails to start up with the error `pg_ctl: could not start server`.

I think we should do one of:

1. Skip creating slots for invalid names.
2. Detect name containing invalid characters at startup and show a nicer error message.
3. Same as 2. but only when use_slots: true
4. Replace invalid characters with underscores when calculating the slot name.

I'm somewhat partial to 4 because I'd like to simplify the initial setup procedure to use hostname as name. This does create the danger of slot names colliding with names differing only in invalid characters, e.g. unicode names. Creating a replication slot name reservation mechanism in the DCS just for this issue seems kind of overkill. 2 seems like a no-go because it will break existing installs when upgrading.

Thoughts?

**Comment by alexeyklyukin** [comment]
I also like the 4th option. We can replace not allowed characters with their unicode positions (i.e u1234) instead of underscores, that would ensure the names are still unique. We should also emit warning to let the user know what's going on.

**Comment by CyberDem0n** [comment]
Fixed by https://github.com/zalando/patroni/pull/277
