### ISSUE TITLE
citus kill slow query

### ISSUE THREAD

**Issue by azeng528** [zalando/patroni#2752]
### What happened?

citus集群，5433/5432为协调节点
通过psql -U testdb -d testdb -h 192.168.2.2 -p 5432连接，然后执行select pg_sleep(3000);生成慢查询
然后通过psql -U testdb -d testdb -h 192.168.2.2 -p 5433，进行如下查询，报如下错误，请问怎么出来localhost了？
select global_pid,state,query from citus_dist_stat_activity;
WARNING:  Error on node with node id 0: failed to connect to localhost:5433

### How can we reproduce it (as minimally and precisely as possible)?

官方postgres0-2.yml启动，patroni版本3.0.3

### What did you expect to happen?

postgres0-2.yml生成了00-01-02用于副本

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.3
-   PostgreSQL version: 15.3
-   DCS (and its version): 3.5.7

### Patroni configuration file

```yaml
官方配置
```

### patronictl show-config

```yaml
官方配置
```

### Patroni log files

```shell
没有错误
```

### PostgreSQL log files

```shell
无错误
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by azeng528** [comment]
![image](https://github.com/zalando/patroni/assets/19300752/fe81db92-6d50-4af6-ade3-21b657833f86)

**Comment by CyberDem0n** [comment]
I am not totally understand what is the problem because I am not speaking your language, but I can certainly tell that this is not a Patroni issue. Under the hood it just runs Postgres/Citus that you provided.
