### ISSUE TITLE
pg start failed but /primary endpoint return 200

### ISSUE THREAD

**Issue by waynerv** [zalando/patroni#2756]
### What happened?

We experienced a Kubernetes production incident due to disk space running out, causing the Postgres process to shutdown. Surprisingly, throughout the entire repaire process, the pod remained in a Ready state. 

This Postgres instance was a single-instance and we used `/primary` api as the readniess probe endpoint . After studying the source code, I found that this endpoint also `/standby-leader` does not check whether the Postgres process is running, while `/replicas` does.
![企业微信截图_59dab74b-2379-4afc-980f-43775ba9eef6](https://github.com/zalando/patroni/assets/39515546/c6af9490-a1c4-4daf-8d04-43ddf5d725c9)

The documentation states that these two ep return an HTTP status code of 200 only when the Patroni node **is running** as primary with leader lock. Therefore, I believe this may be an issue.

### How can we reproduce it (as minimally and precisely as possible)?

Usually, when Patroni detects that PostgreSQL cannot start, it will downgrade its role. 

However, due to the "archive ready wals" feature, the entire HA loop seems to be blocked. This may be the root cause and I may create another issue for it. Therefore, reproducing this scenario may be difficult but it did indeed happen as the screenshot shows.

### What did you expect to happen?

/primary and /standby-leader return 503 when postgres is not in running state .

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.1.5
-   PostgreSQL version: 14 
-   DCS (and its version): kubernetes 1.18.7

### Patroni configuration file

```yaml
-
```

### patronictl show-config

```yaml
-
```

### Patroni log files

```shell
-
```

### PostgreSQL log files

```shell
-
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
> I found that this endpoint also /standby-leader does not check whether the Postgres process is running, while /replicas does.

Well, it seems that you came to a wrong conclusion. The role could be `standby_leader` only when postgres is up, running and queries are successfully executed: https://github.com/zalando/patroni/blob/a4d29eb99ea4e943f9d4fdae48ba9d14b46c567c/patroni/api.py#L1192-L1193

> due to the "archive ready wals" feature, the entire HA loop seems to be blocked.

Again wrong, it is executed from a different thread and doesn't block anything.

**Comment by CyberDem0n** [comment]
> /primary and /standby-leader return 503 when postgres is not in running state .

Meh... postgres could be in restarting state to apply some GUC changes and this is absolutely valid.

**Comment by waynerv** [comment]
Unfortunately, I only retrieved a small portion of the logs: [postgres-d24482ee-0-0-0713.log](https://github.com/zalando/patroni/files/12047720/postgres-d24482ee-0-0-0713.log). Hopefully it can be helpful.

FYI:
1. There were some issues with the archive server(absolutelly a disaster), causing all archiving to fail and resulting in a backlog of over 20,000 wal files.
2. After we expanded the disk space, patroni did not quickly start up the postgres process. Therefore, at around 15:32:28, I manually started the process using `pg_ctl start`.
3. As of now, patronictl list still shows that the status of postgres is "start failed", but still make it the leader.
![企业微信截图_62bee761-d32e-4942-b776-ac7195f461ac](https://github.com/zalando/patroni/assets/39515546/66ba7b5e-d03f-429d-b5e4-9033eca84ca8)

**Comment by CyberDem0n** [comment]
> There were some issues with the archive server(absolutelly a disaster), causing all archiving to fail and resulting in a backlog of over 20,000 wal files.

That's not  Patroni problem Archiving under normal circumstances is done by Postgres and typical a slow archive_command is a culprit.

> After we expanded the disk space, patroni did not quickly start up the postgres process. 

Well. If there is a huge backlog of unarchived files it may take a while for Patroni to process them. Archiving was necessary because recovery in a single-user more will clean them  up and there will be a hole in the continuous backup. https://github.com/zalando/patroni/pull/2726 partially mitigates it (if Patroni wasn't restarted at the same time when postgres crashed).

>Therefore, at around 15:32:28, I manually started the process using pg_ctl start.

Please never-ever-ever-ever-ever do anything with Postgres manually. Patroni decides what to do and when. The best you could use - `patronictl restart --force`.

> As of now, patronictl list still shows that the status of postgres is "start failed", but still make it the leader.

Because you manually brought the system to the inconsistent state. It is probably still busy archiving a backlog.

> the screenshots show there are indeed some cases where pg is unable to running but role still remain master

Yes, it is expected. There is just one node in the cluster and it owns the leader lock.

**Comment by waynerv** [comment]
@CyberDem0n Thank you very much for your patient explanation and advice.

> Yes, it is expected. There is just one node in the cluster and it owns the leader lock.

Still confused about the /primary endpoint not reflecting the running status of the instance, since there is already a /leader endpoint to check if it holds the leader lock.

If the expected goal of /primary is to check whether the database role is primary, we should explain it clearly in the documentation, then user should take additional measures to ensure that the database is available, such as executing select 1 sql.

If I want to detect whether an instance is a primary and in an acceptable read-write state through a health check endpoint, do you have any suggestions on which health check endpoint code should be used?

> Well. If there is a huge backlog of unarchived files it may take a while for Patroni to process them. Archiving was necessary because recovery in a single-user more will clean them up and there will be a hole in the continuous backup. https://github.com/zalando/patroni/pull/2726 partially mitigates it (if Patroni wasn't restarted at the same time when postgres crashed).

can we add a check to skip archive action for single instance? Is checking the member list count a reliable method?

**Comment by CyberDem0n** [comment]
@waynerv Let's take a step back and apply some common sense.
What are the consequences of `GET /primary` endpoint reporting 200 when postgres isn't (yet) running?
Client will either get connection refused errors because port isn't accessible, or postgres will refuse connections because it is in a starting/shutting down state.
Clients **must** be prepared to handle these errors and retry.

These health checks were primary implemented for load-balancers, which normally configured to declare a backend as healthy/failed when a certain number of health-checks succeeds/fails.
Example: https://github.com/zalando/patroni/blob/a4d29eb99ea4e943f9d4fdae48ba9d14b46c567c/extras/confd/templates/haproxy.tmpl#L23
Please pay attention to `inter 3s fall 3 rise 2`.
It means that health checks are executed with the interval 3s and TCP access to the primary will be open after 2 successful health checks.
If we start reporting on `GET /primary` endpoint only when we already know that `pg_is_in_recovery()` returns `false`, than we delay client connections and therefore **_increasing_** the visible (from the client) downtime.

Does it sound logical?

> can we add a check to skip archive action for single instance? Is checking the member list count a reliable method?

Meh. You have a single node cluster and continuous archiving can't keep up with the load. It means that you not only don't have an HA, but also will have a huge data loss if the volume/data will be damaged.
If you are totally fine with that data loss, maybe you should disable archiving and just periodically use pg_dump to take snapshots.
The decision depends on your RPO and RTO requirements, but you can't blame Patroni that it is trying to protect your precious data.

**Comment by waynerv** [comment]
Spent some time reproducing this issue to provide clearer context. The steps are as follows:
1. Create a single-instance pod with a small disk capacity (e.g., 5G) (use a smaller capacity PV or use the dd command to fill available space).
2. Add `sleep n` in `archive_command` to simulate slow archiving actions (the main purpose is to leave unarchived logs in the data directory and make patroni's asynchronous task of handling archives run longer than `primary_start_timeout`).
3. Use stress testing scripts to write the disk full and generate some unarchived log files.
4. After writing the disk full, the pg process will exit actively.
5. Patroni detects that pg has exited and begins trying to archive legacy logs while holding and updating leader locks throughout this period.
6. If archiving exceeds primary_start_timeout, since there is no object available for failover, it continues holding and updating leader locks.
## Patroni logs:
```
2023-07-18 19:12:51,455 INFO: no action. I am (postgres-31f99f98-0-0), the leader with the lock
2023-07-18 19:13:01,401 INFO: no action. I am (postgres-31f99f98-0-0), the leader with the lock
2023-07-18 19:13:11,400 INFO: no action. I am (postgres-31f99f98-0-0), the leader with the lock
2023-07-18 19:13:21,391 INFO: Lock owner: postgres-31f99f98-0-0; I am postgres-31f99f98-0-0
2023-07-18 19:13:26,411 INFO: closed patroni connection to the postgresql cluster
2023-07-18 19:13:26,494 ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 1294, in query
    cursor.execute(sql.encode('utf-8'), params)
psycopg2.OperationalError: connection pointer is NULL


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 1176, in get_postgresql_status
    row = self.query(stmt.format(postgresql.wal_name, postgresql.lsn_name), retry=retry)[0]
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 1118, in query
    return self.server.query(sql, *params)
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 1299, in query
    raise PostgresConnectionException('connection problems')
patroni.exceptions.PostgresConnectionException: connection problems
2023-07-18 19:13:26,531 WARNING: Retry got exception: connection problems
/tmp:5432 - accepting connections
2023-07-18 19:13:28,365 WARNING: Failed to determine PostgreSQL state from the connection, falling back to cached role
2023-07-18 19:13:28,365 ERROR: Exception when called state_handler.last_operation()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 237, in update_lock
    last_lsn = self.state_handler.last_operation()
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 1200, in last_operation
    return self._wal_position(self.is_leader(), self._cluster_info_state_get('wal_position') or 0,
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 443, in _cluster_info_state_get
    raise PostgresConnectionException(self._cluster_info_state['error'])
patroni.exceptions.PostgresConnectionException: Exceeded retry deadline
2023-07-18 19:13:28,485 WARNING: Failed to determine PostgreSQL state from the connection, falling back to cached role
2023-07-18 19:13:28,522 INFO: Error communicating with PostgreSQL. Will try again later
2023-07-18 19:13:31,719 INFO: Lock owner: postgres-31f99f98-0-0; I am postgres-31f99f98-0-0
2023-07-18 19:13:31,719 INFO: establishing a new patroni connection to the postgres cluster
2023-07-18 19:13:34,528 INFO: no action. I am (postgres-31f99f98-0-0), the leader with the lock
......<duplicate lines>
2023-07-18 19:15:01,437 INFO: no action. I am (postgres-31f99f98-0-0), the leader with the lock
2023-07-18 19:15:10,899 ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 1294, in query
    cursor.execute(sql.encode('utf-8'), params)
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 1176, in get_postgresql_status
    row = self.query(stmt.format(postgresql.wal_name, postgresql.lsn_name), retry=retry)[0]
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 1118, in query
    return self.server.query(sql, *params)
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 1299, in query
    raise PostgresConnectionException('connection problems')
patroni.exceptions.PostgresConnectionException: connection problems
2023-07-18 19:15:10,914 ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 1293, in query
    with self.patroni.postgresql.connection().cursor() as cursor:
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 322, in connection
    return self._connection.get()
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 29, in get
    self._connection = psycopg.connect(**self._conn_kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/psycopg.py", line 102, in connect
    ret = _connect(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  the database system is in recovery mode


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 1176, in get_postgresql_status
    row = self.query(stmt.format(postgresql.wal_name, postgresql.lsn_name), retry=retry)[0]
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 1118, in query
    return self.server.query(sql, *params)
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 1299, in query
    raise PostgresConnectionException('connection problems')
patroni.exceptions.PostgresConnectionException: connection problems
2023-07-18 19:15:11,393 INFO: Lock owner: postgres-31f99f98-0-0; I am postgres-31f99f98-0-0
2023-07-18 19:15:11,394 INFO: establishing a new patroni connection to the postgres cluster
2023-07-18 19:15:11,543 INFO: establishing a new patroni connection to the postgres cluster
2023-07-18 19:15:11,556 WARNING: Retry got exception: connection problems
/tmp:5432 - rejecting connections
2023-07-18 19:15:11,627 WARNING: Failed to determine PostgreSQL state from the connection, falling back to cached role
2023-07-18 19:15:11,627 ERROR: Exception when called state_handler.last_operation()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 237, in update_lock
    last_lsn = self.state_handler.last_operation()
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 1200, in last_operation
    return self._wal_position(self.is_leader(), self._cluster_info_state_get('wal_position') or 0,
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 443, in _cluster_info_state_get
    raise PostgresConnectionException(self._cluster_info_state['error'])
patroni.exceptions.PostgresConnectionException: Too many retry attempts
2023-07-18 19:15:11,687 WARNING: Failed to determine PostgreSQL state from the connection, falling back to cached role
2023-07-18 19:15:11,723 INFO: Error communicating with PostgreSQL. Will try again later
/tmp:5432 - no response
2023-07-18 19:15:21,422 WARNING: Postgresql is not running.
2023-07-18 19:15:21,422 INFO: Lock owner: postgres-31f99f98-0-0; I am postgres-31f99f98-0-0
2023-07-18 19:15:21,463 INFO: Reaped pid=57506, exit status=0
2023-07-18 19:15:21,464 INFO: pg_controldata:
  pg_control version number: 1300
  Catalog version number: 202107181
  Database system identifier: 7257093784493416600
  Database cluster state: in crash recovery
  pg_control last modified: Tue Jul 18 19:15:10 2023
  Latest checkpoint location: 0/788ED450
  Latest checkpoint's REDO location: 0/3BB3F128
  Latest checkpoint's REDO WAL file: 00000002000000000000003B
  Latest checkpoint's TimeLineID: 2
  Latest checkpoint's PrevTimeLineID: 2
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:758
  Latest checkpoint's NextOID: 32768
  Latest checkpoint's NextMultiXactId: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint's oldestXID: 727
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestActiveXID: 758
  Latest checkpoint's oldestMultiXid: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Tue Jul 18 19:12:01 2023
  Fake LSN counter for unlogged rels: 0/3E8
  Minimum recovery ending location: 0/0
  Min recovery ending loc's timeline: 0
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: logical
  wal_log_hints setting: on
  max_connections setting: 200
  max_worker_processes setting: 8
  max_wal_senders setting: 10
  max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float8 argument passing: by value
  Data page checksum version: 0
  Mock authentication nonce: ceaa872a70ec1fe72ec90b851aa030654e4bfed9afada17af800ee1308a2fc11

2023-07-18 19:15:21,476 INFO: Reaped pid=57507, exit status=0
2023-07-18 19:15:21,485 INFO: Reaped pid=57508, exit status=0
2023-07-18 19:15:21,558 INFO: doing crash recovery in a single user mode
2023-07-18 19:15:21,626 INFO: Trying to archive 000000010000000000000001: /opt/crunchy/bin/mock_archive.sh
2023-07-18 19:15:31,391 INFO: Lock owner: postgres-31f99f98-0-0; I am postgres-31f99f98-0-0
2023-07-18 19:15:31,404 INFO: updated leader lock during doing crash recovery in a single user mode
2023-07-18 19:15:41,391 INFO: Lock owner: postgres-31f99f98-0-0; I am postgres-31f99f98-0-0
2023-07-18 19:15:41,396 INFO: updated leader lock during doing crash recovery in a single user mode
2023-07-18 19:15:41,642 INFO: Failed to archive WAL segment 000000010000000000000001
2023-07-18 19:15:41,644 INFO: Trying to archive 000000010000000000000002: /opt/crunchy/bin/mock_archive.sh
2023-07-18 19:15:51,391 INFO: Lock owner: postgres-31f99f98-0-0; I am postgres-31f99f98-0-0
2023-07-18 19:15:51,448 INFO: updated leader lock during doing crash recovery in a single user mode
2023-07-18 19:16:01,391 INFO: Lock owner: postgres-31f99f98-0-0; I am postgres-31f99f98-0-0
2023-07-18 19:16:01,396 INFO: updated leader lock during doing crash recovery in a single user mode
2023-07-18 19:16:01,654 INFO: Failed to archive WAL segment 000000010000000000000002
......<duplicate lines>
2023-07-18 19:20:01,782 INFO: Trying to archive 00000001000000000000000F: /opt/crunchy/bin/mock_archive.sh
2023-07-18 19:20:11,391 INFO: Lock owner: postgres-31f99f98-0-0; I am postgres-31f99f98-0-0
2023-07-18 19:20:11,400 INFO: updated leader lock during doing crash recovery in a single user mode
2023-07-18 19:20:21,391 INFO: Lock owner: postgres-31f99f98-0-0; I am postgres-31f99f98-0-0
2023-07-18 19:20:21,435 INFO: updated leader lock during doing crash recovery in a single user mode
2023-07-18 19:20:21,792 INFO: Failed to archive WAL segment 00000001000000000000000F
2023-07-18 19:20:21,792 INFO: Trying to archive 000000010000000000000010: /opt/crunchy/bin/mock_archive.sh
2023-07-18 19:20:31,391 INFO: Lock owner: postgres-31f99f98-0-0; I am postgres-31f99f98-0-0
2023-07-18 19:20:31,397 WARNING: manual failover: members list is empty
2023-07-18 19:20:31,397 INFO: updated leader lock during doing crash recovery in a single user mode
2023-07-18 19:20:41,391 INFO: Lock owner: postgres-31f99f98-0-0; I am postgres-31f99f98-0-0
2023-07-18 19:20:41,397 WARNING: manual failover: members list is empty
2023-07-18 19:20:41,397 INFO: updated leader lock during doing crash recovery in a single user mode
2023-07-18 19:20:41,802 INFO: Failed to archive WAL segment 000000010000000000000010
```

### /primary response
```
[postgres@postgres-31f99f98-0-0 data]$ df .
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/vdb        20961280 20957932      3348 100% /pgdata
[postgres@postgres-31f99f98-0-0 data]$ patronictl list
+ Cluster: postgres-31f99f98 ----------+--------+--------------+----+-----------+
| Member                | Host         | Role   | State        | TL | Lag in MB |
+-----------------------+--------------+--------+--------------+----+-----------+
| postgres-31f99f98-0-0 | 245.1.138.26 | Leader | start failed |    |           |
+-----------------------+--------------+--------+--------------+----+-----------+
[postgres@postgres-31f99f98-0-0 data]$ curl http://127.0.0.1:8009/primary
{"state": "start failed", "role": "master", "dcs_last_seen": 1689678981, "database_system_identifier": "7257093784493416600", "patroni": {"version": "3.0.4", "scope": "postgres-31f99f98"}}
[postgres@postgres-31f99f98-0-0 data]$ curl -v http://127.0.0.1:8009/primary
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8009 (#0)
> GET /primary HTTP/1.1
> Host: 127.0.0.1:8009
> User-Agent: curl/7.61.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: BaseHTTP/0.6 Python/3.6.8
< Date: Tue, 18 Jul 2023 11:16:33 GMT
< Content-Type: application/json
<
* Closing connection 0
{"state": "start failed", "role": "master", "dcs_last_seen": 1689678991, "database_system_identifier": "7257093784493416600", "patroni": {"version": "3.0.4", "scope": "postgres-31f99f98"}}

[postgres@postgres-31f99f98-0-0 data]$ curl -v http://127.0.0.1:8009/primary
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8009 (#0)
> GET /primary HTTP/1.1
> Host: 127.0.0.1:8009
> User-Agent: curl/7.61.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: BaseHTTP/0.6 Python/3.6.8
< Date: Tue, 18 Jul 2023 11:23:08 GMT
< Content-Type: application/json
<
* Closing connection 0
{"state": "start failed", "role": "master", "dcs_last_seen": 1689679381, "database_system_identifier": "7257093784493416600", "patroni": {"version": "3.0.4", "scope": "postgres-31f99f98"}}
```

**Comment by CyberDem0n** [comment]
My opinion about it doesn't change. A single node cluster with archive_command that can't keep up with the load is a very strange thing. 
If the volume is damaged you'll loose a lot of transactions because many WAL files never made it to archive. 
Either you need to improve the speed of archiving or disable it completely and just use periodically pg_dump instead of continuous archiving

**Comment by waynerv** [comment]
Turns out there is a difference in our common sense.

The primary task of a health check endpoint is to telling the truth whether the service is currently running, rather than estimating or assuming that it will run eventually, and give clients a positive illusion. 
It doesn't make much sense if we tell the clients that our service is currently working fine, but they keep encountering errors when making requests.

If we aim to reduce downtime, lowering the success threshold could be effective. We can configure the success/fail threshold and timeout to determine the status strategy. It is not the responsibility of the health check endpoint to address downtime.

> Meh... postgres could be in restarting state to apply some GUC changes and this is absolutely valid.

That's correct, but due to the failure threshold, we don't immediately consider the service to have transitioned from ready to failed state. However, if after exceeding the threshold limit (e.g. 3 times), instances still haven't responded and resumed operation, we should carefully consider there is any abnormality with the instance. In fact, the service is currently not able to accept read/write requests.

Let's cut off irrelevant factors such as archiving and only consider the scenario where a single instance has insufficient available space in the data directory. 
The database keeps switching between different roles, and `/primary` keeps returns 200. However, it can be certain that this instance is no longer available:
```
[postgres@postgres-31f99f98-0-0 /]$ curl -v http://127.0.0.1:8009/primary
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8009 (#0)
> GET /primary HTTP/1.1
> Host: 127.0.0.1:8009
> User-Agent: curl/7.61.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: BaseHTTP/0.6 Python/3.6.8
< Date: Wed, 19 Jul 2023 01:23:45 GMT
< Content-Type: application/json
<
* Closing connection 0
{"state": "starting", "role": "replica", "dcs_last_seen": 1689729818, "database_system_identifier": "7257093784493416600", "patroni": {"version": "3.0.4", "scope": "postgres-31f99f98"}}

[postgres@postgres-31f99f98-0-0 /]$ curl -v http://127.0.0.1:8009/primary
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8009 (#0)
> GET /primary HTTP/1.1
> Host: 127.0.0.1:8009
> User-Agent: curl/7.61.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: BaseHTTP/0.6 Python/3.6.8
< Date: Wed, 19 Jul 2023 01:23:46 GMT
< Content-Type: application/json
<
* Closing connection 0
{"state": "starting", "postmaster_start_time": "2023-07-19 09:23:20.580116+08:00", "role": "replica", "server_version": 140007, "xlog": {"received_location": 2365585736, "replayed_location": 2365585736, "replayed_timestamp": "2023-07-18 19:14:40.294696+08:00", "paused": false}, "timeline": 2, "replication_state": "in archive recovery", "dcs_last_seen": 1689729818, "database_system_identifier": "7257093784493416600", "patroni": {"version": "3.0.4", "scope": "postgres-31f99f98"}}

[postgres@postgres-31f99f98-0-0 /]$ curl -v http://127.0.0.1:8009/primary
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8009 (#0)
> GET /primary HTTP/1.1
> Host: 127.0.0.1:8009
> User-Agent: curl/7.61.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: BaseHTTP/0.6 Python/3.6.8
< Date: Wed, 19 Jul 2023 01:23:50 GMT
< Content-Type: application/json
<
* Closing connection 0
{"state": "unknown", "role": "promoted", "dcs_last_seen": 1689729827, "database_system_identifier": "7257093784493416600", "patroni": {"version": "3.0.4", "scope": "postgres-31f99f98"}}
```

I think we should do something to improve this situation.

**Comment by CyberDem0n** [comment]
> Turns out there is a difference in our common sense.

Exactly. It seems that you still don't understand the reasoning behind the current implementation.

> The primary task of a health check endpoint is to telling the truth whether the service is currently running, rather than estimating or assuming that it will run eventually, and give clients a positive illusion.

Wrong. The primary task of the `/primary` health-check endpoint is providing a load-balancers an information where the primary currently is or will be running soon.

> It doesn't make much sense if we tell the clients that our service is currently working fine, but they keep encountering errors when making requests.

Clients are not even supposed to be communicating with health-check endpoints. The only thing that clients know - the host and port where they have to connect in order to get access to postgres. And, they can't even differentiate between Postgres not accepting connections or load-balancer rejecting connections because health-checks are failing.

> If we aim to reduce downtime, lowering the success threshold could be effective. We can configure the success/fail threshold and timeout to determine the status strategy. It is not the responsibility of the health check endpoint to address downtime.

Again, you have wrong expectations. Not all load-balancers will allow you to reduce interval/threshold  below certain values. Example: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html
Besides that, more frequent health checks result in increased load on Patroni REST API and Postgres.

> That's correct, but due to the failure threshold, we don't immediately consider the service to have transitioned from ready to failed state. However, if after exceeding the threshold limit (e.g. 3 times), instances still haven't responded and resumed operation, we should carefully consider there is any abnormality with the instance. In fact, the service is currently not able to accept read/write requests.

Restart could easily take time that exceeding these thresholds. When restart is finished it will take at least 10 additional seconds before NLB will start routing traffic to the primary. I am not even talking about the fact that NLB does a simple **round-robin across all backends when health-check is failing** for all of them. That is, it will connect you to a random replica!

> Let's cut off irrelevant factors such as archiving and only consider the scenario where a single instance has insufficient available space in the data directory.
The database keeps switching between different roles, and /primary keeps returns 200. However, it can be certain that this instance is no longer available:

Yes, it responds with 200 because it owns the leader lock. And, it doesn't give the leader lock up, because there are **no other healthy nodes** that could become primary. Applications don't care about health-checks, they get errors in all cases, whether health-check is failing or not.

> I think we should do something to improve this situation.

If your suggestion is implemented the downtime for applications will increase without any other benefits or improvements. This isn't a price most people want to pay.

**Comment by waynerv** [comment]
Thank you again for patiently explaining. 

I must admit that my expectations of `/primary` were different from its actual purpose. 
As you said, it is used by LB to discover the master node and route requests to it. 

However, my use case was to use it as a health monitor, triggering alerts and repairs when a node becomes abnormal. That's why I'm particularly concerned about whether instances are running or not.

Will look for other solutions to meet my needs.

**Comment by CyberDem0n** [comment]
You can build flexible alerts based on the content of returned JSON documents.
