### ISSUE TITLE
Patroni packages (3.0.3 and up) for RHEL7

### ISSUE THREAD

**Issue by 1schmnkS** [zalando/patroni#2758]
### What happened?

Hello. 

Quick question: I noticed that no patroni packages > 3.0.2 have been pushed to RHEL7 repos (eg https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-7-x86_64/) ; 

for RHEL8|9 everything looks good. 

Any reason why RHEL7 has been left out? 

kind regards

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### What did you expect to happen?

n/a

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.3 and newer 
-   PostgreSQL version: n/a
-   DCS (and its version): n/a

### Patroni configuration file

```yaml
n/a
```

### patronictl show-config

```yaml
n/a
```

### Patroni log files

```shell
n/a
```

### PostgreSQL log files

```shell
n/a
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
Please use https://yum.postgresql.org/contact/ to report issues with RPM packages.
