### ISSUE TITLE
Extending `nofailover` flag with configurable priorities

### ISSUE THREAD

**Issue by mfpekala-nutanix** [zalando/patroni#2759]
# The Problem

We want more granular control of elections in HA setups than is currently given by the `failover/nofailover` flag. Specifically, for some deployments being able to give "hints" configuring things like  "this node is the preferred primary" would be helpful.

Right now, when a failure happens in the primary, each node detects it and then uses `is_healthiest_node` to determine whether it should race for the leader key. This is where we exclude nodes that have marked `nofailover` as well as nodes with too much lag. After this, we then get a list of other nodes which could participate in the leader race and compare our WAL position to their WAL position. Only if our WAL position is greater than every WAL position we receive from other nodes do we attempt to acquire the leader lock.

Imagine there is a replica node that we'd really like to become the next leader (perhaps because of asymmetric hardware or multi-zone replication, details below). In most cases, the above strategy will work "automatically", since the machine with beefier specs or less lag or whatever will _probably_ have a higher WAL position and thus be the "healthiest node" in this election. However this is not guaranteed. There could be a case when a less-desirable replica sees it's own WAL position as equal to or ahead of the more-desirable node and they both run for election, opening us up to a case where our most-desired replica does not win.

# Potential Solution

At a general level, we take inspiration from [MongoDB's replica sets](https://www.mongodb.com/docs/manual/core/replica-set-elections/) and propose a priority system. The change would replace the `nofailover` flag with a numeric value, `failover_priority`, defaulting to `1`, with the following properties:

- Setting `failover_priority: 0` is equivalent to `nofailover: true`, meaning this node will _never_ attempt to become the primary.
- Setting the same `failover_priority` for each node will mimic the current system when `nofailover` is false. In other words, every node will perform the same `is_healthiest_node` check and only the node with the highest WAL position will try to claim the leader key.
- Otherwise, `is_healthiest_node` will ping the other nodes that can race and do the following:
    - First, it will see if there is another node that is within the maximum replication lag that has a higher priority. If so it will return False in favor of that higher-priority node.
    - Second, it will see if there is another node at the same priority that has a higher WAL status. In this case it will return False in favor of the equally high-priority node that's more up to date.
    - Otherwise it returns True and races for leadership

In essence, instead of using WAL status alone to decide the healthiest node, it first uses user-given priority, and then WAL status. It does this while also still providing the guarantee that any node that races for leadership be within `max_replication_lag` to limit data loss.

This strategy errs on the side of caution and does not guarantee that the highest priority node will _always_ win. Imagine a case where a lower priority replica reads a substantially out-of-date WAL position from the preferred replica and sees that it's behind maximum replication lag. Then the lower-priority replica will race for leadership and could win. However, this is unlikely and this strategy makes it much more likely that higher priority nodes replicas will win without breaking the correctness of the election process or data loss guarantees.

## Argument for Correctness

The correctness of this strategy follows from the correctness of the original algorithm.

Suppose that the leader key lapses. Just like before, any node that is lagging by more than `max_replication_lag` discards itself as not healthy enough to run for election. Unlike before where any node that sees itself as having the highest WAL status will call itself "healthiest" and run for election, we now require that it see itself as having the highest priority _and_ highest WAL status of nodes with that priority. As long as there are _some_ nodes within enough lag to become primary, one of them will pass this criteria and call itself healthiest. 

# Why Is It Important?

There are a couple reasons users of HA setups might want this:

## Asymmetric Hardware

Perhaps one of your machines happens to have beefier specs than the others. Ideally you'd like leadership and writes to be on the beefy machine to improve performance in the average case.

## Preferred Zone in Multizone Synchronous Replication

If you are running synchronous replication across zones, you may have a preference about where leadership ends up when crashes happen. Being able to probabilistically prefer certain zones for these setups could provide value.

## Ideas for Testing

Unit tests:

- Ensure that nodes with `failover_priority: 0` still never call `self.acquire_lock`.
- Ensure that the priority configuration of the system successfully makes it to the DCS and is viewable by every node.
- Ensure that the node(s) with the highest priority that are within max replication lag consider themselves healthiest and call `self.acquire_lock`
- Ensure that when a low-priority node see's a high-priority node that is within tolerable lag it does not call `self.acquire_lock`
- Ensure that when a low-priority node see's a higher-priority node that has too much lag the lower priority node will still call `self.acquire_lock`.

Behave tests:

- 3 node system where two nodes have `failover_priority: 0`, and the leader has `failover_priority: 1`. Ensure that when the leader fails neither of the other nodes take over.
- 3 node system where two nodes have `failover_priority: 1` and the other has `failover_priority: 0`. Failover should go to the other `failover_priority: 1` node.
- 3 node system where the old leader has `failover_priority: 2`, one of the replicas has `failover_priority: 2` and the other has `failover_priority: 1`. Failover should go to the `failover_priority: 2` replica.

**Comment by mfpekala-nutanix** [comment]
> What would be typical values of this delay? How will it be calculated?

The `failover_priority` value for each node would be in the DCS and visible to all nodes. Each node then can see the maximum `failover_priority` on any node in the system. If a nodes priority is `p` and the max is `m` then it would sleep `(m/p - 1) * LOSE`, where LOSE is something that will be found experimentally, but (I'm guessing from playing around) somewhere between 200ms - 1000ms. This expression is nice because when `p` is `m`, it yields `0` seconds, and as `p` approaches `0` it sleeps for arbitrarily large amounts of time. 

The value of LOSE could also be exposed as a configuration parameter, or it could be calculated as the node is running (as some measure of latency to the DCS). Ideally, it should be slightly larger than the amount of time it typically takes for the winning node to claim the leader key, so it makes it much more likely that this node loses.

**Comment by mfpekala-nutanix** [comment]
After starting to take a stab at the implementation, I realized a potentially easier solution that avoids the need for delays and gets more at the root of the problem. @CyberDem0n I've edited the original issue to reflect the new problem statement/potential solution.

In essence, priority will be an extra check in the internal `_is_healthiest_node` function. Here, instead of just checking for the highest WAL status, we check for highest priority, and then highest WAL status among those nodes (assuming that we start by filtering out all nodes who are outside of the tolerable lag).

What are your thoughts on this change to the solution idea?

**Comment by XiuhuaRuan** [comment]
We also need this feature for higher failover priority in the main datacenter than backup datacenter.  Could you please share us when this feature is planned to be ready? Thanks.

**Comment by nexcode** [comment]
We also lack the ability to specify a preferred master in the cluster. Now you can only completely exclude a node from voting for the master. We would really like to be able to implement behavior in which one of the servers will be preferentially selected as a master over the others, even if there is already a master.

**Comment by dberardo-com** [comment]
i can read in the doc about tags, but it is not clear how to assign them. is it possible to assign tags using the REST api or the patronictl command ? i believe the doc should be more explicit on this point.
and are those tags available only with Consul or not
