### ISSUE TITLE
Feature: view/edit tags through Patroni API

### ISSUE THREAD

**Issue by mfpekala-nutanix** [zalando/patroni#2772]
### What happened?

Tags are required to set some configurations, and also provide a way for developers to add additional information to each node. However, as far as I can tell from the API docs, there aren't endpoints to view/modify tags. From reading the code, I don't see a reason why any of the `tags` configs (`nofailover`, `nosync`, `noloadbalance`, `clonefrom`, or user custom) couldn't be changed while the node is running from the API. Added basic support for this.

### How can we reproduce it (as minimally and precisely as possible)?

Try to modify the tags of a node through the API.

### What did you expect to happen?

As far as I can tell, tags should be fine to update/view while the node is running.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.4
-   PostgreSQL version: 15
-   DCS (and its version): etcd 3.5.9

### Patroni configuration file

```yaml
N/A
```

### patronictl show-config

```yaml
N/A
```

### Patroni log files

```shell
N/A
```

### PostgreSQL log files

```shell
N/A
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
> As far as I can tell, tags should be fine to update/view while the node is running.

Well... there are following obstacles:
1. Patroni config is not necessarily a file, it could be just `PATRONI_CONFIGURATION` environment variable.
2. Even if it is a file, Patroni may not have sufficient permissions to change it.
3. Even when Patroni has enough permissions to update the file, what if something goes wrong and we end up with the broken config and it will prevent Patroni from starting up next time.

**Comment by mfpekala-nutanix** [comment]
I submitted a simple PR to add in support for `GET /tags` and a version of `PATCH /tags` that doesn't persist between restarts.

**Comment by CyberDem0n** [comment]
> We could still add a GET /tags endpoint to view the value of tags on a given node which could be helpful

This is redundant. Tags are already exposed as a part of any `GET /*` health check endpoint: https://patroni.readthedocs.io/en/latest/rest_api.html#health-check-endpoints

> What if there is a PATCH /tags but it doesn't guarantee that changes will persist between restarts?

It is even more confusing for people.

**Comment by dberardo-com** [comment]
this feature would be nice to have. or at least via the patronictl command. i am using this operator https://access.crunchydata.com/documentation/postgres-operator/latest/references/crd/5.6.x/postgrescluster#postgresclusterspecdatasourcepostgrescluster and have no way to assign specific tags to instances. .. i would like to go via the API but dont know how to PATCH for a specific node only
