### ISSUE TITLE
Potential hardcoded secrets

### ISSUE THREAD

**Issue by SlimTrabelsi** [zalando/patroni#2798]
### What happened?

Hi,
I identified some potential hardcoded secrets in your source code (maybe false positives)
https://github.com/zalando/patroni/blob/d5b3d943779ebec31dc65c54c897e34d83878ea0/features/environment.py#L583
https://github.com/zalando/patroni/blob/4872ac51e00abefc98678f1771dd93aead59f4ce/kubernetes/citus_k8s.yaml#L480

I hope that it helps

### How can we reproduce it (as minimally and precisely as possible)?

Run a secret scan

### What did you expect to happen?

Can be used by attacker remotely 

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.4

### Patroni configuration file

```yaml
N/A
```

### patronictl show-config

```yaml
N/A
```

### Patroni log files

```shell
N/A
```

### PostgreSQL log files

```shell
N/A
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
These all are used for testing.
