### ISSUE TITLE
Replication slots don't prevent recycling of WAL when standby goes offline

### ISSUE THREAD

**Issue by ants** [zalando/patroni#280]
When standby goes offline for a while the member key will expire and Patroni will happily remove its replication slot.  Having an archive works around this, but it would be nice to make simple deployments more resilient too. Probably needs some kind of persistent flag, or offline_ttl for cluster members so Patroni knows they will be coming back and doesn't remove their replication slots. And a corresponding administration command to kick them out when they actually need to go away.

**Comment by AiAlex** [comment]
Is this problem solved?

**Comment by ants** [comment]
This issue is still active, patches are welcome.

While this is not done, `wal_keep_segments` is a decent workaround. I think in most cases an upper limit for how far behind a replication slot can be would be needed anyway because having the master go down due to full disk is worse than having to reinit a standby. And you need to keep the disk space available for that purpose, so it doesn't matter too much if you are using that disk space even if you don't actually need to.
