### ISSUE TITLE
Does Patroni not support using logical replication between clusters while using streaming replication internally?

### ISSUE THREAD

**Issue by jackin853** [zalando/patroni#2844]
### What happened?

> I have two sets of Patroni clusters and I want to build a disaster recovery plan. Both sets of clusters use physical streaming replication internally, but I want to use logical replication between the clusters because I don't need to replicate some tables. I have been trying to configure it following the official documentation, but I haven't succeeded. The documentation is too vague and only mentions using streaming replication between clusters with a diagram, and there are no examples to refer to. Does Patroni not support using logical replication between clusters while using streaming replication internally?

### How can we reproduce it (as minimally and precisely as possible)?

nothing

### What did you expect to happen?

using logical replication between patroni clusters and using streaming replication internal cluster

### Patroni/PostgreSQL/DCS version

-   Patroni version: 
-   PostgreSQL version: 
-   DCS (and its version): 

### Patroni configuration file

```yaml
nothing
```

### patronictl show-config

```yaml
nothing
```

### Patroni log files

```shell
nothing
```

### PostgreSQL log files

```shell
nothing
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by hughcapet** [comment]
please, ask questions [in the dedicated Slack channel](https://github.com/zalando/patroni#community) (you will also get answers to your question quicker there). Github issues is only for bug reports.
