### ISSUE TITLE
Watching for index may raise EtcdEventIndexCleared

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando/patroni#285]
In https://github.com/zalando/patroni/blob/master/patroni/dcs/etcd.py#L374 we look in the past to see if the key has changed. If more than n (probably 1000) index changes have taken place, this fails with:

```txt
EtcdEventIndexCleared: The event in requested index is outdated and cleared : the requested history has been cleared [208985434/206124848]
```

It occured when manually setting a leader key, to ensure no member would promote itself to master.

**Comment by CyberDem0n** [comment]
Solved by https://github.com/zalando/patroni/pull/287
