### ISSUE TITLE
Enhancement: Retry mechanism when processing Kubernetes API calls

### ISSUE THREAD

**Issue by csnand** [zalando/patroni#2856]
### What happened?

The following code snippet was taken from Patroni 3.1.0

```
def _run_and_handle_exceptions(method: Callable[..., Any], *args: Any, **kwargs: Any) -> Any:
    try:
        return method(*args, **kwargs)
    except k8s_client.rest.ApiException as e:
        if e.status == 403:
            logger.exception('Permission denied')
        elif e.status != 409:  # Object exists or conflict in resource_version
            logger.exception('Unexpected error from Kubernetes API')
        return False
    except (RetryFailedError, K8sException) as e:
        raise KubernetesError(e)


def catch_kubernetes_errors(func: Callable[..., Any]) -> Callable[..., Any]:
    def wrapper(self: 'Kubernetes', *args: Any, **kwargs: Any) -> Any:
        try:
            return _run_and_handle_exceptions(func, self, *args, **kwargs)
        except KubernetesError:
            return False
    return wrapper
```

As shown above, these functions were used to deal with exceptions that may occur during Kubernetes API calls.
As occurred quite a few times the Kubernetes API server may not be responsive from time to time. In this case, such API calls would result in timed-out exceptions. 

Without retries, the Kubernetes API call exceptions were just raised to the upper levels which would in turn eventually affect the serviceability of the Patroni itself. 

In our use cases, adding a retry mechanism would significantly reduce the chance of these kinds of exceptions popping up and affecting the Patroni run cycle.

Therefore, I was wondering if it's possible to add a retry mechanism when processing Kubernetes API calls.
Thank you very much.

### How can we reproduce it (as minimally and precisely as possible)?

This issue occurs when the Kubernetes cluster, especially the Kubernetes API server is in a unstable status.

### What did you expect to happen?

Retry when there were Kubernetes API call exceptions.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.1.0
-   PostgreSQL version: 13.11
-   DCS (and its version): Kubernetes 1.26

### Patroni configuration file

```yaml
N/A
```

### patronictl show-config

```yaml
N/A
```

### Patroni log files

```shell
N/A
```

### PostgreSQL log files

```shell
N/A
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
All important calls to K8s API are already properly retried.
Please stop opening issues for questions, is you want to discuss something there is a #Patroni channel on [Postgres Slack](https://pgtreats.info/slack-invite).
