### ISSUE TITLE
Cluster endpoint provides not parseable answer

### ISSUE THREAD

**Issue by sskserk** [zalando/patroni#2862]
### What happened?

A node of patroni cluster was killed and restarted a couple times with minimum intervals

### How can we reproduce it (as minimally and precisely as possible)?

A node of patroni cluster was killed and restarted a couple times with minimum intervals

### What did you expect to happen?

A parseable json content returned

### Patroni/PostgreSQL/DCS version

-   Patroni version: 
-   PostgreSQL version: 
-   DCS (and its version): 

### Patroni configuration file

```yaml
Nothing special
```

### patronictl show-config

```yaml
Nothing special
```

### Patroni log files

```shell
Nothing special
```

### PostgreSQL log files

```shell
Nothing special
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

Cluster endpoint ("/cluster") provides non parseable response:

`
{
  "members": [
    {
      "name": "patroni-10.128.0.147",
      "role": "leader",
      "state": "running",
      "api_url": "http://10.128.0.147:8008/patroni",
      "host": "[10.128.0.147](https://10.128.0.147/)",
      "port": 5432,
      "timeline": 20,
      "pending_restart": true
    },
    {
      "name": "patroni-10.128.0.148",
      "role": "sync_standby",
      "state": "running",
      "api_url": "http://10.128.0.148:8008/patroni",
      "host": "[10.128.0.148](https://10.128.0.148/)",
      "port": 5432,
      "timeline": 20,
      "pending_restart": true,
      "lag": 0
    },
    {
      "name": "patroni-10.128.0.149",
      "role": "replica",
      "state": "start failed",
      "api_url": "http://10.128.0.149:8008/patroni",
      "host": "[10.128.0.149](https://10.128.0.149/)",
      "port": 5432,
      "lag": "unknown"
    }
  ]
}

`

It is expected that the Lag attribute of a member node will be set to an integer value. Instead, the "Unknown" value is provided. 

The provided value cannot be automatically parsed since a parser normally expects to an integer value.
Somehow it is clear that patroni itself could not obtain the required information from the nested logic...it would make sense not to return the attribute at all in such a case.

**Comment by CyberDem0n** [comment]
I don't think that we ever made a promise about `lag` data type.
