### ISSUE TITLE
SSL handshake failure

### ISSUE THREAD

**Issue by maximegaillard** [zalando/patroni#298]
**Patroni Version:**

1.0

**Steps to Reproduce:**

I'm trying to build a Postgresql cluster with Patroni (if you want to know, on top of https://github.com/rancher/rancher). I've got 3 Postgresql nodes, one Etcd container, and a HAproxy loadbalancer.

I can access Postgresql through the no-ssl port (1111), but through the SSL port I can't : my `psql` command ends up stalling.

According to the HAProxy logs, the issue is an `SSL Handshake failure` :
`Sep  9 09:39:37 localhost haproxy[1132]: xx.xx.xx.xx:55815 [09/Sep/2016:09:39:17.275] e54cf7f6-9f4a-4487-87a3-aa3adb340ad2_5432_frontend/1: SSL handshake failure`

The strange thing is, I can access it with openssl

```
openssl s_client -connect FQDN:5432
CONNECTED(00000003)
depth=1 /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/CN=FQDN
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
XXX
-----END CERTIFICATE-----
subject=/CN=FQDN
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
No client certificate CA names sent
---
SSL handshake has read 3442 bytes and written 456 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES128-SHA
    Session-ID: 3D637AAFDBA43D1021A9F083AAE54E8940F048E6210AC4DE313A5FA031DA38C6
    Session-ID-ctx:
    Master-Key: EABBC21601CC27E6259678A03B30E882E3AA182C12D71B47C8FD8AE69DA039F020B7FD19EF18DF85E5FAEDA96C29842B
    Key-Arg   : None
    Start Time: 1473407829
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by CyberDem0n** [comment]
Where do you terminate SSL?
It looks like you are trying to do it on the HAproxy side and I am not sure that HAProxy has special support of pgsql protocol.
For example I know that stunnel can terminate ssl for the postgres: http://www.stunnel.org/pipermail/stunnel-users/attachments/20071106/cfda8976/attachment.obj

**Comment by maximegaillard** [comment]
I only use HAProxy with this configuration:

```
frontend ssl_frontend
        bind *:5432  ssl crt /etc/haproxy/certs/
        mode tcp

    	default_backend my_backend

frontend my_frontend
        bind *:1111
        mode tcp

    	default_backend my_backend

backend ssl_backend
        mode tcp
        server dee3cbde-df1e-4a1c-a236-00f48d371ac5 10.42.24.77:5432
        server 5e1c7f94-4184-4675-99ef-a7cbc867c2e8 10.42.76.136:5432
        server a2b33d81-8040-43e3-9d8c-c3833800415b 10.42.175.179:5432
        server 72f17a0f-3876-421b-bdec-ab1a63a60c71 10.42.19.212:5432

backend my_backend
        mode tcp
        server dee3cbde-df1e-4a1c-a236-00f48d371ac5 10.42.24.77:5432
        server 5e1c7f94-4184-4675-99ef-a7cbc867c2e8 10.42.76.136:5432
        server a2b33d81-8040-43e3-9d8c-c3833800415b 10.42.175.179:5432
        server 72f17a0f-3876-421b-bdec-ab1a63a60c71 10.42.19.212:5432
```

Are you saying I can't do SSL offloading (have an SSL traffic between the client and HAProxy and a clear traffic between HAProxy and DB nodes?) with HAProxy and I have to use stunnel (or directly configure SSL on my Postgres nodes) ?

**Comment by CyberDem0n** [comment]
> Are you saying I can't do SSL offloading (have an SSL traffic between the client and HAProxy and a clear traffic between HAProxy and DB nodes?) with HAProxy.

Yep, HAProxy works perfectly for http(s) protocol, but it looks like it doesn't support "pgsql" protocol.

> and I have to use stunnel (or directly configure SSL on my Postgres nodes) ?

I just gave stunnel as an example, because it can deal with the "pgsql" handshake.
If you put stunnel in front of HAProxy it will work (I mean it will do SSL offloading for you), but I think it is better to have certificates directly on the postgres nodes.

**Comment by maximegaillard** [comment]
This is something very strange... 
I tried to add certificates directly on the postgres nodes and now it works like a charm.
Thx!
