### ISSUE TITLE
Have any one a concept idea for a multi datacenter cluster?

### ISSUE THREAD

**Issue by daswars** [zalando/patroni#299]
Have any one a concept idea for a multi datacenter cluster?
(Two data centers in the composite)

**Comment by uspen** [comment]
Hello! I use PG in two DC. What are you interested in?

**Comment by daswars** [comment]
Thanks for the fast answer.

Here is my wish scenario.

DC1 (primary):

- 2 Haproxy in Server cluster (Here i use PFsense with carp)
- 2 etcd  Server in cluster (Can i route the request over the haproxy)
- 2 postgres/patroni server  

DC2 (secondary):

- 2 Haproxy in Server cluster (Here i use PFsense with carp)
- 2 etcd  Server in cluster (Can i route the request over the haproxy)
- 2 postgres/patroni server  

How can i replicate postgres the  postgres/patroni server  over the two Datacenter(DC)?

**Comment by uspen** [comment]
Etcd It requires quorum! [See doc](https://coreos.com/etcd/docs/latest/admin_guide.html)
My view about 2 DC (If left DC down, we need up new etcd for right DC for quorum (not tested yet)):
[PostgreSQL HA - not HA DC.pdf](https://github.com/zalando/patroni/files/474691/PostgreSQL.HA.-.not.HA.DC.pdf)

**Comment by jberkus** [comment]
Since there's been no discussion on this in a year, closing.
