### ISSUE TITLE
Running patronictl list on a leader on a Consul cluster removes the leader's lock

### ISSUE THREAD

**Issue by zenitraM** [zalando/patroni#301]
We are using Consul as DCS and noticed that running `patronictl list -c ...yml clustername` on a cluster leader using its .yml will demote the leader dirtily, giving no warning and causing a failover.

The cause seems to be this:
https://github.com/zalando/patroni/blob/master/patroni/dcs/consul.py#L157

Patronictl will create a new session with the name specified on the .yml (the leader one), look for existing leader sessions, find one with matching name but different session ID (the one from the actual Patroni daemon) and decide to remove the lock.

It seems this behavior might make sense if it runs on the daemon itself, but definitely not on patronictl

**Comment by CyberDem0n** [comment]
Will fix it tomorrow. Thank you!
