### ISSUE TITLE
Patroni changed leader for some reason

### ISSUE THREAD

**Issue by valthaide** [zalando/patroni#3055]
### What happened?

Couple things happend, that i cant explain:
1) closed patroni connection to the postgresql cluster
some kind of patroni.exceptions.PostgresConnectionException: 'connection problems'

2) Replication slot does not exist:
 ERROR: Failed to drop replication slot 'srv_pg2'
 
 Which brings another question - why its called "srv_pg2" when hostname is srv-pg2 with "-"
 

3) etcd.EtcdKeyNotFound: Key not found : /namespace/scope/leader
This problem i understand as problem with ttl in patroni.yml config. I have default as 
ttl = 30
loop_wait = 10
retry_timeout = 10

changed ttl to 40, just to be sure its bigger than loop_wait and retry_timeot. 

4) After that patroni changes leader

As far as i understand these problems then became the reason for replication slot problems. 
When srv-pg1 becomes replica it cant replicate WAL properly:
Apr 27 17:47:06 srv-pg1 patroni[13676]: 2024-04-27 17:47:06.472 MSK [16218] СООБЩЕНИЕ:  переход в режим резервного сервера
Apr 27 17:47:06 srv-pg1 patroni[13676]: 2024-04-27 17:47:06.489 MSK [16224] СООБЩЕНИЕ:  начало передачи журнала с главного сервера, с позиции 19BB/CD000000 на линии времени 80
Apr 27 17:47:06 srv-pg1 patroni[13676]: 2024-04-27 17:47:06.489 MSK [16224] ВАЖНО:  не удалось извлечь данные из потока WAL: ОШИБКА:  запрошенный сегмент WAL 00000050000019BB000000CD уже удалён
Apr 27 17:47:06 srv-pg1 patroni[13676]: 2024-04-27 17:47:06.503 MSK [16225] СООБЩЕНИЕ:  начало передачи журнала с главного сервера, с позиции 19BB/CD000000 на линии времени 80
Apr 27 17:47:06 srv-pg1 patroni[13676]: 2024-04-27 17:47:06.503 MSK [16225] ВАЖНО:  не удалось извлечь данные из потока WAL: ОШИБКА:  запрошенный сегмент WAL 00000050000019BB000000CD уже удалён

### How can we reproduce it (as minimally and precisely as possible)?

Regular cluster work process. There was no particular actions involved

### What did you expect to happen?

I didnt expect it to change leader

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.1.4
-   PostgreSQL version: 11.12
-   DCS (and its version): ETCD 3.5.0-rc.0

### Patroni configuration file

```yaml
name: srv-pg1
namespace: /namespace/
scope: scope
restapi:
 listen: 0.0.0.0:8008
 connect_address: srv-pg1:8008
 authentication:
  username: patroni
  password: patroni
etcd:
 hosts: etcd1:2379,etcd2:2379,etcd3:2379
 username: root
 password: pass
bootstrap:
 pg_hba:
 - local all all md5
 - host  all all 0.0.0.0/0 md5
 - host replication replicator samenet md5
 - host replication all 127.0.0.1/32 md5
 - host replication all ::1/128 md5
 dcs:
  ttl: 40
  loop_wait: 10
  retry_timeout: 10
  maximum_lag_on_failover: 1048576
  master_start_timeout: 300
  postgresql:
   use_pg_rewind: true
   use_slots: true
   parameters:
   wal_level: replica
   hot_standby: "on"
   wal_keep_segments: 8
   max_wal_senders: 5
   max_replication_slots: 5
   checkpoint_timeout: 30
 initdb:
 - auth-host: md5
 - auth-local: peer
 - encoding: UTF8
 - data-checksums
 - locale: ru_RU.UTF-8
 users:
  user1:
   password: pass1
   options:
   - superuser
postgresql:
 listen: 0.0.0.0:5433
 connect_address: srv-pg1:5433
 config_dir: /etc/postgresql/11/main
 bin_dir: /usr/lib/postgresql/11/bin
 data_dir: /var/lib/postgresql/11/main
 pgpass: /tmp/pgpass
 authentication:
  superuser:
   username: postgres
   password: postgres
  replication:
   username: replicator
   password: replicator
  rewind:
   username: rewind_user
   password: rewind_user
 parameters:
  unix_socket_directories: '/var/run/postgresql/'
  stats_temp_directory: '/var/run/postgresql/11-main.pg_stat_tmp'
tags:
 nofailover: false
 noloadbalance: false
 clonefrom: false
 nosync: false
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  checkpoint_timeout: 30
  hot_standby: 'on'
  max_replication_slots: 5
  max_wal_senders: 5
  parameters:
    max_standby_archive_delay: 30min
    max_standby_streaming_delay: 30min
  pg_hba:
  - local all all md5
  - host  all all 0.0.0.0/0 md5
  - host replication replicator samenet md5
  - host replication all 127.0.0.1/32 md5
  - host replication all ::1/128 md5
  use_pg_rewind: true
  use_slots: true
  wal_keep_segments: 8
  wal_level: replica
retry_timeout: 10
ttl: 40
```

### Patroni log files

```shell
1) closed patroni connection to the postgresql cluster
Apr 27 17:23:06 srv-pg1 patroni[13676]: 2024-04-27 17:23:06,774 INFO: no action. I am (srv-pg1), the leader with the lock
Apr 27 17:23:06 srv-pg1 patroni[13676]: 2024-04-27 17:23:06,775 WARNING: Loop time exceeded, rescheduling immediately.
Apr 27 17:23:09 srv-pg1 patroni[13676]: 2024-04-27 17:23:09.335 MSK [9519] postgres@postgres ОШИБКА:  выполнение оператора отменено из-за тайм-аута
Apr 27 17:23:09 srv-pg1 patroni[13676]: 2024-04-27 17:23:09.335 MSK [9519] postgres@postgres ОПЕРАТОР:  SELECT pg_catalog.pg_drop_replication_slot('srv_pg2') WHERE EXISTS (SELECT 1 FROM pg_catalog.pg_replicatio
n_slots WHERE slot_name = 'srv_pg2' AND NOT active)
Apr 27 17:23:09 srv-pg1 patroni[13676]: 2024-04-27 17:23:06,777 INFO: Lock owner: srv-pg1; I am srv-pg1
Apr 27 17:23:09 srv-pg1 patroni[13676]: 2024-04-27 17:23:09,524 INFO: closed patroni connection to the postgresql cluster
Apr 27 17:23:10 srv-pg1 patroni[13676]: 2024-04-27 17:23:09,525 ERROR: Exception when changing replication slots
Apr 27 17:23:10 srv-pg1 patroni[13676]: Traceback (most recent call last):
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql/__init__.py", line 267, in _query
Apr 27 17:23:10 srv-pg1 patroni[13676]:     cursor.execute(sql, params or None)
Apr 27 17:23:10 srv-pg1 patroni[13676]: psycopg2.errors.QueryCanceled: ОШИБКА:  выполнение оператора отменено из-за тайм-аута
Apr 27 17:23:10 srv-pg1 patroni[13676]: During handling of the above exception, another exception occurred:
Apr 27 17:23:10 srv-pg1 patroni[13676]: Traceback (most recent call last):
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql/slots.py", line 218, in sync_replication_slots
Apr 27 17:23:10 srv-pg1 patroni[13676]:     self._drop_incorrect_slots(cluster, slots)
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql/slots.py", line 118, in _drop_incorrect_slots
Apr 27 17:23:10 srv-pg1 patroni[13676]:     if not self.ignore_replication_slot(cluster, name) and not self.drop_replication_slot(name):
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql/slots.py", line 111, in drop_replication_slot
Apr 27 17:23:10 srv-pg1 patroni[13676]:     'FROM pg_catalog.pg_replication_slots WHERE slot_name = %s AND NOT active)'), name, name)
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql/slots.py", line 43, in _query
Apr 27 17:23:10 srv-pg1 patroni[13676]:     return self._postgresql.query(sql, *params, retry=False)
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql/__init__.py", line 285, in query
Apr 27 17:23:10 srv-pg1 patroni[13676]:     return self._query(sql, *args)
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql/__init__.py", line 281, in _query
Apr 27 17:23:10 srv-pg1 patroni[13676]:     raise PostgresConnectionException('connection problems')
Apr 27 17:23:10 srv-pg1 patroni[13676]: patroni.exceptions.PostgresConnectionException: 'connection problems'
Apr 27 17:23:10 srv-pg1 patroni[13676]: 2024-04-27 17:23:10,002 ERROR: get_postgresql_status
Apr 27 17:23:10 srv-pg1 patroni[13676]: Traceback (most recent call last):
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 682, in query
Apr 27 17:23:10 srv-pg1 patroni[13676]:     return [r for r in cursor]
Apr 27 17:23:10 srv-pg1 patroni[13676]: psycopg2.InterfaceError: cursor already closed
Apr 27 17:23:10 srv-pg1 patroni[13676]: During handling of the above exception, another exception occurred:
Apr 27 17:23:10 srv-pg1 patroni[13676]: Traceback (most recent call last):
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 615, in get_postgresql_status
Apr 27 17:23:10 srv-pg1 patroni[13676]:     row = self.query(stmt.format(postgresql.wal_name, postgresql.lsn_name), retry=retry)[0]
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 597, in query
Apr 27 17:23:10 srv-pg1 patroni[13676]:     return self.server.query(sql, *params)
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 686, in query
Apr 27 17:23:10 srv-pg1 patroni[13676]:     raise PostgresConnectionException('connection problems')
Apr 27 17:23:10 srv-pg1 patroni[13676]: patroni.exceptions.PostgresConnectionException: 'connection problems'
Apr 27 17:23:10 srv-pg1 patroni[13676]: 2024-04-27 17:23:09,845 ERROR: get_postgresql_status
Apr 27 17:23:10 srv-pg1 patroni[13676]: Traceback (most recent call last):
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 615, in get_postgresql_status
Apr 27 17:23:10 srv-pg1 patroni[13676]:     row = self.query(stmt.format(postgresql.wal_name, postgresql.lsn_name), retry=retry)[0]
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 597, in query
Apr 27 17:23:10 srv-pg1 patroni[13676]:     return self.server.query(sql, *params)
Apr 27 17:23:10 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/api.py", line 686, in query
Apr 27 17:23:10 srv-pg1 patroni[13676]:     raise PostgresConnectionException('connection problems')
Apr 27 17:23:10 srv-pg1 patroni[13676]: patroni.exceptions.PostgresConnectionException: 'connection problems'
Apr 27 17:23:10 srv-pg1 patroni[13676]: 2024-04-27 17:23:10,789 INFO: no action. I am (srv-pg1), the leader with the lock
Apr 27 17:23:20 srv-pg1 patroni[13676]: 2024-04-27 17:23:20,433 INFO: Lock owner: srv-pg1; I am srv-pg1
Apr 27 17:23:20 srv-pg1 patroni[13676]: 2024-04-27 17:23:20,433 INFO: establishing a new patroni connection to the postgres cluster
Apr 27 17:23:20 srv-pg1 patroni[13676]: 2024-04-27 17:23:20,452 ERROR: Failed to drop replication slot 'srv_pg2'
Apr 27 17:23:20 srv-pg1 patroni[13676]: 2024-04-27 17:23:20,455 INFO: no action. I am (srv-pg1), the leader with the lock


2) Replication slot does not exist:
 ERROR: Failed to drop replication slot 'srv_pg2'

3) etcd.EtcdKeyNotFound: Key not found : /namespace/scope/leader
Apr 27 17:46:41 srv-pg1 patroni[13676]: etcd.EtcdKeyNotFound: Key not found : /namespace/scope/leader
Apr 27 17:46:41 srv-pg1 patroni[13676]: 2024-04-27 17:46:41,228 ERROR: failed to update leader lock
Apr 27 17:46:41 srv-pg1 patroni[13676]: 2024-04-27 17:46:41,229 INFO: Demoting self (immediate-nolock)
Apr 27 17:46:41 srv-pg1 patroni[13676]: 2024-04-27 17:46:41.820 MSK [9443] СООБЩЕНИЕ:  получен запрос на немедленное выключение

4) After that patroni changes leader
pr 27 17:46:43 srv-pg1 patroni[13676]: 2024-04-27 17:46:43.253 MSK [9443] СООБЩЕНИЕ:  система БД выключена
Apr 27 17:46:43 srv-pg1 patroni[13676]: 2024-04-27 17:46:43,286 INFO: demoted self because failed to update leader lock in DCS
Apr 27 17:46:43 srv-pg1 patroni[13676]: 2024-04-27 17:46:43,288 WARNING: Loop time exceeded, rescheduling immediately.
Apr 27 17:46:43 srv-pg1 patroni[13676]: 2024-04-27 17:46:43,322 INFO: closed patroni connection to the postgresql cluster
Apr 27 17:46:43 srv-pg1 patroni[13676]: 2024-04-27 17:46:43,323 INFO: Lock owner: None; I am srv-pg1
Apr 27 17:46:43 srv-pg1 patroni[13676]: 2024-04-27 17:46:43,323 INFO: not healthy enough for leader race
Apr 27 17:46:43 srv-pg1 patroni[13676]: 2024-04-27 17:46:43,328 INFO: starting after demotion in progress
```

### PostgreSQL log files

```shell
No errors or warnings
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
> closed patroni connection to the postgresql cluster
some kind of patroni.exceptions.PostgresConnectionException: 'connection problems'

Postgres is terribly slow and can't respond in time to monitoring queries.

>     ERROR: Failed to drop replication slot 'srv_pg2'
Which brings another question - why its called "srv_pg2" when hostname is srv-pg1 with "-"

Because: `HINT:  Replication slot names may only contain lower case letters, numbers, and the underscore character.`


> etcd.EtcdKeyNotFound: Key not found : /namespace/scope/leader

Leader key expired (or was removed).

> When srv-pg1 becomes replica it cant replicate WAL properly:

Well, the new primary doesn't have this WAL segment. You need to have proper PITR to solve it. Or at least use the latest Patroni and setup permanent physical replication slots for all members of the cluster like it is described in the documentation: https://patroni.readthedocs.io/en/latest/dynamic_configuration.html.

> patronictl show-config

It is wrongly formatted. Postgres GUCs are supposed to be under `postgresql.parameters`, but many of them are just under `postgresql`.

> Patroni log files

> Apr 27 17:46:41 srv-pg1 patroni[13676]: etcd.EtcdKeyNotFound: Key not found : /namespace/scope/leader
Apr 27 17:46:41 srv-pg1 patroni[13676]: 2024-04-27 17:46:41,228 ERROR: failed to update leader lock

What happened before? Were heartbeat logs regular or there was nothing for longer than `loop_wait` or `ttl`?

**Comment by valthaide** [comment]
> Postgres is terribly slow and can't respond in time to monitoring queries.
As i understand patroni has 2s statement_timeout, right?
I should look into disk perfomance?

> Because: HINT:  Replication slot names may only contain lower case letters, numbers, and the underscore character.
Thanks, i was thinking about that, but thought patroni will log according to hostnames.

> Leader key expired (or was removed).
But why? Am i right to increase TTL?

> Well, the new primary doesn't have this WAL segment. You need to have proper PITR to solve it. Or at least use the latest Patroni and setup permanent physical replication slots for all members of the cluster like it is described in the documentation: https://patroni.readthedocs.io/en/latest/dynamic_configuration.html.
I need to update from 2.1.4? I am now limited by my OS version(Debian 9)

> It is wrongly formatted. Postgres GUCs are supposed to be under postgresql.parameters, but many of them are just under postgresql.
Thats how patroni placed them after cluster was craeted. I only added **max_standby_archive_delay** and **max_standby_streaming_delay**
`Apr 27 12:50:55 srv-pg1 patroni[13676]: 2024-04-27 12:50:54,991 INFO: Lock owner: srv-pg1; I am srv-pg1
Apr 27 12:50:55 srv-pg1 patroni[13676]: 2024-04-27 12:50:55,070 ERROR:
Apr 27 12:50:55 srv-pg1 patroni[13676]: Traceback (most recent call last):
Apr 27 12:50:55 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 566, in wrapper
Apr 27 12:50:55 srv-pg1 patroni[13676]:     retval = func(self, *args, **kwargs) is not None
Apr 27 12:50:55 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 696, in _update_leader
Apr 27 12:50:55 srv-pg1 patroni[13676]:     return self.retry(self._client.write, self.leader_path, self._name, prevValue=self._name, ttl=self._ttl)
Apr 27 12:50:55 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 447, in retry
Apr 27 12:50:55 srv-pg1 patroni[13676]:     return retry(*args, **kwargs)
Apr 27 12:50:55 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/utils.py", line 334, in __call__
Apr 27 12:50:55 srv-pg1 patroni[13676]:     return func(*args, **kwargs)
Apr 27 12:50:55 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/etcd/client.py", line 500, in write
Apr 27 12:50:55 srv-pg1 patroni[13676]:     response = self.api_execute(path, method, params=params)
Apr 27 12:50:55 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 257, in api_execute
Apr 27 12:50:55 srv-pg1 patroni[13676]:     return self._handle_server_response(response)
Apr 27 12:50:55 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/etcd/client.py", line 987, in _handle_server_response
Apr 27 12:50:55 srv-pg1 patroni[13676]:     etcd.EtcdError.handle(r)
Apr 27 12:50:55 srv-pg1 patroni[13676]:   File "/usr/local/lib/python3.5/dist-packages/etcd/__init__.py", line 306, in handle
Apr 27 12:50:55 srv-pg1 patroni[13676]:     raise exc(msg, payload)
Apr 27 12:50:55 srv-pg1 patroni[13676]: etcd.EtcdKeyNotFound: Key not found : /sakura-prod/sakura-prod/leader
Apr 27 12:50:55 srv-pg1 patroni[13676]: 2024-04-27 12:50:55,095 ERROR: failed to update leader lock
Apr 27 12:50:55 srv-pg1 patroni[13676]: 2024-04-27 12:50:55,095 INFO: Demoting self (immediate-nolock)
`

**Comment by CyberDem0n** [comment]
> As i understand patroni has 2s statement_timeout, right?

Yes.

I should look into disk perfomance?

Its not necessarily related to disk performance. With the same chances it could be memory pressure.

> But why? Am i right to increase TTL?

That's why I asked whether heartbeat logs were regular.

> Thats how patroni placed them after cluster was craeted. I only added max_standby_archive_delay and max_standby_streaming_delay

Meh. Patroni writes the entire `bootstrap.dcs` as it is to the /config key in DCS. It is still your fault.

> Apr 27 12:50:55 srv-pg1 patroni[13676]: 

It doesn't answer my question about regular heartbeat logs.

**Comment by valthaide** [comment]
> Meh. Patroni writes the entire bootstrap.dcs as it is to the /config key in DCS. It is still your fault.
Ok, got it.. wiil look into it

> It doesn't answer my question about regular heartbeat logs.
What kind of heartbit are you interested in?
Like that?
`Apr 27 12:49:01 srv-pg1 patroni[13676]: 2024-04-27 12:49:01,001 INFO: no action. I am (srv-pg1), the leader with the lock
Apr 27 12:49:11 srv-pg1 patroni[13676]: 2024-04-27 12:49:11,000 INFO: no action. I am (srv-pg1), the leader with the lock
Apr 27 12:49:20 srv-pg1 patroni[13676]: 2024-04-27 12:49:20,999 INFO: no action. I am (srv-pg1), the leader with the lock
Apr 27 12:49:30 srv-pg1 patroni[13676]: 2024-04-27 12:49:30,998 INFO: no action. I am (srv-pg1), the leader with the lock
Apr 27 12:49:41 srv-pg1 patroni[13676]: 2024-04-27 12:49:40,999 INFO: no action. I am (srv-pg1), the leader with the lock
Apr 27 12:49:51 srv-pg1 patroni[13676]: 2024-04-27 12:49:51,000 INFO: no action. I am (srv-pg1), the leader with the lock
Apr 27 12:50:01 srv-pg1 patroni[13676]: 2024-04-27 12:50:01,001 INFO: no action. I am (srv-pg1), the leader with the lock
Apr 27 12:50:11 srv-pg1 patroni[13676]: 2024-04-27 12:50:10,999 INFO: no action. I am (srv-pg1), the leader with the lock
Apr 27 12:50:21 srv-pg1 patroni[13676]: 2024-04-27 12:50:20,999 INFO: no action. I am (srv-pg1), the leader with the lock
Apr 27 12:50:55 srv-pg1 patroni[13676]: etcd.EtcdKeyNotFound: Key not found : /namespace/scope/leader
Apr 27 12:50:55 srv-pg1 patroni[13676]: 2024-04-27 12:50:55,095 ERROR: failed to update leader lock
Apr 27 12:50:55 srv-pg1 patroni[13676]: 2024-04-27 12:50:55,095 INFO: Demoting self (immediate-nolock)
Apr 27 12:50:56 srv-pg1 patroni[13676]: 2024-04-27 12:50:56.352 MSK [6259] СООБЩЕНИЕ:  система БД выключена
Apr 27 12:50:56 srv-pg1 patroni[13676]: 2024-04-27 12:50:56,424 INFO: demoted self because failed to update leader lock in DCS
Apr 27 12:50:56 srv-pg1 patroni[13676]: 2024-04-27 12:50:56,435 WARNING: Loop time exceeded, rescheduling immediately.
Apr 27 12:50:56 srv-pg1 patroni[13676]: 2024-04-27 12:50:56,446 INFO: Lock owner: None; I am srv-pg1
Apr 27 12:50:56 srv-pg1 patroni[13676]: 2024-04-27 12:50:56,446 INFO: not healthy enough for leader race
Apr 27 12:50:56 srv-pg1 patroni[13676]: 2024-04-27 12:50:56,450 INFO: starting after demotion in progress
Apr 27 12:50:56 srv-pg1 patroni[13676]: 2024-04-27 12:50:56,497 INFO: closed patroni connection to the postgresql cluster`

**Comment by CyberDem0n** [comment]
> Like that?

Yes.

> Apr 27 12:50:21 srv-pg1 patroni[13676]: 2024-04-27 **12:50:20**,999 INFO: no action. I am (srv-pg1), the leader with the lock 
Apr 27 12:50:55 srv-pg1 patroni[13676]: etcd.EtcdKeyNotFound: Key not found : /namespace/scope/leader 
Apr 27 12:50:55 srv-pg1 patroni[13676]: 2024-04-27 **12:50:55**,095 ERROR: failed to update leader lock 

You see, regular heartbeats are happening every ~10s, and than suddenly it takes 35s. Enabling debug logs might help to get more insights, but I don't think that they will allow to find a root cause.

I've seen similar issues when memory was under a huge pressure and Patroni was paged out of RAM. In my case memory pressure happened because of slow disk and a lot of dirty pages. In your case it could be something else.

**Comment by valthaide** [comment]
> You see, regular heartbeats are happening every ~10s, and than suddenly it takes 35s. Enabling debug logs might help to get more insights, but I don't think that they will allow to find a root cause.
> 
> I've seen similar issues when memory was under a huge pressure and Patroni was paged out of RAM. In my case memory pressure happened because of slow disk and a lot of dirty pages. In your case it could be something else.

thanks. i will look into that either!

So. to wrap everything up:
1. I should change patroni.yml and dynamic configuration accroding to documentation
2. i should look into overall cpu/ram/disk load. Mybe patroni lagging due to that.
3. I should setup physical replication slots. 
right?

**Comment by CyberDem0n** [comment]
> I should setup physical replication slots

 **permanent** physical replication slots, but that would require upgrading Patroni to the latest version, which is not possible with python 3.5

**Comment by CyberDem0n** [comment]
Physical replication slot is a concept of Postgres.
The concept of permanent slots is from Patroni, because it will create them on all nodes for all remaining nodes and move forward LSN to match respective location on the primary (or cascading replicas).

> For example, if i create this dynamic config:
```
slots: 
  srv-pg1:
    type: physical
  srv-pg2:
    type: physical
  srv-pg3:
    type: physical
```

You have to use `'_'` instead of `'-'`

**Comment by valthaide** [comment]
> You have to use '_' instead of '-'
Will it correlate it then to hostname somehow?

**Comment by CyberDem0n** [comment]
> Will it correlate it then to hostname somehow?

Exactly.

> It wont work completely on 2.1.4 patroni or it just has some bugs and you advise to use latest version?

On 2.1.4 it will not create slots on standby nodes. That is, usefulness is very limited.

All further questions please post on Slack: https://patroni.readthedocs.io/en/latest/contributing_guidelines.html#chatting
