### ISSUE TITLE
patroni-consul RPM requires consul package

### ISSUE THREAD

**Issue by elfcheg** [zalando/patroni#3065]
### What happened?

Hey all!

I'm trying to install patroni on my Oracle Linux 8 from official PostgreSQL repository and I found that patroni-consul RPM has a requirement for consul RPM. Which is strange: I don't need to set up a consul node on this particular node, I already have a working consul cluster.

### How can we reproduce it (as minimally and precisely as possible)?

sudo dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm

sudo dnf install patroni-consul

### What did you expect to happen?

First clean installation of patroni and patroni-consul.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.3.0
-   PostgreSQL version: 15
-   DCS (and its version): consul 

### Patroni configuration file

```yaml
n/a
```

### patronictl show-config

```yaml
n/a
```

### Patroni log files

```shell
n/a
```

### PostgreSQL log files

```shell
n/a
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

Here is what I try to do exactly:
```
[root@local-pgdb01 ~]# yum install patroni-consul
This system is receiving updates from Spacewalk server.
Last metadata expiration check: 0:00:27 ago on Wed 15 May 2024 01:43:49 PM MSK.
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides consul needed by patroni-consul-3.3.0-1PGDG.rhel8.noarch from pgdg-common
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by CyberDem0n** [comment]
> I don't need to set up a consul node on this particular node, I already have a working consul cluster.

We are only developing Patroni source code here, not OS packages. PGDG rpms are maintained separately, by @devrimgunduz.

But, maybe Devrim is right by creating this dependency. All applications that run on specific node have to connect to the consul cluster only via the local agent. And for that you need consul package.

**Comment by elfcheg** [comment]
@CyberDem0n Thank you! I'm sorry for bringing this up here, I was unable to find Devrim's email.

I see, seems that I should dig more into consul architecture then!
