### ISSUE TITLE
Unable to connect to external etcdv3 cluster with client TLS authentication (with CommonName in cert)

### ISSUE THREAD

**Issue by ILikePhysics** [zalando/patroni#3071]
### What happened?

I am setting up a pg cluster consisting of 1 master and 2 replicas. I am trying to connect patroni to my existing external etcd v3 cluster which has client TLS auth enabled.

Unfortunately, the only I was able to have patroni connected to it was by using username/password config, with use_proxies enabled and client TLS auth turned off in the etcd cluster. I know that if I supply both client TLS certs and username/password in patroni, etcd will prioritize username/password authentication.

The problem is that regardless of what I do, I get the following error that 
`ERROR: Failed to get list of machines from https://etcd-1.xx:2379/v3: <Unknown error: 'CommonName of client sending a request against gateway will be ignored and not used as expected', code: 2>`.

My etcd cluster is not using any gateway or proxy. Am I misunderstanding something about etcd?

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### What did you expect to happen?

Have patroni authenticate using its client TLS certs (using the CommonName as its username for etcd) or at least, be able to authenticate with username/password while still having client TLS auth enabled in etcd (because the docs says its possible).

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.3.0
-   PostgreSQL version:  16
-   DCS (and its version):  external etcd 3.5 (3 nodes cluster)

### Patroni configuration file

```yaml
etcd3:
  hosts: etcd-1.xx:2379,etcd-2.xx:2379,etcd-3.xx:2379
  cert: /etc/postgresql/certs/tls.crt
  key: /etc/postgresql/certs/tls.key
    #use_proxies: true
  protocol: https
    #username: pg-1-test
    #password: xxxxx
```

### patronictl show-config

```yaml
Error: Can not find suitable configuration of distributed configuration store
Available implementations: consul, etcd, etcd3, kubernetes, raft
```

### Patroni log files

```shell
With the patroni config above for etcd3, I get:

2024-05-31 02:24:34,476 DEBUG: New etcd client created for https://127.0.0.1:4001
2024-05-31 02:24:34,609 ERROR: Failed to get list of machines from https://etcd-3.xx:2379/v3: <Unknown error: 'CommonName of client sending a request against gateway will be ignored and not used as expected', code: 2>
2024-05-31 02:24:34,709 ERROR: Failed to get list of machines from https://etcd-1.xx:2379/v3: <Unknown error: 'CommonName of client sending a request against gateway will be ignored and not used as expected', code: 2>
2024-05-31 02:24:34,781 ERROR: Failed to get list of machines from https://etcd-2.xx:2379/v3: <Unknown error: 'CommonName of client sending a request against gateway will be ignored and not used as expected', code: 2>
2024-05-31 02:24:34,782 INFO: waiting on etcd
```

### PostgreSQL log files

```shell
No started..
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

I have go through the other similar issues in this git repo, everything they were ending up with a workaround not suitable for me... 
I looked at #2036 and #2558

**Comment by CyberDem0n** [comment]
> My etcd cluster is not using any gateway or proxy. Am I misunderstanding something about etcd?

You do. For languages that don't have good gRPC support Etcd runs gRPC-gateway (proxy), that does JSON<->gRPC translation on the fly. Python is one of such languages and therefore Patroni is relying on gRPC-gateway.

> or at least, be able to authenticate with username/password while still having client TLS auth enabled in etcd (because the docs says its possible)

Well, than at least you should create client certificates without `CommonName`, so Etcd doesn't reject them.
