### ISSUE TITLE
Cannot configure SSL for replication

### ISSUE THREAD

**Issue by caseyandgina** [zalando/patroni#3077]
### What happened?

I need to set some ssl parameters - namely `sslmode`, `sslcert`, `sslkey`, and `sslrootcert` within `primary_conninfo`, so that I can use client certificate authentication with `verify-full` for PostgreSQL's replication connections.  It doesn't appear that there's any way to do this.  I also don't see any way to set Patroni to utilize SSL for it's restapi and heartbeat connections to the database.

### How can we reproduce it (as minimally and precisely as possible)?

Try to enable SSL with anything other than the default `sslmode=prefer` for primary_conninfo, or use SSL at all for Patroni's local db connections.

**Comment by BabaTataKaka** [comment]
I'm facing the same issue. There is the Postgresql->authentication->replication settings the the patroni.yml. 

Exemple:

Postgresql:
   authentication:
       replication:
         sslmode: require
         sslcert: /etc/postgresql/certs/tls.crt
         sslkey: /etc/postgresql/certs/tls.key
         sslrootcert: /etc/ssl/certs/ca-cert.crt

However, I'm not sure of the utility of the settings. Is it for patroni to authenticate to the replicas or its to setup the replicas authenticate method withing the cluster(as requested by the OP)?

Thanks

**Comment by BabaTataKaka** [comment]
> I missed those settings when looking in the docs (I was searching for `primary_conninfo`, etc.). I've since added the settings to `postgresql.authentication.replication`, and that is working for replication connections. However, I added the same settings to `postgresql.authentication.superuser`, and that does not seem to work for the restapi and heartbeat connections:
> 
> ```
> postgres=# select a.application_name, s.* from pg_stat_activity a left join pg_stat_ssl s using (pid) where a.application_name ~ 'Patroni';
>  application_name  |   pid   | ssl | version | cipher | bits | client_dn | client_serial | issuer_dn 
> -------------------+---------+-----+---------+--------+------+-----------+---------------+-----------
>  Patroni heartbeat | 3321779 | f   |         |        |      |           |               | 
>  Patroni restapi   | 3321784 | f   |         |        |      |           |               | 
> ```

I'm still having issue even with the authentication settings in the patroni.yml. What are your pg_hba.conf setting? Did you change the primary_conninfo setting the postgresql.conf on the replicas? I would assume this should be done by patroni.
