### ISSUE TITLE
Reinit master with empty directory after data corruption

### ISSUE THREAD

**Issue by gentoosys** [zalando/patroni#3084]
### What happened?

My SDD on master died and I got multiple checksum errors. Replicas also died on reinit, going into loop.
I have pg_dumps, so I moved /data/patroni to new HDD (with multple IO errors), started master, dropped database, pg_restored, and started replicas. But they got checksum errors and went to init loop.
so I decided to remove all /data/patroni and init master on empty datadir, and restore backup.
But starting master with empty dir waits leader to start, it thinks it is replica. 

How to start master with empty dir? Or just remove base dir, which is corrupted? Please help

### How can we reproduce it (as minimally and precisely as possible)?

-

### What did you expect to happen?

start master

### Patroni/PostgreSQL/DCS version

-   Patroni version: 
-   PostgreSQL version: 
-   DCS (and its version): 

### Patroni configuration file

```yaml
-
```

### patronictl show-config

```yaml
-
```

### Patroni log files

```shell
-
```

### PostgreSQL log files

```shell
-
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
Please use Slack for questions (and you already got the answer there).
