### ISSUE TITLE
Target non-master server for restore operations

### ISSUE THREAD

**Issue by jamessewell** [zalando/patroni#309]
Hello,

Is it possible to target an up to date standby server for pg_basebackup or pg_rewind operations?

This would become useful in a situation where something like WAL-E wasn't available to retrieve a base-backup and you were in production and didn't want to impact the master unless absolutely needed.

Cheers,
James

**Comment by jamessewell** [comment]
As an addition to this, I suppose what I really mean is:

- Target an up to date standby for restore operations if one exists, else use the master

**Comment by ants** [comment]
I think the (for some reason) undocumented clonefrom tag does what you want. Looking at the code, it randomly picks one of non-leader servers with clonefrom set, if none exist it goes with the leader.

**Comment by jamessewell** [comment]
So it does.

I had a quick look earlier, but thought it was intended for a list of servers to clone from - this is much better!

**Comment by CyberDem0n** [comment]
Yeah, it really should be documented...
So far the only mention of the tags was in the https://github.com/zalando/patroni/issues/48

**Comment by jamessewell** [comment]
Hmmm, the idea is perfect - but this doesn't seem to work.

My three node cluster bootstraps fine with all nodes set to _clonefrom:  false_, but when I set them all to _clonefrom: true_ I get the following on the two non master nodes:

```
2016-09-20 17:36:36,281 ERROR: Trying again in 5 seconds
pg_basebackup: could not connect to server: could not connect to server: Connection refused
        Is the server running on host "192.168.2.247" and accepting
        TCP/IP connections on port 5432?
2016-09-20 17:36:41,295 ERROR: failed to bootstrap from replica 'postgresql-192.168.2.247'
2016-09-20 17:36:41,296 INFO: Removing data directory: /db/9.5/data/pg_data
2016-09-20 17:36:46,275 INFO: trying to bootstrap from replica 'postgresql-192.168.2.245'
pg_basebackup: could not connect to server: could not connect to server: Connection refused
        Is the server running on host "192.168.2.245" and accepting
        TCP/IP connections on port 5432?

```

**.245** is the current node**, .246** is the master and **.246** is another replica - so it looks like it's trying to clone from everyone (including itself) then not trying the master.

Thanks for the help,
James

**Comment by CyberDem0n** [comment]
It is clearly a bug, node itself must be excluded (as well as any other nodes not in the "running" state)

**Comment by jamessewell** [comment]
Sweet, that fix works for me 👍
