### ISSUE TITLE
Updating nodes' configuration

### ISSUE THREAD

**Issue by maximegaillard** [zalando/patroni#312]
I'm looking to update and/or restart/reload postgres process on my DB nodes.

The main reason to do so, is to update SSL certificates when they expire. I saw there's a restart key on the DCS, but not certain how to use it:
- do I have to update manually (ie with python-etcd) some keys?
- do I have to use the REST API?

If you can put me on the track for the good use-case, it will be wonderful.

**Comment by CyberDem0n** [comment]
You can restart nodes either:
 - via REST API 'POST /restart' 
 - or by using `patronictl restart`

Basically patronictl restart does REST API requests for you.

**Comment by maximegaillard** [comment]
Thanks 👍
