### ISSUE TITLE
Incoming traffic question

### ISSUE THREAD

**Issue by jamessewell** [zalando/patroni#315]
Hi again,

This isn't an issue, just a question - I couldn't see an IRC or message list, feel free to point me at something else if there is a better place to put stuff like this.

What do people generally do for incoming traffic?

I see some HAProxy config in the repo, is clustered HAProxy the way to go?

Is there every any intention of supporting a floating VIP based solution in Patroni? Sometimes it can be a bit crude (if Patroni dies and the VIP was up it's essentially game over) - but it doesn't require any additional (clustered) components to work, which is a bonus in some cases.

Thoughts?

**Comment by CyberDem0n** [comment]
On AWS we are using ELB, which is effectively acts like clustered HAProxy.

In the old fashioned data-center we are using floating IP. Patroni has callback mechanism, which also seems to be not documented properly.
In the postgresql section of config file it is possible to configure callbacks which would be triggered on some actions:
 - on_start # when the postgres is started
 - on_stop # when the postgres was stopped
 - on_restart # when the postgres was restarted
 - on_reload # when pg_ctl reload was executed
 - on_role_change # when postgres was either promoted to master or demoted to read-only

In the all cases callback is called with 3 arguments: <cb_name> <role> <scope>
 - cb_name - possible values: on_start, on_stop, etc..
 - role - current role of the node (master, replica, demoted, etc...)
 - scope - name of the Patroni cluster

**Comment by jamessewell** [comment]
Thanks!

I don't suppose the VIP scripts are going to be open-sourced as well?

If not no worries, I can do my own.
