### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by jamessewell** [zalando/patroni#318]
Hi,

We use [Prometheus](prometheus.io) as our monitoring platform, so I'd like to be able to pull Patroni metrics.

The best way of doing this is to natively instrument the Patroni code to provide metrics via HTTP (/metrics).

Some other notable projects have already done this (Kubernetes, etcd), it doesn't look super difficult.

The question is - if I worked towards this does it sound like something which would be allowed back into the core Patroni code?

**Comment by CyberDem0n** [comment]
What kind of metrics do you want to expose?

/patroni endpoint already gives you something

**Comment by feikesteenbergen** [comment]
I'd be ok with it, we also need monitoring information and we currently use the ``/patroni`` endpoint to gather this.
It could probably use a feature toggle

**Comment by DeathBorn** [comment]
@jamessewell we integrate consul, prometheus, node-exporter and postgres-exporter with added custom queries which provide information straight from postgres itself (some inspiration from zalando/spilo but with prometheus). Endpoint /master lets us implement service discovery with http codes 503 or 200. Although patroni could output prometheus friendly info, I have doubts if monitoring role should be given to patroni.

**Comment by mamercad** [comment]
> @jamessewell we integrate consul, prometheus, node-exporter and postgres-exporter with added custom queries which provide information straight from postgres itself (some inspiration from zalando/spilo but with prometheus). Endpoint /master lets us implement service discovery with http codes 503 or 200. Although patroni could output prometheus friendly info, I have doubts if monitoring role should be given to patroni.

Emitting metrics isn't the same as "doing monitoring".
