### ISSUE TITLE
Postgres timeline needlessly advanced during startup of primary node

### ISSUE THREAD

**Issue by trifthen** [zalando/patroni#326]
It appears Patroni considers every Postgres shutdown a fatal crash. 

In the event an existing cluster is started following a controlled shutdown, Patroni always creates a `recovery.conf` file, even when no recovery is necessary. This advances the internal instance timeline, as Postgres assumes an uncontrolled shutdown and executes the full recovery stack.

To prevent this, Patroni should:

1. Obtain the primary lock, if possible.
2. Lock obtained, attempt to start Postgres without recovery mechanisms.
3. If Postgres starts normally, no further action is taken.
4. If Postgres will not start or reports an error necessitating recovery, create a `recovery.conf` file and follow the current protocol.

**Comment by trifthen** [comment]
I just realized this won't work in a heterogeneous cluster environment. Provided one or more replicas was promoted at a previous time and produced WAL traffic, and were later shut down, a lagging node could start and start a split timeline. Any initial startup **must** begin in recovery in an attempt to consume any distributed WAL files potentially produced by other intermediate primaries.

However, I will note that Patroni, as distributed, does not account for WAL archive broadcast necessary to handle this scenario. Documentation should strongly recommend Postgres 9.5 and above to make use of the 'always' setting for `archive_mode` to automate *some* of this process. An additional mechanism is necessary to ensure all unique WAL files reach all nodes.

Perhaps this should be retitled: "Patroni can not survive mixed-node WAL archive replay scenarios."

**Comment by ants** [comment]
Incrementing the timeline is an important safety feature. Also it does not cause any problems - you're not going to run out of timeline ID's.

A small detail, when given a recovery.conf on a properly shut down instance PostgreSQL does not assume a crash, it knows from the control file that the server was properly shut down. It just starts recovery mode to start replicating. The timeline gets incremented on promotion, as it should.

I' not sure what failure mode you are proposing here. Having both masters and standbys archive WAL makes no sense. WAL archive when being used a source for recovery is intended to be a single resource shared by all nodes in the cluster. This archive will contain all the timeline splits and WAL generated by any succession of masters in the cluster. If the succession of masters goes offline and a lagging standby on an old timeline determines it is allowed to promote (maximum_lag_on_failover is not exceeded), it will reuse the timeline identifiers. The timeline history file and following WAL files will overwrite the existing ones in the archive. If the old servers now come back they will notice  different timeline split from what they have locally and will refuse to follow the master. Under most, but not all circumstances Patroni is smart enough to automatically rewind them.

**Comment by trifthen** [comment]
The issue here is that WAL archival done only by the current primary does not send the WAL files to any existing replicas. Without a  mechanism of sending archived WAL files to all replicas, there is no consistent timeline. The only way to emulate that is to use a shared filesystem like GlusterFS or NFS. Alternatively, every replica can write archived WAL files locally for potential recovery purposes. The only time that fails is if a single node is stopped for a long period of time, and it's the first to win the race in a system-wide outage->recovery scenario.

So would I be right in assuming you suggest a shared filesystem for WAL archival to solve this problem?

**Comment by ants** [comment]
Right, if you want to have a WAL archive use a shared filesystem, NFS is a simple widely supported option. Or if you are running in a cloud or have a private cloud, you can use WAL-E, to store the archive in your favorite object storage system (e.g. Amazon S3, OpenStack Swift).

**Comment by trifthen** [comment]
Ok. I'll close this. I suppose I wanted to confirm my suspicions after noting the need for recovery mode in a mixed server environment. Sorry for the distraction! :)
