### ISSUE TITLE
Example Kubernetes Manifests?

### ISSUE THREAD

**Issue by fortytw2** [zalando/patroni#328]
Would be super awesome for there to be some example k8s manifests laying around - we're currently in the process of migrating into GKE from compute engine and would _love_ to be able to quickly test out patroni with a copy of our production db loaded into it :)

**Comment by alexeyklyukin** [comment]
It requires some additional dependencies outside of Patroni. We have one in the Spilo project here: https://github.com/zalando/spilo/blob/master/postgres-appliance/spilok8s.yaml and  a helm chart here: https://github.com/kubernetes/charts/tree/master/incubator/patroni

**Comment by fortytw2** [comment]
Fantastic! Thanks \o/
