### ISSUE TITLE
Need Changelog

### ISSUE THREAD

**Issue by sm97** [zalando/patroni#330]
It would be nice to have Changelog to track changes and improvements incorporated to Patroni.

**Comment by CyberDem0n** [comment]
Hi, actually https://github.com/zalando/patroni/releases has more or less detailed description of all features and bugfixes.

**Comment by sm97** [comment]
Wow, I didn't see that! May be you just put dummy Changelog with link https://github.com/zalando/patroni/releases to in it?

**Comment by LappleApple** [comment]
Good idea @sm97; just added https://github.com/zalando/patroni/pull/338

**Comment by CyberDem0n** [comment]
fixed with https://github.com/zalando/patroni/pull/338
