### ISSUE TITLE
Annoying 'error: [Errno 32] Broken pipe' errors in patroni logs 

### ISSUE THREAD

**Issue by sm97** [zalando/patroni#331]
I've got a lot of errors from Patroni when using with HAProxy:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

Solution copied from:
Bug 923611 - Haproxy causing broken pipe errors in logs for python-2.7 & python-3.3 
https://bugzilla.redhat.com/show_bug.cgi?id=923611

Original diff: https://github.com/openshift/origin-server/pull/1793/files?diff=unified#diff-779cddf5d4f1921ec8647d9b3b77d460

Errors 'error: [Errno 32] Broken pipe' wanished after adding this option to haproxy.cfg.

**Comment by alexeyklyukin** [comment]
Can you get the problem reproduced and post your steps? 

In the haproxy config you've patched the OPTIONS method is used instead of GET and POST.
In Patroni (api.py) we specifically send only the response code and not the full body upon detecting an OPTIONS request. So I find it weird that we still get a broken pipe. Perhaps you did GET or HEAD instead of an OPTIONS in your haproxy.cfg?

**Comment by CyberDem0n** [comment]
Yeah, I kind of have the same question as @alexeyklyukin, do you use OPTION method for a health-check or something else?

If you are using OPTION, can you please do the following test:
change the line https://github.com/zalando/patroni/blob/master/patroni/api.py#L101
```diff
-self.wfile.write('{0} {1} {2}\r\n'.format(self.protocol_version, status_code, message).encode('utf-8'))
+self.wfile.write('{0} {1} {2}'.format(self.protocol_version, status_code, message).encode('utf-8'))
```
And check if Patroni is still spaming in the log.

BTW, which HAProxy version do you use?

**Comment by sm97** [comment]
Configuration was slightly obfuscated:
```
[kpushkin@cm-stage ~]$ rpm -q haproxy
haproxy-1.5.4-3.el6.x86_64

[kpushkin@cm-stage ~]$ cat /etc/haproxy/haproxy.cfg 
global
    maxconn 100

defaults
    log     global
    mode    tcp
    retries 2
    timeout client 30m
    timeout connect 4s
    timeout server 30m
    timeout check 5s

frontend ft_postgresql
    bind *:5432
    default_backend bk_db

backend bk_db
    option httpchk GET / HTTP/1.0\r\nAuthorization:\ Basic\ some-base64-encoded-credentials
    http-check expect rstring .*
    server postgresql_10.0.0.1_5432 10.0.0.1:5432 maxconn 100 check port 8008
    server postgresql_10.0.0.2_5432 10.0.0.2:5432 maxconn 100 check port 8008
```

**Comment by CyberDem0n** [comment]
```
option httpchk GET / HTTP/1.0\r\nAuthorization:\ Basic\ some-base64-encoded-credentials
```
That explains your problems.

Just replace it with:
```
option httpchk OPTIONS /
```
and exceptions will go away.

Why do you need basic-auth there? Patroni checks auth only for POST-PUT-DELETE requests.

**Comment by sm97** [comment]
I can't remember reason. But your solution works Ok. Thank you.
