### ISSUE TITLE
Issue when running on kubernetes

### ISSUE THREAD

**Issue by jchauncey** [zalando/patroni#337]
So Im trying to install patroni using the kubernetes/helm chart. And I am seeing the following error:

```
2016-10-09 03:41:52,901 ERROR: failed to bootstrap from leader 'test_patroni_1'
2016-10-09 03:41:52,902 INFO: Removing data directory: /home/postgres/pgdata/pgroot/data
kg nod2016-10-09 03:41:57,838 INFO: trying to bootstrap from leader 'test_patroni_1'
pg_basebackup: could not connect to server: could not connect to server: Connection refused
        Is the server running on host "10.0.0.116" and accepting
        TCP/IP connections on port 5432?
2016-10-09 03:41:57,873 ERROR: Trying again in 5 seconds
```

So `10.0.0.116` is the ip of the host not the ip of the service or pod which is what it should be.

**Comment by LappleApple** [comment]
@linki @mikkeloscar Hey guys, can you take a look at @jchauncey's issue? cc @alexeyklyukin @CyberDem0n

**Comment by alexeyklyukin** [comment]
@jchauncey I don't see this problem when installing with helm, can you provide some way to reproduce it?

**Comment by linki** [comment]
@jchauncey also print the version of `helm` and the `patroni` chart

```
helm version
helm search patroni
```

**Comment by alexeyklyukin** [comment]
Closing due to a lack of feedback from the OP.
