### ISSUE TITLE
HA decision loop diagram

### ISSUE THREAD

**Issue by zenitraM** [zalando/patroni#344]
We would like to create (mainly for our ops documentation / debugging) a diagram or some documentation of how the Patroni HA loop takes decisions.

There was this [old one on Governor](https://github.com/compose/governor/blob/master/postgres-ha.pdf) but it was removed from Patroni.

Before we dive into the code, how current / correct is it?

**Comment by CyberDem0n** [comment]
It was removed because it doesn't even cover 20% of all cases...

But yeah, I completely agree, it is a great idea to have such diagram.
If you start doing it - please show us and we will correct if something is wrong.

**Comment by luisbosque** [comment]
How did you create the diagram? If we have the sources we can help improving it instead of creating a new one.

**Comment by uspen** [comment]
https://www.draw.io

So gooood!

**Comment by alexeyklyukin** [comment]
I think the issue is merged, thanks for contributing!
