### ISSUE TITLE
Leader lock is not updated when restart is initiated

### ISSUE THREAD

**Issue by ants** [zalando/patroni#345]
3181c4e5 introduced this bit of code:

``` python
                    msg = self.evaluate_scheduled_restart()
                    if msg is not None:
                        return msg
                    return self.process_healthy_cluster()
```

Unless I'm missing something this means that leader lock will not get updated in the cycle that initiates the restart. Was that intentional?  Looks like something like this would do the correct thing:

``` python
                    if msg is not None:
                        logger.info(msg)
                        return self.handle_long_action_in_progress()
```

**Comment by ants** [comment]
Starting a manual failover from `process_healthy_cluster()` seems to have the same issue.

**Comment by CyberDem0n** [comment]
> Starting a manual failover from process_healthy_cluster() seems to have the same issue.

Manual failover will remove leader key anyway, no need to update.

And about restart: I think it would be better to call `evaluate_scheduled_restart` after `process_healthy_cluster`, because it could happen that postgres was already restarted either by `demote` or by `follow`.

something like:
```python
msg = self.process_healthy_cluster()
return not self._async_executor.busy and self.evaluate_scheduled_restart() or msg
```

**Comment by ants** [comment]
Postponing seems like a good solution for restart. But manual failover will not remove leader key immediately, it will first do a checkpoint and then do a PostgreSQL shut down. This can easily take longer than loop_wait, after which `handle_long_action_in_progress()` takes over updating leader key.

**Comment by CyberDem0n** [comment]
As I understand you are trying to make sure that main loop is ticking regularly, otherwise watchdog will break. `process_manual_failover_from_leader` at the end will call `demote` asynchronously and it should not really harm, but `demote('offline')` is a problem, because it is being executed from the main loop.

Regarding updating leader key when doing manual failover: I think it should be safe to call `process_manual_failover_from_leader` right after successful call of `update_lock`.

I will prepare pull request with these two fixes.

**Comment by CyberDem0n** [comment]
Here we go: https://github.com/zalando/patroni/pull/346

**Comment by ants** [comment]
#346 looks good.

I found these issues when systematically going through the main HA loop to find where are  the actual safe points where we can trigger keepalive and ensuring that every code path has one without actions that could block more than loop_wait under reasonable circumstances. But even without a watchdog they can cause loss of leader key leading to failover or premature promotion of standby.

I already have a couple of solutions for `demote('offline')` that involve reimplementing `pg_ctl stop` in Python, setting an event when user backends have terminated and a background thread pinging the watchdog while the stop completes. Currently trying to figure out a way to structure the code in a way that doesn't make it too convoluted. I'm thinking of making all instances of `not has_lock and state_handler.is_leader()` do synchronous  `demote()`. It might make things a bit cleaner. Any objections?

**Comment by alexeyklyukin** [comment]
The original issue is fixed and the watchdog discussion is a spin off of this issue, better addressed at https://github.com/zalando/patroni/pull/343
