### ISSUE TITLE
Implement a delayed replica

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/patroni#36]
Currently, all replicas in the Spilo cluster are equal and can take over the role of the master when necessary. However, it is impossible to designate a replica as delayed by an hour or two, which in practice is very useful for mitigating disasters like dropping a very important table or running a delete without the where clause.

It would be an improvement to have a replica running in a delayed mode with a configurable delay. Obviously, such replica won't be able to participate in the failover process, but that's ok for the use case we are addressing. 

We might think about implementing this after having the ability to mark a single node as non-participating in the election. Alternatively, using the external master feature, we may just run the whole spilo cluster in a standby mode, and add another parameter to customize such a mode: that might be either a replication delay for delayed replicas, or max_standby_archive/streaming delay to run analytical replicas without affecting the availability of the normal ones.

**Comment by LappleApple** [comment]
@alexeyklyukin Is this something we can tag as "Help Wanted"?

**Comment by alexeyklyukin** [comment]
I think it's not the task of Patroni. One can always implement a delay by supplying custom recovery.conf parameter to Patroni configuration and designating the node as nofailover and noloadbalance. I'm closing this issue.
