### ISSUE TITLE
Patroni Cluster with 2 Datacenter, mixed replication -  synchronous mode parameter configure problem ?

### ISSUE THREAD

**Issue by vigodeltoro** [zalando/patroni#369]
Hello folks,

We have a problem configuring a patroni cluster in a mixed synchronous and asynchronous replication mode. Maybe anybody has an idea what is wrong in the configuration or the setup. Help would be really appreciated.

The following set up which is desired :

2 Datacenter 
in each : 2 HA Proxy Server and 2 Patroni / Postgres database servers. 

Asynchronous replication between the datacenters because of a long network distance and synchronous replication inside the location because of the need of no data loss if the database failovers.

With asynchonous replication everything is running quite well. Even with the HAproxies. But as mentioned we can't loose data if the database perfoms a failover and thats not shure with asynchronous replication.

I tested a lot with synchronous replication in a 2 node test cluster and this works as well. But we figured out the problem with hanging sql queries if the the standby crashs ( Both cases tested : I stopped patroni and i killed postgres and patroni ). This is in my eyes normal behaviour with synchronous replication. 

To avoid that, i tried the "synchronous_mode" parameter. After reading the documentation i would expect that if standby crashs, patroni recognizes the standby is gone and after the "ttl delay", the master server will be return to standalone mode. But this don't happen.. and i have no clue why.

The configurations:

Centos 7.2 / Postgres 9.3.14 / Patroni 1.0

DB1.yml ( first master )

scope: latest
name: x90067.adm.xxxx.de
namespace: /db-xxxx-latest

restapi:
  listen: 0.0.0.0:8008
  connect_address: xxx.xxx.xxx.xxx:8008

  authentication:
    username: postgres
    password: xxxxxx

etcd:

  discovery_srv: latest.stage.xxxxx.de

bootstrap:

  dcs:
    ttl: 15 
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        hba_file: /etc/postgresql/pg_hba.conf
        max_connections: 1000
        wal_keep_segments: 100
        max_wal_senders: 10
        synchronous_commit: "on"
        synchronous_standby_names: "x90068.adm.xxxx.de"

  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums
  - locale: de_DE.UTF-8

  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 127.0.0.1,patronidb-1.latest.stage.xxx.de:5432
  connect_address: patronidb-1.latest.stage.xxxx.de:5432
  data_dir: /data/application/postgresql/patroni_db1
  custom_conf: /etc/postgresql/postgresql.conf
  
  pgpass: /local/postgres/.pgpass
  authentication:
    replication:
      username: replicator
      password: xxxxx
    superuser:
      username: postgres
      password: xxxxx
  parameters:
      hba_file: /etc/postgresql/pg_hba.conf
      unix_socket_directories: '.'
      synchronous_commit: "on"
      synchronous_standby_names: "x90068.adm.xxxx.de"

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false

After initdb i configured via restAPI the synchronous mode

{
  "retry_timeout": 10,
  "postgresql": {
    "parameters": {
      "synchronous_commit": "on",
      "wal_keep_segments": 100,
      "max_wal_senders": 10,
      "hba_file": "/etc/postgresql/pg_hba.conf",
      "synchronous_standby_names": "x90068.adm.xxxx.de",
      "max_connections": 1000
    },
    "use_pg_rewind": true
  },
  "synchronous_mode": "on",
  "maximum_lag_on_failover": 1048576,
  "loop_wait": 10,
  "ttl": 15
}

#######################

DB2.yml ( slave )

scope: latest
name: x90068.adm.xxxx.de
namespace: /db-xxxx-latest

restapi:
  listen: 0.0.0.0:8008
  connect_address: xxx.xxx.xxx.xxx:8008
  authentication:
    username: postgres
    password: xxxx

etcd:

  discovery_srv: latest.stage.xxxx.de

bootstrap:

  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: false
      parameters:
        hba_file: /etc/postgresql/pg_hba.conf
        max_connections: 1000
        wal_keep_segments: 100
        max_wal_senders: 10
        synchronous_commit: "on"
        synchronous_standby_names: "x90068.adm.xxxx.de"
 
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums
  - locale: de_DE.UTF-8

  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 127.0.0.1,patronidb-2.latest.stage.xxxx.de:5432
  connect_address: patronidb-2.latest.stage.xxxx.de:5432
  data_dir: /data/application/postgresql/patroni_db2
  custom_conf: /etc/postgresql/postgresql.conf
  
  pgpass: /local/postgres/.pgpass
  authentication:
    replication:
      username: replicator
      password: xxxxx
    superuser:
      username: postgres
      password: xxxxx
  parameters:
      hba_file: /etc/postgresql/pg_hba.conf
      unix_socket_directories: '.'
      synchronous_commit: "on"
      synchronous_standby_names: "x90068.adm.xxxx.de"

tags:
    nofailover: false 
    noloadbalance: false
    clonefrom: false

API Output:

{
  "retry_timeout": 10,
  "postgresql": {
    "use_pg_rewind": true,
    "parameters": {
      "synchronous_commit": "on",
      "wal_keep_segments": 100,
      "max_wal_senders": 10,
      "hba_file": "/etc/postgresql/pg_hba.conf",
      "synchronous_standby_names": "x90068.adm.xxxx.de",
      "max_connections": 1000
    }
  },
  "synchronous_mode": "on",
  "maximum_lag_on_failover": 1048576,
  "loop_wait": 10,
  "ttl": 15
}
#########################################

Does anybody have an idea whats going wrong ? The database master returns to work if standby patroni is up and running again. But it doesn't go to standalone mode, neither with shutdown patroni controlled nor with a kill -9 to patroni and postgres.

#########################################

If anybody has an idea to solve this setup in a better way, ideas are welcome. :)

At this point, many thanks for everybodies help in advance and a big thank you to the developers of this great tool ... it is really a great peace of work :)

**Comment by uspen** [comment]
Hello!
synchronous_standby_names must be SQL ident syntax. You have dot in name. Its wrong.
Try replace x90068.adm.denic.de --> x90068

**Comment by vigodeltoro** [comment]
Hi and thanks a lot for your reply...

i tested it with only "x90068" in the "synchronous_standby_names" Parameter

{
  "retry_timeout": 10,
  "postgresql": {
    "parameters": {
      "hba_file": "/etc/postgresql/pg_hba.conf",
      "max_wal_senders": 10,
      "wal_keep_segments": 100,
      "synchronous_standby_names": "x90068",
      "max_connections": 1000
    },
    "use_pg_rewind": true
  },
  "synchronous_mode": "on",
  "maximum_lag_on_failover": 1048576,
  "loop_wait": 10,
  "ttl": 15
}


Same issue.. the master server didn't go to standalone mode. The queries are hanging if slave crashs. I also tried to set a additional timeout to my create queries but without success..

Again thanks a lot in advance for your help

**Comment by CyberDem0n** [comment]
> Patroni 1.0

Actually `synchronous_mode` is supported starting from version 1.2. It is available already for installing with pip or you can install it directly from the master branch.

> the master server didn't go to standalone mode.

This is actually the idea of `synchronous_mode`. In case if the synchronous replica has crashed Patroni on the master node should pick another replica and make it synchronous.

**Comment by vigodeltoro** [comment]
Aaaaaaah ... great information ;)

I think that will probably fix my problem .., i will upgrade and have a try 

thanks a lot

**Comment by LappleApple** [comment]
@vigodeltoro Hi there -- if you're using Patroni in production, it would be great to get a few sentences from you about it. Let me know if you're up for sharing. -- Zalando Open Source Evangelist

**Comment by uspen** [comment]
Yes, you must use patroni 1.2 )

I use patroni in production! I may share experiens

**Comment by vigodeltoro** [comment]
Hi Lauri,

 

i was in holiday, sorry for the late answer.

Yes, we're using patroni in production. I will talk to my boss about writing a user story.

If i'm allowed to do it .. where is the place for sharing it ?

 

kind regards

Christian

 

 

Gesendet: Dienstag, 20. Dezember 2016 um 17:44 Uhr
Von: "Lauri Apple" <notifications@github.com>
An: zalando/patroni <patroni@noreply.github.com>
Cc: "Christian Petrasch" <helldog112@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [zalando/patroni] Patroni Cluster with 2 Datacenter, mixed replication - synchronous mode parameter configure problem ? (#369)


@vigodeltoro Hi there -- if you're using Patroni in production, it would be great to get a few sentences from you about it. Let me know if you're up for sharing. -- Zalando Open Source Evangelist
