### ISSUE TITLE
Update patroni to head version 1.2.2 problems

### ISSUE THREAD

**Issue by vigodeltoro** [zalando/patroni#372]
Hi,

i've got a problem with the update to the head version of patroni (1.2.2 ). After updating patroni and postgres ( 9.3.14 -> 9.5.5 ) i'm stuck in the following stacktrace after bootstraping the DB:

Centos7.2 / Patroni 1.2.2 / Python 2.7 / Postgres 9.5.5

Dec 20 17:01:29 x90067 patroni: creating subdirectories ... ok
Dec 20 17:01:29 x90067 patroni: selecting default max_connections ... 100
Dec 20 17:01:29 x90067 patroni: selecting default shared_buffers ... 128MB
Dec 20 17:01:29 x90067 patroni: selecting dynamic shared memory implementation ... posix
Dec 20 17:01:29 x90067 patroni: creating configuration files ... ok
Dec 20 17:01:30 x90067 patroni: creating template1 database in /data/application/postgresql/patro
ni_db1/base/1 ... ok
Dec 20 17:01:30 x90067 patroni: initializing pg_authid ... ok
Dec 20 17:01:30 x90067 patroni: setting password ... ok
Dec 20 17:01:30 x90067 patroni: initializing dependencies ... ok
Dec 20 17:01:30 x90067 patroni: creating system views ... ok
Dec 20 17:01:30 x90067 patroni: loading system objects' descriptions ... ok
Dec 20 17:01:30 x90067 patroni: creating collations ... ok
Dec 20 17:01:31 x90067 patroni: creating conversions ... ok
Dec 20 17:01:31 x90067 patroni: creating dictionaries ... ok
Dec 20 17:01:31 x90067 patroni: setting privileges on built-in objects ... ok
Dec 20 17:01:31 x90067 patroni: creating information schema ... ok
Dec 20 17:01:31 x90067 patroni: loading PL/pgSQL server-side language ... ok
Dec 20 17:01:31 x90067 patroni: vacuuming database template1 ... ok
Dec 20 17:01:31 x90067 patroni: copying template1 to template0 ... ok
Dec 20 17:01:31 x90067 patroni: copying template1 to postgres ... ok
Dec 20 17:01:31 x90067 patroni: syncing data to disk ... ok

Dec 20 17:01:31 x90067 patroni: WARNING: enabling "trust" authentication for local connections
Dec 20 17:01:31 x90067 patroni: You can change this by editing pg_hba.conf or using the option -A, or
Dec 20 17:01:31 x90067 patroni: --auth-local and --auth-host, the next time you run initdb.
Dec 20 17:01:31 x90067 patroni: Success. You can now start the database server using:
Dec 20 17:01:31 x90067 patroni: /usr/pgsql-9.5/bin/pg_ctl -D /data/application/postgresql/patroni_db1 -l logfile start
Dec 20 17:01:31 x90067 patroni: 2016-12-20 17:01:31,948 INFO: removing initialize key after failed attempt to initialize the cluster
Dec 20 17:01:31 x90067 patroni: waiting for server to shut down....< 2016-12-20 17:01:31.971 CET >LOG:  redirecting log output to logging collector process
Dec 20 17:01:31 x90067 patroni: < 2016-12-20 17:01:31.971 CET >HINT:  Future log output will appear in directory "pg_log".
Dec 20 17:01:32 x90067 patroni: done
Dec 20 17:01:32 x90067 patroni: server stopped
Dec 20 17:01:32 x90067 patroni: 2016-12-20 17:01:32,963 INFO: renaming data directory to /data/application/postgresql/patroni_db1_2016-12-20-17-01-32
Dec 20 17:01:33 x90067 patroni: Traceback (most recent call last):
Dec 20 17:01:33 x90067 patroni: File "/bin/patroni", line 9, in <module>
Dec 20 17:01:33 x90067 patroni: load_entry_point('patroni==1.2.2', 'console_scripts', 'patroni')()
Dec 20 17:01:33 x90067 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 172, in main
Dec 20 17:01:33 x90067 patroni: return patroni_main()
Dec 20 17:01:33 x90067 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 134, in patroni_main
Dec 20 17:01:33 x90067 patroni: patroni.run()
Dec 20 17:01:33 x90067 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 110, in run
Dec 20 17:01:33 x90067 patroni: logger.info(self.ha.run_cycle())
Dec 20 17:01:33 x90067 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 938, in run_cycle
Dec 20 17:01:33 x90067 patroni: info = self._run_cycle()
Dec 20 17:01:33 x90067 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 886, in _run_cycle
Dec 20 17:01:33 x90067 patroni: return self.bootstrap()  # new node
Dec 20 17:01:33 x90067 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 151, in bootstrap
Dec 20 17:01:33 x90067 patroni: self.state_handler.bootstrap(self.patroni.config['bootstrap'])
Dec 20 17:01:33 x90067 patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1219, in bootstrap
Dec 20 17:01:33 x90067 patroni: if self._initialize(config) and self.start() and self.run_bootstrap_post_init(config):
Dec 20 17:01:33 x90067 patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 720, in start
Dec 20 17:01:33 x90067 patroni: pid = int(proc.stdout.readline().strip())

****Dec 20 17:01:33 x90067 patroni: ValueError: invalid literal for int() with base 10: "['postgres', '-D', '/data/application/postgresql/patroni_db1', '--hot_standby=on', '--listen_addresses=127.0.0.1,patronidb-1.latest.stage.xxxx.de', '--max_worker_processes=8', '--max_locks_per_transa"****

Dec 20 17:01:33 x90067 systemd[1]: patroni.service: main process exited, code=exited, status=1/FAILURE
Dec 20 17:01:33 x90067 systemd[1]: Unit patroni.service entered failed state.

################################################################

scope: latest
name: x90067
namespace: /db-xxxx-latest

restapi:
  listen: 0.0.0.0:8008
  connect_address: 172.23.90.79:8008
  authentication:
    username: postgres
    password: postgres

etcd:

  discovery_srv: latest.stage.xxxxx.de

bootstrap:
  dcs:
    ttl: 15 
    loop_wait: 10
    retry_timeout: 10
    postgresql:
  
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
 
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:

   listen: 127.0.0.1,patronidb-1.latest.stage.xxx.de:5432
   connect_address: patronidb-1.latest.stage.xxx.de:5432
   data_dir: /data/application/postgresql/patroni_db1
  
##  pgpass: /local/postgres/.pgpass
authentication:
   replication:
      username: replicator
      password: slq!2016%
   superuser:
      username: postgres
      password: sqlIAL2011

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false

Have anybody the same problem or an idea wheres the failure is ?
I appreciate every idea whats going wrong..

thank you very much

**Comment by CyberDem0n** [comment]
Something is really strange happening:

Dec 20 17:01:33 x90067 patroni: pid = int(proc.stdout.readline().strip())
****Dec 20 17:01:33 x90067 patroni: ValueError: invalid literal for int() with base 10: "['postgres', '-D', '/data/application/postgresql/patroni_db1', '--hot_standby=on', '--listen_addresses=127.0.0.1,patronidb-1.latest.stage.xxxx.de', '--max_worker_processes=8', '--max_locks_per_transa"****

It expects to get postmaster pid on this line, which was printed here https://github.com/zalando/patroni/blob/master/patroni/__init__.py#L149.

But instead of pid it gets list of postgres arguments....

Which python version do you have (python --version)?
We run tests with python 2.7.9 on travis and everything is fine there...

**Comment by vigodeltoro** [comment]
After your comment i crosschecked the code again.. i can say.. nothing strange happens. During my tests and a lot of debug i have done because there where a lot of links i had to set for path variables ( postgres tools ), i inserted a "print args" line in patroni source code and exact at the position you mentioned. This line was the reason for the strange logging output. I needed several tests until i realized that Postgres 9.3 isn't supported und a lot more to fix all this errors: 

Dec 21 09:55:12 x90067 patroni: File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
Dec 21 09:55:12 x90067 patroni: raise child_exception
Dec 21 09:55:12 x90067 patroni: OSError: [Errno 2] No such file or directory

If anybody has this errors, you can fix it with linking the following to /usr/bin/

postgres
initdb
pg_ctl
pg_controldata
pg_isready

initdb and pg_ctl was necessary in the past versions of patroni as well.. but the other ones are new.
Another possibility would be to put /usr/pgsql-9.5/bin/ to PATH

After fixing i forgot to remove the line.

BTW: Patroni 1.2.2 is now  working on CentOS 7.2 / Python 2.7.5, maybe the information is helpful for development.. 

I apologize a lot for my fault and the confusion and many thanks for your help.

cheers and a merry christmas

**Comment by CyberDem0n** [comment]
> Another possibility would be to put /usr/pgsql-9.5/bin/ to PATH

You can use:
```yaml
postgresql:
  bin_dir: /usr/pgsql-9.5/bin
```

or `export PATRONI_POSTGRESQL_BIN_DIR=/usr/pgsql-9.5/bin`

**Comment by vigodeltoro** [comment]
cool, the bin_dir parameter is a good hint.. thanks

Export is a solution as well, but with our automation system not the best.. i will configure bin_dir :)
