### ISSUE TITLE
Question: etcd service location

### ISSUE THREAD

**Issue by jamessewell** [zalando/patroni#388]
Hello all,

Is running etcd on the database servers themselves (with a 3+ node cluster) a good idea, or is it always advised to have an external etcd cluster?

If it is run on the database servers are there any implications for resiliency?

Cheers,
James

**Comment by CyberDem0n** [comment]
Hi,

It's up to you where and how you will run etcd nodes.
Etcd itself doesn't consume much resources if Patroni is the only application using it.

Actually for you it should be really interesting to look on (and test) https://github.com/zalando/patroni/pull/375
It implements RAFT protocol internally and allows to run Patroni without etcd.

**Comment by jamessewell** [comment]
Thanks!
