### ISSUE TITLE
Support multi sync standbys

### ISSUE THREAD

**Issue by jamessewell** [zalando/patroni#389]
Hello,

Now PostgreSQL 9.6 supports having N sync standbys with the following syntax:

`synchronous_standby_names='2(standby1, standby2)'`

Are there any plans to extend Patroni to support this?

Ideally it would be great to have 3 nodes at siteA and 3 nodes at siteB and enforce a sync standby in each site at all times. I would imagine this wouldn't be too large a change?

Cheers,

**Comment by CyberDem0n** [comment]
Implementing algorithm selecting two standbys instead of one is not a problem, but right now Patroni has no notion of datacenters, therefore it's not possible to guaranty that these standbys would be on different sites.

**Comment by jamessewell** [comment]
Unless you only have two nodes per site :)

Thanks!
