### ISSUE TITLE
Synchronous mode strict

### ISSUE THREAD

**Issue by jamessewell** [zalando/patroni#397]
hi,

At the moment if no sync standby is available it looks like the master loosens the synchronous contract to allow commits. This is called Maximum Availability in Oracle land, and isn't possible in vanilla PostgreSQL. It's great this is an option!

It would be great to also be able to mandate 0 data loss by blocking all writes when all standbys went offline.

Cheers,
James Sewell

**Comment by alexeyklyukin** [comment]
Hi @jamessewell 

I think you can get this behavior by disabling synchronous mode altogether and setting synchronous_standby_names to '*' in your postgresql configuration. That would disable management of synchronous standbys by Patroni and revert to the PostgreSQL default behavior of waiting for the writes to be acknowledged by a synchronous standby before reporting them as committed to the client.

What are the benefits of the Patroni synchronous mode for you if a default PostgreSQL behavior regarding synchronous commits w/o the sync replica would be enforced?

**Comment by jamessewell** [comment]
You can get the behaviour like that, but then you lose the guarantee that
any failover will only happen to the sync standby - correct?

Cheers,
James Sewell

**Comment by alexeyklyukin** [comment]
Yes, I had the same thoughts. I think it's a valid request.

**Comment by CyberDem0n** [comment]
Closed with https://github.com/zalando/patroni/pull/400
