### ISSUE TITLE
Patroni does not select all addresses etcd

### ISSUE THREAD

**Issue by uspen** [zalando/patroni#401]
Etcd cluster 5 nodes. I go down one node - 1node0001.example.com (10.41.34.51)

Patroni v 1.1

Config:

etcd:
  host: 1node0001.example.com:2379

Patroni try select other etcd node but fail.

фев 21 17:33:14 0node0008.example.com patroni[25051]: 2017-02-21 17:33:14,839 ERROR: Request to server http://10.41.34.51:2379 failed: MaxRetryError("HTTPConnectionPool(host='**10.41.34.51**', port=2379):
фев 21 17:33:14 0node0008.example.com patroni[25051]: 2017-02-21 17:33:14,839 INFO: Reconnection allowed, looking for another server.
фев 21 17:33:14 0node0008.example.com patroni[25051]: 2017-02-21 17:33:14,840 INFO: Selected new etcd server http://**10.16.34.52**:2379
фев 21 17:33:14 0node0008.example.com patroni[25051]: 2017-02-21 17:33:14,840 INFO: Starting new HTTP connection (1): 10.16.34.52
фев 21 17:33:14 0node0008.example.com patroni[25051]: Traceback (most recent call last):
фев 21 17:33:14 0node0008.example.com patroni[25051]: Traceback (most recent call last):
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
фев 21 17:33:14 0node0008.example.com patroni[25051]: Traceback (most recent call last):
фев 21 17:33:14 0node0008.example.com patroni[25051]: 2017-02-21 17:33:14,849 INFO: Lock owner: n0node0008_5432; I am n0node0008_5432
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
фев 21 17:33:14 0node0008.example.com patroni[25051]: Traceback (most recent call last):
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
фев 21 17:33:14 0node0008.example.com patroni[25051]: Traceback (most recent call last):
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish_request(request, client_address)
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.RequestHandlerClass(request, client_address, self)
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.wfile.close()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 279, in close
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish_request(request, client_address)
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.RequestHandlerClass(request, client_address, self)
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish_request(request, client_address)
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.RequestHandlerClass(request, client_address, self)
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.wfile.close()
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish_request(request, client_address)
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 279, in close
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.RequestHandlerClass(request, client_address, self)
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish()
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.wfile.close()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 279, in close
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish_request(request, client_address)
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
фев 21 17:33:14 0node0008.example.com patroni[25051]: Traceback (most recent call last):
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.wfile.close()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 279, in close
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.RequestHandlerClass(request, client_address, self)
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish_request(request, client_address)
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.wfile.close()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 279, in close
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.RequestHandlerClass(request, client_address, self)
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.wfile.close()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 279, in close
фев 21 17:33:14 0node0008.example.com patroni[25051]: Traceback (most recent call last):
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish_request(request, client_address)
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.RequestHandlerClass(request, client_address, self)
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.finish()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.wfile.close()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 279, in close
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.flush()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
фев 21 17:33:14 0node0008.example.com patroni[25051]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.flush()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
фев 21 17:33:14 0node0008.example.com patroni[25051]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.flush()
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.flush()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
фев 21 17:33:14 0node0008.example.com patroni[25051]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
фев 21 17:33:14 0node0008.example.com patroni[25051]: error: [Errno 32] Broken pipe
фев 21 17:33:14 0node0008.example.com patroni[25051]: error: [Errno 32] Broken pipe
фев 21 17:33:14 0node0008.example.com patroni[25051]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
фев 21 17:33:14 0node0008.example.com patroni[25051]: error: [Errno 32] Broken pipe
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.flush()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
фев 21 17:33:14 0node0008.example.com patroni[25051]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
фев 21 17:33:14 0node0008.example.com patroni[25051]: error: [Errno 32] Broken pipe
фев 21 17:33:14 0node0008.example.com patroni[25051]: error: [Errno 32] Broken pipe
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.flush()
фев 21 17:33:14 0node0008.example.com patroni[25051]: self.flush()
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
фев 21 17:33:14 0node0008.example.com patroni[25051]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
фев 21 17:33:14 0node0008.example.com patroni[25051]: error: [Errno 32] Broken pipe
фев 21 17:33:14 0node0008.example.com patroni[25051]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
фев 21 17:33:14 0node0008.example.com patroni[25051]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
фев 21 17:33:14 0node0008.example.com patroni[25051]: error: [Errno 32] Broken pipe
фев 21 17:33:14 0node0008.example.com patroni[25051]: 2017-02-21 17:33:14,973 INFO: no action.  i am the leader with the lock
фев 21 17:33:22 0node0008.example.com patroni[25051]: 2017-02-21 17:33:22,839 INFO: Lock owner: n0node0008_5432; I am n0node0008_5432

<SKIP>

фев 21 17:35:13 0node0008.example.com patroni[25051]: 2017-02-21 17:35:13,028 INFO: no action.  i am the leader with the lock
фев 21 17:35:22 0node0008.example.com patroni[25051]: 2017-02-21 17:35:22,836 INFO: Selected new etcd server http://**10.41.34.51**:2379
фев 21 17:35:22 0node0008.example.com patroni[25051]: 2017-02-21 17:35:22,837 INFO: Starting new HTTP connection (2): 10.41.34.51
фев 21 17:35:26 0node0008.example.com patroni[25051]: 2017-02-21 17:35:26,175 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0)) after connection broken by 'ConnectTimeoutError(<u
фев 21 17:35:26 0node0008.example.com patroni[25051]: 2017-02-21 17:35:26,176 INFO: Starting new HTTP connection (3): 10.41.34.51
фев 21 17:35:29 0node0008.example.com patroni[25051]: 2017-02-21 17:35:29,513 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0)) after connection broken by 'ConnectTimeoutError(<u
фев 21 17:35:29 0node0008.example.com patroni[25051]: 2017-02-21 17:35:29,513 INFO: Starting new HTTP connection (4): 10.41.34.51
фев 21 17:35:32 0node0008.example.com patroni[25051]: 2017-02-21 17:35:32,850 ERROR: Failed to get list of machines from http://10.41.34.51:2379/v2: MaxRetryError("HTTPConnectionPool(host='10.41.34.51
фев 21 17:35:32 0node0008.example.com patroni[25051]: 2017-02-21 17:35:32,850 ERROR: Machines cache is empty, no machines to try.
фев 21 17:35:32 0node0008.example.com patroni[25051]: 2017-02-21 17:35:32,851 ERROR: get_cluster

After that I tried reproduce situation with demo cluster and get result. Patroni will select only 2 nodes

**Comment by CyberDem0n** [comment]
It looks very strange. Can it be that etcd cluster misconfigured?
Please try to execute  `curl http://etcd-nodeX-ip:2379/v2/machines` against every etcd node.
As a response it should print comma separated list of etcd client urls.
Every node should return the same set or urls. How many ulrs in the list?

**Comment by uspen** [comment]
Yes, strange. List have 5 URLs

curl http://1node0001.example.com:2379/v2/machines
http://10.16.34.51:2379, http://10.16.34.52:2379, http://10.16.34.53:2379, http://10.41.34.51:2379, http://10.41.34.52:2379

And similar on other nodes

And Patroni v. 1.2 (i periodically make from git).

Also, if change patroni yaml config (etcd: host:) SIGHUP dont work. Restart helped.

**Comment by uspen** [comment]
On demo lab Patroni select second IP and work. But if second IP Unreachable Patroni fail.

**Comment by CyberDem0n** [comment]
Until v1.2 Patroni had one nasty "feature":
 * It chooses randomly one of the etcd nodes and sticks to it.
 * If the request on this node fails - it switches to another one and updates etcd cluster topology by performing ':2379/v2/machines' request

Now think about situation when you replaced all etcd except the one Patroni connected and more important that these nodes got a new addresses.
Patroni will try to switch to another node, but without success and so on, until list of nodes exhausted.

Such behaviour has changed in v1.2. It will periodically update topology by performing  ':2379/v2/machines' request. Periodically in this case means ones per 5 minutes.

> Also, if change patroni yaml config (etcd: host:) SIGHUP dont work. Restart helped.

Yes, it is not supported for purpose. It's very strange to change etcd connection address in runtime.

**Comment by uspen** [comment]
> It's very strange to change etcd connection address in runtime.

:-)) Yes, I agree with you

> Until v1.2 Patroni had one nasty "feature"

Oh, it mayby! I try upgrade, Thank you!

**Comment by uspen** [comment]
Yes, upgrade solves problem
