### ISSUE TITLE
FATAL:  the database system is starting up < showing up a lot in logs

### ISSUE THREAD

**Issue by drnic** [zalando/patroni#402]
During disaster recovery of leader (we prepopulate /initialize with sysid), and before the `accepting connections` state has been achieved - I see `FATAL:  the database system is starting up` in the logs. A lot. Like 100s a second. 

It's like:
```
FATAL:  the database system is starting up
FATAL:  the database system is starting up
FATAL:  the database system is starting up
FATAL:  the database system is starting up
FATAL:  the database system is starting up
FATAL:  the database system is starting up
FATAL:  the database system is starting up
FATAL:  the database system is starting up
FATAL:  the database system is starting up
```

But hundreds of them.

I think it's caused by a client pinging the database, but its still recovery?

Can anyone think or suggest what in patroni might be hammering the DB during the startup period without pause? Or what else the root cause might be? Perhaps I've configured something incorrectly?

**Comment by sean-** [comment]
It's not Patroni, most likely, it's a replay of the WAL logs.  It should clear up when it's finished applying, but it's almost certainly not Patroni.

**Comment by drnic** [comment]
Ok thx. Any protips in the patroni/wale stack for quietening it down? Not sure these logs are helping; and they do look very scary x 100s.

No one else sees this during any recovery scenarios?

**Comment by drnic** [comment]
Ok, I have a culprit. Sorry for the ticket. But perhaps it helps someone else in future who did the same silly thing.
```
  while true; do
    pg_isready >/dev/null 2>&2 || continue
    ...
  done
```
