### ISSUE TITLE
patroni.yml

### ISSUE THREAD

**Issue by patdenis** [zalando/patroni#404]
hi,
   i configure patroni.yml:

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
         hot_standby: "on"
         wal_level: archive
         wal_keep_segments: 8
         max_wal_senders: 5
         max_replication_slots: 5
         wal_log_hints: "on"
         archive_mode: "on"
         archive_timeout: 1800s
         archive_command: "mycommand"
      recovery_conf:
        restore_command: "mycommand"

but when i look at the file recovery.conf in my data dir i don't see my configuration.
if i prompt: etcdctl -o extended get /service/pgha01/config/
i don'see new key.
i restart patroni cluster but problem persist.
thanks
Denis

**Comment by drnic** [comment]
Perhaps can you repaste in your YAML but within triple back ticks so that it remains formatted?

Ideas here https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by CyberDem0n** [comment]
Hi @patdenis 

If you changed `bootstrap.dcs` for an existing cluster and restarted patroni - it wont do anything,
`bootstrap` section is used only once, when you are starting up a brand new cluster (initdb and so on)

For configuration change in the existing cluster you have to use patroni api: https://github.com/zalando/patroni/blob/master/docs/dynamic_configuration.rst#rest-api

> if i prompt: etcdctl -o extended get /service/pgha01/config/

The right key name would be: `/service/pgha01/config` (without leading slash)

**Comment by alexeyklyukin** [comment]
In addition, you need ``wal_level: hot_standby`` instead of ``wal_level: archive``, as you have ``hot_standby`` enabled and Patroni actually queries replicas in order to figure out their start time, WAL positions and sync replication slots if the replica is designated as a ``clonefrom`` by some other replica.

**Comment by patdenis** [comment]
thanks, sorry for question but i have just started to configure Patroni.
yes, i need wal_level: hot_standby, it wal a distraction.
