### ISSUE TITLE
wale_restore.py calling wal-e backup-list but no response

### ISSUE THREAD

**Issue by drnic** [zalando/patroni#406]
https://github.com/zalando/patroni/blob/master/patroni/scripts/wale_restore.py#L190

The logs show that `wal-e backup-list` is being invoked.

```
INFO: trying to bootstrap (without leader) 
create_replica_with_s3 start... 
wal_e.main   INFO     MSG: starting WAL-E 
        DETAIL: The subcommand is "backup-fetch". 
        STRUCTURED: time=2017-03-04T05:02:40.548006-00 pid=139 
wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download 
        DETAIL: The partition being downloaded is part_00000000.tar.lzo. 
        HINT: The absolute S3 key is backups/T-5663068841/wal/basebackups_005/base_000000010000000000000002_00000040/tar_partitions/part_00000000.tar.lzo. 
        STRUCTURED: time=2017-03-04T05:02:44.981230-00 pid=139 
```

But somehow magically the `ret = subprocess.call` is finishing without resuming any paths in the script. I've put logs all around it and nothing gets called.

```python
    def create_replica_with_s3(self):
        logger.info('create_replica_with_s3 start...') # this gets printed
        # if we're set up, restore the replica using fetch latest
        try:
            ret = subprocess.call(self.wal_e.cmd.split() + ['backup-fetch', '{}'.format(self.data_dir), 'LATEST'])
            logger.info('wal-e backup-fetch: done') # this doesn't get printed
        except subprocess.CalledProcessError as e:
            logger.exception("could not wal-e backup-fetch: {0}".format(e))
            return 1
        except Exception as e:
            logger.info('Error when fetching backup with WAL-E: {0}'.format(e))
            logger.error('Error when fetching backup with WAL-E: {0}'.format(e))
            return 1

        logger.info('wal-e backup-fetch returned {0}'.format(ret))
        if (ret == 0 and not self.fix_subdirectory_path_if_broken('pg_xlog' if get_major_version(self.data_dir) < 10.0 else 'pg_wal')):
            logger.info('fix_subdirectory_path_if_broken returned False')
            return 2
        return ret
```

I've run out of basic python skills and google/stackoverflow ideas.

Can any one think what might be going on during/after the `subprocess.call` for it to be returning and dropping down to the `WALERestore` wrapper `for` loop that does the retry?

Update: Actually not sure that its the wale_restore.py loop that is the retry loop. After the `wal-e backup-fetch` logs, the next log line is:

```
INFO: trying to bootstrap (without leader)
```

Which is back inside patroni itself; but then none of the error/success logs there are displayed either. https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L554

Background: patroni is running on a docker container; and in various environments it works as expected. I'm running the same docker container in a diff host environment; but this bizarre python3/subprocess.call behavior is occurring consistently. Super confusing. I've been debugging the resulting integration test failure for the last 24 hrs and it's come down to this consistent misbehavior I can't explain.

**Comment by CyberDem0n** [comment]
> Can any one think what might be going on during/after the subprocess.call for it to be returning and dropping down to the WALERestore wrapper for loop that does the retry?

After subprocess.call with wal-e backup-fetch it should create missing pg_xlog and exit from retry loop and script itself will finish also.

I wonder, can it be, that either wal-e or wale_restore.py are killed by kernel due to lack of system resources? Can you look into `dmesg`?

**Comment by drnic** [comment]
OMG, thanks for the idea for "give it more resources". That fixed it.

On the downside, I'm still unsure how I'll stop this again if it happens in prod in future. Hmm.
