### ISSUE TITLE
PG 9.6.2 on alpine 3.5 - ERROR:  permission denied for function pg_start_backup

### ISSUE THREAD

**Issue by drnic** [zalando/patroni#408]
Tried running patroni on an alpine 3.5 with its postgresql 9.6.2 and I get the following:

```
2017-03-04 06:07:15,461 INFO: initialized a new cluster
ERROR:  permission denied for function pg_start_backup
STATEMENT:  COPY (SELECT file_name,   lpad(file_offset::text, 8, '0') AS file_offset FROM pg_xlogfile_name_offset(  pg_start_backup('freeze_start_2017-03-04T06:07:16.805422+00:00'))) TO STDOUT WITH CSV HEADER;
```

Is there something additional I should configure/setup in PG 9.6 for this?

## Reproduce

To reproduce (everything is included, the following should "just work" from any docker env with internet access):

```
docker run -d \
    --name dingo-postgresql \
    -e DOCKER_HOST_IP=${DOCKER_HOST_IP:?required} \
    -e DOCKER_HOST_PORT_5432=${PUBLIC_PORT:-5000} \
    -p ${PUBLIC_PORT:-5000}:5432 \
    -e DINGO_ACCOUNT=$(git config --global --get user.email) \
    -e DINGO_CLUSTER=pg96-cluster-$(date +"%s" | rev) \
    dingotiles/dingo-postgresql-96:pre-test
docker logs dingo-postgresql -f
```

## Docker image

The alpine 3.5 image is built from the following two dockerfiles:

* https://github.com/dingotiles/dingo-postgresql-agent/blob/master/images/postgresql96-base/Dockerfile
* https://github.com/dingotiles/dingo-postgresql-agent/blob/master/Dockerfile.pg96

```
docker build -t dingotiles/dingo-postgresql96-agent-base images/postgresql96-base
docker build -t dingotiles/dingo-postgresql-96:pre-test -f Dockerfile.pg96 .
```

**Comment by CyberDem0n** [comment]
I think this is wal-e trying to do a backup.
And somehow it connects not with superuser.
We are running dozen of clusters on 9.6 and don't have such problem, but we are using ubuntu 14.04 as a baseimage

**Comment by drnic** [comment]
@CyberDem0n right, I assumed it was going to be an environment/dependency/wal-e issue more than a patroni code issue.
