### ISSUE TITLE
Consider using better health checking on Zookeeper and Consul.

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#41]
Zookeeper has ephemeral nodes, and Consul has health checks.  Either of these mechanisms provides a means to detect master failure -- and even replica failure -- faster than via the polling method we need to use with etcd.

We should consider using this advanced mechanism on each of these SIS platforms.

**Comment by CyberDem0n** [comment]
We don't use polling method with etcd anymore. Replicas are "watching" for
events on leader key. You should try the latest version from master and see
how fast it promotes.

**Comment by jberkus** [comment]
Ah, great.  So we just need to implement something similar in Zookeeper?

**Comment by CyberDem0n** [comment]
ZooKeeper implementation is using event-based model from the very beginning.
Ephemeral nodes basically is equivalent of key with ttl. When the session is expired all ephemeral nodes associated with this session are removed.

**Comment by jberkus** [comment]
OK, closing issue.
