### ISSUE TITLE
Upgrade Instructions

### ISSUE THREAD

**Issue by carrgilson** [zalando/patroni#410]
Hi,

How do you go about upgrading from a previous release to the latest, in my case 1.1. to 1.2.4?

Many Thanks,
Adam.

**Comment by alexeyklyukin** [comment]
Hi @carrgilson, generally one reads the release notes for the major version (say http://patroni.readthedocs.io/en/latest/releases.html#version-1-2). Seems there are no breaking changes between 1.1 and 1.2. 1.2 -> 1.2.4 is easy, we don't break anything on "-patch" versions, just do bugfixes.

So, at the end of the day, you probably don't have to do anything, expect for upgrading the binaries.
