### ISSUE TITLE
OSError Errno 18 Cross-device link

### ISSUE THREAD

**Issue by offmindby** [zalando/patroni#412]
Hi.
I've got the next traceback while running patroni in Alpine Linux inside Docker.

Linux version 4.9.12-moby (root@11fbdc1f630f) (gcc version 6.2.1 20160822 (Alpine 6.2.1) ) #1 SMP Tue Feb 28 12:11:36 UTC 20
Python version is 2.7.13
Patroni version is 1.2.4

`2017-03-16 09:58:03,049 ERROR: Could not rename data directory data/postgres
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1234, in move_data_directory
    os.rename(self._data_dir, new_name)
OSError: [Errno 18] Cross-device link`

Howeve, replacing os.rename to shutil.move solves the problem.
Please, review the issue

**Comment by CyberDem0n** [comment]
Hi @offmindby, 

It seems you are using mount point for PGDATA directory.
If you change `os.rename` to `shutil.move` - it will kind of work (not fail), but it will move data between different partitions. This is not something we want.

Please read a message from Tom Lane: https://www.postgresql.org/message-id/19360.1438106478@sss.pgh.pa.us
And documentation: [18.2.1. Use of Secondary File Systems](https://www.postgresql.org/docs/current/static/creating-cluster.html#CREATING-CLUSTER-MOUNT-POINTS)
