### ISSUE TITLE
legacy patroni image does not exist

### ISSUE THREAD

**Issue by edib** [zalando/patroni#416]
docker-compose.yml is referencing legacy patroni image that should be in docker but. It does not exist. I tried registery.zalan.do image. It gives an error, Dockerfile is working fine. I have built my local image and changed image adresses local image, that just works fine.

**Comment by CyberDem0n** [comment]
Hi @edib,

It's not legacy. It has never been published anywhere.
If you have time feel free to update documentation and write that before playing with `docker-compose` you have to build a patroni docker image: `docker build -t patroni .`
