### ISSUE TITLE
No election after loss of leader

### ISSUE THREAD

**Issue by abkfenris** [zalando/patroni#419]
I am trying to get patroni setup in Kubernetes (well minikube right now) by [adapting](https://github.com/abkfenris/atomicdb) @jberkus [atomicbd](https://github.com/jberkus/atomicdb/tree/master/patroni_petset).

When I kill the leader pod it will restart fast enough that it reacquires the leader key so their is no failover. It then will try to bootstrap from itself.

```sh
2017-03-24 13:11:11,066 INFO: Selected new etcd server http://172.17.0.6:2379
2017-03-24 13:11:11,066 INFO: Starting new HTTP connection (1): 172.17.0.6
2017-03-24 13:11:11,087 INFO: trying to bootstrap from leader 'patroni_0'
2017-03-24 13:11:11,089 INFO: Lock owner: patroni_0; I am patroni_0
2017-03-24 13:11:11,096 INFO: updated leader lock during bootstrap from leader 'patroni_0'
pg_basebackup: could not connect to server: could not translate host name "patroni-0.patroni" to address: Name or service not known
2017-03-24 13:11:11,129 ERROR: Error when fetching backup: pg_basebackup exited with code=1
2017-03-24 13:11:11,130 WARNING: Trying again in 5 seconds
2017-03-24 13:11:16,090 INFO: Lock owner: patroni_0; I am patroni_0
2017-03-24 13:11:16,097 INFO: updated leader lock during bootstrap from leader 'patroni_0'
pg_basebackup: could not connect to server: could not connect to server: Connection refused
	Is the server running on host "patroni-0.patroni" (172.17.0.7) and accepting
	TCP/IP connections on port 5432?
2017-03-24 13:11:16,146 ERROR: Error when fetching backup: pg_basebackup exited with code=1
2017-03-24 13:11:16,146 ERROR: failed to bootstrap from leader 'patroni_0'
```

The other two pods don't realize that the leader is trying to bootstrap and try to keep following it rather than having an election.

```sh
[patroni-2] 2017-03-24 13:23:56,100 INFO: Lock owner: patroni_0; I am patroni_2
[patroni-2] 2017-03-24 13:23:56,100 INFO: does not have lock
[patroni-1] 2017-03-24 13:23:56,097 INFO: Lock owner: patroni_0; I am patroni_1
[patroni-1] 2017-03-24 13:23:56,098 INFO: does not have lock
[patroni-1] 2017-03-24 13:23:56,108 INFO: no action.  i am a secondary and i am following a leader
[patroni-2] 2017-03-24 13:23:56,110 INFO: no action.  i am a secondary and i am following a leader
[patroni-2] FATAL:  could not connect to the primary server: could not connect to server: Connection refused
[patroni-2] Is the server running on host "patroni-0.patroni" (172.17.0.7) and accepting
[patroni-2] TCP/IP connections on port 5432?
[patroni-2]
[patroni-1] FATAL:  could not connect to the primary server: could not connect to server: Connection refused
[patroni-1] Is the server running on host "patroni-0.patroni" (172.17.0.7) and accepting
[patroni-1] TCP/IP connections on port 5432?
```

As far as I can tell, there is a method ([ha.release_leader_key_voluntarily](https://github.com/zalando/patroni/blob/8fda95780451029cee6b9dc3fdcf9f71ab4480a6/patroni/ha.py#L474)) for the leader to give up the key but it doesn't look like there is a check if a newly created instance is the leader and to release the key.

**Comment by jberkus** [comment]
Yeah, the lock should be released if the master doesn't have data.  I'll look into it.

This hasn't come up previously because in a multi-machine configuration the original leader node never comes back that fast unless it's mounting the same storage (in which case it's still the master).  However, it should Do The Right Thing regardless.

**Comment by abkfenris** [comment]
If I'm reading things right, I think that an if in [ha._run_cycle](https://github.com/zalando/patroni/blob/8fda95780451029cee6b9dc3fdcf9f71ab4480a6/patroni/ha.py#L856) above [`if self.state_handler.data_directory_empty():`](https://github.com/zalando/patroni/blob/8fda95780451029cee6b9dc3fdcf9f71ab4480a6/patroni/ha.py#L888) would do the trick?

```python
if self.state_handler.data_directory_empty() and self.has_lock():
    self.release_leader_key_voluntarily()
```

Then it looks like `ha.bootstrap()` would run and return `'waiting for leader to bootstrap'`. Patroni would wait for the dsc.loop_wait time before trying again.

I just tried those changes in [abkfenris/patroni](https://github.com/abkfenris/patroni). Now when I `kubectl delete pod patroni-0` it releases the leader key, tries to bootstrap from itself, then bootstraps from the new leader.

```bash
[patroni-0] 2017-03-27 11:15:55,868 INFO: Lock owner: patroni_0; I am patroni_0
[patroni-0] 2017-03-27 11:15:55,880 INFO: Leader key released
[patroni-0] 2017-03-27 11:15:55,888 INFO: trying to bootstrap from leader 'patroni_0'
[patroni-0] 2017-03-27 11:15:55,890 INFO: Lock owner: None; I am patroni_0
[patroni-0] 2017-03-27 11:15:55,892 INFO: not healthy enough for leader race
[patroni-0] pg_basebackup: could not connect to server: could not translate host name "patroni-0.patroni" to address: Name or service not known
[patroni-0] 2017-03-27 11:15:55,924 ERROR: Error when fetching backup: pg_basebackup exited with code=1
[patroni-0] 2017-03-27 11:15:55,925 WARNING: Trying again in 5 seconds
[patroni-0] 2017-03-27 11:16:00,890 INFO: Lock owner: patroni_1; I am patroni_0
[patroni-0] 2017-03-27 11:16:00,898 INFO: bootstrap from leader 'patroni_0' in progress

time passes...

[patroni-0] 2017-03-27 11:18:29,508 INFO: bootstrapped from leader 'patroni_1'
[patroni-0] 2017-03-27 11:18:29,605 INFO: postmaster pid=36
[patroni-0] LOG:  database system was interrupted; last known up at 2017-03-27 11:18:29 UTC
[patroni-0] FATAL:  the database system is starting up
[patroni-0] scope: patroni01localhost:5432 - rejecting connections
[patroni-0] FATAL:  the database system is starting up
```

So far while playing leader pod whack-a-mole it keeps working and releasing the lock.

It currently passes tests in Python 2.7, 3.4, and 3.5, but I'm not sure how to write a test case for this.

**Comment by jberkus** [comment]
@abkfenris  Can you open a PR so that we track this?  The core Patroni crew is at KubeCon right now, so it'll be a few days before we can test as well.
