### ISSUE TITLE
Add pgBouncer auto-config for 2-node systems

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#42]
For systems with 1 master and 1 replica, add pgbouncer auto-configuration for rw and ro database handles.  

This is a TODO item for me.

**Comment by LappleApple** [comment]
@jberkus still planning to do this one, or can we tag it as "Help Wanted"/open to other contributors?

**Comment by jberkus** [comment]
This just isn't terribly relevant anymore, so removing.
