### ISSUE TITLE
haproxy timeout with patroni

### ISSUE THREAD

**Issue by patdenis** [zalando/patroni#421]
hi,
i configure three node (patroni + postgresql + etcd). Then i configure haproxy ( as https://github.com/zalando/patroni/blob/master/haproxy.cfg).
I have a problem in this situation:
1) node A (master) node B (slave) node C (slave);
2) from windows cmd execute psql -h to virtual ip of cluster and keep cmd open and connect to server;
3) disconnect eth0 of node A;
4) cluster move leader to node B and haproxy redirect new connection to correct host (node B);
5) but if i run a simple query on psql connection alredy open in step number 2, the query wait until i reconnect eth0 of node A.

thanks 
Denis

**Comment by CyberDem0n** [comment]
Hi @patdenis.

First of all in our repository we provide just a sample haproxy.cfg to try Patroni in action.
It's very hard to guess what is happening there without running `tcpdump` on the host with haproxy.
I suppose haproxy should really cut old connections as soon as it is not able to reach patroni api with a health-check http request.

>  if i run a simple query on psql connection alredy open in step number 2, the query wait until i reconnect eth0 of node A.

And what happens next? Does your psql gets disconnected or query successfully executed?

**Comment by patdenis** [comment]
it's true, haproxy.cfg is just a sample .cfg file. 
when i connect eth0 of node A, the query is successful. Only when patroni (of node A) check that it is no longer the master and update it's state to slave, then connection is interrupted.


haproxy.cfg:

defaults
 mode                    tcp
    log                     global
    option                  tcplog
    retries                 3
    timeout connect         10s
    timeout check           10s
    maxconn                 500

frontend ft_postgresql
        bind pkgpprepvip:5432
        default_backend bk_db

listen haproxy-monitoring *:80                
    mode http
    stats enable
    stats show-legends
    stats refresh 5s
    stats uri /stats                            
    stats realm Haproxy\ Statistics
    stats admin if TRUE

backend bk_db
    option httpchk
        server postgresql_pg02 pkgpprep2:5433 check port 8008
        server postgresql_pg03 pkgpprep3:5433 check port 8008
        server postgresql_pg06 pkgpprep6:5433 check port 8008

**Comment by patdenis** [comment]
have you ever test this with your haproxy and patroni?
there is some haproxy configuration to modify?
thanks

**Comment by jamessewell** [comment]
Have you tried setting `on-marked-down shutdown sessions` ?

**Comment by patdenis** [comment]
hi,
i add this setting and it works.
thanks so much
