### ISSUE TITLE
Add sample init scripts

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#43]
This is a TODO item for me.

Add sample init/upstart/systemd scripts for the most popular platforms.

**Comment by jberkus** [comment]
Upstart script added.

TODO still:  
* init.d
* systemd
* docker-compose

**Comment by LappleApple** [comment]
@jberkus Still working on this one, or can we tag/Help Wanted + open to other contributors?

**Comment by felipeac** [comment]
Hi guys. How can I help with that?

**Comment by CyberDem0n** [comment]
Hi @felipeac,

Not sure how it is relevant now:
 * we already have systemd service file and upstart script [here](https://github.com/zalando/patroni/tree/master/extras/startup-scripts).
 * also we have [docker-compose.yaml](https://github.com/zalando/patroni/blob/master/docker-compose.yml).

If you can provide something more - pull requests are welcome.

**Comment by martinseener** [comment]
I see that there is already an SysVInit script available for Debian, so this Issue might be closed. We use Debian Jessie without Systemd (installed sysvinit-core after install/before first reboot) and we will check the init script if it works there as well and open a new issue/PR if it does not work, but i think it will ;)

**Comment by CyberDem0n** [comment]
@martinseener, all right, closing it, thank you!
