### ISSUE TITLE
implement patroni-cli

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#44]
In order to implement a number of features for patroni, among them issue #11, we need an actual UI for dynamic adminstration of Patroni systems.  I anticipate having both a CLI and a web UI.  I plan to start with the CLI.

The CLI will be a python program which installs with Patroni.  It will have the following spec:

* must install all patroni libraries
* have a configuration file, patroni-cli.yml, which contains connection information to the DCS
* might be a standard CLI, or might be a full-on command shell.  Opinions?

Call: patroni-cli --config config-file --cluster clustername command [options]

--config is not optional, and contains connection information for the DCS, as well as potentially auth information for the APIs.  Possibly it should be a pure positional argument.

--cluster is optional, and is there mainly for shops which have multiple clusters.  For teams with only one cluster, the clustername could be contained in the config file instead.  The command line paramter supercedes clustername in the config file.

Initially, I expect to implement the following commands:

**status**: prints out cluster status

**status $node**: prints detailed information on the status of a particular node

**list**: lists all nodes

**shutdown $node**: shuts down the named node

**restart $node**: makes node restart

**failover**: initates failover by having the master release the key and reboot read-only

**failover $node**: initiates manual failover per above, but to the named node

**disable $ttl**: disables auto-failover for the whole cluster, with optional TTL 

**resume**: resumes auto-failover for the cluster

**initialize $node**: makes node re-initialize itself

**Comment by jberkus** [comment]
Note:

shutdown, restart, failover and initialize will require additions to the node API.

disable, resume, and failover require new keys in the SIS.

**Comment by feikesteenbergen** [comment]
We have some experience with the click library for building these kind of tools: http://click.pocoo.org/5/

A prototype commandline client for Spilo (Patroni on AWS using Zalando Stups) can be found here:
https://github.com/zalando/spilo/tree/master/spilo_cmd

**Comment by jberkus** [comment]
Hey, can you give me the rights to tag issues?  It would save some time ...

**Comment by feikesteenbergen** [comment]
@jberkus Trying to get you collaborator rights, can't promise anything yet

**Comment by jberkus** [comment]
Ah, issue tagging requires full admin rights?  Never mind then.

**Comment by jberkus** [comment]
Adjusted spec per conversation with Erin today.  Erin is going to be picking this up in order to push the CLI towards completion based on @feikesteenbergen initial code.

**Comment by ariyana** [comment]
Picking up @feikesteenbergen code now, moving forward.

**Comment by jberkus** [comment]
This seems done, no?  Can we close this issue now?

**Comment by LappleApple** [comment]
@feikesteenbergen @alexeyklyukin @CyberDem0n Can we close, as per @jberkus's question?

**Comment by alexeyklyukin** [comment]
No, there are some commands that are not implemented (i.e. disable, resume). I'm not sure about the use-case for that, @ariyana do you still need it?
