### ISSUE TITLE
Habitat

### ISSUE THREAD

**Issue by jamessewell** [zalando/patroni#442]
Has anyone looked at habitat as a DCS? They are implementing PostgreSQL support, but I think it will a long time before they have the same featureset Patroni provides.

Is there a list of required features needed from a DCS?

**Comment by bodymindarts** [comment]
Habitat cannot be used as a DCS as such. The habitat based pg solution can be found [here](https://github.com/starkandwayne/habitat-plans/tree/master/postgresql) and is being worked on very much to get to feature parity with patroni (which is what a lot of it is based on) asap.
