### ISSUE TITLE
The function of closing cluster and opening cluster

### ISSUE THREAD

**Issue by yangshushu** [zalando/patroni#447]
Hello, brother
Recently I was testing Patroni, but I didn't see the patronictl command with the option to turn on the cluster and turn off the cluster. If you are free, you want to add the function of closing cluster and opening cluster.

**Comment by alexeyklyukin** [comment]
@yangshushu Hi, what do you mean by 'turning on' and 'turning off' the cluster? If you need to disable the automatic failover, there is a `pause/resume` mode, documented at https://patroni.readthedocs.io/en/latest/pause.html#user-guide.
Or do you mean connecting to the master via `patronictl`? That is the task better handled by the proper postgres clients, and Patroni has no information on the cluster's external URL.

**Comment by yangshushu** [comment]
@alexeyklyukin Hi,
Be similar to patronictl -c postgres0.yml restart batman
If there are parameters that can  stop or start all nodes of Patroni.
like
 patronictl -c postgres0.yml start batman
 patronictl -c postgres0.yml stop batman
I can use these commands to Unified control  start and stop of the Patroni node.
Maybe I haven't found a better way to  close or start all nodes of Patroni,Please tell me.
thanks.

**Comment by CyberDem0n** [comment]
1. patronictl can't start or stop patroni nodes, because it communicates via REST API running on Patroni nodes. Well, in theory it can stop Patroni and postgres on the node, but it wont be able to start it. 

2. the main purpose and task of Patroni is running high-available cluster and it's very strange desire to stop and start it.

**Comment by dima11221122** [comment]
@CyberDem0n pgbackrest requires to stop cluster in order to restore backup https://pgbackrest.org/user-guide.html#quickstart/perform-restore. What should I do in this case? Pause/resume doesn't help

**Comment by ants** [comment]
Just shut down patroni on all nodes. You will have to use a manual failover to get it to promote afterwards as patroni remembers transaction log position before the restore and will refuse to promote due to `maximum_lag_on_failover`
