### ISSUE TITLE
Does Patroni support Consul ACL via tokens?

### ISSUE THREAD

**Issue by makeittotop** [zalando/patroni#453]
Hi,

I couldn't find a mailing list or an IRC channel so creating this issue, but it's more of a question.

We're in the process of rolling out security to our Core Consul cluster by enforcing strict ACL rules but I'm not sure how Patroni would deal with it.

Does Patroni provide an out-of-the-box support for dealing with consul ACLs via tokens? If not, what's the recommended way to deal with a scenario such as this?

**Comment by CyberDem0n** [comment]
Hi,

Currently it's not possible to put the token into config file, but according to the https://github.com/cablehead/python-consul/blob/master/consul/base.py#L249 one can define CONSUL_HTTP_TOKEN environment variable before starting Patroni and it should work.

**Comment by makeittotop** [comment]
Awesome, that would work. However I'd think loading acl tokens into the local consul agent would be a better way to go. I'll try that first. 

Thanks @CyberDem0n
