### ISSUE TITLE
Can't modify option wal_keep_segments without restarting database

### ISSUE THREAD

**Issue by Vanav** [zalando/patroni#459]
It looks like option `wal_keep_segments` is added as command line argument to Postgres, so I can't modify it with `pg_ctl reload`. Is it possible to modify this option without restarting database?

**Comment by CyberDem0n** [comment]
You are right, it is added as command line argument :(
And there is not a single reason to do that.
Fix is coming.

**Comment by Vanav** [comment]
Thank you.

Maybe some other options from this list need to allow for modification too? I just have no need yet:
```
    CMDLINE_OPTIONS = {
        'listen_addresses': (None, lambda _: False, 90100),
        'port': (None, lambda _: False, 90100),
        'cluster_name': (None, lambda _: False, 90500),
        'wal_level': ('hot_standby', lambda v: v.lower() in ('hot_standby', 'replica', 'logical'), 90100),
        'hot_standby': ('on', lambda _: False, 90100),
        'max_connections': (100, lambda v: int(v) >= 100, 90100),
        'max_wal_senders': (5, lambda v: int(v) >= 5, 90100),
        'wal_keep_segments': (8, lambda v: int(v) >= 8, 90100),
        'max_prepared_transactions': (0, lambda v: int(v) >= 0, 90100),
        'max_locks_per_transaction': (64, lambda v: int(v) >= 64, 90100),
        'track_commit_timestamp': ('off', lambda v: parse_bool(v) is not None, 90500),
        'max_replication_slots': (5, lambda v: int(v) >= 5, 90400),
        'max_worker_processes': (8, lambda v: int(v) >= 8, 90400),
        'wal_log_hints': ('on', lambda _: False, 90400)
    }
```

**Comment by CyberDem0n** [comment]
Other options are pretty important: either they must be the same across all cluster nodes (max_connections, max_wal_senders, max_prepared_transactions and so on) or they are needed to make certain features to work (for example wal_log_hints is needed for pg_rewind).

It's important to pass listen_addresses and port  as command line arguments, otherwise it would be not possible to access postgres if somebody decide to run 'alter system ...' and restart postgres.

In any case, rest of parameters needs a restart to change them.

**Comment by Vanav** [comment]
Thank you.

Is there a way to upgrade Patroni without restarting database?

**Comment by CyberDem0n** [comment]
It depends.

If Patroni is not running in a docker with PID=1 you can do following:

1. Bring cluster into a maintenance mode by executing: `patronictl pause <cluster-name>`
2. Install a new version of Patroni on all nodes
3. Restart Patroni on all nodes
4. Switch off maintenance mode by executing: `patronictl resume <cluster-name>`

If it's running in a docker with PID=1, just do a rolling upgrade starting from replicas.
Before upgrading a last node (master) it makes sense to do a manual failover (switchover): `patronictl failover <cluster-name>`

**Comment by Vanav** [comment]
I'm not PID=1. If I restart Patroni on node with master Postgres, then master Postgres will be restarted too?

**Comment by CyberDem0n** [comment]
> I restart Patroni on node with master Postgres, then master Postgres will be restarted too?

If you enable `maintenance mode` it wont touch running postgres.
