### ISSUE TITLE
After initialization of the primary “acquired session lock as a leader”

### ISSUE THREAD

**Issue by yangshushu** [zalando/patroni#462]
Before  initialization i delete all node etcd directories and pgdata directories.start all etcd node.
when i re initialization of the primary,loop “acquired session lock as a leader”.
and standby report:
2017-06-29 10:20:11,064 INFO: waiting for leader to bootstrap
2017-06-29 10:20:21,062 INFO: Lock owner: None; I am postgresql1
cannot initialize standby.

then

i was try change parameters in etcd.
curl -s -XPATCH -d \
        '{"loop_wait":5,"ttl":5,"maximum_lag_on_failover": 1048576,"postgresql":{"parameters":{"max_connections":"100"}}}' \
        http://192.168.191.137:8008/config | jq .

After the changes have been completed,primary ok.report:
2017-06-29 11:51:00,940 INFO: no action.  i am a secondary and i am following a leader

standby can initialize.

Why does this happen?

**Comment by CyberDem0n** [comment]
> Before initialization i delete all node etcd directories and data directories.restart all etcd node.

Why? Why not just clean up etcd ?

> when i re initialization of the primary,loop “acquired session lock as a leader”.

That means SELECT pg_is_in_recovery() returned false. Postgres was running as master

> i was try change parameters in etcd.
> curl -s -XPATCH -d
> '{"loop_wait":5,"ttl":5,"maximum_lag_on_failover": 1048576,"postgresql":{"parameters":{"max_onnections":"100"}}}'
?http://192.168.191.137:8008/config | jq .

Why you set `ttl` so small?
It MUST be at least twice bigger as `loop_wait`, better three times.
Also, if you change `loop_wait` and `ttl` you have to adjust `retry_timeout` parameter, which is 10 by default.
General rule is: `loop_wait+2*retry_timeout < ttl`

Very small ttl and retry_timeout is very questionable, cluster wont be able to tolerate short network lags.
