### ISSUE TITLE
Update from 1.2.4 to 1.2.5

### ISSUE THREAD

**Issue by patdenis** [zalando/patroni#469]
Hi,
   there is a short guide to update patroni version?
thanks 
Denis

**Comment by uspen** [comment]
Hello! My steps:
0. test test test
1. install new version (dont forget update requirements.txt)
2. turn on maintenance mode: patronictl pause [ your cluster ]
3. restart patroni on all nodes: systemctl restart patroni
4. turn off maintenance mode: patronictl resume [ your cluster ]

**Comment by patdenis** [comment]
ok it's work!
thanks
