### ISSUE TITLE
Both patroni servers start as leader

### ISSUE THREAD

**Issue by MilesBrown** [zalando/patroni#484]
Hi . Both my patroni clusters start as masters. Here are details : 
ETCD cluster conf for two servers:
https://pastebin.com/FdHEuv2C

srv1 :
https://pastebin.com/av7Fm2HR

srv2 : 
https://pastebin.com/qhTNfj80

Log of patroni start on both servers:
https://pastebin.com/FPbRke1z

What I am doing wrong ?

**Comment by CyberDem0n** [comment]
> What I am doing wrong ?

Everything.

1 . First of all you can't run HA etcd on TWO nodes, you need to have THREE etcd nodes.
2. Why you redefined namespace? `namespace: /var/lib/pgsql/pg1.etcd/` `namespace: /var/lib/pgsql/pg2.etcd/`. One Patroni can't find another one because they store their states in different namespaces.
3. `scope` - this is more of less a cluster name and `name` is the node name (using `cluster1` and `cluster2` as node names is very confusing).

**Comment by MilesBrown** [comment]
So I cant have patroni HA cluster with two nodes , it must be minimum three ? Or only etcd must be with three nodes ?

**Comment by CyberDem0n** [comment]
Only etcd must be with three nodes (the same applies to zookeeper and consul).
Once you have etcd cluster you can have postgres cluster with auto failover from two nodes.

**Comment by MilesBrown** [comment]
Thank you, please do not close this issue so I can ask some questions . I'll try now with three nodes

**Comment by CyberDem0n** [comment]
It's not only about three nodes, it's also about wrong Patroni configuration:

```
namespace: /var/lib/pgsql/pg1.etcd/
namespace: /var/lib/pgsql/pg2.etcd/
```

namespace must be the same, otherwise you will get TWO separate Patroni clusters

**Comment by MilesBrown** [comment]
Dear CyberDem0n, I add new etcd server, change namespace to defailt ,still have and error . Template params are not enough I must change also in postgres.conf ?

ETCD cluster members and conf:
https://pastebin.com/R23aJPsS

srv1 :
patroni : https://pastebin.com/1TSEzgDU
start log : https://pastebin.com/QkazqajB
postgresql log : https://pastebin.com/V8xJ1c5C

srv2 : 
patorni : https://pastebin.com/nRwiPezF
start log : https://pastebin.com/zee3ytyB
postgresql log : https://pastebin.com/iK6x8R5V

**Comment by CyberDem0n** [comment]
It seems that postgres was running without Patroni on both servers. And more important it was running as a master in both cases.

On the first server Patroni attached to a running postgres and took the leader lock.
But it's not able to create replication slot because `FATAL:  number of requested standby connections exceeds max_wal_senders (currently 0)`
```
2017-07-25 04:24:17,932 INFO: Selected new etcd server http://10.80.80.195:2379
2017-07-25 04:24:17,936 INFO: establishing a new patroni connection to the postgres cluster
2017-07-25 04:24:18,014 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
2017-07-25 04:24:18,095 INFO: acquired session lock as a leader
2017-07-25 04:24:28,017 INFO: Lock owner: cluster1; I am cluster1
2017-07-25 04:24:28,032 INFO: no action.  i am the leader with the lock
2017-07-25 04:24:38,016 INFO: Lock owner: cluster1; I am cluster1
2017-07-25 04:24:38,025 INFO: closed patroni connection to the postgresql cluster
2017-07-25 04:24:38,025 ERROR: Exception when changing replication slots
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/patroni-1.2.5-py2.7.egg/patroni/postgresql.py", line 1490, in sync_replication_slots
    WHERE slot_name = %s)""", slot, slot)
  File "/usr/lib/python2.7/site-packages/patroni-1.2.5-py2.7.egg/patroni/postgresql.py", line 466, in _query
    raise PostgresConnectionException('connection problems')
PostgresConnectionException: 'connection problems'
```

On the second node Patroni restarted (demoted) postgres .
```
2017-07-25 04:24:32,731 INFO: Selected new etcd server http://10.80.80.196:2379
2017-07-25 04:24:32,735 INFO: establishing a new patroni connection to the postgres cluster
2017-07-25 04:24:32,876 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
2017-07-25 04:24:32,911 INFO: Lock owner: cluster1; I am cluster2
2017-07-25 04:24:32,911 INFO: does not have lock
2017-07-25 04:24:33,926 INFO: closed patroni connection to the postgresql cluster
2017-07-25 04:24:33,963 ERROR: End of HA loop reached without sending keepalive
2017-07-25 04:24:33,963 INFO: demoting self because i do not have the lock and i was a leader
2017-07-25 04:24:33,989 INFO: postmaster pid=2450
< 2017-07-25 04:24:34.004 EDT > LOG:  redirecting log output to logging collector process
< 2017-07-25 04:24:34.004 EDT > HINT:  Future log output will appear in directory "pg_log".
10.80.80.196:5432 - accepting connections
10.80.80.196:5432 - accepting connections
2017-07-25 04:24:35,055 INFO: Lock owner: cluster1; I am cluster2
2017-07-25 04:24:35,055 INFO: does not have lock
```

How it happened that postgres was up and running on both nodes?
Who initialized them and started up?

Just start from scratch:
1. Shut down postgres on both nodes (if it is still running)
2. Clean up data directories (rm -fr /var/lib/pgsql/9.6/data)
3. Clean up cluster state in etcd (patronictl -c cat /etc/patroni/postgres0.yml remove pg1)
4. Start Patroni on both nodes. It will initialize a new cluster and start postgres on one of the nodes. The second node will get pg_basebackup from the first one.

**Comment by MilesBrown** [comment]
I do it , after I try to start patroni on my master machine and postgresql not started 
patroni start log:
https://pastebin.com/wurTm7TN
postgresql log:
https://pastebin.com/czU7LrJe

**Comment by CyberDem0n** [comment]
Ok, now it's clear why it is failing:
```
< 2017-07-25 08:04:53.751 EDT > STATEMENT:  DO $$
    BEGIN
        SET local synchronous_commit = 'local';
        PERFORM * FROM pg_authid WHERE rolname = 'admin';
        IF FOUND THEN
            ALTER ROLE "admin" WITH - C R E A T E R O L E   - C R E A T E D B LOGIN PASSWORD 'admin';
        ELSE
            CREATE ROLE "admin" WITH - C R E A T E R O L E   - C R E A T E D B LOGIN PASSWORD 'admin';
        END IF;
    END;
    $$
```

It happens because configuration is wrong:
```yaml
bootstrap:
  users:
    admin:
      password: admin
      options:
       -createrole
        -createdb
```

You need either remove `users` section completely or fix it:
```yaml
bootstrap:
  users:
    admin:
      password: admin
      options:
      - createrole
      - createdb
```

Formating of yaml is very important...

**Comment by MilesBrown** [comment]
I did it
srv1 : 
https://pastebin.com/1E7vC6nZ
postgres log : https://pastebin.com/kC5aiyvT 

srv2:
https://pastebin.com/DcP99pE7
postgres log : 
https://pastebin.com/qCX6AzUm

When I'm trying to check postgresql status with
`systemctl status postgresql-9.6` its inactive on both servers
```
-bash-4.2$ systemctl status postgresql-9.6 
● postgresql-9.6.service - PostgreSQL 9.6 database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql-9.6.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

```

**Comment by CyberDem0n** [comment]
srv1 is up and running as master according to the patroni and postgres logs.
srv2 is up and running as replica

It's doesn't make sense to check status of postgres with systemctl. Postgres has been started and managed by Patroni.

It should be possible to connect to it as: `psql -h 10.80.80.195`

also you can modify config files to listen on localhost:
```yaml
postgresql:
  listen: 10.80.80.195,127.0.0.1:5432
  connect_address: 10.80.80.195:5432
```

or even:
```yaml
postgresql:
  listen: *:5432
  connect_address: 10.80.80.195:5432
```

**Comment by MilesBrown** [comment]
And for example if i want add some new parametrs for postgresql.conf (ex. shared_buffers,autovacuum and some other performance parameters) I must add in patroni template or directly in postgresql.conf ? And when I add it I must stop and start patroni again ? Or how postgres restart will be ?

**Comment by CyberDem0n** [comment]
There are two ways, either you edit yaml file on every node and send SIGHUP to patroni.

Or your can use [dynamic configuration](https://github.com/zalando/patroni/blob/master/docs/dynamic_configuration.rst#rest-api). It will store configuration parameters in etcd and apply them to all nodes in the cluster.

If you don't want to use curl, you can try https://github.com/zalando/patroni/pull/428 (it's already merged into master).

**Comment by MilesBrown** [comment]
Thank you very much , you are awesome .
