### ISSUE TITLE
Issues when using custom bootstrap

### ISSUE THREAD

**Issue by francobellagamba** [zalando/patroni#494]
When trying to perform a restore using wal-e, on a Spilo image, Spilo tries to modify the template1 database. 
Patroni creates a temprary pg_hba file for use during the custom bootstrap, but it only allows to connect to the "postgres" db ([line 1140 or postgresql.py](https://github.com/zalando/patroni/blame/master/patroni/postgresql.py#L1140)).
In order to allow Spilo to create those extensions, instead of setting up "postgres" as the db, it would be handy to set "all" there.

As far as I could see there is no way to pass that as parameter, am I right?

Ideas?
Thanks

**Comment by CyberDem0n** [comment]
Hi @francobellagamba,

you are right, my level of paranoia was way to high when I did that and access should be open for "all".
We need to fix that and this is a nice opportunity to create a simple pull request :)

Actually I have a question in return.
Have you modified Spilo image to perform custom bootstrap? Can we look on your changes?
Was the backup made from another Spilo cluster? If yes, than it's not really necessary to run post_bootstrap script, all the stuff is already there and Patroni only wants to change superuser and replication passwords.

**Comment by francobellagamba** [comment]
Hey @CyberDem0n 
There you have a PR with this simple change.

The backups I am trying to restore are not from Spilo

Answering your questions, so far the only changes I made to Spilo are to add WABS support for wal-e, and to be able to handle the source of the bootstrapping wal-e restore from a different store than the one setup for backing up the database. 

Also in the plan is to add support to restore from pg_dump backups, probably by hooking it in the post_bootstrap callback.

I can share my current work-in-progress "configure_spilo.py", but haven't tested it yet.

**Comment by CyberDem0n** [comment]
> so far the only changes I made to Spilo are to add WABS support for wal-e, and to be able to handle the source of the bootstrapping wal-e restore from a different store than the one setup for backing up the database.

Right now we are working on similar functionality. We basically have to use-cases:
1. Create a new cluster as exact copy from a running one (script around pg_basebackup).
2. Bootstrap a new cluster using PITR (script around wal-e).

Both of them already have kind of "template" in acceptance tests:
https://github.com/zalando/patroni/blob/master/features/environment.py#L545 -- configuration
https://github.com/zalando/patroni/blob/master/features/backup_create.sh -- supporting scripts
https://github.com/zalando/patroni/blob/master/features/backup_restore.sh

> add support to restore from pg_dump backups, probably by hooking it in the post_bootstrap callback.

Good idea!

**Comment by francobellagamba** [comment]
Nice!
> Create a new cluster as exact copy from a running one (script around pg_basebackup).

This is handy in our workflow, as I plan to allow the dev team to spawn envs on demand, taking data from the prod db

And yeah, the scripts inside features are basically what I am doing, only my scripts are more tightly bound to wal-e, as to not need to download in a temp disk all the wals before applying them.
