### ISSUE TITLE
Run sql init script on startup.

### ISSUE THREAD

**Issue by skw02** [zalando/patroni#495]
Hey, is there a possibiltity to add an init sql script to your current docker file, which is executed on docker container startup to create some databases?

**Comment by CyberDem0n** [comment]
Sure, but it's a little bit more flexible, Patroni could execute your shell script or binary after running initdb:
```yaml
bootstrap:
  post_init: /path/to/your/script_or_binary
```

The script receives a connection string URL (with the cluster superuser as a user name). The PGPASSFILE variable is set to the location of pgpass file.

Documentation: http://patroni.readthedocs.io/en/latest/SETTINGS.html#bootstrap-configuration
Example of script: https://github.com/zalando/spilo/blob/master/postgres-appliance/post_init.sh

**Comment by srflaxu40** [comment]
How would you add this to pg operator?

**Comment by julian-perge** [comment]
> Sure, but it's a little bit more flexible, Patroni could execute your shell script or binary after running initdb:
> 
> ```yaml
> bootstrap:
>   post_init: /path/to/your/script_or_binary
> ```
> 
> The script receives a connection string URL (with the cluster superuser as a user name). The PGPASSFILE variable is set to the location of pgpass file.
> 
> Documentation: http://patroni.readthedocs.io/en/latest/SETTINGS.html#bootstrap-configuration Example of script: https://github.com/zalando/spilo/blob/master/postgres-appliance/post_init.sh

Is it possible to have the shell commands in `post_init` without needing a script? I'm trying to figure out how to run this single command for creating a database after the fact, but the documentation is difficult to understand in this regard without some examples. 

e.g.
```
post_init: su postgres -c "psql -c 'SET AUTOCOMMIT ON; CREATE DATABASE basic WITH OWNER=admin;'"
```

Is the path to the post_init script file supposed to already be in the container? I'm really confused on how this is supposed to look like setup wise.

`The script receives a connection string URL (with the cluster superuser as a user name).`
Can you please give an example of how this might look?
