### ISSUE TITLE
Demoted node does not start on fail over when using synchronous mode

### ISSUE THREAD

**Issue by akissa** [zalando/patroni#504]
I am testing 3 nodes in a cluster with  synchronous mode.

```
patronictl -c /etc/patroni/baruwa.yml list baruwa
+---------+------------------------------+--------------+--------+---------+-----------+
| Cluster | Member                       | Host         |  Role  |  State  | Lag in MB |
+---------+------------------------------+--------------+--------+---------+-----------+
| baruwa  | db.home.topdog-software.com  | 192.168.1.15 | Leader | running |       0.0 |
| baruwa  | db2.home.topdog-software.com | 192.168.1.33 |        | running |       0.0 |
| baruwa  | db3.home.topdog-software.com | 192.168.1.34 |        | running |       0.0 |
+---------+------------------------------+--------------+--------+---------+-----------+
```

When i trigger a manual failover using `patronictl -c /etc/patroni/baruwa.yml failover baruwa` The fail over happens and a different host takes over as the leader. However the previous leader is not able to startup postgresql as the `synchronous_standby_names` option is not removed from `postgresql.conf` file.

If i stop the patroni process and start it up again, the `postgresql.conf` file is updated removing the `synchronous_standby_names` option allowing postgresql to startup and rejoin the cluster.

**Comment by CyberDem0n** [comment]
Hi @akissa, thank you for your finding.
It's very interesting use-case we didn't thought about :(
Will prepare a fix soon.

**Comment by CyberDem0n** [comment]
Actually problem is even worse than that.
Synchronous replication didn't worked completely in your case.

https://www.postgresql.org/docs/9.6/static/runtime-config-replication.html#RUNTIME-CONFIG-REPLICATION-MASTER tells:
```
Note: Each standby_name should have the form of a valid SQL identifier, unless it is *.
You can use double-quoting if necessary.
```

Since your member names containing periods and dashes, they must me quoted.

**Comment by uspen** [comment]
Yes, names "Member" with sync standby MUST be SQL syntax. I use
hostname: nodeXX.db.example.com
Member in Patroni: nodexXX

**Comment by CyberDem0n** [comment]
@uspen, yep, but https://github.com/zalando/patroni/pull/505 will fix it and will make it possible to use nodeXX.db.example.com as member name

**Comment by akissa** [comment]
@CyberDem0n #505 does fix the issue for me.

**Comment by akissa** [comment]
@CyberDem0n Thank you.
