### ISSUE TITLE
"system ID mismatch" after restored a backup from different cluster

### ISSUE THREAD

**Issue by xcompass** [zalando/patroni#510]
When I restored a backup from another cluster to a new cluster, patroni refused to start with the following error message:

```
2017-08-28 20:15:55,598 CRITICAL: system ID mismatch, node postgres-recovery-patroni-recovery-0 belongs to a different cluster: 6459238215155531824 != 6414232139510366258
2017-08-28 20:15:56,063 INFO exited: patroni (exit status 1; not expected)
```

Is there a way to get around this when doing the restore? Thanks.

**Comment by uspen** [comment]
Your DEV cluster have old config. patronictl remove CLUSTER dont remove all keys
```
curl -s -XDELETE "http://etcdserver:2379/v2/keys/patch_to_cluster/?recursive=true"
```

**Comment by uspen** [comment]
and remove patroni.dynamic.json from dev cluster PGDATA

**Comment by alexeyklyukin** [comment]
If this is a completely new cluster and the only node to join is the one you have restored then you can just hack the sysid stored in the /service/$cluster/initialize key to match the one from your new node (6414232139510366258). 

There is a new feature in Patroni 1.3 called 'custom bootstrap' that allows bootstrapping a new cluster from the base backup of another one, effectively cloning the original cluster. The description is here: http://patroni.readthedocs.io/en/latest/replica_bootstrap.html?highlight=bootstrap, you can find a simple script that can be used a a template to bootstrap from the base backup here: https://github.com/zalando/patroni/blob/master/features/backup_restore.sh

**Comment by CyberDem0n** [comment]
> When I restored a backup from another cluster to a new cluster

Can you please be more specific?
How you created the new cluster?
How did you restored a backup?

**Comment by xcompass** [comment]
I was using helm chart in https://github.com/kubernetes/charts/tree/master/incubator/patroni and using barman for backup and restore.

@alexeyklyukin Thanks. I was able to "hack" it by set the /service/$cluster/initialize key to the old cluster id and patroni was able to start without any error.

**Comment by ziXet** [comment]
> I was using helm chart in https://github.com/kubernetes/charts/tree/master/incubator/patroni and using barman for backup and restore.
> 
> @alexeyklyukin Thanks. I was able to "hack" it by set the /service/$cluster/initialize key to the old cluster id and patroni was able to start without any error.

Hi, would you please explain how do you do this hack? I'm using patroni on kubernetes

**Comment by anikin-aa** [comment]
@ziXet in case of k8s patroni stores cluster info in config maps. You should just remove initialize key from annotations.

**Comment by leefeipo** [comment]
> [@ziXet](https://github.com/ziXet)对于 Kubernetes，Patroni 会将集群信息存储在配置映射中。您只需从注解中移除初始化键即可。

I mean same problem, how to set?
