### ISSUE TITLE
Github releases since 1.1 lack release notes

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#516]
Looking at https://github.com/zalando/patroni/releases, the "Latest Release" (https://github.com/zalando/patroni/releases/latest) is claimed to be `v1.1`, probably because earlier releases only have a tag commit, and no release notes attached to them.

I understand that release notes are available in `docs/releases.rst`, but it would be good to also include them in the Github release pages.

And if that doesn't advance the "Latest Release" tag to the latest release, that one should get updated as well.

**Comment by CyberDem0n** [comment]
Does it look better now (I mean https://github.com/zalando/patroni/releases now contains links to docs/releases.rst).

Don't really want to convert rst into md.

**Comment by mbanck** [comment]
Yeah, I think that's fine, everything else would be some boring task to make that github releases page look nicer, the release notes are now easily accessible.
