### ISSUE TITLE
Data loss when doing a switchover using async replication?

### ISSUE THREAD

**Issue by kagkarlsson** [zalando/patroni#520]
When running a cluster and using async replication, do Patroni ensure that no data is lost when doing a switchover? 
If yes, how does that work?
If no, how do you suggest a maintenance switchover is done when using async replication?

(Am opening this issue as a `question` because I found no other forum to ask about these things, e.g. IRC, google groups, mailing list..?)

**Comment by alexeyklyukin** [comment]
Normally, the replica that promotes makes sure it restores all available WAL segments before proceeding with promotion (this is done by PostgreSQL), and the master is also archiving all WAL segments and waiting for the streaming replicas to get up-to-date during its shutdown (also done by PostgreSQL). Therefore, as long as this is a controlled switchover and the former master is available during it there should not be any data loss.

It is rather different in the case of the failover, when the former master goes away unexpectedly. There, you cannot guarantee that all data is shipped to the replicas before the promotion, however, Patroni prevents any replica to promote that is more than  `maximum_lag_on_failover` bytes behind the last reported master position.

**Comment by kagkarlsson** [comment]
Thank you for your quick answer!

Am assuming switchover works like this:
1. Issue "normal" shutdown of old master (=> PG allow archiving and replication are to complete before shutdown)
2. Patroni triggers a "manual" promote of the replica
3. Re-initialize old master as replica

Now this is a bit contrived, but what if syncing the replica or archiving is taking a long time to complete. Is there something preventing the regular Patroni loop from doing a "hmm I see the master is down/unavailable, lets promote the replica"?

**Comment by alexeyklyukin** [comment]
No, it doesn't work this way. Patroni on the replica will never make a decision to promote while the leader lock is present. Patroni on the master that is shutting down will not relinquish this lock until it makes sure the master is not running (by checking its PID among other things). 

BTW, the 3rd step is actually not required in most cases, since the former master would start up as a replica and rejoin the new master (in case there are some issues we could use pg_rewind in order to remove the discrepancy).

**Comment by kagkarlsson** [comment]
Ok, thank you for the clarification!

**Comment by cbandy** [comment]
> Therefore, as long as this is a controlled switchover and the former master is available during it there should not be any data loss.

Is `patronictl failover` a controlled switchover?

**Comment by alexeyklyukin** [comment]
it is.

**Comment by mbanck** [comment]
Maybe an alias `switchover` could be added for that to make it clearer, though on the other hand, doing a manual failover (which is the case when running `patronictl` is usually understood to be a switchover I think.
