### ISSUE TITLE
Consul: lock is lost on 7-10 s network issues

### ISSUE THREAD

**Issue by Vanav** [zalando/patroni#522]
I have Patroni and Consul Server on the same server db1 (192.168.241.17), and the same setup for slave server db2 (192.168.241.18). db1 has a lock. If I have short network issues on db1, then Consul after 7 seconds removes this node from the list, and deletes all the locks, and failover happens.

How can I improve the situation and increase timeout to, say, 30-60 s?

I've [asked question in Consul maillist](https://groups.google.com/forum/#!topic/consul-tool/YMa4J40qgM0), and they suggested to associate Session with a TTL based check, and not to bind to “serfHealth”. So, lock will not be lost, if node db1 will be removed.

Consul on db2:
```
2017/09/13 17:29:15 [ERR] memberlist: Failed fallback ping: read tcp 192.168.241.18:34928->192.168.241.17:8301: i/o timeout
2017/09/13 17:29:15 [INFO] memberlist: Suspect db1.aes128.com has failed, no acks received
2017/09/13 17:29:18 [INFO] memberlist: Marking db1.aes128.com as failed, suspect timeout reached (2 peer confirmations)
2017/09/13 17:29:18 [INFO] serf: EventMemberFailed: db1.aes128.com 192.168.241.17
2017/09/13 17:29:18 [INFO] consul: Removing LAN server db1.aes128.com (Addr: tcp/192.168.241.17:8300) (DC: dc1)
2017/09/13 17:29:19 [ERR] memberlist: Failed fallback ping: read tcp 192.168.241.18:34941->192.168.241.17:8301: i/o timeout
2017/09/13 17:29:19 [INFO] memberlist: Suspect db1.aes128.com has failed, no acks received
2017/09/13 17:29:24 [INFO] serf: EventMemberLeave (forced): db1.aes128.com 192.168.241.17
2017/09/13 17:29:24 [INFO] consul: Removing LAN server db1.aes128.com (Addr: tcp/192.168.241.17:8300) (DC: dc1)
```

Patroni on db2:
```
2017-09-13 17:29:14,488 INFO: Lock owner: db1; I am db2
2017-09-13 17:29:14,488 INFO: does not have lock
2017-09-13 17:29:14,504 INFO: no action.  i am a secondary and i am following a leader
2017-09-13 17:29:20,761 WARNING: request failed: GET http://192.168.241.17:8008/patroni (HTTPConnect
ionPool(host='192.168.241.17', port=8008): Read timed out. (read timeout=2))
server signaled
server promoting
2017-09-13 17:29:20,979 INFO: cleared rewind state after becoming the leader
2017-09-13 17:29:21,006 INFO: promoted self to leader by acquiring session lock
2017-09-13 17:29:28,732 INFO: Lock owner: db2; I am db2
2017-09-13 17:29:28,803 INFO: no action.  i am the leader with the lock
```

**Comment by CyberDem0n** [comment]
You definitely have some network problems, but Patroni is doing the best it could do.
I don't know very much about Consul configuration and operations, but in Patroni you can try to bump `ttl` and `retry_timeout` values.

For example you can set ttl=60 and retry_timeout=25.
General rule is: loop_wait+2*retry_timeout <= ttl.
loop_wait by default is 10 seconds.

You can change these parameters with patronictl:
```bash
$ patronictl edit-config -s 'ttl=60' -s 'retry_timeout=25' your_cluster_name
```

In this case leader key will expire only after 60 seconds and Patroni will retry consul requests during 25 seconds. That means if network is restored during 25 seconds master will not be demoted.

**Comment by Vanav** [comment]
I have lost network on db1 for ~10 seconds, and I want to not loose a lock in this case. I had retry_timeout: 30 and ttl: 120 (already increased defaults). I was wondering why failover occurred.
17:29:14 - all is ok, no errors.
17:29:21 - promoted self to leader by acquiring session lock.
Why so fast?

I have an idea that simply lock was deleted:
17:29:15 - Consul node db1 lost network connection. It holds lock session.
17:29:18 - Consul node db1 left the cluster (Consul is very aggressive here to keep cluster up to date).
Lock session has a property "serfHealth" (default) and TTL (60 s, half of 120 s). Because of "serfHealth" property, if node is lost, its sessions are lost too, and lock is deleted.

So, some ideas:
1) I host Patroni and Consul Server on one machine. If I'll use Consul Client here, will it change anything? I'm not sure, because seems that all consul nodes are health checked by serf.
2) Remove default "serfHealth" from Patroni session. Any side effects?
3) Connect to Consul Node over network to other machine. Seems this is not the way Consul should work.
4) Tune Consul Serf timeouts: I've tried this and [discussed on Consul maillist](https://groups.google.com/forum/#!topic/consul-tool/YMa4J40qgM0), but seems keeping Consul node list up to date is important for Consul and better to not break anything here.

**Comment by CyberDem0n** [comment]
Please try following patch:
```diff
diff --git a/patroni/dcs/consul.py b/patroni/dcs/consul.py
index 50ab386..583f2e3 100644
--- a/patroni/dcs/consul.py
+++ b/patroni/dcs/consul.py
@@ -189,7 +189,7 @@ class Consul(AbstractDCS):
         ret = not self._session
         if ret:
             self._session = self._client.session.create(name=self._scope + '-' + self._name,
-                                                        lock_delay=0.001, behavior='delete')
+                                                        checks=[], lock_delay=0.001, behavior='delete')
         self._last_session_refresh = time.time()
         return ret
```

**Comment by CyberDem0n** [comment]
@Vanav any news on that?

**Comment by Vanav** [comment]
CyberDem0n, thank you. I'm using this fix in producton, and found no issues so far. But I've not done any special tests.

**Comment by Vanav** [comment]
I've done some tests, to keep leader lock till TTL, following requirements should met:
1. New setting `checks` for Consul in patroni.yml should be empty:
```
consul:
  host: localhost:8500
  checks: []
```
2. There should be no Consul Server on Patroni nodes. The preferred configuration is to run Consul Client on Patroni node, this client will own a leader lock without serfHealth, and this lock will survive if this Consul Client will be offline for a long time.

Alternative configuration (not tested) is to connect to Consul on other node (not localhost). But Consul prefers to run Client on every node.

Incorrect configuration: if you run one of Consul Servers on the same node as Patroni and Postgres, then lock will be lost in 5 seconds after this node will go offline.

Notice: Consul v1.0.0 and v.1.0.1 had a bug preventing creation a session without serfHealth (https://github.com/hashicorp/consul/issues/3732).
