### ISSUE TITLE
default value for EDITOR env variable?

### ISSUE THREAD

**Issue by kostiantyn-nemchenko** [zalando/patroni#532]
Hi, 

While playing with patronictl options and perusing `invoke_editor()` in `patroni/ctl.py`, I noticed that [`editor_cmd`](https://github.com/zalando/patroni/blob/32b0768631fcd1f8a75b69627e225a19bece4923/patroni/ctl.py#L954) variable doesn't have a default value.
I guess it will be more user-friendly to have a preset value rather than raising `PatroniCtlException` (e.g. Mercurial and IPython projects are using vi as default text editor under Linux/Unix)

Thank you.

**Comment by ants** [comment]
I didn't set it because I was worried newbies would get stuck in vi.

It looks like on debian there is also `/usr/bin/editor` that can be set via `update-alternatives`. Maybe if `EDITOR` is not set we should try `editor` and then `vi`.
