### ISSUE TITLE
Logical Replication

### ISSUE THREAD

**Issue by schmitch** [zalando/patroni#538]
It would be cool if patroni would also feature some kind of logical replication.

**Comment by ants** [comment]
Do you have a particular use case in mind that you want this for? I'm asking because different people have very different ideas what this feature means.

**Comment by jberkus** [comment]
I'd suggest starting with support for whole-database logical replication in Postgres 10.  That's the simplest case, and importantly allows fulfilling the requirements of replication-based upgrades.

**Comment by schmitch** [comment]
yep actually the first and simplest use case would be to have whole-database replication, useful for database upgrades so patroni can just add a bunch of new servers via logical replication.

What might be out of scope is that for database upgrades the SEQUENCES might need to be updated to the current values. Before any client could use the database as a new master.

**Comment by alexeyklyukin** [comment]
The problem so far is that logical replication is in a way incompatible with the main function of the Patroni, namely doing the failovers, since after the failover the whole logical replication needs to be reinitialized.

**Comment by schmitch** [comment]
well yeah logical replication is incompatible as of now since the replication is setup via sql commands and not via config and that sequences are not replicated. but I think it would still be a great addition to patroni.

I mean the best addition would be to make patroni aware of postgresql version so that one could use patroni to also upgrade postgresql without any downtime

something like:
```
patroni (old-version pg) < logical replication > patroni (new-version pg)
```

and an api endpoint where one can actually change the master to the new-version postgresql.
I guess that's the most feasible thing what people want to do with logical replication. version upgrades.

I don't think that zalando or many other users will want to use postgresql only with logical replication, especially since there is no support for cascading logical replication.

**Comment by jberkus** [comment]
Yah, pretty much.  With the state of logical replication right now, it's only useful in an HA sense for rolling upgrades.  So the sequence would go like this:

1. PG 10 cluster.

2. Upgrade to 11.

3. Create new PG 11 server.

4. Start logical replication of all non-system databases to new server.

5. Create binary replicas of 11 server.

6. Fail over to 11 master.

7. Disable logical replication on 11 master.

8. Shut down 10 cluster.

Aside from a lot of skut work with commands, the problems with making this work are:

a) if disabling the logical rep fails

b) sequences

c) fragility (for example, user pushes schema change in middle of process)

**Comment by jberkus** [comment]
I *do* think there is a strong need for a "Logical replication manager", but that would effectively be a separate piece of software from Patroni.  It might interact with Patroni (e.g. to get a list of nodes), but since it would not be focused on HA, it wouldn't be patroni at its core.

**Comment by cobolbaby** [comment]
Any news?

**Comment by Wolfsrudel** [comment]
This could be used for a migration and upgrade of a existing postgres cluster to Patroni.

Meaning
```
pg10existing -> Patroni-standby -> promote
```
I have thought about this already but don't know if it will work.

**Comment by CyberDem0n** [comment]
Logical replication has a lot of limitations and therefore could not be used for implementing HA.

**Comment by amadhaka** [comment]
i have to use wal2json for which logical rpelication is pre step, is it possible to do this setup with patroni ?
