### ISSUE TITLE
registry.opensource.zalan.do/acid/patroni:1.0-SNAPSHOT fails to start 

### ISSUE THREAD

**Issue by IJOL** [zalando/patroni#539]
Hi, I have trying to start a cluster using dev_patroni_cluster.shm wich in turns use the said image to start, etcd, proxy , started as noticed, but postgres cluster ones, give the message below in the logs for the container:

/entrypoint.sh: line 99: /patroni/postgres.yaml: Permission denied
Traceback (most recent call last):
  File "/patroni.py", line 6, in <module>
    main()
  File "/patroni/__init__.py", line 173, in main
    return patroni_main()
  File "/patroni/__init__.py", line 140, in patroni_main
    patroni = Patroni()
  File "/patroni/__init__.py", line 14, in __init__
    from patroni.config import Config
  File "/patroni/config.py", line 11, in <module>
    from patroni.postgresql import Postgresql
  File "/patroni/postgresql.py", line 5, in <module>
    import psutil
ImportError: No module named psutil

ANy help wil be appreciated, 
thanks in advance

Saludos, 
IJOL

**Comment by CyberDem0n** [comment]
Hi @IJOL,

Just build your own image.
And actually I would suggest to use docker-compose to start the cluster, instead of dev_patroni_cluster.sh.

```
docker build -t patroni .
docker-compose up
```

**Comment by hjacobs** [comment]
@CyberDem0n why is there no "official" Patroni Docker image (or maybe there is, but why should users build their own?)?

**Comment by IJOL** [comment]
Ok, built my own and eveyrthing mostly works, y can contribute a docker-composer file for docker swarm, that works, the only big caeat is the dependency on node names, it's not easy to fix nor predict the name of the conbtainer that the service finally builts, so after restart, last leader name is lost and there are new names for evrything, i think i can simply delete the corresponding value on etcd, tht i run externally, from another container,  but i not sure if this approach is secure/suffcient,,


Any help wil be appreciated..

Saludos, IJOL

**Comment by IJOL** [comment]
Ok, working, and restarting correctly in docker swarm, works like a charm, dismiss my comment on names, was my fault not pointing correctly my persistent data volume, i was plugin into standard, var/lib/postgresql and patroni is using /data/cluster-name so...

Many thanks for this great work,

**Comment by nicodmf** [comment]
@IJOL, can you share your swarm/docker-compose file, i should install a postgresql cluster on a swarm, and would like use a tested template rather than reinvent the well
