### ISSUE TITLE
system ID mismatch, node belongs to a different cluster - after reboot

### ISSUE THREAD

**Issue by ClaudiuPID** [zalando/patroni#541]
Hi,

I ended up with a node out of the cluster after a minor postgresql upgrade and system reboot.
I did this before in the past but never with patroni 1.2.5.

Error:
```
2017-10-10 11:20:44,915 CRITICAL: system ID mismatch, node sql2 belongs to a different cluster: 6283810682861444259 !=
2017-10-10 11:20:44,931 ERROR:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/__init__.py", line 134, in patroni_main
    patroni.run()
  File "/usr/local/lib/python3.5/dist-packages/patroni/__init__.py", line 110, in run
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 946, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.5/dist-packages/patroni/ha.py", line 903, in _run_cycle
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 329, in wrapper
    retval = func(self, *args, **kwargs) is not None
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 511, in delete_leader
    return self._client.delete(self.leader_path, prevValue=self._name)
  File "/usr/local/lib/python3.5/dist-packages/etcd/client.py", line 584, in delete
    self.key_endpoint + key, self._MDELETE, params=kwds)
  File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/etcd.py", line 211, in api_execute
    return self._handle_server_response(response)
  File "/usr/local/lib/python3.5/dist-packages/etcd/client.py", line 928, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/usr/local/lib/python3.5/dist-packages/etcd/__init__.py", line 304, in handle
    raise exc(msg, payload)
etcd.EtcdCompareFailed: Compare failed : [sql2 != sql1]
```

I found this: https://github.com/zalando/patroni/issues/438
Edited that file, indented return to proper position but still the same issue.
Any ideas on how to debug this?

Thank you.

**Comment by CyberDem0n** [comment]
Hi,

without looking on your config file it's hard to say anything, but I think either postgresql.data_dir points to the wrong place or Patroni can't find postgres binaries.

**Comment by ClaudiuPID** [comment]
Config:
```
scope: sqlmcp
name: sql2
restapi:
  listen: 10.10.0.71:8008
  connect_address: 10.10.0.71:8008
etcd:
  host: etcd0.local.tld:2379
  discovery_srv: local.tld
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: True
      parameters:
        archive_mode: "on"
        wal_level: hot_standby
        max_wal_senders: 10
        wal_keep_segments: 32
        archive_timeout: 1800s
        max_replication_slots: 10
        hot_standby: "on"
        wal_log_hints: "on"
        config_file: /var/lib/postgresql/data/sql2mcp/postgresql.conf
        max_connections: 1000
    pg_hba:
    - local all all  trust
    - host all all 10.10.0.0/21 md5
    - hostssl all all 10.10.0.0/21 md5
    initdb:
    - encoding: UTF8
    - lc-collate: en_US.UTF-8
    - lc-ctype: en_US.UTF-8
postgresql:
  listen: 10.10.0.71:15432
  connect_address: 10.10.0.71:15432
  data_dir: /var/lib/postgresql/data/sql2mcp
  pgpass: /tmp/pgpass0
  authentication:
    pg_rewind:
      username: postgres
      password: ***
    replication:
      username: replicator
      password: ***
      network: 10.10.0.0/21
    superuser:
      username: postgres
      password: ***
    admin:
      username: admin
      password: ***
  parameters:
    unix_socket_directories: '.'
    archive_command: mkdir -p /var/lib/postgresql/wal_archive && test ! -f /var/lib/postgresql/wal_archive/%f && cp /var/lib/postgresql/data/sql2mcp/%p /var/lib/postgresql/wal_archive/%f
    shared_buffers: 10GB
    effective_cache_size: 32GB
    work_mem: 12582kB
    maintenance_work_mem: 2GB
    min_wal_size: 80MB
    max_wal_size: 1GB
    checkpoint_completion_target: 0.5
    wal_buffers: 16MB
    default_statistics_target: 100
  recovery_conf:
    restore_command: cp /var/lib/postgresql/wal_archive/%f /var/lib/postgresql/data/sql2mcp/%p
    archive_cleanup_command: '/var/lib/postgresql/omnipitr/bin/omnipitr-cleanup -l /var/log/omnipitr/cleanup.log -a /var/lib/postgresql/wal_archive/ %r'
tags:
    nofailover: False
    noloadbalance: False
    clonefrom: False
```

All postgresql binaries are present and datadir is present.
Having an option in patronictl for health check would be nice. Checking needed binaries, access to etcd or whatever is configured. But I guess that is something that some one new to this would need :)

I tried with: ```bin_dir: /usr/lib/postgresql/9.5/bin/```, no change.
And after I tried with: ```data_dir: data/sql2mcp```, patroni started but in logs I have: ```pg_basebackup: could not create directory "data/sql2mcp": Permission denied```.

So it looks like it is related to data dir indeed. Will dig further.

**Comment by ClaudiuPID** [comment]
I renamed the current data dir and now it is creating a replica from master.
No idea how this could of happened after a minor postgresql upgrade. Still using 9.5 just as before and I am sure I did this before in the past but with an older patroni version.

**Comment by bradnicholson** [comment]
I'm seeing instances of the same error - 

`2017-12-04 12:14:41,012 CRITICAL: system ID mismatch, node postgresql82_131 belongs to a different cluster: 6334130145219842093 != 6495656546632441982`

In my case, I am using a custom bootstrap method which is restoring a physical backup (created with pg_basebackup), performing a pg_upgrade on the backup and then subscribing a replica via the default pg_basebackup subscription.  

The master and replica pg_controldata both show the same system ID 
`Database system identifier:           6495656546632441982`

Etcd has a different system ID:

```
{
  "node": {
    "createdIndex": 3872,
    "modifiedIndex": 3873,
    "value": "6334130145219842093",
    "key": "/patroni/postgresql/initialize"
  }
```

**Comment by bradnicholson** [comment]
I've done some more testing, and it looks like a race condition somewhere.  I'm feeding the same backup through an automated deployment pipeline (following the same steps).  Sometimes it deploys cleanly, sometimes it comes up with the system ID mismatch error.

My restore/upgrade process does the following

1. copy the backup to the host 
1. decompress the backup to a staging data dir (not the PG data dir Patroni uses)
1. start Patroni
1. Patroni custom bootstrap script then copies the data from the staging area to the PG data dir (that Patroni knows about) and then runs pg_upgrade on it.

I'm speculating that there is a race condition where Patroni can get the System ID before or after the PG upgrade runs and changes it.

**Comment by CyberDem0n** [comment]
> In my case, I am using a custom bootstrap method which is restoring a physical backup (created with pg_basebackup), performing a pg_upgrade on the backup and then subscribing a replica via the default pg_basebackup subscription.

It looks like very complicated setup. I would like to see your patroni.yaml and scripts for custom bootstrap and `post_bootstrap/post_init`.

But I can guess what is going on: after a custom bootstrap script has been executed patroni starts postgres and later updates initialize key with the value of `Database system identifier` (of the original cluster). In order to avoid running `pg_controldata` all the time patroni caches value of cluster sysid in memory, because nobody replaces data directory in runtime.

pg_upgrade requires you to run `initdb`, which generates a new `Database system identifier`, dumps/restores schemas and copying (or relinking) datafiles to a new directory. Also pg_upgrade starts and stops original cluster. Basically after pg_upgrade you get TWO data directories, the first one is original and another - upgraded to the new version.

What happens next? Do you somehow rename directories in order to give the new one to Patroni? But this is absolutely new cluster with the new sysid. And moreover, it requires a new postgres binaries (from another major version).

The only possible way to do a major upgrade right now is:
1. stop patroni
2. pg_upgrade
3. update patroni yaml
4. remove initialize key from DCS or wipe complete cluster state from DCS. The second one could be achieved by running `patronictl remove <cluster-name>`
5. may be copy `patroni.dynamic.json` from old data dir to the new one (if you wiped cluster state on previous step). It will help you to retain some postgres parameters you set before.
6. start patroni

**Comment by bradnicholson** [comment]
For our use case, since we are doing the pg_upgrade on newly provisioned DB's only, the simplest approach is to upgrade the data before Patroni sees it.

**Comment by c4milo** [comment]
I was using pgbackrest and ran into this problem as well. To fix it, I deleted the `initialize` key from Consul.

**Comment by buluxan** [comment]
> I was using pgbackrest and ran into this problem as well. To fix it, I deleted the `initialize` key from Consul.

hi c4milo could you pls share with us how to delete `initialize` key from consul , 
because i got same problem , i see in my logs liks this : 

2020-02-12 18:11:08,133 CRITICAL: system ID mismatch, node odoo-psql2 belongs to a different cluster: 6792149796479795020 != 6792507679744947325
2020-02-12 18:11:08,674 INFO: Lock owner: odoo-psql; I am odoo-psql2

**Comment by caseyallenshobe** [comment]
I doubt that you want to delete the key from Consul, as it reports that there is an existing lock owner (odoo-psql).  The initialize key comes from PostgreSQL, and can be seen using the `pg_controldata` command.  All instances in your Patroni cluster should have the same ID, which will be the case if the second node was not initialized as a separate database but rather created as a copy of the first.

```
# /usr/lib/postgresql/12/bin/pg_controldata -D /var/lib/postgresql/12/main | grep "Database system identifier"
Database system identifier:           6792036218013953695
```

**Comment by algoritmsystems** [comment]
1.list keys in etcd: etcdctl --endpoints=http://host:2379 get / --prefix --keys-only

2.delete old cluster keys: etcdctl --endpoints=http://host:2379 del /db/your_cluster_path --prefix

3.systemctl restart patroni

4.journalctl -u patroni
