### ISSUE TITLE
Patroni does not perform failover if master lost data directory

### ISSUE THREAD

**Issue by ainlolcat** [zalando/patroni#542]
We are migrating from 1.2 to 1.3.4 and one of our tests fails - we removed data directory and are expecting failover to replica and master reinitialization. But with new version master detects empty dir, releases key and .. wait for leader to bootstrap. Meanwhile replica is considering master as "master" and wait for master too. 
From master: 

> 2017-10-11 11:35:27,431 ERROR: get_postgresql_status
> Traceback (most recent call last):
>   File "/patroni/patroni/api.py", line 405, in get_postgresql_status
>     retry=retry)[0]
>   File "/patroni/patroni/api.py", line 381, in query
>     return retry(self.server.query, sql, *params)
>   File "/patroni/patroni/utils.py", line 259, in __call__
>     return func(*args, **kwargs)
>   File "/patroni/patroni/api.py", line 452, in query
>     raise e
> OperationalError: could not open file "base/12404/2600": No such file or directory
> 
> 2017-10-11 11:35:27,433 INFO: released leader key voluntarily as data dir empty and currently leader
> ...
> 2017-10-11 11:35:37,416 INFO: Lock owner: None; I am node1
> 2017-10-11 11:35:37,420 INFO: waiting for leader to bootstrap

From slave:

> 2017-10-11 14:20:50,223 INFO: Got response from node1 http://10.129.1.63:8008/patroni: {"state": "unknown", "database_system_identifier": "6475561736777527351", "role": "master", "patroni": {"scope": "common", "version": "1.3.4"}}
> 2017-10-11 14:20:50,262 WARNING: Master (node1) is still alive
> 2017-10-11 14:20:50,267 INFO: following a different leader because i am not the healthiest node

I suppose that replica cannot promote itself because broken master declares wrong status. Broken master declares wrong status because it released key but never update `postgresql.role` value.

**Comment by CyberDem0n** [comment]
Good catch, will fix it tomorrow.

**Comment by ainlolcat** [comment]
Thank You. Failover works now but ex-master was not able to start correctly after bootstrap. Looks like this is because postgresql process was not killed before bootstrap and in result we have logs filled with `FATAL:  could not receive data from WAL stream: ERROR:  requested starting point 0/A000000 is ahead of the WAL flush position of this server 0/9002FA8`. Looks like after failover patroni tries to start postgresql several times but each time it fails with `FATAL:  could not create any TCP/IP sockets` because previous process still running. Log looks like this: 

> 2017-10-13 14:34:32,116 INFO: Lock owner: node1; I am node1
> 2017-10-13 14:34:32,122 INFO: Leader key released
> 2017-10-13 14:34:32,127 INFO: released leader key voluntarily as data dir empty and currently leader
> 2017-10-13 14:34:32,128 ERROR: get_postgresql_status
> ...
> 2017-10-13 14:34:42,116 INFO: Lock owner: node2; I am node1
> 2017-10-13 14:34:42,120 INFO: trying to bootstrap from leader 'node2'
> 2017-10-13 14:34:42,827 INFO: replica has been created using basebackup
> 2017-10-13 14:34:42,827 INFO: bootstrapped from leader 'node2'
> 2017-10-13 14:34:42,830 INFO: closed patroni connection to the postgresql cluster
> < 2017-10-13 14:34:42.969 UTC > FATAL:  could not open relation mapping file "global/pg_filenode.map": No such file or directory
> 2017-10-13 14:34:43,318 INFO: postmaster pid=482
> < 2017-10-13 14:34:43.319 UTC > LOG:  could not bind IPv4 socket: Address already in use
> < 2017-10-13 14:34:43.319 UTC > HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
> < 2017-10-13 14:34:43.319 UTC > WARNING:  could not create listen socket for "0.0.0.0"
> < 2017-10-13 14:34:43.319 UTC > FATAL:  could not create any TCP/IP sockets
> < 2017-10-13 14:34:43.319 UTC > LOG:  database system is shut down
> 
> ...

> 2017-10-13 14:35:23,726 ERROR: postmaster is not running
> 2017-10-13 14:35:23,769 INFO: Lock owner: node2; I am node1
> 2017-10-13 14:35:23,771 INFO: failed to start postgres
> < 2017-10-13 14:35:23.973 UTC > FATAL:  could not open relation mapping file "global/pg_filenode.map": No such file or directory
> < 2017-10-13 14:35:24.441 UTC > LOG:  could not open temporary statistics file "pg_stat_tmp/global.tmp": No such file or directory
> < 2017-10-13 14:35:25.089 UTC > LOG:  could not open temporary statistics file "pg_stat_tmp/global.tmp": No such file or directory
> < 2017-10-13 14:35:25.089 UTC > LOG:  could not open temporary statistics file "pg_stat_tmp/global.tmp": No such file or directory
> < 2017-10-13 14:35:25.160 UTC > LOG:  could not open file "postmaster.pid": No such file or directory
> < 2017-10-13 14:35:25.160 UTC > LOG:  performing immediate shutdown because data directory lock file is invalid
> < 2017-10-13 14:35:25.160 UTC > LOG:  received immediate shutdown request
> < 2017-10-13 14:35:25.160 UTC > WARNING:  terminating connection because of crash of another server process
> < 2017-10-13 14:35:25.160 UTC > DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
> < 2017-10-13 14:35:25.160 UTC > HINT:  In a moment you should be able to reconnect to the database and repeat your command.
> < 2017-10-13 14:35:25.162 UTC > LOG:  could not open temporary statistics file "pg_stat/global.tmp": No such file or directory
> < 2017-10-13 14:35:25.167 UTC > LOG:  could not write pg_stat_statement file "pg_stat/pg_stat_statements.stat.tmp": No such file or directory
> < 2017-10-13 14:35:25.170 UTC > LOG:  database system is shut down
> 2017-10-13 14:35:32,125 WARNING: Postgresql is not running.
> 2017-10-13 14:35:32,125 INFO: Lock owner: node2; I am node1
> 2017-10-13 14:35:32,126 INFO: Lock owner: node2; I am node1
> 2017-10-13 14:35:32,136 INFO: Local timeline=11 lsn=0/A000028
> 2017-10-13 14:35:32,141 INFO: master_timeline=11
> 2017-10-13 14:35:32,142 INFO: master: history=1	0/303C918	no recovery target specified
> 
> 2	0/3043768	no recovery target specified
> 
> 3	0/3049978	no recovery target specified
> 
> 4	0/304B968	no recovery target specified
> 
> 5	0/307CDD0	no recovery target specified
> 
> 6	0/7002AA0	no recovery target specified
> 
> 7	0/7005490	no recovery target specified
> 
> 8	0/7008898	no recovery target specified
> 
> 9	0/700BA50	no recovery target specified
> 
> 10	0/7030418	no recovery target specified
> 
> 2017-10-13 14:35:32,148 INFO: starting as a secondary
> 2017-10-13 14:35:32,727 INFO: postmaster pid=749
> < 2017-10-13 14:35:32.815 UTC > LOG:  redirecting log output to logging collector process
> < 2017-10-13 14:35:32.815 UTC > HINT:  Future log output will appear in directory "/proc/1/fd".
> < 2017-10-13 14:35:32.816 UTC > LOG:  database system was shut down at 2017-10-13 14:34:46 UTC
> < 2017-10-13 14:35:32.817 UTC > LOG:  entering standby mode
> < 2017-10-13 14:35:32.828 UTC > LOG:  consistent recovery state reached at 0/A000098
> < 2017-10-13 14:35:32.828 UTC > LOG:  invalid record length at 0/A000098: wanted 24, got 0
> < 2017-10-13 14:35:32.828 UTC > LOG:  database system is ready to accept read only connections
> < 2017-10-13 14:35:32.832 UTC > LOG:  started streaming WAL from primary at 0/A000000 on timeline 11
> < 2017-10-13 14:35:32.833 UTC > FATAL:  could not receive data from WAL stream: ERROR:  requested starting point 0/A000000 is ahead of the WAL flush position of this server 0/9002FA8
> 	
> < 2017-10-13 14:35:32.842 UTC > LOG:  started streaming WAL from primary at 0/A000000 on timeline 11
> < 2017-10-13 14:35:32.842 UTC > FATAL:  could not receive data from WAL stream: ERROR:  requested starting point 0/A000000 is ahead of the WAL flush position of this server 0/9002FA8
> 	
> localhost:5432 - accepting connections
> localhost:5432 - accepting connections

I cannot provide more precise root cause for now. I cannot find correct place in old version which leads to full cluster recovery. May be it happens because patroni cannot bootstrap correctly and perform circle 'directory cleaunup + bootstrap + shutdown' several times. 

Should I create new ticket or reopen current?

**Comment by alexeyklyukin** [comment]
If you have PostgreSQL process running, but the data directory underneath has been wiped out, then Patroni won't be able to do anything with it, and PostgreSQL will keep failing at start with the error about another process already running. Can you look at the ps, whether there are older processes running? What happens if you try to kill them manually (perhaps with kill -9).

**Comment by ainlolcat** [comment]
It is running. After some time it died and patroni was able to start another process. But postgresql state was corrupted already (looks like start without specified replica role). It is not clear if state was corrupted by old process or new processes but during last start postgresql writes in logs `database system was shut down at 2017-10-13 14:34:46 UTC` which coresponds to first failed postgresql start with `LOG: could not bind IPv4 socket: Address already in use`.

It looks like this :

1. rm -rf data directory;
2. patroni releases lock and performs failover;'
3. patroni starts bootstrapl;
4. patroni tries to start postgresql but it fails with ` LOG: could not bind IPv4 socket: Address already in use` because old process still running. This start will be references as `first failed postgresql start`;
5. patroni tries to start postgresql but it fails with ` LOG: could not bind IPv4 socket: Address already in use` because old process still running;
6. patroni tries to start postgresql but it fails with ` LOG: could not bind IPv4 socket: Address already in use` because old process still running;
7. patroni tries to start postgresql but it fails with ` LOG: could not bind IPv4 socket: Address already in use` because old process still running;
8. Old process dies with message `LOG: received immediate shutdown request`;
9. Patroni starts postgresql. Postgresql writes in logs time of last shutdown which corresponding to `first failed postgresql start`;
10. Postgresql running at last but cannot resume replication because `FATAL: could not receive data from WAL stream: ERROR: requested starting point 0/A000000 is ahead of the WAL flush position of this server 0/9002FA8`. This can happen because it was started as master.

**Comment by ainlolcat** [comment]
Ok. I was able to pass scenario with lost data dir with patch like 
[shutdown_postgres_when_lost_data_dir.txt](https://github.com/zalando/patroni/files/1418562/shutdown_postgres_when_lost_data_dir.txt)

**Comment by CyberDem0n** [comment]
Hi @ainlolcat, can you please open a pull request?
