### ISSUE TITLE
How does haproxy determine who is the  primary and connect to the primary?

### ISSUE THREAD

**Issue by yangshushu** [zalando/patroni#547]
I have a question.
How does haproxy determine who is the  primary and connect to the primary?
thanks~!

**Comment by CyberDem0n** [comment]
Haproxy sends health-check probes to all patroni nodes it knows:

Look into config file: https://github.com/zalando/patroni/blob/master/haproxy.cfg#L24 `check port 8008`

8008 is the patroni rest api port.
If node is running as a master, patroni will respond on request 'GET /' with http status code 200, in other case it will return 503.

haproxy sends traffic only to the nodes which responding with 200.

It is also possible to do read load balancing with haproxy, but for that it should do a different health-check: `GET /replica`

**Comment by yangshushu** [comment]
Got it,thank you~!
