### ISSUE TITLE
pg_hba.conf file gets copied by pgbasebackup

### ISSUE THREAD

**Issue by IJOL** [zalando/patroni#566]
AFAIK pg_basebackup copies all the files in datadir, so including config files and pg_hba.conf between them is at least confusing one make a patroni.yml with the hba config, the server starts, later as replication on gets the content of all the datadir, and thus hba ends being changed,by the one used in the bootstrap node in the first time, very confusing.. can this be solved in some naive way, or i'm overlooking something or simply wrong?

Anyhelp will be aprecciatd.. i'm very confused..

**Comment by CyberDem0n** [comment]
Hi,

there are a few ways to manage pg_hba.conf: http://patroni.readthedocs.io/en/latest/SETTINGS.html#postgresql

1. If there in nothing in patroni.yaml about pg_hba - it will use what it got from the backup.
2. You can define location of pg_hba.conf in `postgresql.parameters.hba_file` and manage its content on your own.
3. You can define content of pg_hba.conf in the section `postgresql.pg_hba` of patroni.yaml or globally (patronictl edit-config $your_cluster). In this case patroni will create or overwrite existing pg_hba.conf in the data directory.

**Comment by IJOL** [comment]
I confess that i'm lost, just now, my cluster ( a docker one ) keeps spitting problems related to 127.0.0.1 as replicator not found in hba, i modify the entrypoint to spit a seemgly correct  yaml file with that inside:

  pg_hba:
    - host all all 0.0.0.0/0 md5
    - host replication replicator ${DOCKER_IP}/16    md5
    - host replication replicator 127.0.0.1/32    md5

whenever i get into my datadir, i didnt find my configs there i suppouse looking at the last line, that this was the hba generated when the data directory was created, it has an ip that it's not in my system, so what?

i'm lost in the space

**Comment by CyberDem0n** [comment]
Before starting with docker, I think it make sense to play with two patroni instances on your own host.
This is very easy: https://github.com/zalando/patroni/#running-and-configuring

Next step is to play with patronictl: 
```bash
$ ./patronictl.py -c postgres0.yml list batman
$ ./patronictl.py -c postgres0.yml failover batman
$ ./patronictl.py -c postgres0.yml reinit batman postgresql0
$ ./patronictl.py -c postgres0.yml edit-config batman
```

It's also possible to reload yaml config files in runtime without restarting patroni by sending SIGHUP to the patroni process.

In additional to that you ca read a documentation: http://patroni.readthedocs.io/en/latest/SETTINGS.html,  http://patroni.readthedocs.io/en/latest/ENVIRONMENT.html and http://patroni.readthedocs.io/en/latest/dynamic_configuration.html

After that it would be much easier to figure out what and why is going on in the docker.

**Comment by IJOL** [comment]
I have a running cluster and surpassed all problems, just didnt understand how seeing what i'm seeing, whole damn thing is working very well..but how is it working? , just to get to know, but i have a perfectly ok cluster running very well, so thanks for all the fish, 

ANothe question that bugs me is why in the docker entrypoint DOCKER_IP get add to pg_hba section and 127.0.0.1 doesnt, so doing that everyting started to work very well, but that little damn thing of the real pg_hba.conf file that get being used that keeps bugging me, buut it's doing very very wel until now.. fingers crossed..
