### ISSUE TITLE
get Patroni working on Openshift

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#572]
@ants 

There are a number of obstacles for Patroni/Spilo working on OpenShift, most particularly file permissions issues and errors associated with the random high userid.  While I have issues open with the openshift team about this, I'd like to also document and/or provide some alternate images and config settings which let patroni run on OpenShift.

Here's what I have so far:

* directory permissions: modify group permissions per the canonical OpenShift postgres image, using their fixpermissions() approach.
* userid calls from Postgres: use nss_wrapper and /tmp/passwd
* python userid calls: ???

The last is what I'm stuck on; python doesn't care about nss_wrapper, and at least one library we're using does a call to getuid().

**Comment by ibotty** [comment]
> userid calls from Postgres

Or `chmod a+w /etc/passwd` as is done in most s2i containers.

**Comment by davecramer** [comment]
@jberkus is this still the status of patroni on openshift ?

**Comment by jberkus** [comment]
it's not, but we haven't put together the templates and the RBAC profile into a coherent package.  Sorry, it's on my TODO list, but I've been travelling a lot for work.

**Comment by ttiurani** [comment]
I'm interested in this as well, so would be happy to hear about and test any configs you have @jberkus

**Comment by soukron** [comment]
Hi @jberkus 
Did you manage to get it working in OpenShift without using a cluster-admin privileged account?

**Comment by anikin-aa** [comment]
Guys, hi ! 
we managed to get it working under restricted SCC. 
> Or chmod a+w /etc/passwd as is done in most s2i containers.
this did the job for our case.
