### ISSUE TITLE
kubernetes-native patroni: need more details

### ISSUE THREAD

**Issue by epicsoft** [zalando/patroni#579]
Hello guys.
Thank you a lot for the working example: https://github.com/unguiculus/charts/tree/feature/patroni/incubator/patroni

Would you please help with:
1. How to enable **TLS**?
2. How to configure walE.gcsBucket, **walE.kubernetesSecret**? 
3. How to **restore** the cluster DB from the backup (above)?

Looking forward to hear back from you guys!

**Comment by CyberDem0n** [comment]
> How to enable TLS?

please see an issue #574 

> How to configure walE.gcsBucket, walE.kubernetesSecret?

I believe https://github.com/unguiculus/charts/tree/feature/patroni/incubator/patroni explains is good enough: Specify each parameter using the --set key=value[,key=value] argument to helm install.

> How to restore the cluster DB from the backup (above)?

Are you talking about backup made from existing cluster by wal-e or something else?
Restoring a backup is actually very big and very complicated topic. If you removed an existing cluster (by accident), you can always deploy it once again with the same name and Patroni will restore your data from backup.
But if you are talking about restoring an arbitrary backup into a new cluster, there is another Patroni feature for that: http://patroni.readthedocs.io/en/latest/replica_bootstrap.html#custom-bootstrap

Spilo has support of custom bootstrap, although it is not documented and not really tested, but helm-chart doesn't have it, but again, it should be easy to implement.

**Comment by epicsoft** [comment]
Hello, thank you for your answers.
From docs: walE.kubernetesSecret - kubernetes secret for provider bucket - what is the format of the secret? Do you have any example?

I'm asking about backup from existing cluster (by wal-e).

**Comment by CyberDem0n** [comment]
> walE.kubernetesSecret - kubernetes secret for provider bucket - what is the format of the secret? Do you have any example?

This is a name of kubernetes Secrets object. Example of secret with postgres credentials: https://github.com/unguiculus/charts/blob/feature/patroni/incubator/patroni/templates/secret.yaml

You have to create Secret for wal-e on your own. Later it is referenced from https://github.com/unguiculus/charts/blob/feature/patroni/incubator/patroni/templates/statefulset.yaml


> I'm asking about backup from existing cluster (by wal-e).

Are you asking about disaster recovery or PITR?

**Comment by epicsoft** [comment]
Ok, It looks like you expect google service account JSON key for the walE.kubernetesSecret.
And walE.gcsBucket should comply to gs://bucket/path/optionallymorepath

> re you asking about disaster recovery or PITR?

You probably got it already - I'm noob in Postgres :) I think I'm referring to scenario when I need to restore the DB cluster to some point of time from the WALs stored by wal-e (e.g. in GCE bucket).

**Comment by CyberDem0n** [comment]
> You probably got it already - I'm noob in Postgres :)

Well, you'll have to learn it. It's not really possible to operate a system without understanding how it works under the hood.

> I need to restore the DB cluster to some point of time from the WALs stored by wal-e (e.g. in GCE bucket).

Patroni and Spilo do support it (creating a new cluster from a basebackup made by wal-e to a given point in time), but I am not sure that spilo image build by unguiculus does it. Instead you can use `registry.opensource.zalan.do/acid/spilo-10:1.3-p9`. Unfortunately it's not trivial to configure it, and docs are also missing, but you can try to figure out what env variable control it from here: https://github.com/zalando/spilo/blob/master/postgres-appliance/configure_spilo.py#L147-L164
