### ISSUE TITLE
kubernetes patroni: new label request

### ISSUE THREAD

**Issue by epicsoft** [zalando/patroni#582]
Hello guys!
Is it practical to introduce a new label into Kubernetes patroni pods like _active=true_ (when _role=master_ or _role=replica_)?
I think there should be 2 Kubernetes services:
1. **Write**: _role=master_ label selector, that allows to write into the Master 
2. **Read**: _active=true_ label  selector, that allows to read from both _role=master_ and _role=replica_
Additional label is required as Kubernetes service does not support complex selectors like _role in (master, replica)_

**Comment by epicsoft** [comment]
Hey, any ideas? Does it worth it? 
The goal is to write to a single (master) node but read from all the nodes available (master and replicas) for performance sake. And we should exclude nodes in the init state (neither master nor replica).

**Comment by CyberDem0n** [comment]
It's easy to implement, we can expose a status of postgres into a labels (running, stopped, starting and so on), so you can grab all the pods with status=running if you like, but I don't think that you should do that.

Usually people start load balancing read-only queries across replicas only when master can't cope with the load anymore. More important that not every select could be executed on replica, but only when it's ok if you get a slightly outdated data (it could happen). At the end, you also want to avoid hitting a master with analytical queries for example.

**Comment by epicsoft** [comment]
Understood. Thank you!
