### ISSUE TITLE
patroni-native k8s: roadmap

### ISSUE THREAD

**Issue by epicsoft** [zalando/patroni#587]
Hello guys! 

Is it possible to have access/be notified about new releases of patroni-native k8s (https://github.com/zalando/spilo/tree/feature/minispilo-10/postgres-appliance)

Thank you for the great job you are doing!

**Comment by CyberDem0n** [comment]
We don't really have a roadmap regarding Spilo.
Basically when we do a bugfix or want to have a new feature we build and push the new image.
Right now it lives in a feature branch, but soon we are planning to release the new Patroni version and after that we will merge `feature/minispilo-10` into the master branch.
If you wish, you can find list of existing spilo images:
```bash
$ curl -s https://registry.opensource.zalan.do/v1/repositories/acid/spilo-10/tags | jq .
{
  "1.3-p10": "sha256:d5c8b1c7d144e7d22b24a57d0084f46defb544fe2fc5ad3abcc98adf9f04e234",
  "1.3-p7": "sha256:a787ae59ba0cad29fe9267eb60a3e3fdff34fa7b45ad233a53f1e2a58187ce60",
  "1.3-p3": "sha256:d926823c2c3a23a1124a9eed0217d5944911b0f7a6952ce4cbf374ee3e03d155",
  "1.3-p2": "sha256:2e1f09923de922a37292dd7cc85e3f46d3f69ad48ceb58e2eaa91239c900aeba",
  "1.3-p8": "sha256:afe4ba20769c00157c47e7c8abec875d63a962f80cdb459cf36ced4b6b05abf9",
  "1.3-p9": "sha256:42e1da0bc9ddf2d738c352ae56292e7af4392a61ceba9cab051ce216c86bd651",
  "1.3-p4": "sha256:c65003304898ac5cbf2a5be1ff352434eff7d159e4fec69ad53b7fb53bb69a0c",
  "1.3-p1": "sha256:21b3704364d2fe08e602a771fe858748055b8ccd31e44f15ab8e22542bbb555a",
  "latest": "sha256:d5c8b1c7d144e7d22b24a57d0084f46defb544fe2fc5ad3abcc98adf9f04e234",
  "1.3-p6": "sha256:bce6cea0fd2a4753a32a6b9676d8c448da856f8e72f26a890d21694b5153ac92",
  "1.3-p5": "sha256:2f347a3eca2828da0cb937cf720b5b6ca099ccfed1673de607da0ae9988770d1"
}
```

**Comment by epicsoft** [comment]
Hello guys.

Where should I take a latest version of patroni-native k8s?
Is it **1.4-p1** from https://registry.opensource.zalan.do/v1/repositories/acid/spilo-10?

Thnank you!

**Comment by alexeyklyukin** [comment]
@epicsoft take 1.4-p2 instead, it is the latest one and contains patroni-1.4.1 (https://github.com/zalando/patroni/blob/master/docs/releases.rst#version-141) that supports Kubernetes.

you may also take a look at the https://github.com/zalando/patroni/blob/master/kubernetes/patroni_k8s.yaml from the master, it contains the role-based access control definition for Patroni, defining the role with proper permissions, the service account and the binding between two. Only applies if your default role has limited set of permissions.
