### ISSUE TITLE
Multiple Patronis managing a single PostgreSQL instance

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/patroni#60]
We should make some kind of lock file in the PostgreSQL data directory, that would indicate that the instance is managed by Patroni of a given cluster, in order to prevent multiple Patroni daemons to attach to a single data directory. Right now this is possible, if you run a second patroni with the same data_dir, but point it to another cluster, both would compete to set the instance into the desired state (master, replica) and would likely render the instance unusable.

**Comment by jberkus** [comment]
Hmmm.  The problem with that is I can see potential issues where patroni refuses to start due to an abandoned lock file.

If this is really a problem, I'd suggest adding a locking key per IP address in the SIS instead.  However, I can't see it as a high-priority issue.

**Comment by alexeyklyukin** [comment]
We could write the patroni process pid in the lock file and check whether the pid is really around before refusing to start another Patroni. This is not a high priority issue though.

**Comment by CyberDem0n** [comment]
Think about containers...
The pid file can be created from one container but you are trying to find process with such pid from a different container.

**Comment by alexeyklyukin** [comment]
Your examples bears a bigger problem: PostgreSQL will also be fooled into assuming the older postmaster is no longer around and will happily start the second one. 

We can try to safeguard by periodically touching the Patroni lock file and check in the Patroni candidate that the lock file has not been updated recently.

**Comment by jberkus** [comment]
I don't follow?  How would that happen?

**Comment by feikesteenbergen** [comment]
It seems this problem is outside the scope of Patroni.
