### ISSUE TITLE
Limiting bandwidth during initial pg_basebackup?

### ISSUE THREAD

**Issue by seafoodbuffet** [zalando/patroni#602]
When I'm trying to build a slave node from master, the initial pg_basebackup appears to run at full tilt. This is saturating the network on the active master. Is there a way to reduce this bandwidth? 
I see that pg_basebackup has a --max-rate option but there appears to be no way to supply that to Patroni. Are there other options for achieving this?

**Comment by alexeyklyukin** [comment]
You can create your custom script based that calls pg_basebackup with all parameter you need. See Spilo (https://github.com/zalando/spilo/blob/cfbde098981eb329f71296cec750329f1eb75f67/postgres-appliance/configure_spilo.py#L254 and https://github.com/zalando/spilo/blob/master/postgres-appliance/basebackup.sh) as an example of a similar script.

**Comment by alexeyklyukin** [comment]
I think it might be a good idea to allow passing parameters directly to the built-in pg_basebackup replica creation method with our usual way of defining parameters in the Patroni configuration.

**Comment by seafoodbuffet** [comment]
@alexeyklyukin Thank you very much, that's exactly what I was looking for. I would love to see a supported way to pass parameters to pg_basebackup, but the custom script approach seems fine for my needs for now.

**Comment by CyberDem0n** [comment]
@seafoodbuffet,

by the way, Patroni can use some of the existing replicas to take basebackup from.

Those replicas should be `tagged` with `clonefrom` tag:
```yaml
tags:
  clonefrom: true
```

And Patroni will prefer to use such replicas instead of master.
