### ISSUE TITLE
System incorrectly rebooted when patroni service stopped with watchdog enabled.

### ISSUE THREAD

**Issue by akissa** [zalando/patroni#609]
A regression has been introduced by commit 5da0e12353a2e2462437ff36c6512d6ae8ea7142

This is because it is possible for an exception to be raised at https://github.com/zalando/patroni/commit/5da0e12353a2e2462437ff36c6512d6ae8ea7142#diff-74fbda32f108239eb16ce7417ef10085R85

The  exception is (`psutil.NoSuchProcess`)(`psutil.NoSuchProcess process no longer exists`).

This means the watchdog is not correctly closed. Which then causes the system to get reset.

It can be replicated easily by enabling the watchdog then stop the patroni service.

**Comment by ants** [comment]
Thanks for the report. I will come up with a fix for this.
