### ISSUE TITLE
Bug or feature? Patroni endpoints and etcd is not accessible

### ISSUE THREAD

**Issue by uspen** [zalando/patroni#626]
Patorni last version: 1.4.2.
Patroni in pause state. Get etcd is not accessible.

Check time increased:
from INFO: Selected new etcd server
time is depending on the number of servers
to INFO: PAUSE: DCS is not accessible

This is maybe normal . Just increase e.g. HAproxy timeout check up to 10s
Endpoint /replica - HTTP 200 code
Endpoint /async - HTTP 503 code

Steps:

1. patronictl pause cluster
2. iptables -I OUTPUT -p tcp --dport 2379 -j REJECT (or DROP)
3. curl -s -o /dev/null -w "%{http_code}\n" -X GET http://server.db.example.com:8008/replica
> 200
4. curl -s -o /dev/null -w "%{http_code}\n" -X GET http://server.db.example.com:8008/async
> 503

**Comment by uspen** [comment]
Without the maintenance mode, the behavior is the same

**Comment by CyberDem0n** [comment]
Without access to DCS node can't know for sure whether it is synchronous or nor.

**Comment by uspen** [comment]
Yes, exactly, and understood
