### ISSUE TITLE
When using Custom Bootstrap, Patroni does not write pg_hba values from the patroni conf file

### ISSUE THREAD

**Issue by bradnicholson** [zalando/patroni#631]
When using the custom bootstrap file, Patroni does not use the pg_hba.conf values in the patroni.yml file.

I did a basic A/B test.  First without the custom bootstrap being called.  This test wrote the pg_hba.conf file correctly with the custom values from the patroni config file.

The second test, I enabled a basic custom bootstrap that just calls initdb directly.  I left the rest of the patroni.yml file unchanged.  This time, it did not write the pg_hba values from the patroni config file to the pg_hba.conf file.

**Comment by CyberDem0n** [comment]
Hi @bradnicholson,

can you provide part of the config file with `pg_hba`?

**Comment by bradnicholson** [comment]
```
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums
  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - local      all             all                                              trust
    - host       all             all                      ::1/128                 trust
    - host       all             all                      0.0.0.0/0               trust
    - host       replication    replication-user      0.0.0.0/0               trust
```
