### ISSUE TITLE
Patroni mailing list or slack channel?

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#645]
@CyberDem0n enough people are using Patroni now that it might be a good idea to have a mailing list or a slack channel.  I'm happy to set one up, which would you prefer?

**Comment by jberkus** [comment]
@bradnicholson oh, that's a great idea. @CyberDem0n which one would you use?

**Comment by jberkus** [comment]
Also, @ants what's your preference?

**Comment by ants** [comment]
I have no strong feelings one way or the other.

**Comment by CyberDem0n** [comment]
I don't have any preferences either, but we definitely shouldn't create both.

**Comment by jberkus** [comment]
Well, I have a way to easily create a Slack Channel, and no place to host mailing lists.

So, Slack it is.

Join Postgres Slack here: https://postgres-slack.herokuapp.com/

Channel #patroni

**Comment by CyberDem0n** [comment]
Cool! Thank you.
Now we need somehow reference it from README and DOCS.

**Comment by jberkus** [comment]
Yah, I know, that's why the issue is still open.  I'll get to it in a day or two if someone doesn't beat me there.
