### ISSUE TITLE
Is it possible to make an application server a part of a quorum?

### ISSUE THREAD

**Issue by AiAlex** [zalando/patroni#646]
Hello,

Is it possible to make an application (not postgres) server a part of a quorum?

Let's say I have 1 application server, 1 haproxy server and 3 postgresql servers. When 2 postgres servers down patroni switches the third one to readonly mod. But technically, 3 of 5 servers in the system are still alive. 
And even if the other two postgresql's are still alive and connected to each other there are no use of them without the connection to application and proxy. So it would be better if they don't start the election. And the first server which is connected to proxy and application continiue its work.

So is there any way to do it?

**Comment by jberkus** [comment]
I take it you're using the experimental "patroni on pure RAFT" branch?

If you are, then no, making other types of nodes part of the quorum isn't implemented.  You can implement it (and then please submit patches!) or you can use the more conventional approach of having a separate etcd/consul server or the Kubernetes API.

**Comment by ants** [comment]
And if you aren't using the RAFT branch, Patroni itself doesn't actually create the quorum. It relies on an external provider, like etcd, to establish the quorum and use it to provide correct semantics for leader election.

You can set up etcd on your 5 nodes to get 3 out of 5 behavior.

**Comment by jberkus** [comment]
Closing due to lack of response from OP.
