### ISSUE TITLE
Allow 'permanent' replication slots that don't correspond to the cluster members

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/patroni#656]
When Patroni syncs its replication slots, it removes all slots except for those corresponding to the known members of the cluster.

That may break some useful features that rely on replication slots (i.e. logical decoding via a replication slot, logical replication or even pg_basebackup from the replica in newer versions of PostgreSQL). 

There are at least two ways to resolve this:

- Define some slots in the patroni configuration (in DCS) to be permanent, Patroni will create them and never remove. The downside of this approach is that it requires the user to let Patroni know of such slots explicitly.
- Avoid deleting replication slots that were not created by Patroni, leaving the task of creating actual slots to the user. This is suboptimal since replication slots itself are not replicated and would have to be created anew after each promotion.

Perhaps it would be good to combine both approaches and tag those slots created by Patroni (including permanent one, defined in the configuration) in some way or another, and drop only those slots when necessary. Since there are no comments on replication slots, the obvious way is to use some naming convention with a possible risk of the user naming their slots the same way and confusing Patroni.

**Comment by bradnicholson** [comment]
> Avoid deleting replication slots that were not created by Patroni, leaving the task of creating actual slots to the user. This is suboptimal since replication slots itself are not replicated and would have to be created anew after each promotion.

This seems like a cleaner approach to me though.  This is a limitation in Postgres at the time, and trying to have Patroni work around that seems less than optimal.

When the replication slot gets recreated on another member, it will have lost the place the former slot was on, and the end user will possibly/probably need to take special action to resync anyway.

**Comment by bradnicholson** [comment]
What is the value of persisting a replication slot on failover if we can't pick up from where we left off?

It seems like there is a burden on the application here anyway to handle that case.  Is re-creatin the replication slot as part of that too much burden?

**Comment by jberkus** [comment]
@bradnicholson the purpose of this is to persist replication slots that aren't created by, or maintained by, Patroni.

For example, imagine that you had a replication slot for a logical replication stream that was attached to an external data auditing tool.  Whenever the list of nodes changes, Patroni will delete all slots not associated with an active Patroni node ... including the one for the auditing tool.

**Comment by CyberDem0n** [comment]
Unfortunately there are too many ambiguities in the second approach.
It is not possible to know from the slot name whether it was created by Patroni or not.
Just think about a situation when Patroni was restarted and at the same time, one of the members expires from DCS. Upon start, Patroni will see that there is a slot, but no member in DCS. Should it remove this slot? I think yes, it should.

Patroni creates/removes replication slots only if the list of members changes and it never removes active slots.
@alago197 I think that the current behaviour is more or less fine for you.

**Comment by alago197** [comment]
Ah, thanks for the clarifications CyberDem0n, didn't knew of that. Yes, as long it doesn't remove an active, it's all fine, the barman slot would be active during the receivewal

**Comment by jberkus** [comment]
> It is not possible to know from the slot name whether it was created by Patroni or not.

I think you may have hit on a solution.

Why isn't it possible?  Why can't you name the Patroni slots in an idiosyncratic way so that we know which ones they are?  Postgres doesn't require any particular naming for slots, so we could use any name we want.

**Comment by CyberDem0n** [comment]
> Why can't you name the Patroni slots in an idiosyncratic way so that we know which ones they are?

1. It would be not backward compatible.
2. Anybody can spoil it.


> Postgres doesn't require any particular naming for slots, so we could use any name we want.

Well, first of all, slot name can't be longer than 63 characters. Also it may only contain lower case letters, numbers, and the underscore character: https://github.com/postgres/postgres/blob/master/src/backend/replication/slot.c#L164-L210

That's why we have a function: [slot_name_from_member_name](https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L53-L66)

**Comment by Jan-M** [comment]
Given some recently presented use case and that RDS Postgres supports logical streaming out, this has become a bit more important to be solved.
