### ISSUE TITLE
Allow a HA cluster to run in a standby mode 

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/patroni#657]
Right now, Patroni always promotes one node in a cluster that acquires the leader lock.

We may want to have a standby cluster, running alongside the primary one (i.e. in another datacenter) and consisting of only standby nodes, replicating from the primary one. Such cluster will have no master, there will be one "main" replica replicating from the master in the primary cluster, and all the other cascading replicas replicating from the main one.

We can already achieve this by writing a permanent leader and member keys in DCS, specifying the address of the cluster in the member key. However, the primary leader knows nothing about the standby cluster, it doesn't create a replication slot, and the whole setup requires direct access to DCS from the user implementing it.

What we can do is to create a new key in DCS called standby, holding connection string for the actual master inside. When this key is there, the leader key will be interpreted as a pointer to the main replica, instead of the master, that replica will not promote itself, and the other replicas will replicate from the main one. When the standby key disappears, the cluster stops being a standby, and the replica holding the leader key will promote itself.

From the user point of view, there is not much additional information to be supplied to Patroni. We only need the credentials for the master (standby and superuser names and passwords, they are already required in the current configuration file and obviously should match between the primary and the standby cluster) and the connection string.

**Comment by jberkus** [comment]
Wouldn't it be better to look at this as "support for cascading replication" instead?

Or are you specifically treating the "remote standbys" as a separate cluster in order to deal with the limitations of kubernetes federation?

**Comment by alexeyklyukin** [comment]
@jberkus we already have cascading replication based on per-instance tags. While it is limited to a single fixed node for each cascading destination I don't think it would be terribly useful to make a single origin replica within a single cluster with a primary. 

We didn't have the federation use case in mind, although it may prove useful for that (we don't use Kubernetes federation). We did, however, run an all-replica HA cluster  on AWS at some point in time for one of our biggest databases, replicated from the HA cluster in the DC, as a part of migrating our databases to the cloud.

**Comment by jberkus** [comment]
So a couple things I'm not understanding from your description:

1. How does election of the "relay node" happen?  To make sure that there's always one node replicating from the original DC master?
2. How does the system decide that the original DC is gone?  Would it be possible to automate this via a consensus among three data centers, or are you doing DC failover manually?

**Comment by CyberDem0n** [comment]
> How does election of the "relay node" happen? To make sure that there's always one node replicating from the original DC master?

The same way as leader election currently happens. If we are bootstrapping a new standby cluster, one node will create `/initialize` key in DCS and take a basebackup from the remote cluster. After that, it will create '/leader' key and start postgres with recovery.conf. Other nodes will wait until it becomes accessible and take a basebackup from the "fake leader".

If the /leader key expires in DCS, other nodes will do absolutely the same leader elections, but with slightly relaxed constraints (they don't care about `maximum_lag_on_failover`). The new leader will start replicating from remote cluster and other nodes will start replicating from the new leader.

> How does the system decide that the original DC is gone? Would it be possible to automate this via a consensus among three data centers, or are you doing DC failover manually?

I think that manual promotion of a standby cluster would be good enough for the beginning.

**Comment by jamessewell** [comment]
Snap!

Many people would use this (we currently do) as a "DR" cluster. They want a "Prod" cluster with a single replication stream to a the DR cluster, which then fans out to the other members. The DR cluster is all standbys.

Manual promotion between Prod and DR is the almost certainly desired approach in this case.

**Comment by CyberDem0n** [comment]
This feature is nearly done: https://github.com/zalando/patroni/pull/679
Just a few tiny bits are missing.
