### ISSUE TITLE
Running the example on kubernetes tries to make replication connection from localhost

### ISSUE THREAD

**Issue by davecramer** [zalando/patroni#662]
FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "standby", SSL off

https://github.com/zalando/patroni/blob/e375fac273a75457bb241ade28c1609bf5a7fca2/patroni/postgresql.py#L1205

**Comment by davecramer** [comment]
I suspect this is less of a bug and more of an annoyance. It seems that only the leader should be making this query but all of the standby's do as well

**Comment by CyberDem0n** [comment]
Hi @davecramer, please read https://github.com/zalando/patroni/issues/643
