### ISSUE TITLE
Docker images and k8s

### ISSUE THREAD

**Issue by DotNetPart** [zalando/patroni#666]
Hi guys, for the last few days I was poking around trying to start patroni in my k8s environment.
What I initially tried to do is just building an image using `cd ~/patroni/kubernetes && docker build -t patroni .`
However if I tried docker run patroni after that, the following error was spit out:

`Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    load_entry_point('patroni==1.4.3', 'console_scripts', 'patroni')()
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 176, in main
    return patroni_main()
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 143, in patroni_main
    patroni = Patroni()
  File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 24, in __init__
    self.config = Config()
  File "/usr/local/lib/python2.7/dist-packages/patroni/config.py", line 78, in __init__
    self._data_dir = self.__effective_configuration['postgresql']['data_dir']
KeyError: 'data_dir'`

So, I had a chance to pull image from registry.opensource.zalan.do/acid/patroni:1.0-SNAPSHOT but don't know if it's suited to run in a standalone mode or it should work with no problems in k8s environment.
What would be the path forward? #

**Comment by hjacobs** [comment]
@DotNetPart I would recommend trying out our PostgreSQL Operator for Kubernetes (if you haven't done already): https://github.com/zalando-incubator/postgres-operator

**Comment by DotNetPart** [comment]
Well, I've taken a look at that, but didn't figure out how to install that without Minikube since I'm new to k8s itself.

**Comment by CyberDem0n** [comment]
Hi @DotNetPart , please take a look at [documentation](http://patroni.readthedocs.io/en/latest/kubernetes.html#examples), I believe it has all answers.

**Comment by DotNetPart** [comment]
Thanks I believe this question can be closed

**Comment by Jan-M** [comment]
@DotNetPart Imho you should give the operator a try, this should give you less problems initially. You can then dive into the statefulset/pod configuration we use there for Spilo/Patroni to understand what is happening.

**Comment by DotNetPart** [comment]
@Jan-M, I tried that today, but had some issues with operator pod not being able to access API due to certificate authority problem. Anyhow, I had a chance to start patroni successfully on my cluster.

**Comment by Jan-M** [comment]
Interesting, if you have a minute maybe you could open an issue on the operator, have not seen or heard that before. Sounds more like a k8s setup issue.
