### ISSUE TITLE
Ordering of user creation and post_bootstrap execution

### ISSUE THREAD

**Issue by bradnicholson** [zalando/patroni#667]
Is there a reason why we create all of the non-superuser roles after running the post_bootstrap?

What I'd ideally like to do is create a set of users via Patroni, then be able to create DB objects owned by those users are part of a post_bootstrap script.  While this can be worked around by creating the users in the postbootstrap script, that seems wrong to me.

If there are no objections to creating the users prior to running the post_bootstrap script, I'll put a PR up for the change.

**Comment by alexeyklyukin** [comment]
While I see nothing wrong in creating users in the `post_bootstrap` script I also see no reason why do we create users mentioned in the Patroni configuration before and not after running the post_bootstrap script.

I'd expect people would use one of those two, i.e. either do everything via the `post_bootstrap` or create users with the Patroni configuration. Mixing both looks a bit weird, you will probably end up with a script that assigns privileges to a given set of users while there is no definition of those users anywhere in the script. So creating 'normal' users before and not after the post_bootstrap phase looks like a nuance to me.
