### ISSUE TITLE
Does patroni support multimaster BDR?

### ISSUE THREAD

**Issue by omidraha** [zalando/patroni#673]
Hi,
Dose patroni support for BDR?
I mean multi master for write.
Thanks.

> In this case updates can be performed at any node of the cluster and then propagated to other nodes. [BDR](https://wiki.postgresql.org/wiki/Multimaster) is essentially asynchronous: changes are applied at nodes some time later after committing transaction at master and various ways of resolving conflicts are proposed. BDR is really fast (provides almost the same speed as hot standby), but certainly there is no global consistency in such model.

**Comment by alexeyklyukin** [comment]
No, Patroni has a different scope from BDR, providing your HA for a single primary multiple standbys configuration.
