### ISSUE TITLE
Schedule load_replication_slots when postgres is restarted during pause

### ISSUE THREAD

**Issue by ants** [zalando/patroni#674]
Scenario:

    patronictl pause mycluster
    # stop postgres on master, restore backup, start postgres
    # This removes the replication slot for standbynode
    patronictl reinit mycluster standbynode
    # Master thinks standbynode still has a replication slot, master will not create a new one
    # standbynode cannot replicate

Workaround is to restart postgres via Patroni. It would be nice to schedule reloading of replication slots if we discover that postgres has been restarted.

**Comment by CyberDem0n** [comment]
Hmm, I can't really reproduce it...
What I've tried:
```
$ ./patroni.py postgres0.yml
$ ./patroni.py postgres1.yml


$ patronictl -c postgres0.yml pause --wait
$ psql -h localhost -U postgres
localhost/postgres=# select pg_terminate_backend(active_pid) from pg_replication_slots; select pg_drop_replication_slot(slot_name) from pg_replication_slots;
 pg_terminate_backend 
──────────────────────
 t
(1 row)
 pg_drop_replication_slot 
──────────────────────────
 
(1 row)

$ pg_ctl -D data/postgresql0 restart
```

After that Patroni on postgresql0 notice that postmaster was restarted and resyncs slots.
It happens because of https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L1006
