### ISSUE TITLE
Looking for backup in patroni

### ISSUE THREAD

**Issue by kiranmudemela** [zalando/patroni#687]
I just configured patroni on kubernetes using helm chart 

https://hub.kubeapps.com/charts/incubator/patroni

-Able to see the leader info , failover from one to other. 
-How could i take the back up ? 

postgres@msk-patroni-0:~$ patronictl version
patronictl version 1.4.3
postgres@msk-patroni-0:~$

**Comment by alexeyklyukin** [comment]
Hi @kiranmudemela,

Backups are generally outside of scope of Patroni.

The Patroni chart you've mentioned defines a few variables (`walE.scheduleCronJob `, `walE.retainBackups`, `walE.s3Bucket` or `walE.gcsBucket`). I guess it will make the underlying docker image run a base backup with WAL-E, placing it to the S3 or GSC bucket you've specified; together with WAL archiving it will provide you continuous backups (https://www.postgresql.org/docs/10/static/continuous-archiving.html).

You can also run one-time pg_basebackup or pg_dump on your own, or do it via external cron periodically.

**Comment by hjacobs** [comment]
@alexeyklyukin our [Kubernetes Postgres Operator](https://github.com/zalando-incubator/postgres-operator) handles backups, right? Shouldn't @kiranmudemela just go with that?

**Comment by alexeyklyukin** [comment]
@hjacobs the operator just configures environment variables for Spilo (the same docker image that is used in the Helm chart). There is no code in the operator to perform backups on-demand.

**Comment by hjacobs** [comment]
@alexeyklyukin OK, I see, but that's all a bit confusing: Patroni, Spilo, Postgres Operator --- I think we should have somewhere an high level entry point (docs) to explain how to use everything together. My proposal would be to do that on the PostgreSQL Operator repo as it's the most high level entry point for users (and users should not need to care about implementation details such as Patroni vs Spilo).

**Comment by alexeyklyukin** [comment]
Good idea, especially since the operator documentation is getting through the reorganization phase right now. We should describe what is in scope of the operator and what is not, and what are the dependencies of running the Kubernetes infrastructure using the operator (and why do we need them).
