### ISSUE TITLE
testing high avaliabilty

### ISSUE THREAD

**Issue by kiranmudemela** [zalando/patroni#688]
Any steps that you can share for testing HA Patroni on kubernetes

**Comment by hjacobs** [comment]
As a note, please check out our PostgreSQL Operator for Kubernetes which uses Patroni: https://github.com/zalando-incubator/postgres-operator

**Comment by hjacobs** [comment]
To add to that: another failure scenario would be to test Kubernetes API server unavailability.

**Comment by kiranmudemela** [comment]
I m trying to connect to psql using these commands 

1. Run a postgres pod and connect using the psql cli:
    # login as superuser
    kubectl run -i --tty --rm psql --image=postgres \
      --env "PGPASSWORD=$PGPASSWORD_SUPERUSER" \
      --command -- psql -U postgres \
      -h msk-patroni.default.svc.cluster.local postgres

    # login as admin
    kubectl run -i -tty --rm psql --image=postgres \
      --env "PGPASSWORD=$PGPASSWORD_ADMIN" \
      --command -- psql -U admin \
      -h msk-patroni.default.svc.cluster.local postgres

I get the following output 
----------------------------
if you don't see a command prompt, try pressing enter.
psql: could not connect to server: Connection timed out
	Is the server running on host "msk-patroni.default.svc.cluster.local" (10.96.234.102) and accepting
	TCP/IP connections on port 5432?
Session ended, resume using 'kubectl attach psql-74ccbf7f7c-wjp8d -c psql -i -t' command when the pod is running

**Comment by alexeyklyukin** [comment]
> Is the server running on host "msk-patroni.default.svc.cluster.local" (10.96.234.102) and accepting
TCP/IP connections on port 5432?

Is it running? Can you show kubectl get pods -L role=master  and make sure there is at least one  pod running there (assuming you have a single cluster and your `role_label` is set to `role`, which is the default). If there are no masters, take a look at the logs (kubectl logs) for the replica pods (those that have role=replica), or just those pods that have no labels assigned in case Patroni couldn't get to that stage for some reason. Also it may help to exec into the pod and look for the postgres logs, you may find them in /home/postgres/pgdata/pgroot/pg_log.

Also, can you post the manifest you used to deploy?

**Comment by daya** [comment]
Did this problem get resolved? I am having the same issue
