### ISSUE TITLE
WALs no longer there, replica out of sync: How to recover?

### ISSUE THREAD

**Issue by albertvaka** [zalando/patroni#689]
We have a replica and master running with patroni. The replica went out of sync with the master because WALs were recycled faster than replicated.

My replica shows this in the logs:
```
FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 000000060000019600000018 has already been removed
```

How can I recover from this scenario? Is there any way I can ask it to sync everything from scratch, instead of using WALs?

**Comment by albertvaka** [comment]
I've deleted the data directory and restarted the replica. It is showing this in the logs:

INFO: bootstrap from leader 'patroni-cluster1-keeper-1' in progress

So I guess I did right. Feel free to close the issue if it's the case, otherwise please tell me if I could have done something better :)

**Comment by albertvaka** [comment]
It seems to be taking quite a while and meanwhile the queries to the master are really slow :cold_sweat:

**Comment by alexeyklyukin** [comment]
Hi @albertvaka 

> How can I recover from this scenario? Is there any way I can ask it to sync everything from scratch, instead of using WALs?

Reinitialize the replica with `patronictl reinit`. This is exactly "sync everything from scratch"

In order to avoid WAL files not yet recovered by a replica to be recycled on the primary consider enabling replication slots (http://patroni.readthedocs.io/en/latest/dynamic_configuration.html) in Patroni. This is normally a default, so I am wondering whether you changed it manually or are running PostgreSQL 9.3, which doesn't support replication slots? In the latter case you need to establish WAL archiving (which is always a good idea) in order to avoid replicas falling out of date using just the steaming replication.

**Comment by albertvaka** [comment]
Thanks for your reply, I'm noting down that command for the next time :)

I'm not sure how we got into this state though, we are using Postgres 9.6 and slots are enabled:

```
root@patroni-cluster1-keeper-0:/# patronictl show-config cluster1
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters: null
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

We are on version 1.3.3.

If you can see something wrong with that config that could have caused this problem, please let me know. Otherwise feel free to close the issue. 

Thanks again!

**Comment by bert-jan** [comment]
Recently i had the same issue.. one cluster member seemed to far behind to get back in sync..

(patroni)-bash-4.2$ patronictl -c mycluster.yml list
+------------+------------+--------------+--------+---------+-----------+
|  Cluster   |   Member   |     Host     |  Role  |  State  | Lag in MB |
+------------+------------+--------------+--------+---------+-----------+
| mycluster | pg01 | 172.16.1.1 |        | running |     752.0 |
| mycluster | pg02 | 172.16.1.2 | Leader | running |       0.0 |
| mycluster | pg03 | 172.16.1.3 |        | running |       0.0 |
+------------+------------+--------------+--------+---------+-----------+

What i did was stopping patroni/postgres on the node  (pg01) that had the issue.. i've cleaned up the archive directory and did a rsync on the archive directory from the leader node and started patroni.

**Comment by CyberDem0n** [comment]
There might be about a dozen of different reasons why replica is lagging behind the primary and it is your responsibility to monitor replication lag and act on it if the lag is growing.

Patroni can guaranty that the lagging replica will not be selected as a new primary.

> What i did was stopping patroni/postgres on the node (pg01) that had the issue.. i've cleaned up the archive directory and did a rsync on the archive directory from the leader node and started patroni.

Hmm. Are you talking about archive logs? Or you did something like reinitializing it from basebackup?
If the last one, I would recommend learning about `patronictl` tool:
```
$ patronictl reinit --help
Usage: patronictl.py reinit [OPTIONS] CLUSTER_NAME [MEMBER_NAMES]...

  Reinitialize cluster member
```

**Comment by bert-jan** [comment]
I did a rsync on the archivelog dir from the leader to the problematic host.
