### ISSUE TITLE
[Question] Remove cluster from DCS 

### ISSUE THREAD

**Issue by debraj-manna** [zalando/patroni#690]
We can remove the cluster from DCS like below :
```support@vrni-platform:/var/log/postgresql/patroni$ patronictl -c /etc/patroni/patroni.yml remove arkin
+---------+--------+------+------+-------+-----------+
| Cluster | Member | Host | Role | State | Lag in MB |
+---------+--------+------+------+-------+-----------+
+---------+--------+------+------+-------+-----------+
Please confirm the cluster name to remove: arkin
You are about to remove all information in DCS for arkin, please type: "Yes I am aware": Yes I am aware
```

Is it possible to delete it forcefully without having to confirm the cluster name and typing "Yes I am aware" ? 

Version - 1.3.6

**Comment by CyberDem0n** [comment]
Hi @debraj-manna,

It is a very destructive operation, therefore we decided to always ask confirmation.

**Comment by uspen** [comment]
Try
`curl -s -XDELETE "http://etcd:2379/v2/keys/postgresql/clustername/?recursive=true"`

**Comment by debraj-manna** [comment]
I am using zookeeper
