### ISSUE TITLE
Cleanup archive log on leader

### ISSUE THREAD

**Issue by bert-jan** [zalando/patroni#699]
Currently i have a 3 node patroni cluster and the 'leader' node keeps filling up the local disk with archive 
 logs because archive_cleanup does not run on the leader as described in issue 529 (https://github.com/zalando/patroni/issues/529). But if i change the archive_command to 'true' how does this work on a failover? Do i manually have to modify the new leader after failover? Or should i make 1 node permanent leader or run the pg_archivecleanup command manually on the leader node after pg_basebackup??

configuration snippet of all my nodes:

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        wal_keep_segments: 128
        max_wal_senders: 5
        max_replication_slots: 5
        wal_log_hints: "on"
        archive_mode: "on"
        archive_timeout: 600s
        archive_command: "cp -f %p /var/lib/pgsql/archive/%f"
        synchronous_commit: "on"
        synchronous_standby_names: "*"
      recovery_conf:
        restore_command: "cp -f /var/lib/pgsql/archive/%f %p"
        archive_cleanup_command: "pg_archivecleanup -d /var/lib/pgsql/archive %r"

**Comment by alexeyklyukin** [comment]
> Currently i have a 3 node patroni cluster and the 'leader' node keeps filling up the local disk with archive logs because archive_cleanup does not run on the leader as described in issue 529 (#529)

[archive_cleanup_command](https://www.postgresql.org/docs/current/static/archive-recovery-settings.html) never runs on the primary.

> But if i change the archive_command to 'true' how does this work on a failover?

As long as the standby keeps itself up-to-date by some other method (namely, streaming replication) it will be able to promote.

>  Do i manually have to modify the new leader after failover? 
No

> Or should i make 1 node permanent leader or run the pg_archivecleanup command manually on the leader node after pg_basebackup??

You seem to misunderstand the purpose of WAL archiving. Please, take a loook at https://www.postgresql.org/docs/current/static/continuous-archiving.html.

**Comment by bert-jan** [comment]
ok thanks for the clarification. i'm going to turn off archive_mode.
