### ISSUE TITLE
run startup-scripts/patroni on centos7(Probably postgresql-common does not installed)

### ISSUE THREAD

**Issue by yangdongzky** [zalando/patroni#705]
hi,
    I configuration startup-scripts/patroni and copy it to /etc/init.d . start on service

```
/etc/init.d/patroni start 
Probably postgresql-common does not installed.             [FAILED]
```

   Does this script support Debian only, not centos?
    i'm patroni version is 1.4.3,postgresql version is 10.1,system version is centos7.4

**Comment by CyberDem0n** [comment]
I think you need https://github.com/zalando/patroni/blob/master/extras/startup-scripts/patroni.service for centos.

Also I would recommend to look at https://github.com/cybertec-postgresql/patroni-packaging/blob/master/RPM/patroni.2.service
