### ISSUE TITLE
[Question] Are there any settings in patroni that allows us to set maximum replication lag in a cluster?

### ISSUE THREAD

**Issue by debraj-manna** [zalando/patroni#708]
Are there any settings in patroni that will stop writes in master if any slave lags by X bytes or T time ?

- Patroni - 1.4.4
- Postgres 10.4
- Number of Nodes - 3

I am not able to find any such thing in docs. Just wanted to confirm once.

**Comment by bert-jan** [comment]
You can configure for example the maximum_lag_on_failover: X
For example: maximum_lag_on_failover: 1048576
The purpose of patroni is providing high availability and failover (without manual intervention) so i think there is no parameter which will stop the master if one or more slaves are lagging. 
From my experience the master wil not failover to any slave that has a lag by X bytes..

**Comment by alexeyklyukin** [comment]
No. First, this is out of scope for Patroni that aims to deal with HA, not to be the swiss army knife of Postgres maintenance.  Second, there is no way in PostgreSQL to stop writes to an instant short of restarting it in read-only mode (in which case it will stop being a master). Third, the slave lag is usually variable and in your hypothetical case may lead to clients getting sporadic errors about the database being read-only.

If you need primary to stop accepting writes when the standby is not up-to-date - use synchronous replication.
