### ISSUE TITLE
Document synchronous_mode_strict in patroni/docs/replication_modes.rst and patroni/docs/SETTINGS.rst

### ISSUE THREAD

**Issue by alago197** [zalando/patroni#709]
A text would be like the one used in releases.rst where this funcionality was described (below). 

### Synchronous replication mode strict

Normally, when synchronous_mode is enabled and there are no replicas attached to the master, Patroni will disable synchronous replication in order to keep the master available for writes. The _synchronous_mode_strict_ option changes that. 

When it is set, Patroni will not disable the synchronous replication in a lack of replicas, effectively blocking all clients writing data to the master. In addition to the synchronous mode guarantee of preventing any data loss due to automatic failover, the strict mode ensures that each write is either durably stored on two nodes or not happening altogether if there is only one node in the cluster. #

**Comment by alexeyklyukin** [comment]
Merged at https://github.com/zalando/patroni/commit/41e5f58f2b9c3d63cc708d72b796c5c98eadb83a

Thank you for the report.
