### ISSUE TITLE
[Question] How does patronictl reinit work?

### ISSUE THREAD

**Issue by debraj-manna** [zalando/patroni#712]
Can someone let me know how does `patronictl reinit` reinitialises a cluster member? If this is ran on a slave will it delete the existing data and then take a complete back up from the master using the  method specified in the `create_replica_method` in `patroni.yml` ?

**Comment by alexeyklyukin** [comment]
@debraj-manna patronictl reinit removes the data directory for the cluster member of your choice (cannot be the master) and then reinitializes that member using first available `create_replica_method` methods (pg_basebackup by default). Depending on the method and Patroni configuration, it could be querying the master, or the replica (in case the replica is set as a source in the `clonefrom` tag), or an external WAL storage (i.e. restore from `S3` with `wal-e`).

Looks like we haven't yet documented `reinit`, so feel free to come up with the documentation PR if you feel it should be added.

**Comment by debraj-manna** [comment]
@alexeyklyukin I am not able to see anything under https://github.com/zalando/patroni/tree/master/docs for `patronictl`. So where do you think the documentation should go?

**Comment by alexeyklyukin** [comment]
Yeah, we don't actually have anything on patronictl in the first place. I think for that a new document has to be created.

The reinit functionality is provided by the corresponding REST API endpoint (https://github.com/zalando/patroni/blob/8a3b78ca7bb2bb6af1fe25921cfb5f08fe38325c/patroni/api.py#L283) , so perhaps https://patroni.readthedocs.io/en/latest/dynamic_configuration.html#rest-api is the right place to document the behavior of the REST endpoint.
