### ISSUE TITLE
haproxy source ip

### ISSUE THREAD

**Issue by patdenis** [zalando/patroni#719]
Hi,
I created a cluster in ha with Patroni + haproxy + keepalived.
The connections in Postgresql have as source ip, the ip of haproxy. how can I see the client's source ip?
thanks

**Comment by alago197** [comment]
This is not a Patroni issue, I think. 
By default, a balancer like haproxy replaces the source IP address with the haproxy's host address.   Read https://www.haproxy.com/blog/layer-4-load-balancing-nat-mode/ , https://www.haproxy.com/blog/howto-transparent-proxying-and-binding-with-haproxy-and-aloha-load-balancer/,  (haproxy +  tproxy support)
