### ISSUE TITLE
failed to start postgres

### ISSUE THREAD

**Issue by zpavlig** [zalando/patroni#720]
Hi. The following error occurs:
Do you need the Internet for patroni?
Thanks for any help
`
 patroni[8647]: File "/opt/app/patroni/lib/python2.7/site-packages/patroni/postgresql.py", line 1381, in follow
 patroni[8647]: self.start(timeout=timeout)
 patroni[8647]: File "/opt/app/patroni/lib/python2.7/site-packages/patroni/postgresql.py", line 846, in start
 patroni[8647]: self._write_postgresql_conf()
 patroni[8647]: File "/opt/app/patroni/lib/python2.7/site-packages/patroni/postgresql.py", line 1059, in _write_postgresql_conf
 patroni[8647]: os.rename(self._postgresql_conf, self._postgresql_base_conf)
 patroni[8647]: OSError: [Errno 2] No such file or directory
 patroni[8647]: localhost:5432 - no response
`

**Comment by alexeyklyukin** [comment]
No, you don't need any internet connection for Patorni. It seems you didn't have postgesql.conf in the usual place (pgdata/postgresql.conf) where Patroni expects to find it; if you use a distro-specific postgresq.conf location (i.e. /etc/postgresql/$version/postgresql.conf) you might want to set the `custom_conf` parameter in the PostgreSQL section of the configuration (see https://patroni.readthedocs.io/en/latest/SETTINGS.html#settings)
