### ISSUE TITLE
Every couple of days, the replicas crash. How can I debug ?

### ISSUE THREAD

**Issue by gpernelle** [zalando/patroni#722]
The replicas seem really unstable, but the master is fine. I need to reinit the replicas often.
Where should I start looking to identify the problem?

**Comment by CyberDem0n** [comment]
Hi,

what spilo image do you use?

**Comment by gpernelle** [comment]
i use this one: registry.opensource.zalan.do/acid/spilo-cdp-10:1.4-p8

**Comment by alexeyklyukin** [comment]
I'd suggest to first update to registry.opensource.zalan.do/acid/spilo-cdp-10:1.4-p18. Although we didn't observe any issues that cause the replica (as a Postgres process) to crash, it is always better to start with the most up-to-date image. 

Second, if it continues, you need to examine Patroni and Postgres (pg_log) logs on the crashed replica and look for the errors there.

**Comment by gpernelle** [comment]
Thank you. To update, is it enough to run kubeclt apply -f configmap.yaml, with the updated configmap?

**Comment by gpernelle** [comment]
This seems to have solve the issue, no more crashes since a week! thanks!
