### ISSUE TITLE
Little/minor proposed change in the docs for the REST API endpoints (https://github.com/zalando/patroni/blob/master/docs/SETTINGS.rst)

### ISSUE THREAD

**Issue by alago197** [zalando/patroni#725]
Hi,
Currently, they read as:

_REST API
connect_address: IP address and port to access the REST API.
listen: IP address and port that Patroni will listen to, to provide health-check information for HAProxy._

I suggest to change them to:

_REST API
connect_address: IP address (or hostname) and port, to access the REST API.
listen: IP address (or hostname) and port that Patroni will listen to, to provide health-check information for HAProxy (or any other load balancer capable of doing a HTTP "OPTION" or "GET" check.)_

I have this section working that way (with hostnames) without problems.  The added comment about HAProxy is because people are using other load balancers (as the http check OPTION/GET is common)

**Comment by alexeyklyukin** [comment]
I think the addition for the host names is good, although the description of the listen address is incomplete. This is the address that Patroni REST API listens on and it is used not only for ELB health-checks, but also for user queries (either directly or via the REST API), as well as for the health-checks by the cluster members during the leader election (to determine whether the master is still running or if there is a node which has a WAL position that is ahead of the one doing the query ). The connect_address is put in the member key in DCS, making it possible to translate the member name into the address to connect to its REST API.

We could also mention that the need for the connect_address spawns from the fact that one could set the listen_address to '*', making it impossible for the external clients to connect to. connect_address is optional; if it is not set, the 'listen_address' will be used instead.

Documentation PRs are welcome! :-)

**Comment by alago197** [comment]
ok Alexey, I'm on it..
