### ISSUE TITLE
local connection postgresql

### ISSUE THREAD

**Issue by zpavlig** [zalando/patroni#728]
Hello

I'm trying to connect to the database locally.:

```
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

is it possible to change this to connect locally?
thx

**Comment by alexeyklyukin** [comment]
@zpavlig there is nothing in Patroni that restricts you from setting `unix_socket_directories` in the PostgreSQL configuration.

**Comment by zpavlig** [comment]
ok, thx
