### ISSUE TITLE
Member status after it is stopped (shutdown)

### ISSUE THREAD

**Issue by tonys66** [zalando/patroni#732]
When a member is stopped, the status reported from "patronictl list" remains as "running" although the member is no longer running.  Eventually, the row reported from "patronictl list" goes away.  It would be good to see the status changed to "stopped".  Can the following two lines be added in the HA.shutdown method in patroni/ha.py after line 1170 to change the status to show it is stopped?

                self.state_handler.set_state('stopped')
                self.touch_member()

**Comment by CyberDem0n** [comment]
Implemented in https://github.com/zalando/patroni/pull/733
