### ISSUE TITLE
Complain when given a non-existing filename

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/patroni#739]
Right now if you supply a path that doesn't exist to patronictl (via `patronictl -c /path/to/patroni.yaml`) it will come eventually to config.py:_load_config_file that gobbles all errors coming from trying to open a non-existing filename, returning you nothing (you will get an error next saying that no available DCS methods are configured, which increases the user confusion for this particular situtation).

We should complain right away if the user told us to read the configuration from a non-existing file, possibly aborting the whole thing.

Seen at  https://github.com/zalando/patroni/issues/736

**Comment by mbanck** [comment]
Yeah it's really confusing and happened to me a couple of times as well.
