### ISSUE TITLE
explicitly set recovery_target_timeline in recovery.conf to actual master timeline

### ISSUE THREAD

**Issue by psuderevsky** [zalando/patroni#741]
Considering such **topology**:
Node1 - master
Node2 - standby
Node3 - standby
Using Barman for storing archived WALs. 
_barman-wal-restore_ utility is used in recovey_command to obtain missed WALs.

**Action:**
Node1 down, Node2 promoted. WALs with new timeline archived.
It is decided to rollback and recover Node1 as master.

**Result:**
Standbys won't work even after rewinding since automatically specified _recovery_target_timeline_ in _recovery.conf_ is "latest" and PostgreSQL will try to get WALs with timeline created after Node2 was promoted. 
`requested timeline N is not a child of this server's history`
_recovery.conf_ example:
`restore_command = 'barman-wal-restore -U barman -c /etc/barman.conf barman_host patroni_cluster %f %p'
recovery_target_timeline = 'latest'
standby_mode = 'on'
primary_conninfo = 'user=replicator password=None host=192.168.1.3 port=5432 sslmode=prefer sslcompression=1 application_name=node1'`

**Solution:**
Probably it would be usefull to set _recovery_target_timeline_ equal to current Master one.

**Comment by alexeyklyukin** [comment]
> It is decided to rollback and recover Node1 as master.

How did you rollback? Assuming you created another node from the prior base backup and restored it to some earlier point, wouldn't it create the timeline that is newer than  the one from the node2 to appear, allowing replicas with recovery_timeline='latest' to follow it?

**Comment by psuderevsky** [comment]
> How did you rollback?
In an example above rollback is just stop new master and start previous one (it was just stopped).
I'll descrive issue in other words: if wal archive for some reason contains files of timeline that is higher than the current master timiline, and recovery_target_timeline = 'latest', than standby servers will fail. 
That's why setting _recovery_target_timeline_ equal to current Master timeline would be more durable.
