### ISSUE TITLE
Question: Need help in getting the correct config for postgresql Server on different node 

### ISSUE THREAD

**Issue by cernerpradeep** [zalando/patroni#745]
I was able to setup patroni successfully. I am setting up patroni and server1 and postgresql-9.6 on server2 and server3. The issue I am facing is: Patroni is not able to reach the server2 nor 3. It fails with below error. PFB the config file.
-----------------------------------------------------------
Error log
-----------------------------------------------------------
$ patroni pg-1.yml
**/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
2018-07-20 11:28:17,517 INFO: Failed to import patroni.dcs.consul
2018-07-20 11:28:17,541 INFO: Selected new etcd server http://127.0.0.1:2379
2018-07-20 11:28:17,574 WARNING: Postgresql is not running.
2018-07-20 11:28:17,575 INFO: Lock owner: None; I am pg-1
2018-07-20 11:28:17,585 INFO: Lock owner: None; I am pg-1
2018-07-20 11:28:17,606 INFO: starting as a secondary
"root" execution of the PostgreSQL server is not permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromise.  See the documentation for
more information on how to properly start the server.
2018-07-20 11:28:17,660 INFO: postmaster pid=32450
server1:5432 - accepting connections
server1:5432 - accepting connections
2018-07-20 11:28:17,727 INFO: Lock owner: None; I am pg-1
2018-07-20 11:28:17,728 INFO: establishing a new patroni connection to the postgres cluster
2018-07-20 11:28:17,739 INFO: failed to start postgres
2018-07-20 11:28:27,726 WARNING: Postgresql is not running.**

-----------------------------------------------------------
pg-1.yml
-----------------------------------------------------------
scope: mef
name: pg-1

restapi:
  listen: 0.0.0.0:8008
  connect_address: 127.0.0.1:8008

etcd:
  host: 127.0.0.1:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 5
        max_replication_slots: 5
        checkpoint_timeout: 30

  initdb:
  - encoding: UTF8

  pg_hba:
  - host all dba all md5
  - host replication replica all md5

  users:
    postgres:
      password: postgres
      options:
        - createrole
        - createdb
    replica:
      password: aqwe123@
      options:
        - replication

postgresql:
  listen: differentNode1:5432
  connect_address: differentNode1:5432
  data_dir: /var/lib/pgsql/9.6/data
  config_dir: /var/lib/pgsql/9.6/data
  bin_dir: /usr/pgsql-9.6/bin/
  authentication:
    replication:
      username: replica
      password: aqwe123@
    superuser:
      username: postgres
      password: postgres
  parameters:
    unix_socket_directories: '/tmp'

**Comment by alexeyklyukin** [comment]
```
"root" execution of the PostgreSQL server is not permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromise. See the documentation for
more information on how to properly start the server.
```
It seems you start Patroni as the root user. This is generally a very bad idea from the security standpoint, and postgres specifically disallows being started as a root. Use another system user (i.e. postgres) for starting Patroni.

**Comment by cernerpradeep** [comment]
Yes. That was taken care. However we get the below error. We checked /etc/hosts, everything looks good. Please let me know how this can be fixed.


2018-07-24 08:01:01,457 INFO: starting as a secondary
2018-07-24 08:01:01,508 INFO: postmaster pid=6313
< 2018-07-24 08:01:01.511 CDT > LOG:  could not bind IPv4 socket: Cannot assign requested address
< 2018-07-24 08:01:01.511 CDT > HINT:  Is another postmaster already running on port 5434? If not, wait a few seconds and retry.
< 2018-07-24 08:01:01.511 CDT > WARNING:  could not create listen socket for "server1"
< 2018-07-24 08:01:01.511 CDT > FATAL:  could not create any TCP/IP sockets
< 2018-07-24 08:01:01.511 CDT > LOG:  database system is shut down
server1:5434 - no response
2018-07-24 08:01:02,523 ERROR: postmaster is not running
2018-07-24 08:01:02,530 INFO: Lock owner: pg-1; I am pg-3
2018-07-24 08:01:02,533 INFO: failed to start postgres
^C2018-07-24 08:01:03,400 INFO: Lock owner: pg-1; I am pg-3

**Comment by nordurljosahvida** [comment]
@alexeyklyukin @cernerpradeep how did you fix patroni starting postgres *not* as root? I can't figure out how to fix the "root execution of postgres" error. Thanks

**Comment by ants** [comment]
Start patroni as the user that should run postgres.
