### ISSUE TITLE
Patroni not starting

### ISSUE THREAD

**Issue by billikill** [zalando/patroni#755]
Started Runners to orchestrate a high-availability PostgreSQL.
 systemd: Starting Runners to orchestrate a high-availability PostgreSQL...
 patroni: 2018-07-30 11:34:20,339 INFO: Failed to import patroni.dcs.consul
 patroni: 2018-07-30 11:34:20,357 INFO: Selected new etcd server http://10.200.19.50:2379
 patroni: 2018-07-30 11:34:20,365 INFO: Lock owner: None; I am jr-conf-app-01
 patroni: 2018-07-30 11:34:20,367 INFO: trying to bootstrap a new cluster
 patroni: 2018-07-30 11:34:20,368 ERROR: Exception during execution of long running task bootstrap
 patroni: Traceback (most recent call last):
 patroni: File "/usr/lib/python2.7/site-packages/patroni/async_executor.py", line 97, in run
 patroni: wakeup = func(*args) if args else func()
 patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1561, in bootstrap
 patroni: return do_initialize(config) and self.write_pg_hba(pg_hba) and self.save_configuration_files() \
 patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 546, in _initdb
 patroni: os.write(fd, self._superuser['password'].encode('utf-8'))
 patroni: AttributeError: 'int' object has no attribute 'encode'
 patroni: 2018-07-30 11:34:20,369 INFO: removing initialize key after failed attempt to bootstrap the cluster
 patroni: 2018-07-30 11:34:20,370 INFO: renaming data directory to /data/patroni_2018-07-30-11-34-20
 patroni: 2018-07-30 11:34:20,370 ERROR: Could not rename data directory /data/patroni
 patroni: Traceback (most recent call last):
 patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1603, in move_data_directory
 patroni: os.rename(self._data_dir, new_name)
 patroni: OSError: [Errno 13] Permission denied
 patroni: 2018-07-30 11:34:20,864 INFO: Lock owner: None; I am jr-conf-app-01
 patroni: Traceback (most recent call last):
 patroni: File "/usr/bin/patroni", line 11, in <module>
 patroni: load_entry_point('patroni==1.4.4', 'console_scripts', 'patroni')()
 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 176, in main
 patroni: return patroni_main()
 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 145, in patroni_main
 patroni: patroni.run()
 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 114, in run
 patroni: logger.info(self.ha.run_cycle())
 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1164, in run_cycle
 patroni: info = self._run_cycle()
 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1077, in _run_cycle
 patroni: return self.post_bootstrap()
 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 976, in post_bootstrap
 patroni: self.cancel_initialization()
 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 971, in cancel_initialization
 patroni: raise PatroniException('Failed to bootstrap cluster')
 patroni: patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
 systemd: patroni.service: main process exited, code=exited, status=1/FAILURE
 systemd: Unit patroni.service entered failed state.
 systemd: patroni.service failed.

**Comment by CyberDem0n** [comment]
` patroni: AttributeError: 'int' object has no attribute 'encode'` -- your superuser password has only numbers (what is not good for security). Please quote it: `'12345'` in the configuration file

**Comment by billikill** [comment]
Hi, , but patroni not starting 

postgresql:
    listen: 10.200.19.50:5432
    connect_address: 10.200.19.50:5432
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: rep-pass
        superuser:
            username: postgres
            password: '1234'



Started Runners to orchestrate a high-availability PostgreSQL.
Jul 30 11:42:23 JR-Conf-APP-01 systemd: Starting Runners to orchestrate a high-availability PostgreSQL...
Jul 30 11:42:24 JR-Conf-APP-01 patroni: 2018-07-30 11:42:24,248 INFO: Failed to import patroni.dcs.consul
Jul 30 11:42:24 JR-Conf-APP-01 patroni: 2018-07-30 11:42:24,266 INFO: Selected new etcd server http://10.200.19.50:2379
Jul 30 11:42:24 JR-Conf-APP-01 patroni: 2018-07-30 11:42:24,274 INFO: Lock owner: None; I am jr-conf-app-01
Jul 30 11:42:24 JR-Conf-APP-01 patroni: 2018-07-30 11:42:24,276 INFO: trying to bootstrap a new cluster
Jul 30 11:42:24 JR-Conf-APP-01 patroni: 2018-07-30 11:42:24,281 ERROR: Exception during execution of long running task bootstrap
Jul 30 11:42:24 JR-Conf-APP-01 patroni: Traceback (most recent call last):
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib/python2.7/site-packages/patroni/async_executor.py", line 97, in run
Jul 30 11:42:24 JR-Conf-APP-01 patroni: wakeup = func(*args) if args else func()
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1561, in bootstrap
Jul 30 11:42:24 JR-Conf-APP-01 patroni: return do_initialize(config) and self.write_pg_hba(pg_hba) and self.save_configuration_files() \
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 551, in _initdb
Jul 30 11:42:24 JR-Conf-APP-01 patroni: ret = self.pg_ctl('initdb', *options)
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 281, in pg_ctl
Jul 30 11:42:24 JR-Conf-APP-01 patroni: return subprocess.call(pg_ctl + ['-D', self._data_dir] + list(args), **kwargs) == 0
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib64/python2.7/subprocess.py", line 524, in call
Jul 30 11:42:24 JR-Conf-APP-01 patroni: return Popen(*popenargs, **kwargs).wait()
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
Jul 30 11:42:24 JR-Conf-APP-01 patroni: errread, errwrite)
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
Jul 30 11:42:24 JR-Conf-APP-01 patroni: raise child_exception
Jul 30 11:42:24 JR-Conf-APP-01 patroni: OSError: [Errno 2] No such file or directory
Jul 30 11:42:24 JR-Conf-APP-01 patroni: 2018-07-30 11:42:24,285 INFO: removing initialize key after failed attempt to bootstrap the cluster
Jul 30 11:42:24 JR-Conf-APP-01 patroni: 2018-07-30 11:42:24,286 INFO: renaming data directory to /data/patroni_2018-07-30-11-42-24
Jul 30 11:42:24 JR-Conf-APP-01 patroni: 2018-07-30 11:42:24,287 ERROR: Could not rename data directory /data/patroni
Jul 30 11:42:24 JR-Conf-APP-01 patroni: Traceback (most recent call last):
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1603, in move_data_directory
Jul 30 11:42:24 JR-Conf-APP-01 patroni: os.rename(self._data_dir, new_name)
Jul 30 11:42:24 JR-Conf-APP-01 patroni: OSError: [Errno 13] Permission denied
Jul 30 11:42:24 JR-Conf-APP-01 patroni: 2018-07-30 11:42:24,773 INFO: Lock owner: None; I am jr-conf-app-01
Jul 30 11:42:24 JR-Conf-APP-01 patroni: Traceback (most recent call last):
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/bin/patroni", line 11, in <module>
Jul 30 11:42:24 JR-Conf-APP-01 patroni: load_entry_point('patroni==1.4.4', 'console_scripts', 'patroni')()
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 176, in main
Jul 30 11:42:24 JR-Conf-APP-01 patroni: return patroni_main()
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 145, in patroni_main
Jul 30 11:42:24 JR-Conf-APP-01 patroni: patroni.run()
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 114, in run
Jul 30 11:42:24 JR-Conf-APP-01 patroni: logger.info(self.ha.run_cycle())
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1164, in run_cycle
Jul 30 11:42:24 JR-Conf-APP-01 patroni: info = self._run_cycle()
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1077, in _run_cycle
Jul 30 11:42:24 JR-Conf-APP-01 patroni: return self.post_bootstrap()
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 976, in post_bootstrap
Jul 30 11:42:24 JR-Conf-APP-01 patroni: self.cancel_initialization()
Jul 30 11:42:24 JR-Conf-APP-01 patroni: File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 971, in cancel_initialization
Jul 30 11:42:24 JR-Conf-APP-01 patroni: raise PatroniException('Failed to bootstrap cluster')
Jul 30 11:42:24 JR-Conf-APP-01 patroni: patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
Jul 30 11:42:24 JR-Conf-APP-01 systemd: patroni.service: main process exited, code=exited, status=1/FAILURE
Jul 30 11:42:24 JR-Conf-APP-01 systemd: Unit patroni.service entered failed state.
Jul 30 11:42:24 JR-Conf-APP-01 systemd: patroni.service failed.

**Comment by CyberDem0n** [comment]
Now it can't find postgres binaries:
https://github.com/zalando/patroni/issues/714
https://github.com/zalando/patroni/issues/569
https://github.com/zalando/patroni/issues/497

**Comment by billikill** [comment]
Thank
