### ISSUE TITLE
patroni not start

### ISSUE THREAD

**Issue by billikill** [zalando/patroni#756]
Plz, help me.
Started Runners to orchestrate a high-availability PostgreSQL.
Jul 30 17:10:15 JR-Conf-APP-01.orglot.office systemd[1]: Starting Runners to orchestrate a high-availability PostgreSQL...
Jul 30 17:10:16 JR-Conf-APP-01.orglot.office patroni[17867]: 2018-07-30 17:10:16,047 INFO: Failed to import patroni.dcs.consul
Jul 30 17:10:16 JR-Conf-APP-01.orglot.office patroni[17867]: 2018-07-30 17:10:16,077 INFO: Selected new etcd server http://10.200.19.50:2379
Jul 30 17:10:16 JR-Conf-APP-01.orglot.office patroni[17867]: 2018-07-30 17:10:16,095 CRITICAL: system ID mismatch, node jr-conf-app-01 belongs to a different cluster: 6583990523194021581 != 6583943263285112373
Jul 30 17:10:16 JR-Conf-APP-01.orglot.office patroni[17867]: 2018-07-30 17:10:16,588 INFO: Lock owner: None; I am jr-conf-app-01
Jul 30 17:10:16 JR-Conf-APP-01.orglot.office systemd[1]: patroni.service: main process exited, code=exited, status=1/FAILURE
Jul 30 17:10:16 JR-Conf-APP-01.orglot.office systemd[1]: Unit patroni.service entered failed state.
Jul 30 17:10:16 JR-Conf-APP-01.orglot.office systemd[1]: patroni.service failed.

**Comment by CyberDem0n** [comment]
please read this comment: https://github.com/zalando/patroni/issues/575#issuecomment-351319022

**Comment by billikill** [comment]
thank
