### ISSUE TITLE
patroni not see list

### ISSUE THREAD

**Issue by billikill** [zalando/patroni#758]
ul 31 12:00:04 JR-Conf-APP-01.orglot.office systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
Jul 31 12:00:04 JR-Conf-APP-01.orglot.office systemd[1]: Starting Runners to orchestrate a high-availability PostgreSQL...
Jul 31 12:00:04 JR-Conf-APP-01.orglot.office patroni[14824]: 2018-07-31 12:00:04,533 INFO: Failed to import patroni.dcs.consul
Jul 31 12:00:04 JR-Conf-APP-01.orglot.office patroni[14824]: 2018-07-31 12:00:04,552 INFO: Selected new etcd server http://10.200.19.50:2379
Jul 31 12:00:04 JR-Conf-APP-01.orglot.office patroni[14824]: 2018-07-31 12:00:04,559 INFO: Lock owner: None; I am jr-conf-app-01
Jul 31 12:00:04 JR-Conf-APP-01.orglot.office patroni[14824]: 2018-07-31 12:00:04,561 INFO: waiting for leader to bootstrap
[alexey.bazhenov@JR-Conf-APP-01 ~]$ patronictl -c /etc/patroni/patroni.yml list jira_1
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: zookeeper, exhibitor, etcd'

**Comment by billikill** [comment]
hi, i follow it, patroni work,  but not created cluster
Jul 31 15:36:49 jr-conf-app-02 patroni[30729]: 2018-07-31 15:36:49,706 INFO: Lock owner: None; I am jr-conf-app-02
Jul 31 15:36:49 jr-conf-app-02 patroni[30729]: 2018-07-31 15:36:49,708 INFO: waiting for leader to bootstrap
Jul 31 15:36:59 jr-conf-app-02 patroni[30729]: 2018-07-31 15:36:59,707 INFO: Lock owner: None; I am jr-conf-app-02
Jul 31 15:36:59 jr-conf-app-02 patroni[30729]: 2018-07-31 15:36:59,709 INFO: waiting for leader to bootstrap
Jul 31 15:37:09 jr-conf-app-02 patroni[30729]: 2018-07-31 15:37:09,709 INFO: Lock owner: None; I am jr-conf-app-02
Jul 31 15:37:09 jr-conf-app-02 patroni[30729]: 2018-07-31 15:37:09,712 INFO: waiting for leader to bootstrap
Jul 31 15:37:19 jr-conf-app-02 patroni[30729]: 2018-07-31 15:37:19,708 INFO: Lock owner: None; I am jr-conf-app-02
Jul 31 15:37:19 jr-conf-app-02 patroni[30729]: 2018-07-31 15:37:19,711 INFO: waiting for leader to bootstrap
Jul 31 15:37:29 jr-conf-app-02 patroni[30729]: 2018-07-31 15:37:29,709 INFO: Lock owner: None; I am jr-conf-app-02
Jul 31 15:37:29 jr-conf-app-02 patroni[30729]: 2018-07-31 15:37:29,712 INFO: waiting for leader to bootstrap

**Comment by billikill** [comment]
and  change listen to *,  patroni not starting

"It should be possible to connect to it as: psql -h 10.80.80.195

also you can modify config files to listen on localhost:

postgresql:
  listen: 10.80.80.195,127.0.0.1:5432
  connect_address: 10.80.80.195:5432
or even:

postgresql:
  listen: *:5432
  connect_address: 10.80.80.195:5432"

**Comment by CyberDem0n** [comment]
It looks like you started patroni, stopped it and removed data directory.
Etcd still contains information that such cluster was initialized once.
Please change cluster name or clean up etcd.

**Comment by billikill** [comment]
i change name cluster, but patroni not create cluster

Jul 31 13:06:09 JR-Conf-APP-01.orglot.office patroni[19616]: 2018-07-31 13:06:09,017 WARNING: Postgresql is not running.
Jul 31 13:06:09 JR-Conf-APP-01.orglot.office patroni[19616]: 2018-07-31 13:06:09,017 INFO: Lock owner: None; I am jr-conf-app-01
Jul 31 13:06:09 JR-Conf-APP-01.orglot.office patroni[19616]: 2018-07-31 13:06:09,024 INFO: Lock owner: None; I am jr-conf-app-01
Jul 31 13:06:09 JR-Conf-APP-01.orglot.office patroni[19616]: 2018-07-31 13:06:09,048 INFO: starting as a secondary
Jul 31 13:06:09 JR-Conf-APP-01.orglot.office patroni[19616]: < 2018-07-31 13:06:09.279 MSK > LOG:  could not bind IPv4 socket: Cannot assign requested address
Jul 31 13:06:09 JR-Conf-APP-01.orglot.office patroni[19616]: < 2018-07-31 13:06:09.279 MSK > HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
Jul 31 13:06:09 JR-Conf-APP-01.orglot.office patroni[19616]: < 2018-07-31 13:06:09.279 MSK > WARNING:  could not create listen socket for "10.20.19.50"
Jul 31 13:06:09 JR-Conf-APP-01.orglot.office patroni[19616]: < 2018-07-31 13:06:09.279 MSK > FATAL:  could not create any TCP/IP sockets
Jul 31 13:06:09 JR-Conf-APP-01.orglot.office patroni[19616]: < 2018-07-31 13:06:09.279 MSK > LOG:  database system is shut down

Jul 31 16:04:58 jr-conf-app-02 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
Jul 31 16:04:58 jr-conf-app-02 systemd[1]: Starting Runners to orchestrate a high-availability PostgreSQL...
Jul 31 16:04:59 jr-conf-app-02 patroni[1174]: 2018-07-31 16:04:59,367 INFO: Failed to import patroni.dcs.consul
Jul 31 16:04:59 jr-conf-app-02 patroni[1174]: 2018-07-31 16:04:59,389 INFO: Selected new etcd server http://10.2...:2379
Jul 31 16:04:59 jr-conf-app-02 patroni[1174]: 2018-07-31 16:04:59,406 INFO: Lock owner: None; I am jr-conf-app-02
Jul 31 16:04:59 jr-conf-app-02 patroni[1174]: 2018-07-31 16:04:59,409 INFO: waiting for leader to bootstrap
Jul 31 16:05:09 jr-conf-app-02 patroni[1174]: 2018-07-31 16:05:09,407 INFO: Lock owner: None; I am jr-conf-app-02
Jul 31 16:05:09 jr-conf-app-02 patroni[1174]: 2018-07-31 16:05:09,410 INFO: waiting for leader to bootstrap
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by billikill** [comment]
hi,  i have error for start patroni in slave 

 pg_basebackup: could not connect to server: FATAL:  password authentication failed for user "replicator"
Jul 31 17:25:05 jr-conf-app-02 patroni: password retrieved from file "/tmp/pgpass"
Jul 31 17:25:05 jr-conf-app-02 patroni: 2018-07-31 17:25:05,066 ERROR: Error when fetching backup: pg_basebackup exited with code=1
Jul 31 17:25:05 jr-conf-app-02 patroni: 2018-07-31 17:25:05,066 ERROR: failed to bootstrap from leader 'jr-conf-app-01'
Jul 31 17:25:05 jr-conf-app-02 patroni: 2018-07-31 17:25:05,066 INFO: Removing data directory: /data/patroni
Jul 31 17:25:05 jr-conf-app-02 patroni: 2018-07-31 17:25:05,066 ERROR: Could not remove data directory /data/patroni
Jul 31 17:25:05 jr-conf-app-02 patroni: Traceback (most recent call last):
Jul 31 17:25:05 jr-conf-app-02 patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1618, in remove_data_directory
Jul 31 17:25:05 jr-conf-app-02 patroni: shutil.rmtree(self._data_dir)
Jul 31 17:25:05 jr-conf-app-02 patroni: File "/usr/lib64/python2.7/shutil.py", line 256, in rmtree
Jul 31 17:25:05 jr-conf-app-02 patroni: onerror(os.rmdir, path, sys.exc_info())
Jul 31 17:25:05 jr-conf-app-02 patroni: File "/usr/lib64/python2.7/shutil.py", line 254, in rmtree
Jul 31 17:25:05 jr-conf-app-02 patroni: os.rmdir(path)
Jul 31 17:25:05 jr-conf-app-02 patroni: OSError: [Errno 13] Permission denied: '/data/patroni'
Jul 31 17:25:05 jr-conf-app-02 patroni: 2018-07-31 17:25:05,067 INFO: renaming data directory to /data/patroni_2018-07-31-17-25-05
Jul 31 17:25:05 jr-conf-app-02 patroni: 2018-07-31 17:25:05,067 ERROR: Could not rename data directory /data/patroni
Jul 31 17:25:05 jr-conf-app-02 patroni: Traceback (most recent call last):
Jul 31 17:25:05 jr-conf-app-02 patroni: File "/usr/lib/python2.7/site-packages/patroni/postgresql.py", line 1603, in move_data_directory
Jul 31 17:25:05 jr-conf-app-02 patroni: os.rename(self._data_dir, new_name)
Jul 31 17:25:05 jr-conf-app-02 patroni: OSError: [Errno 13] Permission denied

**Comment by alago197** [comment]
Hi,

I suggest you start again from scratch,  because some of the errores are apparently related to wrong permissions on the "/data/patroni" data directory.  These kind of errors should be easy for you to discover and correct them, following the indications in the web page @CyberDem0n pointed above.

Also, recheck your patroni's YAML configuration file in the pg_hba section, as there seems to be errors regarding authentication too ("password authentication failed for user "replicator"")

**Comment by billikill** [comment]
hi , i am stupid ))
user "replicator" not had role REPLICATION
