### ISSUE TITLE
[Question] Is there a possibility to know that slave is out of cluster

### ISSUE THREAD

**Issue by anikin-aa** [zalando/patroni#760]
Guys, Hello !

I want to know is there a possibility to know that slave is out of cluster. Is it possible to check somehow ?
May be there is some kind of hooks (or may be such kind of hooks can be implemented).   
Or I can check DCS ?

**Comment by alago197** [comment]
Hi,

Several ways:
1.- You can check via the patronictl "list" command the current cluster membership status.

2.- You can query DCS for the list of members at any moment. For example (for ETCD clusters):  

          $ curl http://machine:2379/v2/(members|machines)

      or via etcdctl:

         $ etcdctl ls --recursive

4.- You can query also Patroni REST API for the status of a given node at any time:

         $ http  http://<node>:8008/patroni

**Comment by anikin-aa** [comment]
@alago197 thank you for Your answer. But I need to know this at the moment of slave loss.

Actually, I've got next set up. 
Postgresql 10 version, 2 slaves and sync replication using `synchronous_standby_names` parameter. And its got value like 
```
synchronous_standby_names = 'ANY 2("patroni-0", "patroni-1")';
```
where is patroni-0, patroni-1 is slaves. But if some of the replicas failed, i need to change the parameter, remove the failed slave from quorum of sync replication. 

So, for example, patroni master do not know anything about slave loss, right ? 

more about quorum commit
https://paquier.xyz/postgresql-2/postgres-10-quorum-sync/

**Comment by alago197** [comment]
Yes, in principle, you can't tell from the master logs (say, for example, that patroni is logging to syslog) that a slave failed.  But, well, as said, you can always write a simple script to monitor at intervals the DCS (or the patronictl list output, or as said the Patroni REST API), put it to run in cron (or via a daemon), and act on any change of status on the members.

In the case of ETCD, and if the fault of the slave involved a halt of the node itself (or unresponsiveness), etcd will log "abundantly" (clearly) the fault or loss (you will see in the other nodes a "loss of streaming connection with node xxxxxx") , in the rest of the other node,s including the one with the master role.  So you can act too via tracking the syslog of any of the nodes.

I suggest you take a peek to (for example, there are myriads of this kind of utilities as you know) SEC, an event correlator utility (https://simple-evcorr.github.io/) .  

Or even the excellent monitoring system of Pgwatch (https://github.com/cybertec-postgresql/pgwatch2) from the guys at Cybertec.  I use it for routinely monitor (via alerting of its dashboards) and works very nicely.

Also, check if https://github.com/NaturalHistoryMuseum/plusmoin would be of interest to you.

**Comment by anikin-aa** [comment]
@alago197 again, thank you for your answer.

> In the case of ETCD   

But I'm using Kubernetes as DCS, and there is even no info about the members of the cluster. So its impossible to do.

As for me, this one

> you can always write a simple script to monitor at intervals the DCS

looks like a bad thing to do. I think, such kind of logic should be placed somewhere in Patroni, am I right ?

**Comment by alago197** [comment]
> looks like a bad thing to do. I think, such kind of logic should be placed somewhere in Patroni, am I right ?

I think that code contributions are welcomed for that. Honestly, I'm not clear at which points of the code a new callback detecting a loss of a slave would be appropiate.

**Comment by ants** [comment]
I started work on a feature that should solve this use case. Current work is in #672. I plan to pick this up again after my vacation.

**Comment by anikin-aa** [comment]
Thank you,
resolving the issue.
