### ISSUE TITLE
Not showing cluster list

### ISSUE THREAD

**Issue by billikill** [zalando/patroni#761]
Hello
patronictl -c /etc/patroni/patroni.yml list
2018-08-02 10:18:28,778 - WARNING - Listing members: No cluster names were provided
but cluster runing

**Comment by ysharoiko** [comment]
How did you solve. I am also getting 
- Listing members: No cluster names were provided

**Comment by ykdhan** [comment]
@ysharoiko So what was the problem? Did you just add those last two lines of code in the yml file?

**Comment by naveenrajm7** [comment]
@ykdhan I had the same issue. 
In my case, there was a permission issue . just make sure the user has access to config file patroni.yml

```bash
-bash-4.2$ patronictl -c /etc/patroni/patroni.yml list
2021-03-09 15:43:31,802 - WARNING - Listing members: No cluster names were provided
-bash-4.2$ ls /etc/patroni/patroni
ls: cannot access /etc/patroni/patroni_env.conf: Permission denied
ls: cannot access /etc/patroni/patroni.yml: Permission denied
```

Switched to root user who had permission.
```bash
-bash-4.2$ su root
Password:
[root@PostgresDB1 vagrant]#
[root@PostgresDB1 vagrant]# patronictl -c /etc/patroni/patroni.yml list
+------------------+-------------+---------------+--------+---------+----+-----------+
|     Cluster      |    Member   |      Host     |  Role  |  State  | TL | Lag in MB |
+------------------+-------------+---------------+--------+---------+----+-----------+
| postgres-cluster | PostgresDB1 | 192.168.32.11 | Leader | running |  1 |         0 |
| postgres-cluster | PostgresDB2 | 192.168.32.12 |        | running |    |         0 |
| postgres-cluster | PostgresDB3 | 192.168.32.13 |        | running |    |         0 |
+------------------+-------------+---------------+--------+---------+----+-----------+
```

**Comment by B-Mukul** [comment]
Hi everyone 
For this error " WARNING - Listing members: No cluster names were provided:" 

Simply create a file  /etc/profile.d/patroni.sh which contains the following enty: 
       export PATRONICTL_CONFIG_FILE=/etc/patroni/patroni.yml

Then, after saving this file, run the following two commands also.
# systemctl daemon-reload
# systemctl restart patroni

Now the "patronictl list" command will show all the members.

 Hope this error is gone forever now.
