### ISSUE TITLE
Error installing patroni via pip (CentOS7)

### ISSUE THREAD

**Issue by glimberg** [zalando/patroni#763]
Python 2.7, epel version of python-pip package

```
# pip install patroni[consul]
Collecting patroni[consul]
  Downloading https://files.pythonhosted.org/packages/38/bc/89c16d9505205ae516d99d52ee513df59771364c9b098cc0c7dc690a6309/patroni-1.4.5.tar.gz (100kB)
    100% |████████████████████████████████| 102kB 3.3MB/s
    Complete output from command python setup.py egg_info:
    error in patroni setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
```

**Comment by CyberDem0n** [comment]
Hi @glimberg,

it seems something is wrong with `setuptools` on your system.
Can you please check what version of setuptools you have: `python -c 'import setuptools; print(setuptools.__version__)'`

After that please upgrade it to the latest version (pip install setuptools --upgrade) and try to install patroni once again.

**Comment by glimberg** [comment]
that was it
