### ISSUE TITLE
What is pg_ctl_start?

### ISSUE THREAD

**Issue by twelfthdoctor** [zalando/patroni#765]
Hello. In your code (patroni/postmaster.py, line 157, method "start") you're trying to call a mysterious command - pg_ctl_start
` proc = call_self(['pg_ctl_start', pgcommand, '-D', data_dir,
                          '--config-file={}'.format(conf)] + options, close_fds=True,
                         preexec_fn=os.setsid, stdout=subprocess.PIPE, env=env)`
Unfortunately, I can't run patroni because of these errors:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/patroni/async_executor.py", line 97, in run
    wakeup = func(*args) if args else func()
  File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql.py", line 1430, in follow
    self.start(timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/patroni/postgresql.py", line 910, in start
    options)
  File "/usr/local/lib/python3.5/dist-packages/patroni/postmaster.py", line 160, in start
    pid = int(proc.stdout.readline().strip())
ValueError: invalid literal for int() with base 10: b'Usage: /usr/local/bin/patroni config.yml'
240.243.0.238:5432 - no response
2018-08-06 07:51:49,233 INFO: Lock owner: None; I am postgresql0
2018-08-06 07:51:49,239 INFO: failed to start postgres
^C2018-08-06 07:51:49,622 INFO: Lock owner: None; I am postgresql0
`
What is it? Is there a mistake?

**Comment by CyberDem0n** [comment]
Hi @twelfthdoctor,

It seems that Patroni can't find the postgres binaries (`postgres`, `pg_rewind`, `initdb` and so on).
Please verify that binaries are available in the default PATH or specify path to binaries in the `postgresql.bin_dir` section of Patroni config file.

**Comment by twelfthdoctor** [comment]
@CyberDem0n but there is no such file at all

**Comment by twelfthdoctor** [comment]
I mean pg_ctl_start

**Comment by CyberDem0n** [comment]
If you start postgres via pg_ctl, there is no way to know the pid of started postmaster process, therefore Patroni re-implements behavior of pg_ctl by executing itself and executing postgres from the child process: https://github.com/zalando/patroni/blob/master/patroni/__init__.py#L177-L178

Your problem is not with Patroni but with postgres.
Are you able to start postgres manually?
Can it be that you are starting Patroni as a root user?

**Comment by twelfthdoctor** [comment]
I'm starting Patroni as postgres. Yes, I'm able to start postgres manually.

**Comment by CyberDem0n** [comment]
Can you share the Patroni config?

**Comment by twelfthdoctor** [comment]
`scope: postgres
namespace: /db/
name: postgresql0
bin_dir: /usr/lib/postgresql/10/bin
restapi:
    listen: 240.243.0.238:8008
    connect_address: 240.243.0.238:8008

etcd:
    host: 127.0.0.1:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 trust
    - host replication replicator 240.243.0.238/0 trust
    - host replication replicator 240.243.0.17/0 trust

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 240.243.0.238:5432
    connect_address: 240.243.0.238:5432
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: rep-pass
        superuser:
            username: postgres
            password: secretpassword
    parameters:
        unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
`

**Comment by CyberDem0n** [comment]
why `bin_dir: /usr/lib/postgresql/10/bin` is not in the `postgresql` section?

**Comment by twelfthdoctor** [comment]
@CyberDem0n thank you. I've solved the problem.
Is a watchdog device necessary for patroni? Patroni is running inside an LXC container without it.
(Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog')

**Comment by CyberDem0n** [comment]
No, if you want you can disable it.
More information about watchdog is [here](http://patroni.readthedocs.io/en/latest/watchdog.html) and [here](http://patroni.readthedocs.io/en/latest/SETTINGS.html#watchdog)
