### ISSUE TITLE
Register Services in Consul

### ISSUE THREAD

**Issue by glimberg** [zalando/patroni#771]
It would be nice to have Patroni register services for Postgres Master & Slaves in Consul.

In my particular configuration I have Consul set up to do service discovery via DNS.  I set my database clients to connect to `postgres-master.service.consul:5432` if they want read-write access, or `postgres.service.consul:5432` if they only need read access. In order to do this I have to run a service check on all N Postgres/Patroni servers, where all but 1 are continually failing and cluttering up logs with check failures because it's not the master.  

When the master state changes on the nodes, it would be helpful to have Patroni to ether register itself with Consul as the master postgresql service, or deregister itself.

https://www.consul.io/api/agent/service.html

**Comment by 3manuek** [comment]
It seems to me that the [python-consul base](https://github.com/cablehead/python-consul/blob/master/consul/base.py) supports registering services only through local consul agent. That probably will force you to use agents on the nodes and check this at Patroni startup. But, any solution for _checking_ a service based on Consul will end up using an agent anyways.
