### ISSUE TITLE
[Question] - I am leader but not owner of the session. What does this log mean?

### ISSUE THREAD

**Issue by debraj-manna** [zalando/patroni#774]
I am using patroni 1.4.4 with zookeeper and postgres 10 on Ubuntu 14.

After a node reboot I am seeing an exception in log like below

```
2018-08-13 11:27:08,481 WARNING: Can not get cluster from dcs
2018-08-13 11:27:08,486 INFO: I am leader but not owner of the session. Removing leader node
2018-08-13 11:27:08,491 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/zookeeper.py", line 205, in _load_cluster
    self._client.retry(self._inner_load_cluster)
  File "/usr/local/lib/python2.7/dist-packages/kazoo/client.py", line 272, in _retry
    return self._retry.copy()(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kazoo/retry.py", line 124, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/patroni/dcs/zookeeper.py", line 187, in _inner_load_cluster
    self._client.delete(self.leader_path)
  File "/usr/local/lib/python2.7/dist-packages/kazoo/client.py", line 1310, in delete
    return self.delete_async(path, version).get()
  File "/usr/local/lib/python2.7/dist-packages/kazoo/handlers/utils.py", line 79, in get
    raise self._exception
NoNodeError
```

But using patronictl I was able to get the cluster state

```
ubuntu@platform1:/var/log/postgresql/patroni$ patronictl -c /etc/patroni/patroni.yml remove arkin
+---------+-------------+-----------+--------+---------+-----------+
| Cluster |    Member   |    Host   |  Role  |  State  | Lag in MB |
+---------+-------------+-----------+--------+---------+-----------+
|  arkin  | postgresql0 | localhost | Leader | running |           |
```

Can someone let me know what does the log  `I am leader but not owner of the session` denote?

**Comment by debraj-manna** [comment]
Ok. In what all scenarios can this error come and how to recover in this case? 

The cluster was down because of an outrage in DC after bringing the cluster up I ended up in this scenario. 

Should not patroni recover in this case if some other node holding the leader key dies abruptly?

**Comment by CyberDem0n** [comment]
Every session to zookeeper has its own "id".
All ephemeral objects created under specific session have a reference to the session by "id".
If the application is not running anymore, zookeeper session expires and zookeper removes all ephemeral objects associated with the given session.

This is how it should work.

If the leader key is still there, it could mean that either something is holding (another patroni) it or something is wrong with zookeeper cluster.

**Comment by ants** [comment]
From a cursory review it seems that an `except NoNodeError: pass` is needed for `.delete()` in this block:

https://github.com/zalando/patroni/blob/b282a0f254d69604f4e66218af10c1968eed9953/patroni/dcs/zookeeper.py#L181-L188

I'm not too familiar with how zookeeper works, but it seems to me that the leader key session might expire between 181 and 187 and get_cluster will then throw an uncaught kazoo exception terminating Patroni. If this is true, a service manager restarting Patroni would be enough to recover in this situation, but a proper fix would of course be nicer.

**Comment by debraj-manna** [comment]
I restarted patroni but it was not helping. It was still throwing the exception. I was able to recover the system by stopping and patroni and then doing `patronictl remove`.

**Comment by ants** [comment]
Interesting. If I am reading this correctly this must mean that `self._client.get(self.leader_path)` is returning something, but `self._client.delete(self.leader_path)` raises NoNodeError. That seems broken.
