### ISSUE TITLE
All nodes respond http/200 after switchover

### ISSUE THREAD

**Issue by imcitius** [zalando/patroni#776]
Hello

We've found an issue with latest 1.4.5 release, after a switchover (scheduled and immediate), all nodes gave 200 code on /master endpoint.

/Ilya

**Comment by CyberDem0n** [comment]
Without patroni configs and logs it is hard to tell what is wrong

**Comment by imcitius** [comment]
Config from one of the nodes is here:
[https://gist.github.com/imcitius/185ef685042ba131f91eb69d61d029e6.js]

Log of the master became replica:
https://gist.github.com/imcitius/0be62fcbf8fa880a5a6e8f9627719a27

Log of the replica became master:
https://gist.github.com/imcitius/f022dbd6f7f4c38b714e49c9ba0d6bca

And now both the former master, and current master answer 200:
https://gist.github.com/imcitius/68a8fda9c4bc8a382b01f6435a218312

**Comment by CyberDem0n** [comment]
Confirmed, working on fix.
