### ISSUE TITLE
Autorecovery after master fails dirty

### ISSUE THREAD

**Issue by mrquokka** [zalando/patroni#781]
How to tell to patroni do it automatic?
I use
`pg_rewind -D /work/postgresql0 --source-server='host=new_master_ip password=postgres_password'`

**Comment by mrquokka** [comment]
Thanks for answer, but i already set this flag. Problem does not solved.
`scope: database
name: postgresql1

restapi:
  listen: 192.168.8.202:8008
  connect_address: 192.168.8.202:8008

etcd:
  hosts:
  - 192.168.8.205:12379

bootstrap:
  dcs:
    ttl: 10
    loop_wait: 3
    retry_timeout: 3
    maximum_lag_on_failover: 8589934592
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      parameters:
        max_locks_per_transaction: 2000

  initdb:
  - encoding: UTF8
  - data-checksums
pg_hba:
  - local all postgres peer
  - host all postgres, replicator 127.0.0.1/32 md5
  - host replication replicator 127.0.0.1/32 md5
  - host replication replicator 192.168.8.0/24 md5
  - host all all 192.168.0.0/16 md5

  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 192.168.8.202:15432
  connect_address: 192.168.8.202:15432
  data_dir: /work/postgresql1
  pgpass: /work/pgpass1
  authentication:
    replication:
      username: replicator
      password: rep_pass
    superuser:
      username: postgres
      password: postgre_pass
  parameters:
    unix_socket_directories: '.'

watchdog:
  mode: automatic # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: 5
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
`
On syslog
` 08:26:23.303 MSK [9305] ERROR:  requested starting point 0/49000000 on timeline 2 is not in this server's history
08:26:23.303 MSK [9305] DETAIL:  This server's history forked from timeline 2 at 0/48372000.
`

**Comment by CyberDem0n** [comment]
If you changed the config after cluster was initialized - it won't work.
Can you verify that flag is set by running `patronictl show-config` ?

**Comment by mrquokka** [comment]
I dont reconfigure patroni, this is a new cluster (i deleted etcd, patroni_node_1 and patroni_node_2 folders before restart with new configuration).
This command does not work,
`'Can not find suitable configuration of distributed configuration store\nAvailable implementations: etcd'`
On http `http://192.168.8.205:12379/v2/keys/service/database/config`
I receive json 
`{"action":"get","node":{"key":"/service/database/config","value":"{\"ttl\":10,\"loop_wait\":3,\"retry_timeout\":3,\"maximum_lag_on_failover\":8589934592,\"synchronous_mode\":false,\"postgresql\":{\"use_pg_rewind\":true,\"parameters\":{\"max_locks_per_transaction\":2000}}}","modifiedIndex":9,"createdIndex":9}}`

**Comment by mrquokka** [comment]
For test i use 3 VBox machines (1 etcd, 2 nodes)
for test i use script
`import asyncio
import aiopg
import datetime

dsn = "dbname=test user=postgres host=192.168.8.210 password=postgre_pass"

async def go():
    async with aiopg.create_pool(dsn) as pool:
        async with pool.acquire() as conn:
            async with conn.cursor() as cur:
                # print('wtf')
                val = []
                for i in range(10000):
                  values = (
                    str(i),
                    i/100,
                    i,
                    datetime.datetime.now()
                  )
                  val.append(
                    "('%s', '%s', '%s', '%s')" % values
                  )
                val = ", ".join(val)
                await cur.execute("INSERT INTO measurements (cim_id, value, unit, timestamp) VALUES " + val)


start = datetime.datetime.now()
for i in range(10000):
  loop = asyncio.get_event_loop()
  futures = [go() for i in range(10)]
  loop.run_until_complete(asyncio.wait(futures))
  print(str(datetime.datetime.now() - start))
  start = datetime.datetime.now()`

**Comment by CyberDem0n** [comment]
And what is in Patroni logs when it starts on the former master?

**Comment by mrquokka** [comment]
`
Aug 16 11:23:41 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:41,720 INFO: Failed to import patroni.dcs.consul
Aug 16 11:23:41 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:41,760 INFO: Selected new etcd server http://192.168.8.205:12379
Aug 16 11:23:41 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:41,785 WARNING: Postgresql is not running.
Aug 16 11:23:41 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:41,785 INFO: Lock owner: postgresql1; I am postgresql0
Aug 16 11:23:41 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:41,809 INFO: doing crash recovery in a single user mode
Aug 16 11:23:44 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:44,778 INFO: Lock owner: postgresql1; I am postgresql0
Aug 16 11:23:44 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:44,782 INFO: doing crash recovery in a single user mode in progress
Aug 16 11:23:47 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:47,780 INFO: Lock owner: postgresql1; I am postgresql0
Aug 16 11:23:47 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:47,788 INFO: doing crash recovery in a single user mode in progress
Aug 16 11:23:50 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:50,778 INFO: Lock owner: postgresql1; I am postgresql0
Aug 16 11:23:50 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:50,780 INFO: doing crash recovery in a single user mode in progress
Aug 16 11:23:51 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:51,016 WARNING: Postgresql is not running.
Aug 16 11:23:51 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:51,016 INFO: Lock owner: postgresql1; I am postgresql0
Aug 16 11:23:51 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:51,022 INFO: Lock owner: postgresql1; I am postgresql0
Aug 16 11:23:51 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:51,033 INFO: Local timeline=1 lsn=0/18000028
Aug 16 11:23:51 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:51,235 INFO: master_timeline=2
Aug 16 11:23:51 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:51,237 INFO: master: history=1#0110/16F45FE0#011no recovery target specified
Aug 16 11:23:51 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:51,241 INFO: running pg_rewind from postgresql1
Aug 16 11:23:52 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:52,672 INFO: running pg_rewind from user=postgres host=192.168.8.202 port=15432 dbname=postgres sslmode=prefer sslcompression=1
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: servers diverged at WAL location 0/16F45FE0 on timeline 1
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: rewinding from last common checkpoint at 0/302A778 on timeline 1
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: "/work/postgresql0/.s.PGSQL.15432" is not a regular file
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: Failure, exiting
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: Failure, exiting
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53,580 ERROR: Failed to rewind from healty master: postgresql1
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53,584 WARNING: Postgresql is not running.
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53,586 INFO: Lock owner: postgresql1; I am postgresql0
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53,590 INFO: Lock owner: postgresql1; I am postgresql0
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53,593 INFO: starting as a secondary
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53,638 INFO: postmaster pid=1608
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53.664 MSK [1608] LOG:  listening on IPv4 address "192.168.8.201", port 15432
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53.683 MSK [1608] LOG:  listening on Unix socket "./.s.PGSQL.15432"
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53.871 MSK [1613] LOG:  database system was shut down at 2018-08-16 11:23:50 MSK
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53.871 MSK [1613] LOG:  entering standby mode
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53.871 MSK [1614] FATAL:  the database system is starting up
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 192.168.8.201:15432 - rejecting connections
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53.876 MSK [1613] LOG:  consistent recovery state reached at 0/18000098
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53.876 MSK [1613] LOG:  invalid record length at 0/18000098: wanted 24, got 0
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53.877 MSK [1608] LOG:  database system is ready to accept read only connections
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53.887 MSK [1619] LOG:  fetching timeline history file for timeline 2 from primary server
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53.911 MSK [1619] FATAL:  could not start WAL streaming: ERROR:  requested starting point 0/18000000 on timeline 1 is not in this server's hist$
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: #011DETAIL:  This server's history forked from timeline 1 at 0/16F45FE0.
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53.911 MSK [1613] LOG:  new timeline 2 forked off current database system timeline 1 before current recovery point 0/18000098
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 192.168.8.201:15432 - accepting connections
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53.930 MSK [1622] FATAL:  could not start WAL streaming: ERROR:  requested starting point 0/18000000 on timeline 1 is not in this server's hist$
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: #011DETAIL:  This server's history forked from timeline 1 at 0/16F45FE0.
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53,931 INFO: Lock owner: postgresql1; I am postgresql0
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53,931 INFO: does not have lock
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53,932 INFO: establishing a new patroni connection to the postgres cluster
Aug 16 11:23:53 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:53.933 MSK [1613] LOG:  new timeline 2 forked off current database system timeline 1 before current recovery point 0/18000098
Aug 16 11:23:54 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:54,114 INFO: no action.  i am a secondary and i am following a leader
Aug 16 11:23:55 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:55,159 INFO: Lock owner: postgresql1; I am postgresql0
Aug 16 11:23:55 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:55,159 INFO: does not have lock
Aug 16 11:23:55 clusternode-VirtualBox patroni[1561]: 2018-08-16 11:23:55,166 INFO: no action.  i am a secondary and i am following a leader
`

**Comment by CyberDem0n** [comment]
```
2018-08-16 11:23:51,241 INFO: running pg_rewind from postgresql1
2018-08-16 11:23:52,672 INFO: running pg_rewind from user=postgres host=192.168.8.202 port=15432 dbname=postgres sslmode=prefer sslcompression=1
servers diverged at WAL location 0/16F45FE0 on timeline 1
rewinding from last common checkpoint at 0/302A778 on timeline 1
"/work/postgresql0/.s.PGSQL.15432" is not a regular file
Failure, exiting
Failure, exiting
2018-08-16 11:23:53,580 ERROR: Failed to rewind from healty master: postgresql1
```

You see? Patroni executed pg_rewind, but it failed.

**Comment by mrquokka** [comment]
I am sorry, didn't see this. How can i fix this error?
delete .s.PGSQL.15432 and .s.PGSQL.15432.lock does not change result

` 2018-08-16 11:52:05,001 INFO: does not have lock
 2018-08-16 11:52:05,008 INFO: no action.  i am a secondary and i am following a leader
 2018-08-16 11:52:05.850 MSK [5012] FATAL:  could not start WAL streaming: ERROR:  requested starting poin
         DETAIL:  This server's history forked from timeline 1 at 0/16F45FE0.
 2018-08-16 11:52:05.855 MSK [1613] LOG:  new timeline 2 forked off current database system timeline 1 bef
 2018-08-16 11:52:08,000 INFO: Lock owner: postgresql1; I am postgresql0
`

**Comment by mrquokka** [comment]
Add to visudo 
`%postgres ALL= NOPASSWD:/bin/rm /work/postgresql0/.s.PGSQL.15432*`
and into patroni.service
`ExecStartPre=-/bin/rm /work/postgresql0/.s.PGSQL.15432*`

But... result does not changed..

**Comment by CyberDem0n** [comment]
Something is fishy here.
/work/postgresql0/.s.PGSQL.15432 is a unix-socket, and it should now be there if postgres is not running.

**Comment by mrquokka** [comment]
But what i can check? That 's patroni.service source
```
[Unit]
Description=Runners to orchestrate a high-availability PostgreSQL
After=rsyslog.service network.target multi-user.target keepalived.service haproxy.service
Requires=rsyslog.service network.target multi-user.target keepalived.service haproxy.service
Wants=rsyslog.service network.target keepalived.service haproxy.service
[Service]
Type=simple
Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/lib/postgresql/10/bin"
User=postgres
Group=postgres
ExecStartPre=-/usr/bin/sudo /sbin/modprobe softdog
ExecStartPre=-/usr/bin/sudo /bin/chown postgres /dev/watchdog
ExecStartPre=-/bin/rm /work/postgresql0/.s.PGSQL.15432*
ExecStart=/usr/local/bin/patroni /work/postgresql0.yml
KillMode=process
TimeoutSec=30
Restart=on-failure
RestartSec=10s
[Install]
WantedBy=multi-user.target
```

**Comment by mrquokka** [comment]
It will create anyway on this folder if i run it manually

**Comment by CyberDem0n** [comment]
That's a different error, but again, this is not Patroni error.
You have to either configure wal archiving or increase `wal_keep_segments`.

**Comment by mrquokka** [comment]
What value i need? Tried to use this config
```
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_keep_segments: 20
        wal_log_hints: on
        max_replication_slots: 5
        max_connections: 100
        max_locks_per_transaction: 2000
```
Problem anyway not resolved

**Comment by CyberDem0n** [comment]
Have you verified that the change was applied to the master?
Have you looked into postgres logs?

**Comment by mrquokka** [comment]
Syslog
```
13:49:29 systemd[1]: Startup finished in 4.007s (kernel) + 43.657s (userspace) = 47.664s.
13:49:32,994 INFO: Failed to import patroni.dcs.consul
13:49:33,201 INFO: Selected new etcd server http://192.168.8.205:12379
13:49:33,484 WARNING: Postgresql is not running.
13:49:33,485 INFO: Lock owner: postgresql1; I am postgresql0
13:49:34,235 INFO: doing crash recovery in a single user mode
13:49:36,338 INFO: Lock owner: postgresql1; I am postgresql0
13:49:36,342 INFO: doing crash recovery in a single user mode in progress
13:49:39,342 INFO: Lock owner: postgresql1; I am postgresql0
13:49:39,345 INFO: doing crash recovery in a single user mode in progress
13:49:42,342 INFO: Lock owner: postgresql1; I am postgresql0
13:49:42,351 INFO: doing crash recovery in a single user mode in progress
13:49:45,339 INFO: Lock owner: postgresql1; I am postgresql0
13:49:45,342 INFO: doing crash recovery in a single user mode in progress
13:49:48,342 INFO: Lock owner: postgresql1; I am postgresql0
13:49:48,352 INFO: doing crash recovery in a single user mode in progress
13:49:51,338 INFO: Lock owner: postgresql1; I am postgresql0
13:49:51,340 INFO: doing crash recovery in a single user mode in progress
13:49:54,338 INFO: Lock owner: postgresql1; I am postgresql0
13:49:54,340 INFO: doing crash recovery in a single user mode in progress
13:49:57,341 INFO: Lock owner: postgresql1; I am postgresql0
13:49:57,342 INFO: doing crash recovery in a single user mode in progress
13:49:58,899 WARNING: Postgresql is not running.
13:49:58,899 INFO: Lock owner: postgresql1; I am postgresql0
13:49:58,940 INFO: Lock owner: postgresql1; I am postgresql0
13:49:59,307 INFO: Local timeline=1 lsn=0/29000028
13:49:59,689 INFO: master_timeline=2
13:49:59,728 INFO: master: history=1#0110/28BB0448#011no recovery target specified
13:49:59,732 INFO: running pg_rewind from postgresql1
13:50:01,896 INFO: Lock owner: postgresql1; I am postgresql0
13:50:01,900 INFO: running pg_rewind from postgresql1 in progress
13:50:02,761 INFO: running pg_rewind from user=postgres host=192.168.8.202 port=15432 dbname=postgres sslmode=prefer sslcompression=1
13:50:04,894 INFO: Lock owner: postgresql1; I am postgresql0
13:50:04,902 INFO: running pg_rewind from postgresql1 in progress
13:50:07,897 INFO: Lock owner: postgresql1; I am postgresql0
13:50:07,915 INFO: running pg_rewind from postgresql1 in progress
13:50:10,894 INFO: Lock owner: postgresql1; I am postgresql0
13:50:10,896 INFO: running pg_rewind from postgresql1 in progress
13:50:13,897 INFO: Lock owner: postgresql1; I am postgresql0
13:50:13,899 INFO: running pg_rewind from postgresql1 in progress
13:50:16,899 INFO: Lock owner: postgresql1; I am postgresql0
13:50:16,905 INFO: running pg_rewind from postgresql1 in progress
13:50:19,898 INFO: Lock owner: postgresql1; I am postgresql0
13:50:19,902 INFO: running pg_rewind from postgresql1 in progress
13:50:22,897 INFO: Lock owner: postgresql1; I am postgresql0
13:50:22,899 INFO: running pg_rewind from postgresql1 in progress
13:50:25,897 INFO: Lock owner: postgresql1; I am postgresql0
13:50:25,901 INFO: running pg_rewind from postgresql1 in progress
13:50:28,894 INFO: Lock owner: postgresql1; I am postgresql0
13:50:28,897 INFO: running pg_rewind from postgresql1 in progress
13:50:31,894 INFO: Lock owner: postgresql1; I am postgresql0
13:50:31,896 INFO: running pg_rewind from postgresql1 in progress
13:50:34,898 INFO: Lock owner: postgresql1; I am postgresql0
13:50:34,909 INFO: running pg_rewind from postgresql1 in progress
13:50:37,896 INFO: Lock owner: postgresql1; I am postgresql0
13:50:37,900 INFO: running pg_rewind from postgresql1 in progress
13:50:40,899 INFO: Lock owner: postgresql1; I am postgresql0
13:50:40,904 INFO: running pg_rewind from postgresql1 in progress
13:50:43,901 INFO: Lock owner: postgresql1; I am postgresql0
13:50:43,905 INFO: running pg_rewind from postgresql1 in progress
13:50:46,894 INFO: Lock owner: postgresql1; I am postgresql0
13:50:46,898 INFO: running pg_rewind from postgresql1 in progress
13:50:49,895 INFO: Lock owner: postgresql1; I am postgresql0
13:50:49,898 INFO: running pg_rewind from postgresql1 in progress
13:50:50: servers diverged at WAL location 0/28BB0448 on timeline 1
13:50:50: rewinding from last common checkpoint at 0/50007B0 on timeline 1
13:50:52,901 INFO: Lock owner: postgresql1; I am postgresql0
13:50:52,903 INFO: running pg_rewind from postgresql1 in progress
13:50:55,896 INFO: Lock owner: postgresql1; I am postgresql0
13:50:55,901 INFO: running pg_rewind from postgresql1 in progress
13:50:58,894 INFO: Lock owner: postgresql1; I am postgresql0
13:50:58,897 INFO: running pg_rewind from postgresql1 in progress
13:51:01,897 INFO: Lock owner: postgresql1; I am postgresql0
13:51:01,899 INFO: running pg_rewind from postgresql1 in progress
13:51:04,894 INFO: Lock owner: postgresql1; I am postgresql0
13:51:04,895 INFO: running pg_rewind from postgresql1 in progress
13:51:07,895 INFO: Lock owner: postgresql1; I am postgresql0
13:51:07,897 INFO: running pg_rewind from postgresql1 in progress
13:51:10,895 INFO: Lock owner: postgresql1; I am postgresql0
13:51:10,903 INFO: running pg_rewind from postgresql1 in progress
13:51:13,894 INFO: Lock owner: postgresql1; I am postgresql0
13:51:13,897 INFO: running pg_rewind from postgresql1 in progress
13:51:16,896 INFO: Lock owner: postgresql1; I am postgresql0
13:51:16,898 INFO: running pg_rewind from postgresql1 in progress
13:51:19,896 INFO: Lock owner: postgresql1; I am postgresql0
13:51:19,901 INFO: running pg_rewind from postgresql1 in progress
13:51:22,899 INFO: Lock owner: postgresql1; I am postgresql0
13:51:22,906 INFO: running pg_rewind from postgresql1 in progress
13:51:25,898 INFO: Lock owner: postgresql1; I am postgresql0
13:51:25,905 INFO: running pg_rewind from postgresql1 in progress
13:51:28,895 INFO: Lock owner: postgresql1; I am postgresql0
13:51:28,898 INFO: running pg_rewind from postgresql1 in progress
13:51:31,894 INFO: Lock owner: postgresql1; I am postgresql0
13:51:31,899 INFO: running pg_rewind from postgresql1 in progress
13:51:34,894 INFO: Lock owner: postgresql1; I am postgresql0
13:51:34,897 INFO: running pg_rewind from postgresql1 in progress
13:51:37,894 INFO: Lock owner: postgresql1; I am postgresql0
13:51:37,895 INFO: running pg_rewind from postgresql1 in progress
13:51:40,896 INFO: Lock owner: postgresql1; I am postgresql0
13:51:40,904 INFO: running pg_rewind from postgresql1 in progress
13:51:43,903 INFO: Lock owner: postgresql1; I am postgresql0
13:51:43,913 INFO: running pg_rewind from postgresql1 in progress
13:51:46,902 INFO: Lock owner: postgresql1; I am postgresql0
13:51:46,907 INFO: running pg_rewind from postgresql1 in progress
13:51:49,897 INFO: Lock owner: postgresql1; I am postgresql0
13:51:49,906 INFO: running pg_rewind from postgresql1 in progress
13:51:52,897 INFO: Lock owner: postgresql1; I am postgresql0
13:51:52,912 INFO: running pg_rewind from postgresql1 in progress
13:51:55,894 INFO: Lock owner: postgresql1; I am postgresql0
13:51:55,900 INFO: running pg_rewind from postgresql1 in progress
13:51:58,898 INFO: Lock owner: postgresql1; I am postgresql0
13:51:58,902 INFO: running pg_rewind from postgresql1 in progress
13:52:01,895 INFO: Lock owner: postgresql1; I am postgresql0
13:52:01,898 INFO: running pg_rewind from postgresql1 in progress
13:52:02: Done!
13:52:02,160 WARNING: Postgresql is not running.
13:52:02,160 INFO: Lock owner: postgresql1; I am postgresql0
13:52:02,173 INFO: Lock owner: postgresql1; I am postgresql0
13:52:02,175 INFO: starting as a secondary
13:52:03,080 INFO: postmaster pid=1731
13:52:04.162 MSK [1731] LOG:  listening on IPv4 address "192.168.8.201", port 15432
13:52:04.171 MSK [1731] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.15432"
13:52:04.357 MSK [1734] LOG:  database system was interrupted while in recovery at log time 2018-08-17 13:50:00 MSK
13:52:04.357 MSK [1734] HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
13:52:04.357 MSK [1735] FATAL:  the database system is starting up
13:52:04: 192.168.8.201:15432 - rejecting connections
13:52:04.399 MSK [1737] FATAL:  the database system is starting up
13:52:04: 192.168.8.201:15432 - rejecting connections
13:52:04.796 MSK [1740] FATAL:  the database system is starting up
13:52:05,162 INFO: Lock owner: postgresql1; I am postgresql0
13:52:05,166 INFO: restarting after failure in progress
13:52:05.192 MSK [1734] LOG:  entering standby mode
13:52:05.280 MSK [1741] LOG:  started streaming WAL from primary at 0/5000000 on timeline 2
13:52:05.280 MSK [1741] FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 000000020000000000000005 has already been removed
13:52:05.310 MSK [1742] LOG:  started streaming WAL from primary at 0/5000000 on timeline 2
13:52:05.311 MSK [1742] FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 000000020000000000000005 has already been removed
13:52:05.462 MSK [1745] FATAL:  the database system is starting up
13:52:05: 192.168.8.201:15432 - rejecting connections
13:52:05.846 MSK [1747] FATAL:  the database system is starting up
13:52:06.494 MSK [1750] FATAL:  the database system is starting up
13:52:06: 192.168.8.201:15432 - rejecting connections
13:52:07.546 MSK [1753] FATAL:  the database system is starting up
13:52:07: 192.168.8.201:15432 - rejecting connections
13:52:07.804 MSK [1755] FATAL:  the database system is starting up
13:52:08,164 INFO: Lock owner: postgresql1; I am postgresql0
13:52:08,171 INFO: restarting after failure in progress
13:52:08.613 MSK [1758] FATAL:  the database system is starting up
13:52:08: 192.168.8.201:15432 - rejecting connections
13:52:08.861 MSK [1761] FATAL:  the database system is starting up
13:52:09.706 MSK [1764] FATAL:  the database system is starting up
13:52:09: 192.168.8.201:15432 - rejecting connections
13:52:10.293 MSK [1765] LOG:  started streaming WAL from primary at 0/5000000 on timeline 2
13:52:10.293 MSK [1765] FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 000000020000000000000005 has already been removed
13:52:10.761 MSK [1768] FATAL:  the database system is starting up
13:52:10: 192.168.8.201:15432 - rejecting connections
13:52:10.808 MSK [1770] FATAL:  the database system is starting up
13:52:11,161 INFO: Lock owner: postgresql1; I am postgresql0
13:52:11,164 INFO: restarting after failure in progress
13:52:11.795 MSK [1774] FATAL:  the database system is starting up

```
config

`{"action":"get","node":{"key":"/service/database/config","value":"{\"ttl\":10,\"loop_wait\":3,\"retry_timeout\":3,\"maximum_lag_on_failover\":8589934592,\"synchronous_mode\":false,\"postgresql\":{\"use_pg_rewind\":true,\"use_slots\":true,\"parameters\":{\"wal_keep_segments\":20,\"wal_log_hints\":true,\"max_replication_slots\":5,\"max_connections\":100,\"max_locks_per_transaction\":2000}}}","modifiedIndex":9,"createdIndex":9}}`

**Comment by CyberDem0n** [comment]
Just try to bump it to a higher value, lets say 200

**Comment by mrquokka** [comment]
That's work, but is it a crutch? Can patroni automatic set value on work on somethink another. 2000 value for ~ 30 seconds down, but if it down 1 day i need 6 billions?

**Comment by CyberDem0n** [comment]
Patroni itself has no idea about your transaction rate.
If you don't like an idea of increasing `wal_keep_segments`, you have to configure wal archiving: https://www.postgresql.org/docs/current/static/continuous-archiving.html

Postgres on the replica will be able to fetch missing wals from archive.

**Comment by mrquokka** [comment]
Thanks for answer, does this source resolve problem?
On russian lang:
  Спасибо за ответ. Видел ваш ник на habr'е. Вы мне очень помогли с этой проблемой. Я правильно понимаю, что добавление этого кода должно полностью решить данную проблему?
```
parameters:
  archive_mode: "on"
  wal_level: hot_standby
  archive_command: mkdir -p ../wal_archive && cp %p ../wal_archive/%f
  max_wal_senders: 10
  wal_keep_segments: 8
  max_replication_slots: 5
  hot_standby: "on"
  wal_log_hints: "on"
```

**Comment by CyberDem0n** [comment]
`  archive_command: mkdir -p ../wal_archive && cp %p ../wal_archive/%f` -- thats a very bad example, and we have it in the config (btw, it is commented out)  only for testing purpuses.

For production use, I would recommend to have a look at pgBackRest, wal-e, wal-g, barman and so on. They are widely used, heavily tested and proven to work.

**Comment by mrquokka** [comment]
Can you create guide how to combine patroni with them? I think that it is in-demand for test configuration/

**Comment by CyberDem0n** [comment]
Sorry, but I have no time for that.

**Comment by mkhodave** [comment]
I have run following patroni command on master db instance
`patronictl reinit <cluster-name> <slave-member-name>`

& replication resumed 
see more documentation for this -  https://patroni.readthedocs.io/en/latest/rest_api.html?highlight=reinit#reinitialize-endpoint
