### ISSUE TITLE
Failover never succeeds because of node health

### ISSUE THREAD

**Issue by ktechkez** [zalando/patroni#784]
Hi there, 

I am having an issue that I simply cannot figure out how to deal with, whereby failover never succeeds in my 3 node setup because of the following: 

"following a different leader because i am not the healthiest node"

I am trying to test failover by disabling the master node, but failover never succeeds because of the above. I have noticed significant lag on the slaves when listing nodes in the group, so I tried to enable synchronous commits to help the problem, as well as increasing the maximum lag to 100mb (over 3x the lag), but I am always just hit with the above log message. 

My config is below. Any idea what I'm doing wrong?

Thanks, 

Carey

`scope: postgres
namespace: /db/
name: devpostgres01
synchronous_commit: "on"
synchronous_standby_names: "*"
postgres.maximum_lag_on_failover: 100000000
restapi:
    listen: LOCALIP:8008
    connect_address: LOCALIP:8008
etcd:
    host: ETCDHOST:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        postgresql:
            use_pg_rewind: true
            recovery_conf: 
                recovery_target: immediate

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator node1/0 md5
    - host replication replicator node2/0 md5
    - host replication replicator node3/0 md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: adminpassword 
            options:
                - createrole
                - createdb

postgresql:
    listen: LOCALIP,127.0.0.1:5432
    connect_address: LOCALIP:5432
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: rep-pass
        superuser:
            username: postgres
            password: postgrespassword
    parameters:
        unix_socket_directories: '.'
        logging_collector: on 

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false`

**Comment by CyberDem0n** [comment]
Hi,

please make sure that replicas are streaming from the master.
Also, you might want to check postgres logs.

**Comment by ktechkez** [comment]
Here is the state of the cluster: 

patronictl -c /etc/patroni/patroni.yml list postgres
+----------+---------------+--------------+--------+---------+-----------+
| Cluster  |     Member    |     Host     |  Role  |  State  | Lag in MB |
+----------+---------------+--------------+--------+---------+-----------+
| postgres | devpostgres01 | 10.10.10.211 | Leader | running |       0.0 |
| postgres | devpostgres02 | 10.10.10.212 |        | running |      34.0 |
| postgres | devpostgres03 | 10.10.10.213 |        | running |      50.0 |
+----------+---------------+--------------+--------+---------+-----------+

Here is the only potential relevant thing from pg_log: 

< 2018-08-17 09:53:53.083 UTC >WARNING:  recovery command file "recovery.conf" specified neither primary_conninfo nor restore_command
< 2018-08-17 09:53:53.083 UTC >HINT:  The database server will regularly poll the pg_xlog subdirectory to check for files placed there.
< 2018-08-17 09:53:53.083 UTC >LOG:  entering standby mode

The lag seems suspiciously high which suggests something is not working properly?

**Comment by CyberDem0n** [comment]
`< 2018-08-17 09:53:53.083 UTC >WARNING: recovery command file "recovery.conf" specified neither primary_conninfo nor restore_command` --  is suppose this line appeared in the log after the master death.

What about the logs when the master is up and running?

**Comment by ktechkez** [comment]
I restarted the slave and tailed the new logs and I see the following: 

< 2018-08-17 11:42:00.425 UTC >LOG:  entering standby mode
< 2018-08-17 11:42:00.429 UTC >LOG:  redo starts at 0/2000178
< 2018-08-17 11:42:00.429 UTC >LOG:  consistent recovery state reached at 0/30002F0
< 2018-08-17 11:42:00.429 UTC >LOG:  recovery stopping after reaching consistency
< 2018-08-17 11:42:00.429 UTC >LOG:  recovery has paused
< 2018-08-17 11:42:00.429 UTC >HINT:  Execute pg_xlog_replay_resume() to continue.
< 2018-08-17 11:42:00.430 UTC >LOG:  database system is ready to accept read only connections

The lag is still 34mb behind exactly.

**Comment by CyberDem0n** [comment]
Oh!
Now I understand.

```yaml
postgresql:
  recovery_conf:
    recovery_target: immediate # this line spoils everything
```

Please update configuration: `patronictl -c /etc/patroni/patroni.yml edit-config postgres`, remove `recovery_target` from there and restart replicas

**Comment by ktechkez** [comment]
Thanks, it appears its made some sort of difference as I'm now seeing this in patroni logs:

Aug 17 12:26:51 devpostgres02 patroni[18638]: 2018-08-17 12:26:51,004 ERROR: Error when fetching backup: pg_basebackup exited with code=1
Aug 17 12:26:51 devpostgres02 patroni[18638]: 2018-08-17 12:26:51,004 WARNING: Trying again in 5 seconds
Aug 17 12:26:56 devpostgres02 patroni[18638]: pg_basebackup: could not connect to server: FATAL:  password authentication failed for user "replicator"
Aug 17 12:26:56 devpostgres02 patroni[18638]: password retrieved from file "/tmp/pgpass"
Aug 17 12:26:56 devpostgres02 patroni[18638]: 2018-08-17 12:26:56,027 ERROR: Error when fetching backup: pg_basebackup exited with code=1
Aug 17 12:26:56 devpostgres02 patroni[18638]: 2018-08-17 12:26:56,028 ERROR: failed to bootstrap from leader 'devpostgres01'
Aug 17 12:26:56 devpostgres02 patroni[18638]: 2018-08-17 12:26:56,028 INFO: Removing data directory: /data/patroni

I have the following in my config file: authentication:
replication:
username: replicator
password: rep-pass

I stopped all nodes, removed data directory, wiped etcd store and redeployed but still got the same issue...

**Comment by CyberDem0n** [comment]
```
pg_basebackup: could not connect to server: FATAL: password authentication failed for user "replicator"
```
But what is in the postgres master log?
Looks again like a configuration issue.

Antyway, please try to start with config files in the repository: `postgres0.yml` and `postgres1.yml`
They work without any problems.

**Comment by ktechkez** [comment]
I must have missed a step, I just tried again and its running fine, and failover succeeded instantly. Thankyou so much!

**Comment by ruimarinho** [comment]
@CyberDem0n I've just had this happen to me without any postgres error being logged. I've manually shutdown the leader but I still had to manually failover to one of the replicas I had available. In my case, lag couldn't justify it because I had two sync replicas:

```loop_wait: 10
master_start_timeout: 350
maximum_lag_on_failover: 0
postgresql:
  parameters:
    hot_standby_feedback: true
    max_connections: 2000
    synchronous_commit: remote_apply
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: true
synchronous_node_count: 2
ttl: 30```

Any idea of how to best debug this? I haven't been able to replicate it again.
