### ISSUE TITLE
sync standby not set when synchronous_mode_strict mode turned on

### ISSUE THREAD

**Issue by psuderevsky** [zalando/patroni#789]
I've faced an issue with `synchronous_mode_strict` mode. 
I could reproduce issue under the following circumstances:
1. The first candidate after failover is the node with nosync tag.
2. The first candidate after failover is the Barman running pg_receivexlog.
When failover occurs Patroni sets `synchronous_standby_names = '*'` and sometimes PostgreSQL makes one of the potential standbys synchronous, even if it is Patroni member with nosync tag or Barman wal-receiver, while Patroni does not assign correct member to synchronous_standby_names (sometimes even when member without nosync tag is healthy).

Unfortunately I have not got enough debug information, and issue is not reproducable in 100% of cases. Can just provide some example.

Postgres: 9.6.9
Patroni: 1.4.6

Example 1
Initially:
```+---------+--------+----------------+--------------+---------+-----------+
| Cluster | Member |      Host      |     Role     |  State  | Lag in MB |
+---------+--------+----------------+--------------+---------+-----------+
|  pglab  |  pg0   | 89.113.131.148 |    Leader    | running |       0.0 |
|  pglab  |  pg1   | 192.168.10.112 | Sync standby | running |       0.0 |
|  pglab  |  pg2   | 192.168.10.113 |              | running |       0.0 | <- nosync tag
+---------+--------+----------------+--------------+---------+-----------+
```
```
[root@pglab1 ~]# patronictl show-config | grep synch
    synchronous_commit: remote_apply
synchronous_mode: true
synchronous_mode_strict: true
```
Action: restarting Patroni master node
```
| Cluster | Member |      Host      |  Role  |  State  | Lag in MB |
+---------+--------+----------------+--------+---------+-----------+
|  pglab  |  pg0   | 192.168.10.111 |        | running |       0.0 |
|  pglab  |  pg1   | 192.168.10.112 | Leader | running |       0.0 |
|  pglab  |  pg2   | 192.168.10.113 |        | running |       0.0 |
+---------+--------+----------------+--------+---------+-----------+
```
Result:
```
[root@pglab1 ~]# etcdctl get /service/pglab/sync
{"leader":"pg1","sync_standby":null}
```
```
postgres=# show synchronous_standby_names;
 synchronous_standby_names 
---------------------------
 *
(1 row)
```
```
postgres=# select usename, application_name, client_addr, backend_start, state, sync_priority, sent_location, write_location, sync_state from pg_stat_replication ;
  usename   | application_name |  client_addr   |         backend_start         |   state   | sync_priority | sent_location | write_location | sync_state 
------------+------------------+----------------+-------------------------------+-----------+---------------+---------------+----------------+------------
 replicator | pg2              | 192.168.10.113 | 2018-08-23 18:59:00.852169+03 | streaming |             1 | 6/840001A8    | 6/840001A8     | sync
 barman     | barman_pglab1    | 192.168.10.112 | 2018-08-23 18:59:03.498641+03 | streaming |             1 | 6/840001A8    | 6/840001A8     | potential
 barman     | barman_pglab2    | 192.168.10.113 | 2018-08-23 18:59:03.516632+03 | streaming |             1 | 6/840001A8    | 6/840001A8     | potential
 replicator | pg0              | 192.168.10.111 | 2018-08-23 18:59:12.602+03    | streaming |             1 | 6/840001A8    | 6/840001A8     | potential
```

pg1 patroni log:
```
Aug 23 18:58:51 pglab1 patroni: 2018-08-23 18:58:51,603 DEBUG: Writing {"leader":"pg1","sync_standby":null} to key /service/pglab/sync ttl=None dir=False append=False
Aug 23 18:58:51 pglab1 patroni: 2018-08-23 18:58:51,609 DEBUG: http://127.0.0.1:2379 "PUT /v2/keys/service/pglab/sync HTTP/1.1" 200 309
```

Action2: pg2 set nosync tag to false and reload:
```
Aug 23 19:03:48 pglab2 patroni: 2018-08-23 19:03:48,244 DEBUG: Writing {"conn_url":"postgres://192.168.10.113:5432/postgres","api_url":"http://192.168.10.113:8008/patroni","timeline":182,"state":"running","role":"replica","xlog_location":28017951088} to key /service/pglab/members/pg2 ttl=30 dir=False append=False
```
Result: pg2 officially became sync standby:
```
Aug 23 19:03:57 pglab1 patroni: 2018-08-23 19:03:57,777 DEBUG: Writing {"leader":"pg1","sync_standby":"pg2"} to key /service/pglab/sync ttl=None dir=False append=False
Aug 23 19:03:57 pglab1 patroni: 2018-08-23 19:03:57,785 DEBUG: http://127.0.0.1:2379 "PUT /v2/keys/service/pglab/sync HTTP/1.1" 200 309
```
```
 synchronous_standby_names 
---------------------------
 pg2
(1 row)
```

Example 2:
Initially:
```+---------+--------+----------------+--------------+---------+-----------+
| Cluster | Member |      Host      |     Role     |  State  | Lag in MB |
+---------+--------+----------------+--------------+---------+-----------+
|  pglab  |  pg0   | 192.168.10.111 |    Leader    | running |       0.0 |
|  pglab  |  pg1   | 192.168.10.112 | Sync standby | running |       0.0 |
|  pglab  |  pg2   | 192.168.10.113 |              | running |       0.0 | 
+---------+--------+----------------+--------------+---------+-----------+
```
Action: restart Patroni master node
Result: barman became synchronous node despite the fact pg2 is healthy.
```
postgres=# select usename, application_name, client_addr, backend_start, state, sync_priority, sent_location, write_location, sync_state from pg_stat_replication ;
  usename   | application_name |  client_addr   |         backend_start         |   state   | sync_priority | sent_location | write_location | sync_state 
------------+------------------+----------------+-------------------------------+-----------+---------------+---------------+----------------+------------
 barman     | barman_pglab1    | 192.168.10.112 | 2018-08-23 19:13:03.298657+03 | streaming |             1 | 6/880001A8    | 6/880001A8     | sync
 replicator | pg2              | 192.168.10.113 | 2018-08-23 19:13:03.254545+03 | streaming |             1 | 6/880001A8    | 6/880001A8     | potential
 barman     | barman_pglab2    | 192.168.10.113 | 2018-08-23 19:13:03.341967+03 | streaming |             1 | 6/880001A8    | 6/880001A8     | potential
(3 rows)
```

Patroni log:
```
Aug 23 19:12:55 pglab1 patroni: 2018-08-23 19:12:55,275 DEBUG: Writing {"leader":"pg1","sync_standby":null} to key /service/pglab/sync ttl=None dir=False append=False
Aug 23 19:12:55 pglab1 patroni: 2018-08-23 19:12:55,281 DEBUG: http://127.0.0.1:2379 "PUT /v2/keys/service/pglab/sync HTTP/1.1" 200 309
```

**Comment by CyberDem0n** [comment]
I think this is correct behavior.

There are two different contracts:

1. Patroni should first set a node name into the synchronous_standby_names and only after that write this info into DCS. If Patroni decides (or get a command) that node should not be synchronous, it first removes this info from DCS and only after that from synchronous_standby_names. The order is very important. Otherwise we don't know which node was synchronous when master has died. 

2. Contract with synchronous_mode_strict is slightly different. Master should not perform writes if there is no synchronous standby available (transaction must be persisted by two nodes). Writes are not possible if there are no standbys available. This is very bad for the application. Therefore Patroni is doing the best it can, puts `*` into synchronous_standby_names. As a result, barman (or even the node with nosync flag) can temporarily become a sync standby until somebody better candidate appears in the cluster. After that Patroni will again change synchronous_standby_names and put the name of the good node into it.

The major difference between sync strict and non strict is that in non strict mode master will remove synchronous_standby_names from the config. That basically disables sync replication.

**Comment by psuderevsky** [comment]
Unfortunately, barman or node with nosync tag can become synchronous node not temporarily, but permanently until established sync replication stopped. Even when better candidate has already appeared. That's the issue.

**Comment by CyberDem0n** [comment]
What is in Patroni logs on the master?
DEBUG logs are not really telling much here.
There should be INFO or maybe WARNING logs from here: https://github.com/zalando/patroni/blob/master/patroni/ha.py#L319-L349

**Comment by psuderevsky** [comment]
Nothing usefull.
In those cases when synchronous standby assigned as expected the following INFO messages appear:
`Assigning synchronous standby status to %s`
`Synchronous standby status assigned to %s`
But in those cases when `synchronous_standby_names` stays `= '*'` forever, no related messages appear in log on the master.

**Comment by CyberDem0n** [comment]
Very strange.

This code https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L1724-L1741 picks a sync standby. It will skip all standbys which are not in the list of members or have nosync flag.

**Comment by alexeyklyukin** [comment]
@psuderevsky could it be that pg0 in your first example had been tagged 'nosync' as well? This is the only explanation I can come up with for why it has not been chosen as a sync replica. It would really help to have the complete Patroni logs from all participating nodes.

**Comment by psuderevsky** [comment]
@alexeyklyukin Please find logs attached. 
Highlights:
```
18:58:48    pg0(initial_master)    systemctl restart patroni
18:58:48    pg0(initial_master)    patroni                     Stopping Runners to orchestrate a high_availability PostgreSQL 
18:58:49    pg0(initial_master)    patroni                     Writing "nosync":true (the only time when nosync tag was written)
18:58:49    pg0(initial_master)    postgresql                  shutting down
18:58:51    pg0(initial_master)    postgresql                  database system is shut down
18:58:51    pg0(initial_master)    patroni                     Writing "role":"master","state":"stopped"
18:58:51    pg1(new_master)        patroni                     cleared rewind state after becoming the leader
18:58:51    pg0(initial_master)    patroni                     Started Runners to orchestrate a high_availability PostgreSQL
18:58:52    pg0(initial_master)    patroni                     starting as a secondary
18:58:55    pg1(new_master)        postgresql                  database system is ready to accept connections
18:58:56    pg1(new_master)        patroni                     Writing "role":"master"
18:59:00    pg0(initial_master)    postgresql                  entering standby mode
18:59:00    pg1(new_master)        postgresql                  standby "pg2" is now a synchronous standby with priority 1
18:59:02    pg0(initial_master)    patroni                     Writing "role":"replica","state":"starting"
18:59:02    pg0(initial_master)    patroni                     restarting after failure in progress
18:59:03    pg1(new_master)        postgresql                  standby "barman_pglab1" is now a synchronous standby with priority 1
18:59:12    pg0(initial_master)    postgresql                  database system is ready to accept read only connections
```
[patroni_issue789_pg0.log](https://github.com/zalando/patroni/files/2324411/patroni_issue789_pg0.log)
[patroni_issue789_pg1.log](https://github.com/zalando/patroni/files/2324412/patroni_issue789_pg1.log)
[patroni_issue789_pg2.log](https://github.com/zalando/patroni/files/2324413/patroni_issue789_pg2.log)

**Comment by psuderevsky** [comment]
I've extended pg0 and pg1 logs with 5 minutes more (attached).
You can see that:
```
Aug 23 19:03:56 pglab1 patroni: 2018-08-23 19:03:56,069 INFO: Assigning synchronous standby status to pg2
```
Because I had set `nosync` parameter to false for pg2 and reloaded it. 
The issue is very reproducible for me, I can perform any additional actions to provide you with more debug information if you want.
[patroni_issue789_pg0.log](https://github.com/zalando/patroni/files/2324800/patroni_issue789_pg0.log)
[patroni_issue789_pg1.log](https://github.com/zalando/patroni/files/2324801/patroni_issue789_pg1.log)

**Comment by CyberDem0n** [comment]
Got it.
Here is the fix: https://github.com/zalando/patroni/pull/794
