### ISSUE TITLE
Drop replication user from single node cluster

### ISSUE THREAD

**Issue by madvimer** [zalando/patroni#800]
Hello,

Is there a possibility of dropping replication user (using post_init script maybe ) from database instance ? Per user requirement, if the deployment has only one replica, replication user should not be present.

**Comment by CyberDem0n** [comment]
Why do you want to run single node cluster with Patroni?

**Comment by madvimer** [comment]
We are using a single docker image to run standalone and replicated deployments using openshift. In case of standalone deployments we set replicas value to 1. In this case replication users will not be required.  That is where we think replication user may not be required.

**Comment by CyberDem0n** [comment]
Well, you may drop replication user from post_init script, but I would advise not to do that. In some cases Patoni wants to use it even in single-node setup.
