### ISSUE TITLE
PersistentVolumeClaim assignment problem with Patroni etcd 

### ISSUE THREAD

**Issue by daya** [zalando/patroni#803]
I have 5 pods running Patroni with the desired StorageClass based PVC of 10Gi each deployed using [this chart](https://hub.kubeapps.com/charts/incubator/patroni) on a Rancher created cluster, they are running fine with ***`persistentVolume.storageClass = for-databases`***

But the **patroni-etcd pods (3 by default) are not running** because storage class `for-databases` is not being used **not sure why??**, following are the detail logs/events.

```
Name:          datadir-patroni-etcd-0
Namespace:     patroni
StorageClass:  
Status:        Pending
Volume:        
Labels:        chart=etcd-0.3.9
               component=patroni-etcd
               heritage=Tiller
               release=patroni
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
Events:
  Type    Reason         Age               From                         Message
  ----    ------         ----              ----                         -------
  Normal  FailedBinding  4m (x26 over 9m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

here is the full output of describe https://gist.github.com/daya/93a7ae9d051727e072bec69a9033bcdf

the etcd pod `describe` shows [this](https://git.io/fA43u) 
```
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir-patroni-etcd-0
    ReadOnly:   false
  default-token-6klmn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6klmn
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  4m (x879 over 24m)  default-scheduler  pod has unbound PersistentVolumeClaims (repeated 2 times)
```
Any help is much appreciated.

**Comment by daya** [comment]
the more I dig into it it seems like a [spilo](https://github.com/zalando/spilo) problem

**Comment by CyberDem0n** [comment]
Neither Spilo nor Patroni are responsible for provisioning persistent volumes.

**Comment by jberkus** [comment]
Suggestion: use a deployment based on one here instead of the helm chart: https://github.com/zalando/patroni/tree/master/kubernetes
