### ISSUE TITLE
using kubernetes etcd as a DCS

### ISSUE THREAD

**Issue by daya** [zalando/patroni#806]
Is it possible to use kubernetes etcd as a DCS with this chart? What would happen if etcd is disabled  using `--set etcd.enable=false` will it use the k8s `system` `s etcd?

**Comment by CyberDem0n** [comment]
> Is it possible to use kubernetes etcd as a DCS with this chart?

Patroni project itself doesn't provide helm chart. So I don't have an answer to your question, but I guess it should be possible.

> What would happen if etcd is disabled using --set etcd.enable=false will it use the k8s system `s etcd?

Patroni itself has no idea where it runs, you just have to provide a correct configuration: https://github.com/zalando/patroni/blob/master/postgres0.yml#L19-L20


The learning curve for k8s is very steep. I would suggest you first to learn how Patroni works by starting two or three nodes on your computer https://github.com/zalando/patroni/#running-and-configuring.
There are few tutorials available online:
* https://www.opsdash.com/blog/postgres-getting-started-patroni.html
* https://linode.com/docs/databases/postgresql/create-a-highly-available-postgresql-cluster-using-patroni-and-haproxy/

If you google, you can find more.
