### ISSUE TITLE
Is there a way to migrate existing data directrory to patroni?

### ISSUE THREAD

**Issue by jobinau** [zalando/patroni#807]
Is that Patroni always want to initialize a data directory?. Is there a way to start patroni cluster without running the initalization? I tried replacing the data directory.. But could the database remains in standby mode 
$ patroni /etc/patroni/patroni.yml
2018-09-17 17:40:30,754 INFO: Selected new etcd server http://192.168.50.10:2379
2018-09-17 17:40:30,801 WARNING: Postgresql is not running.
2018-09-17 17:40:30,802 INFO: Lock owner: None; I am pg0
2018-09-17 17:40:30,807 INFO: Lock owner: None; I am pg0
2018-09-17 17:40:30,820 INFO: starting as a secondary
2018-09-17 17:40:30,983 INFO: postmaster pid=6598

**Comment by CyberDem0n** [comment]
Yes, it is possible.
There are a couple of prerequisites:
1. cluster should not be "registered" in etcd
2. if you are "taking over" existing cluster, you should start Patroni on the primary first.

It seems that etcd contains some leftovers from your previous experiments, you should either change the cluster name (scope) or clean up etcd with:
`patronictl -c  /etc/patroni/patroni.yml remove <cluster-name>`

**Comment by jobinau** [comment]
> patronictl -c /etc/patroni/patroni.yml remove <cluster-name>
That really helped. Thanks a lot.
I shall make sure that the steps are publically available for other patroni users.
Thank you once again.
