### ISSUE TITLE
Failed to restart on_role_change.service: Unit on_role_change.service not found.

### ISSUE THREAD

**Issue by vitabaks** [zalando/patroni#812]
Hi!

I'm using callbacks (on_role_change).

After the role was changed, my script is worked, but in the log there is an error like this:

> Sep 26 14:04:28 pgnode01 patroni[1991]: 2018-09-26 14:04:28,331 INFO: manual failover: demoting myself
> Sep 26 14:04:30 pgnode01 patroni[1991]: 2018-09-26 14:04:30,814 INFO: Leader key released
> Sep 26 14:04:32 pgnode01 patroni[1991]: 2018-09-26 14:04:32,820 INFO: closed patroni connection to the postgresql cluster
> Sep 26 14:04:32 pgnode01 patroni[1991]: 2018-09-26 14:04:32,865 INFO: postmaster pid=21534
> Sep 26 14:04:32 pgnode01 patroni[1991]: /var/run/postgresql:5432 - no response
> Sep 26 14:04:33 pgnode01 patroni[1991]: /var/run/postgresql:5432 - accepting connections
> Sep 26 14:04:33 pgnode01 patroni[1991]: /var/run/postgresql:5432 - accepting connections
> Sep 26 14:04:34 pgnode01 patroni[1991]: Failed to restart on_role_change.service: Unit on_role_change.service not found.
> Sep 26 14:04:34 pgnode01 patroni[1991]: Failed to restart replica.service: Unit replica.service not found.
> Sep 26 14:04:34 pgnode01 patroni[1991]: Failed to restart db-cluster.service: Unit db-cluster.service not found.

patroni version 1.5.0

**Comment by CyberDem0n** [comment]
It is hard to tell what is wrong here without looking on the config and the callback script.

**Comment by vitabaks** [comment]
@CyberDem0n 

[tz-patroni.yml.txt](https://github.com/zalando/patroni/files/2419941/tz-patroni.yml.txt)

**Comment by CyberDem0n** [comment]
It happens because patroni adds some additional arguments to the command:
https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L795

`ssh postgres@10.129.50.100 "sudo systemctl restart haproxy"  on_role_change new-role-name cluster-name`

Actually you don't need to restart haproxy, it should use http health-checks: https://github.com/zalando/patroni/blob/master/haproxy.cfg
It is also possible to automate the update and reload of haproxy config file with the help of confd: https://github.com/zalando/patroni/tree/master/extras/confd

**Comment by vitabaks** [comment]
@CyberDem0n 

I'm already using haproxy + confd

The problem is that HAProxy1.8 has a bug, does not work on-marked-down shutdown-sessions.
Haproxy continue to route sessions to a backend marked as down.

In this regard, I decided to use callbacks (on_role_change).

Sorry, but the details in russian:
[haproxy_bug_detail.doc.zip](https://github.com/zalando/patroni/files/2420077/haproxy_bug_detail.doc.zip)
[confd-haproxy_conf.txt](https://github.com/zalando/patroni/files/2420082/confd-haproxy_conf.txt)

**Comment by vitabaks** [comment]
I would not like to create scripts....
But I understand you, and i will try to create a shell script.

Thank you

**Comment by vitabaks** [comment]
Done

```
  callbacks:
#    on_start:
#    on_stop:
#    on_restart:
#    on_reload:
    on_role_change: '/etc/patroni/haproxy_restart.sh'
```


cat /etc/patroni/haproxy_restart.sh

```
#!/bin/bash
# /etc/patroni/haproxy_restart.sh
# restart haproxy on all servers in the cluster

for i in $(patronictl -c /etc/patroni/patroni.yml list -f json | jq '.[] | .Host' | tr -d '"');
do
ssh postgres@$i sudo systemctl restart haproxy
done

exit
```
