### ISSUE TITLE
service not starting

### ISSUE THREAD

**Issue by billikill** [zalando/patroni#813]
Hi.
I am moved patroni.yml and edited patroni.services, after service not starting.
log patroni
https://pastebin.com/p5YUpzAs
could you help me

**Comment by CyberDem0n** [comment]
Patroni can't find config file.

**Comment by billikill** [comment]
sudo ls -l /etc/patroni
total 4
drwx------ 2 postgres        postgres           6 Sep 24 16:22 data
-rw-rw-r-- 1 user user 1324 Sep 26 14:35 patroni.yml
[user@node2 ~]$ sudo cat /etc/systemd/system/patroni.service 
[Unit]
Description=Runners to orchestrate a high-availability PostgreSQL
After=syslog.target network.target
[Service]
Type=simple
User=postgres
Group=postgres
ExecStart=/usr/bin/patroni /etc/patroni/patroni.yml
KillMode=process
TimeoutSec=30
Restart=no
[Install]
WantedBy=multi-user.target

**Comment by CyberDem0n** [comment]
Please make sure that postgres user cat read it
