### ISSUE TITLE
add server in cluster

### ISSUE THREAD

**Issue by billikill** [zalando/patroni#814]
Hi.
1 - I am add new server in cluster, but service patroni not starting.
log patroni https://pastebin.com/WnXzg0HV

**Comment by CyberDem0n** [comment]
There are some python modules missing. Either you have to install them manually, `pip install python-etcd` or install Patroni with explicit mentioning extras: `pip install patroni[etcd]`.

**Comment by billikill** [comment]
but pakege install 
Requirement already satisfied: python-etcd in /usr/lib/python2.7/site-packages (0.4.5)
Requirement already satisfied: urllib3>=1.7.1 in /usr/lib/python2.7/site-packages (from python-etcd) (1.23)
Requirement already satisfied: dnspython>=1.13.0 in /usr/lib/python2.7/site-packages (from python-etcd) (1.15.0)

**Comment by CyberDem0n** [comment]
Logs never lie:
```
Sep 26 17:59:52 jr-conf-app-05 patroni: 2018-09-26 17:59:52,741 INFO: Failed to import patroni.dcs.etcd
```

This log has the only meaning, python-etcd is not available.

**Comment by billikill** [comment]
hmm.
service is running
