### ISSUE TITLE
not edit config

### ISSUE THREAD

**Issue by billikill** [zalando/patroni#815]
Hi.
I can not edit the config patroni, I get an error
patronictl version 1.4.4
https://pastebin.com/bpv7akzg

when problem is resolved, but edit config and save i am error
 File "/usr/lib64/python2.7/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 6, column 3:
      default_statistics_target=1000
      ^
could not find expected ':'
  in "<unicode string>", line 7, column 1:
    retry_timeout: 10
    ^

**Comment by CyberDem0n** [comment]
Have you ever paid attention that config MUST be a valid `yaml`.
` default_statistics_target=1000` -- this is apparently not a valid yaml syntax.
