### ISSUE TITLE
[Question] Patroni + HAProxy configuration

### ISSUE THREAD

**Issue by blelump** [zalando/patroni#820]
Hello!

I am coming here not having any particular issue with Patroni itself, but rather with the overall infrastructure configuration. My problem seems to be with HAproxy configuration (or understanding?), because it simply closes connections -- which is a good thing, but I cannot manage how to deal with it when client is an ORM with connection pool. It is then more a HAproxy problem and I probably should ask 'them', but as you guys use it, perhaps you can share with some suggestions. Sample HAproxy config file with timeouts:
```
defaults
  log     global
  mode    tcp
  retries 2
  timeout connect 4s
  timeout check 5s
  timeout client 30m
  timeout server 30m
```

As said above, the client is an ORM with connection pool on board. The available connections in pool remain open for further usage, but for example, when 30m of idle passes (as specified in config) HAproxy closes such connection in pool and then when you try to use it, you'll obviously get an error, because the connection is already closed. I'd set `timeout client 0`, but that may cause another issues due to too many opened connections that are actually stalled due to various reasons. Increasing ` timeout client` to a higher value is probably not a good idea as well due to the same reasons as `timeout client 0`.

Do you guys have any advices for such configuration? Even though I'd set ORM connection pool size to 1, the connection may always be closed due to idle time higher than 30m (unlikely, but still possible). 

As can be seen in stats, HAproxy continuously closes open connections:
![alt text](https://i.imgur.com/jgRR9El.png "IMG")

**Comment by CyberDem0n** [comment]
Unfortunately it is not possible to solve this problem by changing the haproxy configuration.

The simplest solution would be configuring the connection pool to periodically "ping" open connections if they are "idling". Afaik some connection poolers can do that out of the box.

**Comment by blelump** [comment]
@CyberDem0n , thanks for your answer! I think there's nothing left to add regarding HAProxy. Closing this.
