### ISSUE TITLE
Local config changes don't seem to have precedence over dynamic configurations

### ISSUE THREAD

**Issue by c4milo** [zalando/patroni#821]
As stated in https://patroni.readthedocs.io/en/latest/dynamic_configuration.html#patroni-configuration

**Comment by CyberDem0n** [comment]
What exactly doesn't work?

**Comment by c4milo** [comment]
Hey @CyberDem0n, sorry for the lack of details. I've been trying to update `max_connections`, the only way how I've been able to do it is through dynamic configuration. Whenever I try to override it through local configuration, it does not change or schedule a restart.

**Comment by CyberDem0n** [comment]
That is intentional and it is actually documented:

> Some of the PostgreSQL parameters must hold the same values on the master and the replicas. For those, values set either in the local patroni configuration files or via the environment variables **take no effect**. To alter or set their values one must change the shared configuration in the DCS. Below is the actual list of such parameters together with the default values:
> *    max_connections: 100
> *    max_locks_per_transaction: 64
> *    max_worker_processes: 8
> *    max_prepared_transactions: 0
> *    wal_level: hot_standby
> *    wal_log_hints: on
> *    track_commit_timestamp: off

**Comment by c4milo** [comment]
I went through the docs several times and I couldn't get it. I think it would be useful if in the description at the top when it says: 

> * Local configuration (patroni.yml).
> These options are defined in the configuration file and take precedence over dynamic configuration.

It mentions the exception right away. I think I might have stopped reading once I got to this description.

**Comment by CyberDem0n** [comment]
Please feel free to open a PR improving documentation.
