### ISSUE TITLE
Unstable option passing for custom replica (and custom bootstrap?) methods

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#824]
I have the feeling that the order of the predefined options passed to the custom replica method command is not stable; I understand that you could parse those in an elaborate way, but if I just drop in a simple shell script and rely on `$1`, `$2` etc. for command-line variables, things seem to be unstable.

First off, I realize that things like `retries: 2` can be passes as additional options, maybe those from the yaml patroni conf should be last?

Then the code has
```
                 # add the default parameters
                method_config.update({"scope": self.scope,
                                      "role": "replica",
                                      "datadir": self._data_dir,
                                      "connstring": connstring})
                params = ["--{0}={1}".format(arg, val) for arg, val in method_config.items()]
```
I guess python (or some python versions) don't guarantee stable iterations here?

If I echo those out in order, with:

`echo "scope: $1 role: $2 datadir: $3 connstr: $4"`

I sometimes get things like this:

```
Okt 10 14:24:04 pg1 patroni[15462]: scope: --scope=9.6/main role: --connstring=postgres://replicator@10.0.3.34:5432/postgres datadir: --role=replica connstr: --datadir=/var/lib/postgresql/9.6/main/
```

I think it would be nice if the order was stable, even if that means the code might get a bit less nice.

Or am I missing something here?

**Comment by CyberDem0n** [comment]
> I guess python (or some python versions) don't guarantee stable iterations here?

Yep, unless it is explicitly sorted.
Following snippet should do the trick:

```python
params = ["--{0}={1}".format(arg, val) for arg, val in sorted(method_config.items())]
```

**Comment by CyberDem0n** [comment]
Bash code parsing arguments is also failry simple: https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/basebackup.sh#L5-L18

**Comment by mbanck** [comment]
As I was prototyping a bash script, I am going to adjust it with the first answer from https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash

**Comment by mbanck** [comment]
> Bash code parsing arguments is also failry simple: https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/basebackup.sh#L5-L18

Cool, maybe that one could be shipped in patroni as an example as well? The WAL-E one is pretty involved as well, but in python.
