### ISSUE TITLE
When I use standby cluster with use_slots,primary will not create replication slot

### ISSUE THREAD

**Issue by yangshushu** [zalando/patroni#826]
hi,I tested the new features of standby cluster.
When I specify the use_slots option on the configuration file of standby leader, primary will not create replication slot. The wal log cannot be transferred to standby leader.
I specify the use_slots to false,Everything seemed right.

Here is three node:
scope: batmant2
name: node_192_168_191_143 #primary node

scope: batmant2
name: node_192_168_191_142

scope: batmant3
name: node_192_168_191_141 #standby leader

standby leader configuration:
    standby_cluster:
      host: 192.168.191.143
      port: 5432
      primary_slot_name: node_192_168_191_141

**Comment by CyberDem0n** [comment]
Yes, unfortunately, the primary doesn't know anything about the standby cluster and therefore can't create the replication slot for it.
But we are very close to provide a solution to this problem: https://github.com/zalando/patroni/pull/819
