### ISSUE TITLE
Patroni load balancing question

### ISSUE THREAD

**Issue by Demuzx** [zalando/patroni#828]
Hi. Question: does Patroni have load balancing? Etc "select" queries direct to slaves and "insert" queries direct to master? Or something like this?

**Comment by uspen** [comment]
No, but patroni endpoints (/master /replca /sync /async) may use with haproxy and other balancers

**Comment by anikin-aa** [comment]
@Demuzx you should check this answer:
https://github.com/zalando/patroni/issues/766#issuecomment-411152242
