### ISSUE TITLE
Patroni ContextualVersionConflict on install

### ISSUE THREAD

**Issue by debraj-manna** [zalando/patroni#829]
After installing patroni 1.4.4 and on trying to start I am seeing errors like below

```
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 860, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.24 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('urllib3<1.24,>=1.21.1'), set(['requests']))
```

This is related to the issue discussed below for new version of urllib3 being released yesterday
https://github.com/requests/requests/issues/4830

**Comment by debraj-manna** [comment]
Closing this as request v2.20.0 is released with the fix.

**Comment by cognition** [comment]
its Happening again

Fresh install of: 
CentOS Linux release 7.6.1810 (Core)

`pip --no-cache install patroni
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting patroni
  Downloading https://files.pythonhosted.org/packages/53/5b/eb2369557464077f439272f581b10a029b5d0ec803ba41c56ab21aaac2c2/patroni-1.5.6.tar.gz (111kB)
     |████████████████████████████████| 112kB 1.6MB/s
Collecting urllib3!=1.21,>=1.19.1 (from patroni)
  Downloading https://files.pythonhosted.org/packages/c0/1f/516c14fd47ced1a2e2882edd776241c5b707ffc9051cd372843579829994/urllib3-1.25.1-py2.py3-none-any.whl (150kB)
     |████████████████████████████████| 153kB 60.6MB/s
Requirement already satisfied: psycopg2>=2.5.4 in /usr/lib64/python2.7/site-packages (from patroni) (2.8.2)
Requirement already satisfied: PyYAML in /usr/lib64/python2.7/site-packages (from patroni) (5.1)
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from patroni) (2.21.0)
Requirement already satisfied: six>=1.7 in /usr/lib/python2.7/site-packages (from patroni) (1.12.0)
Requirement already satisfied: click>=4.1 in /usr/lib64/python2.7/site-packages (from patroni) (7.0)
Requirement already satisfied: prettytable>=0.7 in /usr/lib/python2.7/site-packages (from patroni) (0.7.2)
Requirement already satisfied: tzlocal in /usr/lib/python2.7/site-packages (from patroni) (1.5.1)
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/site-packages (from patroni) (2.8.0)
Requirement already satisfied: psutil>=2.0.0 in /usr/lib64/python2.7/site-packages (from patroni) (5.6.1)
Requirement already satisfied: cdiff in /usr/lib/python2.7/site-packages (from patroni) (1.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests->patroni) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python2.7/site-packages (from requests->patroni) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests->patroni) (2019.3.9)
Requirement already satisfied: pytz in /usr/lib/python2.7/site-packages (from tzlocal->patroni) (2019.1)
ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.1 which is incompatible.
Installing collected packages: urllib3, patroni
  Running setup.py install for patroni ... done
Successfully installed patroni-1.5.6 urllib3-1.25.1
`

I have attempted to downgrade and upgrade, but to no avail.  Any help or solution to this would be greatly appreciated.

**Comment by CyberDem0n** [comment]
Just install `urllib3==1.24.2` before installing Patroni.

I think one day I'll get rid from stupid requests as a dependency.

**Comment by cognition** [comment]
Thank you, it worked!
