### ISSUE TITLE
Patroni post_init/post_bootstrap scripts always fail

### ISSUE THREAD

**Issue by MrPlow442** [zalando/patroni#834]
I'm trying to test out the `post_init`/`post_bootstrap` feature of patroni. So I've created a simple script to see if it would be executed:

```
#!/usr/bin/env bash
echo "!!!! post_init/post_bootstrap"
```

and added it to patroni yaml configuration like: `post_bootstrap: /usr/local/bin/scripts/post-bootstrap.sh`

However as soon as I add the configuration line I get the following from patroni: 

> 2018-10-22 11:38:16,627 INFO: running post_bootstrap  
> 2018-10-22 11:38:16,653 ERROR: post_init script /usr/local/bin/scripts/post-boostrap.sh failed  
> 2018-10-22 11:38:16,672 INFO: removing initialize key after failed attempt to bootstrap the cluster

And no matter what I do I keep getting this error with no details as to what is wrong. I am certain that the script is at the location given. I've tried changing the script to be either completely empty or exit with 0 but to no avail.

Are there any special rules or anything regarding these scripts? Is there a way I can get more details than what I've quoted above?

**Comment by CyberDem0n** [comment]
The script should be:
1. Executable by Patroni
2. should exit with code 0, otherwise Patroni thinks that it failed

**Comment by MrPlow442** [comment]
> The script should be:
> 
>     1. Executable by Patroni
> 
>     2. should exit with code 0, otherwise Patroni thinks that it failed

1. Script file has execute permissions and belongs to the same user that is running the patroni instance
2. I've added `exit 0` to the end of the script, however the error still occurs. Thanks for the clarification on the script rules. I'll make sure to always exit with 0 in my future tests.

**Comment by bradnicholson** [comment]
I wonder if it has to do with how your env is setup.

What happens if you change `#!/usr/bin/env bash` to `#!/bin/bash` (or wherever you have bash)?

The other thing to double check is that your Patroni user has permissions to the path that the file lives in.

**Comment by MrPlow442** [comment]
It's a postgresql docker image with patroni installed,  `#!/usr/bin/env` and `#!/bin/bash` behave the same. Tried it anyway and noticed no changes. Changed the permissions for the directory containing scripts to 777 and also no changes. Running the scripts manually with the same user patroni is run with works as expected. 

I was looking at the code responsible for printing the error in the log https://github.com/zalando/patroni/blob/f70edefc656fc394c8859db43d2334dd13e8cfb5/patroni/postgresql.py#L627 and I'm wondering, is there a reason why the exception message/details are not printed alongside the message? It'd probably help me immensely in this case.

**Comment by CyberDem0n** [comment]
You can try to replace `logger.error` with `logger.exception` and see what will happen.

In general, `post_init/post_bootstrap` is well tested and widely used and I am really surprised that somebody is struggling with it :(
