### ISSUE TITLE
Question: Need help pleas

### ISSUE THREAD

**Issue by berezinalex** [zalando/patroni#849]
how can you test the load capacity of a cluster patroni?
I have a cluster on proxmox, cluster on three servers ubuntu 18.04
2gb RAM , hdd - virtio - 150gb

$createdb -U postgres -h 192.168.1.1 -p 5432  pgbench_test
ok
 $pgbench -U postgres -h 192.168.1.1 -p 5432 -i -s 1000 pgbench_test
tested 4 times
2 times an error occurred
and partoni broke the connections, the leader was changing the base was restarted, the test started up as an accident.
$pgbench -b simple-update -c500 -j8 -P60 -T200 -U postgres -h 192.168.1.1 -p 5432 pgbench_test
crash allways
all other things being equal, and testing just one server postgres, on these servers ubuntu 18.04 LTS all tests pass and end without crashes

I suppose that when testing with a pgbench utility, the patroni daemon cannot timeout the state of the database, as it is busy testing and an accident occurs. Patroni restarts the server and gives the leadership in the cluster to another server, and as a result, the utility pgbench loses connection and an accident occurs

Tell me how to correctly test the load saving the cluster Patroni ?

**Comment by CyberDem0n** [comment]
Let me guess.
You are running etcd on the same hosts and it writes the data and logs to the same devices as postgres.

Etcd is very critical to disk latencies and it is better to run them on different hosts or at least etcd should keep the data on different devices.

**Comment by berezinalex** [comment]
yes you are right, etcd installed on the same nodes, thanks for the answer, very much appreciated

**Comment by berezinalex** [comment]
Можно задать Вам вопрос по русски ?На данный момент я собрал конфигурацию из 3 серверов на proxmox1) ETCD + HAPROXY2) Patroni + postgres3) Patroni + postgres я попытался протестировать с помощью gpbench, всё хорошоно вот в чем у меня возникла проблемапосле тестирования pgbench я попытался проверить отказоустойчивость кластера и тупо выключил лидерана момент выключения лидера slave отставал на 17540 - "Lag in MB" После выключения slave не принимал на себя роль лидер и ждал лидера Вопрос , что нужно сделать или какие настройки применить к patroni , чтобы  он как можно быстрее и с минимальными потерямизапустил slave в роле лидера  без потери данных    04.11.2018, 12:06, "Alexander Kukushkin" <notifications@github.com>:Let me guess.
You are running etcd on the same hosts and it writes the data and logs to the same devices as postgres.
Etcd is very critical to disk latencies and it is better to run them on different hosts or at least etcd should keep the data on different devices.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- С Уважением, Александр Александрович Березин

**Comment by mashuma** [comment]
@berezinalex If I have understood you correctly (Russian is not my native language). When replica is behind primary and primary is not available to continue replication, then Patroni will not select the replica to become the new primary due to lag.

You can change this behaviour by applying following setting:
```maximum_lag_on_failover: the maximum bytes a follower may lag to be able to participate in leader election.```
Source: https://patroni.readthedocs.io/en/latest/SETTINGS.html

When replica with lag is deemed suitable to become primary, following will happen:
1. Replica with lag becomes Primary
2. If old primary is available again, it will become a Replica. You will loose the data that was not replicated.

The cluster is waiting for the primary to become available because of this reason - avoid data loss.

I hope this answers your question and apologies, if I have misunderstood you.

**Comment by berezinalex** [comment]
Thank you for your prompt response, and sorry to trouble you.19.11.2018, 16:54, "Janis Puris" <notifications@github.com>:@berezinalex If I have understood you correctly (Russian is not my native language). When replica is behind primary and primary is not available to continue replication, then Patroni will not select the replica to become the new primary due to lag.
You can change this behaviour by applying following setting:
maximum_lag_on_failover: the maximum bytes a follower may lag to be able to participate in leader election.
Source: https://patroni.readthedocs.io/en/latest/SETTINGS.html
When replica with lag is deemed suitable to become primary, following will happen:

Replica with lag becomes Primary
If old primary is available again, it will become a Replica. You will loose the data that was not replicated.

The cluster is waiting for the primary to become available because of this reason - avoid data loss.
I hope this answers your question and apologies, if I have misunderstood you.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

-- С Уважением, Александр Александрович Березин
