### ISSUE TITLE
New feature : introduction of a priority for electing

### ISSUE THREAD

**Issue by ThomasPoty** [zalando/patroni#850]
Hi All,

I would like to see if it was possible to introduce a notion of a priority in electing processus.
For exemple, imagine : 
You have 2 data centers : DC1 and DC2.
You have 3 PostgreSQL server PG1(master), 2 (slave) ,3 (slave) and a communication between DC1 and 2 (ISL1).
PG1,2 are in DC1 and PG 3 is in DC2.
If PG1 get down and PG2 and 3 are on the same "recovery point" (have exactly the same lag),
we would probably prefer to failover on PG2 rather than PG3 in order to avoid communication through ISL1 
I think It would be great to have this feature.

The factors to take into account for electing would be : 
- First, the lag (as now)
- Second, the priority
- Third, random (as now)

Kind Regards

**Comment by alexeyklyukin** [comment]
I see a few ways you could implement this using existing features:

- use a 'standby cluster' for DC2, making it all replicas until you explicitly command Patroni to failover there; after all, switching datacenter for the databases is often a manual decision, as it potentially involves increased latencies not just for replicas, but also for applications.

- set DC2 instance 'nofailover' tag and failover manually if both the primary and the secondary in DC1 are down (I would expect that to happen way less often that just a primary being down)

- let Patroni choose an instance and then trigger a switchover to another one if you are not content with the  choice (after verifying that the other one can indeed cope with the load)

- use synchronous replication with a replica in the same DC, guaranteeing you both that the failover will happen to that replica and that no synchronous transactions will be lost.
