### ISSUE TITLE
Question:Is it necessary to set up watchdog in kubernetes environment?

### ISSUE THREAD

**Issue by lwsbox** [zalando/patroni#854]
Watchdog would reboot the system that may influences the other application in kubernetes.

Alternative solution？

**Comment by CyberDem0n** [comment]
No, you don't need the watchdog on k8s. Actually you can't even enable it.
It is enough to run Patroni with pid=1 in the container and if Patroni dies for some reason, it will break the container and as a result terminate postgres processes running there.

Another option is to use something like supervisord (like we do it in [spilo](https://github.com/zalando/spilo/tree/master/postgres-appliance)). It will take care of restarting the crashed process.
