### ISSUE TITLE
Do you plan to make an official ansible-playbook for patroni? 

### ISSUE THREAD

**Issue by patsevanton** [zalando/patroni#856]
Hello!
Do you plan to make an official ansible-playbook for patroni? Can be for example fork https://github.com/kostiantyn-nemchenko/ansible-role-patroni

**Comment by jberkus** [comment]
Not sure how we could do this?  There's a lot of different choices of environment (bare metal, AWS, Kubernetes, Openshift), and each would need its own playbook.

If someone contributes one or more playbooks I'll be happy to test them, but my own playbooks are way too specific to our environment to be generally useful.

**Comment by vitabaks** [comment]
I would like to share my Ansible playbook. For physical servers (bare metal) and VMs.

Automated deployment of a PostgreSQL HA Cluster (based on Patroni and DCS (etcd)):
https://github.com/vitabaks/postgresql_cluster

**Comment by ashokkoti** [comment]
Thanks @vitabaks  for sharing the playbooks
