### ISSUE TITLE
Failed to bootstrap cluster

### ISSUE THREAD

**Issue by byazrail** [zalando/patroni#860]
Hi guys,

CentOS Linux release 7.5.1804

I Tested;
PostgreSQL 10.6, 11.1, 9.6;
`-bash-4.2$ patroni /etc/patroni.yml
2018-11-13 05:19:22,599 INFO: Failed to import patroni.dcs.consul
2018-11-13 05:19:22,611 INFO: Selected new etcd server http://195.XXX.XXX.XX1:2379
2018-11-13 05:19:22,630 INFO: Lock owner: None; I am node-1
2018-11-13 05:19:22,635 INFO: trying to bootstrap a new cluster
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are enabled.

fixing permissions on existing directory /data/patroni ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /usr/pgsql-9.6/bin/pg_ctl -D /data/patroni -l logfile start

2018-11-13 05:19:23,916 INFO: postmaster pid=3447
159.XXX.XXX.XX1:5432 - no response
2018-11-13 05:19:24,933 ERROR: postmaster is not running
2018-11-13 05:19:24,966 INFO: removing initialize key after failed attempt to bootstrap the cluster
2018-11-13 05:19:24,970 INFO: renaming data directory to /data/patroni_2018-11-13-05-19-24
2018-11-13 05:19:25,130 INFO: Lock owner: None; I am node-1
Traceback (most recent call last):
  File "/bin/patroni", line 11, in <module>
    load_entry_point('patroni==1.5.1', 'console_scripts', 'patroni')()
  File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 182, in main
    return patroni_main()
  File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 149, in patroni_main
    patroni.run()
  File "/usr/lib/python2.7/site-packages/patroni/__init__.py", line 114, in run
    logger.info(self.ha.run_cycle())
  File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1275, in run_cycle
    info = self._run_cycle()
  File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1183, in _run_cycle
    return self.post_bootstrap()
  File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1079, in post_bootstrap
    self.cancel_initialization()
  File "/usr/lib/python2.7/site-packages/patroni/ha.py", line 1074, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'`

problem 3 versions same.
Not private network.
Only public network etcd, postgresql nodes servers.

Patroni.yml;
`
scope: my-ha-cluster
name: node-1

restapi:
  listen: 159.XXX.XXX.XX1:8008
  connect_address: 159.XXX.XXX.XX1:8008

etcd:
  host: 195.XXX.XXX.XX1:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    master_start_timeout: 300
#    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      parameters:
        max_connections: 5000
        wal_level: replica
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 5
        max_replication_slots: 5
        wal_log_hints: "on"
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
        shared_buffers: 32GB
        effective_cache_size: 96GB
        maintenance_work_mem: 2GB
        checkpoint_completion_target: 0.9
        wal_buffers: 16MB
        default_statistics_target: 100
        random_page_cost: 1.1
        effective_io_concurrency: 200
        work_mem: 160MB
        checkpoint_segments: 32
        min_wal_size: 2GB
        max_wal_size: 4GB
        max_worker_processes: 32
        max_parallel_workers_per_gather: 16
        max_parallel_workers: 32
      recovery_conf:
        restore_command: cp ../wal_archive/%f %p
        archive_cleanup_command: pg_archivecleanup /data/wal_archive %r

  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicauser 127.0.0.1/32 md5
  - host replication replicauser 159.XXX.XXX.XX1/0 md5
  - host replication replicauser 159.XXX.XXX.XX2/0 md5
  - host all all 0.0.0.0/0 md5

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

  users:
    dbname:
      password: 'Auth'
      options:
        - createrole
        - createdb

postgresql:
  listen: 159.XXX.XXX.XX1:5432
  connect_address: 159.XXX.XXX.XX1:5432
  bin_dir: /usr/pgsql-9.6/bin
  data_dir: /data/patroni
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicauser
      password: 'Auth'
    superuser:
      username: postgres
      password: 'Auth'
  parameters:
    unix_socket_directories: '.'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    replicatefrom: false`

Install Commands;
yum -y install python python-devel python-pip
sudo pip install --upgrade setuptools
pip install --upgrade pip
pip install psycopg2-binary
pip install patroni[etcd] or pip install patroni two choise tested.
and pip install urllib3==1.23 installed same github issue solve comment not working.
bin_dir add or remove tested.
bin_dir remove test result;
OSError: [Errno 2] No such file or directory
and
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'`

Tested Commands;
su - postgres;
patroni /etc/patroni.yml
or
systemctl start restart patroni etc.

Same error;
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'`

**Comment by CyberDem0n** [comment]
Patroni successfully run initdb, but failed to start postgres.
The postgres data directory is renamed to `/data/patroni_2018-11-13-05-19-24`.
Please figure out where the postgres logs are written and check them.
If you can't find logs files, please configure them explicitly https://www.postgresql.org/docs/current/runtime-config-logging.html and repeat an attempt to start the cluster.

**Comment by byazrail** [comment]
@CyberDem0n Thanks bro.
Reinstall OS after step step install successfully correct install.
Have a nice day ^_^

**Comment by byazrail** [comment]
Another problem issue;

Nov 13 16:12:02 pgrep1 systemd: Started Runners to orchestrate a high-availability PostgreSQL.
Nov 13 16:12:02 pgrep1 systemd: Starting Runners to orchestrate a high-availability PostgreSQL...
Nov 13 16:12:03 pgrep1 patroni: /usr/lib64/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
Nov 13 16:12:03 pgrep1 patroni: """)
Nov 13 16:12:03 pgrep1 patroni: 2018-11-13 16:12:03,179 INFO: Failed to import patroni.dcs.consul

**Comment by CyberDem0n** [comment]
Could you be more specific?
Where is the issue?

**Comment by mashuma** [comment]
Have you tried `pip install psycopg2-binary`, as instructed in the log output ?

**Comment by byazrail** [comment]
@mashuma 
[root@pgrep1 /]# pip install psycopg2-binary
Requirement already satisfied: psycopg2-binary in /usr/lib64/python2.7/site-packages (2.7.6.1)

**Comment by CyberDem0n** [comment]
First of all this is a warning, not an error.
If you want to get rid of it, I would recommend installing psycopg2 from centos packages.

**Comment by byazrail** [comment]
Clean centos install, starting service.
have a warnings but service running.

systemctl status patroni log;
Nov 13 17:36:56 pgrep1 systemd: Current command vanished from the unit file, execution of the command list won't be resumed.
Nov 13 17:37:02 pgrep1 systemd: Stopping Runners to orchestrate a high-availability PostgreSQL...
Nov 13 17:37:02 pgrep1 patroni: 2018-11-13 17:37:02,205 INFO: Lock owner: node1; I am node1
Nov 13 17:37:02 pgrep1 systemd: Stopped Runners to orchestrate a high-availability PostgreSQL.
Nov 13 17:37:07 pgrep1 systemd: Started Runners to orchestrate a high-availability PostgreSQL.
Nov 13 17:37:07 pgrep1 systemd: Starting Runners to orchestrate a high-availability PostgreSQL...
Nov 13 17:37:07 pgrep1 patroni: /usr/lib64/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
Nov 13 17:37:07 pgrep1 patroni: """)
Nov 13 17:37:07 pgrep1 patroni: 2018-11-13 17:37:07,491 INFO: Failed to import patroni.dcs.consul
Nov 13 17:37:07 pgrep1 patroni: 2018-11-13 17:37:07,502 INFO: Selected new etcd server http://XXX:2379
Nov 13 17:37:07 pgrep1 patroni: 2018-11-13 17:37:07,529 WARNING: Postgresql is not running.
Nov 13 17:37:07 pgrep1 patroni: 2018-11-13 17:37:07,530 INFO: Lock owner: None; I am node1
Nov 13 17:37:07 pgrep1 patroni: 2018-11-13 17:37:07,544 INFO: Lock owner: None; I am node1
Nov 13 17:37:07 pgrep1 patroni: 2018-11-13 17:37:07,566 INFO: Lock owner: None; I am node1
Nov 13 17:37:07 pgrep1 patroni: 2018-11-13 17:37:07,572 INFO: starting as a secondary
Nov 13 17:37:07 pgrep1 patroni: 2018-11-13 17:37:07,739 INFO: postmaster pid=26836
Nov 13 17:37:07 pgrep1 patroni: XXX:5432 - rejecting connections
Nov 13 17:37:07 pgrep1 patroni: XXX:5432 - accepting connections
Nov 13 17:37:07 pgrep1 patroni: 2018-11-13 17:37:07,795 INFO: establishing a new patroni connection to the postgres cluster
Nov 13 17:37:07 pgrep1 patroni: 2018-11-13 17:37:07,816 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
Nov 13 17:37:07 pgrep1 patroni: 2018-11-13 17:37:07,827 INFO: promoted self to leader by acquiring session lock
Nov 13 17:37:07 pgrep1 patroni: server promoting
Nov 13 17:37:07 pgrep1 patroni: 2018-11-13 17:37:07,836 INFO: cleared rewind state after becoming the leader
Nov 13 17:37:08 pgrep1 patroni: 2018-11-13 17:37:08,909 INFO: Lock owner: node1; I am node1
Nov 13 17:37:08 pgrep1 patroni: 2018-11-13 17:37:08,925 INFO: no action.  i am the leader with the lock
Nov 13 17:37:16 pgrep1 systemd: Reloading.
Nov 13 17:37:18 pgrep1 patroni: 2018-11-13 17:37:18,907 INFO: Lock owner: node1; I am node1
Nov 13 17:37:18 pgrep1 patroni: 2018-11-13 17:37:18,915 INFO: no action.  i am the leader with the lock
Nov 13 17:37:28 pgrep1 patroni: 2018-11-13 17:37:28,907 INFO: Lock owner: node1; I am node1
Nov 13 17:37:28 pgrep1 patroni: 2018-11-13 17:37:28,917 INFO: no action.  i am the leader with the lock
Nov 13 17:37:38 pgrep1 patroni: 2018-11-13 17:37:38,907 INFO: Lock owner: node1; I am node1
Nov 13 17:37:38 pgrep1 patroni: 2018-11-13 17:37:38,915 INFO: no action.  i am the leader with the lock
