### ISSUE TITLE
need help with etcd

### ISSUE THREAD

**Issue by binooetomo** [zalando/patroni#861]
Dear All ...

I just start to play with patroni, based on https://www.opsdash.com/blog/postgres-getting-started-patroni.html

It works as expected.

Now I need to create dynamic pgbouncer configuration based on cluster condition.
That is I want my pgbouncer to forward 'write' query to 'leader' and 'read' queries is load-balanced among other folowers.

I think i can di this by watching etcd values.

First I do experiment with python etcd 'watch' as documented.

from etcd import Client
myclient = Client(port=2379)
myclient.watch('/service/my-ha-cluster')

I try to shutdown the leader, but my python never catch the change.
How to get cluster status change notification ?

Additionaly :
when I try to client.read('/service/my-ha-cluster') ...
I alway got 'None' for '/service/my-ha-cluster/members'
Is there any way to have list of patroni cluster member from etcd ?

Sincerely
-bino-

**Comment by mashuma** [comment]
I'm quite new to Patroni myself, but have you tried to do GET request on Patroni API ?

Node is primary, if
```
/ 200
/primary 200
/replica 503
```

Node is secondary, if
```
/replica 200
/primary 503
```

Not all that familiar with etcd yet, hence can't help you there :(

**Comment by CyberDem0n** [comment]
Hi,

I would not recommend to reimplement the wheel and use something that is already there. Basically you have two options:
1. use HAProxy + confd: https://github.com/zalando/patroni/tree/master/extras and put pgbouncer in front of haproxy
2. write confd templates for pgbouncer and try to get rid of HAProxy component. The idea is very simple. Confd will extract information about the leader from Etcd, and in case if leader has changed update pgbouncer configuration and reload/restart it.

**Comment by udit47** [comment]
> use HAProxy + confd: https://github.com/zalando/patroni/tree/master/extras and put pgbouncer in front of haproxy

In this case, if pgbouncer on master node fails but master pg is running then requests will fail because haproxy will not route requests to different pgbouncer since it is on replica node.
