### ISSUE TITLE
patronictl list

### ISSUE THREAD

**Issue by ixpict** [zalando/patroni#862]
Hi!

I use one etcd cluster for all postgresql instance in one environment, and i expect command `patronictl list` without cluster name print all clusters in dcs, but i get zero list. It's bug or feature?

**Comment by CyberDem0n** [comment]
List expects to get a list of cluster names as arguments.
If there is nothing specified it will use `scope` from the config file.

```
patronictl list --help 
Usage: patronictl.py list [OPTIONS] [CLUSTER_NAMES]... 
                                                        
  List the Patroni members for a given Patroni 
 
Options: 
  -e, --extended     Show some extra information 
  -t, --timestamp    Print timestamp 
  -f, --format TEXT  Output format (pretty, json, yaml) 
  -W                 Auto update the screen every 2 seconds 
  -w, --watch FLOAT  Auto update the screen every X seconds 
  --help             Show this message and exit.
```

**Comment by ixpict** [comment]
Ok, can i add some special command to show all clusters as list, like `patronictl cluster-list`?

**Comment by ixpict** [comment]
Thank you! I'll back later with pull request
