### ISSUE TITLE
Create stats_temp_directory during postmaster start

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#863]
Debian/Ubuntu by default put `stats_temp_directory` under `(/var)/run/postgresql/` which is a ram disk. This directory will be gone between reboots, so Debian's `pg_ctlcluster` creates it before starting postgres.

As patroni is starting postgres, it would be nice if there was a way to similarly tell it to create this directory, as Postgres fails to start if it is no present. It could be done via `RuntimeDirectory=` in patroni's systemd service, but that looks like the wrong place for creating a child's runtime directory.

Does patroni check the PostgreSQL configuration before starting postres in any other way for things to keep in mind? I don't think so, but if it does, it could be hooked in there.

Otherwise, a new option to simply create that/a directory might be ok?

Another option might be to use `on_start` (if I understand that directly) and run `mkdir -p` there, but at least superficial tests did not work for me and there was no log output to figure out what was going wrong. Besides, users might want to put other things in that hook.

**Comment by CyberDem0n** [comment]
This is a very tricky question.

Do we have a guaranty that `(/var)/run/postgresql/` is owned by postgres? If it is not, we wont be able to create a directory there.
Unfortunately we can't use `on_start` hook, it is executed only when postgres already accepting connections.
ATM Patroni is not really checking all postgres parameters on start, it does it only if something has changed in runtime by querieing `pg_settings`. Verifying postgres configuration is the important thing which should actually be implemented, but we are not yet there.

The easiest thing to get temp dir would be using the `RuntimeDirectory=` in the patroni systemd.
We could also think about implementing a new patroni functionality, like creating `stats_temp_directory` if it is defined in the patroni config, but it won't cover the case when the parameter is defined in the postgres config. Parsing postgresql.conf and pg_hba.conf was actually the thing I was insistently avoiding.

**Comment by mbanck** [comment]
I am using `RuntimeDirectory=` now, but one issue with that is that `RuntimeDirectory` only recently added support for subdirectories (as is required here); notably this does not work on Debian stable.

If you agree to support this in the Patroni yaml config, I think a reasonable thing to do might be to try creating the directory, but to only log a warning if it fails. Or to put it another way: I think if the user requests the creation of that subdirectory, they should be responsible for the postgres user to be able to create it.
