### ISSUE TITLE
How does patroni recognizes to which cluster belongs pg_data folder?

### ISSUE THREAD

**Issue by NewOne121** [zalando/patroni#864]
Hi, i have configured patroni cluster with master/slave node.
I'd like to migrate data from another postgres cluster (not patroni) to current patroni cluster. I'd like to do that just by mounting folder with data that i need to patroni's pg_data folder but unfortunately when i'm doing that i'm getting an error that sounds like :
system ID mismatch, node $NODENAME belongs to a different cluster
Where does patroni stores that data?

So is there any workaround to do that in this way?
P.S. i don't like to use pg_dump/pg_restore way to do this.

**Comment by CyberDem0n** [comment]
Patroni stores information about `Database system identifier` in the DCS.
If you try to start Patroni with the wrong data directory, it will notice it and refuse to work.

You have to options:
1. Set a different `scope` in the configuration.
2. Use `patronictl remove <scope>` to remove information about the cluster from DCS before starting up the Patroni.

**Comment by NewOne121** [comment]
@CyberDem0n Thanks a lot for explanation! It worked for me !
