### ISSUE TITLE
High availability using patroni is not working

### ISSUE THREAD

**Issue by Mouyam** [zalando/patroni#866]
Hello
I am trying to setup a new clustered PostgreSQL environment using Patroni
I have 2 servers (master and Slave), Using Redhat 6.9 and PostgreSQL 9.6
I did the configration for the master and it is working fine and I did the same with the slave but it is not working
I will attatch the errors, setup I used and results
this is the link of the steps that i followed
[https://www.opsdash.com/blog/postgres-getting-started-patroni.html](https://www.opsdash.com/blog/postgres-getting-started-patroni.html)

Looking foroward for your help, please

![master s cluster](https://user-images.githubusercontent.com/45061295/48539236-a2aa3600-e8c7-11e8-9128-8bf6adb79795.PNG)
![masters patroni running](https://user-images.githubusercontent.com/45061295/48539239-a342cc80-e8c7-11e8-81ec-d9e7197b48a9.PNG)
![masters patroni](https://user-images.githubusercontent.com/45061295/48539240-a342cc80-e8c7-11e8-845d-612c3c6b1315.PNG)
![slave patroni](https://user-images.githubusercontent.com/45061295/48539241-a342cc80-e8c7-11e8-9de4-2bda8848855b.PNG)
![slave s cluster](https://user-images.githubusercontent.com/45061295/48539242-a342cc80-e8c7-11e8-92f7-9aefb1b8bb5d.PNG)

**Comment by CyberDem0n** [comment]
1. pg-1 failed to open port for patroni rest api.
2. you didn't installed python-etcd module on pg-2
3. Etcd must be clustered! Please don't expect here to get a help on how to cluster etcd.

**Comment by Mouyam** [comment]
> 1. pg-1 failed to open port for patroni rest api.
> 2. you didn't installed python-etcd module on pg-2
> 3. Etcd must be clustered! Please don't expect here to get a help on how to cluster etcd.

python-etcd is installed in pg-2
![pg-2 etcd](https://user-images.githubusercontent.com/45061295/48546893-7cda5c80-e8da-11e8-90ae-a5cce7517087.PNG)
