### ISSUE TITLE
Patroni not trying to reconnect to other etcd members (simlar to #628)

### ISSUE THREAD

**Issue by svente08** [zalando/patroni#867]
ENV:

python. 2.7
patroni: 1.5.1

etcd health check or "curl  'etcd host members'" working as expected 

db/patroni cluster:

postgre-node-1 
postgre-node-2
postgre-node-3

etcd cluster:

etcd-node-1 - 10.44.2.46
etcd-node-2 - 10.44.2.47

When shutting down one of the etd nodes patroni does not connect to other etcd host. Same issue as in #628 but in 1.5.1 (my version) the fix is already inplemented. Here the log output:

Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,039 INFO: Reconnection allowed, looking for another server.
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,039 DEBUG: Selection next machine in cache. Available machines: []
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,039 ERROR: Machines cache is empty, no machines to try.
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,040 ERROR:
Nov 14 16:55:03 postgre-node-1 patroni[24390]: Traceback (most recent call last):
Nov 14 16:55:03 postgre-node-1 patroni[24390]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 341, in wrapper
Nov 14 16:55:03 postgre-node-1 patroni[24390]: retval = func(self, *args, **kwargs) is not None
Nov 14 16:55:03 postgre-node-1 patroni[24390]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 499, in touch_member
Nov 14 16:55:03 postgre-node-1 patroni[24390]: return self._client.set(self.member_path, data, None if permanent else ttl or self._ttl)
Nov 14 16:55:03 postgre-node-1 patroni[24390]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 721, in set
Nov 14 16:55:03 postgre-node-1 patroni[24390]: return self.write(key, value, ttl=ttl)
Nov 14 16:55:03 postgre-node-1 patroni[24390]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 500, in write
Nov 14 16:55:03 postgre-node-1 patroni[24390]: response = self.api_execute(path, method, params=params)
Nov 14 16:55:03 postgre-node-1 patroni[24390]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 205, in api_execute
Nov 14 16:55:03 postgre-node-1 patroni[24390]: response = self._do_http_request(request_executor, method, self._base_uri + path, **kwargs)
Nov 14 16:55:03 postgre-node-1 patroni[24390]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 168, in _do_http_request
Nov 14 16:55:03 postgre-node-1 patroni[24390]: self._base_uri = self._next_server(cause=e)
Nov 14 16:55:03 postgre-node-1 patroni[24390]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 832, in _next_server
Nov 14 16:55:03 postgre-node-1 patroni[24390]: cause=cause)
Nov 14 16:55:03 postgre-node-1 patroni[24390]: EtcdConnectionFailed: No more machines in the cluster
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,040 INFO: no action.  i am a secondary and i am following a leader
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,336 DEBUG: Issuing read for key /service/postgres/ with args {'recursive': True}
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,340 DEBUG: Selection next machine in cache. Available machines: ['http://etcd-node-1.kuelap.io:2379',
'http://etcd-node-2.kuelap.io:2379']
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,340 INFO: Selected new etcd server http://etcd-node-2.kuelap.io:2379
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,340 DEBUG: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=0, status=None)
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,340 DEBUG: Starting new HTTP connection (11): etcd-node-2.kuelap.io:2379
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,341 DEBUG: http://etcd-node-2.kuelap.io:2379 "GET /v2/machines HTTP/1.1" 200 46
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,342 DEBUG: Retrieved list of machines: [u'http://10.44.2.46:2379', u'http://10.44.2.47:2379']
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,342 DEBUG: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=0, status=None)
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,343 DEBUG: http://etcd-node-2.kuelap.io:2379 "GET /v2/keys/service/postgres/?recursive=true HTTP/1.1"
200 None
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,344 INFO: Lock owner: postgre-node-2; I am postgre-node-1
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,344 INFO: does not have lock
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,347 INFO: Local timeline=33 lsn=0/7001488
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,351 INFO: Leader is still in_recovery and therefore can't be used for rewind
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,351 DEBUG: Writing {"conn_url":"postgres://10.44.2.41:5432/postgres","api_url":"http://10.44.2.41:8008/patroni","timeline":33,"state":"running","role":"replica","xlog_location":117445768} to key /service/postgres/members/postgre-node-1 ttl=30 dir=False append=False
Nov 14 16:55:03 postgre-node-1 patroni[24390]: 2018-11-14 16:55:03,352 DEBUG: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=0, status=None)
Nov 14 16:55:05 postgre-node-1 patroni[24390]: 2018-11-14 16:55:05,021 DEBUG: Incremented Retry for (url='/v2/keys/service/postgres/members/postgre-node-1'): Retry(total=0, connect=None, read=None, redirect=0, status=None)
Nov 14 16:55:05 postgre-node-1 patroni[24390]: 2018-11-14 16:55:05,021 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='etcd-node-2.kuelap.io', port=2379): Read timed out. (read timeout=1.66666666667)",)': /v2/keys/service/postgres/members/postgre-node-1
Nov 14 16:55:05 postgre-node-1 patroni[24390]: 2018-11-14 16:55:05,021 DEBUG: Starting new HTTP connection (12): etcd-node-2.kuelap.io:2379
Nov 14 16:55:06 postgre-node-1 patroni[24390]: 2018-11-14 16:55:06,691 ERROR: Request to server http://etcd-node-2.kuelap.io:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'etcd-node-2.kuelap.io\', port=2379): Max retries exceeded with url: /v2/keys/service/postgres/members/postgre-node-1 (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'etcd-node-2.kuelap.io\', port=2379): Read timed out. (read timeout=1.66666666667)",))',)
Nov 14 16:55:06 postgre-node-1 patroni[24390]: 2018-11-14 16:55:06,691 INFO: Reconnection allowed, looking for another server.
Nov 14 16:55:06 postgre-node-1 patroni[24390]: 2018-11-14 16:55:06,691 DEBUG: Selection next machine in cache. Available machines: [u'http://10.44.2.47:2379', u'http://10.44.2.46:2379']
Nov 14 16:55:06 postgre-node-1 patroni[24390]: 2018-11-14 16:55:06,691 INFO: Selected new etcd server http://10.44.2.46:2379
Nov 14 16:55:06 postgre-node-1 patroni[24390]: 2018-11-14 16:55:06,691 DEBUG: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=0, status=None)
Nov 14 16:55:06 postgre-node-1 patroni[24390]: 2018-11-14 16:55:06,691 DEBUG: Starting new HTTP connection (11): 10.44.2.46:2379
Nov 14 16:55:08 postgre-node-1 patroni[24390]: 2018-11-14 16:55:08,361 DEBUG: Incremented Retry for (url='/v2/keys/service/postgres/members/postgre-node-1'): Retry(total=0, connect=None, read=None, redirect=0, status=None)
Nov 14 16:55:08 postgre-node-1 patroni[24390]: 2018-11-14 16:55:08,361 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdfcfad5d50>, u'Connection to 10.44.2.46 timed out. (connect timeout=1.66666666667)')': /v2/keys/service/postgres/members/postgre-node-1
Nov 14 16:55:08 postgre-node-1 patroni[24390]: 2018-11-14 16:55:08,361 DEBUG: Starting new HTTP connection (12): 10.44.2.46:2379
Nov 14 16:55:09 postgre-node-1 patroni[24390]: 2018-11-14 16:55:09,697 ERROR: Request to server http://10.44.2.46:2379 failed: MaxRetryError(u"HTTPConnectionPool(host=u'10.44.2.46', port=2379): Max retries exceeded with url: /v2/keys/service/postgres/members/postgre-node-1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdfcfaaba50>: Failed to establish a new connection: [Errno 113] No route to host',))",)
Nov 14 16:55:09 postgre-node-1 patroni[24390]: 2018-11-14 16:55:09,698 INFO: Reconnection allowed, looking for another server.
Nov 14 16:55:09 postgre-node-1 patroni[24390]: 2018-11-14 16:55:09,698 DEBUG: Selection next machine in cache. Available machines: [u'http://10.44.2.47:2379']
Nov 14 16:55:09 postgre-node-1 patroni[24390]: 2018-11-14 16:55:09,698 INFO: Selected new etcd server http://10.44.2.47:2379
Nov 14 16:55:09 postgre-node-1 patroni[24390]: 2018-11-14 16:55:09,698 DEBUG: Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=0, status=None)
Nov 14 16:55:09 postgre-node-1 patroni[24390]: 2018-11-14 16:55:09,698 DEBUG: Starting new HTTP connection (11): 10.44.2.47:2379
Nov 14 16:55:11 postgre-node-1 patroni[24390]: 2018-11-14 16:55:11,367 DEBUG: Incremented Retry for (url='/v2/keys/service/postgres/members/postgre-node-1'): Retry(total=0, connect=None, read=None, redirect=0, status=None)
Nov 14 16:55:11 postgre-node-1 patroni[24390]: 2018-11-14 16:55:11,368 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host=u'10.44.2.47', port=2379): Read timed out. (read timeout=1.66666666667)",)': /v2/keys/service/postgres/members/postgre-node-1
Nov 14 16:55:11 postgre-node-1 patroni[24390]: 2018-11-14 16:55:11,368 DEBUG: Starting new HTTP connection (12): 10.44.2.47:2379
Nov 14 16:55:13 postgre-node-1 patroni[24390]: 2018-11-14 16:55:13,037 ERROR: Request to server http://10.44.2.47:2379 failed: MaxRetryError(u'HTTPConnectionPool(host=u\'10.44.2.47\', port=2379): Max retries exceeded with url: /v2/keys/service/postgres/members/postgre-node-1 (Caused by ReadTimeoutError("HTTPConnectionPool(host=u\'10.44.2.47\', port=2379): Read timed out. (read timeout=1.66666666667)",))',)
Nov 14 16:55:13 postgre-node-1 patroni[24390]: 2018-11-14 16:55:13,038 INFO: Reconnection allowed, looking for another server.
Nov 14 16:55:13 postgre-node-1 patroni[24390]: 2018-11-14 16:55:13,038 DEBUG: Selection next machine in cache. Available machines: []
Nov 14 16:55:13 postgre-node-1 patroni[24390]: 2018-11-14 16:55:13,038 ERROR: Machines cache is empty, no machines to try.
Nov 14 16:55:13 postgre-node-1 patroni[24390]: 2018-11-14 16:55:13,038 ERROR:
Nov 14 16:55:13 postgre-node-1 patroni[24390]: Traceback (most recent call last):
Nov 14 16:55:13 postgre-node-1 patroni[24390]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 341, in wrapper
Nov 14 16:55:13 postgre-node-1 patroni[24390]: retval = func(self, *args, **kwargs) is not None
Nov 14 16:55:13 postgre-node-1 patroni[24390]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 499, in touch_member
Nov 14 16:55:13 postgre-node-1 patroni[24390]: return self._client.set(self.member_path, data, None if permanent else ttl or self._ttl)
Nov 14 16:55:13 postgre-node-1 patroni[24390]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 721, in set
Nov 14 16:55:13 postgre-node-1 patroni[24390]: return self.write(key, value, ttl=ttl)
Nov 14 16:55:13 postgre-node-1 patroni[24390]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 500, in write
Nov 14 16:55:13 postgre-node-1 patroni[24390]: response = self.api_execute(path, method, params=params)
Nov 14 16:55:13 postgre-node-1 patroni[24390]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 205, in api_execute
Nov 14 16:55:13 postgre-node-1 patroni[24390]: response = self._do_http_request(request_executor, method, self._base_uri + path, **kwargs)
Nov 14 16:55:13 postgre-node-1 patroni[24390]: File "/usr/lib/python2.7/site-packages/patroni/dcs/etcd.py", line 168, in _do_http_request
 

Can you help?
Cheers

**Comment by CyberDem0n** [comment]
Do you really use only two etcd nodes? Why?
For HA you must have at least three!

**Comment by svente08** [comment]
Good point... Didn't know that will add another host...

**Comment by svente08** [comment]
Fixed it. Many thx.

**Comment by ashmuh** [comment]
what was the solution

**Comment by svente08** [comment]
Adding 3rd host to etcd cluster
