### ISSUE TITLE
Feature request: Support  postgres-xl

### ISSUE THREAD

**Issue by furenle** [zalando/patroni#868]
Can Patroni support postgres-xl in the current version 10r1 ? In my opinion, it will may be quiet simple to change the config to support the postgres-xl core controller node gtm's HA by use zookeeper or consul and patroni. and keep the proxy node datanode and coord node managed by gtm.  node management can be performed by shell use pgxc_ctl command provide by postgres-xl. the gtm node's tcp port normally is 6666 but can't be connect by postgresql it self, only for cluster management. The postgres-xl Doc  is below:
https://www.postgres-xl.org/documentation/

**Comment by alexeyklyukin** [comment]
You cannot do this by changing the config, unless GTM provides a PostgreSQL-compatible interface (including starting and stopping it), which, to my knowledge, it doesn't (and need not to). Some features, like pg_rewind support in Patroni, would make totally no sense for non-PostgreSQL storage.

You can probably use Patroni to failover data nodes in Postgres-XL.
