### ISSUE TITLE
we should enable data page checksums

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#87]
If patroni is initdb'ing, we should enable data page checksums because:

* it's a good idea
* performance impact is not noticeable under most circumstances
* prior to 9.5, it's required for pg_rewind to be safe to use

**Comment by CyberDem0n** [comment]
I guess we should solve this problem more general. We can create special section in the config.yaml file which will contain all needed parameters and options for initdb

**Comment by jberkus** [comment]
Why?

If Patroni is doing initdb, I don't see why it should give the user an option to turn off checksums.

**Comment by a1exsh** [comment]
Do we have any recent benchmark measuring performance penalty of enabling
data checksums? Last time I saw one, the effect was not nearly negligible,
I believe.

**Comment by jberkus** [comment]
Hmmm, I need to publish.  On workloads I've tested overhead has been < 5%.  Compared to the safety of detecting corruption as soon as it happens, that's negligable.  Also, I'm pretty sure that pg_rewind without checksums is unsafe, and you're building pg_rewind into Patroni.

**Comment by a1exsh** [comment]
Would be glad to see the benchmark. :-)  pg_rewind requires checksums OR
logging of hint bits iirc.

**Comment by alexeyklyukin** [comment]
Patroni can be attached to an already running cluster, or maybe in the future used to initialise new replicas out of the master that is completely unaware of patroni. On both of those cases we cannot guarantee the checksums will be on. We might solve this by fetching the checksum value parameter out of an existing master, but I think it would be easier to just make initdb options configurable.

**Comment by jberkus** [comment]
We don't initdb in either of those cases.

**Comment by alexeyklyukin** [comment]
Oh, right. But we also won't be able to rely on the checksums being on for pg_rewind in those cases. I think we should make this option configurable and choose the default value depending on the results of the benchmarks.

**Comment by feikesteenbergen** [comment]
Implemented with custom options.
