### ISSUE TITLE
error if user comments out postgresql/parameters section

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#88]
Two places in postgresql.py, it does this:

        for setting, value in self.config['parameters'].items():

There's two problems with this code:

1. if the user comments out the parameters section because there are no custom parameters, patroni errors

2. we shouldn't be reaching into config inside a function; this should be passed to self.server_parameters in the init function.

I'll fix this later if someone else doesn't do it first.

**Comment by feikesteenbergen** [comment]
Fixed by PR #93
