### ISSUE TITLE
no pg_hba.conf entry for replication

### ISSUE THREAD

**Issue by an0ma1ia** [zalando/patroni#894]
2-node patroni cluster up and running, replication works fine. After first failover I see the following error message on secondary node:

2018-12-07 09:40:37,183 ERROR: Exception when working with master via replication connection
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 1322, in _check_timeline_and_lsn
    with self._get_replication_connection_cursor(**leader.conn_kwargs()) as cur:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 1248, in _get_replication_connection_cursor
    connect_timeout=3, options='-c statement_timeout=2000') as cur:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 1238, in _get_connection_cursor
    with psycopg2.connect(**kwargs) as conn:
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  no pg_hba.conf entry for replication connection from host "192.168.56.31", user "repl", SSL off

Replication works, all DB changes from primary node I see on the secondary. What causes this error?

**Comment by an0ma1ia** [comment]
All software installed from ubuntu official repo and pgdg:
`$ dpkg -l |grep -e patroni -e postgres |awk '{print $2, $3}'
patroni 1.5.1-2.pgdg18.04+1
pgdg-keyring 2018.2
postgresql-11 11.1-1.pgdg18.04+1
postgresql-11-pgmemcache 2.3.0-6.pgdg18.04+1
postgresql-client-11 11.1-1.pgdg18.04+1
postgresql-client-common 197.pgdg18.04+1
postgresql-common 197.pgdg18.04+1
postgresql-server-dev-11 11.1-1.pgdg18.04+1`

`$ cat /etc/patroni/config.yml
scope: patroni
name: ptr1

restapi:
  listen: 0.0.0.0:8008
  connect_address: 192.168.56.31:8008

etcd:
  hosts: 192.168.56.31:2379,192.168.56.32:2379,192.168.56.1:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 5
        max_replication_slots: 5
        checkpoint_timeout: 30

  initdb:
  - encoding: UTF8

  pg_hba:
  - host all dba all md5
  - host replication repl all md5

  users:
    dba:
      password: secret
      options:
        - createrole
        - createdb
    repl:
      password: secret
      options:
        - replication

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 192.168.56.31:5432
  data_dir: /db/pgsql/data
  config_dir: /db/pgsql/data
  bin_dir: /usr/lib/postgresql/11/bin
  authentication:
    replication:
      username: repl
      password: secret
    superuser:
      username: dba
      password: secret
  parameters:
    unix_socket_directories: '/tmp'
`

**Comment by CyberDem0n** [comment]
Please read https://github.com/zalando/patroni/issues/894#issuecomment-445147115 carefully one more time
