### ISSUE TITLE
PDF generation appears to be broken

### ISSUE THREAD

**Issue by xenophenes** [zalando/patroni#899]
Hello!

There's no information that I can find on how to build the documentation locally (HTML, PDF, or otherwise) so hopefully this has a simple answer, and I'm missing something obvious.

HTML builds fine (using `sphinx-build -b html $src $dst`) but when following the standard commands for converting to PDF, no such luck. It results in a mostly empty PDF file - 
[patroni.pdf](https://github.com/zalando/patroni/files/2696778/patroni.pdf). 

What steps do you take to build a PDF? Any ideas on what's causing the issue?

**System information:**
CentOS 7
Patroni 1.4.4
Sphinx v1.1.3
pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013)
kpathsea version 6.1.1

**Steps to reproduce:**
sphinx-build -b latex patroni_1_4_4/docs $dst
(cd $dst && pdflatex Patroni.tex)

**Output of above steps:**
https://gist.github.com/xenophenes/d4c4b978da26a4ce41a5615a82ace86f

**Comment by CyberDem0n** [comment]
Hi @xenophenes 

I don't think we ever tried to build a PDF manually, but it looks like readthedocs succeeds with this task: https://media.readthedocs.org/pdf/patroni/latest/patroni.pdf

**Comment by xenophenes** [comment]
As a heads up, if you ever want to build the PDF yourselves, the workaround I found was to first remove the ":caption:" line from index.rst (for some reason it didn't like that line). Secondly, the nesting levels go too deep for LaTeX's defaults, so you have to add the following to the beginning of the document:

```
\usepackage{enumitem}
\setlistdepth{9}

\setlist[itemize,1]{label=$\bullet$}
\setlist[itemize,2]{label=$\bullet$}
\setlist[itemize,3]{label=$\bullet$}
\setlist[itemize,4]{label=$\bullet$}
\setlist[itemize,5]{label=$\bullet$}
\setlist[itemize,6]{label=$\bullet$}
\setlist[itemize,7]{label=$\bullet$}
\setlist[itemize,8]{label=$\bullet$}
\setlist[itemize,9]{label=$\bullet$}

\renewlist{itemize}{itemize}{9}

```
Those two changes resulted in a correct PDF.
