### ISSUE TITLE
Problems communicating the postgres PID over stdout during startup

### ISSUE THREAD

**Issue by capistrant** [zalando/patroni#901]
Reference links:
* https://github.com/zalando/patroni/blob/master/patroni/postmaster.py#L159
* https://github.com/zalando/patroni/blob/master/patroni/__init__.py#L175
* https://github.com/zalando/patroni/blob/master/patroni/__init__.py#L160

I am running into an issue when starting Patroni that, quite frankly, I'm not sure hasn't been an issue for other users. After reading through open and closed issues I couldn't find anything that echoed my problem.

The three processes that are running while Postgres is starting up are all writing to the same output stream. The actual Patroni proc specifies `subprocess.PIPE` when it "calls itself" and then the second Patroni proc doesn't specify `stdout` when executing Postgres, resulting in that proc inheriting from parent.  Therefore, we now have all three processes writing to same stream. What I am seeing is that the Postgres process is writing some startup logs to stdout and causing the original Patroni proc to read a line from the stream that is not the Postgres pid that it is looking for. This can be seen in the logs below.. I have confirmed that this is the case by sending stdout and stderr to `/dev/null` for Postgres and starting Patroni.

`Dec 19 19:14:06 patroni-node1-centos7-vagrant.vagrantup.com patroni[9397]: pid = int(proc.stdout.readline().strip())`
`Dec 19 19:14:06 patroni-node1-centos7-vagrant.vagrantup.com patroni[9397]: ValueError: invalid literal for int() with base 10: b'2018-12-19 19:14:06.312 GMT [9415] LOG:  skipping missing configuration file "/etc/pgsql-11/exists.conf"'`

After explaining all of this, I guess my takeaways and questions are as follows:
1. Do I have a mis-config in Postgres that causes startup logs to route to stdout. Once the server starts up, file logging begins as expected.
2. Do we really want to have Postgres writing to the same output stream that we are relying on to produce the Postgres pid for Patroni to leverage? Using stdout for precise inter-process communication seems shaky to begin with, even without a third process there to blow things up.
3. Has there been any talk of switching to [multiprocessing.Process](https://docs.python.org/3/library/multiprocessing.html#the-process-classl) when Patroni calls itself? That way [multiprocessing.Queue](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Queue) (or another process safe communication medium) could be used for the inter-process communication? I'm no Python expert, but at face value that seemed like a possibility to me.

I appreciate any feedback!

**Comment by CyberDem0n** [comment]
Hi,

Actually postgres writes these log messages to stderr, but we did one stupid this by redirecting stderr to stdout :(
I believe https://github.com/zalando/patroni/pull/896 should fix the issue you have.

**Comment by capistrant** [comment]
Confirmed that #896 was the fix I needed. 👍
