### ISSUE TITLE
Feature Proposal: env variable to write Patroni logs to a file.

### ISSUE THREAD

**Issue by capistrant** [zalando/patroni#902]
What I propose is an environment variable, perhaps `PATRONI_LOG_DIR` that supplies a path to an existing directory that is writeable by the executing user. When this environment variable is set, Patroni will create two [RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html?highlight=rotatingfilehandler#logging.handlers.RotatingFileHandler) objects. One for each of root and requests loggers. These handlers would leverage the existing environment variables that control log level and message format.

This would be a non-breaking change since existing users will see everything as business as usual as long as the new environment variable is not set.

Another enhancement that I think would be nice is adding the logger name to the default log line format to provide more context. This would however break any existing users who rely on the default format for things like log parsing, etc.

I look forward to getting some feedback! I can create a PR for this if the community thinks it would be a beneficial feature. I know that my team would certainly like it.

**Comment by CyberDem0n** [comment]
> One for each of root and requests loggers. 

I believe everything should go into the same file. The only reason I set requests logs level to a WARNING by default, is that it is logging too much on INFO.

You are right, the logging system is far from benig ideal, any improvements are welcome.
