### ISSUE TITLE
barman on patroni slave does not run as excpected

### ISSUE THREAD

**Issue by samusouser** [zalando/patroni#905]
hello all,

congratulation for the very good patroni project! 

I've a question about the backup recovery tool barman in combination with postgresql HA and patroni. barman is working fine on our patroni master server. but on the slave server i've a special behavior...
On the slave server i can create new barman backups with "barman backup cdb01b_barman". The new created backup is valid and I can use it for recovery. But "barman cron" get me always the message "Starting check-backup for backup 20181227T174848 of server cdb01b_barman". So the barman counter of backups is always the same as before....

as you can see below: I've 6 barman backups, but barman says I've only 3 backups...

postgres@ejpdxd9044:CDB01B:/data/postgres/barman/cdb01b_barman/base> barman cron
Starting WAL archiving for server cdb01a_barman
Starting WAL archiving for server cdb01b_barman
Starting check-backup for backup 20181227T174848 of server cdb01b_barman
Starting WAL archiving for server sdb04
Starting WAL archiving for server sdb05

postgres@ejpdxd9044:CDB01B:/data/postgres/barman/cdb01b_barman/base> barman list-backup cdb01b_barman
cdb01b_barman 20181228T104017 - Fri Dec 28 10:40:17 2018 - Size: 22.5 MiB - WAL Size: 0 B - -
cdb01b_barman 20181228T103918 - Fri Dec 28 10:39:18 2018 - Size: 22.5 MiB - WAL Size: 0 B - -
cdb01b_barman 20181227T174848 - Thu Dec 27 17:48:48 2018 - Size: 22.6 MiB - WAL Size: 0 B - -
cdb01b_barman 20181227T173132 - Thu Dec 27 17:31:34 2018 - Size: 22.5 MiB - WAL Size: 127.9 KiB
cdb01b_barman 20181227T172958 - Thu Dec 27 17:30:00 2018 - Size: 22.5 MiB - WAL Size: 64.0 KiB
cdb01b_barman 20181227T172824 - Thu Dec 27 17:28:26 2018 - Size: 22.5 MiB - WAL Size: 64.0 KiB

postgres@ejpdxd9044:CDB01B:/data/postgres/barman/cdb01b_barman/base> barman check cdb01b_barman
Server cdb01b_barman:
        PostgreSQL: OK
        is_superuser: OK
        PostgreSQL streaming: OK
        wal_level: OK
        replication slot: OK
        directories: OK
        retention policy settings: OK
        backup maximum age: OK (no last_backup_maximum_age provided)
        compression settings: OK
        failed backups: OK (there are 0 failed backups)
        minimum redundancy requirements: OK (have 3 backups, expected at least 2)
        pg_basebackup: OK
        pg_basebackup compatible: OK
        pg_basebackup supports tablespaces mapping: OK
        pg_receivexlog: OK
        pg_receivexlog compatible: OK
        receive-wal running: OK
        archiver errors: OK

So I ask me what is wrong and what can I do for the resolution..Or is this an expected behavior on a patroni slave server?

thanks a lot for Your Suggestions.

with best regards and happy new year
Stefan

**Comment by CyberDem0n** [comment]
Patroni itself doesn't know anything about barman or any other backup tool. Can it be that you are using wrong barman config?
