### ISSUE TITLE
Create a readonly user

### ISSUE THREAD

**Issue by srimaln91** [zalando/patroni#912]
Hi,

I want to create a read-only user. How can I declare that in the bootstrap config?

**Comment by CyberDem0n** [comment]
There is no such thing in postgres as read-only user.
Patroni can provision a user with certain permissions from [bootstrap](https://github.com/zalando/patroni/blob/master/postgres0.yml#L65-L71), but it will not grant/revoke any permissions to/from it.
If you want flexibility, please use `bootstrap.post_init` script.
