### ISSUE TITLE
[1.5.3] Python crash on shutdown

### ISSUE THREAD

**Issue by tuxmaster5000** [zalando/patroni#914]
Hello,
when I shut-down patroni, it will result in an python exception.

> 019-01-08T15:20:20+0100 foo postgres[19295]: [8-1] < 2019-01-08 15:20:20.528 CET >LOG:  shutting down
> 2019-01-08T15:20:20+0100 foo postgres[19289]: [13-1] < 2019-01-08 15:20:20.540 CET >LOG:  database system is shut down
> 2019-01-08T15:20:21+0100 foo patroni[19278]: 2019-01-08 15:20:21,527 ERROR: wait_for_user_backends_to_close
> 2019-01-08T15:20:21+0100 foo patroni[19278]: Traceback (most recent call last):
> 2019-01-08T15:20:21+0100 foo patroni[19278]: File "/usr/lib/python3.4/site-packages/patroni/__init__.py", line 149, in patroni_main
> 2019-01-08T15:20:21+0100 foo patroni[19278]: patroni.run()
> 2019-01-08T15:20:21+0100 foo patroni[19278]: File "/usr/lib/python3.4/site-packages/patroni/__init__.py", line 123, in run
> 2019-01-08T15:20:21+0100 foo patroni[19278]: self.schedule_next_run()
> 2019-01-08T15:20:21+0100 foo patroni[19278]: File "/usr/lib/python3.4/site-packages/patroni/__init__.py", line 101, in schedule_next_run
> 2019-01-08T15:20:21+0100 foo patroni[19278]: elif self.ha.watch(nap_time):
> 2019-01-08T15:20:21+0100 foo patroni[19278]: File "/usr/lib/python3.4/site-packages/patroni/ha.py", line 1309, in watch
> 2019-01-08T15:20:21+0100 foo patroni[19278]: return self.dcs.watch(leader_index, timeout)
> 2019-01-08T15:20:21+0100 foo patroni[19278]: File "/usr/lib/python3.4/site-packages/patroni/dcs/consul.py", line 516, in watch
> 2019-01-08T15:20:21+0100 foo patroni[19278]: return super(Consul, self).watch(None, timeout)
> 2019-01-08T15:20:21+0100 foo patroni[19278]: File "/usr/lib/python3.4/site-packages/patroni/dcs/__init__.py", line 738, in watch
> 2019-01-08T15:20:21+0100 foo patroni[19278]: self.event.wait(timeout)
> 2019-01-08T15:20:21+0100 foo patroni[19278]: File "/usr/lib64/python3.4/threading.py", line 546, in wait
> 2019-01-08T15:20:21+0100 foo patroni[19278]: signaled = self._cond.wait(timeout)
> 2019-01-08T15:20:21+0100 foo patroni[19278]: File "/usr/lib64/python3.4/threading.py", line 294, in wait
> 2019-01-08T15:20:21+0100 foo patroni[19278]: gotit = waiter.acquire(True, timeout)
> 2019-01-08T15:20:21+0100 foo patroni[19278]: File "/usr/lib/python3.4/site-packages/patroni/__init__.py", line 85, in sigterm_handler
> 2019-01-08T15:20:21+0100 foo patroni[19278]: sys.exit()
> 2019-01-08T15:20:21+0100 foo patroni[19278]: SystemExit
> 2019-01-08T15:20:21+0100 foo patroni[19278]: During handling of the above exception, another exception occurred:
> 2019-01-08T15:20:21+0100 foo patroni[19278]: Traceback (most recent call last):
> 2019-01-08T15:20:21+0100 foo patroni[19278]: File "/usr/lib/python3.4/site-packages/patroni/postmaster.py", line 113, in wait_for_user_backends_to_close
> 2019-01-08T15:20:21+0100 foo patroni[19278]: for child in self.children():
> 2019-01-08T15:20:21+0100 foo patroni[19278]: File "/usr/lib64/python3.4/site-packages/psutil/__init__.py", line 271, in wrapper
> 2019-01-08T15:20:21+0100 foo patroni[19278]: raise NoSuchProcess(self.pid, self._name)
> 2019-01-08T15:20:21+0100 foo patroni[19278]: psutil.NoSuchProcess: process no longer exists (pid=19289)
> 2019-01-08T15:20:21+0100 foo patroni[19278]: 2019-01-08 15:20:21,539 INFO: Lock owner: foo.foo.foo; I am foo.foo.foo
> 2019-01-08T15:20:21+0100 foo systemd[1]: Stopped Runners to orchestrate a high-availability PostgreSQL.
>

**Comment by CyberDem0n** [comment]
Is it happening every time or just once?

**Comment by tuxmaster5000** [comment]
It will happens every shut-down of patroni.
Here my environment:
Python 3.4, CentOS 7.6
PGSQL: postgresql11-server-11.1-1PGDG.rhel7.x86_64
Python 3.4 modules:
python34-3.4.9-1.el7.x86_64
python34-tzlocal-1.5.1-1.el7.noarch
python34-patroni-1.5.3-4.el7.noarch
python34-six-1.11.0-1.el7.noarch
python34-click-6.7-7.el7.noarch
python34-prettytable-7-1.el7.noarch
python34-urllib3-1.19.1-4.el7.noarch
python34-psycopg2-2.7.6-1.el7.x86_64
python34-hvac-0.7.0-1.el7.noarch
python34-setuptools-39.2.0-1.el7.noarch
python34-dateutil-2.4.2-3.el7.noarch
python34-cdiff-1.0-1.el7.noarch
python34-PyYAML-3.11-2.el7.x86_64
python34-requests-2.12.5-2.el7.noarch
python34-kazoo-2.6.0-2.el7.noarch
python34-libs-3.4.9-1.el7.x86_64
python34-chardet-2.3.0-4.el7.noarch
python34-pytz-2017.2-1.el7.noarch
python34-consul-1.1.0-1.el7.noarch
python34-vault-client-0.1.2-1.el7.noarch
python34-patroni-consul-1.5.3-4.el7.noarch
python34-idna-2.7-1.el7.noarch
python34-pysocks-1.6.8-5.el7.noarch
python34-psutil-2.2.1-4.el7.x86_64

**Comment by CyberDem0n** [comment]
Let me guess. You are using watchdog?
I absolutely agree, the exception is annoying, but it is absolutely harmless.
May I ask you to apply https://github.com/zalando/patroni/pull/917 and test it?

**Comment by tuxmaster5000** [comment]
I have tested it and it will work.
Thanks
