### ISSUE TITLE
How to change only as slave?

### ISSUE THREAD

**Issue by smartbayaraa** [zalando/patroni#923]
Hello, Everyone

Currently i have a 3 nodes for Postgresql cluster with HAProxy, Patroni and Etcd.

For example:
node1, node2, node3. 

i want to configure only switch between node1 <> node2 servers. node3 only for replication purpose. Means node3 no need Leader.

Thanks,

**Comment by kostiantyn-nemchenko** [comment]
Hi,

Set [nofailover](  https://github.com/zalando/patroni/blob/929ff08bfde51b28cf90d7bea92db0a5838a4284/postgres0.yml#L96) tag to `true`

**Comment by smartbayaraa** [comment]
@kostiantyn-nemchenko Thank you for your quick reply. It is working as i wish.

One more question. Is it possible use same data directory patroni and postgres?

Means: When i stop patroni and start only postgresql server, it different configuration.

So what is your suggestion about that? Should we use different data dir for patroni or can be same? Because I am new of patroni technology.

Thank you.

**Comment by CyberDem0n** [comment]
> Is it possible use same data directory patroni and postgres? Means: When i stop patroni and start only postgresql server, it different configuration.

Yes, you can do that. Patroni is not replacing postgres, it is just managing it.

> So when i reboot my OS, after patroni not work. Because postgresql started first. Should i disable postgresql from startup

Yes, postgres autostart should be disabled. Otherwise, if postgres was running as master before shutdown or crash, there is a chance to get a split-brain.
If you need autostart, just do do it with Patroni: https://github.com/zalando/patroni/tree/master/extras/startup-scripts

**Comment by smartbayaraa** [comment]
> Yes, postgres autostart should be disabled. Otherwise, if postgres was running as master before shutdown or crash, there is a chance to get a split-brain.
> If you need autostart, just do do it with Patroni: https://github.com/zalando/patroni/tree/master/extras/startup-scripts

This is working well. 

I have disable postgresql and enable patroni.

**Comment by smartbayaraa** [comment]
.
> 
> Yes, you can do that. Patroni is not replacing postgres, it is just managing it.
> 

Currently i couldn't solve this problem. This is my configuration follows:

1. Same data_dir = '/data/patroni' config in /etc/patroni.yml and /etc/postgresql/9.5/main/postgresql.conf

2. Start postgresql without patroni. It could not start (postgres@postgres FATAL:  the database system is starting up)

So how can i start it? or how to move patroni data to postgresql data? 

Please provide me some tutorial. Because i guess, in come case i will start postgres without patroni. 

Thanks
