### ISSUE TITLE
postgres password required even if use_unix_sockets is used

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#928]
Patroni allows for local socket connections if `use_unix_sockets` is `true`. This means that no md5 password is required in order to manage the local Postgres instance, yet, Patroni insists on a `postgresql/authentication/superuser/password` key in the YAML configuration, otherwise I get:

```
2019-01-14 16:07:53,727 ERROR: post_bootstrap
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/patroni/postgresql.py", line 1667, in post_bootstrap
    self.create_or_update_role(self._superuser['username'], self._superuser['password'], ['SUPERUSER'])
KeyError: 'password'
```

If I set a password there, then it gets set as md5 password of `postgres` after bootstrap, even though I don't need it (?). Is there a way to not set the md5 password or is it needed even in the case where `use_pg_rewind: false` is set?

**Comment by CyberDem0n** [comment]
I think we should just fix it in the code.
