### ISSUE TITLE
Errors during conversion docs/*.rst into another formats

### ISSUE THREAD

**Issue by jose-l-goncalves** [zalando/patroni#934]
Hi all,

I'm using patroni last version, 1.5.4.
I'm trying to convert docs/*.rst into man file format but I'm getting some errors (the errors occurs also into another formats, e.g. html).
I'm using /usr/bin/rst2man script of python-docutils-0.11 (official rpm of centos7).

Documents with errors:
_docs/SETTINGS.rst_
<stdin>:33: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:34: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:44: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:45: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:53: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:144: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:154: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:157: (ERROR/3) Unknown interpreted text role "ref".
_docs/README.rst_
<stdin>:20: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:22: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:102: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:108: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:114: (ERROR/3) Unknown interpreted text role "ref".
_docs/releases.rst_
<stdin>:104: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:108: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:129: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:133: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:143: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:308: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:405: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:560: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:621: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:631: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:669: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:750: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:848: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:899: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:949: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:951: (ERROR/3) Unknown interpreted text role "ref".
<stdin>:961: (ERROR/3) Unknown interpreted text role "ref".

Could you help address this issue?

Thank you

**Comment by CyberDem0n** [comment]
Hi @jose-l-goncalves, such `"ref"'s` are needed for [readthedocs](https://patroni.readthedocs.io/en/latest/). Fairly speaking we never targeted the documentation to be built as man pages, html and pdf should work though.

**Comment by jose-l-goncalves** [comment]
Hi @CyberDem0n, like I said "(the errors occurs also into another formats, e.g. html)". This is not specific of conversion to man page, the issue seems to be in the rst format.
We are trying converting into man page to include in our patroni rpm, so the users could consult the documents as man pages (the standard of unix).

**Comment by CyberDem0n** [comment]
Well, readthedocs successfully does its job and converts rst to html and pdf.
Maybe https://github.com/zalando/patroni/issues/899 will give you some food for thoughts?
