### ISSUE TITLE
MaxRetryError: HTTPConnectionPool to consul when change ttl+loop_wait

### ISSUE THREAD

**Issue by combrs** [zalando/patroni#945]
I use patroni 1.5.4 + consul 1.4.0, three postgresql nodes, consul installed on each node and referred as localhost.
    `consul:
        host: localhost:8500`

when I use ttl, loop_wait default parameters 30/10, it works normally without errors/timeouts/exceptions.
If i set this config:
`{"retry_timeout": 10,  "loop_wait": 20, "ttl": 60}`

I got a maxretryerror in log periodically
     File "/usr/lib/python2.7/site-packages/urllib3/util/retry.py", line 398, in increment
         raise MaxRetryError(_pool, url, error or ResponseError(cause))
     MaxRetryError: HTTPConnectionPool(host='localhost', port=8500): Max retries exceeded with url:      /v1/kv/service/postgres/leader?index=115626&wait=19.0750558376s (Caused by  ReadTimeoutError("HTTPConnectionPool(host='localhost', port=8500): Read timed out. (read timeout=20.0750558376)",))

Sometimes every loop_wait, sometimes not.
2019-01-24 15:33:06,919 ERROR: watch
2019-01-24 15:33:26,918 ERROR: watch
2019-01-24 15:34:26,905 ERROR: watch
2019-01-24 15:39:26,919 ERROR: watch
2019-01-24 15:39:46,918 ERROR: watch
2019-01-24 15:41:26,918 ERROR: watch
2019-01-24 15:41:46,918 ERROR: watch
2019-01-24 15:45:46,919 ERROR: watch
2019-01-24 15:47:06,918 ERROR: watch
2019-01-24 15:50:46,920 ERROR: watch
2019-01-24 15:53:06,919 ERROR: watch
2019-01-24 15:54:06,919 ERROR: watch
2019-01-24 15:56:06,919 ERROR: watch
2019-01-24 15:56:26,918 ERROR: watch
2019-01-24 16:02:26,919 ERROR: watch
2019-01-24 16:04:46,919 ERROR: watch
2019-01-24 16:05:06,918 ERROR: watch
2019-01-24 16:07:06,919 ERROR: watch
2019-01-24 16:10:26,919 ERROR: watch
2019-01-24 16:10:46,919 ERROR: watch
2019-01-24 16:12:26,911 ERROR: watch
2019-01-24 16:14:26,918 ERROR: watch
2019-01-24 16:15:26,918 ERROR: watch
2019-01-24 16:15:46,918 ERROR: watch
2019-01-24 16:17:06,920 ERROR: watch
2019-01-24 16:17:26,918 ERROR: watch

Consul works ok and answers immediately for curl
[root@pgnode4 patroni]# time curl "localhost:8500/v1/kv/service/postgres/leader?index=115626&wait=19.0750558376s"
[{"LockIndex":1,"Key":"service/postgres/leader","Flags":0,"Value":"cGdub2RlNw==","Session":"67b0bbfd-d3d9-fa50-1ef1-ace904df2c00","CreateIndex":118421,"ModifyIndex":118421}]
real	0m0.013s
[root@pgnode4 patroni]# time curl "localhost:8500/v1/kv/service/postgres/leader?index=115626&wait=19.0750558376s"
[{"LockIndex":1,"Key":"service/postgres/leader","Flags":0,"Value":"cGdub2RlNw==","Session":"67b0bbfd-d3d9-fa50-1ef1-ace904df2c00","CreateIndex":118421,"ModifyIndex":118421}]
real	0m0.013s
[root@pgnode4 patroni]# time curl "localhost:8500/v1/kv/service/postgres/leader?index=115626&wait=19.0750558376s"
[{"LockIndex":1,"Key":"service/postgres/leader","Flags":0,"Value":"cGdub2RlNw==","Session":"67b0bbfd-d3d9-fa50-1ef1-ace904df2c00","CreateIndex":118421,"ModifyIndex":118421}]
real	0m0.012s
[root@pgnode4 patroni]# time curl "localhost:8500/v1/kv/service/postgres/leader?index=115626&wait=19.0750558376s"
[{"LockIndex":1,"Key":"service/postgres/leader","Flags":0,"Value":"cGdub2RlNw==","Session":"67b0bbfd-d3d9-fa50-1ef1-ace904df2c00","CreateIndex":118421,"ModifyIndex":118421}]
real	0m0.012s
[root@pgnode4 patroni]# time curl "localhost:8500/v1/kv/service/postgres/leader?index=115626&wait=19.0750558376s"
[{"LockIndex":1,"Key":"service/postgres/leader","Flags":0,"Value":"cGdub2RlNw==","Session":"67b0bbfd-d3d9-fa50-1ef1-ace904df2c00","CreateIndex":118421,"ModifyIndex":118421}]
real	0m0.012s
[root@pgnode4 patroni]# time curl "localhost:8500/v1/kv/service/postgres/leader?index=115626&wait=19.0750558376s"
[{"LockIndex":1,"Key":"service/postgres/leader","Flags":0,"Value":"cGdub2RlNw==","Session":"67b0bbfd-d3d9-fa50-1ef1-ace904df2c00","CreateIndex":118421,"ModifyIndex":118421}]
real	0m0.013s

Why it may happen? What are timeout timeout=20.0750558376, how it is calculated? if I set ttl=72, this read timeout remain 20 . (it changes from 19.9 to 20.8)
if I change  retry_timeout to 12, it remains 20 also.

What it means - it cannot get answer from consul in retry_timeout * 2 ? Query, no answer, wait retry_timeout, query again, wrote about Maxretryerror ?

There is an issues like #742, fixed by update in #744, but in my case there is last versions (up to current date) of urllib3, python-consul
Requirement already up-to-date: python-consul in /usr/lib/python2.7/site-packages (1.1.0)
Requirement already up-to-date: urllib3 in /usr/lib/python2.7/site-packages (1.24.1)

**Comment by CyberDem0n** [comment]
> Consul works ok and answers immediately for curl

It answers immediately only because `"ModifyIndex":118421` is bigger than `index=115626`. If the index matches with ModifyIndex, the call should return only after `wait=19.0750558376s` or when the `/leader` key disappears from consul.

http read timeout is set to [1 second bigger](https://github.com/zalando/patroni/blob/master/patroni/dcs/consul.py#L105) than the value of `wait` (20.075 vs 19.075).
Basically Patroni exects to get the answer from Consul after 19s, but for some reason consul doesn't answer even after 20 seconds, therefore you get the ERROR.

> if I set ttl=72, this read timeout remain 20

This is not really read timeout, but loop_wait -- number of seconds we sleep between HA loops. During the sleep every replica is watching for the `/leader` key in order to get fast notification when it disappers.

> if I change retry_timeout to 12, it remains 20 also.

Right, because loop_wait is set to 20.
retry_timeout describes for how long Patroni should repeat attempts of communicating with DCS if it is not accessible before giving up. For example if Patroni fails to update leader lock during `retry_timeout` seconds, it will restart postgres in read-only.

**Comment by combrs** [comment]
But there is a question anyway:
If I have a "loop_wait": 10, "ttl": 30 settings, I have NO consul timeouts at all on 3 nodes (for a last 24 hours).
I set "loop_wait": 20, "ttl": 60 and  now I have it:
2019-01-25 15:59:52,773 ERROR: watch
Traceback (most recent call last): 
.......
MaxRetryError: HTTPConnectionPool(host='localhost', port=8500): Max retries exceeded with url: /v1/kv/service/postgres/leader?index=
129237&wait=18.9692771435s (Caused by ReadTimeoutError("HTTPConnectionPool(host='localhost', port=8500): Read timed out. (read timeout=19.9692771435)",))

with this (current) index consul answers in time

[root@pgnode7 log]# time curl "localhost:8500/v1/kv/service/postgres/leader?index=129237&wait=18.9692771435s"
[{"LockIndex":1,"Key":"service/postgres/leader","Flags":0,"Value":"cGdub2RlNA==","Session":"74fb4a48-d847-4518-97e2-afa5e23c40e3","CreateIndex":129237,"ModifyIndex":129237}]
real	0m19.518s
[root@pgnode7 log]# time curl "localhost:8500/v1/kv/service/postgres/leader?index=129237&wait=8.9692771435s"
[{"LockIndex":1,"Key":"service/postgres/leader","Flags":0,"Value":"cGdub2RlNA==","Session":"74fb4a48-d847-4518-97e2-afa5e23c40e3","CreateIndex":129237,"ModifyIndex":129237}]
real	0m9.418s

I try to figure out a common principles - are the  "loop_wait": 20, "ttl": 60  so bad, or my consul install configured wrongly (but it's mostly by default) ?
Or consul is not so supported and better to use etcd ?
I noticed, for example:
When i edit-config and change ttl (in any way) there is strange disconnects from consul and may be switchovers (to proof this I need collect additional data).

**Comment by CyberDem0n** [comment]
> I try to figure out a common principles - are the "loop_wait": 20, "ttl": 60 so bad, or my consul install configured wrongly (but it's mostly by default) ?

I think I've found the [answer](https://www.consul.io/api/index.html#blocking-queries):

> In addition to index, endpoints that support blocking will also honor a wait parameter specifying a maximum duration for the blocking request. This is limited to 10 minutes. If not set, the wait time defaults to 5 minutes. This value can be specified in the form of "10s" or "5m" (i.e., 10 seconds or 5 minutes, respectively). A _small random amount of additional wait time is added to the supplied maximum wait time_ to spread out the wake up time of any concurrent requests. This **adds up to wait / 16 additional time** to the maximum duration.

Will prepare the fix to this problem.

> When i edit-config and change ttl (in any way) there is strange disconnects from consul and may be switchovers (to proof this I need collect additional data).

It doesn't lead to the switchover (the master isn't affected), but leads to restart of postgres on replicas.
Why does it happen? When you are changing ttl, Patroni needs to create the new [session](https://www.consul.io/api/session.html) and recreate the leader key. Since every replica is watching for leader key changes they immediately get a notification that it was deleted. That basically triggers leader election, but replicas don't have any chance to win it, because the real master is there.

**Comment by combrs** [comment]
I patch this code by hand, and timeouts are gone, thanks. It's fixed.
No more MaxRetryError last day.
