### ISSUE TITLE
patronictl list command shows empty lag

### ISSUE THREAD

**Issue by tigranav** [zalando/patroni#946]
in same case `patronictl list` shows empty lag for replica nodes.
Moreover, it can show either 0, then empty value.

I suppose issue is in this line: 
https://github.com/zalando/patroni/blob/2c128520cf7371c80294c6f1dc7d70b4699a8b50/patroni/ctl.py#L728
Is May be in some case `xlog_location_cluster` can be less then `xlog_location` due to the fact that the answer from the Leader comes along with the answer from the replica?

**Comment by tigranav** [comment]
i have to node installation with etcd as DCS, postgresql v10.6  and patroni v1.4.6

**Comment by CyberDem0n** [comment]
Due to its asynchronous nature sometimes replicas can report wal position which is ahead of last know wal position of the master, in this case we don't show any number there, because it would be negative.

**Comment by tigranav** [comment]
> Due to its asynchronous nature sometimes replicas can report wal position which is ahead of last know wal position of the master, in this case we don't show any number there, because it would be negative.

Why not display as zero in this case?
