### ISSUE TITLE
bootstrap.pg_hba vs. create_replica_method

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#953]
If I read the documentation right then the `pg_hba` entries direct in `boostrap` (i.e. `bootstrap.pg_hba`, not `bootstrap.dcs.postgres.pg_hba`) will get appended to an already existing `pg_hba.conf`.

However, I wonder how this is propagated to standbys if `config_dir` is outside of `PGDATA`? Is the default pg_basebackup method also appending the values from `bootstrap.pg_hba`, or is it assuming that `pg_hba.conf` is located in `PGDATA` and will be copied anyway? Is the custom replica method supposed to do something (what?) here? Or should one just set the HBA data in `bootstrap.dcs.postgres.pg_hba` or `postgresql.pg_hba`?

If the standbys do not append the `bootstrap.pg_hba` entries, the hba configuration will be different between nodes in the cluster.

**Comment by CyberDem0n** [comment]
`bootstrap.pg_hba` takes effect only during the bootstrap phase (running a custom bootstrap script or initdb). Patroni appends a few lines from `bootstrap.pg_hba` to the pg_hba.conf after running a custom bootstrap script or initdb. This section will not be evaluated by replicas. Also it will not copy existing files from the data directory to the config_dir. Config dir was invented for users who likes/wants to manage configuration by some external means. I personally don't recommend using `bootstrap.pg_hba`.

`bootstrap.dcs.postgres.pg_hba` -- this is gets written into `/config` key in a DCS as `postgresql.pg_hba` and later could be changed by running `patronictl edit-config`.  All running nodes will pick the change from DCS and apply it by either rewriting `pg_hba.conf` in the `config_dir` on in the `data_dir`.

If the `postgresql.pg_hba` is defined in the yaml file, it overrides the same section from `DCS:/config`. 

> If the standbys do not append the bootstrap.pg_hba entries, the hba configuration will be different between nodes in the cluster.

Yes, it will not be appended. Bootstrap could happen only once during cluster lifecycle when Patroni executes initdb or custom bootstrap script.

**Comment by mbanck** [comment]
OK, thanks for the clarification; I will avoid `boostrap.pg_hba` then.
