### ISSUE TITLE
patroni_env.conf $PATH not expanded with systemd

### ISSUE THREAD

**Issue by natethebosch** [zalando/patroni#954]
I'm not sure if this is the right place for this ticket. 

The systemd unit that comes with patroni uses `/etc/patroni_env.conf` as an `EnvironmentFile` which is great, but in `/etc/patroni_env.conf` it sets the PATH using `PATH=/...<some postgres path>:$PATH`. The problem is that systemd doesn't expand the $PATH so none of my postgres-archive scripts work. 

I'm on patroni version `1.5.4`

For now I'm just overriding $PATH in `/etc/patroni_env.conf`

**Comment by combrs** [comment]
This is systemd intended behaviour, not a patroni problem. 

"The expansion of $PATH will be done by bash, not systemd. Alternatives such as using Environment=PATH=/new/path:$PATH will not work as systemd will not expand the $PATH"

for example, see 
[this question](https://stackoverflow.com/questions/35439123/systemd-environment-directive-to-set-path)

**Comment by natethebosch** [comment]
@combrs I realize that not expanding variables is intended functionality in systemd, but I'm wondering why it's set that way in `/etc/patroni_env.conf`. Patroni certainly isn't expanding the PATH via bash as you suggest b/c when I set my `archive_command` to `>&2 echo $PATH` (`>&2` added to write to stderr so I can see it in the logs), I get `/...<some postgres path>:$PATH`. 

Are users expected to edit `/etc/patroni_env.conf` with their desired PATH to replace it? Or is there some place that bash is supposed to do the substitution and it isn't?

**Comment by combrs** [comment]
As far I can see, if some env var exported in bash somewhere (for example, in /etc/profile.d) it not affect to systemd patroni unit. Therefore if user want to set $PATH for patroni (to find pg_controldata, for example, if it not in default $PATH) he/she must set PATH in patroni_env.conf directly with full paths and not using variables.
I'm using Centos 7. Maybe authors have additional comments.

**Comment by natethebosch** [comment]
That's right, your bash profile's $PATH doesn't affect the systemd unit. However, `/etc/patroni_env.conf` should contain a valid entry for PATH so that patroni can use it. The default value in `/etc/patroni_env.conf` is `PATH=/...<some postgres path>:$PATH` which isn't useful since `$PATH` isn't ever expanded. There should probably be some documentation somewhere that says you need to manually configure `/etc/patroni_env.conf` or the patroni installer should choose some sane values for `$PATH` and automatically put them into `/etc/patroni_env.conf`

I'm using Centos 7 as well.

**Comment by combrs** [comment]
After patroni installation (pip install patroni) I have not /etc/patroni_env.conf at all, so I have not any "default" values in it. Are you install it from rpm? rpm -qf /etc/patroni_env.conf ? Where did you get it?
This file is optional and may be missing, as seen from .service file.

**Comment by natethebosch** [comment]
I used pip... hmm...
Oooo, you're right. I'm sorry for wasting your time. I just re-tested my installation steps on a fresh machine and I must have created `/etc/patroni_env.conf` manually :/ Sorry! Thanks for helping me out.
