### ISSUE TITLE
support for postgis

### ISSUE THREAD

**Issue by chicco785** [zalando/patroni#955]
hi, i wonder if anyone tried to use patroni for postgis.

thx

**Comment by bradnicholson** [comment]
Postgis in an extension installed into Postgres.  Patroni isn't relevant here.

**Comment by chicco785** [comment]
not sure why not :) as you said, it is an extension to postgres, so in principle you should be able to use patroni also for deploying in ha postgis

**Comment by bradnicholson** [comment]
> so in principle you should be able to use patroni also for deploying in ha postgis

Postgis wal logs, and works with streaming replication, so it will work with Patroni (we use it with Patroni, as many others do I'm sure)

**Comment by chicco785** [comment]
cool :) i couldn't find any documentation on how to do that, I suppose the starting point is a simple as baking a docker image including postgis, and then enabling it via psql

**Comment by bradnicholson** [comment]
No Patroni specific docs are needed for the task.

Create a patroni cluster as per usual.  Ensure you have PostGIS built/installed as you would on any Postgres cluster.

Then use the two together.

**Comment by chicco785** [comment]
top 👍
