### ISSUE TITLE
Question : How to increase max_connection and max_replication_slot on patroni ?

### ISSUE THREAD

**Issue by binooetomo** [zalando/patroni#956]
Dear All

currently i got my postgresql.conf like :

> include 'postgresql.base.conf'
> 
> checkpoint_timeout = '30'
> cluster_name = 'patroni'
> hot_standby = 'on'
> listen_addresses = '192.168.5.81'
> max_connections = '100'
> max_locks_per_transaction = '64'
> max_prepared_transactions = '0'
> max_replication_slots = '10'
> max_wal_senders = '10'
> max_worker_processes = '8'
> port = '5433'
> track_commit_timestamp = 'off'
> unix_socket_directories = '/opt/patroni'
> wal_keep_segments = '8'
> wal_level = 'replica'
> wal_log_hints = 'on'
> hba_file = '/opt/patroni/pgdir/pg_hba.conf'
> ident_file = '/opt/patroni/pgdir/pg_ident.conf'
> 

I got an error :

2019-01-29 19:53:56.602 341456 ERROR oslo_service.service OperationalError: (psycopg2.OperationalError) FATAL:  remaining connection slots are reserved for non-replication superuser connections

So I think I need to increase max_connection and max_replication_slot

What I try is :
1. shutdown patroni
2. remove patroni cluster from etcd
3. Add to my patroni.yml  postgresql.parameters:
    max_connections: 500
    max_replication_slots: 100

4. remove old postgresql.conf
5. start patroni

still new generated postgresql.conf get the exact same values of the old one.
also from 'etcdctl get /service/patroni/config' I got :
{"ttl":30,"loop_wait":10,"retry_timeout":10,"maximum_lag_on_failover":1048576,"postgresql":{"use_pg_rewind":false,"use_slots":true,"parameters":{"wal_level":"replica","hot_standby":"on","wal_keep_segments":8,"max_wal_senders":5,"max_replication_slots":5,"checkpoint_timeout":30}}}

Question : How to increase max_connection and max_replication_slot on patroni ?

Sincerely
-bino-

**Comment by combrs** [comment]
You do not need to "stop patroni" or "remove patroni cluster from etcd"
You can use patronictl edit-config to change parameters dynamically (some parameters do not need restart and apply immediately with auto-reload postgres, some need postgres restart manually and can be done by patronictl  ... restart [cluster] [node]
see [documentation](https://patroni.readthedocs.io/en/latest/dynamic_configuration.html)

If you use config like below it must work, but intendation are very important in yaml

```
postgresql:
  parameters:
    maintenance_work_mem: 1GB
    max_connections: '101'`
  use_pg_rewind: true
```

also see #943

**Comment by CyberDem0n** [comment]
@binooetomo you don't read the documentation, do you?

I would really recommend going through the [tutorial](https://speakerdeck.com/alexeyklyukin/managing-postgresql-clusters-with-patroni?slide=34)

**Comment by binooetomo** [comment]
Ah ....
Solved.

just set EDITOR environment to vim before do edit-config

Thankyou for all supports
Sincerely
-bino-
