### ISSUE TITLE
Patroni started instance as secondary even though PostgreSQL failed to rewind from healthy master

### ISSUE THREAD

**Issue by tomsajan** [zalando/patroni#962]
Hello, 
tonight I encountered a disturbing behavior of Patroni (1.5.3). 
Actually two issues.
Let me describe the situation.
The patroni master started to suffer from very high load. The load was caused by iowait (wrong io scheduler probably) and it caused that the postgres was not responding to any user requests, making the cluster unavailable. It was still pinging, but it was not possible to even ssh to the server.
Yet the server was still available on it's api, so haproxy was still sending traffic to it and also `patronictl` showed no indication that something is wrong.
An attempt to manual switchover failed with 503
```root@patroni06c<redacted>(service):~# patronictl -c /etc/patroni/patroni.yml switchover patroni06-p11
Master [patroni06a]: 
Candidate ['patroni06b', 'patroni06c'] []: patroni06b
When should the switchover take place (e.g. 2015-10-01T14:30)  [now]: 
Current cluster topology
+---------------+------------+--------------------------+--------+---------+-----------+
|    Cluster    |   Member   |           Host           |  Role  |  State  | Lag in MB |
+---------------+------------+--------------------------+--------+---------+-----------+
| patroni06-p11 | patroni06a | patroni06a<redacted> | Leader | running |       0.0 |
| patroni06-p11 | patroni06b | patroni06b<redacted> |        | running |       0.0 |
| patroni06-p11 | patroni06c | patroni06c<redacted> |        | running |       0.0 |
+---------------+------------+--------------------------+--------+---------+-----------+
Are you sure you want to switchover cluster patroni06-p11, demoting current master patroni06a? [y/N]: y
Switchover failed, details: 503, Switchover status unknown
```
Rebooting the machine solved the issue, but it still concerns me that patroni still kept the unresponsive node alive. The node was not even able to write logs, etc..

Now to the main issue:
After the reboot, patroni started postgres on the node even though it detected issues and postgres was complaining about it:
Logs from Patroni
```Jan 31 02:33:18 patroni06a patroni[792]: 2019-01-31 02:33:18,256 INFO: Lock owner: patroni06a; I am patroni06a
Jan 31 02:33:18 patroni06a patroni[792]: 2019-01-31 02:33:18,305 INFO: no action.  i am the leader with the lock
Jan 31 02:33:28 patroni06a patroni[792]: 2019-01-31 02:33:28,256 INFO: Lock owner: patroni06a; I am patroni06a
Jan 31 02:33:28 patroni06a patroni[792]: 2019-01-31 02:33:28,305 INFO: no action.  i am the leader with the lock
-- Reboot --
Jan 31 03:02:09 patroni06a systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
Jan 31 03:02:14 patroni06a patroni[835]: 2019-01-31 03:02:14,356 WARNING: Postgresql is not running.
Jan 31 03:02:14 patroni06a patroni[835]: 2019-01-31 03:02:14,356 INFO: Lock owner: patroni06b; I am patroni06a
Jan 31 03:02:14 patroni06a patroni[835]: 2019-01-31 03:02:14,369 INFO: doing crash recovery in a single user mode
Jan 31 03:02:14 patroni06a patroni[835]: 2019-01-31 03:02:14,371 INFO: Lock owner: patroni06b; I am patroni06a
Jan 31 03:02:14 patroni06a patroni[835]: 2019-01-31 03:02:14,371 INFO: doing crash recovery in a single user mode in progress
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,097 WARNING: Postgresql is not running.
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,097 INFO: Lock owner: patroni06b; I am patroni06a
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,102 INFO: Lock owner: patroni06b; I am patroni06a
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,110 INFO: Local timeline=4 lsn=B7/BC000028
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,120 INFO: master_timeline=5
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,120 INFO: master: history=1        0/1C000098        no recovery target specified
Jan 31 03:02:20 patroni06a patroni[835]: 2        70/12000098        no recovery target specified
Jan 31 03:02:20 patroni06a patroni[835]: 3        A6/2000098        no recovery target specified
Jan 31 03:02:20 patroni06a patroni[835]: 4        B7/BBDE88A8        no recovery target specified
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,122 INFO: running pg_rewind from patroni06b
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,228 INFO: running pg_rewind from user=postgres host=patroni06b<redacted> port=5432 dbname=postgres sslmode=prefer sslcompression=1
Jan 31 03:02:20 patroni06a patroni[835]: servers diverged at WAL location B7/BBDE88A8 on timeline 4
Jan 31 03:02:20 patroni06a patroni[835]: could not open file "/var/lib/postgresql/11/patroni/pg_wal/00000004000000B7000000B2": No such file or directory
Jan 31 03:02:20 patroni06a patroni[835]: could not find previous WAL record at B7/B2FFE378
Jan 31 03:02:20 patroni06a patroni[835]: Failure, exiting
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,302 ERROR: Failed to rewind from healty master: patroni06b
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,338 WARNING: Postgresql is not running.
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,339 INFO: Lock owner: patroni06b; I am patroni06a
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,343 INFO: Lock owner: patroni06b; I am patroni06a
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,345 INFO: starting as a secondary
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,508 INFO: postmaster pid=1404
Jan 31 03:02:20 patroni06a patroni[835]: localhost:5432 - rejecting connections
Jan 31 03:02:20 patroni06a patroni[835]: localhost:5432 - accepting connections
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,762 INFO: Lock owner: patroni06b; I am patroni06a
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,762 INFO: does not have lock
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,762 INFO: establishing a new patroni connection to the postgres cluster
Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,793 INFO: no action.  i am a secondary and i am following a leader
Jan 31 03:02:31 patroni06a patroni[835]: 2019-01-31 03:02:31,674 INFO: Lock owner: patroni06b; I am patroni06a
Jan 31 03:02:31 patroni06a patroni[835]: 2019-01-31 03:02:31,674 INFO: does not have lock
```
I shall highlight:
```servers diverged at WAL location B7/BBDE88A8 on timeline 4
could not find previous WAL record at B7/B2FFE378
Failure, exiting
ERROR: Failed to rewind from healty master: patroni06b
starting as a secondary
```

The lag started to grow
```
root@patroni06a<redacted>(service):~# patronictl -c /etc/patroni/patroni.yml list
+---------------+------------+--------------------------+--------+---------+-----------+
|    Cluster    |   Member   |           Host           |  Role  |  State  | Lag in MB |
+---------------+------------+--------------------------+--------+---------+-----------+
| patroni06-p11 | patroni06a | patroni06a<redacted> |        | running |     272.0 |
| patroni06-p11 | patroni06b | patroni06b<redacted> | Leader | running |       0.0 |
| patroni06-p11 | patroni06c | patroni06c<redacted> |        | running |       0.0 |
+---------------+------------+--------------------------+--------+---------+-----------+
```
Postgres was still complaining it it's history has forked
```
2019-01-31 03:29:12 GMT [5493]: [1-1] user=,db= FATAL:  could not start WAL streaming: ERROR:  requested starting point B7/BC000000 on timeline 4 is not in this server's history
        DETAIL:  This server's history forked from timeline 4 at B7/BBDE88A8.
2019-01-31 03:29:12 GMT [1409]: [328-1] user=,db= LOG:  new timeline 5 forked off current database system timeline 4 before current recovery point B7/BC000098
```
Member reinit eventually helped.

I believe this is not a desired behavior of patroni, definitely should not start as a secondary. It should report a problem.

Thanks for any feedback!
Jan.

**Comment by CyberDem0n** [comment]
> The patroni master started to suffer from very high load. The load was caused by iowait (wrong io scheduler probably) and it caused that the postgres was not responding to any user requests, making the cluster unavailable. It was still pinging, but it was not possible to even ssh to the server.
Yet the server was still available on it's api, so haproxy was still sending traffic to it and also patronictl showed no indication that something is wrong.

Yep, because from the Patroni perspective everything was fine. Postgres was up and running. This is your responsibility to monitor server and database.

> An attempt to manual switchover failed with 503

It is not entirely failed, it actually responded as `Switchover status unknown`. Basically that means it started shutting down the postgres, but due to high load it took longer than one minute.

> but it still concerns me that patroni still kept the unresponsive node alive

Please define "unresponsive". Patroni is keeping the connection to the Posgres and periodically executing queries. Obviously postgres was able to run them, therefore from Patroni perspective everything was fine. If you want to do a failover if for example load average is above some threshold - I would say this is an absolutely stupid idea, because right after a failover you'll get the same load (or even higher) on the new master and the next failover.

> After the reboot, patroni started postgres on the node even though it detected issues and postgres was complaining about it:

Well, Patroni successfully detected that it needs to execute pg_rewind and executed it. But pg_rewind failed due to missing wal segments.
Since `remove_data_directory_on_rewind_failure` wasn't set, Patroni did the best it can do and started the postgres.

> I believe this is not a desired behavior of patroni, definitely should not start as a secondary. It should report a problem.

It actually **reported the problem** `Jan 31 03:02:20 patroni06a patroni[835]: 2019-01-31 03:02:20,302 ERROR: Failed to rewind from healty master: patroni06b`

**Comment by tomsajan** [comment]
Hello, thank you very much for your prompt feedback and explanation of the issues.
It is clear now that Patroni reacted as authors intended.
In the case of the rewind failure I just expected Patroni to maybe stop the slave and make the rewind failure more visible via API or patronictl - tools that can be used for monitoring. But of course, even in the current state, the increased lag would surely bring an attention.

I have a proposal in this matter. I don't think that the two options we have (either continue like nothing happened or to reinit from the master) cover all the actions.
May I suggest to extend the `remove_data_directory_on_rewind_failure` option a bit? 
I was thinking about a new config option `on_rewind_failure` that could replace the `remove_data_directory_on_rewind_failure`.

The possible values could be:
- `reinit`: the same as setting `true` for the current option
- `stop`: stop the node and let the operator later decide what to do
- `continue`: the same as the default setting (`false`) for the current option

Thank you considering this proposal.
Best,
Jan

**Comment by combrs** [comment]
There is  a good explanation of backup or not-backup methods at FOSDEM . It stated that replication IS NOT ENOUGH to all causes with cluster. And patroni (by default) is not enough to catch-all any situations with replicas.

See here 
https://archive.fosdem.org/2017/schedule/event/postgresql_backup/

I try to resolve the "could not find previous WAL record at B7/B2FFE378" cause by enable wal archiving (see #964) and 
create_replica_methods:
  - wal_g

As I think, cluster must have a "restore replica" method using base backups and wal archives if master are failovered / pg_rewind failed/ tilmeline switched/unaccessible/other.
