### ISSUE TITLE
"restart required" on every config change because archive_mode on/true

### ISSUE THREAD

**Issue by combrs** [zalando/patroni#964]
I change via edit-config this parameter
archive_node: true

(really in postgres docs it looks as archive_mode=on or archive_mode=auto, but I think it is boolean and set it to 'true')
Now it is:
# consul kv get /service/postgres/config
{....  "postgresql": {"parameters": {"log_min_messages": "NOTICE", "archive_mode": true .....

Change for this parameter requires restart. I restarted all nodes 2 times, and "pending" flag  are gone. But then, if I change some parameter does NOT require restart, I got in patroni.log:
2019-02-06 17:20:47,454 INFO: Changed archive_mode from on to True (restart required)
And 'pending' flag appears again.

How to fix it?
Editing this parameter (true -> on) via edit-config does Nothing!
I'm use mcedit, and when i change it and save - patroni do not see differences ...

**Comment by CyberDem0n** [comment]
It is the yaml's quirk, unquoted `true`, `false`, 'on', `off` are treated as booleans.

**Comment by combrs** [comment]
Thanks, I change it to
````archive_mode: 'on' ````

same problem with 
````random_page_cost: '2.0'````
it's always change to 2 without quotes
Pending status are gone without restart (after apply changes and reload)
2019-02-08 12:04:35,515 INFO: Changed random_page_cost from 2 to 2.0
2019-02-08 12:04:35,517 INFO: PostgreSQL configuration items changed, reloading configuration.

It's one more reason to lint yamls in patroni, with advices to change :)
