### ISSUE TITLE
Any possible breaking change bumping from 1.3.4 to the latest?

### ISSUE THREAD

**Issue by IJOL** [zalando/patroni#974]
Hola a todos:

We are very happy users from patroni from a point somewhere between 1.3.4 and 1.3.5,  bumping to the latest version is safe, or there are any breaking changes, that i should take care before updating to latest?

Sorry for the nosise, and thanks for any help in adavance
Saludos, Ignacio J. Ortega

**Comment by CyberDem0n** [comment]
Hi,

Usually we are quite good backward compatible, but in general we always recommend to first upgrade replicas and only after that the primary.

Upgrade of the primary could be done either by enabling maintenance mode (patronictl pause) or by performing the switchover to one of the replicas.
