### ISSUE TITLE
Recovering from DCS downtime and Consul agent

### ISSUE THREAD

**Issue by Valeriyy** [zalando/patroni#977]
Hello!
1. I have already read https://github.com/zalando/patroni/issues/909 but I still have a question.
I'm use Consul on 3 dedicated servers and I have two Postrgres servers master-slave with Consul Agents. And I find it unacceptable to switch PostgreSQL master to read only if I lose the Consul cluster. I want to get a setting in Patroni that disables this behavior. Or what can I do to Patroni did nothing in case of the fall of the entire DSC cluster? Patroni must make a decision after restoring the Consul cluster failure
2. I noticed that if you stop the Consul Agent on the leader, the program will switch the master. This raises the question of why Patroni can't poll the state of the PostgreSQL master using SQL and only then decide to switch? Very often there is a situation that after updating the Consul Agent it does not start. How to avoid such a situation? I must say that 'patronictl pause' is not suitable before updating Consul

**Comment by CyberDem0n** [comment]
Please get yourself familiar with the [CAP theorem](https://www.google.de/search?q=cap+theorem). The system can't be **C**onsistent **A**vailable and **P**artition tolerant at the same time. Patroni chooses partition tolerance over availability.

**Comment by Valeriyy** [comment]
@CyberDem0n I understand everything, but I would still like to satisfy these 2 points
Stolon or MySQL Orchestrator from GutHub does not switch the master in case of failure of the Consul agent to the server with the PostgreSQL master or in case of failure the whole Consul cluster

**Comment by CyberDem0n** [comment]
Well, well, well. Let's assume that the server where the master is running is partitioned from remaining nodes.
The winning side of partitioning will choose the new master, but the old master at the same time continues to run. Congratulations, you have a split-brain.

**Comment by CyberDem0n** [comment]
> Patroni just needs to be guided not only data obtained from the Consul, but the current health of the master through SQL interface

DCS is our source of truth, when it is not accessible Patroni knows that postgres can't continue to run as the master. Period.

> the agent on the PostgreSQL servers can not start for some time because of the incompatibility of the old configuration

Here you are just trying to shift responsibilities. That's not a Patroni who is operating Consul. This is your task to make such Consul upgrades as smooth as possible. If you can't do it - please use `pause` mode.

**Comment by Valeriyy** [comment]
OK, and it is possible to make so that in case of unavailability of together **all** servers of DSC, Patroni did not switch to RO master instance PostgreSQL?
I ask you to pay attention to the algorithms of [Orchestrator](https://github.com/github/orchestrator) from GitHub. If all servers DSC is unavailable, it checks the entire MySQL topology. That is, it polls the state of each instance MySQL through the SQL interface.

**Comment by CyberDem0n** [comment]
> in case of unavailability of together all servers of DSC, Patroni did not switch to RO master instance PostgreSQL?

No, it is not. If you can't access DCS, which is the source of trust you can't determine your state and therefore is not allowed to run as a master.

> I ask you to pay attention to the algorithms of Orchestrator from GitHub. If all servers DSC is unavailable, it checks the entire MySQL topology. That is, it polls the state of each instance MySQL through the SQL interface.

AFAIK Orchestrator itself implements RAFT algorithm and doesn't rely on external consistency store at all.

**Comment by Valeriyy** [comment]
> AFAIK Orchestrator itself implements RAFT algorithm and doesn't rely on external consistency store at all.

And for PostgreSQL so far no one has come up with such a strong solution.
By the way, I tested Stolon and in case of unavailability of the entire contour of DSC, no one switches master in read only

> No, it is not. If you can't access DCS, which is the source of trust you can't determine your state and therefore is not allowed to run as a master.

You can save and update the last value of 'select pg_is_in_recovery()' in memory, and if all DSC servers fail, then will be checked the value 'select pg_is_in_recovery()' from memory against the current value of the database instances. I believe it is unacceptable to switch the master in RO, if the entire DSC is not available.

**Comment by CyberDem0n** [comment]
Let me repeat myself:

> Please get yourself familiar with the [CAP theorem](https://www.google.de/search?q=cap+theorem). The system can't be **C**onsistent **A**vailable and **P**artition tolerant at the same time.

You can choose only two out of three. By ignoring DCS accessibility and staying available you stop being partition tolerant and therefore may lose consistency (split-brain)

It is not possible to distinguish between cases of DCS being down vs you being isolated.

**Comment by redbaron** [comment]
> You can choose only two out of three. By ignoring DCS accessibility and staying available you stop being partition tolerant and therefore may lose consistency (split-brain)

you can give this choice to users. lets say in a singe AZ setup (such as on-premise) what is more likely to happen: lockup of DCS or once in a thousand year network partition? not all databases are critical as well and being up can be more important if risk of partitioning is low.

**Comment by CyberDem0n** [comment]
We are not going to implement a footgun.
If somebody wants to improve tolerance of DCS unavailability, they should simply increase `ttl` and `retry_timeout`.

**Comment by Valeriyy** [comment]
> Please get yourself familiar with the [CAP theorem](https://www.google.de/search?q=cap+theorem). The system can't be **C**onsistent **A**vailable and **P**artition tolerant at the same time. Patroni chooses partition tolerance over availability.

You are then ready to explain to my CIO about the CAP theorem and the ACID paradigm when cluster DSC will be fuckup?
I think it is nonsense to switch master in RO in case of failure of everything DSC cluster. What will be happens when DSC cluster recovers from the failure? UFO will arrive and change the information about the leader? So I decided to use Stolon

**Comment by CyberDem0n** [comment]
> You are then ready to explain to my CIO about the CAP theorem and the ACID paradigm when cluster DSC will be fuckup?

It is a fundamental law and it applies to everybody, even to the persons who don't understand it.

> So I decided to use Stolon

Good luck in resolving a split-brain and explaining to your boss how you got into such situation.

**Comment by Valeriyy** [comment]
You have not given any cases in which I will get split brain after return of the failed DSC cluster.

**Comment by ants** [comment]
It's not possible to distinguish between a failed DSC cluster and somebody screwing up firewall rules on the master node.

**Comment by Valeriyy** [comment]
Well, in that case, you should think about review the architecture of Patroni so that it uses RAFT and complies with the quorum. How it is done in MySQL Orchestrator from GitHub

**Comment by alexeyklyukin** [comment]
@Valeriyy 

They only way I see Patroni to avoid going all read-only when DCS is not there is by disabling the automatic failover completely. The way to do it currently is by putting a cluster in the maintenance mode, however, this requires triggering a key in DSC so it's not a good solution when DCS is not available. Any solution that triggers this mode individually on Patroni nodes seem to be rather unsafe (think about race conditions with newly joined nodes without this mode when DCS suddenly goes back). So the only reasonable way to do this would be by disabling the possibility of automatic failover, which might be useful in some cases, but doesn't seem like something the topic starter wants here.

> By the way, I tested Stolon and in case of unavailability of the entire contour of DSC, no one switches master in read only

You should file a bug to Stolon, seriously. Unless they use the second RAFT layer to globally agree on the DCS unavailability, keeping things as they were is prone to the difference in perception between individual nodes and may easily lead to a split brain. The solution below:

> You can save and update the last value of 'select pg_is_in_recovery()' in memory, and if all DSC servers fail, then will be checked the value 'select pg_is_in_recovery()' from memory against the current value of the database instances. I believe it is unacceptable to switch the master in RO, if the entire DSC is not available.

won't help, because it's vulnerable to disagreements between nodes when some of them see the primary and others not, unless you implement a full-scale consensus algorithm for that.

BTW, have you seen https://github.com/zalando/patroni/pull/375?

**Comment by redbaron** [comment]
@Valeriyy , 
there is a discussion of patroni doing quorum itself https://github.com/zalando/patroni/pull/375

**Comment by redbaron** [comment]
> Any solution that triggers this mode individually on Patroni nodes seem to be rather unsafe


Patroni is useful (especially in combination with postgres-operator) not only to ensure HA. Single node setup still benefit from convenience of unified deploy, postgresql.conf management, health checks, standby clusters, etc.

Would you be opposed to disable ReadOnly switch, when there are no other possible candidates to swtich to? In other words if master's view of the world was that it was the only possible master to be elected ever (as in single node setup or tags on replicas are preventing them from being promoted), then in case of DCS downtime do nothing and stay in read write mode. Assumption here is that without manual intervention there can be no split brain ever, as there can be no other masters.

**Comment by alexeyklyukin** [comment]
> > Any solution that triggers this mode individually on Patroni nodes seem to be rather unsafe
> 
> Patroni is useful (especially in combination with postgres-operator) not only to ensure HA. Single node setup still benefit from convenience of unified deploy, postgresql.conf management, health checks, standby clusters, etc.
> 
> Would you be opposed to disable ReadOnly switch, when there are no other possible candidates to swtich to? In other words if master's view of the world was that it was the only possible master to be elected ever (as in single node setup or tags on replicas are preventing them from being promoted), then in case of DCS downtime do nothing and stay in read write mode. Assumption here is that without manual intervention there can be no split brain ever, as there can be no other masters.

The conditions above make automatic failover unnecessary, I wrote about it in my previous reply:

> So the only reasonable way to do this would be by disabling the possibility of automatic failover altogether, which might be useful in some cases, but doesn't seem like something the topic starter wants here.

**Comment by Valeriyy** [comment]
> @Valeriyy ,
> there is a discussion of patroni doing quorum itself #375

Will Patroni work without DSC or will it still use DSC to store status information?
