### ISSUE TITLE
Patroni etcd network traffic estimation question

### ISSUE THREAD

**Issue by kmoppel** [zalando/patroni#982]
Hey,
Was looking for some network bandwidth / latency suggestions or minimal requirements when using etcd...but couldn't find anything (except etcd official recommendations). Has someone maybe tried to measure / quantify the minimal needs? e.g. how much per node / total (3 etcd nodes) traffic is generated for a single cluster with default TTL etc settings plus HAProxy with sample config used for connection routing.
Cheers

**Comment by CyberDem0n** [comment]
I recently updated https://github.com/zalando/patroni/blob/master/docker-compose.yml
From now on it starts etcd cluster of 3 nodes + 3 Patroni containers + HAProxy.
You can try to measure it on your own.
