### ISSUE TITLE
Is patroni 1.5.5 supporting postgresql 11 and python 3.6? 

### ISSUE THREAD

**Issue by omm1979** [zalando/patroni#987]
Hi i've some troubles starting or init with patroni.yaml configuration 
My configuration cluster test (without containers -docker-vagrant) just VM testing:
--------------------------------------
patroni 1.5.5 + postgresql 11 and python 3.6 + ubuntu server 18.04
--------------------------------------
I followed the https://www.linode.com/docs/databases/postgresql/create-a-highly-available-postgresql-cluster-using-patroni-and-haproxy/ tutorial but when install patroni and configure it, the patroni.service doesn't start.

--------------------------------------
my test config file is: patroni.service:

[Unit]
Description=Runners para orquestar un cluster PostgreSQL HA o de alta disponibilidad
After=syslog.target network.target
[Service]
Type=simple
User=postgres
Group=postgres
ExecStart=/usr/local/bin/patroni /etc/patroni.yml
ExecReload=/bin/kill -s HUP $MAINPID
KillMode=process
TimeoutSec=30
Restart=no
[Install]
WantedBy=multi-user.target

--------------------------------------
patroni.yml configuration file with:

scope:postgres
namespace:/db/
name:patronipsql1

restapi:listen:192.168.18.150:8008
connect_address:192.168.18.150:8008

etcd:host:192.168.18.153:2379

bootstrap:dcs:ttl:30
loop_wait:10
retry_timeout:10
maximum_lag_on_failover:1048576
postgresql:use_pg_rewind:true

initdb:- encoding:UTF8
- data-checksums

pg_hba:- host replication replicador 127.0.0.1/32 md5 
- host replication replicador 192.168.18.150/0 md5 
- host replication replicador 192.168.18.151/0 md5 
- host replication replicador 192.168.18.152/0 md5 
- host all all 0.0.0.0/0 md5

users:admin:password:pass1
options:- createrole - createdb 
replicador:password:pass2
options:-replication

postgresql:listen:192.168.18.150:5432
connect_address:192.168.18.150:5432
bin_dir:/usr/lib/postgresql/11/bin
data_dir:/data/patroni
pgpass:/tmp/pgpass 
authentication:replication:username:replicador
password:pass2
superuser:username:admin
password:pass1
parameters:unix_socket_directories:'.'

tags:nofailover:false
noloadbalance:false
clonefrom:false
nosync:false
--------------------------------------

the problem start when doing:  service patroni start
or doing:  patronictl -c /etc/patroni.yml configure

output Error from above command (patronictl -c /etc/patroni.yml configure):
--------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 10, in <module>
    sys.exit(ctl())
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 117, in ctl
    ctx.obj = load_config(config_file, dcs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 80, in load_config
    config = Config().copy()
  File "/usr/local/lib/python3.6/dist-packages/patroni/config.py", line 78, in __init__
    self._local_configuration = self._load_config_file()
  File "/usr/local/lib/python3.6/dist-packages/patroni/config.py", line 109, in _load_config_file
    patch_config(config, self.__environment_configuration)
  File "/usr/local/lib/python3.6/dist-packages/patroni/utils.py", line 46, in patch_config
    if isinstance(config[name], dict):
TypeError: string indices must be integers
--------------------------------------
output Error from /var/log/syslog:
Mar  1 12:39:34 patroni_prueba1 systemd[1]: Started Runners para orquestar un cluster PostgreSQL HA o de alta disponibilidad.
Mar  1 12:39:34 patroni_prueba1 patroni[2057]: Traceback (most recent call last):
Mar  1 12:39:34 patroni_prueba1 patroni[2057]:   File "/usr/local/bin/patroni", line 10, in <module>
Mar  1 12:39:34 patroni_prueba1 patroni[2057]:     sys.exit(main())
Mar  1 12:39:34 patroni_prueba1 patroni[2057]:   File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 182, in main
Mar  1 12:39:34 patroni_prueba1 patroni[2057]:     return patroni_main()
Mar  1 12:39:34 patroni_prueba1 patroni[2057]:   File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 146, in patroni_main
Mar  1 12:39:34 patroni_prueba1 patroni[2057]:     patroni = Patroni()
Mar  1 12:39:34 patroni_prueba1 patroni[2057]:   File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 26, in __init__
Mar  1 12:39:34 patroni_prueba1 patroni[2057]:     self.config = Config()
Mar  1 12:39:34 patroni_prueba1 patroni[2057]:   File "/usr/local/lib/python3.6/dist-packages/patroni/config.py", line 88, in __init__
Mar  1 12:39:34 patroni_prueba1 patroni[2057]:     self.__effective_configuration = self._build_effective_configuration({}, self._local_configuration)
Mar  1 12:39:34 patroni_prueba1 patroni[2057]:   File "/usr/local/lib/python3.6/dist-packages/patroni/config.py", line 327, in _build_effective_configuration
Mar  1 12:39:34 patroni_prueba1 patroni[2057]:     for name, value in local_configuration.items():
Mar  1 12:39:34 patroni_prueba1 patroni[2057]: AttributeError: 'str' object has no attribute 'items'
Mar  1 12:39:34 patroni_prueba1 systemd[1]: patroni.service: Main process exited, code=exited, status=1/FAILURE
Mar  1 12:39:34 patroni_prueba1 systemd[1]: patroni.service: Failed with result 'exit-code'.

I hope someone could helpme and standby for your help, thanks.

**Comment by CyberDem0n** [comment]
In `yaml` indentation plays very important role.

Config file is malformed, also a lot of formatting was lost during copy&paste here so I can't even tell what exactly is wrong with the config.

**Comment by omm1979** [comment]
OK, thanks for your reply, i tried another nviroment cluster config.: 
patroni 1.5.5 + postgresql 10 + python 2.7 + ubuntu server 18.04
__________________________________________________________________
i'll put the original patroni.yml identation format file like:
__________________________________________________________________
patroni.yml
__________________________________________________________________
scope: postgres
namespace: /db/
name: patronipsql1

restapi:
 listen: 192.168.18.150:8008
 connect_address: 192.168.18.150:8008

etcd: 
 host: 192.168.18.153:2379

bootstrap:
 dcs:
  ttl: 30
  loop_wait: 10
  retry_timeout: 10
  maximum_lag_on_failover: 1048576
  postgresql:
   use_pg_rewind: true

 initdb:
  - encoding: UTF8
  - data-checksums

 pg_hba:
  - host replication replicador 127.0.0.1/32 md5
  - host replication replicador 192.168.18.150/0 md5
  - host replication replicador 192.168.18.151/0 md5
  - host replication replicador 192.168.18.152/0 md5
  - host all all 0.0.0.0/0 md5
 
 users:
  admin:
   password: pass1
   options:
    - createrole
    - createdb 
  replicador:
   password: pass2
   options:
    - replication

postgresql:
 listen: 192.168.18.150:5432
 connect_address: 192.168.18.150:5432
 bin_dir: /usr/lib/postgresql/10/bin
 data_dir: /data/patroni
 pgpass: /tmp/pgpass 
 authentication:
  replication:
   username: replicador
   password: pass2
  superuser:
   username: admin
   password: pass1
 parameters:
   unix_socket_directories: '.'

tags:
 nofailover: false
 noloadbalance: false
 clonefrom: false
 nosync: false

__________________________________________________________________
chown postgres:postgres -R /data/patroni
chmod 700 /data/patroni
__________________________________________________________________
same patroni.service config
__________________________________________________________________
[Unit]
Description=Runners para orquestar un cluster PostgreSQL HA o de alta disponibilidad
After=syslog.target network.target

[Service]
Type=simple

User=postgres
Group=postgres

ExecStart=/usr/local/bin/patroni /etc/patroni.yml

ExecReload=/bin/kill -s HUP $MAINPID

KillMode=process

TimeoutSec=30

Restart=no

[Install]
WantedBy=multi-user.target
__________________________________________________________________
Executing: systemctl start patroni 
different result in syslog:

Mar  1 21:47:06 patroni_prueba1 systemd[1]: Started Runners para orquestar un cluster PostgreSQL HA o de alta disponibilidad.
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:06,142 INFO: Failed to import patroni.dcs.consul
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:06,151 INFO: Selected new etcd server http://192.168.18.153:2379
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:06,163 INFO: Lock owner: None; I am patronipsql1
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:06,166 INFO: trying to bootstrap a new cluster
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: The files belonging to this database system will be owned by user "postgres".
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: This user must also own the server process.
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: The database cluster will be initialized with locale "es_ES.UTF-8".
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: The default text search configuration will be set to "spanish".
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: Data page checksums are enabled.
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: fixing permissions on existing directory /data/patroni ... ok
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: creating subdirectories ... ok
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: selecting default max_connections ... 100
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: selecting default shared_buffers ... 128MB
Mar  1 21:47:06 patroni_prueba1 patroni[2437]: selecting dynamic shared memory implementation ... posix
Mar  1 21:47:07 patroni_prueba1 patroni[2437]: creating configuration files ... ok
Mar  1 21:47:07 patroni_prueba1 patroni[2437]: running bootstrap script ... ok
Mar  1 21:47:08 patroni_prueba1 patroni[2437]: performing post-bootstrap initialization ... ok
Mar  1 21:47:10 patroni_prueba1 patroni[2437]: syncing data to disk ... ok
Mar  1 21:47:10 patroni_prueba1 patroni[2437]: WARNING: enabling "trust" authentication for local connections
Mar  1 21:47:10 patroni_prueba1 patroni[2437]: You can change this by editing pg_hba.conf or using the option -A, or
Mar  1 21:47:10 patroni_prueba1 patroni[2437]: --auth-local and --auth-host, the next time you run initdb.
Mar  1 21:47:10 patroni_prueba1 patroni[2437]: Success. You can now start the database server using:
Mar  1 21:47:10 patroni_prueba1 patroni[2437]:     /usr/lib/postgresql/10/bin/pg_ctl -D /data/patroni -l logfile start
Mar  1 21:47:10 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:10,202 INFO: postmaster pid=2484
Mar  1 21:47:10 patroni_prueba1 patroni[2437]: 192.168.18.150:5432 - no response
Mar  1 21:47:10 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:10.242 UTC [2484] LOG:  listening on IPv4 address "192.168.18.150", port 5432
Mar  1 21:47:10 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:10.248 UTC [2484] LOG:  listening on Unix socket "./.s.PGSQL.5432"
Mar  1 21:47:10 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:10.288 UTC [2490] LOG:  database system was shut down at 2019-03-01 21:47:08 UTC
Mar  1 21:47:10 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:10.323 UTC [2484] LOG:  database system is ready to accept connections
Mar  1 21:47:11 patroni_prueba1 patroni[2437]: 192.168.18.150:5432 - accepting connections
Mar  1 21:47:11 patroni_prueba1 patroni[2437]: 192.168.18.150:5432 - accepting connections
Mar  1 21:47:11 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:11,282 INFO: establishing a new patroni connection to the postgres cluster
Mar  1 21:47:11 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:11,292 INFO: running post_bootstrap
Mar  1 21:47:11 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:11,305 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
Mar  1 21:47:11 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:11,371 INFO: initialized a new cluster
Mar  1 21:47:21 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:21,305 INFO: Lock owner: patronipsql1; I am patronipsql1
Mar  1 21:47:21 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:21,381 INFO: Lock owner: patronipsql1; I am patronipsql1
Mar  1 21:47:21 patroni_prueba1 patroni[2437]: 2019-03-01 21:47:21,411 INFO: no action.  i am the leader with the lock
__________________________________________________________________
Just the WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"

Whats next with this WARNING?

i'll appreciate your help, i'll wait for a reply, thank you so much again.

**Comment by CyberDem0n** [comment]
Patroni is automatically trying to use [watchdog](https://github.com/zalando/patroni/blob/master/docs/watchdog.rst) on Linux. In your case it is not available and therefore it shows a warning.

**Comment by omm1979** [comment]
Thanks a lot, regards, i'll just continue with project.
