### ISSUE TITLE
patronictl with etcd authentication

### ISSUE THREAD

**Issue by mzwettler2** [zalando/patroni#991]
I configured etcd with authentication.

How do I have to store username + password in the patronictl.yaml file?

I tried "'etcd://username:password@remotehost:2379" but this didn't work.

**Comment by CyberDem0n** [comment]
For a very long time patronictl could use the standard Patroni config file.

**Comment by mzwettler2** [comment]
It doesn't seem to work anymore as I configured username + password for etcd in patroni.yml file. 
This worked for patroni but not for patronictl.
Any idea how to get patronictl using username + password for etcd?

**Comment by CyberDem0n** [comment]
In order to work with DCS (etcd,consul,zookeeper), patronictl is using absolutely the same code as patroni itself.

`patronictl -c patroni.yaml` should just work.

**Comment by mzwettler2** [comment]
Yes, it worked. Thanks.
Curious. What is patrionictl.yaml for?

**Comment by CyberDem0n** [comment]
Just for compatibility with very old versions
