### ISSUE TITLE
Setting logging_collector to false breaks archive_command stdout file descriptor.

### ISSUE THREAD

**Issue by kupson** [zalando/patroni#992]
To deliver Postgresql logs into docker/Kubernetes I'm setting `logging_collector` to `false` and `log_destination` to `stderr`.

That causes the default `wal-g` `archive_command` to be killed with SIGPIPE as it's standard output fd (pipe) is closed.

The receiving side is closed after being used to pass the pid of the postmaster in:
https://github.com/zalando/patroni/blob/e670122c805176a3689a7ddc8849a557038bde58/patroni/postmaster.py#L162-L164

Maybe it would be better to use [pass_fds](https://docs.python.org/3.6/library/subprocess.html#popen-constructor) to communicate pid to parent and leave stdout alone?

**Comment by CyberDem0n** [comment]
Hi @kupson,

unfortunately `pass_fds` is not available on python 2.7, but I think it should be possible to get the same results with https://docs.python.org/2.7/library/multiprocessing.html

**Comment by CyberDem0n** [comment]
Despite 2.7 being EOL in 2020 there are still a lot of systems where only 2.7 available :(

**Comment by redbaron** [comment]
whats your view to do bug fixes and/or features to be introduced only in python3.x version of patroni when keeping python 2.7 compatibility is too hacky? for instance this fix can call subprocess with a set of flags supported by the given runtime and therefore bug would be fixed under 3.x python.


using multiprocess for double forking just to pass file descriptor is super ugly

**Comment by CyberDem0n** [comment]
Double forking itself is already ugly enough :)
Actually I am also not sure that `pass_fds` will work on Windows.

So far it wasn't that hard to keep Patroni 2.7/3.X compatible, everything is more or less covered with `six`.

**Comment by Jan-M** [comment]
Interesting discussion for the Python 2.7 vs Python 3.x. At some point we may need to favor 3.x over additional work for 2.7.
