### ISSUE TITLE
Access problem to postgres/admin users to manage databases in patroni-postgresql 10, without a non dockerized/vagranted (just VM) infrastructure

### ISSUE THREAD

**Issue by omm1979** [zalando/patroni#993]
Hi, one of my problem is: that I want to manage postgres users password or another admin users to apply or do the admin role in master/slave patroni-postgresql 10 (i.e. create tables, insert, update, etc). My example's infraestructure is: 3 nodes (1 master, 2 slaves) with patroni 1.5.5 + postgresql 10 and haproxy version 1.8.8-1ubuntu0.4, released 2019/01/24, etcd version 3.2.17 servers (all servers in infrastructure is configurated in separated in ubuntu server 18.04 VMs), another question is that I've read (https://github.com/zalando/patroni/issues/148) that postgres-operator manages clusters users passwords configurations but does it works with a non like Spilo dockerized/vagranted (just VM)? or I'm misunderstanding it. 

Infrastructure's information:
192.168.18.150 Master - Postgres-Patroni - patroni_prueba1
192.168.18.151 Slave - Postgres-Patroni - patroni_prueba2
192.168.18.152 Slave - Postgres-Patroni - patroni_prueba3
192.168.18.153 etcd - etcd
192.168.18.154 HAproxy - haproxy
_______________________________________________________________________________
My patroni.yml in master (is the same in the 3 nodes with their respective changes in IP, ports and ) config is:
_______________________________________________________________________________
scope: postgres
namespace: /db/
name: patronipsql1

restapi:
 listen: 192.168.18.150:8008
 connect_address: 192.168.18.150:8008

etcd: 
 host: 192.168.18.153:2379

bootstrap:
 dcs:
  ttl: 30
  loop_wait: 10
  retry_timeout: 10
  # 1 Mb en bytes
  maximum_lag_on_failover: 1048576
  synchronous_commit: 'on'
  synchronous_standby_names: '*'
  #synchronous_mode: false
  postgresql:
   use_pg_rewind: true
   use_slots: true
   parameters:
    wal_level: replica
    hot_standby: "on"
    wal_keep_segments: 64
    max_wal_senders: 20
    max_wal_size: 1Gb
    min_wal_size: 128Mb
    max_replication_slots: 20
    checkpoint_timeout: 30
    shared_buffers: '128MB'
    work_mem: '8MB'
    effective_cache_size: '512MB'
    mainenance_work_mem: '64MB'
    loging_collector: 'on'
    log_truncate_on_rotation: 'on'
    log_filename: 'postgresql-%a.log'
    log_rotation_age: '1440'
    log_line_prefix: '%m - %l - %p - %h - %u@%d - &x'
    log_directory: 'pg_log'
    log_min_messages: 'WARNING'
    log_autovacuum_min_duration: '60s'
    log_min_error_statement: 'NOTICE'
    log_min_duration_statement: '30s'
    log_checkpoints: 'on'
    log_statements: 'ddl'
    log_lock_waits: 'on'
    log_tepm_files: '0'
    log_timezone: 'America/Mexico_city'
    log_connections: 'on'
    log_disconnections: 'on'
    log_duration: 'on'
    client_min_messages: 'WARNING'
    active_mode: 'on'
    archive_command: '/bin/true'
    wal_log_hints: 'on'
    #recover_conf:
    #restore_command: cp ../wal_archive/%f %p

 initdb:
  - encoding: UTF8
  - data-checksums

 pg_hba:
  - host replication replicador 127.0.0.1/32 md5
  - host replication replicador 192.168.18.150/0 md5
  - host replication replicador 192.168.18.151/0 md5
  - host replication replicador 192.168.18.152/0 md5
  - host postgres postgres 127.0.0.1/32 trust          <-- trying to connect localhost postgres user
  - host all all 0.0.0.0/0 md5
  #hostssl all all 0.0.0.0/0 md5
 
 users:
  admin:
   password: pass1
   options:
    - createrole
    - createdb 
  replicador:
   password: pass1
   options:
    - replication

postgresql:
 listen: 192.168.18.150:5432
 connect_address: 192.168.18.150:5432
 bin_dir: /usr/lib/postgresql/10/bin
 data_dir: /data/patroni
#config_dir: /data/patroni
 pgpass: /tmp/pgpass 
 authentication:
  replication:
   username: replicador
   password: pass1
  superuser:
   username: admin        <--- i want to use this postgres's user password to create tables/query/insert/ etc...
   password: pass2
   username: postgres   <--- or i want to create a postgres's user password to create tables/query/insert/ etc...
   password: pass3        <--- see errors /var/log/syslog + /var/log/postgresql/postgresql-10-main-log
 parameters:
   unix_socket_directories: '.'
 basebackup:
   - verbose
   - max-rate: 100M

tags:
 nofailover: false
 noloadbalance: false
 clonefrom: false
 nosync: false
_______________________________________________________________________________
postgresql-10-main.log output

2019-03-05 17:31:47.415 UTC [3431] admin@admin FATAL:  password authentication failed for user "admin"
2019-03-05 17:31:47.415 UTC [3431] admin@admin DETAIL:  Role "admin" does not exist.
	Connection matched pg_hba.conf line 94: "host    all             all             ::1/128                 md5"
2019-03-05 17:31:50.339 UTC [3433] admin@admin FATAL:  password authentication failed for user "admin"
2019-03-05 17:31:50.339 UTC [3433] admin@admin DETAIL:  Role "admin" does not exist.
	Connection matched pg_hba.conf line 94: "host    all             all             ::1/128                 md5"
2019-03-05 17:31:50.341 UTC [3434] admin@admin FATAL:  password authentication failed for user "admin"
2019-03-05 17:31:50.341 UTC [3434] admin@admin DETAIL:  Role "admin" does not exist.
	Connection matched pg_hba.conf line 94: "host    all             all             ::1/128                 md5"
2019-03-05 17:41:25.851 UTC [3720] postgres@postgres FATAL:  password authentication failed for user "postgres"
2019-03-05 17:41:25.851 UTC [3720] postgres@postgres DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 94: "host    all             all             ::1/128                 md5"
2019-03-05 17:41:28.517 UTC [3722] postgres@postgres FATAL:  password authentication failed for user "postgres"
2019-03-05 17:41:28.517 UTC [3722] postgres@postgres DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 94: "host    all             all             ::1/128                 md5"
2019-03-05 17:41:28.519 UTC [3723] postgres@postgres FATAL:  password authentication failed for user "postgres"
2019-03-05 17:41:28.519 UTC [3723] postgres@postgres DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 94: "host    all             all             ::1/128                 md5"
2019-03-05 17:31:50.339 UTC [3433] admin@admin DETAIL:  Role "admin" does not exist.
	Connection matched pg_hba.conf line 94: "host    all             all             ::1/128                 md5"
2019-03-05 17:31:50.341 UTC [3434] admin@admin FATAL:  password authentication failed for user "admin"
2019-03-05 17:31:50.341 UTC [3434] admin@admin DETAIL:  Role "admin" does not exist.
	Connection matched pg_hba.conf line 94: "host    all             all             ::1/128                 md5"
2019-03-05 17:41:25.851 UTC [3720] postgres@postgres FATAL:  password authentication failed for user "postgres"
2019-03-05 17:41:25.851 UTC [3720] postgres@postgres DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 94: "host    all             all             ::1/128                 md5"
2019-03-05 17:41:28.517 UTC [3722] postgres@postgres FATAL:  password authentication failed for user "postgres"
2019-03-05 17:41:28.517 UTC [3722] postgres@postgres DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 94: "host    all             all             ::1/128                 md5"
2019-03-05 17:41:28.519 UTC [3723] postgres@postgres FATAL:  password authentication failed for user "postgres"
2019-03-05 17:41:28.519 UTC [3723] postgres@postgres DETAIL:  User "postgres" has no password assigned.
	Connection matched pg_hba.conf line 94: "host    all             all             ::1/128                 md5"
_______________________________________________________________________________
syslog output

Mar  5 17:53:39 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:39.563 UTC [14958] DETAIL:  Role "postgres" does not exist.
Mar  5 17:53:39 patroni_prueba2 patroni[14892]: #011Connection matched pg_hba.conf line 99: "host all all 0.0.0.0/0 md5"
Mar  5 17:53:39 patroni_prueba2 patroni[14892]: 192.168.18.151:5432 - accepting connections
Mar  5 17:53:39 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:39.585 UTC [14960] FATAL:  password authentication failed for user "postgres"
Mar  5 17:53:39 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:39.585 UTC [14960] DETAIL:  Role "postgres" does not exist.
Mar  5 17:53:39 patroni_prueba2 patroni[14892]: #011Connection matched pg_hba.conf line 99: "host all all 0.0.0.0/0 md5"
Mar  5 17:53:39 patroni_prueba2 patroni[14892]: 192.168.18.151:5432 - accepting connections
Mar  5 17:53:39 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:39,598 INFO: Lock owner: patronipsql1; I am patronipsql2
Mar  5 17:53:39 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:39,598 INFO: does not have lock
Mar  5 17:53:39 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:39,598 INFO: establishing a new patroni connection to the postgres cluster
Mar  5 17:53:39 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:39.600 UTC [14961] FATAL:  password authentication failed for user "postgres"
Mar  5 17:53:39 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:39.600 UTC [14961] DETAIL:  Role "postgres" does not exist.
Mar  5 17:53:39 patroni_prueba2 patroni[14892]: #011Connection matched pg_hba.conf line 99: "host all all 0.0.0.0/0 md5"
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:40,397 INFO: establishing a new patroni connection to the postgres cluster
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:40.402 UTC [14962] FATAL:  password authentication failed for user "postgres"
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:40.402 UTC [14962] DETAIL:  Role "postgres" does not exist.
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: #011Connection matched pg_hba.conf line 99: "host all all 0.0.0.0/0 md5"
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:40.425 UTC [14964] FATAL:  password authentication failed for user "postgres"
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:40.425 UTC [14964] DETAIL:  Role "postgres" does not exist.
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: #011Connection matched pg_hba.conf line 99: "host all all 0.0.0.0/0 md5"
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: 192.168.18.151:5432 - accepting connections
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:40,427 INFO: establishing a new patroni connection to the postgres cluster
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:40.429 UTC [14965] FATAL:  password authentication failed for user "postgres"
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:40.429 UTC [14965] DETAIL:  Role "postgres" does not exist.
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: #011Connection matched pg_hba.conf line 99: "host all all 0.0.0.0/0 md5"
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:40,429 ERROR: Exception when changing replication slots
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: Traceback (most recent call last):
Mar  5 17:53:40 patroni_prueba2 patroni[14892]:   File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 1588, in sync_replication_slots
Mar  5 17:53:40 patroni_prueba2 patroni[14892]:     self.load_replication_slots()
Mar  5 17:53:40 patroni_prueba2 patroni[14892]:   File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 1557, in load_replication_slots
Mar  5 17:53:40 patroni_prueba2 patroni[14892]:     cursor = self._query('SELECT slot_name, slot_type, plugin, database FROM pg_catalog.pg_replication_slots')
Mar  5 17:53:40 patroni_prueba2 patroni[14892]:   File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 496, in _query
Mar  5 17:53:40 patroni_prueba2 patroni[14892]:     raise PostgresConnectionException('connection problems')
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: PostgresConnectionException: 'connection problems'
Mar  5 17:53:40 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:40,454 INFO: Error communicating with PostgreSQL. Will try again later
Mar  5 17:53:41 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:41.811 UTC [14969] FATAL:  password authentication failed for user "postgres"
Mar  5 17:53:41 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:41.811 UTC [14969] DETAIL:  Role "postgres" does not exist.
Mar  5 17:53:41 patroni_prueba2 patroni[14892]: #011Connection matched pg_hba.conf line 99: "host all all 0.0.0.0/0 md5"
Mar  5 17:53:41 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:41,811 ERROR: get_postgresql_status
Mar  5 17:53:41 patroni_prueba2 patroni[14892]: Traceback (most recent call last):
Mar  5 17:53:41 patroni_prueba2 patroni[14892]:   File "/usr/local/lib/python2.7/dist-packages/patroni/api.py", line 432, in get_postgresql_status
Mar  5 17:53:41 patroni_prueba2 patroni[14892]:     self.server.patroni.postgresql.lsn_name), retry=retry)[0]
Mar  5 17:53:41 patroni_prueba2 patroni[14892]:   File "/usr/local/lib/python2.7/dist-packages/patroni/api.py", line 404, in query
Mar  5 17:53:41 patroni_prueba2 patroni[14892]:     return self.server.query(sql, *params)
Mar  5 17:53:41 patroni_prueba2 patroni[14892]:   File "/usr/local/lib/python2.7/dist-packages/patroni/api.py", line 488, in query
Mar  5 17:53:41 patroni_prueba2 patroni[14892]:     raise PostgresConnectionException('connection problems')
Mar  5 17:53:41 patroni_prueba2 patroni[14892]: PostgresConnectionException: 'connection problems'
Mar  5 17:53:44 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:44.883 UTC [14971] FATAL:  password authentication failed for user "postgres"
Mar  5 17:53:44 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:44.883 UTC [14971] DETAIL:  Role "postgres" does not exist.
Mar  5 17:53:44 patroni_prueba2 patroni[14892]: #011Connection matched pg_hba.conf line 99: "host all all 0.0.0.0/0 md5"
Mar  5 17:53:44 patroni_prueba2 patroni[14892]: 2019-03-05 17:53:44,886 ERROR: get_postgresql_status
Mar  5 17:53:44 patroni_prueba2 patroni[14892]: Traceback (most recent call last):
Mar  5 17:53:44 patroni_prueba2 patroni[14892]:   File "/usr/local/lib/python2.7/dist-packages/patroni/api.py", line 432, in get_postgresql_status
Mar  5 17:53:44 patroni_prueba2 patroni[14892]:     self.server.patroni.postgresql.lsn_name), retry=retry)[0]
Mar  5 17:53:44 patroni_prueba2 patroni[14892]:   File "/usr/local/lib/python2.7/dist-packages/patroni/api.py", line 404, in query
Mar  5 17:53:44 patroni_prueba2 patroni[14892]:     return self.server.query(sql, *params)
Mar  5 17:53:44 patroni_prueba2 patroni[14892]:   File "/usr/local/lib/python2.7/dist-packages/patroni/api.py", line 488, in query
Mar  5 17:53:44 patroni_prueba2 patroni[14892]:     raise PostgresConnectionException('connection problems')
Mar  5 17:53:44 patroni_prueba2 patroni[14892]: PostgresConnectionException: 'connection problems'
Mar  5 17:53:45 patroni_prueba2 systemd[1]: Stopping PostgreSQL Cluster 10-main...
_______________________________________________________________________________
i want to enter in linux command line like:
su - postgres
su: Authentication failure

and
psql -U postgres
psql: FATAL: peer authentication failed for user "postgres"

and
psql template1 -U postgres -h localhost
psql: FATAL: password authentication failed for user "postgres"

the same thing with admin user:
psql -U admin -h localhost
psql: FATAL:  password authentication failed for user "admin"

_______________________________________________________________________________
I know that is a newbie/rookie question, but what i want is to create a table or query/insert/update it with user "postgres" and password, or the admin user or any user registered in patroni.yml file, or what would be the recommendation to do that in the patroni.yml, or I have to create linux postgres user in the 3 nodes (master +, 2 slaves)?, because I can't create nothing, thanks for your help, I'll  wait for reply, regards.

**Comment by CyberDem0n** [comment]
The `bootstrap` section works exactly one time, if you are changing it after the cluster was initialized it won take any effect.

Also Patroni doesn't enforce password changes, e.g. if you changed passwords in the config file, Patroni will not apply these changes to postgres.

User/password management is out of scope here. The only exception only applies to the moment when the new cluster is being initialized. After that it is your responsibility.

Do you have some experience with postgres at all?

**Comment by omm1979** [comment]
Ok, I understand it's one time configuration in patroni, so I need to change manually the postgresql users password in the 3 nodes (Master and Slaves), my experience with postgresql it's a quite bit poor, i know the basis but this would be the first example, thanks for your reply, and i'll do my best, regards.
