### ISSUE TITLE
Issue when using the Patroni with Postgres-11

### ISSUE THREAD

**Issue by doruksonmez** [zalando/patroni#996]
Hi all,

I am currently trying to build a HA Postgresql Cluster using Postgres 11.2 and Patroni 1.5.5 on Ubuntu 16.04. The issue I am having is that when I try to create a cluster using Postgres 9.5, there is no error and I can see that the secondary one takes the mastership when the actual master is down. However, whenever I try to build the same cluster using Postgres 11, `sudo systemctl status patroni.service` command throws the following output:

● patroni.service - Runners to orchestrate a high-availability PostgreSQL
   Loaded: loaded (/etc/systemd/system/patroni.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-03-06 14:33:22 UTC; 13min ago
 Main PID: 26757 (patroni)
    Tasks: 5
   Memory: 84.3M
      CPU: 1min 16.470s
   CGroup: /system.slice/patroni.service
           └─26757 /usr/bin/python3 /usr/local/bin/patroni /etc/patroni.yml

Mar 06 14:47:01 stolon patroni[26757]: 2019-03-06 14:47:01,961 WARNING: Postgresql is not running.
Mar 06 14:47:01 stolon patroni[26757]: 2019-03-06 14:47:01,961 INFO: Lock owner: postgresql1; I am postgresql2
Mar 06 14:47:01 stolon patroni[26757]: 2019-03-06 14:47:01,968 INFO: Lock owner: postgresql1; I am postgresql2
Mar 06 14:47:01 stolon patroni[26757]: 2019-03-06 14:47:01,985 INFO: Local timeline=None lsn=None
Mar 06 14:47:01 stolon patroni[26757]: 2019-03-06 14:47:01,985 INFO: Lock owner: postgresql1; I am postgresql2
Mar 06 14:47:01 stolon patroni[26757]: 2019-03-06 14:47:01,989 INFO: starting as a secondary
Mar 06 14:47:02 stolon patroni[26757]: 2019-03-06 14:47:02,044 INFO: postmaster pid=6797
Mar 06 14:47:02 stolon patroni[26757]: 2019-03-06 14:47:02.046 UTC [6797] FATAL:  database files are incompatible with server
Mar 06 14:47:02 stolon patroni[26757]: 2019-03-06 14:47:02.046 UTC [6797] DETAIL:  The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 11.2 (Ubuntu 11.2-1.pgdg16.04+1).
Mar 06 14:47:02 stolon patroni[26757]: 10.2.0.14:5432 - no response

I can't understand what does it mean **WARNING: Postgresql is not running.**? When I run `sudo systemctl status postgresql` it gives:

● postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
   Active: active (exited) since Wed 2019-03-06 14:33:32 UTC; 16min ago
  Process: 26900 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 26900 (code=exited, status=0/SUCCESS)

Mar 06 14:33:32 stolon systemd[1]: Starting PostgreSQL RDBMS...
Mar 06 14:33:32 stolon systemd[1]: Started PostgreSQL RDBMS.

Also the other problem is I am installing Postgres 11 from scratch and I don't think it is possible for me to install something related to Postgres 9.5 but as you can see that it also says **DETAIL:  The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 11.2 (Ubuntu 11.2-1.pgdg16.04+1).**. What does that even mean?

Can somebody please help me about the situation?

**Comment by CyberDem0n** [comment]
Hi,

```
Mar 06 14:47:02 stolon patroni[26757]: 2019-03-06 14:47:02.046 UTC [6797] FATAL: database files are incompatible with server
Mar 06 14:47:02 stolon patroni[26757]: 2019-03-06 14:47:02.046 UTC [6797] DETAIL: The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 11.2 (Ubuntu 11.2-1.pgdg16.04+1).
```

the logs are clearly telling that you are trying to start 9.5 cluster with postges 11 binaries. It's not gonna work.
You have to upgrade the cluster by either:
1. reinitializing it from scratch + doing dump/restore
2. running [pg_upgrade](https://www.postgresql.org/docs/current/pgupgrade.html)

In both cases you need to have 9.5 binaries.

**Comment by doruksonmez** [comment]
> Hi,
> 
> ```
> Mar 06 14:47:02 stolon patroni[26757]: 2019-03-06 14:47:02.046 UTC [6797] FATAL: database files are incompatible with server
> Mar 06 14:47:02 stolon patroni[26757]: 2019-03-06 14:47:02.046 UTC [6797] DETAIL: The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 11.2 (Ubuntu 11.2-1.pgdg16.04+1).
> ```
> the logs are clearly telling that you are trying to start 9.5 cluster with postges 11 binaries. It's not gonna work.
> You have to upgrade the cluster by either:
> 
> 1. reinitializing it from scratch + doing dump/restore
> 2. running [pg_upgrade](https://www.postgresql.org/docs/current/pgupgrade.html)
> 
> In both cases you need to have 9.5 binaries.

First of all, thanks for the answer. But the thing confuses me is that I have never installed 9.5 on those machines. Where is that 9.5 coming from?

Should I first install 9.5 from scratch and then upgrade it to 11 using pg_upgrade? Is this what you mean by saying option 2? Sorry for the dumb questions but I am trying to understand.

**Comment by CyberDem0n** [comment]
> Where is that 9.5 coming from?

It is coming from `PG_VERSION` file located in the `postgresql.data_dir`.
Database files are there, somebody created them, and you have to figure out who or what did that.

> Should I first install 9.5 from scratch and then upgrade it to 11 using pg_upgrade? 

It is up to you. If you don't care about existing data you can just drop the content of the data directory.

**Comment by kmoppel** [comment]
@CyberDem0n Hey Alex, a question about running **pg_upgrade** for a cluster managed by Patroni - are there some automation plans or one need to still update the cluster initialization key manually (as initdb will create a new "system identifier") in DCS?

**Comment by CyberDem0n** [comment]
@kmoppel 

It is not really clear how it is should work and IMHO pg_upgrade should not be really in the Patroni scope.
